(in-package "ACL2")
(defttag :fn-native-host)
(progn! (set-raw-mode t)
        (load "host/native/io.lisp")
        (load "host/native/immutable-publish.lisp")
        (load "host/native/checkpoint.lisp")
        (load "host/native/workflow.lisp")
        (load "host/native/tcpcl.lisp")
        (load "host/native/bp.lisp")
        (load "host/native/bp-service.lisp")
        (load "host/native/feed-filename.lisp")
        (load "host/native/owner.lisp")
        (load "host/native/crypto.lisp")
        (load "host/native/anchor.lisp")
        (format t "FN_W21_RAW_LOAD_OK~%"))
:q
