[store]
path = "/home/hbox/fn-deploy/native-1a9dd747-83cec9b/a/init/store"
[listener]
host = "127.0.0.1"
port = 11295
[control]
path = "/home/hbox/fn-deploy/native-1a9dd747-83cec9b/a/init/control.sock"
