; Actual account preparation owns a genuine captured predecessor prefix.
; No E-sequence/count conversion and no supplied source/token/demand.
(in-package "ACL2")
(include-book "history-source-capture")
(defun fn-owner-account-replay-source (state)
 (declare (xargs :stobjs state :guard t))
 (if (boundp-global 'fn-owner-account-replay-source state)
     (f-get-global 'fn-owner-account-replay-source state) nil))
(defun fn-owner-account-replay-currentp (fn-history-backing state)
 (declare (xargs :stobjs (fn-history-backing state) :verify-guards nil :guard t))
 (let* ((owned (fn-owner-account-replay-source state))
        (token (fn-hhc-at 1 owned))
        (slot (fn-owner-history-capture-slot state)))
  (and owned
       (eq (fn-owner-history-recheck token state) :history-source-current)
       (fn-hep-capture-livep (fn-hhc-at 3 slot) token fn-history-backing))))
(defun fn-owner-account-replay-begin (fn-history-backing fn-page-read-pool state)
 (declare (xargs :stobjs (fn-history-backing fn-page-read-pool state)
                 :verify-guards nil :guard t))
 (if (fn-owner-account-replay-source state)
     (mv :account-replay-held nil fn-history-backing fn-page-read-pool state)
  (mv-let (word descriptor fn-history-backing fn-page-read-pool state)
   (fn-owner-history-capture :account-adoption fn-history-backing fn-page-read-pool state)
   (if (not (eq word :captured))
       (mv word nil fn-history-backing fn-page-read-pool state)
    ; Descriptor is actual captured token/epoch/F/sourceID/rootID. F is the
    ; predecessor dense count BEFORE the begin E is offered or appended.
    (let ((state (f-put-global 'fn-owner-account-replay-source descriptor state)))
     (mv :account-replay-retained (fn-hhc-at 3 descriptor)
         fn-history-backing fn-page-read-pool state))))))
(defun fn-owner-account-replay-return (fn-history-backing fn-page-read-pool state)
 (declare (xargs :stobjs (fn-history-backing fn-page-read-pool state)
                 :verify-guards nil :guard t))
 (let ((owned (fn-owner-account-replay-source state)))
  (if (not owned)
      (mv :account-replay-unavailable fn-history-backing fn-page-read-pool state)
   ; Only the actual discard or durable C terminal producer quiesces the
   ; history slot after joining aliases. This hook never asserts that join.
   (mv-let (word fn-history-backing fn-page-read-pool state)
    (fn-owner-history-release (fn-hhc-at 1 owned)
                             fn-history-backing fn-page-read-pool state)
    (if (not (eq word :released))
        (mv word fn-history-backing fn-page-read-pool state)
     (let ((state (f-put-global 'fn-owner-account-replay-source nil state)))
      (mv :account-replay-returned fn-history-backing fn-page-read-pool state)))))))
