; Direct readonly authority over the concrete SAMEpool allocating-turn receipt.
(in-package "ACL2")
(include-book "allocation-turn-slots")
(defun fn-ats-role-bodyp (slot nonce role fn-allocation-turn-slots fn-page-read-pool)
 (declare (xargs :stobjs (fn-allocation-turn-slots fn-page-read-pool) :guard t))
 (and (fn-ats-slotp slot fn-allocation-turn-slots)
      (fn-ats-matchingp slot nonce fn-allocation-turn-slots fn-page-read-pool)
      (equal (fn-ats-kindsi slot fn-allocation-turn-slots) role)
      (eql (fn-ats-phasesi slot fn-allocation-turn-slots) 3)
      (member-eq (fn-prp-alloc-mode fn-page-read-pool) '(:active :draining))
      (posp (fn-prp-alloc-active-turns fn-page-read-pool))))
(defthm fn-ats-role-bodyp-is-exact-current-body-receipt
 (equal (fn-ats-role-bodyp slot nonce role slots pool)
        (and (fn-ats-slotp slot slots) (fn-ats-associatedp slots pool)
             (natp nonce) (equal nonce (fn-ats-noncesi slot slots))
             (equal (fn-ats-kindsi slot slots) role)
             (eql (fn-ats-phasesi slot slots) 3)
             (member-eq (fn-prp-alloc-mode pool) '(:active :draining))
             (posp (fn-prp-alloc-active-turns pool))))
 :hints (("Goal" :in-theory (enable fn-ats-role-bodyp fn-ats-matchingp fn-ats-owned-phasep)))
 :rule-classes nil)
(defthm fn-ats-role-bodyp-uncertainty-closes-authority
 (let ((fault (fn-ats-uncertain-internal slots pool)))
  (not (fn-ats-role-bodyp slot nonce role (mv-nth 1 fault) (mv-nth 2 fault))))
 :hints (("Goal" :in-theory (enable fn-ats-role-bodyp fn-ats-uncertain-internal fn-aec-pool-uncertain-internal)))
 :rule-classes nil)
(defthm fn-ats-role-bodyp-left-consumes-authority
 (implies (equal (mv-nth 0 (fn-ats-finish-owned slot nonce slots pool)) :left)
  (let ((left (fn-ats-finish-owned slot nonce slots pool)))
   (not (fn-ats-role-bodyp slot nonce role (mv-nth 1 left) (mv-nth 2 left)))))
 :hints (("Goal" :in-theory (enable fn-ats-role-bodyp fn-ats-finish-owned)))
 :rule-classes nil)
