; Typed held auxiliary grammar from the actual received/family, dispatch,
; delivery, forwarding/deferral and deletion producers. Not activated yet:
; whole-producer preservation is required before tightening recovery.
(in-package "ACL2")
(include-book "bp-handoff-recovery-shape")
(set-verify-guards-eagerness 2)

(defun fn-bphg-consumed-rowp (row)
 (declare (xargs :guard t))
 (and (fn-bphs-exact-listp row 3)
      (or (null (nth 0 row)) (fn-bpn-machine-textp (nth 0 row)))
      (fn-bphs-bundle-idp (nth 1 row)) (natp (nth 2 row))))
(defun fn-bphg-consumed-rowsp (rows)
 (declare (xargs :guard t))
 (if (consp rows)
  (and (fn-bphg-consumed-rowp (car rows)) (fn-bphg-consumed-rowsp (cdr rows)))
  (null rows)))
(defun fn-bphg-lineagep (lineage)
 (declare (xargs :guard t))
 (or (null lineage)
     (and (fn-bphs-exact-listp lineage 2) (equal (nth 0 lineage) :reassembled)
          (fn-bphg-consumed-rowsp (nth 1 lineage)))))
(defun fn-bphg-anchorp (anchor)
 (declare (xargs :guard t))
 (or (null anchor) (equal anchor '(:wall))
     (and (fn-bphs-exact-listp anchor 3) (equal (nth 0 anchor) :observed-age)
          (natp (nth 1 anchor)) (natp (nth 2 anchor)))))
(defun fn-bphg-dispatchp (dispatch)
 (declare (xargs :guard t))
 (or (null dispatch) (equal dispatch '(:dispatched :forward))
     (and (fn-bphs-exact-listp dispatch 3) (equal (nth 0 dispatch) :delivered)
          (member-eq (nth 1 dispatch)
           '(:request-accepted :request-duplicate :request-returned :request-refused
             :receipt-accepted :receipt-duplicate :receipt-refused))
          (fn-cbor-octet-listp (nth 2 dispatch)))))
(defun fn-bphg-attemptp (attempt)
 (declare (xargs :guard t))
 (or (null attempt)
     (and (fn-bphs-exact-listp attempt 2) (equal (nth 0 attempt) :busy)
          (natp (nth 1 attempt)))
     (and (fn-bphs-exact-listp attempt 6)
          (member-eq (nth 0 attempt) '(:forwarding :uncertain))
          (natp (nth 1 attempt)) (natp (nth 2 attempt))
          (fn-bpp-eidp (nth 3 attempt))
          (consp (nth 4 attempt)) (natp (car (nth 4 attempt)))
          (natp (cdr (nth 4 attempt))) (natp (nth 5 attempt)))))
(defun fn-bphg-deletionp (deletion)
 (declare (xargs :guard t))
 (or (null deletion)
     (and (fn-bphs-exact-listp deletion 7) (equal (nth 0 deletion) :bpnf-deleted)
          (natp (nth 1 deletion)) (natp (nth 2 deletion)) (natp (nth 3 deletion))
          (fn-cbor-octet-listp (nth 4 deletion))
          (equal (nth 5 deletion) :lifetime-expired)
          (fn-cbor-octet-listp (nth 6 deletion)))))
(defun fn-bphg-held-auxp (held)
 (declare (xargs :guard t))
 (and (fn-bphs-exact-listp held 16) (equal (nth 0 held) :bpnf-held)
      (null (nth 5 held))
      (fn-bphg-lineagep (nth 6 held))
      (fn-bphg-anchorp (nth 9 held))
      (fn-bphg-dispatchp (nth 10 held))
      (or (null (nth 11 held)) (fn-bpp-eidp (nth 11 held)))
      (member-equal (nth 12 held) '((:dispatch-pending) (:forward-pending) (:dispatch-done)))
      (fn-bphg-attemptp (nth 13 held))
      (fn-bphg-deletionp (nth 14 held))))
(defun fn-bphg-held-auxsp (held)
 (declare (xargs :guard t))
 (if (consp held)
  (and (fn-bphg-held-auxp (car held)) (fn-bphg-held-auxsp (cdr held)))
  (null held)))
