; Listener generation plus admitted retained sessions; installation stays the
; existing single-writer machine. Its old scalar session consumer is separate.
(in-package "ACL2")
(include-book "bp-node-listener-control")
(include-book "resource-bp-session")
(defun fn-bpsg-livep (row fn-resource-ledger)
 (declare (xargs :stobjs fn-resource-ledger :guard t :verify-guards nil))
 (and (fn-rl-wfp fn-resource-ledger) (true-listp row) (equal (len row) 6)
      (equal (first row) :bp-session-grant) (natp (second row)) (natp (third row))
      (< (second row) (fn-rl-count fn-resource-ledger))
      (equal (fn-rl-phasesi (second row) fn-resource-ledger) 1)
      (equal (fn-rl-gensi (second row) fn-resource-ledger) (third row))))
(verify-guards fn-bpsg-livep :hints (("Goal" :in-theory (enable fn-rl-wfp))))
(defun fn-bpsched-accept-plan (st index row fn-resource-ledger)
 (declare (xargs :stobjs fn-resource-ledger :guard t))
 (and (fn-bpsg-livep row fn-resource-ledger)
      (equal (fourth row) :incoming)
      (not (fifth row)) (not (sixth row))
      (equal (fn-bplc-phase st) :stable)
      (natp index) (< index (len (fn-bplc-ports st)))
      (list :accept (fn-bplc-generation st) (fn-ncfg-nth index (fn-bplc-ports st)))))
(defun fn-bpsched-remove (key xs)
 (declare (xargs :guard t))
 (if (consp xs)
  (if (equal key (fn-ag-car (car xs))) (fn-bpsched-remove key (cdr xs))
   (cons (car xs) (fn-bpsched-remove key (cdr xs)))) nil))
(defun fn-bpsched-session-view (rows)
 (declare (xargs :guard t))
 (and (consp rows)
      (list :accept (fn-ncfg-nth 1 (car rows)) (fn-ncfg-nth 2 (car rows)) rows)))
(defun fn-bpsched-listener-step (st event)
 (declare (xargs :guard t))
 (let ((rows (fn-ncfg-nth 3 (fn-bplc-session st))))
  (case (fn-ag-car event)
   (:retained-accepted
    (let ((plan (fn-ncfg-nth 2 event)))
     (fn-bplc-with-session st
      (fn-bpsched-session-view
       (fn-ag-append rows (list (list (fn-ncfg-nth 1 event)
                          (fn-ncfg-nth 1 plan) (fn-ncfg-nth 2 plan))))))))
   (:retained-closed
    (fn-bplc-with-session st
     (fn-bpsched-session-view (fn-bpsched-remove (fn-ncfg-nth 1 event) rows))))
   (otherwise (fn-bplc-step st event)))))
(defun fn-bpsched-service (phase)
 (declare (xargs :guard t))
 (nth (mod (nfix phase) 8) '(:fragment :dispatch :expiry :outbox :forward :receipt :report :rotation)))
(defun fn-bpsched-next (phase)
 (declare (xargs :guard t)) (mod (+ 1 (nfix phase)) 8))

(defun fn-bpsched-next-slot (slot count)
 (declare (xargs :guard t))
 (if (and (natp slot) (natp count) (<= 2 slot) (< (+ 1 slot) count))
  (+ 1 slot) 2))

(defun fn-bpsched-listener-index (cursor count)
 (declare (xargs :guard t))
 (if (posp count) (mod (nfix cursor) count) 0))
(defun fn-bpsched-deadline (now grant)
 (declare (xargs :guard (true-listp grant))) (+ (nfix now) (nfix (seventh grant))))
(defun fn-bpsched-timeout-p (now deadline)
 (declare (xargs :guard t)) (and (natp deadline) (<= deadline (nfix now))))
(defun fn-bpsched-forward-entry (plan busy)
 (declare (xargs :guard (true-listp busy)))
 (if (consp plan)
  (if (member-equal (fn-ag-car (car plan)) busy)
   (fn-bpsched-forward-entry (cdr plan) busy) (car plan)) nil))

; A completed bounded input/source/output action prepays one slot sweep without
; an artificial sleep at every empty slot. Idle/local polling does not do so.
; This is scheduling cadence, not a resource return or overall latency bound.
(defun fn-bpsched-work-credit (status action previous slots)
 (declare (xargs :guard t))
 (if (and (eq status :work) (member-eq action '(:source :buffer :encode :write)))
  (nfix slots) (if (zp (nfix previous)) 0 (1- (nfix previous)))))
(defun fn-bpsched-idle-p (credit)
 (declare (xargs :guard t)) (zp (nfix credit)))
