; RFC9171 section4.3.2 canonical block framing over an issued immutable
; source. Internal parser, not a backing issuer, integrity result or admission.
; Data/CRC remain source spans; a logical full body is never accumulated.
(in-package "ACL2")
(include-book "bpsec-head")
(set-verify-guards-eagerness 0)
; Fixed14 record:tag,phase,source,total,at,start,head,arraycount,type,number,
; flags,crctype,bodyremaining,data-span. CRC span is emitted at completion.
(defun fn-bpwc-start (source total at)
 (declare (xargs :guard t))
 (if (and (fn-bps-uintp total) (fn-bps-uintp at) (<= at total))
  (list :bp-canonical :array source total at at (fn-bps-head-start)
        0 0 0 0 0 0 nil)
  (list :bp-canonical :refused source 0 0 0 (fn-bps-head-start)
        0 0 0 0 0 0 nil)))
(defun fn-bpwc-next (c phase at head arrays type number flags crc remaining span)
 (declare (xargs :guard t))
 (list :bp-canonical phase (fn-bps-field 2 c) (fn-bps-field 3 c) at
       (fn-bps-field 5 c) head arrays type number flags crc remaining span))
(defun fn-bpwc-event (c at crcspan)
 (declare (xargs :guard t))
 (list :bp-canonical-source (fn-bps-field 2 c) (fn-bps-field 5 c) at
       (fn-bps-field 8 c) (fn-bps-field 9 c) (fn-bps-field 10 c)
       (fn-bps-field 11 c) (fn-bps-field 13 c) crcspan))
(defun fn-bpwc-refused (c at)
 (declare (xargs :guard t))
 (fn-bpwc-next c :refused at (fn-bps-field 6 c) (fn-bps-field 7 c)
               (fn-bps-field 8 c) (fn-bps-field 9 c) (fn-bps-field 10 c)
               (fn-bps-field 11 c) (fn-bps-field 12 c) (fn-bps-field 13 c)))
(defun fn-bpwc-feed (c octet)
 (declare (xargs :guard t))
 (let* ((phase (fn-bps-field 1 c)) (total (fn-bps-field 3 c))
        (at (fn-bps-field 4 c)) (array (fn-bps-field 7 c))
        (type (fn-bps-field 8 c)) (number (fn-bps-field 9 c))
        (flags (fn-bps-field 10 c)) (crc (fn-bps-field 11 c))
        (remaining (fn-bps-field 12 c)) (span (fn-bps-field 13 c)))
  (cond
   ((eq phase :done) (mv :complete c nil))
   ((or (eq phase :refused) (not (fn-cbor-octetp octet))
        (not (fn-bps-uintp at)) (not (fn-bps-uintp total)) (<= total at))
    (mv :refused (fn-bpwc-refused c at) nil))
   ((or (eq phase :data) (eq phase :crc-bytes))
    (if (not (and (natp remaining) (< 0 remaining))) (mv :refused (fn-bpwc-refused c (1+ at)) nil)
     (let* ((next-at (1+ at)) (left (1- remaining))
            (next-phase (if (equal left 0)
                            (if (eq phase :data)
                                (if (equal crc 0) :done :crc-head) :done) phase))
            (next (fn-bpwc-next c next-phase next-at (fn-bps-head-start)
                               array type number flags crc left span)))
      (if (eq next-phase :done)
       (mv :complete next
        (fn-bpwc-event next next-at
          (if (eq phase :crc-bytes)
              (list :bps-span (fn-bps-field 2 c)
                    (- next-at (if (equal crc 1) 2 4)) (if (equal crc 1) 2 4)) nil)))
       (mv :yield next nil)))))
   (t
    (let* ((answer (fn-bps-head-feed (fn-bps-field 6 c) octet))
           (word (car answer)) (pair (cadr answer)) (head (caddr answer))
           (next-at (1+ at)) (major (fn-cbor-ag-car pair))
           (value (fn-cbor-ag-car (fn-cbor-ag-cdr pair))))
     (cond
      ((eq word :more)
       (mv :yield (fn-bpwc-next c phase next-at head array type number flags crc remaining span) nil))
      ((not (eq word :ready)) (mv :refused (fn-bpwc-refused c (1+ at)) nil))
      ((eq phase :array)
       (if (and (equal major 4) (member-equal value '(5 6)))
        (mv :yield (fn-bpwc-next c :type next-at (fn-bps-head-start) value type number flags crc 0 span) nil)
        (mv :refused (fn-bpwc-refused c (1+ at)) nil)))
      ((member-equal phase '(:type :number :flags :crc))
       (if (not (equal major 0)) (mv :refused (fn-bpwc-refused c (1+ at)) nil)
        (cond
         ((eq phase :type)
          (mv :yield (fn-bpwc-next c :number next-at (fn-bps-head-start) array value number flags crc 0 span) nil))
         ((eq phase :number)
          (if (equal value 0) (mv :refused (fn-bpwc-refused c (1+ at)) nil)
           (mv :yield (fn-bpwc-next c :flags next-at (fn-bps-head-start) array type value flags crc 0 span) nil)))
         ((eq phase :flags)
          (mv :yield (fn-bpwc-next c :crc next-at (fn-bps-head-start) array type number value crc 0 span) nil))
         (t
          (if (or (and (equal array 5) (equal value 0))
                  (and (equal array 6) (member-equal value '(1 2))))
           (mv :yield (fn-bpwc-next c :data-head next-at (fn-bps-head-start) array type number flags value 0 span) nil)
           (mv :refused (fn-bpwc-refused c (1+ at)) nil))))))
      ((eq phase :data-head)
       (if (not (and (equal major 2) (natp value) (<= value (- total next-at))))
        (mv :refused (fn-bpwc-refused c (1+ at)) nil)
        (let* ((data-span (list :bps-span (fn-bps-field 2 c) next-at value))
               (next-phase (if (equal value 0) (if (equal crc 0) :done :crc-head) :data))
               (next (fn-bpwc-next c next-phase next-at (fn-bps-head-start) array type number flags crc value data-span)))
         (if (eq next-phase :done) (mv :complete next (fn-bpwc-event next next-at nil))
          (mv :yield next nil)))))
      ((eq phase :crc-head)
       (if (and (equal major 2) (equal value (if (equal crc 1) 2 4))
                (<= value (- total next-at)))
        (mv :yield (fn-bpwc-next c :crc-bytes next-at (fn-bps-head-start) array type number flags crc value span) nil)
        (mv :refused (fn-bpwc-refused c (1+ at)) nil)))
      (t (mv :refused (fn-bpwc-refused c (1+ at)) nil))))))))
(defun fn-bpwc-window-loop (cursor bytes quantum used)
 (declare (xargs :guard (and (natp quantum) (<= quantum 64) (natp used))
                 :measure (nfix quantum) :verify-guards nil))
 (cond ((eq (fn-bps-field 1 cursor) :done) (mv :complete cursor used bytes nil))
       ((eq (fn-bps-field 1 cursor) :refused) (mv :refused cursor used bytes nil))
       ((or (zp quantum) (atom bytes)) (mv :yield cursor used bytes nil))
       (t (mv-let (word next event) (fn-bpwc-feed cursor (car bytes))
   (if (eq word :yield)
    (fn-bpwc-window-loop next (cdr bytes) (1- quantum) (1+ used))
    (mv word next (1+ used) (cdr bytes) event))))))
