; RFC 9172 sections 3.5/3.8/3.9: structural target graph reference.
; This logical list walk is not installed as a served lookup/validation path.
; Operational bounded traversal/refinement and byte-binding are separate joins.
(in-package "ACL2")
(include-book "bpsec-asb")
(include-book "bp-bundle")

(defun fn-bps-block-number-find (number blocks)
  (declare (xargs :guard t))
  (if (consp blocks)
      (if (equal number (fn-bpb-block-number (car blocks))) (car blocks)
        (fn-bps-block-number-find number (cdr blocks))) nil))

(defun fn-bps-target-block (number bundle)
  (declare (xargs :guard t))
  (if (equal number 1) (fn-bpb-bundle-payload bundle)
    (fn-bps-block-number-find number (fn-bpb-bundle-blocks bundle))))

(defun fn-bps-binding-numbers (bindings)
  (declare (xargs :guard t))
  (if (consp bindings) (cons (fn-bps-field 0 (car bindings)) (fn-bps-binding-numbers (cdr bindings))) nil))

(defun fn-bps-bindingsp (bindings)
  (declare (xargs :guard t))
  (if (consp bindings)
      (and (consp (car bindings)) (fn-bps-uintp (caar bindings))
           (fn-bps-asbp (cdar bindings)) (fn-bps-bindingsp (cdr bindings)))
    (null bindings)))

(defun fn-bps-binding-known-contextp (bindings)
  (declare (xargs :guard t))
  (if (consp bindings)
      (and (equal (fn-bps-field 3 (if (consp (car bindings)) (cdar bindings) nil))
                  (if (equal (fn-bps-field 1 (if (consp (car bindings)) (cdar bindings) nil)) 11) 1 2))
           (fn-bps-binding-known-contextp (cdr bindings))) t))

(defun fn-bps-bindings-kind-matchp (bundle bindings)
  (declare (xargs :guard t))
  (if (consp bindings)
      (let* ((binding (car bindings)) (number (fn-bps-field 0 binding))
             (asb (if (consp binding) (cdr binding) nil))
             (block (fn-bps-target-block number bundle)))
        (and (consp block) (member-equal (fn-bpb-block-type block) '(11 12))
             (equal (fn-bpb-block-type block) (fn-bps-field 1 asb))
             (fn-bps-bindings-kind-matchp bundle (cdr bindings)))) t))

; Mandatory logical premise for claims about the ACTUAL bundle. This is not
; run as a second whole-data decoder on a served path. The actual cursor and
; immutable provider must establish/carry the corresponding invariant.
(defun fn-bps-parsed-bindings-matchp (bundle bindings limits)
  (declare (xargs :guard t))
  (if (consp bindings)
      (let* ((binding (car bindings)) (number (fn-bps-field 0 binding))
             (asb (if (consp binding) (cdr binding) nil))
             (block (fn-bps-target-block number bundle)))
        (and (consp block) (member-equal (fn-bpb-block-type block) '(11 12))
             (equal (fn-bpb-block-type block) (fn-bps-field 1 asb))
             (equal (fn-bps-asb-decode (fn-bpb-block-type block) (fn-bpb-block-data block) limits)
                    (list :parsed asb))
             (fn-bps-parsed-bindings-matchp bundle (cdr bindings) limits)))
    (null bindings)))

(defun fn-bps-targets-reason (number kind targets bundle security-block)
  (declare (xargs :guard t))
  (if (consp targets)
      (let* ((target (car targets)) (block (fn-bps-target-block target bundle))
             (type (if (equal target 0) 0 (fn-bpb-block-type block))))
        (cond ((and (not (equal target 0)) (not (consp block))) :missing-target)
              ((and (equal kind 11) (member-equal type '(11 12))) :bib-security-target)
              ((and (equal kind 12) (or (equal target 0) (equal type 12) (equal target number))) :bcb-forbidden-target)
              ((and (equal kind 12) (equal target 1)
                    (or (equal (logand (nfix (fn-bpb-block-flags security-block)) 1) 0)
                        (not (equal (logand (nfix (fn-bpb-block-flags security-block)) 16) 0))))
               :payload-bcb-flags)
              (t (fn-bps-targets-reason number kind (cdr targets) bundle security-block)))) nil))

(defun fn-bps-bindings-target-reason (bundle bindings)
  (declare (xargs :guard t))
  (if (consp bindings)
      (let* ((binding (car bindings)) (number (fn-bps-field 0 binding))
             (asb (if (consp binding) (cdr binding) nil))
             (reason (fn-bps-targets-reason number (fn-bps-field 1 asb) (fn-bps-field 2 asb)
                                           bundle (fn-bps-target-block number bundle))))
        (or reason (fn-bps-bindings-target-reason bundle (cdr bindings)))) nil))

(defun fn-bps-service-pairs (kind targets)
  (declare (xargs :guard t))
  (if (consp targets) (cons (list kind (car targets)) (fn-bps-service-pairs kind (cdr targets))) nil))

(defun fn-bps-binding-service-pairs (bindings)
  (declare (xargs :guard t))
  (if (consp bindings)
      (let ((asb (if (consp (car bindings)) (cdar bindings) nil)))
        (append (fn-bps-service-pairs (fn-bps-field 1 asb) (fn-bps-field 2 asb))
                (fn-bps-binding-service-pairs (cdr bindings)))) nil))

(defun fn-bps-encrypted-bib-targets (targets bundle)
  (declare (xargs :guard t))
  (if (consp targets)
      (if (equal (fn-bpb-block-type (fn-bps-target-block (car targets) bundle)) 11)
          (cons (car targets) (fn-bps-encrypted-bib-targets (cdr targets) bundle))
        (fn-bps-encrypted-bib-targets (cdr targets) bundle)) nil))

(defun fn-bps-encrypted-bib-numbers (bindings bundle)
  (declare (xargs :guard t))
  (if (consp bindings)
      (let ((asb (if (consp (car bindings)) (cdar bindings) nil)))
        (append (if (equal (fn-bps-field 1 asb) 12)
                    (fn-bps-encrypted-bib-targets (fn-bps-field 2 asb) bundle) nil)
                (fn-bps-encrypted-bib-numbers (cdr bindings) bundle))) nil))

(defun fn-bps-memberp (value values)
  (declare (xargs :guard t))
  (if (consp values) (or (equal value (car values)) (fn-bps-memberp value (cdr values))) nil))

(defun fn-bps-subsetp (left right)
  (declare (xargs :guard t))
  (if (consp left) (and (fn-bps-memberp (car left) right) (fn-bps-subsetp (cdr left) right)) t))

(defun fn-bps-intersectp (left right)
  (declare (xargs :guard t))
  (if (consp left) (or (fn-bps-memberp (car left) right) (fn-bps-intersectp (cdr left) right)) nil))

(defun fn-bps-security-coveredp (blocks bound opaque kind)
  (declare (xargs :guard t))
  (if (consp blocks)
      (and (or (not (member-equal (fn-bpb-block-type (car blocks)) '(11 12)))
               (and (not (eq kind :both)) (not (equal kind (fn-bpb-block-type (car blocks)))))
               (fn-bps-memberp (fn-bpb-block-number (car blocks)) bound)
               (and (equal (fn-bpb-block-type (car blocks)) 11)
                    (fn-bps-memberp (fn-bpb-block-number (car blocks)) opaque)))
           (fn-bps-security-coveredp (cdr blocks) bound opaque kind)) t))

(defun fn-bps-pairs-overlapp (pair pairs)
  (declare (xargs :guard t))
  (if (consp pairs)
      (or (and (equal (fn-bps-field 0 pair) 11) (equal (fn-bps-field 0 (car pairs)) 12)
               (equal (fn-bps-field 1 pair) (fn-bps-field 1 (car pairs))))
          (fn-bps-pairs-overlapp pair (cdr pairs))) nil))

(defun fn-bps-bib-bcb-overlapp (todo pairs)
  (declare (xargs :guard t))
  (if (consp todo) (or (fn-bps-pairs-overlapp (car todo) pairs)
                      (fn-bps-bib-bcb-overlapp (cdr todo) pairs)) nil))

(defun fn-bps-binding-target-count (bindings)
  (declare (xargs :guard t))
  (if (consp bindings) (+ (len (fn-bps-field 2 (if (consp (car bindings)) (cdar bindings) nil)))
                         (fn-bps-binding-target-count (cdr bindings))) 0))

(defun fn-bps-target-check (bundle parsed-bindings opaque-bib-numbers limits)
  (declare (xargs :guard t))
  (cond
   ((not (fn-bpb-bundlep bundle)) (list :refused :bundle-shape))
   ((not (fn-bps-limitsp limits)) (list :refused :unrepresentable-profile))
   ((not (and (fn-bps-bindingsp parsed-bindings) (fn-bps-uint-listp opaque-bib-numbers)
              (no-duplicatesp-equal opaque-bib-numbers))) (list :refused :binding-or-opaque-shape))
   ((not (no-duplicatesp-equal (fn-bps-binding-numbers parsed-bindings))) (list :refused :duplicate-binding))
   ((not (fn-bps-bindings-kind-matchp bundle parsed-bindings)) (list :refused :binding-kind))
   ((not (fn-bps-binding-known-contextp parsed-bindings)) (list :unsupported :security-context))
   ((< (nfix (fn-bps-field 6 limits))
       (+ (len parsed-bindings) (len opaque-bib-numbers) (fn-bps-binding-target-count parsed-bindings)))
    (list :refused :graph-metadata-limit))
   (t
    (let* ((bound (fn-bps-binding-numbers parsed-bindings))
           (blocks (fn-bpb-bundle-blocks bundle))
           (reason (fn-bps-bindings-target-reason bundle parsed-bindings)))
      (cond (reason (list :refused reason))
            ((not (fn-bps-security-coveredp blocks bound nil 12))
             (list :unsupported :incomplete-security-coverage))
            (t (let* ((pairs (fn-bps-binding-service-pairs parsed-bindings))
                      (encrypted (fn-bps-encrypted-bib-numbers parsed-bindings bundle)))
                 (cond ((not (no-duplicatesp-equal pairs)) (list :refused :duplicate-service-target))
                       ((fn-bps-intersectp bound encrypted) (list :refused :encrypted-bib-parsed))
                       ((not (and (fn-bps-subsetp encrypted opaque-bib-numbers)
                                  (fn-bps-subsetp opaque-bib-numbers encrypted))) (list :refused :opaque-set))
                       ((not (fn-bps-security-coveredp blocks bound encrypted :both))
                        (list :unsupported :incomplete-security-coverage))
                       ((fn-bps-bib-bcb-overlapp pairs pairs) (list :refused :unencrypted-bib-overlap))
                       ((consp encrypted) :pending-plaintext)
                       (t :valid)))))))))
