; Actual owner alias-holder splice for one complete event's collection.
; Internal only: parameters do not issue current source/BODY/report authority.
(in-package "ACL2")
(include-book "consumer-remote-semantic-state")
(include-book "consumer-remote-collection-buffer")

(defun fn-owner-remote-collection-keep (token pending outcome state)
 (declare (xargs :stobjs state :guard t))
 (let ((held (fn-owner-remote-scan-read state)))
  (fn-owner-remote-scan-update-internal token (fn-cp-nth 3 held)
   (fn-owner-history-read-slot state) pending (fn-cp-nth 6 held) outcome state)))

; The canonical publication/physical completion issuer is separate. An encoded
; buffer cannot authorize cursor advancement or a successful durable reply.
(defun fn-owner-remote-collection-publication (token state)
 (declare (xargs :stobjs state :guard t) (ignore token))
 (mv '(:unavailable :remote-collection-publication-issuer) state))

(defun fn-owner-remote-collection-step-internal
 (token key ingress generation posting-config current-view query-limit items ceiling extent
        fn-arena fn-history-backing fn-octets state)
 (declare (xargs :stobjs (fn-arena fn-history-backing fn-octets state) :guard t))
 (let* ((held (fn-owner-remote-scan-read state)) (pending (fn-cp-nth 5 held))
        (tag (fn-cp-nth 0 pending)) (scanner (fn-cp-nth 3 held))
        (scope (fn-crs-key ingress generation))
        (source (fn-hhc-at 3 (fn-owner-history-capture-slot state))))
  (cond
   ((not (and (eq (fn-cp-nth 0 held) :remote-scan-holder)
               (equal token (fn-cp-nth 1 held)) (eq (fn-cp-nth 2 held) :active)))
    (mv '(:refused :remote-scan-token-or-phase) fn-octets state))
   ((not (equal key (fn-cp-nth 7 held)))
    (mv '(:refused :consumer-source-changed) fn-octets state))
   ((not (and (eq (fn-owner-history-recheck token state) :history-source-current)
               (fn-hep-capture-livep source token fn-history-backing)))
    (mv '(:unavailable :history-source) fn-octets state))
   ((not (eq (fn-cp-nth 0 ingress) :authenticated)) (mv ingress fn-octets state))
   ((not (fn-crcol-profilep items ceiling))
    (mv '(:refused :remote-report-profile) fn-octets state))
   ((member-eq tag '(:event-before-query :semantic))
    (let ((semantic (if (eq tag :semantic) (list :yield (fn-cp-nth 1 pending))
                     (if (equal (fn-cp-nth 2 pending) (fn-cp-nth 5 scanner))
                      (fn-crm-begin scanner (fn-cp-nth 1 pending) ingress generation posting-config current-view)
                      '(:refused :semantic-history-coordinate)))))
     (let ((answer (if (eq (fn-cp-nth 0 semantic) :yield)
                       (fn-crcol-begin (fn-cp-nth 1 semantic) items ceiling) semantic)))
      (if (not (eq (fn-cp-nth 0 answer) :yield)) (mv answer fn-octets state)
       (mv-let (status state)
         (fn-owner-remote-collection-keep token (list :collection-preparing (fn-cp-nth 1 answer)) :preparing state)
        (mv status fn-octets state))))))
   ((eq tag :collection-preparing)
    (let* ((child (fn-cp-nth 1 pending))
           (answer (if (and (equal items (fn-cp-nth 10 child)) (equal ceiling (fn-cp-nth 11 child)))
                       (fn-crcol-tick child key scope query-limit fn-arena)
                     '(:refused :remote-report-policy-source-changed))))
     (if (not (member-eq (fn-cp-nth 0 answer) '(:yield :collection-ready))) (mv answer fn-octets state)
      (mv-let (status state)
        (fn-owner-remote-collection-keep token
          (if (eq (fn-cp-nth 0 answer) :yield)
              (list tag (fn-cp-nth 1 answer)) (list :collection-ready answer key scope items ceiling)) :preparing state)
       (mv status fn-octets state)))))
   ((eq tag :collection-ready)
    (if (not (and (equal key (fn-cp-nth 2 pending)) (equal scope (fn-cp-nth 3 pending))
                  (equal items (fn-cp-nth 4 pending)) (equal ceiling (fn-cp-nth 5 pending))))
        (mv '(:refused :remote-semantic-source-changed) fn-octets state)
     (let ((answer (fn-crcol-write-begin (fn-cp-nth 1 pending) key scope items ceiling
                                        (fn-octets-len fn-octets) extent)))
      (if (not (eq (fn-cp-nth 0 answer) :yield)) (mv answer fn-octets state)
       (mv-let (status state)
         (fn-owner-remote-collection-keep token (list :collection-writing (fn-cp-nth 1 answer) items ceiling) :writing state)
        (mv status fn-octets state))))))
   ((eq tag :collection-writing)
    (mv-let (answer fn-octets)
      (if (and (equal items (fn-cp-nth 2 pending)) (equal ceiling (fn-cp-nth 3 pending)))
          (fn-crcol-write-step (fn-cp-nth 1 pending) key scope extent fn-arena fn-octets)
        (mv '(:refused :remote-report-policy-source-changed) fn-octets))
     (if (not (member-eq (fn-cp-nth 0 answer) '(:yield :encoded))) (mv answer fn-octets state)
      (mv-let (status state)
        (fn-owner-remote-collection-keep token
         (if (eq (fn-cp-nth 0 answer) :yield) (list tag (fn-cp-nth 1 answer) items ceiling)
            (list :collection-encoded answer key scope items ceiling)) :writing state)
       (mv status fn-octets state)))))
   ((eq tag :collection-encoded)
    (if (not (and (equal key (fn-cp-nth 2 pending)) (equal scope (fn-cp-nth 3 pending))
                  (equal items (fn-cp-nth 4 pending)) (equal ceiling (fn-cp-nth 5 pending))))
        (mv '(:refused :remote-semantic-source-changed) fn-octets state)
     (mv-let (answer state) (fn-owner-remote-collection-publication token state)
      (mv answer fn-octets state))))
   (t (mv '(:refused :remote-collection-pending-kind) fn-octets state)))))

(in-theory (disable fn-owner-remote-collection-keep fn-owner-remote-collection-publication
 fn-owner-remote-collection-step-internal))
