; One private physical decoded activation. The actual pool draw must precede
; construction; this book establishes no complete allocator/GC tariff.
(in-package "ACL2")
(include-book "decoded-worker-assignment")

(defstobj fn-decoded-job
  (fn-dwj-carry :type fn-pww-carry)
  (fn-dwj-input :type fn-octets)
  (fn-dwj-hash :type pgs-digest-state)
  (fn-dwj-zin :type fn-zin-st)
  (fn-dwj-win :type fn-zin-win)
  (fn-dwj-tab :type fn-zin-tab)
  (fn-dwj-out :type fn-zin-out)
  (fn-dwj-window :type fn-ew-buffer)
  :inline t)

(defun fn-dwj-assign (ledger worker token root incarnation fn-decoded-job)
  (declare (xargs :stobjs fn-decoded-job :guard t :verify-guards nil))
  (stobj-let ((fn-pww-carry (fn-dwj-carry fn-decoded-job))
              (fn-octets (fn-dwj-input fn-decoded-job)))
    (word fn-pww-carry fn-octets)
    (mv-let (word fn-pww-carry)
      (fn-dwa-assign ledger worker token root incarnation fn-pww-carry)
      (let ((fn-octets (if (eq word :decoded-assigned)
                          (fn-octets-reserve 64 fn-octets) fn-octets)))
        (mv word fn-pww-carry fn-octets)))
    (mv word fn-decoded-job)))

(defun fn-dwj-begin (token fn-decoded-job)
  (declare (xargs :stobjs fn-decoded-job :guard t :verify-guards nil))
  (stobj-let ((fn-pww-carry (fn-dwj-carry fn-decoded-job))
              (pgs-digest-state (fn-dwj-hash fn-decoded-job))
              (fn-zin-st (fn-dwj-zin fn-decoded-job))
              (fn-zin-win (fn-dwj-win fn-decoded-job))
              (fn-zin-tab (fn-dwj-tab fn-decoded-job))
              (fn-zin-out (fn-dwj-out fn-decoded-job)))
    (word fn-pww-carry pgs-digest-state fn-zin-st fn-zin-win fn-zin-tab fn-zin-out)
    (fn-dwc-begin token fn-pww-carry pgs-digest-state fn-zin-st fn-zin-win fn-zin-tab fn-zin-out)
    (mv word fn-decoded-job)))

(defun fn-dwj-one (token fn-decoded-job)
  (declare (xargs :stobjs fn-decoded-job :guard t :verify-guards nil))
  (stobj-let ((fn-pww-carry (fn-dwj-carry fn-decoded-job))
              (fn-octets (fn-dwj-input fn-decoded-job))
              (pgs-digest-state (fn-dwj-hash fn-decoded-job))
              (fn-zin-st (fn-dwj-zin fn-decoded-job))
              (fn-zin-win (fn-dwj-win fn-decoded-job))
              (fn-zin-tab (fn-dwj-tab fn-decoded-job))
              (fn-zin-out (fn-dwj-out fn-decoded-job))
              (fn-ew-buffer (fn-dwj-window fn-decoded-job)))
    (word effect fn-pww-carry fn-octets pgs-digest-state fn-zin-st fn-zin-win fn-zin-tab fn-zin-out fn-ew-buffer)
    (fn-dwc-one token fn-pww-carry fn-octets pgs-digest-state fn-zin-st fn-zin-win fn-zin-tab fn-zin-out fn-ew-buffer)
    (mv word effect fn-decoded-job)))

(defun fn-dwj-read-observation (token revision status fn-decoded-job)
  (declare (xargs :stobjs fn-decoded-job :guard t :verify-guards nil))
  (stobj-let ((fn-pww-carry (fn-dwj-carry fn-decoded-job))
              (fn-octets (fn-dwj-input fn-decoded-job))
              (pgs-digest-state (fn-dwj-hash fn-decoded-job))
              (fn-ew-buffer (fn-dwj-window fn-decoded-job)))
    (word fn-pww-carry fn-octets pgs-digest-state fn-ew-buffer)
    (fn-dwc-read-observation token revision status fn-pww-carry fn-octets pgs-digest-state fn-ew-buffer)
    (mv word fn-decoded-job)))

(defun fn-dwj-outcome (ledger worker token fn-decoded-job)
  (declare (xargs :stobjs fn-decoded-job :guard t :verify-guards nil))
  (stobj-let ((fn-pww-carry (fn-dwj-carry fn-decoded-job)))
    (word)
    (let ((z (fn-dwa-controller fn-pww-carry)))
      (if (and (true-listp z) (true-listp (nth 1 z)))
          (fn-pwz-outcome ledger worker token z) :stale-decoded-worker))
    word))

(defun fn-dwj-byte-at (ledger worker token file eoff elen poff compressed trailer decoded dict-id i fn-decoded-job)
  (declare (xargs :stobjs fn-decoded-job :guard t :verify-guards nil))
  (stobj-let ((fn-pww-carry (fn-dwj-carry fn-decoded-job))
              (fn-ew-buffer (fn-dwj-window fn-decoded-job)))
    (word byte)
    (let ((z (fn-dwa-controller fn-pww-carry)))
      (if (and (true-listp z) (true-listp (nth 1 z)))
          (fn-pwz-byte-at ledger worker token z
                   file eoff elen poff compressed trailer decoded dict-id i fn-ew-buffer)
        (mv :stale-decoded-worker nil)))
    (mv word byte)))

(verify-guards fn-dwj-assign)
(verify-guards fn-dwj-begin)
(verify-guards fn-dwj-one)
(verify-guards fn-dwj-read-observation)
(verify-guards fn-dwj-outcome)
(verify-guards fn-dwj-byte-at)
