; Round 5a: candidate definitions and guard checks, not certified keystones.
; The contracts for review are in planning/design/xc-span-walk-statements-2026-10-08.md.
(in-package "ACL2")
(include-book "extent-cache-span")
(include-book "decoded-window-span")
(include-book "def-buffer")

; Entries are growable octet arrays, not fixed-size entry reservations.
(def-buffer fn-xce-entry :view t)
(def-buffer fn-xce-stage :view t)
(defmacro fn-xce-define ()
  `(defstobj fn-xce
     (fn-xce-keys :type (array t (,(fn-profile-limit :extent-cache-entries))) :initially nil)
     (fn-xce-entries :type (array fn-xce-entry (,(fn-profile-limit :extent-cache-entries))))))
(fn-xce-define)

(defun fn-xc-entry-key (file eoff elen trailer token)
  (declare (xargs :guard t))
  (list 1 file eoff elen trailer token))

; No second decoded-window bank: kinds 2 and 3 share NW table slots.
; Kind 3's plan is Z, the complete decoded controller, not NIL or its raw S.
(defun fn-xc-decoded-planp (z token)
  (declare (xargs :guard t))
  (and (true-listp z) (true-listp (nth 1 z))
       (fn-pwz-plan-matches-token z token)
       (fn-ewz-publication z)
       (natp (nth 4 z))
       (equal (nth 4 z) (fn-pwz-token-window-length token))
       (<= (nth 4 z) (fn-profile-limit :read-window-octets))))

(defun fn-xc-init-all (ne nw fn-xcs fn-xcc)
  (declare (xargs :stobjs (fn-xcs fn-xcc)
                  :guard (and (fn-xcsp fn-xcs) (fn-xccp fn-xcc))))
  (cond ((and (natp ne) (< (fn-profile-limit :extent-cache-entries) ne))
         (mv :refused-entry-rows fn-xcs fn-xcc))
        ((and (natp nw) (< (fn-profile-limit :extent-cache-windows) nw))
         (mv :refused-window-rows fn-xcs fn-xcc))
        (t (fn-xc-init ne nw fn-xcs fn-xcc))))

; Constant-work adoption of the already allocated, verified entry.
; The stage receives the victim buffer; the caller owns its later release.
(defun fn-xce-adopt (slot key fn-xce fn-xce-stage)
  (declare (xargs :stobjs (fn-xce fn-xce-stage)
                  :guard (and (natp slot) (< slot (fn-xce-keys-length fn-xce)))))
  (let ((fn-xce (update-fn-xce-keysi slot key fn-xce)))
    (stobj-let ((fn-xce-entry (fn-xce-entriesi slot fn-xce)))
               (fn-xce-entry fn-xce-stage)
      (swap-stobjs fn-xce-entry fn-xce-stage)
      (mv fn-xce fn-xce-stage))))

(defun fn-xc-install-entry-bytes (file eoff elen trailer token fn-xcs fn-xcc fn-xce fn-xce-stage)
  (declare (xargs :stobjs (fn-xcs fn-xcc fn-xce fn-xce-stage)
                  :guard (and (fn-xcsp fn-xcs) (fn-xccp fn-xcc))
                  :verify-guards nil))
  (if (not (and (fn-xc-readyp fn-xcs fn-xcc)
                (<= (fn-xc-ne fn-xcc) (fn-xce-keys-length fn-xce))))
      (mv :refused-entry-rows nil nil fn-xcs fn-xcc fn-xce fn-xce-stage)
    (if (not (and (natp elen) (equal (fn-xce-stage-len fn-xce-stage)
                                     (+ elen *fn-frame-trailer-octets*))))
        (mv :refused-entry-length nil nil fn-xcs fn-xcc fn-xce fn-xce-stage)
      (mv-let (word slot evicted fn-xcs fn-xcc)
        (fn-xc-install-entry file eoff elen trailer token fn-xcs fn-xcc)
        (if (and (member-equal word '(:installed :replaced)) (natp slot)
                 (< slot (fn-xce-keys-length fn-xce)))
            (mv-let (fn-xce fn-xce-stage)
              (fn-xce-adopt slot (fn-xc-entry-key file eoff elen trailer token) fn-xce fn-xce-stage)
              (mv word slot evicted fn-xcs fn-xcc fn-xce fn-xce-stage))
          (mv word slot evicted fn-xcs fn-xcc fn-xce fn-xce-stage))))))

(defun fn-xc-install-decoded-bytes (token z fn-xcs fn-xcc fn-xcw fn-ew-buffer)
  (declare (xargs :stobjs (fn-xcs fn-xcc fn-xcw fn-ew-buffer)
                  :guard (and (fn-xcsp fn-xcs) (fn-xccp fn-xcc))
                  :verify-guards nil))
  (cond ((not (and (fn-xc-readyp fn-xcs fn-xcc)
                   (<= (fn-xc-nw fn-xcc) (fn-xcw-plans-length fn-xcw))))
         (mv :refused-window-rows nil nil fn-xcs fn-xcc fn-xcw))
        ((not (fn-xc-decoded-planp z token))
         (mv :refused-decoded-plan nil nil fn-xcs fn-xcc fn-xcw))
        (t (let ((base (fn-xc-ne fn-xcc)))
         (mv-let (word slot evicted fn-xcs fn-xcc)
           (fn-xc-install-window token fn-xcs fn-xcc)
           (if (and (member-equal word '(:installed :replaced)) (natp slot)
                    (<= base slot)
                    (< (nfix (- slot base)) (fn-xcw-plans-length fn-xcw)))
               (let* ((row (nfix (- slot base)))
                      (fn-xcw (update-fn-xcw-plansi row z fn-xcw)))
                 (stobj-let ((fn-xcw-win (fn-xcw-winsi row fn-xcw))) (fn-xcw-win)
                   (fn-xcw-copy 0 (fn-pwz-token-window-length token) 0 fn-ew-buffer fn-xcw-win)
                   (mv word slot evicted fn-xcs fn-xcc fn-xcw)))
             (mv word slot evicted fn-xcs fn-xcc fn-xcw)))))))

(defun fn-xc-decoded-span-row (slot ledger file eoff elen poff compressed trailer decoded dict-id p end
                                  fn-xcs fn-xcc fn-xcw fn-ew-span)
  (declare (xargs :stobjs (fn-xcs fn-xcc fn-xcw fn-ew-span)
                  :guard (and (fn-xcsp fn-xcs) (fn-xccp fn-xcc) (fn-xc-cellsp fn-xcc)
                              (natp slot) (< slot (fn-xcs-count fn-xcs))
                              (natp p) (natp end) (natp decoded))
                  :verify-guards nil))
  (let ((row (fn-xc-row slot fn-xcc)) (token (fn-xc-slot-token slot fn-xcs)))
    (if (and (<= (fn-xc-ne fn-xcc) slot) (< row (fn-xcw-plans-length fn-xcw)))
        (let ((z (fn-xcw-plansi row fn-xcw)))
          (if (fn-xc-decoded-planp z token)
              (let ((j (fn-xc-span-end p end decoded (fn-pwz-nth 7 token)
                                     (fn-pwz-token-window-length token))))
                (if (< p j)
                    (stobj-let ((fn-xcw-win (fn-xcw-winsi row fn-xcw))) (word fn-ew-span)
                      (fn-pwz-cache-span-at ledger token file eoff elen poff compressed trailer
                                           decoded dict-id p j fn-xcw-win fn-ew-span)
                      (mv word j fn-ew-span))
                  (mv :miss 0 fn-ew-span)))
            (mv :miss 0 fn-ew-span)))
      (mv :miss 0 fn-ew-span))))

; Scan each row once: no repeated suffix lookup, no host candidate loop.
(defun fn-xc-decoded-span-at (from ledger file eoff elen poff compressed trailer decoded dict-id p end
                                 fn-xcs fn-xcc fn-xcw fn-ew-span)
  (declare (xargs :stobjs (fn-xcs fn-xcc fn-xcw fn-ew-span)
                  :guard (and (fn-xcsp fn-xcs) (fn-xccp fn-xcc)
                              (natp from) (natp p) (natp end) (natp decoded))
                  :measure (nfix (- (fn-xcs-count fn-xcs) (nfix from)))
                  :verify-guards nil))
  (if (and (fn-xc-readyp fn-xcs fn-xcc) (natp from) (< from (fn-xcs-count fn-xcs)))
      (mv-let (word j fn-ew-span)
        (if (and (fn-xc-slot-matchp from nil 3 file eoff elen poff compressed decoded dict-id trailer p fn-xcs)
                 (natp p) (natp end) (natp decoded))
            (fn-xc-decoded-span-row from ledger file eoff elen poff compressed trailer decoded dict-id p end
                                    fn-xcs fn-xcc fn-xcw fn-ew-span)
          (mv :miss 0 fn-ew-span))
        (if (equal word :span)
            (mv-let (touch fn-xcs fn-xcc) (fn-xc-touch from fn-xcs fn-xcc)
              (declare (ignore touch))
              (mv :span (- j p) from fn-ew-span fn-xcs fn-xcc))
          (fn-xc-decoded-span-at (1+ from) ledger file eoff elen poff compressed trailer decoded dict-id p end
                                fn-xcs fn-xcc fn-xcw fn-ew-span)))
    (mv :miss 0 nil fn-ew-span fn-xcs fn-xcc)))

; The entry's scalar and whole-payload callers can use successive bounded
; spans. POFF-EOFF+P is decided here, never computed in native code.
(defun fn-xce-copy (src count dst fn-xce-entry fn-ew-span)
  (declare (xargs :stobjs (fn-xce-entry fn-ew-span)
                  :guard (and (natp src) (natp count) (natp dst)
                              (<= (+ src count) (fn-xce-entry-len fn-xce-entry))
                              (<= (+ dst count) *fn-ew-span-capacity*))
                  :measure (nfix count) :verify-guards nil))
  (if (zp count) fn-ew-span
    (let ((fn-ew-span (update-fn-ew-span-bytesi dst (fn-xce-entry-get src fn-xce-entry) fn-ew-span)))
      (fn-xce-copy (1+ src) (1- count) (1+ dst) fn-xce-entry fn-ew-span))))

(defun fn-xc-entry-span-row (slot file eoff elen poff plen trailer p end fn-xcs fn-xce fn-ew-span)
  (declare (xargs :stobjs (fn-xcs fn-xce fn-ew-span)
                  :guard (and (fn-xcsp fn-xcs) (natp slot) (< slot (fn-xcs-count fn-xcs))
                              (natp eoff) (natp elen) (natp poff) (natp plen) (natp p) (natp end))
                  :verify-guards nil))
  (if (and (< slot (fn-xce-keys-length fn-xce)) (<= eoff poff) (<= (+ poff plen) (+ eoff elen))
           (equal (fn-xce-keysi slot fn-xce)
                  (fn-xc-entry-key file eoff elen trailer (fn-xc-slot-token slot fn-xcs))))
      (let ((j (min (min end plen) (+ p *fn-ew-span-capacity*))))
        (if (< p j)
            (stobj-let ((fn-xce-entry (fn-xce-entriesi slot fn-xce))) (word fn-ew-span)
              (if (equal (fn-xce-entry-len fn-xce-entry) (+ elen *fn-frame-trailer-octets*))
                  (let ((fn-ew-span (fn-xce-copy (+ (- poff eoff) p) (- j p) 0 fn-xce-entry fn-ew-span)))
                    (mv :span fn-ew-span))
                (mv :miss fn-ew-span))
              (mv word j fn-ew-span))
          (mv :miss 0 fn-ew-span)))
    (mv :miss 0 fn-ew-span)))

(defun fn-xc-entry-span-at (from file eoff elen poff plen trailer p end fn-xcs fn-xcc fn-xce fn-ew-span)
  (declare (xargs :stobjs (fn-xcs fn-xcc fn-xce fn-ew-span)
                  :guard (and (fn-xcsp fn-xcs) (fn-xccp fn-xcc) (natp from)
                              (natp eoff) (natp elen) (natp poff) (natp plen) (natp p) (natp end))
                  :measure (nfix (- (fn-xcs-count fn-xcs) (nfix from))) :verify-guards nil))
  (if (and (fn-xc-readyp fn-xcs fn-xcc) (natp from) (< from (fn-xcs-count fn-xcs)))
      (mv-let (word j fn-ew-span)
        (if (and (< from (fn-xc-ne fn-xcc))
                 (fn-xc-slot-matchp from nil 1 file eoff elen 0 0 0 0 trailer 0 fn-xcs)
                 (natp eoff) (natp elen) (natp poff) (natp plen) (natp p) (natp end))
            (fn-xc-entry-span-row from file eoff elen poff plen trailer p end fn-xcs fn-xce fn-ew-span)
          (mv :miss 0 fn-ew-span))
        (if (equal word :span)
            (mv-let (touch fn-xcs fn-xcc) (fn-xc-touch from fn-xcs fn-xcc)
              (declare (ignore touch))
              (mv :span (- j p) from fn-ew-span fn-xcs fn-xcc))
          (fn-xc-entry-span-at (1+ from) file eoff elen poff plen trailer p end fn-xcs fn-xcc fn-xce fn-ew-span)))
    (mv :miss 0 nil fn-ew-span fn-xcs fn-xcc)))

(verify-guards fn-xc-install-entry-bytes)
(verify-guards fn-xc-install-decoded-bytes)
(verify-guards fn-xc-decoded-span-row)
(verify-guards fn-xc-decoded-span-at)
(verify-guards fn-xce-copy)
(verify-guards fn-xc-entry-span-row)
(verify-guards fn-xc-entry-span-at)
