; Bounded persistent updates: one key bit or one copied trie node per action.
(in-package "ACL2")
(include-book "group-number-source")
(local (include-book "arithmetic-5/top" :dir :system))

(defun fn-gns-group-set (group position bit value node)
  (declare (xargs :guard (and (stringp group) (natp position)
                              (<= position (length group)) (natp bit) (< bit 8))
                  :measure (nfix (+ (* 8 (- (length group) (nfix position)))
                                     (- 8 (nfix bit))))))
  (if (not (and (stringp group) (natp position) (<= position (length group))
                (natp bit) (< bit 8))) node
    (if (>= position (length group)) (cons value (fn-ag-cdr node))
      (let ((nextpos (if (= bit 7) (1+ position) position))
            (nextbit (if (= bit 7) 0 (1+ bit))))
        (if (= (fn-gns-bit group position bit) 0)
            (cons (fn-gnix-val node)
                  (cons (fn-gns-group-set group nextpos nextbit value (fn-gnix-zero node))
                        (fn-gnix-one node)))
          (cons (fn-gnix-val node)
                (cons (fn-gnix-zero node)
                      (fn-gns-group-set group nextpos nextbit value (fn-gnix-one node)))))))))

; A frame retains the untouched sibling and old value; older roots are not
; modified. This logical fold is never called by the host update loop.
(defun fn-gns-rebuild (zip node)
  (declare (xargs :guard t))
  (if (consp zip)
      (let* ((f (car zip)) (branch (fn-gns-at 0 f))
             (value (fn-gns-at 1 f)) (sibling (fn-gns-at 2 f)))
        (fn-gns-rebuild (cdr zip)
          (cons value (if (equal branch 0) (cons node sibling) (cons sibling node)))))
    node))

; Fixed11: phase, key kind, key, position, bit, current node, zipper,
; new terminal value, copied nodes, descent frames, allocated trie conses.
(defun fn-gns-update-begin (kind key root value)
  (declare (xargs :guard t))
  (if (or (and (eq kind :group) (stringp key))
          (and (eq kind :number) (posp key)))
      (list :descend kind key 0 0 root nil value 0 0 0)
    (list :refused :number 1 0 0 nil nil nil 0 0 0)))
(defun fn-gns-update-cursorp (c)
  (declare (xargs :guard t))
  (and (true-listp c) (= (len c) 11)
       (member-eq (fn-gns-at 0 c) '(:descend :rebuild :done :refused))
       (or (and (eq (fn-gns-at 1 c) :group) (stringp (fn-gns-at 2 c))
                (natp (fn-gns-at 3 c))
                (<= (fn-gns-at 3 c) (length (fn-gns-at 2 c))))
           (and (eq (fn-gns-at 1 c) :number) (posp (fn-gns-at 2 c))
                (natp (fn-gns-at 3 c))))
       (natp (fn-gns-at 4 c)) (< (fn-gns-at 4 c) 8)
       (true-listp (fn-gns-at 6 c))
       (natp (fn-gns-at 8 c)) (natp (fn-gns-at 9 c)) (natp (fn-gns-at 10 c))
       (implies (eq (fn-gns-at 0 c) :done) (not (fn-gns-at 6 c)))))
(defun fn-gns-update-step (c)
  (declare (xargs :guard (fn-gns-update-cursorp c)))
  (let ((phase (fn-gns-at 0 c)) (kind (fn-gns-at 1 c)) (key (fn-gns-at 2 c))
        (pos (fn-gns-at 3 c)) (bit (fn-gns-at 4 c)) (node (fn-gns-at 5 c))
        (zip (fn-gns-at 6 c)) (value (fn-gns-at 7 c))
        (copied (fn-gns-at 8 c)) (frames (fn-gns-at 9 c)) (cells (fn-gns-at 10 c)))
    (cond
     ((eq phase :descend)
      (if (if (eq kind :group) (>= pos (length key)) (<= key 1))
          (list :rebuild kind key pos bit (cons value (fn-ag-cdr node)) zip value
                (1+ copied) frames (1+ cells))
        (let* ((branch (if (eq kind :group) (fn-gns-bit key pos bit) (mod key 2)))
               (zero (= branch 0)))
          (list :descend kind (if (eq kind :group) key (floor key 2))
                (if (and (eq kind :group) (= bit 7)) (1+ pos) pos)
                (if (eq kind :group) (if (= bit 7) 0 (1+ bit)) bit)
                (if zero (fn-gnix-zero node) (fn-gnix-one node))
                (cons (list branch (fn-gnix-val node)
                            (if zero (fn-gnix-one node) (fn-gnix-zero node))) zip)
                value copied (1+ frames) cells))))
     ((eq phase :rebuild)
      (if (not (consp zip))
          (list :done kind key pos bit node nil value copied frames cells)
        (let* ((f (car zip)) (branch (fn-gns-at 0 f))
               (oldvalue (fn-gns-at 1 f)) (sibling (fn-gns-at 2 f)))
          (list :rebuild kind key pos bit
                (cons oldvalue (if (equal branch 0) (cons node sibling) (cons sibling node)))
                (cdr zip) value (1+ copied) frames (+ 2 cells)))))
     (t c))))
(defun fn-gns-update-result (c)
  (declare (xargs :guard t))
  (if (eq (fn-gns-at 0 c) :done)
      (list :updated (fn-gns-at 5 c) (fn-gns-at 8 c) (fn-gns-at 10 c))
    '(:pending)))
(defun fn-gns-update-denotation (c)
  (declare (xargs :guard (fn-gns-update-cursorp c)))
  (fn-gns-rebuild (fn-gns-at 6 c)
    (if (eq (fn-gns-at 0 c) :descend)
        (if (eq (fn-gns-at 1 c) :group)
            (fn-gns-group-set (fn-gns-at 2 c) (fn-gns-at 3 c) (fn-gns-at 4 c)
                              (fn-gns-at 7 c) (fn-gns-at 5 c))
          (fn-gnix-set (fn-gns-at 2 c) (fn-gns-at 7 c) (fn-gns-at 5 c)))
      (fn-gns-at 5 c))))

(defthm fn-gns-update-begin-cursorp
  (fn-gns-update-cursorp (fn-gns-update-begin kind key root value)))
(defthm fn-gns-update-step-cursorp
  (implies (fn-gns-update-cursorp c)
           (fn-gns-update-cursorp (fn-gns-update-step c))))
(defthm fn-gns-update-step-preserves-denotation
  (implies (fn-gns-update-cursorp c)
           (equal (fn-gns-update-denotation (fn-gns-update-step c))
                  (fn-gns-update-denotation c)))
  :hints (("Goal" :in-theory (enable fn-gns-update-step fn-gns-update-denotation
                                    fn-gns-update-cursorp fn-gnix-set)
           :expand ((fn-gns-group-set (fn-gns-at 2 c) (fn-gns-at 3 c)
                                     (fn-gns-at 4 c) (fn-gns-at 7 c) (fn-gns-at 5 c))
                    (fn-gns-rebuild (fn-gns-at 6 c) (fn-gns-at 5 c))))))

(defthm fn-gns-group-get-of-same-set
  (implies (and (stringp group) (natp pos) (<= pos (length group))
                (natp bit) (< bit 8))
           (equal (fn-gns-group-get group pos bit
                                    (fn-gns-group-set group pos bit value node))
                  value))
  :hints (("Goal" :induct (fn-gns-group-set group pos bit value node))))
(defthm fn-gns-update-step-copy-bound
  (implies (fn-gns-update-cursorp c)
           (and (<= (fn-gns-at 8 c) (fn-gns-at 8 (fn-gns-update-step c)))
                (<= (fn-gns-at 8 (fn-gns-update-step c)) (1+ (fn-gns-at 8 c)))
                (<= (fn-gns-at 10 (fn-gns-update-step c)) (+ 2 (fn-gns-at 10 c)))))
  :hints (("Goal" :in-theory (enable fn-gns-update-step fn-gns-update-cursorp))))
(defthm fn-gns-update-done-is-denotation
  (implies (and (fn-gns-update-cursorp c) (eq (fn-gns-at 0 c) :done)
                (not (fn-gns-at 6 c)))
           (equal (fn-gns-at 5 c) (fn-gns-update-denotation c))))
(defthm fn-gns-update-begin-number-denotation
  (implies (posp n)
           (equal (fn-gns-update-denotation (fn-gns-update-begin :number n root value))
                  (fn-gnix-set n value root)))
  :hints (("Goal" :in-theory (disable fn-gnix-set fn-gns-group-set))))
(defthm fn-gns-update-begin-group-denotation
  (implies (stringp group)
           (equal (fn-gns-update-denotation (fn-gns-update-begin :group group root value))
                  (fn-gns-group-set group 0 0 value root)))
  :hints (("Goal" :in-theory (disable fn-gnix-set fn-gns-group-set))))
