; Actual source/custody composition over the installed all-event backing.
; The owner publisher installs Store/CP/config/source association atomically.
; A shape predicate does not establish that producer invariant or activation.
(in-package "ACL2")
(include-book "history-capture-state")
(include-book "history-event-backing")
(include-book "history-event-directory")
(include-book "runtime-operation-source")

(defun fn-owner-history-publication (state)
 (declare (xargs :stobjs state :guard t))
 (if (boundp-global 'fn-owner-history-publication state)
     (f-get-global 'fn-owner-history-publication state) nil))
; INTERNAL same-publication splice, no supplied descriptor/source setter.
; Caller already published the actual backing in the same Store transaction.
(defun fn-owner-history-install-publication (fn-history-backing state)
 (declare (xargs :stobjs (fn-history-backing state) :guard t))
 (let ((source (fn-hep-current fn-history-backing)))
  (if (not (and (fn-hhc-sourcep source) (posp (fn-hhc-at 2 source))
                (natp (fn-owner-canonical-epoch state))))
      (mv :history-publication-unavailable state)
   (let ((state (f-put-global 'fn-owner-history-publication
                  (list :history-installed (fn-hhc-at 1 source)
                        (fn-hhc-at 2 source) (fn-hhc-at 3 source)
                        (fn-hhc-at 8 source) (fn-owner-canonical-epoch state)) state)))
    (mv :history-publication-installed state)))))
(defun fn-owner-history-source (fn-history-backing state)
 (declare (xargs :stobjs (fn-history-backing state) :guard t))
 (let ((source (fn-hep-current fn-history-backing))
       (parent (fn-owner-history-publication state)))
  (cond ((or (not parent) (not source)) (mv :history-source-unavailable nil))
        ((not (and (fn-hhc-sourcep source) (posp (fn-hhc-at 2 source))
                   (natp (fn-owner-canonical-epoch state)) (fn-hhc-widthp parent 6)
                   (eq (fn-hhc-at 0 parent) :history-installed)
                   (equal (fn-hhc-at 1 parent) (fn-hhc-at 1 source))
                   (equal (fn-hhc-at 2 parent) (fn-hhc-at 2 source))
                   (equal (fn-hhc-at 3 parent) (fn-hhc-at 3 source))
                   (equal (fn-hhc-at 4 parent) (fn-hhc-at 8 source))
                   (equal (fn-hhc-at 5 parent) (fn-owner-canonical-epoch state))))
         (mv :recovery-required nil))
        (t (mv :source source)))))
; Genuine immutable runtime source/table must fund the actual capture row,
; directory continuation, return path and retained frontier before issuance.
; Allowance lowering is absent: a ready source is not an invented vector.
(defun fn-owner-history-capture-demand (kind fn-page-read-pool state)
 (declare (xargs :stobjs (fn-page-read-pool state) :guard t))
 (if (not (member-eq kind '(:remote-poll :remote-reply :checkpoint-history)))
     (mv :invalid-history-capture-kind nil)
  (mv-let (word family)
   (fn-owner-runtime-operation-source kind fn-page-read-pool state)
   (declare (ignore family))
   (if (not (member-eq word '(:ready :runtime-operation-available))) (mv word nil)
    (mv-let (role-word table)
     (fn-owner-runtime-operation-role-table kind fn-page-read-pool state)
     (declare (ignore table))
     (mv (if (member-eq role-word '(:ready :runtime-operation-available))
             :history-capture-allowance-unavailable role-word) nil))))))
(defun fn-owner-history-capture (kind fn-history-backing fn-page-read-pool state)
 (declare (xargs :stobjs (fn-history-backing fn-page-read-pool state) :guard t))
 (if (fn-owner-history-capture-slot state)
     (mv :history-source-busy nil fn-history-backing fn-page-read-pool state)
  (mv-let (word source) (fn-owner-history-source fn-history-backing state)
   (if (not (eq word :source)) (mv word nil fn-history-backing fn-page-read-pool state)
    (mv-let (demand-word demand)
     (fn-owner-history-capture-demand kind fn-page-read-pool state)
     (if (not (eq demand-word :ready))
         (mv demand-word nil fn-history-backing fn-page-read-pool state)
      (mv-let (capture-word descriptor fn-page-read-pool state)
       (fn-owner-history-capture-issued source demand fn-page-read-pool state)
       (if (not (eq capture-word :captured))
           (mv capture-word nil fn-history-backing fn-page-read-pool state)
        (mv-let (pin-word fn-history-backing)
         (fn-hep-capture-retain (fn-hhc-at 1 descriptor) state fn-history-backing)
         (if (not (eq pin-word :retained))
             ; Do not forge a positive capture or refund an ambiguous pin.
             ; The held slot/charge blocks reset until recovery/return joins.
             (mv :recovery-required nil fn-history-backing fn-page-read-pool state)
          (mv :captured descriptor fn-history-backing fn-page-read-pool state)))))))))))
; Terminal return consumes the registered epoch pin while the actual
; quiescent slot/read-NIL authority is still present, then refunds SAME pool.
(defun fn-owner-history-release (token fn-history-backing fn-page-read-pool state)
 (declare (xargs :stobjs (fn-history-backing fn-page-read-pool state) :guard t))
 (mv-let (word fn-history-backing)
  (fn-hep-capture-return token state fn-history-backing)
  (if (not (eq word :returned)) (mv word fn-history-backing fn-page-read-pool state)
   (mv-let (release-word fn-page-read-pool state)
    (fn-owner-history-release-issued token fn-page-read-pool state)
    (mv release-word fn-history-backing fn-page-read-pool state)))))
(defun fn-owner-history-read-slot (state)
 (declare (xargs :stobjs state :guard t))
 (if (boundp-global 'fn-owner-history-read state)
     (f-get-global 'fn-owner-history-read state) nil))
(defun fn-owner-history-read-begin (token ordinal fn-history-backing state)
 (declare (xargs :stobjs (fn-history-backing state) :guard t))
 (if (fn-owner-history-read-slot state) (mv :history-read-busy state)
  (let ((plan (fn-owner-history-read-plan token ordinal state)))
   (if (not (eq (car plan) :read)) (mv (fn-hhc-at 1 plan) state)
    (if (not (fn-hep-capture-livep (fn-hhc-at 1 plan) token fn-history-backing))
        (mv :history-source-stale state)
     (let* ((source (fn-hhc-at 1 plan))
           (child (fn-hed-read-begin (fn-hhc-at 4 source) (fn-hhc-at 6 source) ordinal))
           (state (f-put-global 'fn-owner-history-read
                    (list :history-read-owned token ordinal child :directory) state)))
     (mv :history-read-started state)))))))
; One directory action per call. A physical read uses its separately qualified
; depth+1 envelope, checked before its first nested-stobj access. No native
; root/leaf/slot argument, NIL row is a successful :row result.
(defun fn-owner-history-read-step (fuel fn-history-backing state)
 (declare (xargs :stobjs (fn-history-backing state) :guard t
  :guard-hints (("Goal" :in-theory
    (disable fn-owner-history-read-slot fn-owner-history-read-plan
             fn-hep-capture-livep fn-hed-read-step fn-hep-page-read
             fn-hed-leafp fn-hhc-widthp fn-hhc-at fn-hed-at)))))
 (let* ((r (fn-owner-history-read-slot state))
        (token (fn-hhc-at 1 r)) (ordinal (fn-hhc-at 2 r))
        (child (fn-hhc-at 3 r)) (phase (fn-hhc-at 4 r))
        (plan (fn-owner-history-read-plan token ordinal state)))
  (cond
   ((not (and (fn-hhc-widthp r 5) (eq (fn-hhc-at 0 r) :history-read-owned)
               (natp ordinal) (eq (car plan) :read)
               (fn-hep-capture-livep (fn-hhc-at 1 plan) token fn-history-backing)))
    (mv :history-source-stale nil (nfix fuel) state))
   ((not (natp fuel)) (mv :invalid-history-fuel nil 0 state))
   ((zp fuel) (mv :yield nil fuel state))
   ((eq phase :directory)
    (mv-let (word next leaf) (fn-hed-read-step child)
     (cond
      ((eq word :yield)
       (let ((state (f-put-global 'fn-owner-history-read
                      (list :history-read-owned token ordinal next :directory) state)))
        (mv :yield nil (- fuel 1) state)))
      ((eq word :leaf)
       (let ((state (f-put-global 'fn-owner-history-read
                      (list :history-read-owned token ordinal leaf :page) state)))
        (mv :yield nil (- fuel 1) state)))
      (t (mv word nil (- fuel 1) state)))))
   ((eq phase :page)
    (let* ((source (fn-hhc-at 1 plan)) (base (fn-hhc-at 5 child))
           (frontier (fn-hhc-at 7 source)))
     (if (not (and (fn-hed-leafp child) (natp base)
                   (equal base (* 256 (floor ordinal 256)))
                   (equal (fn-hhc-at 4 child) (fn-hhc-at 2 source))
                   (natp frontier) (< base frontier)))
         (mv :recovery-required nil fuel state)
      (let ((count (min 256 (- frontier base))))
       (mv-let (word row left)
        (fn-hep-page-read source child ordinal count fuel fn-history-backing)
        (if (eq word :row)
         (let ((state (f-put-global 'fn-owner-history-read nil state)))
          (mv :row row left state))
         (mv word nil left state)))))))
   (t (mv :recovery-required nil fuel state)))))
