; Actual retained BEGIN lease and publication readout; no caller source tuple.
(in-package "ACL2")
(include-book "history-semantic-writer")
(include-book "owner-canonical-epoch")
(defun fn-owner-history-writer-gate (token state)
 (declare (xargs :stobjs state :guard t))
 (let ((fault (and (boundp-global 'fn-owner-history-completion-fault state)
                   (f-get-global 'fn-owner-history-completion-fault state)))
       (lease (and (boundp-global 'fn-owner-history-semantic-source state)
                   (f-get-global 'fn-owner-history-semantic-source state)))
       (parent (and (boundp-global 'fn-owner-history-publication state)
                    (f-get-global 'fn-owner-history-publication state))))
  (cond (fault :recovery-required)
        ((not (and (fn-apr-widthp 4 lease)
                    (eq (fn-prl-nth 0 lease) :history-semantic-source)
                    (fn-apr-tokenp token) (fn-apr-tokenp (fn-prl-nth 1 lease))
                    (equal token (fn-prl-nth 1 lease)))) :writer-stale)
        (t (fn-hsw-gate token (fn-apr-owner-current state)
                       (fn-prl-nth 2 lease) parent
                       (fn-owner-canonical-epoch state))))))
