; PRF-1147: actual issued image I/O and fixed-page serialization boundary.
; Runtime definitions are WIP until the narrow guard/source replay below.
(in-package "ACL2")
(include-book "history-image-producer")

(defun fn-hie-currentp (c effect stage ledger)
  (declare (xargs :guard t))
  (let ((pending (fn-omk-at 5 c)))
    (and (fn-omk-widthp effect 10) (fn-omk-widthp pending 10)
         (natp stage) (equal stage (fn-omk-at 3 c))
         (equal effect pending) (fn-hpi-grant-matchesp c ledger))))

; The host receives one exact FD role, offset/count and already-written
; scratch selector. It neither computes page addresses nor maps region labels.
(defun fn-hie-plan (c effect stage ledger)
  (declare (xargs :guard t))
  (let* ((tag (fn-omk-at 0 effect)) (phase (fn-omk-at 0 c))
         (buffer (fn-omk-at 0 (fn-omk-at 17 c))))
    (if (not (fn-hie-currentp c effect stage ledger)) '(:refused :image-effect)
      (cond
       ((and (eq tag :write-page) (eq phase :wait-write)
             (natp buffer) (< buffer 5) (natp (fn-omk-at 7 effect))
             (equal (fn-omk-at 8 effect) 16384))
        (list :io :write :target (fn-omk-at 7 effect) 16384 buffer nil))
       ((and (eq tag :read-stage) (eq phase :wait-stage-read)
             (natp (fn-omk-at 6 effect)) (natp (fn-omk-at 7 effect))
             (< 0 (fn-omk-at 7 effect)) (<= (fn-omk-at 7 effect) 64))
        (list :io :read :target (fn-omk-at 6 effect) (fn-omk-at 7 effect) nil nil))
       ((and (member-eq tag '(:write-spool :read-spool))
             (eq phase (if (eq tag :write-spool) :wait-spool-write :wait-spool-read))
             (member-eq (fn-omk-at 4 effect) '(:data :table))
             (natp (fn-omk-at 6 effect)) (equal (fn-omk-at 7 effect) 32)
             (or (eq tag :read-spool) (fn-hpi-octets-p 32 (fn-omk-at 9 effect))))
        (list :io (if (eq tag :write-spool) :write :read)
              (if (eq (fn-omk-at 4 effect) :data) :data-spool :table-spool)
              (fn-omk-at 6 effect) 32 nil (fn-omk-at 9 effect)))
       (t '(:refused :image-effect-phase))))))

(defun fn-hie-outcome (requested got status)
  (declare (xargs :guard t))
  ; A returned short/error write can have persisted a prefix. It is NEVER
  ; classified as refusal or retried under the same buffer generation.
  (if (and (natp requested) (integerp got) (equal got requested) (eq status :ok))
      :ok :uncertain))

(defun fn-hie-read-count (c effect stage ledger got status)
  (declare (xargs :guard t))
  (let ((plan (fn-hie-plan c effect stage ledger)))
    (if (and (eq (fn-omk-at 0 plan) :io) (eq (fn-omk-at 1 plan) :read)
             (eq (fn-hie-outcome (fn-omk-at 4 plan) got status) :ok))
        (fn-omk-at 4 plan) 0)))

(defun fn-hie-observation (c effect stage ledger got status bytes)
  (declare (xargs :guard t))
  (let* ((plan (fn-hie-plan c effect stage ledger))
         (outcome (fn-hie-outcome (fn-omk-at 4 plan) got status))
         (tag (fn-omk-at 0 effect)))
    ; This function is called after actual syscall return. A lost/stale
    ; authority cannot retroactively establish that IO was not issued.
    (if (not (eq (fn-omk-at 0 plan) :io)) '(:retained :image-effect-observation)
      (cond
       ((eq tag :write-page)
        (list :written (fn-omk-at 1 effect) stage (fn-omk-at 3 effect)
              (fn-omk-at 9 effect) outcome))
       ((eq tag :write-spool)
        (list :spool-written (fn-omk-at 1 effect) stage (fn-omk-at 3 effect)
              (fn-omk-at 4 effect) (fn-omk-at 5 effect) (fn-omk-at 8 effect) outcome))
       (t
        (list (if (eq tag :read-stage) :image-read :spool-read)
              (fn-omk-at 1 effect) stage (fn-omk-at 3 effect)
              (fn-omk-at 4 effect) (fn-omk-at 5 effect) (fn-omk-at 8 effect)
              (if (and (eq outcome :ok) (not (fn-hpi-octets-p (fn-omk-at 4 plan) bytes)))
                  :uncertain outcome)
              bytes))))))

(defun fn-hie-page-byte (c effect stage ledger i fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb)
  (declare (xargs :stobjs (fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb)
                  :guard (and (natp i) (< i 16384))))
  (let* ((plan (fn-hie-plan c effect stage ledger))
         (buffer (fn-omk-at 5 plan)) (word-index (nfix (floor i 8))))
    (if (not (and (eq (fn-omk-at 0 plan) :io)
                  (eq (fn-omk-at 1 plan) :write) (natp buffer) (< buffer 5)
                  (< word-index 2048)))
        (mv :refused 0)
      (mv-let (word w)
        (case buffer (0 (fn-hpb-word word-index fn-hpq0))
                     (1 (fn-hpb-word word-index fn-hpq1))
                     (2 (fn-hpb-word word-index fn-hpq2))
                     (3 (fn-hpb-word word-index fn-hpq3))
                     (otherwise (fn-hpb-word word-index fn-hpb)))
        (if (eq word :word)
            (mv :octet (logand 255 (ash (ifix w) (- (* 8 (mod i 8))))))
          (mv :unwritten 0))))))
