; Distinct typed-C completion and no-append publication. E completion3 and
; its existing register/publish functions remain unchanged.
(in-package "ACL2")
(include-book "history-event-backing")
(include-book "journal-publish")
(include-book "consumer-position")

(defun fn-hcc-turn-tokenp (x)
 (declare (xargs :guard t))
 (and (fn-hed-fixedp x 4) (eq (fn-hed-at 0 x) :account-preparation-turn)
      (natp (fn-hed-at 1 x)) (natp (fn-hed-at 2 x)) (natp (fn-hed-at 3 x))))
(defun fn-hcc-operationp (x)
 (declare (xargs :guard t))
 (and (fn-hed-fixedp x 4) (eq (fn-hed-at 0 x) :account-operation)
      (fn-cp-idp (fn-hed-at 1 x)) (natp (fn-hed-at 2 x)) (natp (fn-hed-at 3 x))))
(defun fn-hcc-coordinatep (x)
 (declare (xargs :guard t))
 (and (fn-hed-fixedp x 4) (eq (fn-hed-at 0 x) :configuration-record)
      (natp (fn-hed-at 1 x)) (natp (fn-hed-at 2 x)) (posp (fn-hed-at 3 x))
      (equal (fn-hed-at 2 x) (1+ (fn-hed-at 1 x)))))
(defun fn-hep-config-completion-matchesp (receipt token fn-history-backing)
 (declare (xargs :stobjs fn-history-backing :guard t :verify-guards nil))
 (let* ((p (fn-hep-producer-receipts fn-history-backing))
        (owner-result (fn-hed-at 6 p)) (expected (fn-hed-at 3 owner-result))
        (journal (fn-hed-at 3 receipt)))
  (and (fn-hed-fixedp receipt 4)
       (eq (fn-hed-at 0 receipt) :history-config-completion)
       (fn-hcc-operationp (fn-hed-at 1 receipt))
       (fn-hcc-coordinatep (fn-hed-at 2 receipt))
       (fn-hed-fixedp journal 3) (fn-jpub-statep journal)
       (eq (fn-jpub-authorityp journal) t)
       (eq (fn-jpub-phase journal) :durable) (eq (fn-jpub-outcome journal) :durable)
       (fn-hcc-turn-tokenp token) (fn-hcc-turn-tokenp (fn-hep-producer-token fn-history-backing))
       (equal token (fn-hep-producer-token fn-history-backing))
       (fn-hed-fixedp p 7) (eq (fn-hed-at 0 p) :history-preparation)
       (fn-hcc-turn-tokenp (fn-hed-at 1 p)) (equal token (fn-hed-at 1 p))
       (equal (fn-hed-at 2 p) (fn-hed-at 3 (fn-hed-at 2 receipt)))
       (eq (fn-hed-at 5 p) :control)
       (fn-hed-fixedp owner-result 10)
       (equal (fn-hed-at 2 token) (fn-hed-at 1 owner-result))
       (fn-hed-fixedp expected 3) (eq (fn-hed-at 0 expected) :history-config-operation)
       (fn-hcc-operationp (fn-hed-at 1 expected))
       (fn-hcc-coordinatep (fn-hed-at 2 expected))
       (equal (fn-hed-at 1 receipt) (fn-hed-at 1 expected))
       (equal (fn-hed-at 2 receipt) (fn-hed-at 2 expected))
       (fn-hep-epoch-livep (fn-hep-current fn-history-backing) fn-history-backing))))

(defun fn-hep-register-config-completion-internal (receipt token fn-history-backing)
 (declare (xargs :stobjs fn-history-backing :guard t :verify-guards nil))
 (cond
  ((not (fn-hep-config-completion-matchesp receipt token fn-history-backing))
   (mv :unavailable fn-history-backing))
  ((and (member-eq (fn-hep-producer-phase fn-history-backing) '(:completed :published))
         (equal receipt (fn-hep-completion fn-history-backing)))
   (mv :already-completed fn-history-backing))
  ((not (eq (fn-hep-producer-phase fn-history-backing) :prepared))
   (mv :unavailable fn-history-backing))
  (t
   (let* ((fn-history-backing (update-fn-hep-completion receipt fn-history-backing))
          (fn-history-backing (update-fn-hep-producer-phase :completed fn-history-backing)))
    (mv :completed fn-history-backing)))))

(defun fn-hep-publish-config-current (receipt fn-history-backing)
 (declare (xargs :stobjs fn-history-backing :guard t :verify-guards nil))
 (let* ((p (fn-hep-producer-receipts fn-history-backing))
        (next (fn-hed-at 3 p)) (old (fn-hep-current fn-history-backing)))
  (cond
   ((not (and (fn-hep-config-completion-matchesp receipt
                 (fn-hep-producer-token fn-history-backing) fn-history-backing)
               (equal receipt (fn-hep-completion fn-history-backing))))
    (mv :unavailable fn-history-backing))
   ((eq (fn-hep-producer-phase fn-history-backing) :published)
    (mv :consumed fn-history-backing))
   ((not (and (eq (fn-hep-producer-phase fn-history-backing) :completed)
               (fn-hep-sourcep next) (fn-hep-sourcep old)
               (equal (fn-hed-at 1 next) (fn-hed-at 1 (fn-hep-producer-token fn-history-backing)))
               (equal (fn-hed-at 8 next) (fn-hed-at 1 (fn-hep-producer-token fn-history-backing)))
               (equal (fn-hed-at 2 next) (fn-hed-at 2 old))
               (equal (fn-hed-at 3 next) (fn-hed-at 3 old))
               (equal (fn-hed-at 7 next) (fn-hed-at 7 old))))
    (mv :unavailable fn-history-backing))
   (t
    ; Preserve actual immutable physical backing fields by pointer. No whole
    ; forest comparison, E append, page mutation or fabricated dense count.
    (let* ((installed (list :history-source (fn-hed-at 1 next)
                            (fn-hed-at 2 old) (fn-hed-at 3 old) (fn-hed-at 4 old)
                            (fn-hed-at 5 old) (fn-hed-at 6 old) (fn-hed-at 7 old)
                            (fn-hed-at 8 next)))
           (fn-history-backing (update-fn-hep-installed-source installed fn-history-backing))
           (fn-history-backing (update-fn-hep-producer-phase :published fn-history-backing)))
     (mv :published fn-history-backing))))))
