; Allocation demand for the live P3 root candidate. Encoder length is counted
; without materializing its octets; a page grow is funded before the flat
; resize. The permanent generation grant survives publication completion.
(in-package "ACL2")
(include-book "history-image-row-step")
(include-book "memory-credits")
(include-book "history-paged-adopt")
(local (include-book "arithmetic/top" :dir :system))

(defun fn-hroot-nat-octets (n)
  (declare (xargs :guard (natp n)))
  (+ 1 (ceiling (integer-length n) 8)))
(defun fn-hroot-string-octets (s)
  (declare (xargs :guard (stringp s)))
  (+ (fn-hroot-nat-octets (length s)) (length s)))
(defun fn-hroot-tree-octets (x)
  (declare (xargs :guard t))
  (cond ((fn-scc-octets-valuep x) (+ 1 (fn-hroot-nat-octets (len x)) (len x)))
        ((consp x) (+ 1 (fn-hroot-tree-octets (car x)) (fn-hroot-tree-octets (cdr x))))
        ((null x) 1)
        ((natp x) (+ 1 (fn-hroot-nat-octets x)))
        ((integerp x) (+ 1 (fn-hroot-nat-octets (- -1 x))))
        ((characterp x) 2)
        ((stringp x) (+ 1 (fn-hroot-string-octets x)))
        ((symbolp x) (+ 2 (fn-hroot-string-octets (symbol-name x))))
        (t 1)))

(defun fn-hroot-page-octets (np)
  (declare (xargs :guard (natp np)))
  (+ (* 8 (+ (* 2048 np) (* 2 np) (pgs-ntables np))) 512))
(defun fn-hroot-memory-octets (fn-hrecs$c)
  (declare (xargs :stobjs fn-hrecs$c))
  (stobj-let ((pgs-mem (fn-hrc-pgs fn-hrecs$c)))
             (n)
             (* 8 (+ (pgs-w-length pgs-mem) (pgs-m-length pgs-mem)
                     (pgs-t-length pgs-mem) (pgs-d-length pgs-mem)
                     (pgs-v-length pgs-mem) (pgs-tv-length pgs-mem)))
             (+ n (* 8 (fn-hrc-sfx-length fn-hrecs$c)) 4096)))
(defun fn-hroot-retain-demand (fn-hrecs$c)
  (declare (xargs :stobjs fn-hrecs$c :guard (fn-hrc-wfp fn-hrecs$c)))
  (+ (fn-hroot-memory-octets fn-hrecs$c) (* 64 (fn-hrc-count fn-hrecs$c))))
(defun fn-hroot-event-demand (ev ordinal fn-hrecs$c)
  (declare (xargs :stobjs fn-hrecs$c :guard (natp ordinal)))
  (+ (fn-hroot-memory-octets fn-hrecs$c) (* 64 (+ 1 ordinal))
     (* 96 (+ 8 (fn-hroot-tree-octets ev)))
     (fn-hroot-page-octets 1)))
(defun fn-hroot-grow-demand (cursor ordinal fn-hrecs$c)
  (declare (xargs :stobjs fn-hrecs$c
                  :guard (and (fn-hpr-cursorp cursor) (natp ordinal)
                              (fn-hrc-wfp fn-hrecs$c)
                              (< (fn-hrc-lo fn-hrecs$c) (fn-hrc-hi fn-hrecs$c)))
                  :verify-guards nil))
  (+ (fn-hroot-memory-octets fn-hrecs$c) (* 64 (+ 1 ordinal))
     (fn-hroot-page-octets (cadr (fn-hpr-final-placement cursor)))
     (* 96 (+ 8 (fn-hroot-tree-octets (fn-hrc-sfxi (fn-hrc-lo fn-hrecs$c) fn-hrecs$c))))))
(defun fn-hroot-credit-key (generation)
  (declare (xargs :guard (posp generation)))
  (cons :history-root generation))

(defun fn-hroot-tail-demand (ev ordinal fn-hist$p)
  (declare (xargs :stobjs fn-hist$p :guard (natp ordinal)))
  (stobj-let ((fn-hrecs$c (fn-hist$p-root fn-hist$p)))
             (amount)
             (+ (* 2 (fn-hroot-memory-octets fn-hrecs$c))
                (* 64 (+ 1 ordinal)) (* 96 (+ 8 (fn-hroot-tree-octets ev))))
             amount))

; The stored SCC length cell is scalar metadata. Read it before decoding the
; event, so the consumer can fund its temporary words/octets/tree allocation.
(defun fn-hroot-read-demand (ordinal retained fn-hist$p)
  (declare (xargs :stobjs fn-hist$p
                  :guard (and (natp ordinal) (natp retained)
                              (fn-hist$p-wfp fn-hist$p))
                  :verify-guards nil))
  (stobj-let ((fn-hrecs$c (fn-hist$p-root fn-hist$p)))
             (verdict amount)
             (if (< ordinal (fn-hrc-nimg fn-hrecs$c))
                 (stobj-let ((pgs-mem (fn-hrc-pgs fn-hrecs$c)))
                            (v n)
                            (fn-hp-x-cell 1 ordinal (fn-hrc-starts fn-hrecs$c) pgs-mem)
                            (mv v (+ retained 512 (* 96 (nfix n)))))
               (mv :ok (+ retained 64)))
             (mv verdict amount)))
(defun fn-hroot-index-demand (ordinal fn-hist$p)
  (declare (xargs :stobjs fn-hist$p
                  :guard (and (natp ordinal) (fn-hist$p-wfp fn-hist$p))
                  :verify-guards nil))
  (stobj-let ((fn-hrecs$c (fn-hist$p-root fn-hist$p)))
             (retained)
             (fn-hroot-retain-demand fn-hrecs$c)
             (fn-hroot-read-demand ordinal retained fn-hist$p)))

(defun fn-hroot-root-retain-demand (fn-hist$p)
  (declare (xargs :stobjs fn-hist$p :guard (fn-hist$p-wfp fn-hist$p)
                  :verify-guards nil))
  (stobj-let ((fn-hrecs$c (fn-hist$p-root fn-hist$p)))
             (amount) (fn-hroot-retain-demand fn-hrecs$c) amount))

(defthm fn-hroot-memory-natural
 (natp (fn-hroot-memory-octets c))
 :rule-classes :type-prescription
 :hints (("Goal" :in-theory (enable fn-hroot-memory-octets))))
(defthm fn-hroot-retain-natural
 (implies (and (fn-hrecs$cp c) (fn-hrc-wfp c)) (natp (fn-hroot-retain-demand c)))
 :rule-classes :type-prescription
 :hints (("Goal" :in-theory (e/d (fn-hroot-retain-demand fn-hrc-count fn-hrc-wfp)
                            (fn-hroot-memory-octets fn-hrecs$cp fn-hrc-fields fn-hrc-updaters)))))
(verify-guards fn-hroot-grow-demand
 :hints (("Goal" :in-theory (e/d (fn-hrc-wfp)
 (fn-hrc-fields fn-hrc-updaters fn-hrecs$cp fn-hpr-final-placement fn-hpr-cursorp fn-hroot-memory-octets fn-hroot-tree-octets)))))
(verify-guards fn-hroot-read-demand
 :hints (("Goal" :in-theory (e/d (fn-hist$p-wfp fn-hrc-wfp fn-hp-starts-okp)
 (fn-hist$p-root-ready fn-hrc-fields fn-hrc-updaters fn-hrecs$cp fn-hist$pp fn-hp-x-cell)))))
(verify-guards fn-hroot-index-demand
 :hints (("Goal" :use ((:instance fn-hist$p-root-is-physical (p fn-hist$p))
                      (:instance fn-hroot-retain-natural (c (fn-hist$p-root fn-hist$p))))
 :in-theory (e/d (fn-hist$p-wfp)
 (fn-hist$pp fn-hrecs$cp fn-hrc-wfp fn-hist$p-root-ready fn-hroot-retain-demand fn-hroot-read-demand)))))
(verify-guards fn-hroot-root-retain-demand
 :hints (("Goal" :in-theory (e/d (fn-hist$p-wfp)
 (fn-hrc-wfp fn-hist$p-root-ready fn-hroot-retain-demand)))))
