; Persistent all-event directory. Kernels inspect one fixed record/forest cell
; per call. Whole-tree flattening below is a proof model, never a served guard.
; Constructor funding and registered page/epoch custody are separate producers.
(in-package "ACL2")
(local (include-book "arithmetic-5/top" :dir :system))
(defun fn-hed-at (n x)
 (declare (xargs :guard (natp n)))
 (if (consp x) (if (zp n) (car x) (fn-hed-at (1- n) (cdr x))) nil))
(defun fn-hed-fixedp (x n)
 (declare (xargs :guard (natp n)))
 (if (zp n) (null x)
  (and (consp x) (fn-hed-fixedp (cdr x) (1- n)))))
(defun fn-hed-leafp (x)
 (declare (xargs :guard t))
 (and (fn-hed-fixedp x 6) (eq (fn-hed-at 0 x) :history-leaf)
      (natp (fn-hed-at 1 x)) (posp (fn-hed-at 2 x))
      (natp (fn-hed-at 3 x)) (posp (fn-hed-at 4 x)) (natp (fn-hed-at 5 x))))
(defun fn-hed-blockp (x)
 (declare (xargs :guard t))
 (and (fn-hed-fixedp x 4) (eq (fn-hed-at 0 x) :history-block)
      (posp (fn-hed-at 1 x)) (natp (fn-hed-at 2 x))))
(defun fn-hed-branchp (x)
 (declare (xargs :guard t))
 (and (fn-hed-fixedp x 3) (eq (fn-hed-at 0 x) :history-branch)))
; Grow7: tag,phase,carry-block,remaining-forest,next-pagecount,maxheight,result.
(defun fn-hed-grow-begin (forest pagecount maxheight leaf)
 (declare (xargs :guard t))
 (if (and (natp pagecount) (natp maxheight) (fn-hed-leafp leaf))
  (list :history-grow :carry (list :history-block 1 0 leaf) forest
        (+ 1 pagecount) maxheight nil)
  (list :history-grow :recovery-required nil forest (nfix pagecount) (nfix maxheight) nil)))
(defun fn-hed-grow-step (cursor)
 (declare (xargs :guard t))
 (if (not (and (fn-hed-fixedp cursor 7)
               (eq (fn-hed-at 0 cursor) :history-grow)
               (eq (fn-hed-at 1 cursor) :carry))) cursor
  (let* ((carry (fn-hed-at 2 cursor)) (rest (fn-hed-at 3 cursor))
         (count (fn-hed-at 4 cursor)) (maximum (fn-hed-at 5 cursor))
         (width (fn-hed-at 1 carry)) (height (fn-hed-at 2 carry)))
   (cond
    ((not (and (fn-hed-blockp carry) (natp count) (natp maximum)
                (or (null rest) (and (consp rest) (fn-hed-blockp (car rest))
                                    (<= width (fn-hed-at 1 (car rest)))))))
     (list :history-grow :recovery-required carry rest count maximum nil))
    ((and (consp rest) (equal width (fn-hed-at 1 (car rest))))
     (let ((nextheight (+ height 1)))
      (list :history-grow :carry
       (list :history-block (+ width width) nextheight
             (list :history-branch (fn-hed-at 3 (car rest)) (fn-hed-at 3 carry)))
       (cdr rest) count (if (< maximum nextheight) nextheight maximum) nil)))
    (t (list :history-grow :done carry rest count maximum
             (cons (list :history-block width height (fn-hed-at 3 carry)) rest)))))))
; Read8: tag,phase,forest,tree,width,offset,pageindex,ordinal. In forest phase,
; OFFSET is from newest end; in tree phase it is chronological within the block.
(defun fn-hed-read-begin (forest pagecount ordinal)
 (declare (xargs :guard t))
 (if (and (natp pagecount) (natp ordinal))
  (let ((pageindex (floor ordinal 256)))
   (if (< pageindex pagecount)
    (list :history-read :forest forest nil 0 (- (- pagecount 1) pageindex) pageindex ordinal)
    (list :history-read :range forest nil 0 0 pageindex ordinal)))
  (list :history-read :range forest nil 0 0 0 ordinal)))
(defun fn-hed-read-step (cursor)
 (declare (xargs :guard t))
 (if (not (and (fn-hed-fixedp cursor 8) (eq (fn-hed-at 0 cursor) :history-read)))
  (mv :recovery-required cursor nil)
  (let ((phase (fn-hed-at 1 cursor)) (forest (fn-hed-at 2 cursor))
        (tree (fn-hed-at 3 cursor)) (width (fn-hed-at 4 cursor))
        (offset (fn-hed-at 5 cursor)) (pageindex (fn-hed-at 6 cursor))
        (ordinal (fn-hed-at 7 cursor)))
   (cond
    ((eq phase :range) (mv :range cursor nil))
    ((eq phase :forest)
     (if (not (and (consp forest) (fn-hed-blockp (car forest)) (natp offset)))
      (mv :recovery-required cursor nil)
      (let ((blockwidth (fn-hed-at 1 (car forest))))
       (if (<= blockwidth offset)
        (mv :yield (list :history-read :forest (cdr forest) nil 0
                         (- offset blockwidth) pageindex ordinal) nil)
        (mv :yield (list :history-read :tree nil (fn-hed-at 3 (car forest)) blockwidth
                         (- (- blockwidth 1) offset) pageindex ordinal) nil)))))
    ((member-eq phase '(:tree :leaf))
     (cond
      ((not (and (posp width) (natp offset) (< offset width)))
       (mv :recovery-required cursor nil))
      ((equal width 1)
       (if (fn-hed-leafp tree)
        (mv :leaf (list :history-read :leaf nil tree width offset pageindex ordinal) tree)
        (mv :recovery-required cursor nil)))
      ((not (and (evenp width) (fn-hed-branchp tree)))
       (mv :recovery-required cursor nil))
      (t (let ((half (floor width 2)))
          (if (< offset half)
           (mv :yield (list :history-read :tree nil (fn-hed-at 1 tree) half
                            offset pageindex ordinal) nil)
           (mv :yield (list :history-read :tree nil (fn-hed-at 2 tree) half
                            (- offset half) pageindex ordinal) nil))))))
    (t (mv :recovery-required cursor nil))))))
; Logical chronological page-descriptor abstraction only.
(defun fn-hed-tree-flat (tree)
 (declare (xargs :guard t))
 (cond ((and (consp tree) (eq (car tree) :history-leaf)) (list tree))
       ((and (consp tree) (eq (car tree) :history-branch)
             (consp (cdr tree)) (consp (cddr tree)))
        (append (fn-hed-tree-flat (cadr tree)) (fn-hed-tree-flat (caddr tree))))
       (t nil)))
(defun fn-hed-forest-flat (forest)
 (declare (xargs :guard t))
 (if (consp forest)
  (append (fn-hed-forest-flat (cdr forest)) (fn-hed-tree-flat (fn-hed-at 3 (car forest)))) nil))
(defun fn-hed-grow-alpha (cursor)
 (declare (xargs :guard t))
 (if (eq (fn-hed-at 1 cursor) :done) (fn-hed-forest-flat (fn-hed-at 6 cursor))
  (append (fn-hed-forest-flat (fn-hed-at 3 cursor))
          (fn-hed-tree-flat (fn-hed-at 3 (fn-hed-at 2 cursor))))))
(defthm fn-hed-grow-step-preserves-chronological-prefix
 (implies (and (fn-hed-fixedp cursor 7) (eq (fn-hed-at 0 cursor) :history-grow))
  (equal (fn-hed-grow-alpha (fn-hed-grow-step cursor)) (fn-hed-grow-alpha cursor)))
 :rule-classes nil
 :hints (("Goal" :in-theory (enable fn-hed-grow-alpha fn-hed-grow-step fn-hed-at))))
(defthm fn-hed-grow-begin-is-one-chronological-page
 (implies (and (natp pagecount) (natp maxheight) (fn-hed-leafp leaf))
  (equal (fn-hed-grow-alpha (fn-hed-grow-begin forest pagecount maxheight leaf))
         (append (fn-hed-forest-flat forest) (list leaf))))
 :rule-classes nil)
