; Scalar captured-source bridge for the actual authenticated byte provider.
; Capture lineage and physical pin admission remain caller correspondences.
(in-package "ACL2")
(include-book "history-auth-reader")
(include-book "snapshot-source-token")

(defun fn-hsr-source-begin (root source root-ticket lease)
  (declare (xargs :guard t))
  (if (not (and (fn-omk-tokenp source) (natp root-ticket)))
      (mv '(:refused :source-shape) nil nil)
    (mv-let (verdict c)
      (fn-hsr-auth-begin root root-ticket (fn-omk-at 0 source)
                         (fn-omk-at 1 source) lease)
      (mv verdict c (if (equal verdict :idle)
                        (list :hsr-source source root-ticket) nil)))))

(defun fn-hsr-source-boundp (binding c)
  (declare (xargs :guard t))
  (let* ((source (fn-omk-at 1 binding)) (io (fn-hsr-field 1 c))
         (capture (fn-hsr-field 6 io)))
    (and (fn-omk-widthp binding 3) (equal (fn-omk-at 0 binding) :hsr-source)
         (fn-omk-tokenp source) (natp (fn-omk-at 2 binding))
         (fn-hsr-auth-shapep c)
         (equal (fn-omk-at 2 binding) (fn-hsr-field 1 io))
         (equal (fn-omk-at 0 source) (fn-hsr-field 2 io))
         (fn-omk-widthp capture 2)
         (equal (fn-omk-at 0 (fn-omk-at 1 source)) (fn-omk-at 0 capture))
         (equal (fn-omk-at 1 (fn-omk-at 1 source)) (fn-omk-at 1 capture)))))

(defun fn-hsr-source-verified-byte (demand binding root-ticket c)
  (declare (xargs :guard t))
  (let ((offset (fn-omk-at 5 demand)))
    (if (not (and (fn-omk-widthp demand 6)
                  (equal (fn-omk-at 0 demand) :need-byte)
                  (fn-hsr-source-boundp binding c)
                  (natp root-ticket) (equal root-ticket (fn-omk-at 2 binding))
                  (fn-omk-token-matchp (fn-omk-at 1 demand) (fn-omk-at 1 binding))
                  (member-eq (fn-omk-at 2 demand) '(:cells :decode :padding :key
                    :octet-nil :symbol-normalize :span-body :opaque-span :mid-character)) (natp (fn-omk-at 3 demand))
                  (equal (fn-omk-at 4 demand) (fn-hsr-field 3 c))
                  (fn-hsr-auth-verified-byte-demand offset c)))
        '(:refused :source-byte)
      (list :ready (fn-hsr-auth-verified-byte-demand offset c)
            (list :byte (fn-omk-at 1 demand) (fn-omk-at 2 demand)
                  (fn-omk-at 3 demand) (fn-omk-at 4 demand) offset)))))

(defun fn-hsr-source-bind (source root-ticket c)
  (declare (xargs :guard t))
  (let ((binding (list :hsr-source source root-ticket)))
    (if (fn-hsr-source-boundp binding c) binding nil)))

(defun fn-hsr-source-byte-complete (skeleton byte)
  (declare (xargs :guard t))
  (if (and (fn-omk-widthp skeleton 6) (equal (fn-omk-at 0 skeleton) :byte)
           (unsigned-byte-p 8 byte))
      (list :byte (fn-omk-at 1 skeleton) (fn-omk-at 2 skeleton)
            (fn-omk-at 3 skeleton) (fn-omk-at 4 skeleton)
            (fn-omk-at 5 skeleton) byte)
    '(:refused :byte-observation)))

(defun fn-hsr-source-action (demand binding root-ticket c)
  (declare (xargs :guard t))
  (if (not (and (fn-omk-widthp demand 6) (equal (fn-omk-at 0 demand) :need-byte)
                (fn-hsr-source-boundp binding c)
                (equal root-ticket (fn-omk-at 2 binding))
                (fn-omk-token-matchp (fn-omk-at 1 demand) (fn-omk-at 1 binding))
                (member-eq (fn-omk-at 2 demand) '(:cells :decode :padding :key
                    :octet-nil :symbol-normalize :span-body :opaque-span :mid-character)) (natp (fn-omk-at 3 demand))
                (natp (fn-omk-at 4 demand)) (natp (fn-omk-at 5 demand))
                (< (fn-omk-at 5 demand) 16384)))
      '(:refused :source-demand)
    (case (fn-hsr-field 0 c)
      (:idle (list :select (fn-omk-at 4 demand)))
      (:verified (if (equal (fn-omk-at 4 demand) (fn-hsr-field 3 c))
                     (fn-hsr-source-verified-byte demand binding root-ticket c)
                   (list :release (fn-hsr-field 5 (fn-hsr-field 1 c)))))
      (:release (list :release (fn-hsr-field 5 (fn-hsr-field 1 c))))
      (:need-read '(:request))
      (:byte (list :feed (fn-hsr-auth-byte-demand c)))
      (:digest '(:digest))
      (:waiting '(:waiting))
      (otherwise (list :terminal (fn-hsr-field 17 c))))))

(defun fn-hsr-source-cancel-returned (outcome c)
  ; Caller has definitely returned/joined the executing source action.
  (declare (xargs :guard t))
  (mv-let (verdict next) (fn-hsr-auth-cancel c)
    (if (equal (fn-hsr-field 0 next) :waiting)
        (fn-hsr-auth-joined-failure (fn-hsr-field 4 (fn-hsr-field 1 next)) outcome next)
      (mv verdict next))))

(defun fn-hsr-source-settle-demand (buffer-id c)
  (declare (xargs :guard t))
  (let ((io (fn-hsr-field 1 c)))
    (cond ((not (and (fn-hsr-auth-shapep c)
                     (not (equal (fn-hsr-field 0 io) :waiting))
                     (not (fn-hsr-field 4 io))))
           '(:retained :pending-source))
          ((and (member-eq (fn-hsr-field 0 c) '(:release :verified :refused :uncertain))
                (natp buffer-id) (equal buffer-id (fn-hsr-field 5 io)))
           (list :settle buffer-id))
          ((and (member-eq (fn-hsr-field 0 c) '(:idle :refused :uncertain))
                (null buffer-id) (null (fn-hsr-field 5 io)))
           '(:closed))
          (t '(:retained :buffer-binding)))))

(defthm fn-hsr-source-verified-byte-unfolds
  (implies (equal (car (fn-hsr-source-verified-byte demand binding root-ticket c)) :ready)
           (and (fn-hsr-source-boundp binding c)
                (equal (cadr (fn-hsr-source-verified-byte demand binding root-ticket c))
                       (fn-hsr-auth-verified-byte-demand (fn-omk-at 5 demand) c))
                (equal (caddr (fn-hsr-source-verified-byte demand binding root-ticket c))
                       (list :byte (fn-omk-at 1 demand) (fn-omk-at 2 demand)
                             (fn-omk-at 3 demand) (fn-omk-at 4 demand)
                             (fn-omk-at 5 demand)))))
  :rule-classes nil
  :hints (("Goal" :in-theory
           (union-theories (theory 'minimal-theory) '(fn-hsr-source-verified-byte car-cons cdr-cons)))))

(in-theory (disable fn-hsr-source-begin fn-hsr-source-boundp
                    fn-hsr-source-verified-byte fn-hsr-source-bind
                    fn-hsr-source-byte-complete fn-hsr-source-action
                    fn-hsr-source-cancel-returned fn-hsr-source-settle-demand))
