; GENERATED by tools/extract/world.py from
;   host/native/build.lisp
; the image's certified books, in its order, then the books its host files
; include, the host :program books last (their wrapper defuns are admitted
; unverified; an extracted guard-verified alias must come first).
; Do not edit; regenerate.  The script includes this book first
; and then turns the compiler off, so each compiled file of the image loads
; once: a top-level include-book reloads its whole closure, and every load
; of a constrained stub takes a TLS index SBCL never frees (world.py).
; It is the thin end of a chain of 3 links (world.py CHAIN): the slices
; of the include lines are books/image-world-part-1 .. -part-3, in this order.
(in-package "ACL2")
(include-book "image-world-part-3")
