; Actual bounded registry lookup/operations for connection-held publications.
; Allocation/admission and selected-owner-view correspondence are supplied by
; the composed open producer; none follows from these internal segment calls.
(in-package "ACL2")
(include-book "index-backing-generations")
(include-book "connection-receiver-source")
(defun fn-ibp-node-connection-read (token fuel slot depth fn-ibp-node)
 (declare (xargs :stobjs fn-ibp-node :guard (and (natp fuel) (natp slot) (natp depth))
                 :measure (nfix depth) :verify-guards nil))
 (cond ((zp fuel) (mv :yield nil fuel))
       ((zp depth)
        (if (not (and (zp slot) (fn-ibp-node-children-boundp 'fn-ibp-connection-segment fn-ibp-node)))
            (mv :unavailable nil fuel)
          (stobj-let ((fn-ibp-connection-segment
                       (fn-ibp-node-children-get 'fn-ibp-connection-segment fn-ibp-node
                                                (create-fn-ibp-connection-segment))))
            (row)
            (fn-ich-row token fn-ibp-connection-segment)
            (mv (if row :present :stale) row (- fuel 1)))))
       ((evenp slot)
        (if (not (fn-ibp-node-children-boundp 'fn-ibp-node-left fn-ibp-node))
            (mv :unavailable nil fuel)
          (stobj-let ((fn-ibp-node-left
                       (fn-ibp-node-children-get 'fn-ibp-node-left fn-ibp-node
                                                (create-fn-ibp-node-left))))
            (status row fuel-left)
            (fn-ibp-node-connection-read token (- fuel 1) (floor slot 2) (- depth 1) fn-ibp-node-left)
            (mv status row fuel-left))))       (t
        (if (not (fn-ibp-node-children-boundp 'fn-ibp-node-right fn-ibp-node))
            (mv :unavailable nil fuel)
          (stobj-let ((fn-ibp-node-right
                       (fn-ibp-node-children-get 'fn-ibp-node-right fn-ibp-node
                                                (create-fn-ibp-node-right))))
            (status row fuel-left)
            (fn-ibp-node-connection-read token (- fuel 1) (floor slot 2) (- depth 1) fn-ibp-node-right)
            (mv status row fuel-left))))))
(verify-guards fn-ibp-node-connection-read)

(defun fn-ibp-connection-read (token fuel fn-index-backing)
 (declare (xargs :stobjs fn-index-backing :guard (natp fuel)))
 (if (not (fn-ich-tokenp token)) (mv :stale nil fuel)
  (let ((depth (fn-ibp-slot-depth fn-index-backing)))
   (if (<= fuel depth) (mv :yield nil fuel)
    (stobj-let ((fn-ibp-node (fn-ibp-registry fn-index-backing)))
     (status row left)
     (fn-ibp-node-connection-read token fuel (- (fn-omk-at 2 token) 1) depth fn-ibp-node)
     (mv status row left))))))

(defun fn-mio-connection-source (id token fuel fn-mio$c)
 (declare (xargs :stobjs fn-mio$c :guard (natp fuel)))
 (stobj-let ((fn-index-backing (fn-mio$c-provider fn-mio$c)))
  (status pin left)
  (mv-let (word row left) (fn-ibp-connection-read token fuel fn-index-backing)
   (if (not (eq word :present)) (mv word nil left)
    (mv-let (status pin) (fn-ich-row-source id row)
     (mv status pin left))))
  (mv status pin left)))

(defun fn-ich-event (token operation id value fn-ibp-connection-segment)
 (declare (xargs :stobjs fn-ibp-connection-segment :guard t))
 (case operation
  (:rx-revoke (mv-let (word fn-ibp-connection-segment)
              (fn-ich-rx-revoke id token fn-ibp-connection-segment)
              (mv word nil fn-ibp-connection-segment)))
  (:rx-origin (mv-let (word origin)
              (fn-ich-rx-origin id token fn-ibp-connection-segment)
              (mv word origin fn-ibp-connection-segment)))
  (:rx-bind (mv-let (word fn-ibp-connection-segment)
            (fn-ich-rx-bind id token value fn-ibp-connection-segment)
            (mv word nil fn-ibp-connection-segment)))
  (:reserve (mv-let (word fn-ibp-connection-segment)
             (fn-ich-reserve token id value fn-ibp-connection-segment)
             (mv word nil fn-ibp-connection-segment)))
  (:attach (mv-let (word fn-ibp-connection-segment)
             (fn-ich-attach token value fn-ibp-connection-segment)
             (mv word nil fn-ibp-connection-segment)))
  (:close (mv-let (word fn-ibp-connection-segment)
             (fn-ich-close id token fn-ibp-connection-segment)
             (mv word nil fn-ibp-connection-segment)))
  ((:acquire :return)
   (mv-let (word fn-ibp-connection-segment)
    (fn-ich-alias token operation fn-ibp-connection-segment)
    (mv word nil fn-ibp-connection-segment)))
  (:release (fn-ich-release-finish token fn-ibp-connection-segment))
  (otherwise (mv :refused nil fn-ibp-connection-segment))))

(defun fn-ibp-node-connection-event (token operation id value fuel slot depth fn-ibp-node)
 (declare (xargs :stobjs fn-ibp-node :guard (and (natp fuel) (natp slot) (natp depth))
                 :measure (nfix depth) :verify-guards nil))
 (cond ((zp fuel) (mv :yield nil fuel fn-ibp-node))
       ((zp depth)
        (if (not (and (zp slot) (fn-ibp-node-children-boundp 'fn-ibp-connection-segment fn-ibp-node)))
            (mv :unavailable nil fuel fn-ibp-node)
          (stobj-let ((fn-ibp-connection-segment
                       (fn-ibp-node-children-get 'fn-ibp-connection-segment fn-ibp-node
                                                (create-fn-ibp-connection-segment))))
            (status payload fn-ibp-connection-segment)
            (fn-ich-event token operation id value fn-ibp-connection-segment)
            (mv status payload (- fuel 1) fn-ibp-node))))
       ((evenp slot)
        (if (not (fn-ibp-node-children-boundp 'fn-ibp-node-left fn-ibp-node))
            (mv :unavailable nil fuel fn-ibp-node)
          (stobj-let ((fn-ibp-node-left
                       (fn-ibp-node-children-get 'fn-ibp-node-left fn-ibp-node
                                                (create-fn-ibp-node-left))))
            (status payload left fn-ibp-node-left)
            (fn-ibp-node-connection-event token operation id value (- fuel 1)
              (floor slot 2) (- depth 1) fn-ibp-node-left)
            (mv status payload left fn-ibp-node))))
       (t
        (if (not (fn-ibp-node-children-boundp 'fn-ibp-node-right fn-ibp-node))
            (mv :unavailable nil fuel fn-ibp-node)
          (stobj-let ((fn-ibp-node-right
                       (fn-ibp-node-children-get 'fn-ibp-node-right fn-ibp-node
                                                (create-fn-ibp-node-right))))
            (status payload left fn-ibp-node-right)
            (fn-ibp-node-connection-event token operation id value (- fuel 1)
              (floor slot 2) (- depth 1) fn-ibp-node-right)
            (mv status payload left fn-ibp-node))))
 ))
(verify-guards fn-ibp-node-connection-event)
(defun fn-ibp-connection-event (token operation id value fuel fn-index-backing)
 (declare (xargs :stobjs fn-index-backing :guard (natp fuel)))
 (if (not (fn-ich-tokenp token)) (mv :stale nil fuel fn-index-backing)
  (let ((depth (fn-ibp-slot-depth fn-index-backing)))
   (if (<= fuel depth) (mv :yield nil fuel fn-index-backing)
    (stobj-let ((fn-ibp-node (fn-ibp-registry fn-index-backing)))
     (status payload left fn-ibp-node)
     (fn-ibp-node-connection-event token operation id value fuel
       (- (fn-omk-at 2 token) 1) depth fn-ibp-node)
     (mv status payload left fn-index-backing))))))

(defun fn-mio-connection-event (token operation id value fuel fn-mio$c)
 (declare (xargs :stobjs fn-mio$c :guard (natp fuel)))
 (stobj-let ((fn-index-backing (fn-mio$c-provider fn-mio$c)))
  (status payload left fn-index-backing)
  (fn-ibp-connection-event token operation id value fuel fn-index-backing)
  (mv status payload left fn-mio$c)))

; Slot settlement follows actual generation reference settlement, never a
; host assertion that close/STOPPING has joined. Preflight funds all traversals
; before either mutation; a failed late substep remains a recovery event.
(defun fn-ibp-connection-release (token fuel fn-index-backing)
 (declare (xargs :stobjs fn-index-backing :guard (natp fuel)))
 (let ((needed (* 3 (+ 1 (fn-ibp-slot-depth fn-index-backing)))))
  (if (< fuel needed) (mv :yield nil fuel fn-index-backing)
   (mv-let (word row left) (fn-ibp-connection-read token fuel fn-index-backing)
    (if (not (eq word :present)) (mv word nil left fn-index-backing)
     (mv-let (ready pin grant) (fn-ich-row-release-ready row)
      (declare (ignore grant))
      (cond ((not (eq ready :ready)) (mv ready nil left fn-index-backing))
            ((not pin)
             (fn-ibp-connection-event token :release nil nil (nfix left) fn-index-backing))
            ((not (and (fn-omk-widthp pin 3)
                       (eq (fn-omk-at 0 pin) :publication-pin)
                       (fn-ibp-generation-tokenp (fn-omk-at 1 pin))))
             (mv :recovery-required nil left fn-index-backing))
            (t
             (mv-let (dropped pub remaining fn-index-backing)
              (fn-ibp-generation-reference (fn-omk-at 1 pin) :drop :pin nil
                                           (nfix left) fn-index-backing)
              (declare (ignore pub))
              (if (not (member-eq dropped '(:live :retiring)))
                  (mv :recovery-required nil remaining fn-index-backing)
                (mv-let (settled released-grant after fn-index-backing)
                 (fn-ibp-connection-event token :release nil nil (nfix remaining) fn-index-backing)
                 (mv (if (eq settled :released) :released :recovery-required)
                     released-grant after fn-index-backing))))))))))))
