; Generated by tools/owner_carrier/families.py composition_events.
; Exact outputs and all ten effects of the pre-move host compositions.
(in-package "ACL2")
(include-book "owner-publication-transitions")

(defun fn-opub-observe (r)
  (declare (xargs :guard t))
  (list (fn-opub-get :attempted r) (fn-opub-get :base r) (fn-opub-get :base-payloads r) (fn-opub-get :deferred r) (fn-opub-get :durable r) (fn-opub-get :inflight r) (fn-opub-get :pending r) (fn-opub-get :requested r) (fn-opub-get :serial r) (fn-opub-get :pass r)))

(defthm fn-opub-due-composition-by-definition
  (let ((word (fn-ock-requested-next
        (fn-opub-get :durable r) count suffix
        (fn-opl-attempted (fn-opub-get :deferred r) (fn-opub-get :attempted r) count now)
        (fn-opub-get :inflight r)
        (fn-opl-blockedp (fn-opub-get :deferred r) budget space count now)
        (fn-opub-get :requested r))))
    (and (equal (mv-nth 0 (fn-opub-due r profile count suffix budget space now)) (if profile (if (equal word :coalesce) :inflight word) :idle))
         (equal (fn-opub-observe (mv-nth 1 (fn-opub-due r profile count suffix budget space now)))
                (if (not profile) (fn-opub-observe r)
          (cond ((equal word :coalesce) (list (fn-opub-get :attempted r) (fn-opub-get :base r) (fn-opub-get :base-payloads r) (fn-opub-get :deferred r) (fn-opub-get :durable r) (fn-opub-get :inflight r) t (fn-opub-get :requested r) (fn-opub-get :serial r) (fn-opub-get :pass r)))
                ((equal word :inflight) (fn-opub-observe r))
                ((equal word :due) (list (fn-opub-get :attempted r) (fn-opub-get :base r) (fn-opub-get :base-payloads r) (fn-opub-get :deferred r) (fn-opub-get :durable r) (fn-opub-get :inflight r) nil (fn-opub-get :requested r) (fn-opub-get :serial r) (fn-opub-get :pass r)))
                (t (list (fn-opub-get :attempted r) (fn-opub-get :base r) (fn-opub-get :base-payloads r) (fn-opub-get :deferred r) (fn-opub-get :durable r) (fn-opub-get :inflight r) nil nil (fn-opub-get :serial r) (fn-opub-get :pass r))))))))
  :hints (("Goal" :in-theory
           (e/d (fn-opub-due fn-opub-observe)
                (fn-opub-get fn-opub-put fn-opl-settle fn-opl-holdsp
                 fn-orc-release-slot fn-ock-requested-next fn-ock-request-word
                 fn-opl-attempted fn-opl-blockedp fn-scka-strip-base fn-sco-sequence)))))

(defthm fn-opub-request-composition-by-definition
  (let ((word (fn-ock-request-word
        (fn-opub-get :durable r) count
        (fn-opl-attempted (fn-opub-get :deferred r) (fn-opub-get :attempted r) count now)
        (fn-opub-get :inflight r)
        (fn-opl-blockedp (fn-opub-get :deferred r) budget space count now))))
    (and (equal (mv-nth 0 (fn-opub-request r profile count budget space now)) (if profile word :nothing-to-compact))
         (equal (fn-opub-observe (mv-nth 1 (fn-opub-request r profile count budget space now)))
                (if profile (list (fn-opub-get :attempted r) (fn-opub-get :base r) (fn-opub-get :base-payloads r) (fn-opub-get :deferred r) (fn-opub-get :durable r) (fn-opub-get :inflight r) (fn-opub-get :pending r) (and (member-eq word '(:requested :coalesced)) t) (fn-opub-get :serial r) (fn-opub-get :pass r)) (fn-opub-observe r)))))
  :hints (("Goal" :in-theory
           (e/d (fn-opub-request fn-opub-observe)
                (fn-opub-get fn-opub-put fn-opl-settle fn-opl-holdsp
                 fn-orc-release-slot fn-ock-requested-next fn-ock-request-word
                 fn-opl-attempted fn-opl-blockedp fn-scka-strip-base fn-sco-sequence)))))

(defthm fn-opub-capture-composition-by-definition
  (let ((serial (fn-opl-next-serial (fn-opub-get :serial r))))
    (and (equal (mv-nth 0 (fn-opub-capture r count)) serial)
         (equal (fn-opub-observe (mv-nth 1 (fn-opub-capture r count)))
                (list count (fn-opub-get :base r) (fn-opub-get :base-payloads r) (fn-opub-get :deferred r) (fn-opub-get :durable r) count (fn-opub-get :pending r) nil serial (fn-opub-get :pass r)))))
  :hints (("Goal" :in-theory
           (e/d (fn-opub-capture fn-opub-observe)
                (fn-opub-get fn-opub-put fn-opl-settle fn-opl-holdsp
                 fn-orc-release-slot fn-ock-requested-next fn-ock-request-word
                 fn-opl-attempted fn-opl-blockedp fn-scka-strip-base fn-sco-sequence)))))

(defthm fn-opub-done-composition-by-definition
  (let ((released (fn-orc-release-slot (list :publication (fn-sco-sequence next))
                    (fn-opub-get :pass r) (fn-opub-get :inflight r))))
    (and (equal (mv-nth 0 (fn-opub-done r next payloads durablep verdict)) (if durablep (fn-sco-sequence next) :none))
         (equal (fn-opub-observe (mv-nth 1 (fn-opub-done r next payloads durablep verdict)))
                (list (fn-opub-get :attempted r) (fn-scka-strip-base next) (and (natp payloads) payloads) (cond ((and (consp verdict) (eq (car verdict) :deferred)) verdict)
                                 (durablep nil) (t (fn-opub-get :deferred r))) (if durablep (fn-sco-sequence next) (fn-opub-get :durable r)) (cadr released) (fn-opub-get :pending r) (fn-opub-get :requested r) (fn-opub-get :serial r) (fn-opub-get :pass r)))))
  :hints (("Goal" :in-theory
           (e/d (fn-opub-done fn-opub-observe)
                (fn-opub-get fn-opub-put fn-opl-settle fn-opl-holdsp
                 fn-orc-release-slot fn-ock-requested-next fn-ock-request-word
                 fn-opl-attempted fn-opl-blockedp fn-scka-strip-base fn-sco-sequence)))))

(defthm fn-opub-abandoned-composition-by-definition
  (let ((settled (fn-opl-settle count serial outcome now (fn-opub-get :pass r)
                         (fn-opub-get :inflight r) (fn-opub-get :serial r) (fn-opub-get :deferred r))))
    (and (equal (mv-nth 0 (fn-opub-abandoned r count serial outcome now)) (if (fn-opl-holdsp count serial (fn-opub-get :pass r) (fn-opub-get :inflight r)
                             (fn-opub-get :serial r)) (caddr settled) :stale))
         (equal (fn-opub-observe (mv-nth 1 (fn-opub-abandoned r count serial outcome now)))
                (list (fn-opub-get :attempted r) (fn-opub-get :base r) (fn-opub-get :base-payloads r) (caddr settled) (fn-opub-get :durable r) (cadr settled) (fn-opub-get :pending r) (fn-opub-get :requested r) (fn-opub-get :serial r) (fn-opub-get :pass r)))))
  :hints (("Goal" :in-theory
           (e/d (fn-opub-abandoned fn-opub-observe)
                (fn-opub-get fn-opub-put fn-opl-settle fn-opl-holdsp
                 fn-orc-release-slot fn-ock-requested-next fn-ock-request-word
                 fn-opl-attempted fn-opl-blockedp fn-scka-strip-base fn-sco-sequence)))))

(defthm fn-opub-install-composition-by-definition
  (equal (fn-opub-observe (fn-opub-install r base)) (list nil base nil nil nil nil nil nil (fn-opub-get :serial r) nil))
  :hints (("Goal" :in-theory (enable fn-opub-install fn-opub-observe))))

(defthm fn-opub-reclaim-install-composition-by-definition
  (equal (fn-opub-observe (fn-opub-reclaim-install r base count)) (list count base nil nil count nil (fn-opub-get :pending r) (fn-opub-get :requested r) (fn-opub-get :serial r) nil))
  :hints (("Goal" :in-theory (enable fn-opub-reclaim-install fn-opub-observe))))
