; Binding-changing companion of the existing counter transaction.
(in-package "ACL2")
(include-book "page-read-counter-transaction")
(include-book "runtime-operation-source")
(defun fn-owner-page-read-bindings-begin
 (next captured-revision nonce kind continuation fn-page-read-pool state)
 (declare (xargs :stobjs (fn-page-read-pool state) :guard t :verify-guards nil))
 (let* ((data (fn-prp-data fn-page-read-pool))
        (mode (fn-prp-mode fn-page-read-pool))
        (epoch-mode (fn-prp-alloc-mode fn-page-read-pool))
        (revision (fn-prb-data-revision data)))
  (if (not (and data (eq mode :served) (member-eq epoch-mode '(:active :draining))
                (natp nonce) (symbolp kind) (natp revision)
                (equal revision captured-revision)
                (natp (fn-prl-nth 2 (fn-prl-nth 0 data)))
                (natp (fn-prl-nth 2 next))))
   (mv :binding-publication-unavailable nil fn-page-read-pool)
   (mv-let (word domain) (fn-owner-runtime-bootstrap-domain fn-page-read-pool state)
    (if (not (and (eq word :runtime-bootstrap-domain) (integerp domain)
                  (< 1 domain) (< revision (- domain 1))))
     (mv :binding-domain-unavailable nil fn-page-read-pool)
     (let* ((successor (+ 1 revision))
            (receipt (list :counter-publication nonce (fn-prl-nth 2 (fn-prl-nth 0 data))
                           (fn-prl-nth 2 next) successor kind))
            (intent (list :binding-publishing mode epoch-mode data next successor receipt continuation))
            (fn-page-read-pool (update-fn-prp-mode intent fn-page-read-pool))
            (fn-page-read-pool (update-fn-prp-alloc-mode :recovery fn-page-read-pool))
            (fn-page-read-pool (update-fn-prp-data (fn-prb-data6 next data successor) fn-page-read-pool)))
      (mv :binding-publishing receipt fn-page-read-pool)))))))
(defun fn-owner-page-read-bindings-finish (receipt fn-page-read-pool)
 (declare (xargs :stobjs fn-page-read-pool :guard t :verify-guards nil))
 (let ((intent (fn-prp-mode fn-page-read-pool)))
  (if (not (and (fn-prb-fixed-widthp 8 intent)
                (eq (fn-prl-nth 0 intent) :binding-publishing)
                (eq (fn-prp-alloc-mode fn-page-read-pool) :recovery)
                (fn-prb-counter-receipt-matchesp receipt (fn-prl-nth 6 intent))
                (equal (fn-prb-data-revision (fn-prp-data fn-page-read-pool)) (fn-prl-nth 4 receipt))
                (equal (fn-prl-nth 2 (fn-owner-page-read-ledger fn-page-read-pool)) (fn-prl-nth 3 receipt))))
   (mv :binding-publication-stale fn-page-read-pool)
   (let* ((fn-page-read-pool (update-fn-prp-alloc-mode (fn-prl-nth 2 intent) fn-page-read-pool))
          (fn-page-read-pool (update-fn-prp-mode (fn-prl-nth 1 intent) fn-page-read-pool)))
    (mv :published fn-page-read-pool)))))
