; Monotonic transfer from idle DEFAULT pool authority to larger Store state.
; Called under the actual owner->extent mutex envelope; no pool reset/refund.
(in-package "ACL2")
(include-book "page-read-ledger")
(defun fn-prl-resident-budget (resident budget)
 (declare (xargs :guard t))
 (list resident (fn-prl-nth 1 budget) (fn-prl-nth 2 budget)
                (fn-prl-nth 3 budget) (fn-prl-nth 4 budget)))
(defun fn-prl-resident-shrink (amount ledger)
 (declare (xargs :guard t))
 (let* ((budget (fn-prl-nth 0 ledger)) (charged (fn-prl-nth 1 ledger))
        (baseline (fn-prl-baseline ledger))
        (resident (fn-prl-nth 0 budget)))
  (if (not (and (natp amount) (natp resident) (<= amount resident)
                 (fn-prs-fundedp budget baseline '(0 0 0 0 0) charged)))
      (mv :read-resources-unavailable ledger)
    (let ((next (fn-prl-resident-budget (- resident amount) budget)))
     (if (not (fn-prs-fundedp next baseline '(0 0 0 0 0) charged))
         (mv :read-resources-unavailable ledger)
       (mv :protected-growth-admitted
           (fn-prl-build next charged (fn-prl-nth 2 ledger)
                         (fn-prl-nth 3 ledger) (fn-prl-nth 4 ledger))))))))
(defthm fn-prl-resident-shrink-preserves-custody
 (let ((next (mv-nth 1 (fn-prl-resident-shrink amount ledger))))
  (and (equal (fn-prl-nth 1 next) (fn-prl-nth 1 ledger))
       (equal (fn-prl-nth 2 next) (fn-prl-nth 2 ledger))
       (equal (fn-prl-nth 3 next) (fn-prl-nth 3 ledger))
       (equal (fn-prl-nth 4 next) (fn-prl-nth 4 ledger))))
 :hints (("Goal" :in-theory (e/d (fn-prl-resident-shrink fn-prl-build fn-prl-nth)
   (fn-prl-resident-budget fn-prs-fundedp fn-prl-baseline)))))
(defthm fn-prl-resident-shrink-keeps-funding
 (implies (fn-prs-fundedp (fn-prl-nth 0 ledger) (fn-prl-baseline ledger) '(0 0 0 0 0)
                         (fn-prl-nth 1 ledger))
          (let ((next (mv-nth 1 (fn-prl-resident-shrink amount ledger))))
           (fn-prs-fundedp (fn-prl-nth 0 next) (fn-prl-baseline next) '(0 0 0 0 0)
                          (fn-prl-nth 1 next))))
 :hints (("Goal" :in-theory (e/d (fn-prl-resident-shrink fn-prl-build fn-prl-nth fn-prl-baseline)
   (fn-prl-resident-budget fn-prs-fundedp)))))
