; HST-049/PRF-1307: independent catchup spool lifetime bank. This selected
; backing projection is partial: native cells, owned cons/controller graphs,
; TLS, integer payloads and collector transients require their actual tariff.
(in-package "ACL2")
(include-book "resource-vector-exec")
(include-book "cold-read-layout")
(include-book "heap-store-figure")

(defun fn-pfr-at (n xs)
 (declare (xargs :guard (natp n)))
 (if (consp xs) (if (zp n) (car xs) (fn-pfr-at (1- n) (cdr xs))) nil))

; Policy: heap, disk, maximum flights, maximum workers, spool per flight,
; total metered work. This is operator authority, not Store-data truncation.
(defun fn-pfr-slots (flights)
 (declare (xargs :guard t)) (+ 2 (* 2 (nfix flights))))
(defun fn-pfr-flight-slot (index)
 (declare (xargs :guard t)) (+ 2 (* 2 (nfix index))))
(defun fn-pfr-work-slot (index)
 (declare (xargs :guard t)) (+ 3 (* 2 (nfix index))))
(defun fn-pfr-bookkeeping (flights)
 (declare (xargs :guard t)) (+ 8192 (* 272 (fn-pfr-slots flights))))
(defun fn-pfr-fixed-backing ()
 (declare (xargs :guard t))
 ; Three direct UB8 vectors; digest native register vector and fixed frames.
 ; Header uses the input vector. No claimed price for pointed-to hash frames.
 (+ (fn-crl-array-octets 512 1) (fn-crl-array-octets 64 1)
    (fn-crl-array-octets 512 1) (fn-crl-array-octets 16 8)
    (fn-crl-array-octets 64 8)
    (* 2 (fn-crl-array-octets 2 8))
    (* 2 (fn-crl-array-octets 0 1))))
(defun fn-pfr-policy-p (p)
 (declare (xargs :guard t))
 (and (true-listp p) (equal (len p) 6)
      (natp (fn-pfr-at 0 p)) (<= (fn-pfr-at 0 p) *fn-rl-word-max*)
      (natp (fn-pfr-at 1 p)) (<= (fn-pfr-at 1 p) *fn-rl-word-max*)
      (posp (fn-pfr-at 2 p)) (< (fn-pfr-slots (fn-pfr-at 2 p)) (expt 2 32))
      (posp (fn-pfr-at 3 p)) (<= (fn-pfr-at 3 p) (fn-pfr-at 2 p))
      (posp (fn-pfr-at 4 p)) (< (fn-pfr-at 4 p) (expt 2 63))
      (<= (fn-pfr-at 4 p) (fn-pfr-at 1 p))
      (natp (fn-pfr-at 5 p)) (<= (fn-pfr-at 5 p) *fn-rl-word-max*)
      (<= (+ (fn-pfr-bookkeeping (fn-pfr-at 2 p)) (fn-pfr-fixed-backing))
          (fn-pfr-at 0 p))))
(defun fn-pfr-native (workers stack runtime)
 (declare (xargs :guard t)) (* (nfix workers) (+ (nfix stack) (nfix runtime))))
(defun fn-pfr-flight-demand (p stack runtime)
 (declare (xargs :guard t))
 (if (and (fn-pfr-policy-p p) (natp stack) (natp runtime)
          (<= (+ (fn-pfr-fixed-backing) stack runtime) *fn-rl-word-max*))
     (list (+ (fn-pfr-fixed-backing) stack runtime) (fn-pfr-at 4 p)
           2 1 1 0 0 0 0)
   nil))
(defun fn-pfr-work-demand (units)
 (declare (xargs :guard t))
 (if (and (natp units) (<= units *fn-rl-word-max*))
     (list 0 0 0 0 0 0 0 0 units) nil))
(defun fn-pfr-budget (p stack runtime)
 (declare (xargs :guard t))
 (list (+ (nfix (fn-pfr-at 0 p)) (fn-pfr-native (fn-pfr-at 3 p) stack runtime))
       (nfix (fn-pfr-at 1 p)) (* 2 (nfix (fn-pfr-at 2 p)))
       (nfix (fn-pfr-at 3 p)) *fn-rl-word-max* 0 0 0 (nfix (fn-pfr-at 5 p))))
(defun fn-pfr-install (p stack runtime fn-resource-ledger)
 (declare (xargs :stobjs fn-resource-ledger :guard t :verify-guards nil))
 (if (not (and (fn-pfr-policy-p p) (natp stack) (natp runtime)
               (<= (+ (fn-pfr-at 0 p) (fn-pfr-native (fn-pfr-at 3 p) stack runtime))
                   *fn-rl-word-max*)))
     (mv :invalid-peer-flight-profile fn-resource-ledger)
   (fn-rl-install (fn-pfr-budget p stack runtime)
                  (list (fn-pfr-bookkeeping (fn-pfr-at 2 p)) 0 0 0 0 0 0 0 0)
                  '(0 0 0 0 0 0 0 0 0)
                  (fn-pfr-slots (fn-pfr-at 2 p)) fn-resource-ledger)))
(verify-guards fn-pfr-install :hints (("Goal" :in-theory (disable fn-rl-install))))
(defun fn-pfr-scope ()
 (declare (xargs :guard t)) :partial-fixed-storage)

; The new private worker reservation is independent of output/syncer grants.
; Native thread stack is the existing launch stack; no new host arithmetic.
(defun fn-pfr-extend-reservation (base policy core observations)
 (declare (xargs :guard t))
 (cond ((not policy) base)
       ((not (eq (fn-pfr-at 0 base) :heap)) base)
       ((not (fn-pfr-policy-p policy))
        (list :refused :invalid-peer-flight-profile 0 (fn-pfr-at 3 base)))
       (t
        (let* ((mb (fn-heap-mb-of (fn-heap-grow-runtime-dynamic
                                     (* *fn-heap-mib* (nfix (fn-pfr-at 1 base)))
                                     (fn-pfr-at 0 policy)
                                     (* *fn-heap-mib* (fn-profile-limit :gc-nursery-mib)))))
               (stack (nfix (fn-pfr-at 4 base)))
               (threads (+ (nfix (fn-pfr-at 5 base)) (fn-pfr-at 3 policy)))
               (total (fn-heap-reservation-octets mb core stack threads)))
         (if (<= total (fn-heap-machine-octets observations))
             (list :heap mb (fn-pfr-at 2 base) (fn-pfr-at 3 base) stack threads)
           (list :refused :machine-cannot-hold-threads (fn-heap-mb-of total)
                 (fn-pfr-at 3 base)))))))

(defthm fn-pfr-accepted-launch-fits-machine
 (implies (and policy
               (equal (fn-pfr-at 0 (fn-pfr-extend-reservation base policy core observations)) :heap))
  (let ((d (fn-pfr-extend-reservation base policy core observations)))
   (<= (fn-heap-reservation-octets (fn-pfr-at 1 d) core (fn-pfr-at 4 d) (fn-pfr-at 5 d))
       (fn-heap-machine-octets observations))))
 :rule-classes nil
 :hints (("Goal" :in-theory (e/d (fn-pfr-extend-reservation fn-pfr-at)
    (fn-pfr-policy-p fn-heap-mb-of fn-heap-reservation-octets fn-heap-machine-octets)))))

; Validate this independent heap slice against the parent's actual runtime
; capture. PROTECTED excludes this peer slice and includes other live banks.
(defun fn-pfr-startup-grant (dynamic protected p)
 (declare (xargs :guard t))
 (cond ((not p) (list :partial :peer-flight-profile-unconfigured))
       ((not (and (fn-pfr-policy-p p) (natp dynamic) (natp protected)))
        (list :refused :invalid-peer-flight-profile))
       ((< dynamic (+ protected (fn-pfr-at 0 p)))
        (list :refused :peer-flight-pool-not-held))
       (t (list :hold p :partial-fixed-storage))))
(defun fn-pfr-install-funded (dynamic protected p stack runtime fn-resource-ledger)
 (declare (xargs :stobjs fn-resource-ledger :guard t :verify-guards nil))
 (let ((grant (fn-pfr-startup-grant dynamic protected p)))
  (if (eq (fn-pfr-at 0 grant) :hold)
      (fn-pfr-install p stack runtime fn-resource-ledger)
    (mv (fn-pfr-at 1 grant) fn-resource-ledger))))
(verify-guards fn-pfr-install-funded)
(defthm fn-pfr-held-startup-fits-capture
 (implies (equal (fn-pfr-at 0 (fn-pfr-startup-grant dynamic protected p)) :hold)
          (<= (+ (nfix protected) (nfix (fn-pfr-at 0 p))) (nfix dynamic)))
 :rule-classes nil
 :hints (("Goal" :in-theory (e/d (fn-pfr-startup-grant fn-pfr-at nfix fn-pfr-policy-p)
                                (fn-pfr-fixed-backing fn-pfr-bookkeeping fn-pfr-slots)))))
