; Internal scalar arena boundary. Source authority and active QPG lookup are
; the indexed provider's carried SAME-row relation, not a handle-prefix test.
(in-package "ACL2")
(include-book "query-payload-grants")
(include-book "payload-view-lease")
(include-book "held-record")
(include-book "payload-arena")
(defun fn-qps-eligiblep (held grant ledger fn-arena)
  (declare (xargs :stobjs fn-arena :guard t))
  (let ((h (fn-held-payload held)))
    (and (fn-qpg-tokenp grant) (fn-pvl-ledgerp ledger)
         (equal (fn-omk-at 4 grant) (fn-omk-at 0 ledger))
         (natp h) (< h (fn-omk-at 5 grant))
         (<= (fn-omk-at 5 grant) (fn-arena-count fn-arena)))))
(defun fn-qps-selected-length (selected held grant ledger fuel fn-arena)
  (declare (xargs :stobjs fn-arena :guard (natp fuel)
                  :guard-hints (("Goal" :in-theory (enable fn-qps-eligiblep)))))
  (cond ((zp fuel) (mv :yield nil fuel))
        ((not (fn-qps-eligiblep held grant ledger fn-arena)) (mv :refused nil (- fuel 1)))
        (t (let* ((h (fn-held-payload held))
                  (n (fn-arena-payload-len h fn-arena)))
             (mv :ready (list :payload-length selected grant h n) (- fuel 1))))))
(fn-payload-kind fn-qps-selected-length :handle "reads the arena at the handle")
(defun fn-qps-selected-byte (selected held grant ledger index fuel fn-arena)
  (declare (xargs :stobjs fn-arena :guard (and (natp index) (natp fuel))
                  :guard-hints (("Goal" :in-theory (enable fn-qps-eligiblep)))))
  (cond ((zp fuel) (mv :yield nil fuel))
        ((not (fn-qps-eligiblep held grant ledger fn-arena)) (mv :refused nil (- fuel 1)))
        (t (let ((h (fn-held-payload held)))
             (if (not (< index (fn-arena-payload-len h fn-arena)))
                 (mv :refused nil (- fuel 1))
               (mv :ready (list :payload-byte selected grant h index
                               (fn-arena-get h index fn-arena)) (- fuel 1)))))))
(fn-payload-kind fn-qps-selected-byte :handle "reads the arena at the handle")
(defthm fn-qps-length-observation-by-definition
  (implies (and (natp fuel) (not (zp fuel))
                (fn-qps-eligiblep held grant ledger fn-arena))
    (equal (mv-list 3 (fn-qps-selected-length selected held grant ledger fuel fn-arena))
           (list :ready (list :payload-length selected grant (fn-held-payload held)
                              (fn-arena-payload-len (fn-held-payload held) fn-arena))
                 (- fuel 1))))
  :rule-classes nil)
(defthm fn-qps-byte-observation-by-definition
  (implies (and (natp fuel) (not (zp fuel)) (natp index)
                (fn-qps-eligiblep held grant ledger fn-arena)
                (< index (fn-arena-payload-len (fn-held-payload held) fn-arena)))
    (equal (mv-list 3 (fn-qps-selected-byte selected held grant ledger index fuel fn-arena))
           (list :ready (list :payload-byte selected grant (fn-held-payload held) index
                              (fn-arena-get (fn-held-payload held) index fn-arena))
                 (- fuel 1))))
  :rule-classes nil)
