; Fixed RX provider. Only installed shared-pool authority can populate carry.
; A nested provider prevents separately supplied carry/buffer combinations.
; Runtime constructor, physical backing and lifetime refinement remain distinct.
(in-package "ACL2")
(include-book "receive-octet-buffer")
(include-book "fixed-buffer-capacity")
(defstobj fn-rx-carry
 (fn-rxc-token :initially nil)
 (fn-rxc-instance :initially nil)
 (fn-rxc-capacity :initially nil)
 :inline t)
(defstobj fn-rx-provider
 (fn-rxp-octets :type fn-octets-rx)
 (fn-rxp-carry :type fn-rx-carry)
 :inline t)
(defun fn-rxc-uninitializedp (fn-rx-carry)
 (declare (xargs :stobjs fn-rx-carry))
 (and (null (fn-rxc-token fn-rx-carry))
      (null (fn-rxc-instance fn-rx-carry))
      (null (fn-rxc-capacity fn-rx-carry))))
(defun fn-rxc-currentp (token fn-rx-carry)
 (declare (xargs :stobjs fn-rx-carry))
 (and (fn-bca-tokenp token) (eq (fn-prl-nth 0 token) :rx-capacity)
      (equal token (fn-rxc-token fn-rx-carry))
      (equal (fn-prl-nth 2 token) (fn-rxc-instance fn-rx-carry))
      (equal (fn-rxc-capacity fn-rx-carry) 4096)))
(defun fn-rxc-fill-range (token n limits fuel fn-rx-carry)
 (declare (xargs :stobjs fn-rx-carry))
 (cond ((not (fn-rxc-currentp token fn-rx-carry))
        (mv :receiver-unavailable 0 0 fuel))
       ((not (and (natp n) (natp fuel))) (mv :bad-receive-range 0 0 fuel))
       ((> n (fn-cbud-step-read-octets limits))
        (mv :receive-quantum-full 0 0 fuel))
       ((> n fuel) (mv :receive-yield 0 0 fuel))
       (t (mv :receive-copy 0 n (- fuel n)))))
(defun fn-rxp-fill-range (token n limits fuel fn-rx-provider)
 (declare (xargs :stobjs fn-rx-provider))
 (stobj-let ((fn-rx-carry (fn-rxp-carry fn-rx-provider)))
            (word start end nextfuel)
            (fn-rxc-fill-range token n limits fuel fn-rx-carry)
            (mv word start end nextfuel fn-rx-provider)))
(defun fn-rxp-token (fn-rx-provider)
 (declare (xargs :stobjs fn-rx-provider))
 (stobj-let ((fn-rx-carry (fn-rxp-carry fn-rx-provider)))
            (token) (fn-rxc-token fn-rx-carry) token))
(defun fn-rxp-instance (fn-rx-provider)
 (declare (xargs :stobjs fn-rx-provider))
 (stobj-let ((fn-rx-carry (fn-rxp-carry fn-rx-provider)))
            (instance) (fn-rxc-instance fn-rx-carry) instance))
(defun fn-rxp-capacity (fn-rx-provider)
 (declare (xargs :stobjs fn-rx-provider))
 (stobj-let ((fn-rx-carry (fn-rxp-carry fn-rx-provider)))
            (capacity) (fn-rxc-capacity fn-rx-carry) capacity))

(defthm fn-rxp-fill-range-preserves-provider
 (equal (mv-nth 4 (fn-rxp-fill-range token n limits fuel fn-rx-provider))
        fn-rx-provider)
 :hints (("Goal" :in-theory (enable fn-rxp-fill-range))))
(defthm fn-rxc-fill-range-copy-bounds
 (implies (equal (mv-nth 0 (fn-rxc-fill-range token n limits fuel fn-rx-carry))
                 :receive-copy)
          (and (fn-rxc-currentp token fn-rx-carry)
               (natp n) (natp fuel)
               (<= n (fn-cbud-step-read-octets limits))
               (<= n 4096) (<= n fuel)
               (equal (mv-nth 1 (fn-rxc-fill-range token n limits fuel fn-rx-carry)) 0)
               (equal (mv-nth 2 (fn-rxc-fill-range token n limits fuel fn-rx-carry)) n)
               (equal (mv-nth 3 (fn-rxc-fill-range token n limits fuel fn-rx-carry)) (- fuel n))))
 :hints (("Goal" :in-theory (enable fn-rxc-fill-range))))
(defthm fn-rxc-fill-range-refusal-preserves-fuel
 (implies (not (equal (mv-nth 0 (fn-rxc-fill-range token n limits fuel fn-rx-carry))
                      :receive-copy))
          (and (equal (mv-nth 1 (fn-rxc-fill-range token n limits fuel fn-rx-carry)) 0)
               (equal (mv-nth 2 (fn-rxc-fill-range token n limits fuel fn-rx-carry)) 0)
               (equal (mv-nth 3 (fn-rxc-fill-range token n limits fuel fn-rx-carry)) fuel)))
 :hints (("Goal" :in-theory (enable fn-rxc-fill-range))))
(defthm fn-rxp-fill-range-copy-bounds
 (implies (equal (mv-nth 0 (fn-rxp-fill-range token n limits fuel fn-rx-provider))
                 :receive-copy)
          (and (natp n) (natp fuel) (<= n 4096) (<= n fuel)
               (<= n (fn-cbud-step-read-octets limits))
               (equal (fn-rxp-token fn-rx-provider) token)
               (equal (fn-rxp-instance fn-rx-provider) (fn-prl-nth 2 token))
               (equal (fn-rxp-capacity fn-rx-provider) 4096)
               (equal (mv-nth 1 (fn-rxp-fill-range token n limits fuel fn-rx-provider)) 0)
               (equal (mv-nth 2 (fn-rxp-fill-range token n limits fuel fn-rx-provider)) n)
               (equal (mv-nth 3 (fn-rxp-fill-range token n limits fuel fn-rx-provider)) (- fuel n))))
 :hints (("Goal" :in-theory (enable fn-rxp-fill-range fn-rxc-fill-range
                                  fn-rxc-currentp fn-rxp-token
                                  fn-rxp-instance fn-rxp-capacity))))
(defthm fn-rxp-fill-range-refusal-preserves-fuel
 (implies (not (equal (mv-nth 0 (fn-rxp-fill-range token n limits fuel fn-rx-provider))
                      :receive-copy))
          (and (equal (mv-nth 1 (fn-rxp-fill-range token n limits fuel fn-rx-provider)) 0)
               (equal (mv-nth 2 (fn-rxp-fill-range token n limits fuel fn-rx-provider)) 0)
               (equal (mv-nth 3 (fn-rxp-fill-range token n limits fuel fn-rx-provider)) fuel)))
 :hints (("Goal" :in-theory (enable fn-rxp-fill-range))))

; Bounded logical reference for the native range-copy boundary. This list
; subject is not the served vector primitive; that primitive owes the named
; complete effect refinement, including bytes, carry and fuel.
(defun fn-rxp-fill-reference (token bytes limits fuel fn-rx-provider)
 (declare (xargs :stobjs fn-rx-provider
                 :guard (fn-cbor-octet-listp bytes)))
 (mv-let (word start end nextfuel fn-rx-provider)
   (fn-rxp-fill-range token (len bytes) limits fuel fn-rx-provider)
   (declare (ignore start end))
   (if (not (eq word :receive-copy))
       (mv word nextfuel fn-rx-provider)
     (stobj-let ((fn-octets-rx (fn-rxp-octets fn-rx-provider)))
                (fn-octets-rx)
                (fn-octets-rx-from-list bytes fn-octets-rx)
                (mv :receive-copy nextfuel fn-rx-provider)))))
(defthm fn-rxp-fill-reference-complete-effect-by-definition
 (let ((range (fn-rxp-fill-range token (len bytes) limits fuel fn-rx-provider)))
   (and (equal (mv-nth 0 (fn-rxp-fill-reference token bytes limits fuel fn-rx-provider))
               (mv-nth 0 range))
        (equal (mv-nth 1 (fn-rxp-fill-reference token bytes limits fuel fn-rx-provider))
               (mv-nth 3 range))
        (equal (mv-nth 2 (fn-rxp-fill-reference token bytes limits fuel fn-rx-provider))
               (if (equal (mv-nth 0 range) :receive-copy)
                   (update-nth 0 bytes fn-rx-provider)
                 fn-rx-provider))))
 :hints (("Goal" :in-theory (enable fn-rxp-fill-reference fn-rxp-fill-range
                                  fn-octets$a-from-list))))

; Native uncertain-copy exit must fence before any consumer can observe RX.
; Preserve issued identity/object/retained U; this is not reset or refund.
(defun fn-rxc-fence (token fn-rx-carry)
 (declare (xargs :stobjs fn-rx-carry))
 (if (not (fn-rxc-currentp token fn-rx-carry))
     (mv :receiver-unavailable fn-rx-carry)
   (let ((fn-rx-carry (update-fn-rxc-capacity nil fn-rx-carry)))
     (mv :receiver-fenced fn-rx-carry))))
(defun fn-rxp-fence (token fn-rx-provider)
 (declare (xargs :stobjs fn-rx-provider))
 (stobj-let ((fn-rx-carry (fn-rxp-carry fn-rx-provider)))
            (word fn-rx-carry)
            (fn-rxc-fence token fn-rx-carry)
            (mv word fn-rx-provider)))
(defun fn-rxp-currentp (token fn-rx-provider)
 (declare (xargs :stobjs fn-rx-provider))
 (stobj-let ((fn-rx-carry (fn-rxp-carry fn-rx-provider)))
            (current) (fn-rxc-currentp token fn-rx-carry) current))
(defthm fn-rxc-second-field-by-definition
 (equal (nth 1 x) (cadr x))
 :hints (("Goal" :expand ((nth 1 x)))))
(defthm fn-rxp-fence-preserves-issued-identity
 (let ((next (mv-nth 1 (fn-rxp-fence token fn-rx-provider))))
  (and (equal (fn-rxp-token next) (fn-rxp-token fn-rx-provider))
       (equal (fn-rxp-instance next) (fn-rxp-instance fn-rx-provider))
       (equal (nth 0 next) (nth 0 fn-rx-provider))))
 :hints (("Goal" :in-theory (e/d (fn-rxp-fence fn-rxc-fence fn-rxp-token
                                  fn-rxp-instance update-nth)
                                 (fn-rxc-currentp fn-bca-tokenp fn-bca-fieldsp))
                 :expand ((update-nth 2 nil (nth 1 fn-rx-provider))
                          (update-nth 1 nil (cdr (nth 1 fn-rx-provider)))))))
(defthm fn-rxp-fence-revokes-readiness
 (not (fn-rxp-currentp token (mv-nth 1 (fn-rxp-fence token fn-rx-provider))))
 :hints (("Goal" :in-theory (enable fn-rxp-currentp fn-rxp-fence
                                  fn-rxc-fence fn-rxc-currentp))))
(defthm fn-rxp-fence-is-idempotent
 (equal (mv-nth 1 (fn-rxp-fence token
                        (mv-nth 1 (fn-rxp-fence token fn-rx-provider))))
        (mv-nth 1 (fn-rxp-fence token fn-rx-provider)))
 :hints (("Goal" :in-theory (enable fn-rxp-fence fn-rxc-fence fn-rxc-currentp))))
