; Actual pre-service file/read controller. Target is image-owned, fixed643;
; source/runtime resources are returned by the common genuine producer.
(in-package "ACL2")
(include-book "page-read-bindings-transaction")
(include-book "runtime-operation-source")
(include-book "recovery-profile-buffer")
(include-book "store-profile-open")
(include-book "allocation-turn-slots")
(defstobj fn-page-file-open
 (fn-pfo-phase :initially :uninstalled)
 (fn-pfo-path :initially nil)
 (fn-pfo-source :initially nil)
 (fn-pfo-slot :initially nil)
 (fn-pfo-turn :initially nil)
 (fn-pfo-file :initially nil)
 (fn-pfo-claim :initially nil)
 (fn-pfo-pending :initially nil)
 (fn-pfo-count :type (integer 0 *) :initially 0)
 (fn-pfo-eof :initially nil)
 (fn-pfo-result :initially nil)
 :inline t)
(defconst *fn-pfo-workspace-size* (nth 7 (fn-recovery-profile-envelope)))
; Entry uses the actual saved image target and retained ATS receipt. Native
; passes only the original borrowed open path; source is selected core-side.
; SAME image buffer identity is the registered caller boundary, not capacity.
(defun fn-owner-page-file-open-begin
 (path slot turn fn-page-file-open fn-recovery-profile-buffer
       fn-page-read-pool fn-allocation-turn-slots state)
 (declare (xargs :stobjs (fn-page-file-open fn-recovery-profile-buffer
                         fn-page-read-pool fn-allocation-turn-slots state)
                  :guard t :verify-guards nil))
 (if (not (and (eq (fn-pfo-phase fn-page-file-open) :uninstalled)
                (eq (fn-prp-mode fn-page-read-pool) :served)
                (stringp path) (natp slot) (natp turn)
                (equal (fn-rpf-bytes-length fn-recovery-profile-buffer)
                       *fn-pfo-workspace-size*)
                (fn-ats-role-bodyp slot turn :recovery-file-issue
                                  fn-allocation-turn-slots fn-page-read-pool)))
  (mv :recovery-file-binding-unavailable fn-page-file-open fn-allocation-turn-slots)
  (mv-let (word source)
   (fn-owner-runtime-operation-source :recovery-file-issue fn-page-read-pool state)
   (if (not (eq word :runtime-operation-available))
    (mv word fn-page-file-open fn-allocation-turn-slots)
    (let* ((intent (list :file-initializing path source slot turn))
           (fn-page-file-open (update-fn-pfo-pending intent fn-page-file-open))
           (fn-page-file-open (update-fn-pfo-phase :initializing fn-page-file-open))
           (fn-page-file-open (update-fn-pfo-path path fn-page-file-open))
           (fn-page-file-open (update-fn-pfo-source source fn-page-file-open))
           (fn-page-file-open (update-fn-pfo-slot slot fn-page-file-open))
           (fn-page-file-open (update-fn-pfo-turn turn fn-page-file-open))
           (fn-page-file-open (update-fn-pfo-phase :ready fn-page-file-open)))
     (mv :recovery-file-ready fn-page-file-open fn-allocation-turn-slots))))))
; No scan: fresh newNEXT identifies an incarnation in the genuine freshpool
; shared-issuance invariant. This subject consumes original PRS result/effects.
(defun fn-pfo-issue (ledger demand)
 (declare (xargs :guard t))
 (if (not (and (fn-prs-vectorp demand)
               (equal (fn-prl-nth 2 demand) 1)
               (equal (fn-prl-nth 3 demand) 0)
               (equal (fn-prl-nth 4 demand) 1)))
  (mv :invalid-file-demand nil ledger)
  (mv-let (word next charged)
   (fn-prs-issue (fn-prl-nth 0 ledger) (fn-prl-baseline ledger)
                 '(0 0 0 0 0) (fn-prl-nth 1 ledger) (fn-prl-nth 2 ledger)
                 (fn-prl-nth 4 (fn-prl-nth 0 ledger)) demand)
   (if (not (eq word :admitted)) (mv word nil ledger)
    (let* ((retained (list (fn-prl-nth 0 demand) (fn-prl-nth 1 demand) 1 0 0))
           (token (list :incarnation next))
           (binding (cons token (list retained :incarnation nil)))
           (ledger (fn-prl-build (fn-prl-nth 0 ledger) charged next
                                 (cons binding (fn-prl-nth 3 ledger))
                                 (fn-prl-nth 4 ledger))))
     (mv :admitted token ledger))))))
(verify-guards fn-pfo-issue)
; Actual caller-derived source registration belongs to the genuine installer.
; A nonnil path/slot alone is NEVER allocation authority.
(defun fn-owner-page-file-open-step
 (fuel fn-page-file-open fn-recovery-profile-buffer fn-page-read-pool fn-allocation-turn-slots state)
 (declare (xargs :stobjs (fn-page-file-open fn-recovery-profile-buffer fn-page-read-pool fn-allocation-turn-slots state)
                 :guard (natp fuel) :verify-guards nil))
 (cond
  ((zp fuel) (mv :yield nil fuel fn-page-file-open fn-page-read-pool fn-allocation-turn-slots))
  ((not (eq (fn-prp-mode fn-page-read-pool) :served))
   (mv :file-recovery-required nil fuel fn-page-file-open fn-page-read-pool fn-allocation-turn-slots))
  ((not (and (natp (fn-pfo-slot fn-page-file-open))
              (natp (fn-pfo-turn fn-page-file-open))
              (fn-ats-role-bodyp (fn-pfo-slot fn-page-file-open)
                                (fn-pfo-turn fn-page-file-open)
                                :recovery-file-issue fn-allocation-turn-slots
                                fn-page-read-pool)))
   (mv :recovery-file-source-unavailable nil fuel fn-page-file-open
       fn-page-read-pool fn-allocation-turn-slots))
  ((eq (fn-pfo-phase fn-page-file-open) :ready)
   (let ((slot (fn-pfo-slot fn-page-file-open)) (turn (fn-pfo-turn fn-page-file-open)))
    (if (not (and (natp slot) (natp turn) (stringp (fn-pfo-path fn-page-file-open))
                  (fn-ats-role-bodyp slot turn :recovery-file-issue fn-allocation-turn-slots fn-page-read-pool)))
     (mv :recovery-file-source-unavailable nil fuel fn-page-file-open fn-page-read-pool fn-allocation-turn-slots)
     (mv-let (source-word resources) (fn-owner-runtime-operation-resources :recovery-file-issue fn-page-read-pool state)
      (if (not (eq source-word :runtime-operation-available))
       (mv source-word nil fuel fn-page-file-open fn-page-read-pool fn-allocation-turn-slots)
       (mv-let (word token ledger) (fn-pfo-issue (fn-owner-page-read-ledger fn-page-read-pool) resources)
        (if (not (eq word :admitted))
         (mv word nil fuel fn-page-file-open fn-page-read-pool fn-allocation-turn-slots)
         (let* ((continuation (list :file-issue token resources
                                    (fn-pfo-source fn-page-file-open)
                                    (fn-pfo-path fn-page-file-open) ledger))
                (fn-page-file-open (update-fn-pfo-pending continuation fn-page-file-open))
                (fn-page-file-open (update-fn-pfo-phase :publishing fn-page-file-open)))
          (mv-let (publish receipt fn-page-read-pool)
           (fn-owner-page-read-bindings-begin ledger
             (fn-owner-page-read-binding-revision fn-page-read-pool)
             (fn-prl-nth 1 token) :recovery-file-issue continuation fn-page-read-pool state)
           (if (not (eq publish :binding-publishing))
            (let ((fn-page-file-open (update-fn-pfo-phase :fenced fn-page-file-open)))
             (mv publish nil fuel fn-page-file-open fn-page-read-pool fn-allocation-turn-slots))
            (let* ((effect (list :file-open token (fn-pfo-path fn-page-file-open)))
                   (fn-page-file-open (update-fn-pfo-file token fn-page-file-open))
                   (fn-page-file-open (update-fn-pfo-claim resources fn-page-file-open))
                   (fn-page-file-open (update-fn-pfo-pending effect fn-page-file-open))
                   (fn-page-file-open (update-fn-pfo-phase :open-pending fn-page-file-open)))
             (mv-let (finish fn-page-read-pool)
              (fn-owner-page-read-bindings-finish receipt fn-page-read-pool)
              (if (eq finish :published)
               (mv :file-open effect (- fuel 1) fn-page-file-open fn-page-read-pool fn-allocation-turn-slots)
               (let ((fn-page-file-open (update-fn-pfo-phase :fenced fn-page-file-open)))
                (mv finish nil fuel fn-page-file-open fn-page-read-pool fn-allocation-turn-slots))))))))))))))
)
  ((and (eq (fn-pfo-phase fn-page-file-open) :reading)
        (>= (fn-pfo-count fn-page-file-open)
            (fn-rpf-bytes-length fn-recovery-profile-buffer)))
   (let* ((fn-page-file-open (update-fn-pfo-result '(:rejected) fn-page-file-open))
          (fn-page-file-open (update-fn-pfo-phase :decoded fn-page-file-open)))
    (mv :profile-overflow nil fuel fn-page-file-open fn-page-read-pool fn-allocation-turn-slots)))
  ((eq (fn-pfo-phase fn-page-file-open) :reading)
   (let* ((count (fn-pfo-count fn-page-file-open))
          (end (min (fn-rpf-bytes-length fn-recovery-profile-buffer) (+ 64 count)))
          (effect (list :file-read (fn-pfo-file fn-page-file-open) count end (- end count)))
          (fn-page-file-open (update-fn-pfo-pending effect fn-page-file-open))
          (fn-page-file-open (update-fn-pfo-phase :read-pending fn-page-file-open)))
    (mv :file-read effect (- fuel 1) fn-page-file-open fn-page-read-pool fn-allocation-turn-slots)))
  ((eq (fn-pfo-phase fn-page-file-open) :eof)
   (let* ((count (fn-pfo-count fn-page-file-open))
          (result (if (<= count *fn-rpf-file-limit*)
                      (fn-spo-config-open (fn-rpf-prefix count fn-recovery-profile-buffer))
                    '(:rejected)))
          (fn-page-file-open (update-fn-pfo-result result fn-page-file-open))
          (fn-page-file-open (update-fn-pfo-phase :decoded fn-page-file-open)))
    (mv :profile-result result (- fuel 1) fn-page-file-open fn-page-read-pool fn-allocation-turn-slots)))
  ((eq (fn-pfo-phase fn-page-file-open) :decoded)
   (let* ((effect (list :file-close (fn-pfo-file fn-page-file-open)))
          (fn-page-file-open (update-fn-pfo-pending effect fn-page-file-open))
          (fn-page-file-open (update-fn-pfo-phase :close-pending fn-page-file-open)))
    (mv :file-close effect (- fuel 1) fn-page-file-open fn-page-read-pool fn-allocation-turn-slots)))
  (t (mv :file-pending nil fuel fn-page-file-open fn-page-read-pool fn-allocation-turn-slots))))

; Called only with the actual primitive observation in the serialized owner
; action. No caller-supplied EOF/ready flag; zero successful read is EOF.
(defun fn-owner-page-file-open-observe
 (token expected-start expected-end io-word count fn-page-file-open fn-page-read-pool fn-allocation-turn-slots)
 (declare (xargs :stobjs (fn-page-file-open fn-page-read-pool fn-allocation-turn-slots)
                 :guard t :verify-guards nil))
 (let ((pending (fn-pfo-pending fn-page-file-open)))
  (cond
   ((not (and (eq (fn-prp-mode fn-page-read-pool) :served)
               (natp (fn-pfo-slot fn-page-file-open))
               (natp (fn-pfo-turn fn-page-file-open))
               (fn-ats-role-bodyp (fn-pfo-slot fn-page-file-open)
                                 (fn-pfo-turn fn-page-file-open)
                                 :recovery-file-issue fn-allocation-turn-slots
                                 fn-page-read-pool)
               (fn-prb-fixed-widthp 2 token)
               (eq (fn-prl-nth 0 token) :incarnation)
               (natp (fn-prl-nth 1 token))
               (equal (fn-prl-nth 1 token) (fn-prl-nth 1 (fn-pfo-file fn-page-file-open)))))
    (mv :stale-file-observation fn-page-file-open))
   ((and (eq (fn-pfo-phase fn-page-file-open) :close-pending)
         (eq io-word :closed) (equal count 0))
    ; Physical close is recorded, but the incarnation binding/claim remains
    ; until its actual last registered source/descriptor alias has returned.
    (let* ((fn-page-file-open (update-fn-pfo-pending nil fn-page-file-open))
           (fn-page-file-open (update-fn-pfo-phase :closed fn-page-file-open)))
     (mv :file-closed-retained fn-page-file-open)))
   ((and (eq (fn-pfo-phase fn-page-file-open) :open-pending)
         (eq io-word :opened) (natp count))
    (let* ((fn-page-file-open (update-fn-pfo-pending nil fn-page-file-open))
           (fn-page-file-open (update-fn-pfo-phase :reading fn-page-file-open)))
     (mv :file-opened fn-page-file-open)))
   ((and (eq (fn-pfo-phase fn-page-file-open) :read-pending)
         (fn-prb-fixed-widthp 5 pending)
         (eq (fn-prl-nth 0 pending) :file-read)
         (equal expected-start (fn-prl-nth 2 pending))
         (equal expected-end (fn-prl-nth 3 pending))
         (natp count) (natp (fn-prl-nth 2 pending))
         (natp (fn-prl-nth 3 pending))
         (<= (fn-prl-nth 2 pending) (fn-prl-nth 3 pending))
         (natp (fn-prl-nth 4 pending))
         (equal (fn-prl-nth 4 pending)
                (- (fn-prl-nth 3 pending) (fn-prl-nth 2 pending)))
         (<= count (fn-prl-nth 4 pending))
         (eq io-word :read))
    (let* ((total (+ (fn-prl-nth 2 pending) count))
           (fn-page-file-open (update-fn-pfo-count total fn-page-file-open))
           (fn-page-file-open (update-fn-pfo-eof (equal count 0) fn-page-file-open))
           (fn-page-file-open (update-fn-pfo-pending nil fn-page-file-open))
           (fn-page-file-open (update-fn-pfo-phase (if (equal count 0) :eof :reading) fn-page-file-open)))
     (mv :file-read-recorded fn-page-file-open)))
   ((and (eq (fn-pfo-phase fn-page-file-open) :read-pending)
         (or (not (equal expected-start (fn-prl-nth 2 pending)))
             (not (equal expected-end (fn-prl-nth 3 pending)))))
    (mv :stale-file-observation fn-page-file-open))
   ((not (member-eq (fn-pfo-phase fn-page-file-open)
                    '(:open-pending :read-pending :close-pending)))
    (mv :stale-file-observation fn-page-file-open))
   (t
    ; Unknown/failing primitive outcome retains pending plan, source and claim.
    (let ((fn-page-file-open (update-fn-pfo-phase :fenced fn-page-file-open)))
     (mv :file-observation-uncertain fn-page-file-open))))))
