; Compile-time assembly only. These definitions confer no phase evidence or
; admission authority; all positive statuses originate in actual protocol roots.
(in-package "ACL2")
(defun fn-roc-at (n x)
 (declare (xargs :guard (natp n)))
 (if (consp x) (if (zp n) (car x) (fn-roc-at (1- n) (cdr x))) nil))
(defun fn-roc-family
 (kind runtime image profile association source primary caller firstuse
  collector external control retained cleanup)
 (declare (xargs :guard t))
 (list :runtime-operation-family kind runtime image profile association source
       primary caller firstuse collector external control retained cleanup))
(defun fn-roc-positive-entryp (entry)
 (declare (xargs :guard t))
 (equal (fn-roc-at 1 entry) :compiled-operation-source))
(defun fn-roc-binding-of-entry (entry)
 (declare (xargs :guard t))
 (let ((family (fn-roc-at 2 entry)))
  (list :compiled-operation-binding (fn-roc-at 2 family)
        (fn-roc-at 3 family) (fn-roc-at 4 family) (fn-roc-at 5 family))))
(defun fn-roc-first-binding (table)
 (declare (xargs :guard t))
 (if (consp table)
     (if (fn-roc-positive-entryp (car table))
         (fn-roc-binding-of-entry (car table))
       (fn-roc-first-binding (cdr table))) nil))
(defun fn-roc-binding-consistentp (binding table)
 (declare (xargs :guard t))
 (if (consp table)
     (and (or (not (fn-roc-positive-entryp (car table)))
              (equal binding (fn-roc-binding-of-entry (car table))))
          (fn-roc-binding-consistentp binding (cdr table)))
   (null table)))
(defun fn-roc-compiled-binding (table)
 (declare (xargs :guard t))
 (let ((binding (fn-roc-first-binding table)))
  (and binding (fn-roc-binding-consistentp binding table) binding)))
(defun fn-roc-entry (kind table)
 (declare (xargs :guard t))
 (if (consp table)
     (if (and (consp (car table)) (equal kind (caar table)))
         (car table)
       (fn-roc-entry kind (cdr table)))
   nil))

(defun fn-roc-positive-kinds (table)
 (declare (xargs :guard t))
 (if (consp table)
     (if (fn-roc-positive-entryp (car table))
         (cons (fn-roc-at 0 (car table))
               (fn-roc-positive-kinds (cdr table)))
       (fn-roc-positive-kinds (cdr table))) nil))
(defun fn-roc-slot-rows (kinds index)
 (declare (xargs :guard (natp index)))
 (if (consp kinds)
     (cons (list (car kinds) index)
           (fn-roc-slot-rows (cdr kinds) (+ 1 index))) nil))

; Protocol roots supply executor roles independently of family operation kinds.
; This build-only projection never infers a role from a request or role table.
(defun fn-roc-executor-kinds (rows)
 (declare (xargs :guard t))
 (if (consp rows)
  (let* ((row (car rows)) (role (fn-roc-at 1 row))
         (rest (fn-roc-executor-kinds (cdr rows))))
   (if (and (consp row) (symbolp role) role
            (not (member-equal role rest))) (cons role rest) rest)) nil))
(defun fn-roc-operation-slots (rows role-slots)
 (declare (xargs :guard t))
 (if (consp rows)
  (let* ((row (car rows))
         (slot (fn-roc-entry (fn-roc-at 1 row) role-slots)))
   (if (and (consp row) (consp slot))
       (cons (list (fn-roc-at 0 row) (fn-roc-at 1 slot))
             (fn-roc-operation-slots (cdr rows) role-slots))
     (fn-roc-operation-slots (cdr rows) role-slots))) nil))

(in-theory (disable fn-roc-entry fn-roc-at fn-roc-family fn-roc-positive-entryp
                   fn-roc-binding-of-entry fn-roc-first-binding
                   fn-roc-binding-consistentp fn-roc-compiled-binding))
