; Read only the actual compiled source after its sole internal SAMEpool
; publication. Missing complete producers remain unavailable.
(in-package "ACL2")
(include-book "page-read-pool-state")
(include-book "runtime-operation-installed-source")
(defun fn-owner-runtime-operation-source (kind fn-page-read-pool state)
 (declare (xargs :stobjs (fn-page-read-pool state) :guard t))
 (if (not (fn-owner-runtime-operation-binding-currentp fn-page-read-pool state))
     (mv :runtime-operation-unavailable nil)
  (mv-let (word family roles resources) (fn-runtime-operation-compiled-source kind)
   (declare (ignore roles resources))
   (if (eq word :compiled-operation-source)
       (mv :runtime-operation-available family)
     (mv :runtime-operation-unavailable nil)))))
(defun fn-owner-runtime-operation-role-table (kind fn-page-read-pool state)
 (declare (xargs :stobjs (fn-page-read-pool state) :guard t))
 (if (not (fn-owner-runtime-operation-binding-currentp fn-page-read-pool state))
     (mv :runtime-operation-unavailable nil)
  (mv-let (word family roles resources) (fn-runtime-operation-compiled-source kind)
   (declare (ignore family resources))
   (if (eq word :compiled-operation-source)
       (mv :runtime-operation-available roles)
     (mv :runtime-operation-unavailable nil)))))
(defun fn-owner-runtime-operation-resources (kind fn-page-read-pool state)
 (declare (xargs :stobjs (fn-page-read-pool state) :guard t))
 (if (not (fn-owner-runtime-operation-binding-currentp fn-page-read-pool state))
     (mv :runtime-operation-unavailable nil)
  (mv-let (word family roles resources) (fn-runtime-operation-compiled-source kind)
   (declare (ignore family roles))
   (if (eq word :compiled-operation-source)
       (mv :runtime-operation-available resources)
     (mv :runtime-operation-unavailable nil)))))
(defun fn-owner-runtime-operation-body-cost (kind request cached fn-page-read-pool state)
 (declare (xargs :stobjs (fn-page-read-pool state) :guard t))
 (if (not (fn-owner-runtime-operation-binding-currentp fn-page-read-pool state))
     (mv :runtime-operation-unavailable nil)
  (mv-let (word cost) (fn-runtime-operation-compiled-body-cost kind request cached)
   (if (and (eq word :compiled-operation-source) (natp cost))
       (mv :runtime-operation-available cost)
     (mv :runtime-operation-unavailable nil)))))
(defun fn-owner-account-operation-resources (operation fn-page-read-pool state)
 (declare (xargs :stobjs (fn-page-read-pool state) :guard t))
 (let ((kind (case operation
              (:begin :account-adoption-begin)
              (:candidate-step :account-adoption-tick)
              (:operation-select :account-adoption-select)
              (otherwise nil))))
  (if (not kind) (mv :account-operation-resources-unavailable nil)
   (mv-let (word resources)
    (fn-owner-runtime-operation-resources kind fn-page-read-pool state)
    (if (eq word :runtime-operation-available)
        (mv :account-operation-resources-available resources)
      (mv :account-operation-resources-unavailable nil))))))
(defun fn-owner-runtime-bootstrap-source (fn-page-read-pool state)
 (declare (xargs :stobjs (fn-page-read-pool state) :guard t))
 (let ((capsule (and (boundp-global 'fn-owner-runtime-bootstrap-capsule state)
                     (f-get-global 'fn-owner-runtime-bootstrap-capsule state))))
  (if (and (fn-owner-runtime-operation-binding-currentp fn-page-read-pool state)
            capsule
            (equal (fn-aec-at 4 capsule)
                   (fn-aec-at 1 (fn-prp-alloc-installation fn-page-read-pool))))
      (mv :runtime-bootstrap-source-available capsule)
    (mv :runtime-bootstrap-source-unavailable nil))))
(defun fn-owner-runtime-bootstrap-domain (fn-page-read-pool state)
 (declare (xargs :stobjs (fn-page-read-pool state) :guard t))
 (mv-let (word capsule)
  (fn-owner-runtime-bootstrap-source fn-page-read-pool state)
  (if (eq word :runtime-bootstrap-source-available)
      (mv :runtime-bootstrap-domain (fn-aec-at 2 (fn-aec-at 3 capsule)))
    (mv :runtime-bootstrap-source-unavailable nil))))
