; fn: a read-restricted session is served the reference walk on the read the
; host calls (FILL-GROUP-ACCESS-PRIVATE-LEAK, FILL-MODERATION-ENVELOPE-READABLE).
;
; The host's read is fn-av-mca-read-span (host/owner-host.lisp
; fn-asto-mca-read-span), generated by tools/available_read_emit.py from the
; legacy chain (books/served-catalog-chain.lisp through books/owner-credits).
; Its catalog arms answer Message-ID and number forms from fn-cat, which holds
; every article; a session with a group-access rule or moderation-queue hiding
; (fn-auth-access-read, PRF-222, PKT-658, D48) must be answered from the view
; its rule projects (specs/nntp.md: "The restricted route ... is always the
; reference walk over the projected pin").  Before this book the generated
; delegate sent such a session to the catalog arms with the view as their
; archive and index, which those arms do not read: tests/acl2/served-
; available-access-tests.lisp evaluates that template and finds STAT, OVER,
; HDR, XHDR, XPAT, ARTICLE, HEAD and BODY of an excluded article answered, and
; the excluded group named in the Xref of a readable one.
;
; Per event (the keystone): for a restricted session the generated
; delegate, auth step and dispatch core ARE the reference
; (fn-scar-auth-delegate-pinned, fn-scar-auth-step-pinned,
; fn-scar-dispatch-core; books/served-carried.lisp equates the last with
; books/served.lisp's fn-served-dispatch-core), with no hypothesis but the
; host cache's fn-gacc-okp, which fn-scr-prepare-access keeps.  The right
; sides take neither fn-cat nor the catalog version: no reply to a restricted
; session depends on an article outside its view.
;
; Per read: a read every one of whose events is dispatched to a restricted
; session (fn-av-read-restrictedp, defined by the legacy fold) is the legacy
; read fn-mca-read-span, whose equations to the reference are
; fn-mca-read-span-within-the-credit-unfolds down to
; fn-scr-ocfg-read-span-is-reference-under-ocl-relation.  The restriction is
; a property of each event, not of the connection: AUTHINFO may change the
; login, and with it the rule, between two events of one read.

(in-package "ACL2")
(include-book "served-available-read")

(local (defthm fn-avac-auth-session-base-of-with-base
  (equal (fn-auth-session-base (fn-auth-with-base as b)) b)
  :hints (("Goal" :in-theory (enable fn-auth-with-base)))))

(local (defthm fn-avac-peer-session-base-of-with-base
  (equal (fn-peer-session-base (fn-peer-with-base ps b)) b)
  :hints (("Goal" :in-theory (enable fn-peer-with-base)))))

(local (defthm fn-avac-projected-of-set-cursor
  (equal (fn-nntp-session-projected (fn-nntp-set-cursor s g n))
         (fn-nntp-session-projected s))
  :hints (("Goal" :in-theory (enable fn-nntp-set-cursor)))))

(local (defthm fn-avac-access-text-of-auth-with-base
  (equal (fn-auth-access-text (fn-auth-with-base as base) config field)
         (fn-auth-access-text as config field))
  :hints (("Goal" :in-theory (enable fn-auth-with-base fn-auth-access-text
                                     fn-auth-access-login)))))

; A GROUP or LISTGROUP re-pin keeps the session's rule: it moves the
; selection, never the login, the configuration or the projection.
(defthm fn-auth-access-read-of-scr-repin
  (equal (fn-auth-access-read (fn-served-conn-session (fn-scr-repin conn fn-cat))
                              (fn-served-conn-config (fn-scr-repin conn fn-cat)))
         (fn-auth-access-read (fn-served-conn-session conn) (fn-served-conn-config conn)))
  :hints (("Goal" :in-theory (e/d (fn-scr-repin fn-scr-repin-session fn-auth-access-read
                                   fn-scr-reselect)
                                  (fn-auth-access-text fn-nntp-set-cursor fn-auth-with-base
                                   fn-peer-with-base)))))

; -----------------------------------------------------------------------------
; Per event

;; KEYSTONE (PRF-1328).  The delegate the host's read calls answers a
;; read-restricted session exactly as the reference does.
(defthm fn-av-scr-auth-delegate-restricted-is-reference
  (implies (and (fn-gacc-okp cache)
                (fn-auth-access-read as config))
           (equal (fn-av-scr-auth-delegate as live trie lver arts cache archive index verdicts
                                           config observation injection wire-event v fn-arena fn-cat)
                  (fn-scar-auth-delegate-pinned as live trie arts archive index verdicts config
                                                observation injection wire-event fn-arena)))
  :hints (("Goal" :in-theory (union-theories
                              '(fn-av-scr-auth-delegate fn-scar-auth-delegate-pinned
                                fn-scr-cached-view-is-the-view)
                              (theory 'minimal-theory)))))

(defthm fn-av-scr-auth-step-restricted-is-reference
  (implies (and (fn-gacc-okp cache)
                (fn-auth-access-read as config))
           (equal (fn-av-scr-auth-step as live trie lver arts cache archive index verdicts
                                       config observation injection wire-event v fn-arena fn-cat)
                  (fn-scar-auth-step-pinned as live trie arts archive index verdicts config
                                            observation injection wire-event fn-arena)))
  :hints (("Goal" :in-theory (union-theories
                              '(fn-av-scr-auth-step fn-scar-auth-step-pinned
                                fn-av-scr-auth-delegate-restricted-is-reference)
                              (theory 'minimal-theory)))))

;; KEYSTONE (PRF-1328).  One served event of a read-restricted connection is
;; the reference's.
(defthm fn-av-scr-dispatch-core-restricted-is-reference
  (implies (and (fn-gacc-okp cache)
                (fn-auth-access-read (fn-served-conn-session conn) (fn-served-conn-config conn)))
           (equal (fn-av-scr-dispatch-core conn event live trie lver arts cache fn-arena fn-cat)
                  (fn-scar-dispatch-core conn event live trie arts fn-arena)))
  :hints (("Goal" :in-theory (union-theories
                              '(fn-av-scr-dispatch-core fn-scar-dispatch-core
                                fn-av-scr-auth-step-restricted-is-reference)
                              (theory 'minimal-theory)))))

; The legacy chain's restricted branch is the same reference.
(defthm fn-scr-auth-delegate-restricted-is-reference
  (implies (and (fn-gacc-okp cache)
                (fn-auth-access-read as config))
           (equal (fn-scr-auth-delegate as live trie lver arts cache archive index verdicts
                                        config observation injection wire-event v fn-arena fn-cat)
                  (fn-scar-auth-delegate-pinned as live trie arts archive index verdicts config
                                                observation injection wire-event fn-arena)))
  :hints (("Goal" :in-theory (union-theories
                              '(fn-scr-auth-delegate fn-scar-auth-delegate-pinned
                                fn-scr-cached-view-is-the-view)
                              (theory 'minimal-theory)))))

(defthm fn-scr-dispatch-core-restricted-is-reference
  (implies (and (fn-gacc-okp cache)
                (fn-auth-access-read (fn-served-conn-session conn) (fn-served-conn-config conn)))
           (equal (fn-scr-dispatch-core conn event live trie lver arts cache fn-arena fn-cat)
                  (fn-scar-dispatch-core conn event live trie arts fn-arena)))
  :hints (("Goal" :in-theory (union-theories
                              '(fn-scr-dispatch-core fn-scar-dispatch-core fn-scr-auth-step
                                fn-scar-auth-step-pinned
                                fn-scr-auth-delegate-restricted-is-reference)
                              (theory 'minimal-theory)))))

; With its GROUP/LISTGROUP re-pin, the event is the legacy chain's
; (fn-scr-dispatch-is-scar-dispatch carries it to the reference).
(defthm fn-av-scr-dispatch-restricted-is-legacy
  (implies (and (fn-gacc-okp cache)
                (fn-auth-access-read (fn-served-conn-session conn) (fn-served-conn-config conn)))
           (equal (fn-av-scr-dispatch conn event live trie lver arts cache fn-arena fn-cat)
                  (fn-scr-dispatch conn event live trie lver arts cache fn-arena fn-cat)))
  :hints (("Goal" :in-theory (union-theories
                              '(fn-av-scr-dispatch fn-scr-dispatch
                                fn-av-scr-dispatch-core-restricted-is-reference
                                fn-scr-dispatch-core-restricted-is-reference
                                fn-auth-access-read-of-scr-repin)
                              (theory 'minimal-theory)))))

; -----------------------------------------------------------------------------
; Per read: the restriction holds at every event the legacy fold dispatches.

(defun fn-av-events-restrictedp (conn events live trie lver arts cache fn-arena fn-cat)
  (declare (xargs :stobjs (fn-arena fn-cat) :verify-guards nil
                  :measure (acl2-count events)))
  (if (consp events)
      (and (fn-auth-access-read (fn-served-conn-session conn) (fn-served-conn-config conn))
           (fn-av-events-restrictedp
            (fn-served-result-conn
             (fn-scr-dispatch conn (car events) live trie lver arts cache fn-arena fn-cat))
            (cdr events) live trie lver arts cache fn-arena fn-cat))
    t))

(defthm fn-av-scr-dispatch-events-restricted-is-legacy
  (implies (and (fn-gacc-okp cache)
                (fn-av-events-restrictedp conn events live trie lver arts cache fn-arena fn-cat))
           (equal (fn-av-scr-dispatch-events conn events live trie lver arts cache fn-arena fn-cat)
                  (fn-scr-dispatch-events conn events live trie lver arts cache fn-arena fn-cat)))
  :hints (("Goal" :induct (fn-av-events-restrictedp conn events live trie lver arts cache
                                                    fn-arena fn-cat)
           :in-theory (e/d (fn-av-events-restrictedp fn-av-scr-dispatch-events
                            fn-scr-dispatch-events fn-av-scr-dispatch-restricted-is-legacy)
                           (fn-av-scr-dispatch fn-scr-dispatch fn-auth-access-read)))))

(defun fn-av-byte-restrictedp (conn byte live trie lver arts cache fn-arena fn-cat)
  (declare (xargs :stobjs (fn-arena fn-cat) :verify-guards nil))
  (let ((fed (fn-wire-feed-byte (fn-served-conn-wire conn) byte)))
    (fn-av-events-restrictedp (fn-served-conn-with-wire conn (fn-wire-result-state fed))
                              (fn-wire-result-events fed) live trie lver arts cache
                              fn-arena fn-cat)))

(defthm fn-av-scr-feed-byte-restricted-is-legacy
  (implies (and (fn-gacc-okp cache)
                (fn-av-byte-restrictedp conn byte live trie lver arts cache fn-arena fn-cat))
           (equal (fn-av-scr-feed-byte conn byte live trie lver arts cache fn-arena fn-cat)
                  (fn-scr-feed-byte conn byte live trie lver arts cache fn-arena fn-cat)))
  :hints (("Goal" :in-theory (e/d (fn-av-byte-restrictedp fn-av-scr-feed-byte fn-scr-feed-byte)
                                  (fn-av-scr-dispatch-events fn-scr-dispatch-events
                                   fn-av-events-restrictedp)))))

(defun fn-av-span-restrictedp (conn i end live trie lver arts cache fn-octets fn-arena fn-cat)
  (declare (xargs :stobjs (fn-octets fn-arena fn-cat) :verify-guards nil
                  :measure (nfix (- end i))
                  :hints (("Goal" :in-theory (disable fn-scr-feed-byte fn-served-submission
                                                      fn-av-byte-restrictedp)))))
  (if (or (not (natp i)) (not (natp end)) (>= i end)
          (fn-served-closed-wirep (fn-served-conn-wire conn))
          (fn-served-haltedp conn))
      t
    (and (fn-av-byte-restrictedp conn (fn-octets-get i fn-octets) live trie lver arts cache
                                 fn-arena fn-cat)
         (let ((here (fn-scr-feed-byte conn (fn-octets-get i fn-octets) live trie lver arts cache
                                       fn-arena fn-cat)))
           (if (fn-served-submission (fn-served-result-effects here))
               t
             (fn-av-span-restrictedp (fn-served-result-conn here) (+ 1 i) end live trie lver arts
                                     cache fn-octets fn-arena fn-cat))))))

(defthm fn-av-scr-feed-span-restricted-is-legacy
  (implies (and (fn-gacc-okp cache)
                (fn-av-span-restrictedp conn i end live trie lver arts cache fn-octets fn-arena fn-cat))
           (equal (fn-av-scr-feed-span conn i end live trie lver arts cache fn-octets fn-arena fn-cat)
                  (fn-scr-feed-span conn i end live trie lver arts cache fn-octets fn-arena fn-cat)))
  :hints (("Goal" :induct (fn-av-span-restrictedp conn i end live trie lver arts cache
                                                  fn-octets fn-arena fn-cat)
           :in-theory (e/d (fn-av-span-restrictedp fn-av-scr-feed-span fn-scr-feed-span
                            fn-av-scr-feed-byte-restricted-is-legacy)
                           (fn-av-scr-feed-byte fn-scr-feed-byte fn-av-byte-restrictedp
                            fn-served-submission)))))

(defthm fn-av-scr-step-span-fast-restricted-is-legacy
  (implies (and (fn-gacc-okp cache)
                (fn-av-span-restrictedp conn i end live trie lver arts cache fn-octets fn-arena fn-cat))
           (equal (fn-av-scr-step-span-fast conn i end live trie lver arts cache fn-octets fn-arena fn-cat)
                  (fn-scr-step-span-fast conn i end live trie lver arts cache fn-octets fn-arena fn-cat)))
  :hints (("Goal" :in-theory (e/d (fn-av-scr-step-span-fast fn-scr-step-span-fast
                                   fn-av-scr-step-span-core fn-scr-step-span-core)
                                  (fn-av-scr-feed-span fn-scr-feed-span fn-av-span-restrictedp
                                   fn-av-scr-scan-span fn-scr-scan-span)))))

(defun fn-av-own-restrictedp (o id i end cache fn-octets fn-arena fn-cat)
  (declare (xargs :stobjs (fn-octets fn-arena fn-cat) :verify-guards nil))
  (let ((conn (fn-own-find-conn id (fn-own-conns o))))
    (or (not conn)
        (fn-av-span-restrictedp (fn-own-tls-served-conn o conn) i end
                                (fn-sn-node (fn-own-store o))
                                (fn-own-view-index (fn-own-view o))
                                (fn-own-view-version (fn-own-view o))
                                (fn-state-articles (fn-own-view-archive (fn-own-view o)))
                                cache fn-octets fn-arena fn-cat))))

(defun fn-av-orr-restrictedp (oc views id i end cache fn-octets fn-arena fn-cat)
  (declare (xargs :stobjs (fn-octets fn-arena fn-cat) :verify-guards nil))
  (fn-av-own-restrictedp (fn-ocfg-owner (if (consp views) (fn-ocfg-at-reader-view oc views) oc))
                         id i end cache fn-octets fn-arena fn-cat))

(defun fn-av-otm-restrictedp (oc views id i end cache s fn-octets fn-arena fn-cat)
  (declare (xargs :stobjs (fn-octets fn-arena fn-cat) :verify-guards nil))
  (fn-av-orr-restrictedp (if (eq (fn-otm-admit-post s) :shed) (fn-otm-shed-ocfg oc id) oc)
                         views id i end cache fn-octets fn-arena fn-cat))

;; The read the host calls, as configured and with posting off (the re-read
;; fn-oas-posting-off-read makes for a slot or credit refusal).
(defun fn-av-read-restrictedp (oc views id i end cache s fn-octets fn-arena fn-cat)
  (declare (xargs :stobjs (fn-octets fn-arena fn-cat) :verify-guards nil))
  (and (fn-av-otm-restrictedp oc views id i end cache s fn-octets fn-arena fn-cat)
       (fn-av-otm-restrictedp (fn-otm-owner-with-allow oc id nil) views id i end cache s
                              fn-octets fn-arena fn-cat)))

(defthm fn-av-scr-own-read-span-restricted-is-legacy
  (implies (and (fn-gacc-okp cache)
                (fn-av-own-restrictedp o id i end cache fn-octets fn-arena fn-cat))
           (equal (fn-av-scr-own-read-span o id i end cache fn-octets fn-arena fn-cat)
                  (fn-scr-own-read-span o id i end cache fn-octets fn-arena fn-cat)))
  :hints (("Goal" :in-theory (e/d (fn-av-own-restrictedp fn-av-scr-own-read-span
                                   fn-scr-own-read-span)
                                  (fn-av-scr-step-span-fast fn-scr-step-span-fast
                                   fn-av-span-restrictedp fn-own-tls-served-conn
                                   fn-scar-finish-read)))))

(defthm fn-av-orr-read-span-restricted-is-legacy
  (implies (and (fn-gacc-okp cache)
                (fn-av-orr-restrictedp oc views id i end cache fn-octets fn-arena fn-cat))
           (equal (fn-av-orr-read-span oc views id i end cache fn-octets fn-arena fn-cat)
                  (fn-orr-read-span oc views id i end cache fn-octets fn-arena fn-cat)))
  :hints (("Goal" :in-theory (e/d (fn-av-orr-restrictedp fn-av-orr-read-span fn-orr-read-span
                                   fn-av-scr-ocfg-read-span fn-scr-ocfg-read-span)
                                  (fn-av-scr-own-read-span fn-scr-own-read-span
                                   fn-av-own-restrictedp fn-ocfg-at-reader-view
                                   fn-ocfg-with-read-owner fn-ocfg-with-view)))))

(defthm fn-av-otm-read-span-restricted-is-legacy
  (implies (and (fn-gacc-okp cache)
                (fn-av-otm-restrictedp oc views id i end cache s fn-octets fn-arena fn-cat))
           (equal (fn-av-otm-read-span oc views id i end cache s fn-octets fn-arena fn-cat)
                  (fn-otm-read-span oc views id i end cache s fn-octets fn-arena fn-cat)))
  :hints (("Goal" :in-theory (e/d (fn-av-otm-restrictedp fn-av-otm-read-span fn-otm-read-span)
                                  (fn-av-orr-read-span fn-orr-read-span fn-av-orr-restrictedp
                                   fn-otm-shed-ocfg fn-otm-admit-post fn-otm-conn-allow
                                   fn-otm-disk-effects fn-otm-unshed-ocfg)))))

;; KEYSTONE (PRF-1328).  The host's read, on a read every event of which
;; goes to a read-restricted session, is the legacy read.
(defthm fn-av-mca-read-span-restricted-is-legacy
  (implies (and (fn-gacc-okp cache)
                (fn-av-read-restrictedp oc views id i end cache s fn-octets fn-arena fn-cat))
           (equal (fn-av-mca-read-span credits oc views id i end cache s slots reserve
                                       fn-octets fn-arena fn-cat)
                  (fn-mca-read-span credits oc views id i end cache s slots reserve
                                    fn-octets fn-arena fn-cat)))
  :hints (("Goal" :in-theory (e/d (fn-av-read-restrictedp fn-av-mca-read-span fn-mca-read-span
                                   fn-av-mca-refused-read fn-mca-refused-read
                                   fn-av-oas-read-span fn-oas-read-span
                                   fn-av-oas-posting-off-read fn-oas-posting-off-read)
                                  (fn-av-otm-read-span fn-otm-read-span fn-av-otm-restrictedp
                                   fn-mcr-resize fn-mca-need fn-mca-shut-read fn-oas-tiers
                                   fn-oas-over-p fn-oas-articlep fn-oas-close-result
                                   fn-oas-post-effects fn-otm-owner-with-allow
                                   fn-otm-conn-allow)))))
