; Generated by tools/available_read_emit.py from the actual read chain.
; LOGIC source route with its guards owed (:verify-guards nil on every form):
; the selective reference and the carried frames are owed, not borrowed from
; the legacy raw-pinned route. All request decisions remain ACL2's.
(in-package "ACL2")
(include-book "owner-credits")
(include-book "served-available-commands")

(defun fn-av-scr-step (session archive index verdicts env wire-event v fn-arena fn-cat)
  (declare (xargs :stobjs (fn-arena fn-cat)
                  :guard (and (natp v)
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))
                  :verify-guards nil))
  (if (or (not (fn-nntp-sessionp session))
          (not (equal (fn-nntp-session-openp session) t)))
      (fn-nntp-make-result session nil)
    (if (and (consp wire-event)
             (equal (car wire-event) :command)
             (consp (cdr wire-event))
             (null (cdr (cdr wire-event))))
        (let ((line (car (cdr wire-event))))
          (if (not (fn-nntp-command-inputp line))
              (fn-nntp-single session (fn-proto-text * :syntax))
            (let ((tokens (fn-nntp-tokenize line)))
              (if (and (consp tokens)
                       (fn-nntp-command-arguments-at-mostp tokens))
                  (fn-scr-command-available
                   session archive index verdicts env tokens v fn-arena fn-cat)
                (fn-nntp-single session (fn-proto-text * :syntax))))))
      (fn-nntp-single session (fn-proto-text * :syntax)))))

(defun fn-av-scr-post-step
    (ps archive index verdicts config observation injection wire-event v fn-arena fn-cat)
  (declare (xargs :stobjs (fn-arena fn-cat)
                  :guard (and (natp v)
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))
                  :verify-guards nil))
  (if (or (not (fn-post-sessionp ps)) (fn-post-session-awaiting ps))
      (fn-nntp-post-step ps archive config observation injection wire-event fn-arena)
    (let ((r (fn-av-scr-step
              (fn-post-session-base ps) archive index verdicts
              (fn-post-command-env config observation injection wire-event)
              wire-event v fn-arena fn-cat)))
      (if (fn-post-offeredp (fn-nntp-result-effects r))
          (if (fn-inj-config-allow config)
              (fn-post-make-result
               (fn-post-make-session (fn-nntp-result-session r) t)
               (fn-nntp-result-effects r) nil)
            (fn-post-make-result
             (fn-post-make-session (fn-nntp-result-session r) nil)
             (fn-post-single ps (fn-proto-text "POST" :not-permitted)) nil))
        (fn-post-make-result
         (fn-post-make-session (fn-nntp-result-session r) nil)
         (fn-nntp-result-effects r) nil)))))

(defun fn-av-scr-peer-delegate
    (ps archive index verdicts config observation injection wire-event v fn-arena fn-cat)
  (declare (xargs :stobjs (fn-arena fn-cat)
                  :guard (and (natp v)
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))
                  :verify-guards nil))
  (let ((r (fn-av-scr-post-step
            (fn-peer-session-base ps) archive index verdicts config
            observation injection wire-event v fn-arena fn-cat)))
    (fn-post-make-result (fn-peer-with-base ps (fn-post-result-session r))
                         (fn-post-result-effects r)
                         (fn-post-result-submission r))))

(defun fn-av-scr-peer-arm
    (ps lver arts archive index verdicts config observation injection wire-event v fn-arena fn-cat)
  (declare (xargs :stobjs (fn-arena fn-cat)
                  :guard (and (fn-pgc-peer-sessionp ps)
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))
                  :verify-guards nil))
  (cond
   ((not (equal (fn-nntp-session-openp (fn-peer-reader-session ps)) t))
    (fn-av-scr-peer-delegate ps archive index verdicts config observation
                                 injection wire-event v fn-arena fn-cat))
   ((fn-peer-session-transfer ps) (fn-pgc-transfer-step ps wire-event))
   ((and (consp wire-event)
         (equal (car wire-event) :command)
         (consp (cdr wire-event))
         (null (cdr (cdr wire-event)))
         (fn-nntp-command-inputp (car (cdr wire-event))))
    (let ((tokens (fn-nntp-tokenize (car (cdr wire-event)))))
      (if (and (consp tokens)
               (fn-nntp-keyword-tokenp (car tokens))
               (fn-nntp-command-arguments-at-mostp tokens))
          (let ((r (fn-scr-peer-command ps (car tokens) (cdr tokens) lver arts fn-arena fn-cat)))
            (if r r
              (fn-av-scr-peer-delegate ps archive index verdicts config
                                           observation injection wire-event v fn-arena fn-cat)))
        (fn-av-scr-peer-delegate ps archive index verdicts config observation
                                     injection wire-event v fn-arena fn-cat))))
   (t (fn-av-scr-peer-delegate ps archive index verdicts config observation
                                   injection wire-event v fn-arena fn-cat))))

(defun fn-av-scr-peer-step
    (ps live trie lver arts archive index verdicts config observation injection wire-event
        v fn-arena fn-cat)
  ; TRIE is kept for the equation with the scar layer (whose peer arm reads
  ; it); the catalog's arm reads LVER instead.
  (declare (xargs :stobjs (fn-arena fn-cat)
                  :guard (and (natp v)
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))
                  :verify-guards nil)
           (ignorable trie))
  (cond
   ((not (fn-scar-peer-sessionp ps live)) (fn-post-make-result ps nil nil))
   ((null (fn-peer-session-peer ps))
    (fn-av-scr-peer-delegate ps archive index verdicts config observation
                          injection wire-event v fn-arena fn-cat))
   (t (fn-av-scr-peer-arm ps lver arts archive index verdicts config
                       observation injection wire-event v fn-arena fn-cat))))

(defun fn-av-scr-auth-delegate
    (as live trie lver arts cache archive index verdicts config observation injection wire-event
        v fn-arena fn-cat)
  (declare (xargs :stobjs (fn-arena fn-cat) :verify-guards nil))
  (let* ((restricted (fn-auth-access-read as config))
         (view (and restricted (fn-scr-cached-view as config archive index cache)))
         (a (if restricted (if view (fn-ag-car view)
                             (fn-auth-view-archive as config archive)) archive))
         (ix (if restricted (if view (fn-ag-cdr view)
                              (fn-auth-view-index as config archive index)) index))
         (r (fn-av-scr-peer-step
             (fn-auth-view-session as config) live trie lver arts a ix verdicts
             (fn-auth-view-config as (fn-auth-moderation-config as config) archive)
             observation injection wire-event v fn-arena fn-cat)))
    (fn-post-make-result (fn-auth-with-base as (fn-post-result-session r))
                         (fn-post-result-effects r) (fn-post-result-submission r))))

(defun fn-av-scr-auth-step
    (as live trie lver arts cache archive index verdicts config observation injection wire-event
        v fn-arena fn-cat)
  (declare (xargs :stobjs (fn-arena fn-cat)
                  :guard (and (natp v)
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))
                  :verify-guards nil))
  (cond
   ((not (fn-scar-auth-sessionp as live)) (fn-post-make-result as nil nil))
   ((fn-auth-tls-eventp wire-event) (fn-auth-tls-established as))
   ((and (fn-auth-redeem-eventp wire-event) (fn-auth-redeem-waitp as))
    (fn-auth-redeem-outcome as wire-event))
   ((fn-auth-session-handshakingp as) (fn-post-make-result as nil nil))
   ((fn-auth-context-eventp wire-event) (fn-auth-install-context as wire-event))
   ((and (fn-auth-sasl-waitingp as)
         (consp wire-event) (equal (car wire-event) :command)
         (consp (cdr wire-event)) (null (cdr (cdr wire-event))))
    (fn-auth-sasl-continue as (car (cdr wire-event))))
   ((and (consp wire-event)
         (equal (car wire-event) :command)
         (consp (cdr wire-event))
         (null (cdr (cdr wire-event)))
         (fn-nntp-command-inputp (car (cdr wire-event))))
    (let ((tokens (fn-nntp-tokenize (car (cdr wire-event)))))
      (if (and (consp tokens)
               (fn-nntp-keyword-tokenp (car tokens))
               (fn-nntp-command-arguments-at-mostp tokens))
          (let ((r (fn-auth-command as config (car tokens) (cdr tokens))))
            (if r r
              (fn-av-scr-auth-delegate as live trie lver arts cache archive index verdicts config
                                    observation injection wire-event v fn-arena fn-cat)))
        (fn-av-scr-auth-delegate as live trie lver arts cache archive index verdicts config observation
                              injection wire-event v fn-arena fn-cat))))
   ((fn-auth-client-eventp wire-event)
    (fn-av-scr-auth-delegate as live trie lver arts cache archive index verdicts config observation
                            injection wire-event v fn-arena fn-cat))
   (t (fn-post-make-result as nil nil))))

(defun fn-av-scr-dispatch-core (conn event live trie lver arts cache fn-arena fn-cat)
  (declare (xargs :stobjs (fn-arena fn-cat)
                  :guard (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat)
                  :verify-guards nil))
  (let* ((v (fn-scr-view-of (fn-served-pinned-version (fn-served-conn-pinned conn)) fn-cat))
         (r (fn-av-scr-auth-step (fn-served-conn-session conn) live trie lver arts cache
                              (fn-served-conn-archive conn)
                              (fn-served-conn-pinned-index conn)
                              (fn-served-conn-verdicts conn)
                              (fn-served-conn-config conn)
                              (fn-served-conn-observation conn)
                              (fn-served-conn-injection conn)
                              event v fn-arena fn-cat))
         (effects (fn-post-result-effects r))
         (submission (fn-post-result-submission r))
         (wire (fn-served-conn-wire conn))
         (wire2 (if (fn-post-offeredp effects)
                    (fn-wire-result-state
                     (fn-wire-begin-article-with-line-limit
                      wire (fn-wire-article-line-limit wire)))
                  wire)))
    (fn-served-make-result
     (fn-served-make-conn-live wire2 (fn-post-result-session r)
                          (fn-served-conn-archive conn)
                          (fn-served-conn-config conn)
                          (fn-served-conn-observation conn)
                          (fn-served-conn-injection conn)
                          (fn-served-conn-verdicts conn)
                          (fn-served-conn-index conn)
                          (fn-served-conn-group-index conn) (fn-served-conn-control conn)
                          (fn-served-conn-pinned conn) (fn-served-conn-live conn))
     (mbe :logic (append effects
                         (if submission
                             (list (fn-served-submit-effect submission (fn-served-login (fn-served-conn-session conn))
                                (fn-served-account (fn-served-conn-session conn))))
                           nil))
          :exec (fn-ag-append effects
                              (if submission
                                  (list (fn-served-submit-effect submission (fn-served-login (fn-served-conn-session conn))
                                (fn-served-account (fn-served-conn-session conn))))
                                nil))))))

(defun fn-av-scr-dispatch (conn event live trie lver arts cache fn-arena fn-cat)
  (declare (xargs :stobjs (fn-arena fn-cat)
                  :guard (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat)
                  :verify-guards nil))
  (if (fn-served-advance-eventp event)
      (let ((r (fn-av-scr-dispatch-core (fn-scr-repin conn fn-cat) event live trie lver arts cache fn-arena fn-cat)))
        (if (fn-served-selectedp (fn-served-result-effects r))
            r
          (fn-served-make-result
           (fn-served-conn-with-wire conn (fn-served-conn-wire (fn-served-result-conn r)))
           (fn-served-result-effects r))))
    (fn-av-scr-dispatch-core conn event live trie lver arts cache fn-arena fn-cat)))

(defun fn-av-scr-dispatch-events-loop (conn events live trie lver arts cache fn-arena fn-cat acc)
  (declare (xargs :stobjs (fn-arena fn-cat)
                  :guard (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat)
                  :verify-guards nil))
  (if (consp events)
      (let ((here (fn-av-scr-dispatch conn (car events) live trie lver arts cache fn-arena fn-cat)))
        (fn-av-scr-dispatch-events-loop
         (fn-served-result-conn here) (cdr events) live trie lver arts cache fn-arena fn-cat
         (fn-ag-rev-onto (fn-served-result-effects here) acc)))
    (fn-served-make-result conn (fn-ag-rev-onto acc nil))))

(defun fn-av-scr-dispatch-events (conn events live trie lver arts cache fn-arena fn-cat)
  (declare (xargs :stobjs (fn-arena fn-cat)
                  :guard (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat)
                  :verify-guards nil))
  (mbe :logic
  (if (consp events)
      (let* ((here (fn-av-scr-dispatch conn (car events) live trie lver arts cache fn-arena fn-cat))
             (tail (fn-av-scr-dispatch-events (fn-served-result-conn here)
                                           (cdr events) live trie lver arts cache fn-arena fn-cat)))
        (fn-served-make-result
         (fn-served-result-conn tail)
         (mbe :logic (append (fn-served-result-effects here)
                             (fn-served-result-effects tail))
              :exec (fn-ag-append (fn-served-result-effects here)
                                  (fn-served-result-effects tail)))))
    (fn-served-make-result conn nil))
  :exec (fn-av-scr-dispatch-events-loop conn events live trie lver arts cache fn-arena fn-cat nil)))

(defun fn-av-scr-feed-byte (conn byte live trie lver arts cache fn-arena fn-cat)
  (declare (xargs :stobjs (fn-arena fn-cat)
                  :guard (and (fn-wire-fast-statep (fn-served-conn-wire conn))
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))
                  :verify-guards nil))
  (let ((fed (fn-wire-feed-byte (fn-served-conn-wire conn) byte)))
    (fn-av-scr-dispatch-events
     (fn-served-conn-with-wire conn (fn-wire-result-state fed))
     (fn-wire-result-events fed) live trie lver arts cache fn-arena fn-cat)))

(defun fn-av-scr-feed-span (conn i end live trie lver arts cache fn-octets fn-arena fn-cat)
  (declare (xargs :stobjs (fn-octets fn-arena fn-cat)
                  :guard (and (fn-wire-fast-statep (fn-served-conn-wire conn))
                              (natp i) (natp end) (<= i end)
                              (<= end (fn-octets-len fn-octets))
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))
                  :measure (nfix (- end i))
                  :verify-guards nil
                  :hints (("Goal" :in-theory (disable fn-av-scr-feed-byte
                                                      fn-served-submission)))))
  (if (or (not (natp i)) (not (natp end)) (>= i end)
          (fn-served-closed-wirep (fn-served-conn-wire conn))
          (fn-served-haltedp conn))
      (fn-served-counted-make 0 (fn-served-make-result conn nil))
    (let ((here (fn-av-scr-feed-byte conn (fn-octets-get i fn-octets) live trie lver arts cache fn-arena fn-cat)))
      (if (fn-served-submission (fn-served-result-effects here))
          (fn-served-counted-make
           1 (fn-served-make-result (fn-served-result-conn here)
                                    (fn-served-result-effects here)))
        (let* ((tail (fn-av-scr-feed-span (fn-served-result-conn here) (+ 1 i) end
                                       live trie lver arts cache fn-octets fn-arena fn-cat))
               (result (fn-served-counted-result tail)))
          (fn-served-counted-make
           (+ 1 (fn-served-counted-consumed tail))
           (fn-served-make-result
            (fn-served-result-conn result)
            (mbe :logic (append (fn-served-result-effects here)
                                (fn-served-result-effects result))
                 :exec (fn-ag-append (fn-served-result-effects here)
                                     (fn-served-result-effects result))))))))))

(defun fn-av-scr-scan-span-loop (conn i end live trie lver arts cache fn-octets fn-arena fn-cat
                                   consumed acc)
  (declare (xargs :stobjs (fn-octets fn-arena fn-cat)
                  :guard (and (fn-wire-fast-statep (fn-served-conn-wire conn))
                              (natp i) (natp end) (<= i end)
                              (<= end (fn-octets-len fn-octets))
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat)
                              (acl2-numberp consumed))
                  :measure (nfix (- end i))
                  :verify-guards nil
                  :hints (("Goal" :in-theory (disable fn-av-scr-dispatch-events
                                                      fn-served-submission)))))
  (if (or (not (natp i)) (not (natp end)) (>= i end)
          (fn-served-closed-wirep (fn-served-conn-wire conn))
          (fn-served-haltedp conn))
      (fn-served-counted-make consumed (fn-served-make-result conn (fn-ag-rev-onto acc nil)))
    (let* ((w (fn-wire-scan (fn-served-conn-wire conn) i end fn-octets))
           (next (fn-wsp-next w))
           (here (fn-av-scr-dispatch-events
                  (fn-served-conn-with-wire conn (fn-wsp-state w))
                  (fn-wsp-events w) live trie lver arts cache fn-arena fn-cat)))
      (if (fn-served-submission (fn-served-result-effects here))
          (fn-served-counted-make
           (+ consumed (- next i))
           (fn-served-make-result (fn-served-result-conn here)
                                  (fn-ag-rev-onto acc (fn-served-result-effects here))))
        (fn-av-scr-scan-span-loop (fn-served-result-conn here) next end
                               live trie lver arts cache fn-octets fn-arena fn-cat
                               (+ consumed (- next i))
                               (fn-ag-rev-onto (fn-served-result-effects here) acc))))))

(defun fn-av-scr-scan-span (conn i end live trie lver arts cache fn-octets fn-arena fn-cat)
  (declare (xargs :stobjs (fn-octets fn-arena fn-cat)
                  :guard (and (fn-wire-fast-statep (fn-served-conn-wire conn))
                              (natp i) (natp end) (<= i end)
                              (<= end (fn-octets-len fn-octets))
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))
                  :measure (nfix (- end i))
                  :verify-guards nil
                  :hints (("Goal" :in-theory (disable fn-av-scr-dispatch-events
                                                      fn-served-submission)))))
  (mbe :logic
  (if (or (not (natp i)) (not (natp end)) (>= i end)
          (fn-served-closed-wirep (fn-served-conn-wire conn))
          (fn-served-haltedp conn))
      (fn-served-counted-make 0 (fn-served-make-result conn nil))
    (let* ((w (fn-wire-scan (fn-served-conn-wire conn) i end fn-octets))
           (next (fn-wsp-next w))
           (here (fn-av-scr-dispatch-events
                  (fn-served-conn-with-wire conn (fn-wsp-state w))
                  (fn-wsp-events w) live trie lver arts cache fn-arena fn-cat)))
      ;; PKT-600: yield after the event that completed a submission; the host
      ;; re-enters at i + consumed.
      (if (fn-served-submission (fn-served-result-effects here))
          (fn-served-counted-make
           (- next i)
           (fn-served-make-result (fn-served-result-conn here)
                                  (fn-served-result-effects here)))
        (let* ((tail (fn-av-scr-scan-span (fn-served-result-conn here) next end
                                       live trie lver arts cache fn-octets fn-arena fn-cat))
               (tail-result (fn-served-counted-result tail)))
          (fn-served-counted-make
           (+ (- next i) (fn-served-counted-consumed tail))
           (fn-served-make-result
            (fn-served-result-conn tail-result)
            (mbe :logic (append (fn-served-result-effects here)
                                (fn-served-result-effects tail-result))
                 :exec (fn-ag-append (fn-served-result-effects here)
                                     (fn-served-result-effects tail-result)))))))))
  :exec (fn-av-scr-scan-span-loop conn i end live trie lver arts cache fn-octets fn-arena fn-cat 0 nil)))

(defun fn-av-scr-step-span-core (conn i end live trie lver arts cache fn-octets fn-arena fn-cat)
  (declare (xargs :verify-guards nil :stobjs (fn-octets fn-arena fn-cat)
                  :guard (and (fn-wire-fast-statep (fn-served-conn-wire conn))
                              (natp i) (natp end) (<= i end)
                              (<= end (fn-octets-len fn-octets))
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))))
  (let* ((wire (fn-served-conn-wire conn))
         ;; PKT-479: executed one framed event at a time (fn-av-scr-scan-span,
         ;; equal to the byte fold by fn-scr-scan-span-is-feed-span).
         (fed (mbe :logic (fn-av-scr-feed-span conn i end live trie lver arts cache fn-octets fn-arena fn-cat)
                   :exec (fn-av-scr-scan-span conn i end live trie lver arts cache fn-octets fn-arena fn-cat)))
         (result (fn-served-counted-result fed))
         (wire2 (fn-served-conn-wire (fn-served-result-conn result))))
    (fn-served-counted-make
     (fn-served-counted-consumed fed)
     (fn-served-make-result
      (fn-served-result-conn result)
      (mbe :logic
           (append (fn-served-result-effects result)
                   (if (and (not (fn-served-closed-wirep wire))
                            (fn-served-closed-wirep wire2))
                       (list (fn-nntp-close-effect))
                     nil))
           :exec
           (fn-ag-append
            (fn-served-result-effects result)
            (if (and (not (fn-served-closed-wirep wire))
                     (fn-served-closed-wirep wire2))
                (list (fn-nntp-close-effect))
              nil)))))))

(defun fn-av-scr-step-span-fast (conn i end live trie lver arts cache fn-octets fn-arena fn-cat)
  (declare (xargs :verify-guards nil :stobjs (fn-octets fn-arena fn-cat)
                  :guard (and (natp i) (natp end) (<= i end)
                              (<= end (fn-octets-len fn-octets))
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))))
  (if (not (fn-wire-fast-statep (fn-served-conn-wire conn)))
      (fn-served-counted-make 0 (fn-served-make-result conn nil))
    (fn-av-scr-step-span-core conn i end live trie lver arts cache fn-octets fn-arena fn-cat)))

(defun fn-av-scr-own-read-span (o id i end cache fn-octets fn-arena fn-cat)
  (declare (xargs :verify-guards nil :stobjs (fn-octets fn-arena fn-cat)
                  :guard (and (natp i) (natp end) (<= i end)
                              (<= end (fn-octets-len fn-octets))
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))))
  (let ((conn (fn-own-find-conn id (fn-own-conns o)))
        (live (fn-sn-node (fn-own-store o)))
        (trie (fn-own-view-index (fn-own-view o)))
        (lver (fn-own-view-version (fn-own-view o)))
        (arts (fn-state-articles (fn-own-view-archive (fn-own-view o)))))
    (if conn
        (let* ((counted
                 (fn-av-scr-step-span-fast
                  (fn-own-tls-served-conn o conn) i end live trie lver arts cache fn-octets fn-arena fn-cat))
               (result
                 (fn-scar-finish-read
                  o conn (fn-served-counted-result counted) live)))
          (fn-own-tls-make-result
           (fn-served-counted-consumed counted) (car result) (cdr result)
           (fn-own-result-repinned (fn-served-counted-result counted))))
      (fn-own-tls-make-result (nfix (- end i)) nil o nil))))

(defun fn-av-scr-ocfg-read-span (oc id i end cache fn-octets fn-arena fn-cat)
  (declare (xargs :verify-guards nil :stobjs (fn-octets fn-arena fn-cat)
                  :guard (and (natp i) (natp end) (<= i end)
                              (<= end (fn-octets-len fn-octets))
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))))
  (let ((result (fn-av-scr-own-read-span (fn-ocfg-owner oc) id i end cache fn-octets fn-arena fn-cat)))
    (fn-own-tls-make-result
     (fn-own-tls-result-consumed result)
     (fn-own-tls-result-effects result)
     (fn-ocfg-with-read-owner oc id (fn-own-tls-result-owner result)
                              (fn-own-tls-result-repinned result))
     (fn-own-tls-result-repinned result))))

(defun fn-av-orr-read-span (oc views id i end cache fn-octets fn-arena fn-cat)
  (declare (xargs :verify-guards nil :stobjs (fn-octets fn-arena fn-cat)
                  :guard (and (natp i) (natp end) (<= i end)
                              (<= end (fn-octets-len fn-octets))
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))))
  (if (consp views)
      (let ((result (fn-av-scr-ocfg-read-span (fn-ocfg-at-reader-view oc views)
                                           id i end cache fn-octets fn-arena fn-cat)))
        (fn-own-tls-make-result
         (fn-own-tls-result-consumed result)
         (fn-own-tls-result-effects result)
         (fn-ocfg-with-view (fn-own-tls-result-owner result)
                            (fn-own-view (fn-ocfg-owner oc)))
         (fn-own-tls-result-repinned result)))
    (fn-av-scr-ocfg-read-span oc id i end cache fn-octets fn-arena fn-cat)))

(defun fn-av-otm-read-span (oc views id i end cache s fn-octets fn-arena fn-cat)
  (declare (xargs :verify-guards nil :stobjs (fn-octets fn-arena fn-cat)
                  :guard (and (natp i) (natp end) (<= i end)
                              (<= end (fn-octets-len fn-octets))
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))))
  (if (eq (fn-otm-admit-post s) :shed)
      (let* ((allow (fn-otm-conn-allow oc id))
             (result (fn-av-orr-read-span (fn-otm-shed-ocfg oc id) views id i end cache
                                       fn-octets fn-arena fn-cat))
             (effects (fn-own-tls-result-effects result)))
        (fn-own-tls-make-result
         (fn-own-tls-result-consumed result)
         (if allow
             (fn-otm-disk-effects effects (fn-otm-post-command-reply s) (fn-otm-shed-reply s))
           effects)
         (fn-otm-unshed-ocfg (fn-own-tls-result-owner result) id allow)
         (fn-own-tls-result-repinned result)))
    (fn-av-orr-read-span oc views id i end cache fn-octets fn-arena fn-cat)))

(defun fn-av-oas-posting-off-read (oc views id i end cache s fn-octets fn-arena fn-cat)
  (declare (xargs :verify-guards nil :stobjs (fn-octets fn-arena fn-cat)
                  :guard (and (natp i) (natp end) (<= i end)
                              (<= end (fn-octets-len fn-octets))
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))))
  (let* ((allow (fn-otm-conn-allow oc id))
         (r (fn-av-otm-read-span (fn-otm-owner-with-allow oc id nil) views id i end cache s
                              fn-octets fn-arena fn-cat)))
    (fn-own-tls-make-result
     (fn-own-tls-result-consumed r)
     (if allow
         (fn-oas-post-effects (fn-own-tls-result-effects r) s)
       (fn-own-tls-result-effects r))
     (fn-otm-owner-with-allow (fn-own-tls-result-owner r) id allow)
     (fn-own-tls-result-repinned r))))

(defun fn-av-oas-read-span (oc views id i end cache s slots fn-octets fn-arena fn-cat)
  (declare (xargs :verify-guards nil :stobjs (fn-octets fn-arena fn-cat)
                  :guard (and (natp i) (natp end) (<= i end)
                              (<= end (fn-octets-len fn-octets))
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))))
  (let ((r (fn-av-otm-read-span oc views id i end cache s fn-octets fn-arena fn-cat)))
    (cond ((not (fn-oas-over-p oc (fn-own-tls-result-owner r) id slots)) r)
          ((fn-oas-articlep oc id) (fn-oas-tiers oc r id i end slots))
          (t (fn-oas-tiers oc (fn-av-oas-posting-off-read oc views id i end cache s
                                                       fn-octets fn-arena fn-cat)
                           id i end slots)))))

(defun fn-av-mca-refused-read (oc views id i end cache s fn-octets fn-arena fn-cat)
  (declare (xargs :verify-guards nil :stobjs (fn-octets fn-arena fn-cat)
                  :guard (and (natp i) (natp end) (<= i end)
                              (<= end (fn-octets-len fn-octets))
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))))
  (let ((r (fn-av-oas-posting-off-read oc views id i end cache s fn-octets fn-arena fn-cat)))
    (if (fn-oas-articlep (fn-own-tls-result-owner r) id)
        (fn-oas-close-result r id)
      r)))

(defun fn-av-mca-read-span (credits oc views id i end cache s slots reserve fn-octets fn-arena fn-cat)
  (declare (xargs :verify-guards nil :stobjs (fn-octets fn-arena fn-cat)
                  :guard (and (natp i) (natp end) (<= i end)
                              (<= end (fn-octets-len fn-octets))
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))))
  (let* ((key (fn-mca-conn-key id))
         (r0 (fn-av-oas-read-span oc views id i end cache s slots fn-octets fn-arena fn-cat))
         (d0 (fn-mcr-resize credits key
                            (fn-mca-need (fn-own-tls-result-owner r0) id reserve))))
    (if (equal (car d0) :ok)
        (cons r0 (cadr d0))
      (let* ((r1 (fn-av-mca-refused-read oc views id i end cache s fn-octets fn-arena fn-cat))
             (d1 (fn-mcr-resize credits key
                                (fn-mca-need (fn-own-tls-result-owner r1) id reserve))))
        (if (equal (car d1) :ok)
            (cons r1 (cadr d1))
          (let* ((r2 (fn-mca-shut-read oc id i end))
                 (d2 (fn-mcr-resize credits key
                                    (fn-mca-need (fn-own-tls-result-owner r2) id reserve))))
            (cons r2 (if (equal (car d2) :ok) (cadr d2) credits))))))))

; The ledger keystones over the read the host calls (books/owner-credits.lisp
; fn-mca-read-span-keeps-funded and its siblings), restated over this read.
(local (include-book "arithmetic-5/top" :dir :system))

(defthm fn-av-mca-read-span-keeps-funded
  (implies (fn-mcr-fundedp credits)
           (fn-mcr-fundedp
            (cdr (fn-av-mca-read-span credits oc views id i end cache s slots reserve
                                   fn-octets fn-arena fn-cat))))
  :hints (("Goal" :in-theory (union-theories '(fn-av-mca-read-span fn-mcr-resize-and-move-keep-funded
                                               car-cons cdr-cons)
                                             (theory 'minimal-theory)))))

(defthm fn-av-mca-read-span-within-the-credit-unfolds
  (implies (equal (car (fn-mcr-resize credits (fn-mca-conn-key id)
                                      (fn-mca-need (fn-own-tls-result-owner
                                                    (fn-av-oas-read-span oc views id i end cache s slots
                                                                      fn-octets fn-arena fn-cat))
                                                   id reserve)))
                  :ok)
           (equal (car (fn-av-mca-read-span credits oc views id i end cache s slots reserve
                                         fn-octets fn-arena fn-cat))
                  (fn-av-oas-read-span oc views id i end cache s slots fn-octets fn-arena fn-cat)))
  :hints (("Goal" :in-theory (e/d () (fn-av-oas-read-span fn-av-mca-refused-read fn-mca-need
                                      fn-mcr-resize fn-mca-shut-read)))))

(defthm fn-av-mca-read-span-never-blocks-what-is-held
  (implies (<= (fn-mca-need (fn-own-tls-result-owner
                             (fn-av-oas-read-span oc views id i end cache s slots
                                               fn-octets fn-arena fn-cat))
                            id reserve)
               (fn-mca-held credits id))
           (equal (car (fn-av-mca-read-span credits oc views id i end cache s slots reserve
                                         fn-octets fn-arena fn-cat))
                  (fn-av-oas-read-span oc views id i end cache s slots fn-octets fn-arena fn-cat)))
  :hints (("Goal" :in-theory (e/d (fn-mca-held)
                                  (fn-av-oas-read-span fn-av-mca-refused-read fn-mca-need
                                   fn-mcr-resize fn-mca-shut-read fn-av-mca-read-span
                                   fn-mcr-total))
           :use (fn-av-mca-read-span-within-the-credit-unfolds
                 (:instance fn-mcr-resize-refuses-exactly-past-the-budget
                            (l credits) (id (fn-mca-conn-key id))
                            (n (fn-mca-need (fn-own-tls-result-owner
                                             (fn-av-oas-read-span oc views id i end cache s slots
                                                               fn-octets fn-arena fn-cat))
                                            id reserve)))))))

(defthm fn-av-mca-read-span-covers-the-connection
  (implies (<= (fn-mca-need oc id reserve) (fn-mca-held credits id))
           (let ((rc (fn-av-mca-read-span credits oc views id i end cache s slots reserve
                                       fn-octets fn-arena fn-cat)))
             (equal (fn-mca-held (cdr rc) id)
                    (fn-mca-need (fn-own-tls-result-owner (car rc)) id reserve))))
  :hints (("Goal" :in-theory (e/d (fn-mca-held)
                                  (fn-av-oas-read-span fn-av-mca-refused-read fn-mca-need
                                   fn-mcr-resize fn-mca-shut-read fn-mcr-total))
           :use ((:instance fn-mcr-resize-sets-the-credit (l credits) (a nil)
                            (id (fn-mca-conn-key id))
                            (n (fn-mca-need (fn-own-tls-result-owner
                                             (fn-av-oas-read-span oc views id i end cache s slots
                                                               fn-octets fn-arena fn-cat))
                                            id reserve)))
                 (:instance fn-mcr-resize-sets-the-credit (l credits) (a nil)
                            (id (fn-mca-conn-key id))
                            (n (fn-mca-need (fn-own-tls-result-owner
                                             (fn-av-mca-refused-read oc views id i end cache s
                                                                  fn-octets fn-arena fn-cat))
                                            id reserve)))
                 (:instance fn-mcr-resize-sets-the-credit (l credits) (a nil)
                            (id (fn-mca-conn-key id))
                            (n (fn-mca-need (fn-own-tls-result-owner
                                             (fn-mca-shut-read oc id i end))
                                            id reserve)))
                 (:instance fn-mcr-resize-refuses-exactly-past-the-budget
                            (l credits) (id (fn-mca-conn-key id))
                            (n (fn-mca-need (fn-own-tls-result-owner
                                             (fn-mca-shut-read oc id i end))
                                            id reserve)))))))
