; Generated by tools/available_command_emit.py; edit the source formatter
; or the specialization map, then regenerate. Raw identity remains retained.
(in-package "ACL2")
(include-book "protocol-served")
(include-book "catalog-available-readers")
(include-book "served-availability")
(include-book "list-metadata-cursor")

(local (in-theory (disable (tau-system))))

(defun fn-av-scat-group-initial (archive group v fn-cat)
  (declare (xargs :stobjs fn-cat :guard (natp v)))
  (let ((summary (fn-scat-available-summary archive group v fn-cat)))
    (fn-nntp-append-pieces
     (list (fn-nntp-string-octets "211 ")
           (fn-nntp-decimal-field (fn-nntp-summary-count summary)) '(32)
           (fn-nntp-decimal-field (fn-nntp-summary-low summary)) '(32)
           (fn-nntp-decimal-field (fn-nntp-summary-high summary)) '(32)
           (fn-nntp-string-octets group)))))

(defun fn-av-nntp-group-result-cat (session archive group v fn-cat)
  (declare (xargs :stobjs fn-cat :guard (natp v)))
  (if (mbe :logic (member-equal group (fn-state-groups archive))
           :exec (fn-ag-member group (fn-state-groups archive)))
      (let* ((low (fn-scat-available-low group v fn-cat))
             (current (if (posp low) low nil))
             (next-session (fn-nntp-set-cursor session group current)))
        (fn-nntp-make-result
         next-session
         (list (fn-nntp-reply-effect
                (fn-nntp-crlf (fn-av-scat-group-initial archive group v fn-cat))))))
    (fn-nntp-single session (fn-proto-text * :no-group))))

(defun fn-av-nntp-listgroup-result-cat (session archive group range v fn-cat)
  (declare (xargs :stobjs fn-cat :guard (natp v)))
  (if (mbe :logic (member-equal group (fn-state-groups archive))
           :exec (fn-ag-member group (fn-state-groups archive)))
      (let* ((low (fn-scat-available-low group v fn-cat))
             (current (if (posp low) low nil))
             (next-session (fn-nntp-set-cursor session group current))
             (shown (fn-scat-available-range-numbers group (nfix (fn-nntp-range-low range))
                                           (nfix (fn-nntp-range-high range)) v fn-cat)))
        (fn-nntp-multi-octets next-session
                              (append (fn-av-scat-group-initial archive group v fn-cat)
                                      (fn-nntp-string-octets " list follows"))
                              (fn-nntp-number-lines shown)))
    (fn-nntp-single session (fn-proto-text * :no-group))))

(defun fn-av-nntp-listgroup-command-cat (session archive args v fn-cat)
  (declare (xargs :stobjs fn-cat :guard (natp v)))
  (let ((all-range (list :ok 1 2147483647)))
    (if (null args)
        (let ((group (fn-nntp-session-group session)))
          (if (null group)
              (fn-nntp-single session (fn-proto-text * :no-group-selected))
            (if (mbe :logic (member-equal group (fn-state-groups archive))
                     :exec (fn-ag-member group (fn-state-groups archive)))
                (fn-av-nntp-listgroup-result-cat session archive group all-range v fn-cat)
              (fn-nntp-single session (fn-proto-text * :no-group-selected)))))
      (if (and (consp args) (null (cdr args))
               (fn-nntp-printable-tokenp (car args)))
          (fn-av-nntp-listgroup-result-cat session archive
                                        (fn-nntp-token-string (car args)) all-range v fn-cat)
        (if (and (consp args) (consp (cdr args)) (null (cdr (cdr args)))
                 (fn-nntp-printable-tokenp (car args)))
            (let ((range (fn-nntp-parse-range (car (cdr args)))))
              (if (fn-nntp-range-okp range)
                  (fn-av-nntp-listgroup-result-cat session archive
                                                (fn-nntp-token-string (car args)) range v fn-cat)
                (fn-nntp-single session (fn-proto-text * :syntax))))
          (fn-nntp-single session (fn-proto-text * :syntax)))))))

(defun fn-av-scat-counts-lines-loop (archive groups closed v fn-cat acc)
  (declare (xargs :stobjs fn-cat :guard (and (natp v) (true-listp acc)) :verify-guards nil))
  (if (consp groups)
      (fn-av-scat-counts-lines-loop archive
                                 (cdr groups)
                                 closed
                                 v
                                 fn-cat
                                 (cons (fn-nntp-counts-summary-line (car groups)
                                                                    (fn-scat-available-summary archive
                                                                                           (car groups)
                                                                                           v
                                                                                           fn-cat)
                                                                    closed)
                                       acc))
    (revappend acc nil)))

(defun fn-av-scat-counts-lines (archive groups closed v fn-cat)
  (declare (xargs :verify-guards nil :stobjs fn-cat :guard (natp v)))
  (mbe :logic
       (if (consp groups)
           (cons (fn-nntp-counts-summary-line
                  (car groups) (fn-scat-available-summary archive (car groups) v fn-cat)
                  closed)
                 (fn-av-scat-counts-lines archive (cdr groups) closed v fn-cat))
         nil)
       :exec (fn-av-scat-counts-lines-loop archive groups closed v fn-cat nil)))

(local
 (defthm fn-av-scat-counts-lines-loop-is-revappend
   (equal (fn-av-scat-counts-lines-loop archive groups closed v fn-cat acc)
          (revappend acc (fn-av-scat-counts-lines archive groups closed v fn-cat)))
   :hints (("Goal" :induct (fn-av-scat-counts-lines-loop archive groups closed v fn-cat acc)
                   :in-theory (union-theories '(fn-av-scat-counts-lines-loop fn-av-scat-counts-lines revappend car-cons cdr-cons)
                                              (theory 'minimal-theory))))))

(verify-guards fn-av-scat-counts-lines-loop)

(verify-guards fn-av-scat-counts-lines
  :hints (("Goal" :in-theory (union-theories '(revappend fn-av-scat-counts-lines)
                                                  (union-theories (theory 'minimal-theory)
                                                                  (executable-counterpart-theory :here)))
                  :use ((:instance fn-av-scat-counts-lines-loop-is-revappend (acc nil))))))

(defun fn-av-nntp-list-counts-command-cat (session archive closed args v fn-cat)
  (declare (xargs :stobjs fn-cat :guard (natp v)))
  (if (null args)
      (fn-nntp-multi session (fn-proto-text "LIST" :newsgroups)
                     (fn-av-scat-counts-lines archive (fn-state-groups archive) closed v fn-cat))
    (if (and (consp args) (null (cdr args)))
        (let ((parsed (fn-wildmat-parse (car args))))
          (if (fn-wildmat-result-okp parsed)
              (fn-nntp-multi session (fn-proto-text "LIST" :newsgroups)
                             (fn-av-scat-counts-lines
                              archive
                              (fn-nntp-filter-groups-by-wildmat
                               (fn-wildmat-result-value parsed) (fn-state-groups archive))
                              closed v fn-cat))
            (fn-nntp-single session (fn-proto-text * :syntax))))
      (fn-nntp-single session (fn-proto-text * :syntax)))))

(defun fn-av-scat-active-line (archive group v fn-cat)
  (declare (xargs :stobjs fn-cat :guard (natp v)))
  (let ((summary (fn-scat-available-summary archive group v fn-cat)))
    (fn-nntp-append-pieces
     (list (fn-nntp-string-octets group) '(32)
           (fn-nntp-decimal-field (fn-nntp-summary-high summary)) '(32)
           (fn-nntp-decimal-field (fn-nntp-summary-low summary))
           (fn-nntp-string-octets " y")))))

(defun fn-av-scat-active-status-line (archive group closed v fn-cat)
  (declare (xargs :stobjs fn-cat :guard (natp v)))
  (let ((summary (fn-scat-available-summary archive group v fn-cat)))
    (fn-nntp-append-pieces
     (list (fn-nntp-string-octets group) '(32)
           (fn-nntp-decimal-field (fn-nntp-summary-high summary)) '(32)
           (fn-nntp-decimal-field (fn-nntp-summary-low summary)) '(32)
           (fn-nntp-string-octets
            (fn-nntp-closed-status (fn-nntp-string-octets group) closed))))))

(defun fn-av-scat-active-lines-loop (archive groups closed statusp v fn-cat acc)
  (declare (xargs :stobjs fn-cat :guard (and (natp v) (true-listp acc)) :verify-guards nil))
  (if (consp groups)
      (fn-av-scat-active-lines-loop
       archive (cdr groups) closed statusp v fn-cat
       (cons (if statusp
                 (fn-av-scat-active-status-line archive (car groups) closed v fn-cat)
               (fn-av-scat-active-line archive (car groups) v fn-cat))
             acc))
    (revappend acc nil)))

(defun fn-av-scat-active-lines (archive groups closed statusp v fn-cat)
  (declare (xargs :verify-guards nil :stobjs fn-cat :guard (natp v)))
  (mbe :logic
       (if (consp groups)
           (cons (if statusp
                     (fn-av-scat-active-status-line archive (car groups) closed v fn-cat)
                   (fn-av-scat-active-line archive (car groups) v fn-cat))
                 (fn-av-scat-active-lines archive (cdr groups) closed statusp v fn-cat))
         nil)
       :exec (fn-av-scat-active-lines-loop archive groups closed statusp v fn-cat nil)))

(local
 (defthm fn-av-scat-active-lines-loop-is-revappend
   (equal (fn-av-scat-active-lines-loop archive groups closed statusp v fn-cat acc)
          (revappend acc (fn-av-scat-active-lines archive groups closed statusp v fn-cat)))
   :hints (("Goal" :induct (fn-av-scat-active-lines-loop archive groups closed statusp v fn-cat acc)
                   :in-theory (union-theories '(fn-av-scat-active-lines-loop fn-av-scat-active-lines
                                                revappend car-cons cdr-cons)
                                              (theory 'minimal-theory))))))

(verify-guards fn-av-scat-active-lines-loop)

(verify-guards fn-av-scat-active-lines
  :hints (("Goal" :in-theory (union-theories '(revappend fn-av-scat-active-lines)
                                             (union-theories (theory 'minimal-theory)
                                                             (executable-counterpart-theory :here)))
                  :use ((:instance fn-av-scat-active-lines-loop-is-revappend (acc nil))))))

(defun fn-av-nntp-list-active-cat (session archive closed args v fn-cat)
  (declare (xargs :stobjs fn-cat :guard (natp v)))
  (let ((arguments (if (consp args) (cdr args) nil))
        (statusp (consp closed)))
    (if (null arguments)
        (fn-nntp-multi session (fn-proto-text "LIST" :active)
                       (fn-av-scat-active-lines archive (fn-state-groups archive)
                                             closed statusp v fn-cat))
      (if (and (consp arguments) (null (cdr arguments)))
          (let ((parsed (fn-wildmat-parse (car arguments))))
            (if (fn-wildmat-result-okp parsed)
                (fn-nntp-multi session (fn-proto-text "LIST" :active)
                               (fn-av-scat-active-lines
                                archive
                                (fn-nntp-filter-groups-by-wildmat
                                 (fn-wildmat-result-value parsed) (fn-state-groups archive))
                                closed statusp v fn-cat))
              (fn-nntp-single session (fn-proto-text * :syntax))))
        (fn-nntp-single session (fn-proto-text * :syntax))))))

; A chosen available neighbour is rendered from its held metadata. The
; availability reader already decides tombstone state; STAT needs no payload
; pread. The raw retrieval commands remain on the retained-history path.
(defun fn-av-held-article (seq fn-cat)
  (declare (xargs :stobjs fn-cat
                  :guard (and (natp seq) (< seq (fn-cat-count fn-cat)))
                  :guard-hints (("Goal" :in-theory (disable fn-cat-count-is-len fn-cat-at-is-nth)))))
  (let ((h (fn-cat-at seq fn-cat)))
    (fn-make-article (fn-record-msgid h) (fn-record-payload h)
                     (fn-record-groups h) (fn-held-numbers h) t (fn-record-stamp h))))

(defun fn-av-nntp-next-or-last-cat (session archive direction v fn-arena fn-cat)
  (declare (xargs :stobjs (fn-arena fn-cat) :guard (natp v) :verify-guards nil))
  (let ((group (fn-nntp-session-group session))
        (current (fn-nntp-session-current session)))
    (if (and group (natp current))
        (let* ((number (if (equal direction :next)
                           (fn-scat-available-next-number group current v fn-cat)
                         (fn-scat-available-previous-number group current v fn-cat)))
               (seq (fn-cat-group-number group number fn-cat)))
          (if (and (posp number) (natp seq) (< seq (fn-cat-count fn-cat))
                   (fn-scv-keptp group number v fn-cat))
              (fn-nntp-make-result
               (fn-nntp-set-cursor session group number)
               (list (fn-nntp-reply-effect
                      (fn-nntp-crlf (fn-nntp-retrieval-initial
                                     :stat number (fn-av-held-article seq fn-cat))))))
            (fn-nntp-single session (if (equal direction :next)
                                        (fn-proto-text "NEXT" :no-next)
                                      (fn-proto-text "LAST" :no-previous)))))
      (fn-nntp-next-or-last session archive direction fn-arena))))

(verify-guards fn-av-nntp-next-or-last-cat
  :hints (("Goal" :in-theory (disable fn-cat-count-is-len fn-cat-at-is-nth))))

; The map changes only selected enumeration helpers in the actual declared
; forms. No second archive/index is allocated in the executable branch.
(defconst *fn-proto-available-command-map*
  '(
    (fn-scat-group-initial . fn-av-scat-group-initial)
    (fn-nntp-group-result-cat . fn-av-nntp-group-result-cat)
    (fn-nntp-listgroup-result-cat . fn-av-nntp-listgroup-result-cat)
    (fn-nntp-listgroup-command-cat . fn-av-nntp-listgroup-command-cat)
    (fn-scat-counts-lines-loop . fn-av-scat-counts-lines-loop)
    (fn-scat-counts-lines . fn-av-scat-counts-lines)
    (fn-nntp-list-counts-command-cat . fn-lst-counts-command)
    (fn-scat-active-line . fn-av-scat-active-line)
    (fn-scat-active-status-line . fn-av-scat-active-status-line)
    (fn-scat-active-lines-loop . fn-av-scat-active-lines-loop)
    (fn-scat-active-lines . fn-av-scat-active-lines)
    (fn-nntp-list-active-cat . fn-lst-active-command)
    (fn-scat-counts-lines-loop-is-revappend . fn-av-scat-counts-lines-loop-is-revappend)
    (fn-scat-active-lines-loop-is-revappend . fn-av-scat-active-lines-loop-is-revappend)
    (fn-nntp-next-or-last-cat . fn-av-nntp-next-or-last-cat)
    (fn-scat-group-summary . fn-scat-available-summary)
    (fn-scat-group-low . fn-scat-available-low)
    (fn-scat-range-numbers . fn-scat-available-range-numbers)
    (fn-scat-next-number . fn-scat-available-next-number)
    (fn-scat-previous-number . fn-scat-available-previous-number)))

(make-event
 `(defun fn-proto-archive-command-available-cat ,*fn-proto-cat-formals*
    (declare (xargs :stobjs (fn-arena fn-cat)
                    :guard (and (natp v)
                                (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))
                    :verify-guards nil))
    (cond
     ,@(sublis *fn-proto-available-command-map*
               (fn-proto-cat-flat-clauses *fn-proto-served-table*))
     (t (fn-nntp-archive-command-pinned session archive index verdicts
                                       env keyword args fn-arena)))))

(verify-guards fn-proto-archive-command-available-cat)

; Only enumeration/navigation selects the logical available projection.
; Retrieval identities, overview/header ranges and NEWNEWS chronology stay raw.
(defun fn-av-available-commandp (keyword args)
  (declare (xargs :guard t))
  (or (fn-nntp-keywordp keyword "GROUP")
      (fn-nntp-keywordp keyword "LISTGROUP")
      (fn-nntp-keywordp keyword "NEXT")
      (fn-nntp-keywordp keyword "LAST")
      (and (fn-nntp-keywordp keyword "LIST")
           (or (fn-scat-list-active-formp args)
               (and (consp args)
                    (fn-nntp-keywordp (car args) "COUNTS"))))))

(defun-nx fn-proto-archive-command-available-reference
  (session archive index verdicts env keyword args fn-arena)
  (let* ((selected (fn-av-available-commandp keyword args))
         (view (if selected (fn-nntp-available-archive archive fn-arena) archive))
         (view-index (if selected
                          (fn-gidx-pin-with-control
                           (fn-midx-build (fn-state-articles view))
                           (fn-gidx-build (fn-state-articles view))
                           (fn-gidx-pin-control index))
                        index)))
    (fn-nntp-archive-command-pinned
     session view view-index verdicts env keyword args fn-arena)))

(in-theory (disable fn-proto-archive-command-available-reference))

; A real command-layer consumer, with the same generated session/archive
; routing as fn-scr-command. Production owner/captured-view composition is
; still owed; the old raw-pinned entry and theorem remain unchanged.
(defun fn-scr-command-available (session archive index verdicts env tokens v fn-arena fn-cat)
  (declare (xargs :stobjs (fn-arena fn-cat)
                  :guard (and (natp v)
                              (fn-cat-handles-inp (fn-cat-count fn-cat) fn-arena fn-cat))
                  :verify-guards nil))
  (fn-nntp-command-dispatch
   (fn-proto-archive-command-available-cat
    session archive index verdicts env keyword args v fn-arena fn-cat)
   :pinned t))

(verify-guards fn-scr-command-available)

; No raw-pinned equality claim: metadata availability has a distinct selective
; reference and requires captured facts completeness. Guard/proof/image and
; actual owner route propagation are explicitly pending at this source.
