; Cheap capture-coordinate fence. Resource adequacy is the maintenance
; owner's separate obligation; this function cannot turn a token into credit.
(in-package "ACL2")
(include-book "snapshot-source-token")
(defun fn-osj-resource-word (context maintenance)
  (declare (xargs :guard t))
  (cond
   ((not (and (fn-omk-widthp context 6) (eq (fn-omk-at 0 context) :ready)
              (natp (fn-omk-at 1 context)) (natp (fn-omk-at 2 context))
              (natp (fn-omk-at 3 context)) (natp (fn-omk-at 4 context))))
    '(:refused :source-state))
   ((not (and (fn-omk-widthp maintenance 4)
              (eq (fn-omk-at 0 maintenance) :maintenance)
              (natp (fn-omk-at 1 maintenance))
              (equal (fn-omk-at 2 maintenance) (fn-omk-at 1 context))
              (equal (fn-omk-at 3 maintenance) (fn-omk-at 4 context))))
    '(:refused :maintenance-capture))
   ((not (equal (nfix (fn-omk-at 2 context))
                (+ (nfix (fn-omk-at 3 context)) (nfix (fn-omk-at 4 context)))))
    '(:refused :capture-count))
   (t (list :capture (if (zp (nfix (fn-omk-at 3 context))) nil (fn-omk-at 5 context))))))
(defun fn-osj-capture-ticket (capture)
  (declare (xargs :guard t))
  (fn-omk-at 0 (fn-omk-at 1 capture)))
; These are observations of actual returned actions and staged-file effects,
; never a timeout or a promise to join.  A private/uncertain stage continues
; to own the grant until definite deletion or publication is observed.
(defun fn-osj-stage-observation (stage observation)
  (declare (xargs :guard t))
  (cond ((and (equal stage :none) (equal observation :created)) :private)
        ((and (member-eq stage '(:private :uncertain))
              (equal observation :deleted)) :deleted)
        ((and (equal stage :private) (equal observation :published)) :published)
        ((and (equal stage :private) (equal observation :ambiguous)) :uncertain)
        (t stage)))
(defun fn-osj-cleanup-word (returned stage)
  (declare (xargs :guard t))
  (cond ((not (equal returned :returned)) '(:refused :action-not-joined))
        ((not (member-eq stage '(:none :deleted :published)))
         '(:uncertain :stage-not-settled))
        (t '(:release :source :payload-view :capture :maintenance))))
(defthm fn-osj-cleanup-needs-return-and-settled-stage
  (iff (equal (car (fn-osj-cleanup-word returned stage)) :release)
       (and (equal returned :returned)
            (member-equal stage '(:none :deleted :published))))
  :hints (("Goal" :in-theory (enable fn-osj-cleanup-word))))
(in-theory (disable fn-osj-resource-word fn-osj-capture-ticket
                    fn-osj-stage-observation fn-osj-cleanup-word))
