; PRF-1099 / HST-040: captured records-field source protocol.
; A based row is supplied only by the separate current-format decoder.
; This cursor never invokes fn-sfr-list, fn-sfr-nth or fn-hp-x-at.
(in-package "ACL2")
(include-book "snoc-list")
(defun fn-osrc-at (n x)
  (declare (xargs :guard (natp n) :measure (nfix n)))
  (if (zp n) (if (consp x) (car x) nil)
    (fn-osrc-at (1- n) (if (consp x) (cdr x) nil))))
(defun fn-osrc-token (cursor)
  (declare (xargs :guard t))
  (list (fn-osrc-at 9 cursor) (fn-osrc-at 10 cursor)
        (fn-osrc-at 12 cursor) (fn-osrc-at 2 cursor)))
(defun fn-osrc-begin (field count epoch lease)
  (declare (xargs :guard (natp count)
                  :guard-hints (("Goal" :in-theory (enable fn-sl-snoc-formp)))))
  (let* ((based (and (consp field) (eq (car field) :hrs-based)))
         (handle (if based (fn-osrc-at 1 field) nil))
         (base (if based (nfix (fn-osrc-at 4 handle)) 0))
         (suffix (if based (if (consp (cdr field)) (cddr field) nil) field))
         (snoc (fn-sl-snoc-formp suffix))
         (reverse (if snoc (cddr suffix) nil))
         (ordered (if snoc nil
                    (if (and (consp suffix) (eq (car suffix) :raw))
                        (cdr suffix) suffix))))
    (list (if snoc :reverse :prefix) field 0 count base handle
          (if snoc (nfix (- count base)) 0) reverse ordered epoch lease ordered 0)))
(defun fn-osrc-with (phase seq left rev out cursor)
  (declare (xargs :guard t))
  (list phase (fn-osrc-at 1 cursor) seq (fn-osrc-at 3 cursor)
        (fn-osrc-at 4 cursor) (fn-osrc-at 5 cursor)
        left rev out (fn-osrc-at 9 cursor) (fn-osrc-at 10 cursor)
        (if (and (equal phase :prefix) (equal (fn-osrc-at 0 cursor) :reverse))
            out (fn-osrc-at 11 cursor)) (fn-osrc-at 12 cursor)))
; Restart a completed bounded suffix preparation; no reverse/redecode here.
; PREPARED (position11) retains the original ordered suffix even as OUT drains.
(defun fn-osrc-restart (cursor)
  (declare (xargs :guard t))
  (if (and (equal (fn-osrc-at 0 cursor) :suffix)
           (equal (fn-osrc-at 2 cursor) (fn-osrc-at 3 cursor))
           (equal (fn-osrc-at 6 cursor) 0))
      (list :restarted
            (update-nth 12 (1+ (nfix (fn-osrc-at 12 cursor)))
                        (fn-osrc-with :prefix 0 0 nil (fn-osrc-at 11 cursor) cursor)))
    (list :refused :source-not-drained cursor)))
(defun fn-osrc-guardp (cursor)
  (declare (xargs :guard t))
  (and (natp (fn-osrc-at 2 cursor)) (natp (fn-osrc-at 3 cursor))
       (natp (fn-osrc-at 4 cursor)) (natp (fn-osrc-at 6 cursor))
       (natp (fn-osrc-at 12 cursor))))
(defun fn-osrc-tick (cursor observation)
  (declare (xargs :guard (fn-osrc-guardp cursor)))
  (let ((phase (fn-osrc-at 0 cursor)) (seq (fn-osrc-at 2 cursor))
        (count (fn-osrc-at 3 cursor)) (base (fn-osrc-at 4 cursor))
        (left (fn-osrc-at 6 cursor)) (rev (fn-osrc-at 7 cursor))
        (out (fn-osrc-at 8 cursor)))
    (cond
     ((eq phase :reverse)
      (if (zp left)
          (list :yield (fn-osrc-with :prefix seq 0 nil out cursor))
        (if (consp rev)
            (list :yield (fn-osrc-with :reverse seq (1- left) (cdr rev)
                                      (cons (car rev) out) cursor))
          (list :refused :short-suffix cursor))))
     ((eq phase :prefix)
      (cond ((> base count) (list :refused :capture-count cursor))
            ((< seq base)
             (list :need-row seq (fn-osrc-at 5 cursor) (fn-osrc-token cursor)
                   (fn-osrc-with :waiting seq left rev out cursor)))
            (t (list :yield (fn-osrc-with :suffix seq left rev out cursor)))))
     ((eq phase :waiting)
      (if (and (consp observation) (eq (car observation) :decoded)
               (equal (fn-osrc-at 1 observation) (fn-osrc-token cursor)))
          (list :row seq (list :decoded (fn-osrc-at 2 observation))
                (fn-osrc-token cursor)
                (fn-osrc-with :prefix (1+ seq) left rev out cursor))
        (list :refused :row-completion cursor)))
     ((eq phase :suffix)
      (cond ((equal seq count) (list :done (fn-osrc-token cursor)))
            ((or (> seq count) (not (consp out)))
             (list :refused :capture-count cursor))
            (t (list :row seq (list :resident (car out))
                     (fn-osrc-token cursor)
                     (fn-osrc-with :suffix (1+ seq) left rev (cdr out) cursor)))))
     (t (list :refused :phase cursor)))))
; The provider proves decoded row correctness independently.  This boundary
; controls ordinal/epoch/lease identity and never treats an ACK as acceptance.
(defthm fn-osrc-decoded-completion-requires-the-issued-token
  (implies (equal (fn-osrc-at 0 cursor) :waiting)
           (iff (equal (car (fn-osrc-tick cursor observation)) :row)
                (and (consp observation) (equal (car observation) :decoded)
                     (equal (fn-osrc-at 1 observation) (fn-osrc-token cursor)))))
  :hints (("Goal" :in-theory (enable fn-osrc-tick))))
(defthm fn-osrc-row-advances-one-ordinal-and-keeps-capture
  (implies (equal (car (fn-osrc-tick cursor observation)) :row)
           (let ((next (fn-osrc-at 4 (fn-osrc-tick cursor observation))))
             (and (equal (fn-osrc-at 2 next) (1+ (fn-osrc-at 2 cursor)))
                  (equal (fn-osrc-at 1 next) (fn-osrc-at 1 cursor))
                  (equal (fn-osrc-at 3 next) (fn-osrc-at 3 cursor))
                  (equal (fn-osrc-at 5 next) (fn-osrc-at 5 cursor))
                  (equal (fn-osrc-at 9 next) (fn-osrc-at 9 cursor))
                  (equal (fn-osrc-at 10 next) (fn-osrc-at 10 cursor)))))
  :hints (("Goal" :in-theory (enable fn-osrc-tick fn-osrc-with fn-osrc-at))))
(defthm fn-osrc-reversal-copies-exactly-one-suffix-cell
  (implies (and (equal (fn-osrc-at 0 cursor) :reverse)
                (posp (fn-osrc-at 6 cursor)) (consp (fn-osrc-at 7 cursor)))
           (let ((next (fn-osrc-at 1 (fn-osrc-tick cursor observation))))
             (and (equal (car (fn-osrc-tick cursor observation)) :yield)
                  (equal (fn-osrc-at 6 next) (1- (fn-osrc-at 6 cursor)))
                  (equal (fn-osrc-at 7 next) (cdr (fn-osrc-at 7 cursor)))
                  (equal (fn-osrc-at 8 next)
                         (cons (car (fn-osrc-at 7 cursor))
                               (fn-osrc-at 8 cursor))))))
  :hints (("Goal" :in-theory (enable fn-osrc-tick fn-osrc-with fn-osrc-at))))
(defthm fn-osrc-begin-establishes-the-executable-cursor
  (implies (natp count) (fn-osrc-guardp (fn-osrc-begin field count epoch lease)))
  :hints (("Goal" :in-theory (enable fn-osrc-guardp fn-osrc-begin fn-osrc-at))))
(defthm fn-osrc-continuation-keeps-the-executable-cursor
  (implies (fn-osrc-guardp cursor)
           (let* ((result (fn-osrc-tick cursor observation))
                  (kind (car result)))
             (and (implies (equal kind :yield) (fn-osrc-guardp (fn-osrc-at 1 result)))
                  (implies (member-equal kind '(:need-row :row))
                           (fn-osrc-guardp (fn-osrc-at 4 result))))))
  :hints (("Goal" :in-theory (enable fn-osrc-guardp fn-osrc-tick fn-osrc-with fn-osrc-at))))
(defthm fn-osrc-restart-advances-pass-and-preserves-source-identity
  (implies (and (fn-osrc-guardp cursor)
                (equal (car (fn-osrc-restart cursor)) :restarted))
           (let ((next (cadr (fn-osrc-restart cursor))))
             (and (fn-osrc-guardp next)
                  (equal (fn-osrc-at 12 next) (1+ (fn-osrc-at 12 cursor)))
                  (equal (fn-osrc-at 2 next) 0)
                  (equal (fn-osrc-at 1 next) (fn-osrc-at 1 cursor))
                  (equal (fn-osrc-at 9 next) (fn-osrc-at 9 cursor))
                  (equal (fn-osrc-at 10 next) (fn-osrc-at 10 cursor))
                  (equal (fn-osrc-at 8 next) (fn-osrc-at 11 cursor)))))
  :hints (("Goal" :in-theory (enable fn-osrc-restart fn-osrc-guardp
                                     fn-osrc-with fn-osrc-at update-nth))))
(in-theory (disable fn-osrc-at fn-osrc-token fn-osrc-begin fn-osrc-with fn-osrc-restart fn-osrc-guardp fn-osrc-tick))
