; Cheap capture-coordinate fence. Resource adequacy is the maintenance
; owner's separate obligation; this function cannot turn a token into credit.
(in-package "ACL2")
(include-book "snapshot-source-token")
(defun fn-osj-resource-word (context maintenance)
  (declare (xargs :guard t))
  (cond
   ((not (and (fn-omk-widthp context 6) (eq (fn-omk-at 0 context) :ready)
              (natp (fn-omk-at 1 context)) (natp (fn-omk-at 2 context))
              (natp (fn-omk-at 3 context)) (natp (fn-omk-at 4 context))))
    '(:refused :source-state))
   ((not (and (fn-omk-widthp maintenance 4)
              (eq (fn-omk-at 0 maintenance) :maintenance)
              (natp (fn-omk-at 1 maintenance))
              (equal (fn-omk-at 2 maintenance) (fn-omk-at 1 context))
              (equal (fn-omk-at 3 maintenance) (fn-omk-at 4 context))))
    '(:refused :maintenance-capture))
   ((not (equal (nfix (fn-omk-at 2 context))
                (+ (nfix (fn-omk-at 3 context)) (nfix (fn-omk-at 4 context)))))
    '(:refused :capture-count))
   (t (list :capture (if (zp (nfix (fn-omk-at 3 context))) nil (fn-omk-at 5 context))))))
(defun fn-osj-capture-ticket (capture)
  (declare (xargs :guard t))
  (fn-omk-at 0 (fn-omk-at 1 capture)))
(in-theory (disable fn-osj-resource-word fn-osj-capture-ticket))
