; PRF-1124: bounded Message-ID FNV continuation for captured history columns.
; This library does not authenticate pages or admit its own allocation.
(in-package "ACL2")
(include-book "history-key-cursor")
(include-book "snapshot-decode-remap")
(defun fn-omk-at (n x)
  (declare (xargs :guard (natp n) :measure (nfix n)))
  (if (zp n) (if (consp x) (car x) nil)
    (fn-omk-at (1- n) (if (consp x) (cdr x) nil))))
(defun fn-omk-widthp (x n)
  (declare (xargs :guard (natp n) :measure (nfix n)))
  (if (zp n) (null x)
    (and (consp x) (fn-omk-widthp (cdr x) (1- n)))))
(defun fn-omk-tokenp (x)
  (declare (xargs :guard t))
  (and (fn-omk-widthp x 4) (natp (fn-omk-at 0 x))
       (fn-omk-widthp (fn-omk-at 1 x) 2)
       (natp (fn-omk-at 0 (fn-omk-at 1 x)))
       (natp (fn-omk-at 1 (fn-omk-at 1 x)))
       (natp (fn-omk-at 2 x)) (natp (fn-omk-at 3 x))))
(defun fn-omk-token-matchp (a b)
  (declare (xargs :guard t))
  (and (fn-omk-tokenp a) (fn-omk-tokenp b)
       (equal (fn-omk-at 0 a) (fn-omk-at 0 b))
       (equal (fn-omk-at 0 (fn-omk-at 1 a)) (fn-omk-at 0 (fn-omk-at 1 b)))
       (equal (fn-omk-at 1 (fn-omk-at 1 a)) (fn-omk-at 1 (fn-omk-at 1 b)))
       (equal (fn-omk-at 2 a) (fn-omk-at 2 b))
       (equal (fn-omk-at 3 a) (fn-omk-at 3 b))))
(defun fn-omk-node-message (node)
  (declare (xargs :guard t))
  (let* ((tag (fn-hdc-car node))
         (held (if (and (consp tag) (eq (car tag) :atom)
                        (eq (fn-omk-at 1 tag) :hstxa))
                   (fn-odm-at 2 node) node)))
    (fn-odm-at 3 held)))
(defun fn-omk-message-source (source)
  (declare (xargs :guard t))
  (cond ((and (consp source) (eq (car source) :resident))
         (let ((m (fn-hist-key-msgid (fn-omk-at 1 source))))
           (if (stringp m) (list :string m) '(:none))))
        ((and (consp source) (eq (car source) :decoded))
         (let ((m (fn-omk-node-message (fn-omk-at 1 source))))
           (cond ((and (consp m) (eq (car m) :span)
                       (equal (fn-omk-at 1 m) 3))
                  (list :span (fn-omk-at 3 m) (fn-omk-at 4 m)))
                 ((and (consp m) (eq (car m) :atom)
                       (stringp (fn-omk-at 1 m)))
                  (list :string (fn-omk-at 1 m)))
                 (t '(:none)))))
        (t '(:none))))
; Nine cells: kind,value,span-offset,index,count,hash,source-token,resource-lease,phase.
(defun fn-omk-begin (source salt token resource-lease)
  (declare (xargs :guard (unsigned-byte-p 32 salt)))
  (let* ((m (fn-omk-message-source source)) (kind (car m))
         (value (if (eq kind :string) (fn-omk-at 1 m) nil))
         (offset (if (eq kind :span) (fn-omk-at 1 m) 0))
         (count (cond ((eq kind :string) (length value))
                      ((eq kind :span) (fn-omk-at 2 m)) (t 0))))
    (if (and (fn-omk-tokenp token) (unsigned-byte-p 64 offset)
             (unsigned-byte-p 64 count) (unsigned-byte-p 64 (+ offset count)))
        (list :begun (list kind value offset 0 count
                          (fn-hkc-begin salt)
                          token resource-lease :active))
      (list :refused :message-source-domain))))
(defun fn-omk-guardp (c)
  (declare (xargs :guard t))
  (and (fn-omk-widthp c 9)
       (member-eq (fn-omk-at 0 c) '(:none :string :span))
       (unsigned-byte-p 64 (fn-omk-at 2 c))
       (unsigned-byte-p 64 (fn-omk-at 3 c))
       (unsigned-byte-p 64 (fn-omk-at 4 c))
       (unsigned-byte-p 32 (fn-omk-at 5 c))
       (<= (fn-omk-at 3 c) (fn-omk-at 4 c))
       (unsigned-byte-p 64 (+ (fn-omk-at 2 c) (fn-omk-at 4 c)))
       (fn-omk-tokenp (fn-omk-at 6 c))
       (implies (eq (fn-omk-at 0 c) :string)
                (and (stringp (fn-omk-at 1 c))
                     (equal (fn-omk-at 4 c) (length (fn-omk-at 1 c)))))
       (implies (eq (fn-omk-at 0 c) :none) (equal (fn-omk-at 4 c) 0))))
(defun fn-omk-with-byte (byte c)
  (declare (xargs :guard (and (fn-omk-guardp c) (unsigned-byte-p 8 byte))))
  (list (fn-omk-at 0 c) (fn-omk-at 1 c) (fn-omk-at 2 c)
        (+ 1 (fn-omk-at 3 c)) (fn-omk-at 4 c)
        (fn-hkc-byte byte (fn-omk-at 5 c))
        (fn-omk-at 6 c) (fn-omk-at 7 c) :active))
(defun fn-omk-tick (c observation)
  (declare (xargs :guard (fn-omk-guardp c)))
  (let ((kind (fn-omk-at 0 c)) (index (fn-omk-at 3 c))
        (count (fn-omk-at 4 c)) (token (fn-omk-at 6 c)))
    (cond ((equal index count)
           (list :done (if (eq kind :none) 0 (+ 1 (fn-omk-at 5 c))) token c))
          ((eq kind :string)
           (list :continue (fn-omk-with-byte (char-code (char (fn-omk-at 1 c) index)) c)))
          ((null observation)
           (list :need-byte (+ (fn-omk-at 2 c) index) token c))
          ((and (fn-omk-widthp observation 4) (eq (car observation) :byte)
                (fn-omk-token-matchp (fn-omk-at 1 observation) token)
                (equal (fn-omk-at 2 observation) (+ (fn-omk-at 2 c) index))
                (unsigned-byte-p 8 (fn-omk-at 3 observation)))
           (list :continue (fn-omk-with-byte (fn-omk-at 3 observation) c)))
          (t (list :refused :message-byte c)))))
(local (include-book "arithmetic/top" :dir :system))
(defthm fn-omk-begin-establishes-the-executable-cursor
  (implies (and (unsigned-byte-p 32 salt)
                (equal (car (fn-omk-begin source salt token resource-lease)) :begun))
           (fn-omk-guardp (cadr (fn-omk-begin source salt token resource-lease))))
  :hints (("Goal" :in-theory (e/d (fn-omk-begin fn-omk-message-source fn-omk-guardp
                                  fn-omk-at fn-omk-widthp)
                                 (fn-hist-key-msgid fn-hkc-begin fn-omk-node-message)))))
(defthm fn-omk-span-completion-requires-the-issued-offset-and-token
  (implies (and (fn-omk-guardp c) (equal (fn-omk-at 0 c) :span)
                (< (fn-omk-at 3 c) (fn-omk-at 4 c)))
           (iff (equal (car (fn-omk-tick c observation)) :continue)
                (and (fn-omk-widthp observation 4) (equal (car observation) :byte)
                     (fn-omk-token-matchp (fn-omk-at 1 observation) (fn-omk-at 6 c))
                     (equal (fn-omk-at 2 observation) (+ (fn-omk-at 2 c) (fn-omk-at 3 c)))
                     (unsigned-byte-p 8 (fn-omk-at 3 observation)))))
  :hints (("Goal" :in-theory (enable fn-omk-tick fn-omk-widthp))))
(defthm fn-omk-continue-is-one-byte-and-keeps-borrow-identities
  (implies (equal (car (fn-omk-tick c observation)) :continue)
           (let ((next (cadr (fn-omk-tick c observation))))
             (and (equal (fn-omk-at 3 next) (+ 1 (fn-omk-at 3 c)))
                  (equal (fn-omk-at 0 next) (fn-omk-at 0 c))
                  (equal (fn-omk-at 1 next) (fn-omk-at 1 c))
                  (equal (fn-omk-at 2 next) (fn-omk-at 2 c))
                  (equal (fn-omk-at 4 next) (fn-omk-at 4 c))
                  (equal (fn-omk-at 6 next) (fn-omk-at 6 c))
                  (equal (fn-omk-at 7 next) (fn-omk-at 7 c)))))
  :hints (("Goal" :in-theory (e/d (fn-omk-tick fn-omk-with-byte fn-omk-at)
                                  (fn-hkc-byte)))))
(defthm fn-omk-continuation-keeps-the-executable-cursor
  (implies (and (fn-omk-guardp c)
                (equal (car (fn-omk-tick c observation)) :continue))
           (fn-omk-guardp (cadr (fn-omk-tick c observation))))
  :hints (("Goal" :in-theory (e/d (fn-omk-tick fn-omk-with-byte fn-omk-guardp
                                  fn-omk-at fn-omk-widthp)
                                 (fn-hkc-byte)))))
(defthm fn-omk-resident-step-preserves-the-current-message-residual
  (implies (and (fn-omk-guardp c) (equal (fn-omk-at 0 c) :string)
                (equal (car (fn-omk-tick c observation)) :continue))
           (let ((next (cadr (fn-omk-tick c observation))))
             (equal (fn-hist-fnv (fn-omk-at 1 c) (fn-omk-at 3 next) (fn-omk-at 5 next))
                    (fn-hist-fnv (fn-omk-at 1 c) (fn-omk-at 3 c) (fn-omk-at 5 c)))))
  :hints (("Goal" :in-theory (e/d (fn-omk-tick fn-omk-with-byte fn-omk-guardp fn-omk-at)
                                  (fn-hkc-byte fn-hist-fnv)))))
(defthm fn-omk-span-step-preserves-the-specified-message-residual
  (implies (and (fn-omk-guardp c) (equal (fn-omk-at 0 c) :span)
                (stringp message) (equal (length message) (fn-omk-at 4 c))
                (< (fn-omk-at 3 c) (fn-omk-at 4 c))
                (fn-omk-widthp observation 4) (equal (car observation) :byte)
                (fn-omk-token-matchp (fn-omk-at 1 observation) (fn-omk-at 6 c))
                (equal (fn-omk-at 2 observation) (+ (fn-omk-at 2 c) (fn-omk-at 3 c)))
                (equal (fn-omk-at 3 observation) (char-code (char message (fn-omk-at 3 c)))))
           (let ((next (cadr (fn-omk-tick c observation))))
             (and (equal (car (fn-omk-tick c observation)) :continue)
                  (equal (fn-hist-fnv message (fn-omk-at 3 next) (fn-omk-at 5 next))
                         (fn-hist-fnv message (fn-omk-at 3 c) (fn-omk-at 5 c))))))
  :hints (("Goal" :in-theory (e/d (fn-omk-tick fn-omk-with-byte fn-omk-guardp fn-omk-at)
                                  (fn-hkc-byte fn-hist-fnv)))))
(in-theory (disable fn-omk-at fn-omk-widthp fn-omk-tokenp fn-omk-token-matchp
                    fn-omk-node-message fn-omk-message-source fn-omk-begin fn-omk-guardp
                    fn-omk-with-byte fn-omk-tick))
