; Scalar captured-source identity seam, extracted without API changes.
(in-package "ACL2")
(defun fn-omk-at (n x)
  (declare (xargs :guard (natp n) :measure (nfix n)))
  (if (zp n) (if (consp x) (car x) nil)
    (fn-omk-at (1- n) (if (consp x) (cdr x) nil))))
(defun fn-omk-widthp (x n)
  (declare (xargs :guard (natp n) :measure (nfix n)))
  (if (zp n) (null x)
    (and (consp x) (fn-omk-widthp (cdr x) (1- n)))))
(defun fn-omk-tokenp (x)
  (declare (xargs :guard t))
  (and (fn-omk-widthp x 4) (natp (fn-omk-at 0 x))
       (fn-omk-widthp (fn-omk-at 1 x) 2)
       (natp (fn-omk-at 0 (fn-omk-at 1 x)))
       (natp (fn-omk-at 1 (fn-omk-at 1 x)))
       (natp (fn-omk-at 2 x)) (natp (fn-omk-at 3 x))))
(defun fn-omk-token-matchp (a b)
  (declare (xargs :guard t))
  (and (fn-omk-tokenp a) (fn-omk-tokenp b)
       (equal (fn-omk-at 0 a) (fn-omk-at 0 b))
       (equal (fn-omk-at 0 (fn-omk-at 1 a)) (fn-omk-at 0 (fn-omk-at 1 b)))
       (equal (fn-omk-at 1 (fn-omk-at 1 a)) (fn-omk-at 1 (fn-omk-at 1 b)))
       (equal (fn-omk-at 2 a) (fn-omk-at 2 b))
       (equal (fn-omk-at 3 a) (fn-omk-at 3 b))))

(in-theory (disable fn-omk-at fn-omk-widthp fn-omk-tokenp fn-omk-token-matchp))
