; Actual capture-row remapping: event ordinal and target arena handle are
; separate core counters. A pending row advances only after its consumer ACK.
(in-package "ACL2")
(include-book "snapshot-held-remap")
(include-book "held-composite-fields")
(include-book "snapshot-decode-remap")
(include-book "snapshot-source-token")
(defun fn-osm-resident-held-headp (row)
  (declare (xargs :guard t))
  (and (consp row) (natp (car row)) (consp (fn-orm-tail 15 row))))
(defun fn-osm-node-held-headp (node)
  (declare (xargs :guard t))
  (let ((tag (fn-hdc-car node)))
    (and (fn-omk-widthp tag 2) (eq (fn-omk-at 0 tag) :atom)
         (natp (fn-omk-at 1 tag)) (fn-odm-prefixp 16 node))))
; The captured Store event relation supplies grammar. Ordinary retained
; rows have a natural sequence head and at least sixteen cells. Short
; numeric-headed keyring/topic events are excluded by that fixed prefix.
; Fixed HSTXA normalization supplies the composite head. Terminal NIL
; may remain a borrowed symbol/octet span, so no raw-tail NIL test is used.
(defun fn-osm-row-source (source handle)
  (declare (xargs :guard (natp handle)))
  (cond
   ((and (fn-omk-widthp source 2) (eq (fn-omk-at 0 source) :resident))
    (let* ((row (fn-omk-at 1 source))
           (ordinary (fn-osm-resident-held-headp row))
           (composite (and (consp row) (eq (car row) :hstxa)))
           (new (cond (ordinary (fn-orm-held row handle))
                      (composite (fn-hstxa-make (fn-hstxa-stxa row)
                                      (fn-orm-held (fn-hstxa-held row) handle)))
                      (t row))))
      (mv (list :resident new) (if (or ordinary composite) (1+ handle) handle))))
   ((and (fn-omk-widthp source 2) (eq (fn-omk-at 0 source) :decoded))
    (let* ((node (fn-omk-at 1 source)) (tag (fn-hdc-car node))
           (composite (and (fn-omk-widthp tag 2) (eq (fn-omk-at 0 tag) :atom)
                           (eq (fn-omk-at 1 tag) :hstxa)))
           (ordinary (fn-osm-node-held-headp node))
           (new (cond (composite (fn-odm-composite node handle))
                      (ordinary (fn-odm-held node handle)) (t node))))
      (mv (list :decoded new) (if (or ordinary composite) (1+ handle) handle))))
   (t (mv source handle))))
; Fixed four cells: phase, expected source4, next target handle, pending4.
; Pending4 retains original source, remapped source, next handle and row token.
(defun fn-osm-begin (source)
  (declare (xargs :guard t))
  (list (if (and (fn-omk-tokenp source) (equal (fn-omk-at 3 source) 0))
            :idle :refused) source 0 nil))
(defun fn-osm-offer (cursor token original)
  (declare (xargs :guard t))
  (if (not (and (fn-omk-widthp cursor 4) (eq (fn-omk-at 0 cursor) :idle)
                (natp (fn-omk-at 2 cursor))
                (fn-omk-token-matchp token (fn-omk-at 1 cursor))
                (fn-omk-widthp original 2)
                (member-eq (fn-omk-at 0 original) '(:resident :decoded))))
      (mv '(:refused :remap-source) cursor)
    (mv-let (mapped next-handle) (fn-osm-row-source original (fn-omk-at 2 cursor))
      (mv (list :mapped mapped original token)
          (list :waiting token (fn-omk-at 2 cursor)
                (list original mapped next-handle token))))))
(defun fn-osm-advance (cursor)
  (declare (xargs :guard t))
  (let ((source (fn-omk-at 1 cursor)) (pending (fn-omk-at 3 cursor)))
    (list :idle
          (list (fn-omk-at 0 source) (fn-omk-at 1 source) (fn-omk-at 2 source)
                (1+ (nfix (fn-omk-at 3 source))))
          (fn-omk-at 2 pending) nil)))
; Actual census state, not a host-generated Boolean or counter, authorizes ACK.
(defun fn-osm-census-ack (cursor census)
  (declare (xargs :guard t))
  (let* ((source (fn-omk-at 1 cursor)) (pair (fn-omk-at 1 source))
         (capture (fn-omk-at 5 census)))
    (if (and (fn-omk-widthp cursor 4) (eq (fn-omk-at 0 cursor) :waiting)
             (fn-omk-tokenp source) (fn-omk-widthp (fn-omk-at 3 cursor) 4)
             (fn-omk-widthp census 7)
             (member-eq (fn-omk-at 0 census) '(:need-row :prepared))
             (equal (fn-omk-at 1 census) (fn-omk-at 1 pair))
             (equal (fn-omk-at 2 census) (1+ (nfix (fn-omk-at 3 source))))
             (fn-omk-widthp capture 2)
             (equal (fn-omk-at 0 capture) (fn-omk-at 0 pair))
             (equal (fn-omk-at 1 capture) (fn-omk-at 1 pair)))
        (mv :acknowledged (fn-osm-advance cursor))
      (mv '(:refused :remap-census-ack) cursor))))
(defun fn-osm-emission-ack (cursor receipt)
  (declare (xargs :guard t))
  (if (and (fn-omk-widthp cursor 4) (eq (fn-omk-at 0 cursor) :waiting)
           (fn-omk-tokenp (fn-omk-at 1 cursor))
           (fn-omk-widthp (fn-omk-at 3 cursor) 4)
           (fn-omk-widthp receipt 3) (eq (fn-omk-at 0 receipt) :row-emitted)
           (fn-omk-token-matchp (fn-omk-at 1 receipt) (fn-omk-at 1 cursor))
           (natp (fn-omk-at 2 receipt)))
      (mv :acknowledged (fn-osm-advance cursor))
    (mv '(:refused :remap-emission-ack) cursor)))
; The exact issued source-row packet is transformed in core, never rebuilt
; in native code. The future source cursor remains the same borrowed pointer.
(defun fn-osm-prepare-row (cursor row)
  (declare (xargs :guard t))
  (if (not (and (fn-omk-widthp row 5) (eq (fn-omk-at 0 row) :row)
                (fn-omk-tokenp (fn-omk-at 3 row))
                (equal (fn-omk-at 1 row) (fn-omk-at 3 (fn-omk-at 3 row)))))
      (mv '(:refused :remap-row-packet) nil cursor)
    (mv-let (word next) (fn-osm-offer cursor (fn-omk-at 3 row) (fn-omk-at 2 row))
      (if (not (eq (fn-omk-at 0 word) :mapped)) (mv word nil cursor)
        (mv :mapped
            (list :row (fn-omk-at 1 row) (fn-omk-at 1 word)
                       (fn-omk-at 3 row) (fn-omk-at 4 row)) next)))))
