; Profile v2 commit codec: uint64 base, uint32 byte-string lengths, resumable
; admission/count/copy/reversal. Legacy stx-commit-codec remains unchanged.
; RFC 8949 sections 3 and 4.2.1. No host activation or signature-domain change.
(in-package "ACL2")
(include-book "stx-commit-codec")

(defun fn-stcp-at (n x)
 (declare (xargs :guard (natp n)))
 (if (zp n) (fn-cbor-ag-car x) (fn-stcp-at (1- n) (fn-cbor-ag-cdr x))))
(defun fn-stcp-widthp (x n)
 (declare (xargs :guard (natp n)))
 (if (zp n) (null x)
  (and (consp x) (fn-stcp-widthp (cdr x) (1- n)))))
; Caller-selected codec profile, not a storage/global epoch ceiling.
(defun fn-stcp-profile (wire-limit field-limit quantum)
 (declare (xargs :guard t))
 (list :fn-stcp-v2 wire-limit field-limit quantum))
(defun fn-stcp-profile-check (p)
 (declare (xargs :guard t))
 (cond ((not (and (fn-stcp-widthp p 4) (eq (fn-stcp-at 0 p) :fn-stcp-v2))) :unsupported-profile)
       ((not (and (natp (fn-stcp-at 1 p)) (natp (fn-stcp-at 2 p))
                  (natp (fn-stcp-at 3 p)))) :invalid-profile)
       ((or (< *fn-cbor-max-uint64* (fn-stcp-at 1 p))
            (< *fn-cbor-max-uint* (fn-stcp-at 2 p))
            (< *fn-cbor-max-uint64* (fn-stcp-at 3 p))) :unsupported-format)
       ((zp (fn-stcp-at 3 p)) :invalid-quantum)
       (t :supported)))
(defun fn-stcp-profilep (p)
 (declare (xargs :guard t))
 (eq (fn-stcp-profile-check p) :supported))
(defun fn-stcp-byte-head (n)
 (declare (xargs :guard (and (natp n) (<= n *fn-cbor-max-uint*))))
 (fn-cbor-encode-argument 2 n))
(defun fn-stcp-terminalp (c)
 (declare (xargs :guard t))
 (member-eq (fn-stcp-at 0 c) '(:done :refused)))

; Encoder: phase, remaining items, counting/body tail, count, original field,
; header tail, wire-reverse, reversal tail, output, emitted count, refusal.
(defun fn-stcp-enc-c (phase items tail count original header rev flip out wire why)
 (declare (xargs :guard t))
 (list phase items tail count original header rev flip out wire why))
(defun fn-stcp-enc-refuse (c why)
 (declare (xargs :guard t))
 (fn-stcp-enc-c :refused (fn-stcp-at 1 c) (fn-stcp-at 2 c) (fn-stcp-at 3 c)
  (fn-stcp-at 4 c) (fn-stcp-at 5 c) (fn-stcp-at 6 c) (fn-stcp-at 7 c)
  (fn-stcp-at 8 c) (fn-stcp-at 9 c) why))
(defun fn-stcp-encode-start (p commit)
 (declare (xargs :guard t))
 (let* ((check (fn-stcp-profile-check p))
        (base (fn-stcp-at 2 commit)) (op (fn-stcp-at 4 commit))
        (why (cond ((not (eq check :supported)) check)
                   ((not (and (fn-stcp-widthp commit 6)
                              (eq (fn-stcp-at 0 commit) :fn-me-commit)
                              (natp base) (fn-me-opp op))) :commit)
                   ((< *fn-cbor-max-uint64* base) :unsupported-format)
                   (t nil))))
  ; Unsupported scalar/profile is decided before item/byte output allocation.
  (if why (fn-stcp-enc-c :refused nil nil 0 nil nil nil nil nil 0 why)
   (fn-stcp-enc-c :choose
    (list (cons :bytes (fn-stcp-at 1 commit)) (cons :uint base)
          (cons :bytes (fn-stcp-at 3 commit)) (cons :uint (fn-stx-op-code op))
          (cons :bytes (fn-stcp-at 5 commit)))
    nil 0 nil nil nil nil nil 0 nil))))
(defun fn-stcp-enc-tick (p c)
 (declare (xargs :guard t))
 (let* ((phase (fn-stcp-at 0 c)) (items (fn-stcp-at 1 c))
        (tail (fn-stcp-at 2 c)) (n (nfix (fn-stcp-at 3 c)))
        (original (fn-stcp-at 4 c)) (head (fn-stcp-at 5 c))
        (rev (fn-stcp-at 6 c)) (flip (fn-stcp-at 7 c))
        (out (fn-stcp-at 8 c)) (wire (nfix (fn-stcp-at 9 c))))
  (cond
   ((fn-stcp-terminalp c) c)
   ((not (fn-stcp-profilep p)) (fn-stcp-enc-refuse c (fn-stcp-profile-check p)))
   ((eq phase :choose)
    (cond ((atom items)
           (fn-stcp-enc-c :reverse nil nil 0 nil nil rev rev nil wire nil))
          ((eq (fn-cbor-ag-car (car items)) :uint)
           (let ((v (fn-cbor-ag-cdr (car items))))
            (if (not (and (natp v) (<= v *fn-cbor-max-uint64*)))
             (fn-stcp-enc-refuse c :unsupported-format)
             (fn-stcp-enc-c :header items nil 0 nil (fn-cbor-encode-uint-wide v)
                            rev flip out wire nil))))
          ((eq (fn-cbor-ag-car (car items)) :bytes)
           (let ((xs (fn-cbor-ag-cdr (car items))))
            (fn-stcp-enc-c :count items xs 0 xs nil rev flip out wire nil)))
          (t (fn-stcp-enc-refuse c :item))))
   ((eq phase :count)
    (cond ((consp tail)
           (cond ((<= (nfix (fn-stcp-at 2 p)) n) (fn-stcp-enc-refuse c :profile-limit))
                 ((not (fn-cbor-octetp (car tail))) (fn-stcp-enc-refuse c :malformed))
                 (t (fn-stcp-enc-c :count items (cdr tail) (+ 1 n) original nil
                                   rev flip out wire nil))))
          ((not (null tail)) (fn-stcp-enc-refuse c :malformed))
          ((< *fn-cbor-max-uint* n) (fn-stcp-enc-refuse c :unsupported-format))
          (t (fn-stcp-enc-c :header items original n original (fn-stcp-byte-head n)
                            rev flip out wire nil))))
   ((eq phase :header)
    (if (consp head)
     (if (<= (nfix (fn-stcp-at 1 p)) wire) (fn-stcp-enc-refuse c :profile-limit)
      (fn-stcp-enc-c :header items tail n original (cdr head)
                     (cons (car head) rev) flip out (+ 1 wire) nil))
     (if (eq (fn-cbor-ag-car (fn-cbor-ag-car items)) :bytes)
      (fn-stcp-enc-c :body items original n original nil rev flip out wire nil)
      (fn-stcp-enc-c :choose (fn-cbor-ag-cdr items) nil 0 nil nil rev flip out wire nil))))
   ((eq phase :body)
    (if (consp tail)
     (cond ((<= (nfix (fn-stcp-at 1 p)) wire) (fn-stcp-enc-refuse c :profile-limit))
           ((not (fn-cbor-octetp (car tail))) (fn-stcp-enc-refuse c :malformed))
           (t (fn-stcp-enc-c :body items (cdr tail) n original nil
                             (cons (car tail) rev) flip out (+ 1 wire) nil)))
     (if (null tail)
      (fn-stcp-enc-c :choose (fn-cbor-ag-cdr items) nil 0 nil nil rev flip out wire nil)
      (fn-stcp-enc-refuse c :malformed))))
   ((eq phase :reverse)
    (if (consp flip)
     (fn-stcp-enc-c :reverse items tail n original head rev (cdr flip)
                    (cons (car flip) out) wire nil)
     (fn-stcp-enc-c :done items tail n original head rev nil out wire nil)))
   (t (fn-stcp-enc-refuse c :cursor)))))
(defun fn-stcp-enc-drive (p c fuel)
 (declare (xargs :guard (natp fuel) :measure (nfix fuel)))
 (if (or (zp fuel) (fn-stcp-terminalp c)) (mv c 0)
  (mv-let (next used) (fn-stcp-enc-drive p (fn-stcp-enc-tick p c) (1- fuel))
   (mv next (+ 1 (nfix used))))))
(defun fn-stcp-enc-result (c)
 (declare (xargs :guard t))
 (cond ((eq (fn-stcp-at 0 c) :done) (fn-stmt-ok (fn-stcp-at 8 c)))
       ((eq (fn-stcp-at 0 c) :refused) (fn-stmt-error (fn-stcp-at 10 c)))
       (t nil)))
(defun fn-stcp-encode-resume (p c)
 (declare (xargs :guard t))
 (fn-stcp-enc-drive p c (if (fn-stcp-profilep p) (nfix (fn-stcp-at 3 p)) 1)))

; Concrete source is a borrowed string; logical source is the remaining octet
; list. No full-source conversion or whole suffix validation in these readers.
(defun fn-stcp-source-empty (source offset)
 (declare (xargs :guard t))
 (if (stringp source) (<= (length source) (nfix offset)) (atom source)))
(defun fn-stcp-source-byte (source offset)
 (declare (xargs :guard t :guard-hints (("Goal" :in-theory (disable nfix char)))))
 (if (stringp source)
  (if (< (nfix offset) (length source))
   (let ((ch (char source (nfix offset)))) (if (characterp ch) (char-code ch) nil)) nil)
  (fn-cbor-ag-car source)))
(defun fn-stcp-source-next (source)
 (declare (xargs :guard t))
 (if (stringp source) source (fn-cbor-ag-cdr source)))
(defun fn-stcp-canonicalp (additional n)
 (declare (xargs :guard (and (natp additional) (natp n))))
 (if (equal additional 27) (< *fn-cbor-max-uint* n)
  (fn-cbor-canonical-argumentp additional n)))
; Decoder: phase, item index, source/tail, offset, additional, argument cells
; left, accumulated argument, body cells left, body reverse, reversal tail,
; ordered body, completed values reverse, wire consumed, refusal.
(defun fn-stcp-dec-c (phase index source offset ai left arg body rev flip out vals wire why)
 (declare (xargs :guard t))
 (list phase index source offset ai left arg body rev flip out vals wire why))
(defun fn-stcp-dec-refuse (c why)
 (declare (xargs :guard t))
 (fn-stcp-dec-c :refused (fn-stcp-at 1 c) (fn-stcp-at 2 c) (fn-stcp-at 3 c)
  (fn-stcp-at 4 c) (fn-stcp-at 5 c) (fn-stcp-at 6 c) (fn-stcp-at 7 c)
  (fn-stcp-at 8 c) (fn-stcp-at 9 c) (fn-stcp-at 10 c) (fn-stcp-at 11 c)
  (fn-stcp-at 12 c) why))
(defun fn-stcp-decode-start (p source)
 (declare (xargs :guard t))
 (let ((why (fn-stcp-profile-check p)))
  (fn-stcp-dec-c (if (eq why :supported) :head :refused) 0 source 0 0 0 0 0
                 nil nil nil nil 0 (if (eq why :supported) nil why))))
(defun fn-stcp-dec-value (p c value)
 (declare (xargs :guard t))
 (let* ((index (nfix (fn-stcp-at 1 c))) (source (fn-stcp-at 2 c))
        (offset (nfix (fn-stcp-at 3 c))) (vals (fn-stcp-at 11 c))
        (wire (nfix (fn-stcp-at 12 c))))
  (cond
   ((not (and (natp value) (<= value *fn-cbor-max-uint64*)))
    (fn-stcp-dec-refuse c :unsupported-format))
   ((member-equal index '(0 2 4))
    (cond ((< *fn-cbor-max-uint* value) (fn-stcp-dec-refuse c :unsupported-format))
          ((< (nfix (fn-stcp-at 2 p)) value) (fn-stcp-dec-refuse c :profile-limit))
          (t (fn-stcp-dec-c :body index source offset 0 0 0 value
                            nil nil nil vals wire nil))))
   ((and (equal index 3) (not (fn-stx-op-of-code value))) (fn-stcp-dec-refuse c :op))
   (t (fn-stcp-dec-c :head (+ 1 index) source offset 0 0 0 0
                     nil nil nil (cons value vals) wire nil)))))
(defun fn-stcp-dec-tick (p c)
 (declare (xargs :guard t :guard-hints (("Goal" :in-theory (disable fn-stcp-at fn-stcp-profilep fn-stcp-profile-check fn-stcp-source-byte fn-stcp-source-empty fn-stcp-terminalp floor mod)))))
 (let* ((phase (fn-stcp-at 0 c)) (index (nfix (fn-stcp-at 1 c)))
        (source (fn-stcp-at 2 c)) (offset (nfix (fn-stcp-at 3 c)))
        (ai (nfix (fn-stcp-at 4 c))) (left (nfix (fn-stcp-at 5 c)))
        (arg (nfix (fn-stcp-at 6 c))) (body (nfix (fn-stcp-at 7 c)))
        (rev (fn-stcp-at 8 c)) (flip (fn-stcp-at 9 c)) (out (fn-stcp-at 10 c))
        (vals (fn-stcp-at 11 c)) (wire (nfix (fn-stcp-at 12 c))))
  (cond
   ((fn-stcp-terminalp c) c)
   ((not (fn-stcp-profilep p)) (fn-stcp-dec-refuse c (fn-stcp-profile-check p)))
   ((and (eq phase :head) (equal index 5))
    (if (fn-stcp-source-empty source offset)
     (if (or (stringp source) (null source))
      (fn-stcp-dec-c :done index source offset ai left arg body rev flip out vals wire nil)
      (fn-stcp-dec-refuse c :malformed))
     (fn-stcp-dec-refuse c :trailing)))
   ((eq phase :reverse)
    (if (consp flip)
     (fn-stcp-dec-c :reverse index source offset ai left arg body rev (cdr flip)
                    (cons (car flip) out) vals wire nil)
     (fn-stcp-dec-c :head (+ 1 index) source offset 0 0 0 0 nil nil nil
                    (cons out vals) wire nil)))
   ((and (eq phase :body) (zp body))
    (fn-stcp-dec-c :reverse index source offset ai left arg 0 rev rev nil vals wire nil))
   ((not (member-eq phase '(:head :argument :body))) (fn-stcp-dec-refuse c :cursor))
   ((fn-stcp-source-empty source offset) (fn-stcp-dec-refuse c :truncated))
   ((<= (nfix (fn-stcp-at 1 p)) wire) (fn-stcp-dec-refuse c :profile-limit))
   (t
    (let* ((b (fn-stcp-source-byte source offset))
           (nextsource (fn-stcp-source-next source))
           (nextoffset (+ 1 offset)) (nextwire (+ 1 wire)))
     (if (not (fn-cbor-octetp b)) (fn-stcp-dec-refuse c :malformed)
      (cond
       ((eq phase :body)
        (fn-stcp-dec-c :body index nextsource nextoffset ai left arg (1- body)
                       (cons b rev) flip out vals nextwire nil))
       ((eq phase :argument)
        (let* ((n (+ (* 256 arg) b))
               (next (fn-stcp-dec-c :argument index nextsource nextoffset ai
                       (if (zp left) 0 (1- left)) n body rev flip out vals nextwire nil)))
         (cond ((< *fn-cbor-max-uint64* n) (fn-stcp-dec-refuse next :unsupported-format))
               ((<= left 1)
                (if (fn-stcp-canonicalp ai n) (fn-stcp-dec-value p next n)
                 (fn-stcp-dec-refuse next :noncanonical)))
               (t next))))
       (t
        (let* ((major (floor b 32)) (add (mod b 32))
               (expected (if (member-equal index '(0 2 4)) 2 0))
               (width (cond ((equal add 24) 1) ((equal add 25) 2)
                            ((equal add 26) 4) ((equal add 27) 8) (t 0)))
               (next (fn-stcp-dec-c :argument index nextsource nextoffset add width 0
                                   body rev flip out vals nextwire nil)))
         (cond ((not (equal major expected)) (fn-stcp-dec-refuse next :field))
               ((< add 24) (fn-stcp-dec-value p next add))
               ((or (zp width) (and (equal expected 2) (equal add 27)))
                (fn-stcp-dec-refuse next :unsupported-format))
               (t next)))))))))))
(defun fn-stcp-dec-drive (p c fuel)
 (declare (xargs :guard (natp fuel) :measure (nfix fuel)))
 (if (or (zp fuel) (fn-stcp-terminalp c)) (mv c 0)
  (mv-let (next used) (fn-stcp-dec-drive p (fn-stcp-dec-tick p c) (1- fuel))
   (mv next (+ 1 (nfix used))))))
(defun fn-stcp-dec-result (c)
 (declare (xargs :guard t))
 (cond ((eq (fn-stcp-at 0 c) :refused) (fn-stmt-error (fn-stcp-at 13 c)))
       ((eq (fn-stcp-at 0 c) :done)
        (let* ((vals (fn-stcp-at 11 c)) (base (fn-stcp-at 3 vals))
               (op (fn-stx-op-of-code (fn-stcp-at 1 vals))))
         (if (and (natp base) (<= base *fn-cbor-max-uint64*) op)
          (fn-stmt-ok (fn-me-commit (fn-stcp-at 4 vals) base
                                   (fn-stcp-at 2 vals) op (fn-stcp-at 0 vals)))
          (fn-stmt-error :commit))))
       (t nil)))
(defun fn-stcp-decode-resume (p c)
 (declare (xargs :guard t))
 (fn-stcp-dec-drive p c (if (fn-stcp-profilep p) (nfix (fn-stcp-at 3 p)) 1)))

(defthm fn-stcp-enc-drive-work-bound
 (<= (mv-nth 1 (fn-stcp-enc-drive p c fuel)) (nfix fuel))
 :hints (("Goal" :induct (fn-stcp-enc-drive p c fuel)
          :in-theory (disable fn-stcp-enc-tick fn-stcp-terminalp))))
(defthm fn-stcp-dec-drive-work-bound
 (<= (mv-nth 1 (fn-stcp-dec-drive p c fuel)) (nfix fuel))
 :hints (("Goal" :induct (fn-stcp-dec-drive p c fuel)
          :in-theory (disable fn-stcp-dec-tick fn-stcp-terminalp))))
(defthm fn-stcp-enc-terminal-is-stable
 (implies (fn-stcp-terminalp c) (equal (mv-nth 0 (fn-stcp-enc-drive p c fuel)) c))
 :hints (("Goal" :in-theory (enable fn-stcp-enc-drive))))
(defthm fn-stcp-dec-terminal-is-stable
 (implies (fn-stcp-terminalp c) (equal (mv-nth 0 (fn-stcp-dec-drive p c fuel)) c))
 :hints (("Goal" :in-theory (enable fn-stcp-dec-drive))))
