; fn TCPCLv4: the opaque records of the tcpcl cluster.
;
; GENERATED by the lane's gen_records.py (planning/lanes/HANDOFF-w4-tcpcl.md);
; edit the generator, not this file.  Each record is a tagged positional
; list: shape, total accessors, constructor, record lemmas, forward-chaining
; shape facts, then withdrawal of every :definition rune (docs/proof-style.md
; section 1).  fn-tcl-msg-kind is the shared tag accessor.

(in-package "ACL2")
(include-book "cbor")

(defun fn-tcl-msg-kind (x)
  (declare (xargs :guard t))
  (fn-cbor-ag-car x))

; --- contact: Contact Header (RFC 9174 section 4.2): version octet and the raw flags octet; bit 0 is CAN_TLS.

(defun fn-tcl-contact-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 3) (equal (car x) :contact)))

(defun fn-tcl-contact-version (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-contact-version)

(defun fn-tcl-contact-flags (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-contact-flags)

(defun fn-tcl-make-contact (version flags)
  (declare (xargs :guard t))
  (list :contact version flags))

(defthm fn-tcl-contact-shapep-of-fn-tcl-make-contact
  (fn-tcl-contact-shapep (fn-tcl-make-contact version flags)))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-contact
  (equal (fn-tcl-msg-kind (fn-tcl-make-contact version flags)) :contact))

(defthm fn-tcl-contact-version-of-fn-tcl-make-contact
  (equal (fn-tcl-contact-version (fn-tcl-make-contact version flags)) version))

(defthm fn-tcl-contact-flags-of-fn-tcl-make-contact
  (equal (fn-tcl-contact-flags (fn-tcl-make-contact version flags)) flags))

(defthm fn-tcl-contact-shapep-forward-shape
  (implies (fn-tcl-contact-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :contact)))
  :rule-classes :forward-chaining)

(defthm fn-tcl-contact-accessors-forward-consp
  (and (implies (fn-tcl-contact-version x) (consp x))
       (implies (fn-tcl-contact-flags x) (consp x)))
  :rule-classes ((:forward-chaining :corollary (implies (fn-tcl-contact-version x) (consp x))
                                    :trigger-terms ((fn-tcl-contact-version x)))
                 (:forward-chaining :corollary (implies (fn-tcl-contact-flags x) (consp x))
                                    :trigger-terms ((fn-tcl-contact-flags x)))))

; --- sess-init: SESS_INIT (section 4.6): keepalive seconds, the two MRUs, the node ID octets, the session extension items.

(defun fn-tcl-sess-init-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 6) (equal (car x) :sess-init)))

(defun fn-tcl-sess-init-keepalive (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-sess-init-keepalive)

(defun fn-tcl-sess-init-segment-mru (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-sess-init-segment-mru)

(defun fn-tcl-sess-init-transfer-mru (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr x)))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))
(verify-guards fn-tcl-sess-init-transfer-mru)

(defun fn-tcl-sess-init-node-id (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr x))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))))
(verify-guards fn-tcl-sess-init-node-id)

(defun fn-tcl-sess-init-ext (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr (cdr x)))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))))
(verify-guards fn-tcl-sess-init-ext)

(defun fn-tcl-make-sess-init (keepalive segment-mru transfer-mru node-id ext)
  (declare (xargs :guard t))
  (list :sess-init keepalive segment-mru transfer-mru node-id ext))

(defthm fn-tcl-sess-init-shapep-of-fn-tcl-make-sess-init
  (fn-tcl-sess-init-shapep (fn-tcl-make-sess-init keepalive segment-mru transfer-mru node-id ext)))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-sess-init
  (equal (fn-tcl-msg-kind (fn-tcl-make-sess-init keepalive segment-mru transfer-mru node-id ext)) :sess-init))

(defthm fn-tcl-sess-init-keepalive-of-fn-tcl-make-sess-init
  (equal (fn-tcl-sess-init-keepalive (fn-tcl-make-sess-init keepalive segment-mru transfer-mru node-id ext)) keepalive))

(defthm fn-tcl-sess-init-segment-mru-of-fn-tcl-make-sess-init
  (equal (fn-tcl-sess-init-segment-mru (fn-tcl-make-sess-init keepalive segment-mru transfer-mru node-id ext)) segment-mru))

(defthm fn-tcl-sess-init-transfer-mru-of-fn-tcl-make-sess-init
  (equal (fn-tcl-sess-init-transfer-mru (fn-tcl-make-sess-init keepalive segment-mru transfer-mru node-id ext)) transfer-mru))

(defthm fn-tcl-sess-init-node-id-of-fn-tcl-make-sess-init
  (equal (fn-tcl-sess-init-node-id (fn-tcl-make-sess-init keepalive segment-mru transfer-mru node-id ext)) node-id))

(defthm fn-tcl-sess-init-ext-of-fn-tcl-make-sess-init
  (equal (fn-tcl-sess-init-ext (fn-tcl-make-sess-init keepalive segment-mru transfer-mru node-id ext)) ext))

(defthm fn-tcl-sess-init-shapep-forward-shape
  (implies (fn-tcl-sess-init-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :sess-init)))
  :rule-classes :forward-chaining)

(defthm fn-tcl-sess-init-accessors-forward-consp
  (and (implies (fn-tcl-sess-init-keepalive x) (consp x))
       (implies (fn-tcl-sess-init-segment-mru x) (consp x))
       (implies (fn-tcl-sess-init-transfer-mru x) (consp x))
       (implies (fn-tcl-sess-init-node-id x) (consp x))
       (implies (fn-tcl-sess-init-ext x) (consp x)))
  :rule-classes ((:forward-chaining :corollary (implies (fn-tcl-sess-init-keepalive x) (consp x))
                                    :trigger-terms ((fn-tcl-sess-init-keepalive x)))
                 (:forward-chaining :corollary (implies (fn-tcl-sess-init-segment-mru x) (consp x))
                                    :trigger-terms ((fn-tcl-sess-init-segment-mru x)))
                 (:forward-chaining :corollary (implies (fn-tcl-sess-init-transfer-mru x) (consp x))
                                    :trigger-terms ((fn-tcl-sess-init-transfer-mru x)))
                 (:forward-chaining :corollary (implies (fn-tcl-sess-init-node-id x) (consp x))
                                    :trigger-terms ((fn-tcl-sess-init-node-id x)))
                 (:forward-chaining :corollary (implies (fn-tcl-sess-init-ext x) (consp x))
                                    :trigger-terms ((fn-tcl-sess-init-ext x)))))

; --- xfer-segment: XFER_SEGMENT (section 5.2.2): raw flags octet (bit 0 END, bit 1 START), transfer ID, transfer extension items (present only with START), data octets.

(defun fn-tcl-xfer-segment-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 5) (equal (car x) :xfer-segment)))

(defun fn-tcl-xfer-segment-flags (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-xfer-segment-flags)

(defun fn-tcl-xfer-segment-xfer-id (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-xfer-segment-xfer-id)

(defun fn-tcl-xfer-segment-ext (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr x)))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))
(verify-guards fn-tcl-xfer-segment-ext)

(defun fn-tcl-xfer-segment-data (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr x))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))))
(verify-guards fn-tcl-xfer-segment-data)

(defun fn-tcl-make-xfer-segment (flags xfer-id ext data)
  (declare (xargs :guard t))
  (list :xfer-segment flags xfer-id ext data))

(defthm fn-tcl-xfer-segment-shapep-of-fn-tcl-make-xfer-segment
  (fn-tcl-xfer-segment-shapep (fn-tcl-make-xfer-segment flags xfer-id ext data)))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-xfer-segment
  (equal (fn-tcl-msg-kind (fn-tcl-make-xfer-segment flags xfer-id ext data)) :xfer-segment))

(defthm fn-tcl-xfer-segment-flags-of-fn-tcl-make-xfer-segment
  (equal (fn-tcl-xfer-segment-flags (fn-tcl-make-xfer-segment flags xfer-id ext data)) flags))

(defthm fn-tcl-xfer-segment-xfer-id-of-fn-tcl-make-xfer-segment
  (equal (fn-tcl-xfer-segment-xfer-id (fn-tcl-make-xfer-segment flags xfer-id ext data)) xfer-id))

(defthm fn-tcl-xfer-segment-ext-of-fn-tcl-make-xfer-segment
  (equal (fn-tcl-xfer-segment-ext (fn-tcl-make-xfer-segment flags xfer-id ext data)) ext))

(defthm fn-tcl-xfer-segment-data-of-fn-tcl-make-xfer-segment
  (equal (fn-tcl-xfer-segment-data (fn-tcl-make-xfer-segment flags xfer-id ext data)) data))

(defthm fn-tcl-xfer-segment-shapep-forward-shape
  (implies (fn-tcl-xfer-segment-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :xfer-segment)))
  :rule-classes :forward-chaining)

(defthm fn-tcl-xfer-segment-accessors-forward-consp
  (and (implies (fn-tcl-xfer-segment-flags x) (consp x))
       (implies (fn-tcl-xfer-segment-xfer-id x) (consp x))
       (implies (fn-tcl-xfer-segment-ext x) (consp x))
       (implies (fn-tcl-xfer-segment-data x) (consp x)))
  :rule-classes ((:forward-chaining :corollary (implies (fn-tcl-xfer-segment-flags x) (consp x))
                                    :trigger-terms ((fn-tcl-xfer-segment-flags x)))
                 (:forward-chaining :corollary (implies (fn-tcl-xfer-segment-xfer-id x) (consp x))
                                    :trigger-terms ((fn-tcl-xfer-segment-xfer-id x)))
                 (:forward-chaining :corollary (implies (fn-tcl-xfer-segment-ext x) (consp x))
                                    :trigger-terms ((fn-tcl-xfer-segment-ext x)))
                 (:forward-chaining :corollary (implies (fn-tcl-xfer-segment-data x) (consp x))
                                    :trigger-terms ((fn-tcl-xfer-segment-data x)))))

; --- xfer-ack: XFER_ACK (section 5.2.3): the acknowledged segment's flags, transfer ID, cumulative acknowledged length.

(defun fn-tcl-xfer-ack-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 4) (equal (car x) :xfer-ack)))

(defun fn-tcl-xfer-ack-flags (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-xfer-ack-flags)

(defun fn-tcl-xfer-ack-xfer-id (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-xfer-ack-xfer-id)

(defun fn-tcl-xfer-ack-acked-len (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr x)))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))
(verify-guards fn-tcl-xfer-ack-acked-len)

(defun fn-tcl-make-xfer-ack (flags xfer-id acked-len)
  (declare (xargs :guard t))
  (list :xfer-ack flags xfer-id acked-len))

(defthm fn-tcl-xfer-ack-shapep-of-fn-tcl-make-xfer-ack
  (fn-tcl-xfer-ack-shapep (fn-tcl-make-xfer-ack flags xfer-id acked-len)))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-xfer-ack
  (equal (fn-tcl-msg-kind (fn-tcl-make-xfer-ack flags xfer-id acked-len)) :xfer-ack))

(defthm fn-tcl-xfer-ack-flags-of-fn-tcl-make-xfer-ack
  (equal (fn-tcl-xfer-ack-flags (fn-tcl-make-xfer-ack flags xfer-id acked-len)) flags))

(defthm fn-tcl-xfer-ack-xfer-id-of-fn-tcl-make-xfer-ack
  (equal (fn-tcl-xfer-ack-xfer-id (fn-tcl-make-xfer-ack flags xfer-id acked-len)) xfer-id))

(defthm fn-tcl-xfer-ack-acked-len-of-fn-tcl-make-xfer-ack
  (equal (fn-tcl-xfer-ack-acked-len (fn-tcl-make-xfer-ack flags xfer-id acked-len)) acked-len))

(defthm fn-tcl-xfer-ack-shapep-forward-shape
  (implies (fn-tcl-xfer-ack-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :xfer-ack)))
  :rule-classes :forward-chaining)

(defthm fn-tcl-xfer-ack-accessors-forward-consp
  (and (implies (fn-tcl-xfer-ack-flags x) (consp x))
       (implies (fn-tcl-xfer-ack-xfer-id x) (consp x))
       (implies (fn-tcl-xfer-ack-acked-len x) (consp x)))
  :rule-classes ((:forward-chaining :corollary (implies (fn-tcl-xfer-ack-flags x) (consp x))
                                    :trigger-terms ((fn-tcl-xfer-ack-flags x)))
                 (:forward-chaining :corollary (implies (fn-tcl-xfer-ack-xfer-id x) (consp x))
                                    :trigger-terms ((fn-tcl-xfer-ack-xfer-id x)))
                 (:forward-chaining :corollary (implies (fn-tcl-xfer-ack-acked-len x) (consp x))
                                    :trigger-terms ((fn-tcl-xfer-ack-acked-len x)))))

; --- xfer-refuse: XFER_REFUSE (section 5.2.4): Table 6 reason code, transfer ID.

(defun fn-tcl-xfer-refuse-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 3) (equal (car x) :xfer-refuse)))

(defun fn-tcl-xfer-refuse-reason (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-xfer-refuse-reason)

(defun fn-tcl-xfer-refuse-xfer-id (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-xfer-refuse-xfer-id)

(defun fn-tcl-make-xfer-refuse (reason xfer-id)
  (declare (xargs :guard t))
  (list :xfer-refuse reason xfer-id))

(defthm fn-tcl-xfer-refuse-shapep-of-fn-tcl-make-xfer-refuse
  (fn-tcl-xfer-refuse-shapep (fn-tcl-make-xfer-refuse reason xfer-id)))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-xfer-refuse
  (equal (fn-tcl-msg-kind (fn-tcl-make-xfer-refuse reason xfer-id)) :xfer-refuse))

(defthm fn-tcl-xfer-refuse-reason-of-fn-tcl-make-xfer-refuse
  (equal (fn-tcl-xfer-refuse-reason (fn-tcl-make-xfer-refuse reason xfer-id)) reason))

(defthm fn-tcl-xfer-refuse-xfer-id-of-fn-tcl-make-xfer-refuse
  (equal (fn-tcl-xfer-refuse-xfer-id (fn-tcl-make-xfer-refuse reason xfer-id)) xfer-id))

(defthm fn-tcl-xfer-refuse-shapep-forward-shape
  (implies (fn-tcl-xfer-refuse-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :xfer-refuse)))
  :rule-classes :forward-chaining)

(defthm fn-tcl-xfer-refuse-accessors-forward-consp
  (and (implies (fn-tcl-xfer-refuse-reason x) (consp x))
       (implies (fn-tcl-xfer-refuse-xfer-id x) (consp x)))
  :rule-classes ((:forward-chaining :corollary (implies (fn-tcl-xfer-refuse-reason x) (consp x))
                                    :trigger-terms ((fn-tcl-xfer-refuse-reason x)))
                 (:forward-chaining :corollary (implies (fn-tcl-xfer-refuse-xfer-id x) (consp x))
                                    :trigger-terms ((fn-tcl-xfer-refuse-xfer-id x)))))

; --- keepalive: KEEPALIVE (section 5.1.1): no fields.

(defun fn-tcl-keepalive-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 1) (equal (car x) :keepalive)))

(defun fn-tcl-make-keepalive ()
  (declare (xargs :guard t))
  (list :keepalive))

(defthm fn-tcl-keepalive-shapep-of-fn-tcl-make-keepalive
  (fn-tcl-keepalive-shapep (fn-tcl-make-keepalive )))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-keepalive
  (equal (fn-tcl-msg-kind (fn-tcl-make-keepalive )) :keepalive))

(defthm fn-tcl-keepalive-shapep-forward-shape
  (implies (fn-tcl-keepalive-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :keepalive)))
  :rule-classes :forward-chaining)

; --- sess-term: SESS_TERM (section 6.1): raw flags octet (bit 0 REPLY), Table 9 reason code.

(defun fn-tcl-sess-term-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 3) (equal (car x) :sess-term)))

(defun fn-tcl-sess-term-flags (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-sess-term-flags)

(defun fn-tcl-sess-term-reason (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-sess-term-reason)

(defun fn-tcl-make-sess-term (flags reason)
  (declare (xargs :guard t))
  (list :sess-term flags reason))

(defthm fn-tcl-sess-term-shapep-of-fn-tcl-make-sess-term
  (fn-tcl-sess-term-shapep (fn-tcl-make-sess-term flags reason)))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-sess-term
  (equal (fn-tcl-msg-kind (fn-tcl-make-sess-term flags reason)) :sess-term))

(defthm fn-tcl-sess-term-flags-of-fn-tcl-make-sess-term
  (equal (fn-tcl-sess-term-flags (fn-tcl-make-sess-term flags reason)) flags))

(defthm fn-tcl-sess-term-reason-of-fn-tcl-make-sess-term
  (equal (fn-tcl-sess-term-reason (fn-tcl-make-sess-term flags reason)) reason))

(defthm fn-tcl-sess-term-shapep-forward-shape
  (implies (fn-tcl-sess-term-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :sess-term)))
  :rule-classes :forward-chaining)

(defthm fn-tcl-sess-term-accessors-forward-consp
  (and (implies (fn-tcl-sess-term-flags x) (consp x))
       (implies (fn-tcl-sess-term-reason x) (consp x)))
  :rule-classes ((:forward-chaining :corollary (implies (fn-tcl-sess-term-flags x) (consp x))
                                    :trigger-terms ((fn-tcl-sess-term-flags x)))
                 (:forward-chaining :corollary (implies (fn-tcl-sess-term-reason x) (consp x))
                                    :trigger-terms ((fn-tcl-sess-term-reason x)))))

; --- msg-reject: MSG_REJECT (section 5.1.2): Table 4 reason code, the rejected message header octet.

(defun fn-tcl-msg-reject-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 3) (equal (car x) :msg-reject)))

(defun fn-tcl-msg-reject-reason (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-msg-reject-reason)

(defun fn-tcl-msg-reject-header (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-msg-reject-header)

(defun fn-tcl-make-msg-reject (reason header)
  (declare (xargs :guard t))
  (list :msg-reject reason header))

(defthm fn-tcl-msg-reject-shapep-of-fn-tcl-make-msg-reject
  (fn-tcl-msg-reject-shapep (fn-tcl-make-msg-reject reason header)))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-msg-reject
  (equal (fn-tcl-msg-kind (fn-tcl-make-msg-reject reason header)) :msg-reject))

(defthm fn-tcl-msg-reject-reason-of-fn-tcl-make-msg-reject
  (equal (fn-tcl-msg-reject-reason (fn-tcl-make-msg-reject reason header)) reason))

(defthm fn-tcl-msg-reject-header-of-fn-tcl-make-msg-reject
  (equal (fn-tcl-msg-reject-header (fn-tcl-make-msg-reject reason header)) header))

(defthm fn-tcl-msg-reject-shapep-forward-shape
  (implies (fn-tcl-msg-reject-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :msg-reject)))
  :rule-classes :forward-chaining)

(defthm fn-tcl-msg-reject-accessors-forward-consp
  (and (implies (fn-tcl-msg-reject-reason x) (consp x))
       (implies (fn-tcl-msg-reject-header x) (consp x)))
  :rule-classes ((:forward-chaining :corollary (implies (fn-tcl-msg-reject-reason x) (consp x))
                                    :trigger-terms ((fn-tcl-msg-reject-reason x)))
                 (:forward-chaining :corollary (implies (fn-tcl-msg-reject-header x) (consp x))
                                    :trigger-terms ((fn-tcl-msg-reject-header x)))))

; --- item: A session or transfer extension item (sections 4.8 and 5.2.5): raw flags octet (bit 0 CRITICAL), 16-bit type, value octets.

(defun fn-tcl-item-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 4) (equal (car x) :item)))

(defun fn-tcl-item-flags (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-item-flags)

(defun fn-tcl-item-type (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-item-type)

(defun fn-tcl-item-value (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr x)))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))
(verify-guards fn-tcl-item-value)

(defun fn-tcl-make-item (flags type value)
  (declare (xargs :guard t))
  (list :item flags type value))

(defthm fn-tcl-item-shapep-of-fn-tcl-make-item
  (fn-tcl-item-shapep (fn-tcl-make-item flags type value)))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-item
  (equal (fn-tcl-msg-kind (fn-tcl-make-item flags type value)) :item))

(defthm fn-tcl-item-flags-of-fn-tcl-make-item
  (equal (fn-tcl-item-flags (fn-tcl-make-item flags type value)) flags))

(defthm fn-tcl-item-type-of-fn-tcl-make-item
  (equal (fn-tcl-item-type (fn-tcl-make-item flags type value)) type))

(defthm fn-tcl-item-value-of-fn-tcl-make-item
  (equal (fn-tcl-item-value (fn-tcl-make-item flags type value)) value))

(defthm fn-tcl-item-shapep-forward-shape
  (implies (fn-tcl-item-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :item)))
  :rule-classes :forward-chaining)

(defthm fn-tcl-item-accessors-forward-consp
  (and (implies (fn-tcl-item-flags x) (consp x))
       (implies (fn-tcl-item-type x) (consp x))
       (implies (fn-tcl-item-value x) (consp x)))
  :rule-classes ((:forward-chaining :corollary (implies (fn-tcl-item-flags x) (consp x))
                                    :trigger-terms ((fn-tcl-item-flags x)))
                 (:forward-chaining :corollary (implies (fn-tcl-item-type x) (consp x))
                                    :trigger-terms ((fn-tcl-item-type x)))
                 (:forward-chaining :corollary (implies (fn-tcl-item-value x) (consp x))
                                    :trigger-terms ((fn-tcl-item-value x)))))

; --- params: One entity's SESS_INIT parameters plus the contact-plan binding: can-tls is the Contact Header flag, expected-peer is nil or the node ID octets the session must announce.

(defun fn-tcl-params-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 7) (equal (car x) :params)))

(defun fn-tcl-params-keepalive (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-params-keepalive)

(defun fn-tcl-params-segment-mru (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-params-segment-mru)

(defun fn-tcl-params-transfer-mru (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr x)))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))
(verify-guards fn-tcl-params-transfer-mru)

(defun fn-tcl-params-node-id (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr x))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))))
(verify-guards fn-tcl-params-node-id)

(defun fn-tcl-params-can-tls (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr (cdr x)))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))))
(verify-guards fn-tcl-params-can-tls)

(defun fn-tcl-params-expected-peer (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr (cdr (cdr x))))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))))))
(verify-guards fn-tcl-params-expected-peer)

(defun fn-tcl-make-params (keepalive segment-mru transfer-mru node-id can-tls expected-peer)
  (declare (xargs :guard t))
  (list :params keepalive segment-mru transfer-mru node-id can-tls expected-peer))

(defthm fn-tcl-params-shapep-of-fn-tcl-make-params
  (fn-tcl-params-shapep (fn-tcl-make-params keepalive segment-mru transfer-mru node-id can-tls expected-peer)))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-params
  (equal (fn-tcl-msg-kind (fn-tcl-make-params keepalive segment-mru transfer-mru node-id can-tls expected-peer)) :params))

(defthm fn-tcl-params-keepalive-of-fn-tcl-make-params
  (equal (fn-tcl-params-keepalive (fn-tcl-make-params keepalive segment-mru transfer-mru node-id can-tls expected-peer)) keepalive))

(defthm fn-tcl-params-segment-mru-of-fn-tcl-make-params
  (equal (fn-tcl-params-segment-mru (fn-tcl-make-params keepalive segment-mru transfer-mru node-id can-tls expected-peer)) segment-mru))

(defthm fn-tcl-params-transfer-mru-of-fn-tcl-make-params
  (equal (fn-tcl-params-transfer-mru (fn-tcl-make-params keepalive segment-mru transfer-mru node-id can-tls expected-peer)) transfer-mru))

(defthm fn-tcl-params-node-id-of-fn-tcl-make-params
  (equal (fn-tcl-params-node-id (fn-tcl-make-params keepalive segment-mru transfer-mru node-id can-tls expected-peer)) node-id))

(defthm fn-tcl-params-can-tls-of-fn-tcl-make-params
  (equal (fn-tcl-params-can-tls (fn-tcl-make-params keepalive segment-mru transfer-mru node-id can-tls expected-peer)) can-tls))

(defthm fn-tcl-params-expected-peer-of-fn-tcl-make-params
  (equal (fn-tcl-params-expected-peer (fn-tcl-make-params keepalive segment-mru transfer-mru node-id can-tls expected-peer)) expected-peer))

(defthm fn-tcl-params-shapep-forward-shape
  (implies (fn-tcl-params-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :params)))
  :rule-classes :forward-chaining)

(defthm fn-tcl-params-accessors-forward-consp
  (and (implies (fn-tcl-params-keepalive x) (consp x))
       (implies (fn-tcl-params-segment-mru x) (consp x))
       (implies (fn-tcl-params-transfer-mru x) (consp x))
       (implies (fn-tcl-params-node-id x) (consp x))
       (implies (fn-tcl-params-can-tls x) (consp x))
       (implies (fn-tcl-params-expected-peer x) (consp x)))
  :rule-classes ((:forward-chaining :corollary (implies (fn-tcl-params-keepalive x) (consp x))
                                    :trigger-terms ((fn-tcl-params-keepalive x)))
                 (:forward-chaining :corollary (implies (fn-tcl-params-segment-mru x) (consp x))
                                    :trigger-terms ((fn-tcl-params-segment-mru x)))
                 (:forward-chaining :corollary (implies (fn-tcl-params-transfer-mru x) (consp x))
                                    :trigger-terms ((fn-tcl-params-transfer-mru x)))
                 (:forward-chaining :corollary (implies (fn-tcl-params-node-id x) (consp x))
                                    :trigger-terms ((fn-tcl-params-node-id x)))
                 (:forward-chaining :corollary (implies (fn-tcl-params-can-tls x) (consp x))
                                    :trigger-terms ((fn-tcl-params-can-tls x)))
                 (:forward-chaining :corollary (implies (fn-tcl-params-expected-peer x) (consp x))
                                    :trigger-terms ((fn-tcl-params-expected-peer x)))))

; --- negotiated: The section 4.3 and 4.7 negotiation result: minimum keepalive, the peer's MRUs as this side's MTUs, the conjunction of CAN_TLS, and the announced peer node ID.

(defun fn-tcl-negotiated-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 6) (equal (car x) :negotiated)))

(defun fn-tcl-negotiated-keepalive (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-negotiated-keepalive)

(defun fn-tcl-negotiated-segment-mtu (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-negotiated-segment-mtu)

(defun fn-tcl-negotiated-transfer-mtu (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr x)))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))
(verify-guards fn-tcl-negotiated-transfer-mtu)

(defun fn-tcl-negotiated-tls (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr x))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))))
(verify-guards fn-tcl-negotiated-tls)

(defun fn-tcl-negotiated-peer-node-id (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr (cdr x)))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))))
(verify-guards fn-tcl-negotiated-peer-node-id)

(defun fn-tcl-make-negotiated (keepalive segment-mtu transfer-mtu tls peer-node-id)
  (declare (xargs :guard t))
  (list :negotiated keepalive segment-mtu transfer-mtu tls peer-node-id))

(defthm fn-tcl-negotiated-shapep-of-fn-tcl-make-negotiated
  (fn-tcl-negotiated-shapep (fn-tcl-make-negotiated keepalive segment-mtu transfer-mtu tls peer-node-id)))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-negotiated
  (equal (fn-tcl-msg-kind (fn-tcl-make-negotiated keepalive segment-mtu transfer-mtu tls peer-node-id)) :negotiated))

(defthm fn-tcl-negotiated-keepalive-of-fn-tcl-make-negotiated
  (equal (fn-tcl-negotiated-keepalive (fn-tcl-make-negotiated keepalive segment-mtu transfer-mtu tls peer-node-id)) keepalive))

(defthm fn-tcl-negotiated-segment-mtu-of-fn-tcl-make-negotiated
  (equal (fn-tcl-negotiated-segment-mtu (fn-tcl-make-negotiated keepalive segment-mtu transfer-mtu tls peer-node-id)) segment-mtu))

(defthm fn-tcl-negotiated-transfer-mtu-of-fn-tcl-make-negotiated
  (equal (fn-tcl-negotiated-transfer-mtu (fn-tcl-make-negotiated keepalive segment-mtu transfer-mtu tls peer-node-id)) transfer-mtu))

(defthm fn-tcl-negotiated-tls-of-fn-tcl-make-negotiated
  (equal (fn-tcl-negotiated-tls (fn-tcl-make-negotiated keepalive segment-mtu transfer-mtu tls peer-node-id)) tls))

(defthm fn-tcl-negotiated-peer-node-id-of-fn-tcl-make-negotiated
  (equal (fn-tcl-negotiated-peer-node-id (fn-tcl-make-negotiated keepalive segment-mtu transfer-mtu tls peer-node-id)) peer-node-id))

(defthm fn-tcl-negotiated-shapep-forward-shape
  (implies (fn-tcl-negotiated-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :negotiated)))
  :rule-classes :forward-chaining)

(defthm fn-tcl-negotiated-accessors-forward-consp
  (and (implies (fn-tcl-negotiated-keepalive x) (consp x))
       (implies (fn-tcl-negotiated-segment-mtu x) (consp x))
       (implies (fn-tcl-negotiated-transfer-mtu x) (consp x))
       (implies (fn-tcl-negotiated-tls x) (consp x))
       (implies (fn-tcl-negotiated-peer-node-id x) (consp x)))
  :rule-classes ((:forward-chaining :corollary (implies (fn-tcl-negotiated-keepalive x) (consp x))
                                    :trigger-terms ((fn-tcl-negotiated-keepalive x)))
                 (:forward-chaining :corollary (implies (fn-tcl-negotiated-segment-mtu x) (consp x))
                                    :trigger-terms ((fn-tcl-negotiated-segment-mtu x)))
                 (:forward-chaining :corollary (implies (fn-tcl-negotiated-transfer-mtu x) (consp x))
                                    :trigger-terms ((fn-tcl-negotiated-transfer-mtu x)))
                 (:forward-chaining :corollary (implies (fn-tcl-negotiated-tls x) (consp x))
                                    :trigger-terms ((fn-tcl-negotiated-tls x)))
                 (:forward-chaining :corollary (implies (fn-tcl-negotiated-peer-node-id x) (consp x))
                                    :trigger-terms ((fn-tcl-negotiated-peer-node-id x)))))

; --- inbound: The one live inbound transfer: its ID, the accepted segment data lists newest first, the carried sum of their lengths, and the Transfer Length Extension total or nil.

(defun fn-tcl-inbound-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 5) (equal (car x) :inbound)))

(defun fn-tcl-inbound-xfer-id (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-inbound-xfer-id)

(defun fn-tcl-inbound-staged (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-inbound-staged)

(defun fn-tcl-inbound-received-len (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr x)))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))
(verify-guards fn-tcl-inbound-received-len)

(defun fn-tcl-inbound-total (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr x))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))))
(verify-guards fn-tcl-inbound-total)

(defun fn-tcl-make-inbound (xfer-id staged received-len total)
  (declare (xargs :guard t))
  (list :inbound xfer-id staged received-len total))

(defthm fn-tcl-inbound-shapep-of-fn-tcl-make-inbound
  (fn-tcl-inbound-shapep (fn-tcl-make-inbound xfer-id staged received-len total)))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-inbound
  (equal (fn-tcl-msg-kind (fn-tcl-make-inbound xfer-id staged received-len total)) :inbound))

(defthm fn-tcl-inbound-xfer-id-of-fn-tcl-make-inbound
  (equal (fn-tcl-inbound-xfer-id (fn-tcl-make-inbound xfer-id staged received-len total)) xfer-id))

(defthm fn-tcl-inbound-staged-of-fn-tcl-make-inbound
  (equal (fn-tcl-inbound-staged (fn-tcl-make-inbound xfer-id staged received-len total)) staged))

(defthm fn-tcl-inbound-received-len-of-fn-tcl-make-inbound
  (equal (fn-tcl-inbound-received-len (fn-tcl-make-inbound xfer-id staged received-len total)) received-len))

(defthm fn-tcl-inbound-total-of-fn-tcl-make-inbound
  (equal (fn-tcl-inbound-total (fn-tcl-make-inbound xfer-id staged received-len total)) total))

(defthm fn-tcl-inbound-shapep-forward-shape
  (implies (fn-tcl-inbound-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :inbound)))
  :rule-classes :forward-chaining)

(defthm fn-tcl-inbound-accessors-forward-consp
  (and (implies (fn-tcl-inbound-xfer-id x) (consp x))
       (implies (fn-tcl-inbound-staged x) (consp x))
       (implies (fn-tcl-inbound-received-len x) (consp x))
       (implies (fn-tcl-inbound-total x) (consp x)))
  :rule-classes ((:forward-chaining :corollary (implies (fn-tcl-inbound-xfer-id x) (consp x))
                                    :trigger-terms ((fn-tcl-inbound-xfer-id x)))
                 (:forward-chaining :corollary (implies (fn-tcl-inbound-staged x) (consp x))
                                    :trigger-terms ((fn-tcl-inbound-staged x)))
                 (:forward-chaining :corollary (implies (fn-tcl-inbound-received-len x) (consp x))
                                    :trigger-terms ((fn-tcl-inbound-received-len x)))
                 (:forward-chaining :corollary (implies (fn-tcl-inbound-total x) (consp x))
                                    :trigger-terms ((fn-tcl-inbound-total x)))))

; --- outbound: The one live outbound transfer: its ID, the node's reference, the not-yet-sent suffix of the octets, the total length, the carried sent length and the cumulative acknowledged length.

(defun fn-tcl-outbound-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 7) (equal (car x) :outbound)))

(defun fn-tcl-outbound-xfer-id (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-outbound-xfer-id)

(defun fn-tcl-outbound-ref (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-outbound-ref)

(defun fn-tcl-outbound-remaining (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr x)))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))
(verify-guards fn-tcl-outbound-remaining)

(defun fn-tcl-outbound-total (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr x))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))))
(verify-guards fn-tcl-outbound-total)

(defun fn-tcl-outbound-sent-len (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr (cdr x)))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))))
(verify-guards fn-tcl-outbound-sent-len)

(defun fn-tcl-outbound-acked-len (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr (cdr (cdr x))))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))))))
(verify-guards fn-tcl-outbound-acked-len)

(defun fn-tcl-make-outbound (xfer-id ref remaining total sent-len acked-len)
  (declare (xargs :guard t))
  (list :outbound xfer-id ref remaining total sent-len acked-len))

(defthm fn-tcl-outbound-shapep-of-fn-tcl-make-outbound
  (fn-tcl-outbound-shapep (fn-tcl-make-outbound xfer-id ref remaining total sent-len acked-len)))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-outbound
  (equal (fn-tcl-msg-kind (fn-tcl-make-outbound xfer-id ref remaining total sent-len acked-len)) :outbound))

(defthm fn-tcl-outbound-xfer-id-of-fn-tcl-make-outbound
  (equal (fn-tcl-outbound-xfer-id (fn-tcl-make-outbound xfer-id ref remaining total sent-len acked-len)) xfer-id))

(defthm fn-tcl-outbound-ref-of-fn-tcl-make-outbound
  (equal (fn-tcl-outbound-ref (fn-tcl-make-outbound xfer-id ref remaining total sent-len acked-len)) ref))

(defthm fn-tcl-outbound-remaining-of-fn-tcl-make-outbound
  (equal (fn-tcl-outbound-remaining (fn-tcl-make-outbound xfer-id ref remaining total sent-len acked-len)) remaining))

(defthm fn-tcl-outbound-total-of-fn-tcl-make-outbound
  (equal (fn-tcl-outbound-total (fn-tcl-make-outbound xfer-id ref remaining total sent-len acked-len)) total))

(defthm fn-tcl-outbound-sent-len-of-fn-tcl-make-outbound
  (equal (fn-tcl-outbound-sent-len (fn-tcl-make-outbound xfer-id ref remaining total sent-len acked-len)) sent-len))

(defthm fn-tcl-outbound-acked-len-of-fn-tcl-make-outbound
  (equal (fn-tcl-outbound-acked-len (fn-tcl-make-outbound xfer-id ref remaining total sent-len acked-len)) acked-len))

(defthm fn-tcl-outbound-shapep-forward-shape
  (implies (fn-tcl-outbound-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :outbound)))
  :rule-classes :forward-chaining)

(defthm fn-tcl-outbound-accessors-forward-consp
  (and (implies (fn-tcl-outbound-xfer-id x) (consp x))
       (implies (fn-tcl-outbound-ref x) (consp x))
       (implies (fn-tcl-outbound-remaining x) (consp x))
       (implies (fn-tcl-outbound-total x) (consp x))
       (implies (fn-tcl-outbound-sent-len x) (consp x))
       (implies (fn-tcl-outbound-acked-len x) (consp x)))
  :rule-classes ((:forward-chaining :corollary (implies (fn-tcl-outbound-xfer-id x) (consp x))
                                    :trigger-terms ((fn-tcl-outbound-xfer-id x)))
                 (:forward-chaining :corollary (implies (fn-tcl-outbound-ref x) (consp x))
                                    :trigger-terms ((fn-tcl-outbound-ref x)))
                 (:forward-chaining :corollary (implies (fn-tcl-outbound-remaining x) (consp x))
                                    :trigger-terms ((fn-tcl-outbound-remaining x)))
                 (:forward-chaining :corollary (implies (fn-tcl-outbound-total x) (consp x))
                                    :trigger-terms ((fn-tcl-outbound-total x)))
                 (:forward-chaining :corollary (implies (fn-tcl-outbound-sent-len x) (consp x))
                                    :trigger-terms ((fn-tcl-outbound-sent-len x)))
                 (:forward-chaining :corollary (implies (fn-tcl-outbound-acked-len x) (consp x))
                                    :trigger-terms ((fn-tcl-outbound-acked-len x)))))

; --- session: The session state.  role :active or :passive; phase one of :tcp-connected :contact :messaging :established :ending :closed; local the own params record; tls the section 4.3 Enable TLS conjunction once the peer Contact Header is seen, else nil; peer the peer's SESS_INIT params record once seen; negotiated the negotiation record once established; inbound and outbound the live transfers or nil; next-xfer-id the section 5.2.1 frontier; last-rx and last-tx monotonic milliseconds; term nil, :sent or :both.

(defun fn-tcl-session-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 13) (equal (car x) :session)))

(defun fn-tcl-session-role (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-session-role)

(defun fn-tcl-session-phase (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-session-phase)

(defun fn-tcl-session-local (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr x)))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))
(verify-guards fn-tcl-session-local)

(defun fn-tcl-session-tls (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr x))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))))
(verify-guards fn-tcl-session-tls)

(defun fn-tcl-session-peer (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr (cdr x)))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))))
(verify-guards fn-tcl-session-peer)

(defun fn-tcl-session-negotiated (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr (cdr (cdr x))))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))))))
(verify-guards fn-tcl-session-negotiated)

(defun fn-tcl-session-inbound (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr (cdr (cdr (cdr x)))))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))))))
(verify-guards fn-tcl-session-inbound)

(defun fn-tcl-session-outbound (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr x))))))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))))))))
(verify-guards fn-tcl-session-outbound)

(defun fn-tcl-session-next-xfer-id (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr x)))))))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))))))))
(verify-guards fn-tcl-session-next-xfer-id)

(defun fn-tcl-session-last-rx (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr x))))))))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))))))))))
(verify-guards fn-tcl-session-last-rx)

(defun fn-tcl-session-last-tx (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr x)))))))))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))))))))))
(verify-guards fn-tcl-session-last-tx)

(defun fn-tcl-session-term (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr x))))))))))))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))))))))))))
(verify-guards fn-tcl-session-term)

(defun fn-tcl-make-session (role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)
  (declare (xargs :guard t))
  (list :session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term))

(defthm fn-tcl-session-shapep-of-fn-tcl-make-session
  (fn-tcl-session-shapep (fn-tcl-make-session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-session
  (equal (fn-tcl-msg-kind (fn-tcl-make-session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)) :session))

(defthm fn-tcl-session-role-of-fn-tcl-make-session
  (equal (fn-tcl-session-role (fn-tcl-make-session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)) role))

(defthm fn-tcl-session-phase-of-fn-tcl-make-session
  (equal (fn-tcl-session-phase (fn-tcl-make-session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)) phase))

(defthm fn-tcl-session-local-of-fn-tcl-make-session
  (equal (fn-tcl-session-local (fn-tcl-make-session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)) local))

(defthm fn-tcl-session-tls-of-fn-tcl-make-session
  (equal (fn-tcl-session-tls (fn-tcl-make-session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)) tls))

(defthm fn-tcl-session-peer-of-fn-tcl-make-session
  (equal (fn-tcl-session-peer (fn-tcl-make-session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)) peer))

(defthm fn-tcl-session-negotiated-of-fn-tcl-make-session
  (equal (fn-tcl-session-negotiated (fn-tcl-make-session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)) negotiated))

(defthm fn-tcl-session-inbound-of-fn-tcl-make-session
  (equal (fn-tcl-session-inbound (fn-tcl-make-session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)) inbound))

(defthm fn-tcl-session-outbound-of-fn-tcl-make-session
  (equal (fn-tcl-session-outbound (fn-tcl-make-session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)) outbound))

(defthm fn-tcl-session-next-xfer-id-of-fn-tcl-make-session
  (equal (fn-tcl-session-next-xfer-id (fn-tcl-make-session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)) next-xfer-id))

(defthm fn-tcl-session-last-rx-of-fn-tcl-make-session
  (equal (fn-tcl-session-last-rx (fn-tcl-make-session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)) last-rx))

(defthm fn-tcl-session-last-tx-of-fn-tcl-make-session
  (equal (fn-tcl-session-last-tx (fn-tcl-make-session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)) last-tx))

(defthm fn-tcl-session-term-of-fn-tcl-make-session
  (equal (fn-tcl-session-term (fn-tcl-make-session role phase local tls peer negotiated inbound outbound next-xfer-id last-rx last-tx term)) term))

(defthm fn-tcl-session-shapep-forward-shape
  (implies (fn-tcl-session-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :session)))
  :rule-classes :forward-chaining)

(defthm fn-tcl-session-accessors-forward-consp
  (and (implies (fn-tcl-session-role x) (consp x))
       (implies (fn-tcl-session-phase x) (consp x))
       (implies (fn-tcl-session-local x) (consp x))
       (implies (fn-tcl-session-tls x) (consp x))
       (implies (fn-tcl-session-peer x) (consp x))
       (implies (fn-tcl-session-negotiated x) (consp x))
       (implies (fn-tcl-session-inbound x) (consp x))
       (implies (fn-tcl-session-outbound x) (consp x))
       (implies (fn-tcl-session-next-xfer-id x) (consp x))
       (implies (fn-tcl-session-last-rx x) (consp x))
       (implies (fn-tcl-session-last-tx x) (consp x))
       (implies (fn-tcl-session-term x) (consp x)))
  :rule-classes ((:forward-chaining :corollary (implies (fn-tcl-session-role x) (consp x))
                                    :trigger-terms ((fn-tcl-session-role x)))
                 (:forward-chaining :corollary (implies (fn-tcl-session-phase x) (consp x))
                                    :trigger-terms ((fn-tcl-session-phase x)))
                 (:forward-chaining :corollary (implies (fn-tcl-session-local x) (consp x))
                                    :trigger-terms ((fn-tcl-session-local x)))
                 (:forward-chaining :corollary (implies (fn-tcl-session-tls x) (consp x))
                                    :trigger-terms ((fn-tcl-session-tls x)))
                 (:forward-chaining :corollary (implies (fn-tcl-session-peer x) (consp x))
                                    :trigger-terms ((fn-tcl-session-peer x)))
                 (:forward-chaining :corollary (implies (fn-tcl-session-negotiated x) (consp x))
                                    :trigger-terms ((fn-tcl-session-negotiated x)))
                 (:forward-chaining :corollary (implies (fn-tcl-session-inbound x) (consp x))
                                    :trigger-terms ((fn-tcl-session-inbound x)))
                 (:forward-chaining :corollary (implies (fn-tcl-session-outbound x) (consp x))
                                    :trigger-terms ((fn-tcl-session-outbound x)))
                 (:forward-chaining :corollary (implies (fn-tcl-session-next-xfer-id x) (consp x))
                                    :trigger-terms ((fn-tcl-session-next-xfer-id x)))
                 (:forward-chaining :corollary (implies (fn-tcl-session-last-rx x) (consp x))
                                    :trigger-terms ((fn-tcl-session-last-rx x)))
                 (:forward-chaining :corollary (implies (fn-tcl-session-last-tx x) (consp x))
                                    :trigger-terms ((fn-tcl-session-last-tx x)))
                 (:forward-chaining :corollary (implies (fn-tcl-session-term x) (consp x))
                                    :trigger-terms ((fn-tcl-session-term x)))))

; --- result: What a transition returns: the next session, the events for the host in order, and the octets not consumed.

(defun fn-tcl-result-shapep (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 4) (equal (car x) :result)))

(defun fn-tcl-result-session (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-result-session)

(defun fn-tcl-result-events (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-result-events)

(defun fn-tcl-result-unconsumed (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr (cdr x)))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr (fn-cbor-ag-cdr x))))))
(verify-guards fn-tcl-result-unconsumed)

(defun fn-tcl-make-result (session events unconsumed)
  (declare (xargs :guard t))
  (list :result session events unconsumed))

(defthm fn-tcl-result-shapep-of-fn-tcl-make-result
  (fn-tcl-result-shapep (fn-tcl-make-result session events unconsumed)))

(defthm fn-tcl-msg-kind-of-fn-tcl-make-result
  (equal (fn-tcl-msg-kind (fn-tcl-make-result session events unconsumed)) :result))

(defthm fn-tcl-result-session-of-fn-tcl-make-result
  (equal (fn-tcl-result-session (fn-tcl-make-result session events unconsumed)) session))

(defthm fn-tcl-result-events-of-fn-tcl-make-result
  (equal (fn-tcl-result-events (fn-tcl-make-result session events unconsumed)) events))

(defthm fn-tcl-result-unconsumed-of-fn-tcl-make-result
  (equal (fn-tcl-result-unconsumed (fn-tcl-make-result session events unconsumed)) unconsumed))

(defthm fn-tcl-result-shapep-forward-shape
  (implies (fn-tcl-result-shapep x)
           (and (consp x) (true-listp x) (equal (fn-tcl-msg-kind x) :result)))
  :rule-classes :forward-chaining)

(defthm fn-tcl-result-accessors-forward-consp
  (and (implies (fn-tcl-result-session x) (consp x))
       (implies (fn-tcl-result-events x) (consp x))
       (implies (fn-tcl-result-unconsumed x) (consp x)))
  :rule-classes ((:forward-chaining :corollary (implies (fn-tcl-result-session x) (consp x))
                                    :trigger-terms ((fn-tcl-result-session x)))
                 (:forward-chaining :corollary (implies (fn-tcl-result-events x) (consp x))
                                    :trigger-terms ((fn-tcl-result-events x)))
                 (:forward-chaining :corollary (implies (fn-tcl-result-unconsumed x) (consp x))
                                    :trigger-terms ((fn-tcl-result-unconsumed x)))))

; --- parse: the decoder's outcome.  Three constructors, three distinct
; recognizers; (fn-tcl-parse-ok msg rest) carries the decoded record and the
; untouched suffix, (fn-tcl-parse-need) says the buffer holds no complete
; message, (fn-tcl-parse-error reason) names the fault.

(defun fn-tcl-parse-ok (msg rest)
  (declare (xargs :guard t))
  (list :ok msg rest))

(defun fn-tcl-parse-need ()
  (declare (xargs :guard t))
  (list :need))

(defun fn-tcl-parse-error (reason)
  (declare (xargs :guard t))
  (list :error reason))

(defun fn-tcl-parse-okp (x)
  (declare (xargs :guard t))
  (and (consp x) (equal (fn-cbor-ag-car x) :ok)))

(defun fn-tcl-parse-needp (x)
  (declare (xargs :guard t))
  (and (consp x) (equal (fn-cbor-ag-car x) :need)))

(defun fn-tcl-parse-errorp (x)
  (declare (xargs :guard t))
  (and (consp x) (equal (fn-cbor-ag-car x) :error)))

(defun fn-tcl-parse-msg (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-parse-msg)

(defun fn-tcl-parse-rest (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr (cdr x))) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr (fn-cbor-ag-cdr x)))))
(verify-guards fn-tcl-parse-rest)

(defun fn-tcl-parse-reason (x)
  (declare (xargs :guard t :verify-guards nil))
  (mbe :logic (car (cdr x)) :exec (fn-cbor-ag-car (fn-cbor-ag-cdr x))))
(verify-guards fn-tcl-parse-reason)

(defthm fn-tcl-parse-okp-of-fn-tcl-parse-ok
  (fn-tcl-parse-okp (fn-tcl-parse-ok msg rest)))
(defthm fn-tcl-parse-okp-of-fn-tcl-parse-need
  (not (fn-tcl-parse-okp (fn-tcl-parse-need))))
(defthm fn-tcl-parse-okp-of-fn-tcl-parse-error
  (not (fn-tcl-parse-okp (fn-tcl-parse-error reason))))
(defthm fn-tcl-parse-needp-of-fn-tcl-parse-need
  (fn-tcl-parse-needp (fn-tcl-parse-need)))
(defthm fn-tcl-parse-needp-of-fn-tcl-parse-ok
  (not (fn-tcl-parse-needp (fn-tcl-parse-ok msg rest))))
(defthm fn-tcl-parse-needp-of-fn-tcl-parse-error
  (not (fn-tcl-parse-needp (fn-tcl-parse-error reason))))
(defthm fn-tcl-parse-errorp-of-fn-tcl-parse-error
  (fn-tcl-parse-errorp (fn-tcl-parse-error reason)))
(defthm fn-tcl-parse-errorp-of-fn-tcl-parse-ok
  (not (fn-tcl-parse-errorp (fn-tcl-parse-ok msg rest))))
(defthm fn-tcl-parse-errorp-of-fn-tcl-parse-need
  (not (fn-tcl-parse-errorp (fn-tcl-parse-need))))
(defthm fn-tcl-parse-msg-of-fn-tcl-parse-ok
  (equal (fn-tcl-parse-msg (fn-tcl-parse-ok msg rest)) msg))
(defthm fn-tcl-parse-rest-of-fn-tcl-parse-ok
  (equal (fn-tcl-parse-rest (fn-tcl-parse-ok msg rest)) rest))
(defthm fn-tcl-parse-reason-of-fn-tcl-parse-error
  (equal (fn-tcl-parse-reason (fn-tcl-parse-error reason)) reason))
(defthm fn-tcl-parse-ok-is-injective
  (equal (equal (fn-tcl-parse-ok msg rest) (fn-tcl-parse-ok msg2 rest2))
         (and (equal msg msg2) (equal rest rest2))))
(defthm fn-tcl-parse-error-is-injective
  (equal (equal (fn-tcl-parse-error reason) (fn-tcl-parse-error reason2))
         (equal reason reason2)))
(defthm fn-tcl-parse-okp-forward-consp
  (implies (fn-tcl-parse-okp x) (consp x))
  :rule-classes :forward-chaining)

; Withdraw every record definition: below this point, and in every includer,
; a record is its constructor and accessors.
(in-theory (disable (:d fn-tcl-msg-kind)
                    (:d fn-tcl-contact-shapep)
                    (:d fn-tcl-make-contact)
                    (:d fn-tcl-contact-version)
                    (:d fn-tcl-contact-flags)
                    (:d fn-tcl-sess-init-shapep)
                    (:d fn-tcl-make-sess-init)
                    (:d fn-tcl-sess-init-keepalive)
                    (:d fn-tcl-sess-init-segment-mru)
                    (:d fn-tcl-sess-init-transfer-mru)
                    (:d fn-tcl-sess-init-node-id)
                    (:d fn-tcl-sess-init-ext)
                    (:d fn-tcl-xfer-segment-shapep)
                    (:d fn-tcl-make-xfer-segment)
                    (:d fn-tcl-xfer-segment-flags)
                    (:d fn-tcl-xfer-segment-xfer-id)
                    (:d fn-tcl-xfer-segment-ext)
                    (:d fn-tcl-xfer-segment-data)
                    (:d fn-tcl-xfer-ack-shapep)
                    (:d fn-tcl-make-xfer-ack)
                    (:d fn-tcl-xfer-ack-flags)
                    (:d fn-tcl-xfer-ack-xfer-id)
                    (:d fn-tcl-xfer-ack-acked-len)
                    (:d fn-tcl-xfer-refuse-shapep)
                    (:d fn-tcl-make-xfer-refuse)
                    (:d fn-tcl-xfer-refuse-reason)
                    (:d fn-tcl-xfer-refuse-xfer-id)
                    (:d fn-tcl-keepalive-shapep)
                    (:d fn-tcl-make-keepalive)
                    (:d fn-tcl-sess-term-shapep)
                    (:d fn-tcl-make-sess-term)
                    (:d fn-tcl-sess-term-flags)
                    (:d fn-tcl-sess-term-reason)
                    (:d fn-tcl-msg-reject-shapep)
                    (:d fn-tcl-make-msg-reject)
                    (:d fn-tcl-msg-reject-reason)
                    (:d fn-tcl-msg-reject-header)
                    (:d fn-tcl-item-shapep)
                    (:d fn-tcl-make-item)
                    (:d fn-tcl-item-flags)
                    (:d fn-tcl-item-type)
                    (:d fn-tcl-item-value)
                    (:d fn-tcl-params-shapep)
                    (:d fn-tcl-make-params)
                    (:d fn-tcl-params-keepalive)
                    (:d fn-tcl-params-segment-mru)
                    (:d fn-tcl-params-transfer-mru)
                    (:d fn-tcl-params-node-id)
                    (:d fn-tcl-params-can-tls)
                    (:d fn-tcl-params-expected-peer)
                    (:d fn-tcl-negotiated-shapep)
                    (:d fn-tcl-make-negotiated)
                    (:d fn-tcl-negotiated-keepalive)
                    (:d fn-tcl-negotiated-segment-mtu)
                    (:d fn-tcl-negotiated-transfer-mtu)
                    (:d fn-tcl-negotiated-tls)
                    (:d fn-tcl-negotiated-peer-node-id)
                    (:d fn-tcl-inbound-shapep)
                    (:d fn-tcl-make-inbound)
                    (:d fn-tcl-inbound-xfer-id)
                    (:d fn-tcl-inbound-staged)
                    (:d fn-tcl-inbound-received-len)
                    (:d fn-tcl-inbound-total)
                    (:d fn-tcl-outbound-shapep)
                    (:d fn-tcl-make-outbound)
                    (:d fn-tcl-outbound-xfer-id)
                    (:d fn-tcl-outbound-ref)
                    (:d fn-tcl-outbound-remaining)
                    (:d fn-tcl-outbound-total)
                    (:d fn-tcl-outbound-sent-len)
                    (:d fn-tcl-outbound-acked-len)
                    (:d fn-tcl-session-shapep)
                    (:d fn-tcl-make-session)
                    (:d fn-tcl-session-role)
                    (:d fn-tcl-session-phase)
                    (:d fn-tcl-session-local)
                    (:d fn-tcl-session-tls)
                    (:d fn-tcl-session-peer)
                    (:d fn-tcl-session-negotiated)
                    (:d fn-tcl-session-inbound)
                    (:d fn-tcl-session-outbound)
                    (:d fn-tcl-session-next-xfer-id)
                    (:d fn-tcl-session-last-rx)
                    (:d fn-tcl-session-last-tx)
                    (:d fn-tcl-session-term)
                    (:d fn-tcl-result-shapep)
                    (:d fn-tcl-make-result)
                    (:d fn-tcl-result-session)
                    (:d fn-tcl-result-events)
                    (:d fn-tcl-result-unconsumed)
                    (:d fn-tcl-parse-ok)
                    (:d fn-tcl-parse-need)
                    (:d fn-tcl-parse-error)
                    (:d fn-tcl-parse-okp)
                    (:d fn-tcl-parse-needp)
                    (:d fn-tcl-parse-errorp)
                    (:d fn-tcl-parse-msg)
                    (:d fn-tcl-parse-rest)
                    (:d fn-tcl-parse-reason)))
