; Bounded canonical Store payload for experimental topic anchor/admission.
; Distinct magic avoids colliding with fn-e and consumer fnce envelopes.
(in-package "ACL2")
(include-book "topic-history-local-admin")

(defconst *fn-th-topic-magic* '(102 110 116 111)) ; "fnto"
(defconst *fn-th-topic-version* 1)
(defconst *fn-th-topic-anchor-v2-version* 2)
(defconst *fn-th-topic-max-octets* 1024)
(defconst *fn-th-topic-max-items* 24)

(defun fn-th-auth-ref-p (ref)
  (declare (xargs :guard t))
  (and (true-listp ref) (equal (len ref) 6)
       (fn-record-uint32p (fn-th-at 0 ref))
       (fn-record-uint32p (fn-th-at 1 ref))
       (fn-th-source-id-p (fn-th-at 2 ref))
       (equal (fn-th-at 3 ref) (fn-th-at 0 ref))
       (fn-record-uint32p (fn-th-at 4 ref))
       (equal (fn-th-at 5 ref) *fn-hsig-profile-tag*)))

(defun fn-th-topic-eventp (event)
  (declare (xargs :guard t))
  (and (true-listp event)
       (or (fn-th-local-admin-eventp event)
           (and (or (equal (len event) 8)
                    (equal (len event) 9))
                (equal (fn-th-at 0 event) :topic-anchor)
                (fn-th-source-id-p (fn-th-at 4 event))
                (fn-th-auth-ref-p (fn-th-at 5 event))
                (equal (fn-th-at 4 event)
                       (fn-th-at 2 (fn-th-at 5 event)))
                (posp (fn-th-at 6 event))
                (<= (fn-th-at 6 event) *fn-th-max-report-quota*)
                (fn-th-exact-octets-p (fn-th-at 7 event) 32)
                (or (equal (len event) 8)
                    (fn-record-uint32p (fn-th-at 8 event))))
           (and (equal (len event) 9)
                (equal (fn-th-at 0 event) :topic-admit)
                (fn-th-source-id-p (fn-th-at 4 event))
                (fn-th-source-id-p (fn-th-at 5 event))
                (fn-th-source-id-p (fn-th-at 6 event))
                (fn-th-auth-ref-p (fn-th-at 7 event))
                (equal (fn-th-at 5 event)
                       (fn-th-at 2 (fn-th-at 7 event)))
                (<= (len (fn-th-at 8 event)) *fn-th-max-parents*)
                (fn-th-parents-p (fn-th-at 8 event) nil)))
       (fn-record-uint32p (fn-th-at 1 event))
       (fn-record-uint32p (fn-th-at 2 event))
       (fn-record-uint32p (fn-th-at 3 event))
       (or (fn-th-local-admin-eventp event)
           (< (fn-th-at 0 (if (equal (fn-th-at 0 event) :topic-anchor)
                                (fn-th-at 5 event) (fn-th-at 7 event)))
              (fn-th-at 1 event)))))

(defun fn-th-topic-v1-anchorp (event)
  (declare (xargs :guard t))
  (and (eq (fn-th-at 0 event) :topic-anchor)
       (equal (len event) 8)))

(defun fn-th-topic-auth-items (ref)
  (declare (xargs :guard t))
  (list (cons :uint (fn-th-at 0 ref))
        (cons :uint (fn-th-at 1 ref))
        (cons :bytes (fn-th-at 2 ref))
        (cons :uint (fn-th-at 3 ref))
        (cons :uint (fn-th-at 4 ref))
        (cons :bytes (fn-th-at 5 ref))))
(defun fn-th-topic-event-items (event)
  (declare (xargs :guard t))
  (append
   (list (cons :bytes *fn-th-topic-magic*)
         (cons :uint (if (and (eq (fn-th-at 0 event) :topic-anchor)
                              (equal (len event) 9))
                         *fn-th-topic-anchor-v2-version*
                       *fn-th-topic-version*))
         (cons :uint (case (fn-th-at 0 event)
                       (:topic-anchor 0) (:topic-admit 1)
                       (otherwise 2)))
         (cons :uint (fn-th-at 1 event))
         (cons :uint (fn-th-at 2 event))
         (cons :uint (fn-th-at 3 event)))
   (cond
    ((equal (fn-th-at 0 event) :topic-admin-install)
     (list (cons :uint (fn-th-at 4 event))
           (cons :bytes (fn-th-at 5 event))))
    ((equal (fn-th-at 0 event) :topic-anchor)
       (append
        (list (cons :bytes (fn-th-at 4 event)))
        (fn-th-topic-auth-items (fn-th-at 5 event))
        (append
         (list (cons :uint (fn-th-at 6 event))
               (cons :bytes (fn-th-at 7 event)))
         (if (equal (len event) 9)
             (list (cons :uint (fn-th-at 8 event))) nil))))
    (t (append
      (list (cons :bytes (fn-th-at 4 event))
            (cons :bytes (fn-th-at 5 event))
            (cons :bytes (fn-th-at 6 event)))
      (fn-th-topic-auth-items (fn-th-at 7 event))
      (list (cons :uint (len (fn-th-at 8 event))))
      (fn-th-parent-items (fn-th-at 8 event)))))))

(defun fn-th-topic-event-encode (event)
  (declare (xargs :guard t))
  (if (not (fn-th-topic-eventp event)) nil
    (let ((octets (fn-stxe-encode-items (fn-th-topic-event-items event))))
      (if (fn-cbor-at-mostp octets *fn-th-topic-max-octets*) octets nil))))

(defun fn-th-topic-auth-from-items (start items)
  (declare (xargs :guard (natp start)))
  (list (fn-cbor-ag-cdr (fn-th-at start items))
        (fn-cbor-ag-cdr (fn-th-at (+ start 1) items))
        (fn-cbor-ag-cdr (fn-th-at (+ start 2) items))
        (fn-cbor-ag-cdr (fn-th-at (+ start 3) items))
        (fn-cbor-ag-cdr (fn-th-at (+ start 4) items))
        (fn-cbor-ag-cdr (fn-th-at (+ start 5) items))))
(defun fn-th-topic-event-from-items (items)
  (declare (xargs :guard t))
  (if (not (and (true-listp items)
                (equal (fn-th-at 0 items)
                       (cons :bytes *fn-th-topic-magic*))
                (member-equal (fn-th-at 1 items)
                              (list (cons :uint *fn-th-topic-version*)
                                    (cons :uint
                                          *fn-th-topic-anchor-v2-version*)))))
      (fn-stmt-error :version)
    (let ((kind (fn-cbor-ag-cdr (fn-th-at 2 items)))
          (version (fn-cbor-ag-cdr (fn-th-at 1 items))))
      (cond
       ((and (equal kind 0)
             (or (and (equal version *fn-th-topic-version*)
                      (equal (len items) 15))
                 (and (equal version *fn-th-topic-anchor-v2-version*)
                      (equal (len items) 16))))
        (let ((event
               (append
                (list :topic-anchor
                      (fn-cbor-ag-cdr (fn-th-at 3 items))
                      (fn-cbor-ag-cdr (fn-th-at 4 items))
                      (fn-cbor-ag-cdr (fn-th-at 5 items))
                      (fn-cbor-ag-cdr (fn-th-at 6 items))
                      (fn-th-topic-auth-from-items 7 items)
                      (fn-cbor-ag-cdr (fn-th-at 13 items))
                      (fn-cbor-ag-cdr (fn-th-at 14 items)))
                (if (equal version *fn-th-topic-anchor-v2-version*)
                    (list (fn-cbor-ag-cdr (fn-th-at 15 items))) nil))))
          (if (fn-th-topic-eventp event) (fn-stmt-ok event)
            (fn-stmt-error :shape))))
       ((and (equal version *fn-th-topic-version*)
             (equal kind 1) (<= 16 (len items))
             (<= (len items) *fn-th-topic-max-items*))
        (let* ((count (fn-cbor-ag-cdr (fn-th-at 15 items)))
               (read (fn-th-read-parents
                      (if (and (natp count) (<= count *fn-th-max-parents*))
                          count 0)
                      (nthcdr 16 items)))
               (event
                (list :topic-admit
                      (fn-cbor-ag-cdr (fn-th-at 3 items))
                      (fn-cbor-ag-cdr (fn-th-at 4 items))
                      (fn-cbor-ag-cdr (fn-th-at 5 items))
                      (fn-cbor-ag-cdr (fn-th-at 6 items))
                      (fn-cbor-ag-cdr (fn-th-at 7 items))
                      (fn-cbor-ag-cdr (fn-th-at 8 items))
                      (fn-th-topic-auth-from-items 9 items)
                      (fn-stmt-value read))))
          (if (and (natp count) (<= count *fn-th-max-parents*)
                   (fn-stmt-okp read) (null (fn-stmt-rest read))
                   (fn-th-topic-eventp event))
              (fn-stmt-ok event) (fn-stmt-error :shape))))
       ((and (equal version *fn-th-topic-version*)
             (equal kind 2) (equal (len items) 8))
        (let ((event
               (list :topic-admin-install
                     (fn-cbor-ag-cdr (fn-th-at 3 items))
                     (fn-cbor-ag-cdr (fn-th-at 4 items))
                     (fn-cbor-ag-cdr (fn-th-at 5 items))
                     (fn-cbor-ag-cdr (fn-th-at 6 items))
                     (fn-cbor-ag-cdr (fn-th-at 7 items)))))
          (if (fn-th-topic-eventp event) (fn-stmt-ok event)
            (fn-stmt-error :shape))))
       (t (fn-stmt-error :kind))))))

(defun fn-th-topic-event-decode-exact (octets)
  (declare (xargs :guard t))
  (if (not (fn-cbor-at-mostp octets *fn-th-topic-max-octets*))
      (fn-stmt-error :octet-limit)
    (let ((decoded (fn-stmt-decode-items *fn-th-topic-max-items* octets)))
      (if (not (fn-stmt-okp decoded)) (fn-stmt-error :codec)
        (let ((parsed (fn-th-topic-event-from-items
                       (fn-stmt-value decoded))))
          (if (and (fn-stmt-okp parsed)
                   (equal (fn-th-topic-event-encode (fn-stmt-value parsed))
                          octets))
              parsed (fn-stmt-error :canonical)))))))

(defthm fn-th-topic-decode-refuses-oversize
  (implies (not (fn-cbor-at-mostp octets *fn-th-topic-max-octets*))
           (equal (fn-th-topic-event-decode-exact octets)
                  (fn-stmt-error :octet-limit)))
  :hints (("Goal" :in-theory (enable fn-th-topic-event-decode-exact))))
(defthm fn-th-topic-decode-accepted-is-canonical
  (implies (fn-stmt-okp (fn-th-topic-event-decode-exact octets))
           (equal (fn-th-topic-event-encode
                   (fn-stmt-value (fn-th-topic-event-decode-exact octets)))
                  octets))
  :hints (("Goal" :in-theory
           (e/d (fn-th-topic-event-decode-exact)
                (fn-th-topic-event-encode fn-th-topic-event-from-items)))))
(defthm fn-th-topic-encode-emits-bounded-by-definition
  (implies (fn-th-topic-event-encode event)
           (fn-cbor-at-mostp (fn-th-topic-event-encode event)
                             *fn-th-topic-max-octets*))
  :hints (("Goal" :in-theory (enable fn-th-topic-event-encode))))
