; Bounded experimental FN-Topic metadata in exact authored source octets.
; This book projects a candidate only.  It does not install topic authority.
(in-package "ACL2")
(include-book "hybrid-store")
(include-book "statement")
(include-book "stx-carrier")

(defconst *fn-th-name* '(102 110 45 116 111 112 105 99))
(defconst *fn-th-max-binary* 1536)
(defconst *fn-th-max-field* 2048)
(defconst *fn-th-max-items* 39)
(defconst *fn-th-max-authors* 16)
(defconst *fn-th-max-parents* 8)

(defun fn-th-at (n xs)
  (declare (xargs :guard (natp n) :measure (nfix n)))
  (if (consp xs)
      (if (zp n) (car xs) (fn-th-at (1- n) (cdr xs)))
    nil))
(defun fn-th-exact-octets-p (xs n)
  (declare (xargs :guard t))
  (and (fn-cbor-octet-listp xs) (equal (len xs) n)))
(defun fn-th-source-id-p (xs)
  (declare (xargs :guard t))
  (and (fn-id-subjectp xs) (fn-th-exact-octets-p xs 48)))
(defun fn-th-author-p (x)
  (declare (xargs :guard t))
  (and (true-listp x) (equal (len x) 2)
       (fn-th-exact-octets-p (fn-th-at 0 x) 32)
       (fn-th-source-id-p (fn-th-at 1 x))))
(defun fn-th-octets-less-p (a b)
  (declare (xargs :guard t))
  (if (and (consp a) (consp b))
      (if (equal (fn-th-at 0 a) (fn-th-at 0 b))
          (fn-th-octets-less-p (cdr a) (cdr b))
        (< (nfix (fn-th-at 0 a)) (nfix (fn-th-at 0 b))))
    (and (not (consp a)) (consp b))))
(defun fn-th-author-less-p (a b)
  (declare (xargs :guard t))
  (if (equal (fn-cbor-ag-car a) (fn-cbor-ag-car b))
      (fn-th-octets-less-p (fn-cbor-ag-car (fn-cbor-ag-cdr a))
                           (fn-cbor-ag-car (fn-cbor-ag-cdr b)))
    (fn-th-octets-less-p (fn-cbor-ag-car a) (fn-cbor-ag-car b))))
(defun fn-th-authors-p (xs previous)
  (declare (xargs :guard t))
  (if (consp xs)
      (and (fn-th-author-p (car xs))
           (or (null previous) (fn-th-author-less-p previous (car xs)))
           (fn-th-authors-p (cdr xs) (car xs)))
    (null xs)))
(defun fn-th-parents-p (xs previous)
  (declare (xargs :guard t))
  (if (consp xs)
      (and (fn-th-source-id-p (car xs))
           (or (null previous) (fn-th-octets-less-p previous (car xs)))
           (fn-th-parents-p (cdr xs) (car xs)))
    (null xs)))
(defun fn-th-value-p (x)
  (declare (xargs :guard t))
  (and (true-listp x)
       (case (fn-th-at 0 x)
         (:root (and (equal (len x) 6)
                     (fn-th-exact-octets-p (fn-th-at 1 x) 32)
                     (fn-th-exact-octets-p (fn-th-at 2 x) 32)
                     (fn-th-source-id-p (fn-th-at 3 x))
                     (fn-cbor-octet-listp (fn-th-at 4 x))
                     (consp (fn-th-at 4 x)) (<= (len (fn-th-at 4 x)) 64)
                     (<= (len (fn-th-at 5 x)) *fn-th-max-authors*)
                     (fn-th-authors-p (fn-th-at 5 x) nil)))
         (:control (and (equal (len x) 4)
                        (fn-th-source-id-p (fn-th-at 1 x))
                        (fn-th-source-id-p (fn-th-at 2 x))
                        (<= (len (fn-th-at 3 x)) *fn-th-max-authors*)
                        (fn-th-authors-p (fn-th-at 3 x) nil)))
         (:report (and (equal (len x) 4)
                       (fn-th-source-id-p (fn-th-at 1 x))
                       (fn-th-source-id-p (fn-th-at 2 x))
                       (<= (len (fn-th-at 3 x)) *fn-th-max-parents*)
                       (fn-th-parents-p (fn-th-at 3 x) nil)))
         (otherwise nil))))
(defun fn-th-author-items (authors)
  (declare (xargs :guard t))
  (if (consp authors)
      (cons (cons :bytes (fn-th-at 0 (fn-th-at 0 authors)))
            (cons (cons :bytes (fn-th-at 1 (fn-th-at 0 authors)))
                  (fn-th-author-items (cdr authors))))
    nil))
(defun fn-th-parent-items (parents)
  (declare (xargs :guard t))
  (if (consp parents)
      (cons (cons :bytes (car parents)) (fn-th-parent-items (cdr parents)))
    nil))
(defun fn-th-items (x)
  (declare (xargs :guard t))
  (case (fn-th-at 0 x)
    (:root (append (list (cons :uint 1) (cons :uint 0)
                         (cons :bytes (fn-th-at 1 x)) (cons :bytes (fn-th-at 2 x))
                         (cons :bytes (fn-th-at 3 x)) (cons :bytes (fn-th-at 4 x))
                         (cons :uint (len (fn-th-at 5 x))))
                   (fn-th-author-items (fn-th-at 5 x))))
    (:control (append (list (cons :uint 1) (cons :uint 1)
                            (cons :bytes (fn-th-at 1 x)) (cons :bytes (fn-th-at 2 x))
                            (cons :uint (len (fn-th-at 3 x))))
                      (fn-th-author-items (fn-th-at 3 x))))
    (:report (append (list (cons :uint 1) (cons :uint 2)
                           (cons :bytes (fn-th-at 1 x)) (cons :bytes (fn-th-at 2 x))
                           (cons :uint (len (fn-th-at 3 x))))
                     (fn-th-parent-items (fn-th-at 3 x))))
    (otherwise nil)))
(local (defthm fn-th-author-items-are-items
  (implies (fn-th-authors-p authors previous)
           (fn-stmt-item-listp (fn-th-author-items authors)))
  :hints (("Goal" :induct (fn-th-authors-p authors previous)
           :in-theory (enable fn-stmt-item-listp fn-cbor-valuep
                              fn-cbor-valuep-bounded)))))
(local (defthm fn-th-parent-items-are-items
  (implies (fn-th-parents-p parents previous)
           (fn-stmt-item-listp (fn-th-parent-items parents)))
  :hints (("Goal" :induct (fn-th-parents-p parents previous)
           :in-theory (enable fn-stmt-item-listp fn-cbor-valuep
                              fn-cbor-valuep-bounded)))))
(defthm fn-th-items-when-value-p
  (implies (fn-th-value-p x) (fn-stmt-item-listp (fn-th-items x)))
  :hints (("Goal" :in-theory
           (e/d (fn-th-items fn-th-value-p fn-stmt-item-listp
                            fn-cbor-valuep fn-cbor-valuep-bounded)
                (fn-th-author-items fn-th-parent-items
                 fn-th-authors-p fn-th-parents-p)))))
(defun fn-th-encode (x)
  (declare (xargs :guard t
                  :guard-hints (("Goal" :in-theory (disable fn-th-items)))))
  (if (not (fn-th-value-p x)) nil
    (let ((octets (fn-stmt-encode-items (fn-th-items x))))
      (if (fn-cbor-at-mostp octets *fn-th-max-binary*) octets nil))))

(defun fn-th-read-authors (n items)
  (declare (xargs :guard (natp n) :measure (nfix n)))
  (if (zp n) (fn-stmt-ok2 nil items)
    (if (not (and (consp items) (consp (cdr items))
                  (fn-stmt-bytes-item-p (fn-th-at 0 items))
                  (fn-stmt-bytes-item-p (fn-th-at 1 items))))
        (fn-stmt-error :author-item)
      (let ((tail (fn-th-read-authors (1- n) (cddr items))))
        (if (fn-stmt-okp tail)
            (fn-stmt-ok2
             (cons (list (fn-cbor-ag-cdr (fn-th-at 0 items)) (fn-cbor-ag-cdr (fn-th-at 1 items)))
                   (fn-stmt-value tail))
             (fn-stmt-rest tail))
          tail)))))
(defun fn-th-read-parents (n items)
  (declare (xargs :guard (natp n) :measure (nfix n)))
  (if (zp n) (fn-stmt-ok2 nil items)
    (if (not (and (consp items) (fn-stmt-bytes-item-p (fn-th-at 0 items))))
        (fn-stmt-error :parent-item)
      (let ((tail (fn-th-read-parents (1- n) (cdr items))))
        (if (fn-stmt-okp tail)
            (fn-stmt-ok2 (cons (fn-cbor-ag-cdr (fn-th-at 0 items)) (fn-stmt-value tail))
                         (fn-stmt-rest tail))
          tail)))))
(defun fn-th-items-value (items)
  (declare (xargs :guard t
                  :guard-hints (("Goal" :in-theory
                                 (enable fn-stmt-uint-item-p
                                         fn-record-uint32p)))))
  (if (not (and (true-listp items) (consp items) (consp (cdr items))
                (equal (fn-th-at 0 items) (cons :uint 1))
                (fn-stmt-uint-item-p (fn-th-at 1 items))))
      (fn-stmt-error :version)
    (let* ((kind (fn-cbor-ag-cdr (fn-th-at 1 items)))
           (prefix (if (equal kind 0) 7 5)))
      (if (not (and (or (equal kind 0) (equal kind 1) (equal kind 2))
                    (<= prefix (len items))
                    (fn-stmt-uint-item-p (fn-th-at (1- prefix) items))))
          (fn-stmt-error :kind)
        (let* ((count (fn-cbor-ag-cdr (fn-th-at (1- prefix) items)))
               (limit (if (equal kind 2) *fn-th-max-parents* *fn-th-max-authors*))
               (tail (nthcdr prefix items))
               (read (if (equal kind 2)
                         (fn-th-read-parents (if (<= count limit) count 0) tail)
                       (fn-th-read-authors (if (<= count limit) count 0) tail)))
               (x (case kind
                    (0 (list :root (fn-cbor-ag-cdr (fn-th-at 2 items)) (fn-cbor-ag-cdr (fn-th-at 3 items))
                             (fn-cbor-ag-cdr (fn-th-at 4 items)) (fn-cbor-ag-cdr (fn-th-at 5 items))
                             (fn-stmt-value read)))
                    (1 (list :control (fn-cbor-ag-cdr (fn-th-at 2 items)) (fn-cbor-ag-cdr (fn-th-at 3 items))
                             (fn-stmt-value read)))
                    (otherwise (list :report (fn-cbor-ag-cdr (fn-th-at 2 items))
                                     (fn-cbor-ag-cdr (fn-th-at 3 items)) (fn-stmt-value read))))))
          (if (and (<= count limit) (fn-stmt-okp read)
                   (null (fn-stmt-rest read))
                   (fn-th-value-p x))
              (fn-stmt-ok x)
            (fn-stmt-error :shape)))))))
(defun fn-th-decode (octets)
  (declare (xargs :guard t))
  (if (not (fn-cbor-at-mostp octets *fn-th-max-binary*))
      (fn-stmt-error :binary-limit)
    (let ((decoded (fn-stmt-decode-items *fn-th-max-items* octets)))
      (if (not (fn-stmt-okp decoded)) (fn-stmt-error :codec)
        (let ((parsed (fn-th-items-value (fn-stmt-value decoded))))
          (if (and (fn-stmt-okp parsed)
                   (equal (fn-th-encode (fn-stmt-value parsed)) octets))
              parsed (fn-stmt-error :canonical)))))))
(defun fn-th-field-encode (x)
  (declare (xargs :guard t))
  (let ((binary (fn-th-encode x)))
    (if (not binary) nil
      (let ((b64 (fn-stx-b64-encode binary)))
        (if (fn-cbor-at-mostp b64 2045)
            (append '(118 49 32) b64) nil)))))
(defun fn-th-field-decode (value)
  (declare (xargs :guard t))
  (if (not (fn-cbor-at-mostp value *fn-th-max-field*))
      (fn-stmt-error :field-limit)
    (if (not (and (equal (fn-th-at 0 value) 118)
                  (equal (fn-th-at 1 value) 49)
                  (equal (fn-th-at 2 value) 32)))
        (fn-stmt-error :field-version)
      (let ((binary (fn-stx-b64-decode-exact (fn-hc-drop 3 value))))
        (if (not (fn-stx-okp binary)) (fn-stmt-error :base64)
          (fn-th-decode (fn-stx-val binary)))))))
(defun fn-th-project-fields (fields)
  (declare (xargs :guard t))
  (let ((count (fn-hc-count-name *fn-th-name* fields)))
    (if (equal count 0) (fn-stmt-error :missing)
      (if (not (equal count 1)) (fn-stmt-error :duplicate)
        (let ((field (fn-hc-find-name *fn-th-name* fields)))
          (if (not (true-listp field)) (fn-stmt-error :invalid)
            (let ((value (fn-article-field-unfolded-value field)))
              (if (not (equal (fn-th-at 0 value) 32))
                  (fn-stmt-error :field-prefix)
                (fn-th-field-decode (fn-cbor-ag-cdr value))))))))))
(defun fn-th-project-source (source)
  (declare (xargs :guard t))
  (let ((parsed (fn-article-parse source)))
    (if (not (fn-article-result-okp parsed)) (fn-stmt-error :article)
      (let ((article (fn-article-result-article parsed)))
        (if (not (fn-article-syntax-p article)) (fn-stmt-error :article)
          (fn-th-project-fields (fn-article-fields article)))))))

(defun fn-th-host-inspect-source (source)
  (declare (xargs :guard t))
  (fn-th-project-source source))

(defthm fn-th-encode-emits-bounded-by-definition
  (implies (fn-th-encode x)
           (fn-cbor-at-mostp (fn-th-encode x) *fn-th-max-binary*))
  :hints (("Goal" :in-theory (enable fn-th-encode))))
(defthm fn-th-decode-refuses-oversize-by-definition
  (implies (not (fn-cbor-at-mostp octets *fn-th-max-binary*))
           (equal (fn-th-decode octets) (fn-stmt-error :binary-limit)))
  :hints (("Goal" :in-theory
           (e/d (fn-th-decode)
                (fn-th-encode fn-th-items-value fn-th-value-p fn-th-items)))))
(defthm fn-th-decode-accepted-is-canonical
  (implies (fn-stmt-okp (fn-th-decode octets))
           (equal (fn-th-encode (fn-stmt-value (fn-th-decode octets)))
                  octets))
  :hints (("Goal" :in-theory
           (e/d (fn-th-decode)
                (fn-th-encode fn-th-items-value fn-th-value-p fn-th-items)))))
