; Authored POST body windows over the retained HTTP request, PRF-1293.
; Program execution boundary: tests establish byte agreement, not refinement.
(in-package "ACL2")
(include-book "web-session-keystones")

; HEAD REST, encoded offset/end, BOL, pending CR, pending fragment, phase.
(defun fn-wps-cursor (head bs be)
  (declare (xargs :mode :program))
  (list head bs be t nil nil :head))

(defun fn-wps-next (cursor fn-web-in)
  (declare (xargs :mode :program :stobjs fn-web-in))
  (let ((head (nth 0 cursor)) (i (nth 1 cursor)) (e (nth 2 cursor))
        (bol (nth 3 cursor)) (pcr (nth 4 cursor)) (pending (nth 5 cursor))
        (phase (nth 6 cursor)))
    (cond
     ((consp pending)
      (mv (car pending) (update-nth 5 (cdr pending) cursor) nil))
     ((equal phase :head)
      (if (consp head)
          (mv (car head) (update-nth 0 (cdr head) cursor) nil)
        (mv nil (update-nth 6 :body cursor) nil)))
     ((equal phase :body)
      (if (>= i e)
          (mv nil (update-nth 5 (append (if (or pcr (not bol)) '(13 10) nil) '(46 13 10))
                   (update-nth 6 :tail cursor)) nil)
        (let* ((d (fn-wss-decode-at i e fn-web-in)) (o (car d)))
          (if (and pcr (not (equal o 10)))
              ; Flush the pending CR without consuming this decoded octet.
              (mv nil (update-nth 5 '(13 10)
                       (update-nth 3 t (update-nth 4 nil cursor))) nil)
            (let* ((b (if pcr t bol))
                   (bytes (if pcr '(13 10) (fn-wss-step-octets o b))))
              (mv nil (list head (cdr d) e (fn-wss-step-bol o b)
                            (fn-wss-step-pcr o) bytes phase) nil))))))
     (t (mv nil cursor t)))))

(defun fn-wps-window (fuel cursor acc fn-web-in)
  ; One transition per work unit; zero-output CR/phase transitions also pay.
  ; At most FUEL octets and one <=5-byte fragment, including quantum one.
  (declare (xargs :mode :program :stobjs fn-web-in))
  (if (zp fuel) (mv (reverse acc) cursor nil)
    (mv-let (o next done) (fn-wps-next cursor fn-web-in)
      (if done (mv (reverse acc) next t)
        (fn-wps-window (1- fuel) next (if o (cons o acc) acc) fn-web-in)))))

(defun fn-wps-private-begin (config action fn-web-in fn-web-out)
  (declare (xargs :mode :program :stobjs (fn-web-in fn-web-out)))
  (let* ((row (nth 1 action)) (session (nth 2 action)) (ctx (nth 3 action))
         (request (fn-wss-c-request ctx)))
    (if (and (fn-web-private-begin-p action) (equal (fn-web-row-name row) :post)
             session (fn-wss-same-site request)
             (equal (fn-wss-form (fn-wrq-oct "csrf") ctx fn-web-in) (fn-wss-s-csrf session)))
        (let* ((group (fn-wss-form (fn-wrq-oct "g") ctx fn-web-in))
               (subject (fn-wss-form (fn-wrq-oct "subject") ctx fn-web-in))
               (bs (fn-wss-c-bs ctx)) (be (fn-wss-c-be ctx))
               (span (and (<= bs be) (<= be (fn-octets-len fn-web-in))
                          (fn-wrq-body-span (fn-wrq-oct "body") bs be fn-web-in))))
          (if (and (fn-wss-groupp group) (consp subject) (consp span)
                   (natp (car span)) (natp (cdr span)) (< (car span) (cdr span)))
              (let* ((head (fn-wss-post-head (fn-wss-s-login session)
                                           (fn-wss-cfg-domain config) group subject))
                     (cursor (fn-wps-cursor (nthcdr 6 head) (car span) (cdr span)))
                     (fn-web-out (fn-octets-clear fn-web-out))
                     (fn-web-out (fn-octets-append-list '(80 79 83 84 13 10) fn-web-out)))
                (mv (list :post-command (fn-wss-s-cid session) cursor
                          (fn-wss-flow :post :posting ctx (list group nil))) fn-web-out))
            (fn-web-private-begin-step config action fn-web-in fn-web-out)))
      (fn-web-private-begin-step config action fn-web-in fn-web-out))))

(defun fn-wps-private-reply (config flow event cursor fn-web-in fn-web-out)
  (declare (xargs :mode :program :stobjs (fn-web-in fn-web-out)))
  (if (and cursor (equal (fn-wss-f-route flow) :post)
           (equal (fn-wss-f-stage flow) :posting)
           (equal (fn-wss-reply-code (fn-wss-reply 0 fn-web-in)) 340))
      (mv (list :post-stream (fn-wss-s-cid (fn-wss-c-session (fn-wss-f-ctx flow)))
                (fn-wss-flow :post :article (fn-wss-f-ctx flow) (fn-wss-f-data flow))) fn-web-out)
    (fn-web-private-reply-step config flow event fn-web-in fn-web-out)))
