# GENERATED by tools/interface_emit.py from the definterface :root
# declarations in host/interfaces.lisp and host/interfaces-extract.lisp.
# Do not edit; regenerate.
FN_EXTRACT_ROOTS_DECLARED="create-fn-arena fn-reader-use-seed fn-reader-set-posting fn-reader-model-octets fn-reader-reset fn-reader-chunk fn-reader-outcome fn-reader-observe-clock fn-outcome-code fn-ns-file-render fn-intern-events fn-arx-entry-ok-buffer fn-arx-read-cache-entries fn-reader-use-store fn-lzr-lz-read fn-xo-open-store"
FN_EXTRACT_EXTRA_DECLARED="create-fn-octets-rd create-fn-octets-lg fn-blake3-stobj fn-blake3-of-prefixed-buffer fn-blake3-of-prefixed-range fn-sha256"
