# GENERATED by tools/interface_emit.py from the definterface :root
# declarations in host/interfaces.lisp.
# Do not edit; regenerate.
FN_EXTRACT_ROOTS_DECLARED="create-fn-arena fn-arx-entry-ok-buffer fn-arx-file-count fn-arx-read-cache-entries fn-ats-finish-owned fn-intern-events fn-lzr-lz-read fn-ns-file-render fn-outcome-code fn-outcome-host-condition-exit-code fn-owner-recovery-prs-install fn-owner-runtime-ats-construct-internal fn-owner-runtime-bootstrap-admit fn-owner-runtime-bootstrap-fence-internal fn-owner-runtime-operation-binding-install-internal fn-reader-chunk fn-reader-model-octets fn-reader-observe-clock fn-reader-outcome fn-reader-reset fn-reader-set-posting fn-reader-use-seed fn-reader-use-store"
FN_EXTRACT_EXTRA_DECLARED="create-fn-octets-lg create-fn-octets-rd fn-blake3-of-prefixed-buffer fn-blake3-of-prefixed-range fn-blake3-stobj fn-sha256"
