;; Actual raw-host writer control flow; all I/O is recorded, never performed.
(require :sb-posix)
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(defparameter +fnn-o-nofollow+ 0)
(defvar *trace* nil)
(defvar *fail-write* nil)
(defvar *fail-close* nil)
(defun fnn-open (&rest ignored)
  (declare (ignore ignored)) (push :opened *trace*) 123)
(defun fnn-close (fd) (assert (= fd 123)) (push :closed *trace*)
  (when *fail-close* (error "injected close failure")))
(defun fnn-write-all (fd bytes)
  (declare (ignore fd bytes)) (push :write *trace*)
  (when *fail-write* (error "injected write failure")))
(defun fnn-fsync-file (fd) (declare (ignore fd)) (push :barrier *trace*))
(defmacro fnn-posix (options &body forms)
  (declare (ignore options forms)) '(push :seek *trace*))
(defun fnn-indeterminate (&rest args) (error "uncertain: ~s" args))
(defun fnn-log-pread (&rest args) (declare (ignore args)) nil)
(defun fnn-octet-list (x) x)
(defun fnn-core (name &rest args)
  (let ((job (first args)))
    (case name
      (fn-bpck-stage-observation
       (push (second args) *trace*)
       (list :stage (if (eq (second args) :created) :private :uncertain)
             :remaining (getf job :remaining)))
      (fn-bpck-io-begin '(:open :pending))
      (fn-bpck-io-action
       (case (first job)
         (:open :open) (:prefix :emit) (:close :close) (otherwise :done)))
      (fn-bpck-io-step
       (cond ((eq (first job) :close)
              (if (eq (second args) :ok) (list :done (second job))
                '(:fenced :uncertain)))
             ((eq (second args) :error) '(:close :uncertain))
             ((eq (first job) :open) '(:prefix :pending))
             (t job)))
      (fn-bpck-write-action
       (if (plusp (getf job :remaining)) :emit :digest))
      (fn-bpck-emit-step
       (push :emit *trace*)
       (list (list :stage (getf job :stage)
                   :remaining (1- (getf job :remaining))) '(42)))
      (fn-bpck-prefix-end 1)
      (otherwise (error "Unexpected core call ~s" name)))))
(defun fnn-call (name &rest args)
  (declare (ignore args))
  (case name
    (fn-bpck-digest-start '(:started))
    (fn-bpck-digest-action '((:trailer (1 2 3))))
    (otherwise (error "Unexpected digest call ~s" name))))

;; These recording stubs refute native control-flow regressions only. They
;; neither certify the ACL2 decisions nor perform disk/network/native I/O.
(load "host/native/bp-checkpoint-writer.lisp")
(let* ((*trace* nil) (*fail-write* t)
       (record (fnn-bps-checkpoint-open-job
                "unused" (list :stage :none :remaining 3) nil)))
  (assert (eq (fnn-bps-checkpoint-turn record) record))
  (assert (eq (getf (fnn-bpck-io-job record) :stage) :private))
  (assert (= (fnn-bpck-io-fd record) 123))
  (assert (eq (fnn-bps-checkpoint-turn record) record))
  (assert (eq (getf (fnn-bpck-io-job record) :stage) :uncertain))
  (assert (equal (fnn-bpck-io-control record) '(:close :uncertain)))
  (assert (fnn-bpck-io-failure record))
  (assert (eq (fnn-bpck-io-source-result record) :returned))
  (assert (eq (fnn-bpck-io-close-result record) :open))
  (fnn-bps-checkpoint-turn record)
  (assert (null (fnn-bpck-io-fd record)))
  (assert (eq (fnn-bpck-io-close-result record) :closed))
  (assert (equal (fnn-bpck-io-control record) '(:done :uncertain)))
  (assert (= (count :closed *trace*) 1)))
(let* ((*trace* nil) (*fail-write* nil)
       (record (fnn-bps-checkpoint-open-job
                "unused" (list :stage :none :remaining 1000) nil)))
  (fnn-bps-checkpoint-turn record)
  (fnn-bps-checkpoint-turn record)
  (assert (= (count :emit *trace*) 1))
  (assert (= (getf (fnn-bpck-io-job record) :remaining) 999))
  (assert (eq (fnn-bpck-io-source-result record) :returned))
  (let ((*fail-close* t))
    (setf (fnn-bpck-io-control record) '(:close :uncertain))
    (fnn-bps-checkpoint-turn record))
  (assert (null (fnn-bpck-io-fd record)))
  (assert (eq (fnn-bpck-io-close-result record) :uncertain))
  (assert (equal (fnn-bpck-io-control record) '(:fenced :uncertain)))
  (fnn-bps-checkpoint-turn record)
  (assert (= (count :closed *trace*) 1)))
(format t "PASS: bounded tick, retained write failure, ambiguous close never retried.~%")
