;;; Recording scope only: actual caller source, no disk/native grant claim.
(require :sb-posix)
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(defparameter +fnn-o-nofollow+ 0)
(defvar *fnn-extent-lock* (sb-thread:make-mutex))
(defvar *gets* 0)
(defvar *opens* 0)
(defvar *writes* 0)
(defvar *nexts* 0)
(defvar *observes* 0)
(defvar *fail-join* nil)
(defvar *hold-open* nil)
(defvar *release-open* nil)
(defun fnn-fault (message) (error "~a" message))
(defun fnn-live-bp-controller-registry () (incf *gets*) :actual-registry)
(defun fnn-open (&rest ignored)
 (declare (ignore ignored))
 (assert (not (sb-thread:holding-mutex-p *fnn-extent-lock*)))
 (incf *opens*)
 (when *hold-open*
  (sb-thread:signal-semaphore *hold-open*)
  (unless (sb-thread:wait-on-semaphore *release-open* :timeout 2)
   (error "recording open release timed out")))
 123)
(defun fnn-write-all (fd bytes)
 (assert (= fd 123)) (assert (equal bytes '(1 2 3)))
 (assert (not (sb-thread:holding-mutex-p *fnn-extent-lock*)))
 (incf *writes*) (error "injected uncertain write"))
(load "host/native/bp-checkpoint-registered-driver.lisp")
(assert (handler-case
          (progn (fnn-bps-registered-checkpoint-record :controller "unused") nil)
          (error () t)))
(assert (= *gets* 0)) (assert (= *opens* 0))
(let ((*fnn-bpck-prefix-next-callback*
       (lambda (controller job-token fuel registry)
          (assert (eq job-token :job))
        (assert (eq controller :controller)) (assert (= fuel 6))
        (assert (eq registry :actual-registry))
        (assert (sb-thread:holding-mutex-p *fnn-extent-lock*))
        (incf *nexts*)
        (values :action-prepared
         (if (= *nexts* 1) '(:bp-checkpoint-io-action :job-token 2 :open 0 nil)
           '(:bp-checkpoint-io-action :job-token 4 :emit 0 (1 2 3)))
         3 registry)))
      (*fnn-bpck-prefix-observe-callback*
       (lambda (controller token revision observation fuel registry)
        (assert (eq controller :controller)) (assert (eq token :job-token))
        (assert (= fuel 6)) (assert (eq registry :actual-registry))
        (assert (sb-thread:holding-mutex-p *fnn-extent-lock*))
        (incf *observes*)
        (if (= revision 2)
         (progn (assert (eq observation :ok)) (values :observed 4 registry))
         (progn (assert (= revision 4)) (assert (eq observation :unknown))
          (when *fail-join* (error "injected failed core join"))
          (values :uncertain 4 registry))))))
 ;; Even installed compiled roles do not supply a per-job constructor claim.
 (assert (handler-case
           (progn (fnn-bps-registered-checkpoint-record :controller "unused") nil)
           (error () t)))
 (assert (= *gets* 0)) (assert (= *nexts* 0))
 (multiple-value-bind (word record) (values :raw-unfunded (%make-fnn-bpck-registered-io :controller :controller :job-token :job :stage "unused"))
  (assert (eq word :raw-unfunded))
  (assert (eq (fnn-bps-registered-checkpoint-prefix-turn record 6) record))
  (assert (= *opens* 1)) (assert (= *observes* 0))
  (assert (= (fnn-bpck-registered-io-fd record) 123))
  (assert (eq (fnn-bpck-registered-io-close-result record) :open))
  (fnn-bps-registered-checkpoint-prefix-turn record 6)
  (assert (= *opens* 1)) (assert (= *observes* 1))
  (assert (null (fnn-bpck-registered-io-action record)))
  (fnn-bps-registered-checkpoint-prefix-turn record 6)
  (assert (= *writes* 1)) (assert (= *observes* 1))
  (assert (eq (fnn-bpck-registered-io-outcome record) :unknown))
  (assert (fnn-bpck-registered-io-failure record))
  (let ((*fail-join* t)) (fnn-bps-registered-checkpoint-prefix-turn record 6))
  (assert (fnn-bpck-registered-io-core-failure record))
  (assert (fnn-bpck-registered-io-action record))
  (fnn-bps-registered-checkpoint-prefix-turn record 6)
  (assert (= *writes* 1)) (assert (= *opens* 1))
  (assert (= *nexts* 2)) (assert (= *observes* 2))
  (assert (= (fnn-bpck-registered-io-fd record) 123))))
;; A real competing thread cannot join :unknown before the held primitive
;; actually returns. The source mutex is tried, never waited on by that turn.
(setf *opens* 0 *writes* 0 *nexts* 0 *observes* 0
      *hold-open* (sb-thread:make-semaphore)
      *release-open* (sb-thread:make-semaphore))
(let* ((next-callback (lambda (controller job-token fuel registry)
                       (declare (ignore controller fuel))
          (assert (eq job-token :job))
                       (incf *nexts*)
                       (values :action-prepared
                        '(:bp-checkpoint-io-action :job-token 2 :open 0 nil) 3 registry)))
       (observe-callback (lambda (controller token revision observation fuel registry)
                          (declare (ignore controller token revision fuel))
                          (incf *observes*)
                          (values (if (eq observation :ok) :observed :uncertain) 3 registry)))
       (*fnn-bpck-prefix-next-callback* next-callback)
       (*fnn-bpck-prefix-observe-callback* observe-callback))
 (multiple-value-bind (word record) (values :raw-unfunded (%make-fnn-bpck-registered-io :controller :controller :job-token :job :stage "unused"))
  (assert (eq word :raw-unfunded))
  (let ((worker (sb-thread:make-thread
                 (lambda ()
                  (let ((*fnn-bpck-prefix-next-callback* next-callback)
                        (*fnn-bpck-prefix-observe-callback* observe-callback))
                   (fnn-bps-registered-checkpoint-prefix-turn record 6))))))
   (assert (sb-thread:wait-on-semaphore *hold-open* :timeout 2))
   (assert (eq (fnn-bpck-registered-io-source-result record) :running))
   (fnn-bps-registered-checkpoint-prefix-turn record 6)
   (assert (= *nexts* 1)) (assert (= *observes* 0))
   (assert (eq (fnn-bpck-registered-io-source-result record) :running))
   (sb-thread:signal-semaphore *release-open*)
   (sb-thread:join-thread worker :timeout 2)
   (assert (eq (fnn-bpck-registered-io-source-result record) :returned))
   (assert (eq (fnn-bpck-registered-io-outcome record) :ok))
   (fnn-bps-registered-checkpoint-prefix-turn record 6)
   (assert (= *opens* 1)) (assert (= *observes* 1)))))
(setf *hold-open* nil *release-open* nil)
(format t "registered checkpoint caller recording refuter PASS~%")
; Actual detached-close lifetime: unknown close retains debt and cannot be
; retried, even though the native descriptor slot is now NIL.
(defvar *closes* 0)
(defvar *close-fails* nil)
(defun fnn-close (fd)
 (assert (= fd 123))
 (assert (not (sb-thread:holding-mutex-p *fnn-extent-lock*)))
 (incf *closes*)
 (when *close-fails* (error "injected ambiguous close")))
(dolist (ambiguous '(nil t))
 (let* ((*closes* 0) (*close-fails* ambiguous) (issued nil) (settled nil)
        (record (%make-fnn-bpck-registered-io :controller :controller :job-token :job :stage "unused"
                  :fd 123 :close-result :open))
        (*fnn-bpck-close-next-callback*
         (lambda (controller job-token fuel registry)
          (assert (eq job-token :job))
          (assert (eq controller :controller))
          (if issued (values :close-not-required nil fuel registry)
           (progn (setf issued t)
            (values :action-prepared '(:bp-checkpoint-io-action :job 9 :close 17 nil)
                    fuel registry)))))
        (*fnn-bpck-close-observe-callback*
         (lambda (controller token revision outcome fuel registry)
          (assert (eq controller :controller)) (assert (eq token :job))
          (assert (= revision 9))
          (assert (eq outcome (if ambiguous :unknown :ok)))
          (setf settled t)
          (values (if ambiguous :close-uncertain :close-observed) fuel registry))))
  (fnn-bps-registered-checkpoint-close-turn record 6)
  (assert (= *closes* 1)) (assert (null (fnn-bpck-registered-io-fd record)))
  (assert (eq (fnn-bpck-registered-io-close-result record)
              (if ambiguous :uncertain :closed)))
  (fnn-bps-registered-checkpoint-close-turn record 6)
  (assert settled) (assert (null (fnn-bpck-registered-io-action record)))
  (fnn-bps-registered-checkpoint-close-turn record 6)
  (assert (= *closes* 1))))
; A detached ambiguous descriptor is not an already-closed positive.
(let ((*closes* 0)
      (record (%make-fnn-bpck-registered-io :controller :controller :job-token :job :stage "unused"
                :fd nil :close-result :uncertain))
      (*fnn-bpck-close-next-callback*
       (lambda (controller job-token fuel registry)
        (declare (ignore controller))
          (assert (eq job-token :job))
        (values :action-prepared '(:bp-checkpoint-io-action :job 10 :close 17 nil)
                fuel registry)))
      (*fnn-bpck-close-observe-callback*
       (lambda (controller token revision outcome fuel registry)
        (declare (ignore controller token revision))
        (assert (eq outcome :unknown))
        (values :close-uncertain fuel registry))))
 (fnn-bps-registered-checkpoint-close-turn record 6)
 (assert (= *closes* 0))
 (assert (eq (fnn-bpck-registered-io-close-result record) :uncertain))
 (fnn-bps-registered-checkpoint-close-turn record 6)
 (assert (eq (fnn-bpck-registered-io-status record) :close-uncertain)))
(format t "registered checkpoint close recording refuter PASS~%")
; An old primitive result refused by ordinary dispatch can be joined only
; through the exact cancelled-job observation, without another I/O attempt.
(dolist (settlement '(:stale-checkpoint-observation :cancelled-observed :cancelled-uncertain))
 (let* ((record (%make-fnn-bpck-registered-io :controller :controller :job-token :job :stage "unused"
                  :fd 123 :close-result :open :core-failure :stale-checkpoint-observation
                  :action '(:bp-checkpoint-io-action :job 8 :emit 17 (1 2 3))
                  :outcome :unknown))
        (opens *opens*) (writes *writes*)
        (*fnn-bpck-cancelled-observe-callback*
         (lambda (controller token revision outcome fuel registry)
          (assert (eq controller :controller)) (assert (eq token :job))
          (assert (= revision 8)) (assert (eq outcome :unknown))
          (values settlement fuel registry))))
  (fnn-bps-registered-checkpoint-cancelled-result-turn record 6)
  (assert (= *opens* opens)) (assert (= *writes* writes))
  (assert (= (fnn-bpck-registered-io-fd record) 123))
  (assert (eq (fnn-bpck-registered-io-close-result record) :open))
  (if (eq settlement :stale-checkpoint-observation)
   (progn (assert (fnn-bpck-registered-io-action record))
          (assert (fnn-bpck-registered-io-core-failure record)))
   (progn (assert (null (fnn-bpck-registered-io-action record)))
          (assert (null (fnn-bpck-registered-io-core-failure record)))))))
(format t "registered checkpoint cancelled-result recording refuter PASS~%")
; Cancellation result join shares the primitive owner lock. It cannot settle
; the placeholder unknown while an actual open is held in another thread.
(let* ((*hold-open* (sb-thread:make-semaphore :count 0))
       (*release-open* (sb-thread:make-semaphore :count 0))
       (record (%make-fnn-bpck-registered-io :controller :controller :job-token :job :stage "unused"))
       (settlements 0)
       (*fnn-bpck-prefix-next-callback*
        (lambda (controller job-token fuel registry)
         (declare (ignore controller))
          (assert (eq job-token :job))
         (values :action-prepared '(:bp-checkpoint-io-action :job 11 :open 0 nil)
                 fuel registry)))
       (*fnn-bpck-cancelled-observe-callback*
        (lambda (controller token revision outcome fuel registry)
         (assert (eq controller :controller)) (assert (eq token :job))
         (assert (= revision 11)) (assert (eq outcome :ok))
         (incf settlements)
         (values :cancelled-observed fuel registry)))
       (next-callback *fnn-bpck-prefix-next-callback*)
       (held *hold-open*) (release *release-open*))
 (let ((worker (sb-thread:make-thread
                (lambda ()
                 (let ((*fnn-bpck-prefix-next-callback* next-callback)
                       (*hold-open* held) (*release-open* release))
                  (fnn-bps-registered-checkpoint-prefix-turn record 6))))))
  (assert (sb-thread:wait-on-semaphore *hold-open* :timeout 2))
  (fnn-bps-registered-checkpoint-cancelled-result-turn record 6)
  (assert (= settlements 0))
  (assert (eq (fnn-bpck-registered-io-source-result record) :running))
  (assert (fnn-bpck-registered-io-action record))
  (sb-thread:signal-semaphore *release-open*)
  (sb-thread:join-thread worker :timeout 2)
  (fnn-bps-registered-checkpoint-cancelled-result-turn record 6)
  (assert (= settlements 1))
  (assert (eq (fnn-bpck-registered-io-source-result record) :returned))
  (assert (null (fnn-bpck-registered-io-action record)))
  (assert (= (fnn-bpck-registered-io-fd record) 123))
  (assert (eq (fnn-bpck-registered-io-close-result record) :open))))
(format t "registered checkpoint cancelled held-primitive refuter PASS~%")
