;;; Recording scope only: actual caller source, no disk/native grant claim.
(require :sb-posix)
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(defparameter +fnn-o-nofollow+ 0)
(defvar *fnn-extent-lock* (sb-thread:make-mutex))
(defvar *gets* 0)
(defvar *opens* 0)
(defvar *writes* 0)
(defvar *nexts* 0)
(defvar *observes* 0)
(defvar *fail-join* nil)
(defun fnn-fault (message) (error "~a" message))
(defun fnn-live-bp-controller-registry () (incf *gets*) :actual-registry)
(defun fnn-open (&rest ignored)
 (declare (ignore ignored))
 (assert (not (sb-thread:holding-mutex-p *fnn-extent-lock*)))
 (incf *opens*) 123)
(defun fnn-write-all (fd bytes)
 (assert (= fd 123)) (assert (equal bytes '(1 2 3)))
 (assert (not (sb-thread:holding-mutex-p *fnn-extent-lock*)))
 (incf *writes*) (error "injected uncertain write"))
(load "host/native/bp-checkpoint-registered-driver.lisp")
(multiple-value-bind (word record) (fnn-bps-registered-checkpoint-record :controller "unused")
 (assert (eq word :bp-runtime-unavailable)) (assert (null record))
 (assert (= *gets* 0)) (assert (= *opens* 0)))
(let ((*fnn-bpck-prefix-next-callback*
       (lambda (controller fuel registry)
        (assert (eq controller :controller)) (assert (= fuel 6))
        (assert (eq registry :actual-registry))
        (assert (sb-thread:holding-mutex-p *fnn-extent-lock*))
        (incf *nexts*)
        (values :action-prepared
         (if (= *nexts* 1) '(:bp-checkpoint-io-action :job-token 2 :open 0 nil)
           '(:bp-checkpoint-io-action :job-token 4 :emit 0 (1 2 3)))
         3 registry)))
      (*fnn-bpck-prefix-observe-callback*
       (lambda (controller token revision observation fuel registry)
        (assert (eq controller :controller)) (assert (eq token :job-token))
        (assert (= fuel 6)) (assert (eq registry :actual-registry))
        (assert (sb-thread:holding-mutex-p *fnn-extent-lock*))
        (incf *observes*)
        (if (= revision 2)
         (progn (assert (eq observation :ok)) (values :observed 4 registry))
         (progn (assert (= revision 4)) (assert (eq observation :unknown))
          (when *fail-join* (error "injected failed core join"))
          (values :uncertain 4 registry))))))
 (multiple-value-bind (word record) (fnn-bps-registered-checkpoint-record :controller "unused")
  (assert (eq word :retained))
  (assert (eq (fnn-bps-registered-checkpoint-prefix-turn record 6) record))
  (assert (= *opens* 1)) (assert (= *observes* 0))
  (assert (= (fnn-bpck-registered-io-fd record) 123))
  (assert (eq (fnn-bpck-registered-io-close-result record) :open))
  (fnn-bps-registered-checkpoint-prefix-turn record 6)
  (assert (= *opens* 1)) (assert (= *observes* 1))
  (assert (null (fnn-bpck-registered-io-action record)))
  (fnn-bps-registered-checkpoint-prefix-turn record 6)
  (assert (= *writes* 1)) (assert (= *observes* 1))
  (assert (eq (fnn-bpck-registered-io-outcome record) :unknown))
  (assert (fnn-bpck-registered-io-failure record))
  (let ((*fail-join* t)) (fnn-bps-registered-checkpoint-prefix-turn record 6))
  (assert (fnn-bpck-registered-io-core-failure record))
  (assert (fnn-bpck-registered-io-action record))
  (fnn-bps-registered-checkpoint-prefix-turn record 6)
  (assert (= *writes* 1)) (assert (= *opens* 1))
  (assert (= *nexts* 2)) (assert (= *observes* 2))
  (assert (= (fnn-bpck-registered-io-fd record) 123))))
(format t "registered checkpoint caller recording refuter PASS~%")
