;; Recording of the actual unhooked core consumer body. Registry/machine stubs
;; expose state ownership and effects ordering, not ACL2/guard/runtime evidence.
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(declaim (declaration xargs))
(defmacro mv (&rest values) `(values ,@values))
(defmacro mv-let (bindings value &body body) `(multiple-value-bind ,bindings ,value ,@body))
(defvar *current* '(7 :issued :registered-current))
(defvar *fetch-status* :current)
(defvar *replace-status* :updated)
(defvar *calls* nil)
(defun fn-bpc-current (token fuel registry)
  (declare (ignore registry)) (assert (eq token :controller))
  (push :fetch *calls*) (values *fetch-status* *current* fuel))
(defun fn-bpnj-host-eventp (event) (member event '(:dispatch :recover)))
(defun fn-bpnf-epoch (current) (first current))
(defun fn-bpnf-issued (current) (second current))
(defun fn-bpnj-step (current event)
  (assert (eq (third current) :registered-current))
  (push (list :machine event current) *calls*)
  (list (list (1+ (first current)) nil :registered-current) (list :effect event)))
(defun fn-bpnf-answer-state (answer) (first answer))
(defun fn-bpnf-answer-effects (answer) (second answer))
(defun fn-bpc-current-replace (token epoch issued next fuel registry)
  (assert (eq token :controller))
  (assert (= epoch (first *current*))) (assert (eq issued (second *current*)))
  (push :replace *calls*)
  (when (eq *replace-status* :updated) (setf *current* next))
  (values *replace-status* fuel registry))
(with-open-file (source "books/bp-controller-dispatch.lisp")
  (loop for form = (read source nil nil) while form
        when (and (consp form) (eq (car form) 'defun)) do (eval form)))
(defvar *fnn-extent-lock* (sb-thread:make-mutex :name "recording BP registry"))
(defvar *the-live-state* :recording-state)
(defvar *registry-observations* 0)
(defun user-stobj-alist (state)
  (assert (eq state :recording-state)) (incf *registry-observations*)
  '((fn-bp-controller-registry . :registry)))
(defun fnn-fault (&rest args) (error "~s" args))
(load "host/native/bp-controller-registry.lisp")
(load "host/native/bp-controller-driver.lisp")
(let ((*current* '(7 :issued :registered-current)) (*calls* nil))
  (assert (handler-case (progn (fnn-bps-registered-foundation-step :controller :dispatch 10) nil)
            (error () t)))
  (assert (null *calls*)) (assert (= *registry-observations* 0)))
; Diagnostic test installation only; production component has no installer.
(setf *fnn-bp-controller-step-callback* #'fn-owner-bp-controller-step)
(let ((*current* '(7 :issued :registered-current)) (*calls* nil))
  (multiple-value-bind (status effects fuel)
      (fnn-bps-registered-foundation-step :controller :dispatch 10)
    (assert (eq status :updated)) (assert (equal effects '(:effect :dispatch)))
    (assert (= fuel 10)) (assert (= (first *current*) 8))
    (assert (= *registry-observations* 1))))
(dolist (event '(:dispatch :recover))
  (let ((*calls* nil) (*current* '(7 :issued :registered-current)))
    (multiple-value-bind (status effects fuel registry)
        (fn-owner-bp-controller-step :controller event 10 :registry)
      (assert (eq status :updated)) (assert (equal effects (list :effect event)))
      (assert (= fuel 10)) (assert (eq registry :registry))
      (assert (= (first *current*) 8))
      (assert (equal (reverse *calls*) (list :fetch (list :machine event '(7 :issued :registered-current)) :replace))))))
(dolist (status '(:yield :stale-controller :controller-unavailable :controller-fenced))
  (let ((*calls* nil) (*fetch-status* status))
    (multiple-value-bind (result effects)
        (fn-owner-bp-controller-step :controller :dispatch 10 :registry)
      (assert (eq result status)) (assert (null effects)) (assert (equal *calls* '(:fetch))))))
(dolist (status '(:yield :stale-controller :stale-current :controller-unavailable :controller-busy :controller-fenced))
  (let ((*calls* nil) (*replace-status* status) (*current* '(7 :issued :registered-current)))
    (multiple-value-bind (result effects)
        (fn-owner-bp-controller-step :controller :recover 10 :registry)
      (assert (eq result status)) (assert (null effects))
      (assert (equal *current* '(7 :issued :registered-current))))))
(let ((*calls* nil))
  (multiple-value-bind (status effects)
      (fn-owner-bp-controller-step :controller :invalid 10 :registry)
    (assert (eq status :invalid-controller-event)) (assert (null effects))
    (assert (equal *calls* '(:fetch)))))
(format t "PASS: actual token-only consumer composition uses registered CURRENT; effects follow successful replacement only, for dispatch/recovery.~%")
