; Executes actual head/primary framing bodies with CL shims only.
; No ACL2/source provider/span lifetime/integrity/admission claim.
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(declaim (declaration xargs))
(defconstant *fn-bpc-max-uint* 18446744073709551615)
(defun true-listp (x) (if (consp x) (true-listp (cdr x)) (null x)))
(defun len (x) (length x))
(defun natp (x) (and (integerp x) (<= 0 x)))
(defun zp (x) (or (not (integerp x)) (<= x 0)))
(defun member-equal (x xs) (member x xs :test #'equal))
(defun fn-cbor-octetp (x) (and (integerp x) (<= 0 x 255)))
(defun fn-cbor-ag-car (x) (if (consp x) (car x) nil))
(defun fn-cbor-ag-cdr (x) (if (consp x) (cdr x) nil))
(defmacro mv (&rest args) `(values ,@args))
(defmacro mv-let (names expression &body body)
 `(multiple-value-bind ,names ,expression ,@body))
(with-open-file (stream "books/bpsec-model.lisp")
 (loop for form = (read stream nil :end) until (eq form :end)
  when (and (eq (car form) 'defun) (member (second form) '(fn-bps-field fn-bps-uintp)))
  do (eval form)))
(dolist (path '("books/bpsec-head.lisp" "books/bp-wire-primary-cursor.lisp" "books/bp-wire-canonical-cursor.lisp" "books/tcpcl-segment-source-cursor.lisp" "books/bp-segmented-wire-job.lisp"))
 (with-open-file (stream path)
  (loop for form = (read stream nil :end) until (eq form :end)
        when (eq (car form) 'defun) do (eval form))))


(defun run-segmented (root total q)
 (let ((j (fn-bpsw-begin :held-transfer root total)) (events nil))
  (loop repeat 10000 do
   (multiple-value-bind (word next used event) (fn-bpsw-turn j q 0)
    (assert (<= used q))
    (assert (eq (fn-tsc-at 8 (fn-bps-field 5 next)) root))
    (setf j next)
    (when (eq word :block-source) (push event events))
    (when (member word '(:source-complete :refused))
     (return-from run-segmented (values word (reverse events) j)))))
  (error "Unsettled segmented source")))
(defparameter *primary* '(136 7 0 0 130 2 130 10 0 130 2 130 11 0
                         130 2 130 10 0 130 0 1 10))
(defparameter *bundle* (append '(159) *primary* '(133 1 1 0 0 67 65 66 67 255)))
(dolist (cut '(0 1 7 24 33))
 (let ((root (list (nthcdr cut *bundle*) nil (subseq *bundle* 0 cut))))
  (dolist (q '(1 7 64))
   (multiple-value-bind (word events job) (run-segmented root (length *bundle*) q)
    (assert (eq word :source-complete)) (assert (= (length events) 2))
    (assert (eq (caar events) :bp-primary-source))
    (assert (equal (second events)
             '(:bp-canonical-source :held-transfer 24 33 1 1 0 0
               (:bps-span :held-transfer 30 3) nil)))
    (assert (eq (fn-tsc-at 8 (fn-bps-field 5 job)) root))))))
(dolist (wire (list (butlast *bundle*) (append *bundle* '(0))
                   (append '(159) *primary* '(255))
                   (append '(159) *primary* '(133 1 2 0 0 64 255))
                   (append '(159) *primary* '(133 1 1 0 0 64 133 2 2 0 0 64 255))))
 (let ((root (list wire)))
  (multiple-value-bind (word events job) (run-segmented root (length wire) 1)
   (declare (ignore events)) (assert (eq word :refused))
   (assert (eq (second job) :refused)))))
(format t "PASS actual segmented source+primary+canonical bodies: all cuts/q1/7/64, retained roots, spans/refusals.~%")
