; Executes actual head/canonical parser bodies with CL shims only.
; No ACL2/source provider/span lifetime/integrity/admission claim.
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(declaim (declaration xargs))
(defconstant *fn-bpc-max-uint* 18446744073709551615)
(defun true-listp (x) (if (consp x) (true-listp (cdr x)) (null x)))
(defun len (x) (length x))
(defun natp (x) (and (integerp x) (<= 0 x)))
(defun zp (x) (or (not (integerp x)) (<= x 0)))
(defun member-equal (x xs) (member x xs :test #'equal))
(defun fn-cbor-octetp (x) (and (integerp x) (<= 0 x 255)))
(defun fn-cbor-ag-car (x) (if (consp x) (car x) nil))
(defun fn-cbor-ag-cdr (x) (if (consp x) (cdr x) nil))
(defmacro mv (&rest args) `(values ,@args))
(defmacro mv-let (names expression &body body)
 `(multiple-value-bind ,names ,expression ,@body))
(with-open-file (stream "books/bpsec-model.lisp")
 (loop for form = (read stream nil :end) until (eq form :end)
  when (and (eq (car form) 'defun) (member (second form) '(fn-bps-field fn-bps-uintp)))
  do (eval form)))
(dolist (path '("books/bpsec-head.lisp" "books/bp-wire-canonical-cursor.lisp"))
 (with-open-file (stream path)
  (loop for form = (read stream nil :end) until (eq form :end)
        when (eq (car form) 'defun) do (eval form))))
(defun run-block (bytes quantum)
 (let ((cursor (fn-bpwc-start :original-source (length bytes) 0)) (rest bytes))
  (loop repeat 1000 do
   (multiple-value-bind (word next used suffix event)
       (fn-bpwc-window-loop cursor rest quantum 0)
    (assert (<= used quantum))
    (assert (eq suffix (nthcdr used rest)))
    (setf cursor next rest suffix)
    (when (member word '(:complete :refused))
     (return-from run-block (values word event cursor rest)))))
  (error "Block did not settle")))
(dolist (q '(1 7 64))
 (multiple-value-bind (word event cursor rest)
     (run-block '(133 1 1 0 0 67 65 66 67) q)
  (declare (ignore cursor))
  (assert (eq word :complete)) (assert (null rest))
  (assert (equal event '(:bp-canonical-source :original-source 0 9 1 1 0 0
                        (:bps-span :original-source 6 3) nil))))
 (multiple-value-bind (word event cursor rest)
     (run-block '(134 1 1 0 1 65 65 66 0 0) q)
  (declare (ignore cursor rest))
  (assert (eq word :complete))
  (assert (equal event '(:bp-canonical-source :original-source 0 10 1 1 0 1
                        (:bps-span :original-source 6 1)
                        (:bps-span :original-source 8 2))))))
(dolist (bytes '((133 1 0 0 0 64) (133 1 1 0 1 64) (134 1 1 0 1 64 67 0 0 0)
                 (133 24 1 1 0 0 64)))
 (assert (eq (run-block bytes 1) :refused)))
(let ((bytes (append '(133 1 1 0 0 89 1 0) (make-list 256 :initial-element 65))))
 (dolist (q '(1 64))
  (multiple-value-bind (word event cursor rest) (run-block bytes q)
   (declare (ignore cursor rest))
   (assert (eq word :complete))
   (assert (equal (ninth event) '(:bps-span :original-source 8 256))))))
(format t "PASS actual canonical framing/head bodies: q1/7/64 spans/CRC shape/large body/refusals.~%")
