; Executes actual head/primary framing bodies with CL shims only.
; No ACL2/source provider/span lifetime/integrity/admission claim.
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(declaim (declaration xargs))
(defconstant *fn-bpc-max-uint* 18446744073709551615)
(defun true-listp (x) (if (consp x) (true-listp (cdr x)) (null x)))
(defun len (x) (length x))
(defun natp (x) (and (integerp x) (<= 0 x)))
(defun zp (x) (or (not (integerp x)) (<= x 0)))
(defun member-equal (x xs) (member x xs :test #'equal))
(defun fn-cbor-octetp (x) (and (integerp x) (<= 0 x 255)))
(defun fn-cbor-ag-car (x) (if (consp x) (car x) nil))
(defun fn-cbor-ag-cdr (x) (if (consp x) (cdr x) nil))
(defmacro mv (&rest args) `(values ,@args))
(defmacro mv-let (names expression &body body)
 `(multiple-value-bind ,names ,expression ,@body))
(with-open-file (stream "books/bpsec-model.lisp")
 (loop for form = (read stream nil :end) until (eq form :end)
  when (and (eq (car form) 'defun) (member (second form) '(fn-bps-field fn-bps-uintp)))
  do (eval form)))
(dolist (path '("books/bpsec-head.lisp" "books/bp-wire-primary-cursor.lisp"))
 (with-open-file (stream path)
  (loop for form = (read stream nil :end) until (eq form :end)
        when (eq (car form) 'defun) do (eval form))))

(defun run-primary (bytes q)
 (let ((cursor (fn-bpwp-start :held-source (length bytes) 0)) (rest bytes))
  (loop repeat 2000 do
   (multiple-value-bind (word next used suffix event)
       (fn-bpwp-window-loop cursor rest q 0)
    (assert (<= used q)) (assert (eq suffix (nthcdr used rest)))
    (setf cursor next rest suffix)
    (when (member word '(:complete :refused))
     (return-from run-primary (values word event cursor rest)))))
  (error "Unsettled primary")))
; Primary8 CRC0, three ipn EIDs, timestamp2, lifetime10.
(defparameter *primary* '(136 7 0 0 130 2 130 10 0 130 2 130 11 0
                         130 2 130 10 0 130 0 1 10))
(dolist (q '(1 7 64))
 (multiple-value-bind (word event cursor rest) (run-primary *primary* q)
  (assert (eq word :complete)) (assert (null rest))
  (assert (eq (second cursor) :done))
  (assert (equal (subseq event 0 6)
                 (list :bp-primary-source :held-source 0 (length *primary*) 0 0)))))
; CRC2 adds only fixed4 span, body bytes never accumulate.
(let ((p (append '(137 7 0 2) (nthcdr 4 *primary*) '(68 0 0 0 0))))
 (dolist (q '(1 7 64))
  (multiple-value-bind (word event cursor rest) (run-primary p q)
   (declare (ignore cursor rest)) (assert (eq word :complete))
   (assert (member (list :crc-bytes :bps-span :held-source (- (length p) 4) 4)
                   (seventh event) :test #'equal)))))
; Fragment flag adds exact offset/total fields, then CRC1 span2.
(let ((p (append '(139 7 1 1) (nthcdr 4 *primary*) '(0 24 100 66 0 0))))
 (dolist (q '(1 7 64))
  (multiple-value-bind (word event cursor rest) (run-primary p q)
   (declare (ignore cursor rest)) (assert (eq word :complete))
   (assert (member '(:fragment-offset 0) (seventh event) :test #'equal))
   (assert (member '(:total-adu 100) (seventh event) :test #'equal)))))
; Text SSP spans can cross allocation leaves; no text body retained.
(let ((p (append '(136 7 0 0 130 1 121 1 0)
                 (make-list 256 :initial-element 65)
                 '(130 2 130 11 0 130 2 130 10 0 130 0 1 10))))
 (dolist (q '(1 64)) (assert (eq (run-primary p q) :complete))))
(dolist (p '((136 6 0 0) (136 7 0 2) (136 7 0 0 130 3)
             (136 24 7 0 0)))
 (multiple-value-bind (word event cursor rest) (run-primary p 1)
  (declare (ignore event rest)) (assert (eq word :refused))
  (assert (eq (second cursor) :refused))))
(format t "PASS actual primary framing/head bodies: q1/7/64, spans, shape/nonminimal refusals.~%")
