
;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-core-state (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-core-state "host/native/io.lisp"))
(defun fnn-err (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-err "host/native/io.lisp"))
(defun fnn-extent-pool-funded-p ()
  (harness-stub-reached 'fnn-extent-pool-funded-p "host/native/extent.lisp"))
(defun fnn-mux-output-window (conn octets end)
  (declare (ignorable conn octets end))
  (harness-stub-reached 'fnn-mux-output-window "host/native/mux.lisp"))
(defun fnn-mux-write-now (conn)
  (declare (ignorable conn))
  (harness-stub-reached 'fnn-mux-write-now "host/native/mux.lisp"))
(defun fnn-owner-await-logical (service cid &optional deadline)
  (declare (ignorable service cid deadline))
  (harness-stub-reached 'fnn-owner-await-logical "host/native/owner.lisp"))
(defun fnn-owner-connection-call (service operation thunk)
  (declare (ignorable service operation thunk))
  (harness-stub-reached 'fnn-owner-connection-call "host/native/owner.lisp"))
;;; ---- derived stubs: END ----
;;; Actual native cursor/mux functions with mocked I/O and ACL2 dispatch.
;;; This discriminates poll/control flow, not ACL2 semantics or image custody.
(require :sb-posix)
(require :sb-bsd-sockets)
(unless (find-package "ACL2") (make-package "ACL2" :use '("CL")))
(defun load-selected (path names)
  (let ((seen nil))
    (with-open-file (stream path)
      (loop for form = (read stream nil :eof) until (or (eq form :eof) (= (length seen) (length names))) do
        (when (and (consp form) (member (car form) '(defun defstruct defconstant))
                   (member (if (consp (second form)) (car (second form)) (second form)) names))
          (push (if (consp (second form)) (car (second form)) (second form)) seen)
          (eval form))))
    (assert (= (length seen) (length names)))))
(defvar *fnn-extent-no-io* nil)
(defvar *held* nil)
(defvar *cold* nil)
(defvar *calls* 0)
(defvar *issued* nil)
(defvar *read* (list :issued))
(defvar *poll-word* :serve)
(defvar *poll-args* nil)
(defvar *clock* 100)
(defvar *queued* nil)
(defvar *worked* nil)
(defvar *after-called* nil)
(defvar *render-calls* 0)
(defvar *private-logical* nil)
(defvar *private-awaits* 0)
(defvar *private-unpins* 0)
(define-condition fnn-store-io-refusal (error)
  ((message :initarg :message :reader refusal-message)))
(defun fnn-fault (&rest args) (error "Unexpected fault ~s" args))
(defun fnn-owner-cursor-step-serialized (service cid thunk class)
  (declare (ignore service cid class))
  (let ((*held* t)) (funcall thunk)))
(defun fnn-owner-over-window () 1)
(defun fnn-live-stobj (name) (assert *held*) name)
(defun fnn-call (name plan window arena &optional cat)
  (declare (ignore name plan window arena cat))
  (assert *held*) (assert *fnn-extent-no-io*) (incf *calls*)
  (when *cold* (throw 'fnn-extent-cold '(3 100 4096 77)))
  (list :ok :advanced))
(defun fnn-owner-cold-issue-locked (service cid entry)
  (declare (ignore service cid))
  (assert *held*) (push entry *issued*) *read*)
(defun fnn-owner-cold-await (&rest args)
  (declare (ignore args))
  (assert *private-logical*) (incf *private-awaits*) (setf *cold* nil)
  (values :serve *clock*))
(defun fnn-owner-response-unpin (&rest args)
  (declare (ignore args))
  (assert *private-logical*) (incf *private-unpins*))
(defun fnn-make-octets (size) (make-array size :element-type '(unsigned-byte 8)))
(defun fnn-owner-render-next (plan &optional compressedp borrowp)
  ;; (values OCTETS PLAN-REST DONEP CURSORP END), as the host's.
  (declare (ignore compressedp borrowp)) (incf *render-calls*)
  (if (eq plan :original) (values #() plan nil t 0)
    (values #(65 13 10) nil t nil 3)))
(defun fnn-developer-selector (name) (declare (ignore name)) nil)
(defun fnn-owner-monotonic-ms () *clock*)
(defun fnn-now () 1000)
(defun fnn-owner-cold-poll (service read first-miss since)
  (declare (ignore service))
  (setf *poll-args* (list read first-miss since))
  (values *poll-word* since *clock* nil))
(defun fnn-mux-queue (loop conn octets op after &optional end)
  (declare (ignore loop conn end)) (push (list octets op after) *queued*))
(defun fnn-mux-after (loop conn after)
  (declare (ignore loop conn after)) (setf *after-called* t))
(defun fnn-mux-work (loop conn)
  (declare (ignore loop conn)) (setf *worked* t))
(defun fnn-core (name &rest args)
  (declare (ignore args))
  ;; The plans here are the cursor's own (:original, :advanced), never an
  ;; ARTICLE preflight or article plan.
  (case name (fn-splan-cursor-resume-ms 1) (fn-splan-at-cursorp nil)
    ((fn-asto-preflight-planp fn-asto-plan-articlep fn-asto-plan-cursorp) nil)
    (otherwise (error "Unexpected core call ~s" name))))
(defun fnn-mux-plan-yield (&rest args)
  (declare (ignore args)) (error "Cold read is distinct from empty progress"))
(defun fnn-mux-z-out (conn octets) (declare (ignore conn)) octets)
(defun fnn-mux-ticks (seconds) seconds)
(defconstant +fnn-mux-send-seconds+ 10)
(defun fnn-octets (octets) octets)
(defun fnn-owner-past-p (deadline) (declare (ignore deadline)) nil)
(defun fnn-owner-handle-chunk (&rest args)
  (declare (ignore args)) (values :original nil nil 1))
(defun fnn-owner-join-octets (parts) (apply #'concatenate 'vector parts))
;; No output ledger is installed on this service (the host's
;; fnn-owner-output-issue answers NIL then): no output grant.
(defun fnn-owner-output-issue (service identity &optional capture)
  (declare (ignore service identity capture))
  nil)
;; The response's identity (the owner's fn-rid-response reservation): one
;; response of this connection; nothing here reads it.
(defun fnn-owner-response-identity (service connection class)
  (declare (ignore service connection class))
  '(:response 7 1 1))
;; The render's measurement envelope (fnn-owner-measured); measurement and
;; the trace collector are off here, so it runs its body.
(defvar *fnn-owner-measure* nil)
(defvar *fnn-trace-state* nil)
(defvar *fnn-trace-operation* nil)
(defvar *fnn-trace-connection-generation* nil)
(with-open-file (stream "host/native/owner.lisp")
  (loop for form = (read stream nil :eof) until (eq form :eof)
        when (and (consp form) (eq (car form) 'defmacro) (eq (cadr form) 'fnn-owner-measured))
          do (eval form) (return)))
;; The scalar window activation the cursor step runs under (no response
;; capture here, so no window is retained: it calls its thunk).
(defvar *fnn-response-capture* nil)
(defvar *fnn-extent-window-mode* nil)
(defvar *fnn-extent-window-worker* nil)
(defvar *fnn-extent-window-token* nil)
(load-selected "host/native/owner.lisp"
               '(fnn-owner-window-activation fnn-owner-ready-plan-step fnn-owner-cursor-step
                 fnn-owner-render-next-quantum fnn-owner-feed-logical))
(load-selected "host/native/mux.lisp"
               '(fnn-mux-loop fnn-mux-conn +fnn-mux-cold-poll-ms+ fnn-mux-service
                 fnn-mux-render-next fnn-mux-plan-cold fnn-mux-queue-plan
                 fnn-mux-flush fnn-mux-cold-check))
(let ((loop (%make-fnn-mux-loop :service :service))
      (conn (%make-fnn-mux-conn :cid 7)))
  ;; Warm consumes precisely one semantic attempt.
  (multiple-value-bind (plan read) (fnn-owner-cursor-step :service 7 :original :reader)
    (assert (eq plan :advanced)) (assert (null read)) (assert (= *calls* 1)))
  ;; Cold returns untouched plan and issued physical read, without rendering.
  (setf *cold* t *calls* 0)
  (multiple-value-bind (octets plan done yield read)
      (fnn-owner-render-next-quantum :service 7 :original :reader)
    (assert (= (length octets) 0)) (assert (eq plan :original))
    (assert (null done)) (assert (null yield)) (assert (eq read *read*))
    (assert (= *calls* 1)) (assert (= *render-calls* 1)))
  ;; Queue suspension retains input, original plan and whole-response action.
  (setf (fnn-mux-conn-input conn) :incoming)
  (fnn-mux-queue-plan loop conn :original :whole-response-after)
  (assert (eq (fnn-mux-conn-plan conn) :original))
  (assert (eq (first (fnn-mux-conn-cold conn)) *read*))
  (assert (eq (fourth (fnn-mux-conn-cold conn)) :cursor))
  (assert (eq (fnn-mux-conn-after conn) :whole-response-after))
  (assert (eq (fnn-mux-conn-input conn) :incoming))
  (assert (null *queued*)) (assert (null *after-called*))
  (assert (> (fnn-mux-conn-resume-at conn) (fnn-now)))
  ;; Pending returns to poll without advancing input, output or continuation.
  (setf *poll-word* '(:wait 20)) (fnn-mux-cold-check loop conn)
  (assert (fnn-mux-conn-cold conn)) (assert (null *worked*))
  (assert (eq (fnn-mux-conn-plan conn) :original)) (assert (null *queued*))
  ;; Cache churn may miss again: retain the first dependency deadline.
  (setf *poll-word* :serve *clock* 1000 *read* (list :issued-again))
  (fnn-mux-cold-check loop conn)
  (assert (= (second *poll-args*) 100))
  (assert (= (second (fnn-mux-conn-cold conn)) 100))
  (assert (= (third (fnn-mux-conn-cold conn)) 1000))
  (assert (eq (first (fnn-mux-conn-cold conn)) *read*))
  (assert (null *worked*)) (assert (null *queued*))
  ;; Returned read resumes exactly the held plan, never the input step.
  (setf *cold* nil) (fnn-mux-cold-check loop conn)
  (assert (null (fnn-mux-conn-cold conn))) (assert (null *worked*))
  (assert (equalp *queued* '((#(65 13 10) :send-reply :whole-response-after))))
  (assert (null *after-called*))
  ;; A new response resets its dependency clock. Refusal adds no body line.
  (setf *queued* nil *cold* t *clock* 2000)
  (fnn-mux-queue-plan loop conn :original :next-response)
  (assert (= (second (fnn-mux-conn-cold conn)) 2000))
  (dolist (word '(:unavailable :read-resources-unavailable))
    (setf *poll-word* word)
    (assert (handler-case (progn (fnn-mux-cold-check loop conn) nil)
              (fnn-store-io-refusal () t)))
    (assert (null *queued*)) (assert (null *after-called*))
    (when (eq word :unavailable)
      (fnn-mux-plan-cold loop conn :original :next-response *read*)))
  ;; Existing line continuation remains READ-first and resumes its input.
  (setf *poll-word* :serve *worked* nil
        (fnn-mux-conn-cold conn) (list *read* nil 3000))
  (fnn-mux-cold-check loop conn)
  (assert *worked*) (assert (eq (first (fnn-mux-conn-cold-word conn)) :serve)))
;; Legacy logical feed consumes the same fifth value on its private worker.
(let ((*private-logical* t) (*cold* t))
  (multiple-value-bind (reply closing uncertain)
      (fnn-owner-feed-logical :service 7 #(1) :reader "fixture")
    (assert (equalp reply #(65 13 10)))
    (assert (null closing)) (assert (null uncertain))
    (assert (= *private-awaits* 1)) (assert (= *private-unpins* 1))))
(format t "CURSOR-COLD-POLL actual native bodies: warm/suspend/wait/retry/resume/refuse/line PASS~%")
