;;; Use the existing warm source owner. Destination methods affirmatively
;;; reject trace I/O under the collector lock; no timing race or sleeps.
(in-package "ACL2")

(defclass fntrs-lock-free-stream (sb-gray:fundamental-character-output-stream)
  ((lock :initarg :lock :reader fntrs-lock)
   (writes :initform 0 :accessor fntrs-writes)))
(defmethod sb-gray:stream-write-char ((stream fntrs-lock-free-stream) char)
  (assert (not (sb-thread:holding-mutex-p (fntrs-lock stream))))
  (incf (fntrs-writes stream))
  char)
(defmethod sb-gray:stream-write-string ((stream fntrs-lock-free-stream) string
                                       &optional (start 0) end)
  (assert (not (sb-thread:holding-mutex-p (fntrs-lock stream))))
  (incf (fntrs-writes stream) (- (or end (length string)) start))
  string)

(defun fntrs-run ()
  (let ((*fnn-trace-state* nil) (*fnn-trace-parent* nil)
        (*fnn-trace-parent-state* nil)
        (*fnn-trace-operation* nil) (*fnn-trace-connection-generation* nil))
    (fnn-trace-start :capacity 4)
    (fnn-trace-span (:finished) :ok)
    (let ((out (make-instance 'fntrs-lock-free-stream
                             :lock (fnn-trace-state-lock *fnn-trace-state*))))
      (fnn-trace-report out)
      (fnn-trace-hotspots out)
      (assert (plusp (fntrs-writes out))))
    (fnn-trace-span (:still-active)
      (multiple-value-bind (rows attempts recorded dropped incomplete every)
          (fnn-trace-snapshot *fnn-trace-state*)
        (assert (and (= attempts 2) (= recorded 2) (= dropped 0)
                     (= incomplete 1) (= every 1)))
        (assert (eq (aref rows 0) (aref (fnn-trace-state-rows *fnn-trace-state*) 0)))
        (assert (null (aref rows 1)))
        (assert (not (eq rows (fnn-trace-state-rows *fnn-trace-state*))))
        (let ((text (with-output-to-string (s) (fnn-trace-report s))))
          (assert (search "\"recorded\":2" text))
          (assert (search "\"incomplete\":1" text))
          (assert (not (search "\"phase\":\"still-active\"" text))))
        (assert (= (fnn-trace-state-next *fnn-trace-state*) 2))))
    (format t "NATIVE_TRACE_SNAPSHOT_PASS~%")
    :passed))
