;;; Test the actual driver's I/O and refusal propagation with stubbed ACL2
;;; results. This fixture claims no codec or whole-open refinement theorem.
(require :sb-posix)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(defmacro fnn-posix (args &body body) (declare (ignore args)) `(progn ,@body))
(defun fnn-write-range (fd data start end)
  (loop for i from start below end do
    (let ((one (make-array 1 :element-type '(unsigned-byte 8) :initial-element (aref data i))))
      (sb-sys:with-pinned-objects (one)
        (assert (= 1 (sb-posix:write fd (sb-sys:vector-sap one) 1)))))))
(defvar *calls* nil)
(defvar *io* nil)
(defvar *fail-barrier* nil)
(defun fnn-durable-barrier (fd)
  (push (list :barrier fd) *io*)
  (when (eql fd *fail-barrier*) (error 'fnn-os-error)))
(defvar *directory-refusal* nil)
(defvar *page-refusal* nil)
(define-condition fnn-os-error (error) ())
(defun fnn-indeterminate (control &rest args)
  (declare (ignore control args))
  (error "indeterminate"))
(defvar *expected-slot* 512)
(defvar *commit-plan* '(:plan record (11) (0) (12) 13 1 allocation digests table-digests))
(defun fnn-call (name &rest args)
  (push name *calls*)
  (case name
    (fn-cpl-x-write-frame
     (let ((buffer (fourth args)))
       (assert (equal (subseq args 0 3) '(0 2 69)))
       (setf (svref buffer 0) (make-array 6 :element-type '(unsigned-byte 8)
                                         :initial-contents '(40 41 9 8 7 6))
             (svref buffer 1) 6)
       (list '(106 2) 'trailer buffer)))
    (pgs-x-commit
     (assert (eql (fifth args) *expected-slot*))
     (list *commit-plan* 'mem 'octets))
    (fn-hrs-open-pgs (list *directory-refusal* 'mem 'octets))
    (pgs-x-open-page (list *page-refusal* 'mem 'octets))
    (fn-pck-x-open '(:ok rows roots reads arena octets f 69 42 context tail))
    (otherwise (error "unexpected call ~s" name))))
(defun fnn-core (name &rest args)
  (push name *calls*)
  (case name
    (pgs-x-commit-slot (if (eql (first args) 1) 0 512))
    (pgs-x-commit-durable (push :durable *io*) 'mem)
    (pgs-rec-npages 1)
    (pgs-rec-txid 42)
    (pgs-x-open-pages '((0 12)))
    (fn-pgs-fill-frame (assert (equal (subseq args 0 4) '(page-file 12 0 0))) 'mem)
    (pgs-x-words-load
     (let ((buffer (sixth args)))
       (assert (zerop (svref buffer 1)))
       (setf (svref buffer 0) (make-array 3 :element-type '(unsigned-byte 8)
                                         :initial-contents '(1 2 3))
             (svref buffer 1) 3)))
    (otherwise (error "unexpected core ~s" name))))
(load "host/native/checkpoint-pages.lisp")

(defun open-capture ()
  (setf *calls* nil)
  (multiple-value-list
   (fnn-pck-open-resident-capture 'page-file 'record 'payload-file 'mem 'page-octets 'arena 'octets)))
(assert (equal (open-capture) '(nil (:ok rows roots reads arena octets f 69 42 context tail))))
(assert (equal (reverse *calls*) '(fn-hrs-open-pgs pgs-rec-npages pgs-rec-txid pgs-x-open-pages
                                  fn-pgs-fill-frame pgs-x-open-page pgs-rec-npages fn-pck-x-open)))
(setf *directory-refusal* '(:dir-damaged))
(assert (equal (open-capture) '((:dir-damaged) nil)))
(assert (equal *calls* '(fn-hrs-open-pgs)))
(setf *directory-refusal* nil *page-refusal* '(:page-damaged 0 12))
(assert (equal (open-capture) '((:page-damaged 0 12) nil)))
(assert (not (member 'fn-pck-x-open *calls*)))

;; A torn tail has physical EOF 512. The actual driver must overwrite at
;; committed PLEN 69 and drain only ACL2's appended frame, not its source.
(let* ((path "build/s-pck-driver-witness.dat")
       (fd (sb-posix:open path (logior sb-posix:o-creat sb-posix:o-excl sb-posix:o-rdwr) #o600))
       (buffer (vector (make-array 2 :element-type '(unsigned-byte 8) :initial-contents '(40 41)) 2)))
  (unwind-protect
       (progn
         (sb-posix:ftruncate fd 512)
         (assert (equal (multiple-value-list (fnn-pck-write-payload-frame fd 69 0 2 buffer))
                        '((106 2) trailer)))
         (assert (= (sb-posix:lseek fd 0 sb-posix:seek-cur) 73))
         (assert (= (sb-posix:stat-size (sb-posix:fstat fd)) 512))
         (let ((readback (make-array 4 :element-type '(unsigned-byte 8))))
           (sb-posix:lseek fd 69 sb-posix:seek-set)
           (sb-sys:with-pinned-objects (readback)
             (assert (= 4 (sb-posix:read fd (sb-sys:vector-sap readback) 4))))
           (assert (equalp readback #(9 8 7 6))))
         (fnn-pck-write-words fd 10 0 0 3 'mem buffer)
         (assert (= (sb-posix:lseek fd 0 sb-posix:seek-cur) 13)))
    (sb-posix:close fd)
    (delete-file path)))
;; Exercise the actual commit driver with planned geometry, recording only
;; writes and barriers. A payload barrier failure must prevent the record;
;; a page barrier failure must prevent durable marking and require recovery.
(let ((writer (fdefinition 'fnn-pck-write-words)))
  (unwind-protect
       (progn
         (setf (fdefinition 'fnn-pck-write-words)
               (lambda (fd offset sel base count mem octets)
                 (declare (ignore mem octets))
                 (push (list :write fd offset sel base count) *io*)))
         (setf *io* nil)
         (fnn-pck-commit-pages 10 20 '(8) 9 2 '(nil 11) 0 'mem 'octets)
         (assert (equal (reverse *io*)
                        '((:write 10 180224 0 16384 2048)
                          (:write 10 196608 2 0 2048)
                          (:write 10 212992 1 1024 2048)
                          (:barrier 20) (:write 10 4096 1 512 20)
                          (:barrier 10) :durable)))
         ;; Both adopted-slot values are passed unchanged to ACL2's selector.
         (setf *io* nil *expected-slot* 0)
         (fnn-pck-commit-pages 10 20 '(8) 9 2 '(nil 11) 1 'mem 'octets)
         (assert (member '(:write 10 0 1 0 20) *io* :test #'equal))
         (assert (not (member '(:write 10 4096 1 512 20) *io* :test #'equal)))
         (setf *expected-slot* 512)
         (dolist (fd '(20 10))
           (setf *io* nil *fail-barrier* fd)
           (assert (handler-case
                       (progn (fnn-pck-commit-pages 10 20 '(8) 9 2 '(nil 11) 0 'mem 'octets) nil)
                     (error (e) (search "indeterminate" (princ-to-string e)))))
           (assert (not (member :durable *io*)))
           (when (= fd 20)
             (assert (not (member '(:write 10 4096 1 512 20) *io* :test #'equal)))))
         (setf *io* nil *fail-barrier* nil *commit-plan* '(:refused :allocation))
         (assert (equal (fnn-pck-commit-pages 10 20 '(8) 9 2 '(nil 11) 0 'mem 'octets)
                        '(:refused :allocation)))
         (assert (null *io*)))
    (setf (fdefinition 'fnn-pck-write-words) writer)))
(format t "native_checkpoint_pages_raw-mock passed (resident order, refusal propagation, PLEN overwrite, payload-before-record barrier, recovery on I/O failure)~%")
