(load "tests/native_web_article_stream_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-extent-window-cancel (worker token)
  (declare (ignorable worker token))
  (harness-stub-reached 'fnn-extent-window-cancel "host/native/extent.lisp"))
(defun fnn-owner-cold-window-result-locked (service read)
  (declare (ignorable service read))
  (harness-stub-reached 'fnn-owner-cold-window-result-locked "host/native/owner.lisp"))
;;; ---- derived stubs: END ----
(load-page-forms "books/octet-text.lisp"
 '(fn-ot-radixp fn-ot-hex-digit fn-ot-nat-digits fn-ot-nat-octets fn-ot-decimal-octets))
(load-page-forms "books/web-session.lisp"
 '(*fn-wss-window* *fn-wss-msg-unreachable* fn-wss-f-stage fn-wss-split-loop fn-wss-split fn-wss-over-rows))
(load-page-forms "books/web-render.lisp"
 '(fn-wr-over-row-segments fn-wr-over-rows-loop fn-wr-over-rows fn-wr-group-main-segments fn-wr-group-main))
(load-page-forms "books/web-reply-stream.lisp")
(load-page-forms "host/web-host.lisp"
 '(fn-web-host-stream-p fn-web-host-stream-start fn-web-host-stream-scan fn-web-host-stream-page))
(let* ((login (fn-wrq-oct "wren")) (session (list nil nil login (fn-wrq-oct "csrf")))
       (ctx (append (list (list :request :get)) (make-list 8) (list session :auto)))
       (group (fn-wrq-oct "fn.test")) (flow (list :group :over ctx (list group 20 1)))
       (config (list :web-config (fn-wrq-oct "fn") nil nil 600 16))
       (prefix (article-octets '("224 Overview follows")))
       (rows (loop for n from 20 below 120 append
                  (append (fn-wrq-oct (format nil "~d" n)) '(9)
                          (if (= n 75) (make-list 10003 :initial-element 38)
                            (fn-wrq-oct "=?UTF-8?Q?caf=C3=A9?=")) '(9)
                          (fn-wrq-oct "Wren <wren@fn>") '(9) (fn-wrq-oct "today")
                          '(9) (fn-wrq-oct "<m@fn>") '(9 9 13 10))))
       (xs (append prefix rows '(46 13 10))) (in (create-fn-octets$c)))
  (fnn-web-fill in (fnn-octets xs))
  (let* ((ref-rows (fn-wss-over-rows (length prefix) (- (length xs) 3) nil in))
         (reference (fn-wr-seq (fn-wr-frame group (fn-wrq-oct "fn") :auto login
                                 (fn-wss-s-csrf session)
                                 (fn-wr-group-main group ref-rows (fn-ot-decimal-octets 20))) xs)))
    (native-stream-consumer xs flow config reference 42 1200)
    (dolist (width '(1 2 7 4096))
      (let ((scan (fn-wrs-start flow)) (window (create-fn-octets$c)))
        (loop for at from 0 below (length xs) by width do
          (fnn-web-fill window (fnn-octets (subseq xs at (min (length xs) (+ at width)))))
          (setf scan (fn-wrs-scan scan window)))
        (assert (eq (fn-was-get :phase scan) :done))
        (assert (= (length (fn-was-get :rows scan)) 100))
        (let ((action (fn-wrs-page config flow scan)))
          (multiple-value-bind (actual count) (virtual-page (sixth action) xs 4096)
            (assert (equal actual reference)) (assert (= count (length reference))))))))
  ;; An impossible generated reply cannot admit row101 or silently truncate.
  (let* ((scan (fn-wov-start))
         (xs (append prefix (loop repeat 101 append (article-octets '("1"))) '(46 13 10))))
    (fnn-web-fill in (fnn-octets xs))
    (setf scan (fn-wrs-scan scan in))
    (assert (eq (fn-was-get :phase scan) :invalid))
    (assert (= (length (fn-was-get :rows scan)) 100))
    (assert (equal (fn-wrs-page config flow scan) '(:invalid))))
  (assert (fn-web-host-stream-p flow))
  (assert (not (fn-web-host-stream-p (list :group :group ctx (list group)))))
  (assert (fn-web-host-stream-p (list :article :article ctx (list group)))))
(format t "NATIVE WEB OVER STREAM RAW PASS: exact100-row reference/newest-first/long field; bounded metadata; overflow fails~%")
