;;; Actual private operation constructor, source continuation and TCPCL ACK
;;; consumer. Typed grant/I/O/durable callback are recorded; no image claim.
(load "tests/native_bp_session_bank_raw.lisp")
(in-package "ACL2")
(defvar *fnn-tcl-source-turn* nil)
(defvar *fnn-tcl-deliver* nil)
(defvar *fnn-tcl-deliver-counted* nil)
(defmacro mv (&rest xs) `(values ,@xs))
(defmacro mv-let (names expression &body body) `(multiple-value-bind ,names ,expression ,@body))
(defun fn-cbor-octetp (x) (and (integerp x) (<= 0 x 255)))
(defun fnn-make-octets (n) (make-array n :element-type '(unsigned-byte 8) :initial-element 0))
(dolist (path '("books/tcpcl-segment-source-cursor.lisp" "books/bp-session-received-source.lisp"))
 (with-open-file (stream path)
  (loop for form = (read stream nil :eof) until (eq form :eof) do
   (when (and (consp form) (eq (first form) 'defun))
    (eval (cons 'defun (cons (second form) (cons (third form)
     (remove-if (lambda (x) (and (consp x) (eq (car x) 'declare))) (cdddr form))))))))))
(define-condition fnn-store-indeterminate (error) ((message :initarg :message)))
(with-open-file (stream "host/native/tcpcl.lisp")
 (loop for form = (read stream nil :eof) until (eq form :eof) do
  (when (and (consp form)
   (or (and (eq (first form) 'define-condition) (eq (second form) 'fnn-tcl-source-indeterminate))
       (and (eq (first form) 'defun) (member (second form)
        '(fnn-tcl-source-escape fnn-tcl-source-disposition fnn-tcl-source-tick fnn-tcl-act
          fnn-tcl-settle-delivery fnn-tcl-deliver-transfer))))) (eval form))))
(defvar *flushes* 0)
(defvar *publications* 0)
(defun fnn-tcl-flush (conn) (declare (ignore conn)) (incf *flushes*))
(defun fnn-core (name &rest args)
 (case name
  ((fn-bpsrx-start fn-bpsrx-turn fn-bpsrx-authorizedp fn-tsc-at fn-bpsg-step fn-bpsg-release-ready) (apply name args))
  (fn-tcl-source-result-action (if (eq (caar args) :source-yield) :retain :settle))
  (fn-tcl-source-result-token (cadar args))
  (fn-tcl-delivery-plan (third args))
  (fn-tcl-delivery-plan-status (caar args))
  (fn-tcl-delivery-plan-messages nil)
  (fn-tcl-delivery-plan-progress-p t)
  (fn-tcl-delivery-plan-detail nil)
  (otherwise (error "Unexpected received core ~s" name))))
(defun source-case (cut)
 (let* ((bank (test-bank)) (conn (make-fnn-tcl-conn))
        (grant (test-grant bank 2 :incoming :socket conn))
        (root (list (loop for i from 500 below 1000 collect (mod i 256)) nil
                    (loop for i below 500 collect (mod i 256))))
        (*flushes* 0) (*publications* 0) (turns 0) (failed nil)
        (*fnn-tcl-source-start* (lambda (c id chain count)
          (fnn-bp-session-source-start grant c id chain count 1000)))
        (*fnn-tcl-source-turn* (lambda (c token) (fnn-bp-session-source-turn grant c token)))
        (*fnn-tcl-deliver* (lambda (c id bytes)
          (declare (ignore c)) (assert (= id 7)) (assert (zerop *flushes*))
          (incf *publications*)
          (assert (equal bytes (loop for i below 1000 collect (mod i 256))))
          (when (eq cut :publication) (error "recording durable publication cut"))
          '(:accepted nil))))
  (fnn-tcl-act conn (list '(:send (:xfer-ack 3 7 1000))
                          (list :bundle-segments-received 7 root 1000)))
  (assert (fnn-tclc-source-pending conn)) (assert (zerop *publications*))
  (loop repeat 100 while (fnn-tclc-source-pending conn) until failed do
   (incf turns)
   (when (and (eq cut :generation) (= turns 2))
    (setf (fnn-bpsg-row grant) (fn-bpsg-row 2 2 :incoming)))
   (let ((before (fnn-bpsrx-offset (fnn-tclc-source-token conn))))
    (handler-case (fnn-tcl-source-tick conn) (fnn-tcl-source-indeterminate () (setf failed t)))
    (when (fnn-tclc-source-token conn)
     (assert (<= (- (fnn-bpsrx-offset (fnn-tclc-source-token conn)) before) 64)))))
  (if cut
   (progn
    (assert failed) (assert (fnn-tclc-fenced conn))
    (assert (eq (fnn-tclc-source-root conn) root)) (assert (fnn-tclc-source-token conn))
    (assert (zerop *flushes*))
    (assert (= *publications* (if (eq cut :publication) 1 0)))
    (let ((before *publications*))
     (assert (handler-case (progn (fnn-tcl-source-tick conn) nil) (fnn-tcl-source-indeterminate () t)))
     (assert (= *publications* before))))
   (progn
    (assert (> turns 16)) (assert (= *publications* 1)) (assert (= *flushes* 1))
    (assert (= (fnn-tclc-accepted conn) 1)) (assert (null (fnn-tclc-source-root conn)))))))
(source-case nil)
(source-case :generation)
(source-case :publication)
(format t "PASS actual incoming grant -> bounded received source -> one durable callback/END ACK; stale generation and publication cut retain/fence exact borrow.~%")
