;;; SCN1134: actual BP startup helpers and actual listener entry callers.
;;; Physical constructors are recorded; no full tariff/native image claim.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-accept-loop (listener handler &optional once)
  (declare (ignorable listener handler once))
  (harness-stub-reached 'fnn-accept-loop "host/native/io.lisp"))
(defun fnn-app-journal-close (journal)
  (declare (ignorable journal))
  (harness-stub-reached 'fnn-app-journal-close "host/native/workflow.lisp"))
(defun fnn-bp-eid (text)
  (declare (ignorable text))
  (harness-stub-reached 'fnn-bp-eid "host/native/bp.lisp"))
(defun fnn-bp-evidence-open (tally)
  (declare (ignorable tally))
  (harness-stub-reached 'fnn-bp-evidence-open "host/native/bp.lisp"))
(defun fnn-bp-exit-code (tally conn)
  (declare (ignorable tally conn))
  (harness-stub-reached 'fnn-bp-exit-code "host/native/bp.lisp"))
(defun fnn-bp-note (tally word)
  (declare (ignorable tally word))
  (harness-stub-reached 'fnn-bp-note "host/native/bp.lisp"))
(defun fnn-bp-observation (wall wall-error)
  (declare (ignorable wall wall-error))
  (harness-stub-reached 'fnn-bp-observation "host/native/bp.lisp"))
(defun fnn-bp-run-evidence (tally)
  (declare (ignorable tally))
  (harness-stub-reached 'fnn-bp-run-evidence "host/native/bp.lisp"))
(defun fnn-bp-session-abort-all (bank &optional signal-condition)
  (declare (ignorable bank signal-condition))
  (harness-stub-reached 'fnn-bp-session-abort-all "host/native/bp-session.lisp"))
(defun fnn-bp-session-install (bp owner transfer segment)
  (declare (ignorable bp owner transfer segment))
  (harness-stub-reached 'fnn-bp-session-install "host/native/bp-session.lisp"))
(defun fnn-bp-session-loop (bank control listeners begin once service pending)
  (declare (ignorable bank control listeners begin once service pending))
  (harness-stub-reached 'fnn-bp-session-loop "host/native/bp-session.lisp"))
(defun fnn-bp-summary (tally)
  (declare (ignorable tally))
  (harness-stub-reached 'fnn-bp-summary "host/native/bp.lisp"))
(defun fnn-bpapp-deliver (service journal tally node-id conn xfer-id wire ingress-state session-counter channel)
  (declare (ignorable service journal tally node-id conn xfer-id wire ingress-state session-counter channel))
  (harness-stub-reached 'fnn-bpapp-deliver "host/native/bp-app.lisp"))
(defun fnn-bpapp-open-journal (service receipt-root destination policy issuer)
  (declare (ignorable service receipt-root destination policy issuer))
  (harness-stub-reached 'fnn-bpapp-open-journal "host/native/bp-app.lisp"))
(defun fnn-bpc-advance-clock (service obs)
  (declare (ignorable service obs))
  (harness-stub-reached 'fnn-bpc-advance-clock "host/native/bp-contact.lisp"))
(defun fnn-bplc-close-all (node)
  (declare (ignorable node))
  (harness-stub-reached 'fnn-bplc-close-all "host/native/bp-listener-control.lisp"))
(defun fnn-bplc-start (mode)
  (declare (ignorable mode))
  (harness-stub-reached 'fnn-bplc-start "host/native/bp-listener-control.lisp"))
(defun fnn-bpnc-pump (node &optional timeout-ms)
  (declare (ignorable node timeout-ms))
  (harness-stub-reached 'fnn-bpnc-pump "host/native/bp-control.lisp"))
(defun fnn-bpnc-retire (node)
  (declare (ignorable node))
  (harness-stub-reached 'fnn-bpnc-retire "host/native/bp-control.lisp"))
(defun fnn-bpnc-start (config-path store-root owner)
  (declare (ignorable config-path store-root owner))
  (harness-stub-reached 'fnn-bpnc-start "host/native/bp-control.lisp"))
(defun fnn-bpnode-delete-expired (bp reports-enabled)
  (declare (ignorable bp reports-enabled))
  (harness-stub-reached 'fnn-bpnode-delete-expired "host/native/bp-node.lisp"))
(defun fnn-bpnode-dispatch-one (bp owner receipt-root workflow-root destination policy issuer node-id configured-peer)
  (declare (ignorable bp owner receipt-root workflow-root destination policy issuer node-id configured-peer))
  (harness-stub-reached 'fnn-bpnode-dispatch-one "host/native/bp-node.lisp"))
(defun fnn-bpnode-dispatch-pending (bp owner receipt-root workflow-root destination policy issuer node-id configured-peer)
  (declare (ignorable bp owner receipt-root workflow-root destination policy issuer node-id configured-peer))
  (harness-stub-reached 'fnn-bpnode-dispatch-pending "host/native/bp-node.lisp"))
(defun fnn-bpnode-expire-turn (bp reports-enabled)
  (declare (ignorable bp reports-enabled))
  (harness-stub-reached 'fnn-bpnode-expire-turn "host/native/bp-node.lisp"))
(defun fnn-bpnode-forward-contact (bp node-id peer-id transfer-mru wall wall-error)
  (declare (ignorable bp node-id peer-id transfer-mru wall wall-error))
  (harness-stub-reached 'fnn-bpnode-forward-contact "host/native/bp-node.lisp"))
(defun fnn-bpnode-forward-start (bank bp node-id transfer-mru wall wall-error entry table)
  (declare (ignorable bank bp node-id transfer-mru wall wall-error entry table))
  (harness-stub-reached 'fnn-bpnode-forward-start "host/native/bp-node.lisp"))
(defun fnn-bpnode-observe-reports (bp node-id)
  (declare (ignorable bp node-id))
  (harness-stub-reached 'fnn-bpnode-observe-reports "host/native/bp-node.lisp"))
(defun fnn-bpnode-observed-channel (socket)
  (declare (ignorable socket))
  (harness-stub-reached 'fnn-bpnode-observed-channel "host/native/bp-node.lisp"))
(defun fnn-bpnode-passive-begin (bp grant socket owner receipt-root workflow-root destination policy issuer node-id peer-id transfer-mru wall wall-error finish)
  (declare (ignorable bp grant socket owner receipt-root workflow-root destination policy issuer node-id peer-id transfer-mru wall wall-error finish))
  (harness-stub-reached 'fnn-bpnode-passive-begin "host/native/bp-node.lisp"))
(defun fnn-bpnode-queue-outbox (bp owner receipt-root destination policy issuer node-id peer-id view contact-host contact-port transfer-mru wall wall-error)
  (declare (ignorable bp owner receipt-root destination policy issuer node-id peer-id view contact-host contact-port transfer-mru wall wall-error))
  (harness-stub-reached 'fnn-bpnode-queue-outbox "host/native/bp-node.lisp"))
(defun fnn-bpnode-queue-outboxes (bp owner receipt-root destination policy issuer node-id peer-id contact-host contact-port transfer-mru wall wall-error)
  (declare (ignorable bp owner receipt-root destination policy issuer node-id peer-id contact-host contact-port transfer-mru wall wall-error))
  (harness-stub-reached 'fnn-bpnode-queue-outboxes "host/native/bp-node.lisp"))
(defun fnn-bpnode-queue-report (bp peer-id node-id view contact-host contact-port transfer-mru wall wall-error)
  (declare (ignorable bp peer-id node-id view contact-host contact-port transfer-mru wall wall-error))
  (harness-stub-reached 'fnn-bpnode-queue-report "host/native/bp-node.lisp"))
(defun fnn-bpnode-queue-reports (bp peer-id node-id contact-host contact-port transfer-mru wall wall-error)
  (declare (ignorable bp peer-id node-id contact-host contact-port transfer-mru wall wall-error))
  (harness-stub-reached 'fnn-bpnode-queue-reports "host/native/bp-node.lisp"))
(defun fnn-bpnode-receipt-turn (bank bp peer-id contact once)
  (declare (ignorable bank bp peer-id contact once))
  (harness-stub-reached 'fnn-bpnode-receipt-turn "host/native/bp-node.lisp"))
(defun fnn-bpnode-route-by-owner (bp)
  (declare (ignorable bp))
  (harness-stub-reached 'fnn-bpnode-route-by-owner "host/native/bp-node.lisp"))
(defun fnn-bpnode-send-receipts (bp peer-id)
  (declare (ignorable bp peer-id))
  (harness-stub-reached 'fnn-bpnode-send-receipts "host/native/bp-node.lisp"))
(defun fnn-bps-fragment-progress (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-bps-fragment-progress "host/native/bp-service.lisp"))
(defun fnn-bps-fragment-work-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-bps-fragment-work-p "host/native/bp-service.lisp"))
(defun fnn-bps-outcome (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-bps-outcome "host/native/bp-service.lisp"))
(defun fnn-bps-serve-rotate-when-due (bp journal config wall wall-error)
  (declare (ignorable bp journal config wall wall-error))
  (harness-stub-reached 'fnn-bps-serve-rotate-when-due "host/native/bp-node.lisp"))
(defun fnn-out (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-out "host/native/io.lisp"))
(defun fnn-owner-action (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-owner-action "host/native/owner.lisp"))
(defun fnn-owner-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-owner-core "host/native/owner.lisp"))
(defun fnn-owner-feed-close-all (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-feed-close-all "host/native/owner.lisp"))
(defun fnn-socket-fd (socket)
  (declare (ignorable socket))
  (harness-stub-reached 'fnn-socket-fd "host/native/io.lisp"))
(defun fnn-socket-shut (socket)
  (declare (ignorable socket))
  (harness-stub-reached 'fnn-socket-shut "host/native/io.lisp"))
(defun fnn-tcl-listen (port)
  (declare (ignorable port))
  (harness-stub-reached 'fnn-tcl-listen "host/native/tcpcl.lisp"))
(defun fnn-tcl-params (node-id peer keepalive segment-mru transfer-mru)
  (declare (ignorable node-id peer keepalive segment-mru transfer-mru))
  (harness-stub-reached 'fnn-tcl-params "host/native/tcpcl.lisp"))
(defun fnn-tcl-session (fd role params tag spool &key bundle trace expect on-ready refuse-inbound)
  (declare (ignorable fd role params tag spool bundle trace expect on-ready refuse-inbound))
  (harness-stub-reached 'fnn-tcl-session "host/native/tcpcl.lisp"))
;;; ---- derived stubs: END ----
(declaim (declaration xargs))
(defun source-forms (path names)
 (with-open-file (in (if (equal path "host/native/bp-service.lisp")
                          (or (sb-ext:posix-getenv "FN_BP_STARTUP_SOURCE") path) path))
  (loop for form = (read in nil :eof) until (eq form :eof)
   when (and (consp form) (member (car form) '(defun defstruct))
             (member (if (consp (second form)) (car (second form)) (second form)) names))
   do (progn (eval form)
             (setf names (remove (if (consp (second form)) (car (second form)) (second form)) names)))
   finally (assert (null names)))))
(source-forms "books/owner-retire-settlement.lisp"
 '(fn-ort-store-close-action fn-ort-service-settlement-action fn-ort-service-claim-action fn-ort-service-start-reason))
(defvar *fnn-owner-caller-reservation* nil)
(defvar *fnn-owner-retained-service* nil)
(defvar *fnn-owner-retained-settlement* :held)
(defvar *fnn-owner-reserving-thread* nil)
(defvar *fnn-log-queue-mutex* (sb-thread:make-mutex))
(defvar *fnn-log-writer* nil)
(defvar *fnn-owner-log-fd* nil)
(defstruct fnn-owner-service store peer-flight-bank close-hooks snapshot-jobs)
(defmacro fnn-with-roster ((service) &body body)
 (declare (ignore service)) `(progn ,@body))
(defstruct fnn-store fenced)
(define-condition fixture-stop (error) ())
(defvar *mode* nil)
(defvar *events* nil)
(defvar *pool* nil)
(defvar *workers* nil)
(defvar *store* nil)
(defun fnn-core (name &rest args)
 (case name
  (fn-bpsp-root-release-ready (zerop (first args)))
  (fn-pfr-startup-grant (list :hold (third args)))
  (create-fn-resource-ledger
   (case *mode*
    (:peer-create-error (error 'fixture-stop))
    (:peer-create-throw (throw 'peer-cut :escaped)))
   :peer-ledger)
  (fn-csp-bank-idle-p (not (eq *mode* :peer-ledger-debt)))
  (otherwise (apply name args))))
(defun fnn-call (name &rest args)
 (assert (eq name 'fn-pfr-install-funded))
 (assert (equal (butlast args) '(1000 100 :peer-policy 8192 1024)))
 (assert (eq (car (last args)) :peer-ledger))
 (list (if (eq *mode* :peer-install-error) :refused :installed) :peer-ledger))
(defun fnn-fault (&rest args) (declare (ignore args)) (error 'fixture-stop))
(defun fnn-extent-executor-drained-p ()
 (and (not *workers*) (not (eq *mode* :executor-debt))))
(defun fnn-absolute (path) (assert (equal path "/store")) path)
(defun fnn-indeterminate (&rest args) (declare (ignore args)) (error 'fixture-stop))
(defun fnn-owner-page-read-startup (root connections cold output retain)
 (assert (equal root "/store")) (assert (member connections '(1 2)))
 (assert (null cold)) (assert (null output))
 (assert *fnn-owner-retained-service*)
 (push :preflight *events*)
 (when (eq *mode* :refused) (error 'fixture-stop))
 (setf *pool* t)
 (funcall retain)
 (push :pool-retained *events*)
 (when (member *mode* '(:constructor-error :constructor-arena-debt)) (error 'fixture-stop))
 (setf *workers* t)
 (push :workers *events*)
 (values :plan
  (when (member *mode* '(:peer-ok :peer-create-error :peer-create-throw
                        :peer-install-error :peer-ledger-debt :peer-lease-debt))
   '(1000 100 :peer-policy 8192 1024))))
(defun fnn-owner-install (root connections)
 (declare (ignore root connections))
 (assert (and *pool* *workers*))
 (push :store-open *events*)
 (let ((service (make-fnn-owner-service :store *store*)))
  (when (member *mode* '(:recovery-error :join-error))
   (fnn-owner-retain-run-authority service)
   (error 'fixture-stop))
  service))
(defun fnn-extent-end-recovery-cache () (push :recovery-end *events*))
(defun fnn-extent-executor-stop ()
 (push :executor-join *events*)
 (when (eq *mode* :join-error) (error 'fixture-stop))
 (setf *workers* nil))
(defun fnn-arena-return-observation (log)
 (assert (null log))
 (if (member *mode* '(:arena-debt :constructor-arena-debt)) :uncertain :closed))
(defun fnn-owner-cold-shutdown (service)
 (assert (eq (fnn-owner-service-store service) *store*))
 (fnn-extent-executor-stop))
(defun fnn-store-close (store)
 (assert (eq store *store*)) (assert (not *workers*))
 (push :store-close *events*)
 (when (eq *mode* :close-error) (error 'fixture-stop)))
(source-forms "host/native/catchup-spool.lisp"
 '(fnn-peer-flight-bank fnn-peer-flight-bank-install
   fnn-peer-flight-bank-drained fnn-peer-flight-bank-close))
(source-forms "host/native/owner.lisp"
 '(fnn-owner-claim-run-authority fnn-owner-retain-run-authority fnn-owner-store-settlement
   fnn-owner-peer-flight-startup fnn-owner-snapshot-jobs-drained-p))
(source-forms "host/native/bp-service.lisp"
 '(fnn-bp-served-owner-custody fnn-bp-served-owner-start
   fnn-bp-served-owner-stop fnn-bp-served-owner-settle))
(defun helper-case (mode expected held)
 (let ((*mode* mode) (*events* nil) (*pool* nil) (*workers* nil)
       (*store* (make-fnn-store)) (*fnn-owner-retained-service* nil)
       (*fnn-owner-reserving-thread* nil) (service nil)
       (custody (make-fnn-bp-served-owner-custody)))
  (handler-case (setf service (fnn-bp-served-owner-start custody "/store" 2))
   (fixture-stop () nil))
  (handler-case (fnn-bp-served-owner-stop custody service) (fixture-stop () nil))
  (handler-case (fnn-bp-served-owner-settle custody service (not (eq mode :root-debt)))
   (fixture-stop () nil))
  (assert (equal (reverse *events*) expected))
  (assert (eql (and *fnn-owner-retained-service* t) held))
  (when (eq mode :close-error) (assert (fnn-store-fenced *store*)))
  (when held
   ;; A fresh BP/owner claimant cannot overwrite retained physical authority.
   (let ((blocked nil))
    (handler-case (fnn-owner-claim-run-authority) (fixture-stop () (setq blocked t)))
    (assert blocked)))
  (format t "~a events=~s held=~s~%" mode (reverse *events*) held)))
(helper-case :normal '(:preflight :pool-retained :workers :store-open :recovery-end :executor-join :store-close) nil)
(helper-case :refused '(:preflight) nil)
(helper-case :constructor-error '(:preflight :pool-retained :executor-join) nil)
(helper-case :recovery-error '(:preflight :pool-retained :workers :store-open :executor-join :store-close) nil)
(helper-case :join-error '(:preflight :pool-retained :workers :store-open :executor-join) t)
(helper-case :close-error '(:preflight :pool-retained :workers :store-open :recovery-end :executor-join :store-close) t)
(helper-case :root-debt '(:preflight :pool-retained :workers :store-open :recovery-end :executor-join) t)
(helper-case :arena-debt '(:preflight :pool-retained :workers :store-open :recovery-end :executor-join) t)
(helper-case :constructor-arena-debt '(:preflight :pool-retained :executor-join) t)

;;; Use the actual bank constructor/close and snapshot observer under the
;;; actual BP entry helper. Core ledger calls are recorded allocation seams.
(dolist (mode '(:peer-ok :peer-create-error :peer-create-throw :peer-install-error
                :peer-ledger-debt :peer-lease-debt :snapshot-unjoined
                :snapshot-pin-debt :executor-debt))
 (let ((*mode* mode) (*events* nil) (*pool* nil) (*workers* nil)
       (*store* (make-fnn-store)) (*fnn-owner-retained-service* nil)
       (*fnn-owner-reserving-thread* nil) (service nil)
       (custody (make-fnn-bp-served-owner-custody)))
  (catch 'peer-cut
   (handler-case (setf service (fnn-bp-served-owner-start custody "/store" 2))
    (fixture-stop () nil)))
  (let* ((actual (or service *fnn-owner-retained-service*))
         (bank (fnn-owner-service-peer-flight-bank actual)))
   (assert (fnn-owner-service-p actual))
   (when (member mode '(:peer-ok :peer-create-error :peer-create-throw
                       :peer-install-error :peer-ledger-debt :peer-lease-debt))
    (assert bank)
    (assert (= (length (fnn-owner-service-close-hooks actual)) 1)))
   (when (eq mode :peer-lease-debt)
    (setf (fnn-peer-flight-bank-leases bank) '(:retained-lease)))
   (when (member mode '(:snapshot-unjoined :snapshot-pin-debt))
    (setf (fnn-owner-service-snapshot-jobs actual) (list mode)))
   (handler-case (fnn-bp-served-owner-stop custody service) (fixture-stop () nil))
   (handler-case (fnn-bp-served-owner-settle custody service t) (fixture-stop () nil))
   (assert (eql (fnn-bp-served-owner-custody-stopped custody) (eq mode :peer-ok)))
   (assert (eql (and *fnn-owner-retained-service* t) (not (eq mode :peer-ok))))
   (assert (eql (and (member :store-close *events*) t) (eq mode :peer-ok)))
   (when (eq mode :peer-ok) (assert (eq (fnn-peer-flight-bank-phase bank) :closed)))
   (format t "~a terminal-stopped=~s held=~s~%" mode
           (fnn-bp-served-owner-custody-stopped custody)
           (and *fnn-owner-retained-service* t)))))

;;; Call the production commands, not a reconstructed entry recipe. Refusal
;;; before owner return must still stop the partial pool and preserve authority
;;; on join escape. Unrelated FNBS/spool construction is recorded.
(defvar *fnn-bpnode-receipt-signer* nil)
(defvar *fnn-bpnode-budgets* nil)
(defvar *fnn-bp-session-stranded-roots* nil)
(defvar *fnn-bp-session-bank* nil)
(defvar *fnn-bpnode-control-pump* nil)
(defun fnn-bp-config (&rest args) (declare (ignore args)) :config)
(defun fnn-bps-open-node (&rest args) (declare (ignore args)) :bp)
(defun fnn-bps-release (bp) (assert (eq bp :bp)) (push :fnbs-release *events*))
(defun fnn-bpnode-read-budgets (&rest args)
 (declare (ignore args))
 (when (eq *mode* :budget-error) (error 'fixture-stop)) nil)
(defun fnn-bp-journal-dir (root) root)
(defun fnn-tcl-spool-acquire (&rest args) (declare (ignore args)) :spool)
(defun fnn-tcl-spool-release (lock) (assert (eq lock :spool)) (push :spool-release *events*))
(source-forms "host/native/bp-node.lisp" '(fnn-command-bp-node))
(source-forms "host/native/bp-app.lisp" '(fnn-command-bp-app-receive))
(dolist (command '(:node :app))
 (dolist (mode '(:constructor-error :recovery-error :join-error
                 :peer-create-error :peer-create-throw :peer-install-error))
  (let ((*mode* mode) (*events* nil) (*pool* nil) (*workers* nil)
        (*store* (make-fnn-store)) (*fnn-owner-retained-service* nil)
        (*fnn-owner-reserving-thread* nil))
   (catch 'peer-cut
    (handler-case
    (if (eq command :node)
     (fnn-command-bp-node 0 nil "/fnbs" "/store" "/receipts" "/workflow"
      "node" "peer" "dest" "policy" "issuer" "host" 4556 1000 2 16 32768 nil 0 nil)
     (fnn-command-bp-app-receive 0 nil "/spool" "/store" "/receipts"
      "node" "peer" "dest" "policy" "issuer" 1000 2 16 32768 2 nil 0))
    (fixture-stop () nil)))
   (assert (member :executor-join *events*))
   (let ((held (and (member mode '(:join-error :peer-create-error
                                 :peer-create-throw :peer-install-error)) t)))
    (assert (eql (and *fnn-owner-retained-service* t) held))
    (when held (assert (not (member :store-close *events*)))))
   (assert (member (if (eq command :node) :fnbs-release :spool-release) *events*)))))
(let ((*mode* :budget-error) (*events* nil))
 (handler-case
  (fnn-command-bp-node 0 nil "/fnbs" "/store" "/receipts" "/workflow"
   "node" "peer" "dest" "policy" "issuer" "host" 4556 1000 2 16 32768 nil 0 nil)
  (fixture-stop () nil))
 (assert (equal *events* '(:fnbs-release))))
(format t "PASS actual BP served owner pre-open and teardown custody~%")
