;;; Actual shipped retained TCPCL driver and scalar ACL2 scheduler definitions.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(defun nfix (x) (if (and (integerp x) (<= 0 x)) x 0))
(defun fn-cbor-ag-car (x) (if (consp x) (car x) nil))
(defun fn-cbor-ag-cdr (x) (if (consp x) (cdr x) nil))
(defun zp (x) (<= (nfix x) 0))
(defun member-eq (x xs) (member x xs :test #'eq))
(defconstant *fn-tcl-ext-cap* 4096)
(defun natp (x) (and (integerp x) (<= 0 x)))
(defun fnn-register-verb (&rest args) (declare (ignore args)))
(define-condition fnn-os-error (error) ())
(define-condition fnn-store-indeterminate (error) ())
(defconstant +fnn-tcl-write-timeout+ 30)
(defvar *fnn-tcl-progress* nil)
(defvar *fnn-tcl-source-start* nil)
(defun fnn-core (&rest args) (declare (ignore args)))
(dolist (path '("books/tcpcl-retained-turn.lisp" "books/tcpcl-frame-cursor.lisp" "books/tcpcl-input-materialize.lisp"))
(with-open-file (stream path)
 (loop for form = (read stream nil :eof) until (eq form :eof) do
  (when (and (consp form) (eq (first form) 'defun))
   (eval (cons 'defun (cons (second form) (cons (third form)
    (remove-if (lambda (x) (and (consp x) (eq (car x) 'declare))) (cdddr form)))))))))
)
(defun fn-octets-len (st) (svref st 1))
(defun fn-octets-get (i st) (aref (svref st 0) i))
(defun create-fn-octets$c () (vector (make-array 0 :element-type '(unsigned-byte 8)) 0))
(defun fn-octets$c-reserve (n st) (setf (svref st 0) (make-array n :element-type '(unsigned-byte 8))) st)
(with-open-file (stream "host/native/tcpcl.lisp")
 (loop for form = (read stream nil :eof) until (eq form :eof) do
  (when (and (consp form)
    (or (and (eq (first form) 'defstruct) (eq (car (second form)) 'fnn-tcl-conn))
        (and (eq (first form) 'defun)
          (member (second form) '(fnn-tcl-flush fnn-tcl-drop fnn-tcl-pump-out fnn-tcl-offer
            fnn-tcl-input-initialize fnn-tcl-input-decode fnn-tcl-input-materialize-turn fnn-tcl-input-turn fnn-tcl-physical-attempt fnn-tcl-begin fnn-tcl-turn-lost fnn-tcl-turn-local fnn-tcl-turn fnn-tcl-session)))))
   (eval form))))
(defvar *fnn-tcl-progress* nil)
(defvar *fnn-tcl-source-start* nil)
(defvar *now* 100)
(defvar *calls* nil)
(defvar *writes* nil)
(defvar *wait-write* nil)
(defvar *incoming* :wait)
(defvar *pump-count* 0)
(defvar *tick-count* 0)
(defun fnn-tcl-now () *now*)
(defun fnn-octets (x) (coerce x 'vector))
(defun fnn-octet-list (x) (coerce x 'list))
(defun fnn-tcl-log (&rest args) (declare (ignore args)))
(defun fnn-tcl-record-trace (&rest args) (declare (ignore args)))
(defun fnn-fault (&rest args) (error "fault ~s" args))
(defun fnn-tcl-apply (conn triple &optional source)
 (declare (ignore source))
 (setf (fnn-tclc-session conn) (first triple))
 (dolist (m (second triple)) (push m (fnn-tclc-held conn)))
 (unless (fnn-tclc-source-pending conn) (fnn-tcl-flush conn)))
(defun fnn-core (name &rest args)
 (case name
  ((fn-tcim-turn fn-tcf-at fn-tcf-begin fn-tcf-contactp fn-tcf-byte fn-tcf-span fn-tcrt-action fn-tcrt-write-end fn-tcrt-read-limit fn-tcrt-write-deadline fn-tcrt-contact-deadline fn-tcrt-contact-timeout-p) (apply name args))
  (fn-tclsctl-turn (list (first args) nil))
  (fn-tcl-max-message 200000)
  (fn-tcl-host-segment-mru 100000)
  (fn-tcl-host-input-probe t)
  (fn-tcl-host-initial :established)
  (fn-tcl-host-phase (first args))
  (fn-tcl-host-encode (first args))
  (fn-tcl-host-open (list :established (list '(1 2 3 4 5 6)) nil))
  (fn-tcl-host-tick (incf *tick-count*) (list (first args) nil nil))
  (fn-tcl-host-tcp-closed (list :closed nil nil))
  (fn-tcl-host-active-closep nil)
  (fn-tcl-host-pump (incf *pump-count*) (list :established (and (< *pump-count* 3) (list '(9))) nil))
  (fn-tcl-host-drive (list :established (list '(7 8)) nil))
  (otherwise (error "unexpected core ~s" name))))
(defun fnn-socket-write-now (fd data offset end)
 (declare (ignore fd))
 (push (list :write data offset end) *calls*)
 (assert (<= (- end offset) 4096))
 (if *wait-write* :wait
  (let ((n (min 2 (- end offset))))
   (dotimes (i n) (push (aref data (+ offset i)) *writes*)) n)))
(defun fnn-socket-read-now (fd limit)
 (declare (ignore fd)) (assert (= limit 4096)) (push :read *calls*) *incoming*)
(defun fnn-tcl-source-tick (conn)
 (push :source *calls*)
 (assert (fnn-tclc-source-root conn)))
;;; No write in begin; exact byte range and identity retained across wait.
(let ((conn (fnn-tcl-begin 99 :passive :params "test" "/spool")))
 (assert (null *calls*))
 (assert (eq (fnn-tcl-turn conn) :work)) ; encode
 (let ((data (fnn-tclc-tx-data conn)))
  (setq *wait-write* t)
  (assert (eq (fnn-tcl-turn conn) :wait))
  (assert (eq data (fnn-tclc-tx-data conn)))
  (assert (zerop (fnn-tclc-tx-offset conn)))
  (setq *wait-write* nil)
  (dotimes (i 3) (fnn-tcl-turn conn))
  (assert (null (fnn-tclc-tx-data conn)))
  (assert (equal (reverse *writes*) '(1 2 3 4 5 6))))
 (setq *calls* nil *writes* nil *incoming* #(42))
 (fnn-tcl-turn conn) ; read creates released ACK
 (assert (equal *calls* '(:read)))
 (loop while (fnn-tclc-source-more conn) do (fnn-tcl-turn conn)) ; bounded conversion then one decode
 (let ((*fnn-tcl-progress* (lambda (c) (declare (ignore c))
                            (assert (equal (reverse *writes*) '(7 8)))
                            (push :progress *calls*))))
  (fnn-tcl-turn conn) ; encode
  (fnn-tcl-turn conn) ; write
  (assert (not (member :progress *calls*)))
  (fnn-tcl-turn conn) ; local after physical write
  (assert (member :progress *calls*)))
 ;; Every outbound pump has an intervening bounded input attempt.
 (setq *incoming* :wait *calls* nil)
 (setf (fnn-tclc-pump-pending conn) t (fnn-tclc-input-due conn) t)
 (dotimes (i 11) (fnn-tcl-turn conn))
 (assert (= *pump-count* 3))
 (assert (>= (count :read *calls*) 3))
 ;; Received source retains exact borrow, reads and application hook excluded.
 (setq *calls* nil)
 (setf (fnn-tclc-source-pending conn) t (fnn-tclc-source-root conn) '((1 2)))
 (fnn-tcl-turn conn)
 (assert (equal *calls* '(:source)))
 ;; EOF is connection loss, does not escape or reset the node/service.
 (setf (fnn-tclc-source-pending conn) nil)
 (setq *incoming* #())
 (setf (fnn-tclc-input-due conn) t)
 (fnn-tcl-turn conn)
 (assert (eq (fnn-tclc-session conn) :closed))
 (assert (eq (fnn-tcl-turn conn) :done)))
;;; A publication-shaped local error escapes; it is never socket loss.
(let ((conn (make-fnn-tcl-conn :retained t :session :established :input-due nil))
      (*fnn-tcl-progress* (lambda (conn) (declare (ignore conn)) (error 'fnn-os-error))))
 (assert (handler-case (progn (fnn-tcl-turn conn) nil) (fnn-os-error () t)))
 (assert (not (fnn-tclc-broken conn))))
;;; Write deadline records loss, with no physical-close/settlement invention.
(let ((conn (make-fnn-tcl-conn :retained t :session :established :tx-data #(1)
                              :tx-deadline 100)))
 (setq *calls* nil)
 (fnn-tcl-turn conn)
 (assert (null *calls*))
 (assert (fnn-tclc-broken conn))
 (assert (eq (fnn-tcl-turn conn) :done)))
(format t "PASS retained TCPCL actual driver: exact partial writes/wait, ACK flush before progress, read/pump turns, source borrow, EOF/deadline loss.~%")

;;; An incomplete Contact Header cannot consume a retained slot forever.
;;; Deadline loss itself neither closes a socket nor settles a bank token.
(let ((conn (make-fnn-tcl-conn :retained t :session :contact
                             :contact-deadline 60100))
      (*now* 60100) (*calls* nil))
 (assert (eq (fnn-tcl-turn conn) :done))
 (assert (null *calls*)) (assert (fnn-tclc-broken conn))
 (assert (eq (fnn-tclc-session conn) :closed)))
(let ((conn (make-fnn-tcl-conn :retained t :session :contact
                             :contact-deadline 60100))
      (*now* 60099) (*incoming* :wait) (*calls* nil))
 (assert (eq (fnn-tcl-turn conn) :wait))
 (assert (not (fnn-tclc-broken conn))) (assert (equal *calls* '(:read))))
(let ((conn (make-fnn-tcl-conn :retained t :session :established
                             :contact-deadline 60100 :source-pending t
                             :source-root '(:exact-root) :held '(:end-ack)))
      (*now* 60101) (*calls* nil))
 (fnn-tcl-turn conn)
 (assert (equal *calls* '(:source)))
 (assert (not (fnn-tclc-broken conn)))
 (assert (equal (fnn-tclc-held conn) '(:end-ack)))
 (assert (equal (fnn-tclc-source-root conn) '(:exact-root))))
(format t "PASS actual retained Contact Header timeout: boundary timing/no syscall, established source/END ACK unaffected.~%")

;;; Bytes physically received before the deadline may finish their bounded
;;; framing/materialization turns after it. No new read extends the deadline.
(let ((conn (make-fnn-tcl-conn :retained t :session :contact
             :contact-deadline 60100 :source-more t :input-vector #(100 116 110 33 4 0)))
      (*now* 60100) (*calls* nil))
 (loop repeat 4 do (fnn-tcl-turn conn))
 (assert (eq (fnn-tclc-session conn) :established))
 (assert (not (fnn-tclc-broken conn)))
 (assert (not (member :read *calls*))))
(format t "PASS captured Contact Header finishes bounded decode afterdeadline without another read.~%")
