;;; Actual feed lifecycle over the shared actor envelope; socket effects stubbed.
(load "tests/native_actor_envelope_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-arena-return-observation (log)
  (declare (ignorable log))
  (harness-stub-reached 'fnn-arena-return-observation "host/native/io.lisp"))
(defun fnn-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-core "host/native/io.lisp"))
(defun fnn-extent-direct-start ()
  (harness-stub-reached 'fnn-extent-direct-start "host/native/extent.lisp"))
(defun fnn-extent-end-recovery-cache ()
  (harness-stub-reached 'fnn-extent-end-recovery-cache "host/native/extent.lisp"))
(defun fnn-extent-executor-drained-p ()
  (harness-stub-reached 'fnn-extent-executor-drained-p "host/native/extent.lisp"))
(defun fnn-extent-executor-stop ()
  (harness-stub-reached 'fnn-extent-executor-stop "host/native/extent.lisp"))
(defun fnn-gc-nursery-octets ()
  (harness-stub-reached 'fnn-gc-nursery-octets "host/native/io.lisp"))
(defun fnn-listen (port &key family backlog address)
  (declare (ignorable port family backlog address))
  (harness-stub-reached 'fnn-listen "host/native/io.lisp"))
(defun fnn-log-line (line)
  (declare (ignorable line))
  (harness-stub-reached 'fnn-log-line "host/native/io.lisp"))
(defun fnn-log-seal-capture (store)
  (declare (ignorable store))
  (harness-stub-reached 'fnn-log-seal-capture "host/native/io.lisp"))
(defun fnn-log-sync-collected (log)
  (declare (ignorable log))
  (harness-stub-reached 'fnn-log-sync-collected "host/native/io.lisp"))
(defun fnn-log-writer-start ()
  (harness-stub-reached 'fnn-log-writer-start "host/native/io.lisp"))
(defun fnn-mux-budget-install (service tls-context)
  (declare (ignorable service tls-context))
  (harness-stub-reached 'fnn-mux-budget-install "host/native/mux.lisp"))
(defun fnn-mux-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-mux-drained-p "host/native/mux.lisp"))
(defun fnn-mux-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-mux-start "host/native/mux.lisp"))
(defun fnn-out (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-out "host/native/io.lisp"))
(defun fnn-owner-accept (service listener once)
  (declare (ignorable service listener once))
  (harness-stub-reached 'fnn-owner-accept "host/native/owner.lisp"))
(defun fnn-owner-answer-early (ledger members)
  (declare (ignorable ledger members))
  (harness-stub-reached 'fnn-owner-answer-early "host/native/owner.lisp"))
(defun fnn-owner-claim-run-authority (&optional caller-reservation)
  (declare (ignorable caller-reservation))
  (harness-stub-reached 'fnn-owner-claim-run-authority "host/native/owner.lisp"))
(defun fnn-owner-cold-shutdown (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-cold-shutdown "host/native/owner.lisp"))
(defun fnn-owner-commit-complete-locked (service action members deferred)
  (declare (ignorable service action members deferred))
  (harness-stub-reached 'fnn-owner-commit-complete-locked "host/native/owner.lisp"))
(defun fnn-owner-commit-event (service event)
  (declare (ignorable service event))
  (harness-stub-reached 'fnn-owner-commit-event "host/native/owner.lisp"))
(defun fnn-owner-commit-start-event (members uncertain)
  (declare (ignorable members uncertain))
  (harness-stub-reached 'fnn-owner-commit-start-event "host/native/owner.lisp"))
(defun fnn-owner-commit-start-locked (service &key seal)
  (declare (ignorable service seal))
  (harness-stub-reached 'fnn-owner-commit-start-locked "host/native/owner.lisp"))
(defun fnn-owner-commit-wake (service returned queued)
  (declare (ignorable service returned queued))
  (harness-stub-reached 'fnn-owner-commit-wake "host/native/owner.lisp"))
(defun fnn-owner-committer-await-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-committer-await-start "host/native/owner.lisp"))
(defun fnn-owner-committer-may-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-committer-may-start "host/native/owner.lisp"))
(defun fnn-owner-complete-generation (ledger gen final members)
  (declare (ignorable ledger gen final members))
  (harness-stub-reached 'fnn-owner-complete-generation "host/native/owner.lisp"))
(defun fnn-owner-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-owner-core "host/native/owner.lisp"))
(defun fnn-owner-deliver (service cid completion)
  (declare (ignorable service cid completion))
  (harness-stub-reached 'fnn-owner-deliver "host/native/owner.lisp"))
(defun fnn-owner-disk-event (service kind &optional arg)
  (declare (ignorable service kind arg))
  (harness-stub-reached 'fnn-owner-disk-event "host/native/owner.lisp"))
(defun fnn-owner-disk-stalled-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-disk-stalled-p "host/native/owner.lisp"))
(defun fnn-owner-disk-wait-ms (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-disk-wait-ms "host/native/owner.lisp"))
(defun fnn-owner-drain-service (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-drain-service "host/native/owner.lisp"))
(defun fnn-owner-feed-close-all (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-feed-close-all "host/native/owner.lisp"))
(defun fnn-owner-frames-job (service job)
  (declare (ignorable service job))
  (harness-stub-reached 'fnn-owner-frames-job "host/native/owner.lisp"))
(defun fnn-owner-history-root-maintain (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-history-root-maintain "host/native/history-root.lisp"))
(defun fnn-owner-install (root max-connections &optional fault)
  (declare (ignorable root max-connections fault))
  (harness-stub-reached 'fnn-owner-install "host/native/owner.lisp"))
(defun fnn-owner-journal-close ()
  (harness-stub-reached 'fnn-owner-journal-close "host/native/owner.lisp"))
(defun fnn-owner-journal-note (service a b)
  (declare (ignorable service a b))
  (harness-stub-reached 'fnn-owner-journal-note "host/native/owner.lisp"))
(defun fnn-owner-journal-open (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-journal-open "host/native/owner.lisp"))
(defun fnn-owner-log-settlement ()
  (harness-stub-reached 'fnn-owner-log-settlement "host/native/owner.lisp"))
(defun fnn-owner-measure-report ()
  (harness-stub-reached 'fnn-owner-measure-report "host/native/owner.lisp"))
(defun fnn-owner-output-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-output-drained-p "host/native/owner.lisp"))
(defun fnn-owner-page-read-startup (root max-connections cold-resources output-resources retain)
  (declare (ignorable root max-connections cold-resources output-resources retain))
  (harness-stub-reached 'fnn-owner-page-read-startup "host/native/owner.lisp"))
(defun fnn-owner-peer-flight-startup (service capture)
  (declare (ignorable service capture))
  (harness-stub-reached 'fnn-owner-peer-flight-startup "host/native/owner.lisp"))
(defun fnn-owner-reader-capture (event)
  (declare (ignorable event))
  (harness-stub-reached 'fnn-owner-reader-capture "host/native/owner.lisp"))
(defun fnn-owner-refresh-read-octets (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-refresh-read-octets "host/native/owner.lisp"))
(defun fnn-owner-release-recovery-garbage ()
  (harness-stub-reached 'fnn-owner-release-recovery-garbage "host/native/owner.lisp"))
(defun fnn-owner-retain-run-authority (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-retain-run-authority "host/native/owner.lisp"))
(defun fnn-owner-retire-final-report (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-retire-final-report "host/native/owner.lisp"))
(defun fnn-owner-run-startup-hooks (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-run-startup-hooks "host/native/owner.lisp"))
(defun fnn-owner-serialized (service cid thunk &optional class)
  (declare (ignorable service cid thunk class))
  (harness-stub-reached 'fnn-owner-serialized "host/native/owner.lisp"))
(defun fnn-owner-service-nursery ()
  (harness-stub-reached 'fnn-owner-service-nursery "host/native/owner.lisp"))
(defun fnn-owner-shed-queued-locked (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-shed-queued-locked "host/native/owner.lisp"))
(defun fnn-owner-snapshot-jobs-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-snapshot-jobs-drained-p "host/native/owner.lisp"))
(defun fnn-owner-space-event (service need)
  (declare (ignorable service need))
  (harness-stub-reached 'fnn-owner-space-event "host/native/owner.lisp"))
(defun fnn-owner-space-prime (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-space-prime "host/native/owner.lisp"))
(defun fnn-owner-stall-release (service members)
  (declare (ignorable service members))
  (harness-stub-reached 'fnn-owner-stall-release "host/native/owner.lisp"))
(defun fnn-owner-start-committer (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-start-committer "host/native/owner.lisp"))
(defun fnn-owner-start-tls-accept (service listener &optional implicit-tls)
  (declare (ignorable service listener implicit-tls))
  (harness-stub-reached 'fnn-owner-start-tls-accept "host/native/owner.lisp"))
(defun fnn-owner-store-settlement (service settlement)
  (declare (ignorable service settlement))
  (harness-stub-reached 'fnn-owner-store-settlement "host/native/owner.lisp"))
(defun fnn-owner-syncer-abandon (service grant ledger members)
  (declare (ignorable service grant ledger members))
  (harness-stub-reached 'fnn-owner-syncer-abandon "host/native/owner.lisp"))
(defun fnn-owner-syncer-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-syncer-drained-p "host/native/owner.lisp"))
(defun fnn-owner-syncer-outcome (service grant generation)
  (declare (ignorable service grant generation))
  (harness-stub-reached 'fnn-owner-syncer-outcome "host/native/owner.lisp"))
(defun fnn-owner-syncer-physical (service grant receipt)
  (declare (ignorable service grant receipt))
  (harness-stub-reached 'fnn-owner-syncer-physical "host/native/owner.lisp"))
(defun fnn-owner-wait-workers (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-wait-workers "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-drain (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-drain "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-joined (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-joined "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-start "host/native/owner.lisp"))
(defun fnn-peer-flight-bank-drained (bank)
  (declare (ignorable bank))
  (harness-stub-reached 'fnn-peer-flight-bank-drained "host/native/catchup-spool.lisp"))
;;; ---- derived stubs: END ----
(load-deployed-forms "host/native/owner.lisp"
 '((defun fnn-owner-actor-for-custody) (defun fnn-owner-thread-escape)
   (defun fnn-owner-signal-commit)))
(load-deployed-forms "host/native/feed-service.lisp"
 '((defstruct (fnn-feed-runtime (:constructor %make-fnn-feed-runtime)))
   (defparameter *fnn-feed-runtime-lock*) (defparameter *fnn-feed-runtimes*)
   (defun fnn-feed-runtime-get) (defun fnn-feed-runtime-put) (defun fnn-feed-runtime-drop)
   (defun fnn-feed-stoppingp) (defun fnn-feed-worker-guarded)
   (def-actor fnn-feed-spawn-worker) (defun fnn-feed-service-start)
   (defun fnn-feed-service-wake) (defun fnn-feed-service-close)))
(defun fnn-feed-peer-list (service) (declare (ignore service)) nil)
(defun fnn-feed-read-limit (service) (declare (ignore service)) 1)
(defun fnn-feed-link-for-peer (name) (declare (ignore name)) (error "unexpected peer"))
(defun fnn-feed-link-socket (link) (declare (ignore link)) (error "unexpected socket"))
(defun fnn-socket-shutdown (socket) (declare (ignore socket)) (error "unexpected shutdown"))
(defun fnn-feed-worker (runtime) (declare (ignore runtime)) (error "unexpected worker"))

;; A failed join during held terminal cleanup must retain the module registry.
(let* ((s (%make-fnn-owner-service))
       (started (sb-thread:make-semaphore :count 0))
       (cleanup-held (sb-thread:make-semaphore :count 0)))
  (setf (symbol-function 'fnn-feed-worker)
        (lambda (runtime)
          (unwind-protect
               (progn (sb-thread:signal-semaphore started)
                      (loop until (fnn-feed-stoppingp runtime) do (sb-thread:thread-yield)))
            (wait-label cleanup-held))))
  (fnn-feed-service-start s)
  (wait-label started)
  (let* ((runtime (fnn-feed-runtime-get s))
         (actor (fnn-owner-actor-for-custody s runtime))
         (*fnn-actor-thread-joiner* (lambda (&rest args) (declare (ignore args))
                                   (error "held feed cleanup"))))
    (handler-case (progn (fnn-feed-service-close s) (error "expected held close"))
      (fnn-store-fault () nil))
    (check (and (eq runtime (fnn-feed-runtime-get s)) (registered s actor))
           "held feed close preserves module and reservation"))
  (sb-thread:signal-semaphore cleanup-held)
  (fnn-feed-service-close s)
  (check (and (null (fnn-feed-runtime-get s)) (null (fnn-owner-service-actors s)))
         "feed module drops only after physical cleanup join"))

;; Startup may fail before returning the worker slot; retained actor custody
;; still locates a created parked child for a later physical join.
(let* ((s (%make-fnn-owner-service))
       (*fnn-actor-start-signal* (lambda (latch) (declare (ignore latch))
                                 (error "failed feed release")))
       (*fnn-actor-thread-terminator* (lambda (worker) (declare (ignore worker)) nil)))
  (handler-case (progn (fnn-feed-service-start s) (error "expected startup failure"))
    (error () nil))
  (let* ((runtime (fnn-feed-runtime-get s))
         (actor (fnn-owner-actor-for-custody s runtime))
         (worker (fnn-owner-actor-thread actor)))
    (check (and (null (fnn-feed-runtime-worker runtime))
                (sb-thread:thread-alive-p worker) (registered s actor))
           "failed starter child remains discoverable through custody")
    (sb-thread:terminate-thread worker)
    (fnn-feed-service-close s)
    (check (null (fnn-feed-runtime-get s)) "failed starter eventually physically closes")))

;; The actual fault-service entry must send a late cleanup fault through
;; ACL2's lattice even after a graceful stop. Effects/gate are recording stubs.
(defun fn-outcome-code (word)
  (ecase word (:accepted 0) (:refused 1) (:usage 5) (:fault 4) (:fenced 3)))
(load-deployed-forms "books/failure-scope.lisp"
 '((defun fn-fs-stop-exit-rank) (defun fn-fs-stop-exit-escalate)))
(defparameter +fnn-exit-fault+ 4)
(defvar *fnn-owner-last-fault* nil)
(defmacro fnn-owner-gated ((service class &key cid) &body body)
  (declare (ignore service class cid body))
  '(error "an aborted scheduler cannot grant a fault boundary"))
(defun fnn-owner-stop-service-locked (service code)
  (check (sb-thread:holding-mutex-p (fnn-owner-service-lock service))
         "irreversible fault applies lattice under owner exclusion")
  (setf (fnn-owner-service-stopping service) t
        (fnn-owner-service-exit-code service)
        (fn-fs-stop-exit-escalate (fnn-owner-service-exit-code service) code)))
(defun fnn-owner-connection-selected-p (service) (declare (ignore service)) nil)
(defun fnn-owner-action (&rest args) (declare (ignore args)) (error "unexpected mutation"))
(load-deployed-forms "host/native/owner.lisp" '((defun fnn-owner-fault-service)))
(dolist (initial '(0 3))
  (let ((s (%make-fnn-owner-service :stopping t :exit-code initial
                                   :lock (sb-thread:make-mutex))))
    (check (not (sb-thread:holding-mutex-p (fnn-owner-service-lock s)))
           "fault-service entry is outside owner exclusion")
    (let ((cleanup-reached nil))
      (fnn-owner-fault-service s nil (make-condition 'simple-error))
      (setq cleanup-reached t)
      (check cleanup-reached "aborted gate does not intercept terminal cleanup"))
    (check (eql (fnn-owner-service-exit-code s) (if (zerop initial) 4 3))
           "cleanup fault escalates graceful stop and never masks uncertainty")))
(define-condition feed-unknown-store-subclass (fnn-store-error) ())
(dolist (condition '(fnn-store-error feed-unknown-store-subclass))
  (let* ((s (%make-fnn-owner-service :stopping t :exit-code 0
                                    :lock (sb-thread:make-mutex)))
         (runtime (%make-fnn-feed-runtime :service s)))
    (setf (symbol-function 'fnn-feed-worker)
          (lambda (runtime) (declare (ignore runtime)) (error condition)))
    (fnn-feed-worker-guarded runtime)
    (check (eql (fnn-owner-service-exit-code s)
                (if (eq condition 'fnn-store-error) 0 4))
           "known stopping refusal scoped; unknown store subclass faults after stop")))
(format t "~&native_feed_actor_raw: PASS retained module/failed start/cleanup escalation~%")
