;;; Actual owner loan/close functions over recording physical and typed leaves.
;;; This checks native ordering; it is not typed/controller equivalence evidence.
(load "tests/native_output_response_lease_raw-mock.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-arena-return-observation (log)
  (declare (ignorable log))
  (harness-stub-reached 'fnn-arena-return-observation "host/native/io.lisp"))
(defun fnn-dev-held-verdicts-dump (label)
  (declare (ignorable label))
  (harness-stub-reached 'fnn-dev-held-verdicts-dump "host/native/owner.lisp"))
(defun fnn-extent-direct-start ()
  (harness-stub-reached 'fnn-extent-direct-start "host/native/extent.lisp"))
(defun fnn-extent-end-recovery-cache ()
  (harness-stub-reached 'fnn-extent-end-recovery-cache "host/native/extent.lisp"))
(defun fnn-extent-executor-drained-p ()
  (harness-stub-reached 'fnn-extent-executor-drained-p "host/native/extent.lisp"))
(defun fnn-extent-executor-stop ()
  (harness-stub-reached 'fnn-extent-executor-stop "host/native/extent.lisp"))
(defun fnn-extent-window-settle-fault (worker token)
  (declare (ignorable worker token))
  (harness-stub-reached 'fnn-extent-window-settle-fault "host/native/extent.lisp"))
(defun fnn-gc-nursery-octets ()
  (harness-stub-reached 'fnn-gc-nursery-octets "host/native/io.lisp"))
(defun fnn-listen (port &key family backlog address)
  (declare (ignorable port family backlog address))
  (harness-stub-reached 'fnn-listen "host/native/io.lisp"))
(defun fnn-log-line (line)
  (declare (ignorable line))
  (harness-stub-reached 'fnn-log-line "host/native/io.lisp"))
(defun fnn-log-seal-capture (store)
  (declare (ignorable store))
  (harness-stub-reached 'fnn-log-seal-capture "host/native/io.lisp"))
(defun fnn-log-sync-collected (log)
  (declare (ignorable log))
  (harness-stub-reached 'fnn-log-sync-collected "host/native/io.lisp"))
(defun fnn-log-writer-start ()
  (harness-stub-reached 'fnn-log-writer-start "host/native/io.lisp"))
(defun fnn-mux-after (loop conn after)
  (declare (ignorable loop conn after))
  (harness-stub-reached 'fnn-mux-after "host/native/mux.lisp"))
(defun fnn-mux-await (loop conn step redeem after)
  (declare (ignorable loop conn step redeem after))
  (harness-stub-reached 'fnn-mux-await "host/native/mux.lisp"))
(defun fnn-mux-budget-install (service tls-context)
  (declare (ignorable service tls-context))
  (harness-stub-reached 'fnn-mux-budget-install "host/native/mux.lisp"))
(defun fnn-mux-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-mux-drained-p "host/native/mux.lisp"))
(defun fnn-mux-plan-cold (loop conn plan after read)
  (declare (ignorable loop conn plan after read))
  (harness-stub-reached 'fnn-mux-plan-cold "host/native/mux.lisp"))
(defun fnn-mux-plan-window-wait (conn plan after)
  (declare (ignorable conn plan after))
  (harness-stub-reached 'fnn-mux-plan-window-wait "host/native/mux.lisp"))
(defun fnn-mux-plan-yield (loop conn plan after &optional empty-progressp)
  (declare (ignorable loop conn plan after empty-progressp))
  (harness-stub-reached 'fnn-mux-plan-yield "host/native/mux.lisp"))
(defun fnn-mux-queue (loop conn octets op after &optional end)
  (declare (ignorable loop conn octets op after end))
  (harness-stub-reached 'fnn-mux-queue "host/native/mux.lisp"))
(defun fnn-mux-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-mux-start "host/native/mux.lisp"))
(defun fnn-now ()
  (harness-stub-reached 'fnn-now "host/native/io.lisp"))
(defun fnn-out (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-out "host/native/io.lisp"))
(defun fnn-owner-accept (service listener once)
  (declare (ignorable service listener once))
  (harness-stub-reached 'fnn-owner-accept "host/native/owner.lisp"))
(defun fnn-owner-answer-early (ledger members)
  (declare (ignorable ledger members))
  (harness-stub-reached 'fnn-owner-answer-early "host/native/owner.lisp"))
(defun fnn-owner-chunk-results (service cid incoming socket class peerp results cold-since)
  (declare (ignorable service cid incoming socket class peerp results cold-since))
  (harness-stub-reached 'fnn-owner-chunk-results "host/native/owner.lisp"))
(defun fnn-owner-claim-run-authority (&optional caller-reservation)
  (declare (ignorable caller-reservation))
  (harness-stub-reached 'fnn-owner-claim-run-authority "host/native/owner.lisp"))
(defun fnn-owner-cold-shutdown (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-cold-shutdown "host/native/owner.lisp"))
(defun fnn-owner-cold-window-fault (word)
  (declare (ignorable word))
  (harness-stub-reached 'fnn-owner-cold-window-fault "host/native/owner.lisp"))
(defun fnn-owner-commit-complete-locked (service action members deferred)
  (declare (ignorable service action members deferred))
  (harness-stub-reached 'fnn-owner-commit-complete-locked "host/native/owner.lisp"))
(defun fnn-owner-commit-event (service event)
  (declare (ignorable service event))
  (harness-stub-reached 'fnn-owner-commit-event "host/native/owner.lisp"))
(defun fnn-owner-commit-start-event (members uncertain)
  (declare (ignorable members uncertain))
  (harness-stub-reached 'fnn-owner-commit-start-event "host/native/owner.lisp"))
(defun fnn-owner-commit-start-locked (service &key seal)
  (declare (ignorable service seal))
  (harness-stub-reached 'fnn-owner-commit-start-locked "host/native/owner.lisp"))
(defun fnn-owner-commit-wake (service returned queued)
  (declare (ignorable service returned queued))
  (harness-stub-reached 'fnn-owner-commit-wake "host/native/owner.lisp"))
(defun fnn-owner-committer-await-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-committer-await-start "host/native/owner.lisp"))
(defun fnn-owner-committer-may-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-committer-may-start "host/native/owner.lisp"))
(defun fnn-owner-complete-generation (ledger gen final members)
  (declare (ignorable ledger gen final members))
  (harness-stub-reached 'fnn-owner-complete-generation "host/native/owner.lisp"))
(defun fnn-owner-deliver (service cid completion)
  (declare (ignorable service cid completion))
  (harness-stub-reached 'fnn-owner-deliver "host/native/owner.lisp"))
(defun fnn-owner-disk-event (service kind &optional arg)
  (declare (ignorable service kind arg))
  (harness-stub-reached 'fnn-owner-disk-event "host/native/owner.lisp"))
(defun fnn-owner-disk-stalled-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-disk-stalled-p "host/native/owner.lisp"))
(defun fnn-owner-disk-wait-ms (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-disk-wait-ms "host/native/owner.lisp"))
(defun fnn-owner-drain-service (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-drain-service "host/native/owner.lisp"))
(defun fnn-owner-feed-close-all (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-feed-close-all "host/native/owner.lisp"))
(defun fnn-owner-frames-job (service job)
  (declare (ignorable service job))
  (harness-stub-reached 'fnn-owner-frames-job "host/native/owner.lisp"))
(defun fnn-owner-handle-chunk-read (service cid incoming socket class &optional peerp)
  (declare (ignorable service cid incoming socket class peerp))
  (harness-stub-reached 'fnn-owner-handle-chunk-read "host/native/owner.lisp"))
(defun fnn-owner-history-root-maintain (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-history-root-maintain "host/native/history-root.lisp"))
(defun fnn-owner-install (root max-connections &optional fault)
  (declare (ignorable root max-connections fault))
  (harness-stub-reached 'fnn-owner-install "host/native/owner.lisp"))
(defun fnn-owner-journal-close ()
  (harness-stub-reached 'fnn-owner-journal-close "host/native/owner.lisp"))
(defun fnn-owner-journal-note (service a b)
  (declare (ignorable service a b))
  (harness-stub-reached 'fnn-owner-journal-note "host/native/owner.lisp"))
(defun fnn-owner-journal-open (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-journal-open "host/native/owner.lisp"))
(defun fnn-owner-log-settlement ()
  (harness-stub-reached 'fnn-owner-log-settlement "host/native/owner.lisp"))
(defun fnn-owner-measure-report ()
  (harness-stub-reached 'fnn-owner-measure-report "host/native/owner.lisp"))
(defun fnn-owner-monotonic-ms ()
  (harness-stub-reached 'fnn-owner-monotonic-ms "host/native/owner.lisp"))
(defun fnn-owner-page-read-startup (root max-connections cold-resources output-resources retain)
  (declare (ignorable root max-connections cold-resources output-resources retain))
  (harness-stub-reached 'fnn-owner-page-read-startup "host/native/owner.lisp"))
(defun fnn-owner-peer-flight-startup (service capture)
  (declare (ignorable service capture))
  (harness-stub-reached 'fnn-owner-peer-flight-startup "host/native/owner.lisp"))
(defun fnn-owner-peer-read-class (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-peer-read-class "host/native/owner.lisp"))
(defun fnn-owner-reader-capture (event)
  (declare (ignorable event))
  (harness-stub-reached 'fnn-owner-reader-capture "host/native/owner.lisp"))
(defun fnn-owner-refresh-read-octets (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-refresh-read-octets "host/native/owner.lisp"))
(defun fnn-owner-release-recovery-garbage ()
  (harness-stub-reached 'fnn-owner-release-recovery-garbage "host/native/owner.lisp"))
(defun fnn-owner-resource-unavailable-line (service cid incoming word class)
  (declare (ignorable service cid incoming word class))
  (harness-stub-reached 'fnn-owner-resource-unavailable-line "host/native/owner.lisp"))
(defun fnn-owner-response-identity (service connection class)
  (declare (ignorable service connection class))
  (harness-stub-reached 'fnn-owner-response-identity "host/native/owner.lisp"))
(defun fnn-owner-retain-run-authority (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-retain-run-authority "host/native/owner.lisp"))
(defun fnn-owner-retire-final-report (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-retire-final-report "host/native/owner.lisp"))
(defun fnn-owner-run-startup-hooks (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-run-startup-hooks "host/native/owner.lisp"))
(defun fnn-owner-serialized (service cid thunk &optional class)
  (declare (ignorable service cid thunk class))
  (harness-stub-reached 'fnn-owner-serialized "host/native/owner.lisp"))
(defun fnn-owner-service-nursery ()
  (harness-stub-reached 'fnn-owner-service-nursery "host/native/owner.lisp"))
(defun fnn-owner-shed-queued-locked (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-shed-queued-locked "host/native/owner.lisp"))
(defun fnn-owner-snapshot-jobs-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-snapshot-jobs-drained-p "host/native/owner.lisp"))
(defun fnn-owner-space-event (service need)
  (declare (ignorable service need))
  (harness-stub-reached 'fnn-owner-space-event "host/native/owner.lisp"))
(defun fnn-owner-space-prime (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-space-prime "host/native/owner.lisp"))
(defun fnn-owner-stall-release (service members)
  (declare (ignorable service members))
  (harness-stub-reached 'fnn-owner-stall-release "host/native/owner.lisp"))
(defun fnn-owner-start-committer (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-start-committer "host/native/owner.lisp"))
(defun fnn-owner-start-tls-accept (service listener &optional implicit-tls)
  (declare (ignorable service listener implicit-tls))
  (harness-stub-reached 'fnn-owner-start-tls-accept "host/native/owner.lisp"))
(defun fnn-owner-store-settlement (service settlement)
  (declare (ignorable service settlement))
  (harness-stub-reached 'fnn-owner-store-settlement "host/native/owner.lisp"))
(defun fnn-owner-syncer-abandon (service grant ledger members)
  (declare (ignorable service grant ledger members))
  (harness-stub-reached 'fnn-owner-syncer-abandon "host/native/owner.lisp"))
(defun fnn-owner-syncer-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-syncer-drained-p "host/native/owner.lisp"))
(defun fnn-owner-syncer-outcome (service grant generation)
  (declare (ignorable service grant generation))
  (harness-stub-reached 'fnn-owner-syncer-outcome "host/native/owner.lisp"))
(defun fnn-owner-syncer-physical (service grant receipt)
  (declare (ignorable service grant receipt))
  (harness-stub-reached 'fnn-owner-syncer-physical "host/native/owner.lisp"))
(defun fnn-owner-unavailable-line (service cid incoming since now limit class)
  (declare (ignorable service cid incoming since now limit class))
  (harness-stub-reached 'fnn-owner-unavailable-line "host/native/owner.lisp"))
(defun fnn-owner-wait-workers (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-wait-workers "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-joined (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-joined "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-start "host/native/owner.lisp"))
(defun fnn-peer-flight-bank-drained (bank)
  (declare (ignorable bank))
  (harness-stub-reached 'fnn-peer-flight-bank-drained "host/native/catchup-spool.lisp"))
(defun fnn-tls-consume-plaintext (fd expected seconds)
  (declare (ignorable fd expected seconds))
  (harness-stub-reached 'fnn-tls-consume-plaintext "host/native/tls.lisp"))
;;; ---- derived stubs: END ----
(load-deployed-forms "host/native/extent.lisp"
 '((defvar *fnn-extent-lock*) (defmacro fnn-extent-native-observe) (defvar *fnn-extent-window-mode*)
   (defvar *fnn-extent-window-worker*) (defvar *fnn-extent-window-token*)
   (defun fnn-extent-window-observation)))
;; Developer-only observations are off.
(defun fnn-developer-selector (name) (declare (ignore name)) nil)
(load-deployed-forms "host/native/owner.lisp"
 '((defun fnn-owner-window-activation) (defun fnn-owner-cold-remove-locked)
   (defun fnn-owner-cold-window-result-locked) (defun fnn-owner-response-window-close)))
;; The window close runs as one fnn-quantum-mux-finish quantum; this fixture's subject
;; is the window's custody inside it, so the quantum just runs its thunk (the
;; envelope itself is native_section_envelope_raw's subject).
(defun fnn-quantum-mux-finish (service cid thunk &optional class)
  (declare (ignore service cid class)) (funcall thunk))
(defvar *window-returned* nil)
(defvar *window-word* :ready)
(defvar *window-effects* nil)
(defvar *window-release-word* :released)
(defun fnn-extent-pool-funded-p () t)
(defun fnn-extent-executor-returned-p (worker) (declare (ignore worker)) *window-returned*)
(defun fnn-extent-window-outcome (worker token) (declare (ignore worker token)) *window-word*)
(defun fnn-extent-window-cancel (worker token)
  (push (list :cancel worker token) *window-effects*)
  (setq *window-word* :cancelled) :cancelled)
(defun fnn-extent-window-settle-cancelled (worker token)
  (push (list :release worker token) *window-effects*) *window-release-word*)
(defun fnn-extent-window-release (worker token &optional cachep)
  (declare (ignore cachep))
  (push (list :release worker token) *window-effects*) *window-release-word*)
(defun fnn-owner-output-observe-returned (service read) (declare (ignore service read)))
(defun fnn-owner-output-dependency-consumed (service read)
  (declare (ignore service read)) (push :consumed *window-effects*))
(defun fnn-owner-release-pending-extents-locked (service) (declare (ignore service)))
(defun window-case (returned)
  (let* ((service (%make-fnn-owner-service :lock (sb-thread:make-mutex)))
         (read (%make-fnn-owner-cold-read :windowp t :worker :worker :token :token :queuedp t))
         (capture (%make-fnn-response-capture :window-read read))
         (*window-returned* returned) (*window-word* :ready) (*window-effects* nil))
    (setf (fnn-owner-service-cold-head service) read (fnn-owner-service-cold-tail service) read)
    (when returned
      (check (fnn-owner-cold-window-result-locked service read) "ready scalar loan")
      (check (and (fnn-owner-cold-read-borrowedp read) (not (fnn-owner-cold-read-settledp read))
                  (null *window-effects*)) "physical return alone retains scalar charge")
      (let ((*fnn-response-capture* capture))
        (fnn-owner-window-activation
         (lambda () (check (and *fnn-extent-window-mode*
                                (eq *fnn-extent-window-worker* :worker)
                                (eq *fnn-extent-window-token* :token)) "exact captured scalar borrow")))))
    (check (eq (fnn-owner-response-window-close service capture) :window-closed) "whole-response close")
    (unless returned
      (check (and (not (fnn-owner-cold-read-settledp read))
                  (eq (fnn-owner-service-cold-head service) read)
                  (= 1 (length *window-effects*))) "close before physical return preserves charge and roster")
      (setq *window-returned* t)
      (check (fnn-owner-cold-window-result-locked service read) "late actual return settles cancelled loan"))
    (check (and (fnn-owner-cold-read-settledp read) (null (fnn-owner-service-cold-head service))
                (= 1 (count :consumed *window-effects*))
                (= 1 (count :release *window-effects* :key (lambda (x) (if (consp x) (car x) x)))))
           "one release only after terminal last borrow")
    (let ((before (copy-list *window-effects*)))
      (fnn-owner-response-window-close service capture)
      (fnn-owner-cold-window-result-locked service read)
      (check (equal before *window-effects*) "duplicate close/reap never releases twice"))))
(window-case t)
(window-case nil)
(let* ((service (%make-fnn-owner-service :lock (sb-thread:make-mutex)))
       (read (%make-fnn-owner-cold-read :windowp t :worker :worker :token :token :abandonedp t))
       (*window-returned* t) (*window-word* :cancelled) (*window-release-word* :stale-job))
  (check (handler-case (progn (fnn-owner-cold-window-result-locked service read) nil) (serious-condition () t))
         "refused release faults")
  (check (and (not (fnn-owner-cold-read-settledp read)) (eq (fnn-owner-cold-read-worker read) :worker))
         "missing release receipt retains exact custody"))
(format t "native_response_window_raw: PASS ready borrow/close-held/late return/duplicate/refused release~%")
