;;; Drive the shipped live-admin function under a recording owner boundary.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")

(defstruct test-store config-generation config-served config-domain fenced)
(defsetf fnn-store-config-generation (store) (value)
  `(setf (test-store-config-generation ,store) ,value))
(defsetf fnn-store-config-served (store) (value)
  `(setf (test-store-config-served ,store) ,value))
(defsetf fnn-store-config-domain (store) (value)
  `(setf (test-store-config-domain ,store) ,value))
(defsetf fnn-store-fenced (store) (value)
  `(setf (test-store-fenced ,store) ,value))
(defvar *store* (make-test-store :config-generation 1
                                 :config-served '("fn.test")
                                 :config-domain '("fn.test")))
(defvar *calls* nil)
(defvar *bad-domain* nil)
(define-condition test-indeterminate (error) ())
(defun fnn-indeterminate (&rest args)
  (declare (ignore args)) (error 'test-indeterminate))
(defun fnn-fault (&rest args) (error "fault: ~s" args))
(defun fnn-octet-list-p (x)
  (and (listp x) (every (lambda (b) (and (integerp b) (<= 0 b 255))) x)))
(defun fnn-octets (x) x)
(defun fnn-octets-string (x) (map 'string #'code-char x))
(defun fnn-owner-serialized (service cid thunk)
  (declare (ignore service cid)) (funcall thunk))
(defun fnn-owner-service-store (service)
  (declare (ignore service)) *store*)
(defun fnn-core (name &rest args)
  (push (cons name args) *calls*)
  (case name (fn-native-admin-host-plan :plan) (otherwise (error "core ~s" name))))
(defun fnn-owner-core (name &rest args)
  (push (cons name args) *calls*)
  (case name
    (fn-owner-open 7)
    (fn-owner-reconfigure-octets '(1 2))
    (fn-owner-config-generation 2)
    (fn-owner-config-served '(102 110 46 116 101 115 116 10
                              102 110 46 108 105 118 101))
    (fn-owner-domain (if *bad-domain* :bad
                       '(102 110 46 116 101 115 116 10
                         102 110 46 108 105 118 101)))
    (otherwise (error "owner core ~s" name))))
(defun fnn-owner-action (name &rest args)
  (push (cons name args) *calls*)
  (case name
    (fn-native-admin-host-owner-reconfigure :staged)
    (fn-owner-reconfigure-complete :durable)
    (otherwise nil)))
(defun fnn-admin-plan-acceptedp (x) (eq x :plan))
(defun fnn-config-record-observation (store) (declare (ignore store)) nil)
(defun fnn-config-records-from-observation (observation)
  (declare (ignore observation)) nil)
(defun fnn-durable-records (store) (declare (ignore store)) nil)
(defun fnn-admin-authorize (&rest args) (declare (ignore args)) :authorization)
(defun fnn-admin-publish (&rest args)
  (declare (ignore args)) (push '(publish) *calls*) (values 2 "generation-2"))
(defun fnn-owner-feed-refresh-configuration (service)
  (declare (ignore service)) (push '(feed-refresh) *calls*))

(dolist (spec '(("host/native/io.lisp" fnn-decode-joined-names)
                ("host/native/admin.lisp" fnn-owner-refresh-config-cache)
                ("host/native/admin.lisp" fnn-owner-live-admin-serialized)))
  (destructuring-bind (path name) spec
    (let ((found nil))
      (with-open-file (stream path)
        (loop for form = (read stream nil :eof)
              until (eq form :eof)
              when (and (consp form) (eq (car form) 'defun)
                        (eq (cadr form) name))
                do (eval form) (setf found t)))
      (unless found (error "deployed function ~s missing" name)))))

(unless (eq (fnn-owner-live-admin-serialized :service '(1)) :accepted)
  (error "durably completed live config was not accepted"))
(unless (and (= (test-store-config-generation *store*) 2)
             (equal (test-store-config-served *store*) '("fn.test" "fn.live"))
             (equal (test-store-config-domain *store*) '("fn.test" "fn.live")))
  (error "native config cache did not follow owner ACL2 projections"))
(let* ((calls (reverse *calls*))
       (complete (position 'fn-owner-reconfigure-complete calls :key #'car))
       (generation (position 'fn-owner-config-generation calls :key #'car))
       (domain (position 'fn-owner-domain calls :key #'car))
       (feed (position 'feed-refresh calls :key #'car)))
  (unless (and complete generation domain feed
               (< complete generation) (< generation domain) (< domain feed))
    (error "config cache refresh preceded durable completion or followed feed: ~s"
           calls)))

(setq *store* (make-test-store :config-generation 1 :config-served '("fn.test")
                               :config-domain '("fn.test"))
      *bad-domain* t *calls* nil)
(handler-case
    (progn (fnn-owner-live-admin-serialized :service '(1))
           (error "malformed owner domain was accepted"))
  (test-indeterminate () nil))
(unless (and (test-store-fenced *store*)
             (= (test-store-config-generation *store*) 1)
             (equal (test-store-config-domain *store*) '("fn.test"))
             (not (member 'feed-refresh *calls* :key #'car)))
  (error "failed post-commit projection neither fenced nor preserved old triple"))
(format t "native live config cache boundary passed~%")
