;;; Load in the retained source owner after admitting the actual selected EWZ
;;; definitions and guarded optimized counterparts. Only private digest state
;;; is mutated; production function routes and owner state stay unchanged.
(in-package "ACL2")

(defun fnda-function (name)
  (let ((normal (find-symbol (symbol-name name) "ACL2_*1*_ACL2")))
    (unless (and (eq (getpropc name 'symbol-class nil (w *the-live-state*))
                     :common-lisp-compliant)
                 normal (fboundp normal)
                 (compiled-function-p (symbol-function normal)))
      (error "actual guarded compiled counterpart unavailable: ~s" name))
    (symbol-function normal)))

(defmacro fnda-with-capture-route ((sharedp) &body body)
  (let ((original (gensym "BOUND")))
    `(let ((,original (symbol-function 'fn-ews-boundp)))
       (unwind-protect
            (progn
              (when ,sharedp
                (setf (symbol-function 'fn-ews-boundp)
                      (symbol-function 'fn-ews-no-copy-boundp)))
              ,@body)
         (setf (symbol-function 'fn-ews-boundp) ,original)))))

(defun fnda-run ()
  (let* ((legacy (fnda-function 'fn-ewz-next-action))
         (single (fnda-function 'fn-ewz-single-effect-action))
         (bound (fnda-function 'fn-ews-boundp))
         (no-copy (fnda-function 'fn-ews-no-copy-boundp))
         (capture (fnda-function 'fn-ews-capture))
         (matches (fnda-function 'fn-ews-capture-matches))
         (begin (fnda-function 'fn-ews-begin))
         (tick (fnda-function 'fn-ews-tick))
         (effect (fnda-function 'fn-ews-effect))
         (state (fnda-function 'fn-ewz-state))
         (digest (create-pgs-digest-state))
         (*fnn-trace-state* nil) (*fnn-trace-parent* nil)
         (*fnn-trace-operation* nil) (*fnn-trace-connection-generation* nil))
    (assert (fn-list/fields= nil))
    (assert (not (fn-list/fields= '(1))))
    (assert (fn-list/fields= '(1) 1))
    (assert (not (fn-list/fields= '(1 . :tail) 1)))
    (let ((seen nil))
      (assert (not (fn-list/fields= (progn (push :product seen) '(:wrong))
                     (progn (push :one seen) 1) (progn (push :two seen) 2))))
      (assert (equal (reverse seen) '(:product :one :two))))
    (let ((original (symbol-function 'fn-ews-boundp)))
      (assert (eq (catch 'fnda-exit
                    (fnda-with-capture-route (t) (throw 'fnda-exit :left))) :left))
      (assert (handler-case (fnda-with-capture-route (t) (error "diagnostic exit"))
                (error () t)))
      (assert (eq original (symbol-function 'fn-ews-boundp))))
    (multiple-value-bind (plan next-digest)
        (funcall begin 7 100 64 100 64 0 23 47 59 0 digest)
      (setf digest next-digest)
      ;; A fresh digest first initializes its tree/chunk cursor. Reach the
      ;; real issued-read state through its actual transition entry.
      (loop for steps below 32
            until (funcall effect plan digest)
            do (multiple-value-bind (status next-plan next-digest)
                   (funcall tick plan digest)
                 (assert (eq status :continue))
                 (setf plan next-plan digest next-digest))
            finally (assert (funcall effect plan digest)))
      (let ((z (funcall state :scan plan 64 0 64 1024 0 0 :more)))
        (assert (eq (car (funcall legacy z digest)) :read))
        (assert (funcall bound plan digest))
        (assert (funcall no-copy plan digest))
        ;; Actual controller branch decisions, including codec, invalid hash,
        ;; and publication. Never reconstruct a host-issued read effect.
        (dolist (mode '(:scan :drain :decoded :codec :bounds :unknown))
          (dolist (phase '(:scan :trailer :verified :bounds :unknown))
            (let ((candidate (copy-list z)) (p (copy-list plan)))
              (setf (car candidate) mode (car p) phase (cadr candidate) p)
              (assert (equal (funcall legacy candidate digest)
                             (funcall single candidate digest)))
              (assert (equal (funcall legacy candidate digest)
                             (fnda-with-capture-route (t)
                               (funcall single candidate digest)))))))
        ;; Every captured field, exact proper length, and malformed tails.
        (dolist (p (list nil '(1) plan))
          (assert (equal (funcall bound p digest) (funcall no-copy p digest))))
        (let ((tuple (funcall capture plan)))
          (dolist (x (list nil :atom tuple (butlast tuple)
                          (append tuple '(:extra))
                          (append (butlast tuple) :tail)))
            (assert (equal (funcall matches x plan) (equal x tuple))))
          (dotimes (i 12)
            (let ((x (copy-list tuple)))
              (setf (nth i x) :corrupted)
              (assert (not (funcall matches x plan))))))
        (dotimes (i 14)
          (let ((p (copy-list plan)))
            (setf (nth i p) :corrupted)
            ;; Arithmetic fields must retain their existing guard domain.
            (when (member i '(1 2 4 6 8 9 10 11 12 13))
              (assert (equal (funcall bound p digest) (funcall no-copy p digest))))))
        (fnn-trace-start :capacity 5 :allocation :process)
        (dolist (route (list (list :legacy-effect legacy z)
                            (list :single-effect single z)
                            (list :legacy-capture bound plan)
                            (list :field-capture no-copy plan)
                            (list :combined-effect single z)))
          (fnda-with-capture-route ((eq (first route) :combined-effect))
            (dotimes (warm 4)
              (dotimes (i 1000) (funcall (second route) (third route) digest)))
            (sb-ext:gc :full t)
            (fnn-trace-span ((first route) :operation 1)
              (dotimes (i 20000) (funcall (second route) (third route) digest)))))
        (fnn-trace-report *standard-output*)
        (format t "NATIVE_DECODED_DECISION_PASS branch-cases=30 repetitions=20000 scope=process-inclusive~%")
        :passed))))
