;;; Actual private operation constructor, source continuation and TCPCL ACK
;;; consumer. Typed grant/I/O/durable callback are recorded; no image claim.
(load "tests/native_bp_session_bank_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-bp-observation (wall wall-error)
  (declare (ignorable wall wall-error))
  (harness-stub-reached 'fnn-bp-observation "host/native/bp.lisp"))
(defun fnn-bpnode-budgeted (event)
  (declare (ignorable event))
  (harness-stub-reached 'fnn-bpnode-budgeted "host/native/bp-node.lisp"))
(defun fnn-bpnode-forward-result (bp sent session-id result wall wall-error)
  (declare (ignorable bp sent session-id result wall wall-error))
  (harness-stub-reached 'fnn-bpnode-forward-result "host/native/bp-node.lisp"))
(defun fnn-bpnode-pause-at-durable-cut (selector marker)
  (declare (ignorable selector marker))
  (harness-stub-reached 'fnn-bpnode-pause-at-durable-cut "host/native/bp-node.lisp"))
(defun fnn-bps-drive-effects (service effects)
  (declare (ignorable service effects))
  (harness-stub-reached 'fnn-bps-drive-effects "host/native/bp-service.lisp"))
(defun fnn-bps-foundation-step (service event)
  (declare (ignorable service event))
  (harness-stub-reached 'fnn-bps-foundation-step "host/native/bp-service.lisp"))
(defun fnn-graceful-close (fd)
  (declare (ignorable fd))
  (harness-stub-reached 'fnn-graceful-close "host/native/io.lisp"))
(defun fnn-refuse (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-refuse "host/native/io.lisp"))
(defun fnn-tcl-params (node-id peer keepalive segment-mru transfer-mru)
  (declare (ignorable node-id peer keepalive segment-mru transfer-mru))
  (harness-stub-reached 'fnn-tcl-params "host/native/tcpcl.lisp"))
(defun fnn-tcl-stage (conn xfer-id octets)
  (declare (ignorable conn xfer-id octets))
  (harness-stub-reached 'fnn-tcl-stage "host/native/tcpcl.lisp"))
(defun fnn-tcl-summary (conn)
  (declare (ignorable conn))
  (harness-stub-reached 'fnn-tcl-summary "host/native/tcpcl.lisp"))
;;; ---- derived stubs: END ----
(defvar *fnn-tcl-source-turn* nil)
(defvar *fnn-tcl-deliver* nil)
(defvar *fnn-tcl-deliver-counted* nil)
(defmacro mv (&rest xs) `(values ,@xs))
(defmacro mv-let (names expression &body body) `(multiple-value-bind ,names ,expression ,@body))
(defun fn-cbor-octetp (x) (and (integerp x) (<= 0 x 255)))
(defun fnn-make-octets (n) (make-array n :element-type '(unsigned-byte 8) :initial-element 0))
(dolist (path '("books/tcpcl-segment-source-cursor.lisp" "books/bp-session-received-source.lisp"))
 (with-open-file (stream path)
  (loop for form = (read stream nil :eof) until (eq form :eof) do
   (when (and (consp form) (eq (first form) 'defun))
    (eval (cons 'defun (cons (second form) (cons (third form)
     (remove-if (lambda (x) (and (consp x) (eq (car x) 'declare))) (cdddr form))))))))))
(define-condition fnn-store-indeterminate (error) ((message :initarg :message)))
(with-open-file (stream "host/native/tcpcl.lisp")
 (loop for form = (read stream nil :eof) until (eq form :eof) do
  (when (and (consp form)
   (or (and (eq (first form) 'define-condition) (eq (second form) 'fnn-tcl-source-indeterminate))
       (and (eq (first form) 'defun) (member (second form)
        '(fnn-tcl-source-escape fnn-tcl-source-disposition fnn-tcl-source-tick fnn-tcl-act
          fnn-tcl-settle-delivery fnn-tcl-deliver-transfer))))) (eval form))))
(defvar *flushes* 0)
(defvar *publications* 0)
(defun fnn-tcl-flush (conn) (declare (ignore conn)) (incf *flushes*))
(defvar *bank-recording-core* (symbol-function 'fnn-core))
(defun fnn-core (name &rest args)
 (case name
  ((fn-tcim-turn fn-bpsrx-start fn-bpsrx-turn fn-bpsrx-authorizedp fn-bpsrx-abort-plan fn-tsc-at fn-bpsg-step fn-bpsg-release-ready) (apply name args))
  (fn-tclsctl-turn (list (first args) nil))
  (fn-tcl-source-result-action (if (eq (caar args) :source-yield) :retain :settle))
  (fn-tcl-source-result-token (cadar args))
  (fn-tcl-delivery-plan (third args))
  (fn-tcl-delivery-plan-status (caar args))
  (fn-tcl-delivery-plan-messages nil)
  (fn-tcl-delivery-plan-progress-p t)
  (fn-tcl-delivery-plan-detail nil)
  (otherwise (apply *bank-recording-core* name args))))
(defun source-case (cut)
 (let* ((bank (test-bank)) (conn (make-fnn-tcl-conn))
        (grant (test-grant bank 2 :incoming :socket conn))
        (root (list (loop for i from 500 below 1000 collect (mod i 256)) nil
                    (loop for i below 500 collect (mod i 256))))
        (*flushes* 0) (*publications* 0) (turns 0) (failed nil)
        (*fnn-tcl-source-start* (lambda (c id chain count)
          (fnn-bp-session-source-start grant c id chain count 1000)))
        (*fnn-tcl-source-turn* (lambda (c token) (fnn-bp-session-source-turn grant c token)))
        (*fnn-tcl-deliver* (lambda (c id bytes)
          (declare (ignore c)) (assert (= id 7)) (assert (zerop *flushes*))
          (incf *publications*)
          (assert (equal bytes (loop for i below 1000 collect (mod i 256))))
          (when (eq cut :publication) (error "recording durable publication cut"))
          '(:accepted nil))))
  (fnn-tcl-act conn (list '(:send (:xfer-ack 3 7 1000))
                          (list :bundle-segments-received 7 root 1000)))
  (assert (fnn-tclc-source-pending conn)) (assert (zerop *publications*))
  (loop repeat 100 while (fnn-tclc-source-pending conn) until failed do
   (incf turns)
   (when (and (eq cut :generation) (= turns 2))
    (setf (fnn-bpsg-row grant) (fn-bpsg-row 2 2 :incoming)))
   (let ((before (fnn-bpsrx-offset (fnn-tclc-source-token conn))))
    (handler-case (fnn-tcl-source-tick conn) (fnn-tcl-source-indeterminate () (setf failed t)))
    (when (fnn-tclc-source-token conn)
     (assert (<= (- (fnn-bpsrx-offset (fnn-tclc-source-token conn)) before) 64)))))
  (if cut
   (progn
    (assert failed) (assert (fnn-tclc-fenced conn))
    (assert (eq (fnn-tclc-source-root conn) root)) (assert (fnn-tclc-source-token conn))
    (assert (zerop *flushes*))
    (assert (= *publications* (if (eq cut :publication) 1 0)))
    (let ((before *publications*))
     (assert (handler-case (progn (fnn-tcl-source-tick conn) nil) (fnn-tcl-source-indeterminate () t)))
     (assert (= *publications* before))))
   (progn
    (assert (> turns 16)) (assert (= *publications* 1)) (assert (= *flushes* 1))
    (assert (= (fnn-tclc-accepted conn) 1)) (assert (null (fnn-tclc-source-root conn)))))))
(source-case nil)
(source-case :generation)
(source-case :publication)
(format t "PASS actual incoming grant -> bounded received source -> one durable callback/END ACK; stale generation and publication cut retain/fence exact borrow.~%")

;;; Actual loop cadence: a private source action keeps one bounded slot sweep
;;; awake, while every local service and independent slot still rotates.
(defvar *idle-waits* 0)
(defun fnn-bp-session-idle-wait () (incf *idle-waits*))
(let* ((bank (test-bank)) (conn (make-fnn-tcl-conn))
       (grant (test-grant bank 2 :incoming :socket conn))
       (root (list (make-list 16384 :initial-element 65)))
       (*accepted* 2) (*idle-waits* 0) (*flushes* 0) (services nil) (turns 0)
       (*fnn-tcl-source-start* (lambda (c id chain count)
        (fnn-bp-session-source-start grant c id chain count 16384)))
       (*fnn-tcl-source-turn* (lambda (c token) (fnn-bp-session-source-turn grant c token)))
       (*fnn-tcl-deliver* (lambda (c id bytes)
        (declare (ignore c id)) (assert (= (length bytes) 16384)) '(:accepted nil))))
 (fnn-tcl-act conn (list '(:send (:xfer-ack 3 7 16384))
                        (list :bundle-segments-received 7 root 16384)))
 (setf (fnn-bpsg-turn grant)
  (lambda () (incf turns) (fnn-tcl-source-tick conn)
   (if (fnn-tclc-source-pending conn) (values :work :source)
    (progn (setf (fnn-tclc-finished conn) t) (values :done :source)))))
 (catch 'finished
  (fnn-bp-session-loop bank nil :listeners (lambda (&rest xs) (declare (ignore xs))) nil
   (lambda (action) (pushnew action services)
    (when (zerop (hash-table-count (fnn-bpsb-held bank))) (throw 'finished t)))
   (lambda () nil)))
 (assert (> turns 256)) (assert (= (length services) 8))
 (assert (zerop *idle-waits*)) (assert (= *flushes* 1)))
(let ((bank (test-bank)) (*accepted* 2) (*idle-waits* 0) (services 0))
 (catch 'finished
  (fnn-bp-session-loop bank nil :listeners (lambda (&rest xs) (declare (ignore xs))) nil
   (lambda (action) (declare (ignore action))
    (incf services) (when (= services 10) (throw 'finished t))) (lambda () nil)))
 (assert (= *idle-waits* 9)))
(format t "PASS actual node cadence: 16384-byte private source/all8 services with zero artificial sleeps; idle node retains waits.~%")

;;; Actual teardown: only the known pre-publication private operation may be
;;; retired. Independent physical close controls return; publication entry and
;;; unknown providers keep their root/Store authority held.
(dolist (phase '(:copy :convert :publish :publishing :foreign))
 (dolist (physical '(:closed :unobserved))
  (let* ((bank (test-bank)) (conn (make-fnn-tcl-conn))
         (grant (test-grant bank 2 :incoming :socket conn))
         (root '((65 66))) (*close-receipt* physical) (*flushes* 0)
         (job (second (fnn-bp-session-source-start grant conn 7 root 2 2)))
         (private (member phase '(:copy :convert :publish))))
   (setf (fnn-tclc-source-pending conn) t (fnn-tclc-source-root conn) root
         (fnn-tclc-source-held conn) '(:end-ack) (fnn-tclc-held conn) '(:end-ack)
         (fnn-tclc-source-token conn) (if (eq phase :foreign) :foreign job)
         (fnn-bpsg-turn grant) (lambda () (error "retired turn ran"))
         (fnn-bpsg-finish grant) (lambda (&rest xs) (declare (ignore xs)) (error "retired finish ran")))
   (setf (fnn-bpsrx-phase job) phase)
   (fnn-bp-session-abort-all bank nil)
   (assert (null (fnn-bpsg-turn grant))) (assert (null (fnn-bpsg-finish grant)))
   (assert (zerop *flushes*))
   (if private
    (progn
     (assert (null (fnn-tclc-source-root conn))) (assert (null (fnn-tclc-source-token conn)))
     (assert (null (fnn-tclc-source-held conn))) (assert (null (fnn-bpsg-conn grant)))
     (assert (fifth (fnn-bpsg-row grant)))
     (assert (eq (not (null (gethash grant (fnn-bpsb-held bank)))) (eq physical :unobserved))))
    (progn
     (assert (eq (fnn-tclc-source-root conn) root)) (assert (fnn-tclc-source-token conn))
     (assert (gethash grant (fnn-bpsb-held bank))) (assert (not (fifth (fnn-bpsg-row grant)))))))))
(format t "PASS private pre-publication retirement: copy/convert/publish drop aliases without ACK; publishing/foreign remain held; ambiguous physical close never returns grant.~%")
