; SCN-1100 actual init + command bodies and ACL2 compatibility decision.
; Exact codec observations have separate ACL2 teeth; this host fixture seeds
; their decoder outputs and records effects without touching a real store.
(require :sb-posix)
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(declaim (declaration xargs))
(defmacro include-book (&rest args) (declare (ignore args)) nil)
(defmacro defthm (&rest args) (declare (ignore args)) nil)
(defun fn-record-parse-ok (value rest) (list :ok value rest))
(defun fn-record-parse-okp (value) (eq (first value) :ok))
(defun fn-record-parse-value (value) (second value))
(defun fn-cfg-record-shapep (value) (and (listp value) (= (length value) 5)))
(defun fn-cfg-record-sequence (value) (first value))
(defun fn-cfg-record-txid (value) (second value))
(defun fn-cfg-record-generation (value) (third value))
(defun fn-cfg-record-change (value) (fourth value))
(defun fn-cfg-decode-exact (octets)
  (cond ((equal octets '(1)) (fn-record-parse-ok '(0 0 1 (:initial-groups) :old-stamp) nil))
        ((equal octets '(2)) (fn-record-parse-ok '(0 0 1 (:other-groups) :old-stamp) nil))
        ((equal octets '(3)) (fn-record-parse-ok '(0 0 1 (:initial-groups) :new-stamp) nil))
        ((equal octets '(5)) (fn-record-parse-ok '(0 0 2 (:initial-groups) :new-stamp) nil))
        (t '(:error :invalid))))
(load "books/native-init-resume.lisp")

(defparameter +fnn-default-groups+ '("fn.test"))
(defparameter +fnn-config-record-bytes+ 16384)
(defparameter +fnn-lock-un+ 8)
(defparameter +fnn-exit-ok+ 0)
(defparameter *effects* nil)
(defparameter *output* nil)
(defparameter *fixture-profile* :development)
(defparameter *fixture-record* #(3))
(defparameter *fixture-history* '("00000001.cfg" "00000002.cfg"))
(defparameter *config-present* t)
(defparameter *injected-decision* nil)
(defstruct fixture-store root config sealed-config)
(define-condition fixture-refusal (error) ((text :initarg :text)))
(define-condition fixture-fault (error) ())
(defun fnn-refuse (control &rest args)
  (error 'fixture-refusal :text (apply #'format nil control args)))
(defun fnn-fault (&rest args) (declare (ignore args)) (error 'fixture-fault))
(defun fnn-indeterminate (&rest args) (declare (ignore args)) (error 'fixture-fault))
(defun source-forms (path names)
  (with-open-file (in path)
    (loop for form = (read in nil :eof) until (eq form :eof)
          when (and (consp form) (eq (car form) 'defun) (member (second form) names))
          do (progn (eval form) (setf names (remove (second form) names))
                    (when (null names) (return)))
          finally (assert (null names)))))

(defun make-fnn-store (root &rest args)
  (declare (ignore args)) (make-fixture-store :root root))
(defun fnn-store-root (store) (fixture-store-root store))
(defun fnn-store-config (store) (fixture-store-config store))
(defun (setf fnn-store-config) (value store) (setf (fixture-store-config store) value))
(defun fnn-store-sealed-config (store) (fixture-store-sealed-config store))
(defun (setf fnn-store-sealed-config) (value store) (setf (fixture-store-sealed-config store) value))
(defun fnn-store-close (store) (declare (ignore store)) t)
(defun fnn-init-test-fault () nil)
(defun fnn-core (entry &rest args)
  (case entry
    (fn-store-profile-logp t)
    (fn-nir-resume-decision (or *injected-decision* (apply #'fn-nir-resume-decision args)))
    (fn-nir-resume-line (apply #'fn-nir-resume-line args))
    (otherwise (error "Unexpected ACL2 dispatch ~s" entry))))
(defun fnn-metadata-config-frame (profile) profile)
(defun fnn-metadata-config-decode (frame) frame)
(defun fnn-config-path (store) (declare (ignore store)) "/fixture/config.json")
(defun fnn-config-record-path (store gen) (declare (ignore store gen)) "/fixture/config/00000001.cfg")
(defun fnn-staging (store) (declare (ignore store)) "/fixture/staging")
(defun fnn-config-dir (store) (declare (ignore store)) "/fixture/config")
(defun fnn-journal-dir (store) (declare (ignore store)) "/fixture/journal")
(defun fnn-lstat (path)
  (cond ((equal path "/fixture/config.json") *config-present*)
        ((equal path "/fixture/config") (and *fixture-history* t))
        (t (and *fixture-record* t))))
(defun fnn-load-config (store)
  (setf (fnn-store-sealed-config store) *fixture-profile*
        (fnn-store-config store) :later-live-limit-overlay))
(defun fnn-check-regular (path) (declare (ignore path)) t)
(defun fnn-read-regular-bounded (path bound)
  (declare (ignore path)) (assert (= bound +fnn-config-record-bytes+)) *fixture-record*)
(defun fnn-octet-list (octets) (coerce octets 'list))
(defun fnn-bridge-config-initial (groups)
  (if (equal groups '("fn.test")) #(1) #(2)))
(defun fnn-safe-directory (path &rest args)
  (declare (ignore args))
  ;; An existing store with history already has its required directories.
  (unless (or (equal path "/fixture") (and *config-present* *fixture-history*))
    (push :mkdir *effects*)))
(defun fnn-require-clone-activated (store) (declare (ignore store)) t)
(defun fnn-open-lock (&rest args) (declare (ignore args)) 10)
(defun fnn-init-cut (&rest args) (declare (ignore args)) nil)
(defun fnn-flock (&rest args) (declare (ignore args)) t)
(defun fnn-close (&rest args) (declare (ignore args)) t)
(defun fnn-publish-initial-file (store path bytes &rest args)
  (declare (ignore store args))
  (push :publish *effects*)
  (if (and (equal path "/fixture/config.json") *config-present*) :existing
    (progn
      (if (equal path "/fixture/config.json") (setf *config-present* t)
        (setf *fixture-record* bytes *fixture-history* '("00000001.cfg")))
      :published)))
(defun fnn-config-record-names (&rest args) (declare (ignore args)) *fixture-history*)
(defun fnn-fsync-dir (&rest args) (declare (ignore args)) (push :fence *effects*))
(defun fnn-fsync-regular (&rest args) (declare (ignore args)) (push :fence *effects*))
(defun fnn-log-init-genesis (&rest args) (declare (ignore args)) (push :genesis *effects*))
(defun fnn-log-init-segment (&rest args) (declare (ignore args)) (push :segment *effects*))
(defun fnn-parent (path) path)
(defun fnn-join (a b) (concatenate 'string a "/" b))
(defun fnn-record-filesystem-at-init (&rest args) (declare (ignore args)) (push :filesystem *effects*))
(defun fnn-acquire (&rest args) (declare (ignore args)) t)
(defun fnn-node-secret-create (&rest args) (declare (ignore args)) (push :secret *effects*))
(defun fnn-out (control &rest args) (setf *output* (apply #'format nil control args)))

(source-forms "host/native/io.lisp" '(fnn-initialize-resume-check))
(source-forms (or (second sb-ext:*posix-argv*) "host/native/io.lisp") '(fnn-initialize fnn-command-init))

(defun run-case (label groups profile expected &key (record #(3)) (history '("00000001.cfg" "00000002.cfg")) (config t) decision)
  (let* ((*effects* nil) (*output* nil) (*fixture-record* record)
         (*fixture-history* history) (*config-present* config) (*injected-decision* decision)
         (code (handler-case (fnn-command-init "/fixture" groups profile)
                 (fixture-refusal () 1) (fixture-fault () 4))))
    (assert (= code expected))
    (if (zerop code)
        (progn (assert (member :genesis *effects*)) (assert (member :secret *effects*))
               (assert (search "initialized" *output*)))
      (progn (assert (null *effects*)) (assert (null *output*))))
    (format t "~a code=~d effects=~s~%" label code (reverse *effects*))))

(run-case "profile-mismatch" '("fn.test") :production 1)
(run-case "groups-mismatch" '("fn.other") :development 1)
(run-case "same-sealed-despite-live-overlay-and-new-stamp" '("fn.test") :development 0)
(run-case "interrupted-before-gen1" '("fn.test") :development 0 :record nil :history nil)
(run-case "corrupt-gen1" '("fn.test") :development 4 :record #(4))
(run-case "wrong-generation" '("fn.test") :development 4 :record #(5))
(run-case "missing-gen1-with-history" '("fn.test") :development 4 :record nil)
(run-case "fresh-init" '("fn.test") :development 0 :record nil :history nil :config nil)
(run-case "unknown-core-decision" '("fn.test") :development 4 :decision '(:unexpected :resume))
(format t "SOURCE INIT RESUME PASSED~%")
