;;; Actual ACL2 serial producer and native retained-result helpers/queue entry.
(load "tests/native_actor_envelope_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-owner-syncer-physical (service grant receipt)
  (declare (ignorable service grant receipt))
  (harness-stub-reached 'fnn-owner-syncer-physical "host/native/owner.lisp"))
;;; ---- derived stubs: END ----
(defmacro mv (&rest xs) `(values ,@xs))
(defmacro mv-let (vars form &body body) `(multiple-value-bind ,vars ,form ,@body))
(defun true-listp (x) (or (null x) (and (consp x) (true-listp (cdr x)))))
(defun len (x) (length x))
;; Actual pure definitions, only ACL2 declarations removed for SBCL execution.
(with-open-file (s "books/response-identity.lisp")
  (loop for f = (read s nil :eof) until (eq f :eof)
        when (and (consp f) (eq (car f) 'defun))
        do (eval (append (subseq f 0 3) (remove-if (lambda (x) (and (consp x) (eq (car x) 'declare))) (nthcdr 3 f))))))
(load-deployed-forms "host/native/owner.lisp"
 '((defun fnn-owner-connection-identity-locked) (defun fnn-owner-response-identity-locked) (defun fnn-owner-response-identity)))
(load-deployed-forms "host/native/mux.lisp"
 '((defstruct (fnn-mux-loop (:constructor %make-fnn-mux-loop)))
   (defstruct (fnn-mux-conn (:constructor %make-fnn-mux-conn)))
   (defun fnn-mux-queue-plan)))
(defvar *identity-calls* nil)
(defun fnn-call (subject &rest args)
  (push (cons subject args) *identity-calls*)
  (multiple-value-list (apply (symbol-function subject) args)))
(defun fnn-owner-serialized (service cid thunk &optional class)
  (declare (ignore cid class))
  (sb-thread:with-mutex ((fnn-owner-service-lock service)) (funcall thunk)))
(defun fnn-mux-service (loop) (fnn-mux-loop-service loop))
(defvar *seen-before-factory* nil)
(defun fnn-mux-render-next (loop conn plan)
  (declare (ignore loop))
  (push (list (fnn-mux-conn-response-identity conn) plan) *seen-before-factory*)
  (values #() plan nil t))
(defun fnn-mux-plan-yield (loop conn rest after cursorp)
  (declare (ignore loop after cursorp)) (setf (fnn-mux-conn-plan conn) rest))
(defun fnn-mux-queue (&rest xs) (declare (ignore xs)) (error "unexpected output"))
(defun fnn-mux-after (&rest xs) (declare (ignore xs)) (error "unexpected response terminal"))
(let* ((s (%make-fnn-owner-service :lock (sb-thread:make-mutex :name "actual recorded O")))
       (c1 (fnn-owner-connection-identity-locked s 17))
       (c2 (fnn-owner-connection-identity-locked s 17))
       (loop (%make-fnn-mux-loop :service s))
       (conn (%make-fnn-mux-conn :cid 17 :connection-identity c2))
       (plan (list :retained-cursor)))
  (check (equal c1 '(:connection 17 1)) "first admitted lifetime")
  (check (equal c2 '(:connection 17 2)) "same CID independent new lifetime")
  (fnn-mux-queue-plan loop conn plan :next)
  (let ((id (fnn-mux-conn-response-identity conn)) (calls (length *identity-calls*)))
    (check (equal id '(:response 17 2 1)) "ACL2 response keeps exact connection generation")
    (check (eq (fnn-mux-conn-plan conn) plan) "original cursor retained")
    (fnn-mux-queue-plan loop conn plan :next)
    (check (eq id (fnn-mux-conn-response-identity conn)) "resume retains exact identity object")
    (check (= calls (length *identity-calls*)) "resume does not reserve another operation"))
  (check (every (lambda (row) (and (first row) (eq (second row) plan))) *seen-before-factory*)
         "identity precedes every actual render factory entry")
  (setf (fnn-owner-service-response-generation s) 18446744073709551615
        (fnn-mux-conn-response-identity conn) nil)
  (let ((before (length *seen-before-factory*)))
    (check (handler-case (progn (fnn-mux-queue-plan loop conn plan :next) nil)
             (serious-condition () t)) "exhaustion signals before materialization")
    (check (= before (length *seen-before-factory*)) "no factory on exhausted serial")
    (check (= (fnn-owner-service-response-generation s) 18446744073709551615) "no wrap")))
(format t "native_response_identity_raw: PASS actual producer/native capture/pre-render/resume/exhaustion~%")
