(load "tests/native_store_cleanup_source.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-checkpoint-test-stop (point)
  (declare (ignorable point))
  (harness-stub-reached 'fnn-checkpoint-test-stop "host/native/checkpoint.lisp"))
(defun fnn-clone-fence-path (s)
  (declare (ignorable s))
  (harness-stub-reached 'fnn-clone-fence-path "host/native/io.lisp"))
(defun fnn-core-state (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-core-state "host/native/io.lisp"))
(defun fnn-fsync-dir (path)
  (declare (ignorable path))
  (harness-stub-reached 'fnn-fsync-dir "host/native/io.lisp"))
(defun fnn-out (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-out "host/native/io.lisp"))
(defun fnn-owner-consumer-commit (service event)
  (declare (ignorable service event))
  (harness-stub-reached 'fnn-owner-consumer-commit "host/native/owner.lisp"))
(defun fnn-write-all (fd octets)
  (declare (ignorable fd octets))
  (harness-stub-reached 'fnn-write-all "host/native/io.lisp"))
;;; ---- derived stubs: END ----
(defvar *fnn-clone-copy-bytes* 0)
(defconstant +fnn-o-nofollow+ 0)
(defconstant +fnn-exit-ok+ 0)
(defvar *body-fails* nil)
(defvar *body-condition* (make-condition 'simple-error :format-control "copy body failed"))
(defun fnn-open (path flags &optional mode)
  (declare (ignore flags mode)) (if (equal path "input") :input :output))
(defun fnn-fstat (fd) (declare (ignore fd)) (sb-posix:stat "/dev/null"))
(defun fnn-regular-p (info) (declare (ignore info)) t)
(defun fnn-make-octets (count) (make-array count :element-type '(unsigned-byte 8)))
(defun fnn-read-fd (&rest ignored) (declare (ignore ignored)) 0)
(defun fnn-fsync-file (fd)
  (declare (ignore fd)) (when *body-fails* (error *body-condition*)))
(defun fnn-fault (&rest ignored) (declare (ignore ignored)) (error *body-condition*))
(defun fnn-refuse (&rest ignored) (declare (ignore ignored)) (error *body-condition*))
(defun fnn-indeterminate (&rest ignored) (declare (ignore ignored)) (error *body-condition*))
(defun fnn-clone-canonical-target (path) path)
(defun fnn-clone-read-marker (path) (declare (ignore path)) '(0))
(defun fnn-octet-list (value) value)
(defun fnn-core (name &rest ignored)
  (declare (ignore ignored))
  (case name (fn-cpe-decode-exact '(:ok :event)) (otherwise (error "unexpected core"))))
(defstruct (fnn-owner-service (:constructor %make-fnn-owner-service)) store)
(defun fnn-owner-install (&rest ignored)
  (declare (ignore ignored)) (%make-fnn-owner-service :store :store))
(defun fnn-owner-core (&rest ignored)
  (declare (ignore ignored)) (if *body-fails* (error *body-condition*) :completed))
(defun fnn-owner-feed-close-all (&rest ignored)
  (declare (ignore ignored)) (record-call :feeds))
(defun fnn-store-close (&rest ignored) (declare (ignore ignored)) (record-call :store))
(defun fnn-open-live-store (&rest ignored)
  (declare (ignore ignored)) (record-call :reopen) (error "should not reopen"))
(with-open-file (input "host/native/checkpoint.lisp")
  (loop for form = (read input nil :eof) until (eq form :eof) do
    (when (and (consp form) (eq (car form) 'defun)
               (member (second form) '(fnn-clone-copy-regular fnn-clone-activate)))
      (eval form))))
(dolist (body-fails '(t nil))
  (let ((*body-fails* body-fails) (*calls* nil) (*failures* '(:output)) (caught nil))
    (handler-case (fnn-clone-copy-regular "input" "output" 100)
      (error (e) (setq caught e)))
    (assert (eq caught (if body-fails *body-condition* *condition*)))
    (assert (equal (reverse *calls*) '(:output :input)))))
(dolist (body-fails '(t nil))
  (let ((*body-fails* body-fails) (*calls* nil) (*failures* '(:feeds)) (caught nil))
    (handler-case (fnn-clone-activate "/unused") (error (e) (setq caught e)))
    (assert (eq caught (if body-fails *body-condition* *condition*)))
    (assert (equal (reverse *calls*) '(:feeds :store)))))
(format t "PASS actual checkpoint: independent file/owner cleanup; primary preserved; no reopen after cleanup failure.~%")
