; Actual host journal body + actual ACL2 stream fold; physical observations
; are deterministic seams. Replay uses the actual reference fn-otm-replay
; with start/note environment operations supplied by this lifecycle fixture.
(require :sb-posix)
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(declaim (declaration xargs))
(defmacro include-book (&rest args) (declare (ignore args)) nil)
(defmacro local (&rest args) (declare (ignore args)) nil)
(defmacro defthm (&rest args) (declare (ignore args)) nil)
(defmacro mv (&rest args) `(values ,@args))
(defmacro mv-let (names expr &body body) `(multiple-value-bind ,names ,expr ,@body))
(defun natp (x) (and (integerp x) (<= 0 x)))
(defun nfix (x) (if (natp x) x 0))
(defun true-list-fix (x) (if (consp x) (cons (car x) (true-list-fix (cdr x))) nil))
(defun len (x) (length (true-list-fix x)))
(defun update-nth (n value xs)
  (if (zerop n) (cons value (cdr xs))
    (cons (car xs) (update-nth (1- n) value (cdr xs)))))
(defun nat-listp (xs) (and (listp xs) (every #'natp xs)))
(defun fn-otm-init () 0)
(defun fn-otm-jseq (s) s)
(defun fn-otm-note (s a b) (declare (ignore a b)) (values (1+ s) nil))
(defun fn-otm-kind-of-op (op) (declare (ignore op)) nil)
(defun fn-osch-text (text) (map 'list #'char-code text))
(defun fn-osch-decimal (n) (fn-osch-text (format nil "~d" (nfix n))))
(defun fn-osch-kv (key n) (append (fn-osch-text (concatenate 'string " " key "=")) (fn-osch-decimal n)))
(defun source-functions (path names)
  (with-open-file (in path)
    (loop for form = (read in nil :eof) until (eq form :eof)
          when (and (consp form) (eq (car form) 'defun) (member (second form) names))
          do (progn (eval form) (setf names (remove (second form) names))
                    (when (null names) (return)))
          finally (assert (null names)))))
(source-functions "books/owner-time-journal.lisp" '(fn-otm-revonto fn-otm-replay fn-otm-verdict-text))
(load "books/owner-time-journal-stream.lisp")

(defparameter +fnn-o-nofollow+ #x20000)
(defparameter *fixture-bytes* #())
(defparameter *fixture-size* 0)
(defparameter *fixture-present* t)
(defparameter *fixture-regular* t)
(defparameter *fixture-read-fault* nil)
(defparameter *fixture-core-fault* nil)
(defparameter *fixture-fstat-fault* nil)
(defparameter *fixture-short-read* nil)
(defparameter *position* 0)
(defparameter *closed* 0)
(defparameter *opened* 0)
(defparameter *allocations* nil)
(defparameter *report* nil)
(define-condition fixture-refusal (error) ())
(define-condition fixture-fault (error) ())
(defun fnn-refuse (&rest args) (declare (ignore args)) (error 'fixture-refusal))
(defun fnn-fault (&rest args) (declare (ignore args)) (error 'fixture-fault))
(defun fnn-join (a b) (concatenate 'string a "/" b))
(defun fnn-check-regular (path) (declare (ignore path)) *fixture-present*)
(defun fnn-open (path flags)
  (declare (ignore path))
  (assert (not (zerop (logand flags +fnn-o-nofollow+))))
  (assert (not (zerop (logand flags sb-posix:o-nonblock))))
  (incf *opened*) 10)
(defun fnn-fstat (fd)
  (assert (= fd 10))
  (when *fixture-fstat-fault* (error 'fixture-fault))
  (let ((info (make-instance 'sb-posix:stat)))
    (setf (slot-value info 'sb-posix::size) *fixture-size*) info))
;; The actual host uses the size captured by fstat, independently of later
;; available bytes (append fixture). Set this field through SBCL's accessor.
(defun fnn-regular-p (info)
  (declare (ignore info)) *fixture-regular*)
(defun fnn-close (fd) (assert (= fd 10)) (incf *closed*))
(defun fnn-nat (x) (assert (natp x)) x)
(defun fnn-make-octets (n)
  (assert (<= n 65536)) (push n *allocations*)
  (make-array n :element-type '(unsigned-byte 8)))
(defun fnn-octet-list (xs) (coerce xs 'list))
(defun fnn-read-fd (fd buffer)
  (assert (= fd 10))
  (when *fixture-read-fault* (error 'fixture-fault))
  (let ((count (min (length buffer) (- (length *fixture-bytes*) *position*)
                    (or *fixture-short-read* (length buffer)))))
    (replace buffer *fixture-bytes* :start2 *position* :end2 (+ *position* count))
    (incf *position* count) count))
(defun fnn-core (entry &rest args)
  (when (eq entry *fixture-core-fault*) (error 'fixture-fault))
  (when (member entry '(fn-otjs-consume fn-otm-journal-report fn-otm-journal-exit))
    (assert (<= (length (first args)) 65536)))
  (apply (symbol-function entry) args))
(defun fnn-write-report (octets) (setf *report* (coerce (mapcar #'code-char octets) 'string)))
(source-functions (or (second sb-ext:*posix-argv*) "host/native/io.lisp") '(fnn-command-store-journal))

(defun run-case (label text expected &key size (present t) (regular t) read-fault core-fault fstat-fault short-read)
  (let* ((*fixture-bytes* (map 'vector #'char-code text))
         (*fixture-size* (or size (length text))) (*fixture-present* present)
         (*fixture-regular* regular) (*fixture-read-fault* read-fault)
         (*fixture-core-fault* core-fault) (*fixture-fstat-fault* fstat-fault)
         (*fixture-short-read* short-read) (*position* 0) (*closed* 0)
         (*opened* 0) (*allocations* nil) (*report* nil)
         (code (handler-case (fnn-command-store-journal "/fixture")
                 (fixture-refusal () 1) (fixture-fault () 4))))
    (assert (= code expected))
    (assert (= *closed* *opened*))
    (when (and (= code 0) present regular)
      (assert (= *position* *fixture-size*)) (assert *report*))
    (when (= code 4) (assert (null *report*)))
    (format t "~a code=~d closed=~d windows=~d max=~d report=~s~%"
            label code *closed* (length *allocations*)
            (reduce #'max *allocations* :initial-value 0) *report*)
    (values *report* *position* (length *allocations*))))

(when (third sb-ext:*posix-argv*)
  ;; Actual prior host function opens the real scratch journal through its
  ;; old CL stream. This observation rejects a whole-file ACL2 input window;
  ;; its assertion must fail before any unavailable legacy renderer is called.
  (fnn-command-store-journal (third sb-ext:*posix-argv*))
  (error "prior source unexpectedly preserved the input window bound"))

(run-case "absent" "" 1 :present nil)
(run-case "nonregular-replacement" "" 4 :regular nil)
(run-case "fstat-error-close" "" 4 :fstat-fault t)
(run-case "read-error-close" "0 0 0 0 0 0 0
" 4 :read-fault t)
(run-case "core-error-close" "0 0 0 0 0 0 0
" 4 :core-fault 'fn-otjs-consume)
(run-case "shortened" "0 0" 1 :size 40)
(let ((line "0 0 0 0 0 0 0
"))
  (multiple-value-bind (report consumed windows)
      (run-case "captured-prefix-ignores-append" (concatenate 'string line line) 0 :size (length line) :short-read 3)
    (declare (ignore windows))
    (assert (= consumed (length line)))
    (assert (search "entries=1 segments=1 status=whole replay=agrees" report)))
  (let ((large (with-output-to-string (out) (dotimes (i 160000) (write-string line out)))))
    (multiple-value-bind (report consumed windows) (run-case "large-journal" large 0)
      (assert (> consumed 2000000)) (assert (> windows 30))
      (assert (search "entries=160000 segments=160000 status=whole replay=agrees" report)))))
(run-case "first-replay-gap-retained" "0 0 0 0 0 0 0
3 5 0 1 2 0 0
0 0 0 0 0 0 0
" 1)
(format t "SOURCE JOURNAL STREAM PASSED~%")
