;;; Actual native private controller envelope. Typed/controller functions are
;;; recording boundaries here; their real loaded-world probe is independent.
(load "tests/native_section_envelope_raw.lisp")
(unless (find-package "ACL2_*1*_ACL2") (defpackage "ACL2_*1*_ACL2" (:use "CL")))
(in-package "ACL2")
(load-deployed-forms "host/native/extent.lisp"
 '((defstruct (fnn-cold-worker (:constructor %make-fnn-cold-worker))) (defmacro fnn-core-cold-pool)))
(defvar *fnn-extent-lock* (sb-thread:make-mutex :name "decoded fixture E"))
(defvar *fnn-extent-fds* (make-hash-table))
(defvar *fnn-extent-incarnations* (make-hash-table))
(load-deployed-forms "host/native/extent-decoded.lisp"
 '((defstruct fnn-decoded-activation) (defmacro fnn-decoded-semantic)
   (defun fnn-extent-decoded-window-pread)
   (defun fnn-extent-decoded-window-run)))
(defvar *decoded-calls* nil)
(defvar *decoded-permitted* t)
(defvar *decoded-cut* nil)
(defvar *decoded-actions* nil)
(defvar *decoded-job* nil)
(defun fnn-live-page-read-pool () :same-pool)
(defun fnn-cold-call (subject &rest args)
  (push (cons subject args) *decoded-calls*)
  (assert (eq subject 'fn-owner-page-window-work-permittedp))
  (list *decoded-permitted*))
(defun fnn-core (subject &rest args)
  (push (cons subject args) *decoded-calls*)
  (case subject
    (fn-pwz-nth (assert (equal args '(2 :token))) 7)
    (create-fn-decoded-job
     (when (eq *decoded-cut* :creator) (error "creator cut"))
     *decoded-job*)
    (otherwise (error "unexpected decoded core subject ~s" subject))))
(defun fnn-call (subject &rest args)
  (push (cons subject args) *decoded-calls*)
  (when (eq subject *decoded-cut*) (error "semantic cut"))
  (case subject
    (fn-owner-page-decoded-job-assign
     (assert (equal args (list :row :token :token 47 *decoded-job* :same-pool)))
     (list :decoded-assigned *decoded-job* :same-pool))
    (fn-dwj-begin (list :decoded-started *decoded-job*))
    (fn-dwj-one (append (pop *decoded-actions*) (list *decoded-job*)))
    (fn-dwj-read-observation
     (assert (equal args (list :token 3 :ok *decoded-job*)))
     (list :decoded-input *decoded-job*))
    (otherwise (error "unexpected decoded semantic subject ~s" subject))))
(defun fnn-extent-window-pread (fd input offset count)
  (assert (equal (list fd input offset count) (list 9 (svref *decoded-job* 1) 100 8)))
  (push :physical-pread *decoded-calls*) :ok)
(setf (gethash 7 *fnn-extent-fds*) 9 (gethash 7 *fnn-extent-incarnations*) 47)
(defun decoded-worker-fixture ()
  (%make-fnn-cold-worker :row :row :token :token :phase :running))
(let ((*decoded-job* (vector nil (vector (make-array 64 :element-type '(unsigned-byte 8)) 0)))
      (*decoded-actions* '((:read (:decoded-read :token 3 (:read 7 47 0 100 8))) (:ready nil)))
      (*decoded-calls* nil))
  (let* ((worker (decoded-worker-fixture)) (result (fnn-extent-decoded-window-run worker :token)))
    (assert (eq result (fnn-cold-worker-decoded worker)))
    (assert (eq (fnn-decoded-activation-stage result) :idle))
    (assert (eq *decoded-job* (fnn-decoded-activation-job result)))
    (assert (equal (mapcar (lambda (x) (if (consp x) (car x) x)) (reverse *decoded-calls*))
      '(fn-owner-page-window-work-permittedp fn-pwz-nth fn-pwz-nth create-fn-decoded-job
        fn-owner-page-decoded-job-assign fn-dwj-begin fn-owner-page-window-work-permittedp
        fn-dwj-one :physical-pread fn-dwj-read-observation
        fn-owner-page-window-work-permittedp fn-dwj-one)))))
;; Revocation prevents the expensive constructor and retains only the envelope.
(let ((*decoded-permitted* nil) (*decoded-calls* nil))
  (let ((worker (decoded-worker-fixture)))
    (assert (handler-case (progn (fnn-extent-decoded-window-run worker :token) nil) (error () t)))
    (assert (equal (mapcar #'car *decoded-calls*) '(fn-owner-page-window-work-permittedp)))
    (assert (fnn-cold-worker-decoded worker))))
;; Both failed constructor and torn private step remain physically discoverable.
(dolist (cut '(:creator fn-dwj-begin fn-dwj-one fn-dwj-read-observation))
  (let ((*decoded-cut* cut) (*decoded-calls* nil)
        (*decoded-job* (vector nil (vector (make-array 64 :element-type '(unsigned-byte 8)) 0)))
        (*decoded-actions* '((:read (:decoded-read :token 3 (:read 7 47 0 100 8))) (:ready nil))))
    (let ((worker (decoded-worker-fixture)))
      (assert (handler-case (progn (fnn-extent-decoded-window-run worker :token) nil) (error () t)))
      (let ((activation (fnn-cold-worker-decoded worker)))
        (assert (eq :calling (fnn-decoded-activation-stage activation)))
        (let ((before (length *decoded-calls*)))
          (assert (handler-case (progn (fnn-decoded-semantic (activation) (fnn-call 'fn-dwj-one :token *decoded-job*)) nil)
                    (error () t)))
          (assert (= before (length *decoded-calls*))))))))
(format t "native_decoded_worker_raw: PASS same-pool preconstructor check/retained read effect/private cut/no retry~%")
