;;; Actual native lease/mux factory functions. Typed semantic methods are
;;; recording boundaries; actual output typed/bank tests remain independent.
(load "tests/native_actor_envelope_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-owner-syncer-physical (service grant receipt)
  (declare (ignorable service grant receipt))
  (harness-stub-reached 'fnn-owner-syncer-physical "host/native/owner.lisp"))
;;; ---- derived stubs: END ----
(defvar *fnn-output-grant* nil)
(defvar *fnn-response-capture* nil)
(unless (find-package "ACL2_*1*_ACL2") (make-package "ACL2_*1*_ACL2" :use nil))
(load-deployed-forms "host/native/owner.lisp"
 '((defstruct (fnn-response-capture (:constructor %make-fnn-response-capture)))
   (defun fnn-owner-capture-reader-context)
   (defstruct (fnn-owner-cold-read (:constructor %make-fnn-owner-cold-read)))
   (defstruct (fnn-output-dependency (:constructor %make-fnn-output-dependency)))
   (defstruct (fnn-output-grant (:constructor %make-fnn-output-grant)))
   (defun fnn-owner-output-issue) (defun fnn-owner-output-dependency)
   (defun fnn-owner-output-observe-returned) (defun fnn-owner-output-receipt-locked)
   (defun fnn-owner-output-maybe-physical-locked) (defun fnn-owner-output-close)
   (defun fnn-owner-output-dependency-consumed) (defun fnn-owner-output-drained-p)))
(load-deployed-forms "host/native/extent.lisp"
 '((defstruct (fnn-cold-worker (:constructor %make-fnn-cold-worker)))))
(load-deployed-forms "host/native/mux.lisp"
 '((defstruct (fnn-mux-loop (:constructor %make-fnn-mux-loop)))
   (defstruct (fnn-mux-conn (:constructor %make-fnn-mux-conn)))
   (defun fnn-mux-render-next) (defun fnn-mux-step)))
(defvar *lease-calls* nil)
(defvar *torn-kind* nil)
(defstruct test-output-ledger token opgen output physical)
(defun fnn-refuse (&rest xs) (error "refused ~s" xs))
(defun fnn-call (subject &rest xs)
  (push (cons subject xs) *lease-calls*)
  (when (eq *torn-kind* subject) (throw 'raw-ev-fncall :torn))
  (case subject
    (fn-rlo-issue
     (destructuring-bind (cid cgen opgen dependency ledger) xs
       (check (eq dependency :issued) "conservative dependency before any factory")
       (let ((token (list :resource (list :connection cid cgen) 2 1)))
         (setf (test-output-ledger-token ledger) token (test-output-ledger-opgen ledger) opgen)
         (list :drawn token ledger))))
    ((fn-rlo-output fn-rlo-physical)
     (destructuring-bind (token opgen receipt ledger) xs
       (check (equal token (test-output-ledger-token ledger)) "exact captured token")
       (check (eql opgen (test-output-ledger-opgen ledger)) "independent captured operation")
       (if (eq subject 'fn-rlo-output) (setf (test-output-ledger-output ledger) receipt)
         (setf (test-output-ledger-physical ledger) receipt))
       (if (and (test-output-ledger-output ledger) (test-output-ledger-physical ledger))
           (progn (setf (test-output-ledger-token ledger) nil) (list :settled ledger))
         (list :pending ledger))))
    (otherwise (error "unexpected semantic boundary ~s" subject))))
(defun fnn-core (subject ledger)
  (check (eq subject 'fn-rlo-drainedp) "only genuine typed drain observation")
  (null (test-output-ledger-token ledger)))
(defun fnn-extent-executor-observe-returned (worker)
  ;; Independent physical observation of this fixture's actual held child.
  (not (sb-thread:thread-alive-p (fnn-cold-worker-thread worker))))
(defun fnn-mux-service (loop) (fnn-mux-loop-service loop))
(defun fnn-owner-render-next-quantum (service cid plan class compressedp)
  (declare (ignore service cid class compressedp))
  (check (and *fnn-output-grant* (fnn-output-grant-token *fnn-output-grant*))
         "draw exists before actual factory entry")
  (values #(1 2 3) plan nil t :literal-fifth))
(defun lease-service () (%make-fnn-owner-service :output-ledger (make-test-output-ledger)))
(defun held-dependency ()
  (let* ((entered (sb-thread:make-semaphore :count 0))
         (release (sb-thread:make-semaphore :count 0))
         (thread (sb-thread:make-thread (lambda () (sb-thread:signal-semaphore entered)
                                        (sb-thread:wait-on-semaphore release)))))
    (sb-thread:wait-on-semaphore entered)
    (values (%make-fnn-owner-cold-read :token (list :exact-issued-token)
                                      :worker (%make-fnn-cold-worker :thread thread)) release)))
(let* ((s (lease-service)) (loop (%make-fnn-mux-loop :service s))
       (conn (%make-fnn-mux-conn :cid 7 :response-identity '(:response 7 11 8)))
       (plan (list :original-cursor)) (*lease-calls* nil))
  (let ((values (multiple-value-list (fnn-mux-render-next loop conn plan))))
    (check (and (eq (second values) plan) (eq (fifth values) :literal-fifth))
           "exact original plan and fifth cold result retained"))
  (let ((grant (fnn-mux-conn-output-grant conn)))
    (fnn-mux-render-next loop conn plan)
    (check (eq grant (fnn-mux-conn-output-grant conn)) "single grant spans response windows")
    (check (= 1 (count 'fn-rlo-issue *lease-calls* :key #'car)) "draw once")
    (multiple-value-bind (read1 release1) (held-dependency)
      (fnn-owner-output-dependency s grant read1)
      (check (handler-case (progn (fnn-owner-output-observe-returned s read1) nil)
               (serious-condition () t)) "held child is not terminal")
      (sb-thread:signal-semaphore release1)
      (sb-thread:join-thread (fnn-cold-worker-thread (fnn-owner-cold-read-worker read1)))
      (fnn-owner-output-observe-returned s read1)
      (fnn-owner-output-dependency-consumed s read1)
      (check (not (find 'fn-rlo-physical *lease-calls* :key #'car))
             "physical child end does not close future dependency authority")
      (multiple-value-bind (read2 release2) (held-dependency)
        (fnn-owner-output-dependency s grant read2)
        (fnn-owner-output-close s grant :drained)
        (check (not (fnn-owner-output-drained-p s)) "whole output alone retains late physical child")
        (check (not (find 'fn-rlo-physical *lease-calls* :key #'car)) "no premature physical receipt")
        (sb-thread:signal-semaphore release2)
        (sb-thread:join-thread (fnn-cold-worker-thread (fnn-owner-cold-read-worker read2)))
        (fnn-owner-output-observe-returned s read2)
        (fnn-owner-output-dependency-consumed s read2)
        (check (fnn-owner-output-drained-p s) "both terminal domains settle actual native roster")
        (let ((before (length *lease-calls*)))
          (fnn-owner-output-close s grant :drained)
          (check (= before (length *lease-calls*)) "duplicate closure never replays semantic receipt"))))))
(let* ((s (lease-service)) (*lease-calls* nil)
       (grant (fnn-owner-output-issue s '(:response 7 11 8))))
  (fnn-owner-output-close s grant :discarded)
  (check (fnn-owner-output-drained-p s) "closed operation with no issued children settles")
  (check (eq (third (cdr (find 'fn-rlo-physical *lease-calls* :key #'car))) :no-actor-created)
         "no-child receipt only after issuance authority closes"))
(dolist (kind '(fn-rlo-issue fn-rlo-output))
  (let* ((s (lease-service)) (*torn-kind* kind) (*lease-calls* nil)
         (grant nil))
    (catch 'raw-ev-fncall
      (setf grant (fnn-owner-output-issue s '(:response 7 11 8)))
      (fnn-owner-output-close s grant :discarded))
    (check (not (fnn-owner-output-drained-p s)) "torn step retains native envelope")
    (when grant
      (let ((before (length *lease-calls*)))
        (check (handler-case (progn (fnn-owner-output-close s grant :discarded) nil)
                 (serious-condition () t)) "torn output refuses closure replay")
        (check (= before (length *lease-calls*)) "torn output never drives a later physical settlement")))))
(let* ((root (list :catalog-root 19)) (view (list :actual-held-view))
       (context (list root view :archive :index :config :auth))
       (arena (list :captured-arena)) (catalog (list :captured-catalog))
       (capture (%make-fnn-response-capture)) (*fnn-response-capture* capture)
       (s (lease-service)) (loop (%make-fnn-mux-loop :service s))
       (conn (%make-fnn-mux-conn :cid 7 :response-identity '(:response 7 11 9)))
       (seen 0))
  ;; Recording the actual ACL2 constructor boundary; logical held-view
  ;; selection is separately owned by its program constructor/probe.
  (setf (symbol-function 'fnn-owner-core)
        (lambda (subject cid)
          (check (and (eq subject 'fn-owner-catalog-capture-context) (= cid 7))
                 "actual constructor subject and admitted CID")
          (incf seen) context)
        (symbol-function 'fnn-live-arena) (lambda () arena)
        (symbol-function 'fnn-live-cat) (lambda () catalog))
  (setf (fnn-owner-service-lock s) (sb-thread:make-mutex :name "captured reader O"))
  (sb-thread:with-mutex ((fnn-owner-service-lock s))
    (fnn-owner-capture-reader-context 7))
  (check (and (eq (fnn-response-capture-context capture) context)
              (eq (fnn-response-capture-arena capture) arena)
              (eq (fnn-response-capture-catalog capture) catalog))
         "exact starting semantic view and actual physical refs retained")
  (setf (fnn-mux-conn-response-capture conn) capture)
  (fnn-mux-render-next loop conn (list :original-plan))
  (let ((grant (fnn-mux-conn-output-grant conn)))
    (check (eq (fnn-output-grant-capture grant) capture) "grant receives original capture")
    (fnn-mux-render-next loop conn (list :resumed-plan))
    (check (= seen 1) "renderer resumes never recapture current root")
    (fnn-owner-output-close s grant :drained)
    (check (null (fnn-output-grant-capture grant)) "capture references end at dual settlement")))
(let* ((s (lease-service)) (loop (%make-fnn-mux-loop :service s))
       (conn (%make-fnn-mux-conn :cid 7 :class :reader :input #(5)))
       (context (list :original-root :held-view :archive :index :config :auth))
       (entered nil) (queued nil))
  (setf (symbol-function 'fnn-owner-core)
        (lambda (subject cid)
          (check (and (eq subject 'fn-owner-catalog-capture-context) (= cid 7))
                 "mux actual read constructor route") context)
        (symbol-function 'fnn-owner-handle-chunk)
        (lambda (service cid incoming socket class peerp)
          (declare (ignore service incoming socket class peerp))
          (check (eq (fnn-mux-conn-response-capture conn) *fnn-response-capture*)
                 "actual mux publishes holder before reader entry")
          (setq entered t)
          (fnn-owner-capture-reader-context cid)
          (values (list :actual-returned-plan) nil nil 1 nil nil))
        (symbol-function 'fnn-mux-queue-plan)
        (lambda (l c plan after)
          (declare (ignore l plan after))
          (check (eq (fnn-response-capture-context (fnn-mux-conn-response-capture c)) context)
                 "actual mux transfers starting capture to plan path")
          (setq queued t)))
  (fnn-mux-step loop conn)
  (check (and entered queued) "actual mux reader and plan handoff both execute")
  (setq queued nil)
  (setf (fnn-mux-conn-input conn) #(5)
        (symbol-function 'fnn-owner-handle-chunk)
        (lambda (&rest args)
          (declare (ignore args))
          (fnn-owner-capture-reader-context 7)
          (throw 'raw-ev-fncall :after-capture)))
  (check (eq (catch 'raw-ev-fncall (fnn-mux-step loop conn)) :after-capture)
         "actual mux propagates reader raw escape")
  (check (and (not queued)
              (eq (fnn-response-capture-context (fnn-mux-conn-response-capture conn)) context))
         "fallible reader leaves published original capture discoverable without plan publication"))
(format t "native_output_response_lease_raw: PASS retained plan/late physical/second child/no-child/torn step~%")
