;;; FNPL/FNCU publication classification over actual append/phase/cut source.
;;; ACL2 envelope answers are scripted; kernel file writes/fsync/close are real.
(load "tests/native_section_envelope_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-concat (&rest strings)
  (declare (ignorable strings))
  (harness-stub-reached 'fnn-concat "host/native/io.lisp"))
(defun fnn-emit (stream text)
  (declare (ignorable stream text))
  (harness-stub-reached 'fnn-emit "host/native/io.lisp"))
(defun fnn-log-offer (destination octets)
  (declare (ignorable destination octets))
  (harness-stub-reached 'fnn-log-offer "host/native/io.lisp"))
(defun fnn-string-octets (string)
  (declare (ignorable string))
  (harness-stub-reached 'fnn-string-octets "host/native/io.lisp"))
;;; ---- derived stubs: END ----
(load-deployed-forms "host/native/io.lisp"
 '((define-condition fnn-os-error) (define-condition fnn-entry-guard-fault)
   (defun fnn-indeterminate) (defun fnn-make-octets) (deftype fnn-octets)
   (defun fnn-octets) (defun fnn-octet-list-p)))
(load-deployed-forms "books/feed-journal.lisp" '((defun fn-feed-journal-phase-step)))
(load-deployed-forms "host/native/owner.lisp"
 '((defstruct (fnn-owner-feed-journal (:constructor %make-fnn-owner-feed-journal)))
   (defun fnn-owner-feed-phase) (defun fnn-owner-feed-close)))
(load-deployed-forms "host/native/pull-service.lisp"
 '((defvar *fnn-pull-append-count*) (defvar *fnn-catchup-append-count*)
   (defun fnn-pull-test-cut) (defun fnn-pull-journal-append)))
(defvar *path* (second sb-ext:*posix-argv*))
(defvar *mode* (third sb-ext:*posix-argv*))
(defvar *kind* (if (equal (fourth sb-ext:*posix-argv*) "catch-up") :catch-up :pull))
(defvar *events* nil)
(defun append-check (test message)
  (unless test
    (format t "~&APPEND_ASSERTION:~a~%" message) (finish-output)
    (error "append assertion: ~a" message)))
(defun fnn-core (subject &rest args)
  (case subject
    ((fn-pull-cursor-envelope fn-cu-cursor-envelope)
     (push subject *events*)
     (cond ((equal *mode* "envelope") :bad)
           ((equal *mode* "core") (error 'fnn-entry-guard-fault :message "pre-write core fault"))
           (t '(65 66 67))))
    (fn-feed-journal-phase-step
     (push (second args) *events*)
     (when (and (equal *mode* "durable-phase") (eq (second args) :append-durable))
       (error 'fnn-entry-guard-fault :message "post-barrier phase fault"))
     (apply #'fn-feed-journal-phase-step args))
    (t (error "unexpected core subject ~s" subject))))
(defun fnn-developer-selector (variable)
  (declare (ignore variable)) (when (equal *mode* "selector") "malformed"))
(defun fnn-err (&rest args) (declare (ignore args)) nil)
(defun fnn-write-all (fd bytes)
  (push :write *events*)
  (sb-sys:with-pinned-objects (bytes)
    (sb-posix:write fd (sb-sys:vector-sap bytes)
                   (if (member *mode* '("write" "close") :test #'equal) 1 (length bytes))))
  (when (member *mode* '("write" "close") :test #'equal)
    (error 'fnn-os-error :errno sb-posix:eio)))
(defun fnn-fsync-file (fd)
  (push :fsync *events*)
  (when (equal *mode* "fsync") (error 'fnn-os-error :errno sb-posix:eio))
  (sb-posix:fsync fd))
(defun fnn-close (fd)
  (push :close *events*)
  (sb-posix:close fd)
  (when (equal *mode* "close") (error 'fnn-os-error :errno sb-posix:eio)))
(let* ((fd (sb-posix:open *path* (logior sb-posix:o-rdwr sb-posix:o-creat) #o600))
       (journal (%make-fnn-owner-feed-journal :fd fd :path *path* :phase :ready))
       (outcome
         (handler-case (progn (fnn-pull-journal-append journal :cursor *kind*) :accepted)
           (fnn-store-indeterminate () :uncertain)
           (fnn-entry-guard-fault () :entry-fault)
           (fnn-store-fault () :fault))))
  (cond
    ((member *mode* '("envelope" "core" "selector") :test #'equal)
     (append-check (eq outcome (if (equal *mode* "core") :entry-fault :fault))
                   "pre-write envelope fault must retain its class")
     (append-check (and (not (member :write *events*)) (not (member :fsync *events*)))
                   "pre-write fault must attempt no publication")
     (append-check (eq (fnn-owner-feed-journal-phase journal) :ready)
                   "pre-write fault retains ready journal"))
    ((member *mode* '("write" "fsync" "close") :test #'equal)
     (append-check (eq outcome :uncertain) "attempted publication must remain uncertain after cleanup")
     (append-check (eq (fnn-owner-feed-journal-phase journal) :uncertain)
                   "ACL2 uncertainty retained")
     (append-check (null (fnn-owner-feed-journal-fd journal)) "failed publication closes custody"))
    ((equal *mode* "durable-phase")
     (append-check (eq outcome :entry-fault) "post-barrier fault retains its class")
     (append-check (member :fsync *events*) "durability barrier precedes post-barrier fault"))
    ((equal *mode* "good")
     (append-check (eq outcome :accepted) "successful append accepted")
     (append-check (eq (fnn-owner-feed-journal-phase journal) :ready) "successful append ready"))
    (t (error "unknown append schedule ~a" *mode*)))
  (append-check (member (if (eq *kind* :catch-up) 'fn-cu-cursor-envelope 'fn-pull-cursor-envelope)
                        *events*) "actual selected consumer envelope subject")
  (when (fnn-owner-feed-journal-fd journal) (fnn-owner-feed-close journal))
  (let ((size (sb-posix:stat-size (sb-posix:stat *path*))))
    (append-check (if (member *mode* '("envelope" "core" "selector") :test #'equal)
                     (zerop size) (> size 0)) "kernel journal size agrees with publication attempt"))
  (format t "~&PULL_APPEND_BOUNDARY_PASS ~a ~a~%" *kind* *mode*))
