(load "tests/native_store_cleanup_source.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-app-install (journal records)
  (declare (ignorable journal records))
  (harness-stub-reached 'fnn-app-install "host/native/workflow.lisp"))
(defun fnn-app-read-records (journal names)
  (declare (ignorable journal names))
  (harness-stub-reached 'fnn-app-read-records "host/native/workflow.lisp"))
(defun fnn-app-record-names (journal)
  (declare (ignorable journal))
  (harness-stub-reached 'fnn-app-record-names "host/native/workflow.lisp"))
(defun fnn-app-require-live-store (store)
  (declare (ignorable store))
  (harness-stub-reached 'fnn-app-require-live-store "host/native/workflow.lisp"))
(defun fnn-bpo-canonical-release (service release)
  (declare (ignorable service release))
  (harness-stub-reached 'fnn-bpo-canonical-release "host/native/bp-obligation.lisp"))
(defun fnn-bpo-complete-waivers (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-bpo-complete-waivers "host/native/bp-obligation.lisp"))
(defun fnn-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-core "host/native/io.lisp"))
(defun fnn-fsync-dir (path)
  (declare (ignorable path))
  (harness-stub-reached 'fnn-fsync-dir "host/native/io.lisp"))
(defun fnn-parent (path)
  (declare (ignorable path))
  (harness-stub-reached 'fnn-parent "host/native/io.lisp"))
(defun fnn-safe-directory (path &optional create initializer-store mkdir-cut parent-cut)
  (declare (ignorable path create initializer-store mkdir-cut parent-cut))
  (harness-stub-reached 'fnn-safe-directory "host/native/io.lisp"))
(defun fnn-workflow-commit-receipt-intent (journal intent canonical-release-callback)
  (declare (ignorable journal intent canonical-release-callback))
  (harness-stub-reached 'fnn-workflow-commit-receipt-intent "host/native/workflow.lisp"))
;;; ---- derived stubs: END ----
(defconstant +fnn-o-nofollow+ 0)
(defconstant +fnn-lock-ex+ 2)
(defconstant +fnn-lock-nb+ 4)
(define-condition fnn-os-error (error) ((errno :initarg :errno :reader fnn-os-errno)))
(define-condition fnn-store-indeterminate (error) ())
(defun fnn-indeterminate (&rest ignored)
  (declare (ignore ignored)) (error 'fnn-store-indeterminate))
(defvar *store* nil)
(defvar *opened-journal* nil)
(defvar *regular* t)
(defvar *body-condition* (make-condition 'simple-error :format-control "application body failed"))
(defun fnn-fault (&rest ignored) (declare (ignore ignored)) (error *body-condition*))
(defun fnn-refuse (&rest ignored) (declare (ignore ignored)) (error *body-condition*))
(defun fnn-join (a b) (concatenate 'string a "/" b))
(defun fnn-open (&rest ignored) (declare (ignore ignored)) :acquired)
(defun fnn-fstat (&rest ignored) (declare (ignore ignored)) *regular*)
(defun fnn-regular-p (value) value)
(defun fnn-developer-selector (&rest ignored) (declare (ignore ignored)) nil)
(defun fnn-open-live-store (&rest ignored) (declare (ignore ignored)) (values *store* 0))
(with-open-file (input "host/native/workflow.lisp")
  (loop for form = (read input nil :eof) until (eq form :eof) do
    (when (and (consp form)
               (or (and (eq (car form) 'defstruct) (eq (second form) 'fnn-app-journal))
                   (and (eq (car form) 'defun)
                        (member (second form) '(fnn-app-retain-close-debt fnn-app-journal-close
                           fnn-app-journal-lock fnn-app-call-with-journal)))))
      (eval form))))
(defun fnn-app-open (store &rest ignored)
  (declare (ignore ignored))
  (setq *opened-journal* (make-fnn-app-journal :store store :lock-fd :journal :fenced nil)))
(dolist (body-fails '(t nil))
  (let* ((*store* (make-fnn-store :lock-fd :store)) (*opened-journal* nil)
         (*failures* '(:journal)) (*calls* nil) (caught nil))
    (handler-case
        (fnn-app-call-with-journal "/store" "/journal" :workflow t
          (lambda (journal) (declare (ignore journal))
            (if body-fails (error *body-condition*) (values :durable :detail))))
      (error (e) (setq caught e)))
    (assert (if body-fails (eq caught *body-condition*) (typep caught 'fnn-store-indeterminate)))
    (assert (equal (reverse *calls*) '(:unlock :journal :unlock :store)))
    (assert (fnn-store-fenced *store*))
    (assert (fnn-store-close-debt *store*))
    (assert (equal (fnn-store-application-close-debts *store*)
                   (list (list *opened-journal* :journal *condition*))))
    (let ((*calls* nil))
      (handler-case (fnn-app-journal-close *opened-journal*)
        (error (e) (assert (typep e 'fnn-store-indeterminate))))
      (assert (null *calls*)))))
(let* ((*store* (make-fnn-store :lock-fd :store)) (*failures* nil))
  (assert (equal (multiple-value-list
                  (fnn-app-call-with-journal "/store" "/journal" :workflow t
                    (lambda (journal) (declare (ignore journal)) (values :durable :detail))))
                 '(:durable :detail)))
  (assert (null (fnn-store-application-close-debts *store*))))
(let* ((store (make-fnn-store :lock-fd :store)) (*regular* nil)
       (*failures* '(:acquired)) (*calls* nil) (caught nil))
  (handler-case (fnn-app-journal-lock "/journal" :workflow store)
    (error (e) (setq caught e)))
  (assert (eq caught *body-condition*))
  (assert (equal *calls* '(:acquired)))
  (assert (equal (fnn-store-application-close-debts store)
                 (list (list '(:workflow "/journal/workflow.lock") :acquired *condition*))))
  (let ((*calls* nil) (caught nil))
    (handler-case (fnn-store-close store) (error (e) (setq caught e)))
    (assert (eq caught *condition*))
    (assert (equal (reverse *calls*) '(:unlock :store)))))
(format t "PASS actual app cleanup: independent journal/Store close, sticky holder debt, acquisition unwind, preserved values/body.~%")
;;; Shared owner wrapper: one failed carry close cannot strand workflow/feed/Store.
(defstruct (fnn-owner-service (:constructor %make-fnn-owner-service)) store)
(defun fnn-owner-install (&rest ignored)
  (declare (ignore ignored)) (%make-fnn-owner-service :store *store*))
(defun fnn-quantum-command (service cid thunk)
  (declare (ignore service cid)) (funcall thunk))
(defun fnn-absolute (value) value)
(defun fnn-post-entry-fault (&rest ignored) (declare (ignore ignored)) nil)
(defun fnn-owner-feed-close-all (&rest ignored) (declare (ignore ignored)) (record-call :feeds))
(defun fnn-app-open (store path domain &rest ignored)
  (declare (ignore path ignored))
  (make-fnn-app-journal :store store :lock-fd domain :domain domain :fenced nil))
(with-open-file (input "host/native/bp-obligation.lisp")
  (loop for form = (read input nil :eof) until (eq form :eof) do
    (when (and (consp form) (eq (car form) 'defun)
               (eq (second form) 'fnn-bpo-call-with-owner-journal)) (eval form))))
(dolist (body-fails '(t nil))
  (let* ((*store* (make-fnn-store :lock-fd :store)) (*calls* nil)
         (*failures* '(:carry)) (caught nil))
    (handler-case
        (fnn-bpo-call-with-owner-journal "/store" "/journal" nil
          (lambda (&rest ignored) (declare (ignore ignored))
            (if body-fails (error *body-condition*) (values :durable :detail))))
      (error (e) (setq caught e)))
    (assert (if body-fails (eq caught *body-condition*) (typep caught 'fnn-store-indeterminate)))
    (assert (equal (reverse *calls*) '(:unlock :carry :unlock :workflow :feeds :unlock :store)))
    (assert (fnn-store-close-debt *store*))))
(format t "PASS actual carry owner cleanup: carry/workflow/feed/Store all attempted; uncertainty retained.~%")
(defun fnn-bpnode-source-decision (&rest ignored) (declare (ignore ignored)))
(defun fnn-bpnode-receipt-observations (&rest ignored) (declare (ignore ignored)) nil)
(defun fnn-bpnode-release-line (&rest ignored) (declare (ignore ignored)))
(defun fnn-bpnode-receipt-detail (&rest ignored) (declare (ignore ignored)) '(0))
(defun fnn-owner-core (name &rest ignored)
  (declare (ignore ignored))
  (case name (fn-owner-bp-receipt-gatep t) (fn-owner-bp-receipt-release-record nil)
    (otherwise (error "unexpected owner call ~a" name))))
(defun fnn-quantum-bp (service cid thunk)
  (declare (ignore service cid)) (funcall thunk))
(defun fnn-octets (value) value)
(defun fnn-octets-string (&rest ignored) (declare (ignore ignored)) "detail")
(defun fnn-out (&rest ignored) (declare (ignore ignored)))
(with-open-file (input "host/native/bp-node.lisp")
  (loop for form = (read input nil :eof) until (eq form :eof) do
    (when (and (consp form) (eq (car form) 'defun)
               (eq (second form) 'fnn-bpnode-receipt-result)) (eval form))))
(dolist (close-fails '(t nil))
  (let* ((*store* (make-fnn-store :lock-fd :store)) (*calls* nil)
         (*failures* (and close-fails '(:workflow)))
         (service (%make-fnn-owner-service :store *store*)) (caught nil) (result nil))
    (handler-case
        (setq result (multiple-value-list (fnn-bpnode-receipt-result service "/workflow" nil nil)))
      (error (e) (setq caught e)))
    (if close-fails
        (progn (assert (typep caught 'fnn-store-indeterminate))
               (assert (null result)) (assert (fnn-store-application-close-debts *store*)))
      (progn (assert (null caught)) (assert (equal result '(:receipt-refused (0))))))))
(format t "PASS actual BP receipt: normal semantic refusal never hides physical cleanup uncertainty.~%")
