; Exact retained owner/READY/native bodies with a recorded owner-state and
; list arena I/O seam. No admission, full factory or physical decoder claim.
(require :sb-posix)
(require :sb-bsd-sockets)
(load "tests/native_article_stream_source.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-developer-selector (name)
  (declare (ignorable name))
  (harness-stub-reached 'fnn-developer-selector "host/native/io.lisp"))
(defun fnn-err (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-err "host/native/io.lisp"))
(defun fnn-extent-pool-funded-p ()
  (harness-stub-reached 'fnn-extent-pool-funded-p "host/native/extent.lisp"))
(defun fnn-owner-cursor-step (service cid plan class)
  (declare (ignorable service cid plan class))
  (harness-stub-reached 'fnn-owner-cursor-step "host/native/owner.lisp"))
(defun fnn-owner-render-next (plan &optional compressedp borrowp)
  (declare (ignorable plan compressedp borrowp))
  (harness-stub-reached 'fnn-owner-render-next "host/native/owner.lisp"))
;;; ---- derived stubs: END ----
(defun fn-ag-car (x) (if (consp x) (car x) nil))
(defun fn-ag-cdr (x) (if (consp x) (cdr x) nil))
(defun fn-ag-append (x y) (append x y))
(defun fn-cfg-ag-car (x) (fn-ag-car x))
(defun fn-ng-char-code (x) (char-code x))
(defun fixture-load (path predicate)
  (with-open-file (in path)
    (loop for form = (read in nil :end) until (eq form :end)
          when (and (consp form) (member (car form) '(defun defmacro))
                    (funcall predicate (symbol-name (second form))))
          do (eval form))))
(fixture-load "books/injection-shape.lisp"
              (lambda (n) (member n '("FN-INJ-CAR" "FN-INJ-CDR" "FN-INJ-NTH") :test #'equal)))
(fixture-load "books/owner.lisp"
              (lambda (n) (or (and (search "FN-OWN-CONN-" n) (not (member n '("FN-OWN-CONN-BOUNDEDP" "FN-OWN-CONN-LIVE-SESSION") :test #'equal)))
                              (member n '("FN-OWN-STORE" "FN-OWN-VIEW" "FN-OWN-CONNS"
                                "FN-OWN-NEXT-ID" "FN-OWN-MAX-CONNS" "FN-OWN-PENDING"
                                "FN-OWN-LEDGER-FIELD" "FN-OWN-CLOCK" "FN-OWN-FACTS"
                                "FN-OWN-CONFIG" "FN-OWN-QUEUE" "FN-OWN-INFLIGHT"
                                "FN-OWN-FEEDS" "FN-OWN-NODE-SECRET" "FN-OWN-REFUSED"
                                "FN-OWN-MAKE" "FN-OWN-SET-CONNS" "FN-OWN-FIND-CONN"
                                "FN-OWN-REPLACE-CONN" "FN-OWN-REPLACE-CONN-LOOP") :test #'equal))))
(fixture-load "books/owner-config.lisp"
              (lambda (n) (member n '("FN-OCFG-OWNER" "FN-OCFG-PINS" "FN-OCFG-STAGED"
                                      "FN-OCFG-MAKE" "FN-OCFG-WITH-OWNER" "FN-OCFG-PIN-FIND" "FN-OCFG-CONN-CONFIG") :test #'equal)))
(source-load-defuns "books/owner-config-selector.lisp" '(fn-ocfg-config))
(source-load-defuns "books/config.lisp" '(fn-cfg-generation))
(fixture-load "books/nntp-auth.lisp"
              (lambda (n) (or (search "FN-AUTH-SESSION-" n)
                              (member n '("FN-AUTH-WITH-BASE" "FN-AUTH-MAKE-SESSION") :test #'equal))))
(fixture-load "books/peer-inbound.lisp"
              (lambda (n) (or (search "FN-PEER-SESSION-" n)
                              (member n '("FN-PEER-WITH-BASE" "FN-PEER-MAKE-SESSION"
                                          "FN-PEER-READER-SESSION") :test #'equal))))
(source-load-defuns "books/nntp-post.lisp" '(fn-post-session-base fn-post-make-session))
(defparameter *fn-nntp-max-message-id-octets* 250)
(source-load-defuns "books/nntp-session.lisp"
  '(fn-nntp-session-openp fn-nntp-session-group fn-nntp-session-current fn-nntp-session-projected
    fn-nntp-make-session fn-nntp-set-cursor fn-nntp-article-idp fn-nntp-result-effects
    fn-nntp-make-result fn-nntp-single fn-nntp-reply-effect fn-nntp-crlf))
(source-load-defuns "books/nntp-syntax.lisp"
  '(fn-nntp-printable-tokenp fn-nntp-message-id-tailp fn-nntp-message-id-tokenp
    fn-nntp-string-octets fn-nntp-string-octets-aux fn-nntp-string-octets-aux-loop))
(defparameter *fn-rcl-magic* '(0 70 78 45 82 67 76 50))
(defparameter *fn-rcl-tombstone-fixed* 145)
(source-load-defuns "books/reclaim-tombstone.lisp" '(fn-rcl-prefixp fn-rcl-at-leastp fn-rcl-tombstonep))
(source-load-defuns "books/article-arena-reads.lisp" '(fn-nntp-arena-prefixp fn-nntp-article-tombstonep))
(source-load-defuns "books/served-plan-shape.lisp" '(fn-splan-cur fn-splan-rest fn-splan-cursor-effectp fn-srb-effect-octets))
(source-load-defuns "books/served-plan.lisp" '(fn-splan-rest-donep))
(source-load-defuns "books/article-stream-server.lisp")
(source-load-defuns "books/article-stream-owner.lisp")
(defmacro value (x) `(values nil ,x state))
(defvar *fixture-state*)
(defvar *fixture-arena*)
(defvar *fixture-window* 3)
(defvar *fixture-installs* 0)
(defvar *fixture-cold-offset* nil)
(defvar *fixture-cold-fired* nil)
(defvar *fixture-serialized* nil)
(defvar *fnn-extent-no-io* nil)
(defun fn-owner-ocfg (state) (car state))
(defun fn-owner-install-ocfg (oc state) (incf *fixture-installs*) (list oc (second state)))
(source-load-defuns "host/owner-host.lisp" '(fn-owner-article-ready-plan-step))
(defun fnn-core (name &rest args) (apply name args))
(defun fnn-call (name &rest args) (multiple-value-list (apply name args)))
(defun fnn-core-state (name &rest args)
  (multiple-value-bind (error answer state) (apply name (append args (list *fixture-arena* *fixture-state*)))
    (source-check (null error)) (setq *fixture-state* state) answer))
(defun fnn-live-stobj (name) (source-check (eq name 'fn-arena)) *fixture-arena*)
(defun fnn-owner-over-window () *fixture-window*)
(defun fnn-owner-cursor-step-serialized (service cid thunk class)
  (declare (ignore service cid class))
  (let ((*fixture-serialized* t)) (funcall thunk)))
(defun fnn-owner-cold-issue-locked (service cid request)
  (declare (ignore service cid)) (source-check *fixture-serialized*) (list :read request))
(defun fn-arena-get (h at arena)
  (when (and *fnn-extent-no-io* (eql at *fixture-cold-offset*) (not *fixture-cold-fired*))
    (setq *fixture-cold-fired* t) (throw 'fnn-extent-cold (list :page h at)))
  (nth at (nth h arena)))
(defun fnn-fault (format &rest args) (apply #'error format args))
(source-load-defuns "host/native/io.lisp" '(fnn-make-octets fnn-octets))
(deftype fnn-octets () '(simple-array (unsigned-byte 8) (*)))
; This recorded seam has no physical response capture; execute the actual
; activation wrapper in its uncaptured branch, without a decoded-pool claim.
(defvar *fnn-response-capture* nil)
(source-load-defuns "host/native/owner.lisp"
  '(fnn-owner-window-activation fnn-owner-ready-plan-step fnn-owner-render-next-quantum))
(defun fixture-reader (oc)
  (fn-peer-reader-session (fn-auth-session-base (fn-own-conn-session
    (fn-own-find-conn 7 (fn-own-conns (fn-ocfg-owner oc)))))))
(let* ((payload (append (bytes "Subject: ready") '(13 10 13 10 46 13 10 65 13 10)))
       (*fixture-arena* (list payload))
       (reader (fn-nntp-make-session t "fn.a" 1 t))
       (ps (fn-peer-make-session (fn-post-make-session reader nil) nil nil 0 nil nil nil))
       (as (fn-auth-make-session ps nil nil nil nil nil nil nil 0))
       (conn (fn-own-conn-make-group-indexed 7 0 0 nil as nil nil nil nil nil nil nil))
       (owner (fn-own-make nil nil (list conn) 8 9 nil nil 0 nil nil nil nil nil nil nil))
       (oc (fn-ocfg-make owner '(2 nil) nil nil)))
  (dolist (kind '(:article :head :body))
    (let* ((*fixture-state* (list oc nil)) (*fixture-installs* 0)
           (*fixture-cold-offset* 4) (*fixture-cold-fired* nil)
           (article (list "<ready@example>" 0 '(("fn.a" . 9))))
           (capture (list conn ps
                          (fn-ast-select-state :number "fn.a" 9
                            (append (loop for n below 8 collect
                                      (list (format nil "<before~d@example>" n) 0 (list (cons "fn.a" n))))
                                    (list article)) nil nil nil 0 :next)
                          kind nil nil nil))
           (raw (cons nil (list (list :article-preflight capture))))
           (plan raw) (ready nil))
      (loop until ready do
        (multiple-value-bind (next complete yield cold) (fnn-owner-ready-plan-step nil 7 plan :reader)
          (source-check (= (fn-nntp-session-current (fixture-reader (car *fixture-state*)))
                           (if complete 9 1)))
          (when cold (source-check (eq next plan)) (source-check (not yield)))
          (source-check (= *fixture-installs* (if complete 1 0)))
          (setq plan next ready complete)
          ; Publication for another connection may change the live generation.
          ; This response retains the same per-connection configuration pin.
          (unless complete
            (let ((old (car *fixture-state*)))
              (setf (car *fixture-state*)
                    (fn-ocfg-make (fn-ocfg-owner old) '(3 nil)
                                  (fn-ocfg-pins old) (fn-ocfg-staged old)))))))
      (source-check *fixture-cold-fired*)
      (let ((original plan))
        (dolist (window '(1 3 4096))
          (let ((*fixture-window* window) (*fixture-cold-offset* 20) (*fixture-cold-fired* nil)
                (cur original) (acc nil) (done nil))
            (loop until done do
              (multiple-value-bind (part rest end yield cold)
                  (fnn-owner-render-next-quantum nil 7 cur :reader)
                (source-check (<= (length part) window))
                (when cold (source-check (eq rest cur)) (source-check (zerop (length part))))
                (when yield (source-check (not end)))
                (setq acc (append acc (coerce part 'list)) cur rest done end)))
            (source-check (equal acc (source-reference payload kind 9 "<ready@example>")))
            (source-check (= *fixture-installs* 1))))))))
; Message-ID selection passes through the same actual owner READY/native
; producer, but never changes the selected group/current cursor.
(let* ((payload (append (bytes "Subject: ready") '(13 10 13 10 46 13 10 65 13 10)))
       (*fixture-arena* (list payload))
       (reader (fn-nntp-make-session t "fn.a" 1 t))
       (ps (fn-peer-make-session (fn-post-make-session reader nil) nil nil 0 nil nil nil))
       (as (fn-auth-make-session ps nil nil nil nil nil nil nil 0))
       (conn (fn-own-conn-make-group-indexed 7 0 0 nil as nil nil nil nil nil nil nil))
       (owner (fn-own-make nil nil (list conn) 8 9 nil nil 0 nil nil nil nil nil nil nil))
       (oc (fn-ocfg-make owner '(2 nil) nil nil)))
  (dolist (kind '(:article :head :body))
    (let* ((*fixture-state* (list oc nil)) (*fixture-installs* 0)
           (*fixture-cold-offset* 4) (*fixture-cold-fired* nil)
           (article (list "<ready@example>" 0 '(("fn.a" . 9))))
           (capture (list conn ps
                          (fn-ast-select-state :msgid "fn.a" "<ready@example>"
                            (append (loop for n below 8 collect
                                      (list (format nil "<before~d@example>" n) 0 (list (cons "fn.a" n))))
                                    (list article)) nil nil nil 0 :msgid-next)
                          kind nil nil nil))
           (raw (cons nil (list (list :article-preflight capture))))
           (plan raw) (ready nil))
      (loop until ready do
        (multiple-value-bind (next complete yield cold) (fnn-owner-ready-plan-step nil 7 plan :reader)
          (source-check (= (fn-nntp-session-current (fixture-reader (car *fixture-state*)))
                           1))
          (when cold (source-check (eq next plan)) (source-check (not yield)))
          (source-check (= *fixture-installs* 0))
          (setq plan next ready complete)
          ; Publication for another connection may change the live generation.
          ; This response retains the same per-connection configuration pin.
          (unless complete
            (let ((old (car *fixture-state*)))
              (setf (car *fixture-state*)
                    (fn-ocfg-make (fn-ocfg-owner old) '(3 nil)
                                  (fn-ocfg-pins old) (fn-ocfg-staged old)))))))
      (source-check *fixture-cold-fired*)
      (source-check (equal (fixture-reader (car *fixture-state*)) reader))
      (let ((original plan))
        (dolist (window '(1 3 4096))
          (let ((*fixture-window* window) (*fixture-cold-offset* 20) (*fixture-cold-fired* nil)
                (cur original) (acc nil) (done nil))
            (loop until done do
              (multiple-value-bind (part rest end yield cold)
                  (fnn-owner-render-next-quantum nil 7 cur :reader)
                (source-check (<= (length part) window))
                (when cold (source-check (eq rest cur)) (source-check (zerop (length part))))
                (when yield (source-check (not end)))
                (setq acc (append acc (coerce part 'list)) cur rest done end)))
            (source-check (equal acc (source-reference payload kind 9 "<ready@example>")))
            (source-check (= *fixture-installs* 0))))))))
(let* ((reader (fn-nntp-make-session t "fn.a" 1 t))
       (ps (fn-peer-make-session (fn-post-make-session reader nil) nil nil 0 nil nil nil))
       (as (fn-auth-make-session ps nil nil nil nil nil nil nil 0))
       (conn (fn-own-conn-make-group-indexed 7 0 0 nil as nil nil nil nil nil nil nil))
       (owner (fn-own-make nil nil (list conn) 8 9 nil nil 0 nil nil nil nil nil nil nil))
       (oc (fn-ocfg-make owner '(2 nil) nil nil)))
  (dolist (case (list (list "<bad" '(65 13 10 13 10) t "503 stored article identifier unavailable")
                     (list "<good@example>" '(65 10 13 10) t "503 stored article framing unavailable")
                     (list "<good@example>" (append *fn-rcl-magic* (make-list 137 :initial-element 0)) t "423 article reclaimed")
                     (list "<good@example>" (append *fn-rcl-magic* (make-list 137 :initial-element 0)) nil "430 article reclaimed")))
    (destructuring-bind (mid payload update text) case
      (let* ((*fixture-state* (list oc nil)) (*fixture-installs* 0)
             (*fixture-cold-offset* nil) (*fixture-cold-fired* nil)
             (*fixture-arena* (list payload)) (article (list mid 0))
             (scan (fn-asto-payload-preflight article *fixture-arena*))
             (capture (list conn ps (list article 9 update "fn.a") :article nil scan nil))
             (plan (cons nil (list (list :article-preflight capture)))) (ready nil))
        (when (search "reclaimed" text) (source-check (fn-ast-scan-donep scan)))
        (loop until ready do
          (multiple-value-bind (next done) (fnn-owner-ready-plan-step nil 7 plan :reader)
            (setq plan next ready done)))
        (source-check (equal (fixture-reader (car *fixture-state*)) reader))
        (source-check (equal (fn-splan-rest plan) (list (list :reply (append (bytes text) '(13 10))))))
        (source-check (not (fn-asto-preflight-planp plan)))))))
(let* ((reader (fn-nntp-make-session t "fn.a" 1 t))
       (ps (fn-peer-make-session (fn-post-make-session reader nil) nil nil 0 nil nil nil))
       (as (fn-auth-make-session ps nil nil nil nil nil nil nil 0))
       (conn (fn-own-conn-make-group-indexed 7 0 0 nil as nil nil nil nil nil nil nil))
       (owner (fn-own-make nil nil (list conn) 8 9 nil nil 0 nil nil nil nil nil nil nil))
       (oc (fn-ocfg-make owner '(2 nil) nil nil)))
  (dolist (case (list (list :current nil nil "420 no current article")
                     (list :number nil nil "423 no article with that number")
                     (list :number nil (list (list "<withdrawn@example>" 0 '(("fn.a" . 9)))) "423 withdrawn")
                     (list :number nil (list (list "<other@example>" 0 '(("fn.b" . 9)))) "423 no article with that number")
                     (list :msgid nil nil "430 no article with that message-id")
                     (list :msgid nil (list (list "<withdrawn@example>" 0 '(("fn.a" . 9)))) "430 withdrawn")
                     (list :msgid nil (list (list "<other@example>" 0 '(("fn.a" . 9)))) "430 no article with that message-id")))
    (destructuring-bind (mode articles withdrawn text) case
      (let* ((*fixture-state* (list oc nil)) (*fixture-installs* 0)
             (*fixture-cold-offset* nil) (*fixture-cold-fired* nil) (*fixture-arena* nil)
             (capture (list conn ps (fn-ast-select-state mode "fn.a"
                              (if (eq mode :msgid) "<withdrawn@example>" 9)
                              articles nil nil nil 0 (if (eq mode :msgid) :msgid-next :next))
                            :article nil nil nil withdrawn))
             (plan (cons nil (list (list :article-preflight capture)))) (ready nil))
        (loop until ready do
          (multiple-value-bind (next done) (fnn-owner-ready-plan-step nil 7 plan :reader)
            (setq plan next ready done)))
        (source-check (equal (fixture-reader (car *fixture-state*)) reader))
        (source-check (equal (fn-splan-rest plan) (list (list :reply (append (bytes text) '(13 10))))))
        (source-check (zerop *fixture-installs*))))))
(format t "article READY/native actual-source PASS checks=~d~%" *checks*)
