;;; Actual pull worker unwind/start/close and shared actor over recording
;;; transport/journal leaves, with physical SBCL threads and joins.
(load "tests/native_actor_envelope_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-core "host/native/io.lisp"))
(defun fnn-owner-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-owner-core "host/native/owner.lisp"))
(defun fnn-owner-syncer-physical (service grant receipt)
  (declare (ignorable service grant receipt))
  (harness-stub-reached 'fnn-owner-syncer-physical "host/native/owner.lisp"))
(defun fnn-owner-transit-serialized (service cid thunk)
  (declare (ignorable service cid thunk))
  (harness-stub-reached 'fnn-owner-transit-serialized "host/native/owner.lisp"))
(defun fnn-pull-admit-flight (runtime plans kind)
  (declare (ignorable runtime plans kind))
  (harness-stub-reached 'fnn-pull-admit-flight "host/native/pull-service.lisp"))
(defun fnn-pull-flight-dispose (flight)
  (declare (ignorable flight))
  (harness-stub-reached 'fnn-pull-flight-dispose "host/native/pull-service.lisp"))
(defun fnn-pull-flight-finish (flight)
  (declare (ignorable flight))
  (harness-stub-reached 'fnn-pull-flight-finish "host/native/pull-service.lisp"))
(defun fnn-pull-flight-step (flight)
  (declare (ignorable flight))
  (harness-stub-reached 'fnn-pull-flight-step "host/native/pull-service.lisp"))
(defun fnn-pull-prune-journals (runtime plans &optional kind)
  (declare (ignorable runtime plans kind))
  (harness-stub-reached 'fnn-pull-prune-journals "host/native/pull-service.lisp"))
(defun fnn-pull-retire-flights (runtime plans kind)
  (declare (ignorable runtime plans kind))
  (harness-stub-reached 'fnn-pull-retire-flights "host/native/pull-service.lisp"))
;;; ---- derived stubs: END ----
(load-deployed-forms "host/native/owner.lisp"
 '((defun fnn-owner-actor-for-custody) (defun fnn-owner-thread-escape)))
(load-deployed-forms "host/native/pull-service.lisp"
 '((defstruct (fnn-pull-runtime (:constructor %make-fnn-pull-runtime)))
   (defstruct (fnn-pull-flight (:constructor %make-fnn-pull-flight)))
   (defparameter *fnn-pull-runtime-lock*) (defparameter *fnn-pull-runtimes*)
   (defun fnn-pull-runtime-get) (defun fnn-pull-worker)
   (def-actor fnn-pull-spawn) (defun fnn-pull-service-start)
   (defun fnn-pull-service-wake) (defun fnn-pull-service-close)))
(defvar *pull-cut* nil)
(defvar *pull-close-cut* nil)
(defvar *pull-entered* nil)
(defvar *pull-release* nil)
(defvar *pull-closed* (list nil))
(defvar *pull-unwind-entered* nil)
(defun fnn-owner-fence-service (service)
  (setf (fnn-owner-service-stopping service) t))
(defun fnn-pull-stoppingp (runtime)
  ;; Select the actual worker's unwind without fabricating its receipt.
  (setf (fnn-pull-runtime-journals runtime) '((:one . :journal-one) (:two . :journal-two)))
  (case *pull-cut*
    (:hold
     (sb-thread:signal-semaphore *pull-entered*)
     (assert (sb-thread:wait-on-semaphore *pull-release* :timeout 2))
     t)
    (:fault
     (setf (fnn-owner-service-stopping (fnn-pull-runtime-service runtime)) t)
     (error 'fnn-store-fault :message "pull fault after stop"))
    (:uncertain
     (setf (fnn-owner-service-stopping (fnn-pull-runtime-service runtime)) t)
     (error 'fnn-store-indeterminate :message "pull uncertainty after stop"))
    (:throw (throw 'raw-ev-fncall :pull-torn))
    (otherwise t)))
(defun fnn-owner-feed-close (journal)
  (push journal (car *pull-closed*))
  (when (eq journal :journal-one)
    (case *pull-close-cut*
      (:fault (error 'fnn-store-fault :message "journal close failed"))
      (:throw (throw 'raw-ev-fncall :cleanup-torn))
      (:hold
       (sb-thread:signal-semaphore *pull-unwind-entered*)
       (assert (sb-thread:wait-on-semaphore *pull-release* :timeout 2)))))
  nil)
(defun fnn-socket-shutdown (socket) (declare (ignore socket)) nil)

;; SBCL child threads do not inherit the caller's dynamic bindings. Capture
;; only the recording leaf settings explicitly; the actor starter itself is
;; still the deployed implementation and uses a real SBCL maker/join.
(let* ((maker *fnn-actor-thread-maker*)
       (*fnn-actor-thread-maker*
         (lambda (thunk &rest arguments)
           (let ((cut *pull-cut*) (close-cut *pull-close-cut*)
                 (entered *pull-entered*) (release *pull-release*)
                 (closed *pull-closed*) (unwind-entered *pull-unwind-entered*))
             (apply maker
                    (lambda ()
                      (let ((*pull-cut* cut) (*pull-close-cut* close-cut)
                            (*pull-entered* entered) (*pull-release* release)
                            (*pull-closed* closed) (*pull-unwind-entered* unwind-entered))
                        (funcall thunk)))
                    arguments)))))

;; An already stopped/immediately finishing worker remains registered until
;; physical join. Repeated start cannot allocate a second runtime/actor.
(let ((*pull-cut* nil) (*pull-close-cut* nil) (*pull-closed* (list nil))
      (service (%make-fnn-owner-service)))
  (fnn-pull-service-start service)
  (let* ((runtime (fnn-pull-runtime-get service))
         (worker (fnn-pull-runtime-worker runtime)))
    (fnn-pull-service-start service)
    (assert (eq runtime (fnn-pull-runtime-get service)))
    (assert (= (length (fnn-owner-service-actors service)) 1))
    (assert (member worker (fnn-owner-service-workers service)))
    (fnn-pull-service-close service)
    (assert (not (sb-thread:thread-alive-p worker)))
    (assert (eq (fnn-pull-runtime-cleanup-stage runtime) :returned))
    (assert (equal (car *pull-closed*) '(:journal-two :journal-one)))
    (assert (null (fnn-pull-runtime-get service)))
    (assert (null (fnn-owner-service-actors service)))
    (fnn-pull-service-close service)))

;; Failed join cannot erase a still live worker or its runtime/journals.
(let* ((*pull-cut* :hold) (*pull-close-cut* nil)
       (*pull-entered* (sb-thread:make-semaphore :count 0))
       (*pull-release* (sb-thread:make-semaphore :count 0))
       (service (%make-fnn-owner-service)))
  (fnn-pull-service-start service)
  (wait-label *pull-entered*)
  (let* ((runtime (fnn-pull-runtime-get service))
         (worker (fnn-pull-runtime-worker runtime))
         (*fnn-actor-thread-joiner* (lambda (&rest args) (declare (ignore args)) (error "join refused"))))
    (assert (handler-case (progn (fnn-pull-service-close service) nil) (serious-condition () t)))
    (assert (sb-thread:thread-alive-p worker))
    (assert (eq runtime (fnn-pull-runtime-get service)))
    (assert (fnn-owner-actor-for-custody service runtime)))
  (sb-thread:signal-semaphore *pull-release*)
  (fnn-pull-service-close service)
  (assert (null (fnn-pull-runtime-get service))))

;; Cleanup held while stop runs is still part of the live activation.
(let* ((*pull-cut* nil) (*pull-close-cut* :hold)
       (*pull-unwind-entered* (sb-thread:make-semaphore :count 0))
       (*pull-release* (sb-thread:make-semaphore :count 0))
       (service (%make-fnn-owner-service)))
  (fnn-pull-service-start service)
  (wait-label *pull-unwind-entered*)
  (let ((runtime (fnn-pull-runtime-get service)))
    (fnn-pull-service-wake service)
    (assert (eq (fnn-pull-runtime-cleanup-stage runtime) :calling))
    (assert (sb-thread:thread-alive-p (fnn-pull-runtime-worker runtime)))
    (assert (fnn-owner-actor-for-custody service runtime)))
  (sb-thread:signal-semaphore *pull-release*)
  (fnn-pull-service-close service))

;; Known physical completion is separate from a failed/torn journal cleanup.
;; Sibling close is attempted after an ordinary condition; torn cleanup keeps
;; :calling and is never invoked a second time by close.
(dolist (cut '(:fault :throw))
  (let* ((*pull-cut* nil) (*pull-close-cut* cut) (*pull-closed* (list nil))
         (service (%make-fnn-owner-service)))
    (fnn-pull-service-start service)
    (let* ((runtime (fnn-pull-runtime-get service))
           (worker (fnn-pull-runtime-worker runtime)))
      (fnn-owner-actor-join service worker)
      (assert (eq (fnn-pull-runtime-cleanup-stage runtime)
                  (if (eq cut :throw) :calling :returned)))
      (assert (equal (car *pull-closed*) (if (eq cut :fault) '(:journal-two :journal-one) '(:journal-one))))
      (dotimes (i 2)
        (assert (handler-case (progn (fnn-pull-service-close service) nil) (serious-condition () t))))
      (assert (eq runtime (fnn-pull-runtime-get service)))
      (assert (equal (car *pull-closed*) (if (eq cut :fault) '(:journal-two :journal-one) '(:journal-one)))))))

;; Body failures, including a raw ACL2 escape, keep their classification even
;; after stop; they do not masquerade as an actor's successful return.
(dolist (cut '(:fault :uncertain :throw))
  (let ((*pull-cut* cut) (*pull-close-cut* nil) (service (%make-fnn-owner-service)))
    (fnn-pull-service-start service)
    (let ((runtime (fnn-pull-runtime-get service)))
      (multiple-value-bind (ended receipt)
          (fnn-owner-actor-join service (fnn-pull-runtime-worker runtime))
        (assert ended)
        (assert (eq (third receipt) (if (eq cut :uncertain) :indeterminate :fault))))
      (assert (fnn-owner-service-stopping service))
      (fnn-pull-service-close service))))

;; A primary body condition survives an independent cleanup condition; both
;; terminal debt and original provenance remain observable after physical join.
(let ((*pull-cut* :fault) (*pull-close-cut* :fault)
      (service (%make-fnn-owner-service)))
  (setq *join-faults* nil)
  (fnn-pull-service-start service)
  (let ((runtime (fnn-pull-runtime-get service)))
    (fnn-owner-actor-join service (fnn-pull-runtime-worker runtime))
    (assert (search "pull fault after stop" (princ-to-string (car *join-faults*))))
    (assert (search "journal close failed"
                    (princ-to-string (fnn-pull-runtime-cleanup-debt runtime))))))

;; No child means the map can be cleared. A child parked by a post-create
;; latch fault remains discoverable even when compensation does not terminate.
(let* ((service (%make-fnn-owner-service))
       (*fnn-actor-thread-maker* (lambda (&rest args) (declare (ignore args)) (error "maker failed"))))
  (assert (handler-case (progn (fnn-pull-service-start service) nil) (serious-condition () t)))
  (assert (null (fnn-pull-runtime-get service)))
  (assert (null (fnn-owner-service-actors service))))
(let* ((service (%make-fnn-owner-service))
       (*fnn-actor-start-signal* (lambda (&rest args) (declare (ignore args)) (error "latch failed")))
       (*fnn-actor-thread-terminator* (lambda (worker) (declare (ignore worker)) nil)))
  (assert (handler-case (progn (fnn-pull-service-start service) nil) (serious-condition () t)))
  (let* ((runtime (fnn-pull-runtime-get service))
         (worker (fnn-pull-runtime-worker runtime)))
    (assert (sb-thread:thread-alive-p worker))
    (assert (fnn-owner-actor-for-custody service runtime))
    (sb-thread:terminate-thread worker)
    (fnn-pull-service-close service)
    (assert (null (fnn-pull-runtime-get service)))))

;; A latch can release the body and then signal a condition. Compensation
;; observes a physically ended actor, but may not erase its cleanup debt.
(dolist (cut '(:fault :throw))
  (let* ((*pull-cut* nil) (*pull-close-cut* cut)
         (service (%make-fnn-owner-service))
         (*fnn-actor-start-signal*
           (lambda (latch)
             (sb-thread:signal-semaphore latch)
             (let* ((actor (car (fnn-owner-service-actors service)))
                    (worker (fnn-owner-actor-thread actor)))
               (sb-thread:join-thread worker :default :abnormal))
             (error "signal failed after child cleanup")))
         (*fnn-actor-thread-terminator* (lambda (worker) (declare (ignore worker)) nil)))
    (assert (handler-case (progn (fnn-pull-service-start service) nil) (serious-condition () t)))
    (let ((runtime (fnn-pull-runtime-get service)))
      (assert runtime)
      (assert (null (fnn-owner-service-actors service)))
      (assert (if (eq cut :fault) (fnn-pull-runtime-cleanup-debt runtime)
                (eq (fnn-pull-runtime-cleanup-stage runtime) :calling)))
      (assert (handler-case (progn (fnn-pull-service-close service) nil) (serious-condition () t)))
      (assert (eq runtime (fnn-pull-runtime-get service))))))
)
(format t "native_pull_lifecycle_raw: PASS physical start/join/held cleanup/late fault/debt/no-child/post-create custody~%")
