; SCN-1136 continuation: actual STATUS/HEALTH consumers retain normalized
; configuration policies; the actual ACL2 output extension contributes MB.
(load "tests/native_heap_default_source.lisp")
(require :sb-bsd-sockets)
(in-package "ACL2")
(selected-source "books/native-config.lisp"
 '(fn-native-config-store fn-native-config-cold-resources fn-native-config-output-resources))
(selected-source "books/native-operator.lisp" '(fn-native-operator-result-config))
(selected-source "host/native-operator-host.lisp"
 '(fn-native-operator-host-result-config fn-native-operator-host-result-store-root))
(source-forms "host/native/operator.lisp" '(fnn-operator-print-next-run-heap))
(source-forms (or (sixth sb-ext:*posix-argv*) "host/native/operator.lisp")
 '(fnn-operator-execute-status fnn-operator-execute-health))
(defparameter *before-diagnostic-core* (symbol-function 'fnn-core))
(defun fnn-core (entry &rest args)
 (case entry
  ((fn-native-operator-host-result-config fn-native-operator-host-result-store-root
    fn-native-config-cold-resources fn-native-config-output-resources)
   (apply (symbol-function entry) args))
  (fn-native-operator-host-result-command (third (first args)))
  ((fn-native-operator-host-result-status-watch
    fn-native-operator-host-result-status-control-path-octets) nil)
  (fn-native-operator-host-result-status-kind :fixture)
  (fn-native-operator-host-result-health-min-percent 10)
  (fn-native-health-host-exit 0)
  (otherwise (apply *before-diagnostic-core* entry args))))
(defun fnn-filesystem-durability-warn (&rest args) (declare (ignore args)) nil)
(defun fnn-operator-status-once (&rest args) (declare (ignore args)) 0)
(defun fnn-operator-emit-status (&rest args) (declare (ignore args)) nil)
(defun fnn-operator-status-of-exit-code (code) (assert (= code 0)) :accepted)
(defun fnn-operator-health-report (&rest args) (declare (ignore args)) :health-report)
(defun fnn-write-report (report) (assert (eq report :health-report)))
(defparameter +fnn-exit-refused+ 1)
(defun policy-case (command cold output expected)
 (let* ((config (make-list 31))
        (result (list :accepted nil command config nil))
        (*fnn-stdout* (make-string-output-stream))
        (*calls* nil) (*captured-core* 0) (*captured-machine* 0))
  (setf (first config) "/fixture" (nth 29 config) cold (nth 30 config) output)
  (assert (= (if (equal command "status")
                (fnn-operator-execute-status result)
              (fnn-operator-execute-health result)) 0))
  (assert (equal (get-output-stream-string *fnn-stdout*) expected))
  (let ((cold-call (assoc :cold *calls*)) (output-call (assoc :output *calls*)))
   (assert (equal (third cold-call) cold))
   (assert (equal (third output-call) output)))
  (assert (= *captured-core* *captured-machine* 1))))
; Final trigger-growth pricing: the 16 MiB output backing also enlarges
; collector nursery protection. DEFAULT257/explicit256 become276/275,
; respectively; the old273/272 figures omitted that growth.
(dolist (command '("status" "health"))
 (policy-case command nil '(16777216 1048576) "(:HEAP 276 :SMALL 8192 1024 16)")
 (policy-case command '(67108864 4 256 256 256) '(16777216 1048576)
              "(:HEAP 275 :SMALL 8192 1024 16)"))
(format t "SOURCE NEXT-RUN POLICY DIAGNOSTICS PASSED~%")
