;;; Actual shared actor/classifier + maintenance/listener starters over
;;; recording maintenance and accept leaves, using physical SBCL threads.
(load "tests/native_actor_envelope_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-owner-syncer-physical (service grant receipt)
  (declare (ignorable service grant receipt))
  (harness-stub-reached 'fnn-owner-syncer-physical "host/native/owner.lisp"))
;;; ---- derived stubs: END ----
(defparameter *fnn-sigterm-requested* nil)
(load-deployed-forms "host/native/owner.lisp"
 '((def-actor fnn-owner-spawn-listener) (def-actor fnn-owner-spawn-tls-listener)
   (def-actor fnn-owner-spawn-maintenance) (defun fnn-owner-start-tls-accept)
   (defun fnn-owner-start-maintenance) (defun fnn-owner-thread-escape)))
(defvar *background-cut* nil)
(defvar *background-fences* 0)
(defun fnn-owner-fence-service (service)
  (incf *background-fences*)
  (setf (fnn-owner-service-stopping service) t))
(defun fnn-owner-maintenance-tick (service)
  ;; Literal stop is an observed recording boundary in this fixture; the
  ;; ensuing condition must not disappear merely because stop is set.
  (setf (fnn-owner-service-stopping service) t)
  (case *background-cut*
    (:fault (error 'fnn-store-fault :message "late maintenance Store fault"))
    (:uncertain (error 'fnn-store-indeterminate :message "late durable uncertainty"))
    (:throw (throw 'raw-ev-fncall :maintenance-torn))
    (otherwise (error "unknown maintenance cut"))))
(defun fnn-owner-accept-one (service listener seconds &optional implicit-tls)
  (assert (equal (list listener seconds implicit-tls) '(:listener 1 t)))
  (when (member *background-cut* '(:socket-stopped :store-stopped :throw-stopped))
    (setf (fnn-owner-service-stopping service) t))
  (case *background-cut*
    ((:socket-stopped :socket-live)
     (error 'sb-bsd-sockets:socket-error :errno sb-posix:ebadf :syscall "accept"))
    (:store-stopped (error 'fnn-store-fault :message "listener Store fault after stop"))
    (:throw-stopped (throw 'raw-ev-fncall :listener-torn))
    (otherwise (error "unknown listener cut"))))
(dolist (cut '(:fault :uncertain :throw))
  (setq *background-cut* cut *background-fences* 0 *join-faults* nil)
  (let* ((service (%make-fnn-owner-service))
         (thread (fnn-owner-start-maintenance service)))
    (multiple-value-bind (ended receipt) (fnn-owner-actor-join service thread)
      (assert ended)
      (assert (eq (third receipt) (if (eq cut :uncertain) :indeterminate :fault))))
    (assert (fnn-owner-service-stopping service))
    (assert (null (fnn-owner-service-workers service)))
    (assert (null (fnn-owner-service-actors service)))
    (if (eq cut :uncertain)
        (assert (and (= *background-fences* 1) (null *join-faults*)))
      (assert *join-faults*))))
(dolist (cut '(:socket-stopped :socket-live :store-stopped :throw-stopped))
  (setq *background-cut* cut *join-faults* nil)
  (let* ((service (%make-fnn-owner-service))
         (thread (fnn-owner-start-tls-accept service :listener)))
    (multiple-value-bind (ended receipt) (fnn-owner-actor-join service thread)
      (assert ended)
      (assert (eq (third receipt) (if (eq cut :socket-stopped) :ok :fault)))
      (assert (equal (fourth receipt) '(:listener))))
    (if (eq cut :socket-stopped) (assert (null *join-faults*))
      (assert *join-faults*))))
;; Even an actor that immediately observes stop remains registered until its
;; physical join. Neither starter recursively holds the roster across spawn.
(let ((service (%make-fnn-owner-service :stopping t)))
  (let ((thread (fnn-owner-start-maintenance service)))
    (assert (fnn-owner-service-actors service))
    (assert (member thread (fnn-owner-service-workers service)))
    (fnn-owner-actor-join service thread)
    (assert (null (fnn-owner-service-actors service)))))
;; Definite no-child maker failure leaves no physical registration.
(let* ((service (%make-fnn-owner-service))
       (*fnn-actor-thread-maker* (lambda (&rest args) (declare (ignore args)) (error "no background child"))))
  (assert (handler-case (progn (fnn-owner-start-maintenance service) nil) (error () t)))
  (assert (null (fnn-owner-service-actors service)))
  (assert (null (fnn-owner-service-workers service))))
(format t "native_owner_background_raw: PASS late maintenance/listener faults/uncertainty/raw throw/expected shutdown/physical actor join~%")
