; SCN-1132: actual host definitions and actual ACL2 policy, no saved image.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-make-octets (n)
  (declare (ignorable n))
  (harness-stub-reached 'fnn-make-octets "host/native/io.lisp"))
;;; ---- derived stubs: END ----
(declaim (declaration xargs))
(defmacro defconst (name value) `(defparameter ,name ,value))
(defmacro include-book (&rest args) (declare (ignore args)) nil)
(defmacro defthm (&rest args) (declare (ignore args)) nil)
(defmacro verify-guards (&rest args) (declare (ignore args)) nil)
(defmacro in-theory (&rest args) (declare (ignore args)) nil)
(defparameter *fn-nntp-max-command-octets* 510)
(defparameter *fn-nntp-max-response-octets* 512)
(defun natp (n) (and (integerp n) (<= 0 n)))
(defun posp (n) (and (integerp n) (< 0 n)))
(defun true-listp (xs) (or (null xs) (and (consp xs) (true-listp (cdr xs)))))
(defun booleanp (x) (or (null x) (eq x t)))
(defun fn-record-string-octets (s) (map 'list #'char-code s))
(defun fn-nntp-printable-tokenp (xs) (every (lambda (n) (and (integerp n) (<= 33 n 126))) xs))
(defun fn-nntp-keywordp (xs text) (string-equal (map 'string #'code-char xs) text))
(defun fn-cbor-at-mostp (xs n) (and (true-listp xs) (<= (length xs) n)))
(defun fn-nntp-command-inputp (xs) (and (<= (length xs) 510) (every (lambda (n) (<= 32 n 255)) xs)))
(load "books/native-redeem-input.lisp")
(deftype fnn-octets () '(simple-array (unsigned-byte 8) (*)))
(define-condition fixture-refusal (error) ())
(defun fnn-refuse (&rest args) (declare (ignore args)) (error 'fixture-refusal))
(defun fnn-fault (&rest args) (declare (ignore args)) (error "unexpected core decision"))
(defun fnn-core (name &rest args) (apply name args))
(with-open-file (in "host/native/io.lisp")
  (loop for form = (read in nil :eof) until (eq form :eof)
        when (and (consp form) (eq (car form) 'defun)
                  (member (second form) '(fnn-redeem-read-line fnn-redeem-password-line)))
          do (eval form)))
(defun bytes (string) (map 'fnn-octets #'char-code string))
(defun refused (thunk)
  (handler-case (progn (funcall thunk) nil) (fixture-refusal () t)))
(let ((newline (string #\Newline)))
  (assert (= 496 (length (fnn-redeem-password-line
                         (make-string-input-stream (concatenate 'string (make-string 496 :initial-element #\x) newline))))))
  (let ((stream (make-string-input-stream (make-string 100000 :initial-element #\x))))
    (assert (refused (lambda () (fnn-redeem-password-line stream))))
    (assert (= 497 (file-position stream)))) ; refused before retaining byte497
  (dolist (text (list "" " " (string #\Tab) (string (code-char 256))
                     (format nil "x~cQUIT~%" #\Return)))
    (assert (refused (lambda () (fnn-redeem-password-line (make-string-input-stream text))))))
  (assert (equal '(120) (fnn-redeem-password-line (make-string-input-stream (format nil "x~c~%" #\Return)))))
  (assert (equal '(120) (fnn-redeem-password-line (make-string-input-stream "x"))))
  (let ((reads 0))
    (multiple-value-bind (line rest)
        (fnn-redeem-read-line (lambda () (incf reads) (bytes (format nil "~c~%NEXT~%" #\Return)))
                             (bytes (make-string 510 :initial-element #\x)))
      (assert (= 510 (length line))) (assert (= 5 (length rest))) (assert (= 1 reads))))
  (assert (eq :lost (fnn-redeem-read-line
                     (lambda () (error "must reject pending prefix"))
                     (bytes (concatenate 'string (make-string 4097 :initial-element #\x) newline)))))
  (assert (eq :lost (fnn-redeem-read-line (lambda () (bytes newline))
                                        (bytes (make-string 512 :initial-element #\x))))))


(assert (equal (fn-rip-command :code "abc" "robin") (fn-record-string-octets (format nil "XREDEEM abc robin~c~%" #\Return))))
(dolist (token (list "" "a b" (format nil "a~cb" #\Tab) (format nil "a~cQUIT" #\Return) (string (code-char 256))))
  (assert (null (fn-rip-command :code token "robin")))
  (assert (null (fn-rip-command :code "abc" token))))
(assert (null (fn-rip-command :code "PaSs" "robin")))
(assert (null (fn-rip-command :password (make-list 498 :initial-element 120) nil)))

(format t "REDEEM INPUT SOURCE PASSED; bounded retention and exact wire edges~%")
