;;; Deterministic raw-native I/O boundary tests.  This loads the same
;;; host/native/io.lisp SBCL code that the saved image loads; no Python process
;;; or parser is part of the exercised path.

(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
;; Raw-I/O tests do not enter an ACL2 wrapper, but these names let SBCL compile
;; the full native adapter exactly once without warning about the image state.
(defvar *the-live-state* nil)
(defun f-get-global (name state)
  (declare (ignore name state))
  nil)
(load "host/native/io.lisp")

(defun nio-check (test control &rest args)
  (unless test (error (apply #'format nil control args))))

(defun nio-expects (expected thunk)
  (handler-case (funcall thunk)
    (error (e)
      (unless (typep e expected)
        (error "expected ~a, got ~a" expected e))
      t)
    (:no-error (&rest values)
      (declare (ignore values))
      (error "expected ~a, got normal return" expected))))

(defun nio-wrong-condition-is-rejected ()
  (let ((rejected nil))
    (handler-case
        (nio-expects 'fnn-store-fault (lambda () (fnn-refuse "semantic refusal")))
      (error () (setq rejected t)))
    (nio-check rejected "test helper accepted refusal where a fault was required")))

(defun nio-read-eintr-then-data ()
  (let ((calls 0) (buffer (fnn-make-octets 3)))
    (let ((*fnn-read-syscall*
            (lambda (fd target)
              (declare (ignore fd))
              (incf calls)
              (if (= calls 1)
                  (values nil sb-posix:eintr)
                  (progn (setf (aref target 0) 42) (values 1 nil))))))
      (nio-check (= (fnn-read-fd 9 buffer) 1) "read did not return byte count")
      (nio-check (= calls 2) "read did not retry EINTR")
      (nio-check (= (aref buffer 0) 42) "read retry did not preserve buffer"))))

(defun nio-read-eof-remains-zero ()
  (let ((*fnn-read-syscall* (lambda (fd buffer)
                               (declare (ignore fd buffer))
                               (values 0 nil))))
    (nio-check (zerop (fnn-read-fd 9 (fnn-make-octets 2)))
               "EOF read was not preserved as zero")))

(defun nio-store-write-progress ()
  (let ((answers '(1 2 1)) (seen nil))
    (let ((*fnn-write-syscall*
            (lambda (fd octets offset count)
              (declare (ignore fd octets))
              (push (list offset count) seen)
              (values (pop answers) nil))))
      (fnn-write-all 9 (fnn-octets '(10 11 12 13)))
      (nio-check (equal (nreverse seen) '((0 4) (1 3) (3 1)))
                 "partial store writes did not resume at exact offsets")
      (nio-check (null answers) "store write did not consume every injected partial result"))))

(defun nio-zero-writes-fault ()
  (let ((*fnn-write-syscall* (lambda (&rest ignored)
                                (declare (ignore ignored))
                                (values 0 nil))))
    (nio-check (nio-expects 'fnn-store-fault
                            (lambda () (fnn-write-all 9 (fnn-octets '(1)))))
               "zero store write did not fault")))

(defun nio-send-retries-with-one-deadline ()
  (let ((ticks 0) (attempts 0) (waits nil) (writes nil))
    (let ((*fnn-monotonic-ticks* (lambda () (incf ticks 100)))
          (*fnn-fd-waiter* (lambda (fd direction seconds)
                              (declare (ignore fd direction))
                              (push seconds waits)
                              t))
          (*fnn-write-syscall*
            (lambda (fd octets offset count)
              (declare (ignore fd octets))
              (push (list offset count) writes)
              (incf attempts)
              (case attempts
                (1 (values nil sb-posix:eintr))
                (2 (values 1 nil))
                (3 (values 1 nil))))))
      (fnn-send-all 9 (fnn-octets '(1 2)) 1)
      (setq waits (nreverse waits))
      (nio-check (= attempts 3) "socket write did not retry EINTR and resume partial write")
      (nio-check (equal (nreverse writes) '((0 2) (0 2) (1 1)))
                 "socket partial write did not resume at the unwritten offset")
      (nio-check (= (length waits) 2) "unexpected socket wait count")
      (nio-check (< (second waits) (first waits))
                 "socket retry reset its deadline instead of consuming it"))))

(defun nio-zero-send-faults ()
  (let ((*fnn-monotonic-ticks* #'get-internal-real-time)
        (*fnn-fd-waiter* (lambda (&rest ignored) (declare (ignore ignored)) t))
        (*fnn-write-syscall* (lambda (&rest ignored)
                                (declare (ignore ignored))
                                (values 0 nil))))
    (nio-check (nio-expects 'fnn-store-fault
                            (lambda () (fnn-send-all 9 (fnn-octets '(1)) 1)))
               "zero socket write did not fault")))

(defun nio-send-eintr-obeys-deadline ()
  (let ((ticks 0))
    (let ((*fnn-monotonic-ticks* (lambda () (incf ticks 600000)))
          (*fnn-fd-waiter* (lambda (&rest ignored) (declare (ignore ignored)) t))
          (*fnn-write-syscall* (lambda (&rest ignored)
                                  (declare (ignore ignored))
                                  (values nil sb-posix:eintr))))
      (nio-check (nio-expects 'fnn-os-error
                              (lambda () (fnn-send-all 9 (fnn-octets '(1)) 1)))
                 "repeated EINTR bypassed the socket deadline"))))

(defun nio-recv-eintr-obeys-deadline ()
  (let ((ticks 0))
    (let ((*fnn-monotonic-ticks* (lambda () (incf ticks 600000)))
          (*fnn-fd-waiter* (lambda (&rest ignored) (declare (ignore ignored)) t))
          (*fnn-read-syscall* (lambda (&rest ignored)
                                (declare (ignore ignored))
                                (values nil sb-posix:eintr))))
      (nio-check (nio-expects 'fnn-os-error (lambda () (fnn-recv 9 1)))
                 "read EINTR retry bypassed the receive deadline"))))

(defun nio-core-boundary-faults ()
  (let ((old-counterpart (symbol-function 'fnn-counterpart))
        (old-call (symbol-function 'fnn-call)))
    (unwind-protect
         (progn
           (setf (symbol-function 'nio-core-boom) (lambda (&rest ignored)
                                                      (declare (ignore ignored))
                                                      (error "injected core error")))
           (setf (symbol-function 'fnn-counterpart) (lambda (name)
                                                       (declare (ignore name))
                                                       'nio-core-boom))
           (nio-check (nio-expects 'fnn-store-fault (lambda () (fnn-call 'nio-core)))
                      "thrown core condition was not a fault")
           (setf (symbol-function 'fnn-call) (lambda (&rest ignored)
                                                (declare (ignore ignored))
                                                (list t :bad-state)))
           (nio-check (nio-expects 'fnn-store-fault (lambda () (fnn-core-state 'nio-core)))
                      "core erp was not a fault")
           (nio-check (nio-expects 'fnn-store-fault (lambda () (fnn-nat :not-a-natural)))
                      "malformed natural result was not a fault")
           (nio-check (nio-expects 'fnn-store-fault (lambda () (fnn-as-octets '(256))))
                      "malformed octet result was not a fault")
           (nio-check (eq (fnn-action :refused) :refused)
                      "explicit semantic refusal was not preserved"))
      (setf (symbol-function 'fnn-counterpart) old-counterpart
            (symbol-function 'fnn-call) old-call))))

(defun nio-outcome-taxonomy ()
  (nio-check (= (fnn-exit-code-for
                 (make-condition 'fnn-store-indeterminate :message "test"))
                +fnn-exit-uncertain+)
             "indeterminate did not retain exit 3")
  (nio-check (= (fnn-exit-code-for
                 (make-condition 'fnn-store-fault :message "test"))
                +fnn-exit-fault+)
             "fault did not retain exit 4")
  (nio-check (= (fnn-exit-code-for
                 (make-condition 'fnn-store-error :message "test"))
                +fnn-exit-refused+)
             "semantic refusal did not retain exit 1"))

(defun nio-with-reader-stubs (thunk)
  (let* ((symbols '(fnn-socket-fd fnn-socket-shut fnn-send-all fnn-reader-reset
                    fnn-recv fnn-reader-chunk))
         (saved (mapcar (lambda (symbol) (cons symbol (symbol-function symbol))) symbols)))
    (unwind-protect
         (progn
           (setf (symbol-function 'fnn-socket-fd) (lambda (socket)
                                                    (declare (ignore socket)) 9)
                 (symbol-function 'fnn-socket-shut) (lambda (socket)
                                                      (declare (ignore socket)) nil)
                 (symbol-function 'fnn-send-all) (lambda (&rest ignored)
                                                   (declare (ignore ignored)) t)
                 (symbol-function 'fnn-reader-reset) (lambda () (fnn-make-octets 0))
                 (symbol-function 'fnn-recv) (lambda (&rest ignored)
                                               (declare (ignore ignored))
                                               (fnn-octets '(65))))
           (funcall thunk))
      (dolist (pair saved)
        (setf (symbol-function (car pair)) (cdr pair))))))

(defun nio-reader-preserves-subtypes ()
  (flet ((serve (thunk)
           (nio-with-reader-stubs
            (lambda ()
              (setf (symbol-function 'fnn-reader-chunk)
                    (lambda (octets) (declare (ignore octets)) (funcall thunk)))
              (fnn-serve-client :test-socket)))))
    (nio-check (nio-expects 'fnn-store-indeterminate
                            (lambda () (serve (lambda () (fnn-indeterminate "test")))))
               "reader collapsed indeterminate into a connection refusal")
    (nio-check (nio-expects 'fnn-store-fault
                            (lambda () (serve (lambda () (fnn-fault "test")))))
               "reader collapsed fault into a connection refusal")
    (nio-check (null (serve (lambda () (fnn-refuse "test"))))
               "reader did not retain semantic refusal as a connection-only result")))

(nio-read-eintr-then-data)
(nio-read-eof-remains-zero)
(nio-wrong-condition-is-rejected)
(nio-store-write-progress)
(nio-zero-writes-fault)
(nio-send-retries-with-one-deadline)
(nio-zero-send-faults)
(nio-send-eintr-obeys-deadline)
(nio-recv-eintr-obeys-deadline)
(nio-core-boundary-faults)
(nio-outcome-taxonomy)
(nio-reader-preserves-subtypes)
(format t "native-io-progress: ok~%")
