;;; Actual AUTHINFO lock/execute adapters plus shared cleanup macro.
(require :sb-posix)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(defun source-definition (path kind name)
  (with-open-file (stream path)
    (let* ((text (make-string (file-length stream)))
           (prefix (format nil "(~a ~a " kind name)))
      (read-sequence text stream)
      (let ((start (search prefix text)))
        (unless start (error "missing definition ~a" name))
        (read-from-string text nil nil :start start)))))
(define-condition fnn-os-error (error) ((errno :initarg :errno :reader fnn-os-errno)))
(define-condition refused (error) ())
(defparameter +fnn-o-nofollow+ 0)
(defparameter +fnn-lock-ex+ 2)
(defparameter +fnn-lock-nb+ 4)
(defparameter +fnn-lock-un+ 8)
(defparameter +fnn-exit-usage+ 2)
(defvar *fnn-native-auth-admin-cut-callback* nil)
(defvar *mode* nil)
(defvar *opens* 0)
(defvar *closes* 0)
(defvar *unlocks* 0)
(defvar *close-failure* nil)
(defun fnn-err (&rest args) (declare (ignore args)))
(defun fnn-refuse (&rest args) (declare (ignore args)) (error 'refused))
(defun fnn-open (&rest args)
  (declare (ignore args))
  (incf *opens*)
  (case *mode*
    (:open-symlink (error 'fnn-os-error :errno sb-posix:eloop))
    (:open-fault (error 'fnn-os-error :errno sb-posix:eio)))
  11)
(defun fnn-fstat (fd)
  (assert (= fd 11))
  (when (eq *mode* :fstat-fault) (error 'fnn-os-error :errno sb-posix:eio)) :info)
(defun fnn-regular-p (info) (assert (eq info :info)) (not (eq *mode* :nonregular)))
(defun fnn-flock (fd flags)
  (assert (= fd 11))
  (if (= flags +fnn-lock-un+)
      (progn (incf *unlocks*)
             (when (eq *mode* :unlock-fault) (error "unlock-fault")))
    (case *mode*
      (:busy (error 'fnn-os-error :errno sb-posix:eagain))
      (:denied (error 'fnn-os-error :errno sb-posix:eacces))
      (:flock-fault (error 'fnn-os-error :errno sb-posix:eio)))))
(defun fnn-close (fd)
  (assert (= fd 11)) (incf *closes*)
  (when *close-failure* (error "close-fault")))
(defun fnn-native-auth-admin-core (&rest args) (declare (ignore args)) :accepted)
(defun fnn-native-auth-admin-paths (path) (values path "/lock" "/stage" "/directory"))
(defun fnn-native-auth-admin-check-directory (path) (declare (ignore path)))
(defun fnn-native-auth-admin-test-cut ()
  (when (eq *mode* :invalid-cut) (error "invalid-cut")) nil)
(defun fnn-native-auth-admin-recover (&rest args) (declare (ignore args)) t)
(defun fnn-native-auth-admin-read-held (&rest args) (declare (ignore args)) nil)
(defun fnn-native-auth-admin-execute-held (&rest args)
  (declare (ignore args))
  (when (eq *mode* :body-fault) (error "body-fault")) 0)
(eval (source-definition (or (sb-ext:posix-getenv "FN_CLEANUP_HOST_SOURCE") "host/native/io.lisp")
                         "defmacro" "fnn-unwind-cleanups"))
(let ((source (or (sb-ext:posix-getenv "FN_AUTH_ADMIN_HOST_SOURCE") "host/native/auth-admin.lisp")))
  (dolist (name '("fnn-native-auth-admin-open-lock" "fnn-native-auth-admin-execute"))
    (eval (source-definition source "defun" name))))
(defun observed (thunk)
  (handler-case (funcall thunk)
    (fnn-os-error (e) (list :os (fnn-os-errno e)))
    (refused () :refused)
    (error (e) (princ-to-string e))))
(dolist (case (list (list :success 11 0)
                   (list :busy :refused 1) (list :denied :refused 1)
                   (list :nonregular :refused 1)
                   (list :fstat-fault (list :os sb-posix:eio) 1)
                   (list :flock-fault (list :os sb-posix:eio) 1)
                   (list :open-symlink :refused 0)
                   (list :open-fault (list :os sb-posix:eio) 0)))
  (let ((*mode* (first case)) (*opens* 0) (*closes* 0))
    (assert (equal (observed (lambda () (fnn-native-auth-admin-open-lock "/lock")))
                   (second case)))
    (assert (= *closes* (third case)))))
(let ((*mode* :fstat-fault) (*closes* 0) (*close-failure* t))
  (assert (equal (observed (lambda () (fnn-native-auth-admin-open-lock "/lock")))
                 (list :os sb-posix:eio)))
  (assert (= *closes* 1)))
(dolist (mode '(:success :invalid-cut :body-fault :unlock-fault))
  (let ((*mode* mode) (*opens* 0) (*closes* 0) (*unlocks* 0)
        (*fnn-native-auth-admin-cut-callback* nil))
    (assert (equal (observed (lambda () (fnn-native-auth-admin-execute :plan "/auth" 1)))
                   (case mode (:success 0) (:invalid-cut "invalid-cut")
                     (:body-fault "body-fault") (:unlock-fault "unlock-fault"))))
    (assert (= *opens* (if (eq mode :invalid-cut) 0 1)))
    (assert (= *closes* (if (eq mode :invalid-cut) 0 1)))
    (assert (= *unlocks* (if (eq mode :invalid-cut) 0 1)))))
(format t "AUTHINFO physical lock classification and custody passed (13 paths)~%")
