;;; Actual staging/readback/install and private snapshot custody. Kernel files
;;; and page codec are real; framed-run admission and snapshot storage record
;;; their boundaries. This is not a saved-image or page-store refinement claim.
(load "tests/native_section_envelope_raw.lisp")
(in-package "ACL2")

(defun natp (x) (and (integerp x) (<= 0 x)))
(defun zp (x) (not (and (integerp x) (> x 0))))
(defun nfix (x) (if (natp x) x 0))
(defun ifix (x) (if (integerp x) x 0))
(defun len (x) (length x))
(defmacro mbe (&key logic exec) (declare (ignore logic)) exec)
(defun take (n x) (loop for i below n collect (nth i x)))
(defvar *fnn-checkpoint-image-custody* nil)
(defvar *fnn-checkpoint-stop-test* nil)
(defparameter *readback-new*
 (with-open-file (s "host/native/io.lisp")
  (loop for f = (read s nil :eof) until (eq f :eof)
   thereis (and (consp f) (eq (car f) 'defmacro) (eq (cadr f) 'fnn-with-history-image)))))
(unless *readback-new* (defmacro fnn-with-history-image (&body body) `(progn ,@body)))
(load-deployed-forms "books/pagestore-words-blake3.lisp"
 '((defun pgs-octet) (defun pgs-word-le-octets) (defun pgs-words-le-octets-loop)
   (defun pgs-words-le-octets)))
(load-deployed-forms "books/history-image-snapshot.lisp"
 '((defconst *fn-his-magic*) (defconst *fn-his-version*) (defconst *fn-his-base*)
   (defconst *fn-his-page-octets*) (defconst *fn-his-header-octets*)
   (defun fn-his-le) (defun fn-his-le-value) (defun fn-his-image-header)
   (defun fn-his-image-header-np) (defun fn-his-skip-octets)
   (defun fn-his-base-octets) (defun fn-his-np)))
(when *readback-new*
 (load-deployed-forms "books/history-image-snapshot.lisp"
  '((defun fn-his-readback-header-p) (defun fn-his-readback-page)))
 (load-deployed-forms "host/native/io.lisp"
  '((defun fnn-history-image-release) (defmacro fnn-with-history-image))))
(load-deployed-forms "host/native/io.lisp"
 '((define-condition fnn-store-io-refusal) (defun fnn-refuse-io)
   (defstruct (fnn-store (:constructor %make-fnn-store)))
   (deftype fnn-octets) (defun fnn-make-octets) (defun fnn-octets)
   (defun fnn-octet-list) (defmacro fnn-posix) (defun fnn-open)
   (defun fnn-close) (defun fnn-unlink) (defun fnn-durable-step) (defun fnn-replace)
   (defun fnn-read-exact-fd) (defun fnn-write-staged-at) (defun fnn-checkpoint-yield)
   (defun fnn-history-image-build) (defun fnn-history-image-write)
   (defun fnn-state-checkpoint-write) (defun fnn-state-checkpoint-stage)
   (defun fnn-state-checkpoint-verify) (defun fnn-state-checkpoint-install)))
(defconstant +fnn-o-nofollow+ sb-posix:o-nofollow)
(when *readback-new*
 (load-deployed-forms "host/native/io.lisp" '((defun fnn-history-image-readback))))
(defvar *directory* (second sb-ext:*posix-argv*))
(defvar *mode* (third sb-ext:*posix-argv*))
(defvar *snapshot* nil)
(defvar *releases* 0)
(defvar *installs* 0)
(defvar *max-read* 0)
(defvar *page-reads* 0)
(setq *fnn-checkpoint-stop-test*
      (lambda () (and (equal *mode* "stop") (plusp *page-reads*))))
(defun fnn-live-hrecs () :private-snapshot)
(defun fn-his-words (sel at st)
 (check (and (eq st :private-snapshot) *snapshot* (= sel 0) (= at 0)) "retained snapshot read")
 *snapshot*)
(defun fnn-call (subject &rest args)
 (case subject
  (fn-his-snapshot (setq *snapshot* (make-list 2048 :initial-element 42))
                   (list :ok :record '((1 0 0))))
  (fn-his-release (incf *releases*) (setq *snapshot* nil) nil)
  (otherwise (list (apply #'fnn-core subject args)))))
(defun fnn-core (subject &rest args)
 (case subject
  ((fn-his-image-header fn-his-image-header-np fn-his-skip-octets fn-his-base-octets
    fn-his-np fn-his-words fn-his-readback-header-p fn-his-readback-page)
   (apply (symbol-function subject) args))
  (fn-his-binding :binding)
  (fn-store-sco-segment-header-octets 37)
  (fn-store-sco-trailer-octets 1)
  (fn-store-sco-segment-admit '(:ok 39 1))
  (fn-sccv-initial 0)
  (fn-sccv-step (1+ (first args)))
  (fn-sccv-final (if (= (first args) 5) '(:ok 2) '(:refused :frames)))
  (otherwise (error "unexpected core subject ~s" subject))))
(defun fnn-join (a b) (concatenate 'string a "/" b))
(defun fnn-staging (s) (fnn-store-root s))
(defun fnn-state-checkpoint-path (s) (fnn-join (fnn-store-root s) "checkpoint"))
(defun fnn-random-hex (n) (declare (ignore n)) "test")
(defun fnn-read-fd (fd buffer &rest ignored)
 (declare (ignore ignored))
 (setq *max-read* (max *max-read* (length buffer)))
 (when (= (length buffer) 16384) (incf *page-reads*))
 (sb-sys:with-pinned-objects (buffer)
  (sb-posix:read fd (sb-sys:vector-sap buffer) (length buffer))))
(defun fnn-write-range (fd bytes start end)
 (sb-sys:with-pinned-objects (bytes)
  (sb-posix:write fd (sb-sys:sap+ (sb-sys:vector-sap bytes) start) (- end start))))
(defun fnn-write-all (fd bytes) (fnn-write-range fd bytes 0 (length bytes)))
(defun fnn-fsync-file (fd) (sb-posix:fsync fd))
(defun fnn-fsync-dir (path) (declare (ignore path)) nil)
(defun fnn-at (store cut) (declare (ignore store))
 (when (eq cut :state-checkpoint-replaced) (incf *installs*)))
(defun fnn-octets-pub-fill (chunk) chunk)
(defun fnn-state-checkpoint-test-flip (path)
 (cond
  ((equal *mode* "raw-exit") (throw 'stage-escape :escaped))
  ((member *mode* '("page" "zero-page" "header") :test #'equal)
   (let* ((fd (sb-posix:open path sb-posix:o-rdwr))
          (offset (cond ((equal *mode* "header") 5)
                        ((equal *mode* "zero-page") 16384) (t (+ 32768 100)))))
    (unwind-protect
     (progn (sb-posix:lseek fd offset sb-posix:seek-set)
            (fnn-write-all fd (fnn-octets '(255))))
     (sb-posix:close fd))))))
(defun image-check (x label)
 (unless x (format t "IMAGE_READBACK_ASSERTION:~a~%" label) (error "~a" label)))
(let* ((store (%make-fnn-store :root *directory*))
       (old #(79 76 68))
       (path (fnn-state-checkpoint-path store)))
 (with-open-file (s path :direction :output :element-type '(unsigned-byte 8)
                         :if-exists :supersede) (write-sequence old s))
 (let ((outcome
  (catch 'stage-escape
   (handler-case
    (fnn-with-history-image
     (multiple-value-bind (position image) (fnn-history-image-build '(a b) :node 0 '(2 :trail))
      (declare (ignore position))
      (when (equal *mode* "deferred") (throw 'stage-escape :deferred))
      (apply #'fnn-state-checkpoint-write store
       (lambda (fd)
        (fnn-history-image-write fd image)
        (dotimes (i 5) (declare (ignore i)) (fnn-write-all fd (fnn-make-octets 39))))
       2 (if *readback-new* (list image) nil))
      (image-check (null *snapshot*) "snapshot returned before install can reopen publisher slot")
      :accepted))
    (fnn-store-io-refusal () :refused)))))
  (when (member *mode* '("page" "zero-page" "header" "stop") :test #'equal)
   (image-check (eq outcome :refused) "damaged staged image must refuse before checkpoint replacement")
   (image-check (zerop *installs*) "damaged image cannot authorize replacement or drop")
   (with-open-file (s path :element-type '(unsigned-byte 8))
    (let ((got (make-array (file-length s)))) (read-sequence got s)
     (image-check (equalp old got) "old checkpoint retained"))))
  (when (equal *mode* "good")
   (image-check (and (eq outcome :accepted) (= *installs* 1)) "valid image installs once"))
  (when (equal *mode* "stop")
   (image-check (= *page-reads* 1) "stop fence observed before reading next image page"))
  (image-check (and (null *snapshot*) (= *releases* 1)) "snapshot released on every publication exit")
  (image-check (<= *max-read* 16384) "readback bounded to one page")
  (format t "CHECKPOINT_IMAGE_READBACK_PASS ~a~%" *mode*)))
