;;; Actual snapshot capture/starter/cleanup + shared actor and export body,
;;; recording pin/archive leaves; physical SBCL threads, no file proof claim.
(load "tests/native_actor_envelope_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-arena-return-observation (log)
  (declare (ignorable log))
  (harness-stub-reached 'fnn-arena-return-observation "host/native/io.lisp"))
(defun fnn-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-core "host/native/io.lisp"))
(defun fnn-extent-direct-start ()
  (harness-stub-reached 'fnn-extent-direct-start "host/native/extent.lisp"))
(defun fnn-extent-end-recovery-cache ()
  (harness-stub-reached 'fnn-extent-end-recovery-cache "host/native/extent.lisp"))
(defun fnn-extent-executor-drained-p ()
  (harness-stub-reached 'fnn-extent-executor-drained-p "host/native/extent.lisp"))
(defun fnn-extent-executor-stop ()
  (harness-stub-reached 'fnn-extent-executor-stop "host/native/extent.lisp"))
(defun fnn-listen (port &key family backlog address)
  (declare (ignorable port family backlog address))
  (harness-stub-reached 'fnn-listen "host/native/io.lisp"))
(defun fnn-log-line (line)
  (declare (ignorable line))
  (harness-stub-reached 'fnn-log-line "host/native/io.lisp"))
(defun fnn-log-seal-capture (store)
  (declare (ignorable store))
  (harness-stub-reached 'fnn-log-seal-capture "host/native/io.lisp"))
(defun fnn-log-sync-collected (log)
  (declare (ignorable log))
  (harness-stub-reached 'fnn-log-sync-collected "host/native/io.lisp"))
(defun fnn-log-writer-start ()
  (harness-stub-reached 'fnn-log-writer-start "host/native/io.lisp"))
(defun fnn-mux-budget-install (service tls-context)
  (declare (ignorable service tls-context))
  (harness-stub-reached 'fnn-mux-budget-install "host/native/mux.lisp"))
(defun fnn-mux-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-mux-drained-p "host/native/mux.lisp"))
(defun fnn-mux-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-mux-start "host/native/mux.lisp"))
(defun fnn-out (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-out "host/native/io.lisp"))
(defun fnn-owner-accept (service listener once)
  (declare (ignorable service listener once))
  (harness-stub-reached 'fnn-owner-accept "host/native/owner.lisp"))
(defun fnn-owner-answer-early (ledger members)
  (declare (ignorable ledger members))
  (harness-stub-reached 'fnn-owner-answer-early "host/native/owner.lisp"))
(defun fnn-owner-claim-run-authority (&optional caller-reservation)
  (declare (ignorable caller-reservation))
  (harness-stub-reached 'fnn-owner-claim-run-authority "host/native/owner.lisp"))
(defun fnn-owner-cold-shutdown (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-cold-shutdown "host/native/owner.lisp"))
(defun fnn-owner-commit-complete-locked (service action members deferred)
  (declare (ignorable service action members deferred))
  (harness-stub-reached 'fnn-owner-commit-complete-locked "host/native/owner.lisp"))
(defun fnn-owner-commit-event (service event)
  (declare (ignorable service event))
  (harness-stub-reached 'fnn-owner-commit-event "host/native/owner.lisp"))
(defun fnn-owner-commit-start-event (members uncertain)
  (declare (ignorable members uncertain))
  (harness-stub-reached 'fnn-owner-commit-start-event "host/native/owner.lisp"))
(defun fnn-owner-commit-start-locked (service &key seal)
  (declare (ignorable service seal))
  (harness-stub-reached 'fnn-owner-commit-start-locked "host/native/owner.lisp"))
(defun fnn-owner-commit-wake (service returned queued)
  (declare (ignorable service returned queued))
  (harness-stub-reached 'fnn-owner-commit-wake "host/native/owner.lisp"))
(defun fnn-owner-complete-generation (ledger gen final members)
  (declare (ignorable ledger gen final members))
  (harness-stub-reached 'fnn-owner-complete-generation "host/native/owner.lisp"))
(defun fnn-owner-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-owner-core "host/native/owner.lisp"))
(defun fnn-owner-deliver (service cid completion)
  (declare (ignorable service cid completion))
  (harness-stub-reached 'fnn-owner-deliver "host/native/owner.lisp"))
(defun fnn-owner-disk-event (service kind &optional arg)
  (declare (ignorable service kind arg))
  (harness-stub-reached 'fnn-owner-disk-event "host/native/owner.lisp"))
(defun fnn-owner-disk-stalled-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-disk-stalled-p "host/native/owner.lisp"))
(defun fnn-owner-disk-wait-ms (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-disk-wait-ms "host/native/owner.lisp"))
(defun fnn-owner-drain-service (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-drain-service "host/native/owner.lisp"))
(defun fnn-owner-feed-close-all (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-feed-close-all "host/native/owner.lisp"))
(defun fnn-owner-frames-job (service job)
  (declare (ignorable service job))
  (harness-stub-reached 'fnn-owner-frames-job "host/native/owner.lisp"))
(defun fnn-owner-install (root max-connections &optional fault)
  (declare (ignorable root max-connections fault))
  (harness-stub-reached 'fnn-owner-install "host/native/owner.lisp"))
(defun fnn-owner-journal-close ()
  (harness-stub-reached 'fnn-owner-journal-close "host/native/owner.lisp"))
(defun fnn-owner-journal-note (service a b)
  (declare (ignorable service a b))
  (harness-stub-reached 'fnn-owner-journal-note "host/native/owner.lisp"))
(defun fnn-owner-journal-open (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-journal-open "host/native/owner.lisp"))
(defun fnn-owner-log-settlement ()
  (harness-stub-reached 'fnn-owner-log-settlement "host/native/owner.lisp"))
(defun fnn-owner-measure-report ()
  (harness-stub-reached 'fnn-owner-measure-report "host/native/owner.lisp"))
(defun fnn-owner-output-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-output-drained-p "host/native/owner.lisp"))
(defun fnn-owner-page-read-startup (root max-connections cold-resources output-resources retain)
  (declare (ignorable root max-connections cold-resources output-resources retain))
  (harness-stub-reached 'fnn-owner-page-read-startup "host/native/owner.lisp"))
(defun fnn-owner-peer-flight-startup (service capture)
  (declare (ignorable service capture))
  (harness-stub-reached 'fnn-owner-peer-flight-startup "host/native/owner.lisp"))
(defun fnn-owner-reader-capture (event)
  (declare (ignorable event))
  (harness-stub-reached 'fnn-owner-reader-capture "host/native/owner.lisp"))
(defun fnn-owner-refresh-read-octets (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-refresh-read-octets "host/native/owner.lisp"))
(defun fnn-owner-release-recovery-garbage ()
  (harness-stub-reached 'fnn-owner-release-recovery-garbage "host/native/owner.lisp"))
(defun fnn-owner-retain-run-authority (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-retain-run-authority "host/native/owner.lisp"))
(defun fnn-owner-retire-final-report (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-retire-final-report "host/native/owner.lisp"))
(defun fnn-owner-run-startup-hooks (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-run-startup-hooks "host/native/owner.lisp"))
(defun fnn-owner-serialized (service cid thunk &optional class)
  (declare (ignorable service cid thunk class))
  (harness-stub-reached 'fnn-owner-serialized "host/native/owner.lisp"))
(defun fnn-owner-service-nursery ()
  (harness-stub-reached 'fnn-owner-service-nursery "host/native/owner.lisp"))
(defun fnn-owner-shed-queued-locked (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-shed-queued-locked "host/native/owner.lisp"))
(defun fnn-owner-space-event (service need)
  (declare (ignorable service need))
  (harness-stub-reached 'fnn-owner-space-event "host/native/owner.lisp"))
(defun fnn-owner-space-prime (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-space-prime "host/native/owner.lisp"))
(defun fnn-owner-stall-release (service members)
  (declare (ignorable service members))
  (harness-stub-reached 'fnn-owner-stall-release "host/native/owner.lisp"))
(defun fnn-owner-start-committer (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-start-committer "host/native/owner.lisp"))
(defun fnn-owner-start-tls-accept (service listener &optional implicit-tls)
  (declare (ignorable service listener implicit-tls))
  (harness-stub-reached 'fnn-owner-start-tls-accept "host/native/owner.lisp"))
(defun fnn-owner-stop-service (service exit-code)
  (declare (ignorable service exit-code))
  (harness-stub-reached 'fnn-owner-stop-service "host/native/owner.lisp"))
(defun fnn-owner-store-settlement (service settlement)
  (declare (ignorable service settlement))
  (harness-stub-reached 'fnn-owner-store-settlement "host/native/owner.lisp"))
(defun fnn-owner-syncer-abandon (service grant ledger members)
  (declare (ignorable service grant ledger members))
  (harness-stub-reached 'fnn-owner-syncer-abandon "host/native/owner.lisp"))
(defun fnn-owner-syncer-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-syncer-drained-p "host/native/owner.lisp"))
(defun fnn-owner-syncer-outcome (service grant generation)
  (declare (ignorable service grant generation))
  (harness-stub-reached 'fnn-owner-syncer-outcome "host/native/owner.lisp"))
(defun fnn-owner-syncer-physical (service grant receipt)
  (declare (ignorable service grant receipt))
  (harness-stub-reached 'fnn-owner-syncer-physical "host/native/owner.lisp"))
(defun fnn-owner-wait-workers (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-wait-workers "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-joined (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-joined "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-start "host/native/owner.lisp"))
(defun fnn-peer-flight-bank-drained (bank)
  (declare (ignorable bank))
  (harness-stub-reached 'fnn-peer-flight-bank-drained "host/native/catchup-spool.lisp"))
;;; ---- derived stubs: END ----
(load-deployed-forms "books/failure-scope.lisp" '((defun fn-fs-classify-job)))
(load-deployed-forms "host/native/io.lisp" '((define-condition fnn-store-io-refusal)))
(load-deployed-forms "host/native/owner.lisp"
 '((defvar *fnn-snapshot-job*)
   (defstruct (fnn-snapshot-job (:constructor %make-fnn-snapshot-job)))
   (def-actor fnn-owner-spawn-publisher) (def-actor fnn-owner-spawn-exporter)
   (defun fnn-owner-snapshot-job-capture) (defun fnn-owner-snapshot-job-release)
   (defun fnn-owner-snapshot-job-physical) (defun fnn-owner-snapshot-jobs-drained-p)
   (defun fnn-owner-snapshot-pin-release) (defun fnn-owner-snapshot-job-run)
   (defun fnn-owner-publisher-start) (defun fnn-owner-publisher-release)
   (defun fnn-owner-export-start) (defun fnn-owner-export-captured)
   (defun fnn-owner-worker-tail-hold)
   (defun fnn-owner-actor-for-custody) (defun fnn-owner-thread-escape)))
;; No developer selector is set: the tail hold is the deployed no-op.
(defun fnn-developer-selector (name) (declare (ignore name)) nil)
(defvar *snapshot-service* nil)
(defvar *snapshot-cut* nil)
(defvar *snapshot-pin-cut* nil)
(defvar *snapshot-unpin-cut* nil)
(defvar *snapshot-unpins* 0)
(defvar *snapshot-entered* nil)
(defvar *snapshot-release* nil)
(defvar *snapshot-cleanup-entered* nil)
(defvar *fnn-checkpoint-stop-test* nil)
(defun fnn-live-arena () :captured-arena)
(defun fnn-gc-nursery-octets () (* 64 1024 1024))
(defun fnn-owner-fence-service (service)
  (setf (fnn-owner-service-stopping service) t))
(defun fnn-arena-pin ()
  (when *snapshot-pin-cut* (throw 'raw-ev-fncall :pin-torn))
  17)
(defun fnn-arena-unpin (pin)
  (assert (eql pin 17))
  (incf *snapshot-unpins*)
  (case *snapshot-unpin-cut*
    (:fault (error 'fnn-store-fault :message "pin release failed"))
    (:throw (throw 'raw-ev-fncall :pin-release-torn))
    (:hold
     (sb-thread:signal-semaphore *snapshot-cleanup-entered*)
     (assert (sb-thread:wait-on-semaphore *snapshot-release* :timeout 2))))
  nil)
(defun snapshot-operation (kind)
  (let ((job *fnn-snapshot-job*))
    (assert job)
    (assert (eq (fnn-snapshot-job-arena job) :captured-arena))
    (assert (eql (fnn-snapshot-job-pin job) 17))
    ;; Parent must install both the job's thread and the activity slot BEFORE
    ;; signal. Early exit may clear it, never followed by a stale parent store.
    (assert (eq (fnn-snapshot-job-thread job) sb-thread:*current-thread*))
    (assert (eq (if (eq kind :publisher)
                   (fnn-owner-service-publisher *snapshot-service*)
                 (fnn-owner-service-exporter *snapshot-service*))
                sb-thread:*current-thread*))
    (case *snapshot-cut*
      (:hold
       (sb-thread:signal-semaphore *snapshot-entered*)
       (assert (sb-thread:wait-on-semaphore *snapshot-release* :timeout 2)))
      (:fault (error 'fnn-store-fault :message "captured operation fault"))
      (:throw (throw 'raw-ev-fncall :captured-operation-torn))))
  3)
(defun fnn-owner-publish-captured (service captured arena &optional position pin)
  (assert (equal (list captured arena position pin) '(:capture :captured-arena :position 17)))
  (unwind-protect (snapshot-operation :publisher)
    (unwind-protect (fnn-owner-snapshot-pin-release service pin)
      (fnn-owner-publisher-release service))))
(defun fnn-owner-export-write (store records count configs frontier dir arena)
  (assert (equal (list store records count configs frontier dir arena)
                 '(:store (a b c) 3 nil :frontier :dir :captured-arena)))
  (snapshot-operation :exporter))
(defun snapshot-start (kind)
  (if (eq kind :publisher)
      (fnn-owner-publisher-start *snapshot-service* :capture :position)
    (fnn-owner-export-start *snapshot-service* '((a b c) 3 nil :frontier) :dir)))
(defun snapshot-reset ()
  (setq *snapshot-service* (%make-fnn-owner-service :store :store)
        *snapshot-cut* nil *snapshot-pin-cut* nil *snapshot-unpin-cut* nil
        *snapshot-unpins* 0 *join-faults* nil))

;; Normal operation and immediate exit: immutable capture and pin retained
;; until independent physical join, with no stale post-wake activity slot.
(dolist (kind '(:publisher :exporter))
  (snapshot-reset)
  (let* ((worker (snapshot-start kind))
         (job (car (fnn-owner-service-snapshot-jobs *snapshot-service*))))
    (sb-thread:join-thread worker :default :abnormal)
    (assert (eq (fnn-snapshot-job-stage job) :released))
    (assert (null (fnn-snapshot-job-physical job)))
    (assert (not (fnn-owner-snapshot-jobs-drained-p *snapshot-service*)))
    (assert (null (if (eq kind :publisher)
                     (fnn-owner-service-publisher *snapshot-service*)
                   (fnn-owner-service-exporter *snapshot-service*))))
    (assert (member worker (fnn-owner-service-workers *snapshot-service*)))
    (fnn-owner-actor-join *snapshot-service* worker)
    (assert (= *snapshot-unpins* 1))
    (assert (fnn-owner-snapshot-jobs-drained-p *snapshot-service*))
    (fnn-owner-actor-join *snapshot-service* worker)
    (assert (= *snapshot-unpins* 1))))

;; Failed live join retains pin, capture and activity. Cleanup held after
;; stop also keeps physical registration; last body return is not a join.
(dolist (phase '(:operation :cleanup))
  (snapshot-reset)
  (setq *snapshot-entered* (sb-thread:make-semaphore :count 0)
        *snapshot-cleanup-entered* (sb-thread:make-semaphore :count 0)
        *snapshot-release* (sb-thread:make-semaphore :count 0))
  (if (eq phase :operation) (setq *snapshot-cut* :hold)
    (setq *snapshot-unpin-cut* :hold))
  (let ((worker (snapshot-start :publisher)))
    (wait-label (if (eq phase :operation) *snapshot-entered* *snapshot-cleanup-entered*))
    (let ((*fnn-actor-thread-joiner* (lambda (&rest args) (declare (ignore args)) (error "join failed"))))
      (assert (not (fnn-owner-actor-join *snapshot-service* worker))))
    (assert (not (fnn-owner-snapshot-jobs-drained-p *snapshot-service*)))
    (assert (sb-thread:thread-alive-p worker))
    (sb-thread:signal-semaphore *snapshot-release*)
    (fnn-owner-actor-join *snapshot-service* worker)
    (assert (fnn-owner-snapshot-jobs-drained-p *snapshot-service*))))

;; Operation failures (including raw ACL2 throws) still run pin cleanup. Pin
;; cleanup failures instead remain once-only debt after physical join.
(dolist (kind '(:publisher :exporter))
  (dolist (cut '(:fault :throw))
    (snapshot-reset)
    (setq *snapshot-cut* cut)
    (let ((worker (snapshot-start kind)))
      (fnn-owner-actor-join *snapshot-service* worker)
      (assert (fnn-owner-service-stopping *snapshot-service*))
      (assert (fnn-owner-snapshot-jobs-drained-p *snapshot-service*))
      (assert (= *snapshot-unpins* 1)))))
(dolist (cut '(:fault :throw))
  (snapshot-reset)
  (setq *snapshot-unpin-cut* cut)
  (let ((worker (snapshot-start :publisher)))
    (fnn-owner-actor-join *snapshot-service* worker)
    (let ((job (car (fnn-owner-service-snapshot-jobs *snapshot-service*))))
      (assert (eq (fnn-snapshot-job-stage job) :releasing))
      (assert (eq (fnn-snapshot-job-physical job) :terminal))
      (assert (eql (fnn-snapshot-job-pin job) 17))
      (assert (eq (fnn-snapshot-job-captured job) :capture))
      (fnn-owner-snapshot-job-release *snapshot-service* job)
      (fnn-owner-actor-join *snapshot-service* worker)
      (assert (= *snapshot-unpins* 1))
      (assert (not (fnn-owner-snapshot-jobs-drained-p *snapshot-service*))))))

;; Pin call torn before it returned retains an unknown envelope, no retry.
(snapshot-reset)
(setq *snapshot-pin-cut* t)
(catch 'raw-ev-fncall (snapshot-start :publisher))
(assert (eq (fnn-snapshot-job-stage (car (fnn-owner-service-snapshot-jobs *snapshot-service*))) :pinning))
(assert (not (fnn-owner-snapshot-jobs-drained-p *snapshot-service*)))

;; Definite maker failure releases pin. Post-create no-op termination retains
;; parked child and pin until actual termination/physical join.
(snapshot-reset)
(let ((*fnn-actor-thread-maker* (lambda (&rest args) (declare (ignore args)) (error "no child"))))
  (assert (handler-case (progn (snapshot-start :publisher) nil) (serious-condition () t)))
  (assert (= *snapshot-unpins* 1))
  (assert (fnn-owner-snapshot-jobs-drained-p *snapshot-service*)))
(snapshot-reset)
(let ((*fnn-actor-start-signal* (lambda (&rest args) (declare (ignore args)) (error "signal failed")))
      (*fnn-actor-thread-terminator* (lambda (worker) (declare (ignore worker)) nil)))
  (assert (handler-case (progn (snapshot-start :exporter) nil) (serious-condition () t))))
(let* ((job (car (fnn-owner-service-snapshot-jobs *snapshot-service*)))
       (worker (fnn-snapshot-job-thread job)))
  (assert (sb-thread:thread-alive-p worker))
  (assert (= *snapshot-unpins* 0))
  (assert (eq (fnn-owner-service-exporter *snapshot-service*) worker))
  (sb-thread:terminate-thread worker)
  (fnn-owner-actor-join *snapshot-service* worker)
  (assert (= *snapshot-unpins* 1))
  (assert (null (fnn-owner-service-exporter *snapshot-service*)))
  (assert (fnn-owner-snapshot-jobs-drained-p *snapshot-service*)))

;; Actual starts run under owner exclusion. Post-create compensation/join
;; faults must use that held fence, never recursively acquire the mutex.
(snapshot-reset)
(setf (fnn-owner-service-lock *snapshot-service*)
      (sb-thread:make-mutex :name "snapshot capture owner"))
(let ((saved (symbol-function 'fnn-owner-stop-service-locked)) (held-faults 0))
  (unwind-protect
       (progn
         (setf (symbol-function 'fnn-owner-stop-service-locked)
               (lambda (service exit &optional answering)
                 (declare (ignore answering))
                 (assert (eq exit +fnn-exit-fault+))
                 (assert (sb-thread:holding-mutex-p (fnn-owner-service-lock service)))
                 (incf held-faults)
                 (setf (fnn-owner-service-stopping service) t)))
         (let ((*fnn-actor-start-signal* (lambda (&rest args) (declare (ignore args)) (error "capture latch failed")))
               (*fnn-actor-thread-terminator* (lambda (worker) (declare (ignore worker)) nil)))
           (sb-thread:with-mutex ((fnn-owner-service-lock *snapshot-service*))
             (assert (handler-case (progn (snapshot-start :publisher) nil) (serious-condition () t)))))
         (assert (plusp held-faults))
         (let* ((job (car (fnn-owner-service-snapshot-jobs *snapshot-service*)))
                (worker (fnn-snapshot-job-thread job)))
           (assert (sb-thread:thread-alive-p worker))
           (assert (eq (fnn-snapshot-job-stage job) :holding))
           (sb-thread:terminate-thread worker)
           (fnn-owner-actor-join *snapshot-service* worker)
           (assert (fnn-owner-snapshot-jobs-drained-p *snapshot-service*))))
    (setf (symbol-function 'fnn-owner-stop-service-locked) saved)))
(format t "native_snapshot_actor_raw: PASS capture/pre-wake slot/early exit/physical join/pin cleanup debt/maker and latch failure~%")
