;;; A rejected owner group lookup must become a completed refusal word.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")

(define-condition fnn-store-error (error) ())
(define-condition fnn-store-fault (fnn-store-error) ())
(define-condition fnn-store-indeterminate (fnn-store-error) ())
(define-condition fnn-os-error (error) ())
(defvar *calls* nil)
(defvar *bad-group* t)
(defvar *bad-charge* nil)
(defun fnn-owner-service-store (service) (declare (ignore service)) :store)
(defun fnn-charge (length)
  (declare (ignore length))
  (if *bad-charge* (error 'fnn-store-error) 1))
(defun fnn-octet-list (x) x)
(defun fnn-owner-core (name &rest args)
  (push (cons name args) *calls*)
  (case name (fn-owner-group-codes (if *bad-group* :bad '(0)))
        (otherwise (error "unexpected ACL2 call ~s" name))))
(defun fnn-refuse (&rest args) (declare (ignore args)) (error 'fnn-store-error))

(let ((found nil))
  (with-open-file (stream "host/native/owner.lisp")
    (loop for form = (read stream nil :eof)
          until (eq form :eof)
          when (and (consp form) (eq (car form) 'defun)
                    (eq (cadr form) 'fnn-owner-attempt))
            do (eval form) (setf found t)))
  (unless found (error "deployed owner attempt missing")))

(unless (eq (fnn-owner-attempt :service '(1) '(2) '((102 110 46 108 105 118 101)) '(3))
            :refused)
  (error "unknown group escaped before the Store-attempt refusal handler"))
(unless (equal (reverse *calls*)
               '((fn-owner-group-codes ((102 110 46 108 105 118 101)))))
  (error "owner lookup did not use current ACL2 allocation domain: ~s"
         (reverse *calls*)))
(setq *bad-group* nil *bad-charge* t *calls* nil)
(unless (eq (fnn-owner-attempt :service '(1) '(2) '((102 110 46 116 101 115 116)) '(3))
            :refused)
  (error "charge preflight escaped before the Store-attempt refusal handler"))
(unless (equal (reverse *calls*)
               '((fn-owner-group-codes ((102 110 46 116 101 115 116)))))
  (error "charge refusal did not follow the ACL2 owner group lookup"))
(format t "native owner group-code boundary passed~%")
