;;; Actual snapshot capture/starter/cleanup + shared actor and export body,
;;; recording pin/archive leaves; physical SBCL threads, no file proof claim.
(load "tests/native_actor_envelope_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-owner-syncer-physical (service grant receipt)
  (declare (ignorable service grant receipt))
  (harness-stub-reached 'fnn-owner-syncer-physical "host/native/owner.lisp"))
;;; ---- derived stubs: END ----
(load-deployed-forms "books/failure-scope.lisp" '((defun fn-fs-classify-job)))
(load-deployed-forms "host/native/io.lisp" '((define-condition fnn-store-io-refusal)))
(load-deployed-forms "host/native/owner.lisp"
 '((defvar *fnn-snapshot-job*)
   (defstruct (fnn-snapshot-job (:constructor %make-fnn-snapshot-job)))
   (def-actor fnn-owner-spawn-publisher) (def-actor fnn-owner-spawn-exporter)
   (defun fnn-owner-snapshot-job-capture) (defun fnn-owner-snapshot-job-release)
   (defun fnn-owner-snapshot-job-physical) (defun fnn-owner-snapshot-jobs-drained-p)
   (defun fnn-owner-snapshot-pin-release) (defun fnn-owner-snapshot-job-run)
   (defun fnn-owner-publisher-start) (defun fnn-owner-publisher-release)
   (defun fnn-owner-export-start) (defun fnn-owner-export-captured)
   (defun fnn-owner-actor-for-custody) (defun fnn-owner-thread-escape)))
(defvar *snapshot-service* nil)
(defvar *snapshot-cut* nil)
(defvar *snapshot-pin-cut* nil)
(defvar *snapshot-unpin-cut* nil)
(defvar *snapshot-unpins* 0)
(defvar *snapshot-entered* nil)
(defvar *snapshot-release* nil)
(defvar *snapshot-cleanup-entered* nil)
(defvar *fnn-checkpoint-stop-test* nil)
(defun fnn-live-arena () :captured-arena)
(defun fnn-gc-nursery-octets () (* 64 1024 1024))
(defun fnn-owner-fence-service (service)
  (setf (fnn-owner-service-stopping service) t))
(defun fnn-arena-pin ()
  (when *snapshot-pin-cut* (throw 'raw-ev-fncall :pin-torn))
  17)
(defun fnn-arena-unpin (pin)
  (assert (eql pin 17))
  (incf *snapshot-unpins*)
  (case *snapshot-unpin-cut*
    (:fault (error 'fnn-store-fault :message "pin release failed"))
    (:throw (throw 'raw-ev-fncall :pin-release-torn))
    (:hold
     (sb-thread:signal-semaphore *snapshot-cleanup-entered*)
     (assert (sb-thread:wait-on-semaphore *snapshot-release* :timeout 2))))
  nil)
(defun snapshot-operation (kind)
  (let ((job *fnn-snapshot-job*))
    (assert job)
    (assert (eq (fnn-snapshot-job-arena job) :captured-arena))
    (assert (eql (fnn-snapshot-job-pin job) 17))
    ;; Parent must install both the job's thread and the activity slot BEFORE
    ;; signal. Early exit may clear it, never followed by a stale parent store.
    (assert (eq (fnn-snapshot-job-thread job) sb-thread:*current-thread*))
    (assert (eq (if (eq kind :publisher)
                   (fnn-owner-service-publisher *snapshot-service*)
                 (fnn-owner-service-exporter *snapshot-service*))
                sb-thread:*current-thread*))
    (case *snapshot-cut*
      (:hold
       (sb-thread:signal-semaphore *snapshot-entered*)
       (assert (sb-thread:wait-on-semaphore *snapshot-release* :timeout 2)))
      (:fault (error 'fnn-store-fault :message "captured operation fault"))
      (:throw (throw 'raw-ev-fncall :captured-operation-torn))))
  3)
(defun fnn-owner-publish-captured (service captured arena &optional position pin)
  (assert (equal (list captured arena position pin) '(:capture :captured-arena :position 17)))
  (unwind-protect (snapshot-operation :publisher)
    (unwind-protect (fnn-owner-snapshot-pin-release service pin)
      (fnn-owner-publisher-release service))))
(defun fnn-owner-export-write (store records count configs frontier dir arena)
  (assert (equal (list store records count configs frontier dir arena)
                 '(:store (a b c) 3 nil :frontier :dir :captured-arena)))
  (snapshot-operation :exporter))
(defun snapshot-start (kind)
  (if (eq kind :publisher)
      (fnn-owner-publisher-start *snapshot-service* :capture :position)
    (fnn-owner-export-start *snapshot-service* '((a b c) 3 nil :frontier) :dir)))
(defun snapshot-reset ()
  (setq *snapshot-service* (%make-fnn-owner-service :store :store)
        *snapshot-cut* nil *snapshot-pin-cut* nil *snapshot-unpin-cut* nil
        *snapshot-unpins* 0 *join-faults* nil))

;; Normal operation and immediate exit: immutable capture and pin retained
;; until independent physical join, with no stale post-wake activity slot.
(dolist (kind '(:publisher :exporter))
  (snapshot-reset)
  (let* ((worker (snapshot-start kind))
         (job (car (fnn-owner-service-snapshot-jobs *snapshot-service*))))
    (sb-thread:join-thread worker :default :abnormal)
    (assert (eq (fnn-snapshot-job-stage job) :released))
    (assert (null (fnn-snapshot-job-physical job)))
    (assert (not (fnn-owner-snapshot-jobs-drained-p *snapshot-service*)))
    (assert (null (if (eq kind :publisher)
                     (fnn-owner-service-publisher *snapshot-service*)
                   (fnn-owner-service-exporter *snapshot-service*))))
    (assert (member worker (fnn-owner-service-workers *snapshot-service*)))
    (fnn-owner-actor-join *snapshot-service* worker)
    (assert (= *snapshot-unpins* 1))
    (assert (fnn-owner-snapshot-jobs-drained-p *snapshot-service*))
    (fnn-owner-actor-join *snapshot-service* worker)
    (assert (= *snapshot-unpins* 1))))

;; Failed live join retains pin, capture and activity. Cleanup held after
;; stop also keeps physical registration; last body return is not a join.
(dolist (phase '(:operation :cleanup))
  (snapshot-reset)
  (setq *snapshot-entered* (sb-thread:make-semaphore :count 0)
        *snapshot-cleanup-entered* (sb-thread:make-semaphore :count 0)
        *snapshot-release* (sb-thread:make-semaphore :count 0))
  (if (eq phase :operation) (setq *snapshot-cut* :hold)
    (setq *snapshot-unpin-cut* :hold))
  (let ((worker (snapshot-start :publisher)))
    (wait-label (if (eq phase :operation) *snapshot-entered* *snapshot-cleanup-entered*))
    (let ((*fnn-actor-thread-joiner* (lambda (&rest args) (declare (ignore args)) (error "join failed"))))
      (assert (not (fnn-owner-actor-join *snapshot-service* worker))))
    (assert (not (fnn-owner-snapshot-jobs-drained-p *snapshot-service*)))
    (assert (sb-thread:thread-alive-p worker))
    (sb-thread:signal-semaphore *snapshot-release*)
    (fnn-owner-actor-join *snapshot-service* worker)
    (assert (fnn-owner-snapshot-jobs-drained-p *snapshot-service*))))

;; Operation failures (including raw ACL2 throws) still run pin cleanup. Pin
;; cleanup failures instead remain once-only debt after physical join.
(dolist (kind '(:publisher :exporter))
  (dolist (cut '(:fault :throw))
    (snapshot-reset)
    (setq *snapshot-cut* cut)
    (let ((worker (snapshot-start kind)))
      (fnn-owner-actor-join *snapshot-service* worker)
      (assert (fnn-owner-service-stopping *snapshot-service*))
      (assert (fnn-owner-snapshot-jobs-drained-p *snapshot-service*))
      (assert (= *snapshot-unpins* 1)))))
(dolist (cut '(:fault :throw))
  (snapshot-reset)
  (setq *snapshot-unpin-cut* cut)
  (let ((worker (snapshot-start :publisher)))
    (fnn-owner-actor-join *snapshot-service* worker)
    (let ((job (car (fnn-owner-service-snapshot-jobs *snapshot-service*))))
      (assert (eq (fnn-snapshot-job-stage job) :releasing))
      (assert (eq (fnn-snapshot-job-physical job) :terminal))
      (assert (eql (fnn-snapshot-job-pin job) 17))
      (assert (eq (fnn-snapshot-job-captured job) :capture))
      (fnn-owner-snapshot-job-release *snapshot-service* job)
      (fnn-owner-actor-join *snapshot-service* worker)
      (assert (= *snapshot-unpins* 1))
      (assert (not (fnn-owner-snapshot-jobs-drained-p *snapshot-service*))))))

;; Pin call torn before it returned retains an unknown envelope, no retry.
(snapshot-reset)
(setq *snapshot-pin-cut* t)
(catch 'raw-ev-fncall (snapshot-start :publisher))
(assert (eq (fnn-snapshot-job-stage (car (fnn-owner-service-snapshot-jobs *snapshot-service*))) :pinning))
(assert (not (fnn-owner-snapshot-jobs-drained-p *snapshot-service*)))

;; Definite maker failure releases pin. Post-create no-op termination retains
;; parked child and pin until actual termination/physical join.
(snapshot-reset)
(let ((*fnn-actor-thread-maker* (lambda (&rest args) (declare (ignore args)) (error "no child"))))
  (assert (handler-case (progn (snapshot-start :publisher) nil) (serious-condition () t)))
  (assert (= *snapshot-unpins* 1))
  (assert (fnn-owner-snapshot-jobs-drained-p *snapshot-service*)))
(snapshot-reset)
(let ((*fnn-actor-start-signal* (lambda (&rest args) (declare (ignore args)) (error "signal failed")))
      (*fnn-actor-thread-terminator* (lambda (worker) (declare (ignore worker)) nil)))
  (assert (handler-case (progn (snapshot-start :exporter) nil) (serious-condition () t))))
(let* ((job (car (fnn-owner-service-snapshot-jobs *snapshot-service*)))
       (worker (fnn-snapshot-job-thread job)))
  (assert (sb-thread:thread-alive-p worker))
  (assert (= *snapshot-unpins* 0))
  (assert (eq (fnn-owner-service-exporter *snapshot-service*) worker))
  (sb-thread:terminate-thread worker)
  (fnn-owner-actor-join *snapshot-service* worker)
  (assert (= *snapshot-unpins* 1))
  (assert (null (fnn-owner-service-exporter *snapshot-service*)))
  (assert (fnn-owner-snapshot-jobs-drained-p *snapshot-service*)))

;; Actual starts run under owner exclusion. Post-create compensation/join
;; faults must use that held fence, never recursively acquire the mutex.
(snapshot-reset)
(setf (fnn-owner-service-lock *snapshot-service*)
      (sb-thread:make-mutex :name "snapshot capture owner"))
(let ((saved (symbol-function 'fnn-owner-stop-service-locked)) (held-faults 0))
  (unwind-protect
       (progn
         (setf (symbol-function 'fnn-owner-stop-service-locked)
               (lambda (service exit &optional answering)
                 (declare (ignore answering))
                 (assert (eq exit +fnn-exit-fault+))
                 (assert (sb-thread:holding-mutex-p (fnn-owner-service-lock service)))
                 (incf held-faults)
                 (setf (fnn-owner-service-stopping service) t)))
         (let ((*fnn-actor-start-signal* (lambda (&rest args) (declare (ignore args)) (error "capture latch failed")))
               (*fnn-actor-thread-terminator* (lambda (worker) (declare (ignore worker)) nil)))
           (sb-thread:with-mutex ((fnn-owner-service-lock *snapshot-service*))
             (assert (handler-case (progn (snapshot-start :publisher) nil) (serious-condition () t)))))
         (assert (plusp held-faults))
         (let* ((job (car (fnn-owner-service-snapshot-jobs *snapshot-service*)))
                (worker (fnn-snapshot-job-thread job)))
           (assert (sb-thread:thread-alive-p worker))
           (assert (eq (fnn-snapshot-job-stage job) :holding))
           (sb-thread:terminate-thread worker)
           (fnn-owner-actor-join *snapshot-service* worker)
           (assert (fnn-owner-snapshot-jobs-drained-p *snapshot-service*))))
    (setf (symbol-function 'fnn-owner-stop-service-locked) saved)))
(format t "native_snapshot_actor_raw: PASS capture/pre-wake slot/early exit/physical join/pin cleanup debt/maker and latch failure~%")
