(load "tests/native_immutable_close_source.lisp")
(in-package "ACL2")
(defconstant +fnn-exit-ok+ 0)
(defconstant +fnn-export-chunk+ 1024)
(defvar *export-failure* nil)
(defvar *export-store* nil)
(defun fnn-open-live-store (&rest args) (declare (ignore args)) (values *export-store* 0))
(defun fnn-lstat (&rest args) (declare (ignore args)) nil)
(defun fnn-export-test-fault () nil)
(defun fnn-config-path (&rest args) (declare (ignore args)) "/config")
(defun fnn-read-regular-bounded (&rest args) (declare (ignore args)) #(1))
(defun fnn-octet-list (x) (coerce x 'list))
(defun fnn-metadata-frontier-frame (&rest args) (declare (ignore args)) nil)
(defun fnn-config-record-observation (&rest args) (declare (ignore args)) nil)
(defun fnn-core (name &rest args)
  (declare (ignore args)) (case name (fn-sxp-export-head '((nil nil))) (otherwise (error "unexpected core ~a" name))))
(defun fnn-join (&rest args) (declare (ignore args)) "/manifest")
(defun fnn-mkdir (&rest args) (declare (ignore args)))
(defun fnn-export-step (&rest args)
  (declare (ignore args)) (when (eq *export-failure* :body-close) (error *body-primary*)))
(defun fnn-log-history-each (&rest args) (declare (ignore args)))
(defun fnn-export-at (&rest args) (declare (ignore args)))
(defun fnn-export-sync-data (&rest args) (declare (ignore args)))
(defun fnn-replace (&rest args)
  (declare (ignore args)) (setq *published* t)
  (when (eq *export-failure* :rename) (error *physical*)))
(defun fnn-fsync-dir (&rest args)
  (declare (ignore args)) (when (and *published* (eq *export-failure* :barrier)) (error *physical*)))
(defun fnn-out (&rest args) (declare (ignore args)))
(with-open-file (in "host/native/io.lisp")
 (loop for f = (read in nil :eof) until (eq f :eof) do
  (when (and (consp f) (eq (car f) 'defun) (eq (second f) 'fnn-command-store-export)) (eval f))))
(dolist (fault '(:close :body-close :rename :barrier nil))
  (let ((*fnn-immutable-close-debts* nil) (*fnn-publication-close-debts* nil)
        (*publication-failure* (and (member fault '(:close :body-close)) fault))
        (*export-failure* fault) (*publication-calls* nil) (*published* nil)
        (*export-store* (%make-fnn-store :root "/root")) (caught nil) (code nil))
    (handler-case (setq code (fnn-command-store-export "/root" "/export"))
      (error (e) (setq caught e)))
    (assert (= 1 (count '(:close 55) *publication-calls* :test #'equal)))
    (cond ((eq fault :body-close) (assert (eq caught *body-primary*)))
          (fault (assert (typep caught 'fnn-store-indeterminate)))
          (t (assert (null caught)) (assert (= code 0))))
    (when (member fault '(:rename :barrier)) (assert *published*))
    (when (member fault '(:close :body-close))
      (assert (fnn-store-close-debt *export-store*))
      (assert (eq (aref (car *fnn-immutable-close-debts*) 4) *export-store*)))))
(format t "native export terminal source PASS~%")
