;;; Actual retained BP host consumer, with recording typed-bank boundary.
(load "tests/native_tcpcl_retained_turn_raw.lisp")
(in-package "ACL2")
(defconstant +fnn-gc-nursery-octets+ 1)
(defun len (x) (length x))
(defun posp (x) (and (integerp x) (< 0 x)))
(defun member-equal (x xs) (member x xs :test #'equal))
(defun true-listp (x) (or (null x) (and (consp x) (true-listp (cdr x)))))
(defun fn-ag-car (x) (and (consp x) (car x)))
(with-open-file (stream "books/bp-session-profile.lisp")
 (loop for form = (read stream nil :eof) until (eq form :eof) do
  (when (and (consp form) (eq (first form) 'defun)
             (member (second form) '(fn-bpsg-row fn-bpsg-step fn-bpsg-release-ready fn-bpsg-slots fn-bpsg-key fn-bpsp-root-release-ready fn-bpsg-context-abort-plan)))
   (eval (cons 'defun (cons (second form) (cons (third form)
    (remove-if (lambda (x) (and (consp x) (eq (car x) 'declare))) (cdddr form)))))))))
(with-open-file (stream "books/bp-session-scheduler.lisp")
 (loop for form = (read stream nil :eof) until (eq form :eof) do
  (when (and (consp form) (eq (first form) 'defun)
             (member (second form) '(fn-bpsched-service fn-bpsched-next fn-bpsched-next-slot
                       fn-bpsched-listener-index fn-bpsched-deadline fn-bpsched-timeout-p fn-bpsched-work-credit fn-bpsched-idle-p)))
   (eval (cons 'defun (cons (second form) (cons (third form)
    (remove-if (lambda (x) (and (consp x) (eq (car x) 'declare))) (cdddr form)))))))))
(define-condition fnn-peer-dial-error (error) ())
(defun fnn-indeterminate (&rest xs) (error "indeterminate ~s" xs))
(load "host/native/bp-session.lisp")
(defvar *receipts* nil)
(defvar *closures* 0)
(defvar *close-receipt* :closed)
(defun fnn-socket-shut (socket)
 (incf *closures*) (values nil (if (eq socket :first-unobserved) :unobserved *close-receipt*) :unobserved))
(defun fnn-call (name &rest args)
 (case name
  (fn-bpsg-return
   (assert (fifth (first args))) (assert (sixth (first args)))
   (push :settled *receipts*) (list :settled (second args)))
  (otherwise (error "unexpected call ~s" name))))
(defun fnn-core (name &rest args)
 (case name
  ((fn-bpsg-context-abort-plan fn-bpsg-step fn-bpsg-release-ready fn-bpsg-key fn-bpsched-service fn-bpsched-next
     fn-bpsched-next-slot fn-bpsched-listener-index fn-bpsched-deadline fn-bpsched-timeout-p
     fn-bpsched-work-credit fn-bpsched-idle-p)
   (apply name args))
  (fn-bpsched-accept-plan '(:accept 1 9))
  (fn-bpsched-listener-step (first args))
  (fn-bplc-runtime-line "BP NODE GENERATION witness")
  (fn-tcl-host-tcp-closed (list :closed nil nil))
  (fn-tcl-host-phase (first args))
  (otherwise (error "unexpected core ~s" name))))
(defun test-bank () (make-fnn-bp-session-bank :grant '(:hold 1000000 10 1000 2 1 30000)
                         :ledger :ledger :slots (make-array 5 :initial-element nil)))
(defun test-grant (bank slot class &optional socket conn)
 (let ((grant (make-fnn-bp-session-grant :row (fn-bpsg-row slot 1 class) :socket socket :conn conn)))
  (setf (gethash grant (fnn-bpsb-held bank)) t (aref (fnn-bpsb-slots bank) slot) grant) grant))
;;; Physical receipt alone holds the exact reservation; later context release settles once.
(let* ((bank (test-bank)) (conn (make-fnn-tcl-conn))
       (grant (test-grant bank 2 :incoming :socket conn)))
 (fnn-bp-session-close bank grant)
 (assert (= (hash-table-count (fnn-bpsb-held bank)) 1))
 (fnn-bp-session-release-context bank grant)
 (assert (= (hash-table-count (fnn-bpsb-held bank)) 1))
 (setf (fnn-tclc-finished conn) t)
 (fnn-bp-session-release-context bank grant)
 (assert (zerop (hash-table-count (fnn-bpsb-held bank))))
 (assert (= (count :settled *receipts*) 1)))
;;; An unobserved physical close cannot settle even when the context is terminal.
(let* ((bank (test-bank)) (grant (test-grant bank 2 :incoming :socket (make-fnn-tcl-conn :finished t)))
       (*close-receipt* :unobserved) (caught nil) (before *closures*))
 (handler-case (fnn-bp-session-close bank grant) (error () (setq caught t)))
 (assert caught) (assert (not (sixth (fnn-bpsg-row grant))))
 (fnn-bp-session-release-context bank grant)
 (assert (= (hash-table-count (fnn-bpsb-held bank)) 1))
 (fnn-bp-session-close bank grant)
 (assert (= *closures* (+ before 1))))
(let* ((bank (test-bank))
       (first (test-grant bank 2 :incoming :first-unobserved (make-fnn-tcl-conn :finished t)))
       (second (test-grant bank 3 :incoming :second (make-fnn-tcl-conn :finished t)))
       (condition (fnn-bp-session-abort-all bank nil)))
 (assert condition)
 (assert (gethash first (fnn-bpsb-held bank)))
 (assert (not (gethash second (fnn-bpsb-held bank))))
 (assert (not (fn-bpsp-root-release-ready (hash-table-count (fnn-bpsb-held bank)))))
 (assert (fnn-bpsg-close-attempted second)))
;;; Rearm keeps the same token and reservation while changing physical sockets.
(let* ((bank (test-bank)) (conn (make-fnn-tcl-conn :finished t))
       (grant (test-grant bank 4 :outgoing :socket conn)) (row (copy-list (fnn-bpsg-row grant)))
       (before (length *receipts*)))
 (fnn-bp-session-rearm bank grant "literal" 9 :params "test" "/spool"
  (lambda (c) (declare (ignore c))) (lambda (j r) (declare (ignore j r))))
 (assert (equal row (fnn-bpsg-row grant)))
 (assert (= (length *receipts*) before))
 (assert (= (hash-table-count (fnn-bpsb-held bank)) 1)))
;;; The actual loop admits another session while the first remains alive; each
;;; of its eight local services runs before the first completes.
(defvar *accepted* 0)
(defvar *served* nil)
(defvar *first-turns* 0)
(defvar *second-ran* nil)
(defun fnn-out (&rest xs) (declare (ignore xs)))
(defun fnn-bpnc-pump (x) (declare (ignore x)))
(defun fnn-bplc-live (x) (declare (ignore x)) '(9))
(defun fnn-bplc-model (x) x)
(defun (setf fnn-bplc-model) (value object) (declare (ignore object)) value)
(defun fnn-socket-fd (x) x)
(defun fnn-poll-readable (fds timeout) (declare (ignore fds timeout)) (< *accepted* 2))
(defun fnn-accept-attempt (x) (declare (ignore x)) (incf *accepted*) (list :socket *accepted*))
(defun fnn-bp-session-acquire (bank class)
 (let ((slot (find nil (fnn-bpsb-slots bank) :start 2 :end 4)))
  (declare (ignore slot))
  (loop for i from 2 below 4 unless (aref (fnn-bpsb-slots bank) i)
   do (return (test-grant bank i class)))))
(let ((bank (test-bank)) (stopped nil))
 (catch 'stop
  (fnn-bp-session-loop bank nil :listeners
   (lambda (grant socket)
    (declare (ignore socket))
    (setf (fnn-bpsg-turn grant)
      (if (= *accepted* 1)
       (lambda () (incf *first-turns*) :wait)
       (lambda () (setq *second-ran* t) :done)))) nil
   (lambda (action)
    (pushnew action *served*)
    (when (and *second-ran* (= (length *served*) 8)) (setq stopped t) (throw 'stop t)))
   (lambda () nil)))
 (assert stopped) (assert *second-ran*) (assert (> *first-turns* 0))
 (assert (= (hash-table-count (fnn-bpsb-held bank)) 1)))
;;; Terminal outcome is consumed once even when a received-source dependency
;;; retains the context; no repeated result publication or invented return.
(let* ((bank (test-bank))
       (grant (test-grant bank 2 :incoming :socket
                  (make-fnn-tcl-conn :finished t :source-pending t)))
       (completions 0) (services 0) (*accepted* 2))
 (setf (fnn-bpsg-turn grant) (lambda () :done)
       (fnn-bpsg-finish grant) (lambda (job) (declare (ignore job)) (incf completions) nil))
 (catch 'stop
  (fnn-bp-session-loop bank nil :listeners (lambda (&rest xs) (declare (ignore xs))) nil
   (lambda (action) (declare (ignore action))
    (incf services) (when (= services 12) (throw 'stop t))) (lambda () nil)))
 (assert (= completions 1))
 (assert (null (fnn-bpsg-turn grant))) (assert (null (fnn-bpsg-finish grant)))
 (assert (gethash grant (fnn-bpsb-held bank)))
 (assert (fnn-tclc-source-pending (fnn-bpsg-conn grant))))
(format t "PASS actual BP retained bank/loop: close custody, ambiguous return, fragment rearm, live peer fairness.~%")

;;; Abort ordinary live contexts only after future callbacks are disabled.
;;; Neither logical termination nor timeout invents a physical close receipt.
(dolist (fenced '(nil t))
 (dolist (physical '(:closed :unobserved))
  (let* ((bank (test-bank))
         (conn (make-fnn-tcl-conn :retained t :session :established
                :held '(:unreleased-ack) :input-vector #(1 2 3) :input-octets '(1 2 3)))
         (grant (test-grant bank 2 :incoming :socket conn))
         (*close-receipt* physical))
   (setf (fnn-tclc-fenced conn) fenced
         (fnn-bpsg-turn grant) (lambda () (error "aborted turn invoked"))
         (fnn-bpsg-finish grant) (lambda (&rest xs) (declare (ignore xs)) (error "aborted finish invoked")))
   (fnn-bp-session-abort-all bank nil)
   (assert (null (fnn-bpsg-turn grant))) (assert (null (fnn-bpsg-finish grant)))
   (if fenced
    (progn (assert (gethash grant (fnn-bpsb-held bank)))
           (assert (equal (fnn-tclc-held conn) '(:unreleased-ack))))
    (progn (assert (fnn-tclc-finished conn)) (assert (null (fnn-tclc-held conn)))
           (assert (null (fnn-tclc-input-vector conn))) (assert (null (fnn-tclc-input-octets conn)))
           (assert (null (fnn-bpsg-conn grant)))
           (assert (eq (not (null (gethash grant (fnn-bpsb-held bank)))) (eq physical :unobserved))))))))
(format t "PASS ordinary live abort retires volatile aliases without ACK; publication fence and unobserved physical return remain held.~%")
