;;; Actual HTTP continuation consumer with adversarial readiness/completion
;;; schedules. Tiny semantic adapters are not an ACL2 proof or an image test.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(deftype fnn-octets () '(simple-array (unsigned-byte 8) (*)))
(define-condition fnn-os-error (error) ())
(define-condition fnn-store-error (error) ())
(define-condition fnn-store-fault (fnn-store-error) ())
(define-condition fnn-store-indeterminate (fnn-store-error) ())
(define-condition fnn-tls-error (error) ())
(defvar *the-live-state* nil)
(defvar *fnn-sigterm-requested* nil)
(defvar *fnn-operator-config-octets* nil)
(defvar *clock* 0)
(defvar *written* nil)
(defvar *closed* nil)
(defvar *released* nil)
(defvar *callbacks* nil)
(defvar *feeds* nil)
(defvar *faults* nil)
(defvar *write-limit* 137)
(defvar *read-result* :input)
(defvar *cold-result* '(:wait 2))
(defvar *render-cold* nil)
(defvar *poll-timeout* nil)
(defconstant +fnn-mux-pollin+ 1)
(defconstant +fnn-mux-pollout+ 4)
(defconstant +fnn-mux-poll-trouble+ 56)
(defmacro def-actor (name &key thread-name roster)
  (declare (ignore thread-name roster))
  `(defun ,name (&rest args) (declare (ignore args)) (error "fixture never starts an actor")))
(defmacro def-section (name &key actors classes admits doc)
  (declare (ignore actors classes admits doc))
  `(defun ,name (service cid thunk &optional class)
     (declare (ignore service cid class)) (funcall thunk)))
(defun fn-fs-inbox-admit (closed) (if closed :closed :admitted))
(defun fnn-fault (control &rest args) (error (apply #'format nil control args)))
(defun fnn-now () *clock*)
(defun fnn-mux-ms-ticks (ms) (+ *clock* (ceiling (* ms internal-time-units-per-second) 1000)))
(defun fnn-owner-monotonic-ms () (floor (* *clock* 1000) internal-time-units-per-second))
(defun fnn-make-octets (n) (make-array n :element-type '(unsigned-byte 8) :initial-element 0))
(defun fnn-octets (xs) (coerce xs '(simple-array (unsigned-byte 8) (*))))
(defun create-fn-octets$c () (vector (fnn-make-octets 0) 0))
(defun fn-octets$c-reserve (n st)
  (when (< (length (svref st 0)) n)
    (let ((new (fnn-make-octets n))) (replace new (svref st 0)) (setf (svref st 0) new))) st)
(defun fnn-octet-list-p (xs) (every (lambda (x) (typep x '(unsigned-byte 8))) xs))
(defun fnn-core (name &rest args)
  (case name
    (fn-web-host-head '(72 69 65 68))
    (fn-web-host-reserve-size (if (<= (first args) (second args)) (second args)
                              (max 1024 (* 2 (first args)))))
    (fn-web-host-window-end (min (second args) (+ (first args) 4096)))
    (fn-web-host-max-events 16)
    (fn-web-host-request-seconds 15)
    (fn-web-host-action-kind (first (first args)))
    (fn-splan-cursor-resume-ms 2)
    (fn-splan-step-plan (second args))
    (t (error "unexpected core ~s ~s" name args))))
(defun fnn-call (name &rest args)
  (case name
    (fn-web-host-event-cid (list nil))
    (fn-web-host-step
     (let ((out (fifth args)))
       (fnn-web-fill out (fnn-octets '(65 66 67)))
       (list (list :respond 200 nil t) out nil)))
    (t (error "unexpected call ~s" name))))
(defun fnn-owner-serialized (service cid thunk &optional class)
  (declare (ignore service cid class)) (funcall thunk))
(defun fnn-owner-service-stopping (service) (declare (ignore service)) nil)
(defun fnn-owner-thread-escape (service condition label)
  (declare (ignore service label)) (push condition *faults*))
(defun fnn-owner-response-unpin (service cid) (declare (ignore service)) (push cid *released*))
(defun fnn-owner-action (name cid) (push (list name cid) *released*) :ok)
(defun fnn-owner-await-register (service cid callback socket)
  (declare (ignore service socket)) (push (cons cid callback) *callbacks*) nil)
(defun fnn-owner-await-abandon (service cid) (declare (ignore service)) (push (list :abandon cid) *released*))
(defun fnn-owner-cold-abandon (read) (push (list :cold read) *released*))
(defun fnn-owner-handle-chunk-step (service cid incoming socket class peerp &rest word)
  (declare (ignore service socket class peerp word))
  (push (list cid (coerce incoming 'list)) *feeds*)
  (values :await :step nil nil nil (length incoming)))
(defun fnn-owner-render-next-quantum (service cid plan class)
  (declare (ignore service cid class))
  (if *render-cold* (values (fnn-make-octets 0) plan nil nil :read)
    (values (fnn-octets '(50 52 48 13 10)) nil t nil nil)))
(defun fnn-owner-cold-poll (service read first since)
  (declare (ignore service read first)) (values *cold-result* since 10 nil))
(defun fnn-transport-write-now (fd channel data offset)
  (declare (ignore channel))
  (let ((n (min *write-limit* (- (length data) offset))))
    (push (list fd (coerce (subseq data offset (+ offset n)) 'list)) *written*) n))
(defun fnn-mux-read-plain (fd buffer) (declare (ignore fd buffer)) *read-result*)
(defun fnn-socket-shut (socket) (push socket *closed*))
(defun fnn-socket-fd (socket) socket)
(defun fnn-mux-poll (fds events timeout)
  (declare (ignore events)) (setq *poll-timeout* timeout) (make-array (length fds) :initial-element 0))
(load (or (sb-ext:posix-getenv "FN_WEB_REACTOR_SOURCE") "host/native/web-host.lisp"))
(defun fixture-conn (socket phase &optional cid)
  (%make-fnn-web-conn :socket socket :fd socket :phase phase :cid cid
                     :in (create-fn-octets$c) :out (create-fn-octets$c) :deadline 15))
(defun wire-for (fd)
  (loop for (socket bytes) in (reverse *written*) when (= socket fd) append bytes))
;;; Window/partial offset: exact bytes, no whole HTTP body copy.
(let* ((conn (fixture-conn 1 :event)) (face (%make-fnn-web-face :service :service))
       (body (fnn-make-octets 10003)))
  (dotimes (i (length body)) (setf (aref body i) (mod i 256)))
  (fnn-web-fill (fnn-web-conn-out conn) body)
  (let ((saved (symbol-function 'fnn-core)))
    (unwind-protect
      (progn (setf (symbol-function 'fnn-core)
               (lambda (name &rest args)
                 (if (eq name 'fn-web-host-head) '(72 69 65 68) (apply saved name args))))
        (fnn-web-response face conn 200 nil t)
        (loop until (eq (fnn-web-conn-phase conn) :done) do
          (assert (<= (length (fnn-web-conn-wire conn)) 4096))
          (fnn-web-write-ready face conn))
        (assert (equal (wire-for 1) (append '(72 69 65 68) (coerce body 'list)))))
      (setf (symbol-function 'fnn-core) saved))))
;;; Stalled input, awaiting POST and healthy rendering coexist in one actor.
(let* ((slow (fixture-conn 2 :head)) (post (fixture-conn 3 :feed 7))
       (healthy (fixture-conn 4 :event))
       (face (%make-fnn-web-face :service :service :capacity 3 :conns (list slow post healthy))))
  (fnn-web-fill (fnn-web-conn-out post) (fnn-octets '(80 79 83 84)))
  (setf (fnn-web-conn-cmd-end post) 4)
  (fnn-web-feed-step face post)
  (assert (eq (fnn-web-conn-phase post) :await))
  (fnn-web-advance face healthy)
  (assert (eq (fnn-web-conn-phase healthy) :write))
  (assert (eq (fnn-web-conn-phase slow) :head))
  ;; Publication callback is a mailbox only; it cannot render or write.
  (setf (fnn-web-face-wake-closed face) t)
  (funcall (cdr (assoc 7 *callbacks*)) :completion)
  (assert (eq (fnn-web-conn-phase post) :await))
  (fnn-web-advance face post)
  (assert (eq (fnn-web-conn-phase post) :render))
  (fnn-web-render-step face post)
  (fnn-web-render-step face post)
  (fnn-web-feed-step face post)
  (assert (eq (fnn-web-conn-phase post) :event))
  (assert (equalp (fnn-web-slice (fnn-web-conn-in post) 0 5) (fnn-octets '(50 52 48 13 10))))
  (fnn-web-finish face post)
  (let ((n (length *closed*)))
    (fnn-web-finish face post) (assert (= n (length *closed*))))
  (fnn-web-await-publish face post :late)
  (assert (null (fnn-web-conn-completion post))))
;;; Cold render retains exact plan/pin; wait makes no progress, serve resumes.
(let* ((conn (fixture-conn 5 :render 8)) (face (%make-fnn-web-face :service :service))
       (plan (list :original-plan)))
  (setf (fnn-web-conn-plan conn) plan)
  (let ((*render-cold* t)) (fnn-web-render-step face conn))
  (assert (eq (fnn-web-conn-phase conn) :cold))
  (assert (eq (fnn-web-conn-plan conn) plan))
  (setq *clock* (+ *clock* internal-time-units-per-second))
  (fnn-web-cold-step face conn)
  (assert (eq (fnn-web-conn-phase conn) :cold))
  (setq *clock* (+ *clock* internal-time-units-per-second))
  (let ((*cold-result* :serve)) (fnn-web-cold-step face conn))
  (assert (eq (fnn-web-conn-phase conn) :render))
  (assert (eq (fnn-web-conn-plan conn) plan)))
;;; Same session cannot acquire two pending feed/await routes.
(let* ((one (fixture-conn 6 :await 9)) (two (fixture-conn 7 :feed 9))
       (face (%make-fnn-web-face :conns (list one two))))
  (setf (fnn-web-conn-leased one) t)
  (assert (not (fnn-web-feed-owned-p face two)))
  (setf (fnn-web-conn-leased one) nil)
  (assert (fnn-web-feed-owned-p face two)))
;;; Actual fixed worker: a blocked owner operation does not block the reactor.
(let* ((post (fixture-conn 10 :feed 11)) (healthy (fixture-conn 12 :event))
       (face (%make-fnn-web-face :service :service :capacity 2 :conns (list post healthy)
                                 :wake-closed t))
       (entered (sb-thread:make-semaphore)) (release (sb-thread:make-semaphore))
       (saved (symbol-function 'fnn-owner-handle-chunk-step)) (worker nil))
  (fnn-web-fill (fnn-web-conn-out post) (fnn-octets '(80 79 83 84)))
  (setf (fnn-web-conn-cmd-end post) 4)
  (unwind-protect
    (progn
      (setf (symbol-function 'fnn-owner-handle-chunk-step)
            (lambda (&rest args)
              (sb-thread:signal-semaphore entered)
              (sb-thread:wait-on-semaphore release)
              (apply saved args)))
      (setq worker (sb-thread:make-thread (lambda () (fnn-web-semantic-body face))))
      (fnn-web-advance face post)
      (assert (sb-thread:wait-on-semaphore entered :timeout 2))
      (fnn-web-advance face healthy)
      (assert (eq (fnn-web-conn-phase healthy) :write))
      (let ((before (length *released*)))
        (fnn-web-finish face post)
        (assert (= before (length *released*))) ; semantic custody still live
        (assert (member 10 *closed*))) ; transport disposed independently
      (sb-thread:signal-semaphore release)
      (sb-thread:with-mutex ((fnn-web-face-lock face))
        (setf (fnn-web-face-jobs-closed face) t)
        (sb-thread:condition-notify (fnn-web-face-job-ready face)))
      (sb-thread:join-thread worker :timeout 2)
      (assert (not (sb-thread:thread-alive-p worker)))
      (assert (fnn-web-job-returned (fnn-web-conn-job post)))
      (assert (eq (fnn-web-conn-phase post) :done))
      (assert (member '(:abandon 11) *released* :test #'equal))
      (fnn-web-job-consume face post)
      (assert (null (fnn-web-conn-job post)))
      (assert (not (fnn-web-job-submit face healthy :render))))
    (setf (symbol-function 'fnn-owner-handle-chunk-step) saved)))
;;; Cleanup has a receipt separate from worker activation return. A paused
;;; cancelled CID release cannot disappear from capacity/lease ownership.
(let* ((old (fixture-conn 20 :feed 21)) (next (fixture-conn 22 :feed 21))
       (face (%make-fnn-web-face :service :service :capacity 2 :listener 100
                                 :conns (list old next) :wake-closed t))
       (entered (sb-thread:make-semaphore)) (release (sb-thread:make-semaphore))
       (saved (symbol-function 'fnn-owner-action)) (worker nil))
  (setf (fnn-web-conn-leased old) t)
  (fnn-web-fill (fnn-web-conn-out old) (fnn-octets '(80 79 83 84)))
  (setf (fnn-web-conn-cmd-end old) 4)
  (fnn-web-job-submit face old :feed)
  (fnn-web-finish face old)
  (unwind-protect
    (progn
      (setf (symbol-function 'fnn-owner-action)
            (lambda (name cid)
              (when (and (eq name 'fn-owner-close) (= cid 21))
                (sb-thread:signal-semaphore entered)
                (sb-thread:wait-on-semaphore release))
              (funcall saved name cid)))
      (setq worker (sb-thread:make-thread (lambda () (fnn-web-semantic-body face))))
      (assert (sb-thread:wait-on-semaphore entered :timeout 2))
      (assert (fnn-web-job-returned (fnn-web-conn-job old)))
      (fnn-web-iterate face)
      (assert (member old (fnn-web-face-conns face)))
      (assert (not (fnn-web-conn-semantic-ended old)))
      (fnn-web-finish face old) ; a concurrent shutdown observer
      (assert (not (fnn-web-conn-semantic-ended old)))
      (assert (not (fnn-web-feed-owned-p face next)))
      (sb-thread:signal-semaphore release)
      (sb-thread:with-mutex ((fnn-web-face-lock face))
        (setf (fnn-web-face-jobs-closed face) t)
        (sb-thread:condition-notify (fnn-web-face-job-ready face)))
      (sb-thread:join-thread worker :timeout 2)
      (assert (fnn-web-conn-semantic-ended old))
      (assert (fnn-web-feed-owned-p face next)))
    (setf (symbol-function 'fnn-owner-action) saved)))
(assert (null *faults*))
(format t "native web continuation raw: PASS exact windows, slow+healthy+POST, mailbox, cold resume, session lease, once cleanup~%")
