;;; Compose actual arena-return and lifecycle wrappers. Recording callbacks
;;; below model a destructive arena reset and release that mutates then escapes;
;;; no whole-owner or concrete ACL2 arena refinement is claimed.
(load "tests/native_arena_return_source.lisp")
(in-package "ACL2")
(defun member-equal (x xs) (member x xs :test #'equal))
(with-open-file (in "books/payload-view-lease.lisp")
  (loop for f = (read in nil :eof) until (eq f :eof) do
    (when (and (consp f) (eq (car f) 'defun)
               (member (second f) '(fn-pvl-runtime-step fn-pvl-runtime-return-step)))
      (eval (append (subseq f 0 3)
                    (remove-if (lambda (x) (and (consp x) (eq (car x) 'declare)))
                               (nthcdr 3 f)))))))
(defun fnn-core (name &rest args)
  (assert (member name '(fn-pvl-runtime-step fn-pvl-runtime-return-step)))
  (apply (symbol-function name) args))
(defvar *the-live-state* nil)
(defvar *payload-reset-count* 0)
(defvar *payload-release-callback* (symbol-function 'fnn-call))
(defun fnn-call (name &rest args)
  (if (eq name 'fn-owner-payload-view-reset)
      (progn
        (assert (eq (first args) *arena*))
        (incf *payload-reset-count*)
        (setf (car *arena*) :reset)
        (list nil '(:reset)))
    (apply *payload-release-callback* name args)))
(with-open-file (in "host/native/io.lisp")
  (loop for f = (read in nil :eof) until (eq f :eof) do
    (when (and (consp f) (member (car f) '(defvar defun))
               (member (second f)
                       '(*fnn-payload-lifecycle-lock* *fnn-payload-lifecycle-phase*
                         *fnn-payload-lifecycle-arena* *fnn-payload-lifecycle-owner*
                         fnn-payload-lifecycle-answer fnn-payload-startup-reset)))
      (eval f))))
(dolist (failure '(0 :escape :not-started))
  (let ((*fnn-arena-release-custody* nil)
        (*fnn-payload-lifecycle-phase* :quiescent)
        (*arena* (list :staged :staged)) (*arena-failure* failure)
        (*due* '((0 0 1))) (*payload-reset-count* 0))
    (fnn-arena-release-due)
    (unless (eq failure :not-started)
      (handler-case (catch 'arena-escape (fnn-arena-release-returned))
        (simple-error () nil)))
    (let ((custody *fnn-arena-release-custody*) (before (copy-list *arena*)))
      (assert (eq (fnn-arena-return-observation nil) :uncertain))
      (assert (equal (fnn-payload-startup-reset) '(:refused :arena-not-quiescent)))
      (assert (zerop *payload-reset-count*))
      (dolist (event '(:start :recover))
        (assert (equal (fnn-payload-lifecycle-answer event nil nil)
                       '(:refused :quiescent))))
      (setq *fnn-payload-lifecycle-phase* :draining)
      (assert (equal (fnn-payload-lifecycle-answer :joined nil t)
                     '(:refused :draining)))
      (assert (eq custody *fnn-arena-release-custody*))
      (assert (equal *arena* before)))))
;; Definite physical return leaves reset available; the gate is not a permanent
;; refusal or a proxy for logical phase/lease validation.
(let ((*fnn-arena-release-custody* nil)
      (*fnn-payload-lifecycle-phase* :quiescent)
      (*arena* (list :staged)) (*arena-failure* nil)
      (*due* '((0 0))) (*payload-reset-count* 0))
  (fnn-arena-release-due)
  (fnn-arena-release-returned)
  (assert (eq (fnn-arena-return-observation nil) :closed))
  (assert (equal (fnn-payload-startup-reset) '(:reset)))
  (assert (= *payload-reset-count* 1)))
(format t "native payload return/reset composition PASS~%")
