(require :sb-posix)
(require :sb-bsd-sockets)
;;; Load complete production definitions, inject physical close failures.
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(defun fnn-err (&rest ignored) (declare (ignore ignored)))
(with-open-file (input "host/native/io.lisp")
  (loop for form = (read input nil :eof) until (eq form :eof) do
    (when (and (consp form) (eq (car form) 'defmacro)
               (eq (second form) 'fnn-unwind-cleanups)) (eval form))))
(defstruct fnn-owner-service store feeds)
(defvar *calls* nil)
(defvar *close-condition* (make-condition 'simple-error :format-control "close failed"))
(defvar *open-condition* (make-condition 'simple-error :format-control "open failed"))
(defun fnn-owner-feed-close (journal)
  (push journal *calls*)
  (when (member journal '(:a :b)) (error *close-condition*)))
(defun fnn-owner-feed-existing-peers (store) (declare (ignore store)) nil)
(defun fnn-owner-feed-open (store peer)
  (declare (ignore store))
  (cond ((equal peer "a") :a) ((equal peer "b") :b) (t (error *open-condition*))))
(with-open-file (input "host/native/owner.lisp")
  (loop for form = (read input nil :eof) until (eq form :eof) do
    (when (and (consp form) (eq (car form) 'defun)
               (member (second form) '(fnn-owner-feed-close-entries fnn-owner-feed-open-all
                                      fnn-owner-feed-close-all fnn-owner-feed-open-missing)))
      (eval form))))
(let ((service (make-fnn-owner-service :feeds '(("a" . :a) ("b" . :b) ("c" . :c))))
      (caught nil) (*calls* nil))
  (handler-case (fnn-owner-feed-close-all service) (error (e) (setq caught e)))
  (assert (eq caught *close-condition*))
  (assert (equal (reverse *calls*) '(:a :b :c)))
  (assert (null (fnn-owner-service-feeds service))))
(dolist (operation '(fnn-owner-feed-open-all fnn-owner-feed-open-missing))
  (let ((service (make-fnn-owner-service :feeds '(("old" . :old))))
        (caught nil) (*calls* nil))
    (handler-case (funcall operation service '("a" "b" "fail"))
      (error (e) (setq caught e)))
    (assert (eq caught *open-condition*))
    (assert (equal (reverse *calls*) '(:b :a)))
    (assert (equal (fnn-owner-service-feeds service) '(("old" . :old))))))
(format t "PASS actual source feed cleanup: all closes attempted; primary open failure preserved.~%")
;;; Routing helper must attempt Store cleanup even after journal close fails.
(defvar *route-body-fails* t)
(defun fnn-owner-install (&rest ignored) (declare (ignore ignored)) :owner)
(defun fnn-owner-core (&rest ignored)
  (declare (ignore ignored))
  (if *route-body-fails* (error *open-condition*) :routes))
(defun fnn-owner-service-store (owner) (declare (ignore owner)) :store)
(defun fnn-owner-feed-close-all (owner)
  (declare (ignore owner)) (push :feeds *calls*) (error *close-condition*))
(defun fnn-store-close (store)
  (declare (ignore store)) (push :store *calls*) (error *close-condition*))
(with-open-file (input "host/native/bp-service.lisp")
  (loop for form = (read input nil :eof) until (eq form :eof) do
    (when (and (consp form) (eq (car form) 'defun)
               (eq (second form) 'fnn-bps-read-route-table)) (eval form))))
(dolist (body-fails '(t nil))
  (let ((*route-body-fails* body-fails) (*calls* nil) (caught nil))
    (handler-case (fnn-bps-read-route-table "/unused") (error (e) (setq caught e)))
    (assert (equal (reverse *calls*) '(:feeds :store)))
    (assert (eq caught (if body-fails *open-condition* *close-condition*)))))
(format t "PASS actual route-table cleanup: Store close attempted; primary condition preserved.~%")
