;;; Actual heap routing, profile capture and transport adapter. Physical
;;; liveness/transport are fixtures; the liveness decision is the real book.
(load "tests/native_operator_diagnostics_source-mock.lisp")
(in-package "ACL2")
(with-open-file (in "host/native/operator.lisp")
  (loop for form = (read in nil :eof) until (eq form :eof) do
    (when (and (consp form) (eq (car form) 'defstruct)
               (consp (second form)) (eq (caadr form) 'fnn-operator-live-owner))
      (eval form))))
(source-forms "books/native-control.lisp" '(fn-native-control-liveness))
(source-forms "host/native/store-identity.lisp"
              '(fnn-live-profile-read fnn-live-profile-owner-reply))
(defvar *disk-reads* 0)
(defvar *profile-asks* 0)
(defvar *socket-present* t)
(defvar *lock* :held)
(defvar *under-owner* nil)
(defvar *reply-ok* t)
(defvar *base-core* (symbol-function 'fnn-core))
(defun fnn-core (name &rest args)
  (case name
    (fn-omr-control-path-octets '(47 99))
    (fn-lpf-request '(26))
    (fn-lpf-reply-bound 676)
    (fn-lpf-reply (assert (not *under-owner*))
                  (assert (equal args '((:recorded-profile)))) '(27))
    (fn-lpf-reply-read (assert (equal args '((27))))
                       (and *reply-ok* '(:decided-profile)))
    (otherwise (apply *base-core* name args))))
(defun fnn-heap-store-profile (root)
  (assert (equal root "/fixture")) (incf *disk-reads*) '(:offline-profile))
(defun fnn-owner-serialized (service id thunk &optional class)
  (declare (ignore service id class))
  (let ((*under-owner* t)) (funcall thunk)))
(defun fnn-owner-service-store (service)
  (assert *under-owner*) service)
(defun fnn-octets-string (octets) (coerce (map 'list #'code-char octets) 'string))
(defun fnn-control-exchange (path request &optional bound seconds)
  (declare (ignore seconds))
  (assert (equal path "/c")) (assert (equal request '(26))) (assert (= bound 676))
  (incf *profile-asks*) (values #(27) :after-submission))
(assert (equal (fnn-live-profile-owner-reply (make-fixture-store)) '(27)))
(let ((*fnn-operator-live-owner*
        (make-fnn-operator-live-owner
         :admin-observe (lambda (root path queryp)
                          (assert (equal root "/fixture")) (assert (equal path '(47 99)))
                          (assert queryp)
                          (fn-native-control-liveness *socket-present* *lock*))
         :profile #'fnn-live-profile-read)))
  ;; Planted config occupants cannot be read on this path: no disk callback.
  (assert (equal (fnn-heap-operator-profile "CONFIG" '("group" "create" "fn.occupied"))
                 '(:decided-profile)))
  (assert (= *profile-asks* 1)) (assert (zerop *disk-reads*))
  ;; A live owner's bad reply is a fault, with no disk fallback.
  (let ((*reply-ok* nil))
    (assert (eq (handler-case (fnn-heap-operator-store-profile "/fixture" :result)
                  (fnn-store-fault () :fault)) :fault)))
  (assert (zerop *disk-reads*))
  ;; No reachable control socket with a held lock also forbids disk reads.
  (let ((*socket-present* nil))
    (assert (eq (handler-case (fnn-heap-operator-store-profile "/fixture" :result)
                  (fnn-store-error () :refused)) :refused)))
  (assert (zerop *disk-reads*))
  ;; The stopped/stale controls alone select disk observation.
  (dolist (socket '(nil t))
    (let ((*socket-present* socket) (*lock* :free))
      (assert (equal (fnn-heap-operator-store-profile "/fixture" :result) '(:offline-profile)))))
  (assert (= *disk-reads* 2)))
(format t "live profile: capture under owner, framing off owner, live/held never read disk; offline/stale controls passed~%")
