;;; Actual registered private creator and normal output-method counterparts.
;;; The ledger seed is a typed protocol fixture, not a physical heap grant.
(in-package "ACL2")
(require :sb-posix)
(require :sb-bsd-sockets)
(defun fnor-load-host-forms (path wanted)
  (let ((missing (copy-list wanted)))
    (with-open-file (stream path)
      (loop for form = (read stream nil :eof) until (eq form :eof)
            when (and (consp form)
                      (member (list (car form) (cadr form)) wanted :test #'equal))
              do (eval form)
                 (setf missing (remove (list (car form) (cadr form)) missing :test #'equal))))
    (when missing (error "output retirement host forms missing: ~s" missing))))
(defvar *fnor-io-path* (merge-pathnames "../host/native/io.lisp" *load-truename*))
(fnor-load-host-forms *fnor-io-path*
 '((define-condition fnn-store-error) (define-condition fnn-store-fault)
   (define-condition fnn-entry-guard-fault) (defun fnn-fault)
   (defun fnn-counterpart) (defun fnn-install-raw-dispatch)
   (defun fnn-dispatch-function) (defun fnn-guard-conjuncts)
   (defun fnn-entry-guard-spec) (defun fnn-entry-guard-describe)
   (defun fnn-entry-guard) (defun fnn-call) (defun fnn-core)))
(defvar *fnn-dispatch-counterpart* nil)
(defvar *fnn-raw-dispatch* (make-hash-table :test 'eq))
(defvar *fnn-startup-creators* (make-hash-table :test 'eq))
(defvar *fnn-entry-guard-specs* (make-hash-table :test 'eq))
(defvar *fn-entry-guard-kinds* nil)
(fnn-install-raw-dispatch :report nil)
(dolist (first '(:output :physical))
  (let* ((ledger (fnn-core 'create-fn-resource-ledger))
         (token nil))
    (setq *fnn-dispatch-counterpart* t)
    (dolist (name '(fn-rl-install fn-rlo-issue fn-rlo-output fn-rlo-physical))
      (unless (eq (fnn-dispatch-function name) (fnn-counterpart name))
        (error "retirement probe did not use normal counterpart: ~s" name)))
    (unless (eq (first (fnn-call 'fn-rl-install '(16777216 0 0 0 0 0 0 0 0)
                          '(8192 0 0 0 0 0 0 0 0) '(1048576 0 0 0 0 0 0 0 0) 4 ledger)) :installed)
      (error "typed protocol fixture installation refused"))
    (fnn-call 'fn-rlo-free-init 2 ledger)
    ;; Fixture-only state seed: same installed column shape and u64 domain.
    (update-fn-rl-next 2 ledger)
    (update-fn-rl-file-limit 1048576 ledger)
    (update-fn-rl-mode 2 ledger)
    (update-fn-rl-gensi 2 (1- *fn-rl-word-max*) ledger)
    (let ((issue (fnn-call 'fn-rlo-issue 7 11 8 :issued ledger)))
      (setq token (second issue))
      (unless (and (eq (first issue) :drawn) (= (fourth token) *fn-rl-word-max*))
        (error "last representable generation was not issued exactly")))
    (let ((one (if (eq first :output)
                   (fnn-call 'fn-rlo-output token 8 :discarded ledger)
                 (fnn-call 'fn-rlo-physical token 8 :terminal ledger)))
          (two nil))
      (unless (eq (first one) :pending) (error "one receipt released custody"))
      (setq two (if (eq first :output)
                    (fnn-call 'fn-rlo-physical token 8 :terminal ledger)
                  (fnn-call 'fn-rlo-output token 8 :discarded ledger)))
      (unless (and (eq (first two) :settled) (= (fn-rl-next ledger) 3)
                   (= (fn-rl-gensi 2 ledger) *fn-rl-word-max*))
        (error "exhausted row blocked free head or wrapped generation")))
    (unless (and (eq (first (fnn-call 'fn-rlo-output token 8 :discarded ledger)) :stale)
                 (eq (first (fnn-call 'fn-rlo-physical token 8 :terminal ledger)) :stale))
      (error "settled receipt replay changed retired custody"))
    (let ((issue (fnn-call 'fn-rlo-issue 9 15 12 :issued ledger)))
      (unless (and (eq (first issue) :drawn)
                   (equal (second issue) '(:resource (:connection 9 15) 3 1)))
        (error "retired row stranded the remaining typed protocol row")))))
(format t "~%native_output_retirement_raw: PASS registered creator, normal counterparts, both receipt orders, no wrap and remaining-row progress; generic protocol fixture, not fresh-service RID reachability or heap coverage~%")
