;;; Send only after actual decoded-worker-job plus the actual projected host
;;; issuer have loaded. Native execution probe, not an ACL2 proof event.
;;; Existing native trust boundary permits inspection of fresh concrete fields.
(defttag :fn-native-host)
(progn! (set-raw-mode t)
 (let* ((job (create-fn-decoded-job))
        (ledger (cadr (multiple-value-list (fn-prl-register (fn-prl-make '(100000 0 2 1 20)) 7 '(64 0 1 0 0)))))
        (pool (create-fn-page-read-pool))
        (descriptor '(7 100 320 120 40 200 99 250 0)))
  (update-fn-prp-mode :served pool)
  (update-fn-prp-data (list ledger 0 0 0 1) pool)
  (let* ((issued (multiple-value-list (fn-owner-page-decoded-window-acquire-projected (fn-pxe-new 0) descriptor pool)))
         (token (third issued)) (worker (second issued))
         (charged (fn-prl-nth 1 (fn-owner-page-read-ledger pool))))
   (assert (eq (first issued) :assigned))
   (assert (eq (fourth issued) :partial-fixed-storage))
   (assert (equal charged '(86992 0 1 1 1)))
   (assert (not (eq :assigned (first (multiple-value-list
      (fn-owner-page-decoded-window-acquire-projected (fn-pxe-new 1) descriptor pool))))))
   (assert (equal charged (fn-prl-nth 1 (fn-owner-page-read-ledger pool))))
   (assert (eq :decoded-assigned (first (multiple-value-list
      (fn-dwj-assign (fn-owner-page-read-ledger pool) worker token token 47 job)))))
   (assert (eq :decoded-started (first (multiple-value-list (fn-dwj-begin token job)))))
   (assert (= (length job) 8))
   (assert (equal (loop for child across job collect (length child)) '(12 2 16 20 2 2 2 16384)))
   (assert (= (length (svref (svref job 2) 15)) 64))
   (assert (equal (loop for i in '(1 4 5 6) collect (length (svref (svref job i) 0))) '(64 65536 3494 64)))
   (let ((returned (multiple-value-list (fn-pwx-return (fn-owner-page-read-ledger pool) worker token))))
    (assert (eq :returned (first returned)))
    (assert (equal charged (fn-prl-nth 1 (third returned))))
    (let ((released (multiple-value-list (fn-pwx-release (third returned) (second returned) token))))
     (assert (eq :released (first released)))
     (assert (equal '(64 0 1 0 1) (fn-prl-nth 1 (third released))))
     (fn-owner-page-read-keep-ledger (third released) pool)
     (assert (eq :assigned (first (multiple-value-list
       (fn-owner-page-decoded-window-acquire-projected (second released) descriptor pool)))))))
   ;; A complete installation cannot borrow the legacy projected issuer.
   (update-fn-prp-alloc-installation :complete-test-installation pool)
   (let ((before (fn-prp-data pool))
         (reply (multiple-value-list (fn-owner-page-decoded-window-acquire-projected (fn-pxe-new 1) descriptor pool))))
    (assert (eq :unpriced-decoded-window (first reply)))
    (assert (null (third reply)))
    (assert (equal before (fn-prp-data pool))))
   (format t "native_decoded_constructor_source: PASS actual dimensions/fixed-storage overcommit/return-held/release/full-profile refusal~%")))
 (set-raw-mode nil))
(defttag nil)
