; Actual primitive -> actual core bodies, under explicit unissued diagnostics.
; Reads only trusted repository source; never external article/bundle input.
; CL shims supply ACL2 builtins, not a second suite/comparison decision.
(require :sb-posix)
(unless (find-package "ACL2") (make-package "ACL2" :use '("COMMON-LISP")))
(in-package "ACL2")
(declaim (declaration xargs))
(defparameter *fn-bpc-max-uint* 18446744073709551615)
(defun natp (x) (and (integerp x) (<= 0 x)))
(defun zp (x) (or (not (integerp x)) (<= x 0)))
(dolist (selection '(("books/cbor.lisp" fn-cbor-octetp)
                     ("books/bpsec-model.lisp" fn-bps-field fn-bps-uintp)
                     ("books/bpsec-operation.lisp")
                     ("books/bpsec-primitive-plan.lisp")))
 (with-open-file (stream (car selection))
  (loop for form = (read stream nil :end) until (eq form :end)
   when (and (eq (car form) 'defun)
             (or (null (cdr selection)) (member (second form) (cdr selection))))
   do (eval form))))
(handler-bind ((style-warning #'muffle-warning))
 (load "host/native/crypto.lisp")
 (load "host/native/tls.lisp")
 (load "host/native/bpsec-crypto.lisp"))
(load "tests/fixtures/bpsec/nist-gcm-decrypt.lisp")
(defvar *bpsec-core-observation-checks* 0)
(defun bpsec-observation-check (x)
 (incf *bpsec-core-observation-checks*) (assert x))
(defun bpsec-observation-hex (s)
 (let ((v (make-array (/ (length s) 2) :element-type '(unsigned-byte 8))))
  (dotimes (i (length v) v)
   (setf (aref v i) (parse-integer s :radix 16 :start (* i 2) :end (+ 2 (* i 2)))))))
(defun bpsec-observation-feed (function handle bytes quantum)
 (loop for at from 0 below (length bytes) by quantum do
  (bpsec-observation-check (null (funcall function handle bytes at (min quantum (- (length bytes) at)))))))
(defun bpsec-observation-descriptor (action variant width)
 (fn-bps-op-make action '(:bps-ref 1 1) '(:bps-ref 2 1) '(:bps-ref 3 1)
  '(:bps-ref 4 1) 7 1 (if (eq action :verify-bib) 1 2)
  (if (eq action :verify-bib) (list :bps-bib-params variant 7 nil)
   (list :bps-bcb-params variant 7 '(:bytes-span 9 0 12) nil :separate-tag))
  '(:bps-ref 5 1) (list :bytes-span 9 256 width)))
; RFC4868 sections2.7.2.1/2/3 AUTH*-1 full PRF outputs; BPSec uses FULL
; width, never the truncated IPsec authenticators. Keys are output-sized.
(dolist (row '((5 32 "198a607eb44bfbc69903a0f1cf2bbdc5ba0aa3f3d9ae3c1c7a3b1696a0b68cf7")
               (6 48 "b6a8d5636f5c6a7224f9977dcf7ee6c7fb6d0c48cbdee9737a959796489bddbc4c5df61d5b3297b4fb68dab9f1b582c2")
               (7 64 "637edc6e01dce7e6742a99451aae82df23da3e92439e590e43e761b33e910fb8ac2878ebd5803f6f0b61dbce5e251ff8789a4722c1be65aea45fd464e89f8f5b")))
 (destructuring-bind (variant width literal) row
  (let* ((descriptor (bpsec-observation-descriptor :verify-bib variant width))
         (key (make-array width :element-type '(unsigned-byte 8) :initial-element 11))
         (input (bpsec-observation-hex "4869205468657265"))
         (expected (coerce (bpsec-observation-hex literal) 'list))
         (plan (fn-bps-primitive-select descriptor (length key))))
   (bpsec-observation-check (eq (first plan) :bps-primitive-plan))
   (bpsec-observation-check (equal (fn-bps-primitive-select descriptor 16) '(:refused :key-width)))
   (dolist (q '(1 7 64))
    (let ((handle (fnn-bpsec-hmac-start descriptor (third plan) key 64)))
     (unwind-protect
      (progn
       (bpsec-observation-feed #'fnn-bpsec-hmac-update handle input q)
       (let* ((raw (fnn-bpsec-hmac-final handle))
              (actual (coerce (subseq (third raw) 0 (fourth raw)) 'list))
              (observation (list :bps-primitive-observation (first raw) (second raw) actual))
              (answer (fn-bps-primitive-answer descriptor observation expected))
              (completion (fourth answer))
              (operation (list :bps-operation :issued descriptor)))
        (bpsec-observation-check (eq (first raw) descriptor))
        (bpsec-observation-check (equal answer (list :bps-primitive-status :verified :ok
                                               (list :bps-completion descriptor :verified nil :ok))))
        (bpsec-observation-check (eq (second (fn-bps-op-complete operation (fn-bps-op-current descriptor) completion)) :verified))
        (bpsec-observation-check (null (fifth (fn-bps-op-complete operation nil completion))))
        (bpsec-observation-check (eq (second (fn-bps-op-complete (fn-bps-op-cancel operation) (fn-bps-op-current descriptor) completion)) :ignored))
        (let ((changed (copy-list expected)))
         (setf (car (last changed)) (logxor 1 (car (last changed))))
         (bpsec-observation-check (eq (second (fn-bps-primitive-answer descriptor observation changed)) :failed)))
        (bpsec-observation-check (eq (second (fn-bps-primitive-answer descriptor
          (list :bps-primitive-observation (bpsec-observation-descriptor :verify-bib variant width) :hmac-bytes (butlast actual)) expected)) :uncertain))
        (fnn-bpsec-cleanse (third raw))))
      (fnn-bpsec-cancel handle)))))))
; Actual CAVP auth/refusal output goes through the core. Successful first
; authentication pass cannot produce a verified BCB completion/plaintext ref.
(dolist (row *fnn-bpsec-test-nist-gcm*)
 (destructuring-bind (name cipher keyhex ivhex aadhex cthex taghex plaintext) row
  (declare (ignore name))
  (let* ((descriptor (bpsec-observation-descriptor :decrypt-bcb (if (eq cipher :aes128-gcm) 1 3) 16))
         (key (bpsec-observation-hex keyhex))
         (plan (fn-bps-primitive-select descriptor (length key))))
   (bpsec-observation-check (eq (third plan) cipher))
   (dolist (q '(1 7 64))
    (let ((handle (fnn-bpsec-gcm-start descriptor (third plan) key (bpsec-observation-hex ivhex) 64)))
     (unwind-protect
      (progn
       (bpsec-observation-feed #'fnn-bpsec-gcm-aad handle (bpsec-observation-hex aadhex) q)
       (bpsec-observation-feed #'fnn-bpsec-gcm-update handle (bpsec-observation-hex cthex) q)
       (let* ((raw (fnn-bpsec-gcm-final handle (bpsec-observation-hex taghex)))
              (answer (fn-bps-primitive-answer descriptor (list :bps-primitive-observation (first raw) (second raw) (third raw)) nil)))
        (bpsec-observation-check (eq (first raw) descriptor))
        (bpsec-observation-check (null (third raw)))
        (if plaintext
         (progn (bpsec-observation-check (eq (second answer) :authenticated))
                (bpsec-observation-check (not (fn-bps-completionp (fourth answer)))))
         (progn (bpsec-observation-check (eq (second answer) :failed))
                (bpsec-observation-check (fn-bps-completionp (fourth answer)))))))
      (fnn-bpsec-cancel handle)))))))
(format t "PASS actual primitive -> actual core observations checks=~d, unissued diagnostic descriptors, no native admission~%" *bpsec-core-observation-checks*)
