(load "tests/native_store_cleanup_source.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-core "host/native/io.lisp"))
(defun fnn-core-state (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-core-state "host/native/io.lisp"))
(defun fnn-fault (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-fault "host/native/io.lisp"))
(defun fnn-history-last-record (store)
  (declare (ignorable store))
  (harness-stub-reached 'fnn-history-last-record "host/native/io.lisp"))
(defun fnn-indeterminate (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-indeterminate "host/native/io.lisp"))
(defun fnn-log-history-release-prefix (store)
  (declare (ignorable store))
  (harness-stub-reached 'fnn-log-history-release-prefix "host/native/io.lisp"))
(defun fnn-log-line (line)
  (declare (ignorable line))
  (harness-stub-reached 'fnn-log-line "host/native/io.lisp"))
(defun fnn-make-owner-gate ()
  (harness-stub-reached 'fnn-make-owner-gate "host/native/owner.lisp"))
(defun fnn-ms-since-process-start ()
  (harness-stub-reached 'fnn-ms-since-process-start "host/native/io.lisp"))
(defun fnn-open-report (store)
  (declare (ignorable store))
  (harness-stub-reached 'fnn-open-report "host/native/io.lisp"))
(defun fnn-owner-advance-clock ()
  (harness-stub-reached 'fnn-owner-advance-clock "host/native/owner.lisp"))
(defun fnn-owner-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-owner-core "host/native/owner.lisp"))
(defun fnn-owner-feed-close-all (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-feed-close-all "host/native/owner.lisp"))
(defun fnn-owner-feed-flush (service publication)
  (declare (ignorable service publication))
  (harness-stub-reached 'fnn-owner-feed-flush "host/native/owner.lisp"))
(defun fnn-owner-feed-open-all (service configured)
  (declare (ignorable service configured))
  (harness-stub-reached 'fnn-owner-feed-open-all "host/native/owner.lisp"))
(defun fnn-owner-feed-reconcile (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-feed-reconcile "host/native/owner.lisp"))
(defun fnn-owner-feed-step (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-owner-feed-step "host/native/owner.lisp"))
(defun fnn-owner-feed-word (publication)
  (declare (ignorable publication))
  (harness-stub-reached 'fnn-owner-feed-word "host/native/owner.lisp"))
(defun fnn-owner-history-root-maintain (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-history-root-maintain "host/native/history-root.lisp"))
(defun fnn-owner-install-node-secret (store ring)
  (declare (ignorable store ring))
  (harness-stub-reached 'fnn-owner-install-node-secret "host/native/owner.lisp"))
(defun fnn-owner-key-statement-recover (service records)
  (declare (ignorable service records))
  (harness-stub-reached 'fnn-owner-key-statement-recover "host/native/owner.lisp"))
(defun fnn-owner-names (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-owner-names "host/native/owner.lisp"))
(defun fnn-owner-observe (operation result)
  (declare (ignorable operation result))
  (harness-stub-reached 'fnn-owner-observe "host/native/owner.lisp"))
(defun fnn-owner-read-node-secret (store)
  (declare (ignorable store))
  (harness-stub-reached 'fnn-owner-read-node-secret "host/native/owner.lisp"))
(defun fnn-owner-recover-core (store records max-connections entry)
  (declare (ignorable store records max-connections entry))
  (harness-stub-reached 'fnn-owner-recover-core "host/native/owner.lisp"))
(defun fnn-store-recovery-barriers (store)
  (declare (ignorable store))
  (harness-stub-reached 'fnn-store-recovery-barriers "host/native/io.lisp"))
;;; ---- derived stubs: END ----
(defstruct (fnn-owner-service (:constructor %make-fnn-owner-service)) store)
(defvar *retained* nil)
(defvar *startup-store* nil)
(defvar *body-condition* (make-condition 'simple-error :format-control "initialization failed"))
(defvar *pre-return-failure* nil)
(defun fnn-open-live-store (&rest ignored)
  (declare (ignore ignored))
  (if *pre-return-failure* (fnn-store-failed-open-close *startup-store* *body-condition*)
    (values *startup-store* 0)))
(defun fnn-check-filesystem-identity (&rest ignored) (declare (ignore ignored)) (error *body-condition*))
(defun fnn-owner-retain-run-authority (service) (setq *retained* service))
(with-open-file (input "host/native/owner.lisp")
  (loop for form = (read input nil :eof) until (eq form :eof) do
    (when (and (consp form) (eq (car form) 'defun) (eq (second form) 'fnn-owner-install))
      (eval form))))
(dolist (failure '(nil :lock))
  (let ((*startup-store* (make-fnn-store :lock-fd :lock))
        (*failures* (list failure)) (*retained* nil) (caught nil))
    (handler-case (fnn-owner-install "/unused" 1) (error (e) (setq caught e)))
    (assert (eq caught *body-condition*))
    (if failure
        (progn (assert (fnn-owner-service-p *retained*))
               (assert (eq (fnn-owner-service-store *retained*) *startup-store*))
               (assert (fnn-store-close-debt *startup-store*)))
      (assert (null *retained*)))))
(format t "PASS actual owner install rollback: primary preserved; uncertain Store carrier retained.~%")

(let ((*startup-store* (make-fnn-store :lock-fd :lock))
      (*failures* '(:lock)) (*retained* nil) (*pre-return-failure* t) (caught nil))
  (handler-case (fnn-owner-install "/unused" 1) (error (e) (setq caught e)))
  (assert (eq caught *body-condition*))
  (assert (fnn-owner-service-p *retained*))
  (assert (eq (fnn-owner-service-store *retained*) *startup-store*))
  (assert (fnn-store-close-debt *startup-store*)))
(format t "PASS actual owner initial-open callback retains pre-return physical debt.~%")
