;;; Actual credential preflight consumers; kernel fd operations, ACL2 codec.
;;; Socket/owner effects are recorded. This is a raw schedule, not an image claim.
(load "tests/native_section_envelope_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-concat (&rest strings)
  (declare (ignorable strings))
  (harness-stub-reached 'fnn-concat "host/native/io.lisp"))
(defun fnn-emit (stream text)
  (declare (ignorable stream text))
  (harness-stub-reached 'fnn-emit "host/native/io.lisp"))
(defun fnn-feed-enable-tls (runtime link security)
  (declare (ignorable runtime link security))
  (harness-stub-reached 'fnn-feed-enable-tls "host/native/feed-service.lisp"))
(defun fnn-log-offer (destination octets)
  (declare (ignorable destination octets))
  (harness-stub-reached 'fnn-log-offer "host/native/io.lisp"))
(defun fnn-string-octets (string)
  (declare (ignorable string))
  (harness-stub-reached 'fnn-string-octets "host/native/io.lisp"))
;;; ---- derived stubs: END ----
(defun len (x) (length x))
(defun nfix (x) (if (and (integerp x) (>= x 0)) x 0))
(load-deployed-forms "books/peer-round-driver.lisp" '((defun fn-prd-deadline)))
(defun posp (x) (and (integerp x) (> x 0)))
(defun assoc-equal (key alist) (assoc key alist :test #'equal))
(defvar *fnn-feed-active* nil)
(defmacro mbe (&key logic exec) (declare (ignore exec)) logic)
(load-deployed-forms "books/records-shape.lisp"
 '((defun fn-record-string-octets-aux) (defun fn-record-string-octets)))
(load-deployed-forms "books/peer-host.lisp"
 '((defconst *fn-peer-dial-outcome-words*) (defun fn-phost-tokenp)
   (defun fn-phost-token) (defun fn-peer-dial-log-line)))
(load-deployed-forms "books/feed-auth-profile.lisp"
 '((defconst *fn-fap-max-octets*) (defconst *fn-fap-magic*)
   (defconst *fn-fap-max-token-octets*) (defun fn-fap-prefixp)
   (defun fn-fap-drop) (defun fn-fap-reverse-aux) (defun fn-fap-reverse)
   (defun fn-fap-line-aux) (defun fn-fap-line) (defun fn-fap-tokenp)
   (defun fn-fap-decode)))
(load-deployed-forms "books/nntp-syntax.lisp"
 '((defun fn-nntp-printable-tokenp)))
(load-deployed-forms "books/wire.lisp" '((defun fn-wire-octetp) (defun fn-wire-octet-listp)))
(define-condition fnn-tls-error (error) ())
(load-deployed-forms "host/native/io.lisp"
 '((define-condition fnn-os-error) (define-condition fnn-input-overbound)
   (define-condition fnn-entry-guard-fault) (define-condition fnn-peer-dial-error)
   (defconstant +fnn-o-nofollow+) (defmacro fnn-posix)
   (defun fnn-os-fail) (defun fnn-overbound) (defun fnn-open) (defun fnn-close)
   (defun fnn-fstat) (defun fnn-regular-p) (defun fnn-make-octets)
   (defun fnn-octet-list) (defun fnn-read-bounded-fd)
   (defun fnn-peer-dial-outcome) (defun fnn-peer-dial-report)))
;; One OS leaf: reads the same already admitted descriptor, never reopens path.
(defun fnn-read-fd (fd buffer &rest ignored)
  (declare (ignore ignored))
  (sb-sys:with-pinned-objects (buffer)
    (sb-posix:read fd (sb-sys:vector-sap buffer) (length buffer))))
(load-deployed-forms "host/native/feed-service.lisp"
 '((define-condition fnn-feed-auth-error)
   (defstruct (fnn-feed-runtime (:constructor %make-fnn-feed-runtime)))
   (defstruct (fnn-feed-link (:constructor %make-fnn-feed-link)))
   (defun fnn-feed-auth-profile) (defun fnn-feed-stoppingp)
   (defun fnn-feed-publish-socket) (defun fnn-feed-dial) (defun fnn-feed-connected-step)
   (defun fnn-feed-worker-guarded)))
(load-deployed-forms "host/native/pull-service.lisp"
 '((defstruct (fnn-pull-runtime (:constructor %make-fnn-pull-runtime)))
   (defun fnn-pull-profile) (defun fnn-pull-worker-guarded)))
(load-deployed-forms "host/native/owner.lisp" '((defun fnn-owner-thread-escape)))
(defvar *path* (second sb-ext:*posix-argv*))
(defvar *mode* (third sb-ext:*posix-argv*))
(defvar *calls* nil)
(defun credential-check (test message)
  (unless test
    (format t "~&CREDENTIAL_ASSERTION:~a~%" message) (finish-output)
    (error "credential assertion: ~a" message)))
(defun fnn-pull-peer-string (peer) (declare (ignore peer)) "p")
(defvar *core-fault* nil)
(defvar *read-fault* nil)
(defvar *close-fault* nil)
(defvar *worker-fault* nil)
(defun fnn-pull-worker (runtime)
  (declare (ignore runtime)) (error *worker-fault* :message "late"))
(defun fnn-feed-worker (runtime)
  (declare (ignore runtime)) (error *worker-fault* :message "late"))
(defvar *opened-profiles* nil)
(let ((open (symbol-function 'fnn-open)))
  (setf (symbol-function 'fnn-open)
        (lambda (&rest args)
          (let ((fd (apply open args)))
            (push fd *opened-profiles*) fd))))
(let ((close (symbol-function 'fnn-close)))
  (setf (symbol-function 'fnn-close)
        (lambda (fd)
          (funcall close fd)
          (when *close-fault* (error 'fnn-os-error :errno sb-posix:eio)))))
(define-condition credential-unknown-overbound (fnn-input-overbound) ())
(let ((read (symbol-function 'fnn-read-bounded-fd)))
  (setf (symbol-function 'fnn-read-bounded-fd)
        (lambda (&rest args)
          (if *read-fault* (error *read-fault* :message "injected read fault")
            (apply read args)))))
(defun fnn-core (subject &rest args)
  (when (eq subject *core-fault*) (error 'fnn-entry-guard-fault :message "injected core fault"))
  (case subject
    (fn-owner-feed-profile-max-octets *fn-fap-max-octets*)
    (fn-owner-feed-profile-decode (fn-fap-decode (first args)))
    (fn-prd-deadline (apply #'fn-prd-deadline args))
    (fn-peer-dial-log-line (apply #'fn-peer-dial-log-line args))
    (fn-pull-plan-profile-path *path*)
    (fn-pull-plan-peer '(112))
    (fn-pull-plan-host "127.0.0.1")
    (t (error "unexpected core subject ~s" subject))))
(defun fnn-log-line (line) (push (coerce (mapcar #'code-char line) 'string) *calls*))
(defun fnn-feed-dial-plan (&rest ignored)
  (declare (ignore ignored))
  (values t "127.0.0.1" 119 1 1 '(:clear) (list :authinfo *path* t)))
(defun fnn-peer-connect-start (&rest ignored)
  (declare (ignore ignored)) (push :connect *calls*) (values :socket :connected))
(defun fnn-socket-fd (socket) (declare (ignore socket)) 5)
(defun fnn-feed-connect-core (&rest args) (push (cons :core-open args) *calls*))
(defun fnn-socket-shut (&rest ignored) (declare (ignore ignored)) (push :shut *calls*))
(defun fnn-feed-drop-link (runtime link now backoff cause)
  (declare (ignore runtime link now backoff)) (push (list :drop cause) *calls*))
(defun fnn-pull-stoppingp (runtime) (fnn-pull-runtime-stopping runtime))
(defun fnn-owner-fault-service (service cid condition)
  (declare (ignore service cid)) (push (list :fault (type-of condition)) *calls*))
(defun fnn-owner-fence-service (service) (declare (ignore service)) (push :fenced *calls*))
(defun fnn-err (&rest args) (declare (ignore args)) nil)
(defun credential-outcome (thunk)
  (handler-case (progn (funcall thunk) :accepted)
    (fnn-feed-auth-error () :credential)
    (fnn-store-fault (e) (type-of e))))
(let ((runtime (%make-fnn-feed-runtime :service :owner :lock (sb-thread:make-mutex)))
      (link (%make-fnn-feed-link :peer "p" :peer-octets #(112))))
  (cond
    ((equal *mode* "fifo")
     (format t "~&CREDENTIAL_FIFO_BEGIN~%") (finish-output)
     (credential-check (eq (credential-outcome (lambda () (fnn-feed-auth-profile (list :authinfo *path* nil))))
                :credential) "FIFO descriptor promptly refused")
     (format t "~&CREDENTIAL_FIFO_REFUSED~%"))
    ((equal *mode* "invalid")
     (fnn-feed-dial runtime link 0)
     (credential-check (not (member :connect *calls*)) "credential admitted before any TCP connect")
     (credential-check (member '(:drop :credential) *calls* :test #'equal) "named credential drop")
     (credential-check (some (lambda (x) (and (stringp x) (search "outcome=credential" x))) *calls*)
            "ACL2 renders credential outcome")
     (credential-check (null (fnn-pull-profile :plan)) "pull credential refusal")
     (format t "~&CREDENTIAL_INVALID_REFUSED~%"))
    ((equal *mode* "good")
     (fnn-feed-dial runtime link 0)
     (credential-check (member :connect *calls*) "admitted profile permits dial")
     (credential-check (null (find :core-open *calls* :key (lambda (call) (and (consp call) (car call)))))
                       "core open waits for later TCP completion turn")
     (fnn-feed-connected-step runtime link)
     (credential-check (equal (last (cdr (assoc :core-open *calls*)) 3) '((110) (112) t))
                       "admitted credentials survive retained TCP completion")
     (credential-check (equal (fnn-pull-profile :plan) '((110) (112))) "ACL2 decoded credential passed to pull")
     (format t "~&CREDENTIAL_GOOD_ADMITTED~%"))
    ((equal *mode* "cleanup-fault")
     (setq *read-fault* 'fnn-store-fault *close-fault* t)
     (credential-check
      (eq (credential-outcome (lambda () (fnn-feed-auth-profile (list :authinfo *path* nil))))
          'fnn-store-fault)
      "cleanup OS error must preserve primary store fault")
     (format t "~&CREDENTIAL_CLEANUP_FAULT_PRESERVED~%"))
    ((equal *mode* "faults")
     (dolist (fault '(fnn-store-fault fnn-entry-guard-fault credential-unknown-overbound))
       (setq *read-fault* fault)
       (credential-check (eq (credential-outcome (lambda () (fnn-feed-auth-profile (list :authinfo *path* nil)))) fault)
              "read fault retains exact class")
       (credential-check (eq (credential-outcome (lambda () (fnn-pull-profile :plan))) fault)
              "pull does not swallow read fault"))
     (setq *read-fault* 'fnn-input-overbound)
     (credential-check (eq (credential-outcome (lambda () (fnn-feed-auth-profile (list :authinfo *path* nil))))
                :credential) "known bounded input refusal")
     (setq *read-fault* nil)
     (dolist (subject '(fn-owner-feed-profile-max-octets fn-owner-feed-profile-decode))
       (setq *core-fault* subject)
       (credential-check (eq (credential-outcome (lambda () (fnn-pull-profile :plan))) 'fnn-entry-guard-fault)
              "core guard fault propagates from pull"))
     (setq *core-fault* nil)
     (dolist (fault '(fnn-store-fault fnn-entry-guard-fault credential-unknown-overbound
                      fnn-store-indeterminate))
       (let ((pull (%make-fnn-pull-runtime :service :owner :stopping t))
             (feed (%make-fnn-feed-runtime :service :owner :stopping t)))
         (setq *calls* nil)
         (setq *worker-fault* fault)
         (fnn-pull-worker-guarded pull)
         (fnn-feed-worker-guarded feed)
         (credential-check
          (if (eq fault 'fnn-store-indeterminate)
              (= (count :fenced *calls*) 2)
            (= (count (list :fault fault) *calls* :test #'equal) 2))
          "late stopping feed/pull fault reaches shared owner boundary")))
     (format t "~&CREDENTIAL_FAULTS_PRESERVED~%"))
    (t (error "unknown schedule ~s" *mode*))))

(dolist (fd *opened-profiles*)
  (credential-check
   (handler-case (progn (sb-posix:fstat fd) nil)
     (sb-posix:syscall-error (e) (= (sb-posix:syscall-errno e) sb-posix:ebadf)))
   "profile descriptor closed after refusal, acceptance or fault"))
