;;; Actual BP service constructor/cleanup, injected physical/model seams.
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(define-condition fnn-os-error (error) ())
(defvar *mode* nil)
(defvar *closed* nil)
(defvar *unlocked* nil)
(defvar *spool-releases* 0)
(defvar *locks* 0)
(defvar *fnn-bps-lifecycle-enumerations* 0)
(defparameter +fnn-lock-un+ :unlock)
(defstruct fnn-bps release-debt spool-lock lock-fd tally state plan profile node-profile root lifecycle stages recovery-event)
(defstruct fnn-bp-tally config wall wall-error journal spool-lock)
(defun source-definition (path kind name)
  (with-open-file (stream path)
    (let* ((text (make-string (file-length stream))) (prefix (format nil "(~a ~a" kind name)))
      (read-sequence text stream)
      (let ((start (or (search (concatenate 'string prefix " ") text)
                        (search (concatenate 'string prefix (string #\Newline)) text))))
        (unless start (error "missing definition ~a" name))
        (read-from-string text nil nil :start start)))))
(defun fnn-err (&rest args) (declare (ignore args)))
(defun fnn-bp-profile-points () nil)
(defun fnn-bp-profile-open (&rest args) (declare (ignore args)))
(defun fnn-bp-journal-dir (journal) journal)
(defun fnn-tcl-spool-acquire (root) (declare (ignore root)) :spool)
(defun fnn-tcl-spool-release (spool)
  (assert (eq spool :spool)) (incf *spool-releases*)
  (when (eq *mode* :spool-close-fault) (error "spool-close-fault")))
(eval (source-definition (or (sb-ext:posix-getenv "FN_CLEANUP_HOST_SOURCE") "host/native/io.lisp") "defmacro" "fnn-unwind-cleanups"))
(defvar *fnn-bps-release-debts* nil)
(defun fnn-tcl-spool-close-observation () :closed)
(eval (source-definition (or (sb-ext:posix-getenv "FN_BP_RELEASE_HOST_SOURCE") "host/native/bp-service.lisp")
                         "defun" "fnn-bps-release-observation"))
(eval (source-definition (or (sb-ext:posix-getenv "FN_BP_RELEASE_HOST_SOURCE") "host/native/bp-service.lisp")
                         "defun" "fnn-bps-release"))
(defun fnn-bps-read-profile (root)
  (declare (ignore root))
  (when (eq *mode* :profile-fault) (error "profile-fault")) '(1 2))
(defun fnn-bps-selection-plan (&rest args) (declare (ignore args)) :plan)
(defun fnn-join (&rest args) (declare (ignore args)) "/life")
(defun fnn-parent (path) path)
(defun fnn-safe-directory (&rest args) (declare (ignore args)))
(defun fnn-fsync-dir (&rest args) (declare (ignore args)))
(defun fnn-bps-lock (root) (declare (ignore root)) (incf *locks*) 41)
(defun fnn-close (fd)
  (push fd *closed*)
  (when (eq *mode* :both-fault) (error "close-fault")))
(defun fnn-flock (fd op) (assert (eq op :unlock)) (push fd *unlocked*))
(defun fnn-indeterminate (&rest args) (error "uncertain ~a" args))
(defun fnn-bps-base (service) (fnn-bps-state service))
(defun fnn-bps-namespace-plan (service) (declare (ignore service)) (values nil :namespace))
(defun fnn-bps-clock-domain-gate (&rest args) (declare (ignore args)) :domain)
(defun fnn-bps-read-records (&rest args) (declare (ignore args)) nil)
(defun fnn-bps-read-received-rows (&rest args) (declare (ignore args)) nil)
(defun fnn-bps-sequence-ready (&rest args) (declare (ignore args)) 1)
(defun fnn-bps-foundation-step (&rest args) (declare (ignore args)) nil)
(defun fnn-bps-drive-effects (&rest args) (declare (ignore args)))
(defun fnn-bps-fragment-progress (&rest args) (declare (ignore args)))
(defun fnn-out (&rest args) (declare (ignore args)))
(defun fnn-core (name &rest args)
  (declare (ignore args))
  (case name
    (fn-bpnpf-node-profile-base
     (when (eq *mode* :projection-fault) (error "projection-fault")) '(1 2))
    (fn-bprpf-selection-admit '(:ready))
    (fn-bpnr-plan-directory "life")
    (fn-bpnf-initial-state
     (when (member *mode* '(:state-fault :both-fault :spool-close-fault)) (error "state-fault")) :state)
    ((fn-bpn-machine-invariantp fn-bpn-host-lifecycle-recovery-ready-p fn-bpn-host-lifecycle-recovery-agrees-p) t)
    (fn-bpn-host-lifecycle-recovery :recovery)
    (fn-bprpf-admit-recovery nil)
    (fn-bpnf-base-job-count 0)
    (otherwise nil)))
(eval (source-definition (or (sb-ext:posix-getenv "FN_CLEANUP_HOST_SOURCE") "host/native/io.lisp") "defmacro" "fnn-unwind-cleanups"))
(eval (source-definition (or (sb-ext:posix-getenv "FN_BP_SERVICE_HOST_SOURCE") "host/native/bp-service.lisp") "defun" "fnn-bps-open"))
(dolist (heldp '(nil t))
  (dolist (mode '(:success :profile-fault :projection-fault :state-fault :both-fault :spool-close-fault))
    (let* ((*mode* mode) (*closed* nil) (*unlocked* nil) (*spool-releases* 0) (*locks* 0) (*fnn-bps-release-debts* nil)
           (held (and heldp (make-fnn-bps :spool-lock :spool :lock-fd 41 :tally :tally)))
           (answer (handler-case (fnn-bps-open "/bp" :config nil 0 held)
                     (error (e) (princ-to-string e)))))
      (if (eq mode :success)
          (progn (assert (fnn-bps-p answer)) (assert (null *closed*)) (assert (= *spool-releases* 0)))
        (progn
          (assert (equal answer (case mode (:profile-fault "profile-fault")
                                  (:projection-fault "projection-fault") (otherwise "state-fault"))))
          (assert (= *spool-releases* (if heldp 0 1)))
          (when (and (not heldp) (member mode '(:both-fault :spool-close-fault)))
            (assert (= (length *fnn-bps-release-debts*) 1))
            (assert (if (eq mode :both-fault)
                        (= (first (fnn-bps-release-debt (first *fnn-bps-release-debts*))) 41)
                      (eq (second (fnn-bps-release-debt (first *fnn-bps-release-debts*))) :spool))))
          (assert (= (length *closed*) (if (or heldp (member mode '(:profile-fault :projection-fault))) 0 1))))))))
(format t "BP service constructor custody passed (12 paths)~%")
(let ((*mode* :success) (*closed* nil) (*unlocked* nil) (*spool-releases* 0)
      (*locks* 0) (*fnn-bps-release-debts* (list :prior-debt)))
  (assert (search "prior lock return" (handler-case (fnn-bps-open "/bp" :config nil 0)
                                      (error (e) (princ-to-string e)))))
  (assert (= *locks* 0))
  (assert (= *spool-releases* 0))
  (assert (fnn-bps-p (fnn-bps-open "/bp" :config nil 0
                      (make-fnn-bps :spool-lock :spool :lock-fd 41 :tally :tally)))))
(format t "BP acquisition debt guard passed (2 paths)~%")
;;; Command bodies use the same custody boundary after open.
(defparameter +fnn-tcl-keepalive+ 1)
(defparameter +fnn-tcl-segment-mru+ 1)
(defparameter +fnn-exit-refused+ 1)
(defun fnn-bp-config (&rest args) (declare (ignore args)) :config)
(defun fnn-bp-eid (text) text)
(defun fnn-bpo-request-publish (&rest args)
  (declare (ignore args)) (list '("work" "attempt" 1) '(1) "peer"))
(defun fnn-bps-open (&rest args)
  (declare (ignore args)) (make-fnn-bps :lock-fd 41 :spool-lock :spool))
(defun fnn-read-regular-bounded (&rest args) (declare (ignore args)) (error "body-fault"))
(defun fnn-bps-use-store-routes (&rest args) (declare (ignore args)) (error "body-fault"))
(dolist (name '(fnn-command-bp-service-run fnn-command-bp-service-resume))
  (eval (source-definition (or (sb-ext:posix-getenv "FN_BP_SERVICE_HOST_SOURCE") "host/native/bp-service.lisp")
                           "defun" (string-downcase name))))
(eval (source-definition (or (sb-ext:posix-getenv "FN_BP_OBLIGATION_HOST_SOURCE") "host/native/bp-obligation.lisp")
                         "defun" "fnn-command-bpo-owner-request"))
(dolist (args '((fnn-command-bp-service-run "host" 1 "adu" "journal" "node" "peer" "work" "attempt" 1 1 1 1 1 nil 0)
                (fnn-command-bp-service-resume "journal" "node" 1 1 1 1 nil 0)
                (fnn-command-bpo-owner-request "store" "journal" "work" "attempt" "fnbs" "node" "host" 1 1 1 1 1 nil 0)))
  (dolist (mode '(:state-fault :both-fault))
    (let ((*mode* mode) (*closed* nil) (*unlocked* nil) (*spool-releases* 0) (*fnn-bps-release-debts* nil))
      (let ((answer (handler-case (apply (first args) (rest args))
                      (error (e) (princ-to-string e)))))
        (assert (equal answer "body-fault"))
        (assert (= (length *closed*) 1))
        (assert (= *spool-releases* 1))))))
(format t "BP service command cleanup passed (6 paths)~%")
