(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(defconstant +fnn-exit-ok+ 0)
(defconstant +fnn-exit-refused+ 1)
(defconstant +fnn-o-nofollow+ 0)
(define-condition fnn-store-open-refusal (error) ())
(define-condition fnn-usage-error (error) ())
(defvar *body-failure* nil)
(defvar *close-failure* nil)
(defvar *primary* (make-condition 'simple-error :format-control "body fault"))
(defvar *secondary* (make-condition 'simple-error :format-control "close fault"))
(defvar *closes* nil)
(defvar *fnn-lz-tally* nil)
(defvar *fnn-stdout* (make-broadcast-stream))
(defstruct fnn-store lock-fd)
(defun make-fnn-store (&rest args) (declare (ignore args)) :store)
(defun fixture-body () (when *body-failure* (error *primary*)))
(defun fnn-err (&rest args) (declare (ignore args)))
(defun fnn-store-close (s) (push s *closes*) (when *close-failure* (error *secondary*)))
(defun fnn-close (fd) (push fd *closes*) (when *close-failure* (error *secondary*)))
(defun fnn-open-live-store (&rest args) (declare (ignore args)) (values :store 0))
(defun fnn-state-checkpoint-test-fault () nil)
(defun fnn-state-checkpoint-publish-steps (&rest args) (declare (ignore args)) (fixture-body) :report)
(defun fnn-out (&rest args) (declare (ignore args)) (fixture-body))
(defun fnn-write-report (&rest args) (declare (ignore args)) (fixture-body))
(defun fnn-open-report (&rest args) (declare (ignore args)) :report)
(defun fnn-core-state (name &rest args)
  (declare (ignore args))
  (unless (eq name 'fn-store-sco-want-checkpoint-digest) (fixture-body))
  (if (eq name 'fn-store-prov-for-msgid) nil 0))
(defun fnn-core (name &rest args)
  (declare (ignore args))
  (case name (fn-smid-rebind-plan '(:record :record)) (fn-otjs-exit 0)
    (otherwise nil)))
(defun fnn-safe-directory (&rest args) (declare (ignore args)))
(defun fnn-store-root (&rest args) (declare (ignore args)) "/root")
(defun fnn-staging (&rest args) (declare (ignore args)) "/stage")
(defun fnn-open-lock (&rest args) (declare (ignore args)) 4)
(defun (setf fnn-store-lock-fd) (value store) (declare (ignore store)) value)
(defun fnn-load-config (&rest args) (declare (ignore args)) (fixture-body))
(defun fnn-filesystem-record-observation (&rest args) (declare (ignore args)))
(defun fnn-filesystem-observation (&rest args) (declare (ignore args)))
(defun fnn-publish-filesystem-record (&rest args) (declare (ignore args)))
(defun fnn-filesystem-text (x) x)
(defun fnn-join (&rest args) (declare (ignore args)) "/dev/null")
(defun fnn-check-regular (&rest args) (declare (ignore args)) t)
(defun fnn-open (&rest args) (declare (ignore args)) 5)
(defun fnn-fstat (&rest args) (declare (ignore args)) (fixture-body) (sb-posix:stat "/dev/null"))
(defun fnn-regular-p (&rest args) (declare (ignore args)) t)
(defun fnn-nat (x) x)
(defun fnn-bridge-pin-count () (fixture-body) 0)
(defun fnn-bridge-reserved () 0)
(defun fnn-store-config-generation (&rest args) (declare (ignore args)) (fixture-body) 0)
(defun fnn-store-config-served (&rest args) (declare (ignore args)) nil)
(defun fnn-store-config-domain (&rest args) (declare (ignore args)) nil)
(defun fnn-ascii-octet-list (&rest args) (declare (ignore args)) (fixture-body) nil)
(defun fnn-octets (x) x)
(defun fnn-bridge-lookup-found-p (&rest args) (declare (ignore args)) nil)
(with-open-file (in "host/native/io.lisp")
 (loop for f = (read in nil :eof) until (eq f :eof) do
  (when (and (consp f)
             (or (and (eq (car f) 'defmacro) (eq (second f) 'fnn-unwind-cleanups))
                 (and (eq (car f) 'defun) (member (second f)
                    '(fnn-command-rebind-filesystem fnn-command-store-digest fnn-command-store-journal
                      fnn-command-state-checkpoint fnn-command-retention fnn-command-compression
                      fnn-command-config fnn-command-inspect fnn-command-provenance)))))
    (eval f))))
(dolist (entry '((fnn-command-rebind-filesystem "/root" nil) (fnn-command-store-digest "/root")
 (fnn-command-store-journal "/root") (fnn-command-state-checkpoint "/root")
 (fnn-command-retention "/root") (fnn-command-compression "/root") (fnn-command-config "/root")
 (fnn-command-inspect "/root" "id") (fnn-command-provenance "/root" "id")))
 (dolist (mode '(:body-and-close :close nil))
  (let ((*body-failure* (eq mode :body-and-close)) (*close-failure* mode) (*closes* nil) (caught nil))
   (handler-case (apply (first entry) (rest entry)) (error (e) (setq caught e)))
   (assert (= (length *closes*) 1))
   (assert (eq caught (case mode (:body-and-close *primary*) (:close *secondary*) (t nil)))))))
(format t "native nine command cleanup source PASS~%")
