;;; Actual registered mux starter/cleanup with real threads and pipe syscalls.
;;; Socket iteration and service fence are recording leaves; no ACL2 funding
;;; or complete physical mux semantics claim is made by this schedule.
(load "tests/native_actor_envelope_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-owner-syncer-physical (service grant receipt)
  (declare (ignorable service grant receipt))
  (harness-stub-reached 'fnn-owner-syncer-physical "host/native/owner.lisp"))
;;; ---- derived stubs: END ----
(defparameter +fnn-mux-loops+ 2) ; two physical startup slots in this fixture
(defparameter +fnn-mux-send-seconds+ 10)
(load-deployed-forms "host/native/owner.lisp"
 '((defun fnn-owner-actor-for-custody)))
(load-deployed-forms "host/native/mux.lisp"
 '((defstruct (fnn-mux-loop (:constructor %make-fnn-mux-loop)))
   (defstruct (fnn-mux-conn (:constructor %make-fnn-mux-conn)))
   (defstruct (fnn-mux-cleanup-receipt (:constructor %make-fnn-mux-cleanup-receipt)))
   (defun fnn-mux-service) (defun fnn-mux-cleanup-debt)
   (defun fnn-mux-close-wake) (def-actor fnn-mux-spawn)
   (defun fnn-mux-stop-loop) (defun fnn-mux-run) (defun fnn-mux-start)
   (defun fnn-mux-drained-p)))
(defvar *mux-hold* nil)
(defvar *mux-started* nil)
(defvar *mux-fds* nil)
(defvar *mux-setup-cut* nil)
(defvar *mux-setup-count* 0)
(defvar *mux-stop-cut* nil)
(defvar *mux-raw-cut* nil)
(defun fnn-set-nonblocking (fd)
  (push fd *mux-fds*)
  (incf *mux-setup-count*)
  (when (eql *mux-setup-count* *mux-setup-cut*) (error "mux setup cut"))
  fd)
(defun fnn-mux-iterate (loop)
  (declare (ignore loop))
  (when *mux-raw-cut* (throw 'raw-ev-fncall :mux-raw-cut))
  (sb-thread:signal-semaphore *mux-started*)
  (assert (sb-thread:wait-on-semaphore *mux-hold* :timeout 3)))
(defun fnn-owner-thread-escape (service condition context)
  (declare (ignore context))
  (fnn-owner-fault-service service nil condition)
  (when *mux-hold* (dotimes (n +fnn-mux-loops+) (sb-thread:signal-semaphore *mux-hold*))))
(defun fnn-mux-take-arrived (loop)
  (declare (ignore loop))
  (when *mux-stop-cut* (error "mux stop before wake close")))
(defun fnn-mux-ticks (seconds) seconds)
(defun fnn-seconds-to-deadline (deadline) deadline)
(defun fnn-owner-send (&rest args) (declare (ignore args)) (error "no output in mux lifecycle fixture"))
(defun fnn-mux-finish (&rest args) (declare (ignore args)) (error "no connections in mux lifecycle fixture"))
(defun fnn-mux-wake (loop) (declare (ignore loop)) nil)
(defun mux-fd-open-p (fd)
  (handler-case (progn (sb-posix:fstat fd) t) (sb-posix:syscall-error () nil)))
(defun mux-join-all (service)
  (dolist (loop (fnn-owner-service-mux service))
    (when (fnn-mux-loop-thread loop)
      (assert (fnn-owner-actor-join service (fnn-mux-loop-thread loop)))))
  (assert (null (fnn-owner-service-workers service)))
  (assert (null (fnn-owner-service-actors service))))
;; Child setup captures both real descriptors before registered actor wake.
(let* ((service (%make-fnn-owner-service))
       (*mux-fds* nil) (*mux-setup-count* 0))
  (setq *mux-hold* (sb-thread:make-semaphore :count 0)
        *mux-started* (sb-thread:make-semaphore :count 0))
  (fnn-mux-start service)
  (dotimes (n +fnn-mux-loops+) (wait-label *mux-started*))
  (assert (= +fnn-mux-loops+ (length (fnn-owner-service-actors service))))
  (dolist (loop (fnn-owner-service-mux service))
    (assert (fnn-owner-actor-for-custody service loop))
    (assert (mux-fd-open-p (fnn-mux-loop-wake-read loop)))
    (assert (mux-fd-open-p (fnn-mux-loop-wake-write loop))))
  (setf (fnn-owner-service-stopping service) t)
  (dotimes (n +fnn-mux-loops+) (sb-thread:signal-semaphore *mux-hold*))
  (mux-join-all service)
  (assert (every (lambda (fd) (not (mux-fd-open-p fd))) *mux-fds*))
  (assert (fnn-mux-drained-p service)))
;; Later setup failure closes every captured FD, including the unstarted loop;
;; previously started actors stay registered until actual physical join.
(let* ((service (%make-fnn-owner-service))
       (*mux-fds* nil) (*mux-setup-count* 0) (*mux-setup-cut* 3))
  (setq *mux-hold* (sb-thread:make-semaphore :count 0)
        *mux-started* (sb-thread:make-semaphore :count 0))
  (assert (handler-case (progn (fnn-mux-start service) nil) (error () t)))
  (mux-join-all service)
  (assert (every (lambda (loop) (and (null (fnn-mux-loop-wake-read loop))
                                    (null (fnn-mux-loop-wake-write loop))))
                 (fnn-owner-service-mux service)))
  (assert (fnn-mux-drained-p service)))
;; Definite maker failure closes this loop's pipe without inventing an actor.
(let* ((service (%make-fnn-owner-service)) (*mux-fds* nil) (*mux-setup-count* 0)
       (*fnn-actor-thread-maker* (lambda (&rest args) (declare (ignore args)) (error "maker failed"))))
  (assert (handler-case (progn (fnn-mux-start service) nil) (error () t)))
  (assert (null (fnn-owner-service-actors service)))
  (assert (every (lambda (fd) (not (mux-fd-open-p fd))) *mux-fds*))
  (assert (fnn-mux-drained-p service)))
;; A post-create failed latch plus no-op terminator retains the live parked
;; actor AND its pipe. Only independent actual termination permits cleanup.
(let* ((service (%make-fnn-owner-service)) (*mux-fds* nil) (*mux-setup-count* 0)
       (*fnn-actor-start-signal* (lambda (&rest args) (declare (ignore args)) (error "latch failed")))
       (*fnn-actor-thread-terminator* (lambda (&rest args) (declare (ignore args)) nil)))
  (assert (handler-case (progn (fnn-mux-start service) nil) (error () t)))
  (let* ((loop (first (fnn-owner-service-mux service)))
         (thread (fnn-mux-loop-thread loop)))
    (assert (and thread (sb-thread:thread-alive-p thread)))
    (assert (fnn-owner-actor-for-custody service loop))
    (assert (mux-fd-open-p (fnn-mux-loop-wake-read loop)))
    (assert (mux-fd-open-p (fnn-mux-loop-wake-write loop)))
    (assert (not (fnn-mux-drained-p service)))
    (sb-thread:terminate-thread thread)
    (fnn-owner-actor-join service thread)
    (fnn-mux-stop-loop loop)
    (assert (fnn-mux-drained-p service))))
;; Close failure is sticky, attempts the sibling independently, and blocks
;; terminal disposal even when an externally closed fd has no live OS object.
(let ((service (%make-fnn-owner-service)))
  (multiple-value-bind (read write) (sb-posix:pipe)
    (let ((loop (%make-fnn-mux-loop :service service :wake-read read :wake-write write :closed t)))
      (setf (fnn-owner-service-mux service) (list loop))
      (sb-posix:close read)
      (fnn-mux-close-wake loop)
      (assert (eql read (fnn-mux-loop-wake-read loop)))
      (assert (null (fnn-mux-loop-wake-write loop)))
      (assert (not (mux-fd-open-p write)))
      (assert (= 1 (length (fnn-mux-loop-cleanup-debts loop))))
      (assert (eq :calling (fnn-mux-cleanup-receipt-stage
                            (cdr (assoc :read (fnn-mux-loop-wake-receipts loop))))))
      (let ((before (copy-list (fnn-mux-loop-wake-receipts loop))))
        (fnn-mux-close-wake loop)
        (assert (equal before (fnn-mux-loop-wake-receipts loop))))
      (assert (not (fnn-mux-drained-p service))))))
;; An unknown ACL2 nonlocal escape reaches the registered actor classifier;
;; the loop still closes its captured descriptors before physical join.
(setq *mux-raw-cut* t)
(unwind-protect
    (let* ((service (%make-fnn-owner-service)) (*mux-fds* nil) (*mux-setup-count* 0))
      (fnn-mux-start service)
      (mux-join-all service)
      (assert (fnn-owner-service-stopping service))
      (assert (fnn-mux-drained-p service))
      (assert (every (lambda (fd) (not (mux-fd-open-p fd))) *mux-fds*)))
  (setq *mux-raw-cut* nil))
;; Earlier terminal body escape still closes both wake pipes independently.
(let ((service (%make-fnn-owner-service)) (*mux-stop-cut* t))
  (multiple-value-bind (read write) (sb-posix:pipe)
    (let ((loop (%make-fnn-mux-loop :service service :wake-read read :wake-write write)))
      (assert (handler-case (progn (fnn-mux-stop-loop loop) nil) (error () t)))
      (assert (not (mux-fd-open-p read)))
      (assert (not (mux-fd-open-p write))))))
(format t "native_mux_lifecycle_raw: PASS registered actors/setup rollback/live post-create retention/independent sticky FD close~%")
