;;; Actual startup roster/thread and terminal scratch consumer. Typed methods
;;; are recording boundaries; this is not a pool accounting proof.
(load "tests/native_decoded_worker_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-concat (&rest strings)
  (declare (ignorable strings))
  (harness-stub-reached 'fnn-concat "host/native/io.lisp"))
(defun fnn-emit (stream text)
  (declare (ignorable stream text))
  (harness-stub-reached 'fnn-emit "host/native/io.lisp"))
(defun fnn-extent-executor-actual-return (worker)
  (declare (ignorable worker))
  (harness-stub-reached 'fnn-extent-executor-actual-return "host/native/extent.lisp"))
(defun fnn-extent-executor-job (worker)
  (declare (ignorable worker))
  (harness-stub-reached 'fnn-extent-executor-job "host/native/extent.lisp"))
(defun fnn-extent-executor-returned-p (worker)
  (declare (ignorable worker))
  (harness-stub-reached 'fnn-extent-executor-returned-p "host/native/extent.lisp"))
(defun fnn-extent-page-observation (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-extent-page-observation "host/native/extent.lisp"))
(defun fnn-log-offer (destination octets)
  (declare (ignorable destination octets))
  (harness-stub-reached 'fnn-log-offer "host/native/io.lisp"))
(defun fnn-native-observation-unavailable (reason)
  (declare (ignorable reason))
  (harness-stub-reached 'fnn-native-observation-unavailable "host/native/owner.lisp"))
(defun fnn-owner-cold-cancel (read)
  (declare (ignorable read))
  (harness-stub-reached 'fnn-owner-cold-cancel "host/native/owner.lisp"))
(defun fnn-owner-cold-settle-locked (service read)
  (declare (ignorable service read))
  (harness-stub-reached 'fnn-owner-cold-settle-locked "host/native/owner.lisp"))
(defun fnn-string-octets (string)
  (declare (ignorable string))
  (harness-stub-reached 'fnn-string-octets "host/native/io.lisp"))
;;; ---- derived stubs: END ----
(load-deployed-forms "host/native/io.lisp"
 '((defvar *fnn-native-observer*) (defvar *fnn-native-actor-identity*) (defvar *fnn-native-wait-release*)
   (defmacro fnn-with-observed-mutex) (defun fnn-observed-condition-wait)))
(load-deployed-forms "host/native/extent.lisp"
 '((defvar *fnn-cold-workers*) (defvar *fnn-cold-free*) (defvar *fnn-cold-stopping*)
   (defun fnn-extent-executor-loop) (defun fnn-extent-executor-start) (defun fnn-extent-executor-stop)
   (defun fnn-extent-executor-discard-idle-locked) (defun fnn-extent-executor-discard-idle)
   (defun fnn-extent-executor-observe-returned)
   (defun fnn-extent-window-release) (defun fnn-extent-window-settle-cancelled)
   (defun fnn-extent-window-cancel)))
(defun fnn-native-observed-thread-thunk (body) body)
(defun fn-pwx-tokenp (token) (eq token :retained-token))
(defun fnn-err (&rest args) (declare (ignore args)) nil)
(defvar *startup-word* :ready)
(defvar *startup-events* nil)
(defvar *startup-cut* nil)
(defvar *startup-retained* nil)
(defvar *release-cut* nil)
(defun fnn-core (subject &rest args)
 (push subject *startup-events*)
 (case subject
  (fn-prstartup-planp (equal args '(:admitted-plan)))
  (fn-prstartup-decoded-workers 2)
  (fn-pxe-new (list :row (first args)))
  (create-fn-decoded-job
   (setq *startup-retained* (first *fnn-cold-workers*))
   (when (eq *startup-cut* :creator) (error "constructor cut"))
   (copy-seq *decoded-job*))
  (fn-dwj-reserve
   (assert (vectorp (first args)))
   (when (eq *startup-cut* :reserve) (error "reserve cut"))
   (first args))
  (otherwise (error "unexpected startup core ~s" subject))))
(defun fnn-cold-call (subject &rest args)
 (declare (ignore args))
 (push subject *startup-events*)
 (case subject
  (fn-owner-page-read-default-worker-constructionp (list (not (member *startup-cut* '(:reservation :already-ready)))))
  (fn-owner-page-read-default-worker-ready
   (assert (fnn-cold-worker-thread (first *fnn-cold-workers*)))
   (assert (not (eq *fnn-cold-free* (first *fnn-cold-workers*))))
   (list *startup-word* :same-pool))
  ((fn-owner-page-window-executor-release fn-owner-page-window-executor-settle-cancelled)
   (when *release-cut* (error "torn settlement"))
   (list :released :idle-row :same-pool))
  (otherwise (error "unexpected startup cold ~s" subject))))
;; The free stack is populated only after constructed/reserved scratch and
;; the actual private thread both exist. Failed readiness still joins it.
(let ((*decoded-job* (vector :scratch)) (*startup-events* nil))
 (unwind-protect
  (progn
   (fnn-extent-executor-start 2 :admitted-plan)
   (assert (= 2 (length *fnn-cold-workers*)))
   (assert *fnn-cold-free*)
   (assert (not (eq (fnn-decoded-activation-job (fnn-cold-worker-decoded-storage (first *fnn-cold-workers*)))
                    (fnn-decoded-activation-job (fnn-cold-worker-decoded-storage (second *fnn-cold-workers*))))))
   (dolist (worker *fnn-cold-workers*)
    (assert (eq :idle (fnn-cold-worker-phase worker)))
    (assert (sb-thread:thread-alive-p (fnn-cold-worker-thread worker)))
    (assert (eq :idle (fnn-decoded-activation-stage (fnn-cold-worker-decoded-storage worker)))))
   (assert (= 2 (count 'create-fn-decoded-job *startup-events*)))
   (assert (= 2 (count 'fn-dwj-reserve *startup-events*))))
  (fnn-extent-executor-stop)))
(dolist (cut '(:creator :reserve :ready))
 (let ((*decoded-job* (vector :scratch)) (*startup-cut* cut)
       (*startup-word* (if (eq cut :ready) :default-worker-not-reserved :ready))
       (*startup-retained* nil) (*startup-events* nil)
       (*fnn-cold-workers* nil) (*fnn-cold-free* nil))
  (assert (handler-case (progn (fnn-extent-executor-start 2 :admitted-plan) nil) (error () t)))
  (assert (null *fnn-cold-free*))
  (if (member cut '(:creator :reserve))
      (assert (eq *startup-retained* (first *fnn-cold-workers*)))
    (assert (null *fnn-cold-workers*)))
  (assert *startup-retained*)
  (when (fnn-cold-worker-thread *startup-retained*)
   (assert (not (sb-thread:thread-alive-p (fnn-cold-worker-thread *startup-retained*)))))))
;; Legacy direct startup creates no decoder and does not acknowledge readiness.
(let ((*startup-events* nil))
 (unwind-protect
  (progn (fnn-extent-executor-start 1)
   (assert (null (fnn-cold-worker-decoded-storage (first *fnn-cold-workers*))))
   (assert (not (member 'create-fn-decoded-job *startup-events*))))
  (fnn-extent-executor-stop)))
;; Use the actual release consumer after an affirmative return. The semantic
;; retirement runs before settlement. A torn settlement refuses repeat entry.
(defun fnn-core-cold-single (subject &rest args)
 (declare (ignore args))
 (case subject (fn-pwx-boundp t) (fn-owner-page-read-ledger :ledger)
  (otherwise (error "unexpected terminal single ~s" subject))))
(defvar *terminal-order* nil)
(defun fnn-call (subject &rest args)
 (push subject *terminal-order*)
 (case subject
  (fn-owner-page-decoded-job-retire
   (assert (eq (fourth args) :same-pool))
   (list :reusable (third args) :same-pool))
  (otherwise (error "unexpected terminal subject ~s" subject))))
(let* ((*decoded-job* (vector :scratch))
       (activation (make-fnn-decoded-activation :job *decoded-job* :stage :idle))
       (thread (sb-thread:make-thread (lambda () nil)))
       (worker (%make-fnn-cold-worker :row :row :token :token :phase :returned :thread thread
                                     :decoded activation :decoded-storage activation :result activation)))
 (sb-thread:join-thread thread)
 (let ((*release-cut* t))
  (assert (handler-case (progn (fnn-extent-window-release worker :token) nil) (error () t))))
 (assert (eq :releasing (fnn-cold-worker-phase worker)))
 (assert (eq activation (fnn-cold-worker-decoded-storage worker)))
 (let ((before (length *terminal-order*)))
  (assert (handler-case (progn (fnn-extent-window-release worker :token) nil) (error () t)))
  (assert (= before (length *terminal-order*)))))
(format t "native_decoded_startup_raw: PASS real startup/ready refusal/legacy/no retry after torn settlement~%")

;; A plan alone is insufficient: a refused installed slot allocates no backing.
(let ((*startup-cut* :reservation) (*startup-events* nil))
 (assert (handler-case (progn (fnn-extent-executor-start 2 :admitted-plan) nil) (error () t)))
 (assert (not (member 'create-fn-decoded-job *startup-events*)))
 (assert (null *fnn-cold-workers*)))

;; Both normal and cancelled last-borrow consumers preserve the persistent
;; backing while clearing per-operation references after literal retirement.
(dolist (release '(fnn-extent-window-release fnn-extent-window-settle-cancelled))
 (let* ((*decoded-job* (vector :scratch)) (*terminal-order* nil)
        (activation (make-fnn-decoded-activation :job *decoded-job* :stage :idle))
        (thread (sb-thread:make-thread (lambda () nil)))
        (worker (%make-fnn-cold-worker :row :row :token :token :phase :returned :thread thread
                                      :decoded activation :decoded-storage activation :result activation)))
  (sb-thread:join-thread thread)
  (assert (eq :released (funcall release worker :token)))
  (assert (eq :idle (fnn-cold-worker-phase worker)))
  (assert (eq activation (fnn-cold-worker-decoded-storage worker)))
  (assert (and (null (fnn-cold-worker-decoded worker)) (null (fnn-cold-worker-result worker))
               (null (fnn-cold-worker-token worker))))
  (assert (equal *terminal-order* '(fn-owner-page-decoded-job-retire)))))
(format t "native_decoded_startup_raw: PASS normal/cancelled last borrow preserves idle backing~%")

;; An already-constructed slot cannot spend the baseline a second time.
(let ((*startup-cut* :already-ready) (*startup-events* nil))
 (assert (handler-case (progn (fnn-extent-executor-start 2 :admitted-plan) nil) (error () t)))
 (assert (not (member 'create-fn-decoded-job *startup-events*))))

;; A physical join leaves every outstanding/torn slot discoverable. No
;; cancellation or second stop retries a prior torn terminal semantic call.
(let* ((activation (make-fnn-decoded-activation :job (vector :retained) :stage :idle))
       (thread (sb-thread:make-thread (lambda () nil)))
       (worker (%make-fnn-cold-worker :thread thread :phase :releasing :token :retained-token
                                     :decoded-storage activation))
       (*fnn-cold-workers* (list worker)) (*fnn-cold-free* worker))
 (sb-thread:join-thread thread)
 (assert (eq worker (first (fnn-extent-executor-stop))))
 (assert (null *fnn-cold-free*))
 (assert (eq worker (first (fnn-extent-executor-stop))))
 (assert (handler-case (progn (fnn-extent-window-cancel worker :retained-token) nil) (error () t)))
 ;; Only an actual terminal idle state can disappear from the roster.
 (setf (fnn-cold-worker-token worker) nil (fnn-cold-worker-phase worker) :idle)
 (assert (null (fnn-extent-executor-discard-idle))))
(format t "native_decoded_startup_raw: PASS stop retains unsettled/torn custody after physical join~%")
;; Even an empty owner read queue cannot hide independent roster custody.
;; The actual shutdown gate must prevent Store teardown with that debt.
(defvar +fnn-exit-ok+ 0)
(load-deployed-forms "host/native/owner.lisp"
 '((defstruct (fnn-owner-service (:constructor %make-fnn-owner-service)))
   (defun fnn-owner-cold-shutdown)))
(let* ((thread (sb-thread:make-thread (lambda () nil)))
       (worker (%make-fnn-cold-worker :thread thread :phase :releasing :token :retained-token))
       (*fnn-cold-workers* (list worker)) (*fnn-cold-free* nil)
       (service (%make-fnn-owner-service :cold-head nil)))
 (sb-thread:join-thread thread)
 (let ((condition nil))
  (handler-case (fnn-owner-cold-shutdown service) (error (c) (setq condition c)))
  (assert (and condition (search "terminal cleanup debt" (princ-to-string condition)))))
 (assert (eq worker (first *fnn-cold-workers*))))
(format t "native_decoded_startup_raw: PASS actual owner shutdown refuses independent roster debt~%")
