;;; Actual BP receipt acquisition plus shared cleanup macro; injected effects.
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(defun source-definition (path kind name)
  (with-open-file (stream path)
    (let* ((text (make-string (file-length stream)))
           (prefix (format nil "(~a ~a " kind name)))
      (read-sequence text stream)
      (let ((start (search prefix text)))
        (unless start (error "missing definition ~a in ~a" name path))
        (read-from-string text nil nil :start start)))))
(defvar *mode* :match)
(defvar *closes* 0)
(defvar *close-failure* nil)
(defvar *diagnostics* nil)
(defun fnn-err (&rest args) (push args *diagnostics*))
(defun fnn-quantum-bp (service ignored thunk)
  (declare (ignore service ignored)) (funcall thunk))
(defun fnn-bpapp-bind-owner-store () :ready)
(defun fnn-owner-service-store (service) service)
(defun fnn-app-open (&rest args)
  (declare (ignore args))
  (when (eq *mode* :open-fault) (error "open-fault"))
  :journal)
(defun fnn-owner-action (&rest args)
  (declare (ignore args))
  (case *mode*
    (:config-fault (error "config-fault"))
    ((:initialize-fault :initialize-escape :absent) :absent)
    (:conflict :conflict)
    (otherwise :match)))
(defun fnn-receipt-initialize (&rest args)
  (declare (ignore args))
  (case *mode*
    (:initialize-fault (error "initialize-fault"))
    (:initialize-escape (throw 'escape :escaped))
    (otherwise :durable)))
(defun fnn-refuse (&rest args) (declare (ignore args)) (error "conflict"))
(defun fnn-app-journal-close (journal)
  (assert (eq journal :journal))
  (incf *closes*)
  (when *close-failure* (error "close-fault")))
(eval (source-definition
       (or (sb-ext:posix-getenv "FN_CLEANUP_HOST_SOURCE") "host/native/io.lisp")
       "defmacro" "fnn-unwind-cleanups"))
(eval (source-definition
       (or (sb-ext:posix-getenv "FN_BPAPP_HOST_SOURCE") "host/native/bp-app.lisp")
       "defun" "fnn-bpapp-open-journal"))
(defun run-case (mode closes expected &optional close-failure)
  (let ((*mode* mode) (*closes* 0) (*close-failure* close-failure)
        (*diagnostics* nil))
    (let ((result
            (handler-case
                (catch 'escape
                  (fnn-bpapp-open-journal :service "/receipt" "dest" "policy" "issuer"))
              (error (e) (princ-to-string e)))))
      (assert (equal result expected) () "~s gave ~s expected ~s" mode result expected)
      (assert (= *closes* closes) () "~s closed ~d expected ~d" mode *closes* closes)
      (when close-failure (assert *diagnostics*)))))
(run-case :match 0 :journal)
(run-case :absent 0 :journal)
(run-case :open-fault 0 "open-fault")
(run-case :config-fault 1 "config-fault")
(run-case :initialize-fault 1 "initialize-fault")
(run-case :conflict 1 "conflict")
(run-case :initialize-escape 1 :escaped)
(run-case :initialize-fault 1 "initialize-fault" t)
(format t "BP application acquisition custody passed (8 paths)~%")
