;;; Actual logical wait and completion mailbox lifetime. Physical operation
;;; custody is separate and is never settled by cancelling reply publication.
(load "tests/native_actor_envelope_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-arena-return-observation (log)
  (declare (ignorable log))
  (harness-stub-reached 'fnn-arena-return-observation "host/native/io.lisp"))
(defun fnn-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-core "host/native/io.lisp"))
(defun fnn-extent-direct-start ()
  (harness-stub-reached 'fnn-extent-direct-start "host/native/extent.lisp"))
(defun fnn-extent-end-recovery-cache ()
  (harness-stub-reached 'fnn-extent-end-recovery-cache "host/native/extent.lisp"))
(defun fnn-extent-executor-drained-p ()
  (harness-stub-reached 'fnn-extent-executor-drained-p "host/native/extent.lisp"))
(defun fnn-extent-executor-stop ()
  (harness-stub-reached 'fnn-extent-executor-stop "host/native/extent.lisp"))
(defun fnn-extent-window-cancel (worker token)
  (declare (ignorable worker token))
  (harness-stub-reached 'fnn-extent-window-cancel "host/native/extent.lisp"))
(defun fnn-gc-nursery-octets ()
  (harness-stub-reached 'fnn-gc-nursery-octets "host/native/io.lisp"))
(defun fnn-listen (port &key family backlog address)
  (declare (ignorable port family backlog address))
  (harness-stub-reached 'fnn-listen "host/native/io.lisp"))
(defun fnn-log-line (line)
  (declare (ignorable line))
  (harness-stub-reached 'fnn-log-line "host/native/io.lisp"))
(defun fnn-log-sync-collected (log)
  (declare (ignorable log))
  (harness-stub-reached 'fnn-log-sync-collected "host/native/io.lisp"))
(defun fnn-log-writer-start ()
  (harness-stub-reached 'fnn-log-writer-start "host/native/io.lisp"))
(defun fnn-mux-budget-install (service tls-context)
  (declare (ignorable service tls-context))
  (harness-stub-reached 'fnn-mux-budget-install "host/native/mux.lisp"))
(defun fnn-mux-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-mux-drained-p "host/native/mux.lisp"))
(defun fnn-mux-handshake-release (loop conn)
  (declare (ignorable loop conn))
  (harness-stub-reached 'fnn-mux-handshake-release "host/native/mux.lisp"))
(defun fnn-mux-read-class (loop conn)
  (declare (ignorable loop conn))
  (harness-stub-reached 'fnn-mux-read-class "host/native/mux.lisp"))
(defun fnn-mux-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-mux-start "host/native/mux.lisp"))
(defun fnn-out (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-out "host/native/io.lisp"))
(defun fnn-owner-abandon-append-prefix (service grant)
  (declare (ignorable service grant))
  (harness-stub-reached 'fnn-owner-abandon-append-prefix "host/native/owner.lisp"))
(defun fnn-owner-accept (service listener once)
  (declare (ignorable service listener once))
  (harness-stub-reached 'fnn-owner-accept "host/native/owner.lisp"))
(defun fnn-owner-answer-early (ledger members)
  (declare (ignorable ledger members))
  (harness-stub-reached 'fnn-owner-answer-early "host/native/owner.lisp"))
(defun fnn-owner-claim-run-authority (&optional caller-reservation)
  (declare (ignorable caller-reservation))
  (harness-stub-reached 'fnn-owner-claim-run-authority "host/native/owner.lisp"))
(defun fnn-owner-cold-abandon (read)
  (declare (ignorable read))
  (harness-stub-reached 'fnn-owner-cold-abandon "host/native/owner.lisp"))
(defun fnn-owner-cold-shutdown (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-cold-shutdown "host/native/owner.lisp"))
(defun fnn-owner-cold-window-result-locked (service read)
  (declare (ignorable service read))
  (harness-stub-reached 'fnn-owner-cold-window-result-locked "host/native/owner.lisp"))
(defun fnn-owner-commit-complete-locked (service action members deferred)
  (declare (ignorable service action members deferred))
  (harness-stub-reached 'fnn-owner-commit-complete-locked "host/native/owner.lisp"))
(defun fnn-owner-commit-event (service event)
  (declare (ignorable service event))
  (harness-stub-reached 'fnn-owner-commit-event "host/native/owner.lisp"))
(defun fnn-owner-commit-start-locked (service &key seal held)
  (declare (ignorable service seal held))
  (harness-stub-reached 'fnn-owner-commit-start-locked "host/native/owner.lisp"))
(defun fnn-owner-commit-wake (service returned queued &optional append-idle append-returned held-caller)
  (declare (ignorable service returned queued append-idle append-returned held-caller))
  (harness-stub-reached 'fnn-owner-commit-wake "host/native/owner.lisp"))
(defun fnn-owner-complete-generation (ledger gen final members)
  (declare (ignorable ledger gen final members))
  (harness-stub-reached 'fnn-owner-complete-generation "host/native/owner.lisp"))
(defun fnn-owner-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-owner-core "host/native/owner.lisp"))
(defun fnn-owner-disk-event (service kind &optional arg)
  (declare (ignorable service kind arg))
  (harness-stub-reached 'fnn-owner-disk-event "host/native/owner.lisp"))
(defun fnn-owner-disk-stalled-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-disk-stalled-p "host/native/owner.lisp"))
(defun fnn-owner-disk-wait-ms (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-disk-wait-ms "host/native/owner.lisp"))
(defun fnn-owner-drain-service (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-drain-service "host/native/owner.lisp"))
(defun fnn-owner-feed-close-all (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-feed-close-all "host/native/owner.lisp"))
(defun fnn-owner-frames-job (service job)
  (declare (ignorable service job))
  (harness-stub-reached 'fnn-owner-frames-job "host/native/owner.lisp"))
(defun fnn-owner-install (root max-connections &optional fault)
  (declare (ignorable root max-connections fault))
  (harness-stub-reached 'fnn-owner-install "host/native/owner.lisp"))
(defun fnn-owner-install-or-end (install original label)
  (declare (ignorable install original label))
  (harness-stub-reached 'fnn-owner-install-or-end "host/native/owner.lisp"))
(defun fnn-owner-journal-close ()
  (harness-stub-reached 'fnn-owner-journal-close "host/native/owner.lisp"))
(defun fnn-owner-journal-note (service a b)
  (declare (ignorable service a b))
  (harness-stub-reached 'fnn-owner-journal-note "host/native/owner.lisp"))
(defun fnn-owner-journal-open (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-journal-open "host/native/owner.lisp"))
(defun fnn-owner-log-settlement ()
  (harness-stub-reached 'fnn-owner-log-settlement "host/native/owner.lisp"))
(defun fnn-owner-measure-report ()
  (harness-stub-reached 'fnn-owner-measure-report "host/native/owner.lisp"))
(defun fnn-owner-output-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-output-drained-p "host/native/owner.lisp"))
(defun fnn-owner-output-maybe-physical-locked (service grant)
  (declare (ignorable service grant))
  (harness-stub-reached 'fnn-owner-output-maybe-physical-locked "host/native/owner.lisp"))
(defun fnn-owner-output-receipt-locked (service grant kind receipt)
  (declare (ignorable service grant kind receipt))
  (harness-stub-reached 'fnn-owner-output-receipt-locked "host/native/owner.lisp"))
(defun fnn-owner-page-read-startup (root max-connections cold-resources output-resources retain)
  (declare (ignorable root max-connections cold-resources output-resources retain))
  (harness-stub-reached 'fnn-owner-page-read-startup "host/native/owner.lisp"))
(defun fnn-owner-peer-flight-startup (service capture)
  (declare (ignorable service capture))
  (harness-stub-reached 'fnn-owner-peer-flight-startup "host/native/owner.lisp"))
(defun fnn-owner-pipeline-close (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-pipeline-close "host/native/owner.lisp"))
(defun fnn-owner-reader-capture (event)
  (declare (ignorable event))
  (harness-stub-reached 'fnn-owner-reader-capture "host/native/owner.lisp"))
(defun fnn-owner-refresh-read-octets (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-refresh-read-octets "host/native/owner.lisp"))
(defun fnn-owner-release-recovery-garbage ()
  (harness-stub-reached 'fnn-owner-release-recovery-garbage "host/native/owner.lisp"))
(defun fnn-owner-retain-run-authority (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-retain-run-authority "host/native/owner.lisp"))
(defun fnn-owner-retire-final-report (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-retire-final-report "host/native/owner.lisp"))
(defun fnn-owner-run-startup-hooks (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-run-startup-hooks "host/native/owner.lisp"))
(defun fnn-owner-service-nursery ()
  (harness-stub-reached 'fnn-owner-service-nursery "host/native/owner.lisp"))
(defun fnn-owner-shed-queued-locked (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-shed-queued-locked "host/native/owner.lisp"))
(defun fnn-owner-snapshot-jobs-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-snapshot-jobs-drained-p "host/native/owner.lisp"))
(defun fnn-owner-space-event (service need)
  (declare (ignorable service need))
  (harness-stub-reached 'fnn-owner-space-event "host/native/owner.lisp"))
(defun fnn-owner-space-prime (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-space-prime "host/native/owner.lisp"))
(defun fnn-owner-stall-release (service members)
  (declare (ignorable service members))
  (harness-stub-reached 'fnn-owner-stall-release "host/native/owner.lisp"))
(defun fnn-owner-start-append-prefix (service gen job grant)
  (declare (ignorable service gen job grant))
  (harness-stub-reached 'fnn-owner-start-append-prefix "host/native/owner.lisp"))
(defun fnn-owner-start-committer (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-start-committer "host/native/owner.lisp"))
(defun fnn-owner-start-tls-accept (service listener &optional implicit-tls)
  (declare (ignorable service listener implicit-tls))
  (harness-stub-reached 'fnn-owner-start-tls-accept "host/native/owner.lisp"))
(defun fnn-owner-stop-service (service exit-code)
  (declare (ignorable service exit-code))
  (harness-stub-reached 'fnn-owner-stop-service "host/native/owner.lisp"))
(defun fnn-owner-store-settlement (service settlement)
  (declare (ignorable service settlement))
  (harness-stub-reached 'fnn-owner-store-settlement "host/native/owner.lisp"))
(defun fnn-owner-syncer-abandon (service grant ledger members)
  (declare (ignorable service grant ledger members))
  (harness-stub-reached 'fnn-owner-syncer-abandon "host/native/owner.lisp"))
(defun fnn-owner-syncer-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-syncer-drained-p "host/native/owner.lisp"))
(defun fnn-owner-syncer-outcome (service grant generation)
  (declare (ignorable service grant generation))
  (harness-stub-reached 'fnn-owner-syncer-outcome "host/native/owner.lisp"))
(defun fnn-owner-syncer-physical (service grant receipt)
  (declare (ignorable service grant receipt))
  (harness-stub-reached 'fnn-owner-syncer-physical "host/native/owner.lisp"))
(defun fnn-owner-wait-workers (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-wait-workers "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-joined (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-joined "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-start "host/native/owner.lisp"))
(defun fnn-peer-flight-bank-drained (bank)
  (declare (ignorable bank))
  (harness-stub-reached 'fnn-peer-flight-bank-drained "host/native/catchup-spool.lisp"))
(defun fnn-tls-close-channel (channel)
  (declare (ignorable channel))
  (harness-stub-reached 'fnn-tls-close-channel "host/native/tls.lisp"))
(defun fnn-zout-free (zout)
  (declare (ignorable zout))
  (harness-stub-reached 'fnn-zout-free "host/native/deflate.lisp"))
;;; ---- derived stubs: END ----
(load-deployed-forms "host/native/io.lisp" '((defvar *fnn-monotonic-ticks*) (defun fnn-now)))
(load-deployed-forms "host/native/owner.lisp"
 '((defun fnn-owner-deliver) (defun fnn-owner-await-register)
   (defun fnn-owner-awaiting-sockets) (defun fnn-owner-past-p)
   (defun fnn-owner-await-logical)))
;; Let the unchanged harness execute its behavioral assertions on the baseline.
(when (with-open-file (stream "host/native/owner.lisp")
        (loop for form = (read stream nil :eof) until (eq form :eof)
              thereis (and (consp form) (eq (car form) 'defun)
                           (eq (cadr form) 'fnn-owner-await-abandon))))
  (load-deployed-forms "host/native/owner.lisp" '((defun fnn-owner-await-abandon))))
(let ((which (sb-ext:posix-getenv "FN_AWAIT_TEST_CASE")))
  ;; Real SBCL wait times out once before producer delivery. A timeout returns
  ;; without the mutex: the next observation must acquire it anew.
  (when (or (null which) (string= which "wait"))
    (let* ((s (%make-fnn-owner-service)) (condition nil) (answer nil)
           (completion #(50 52 48))
           (producer (sb-thread:make-thread
                      (lambda () (sleep 1.1) (fnn-owner-deliver s 41 completion)))))
      (unwind-protect
           (handler-case
               (setq answer (fnn-owner-await-logical s 41
                             (+ (fnn-now) (* 3 internal-time-units-per-second))))
             (error (e) (setq condition e)))
        (sb-thread:join-thread producer))
      (check (and (null condition) (eq answer completion))
             (format nil "logical wait survives timed wake and receives completion; condition=~a" condition))
      (check (and (zerop (hash-table-count (fnn-owner-service-awaiting s)))
                  (zerop (hash-table-count (fnn-owner-service-done s))))
             "completed logical wait leaves no mailbox entry")))
  (when (or (null which) (string= which "cancel"))
    (let ((s (%make-fnn-owner-service)))
      (setf (fnn-owner-service-syncer-grants s) '(:physical-operation-still-owed))
      (check (eq (fnn-owner-await-logical s 52 (1- (fnn-now))) :uncertain)
             "expired logical caller receives uncertainty")
      (check (null (fnn-owner-awaiting-sockets s 52)) "abandoned wait names no socket")
      (fnn-owner-deliver s 52 #(50 52 48))
      (check (and (zerop (hash-table-count (fnn-owner-service-awaiting s)))
                  (zerop (hash-table-count (fnn-owner-service-done s))))
             "late completion of abandoned logical caller is not retained forever in DONE")
      (check (equal (fnn-owner-service-syncer-grants s) '(:physical-operation-still-owed))
             "reply abandonment never settles physical operation custody"))))
(format t "native_await_lifetime_raw: PASS actual timed wait and late completion lifetime~%")

;; Cancellation racing a callback already selected by DELIVER creates no
;; replacement mailbox entry. The detached callback retains only its own cell.
(let* ((s (%make-fnn-owner-service)) (entered (sb-thread:make-semaphore :count 0))
       (release (sb-thread:make-semaphore :count 0)) (received nil))
  (fnn-owner-await-register s 63
   (lambda (value) (sb-thread:signal-semaphore entered) (wait-label release)
     (setq received value)) :socket)
  (let ((producer (sb-thread:make-thread (lambda () (fnn-owner-deliver s 63 :completed)))))
    (wait-label entered)
    (fnn-owner-await-abandon s 63)
    (sb-thread:signal-semaphore release)
    (sb-thread:join-thread producer)
    (check (and (eq received :completed)
                (zerop (hash-table-count (fnn-owner-service-awaiting s)))
                (zerop (hash-table-count (fnn-owner-service-done s))))
           "in-flight callback cancellation creates no orphan marker or done entry")))

;; Nonlocal escape from an actual wait also closes the reply route, while
;; retaining the pending-delivery marker until the real result arrives.
(let ((s (%make-fnn-owner-service))
      (*fnn-monotonic-ticks* (lambda () (throw 'await-clock-escape :clock-escaped))))
  (check (eq (catch 'await-clock-escape (fnn-owner-await-logical s 74 1)) :clock-escaped)
         "logical wait preserves original nonlocal escape")
  (fnn-owner-deliver s 74 :completed)
  (check (and (zerop (hash-table-count (fnn-owner-service-awaiting s)))
              (zerop (hash-table-count (fnn-owner-service-done s))))
         "nonlocal wait exit cannot leak late completion"))

;; The actual mux terminal consumer closes its pending reply route too.
(load-deployed-forms "host/native/mux.lisp"
 '((defstruct (fnn-mux-cleanup-receipt (:constructor %make-fnn-mux-cleanup-receipt)))
   (defun fnn-mux-service) (defun fnn-mux-cleanup-debt)
   (defun fnn-mux-cleanup-attempt) (defun fnn-mux-capture-output-grant)
   (defun fnn-mux-finish)))
(load-deployed-forms "host/native/owner.lisp"
 '((defun fnn-owner-output-close) (defun fnn-owner-response-window-close)))
(defun fnn-owner-response-unpin (&rest args) (declare (ignore args)) nil)
;; Recording cleanup boundaries; real cleanup envelope/failure witnesses are
;; in native_mux_cleanup_raw. This fixture owns the reply-abandon consumer.
(defun fnn-quantum-mux-finish (service cid thunk &optional class)
  (declare (ignore service cid class)) (funcall thunk))
(defun fnn-owner-thread-escape (&rest args) (declare (ignore args)) nil)
(defun fnn-owner-action (name &rest args)
  (declare (ignore args))
  (case name (fn-owner-close :closed) (fn-owner-exposure-release :released)
             (otherwise (error "unexpected await cleanup subject ~s" name))))
(defun fnn-socket-shut (socket) (declare (ignore socket)) (values nil :closed nil))
(defun fnn-mux-start-waiting-handshake (&rest args) (declare (ignore args)) nil)
(let* ((s (%make-fnn-owner-service :clients '(:closing-socket)))
       (loop (%make-fnn-mux-loop :service s))
       (conn (%make-fnn-mux-conn :cid 85 :opened-cid 85 :phase :await
                                :await '(step redeem nil) :socket :closing-socket))
       (published nil))
  (fnn-owner-await-register s 85 (lambda (value) (setq published value)) :closing-socket)
  (fnn-mux-finish loop conn)
  (fnn-owner-deliver s 85 :completed)
  (check (and (eq (fnn-mux-conn-phase conn) :done) (null (fnn-mux-conn-await conn))
              (not published) (null (fnn-owner-service-clients s))
              (zerop (hash-table-count (fnn-owner-service-awaiting s)))
              (zerop (hash-table-count (fnn-owner-service-done s))))
         "finished mux connection drops eventual completion without retained callback"))
(format t "native_await_lifetime_raw: PASS cancellation/callback/nonlocal/mux schedules~%")
