(load "tests/native_web_page_cursor_raw.lisp")
(in-package "ACL2")
(defun member-equal (x xs) (member x xs :test #'equal))
(load-page-forms "books/web-request.lisp"
 '(fn-wrq-chars-octets fn-web-row *fn-web-routes* fn-web-row-name))
(load-page-forms "books/web-session.lisp"
 '(fn-wss-car fn-web-private-begin-row-p fn-web-private-begin-p fn-web-private-begin-step))
(load-page-forms "host/web-host.lisp" '(fn-web-host-private-begin-step))
; This fixture records the outer private gate, not the new body producer.
(defun fn-wpf-private-begin (config action in out)
  (fn-web-private-begin-step config action in out))
(defvar *private-begin-held* nil)
(defvar *private-begin-release* nil)
(defun fn-wss-gate (row session sessions ctx config in out)
  (declare (ignore config in))
  ;; A recording gate seam, not a claim about the form/parser/body producer.
  (assert (fn-web-private-begin-row-p row)) (assert (null sessions))
  (assert (eq session :captured-session)) (assert (eq ctx :captured-context))
  (setf *private-begin-held* t)
  (loop until *private-begin-release* do (sleep .001))
  (fnn-web-fill out (fnn-octets '(65 66 67)))
  (values '(:respond 200 nil t) nil out))
(let* ((row (find :post *fn-web-routes* :key #'fn-web-row-name))
       (action (list :private-begin row :captured-session :captured-context))
       (conn (fixture-conn 51 :event 44)) (healthy (fixture-conn 52 :event))
       (face (%make-fnn-web-face :service *fixture-service* :wake-closed t :conns (list conn healthy)))
       (saved-call (symbol-function 'fnn-call)) (saved-owner (symbol-function 'fnn-owner-serialized))
       (main-thread sb-thread:*current-thread*) (worker nil))
  (assert (fn-web-private-begin-p action))
  (assert (not (fn-web-private-begin-row-p (find :signin *fn-web-routes* :key #'fn-web-row-name))))
  (assert (not (fn-web-private-begin-row-p '(:post))))
  (assert (not (fn-web-private-begin-p '(:send 44 0 6 nil))))
  (setf (fnn-web-conn-leased conn) t)
  (unwind-protect
      (progn
        (setf (symbol-function 'fnn-call)
              (lambda (name &rest args)
                (if (eq name 'fn-web-host-private-begin-step)
                    (multiple-value-list (apply #'fn-web-host-private-begin-step args))
                  (apply saved-call name args))))
        (setf (symbol-function 'fnn-owner-serialized)
              (lambda (service cid thunk &optional class)
                (declare (ignore service cid class))
                (assert (eq sb-thread:*current-thread* main-thread))
                (funcall thunk)))
        (fnn-web-apply-action face conn action)
        (assert (eq (fnn-web-conn-phase conn) :private-begin))
        (fnn-web-advance face conn)
        (assert (eq (fnn-web-job-kind (fnn-web-conn-job conn)) :private-begin))
        (setf (fnn-web-face-jobs-closed face) t)
        (setf worker (sb-thread:make-thread (lambda () (fnn-web-semantic-body face))))
        (loop repeat 10000 until *private-begin-held* do (sleep .001))
        (assert *private-begin-held*)
        ;; Actual network actor's owner event remains available while the
        ;; private form/body worker is held outside O.
        (fnn-web-event face healthy)
        (assert (eq (fnn-web-conn-phase healthy) :write))
        (assert (not (fnn-web-job-returned (fnn-web-conn-job conn))))
        (setf *private-begin-release* t)
        (sb-thread:join-thread worker)
        (assert (fnn-web-job-returned (fnn-web-conn-job conn)))
        (assert (eq (fnn-web-conn-phase conn) :write))
        (assert (null (fnn-web-conn-private-begin conn)))
        (assert (fnn-web-conn-leased conn)))
    (setf *private-begin-release* t)
    (when (and worker (sb-thread:thread-alive-p worker)) (sb-thread:join-thread worker))
    (setf (symbol-function 'fnn-call) saved-call (symbol-function 'fnn-owner-serialized) saved-owner)))
(format t "NATIVE WEB PRIVATE BEGIN RAW PASS: exact classifier/captured wrapper; fixed worker outside O; healthy owner event during held gate~%")
