;;; Actual owner loan/close functions over recording physical and typed leaves.
;;; This checks native ordering; it is not typed/controller equivalence evidence.
(load "tests/native_output_response_lease_raw.lisp")
(in-package "ACL2")
(load-deployed-forms "host/native/extent.lisp"
 '((defvar *fnn-extent-lock*) (defvar *fnn-extent-window-mode*)
   (defvar *fnn-extent-window-worker*) (defvar *fnn-extent-window-token*)))
(load-deployed-forms "host/native/owner.lisp"
 '((defun fnn-owner-window-activation) (defun fnn-owner-cold-remove-locked)
   (defun fnn-owner-cold-window-result-locked) (defun fnn-owner-response-window-close)))
(defvar *window-returned* nil)
(defvar *window-word* :ready)
(defvar *window-effects* nil)
(defvar *window-release-word* :released)
(defun fnn-extent-pool-funded-p () t)
(defun fnn-extent-executor-returned-p (worker) (declare (ignore worker)) *window-returned*)
(defun fnn-extent-window-outcome (worker token) (declare (ignore worker token)) *window-word*)
(defun fnn-extent-window-cancel (worker token)
  (push (list :cancel worker token) *window-effects*)
  (setq *window-word* :cancelled) :cancelled)
(defun fnn-extent-window-settle-cancelled (worker token)
  (push (list :release worker token) *window-effects*) *window-release-word*)
(defun fnn-extent-window-release (worker token)
  (push (list :release worker token) *window-effects*) *window-release-word*)
(defun fnn-owner-output-observe-returned (service read) (declare (ignore service read)))
(defun fnn-owner-output-dependency-consumed (service read)
  (declare (ignore service read)) (push :consumed *window-effects*))
(defun fnn-owner-release-pending-extents-locked (service) (declare (ignore service)))
(defun window-case (returned)
  (let* ((service (%make-fnn-owner-service :lock (sb-thread:make-mutex)))
         (read (%make-fnn-owner-cold-read :windowp t :worker :worker :token :token :queuedp t))
         (capture (%make-fnn-response-capture :window-read read))
         (*window-returned* returned) (*window-word* :ready) (*window-effects* nil))
    (setf (fnn-owner-service-cold-head service) read (fnn-owner-service-cold-tail service) read)
    (when returned
      (check (fnn-owner-cold-window-result-locked service read) "ready scalar loan")
      (check (and (fnn-owner-cold-read-borrowedp read) (not (fnn-owner-cold-read-settledp read))
                  (null *window-effects*)) "physical return alone retains scalar charge")
      (let ((*fnn-response-capture* capture))
        (fnn-owner-window-activation
         (lambda () (check (and *fnn-extent-window-mode*
                                (eq *fnn-extent-window-worker* :worker)
                                (eq *fnn-extent-window-token* :token)) "exact captured scalar borrow")))))
    (check (eq (fnn-owner-response-window-close service capture) :window-closed) "whole-response close")
    (unless returned
      (check (and (not (fnn-owner-cold-read-settledp read))
                  (eq (fnn-owner-service-cold-head service) read)
                  (= 1 (length *window-effects*))) "close before physical return preserves charge and roster")
      (setq *window-returned* t)
      (check (fnn-owner-cold-window-result-locked service read) "late actual return settles cancelled loan"))
    (check (and (fnn-owner-cold-read-settledp read) (null (fnn-owner-service-cold-head service))
                (= 1 (count :consumed *window-effects*))
                (= 1 (count :release *window-effects* :key (lambda (x) (if (consp x) (car x) x)))))
           "one release only after terminal last borrow")
    (let ((before (copy-list *window-effects*)))
      (fnn-owner-response-window-close service capture)
      (fnn-owner-cold-window-result-locked service read)
      (check (equal before *window-effects*) "duplicate close/reap never releases twice"))))
(window-case t)
(window-case nil)
(let* ((service (%make-fnn-owner-service :lock (sb-thread:make-mutex)))
       (read (%make-fnn-owner-cold-read :windowp t :worker :worker :token :token :abandonedp t))
       (*window-returned* t) (*window-word* :cancelled) (*window-release-word* :stale-job))
  (check (handler-case (progn (fnn-owner-cold-window-result-locked service read) nil) (serious-condition () t))
         "refused release faults")
  (check (and (not (fnn-owner-cold-read-settledp read)) (eq (fnn-owner-cold-read-worker read) :worker))
         "missing release receipt retains exact custody"))
(format t "native_response_window_raw: PASS ready borrow/close-held/late return/duplicate/refused release~%")
