; Execute the actual shared producer bodies over the arena list model.
; This fixture does not substitute for the owner/cold consumer refinement.
(unless (find-package "ACL2") (make-package "ACL2" :use '("COMMON-LISP")))
(in-package "ACL2")
(declaim (declaration xargs))
(defmacro mv (&rest xs) `(values ,@xs))
(defmacro mv-let (names call &body body) `(multiple-value-bind ,names ,call ,@body))
(defmacro mbe (&key logic exec) (declare (ignore logic)) exec)
(defun nfix (n) (if (and (integerp n) (<= 0 n)) n 0))
(defun natp (n) (and (integerp n) (<= 0 n)))
(defun zp (n) (or (not (integerp n)) (<= n 0)))
(defun len (xs) (length xs))
(defun fn-cbor-ag-car (x) (if (consp x) (car x) nil))
(defun fn-cbor-ag-cdr (x) (if (consp x) (cdr x) nil))
(defun fn-octetp (x) (and (integerp x) (<= 0 x 255)))
(defun fn-arena-count (arena) (length arena))
(defun fn-arena-payload-len (h arena) (length (nth h arena)))
(defun fn-arena-get (h at arena) (nth at (nth h arena)))
(defun fn-article-payload (article) (second article))
(defun fn-article-msgid (article) (first article))
(defun fn-nntp-article-bytes (article arena)
  (let ((p (fn-article-payload article))) (if (natp p) (nth p arena) p)))
(defun digit-to-char (n) (digit-char n))
(defun source-load-defuns (path &optional names)
  (with-open-file (in path)
    (loop for form = (read in nil :end) until (eq form :end)
          when (and (consp form) (eq (car form) 'defun)
                    (or (not names) (member (second form) names)))
          do (eval form))))
(source-load-defuns "books/nov-decimal-window.lisp" '(fn-nbw-decimal-tick))
(source-load-defuns "books/nov-piece-window.lisp" '(fn-npw-one))
(source-load-defuns "books/nntp-article-pass.lisp"
                    '(fn-nntp-crlf-validp fn-nntp-blank-linep fn-nntp-block-rev))
(source-load-defuns "books/article-stream.lisp")
(defvar *checks* 0)
(defun source-check (condition)
  (incf *checks*) (unless condition (error "article source check ~d failed" *checks*)))
(defun bytes (text) (map 'list #'char-code text))
(defun source-scan (source quantum arena)
  (let ((scan (fn-ast-preflight source)))
    (loop until (fn-ast-scan-donep scan) do
      (multiple-value-bind (next used) (fn-ast-scan-step scan quantum arena)
        (source-check (<= 0 used quantum))
        (source-check (<= (- (third (first scan)) (third (first next))) quantum))
        (setf scan next))) scan))
(defun source-render (cur quantum arena)
  (let ((acc nil) (initial (copy-tree cur)))
    (loop until (eq (car cur) :done) do
      (multiple-value-bind (out next used) (fn-ast-render-step cur quantum arena)
        (source-check (<= 0 used quantum))
        (source-check (<= (length out) (* 2 quantum)))
        (setf acc (revappend out acc) cur next)))
    (source-check (not (eq (car initial) :done)))
    (reverse acc)))
(defun source-render-window (cur window arena)
  (let ((acc nil) (initial (copy-tree cur)) (original cur))
    (loop until (fn-ast-window-donep cur) do
      (multiple-value-bind (out next) (fn-ast-render-window cur window window arena)
        (source-check (<= (length out) window))
        (setf acc (revappend out acc) cur next)))
    (source-check (equal initial original))
    (reverse acc)))
(defun source-reference (payload kind number mid &optional server pairs)
  (let* ((split (loop for at below (- (length payload) 3)
                     when (equal (subseq payload at (+ 4 at)) '(13 10 13 10)) return (+ at 4)))
         (section (case kind (:head (subseq payload 0 (- split 2)))
                            (:body (subseq payload split)) (t payload)))
         (xref (and server (not (eq kind :body))
                    (append (bytes "Xref: ") server
                      (loop for (group . num) in pairs append (bytes (format nil " ~a:~d" group num)))
                      '(13 10))))
         (initial (bytes (format nil "~d ~d ~a ~a" (case kind (:head 221) (:body 222) (t 220))
                                  number mid (case kind (:head "headers follow") (:body "body follows")
                                                      (t "article follows")))))
         (block (fn-nntp-block-rev (append xref section) t nil)))
    (append initial '(13 10) (revappend block '(46 13 10)))))
(let* ((payload (append (bytes "Subject: example") '(13 10 13 10)
                        (bytes ".first") '(13 10) (bytes "last") '(13 10)))
       (article (list "<stream@example>" 0)) (arena (list payload))
       (pairs '(("fn.a" . 123456789012345678901234567890) ("fn.b" . 2)))
       (server (bytes "node.example")))
  (dolist (quantum '(1 2 3 4 7 16 256))
    (let ((scan (source-scan (fn-ast-source article arena) quantum arena)))
      (source-check (fn-ast-scan-validp scan))
      (dolist (kind '(:article :head :body))
        (let* ((ready (fn-ast-ready scan kind 123456789012345678901234567890 article server pairs))
               (before (copy-tree ready))
               (one (source-render ready quantum arena))
               (two (source-render ready (1+ quantum) arena)))
          (source-check (equal ready before))
          (source-check (equal one two))
          (source-check (equal one (source-reference payload kind 123456789012345678901234567890
                                                     "<stream@example>" server pairs))))))))
(dolist (payload '(nil (13) (10) (0) (65 13 10) (13 10 13 10) (13 10 13 10 65)
                   (13 10 13 10 46 13 10) (13 10 13 10 13 13 10) (13 10 13 10 0 13 10)))
  (dolist (quantum '(1 2 3 7))
    (let ((scan (source-scan (list nil 0 (length payload) payload) quantum nil)))
      (source-check (equal (and (fn-ast-scan-validp scan) t)
                          (and (fn-nntp-crlf-validp payload t) (fn-nntp-blank-linep payload) t))))))
(let* ((payload (append (bytes "Subject: dense") '(13 10 13 10)
                        (loop repeat 5000 append '(46 13 10))))
       (article (list "<dense@example>" 0)) (arena (list payload))
       (scan (source-scan (fn-ast-source article arena) 4096 arena))
       (ready (fn-ast-ready scan :body 7 article nil nil))
       (saved (copy-tree ready))
       (reference (source-reference payload :body 7 "<dense@example>")))
  (dolist (window '(1 2 3 4096))
    (source-check (equal (source-render-window ready window arena) reference))
    (source-check (equal ready saved))))
(format t "article stream actual-source PASS checks=~d~%" *checks*)
