; Actual service retainer + actual bank installer, allocation/install seams.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "COMMON-LISP"))
(defpackage "ACL2_*1*_ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(defun selected (path names)
  (with-open-file (in path)
    (loop for form = (read in nil :eof) until (eq form :eof)
          when (and (consp form) (member (car form) '(defun defstruct))
                    (member (if (consp (second form)) (car (second form)) (second form)) names))
          do (eval form) (setf names (remove (if (consp (second form)) (car (second form)) (second form)) names))
          finally (assert (null names)))))
(defstruct fnn-owner-service peer-flight-bank close-hooks)
(defvar *cut* nil)
(defvar *created* 0)
(defun fnn-fault (&rest args) (declare (ignore args)) (error "bank fault"))
(defun fnn-core (name &rest args)
 (case name
  (fn-pfr-startup-grant (list :hold (third args)))
  (create-fn-resource-ledger
    (incf *created*)
    (case *cut* (:create-error (error "creator error")) (:create-throw (throw 'creator-cut :escaped)))
    :ledger)
  (fn-csp-bank-idle-p t)
  (otherwise (error "unknown core ~s" name))))
(defun fnn-call (name &rest args)
 (assert (eq name 'fn-pfr-install-funded))
 (assert (eq (car (last args)) :ledger))
 (list (if (eq *cut* :install-error) :refused :installed) :returned-ledger))
(selected "host/native/catchup-spool.lisp"
 '(fnn-peer-flight-bank fnn-peer-flight-bank-install fnn-peer-flight-bank-drained fnn-peer-flight-bank-close))
(selected "host/native/owner.lisp" '(fnn-owner-peer-flight-startup))
(let ((*created* 0) (service (make-fnn-owner-service)))
 (fnn-owner-peer-flight-startup service nil)
 (assert (= *created* 0)) (assert (null (fnn-owner-service-peer-flight-bank service))))
(dolist (cut '(nil :create-error :create-throw :install-error))
 (let ((*cut* cut) (*created* 0) (service (make-fnn-owner-service)))
  (catch 'creator-cut
   (handler-case (fnn-owner-peer-flight-startup service '(1000 100 :policy 8192 1024))
    (error () (assert cut))))
  (assert (= *created* 1))
  (let ((bank (fnn-owner-service-peer-flight-bank service)))
   (assert bank) (assert (= (length (fnn-owner-service-close-hooks service)) 1))
   (assert (eql (and (fnn-peer-flight-bank-drained bank) t) (null cut)))
   (when (member cut '(nil :install-error))
    (assert (eq (fnn-peer-flight-bank-ledger bank) :returned-ledger)))
   (handler-case (funcall (first (fnn-owner-service-close-hooks service)) service)
    (error () (assert cut)))
   (when (null cut) (assert (eq (fnn-peer-flight-bank-phase bank) :closed))))))
(format t "SOURCE PEER BANK STARTUP PASSED~%")
