;;; Actual worker, ACL2 scheduling/action book, and kernel nonblocking sockets.
;;; Protocol/session and journal leaves are recorded here; this is not a
;;; saved-image codec/durability claim. The selected image scenario supplies it.
(load "tests/native_section_envelope_raw.lisp")
(in-package "ACL2")
(defun nfix (x) (if (and (integerp x) (>= x 0)) x 0))
(defun natp (x) (and (integerp x) (>= x 0)))
(defun posp (x) (and (integerp x) (> x 0)))
(defun zp (x) (not (posp x)))
(defun mbe (&key logic exec) (declare (ignore exec)) logic)
(defparameter *fn-feed-wire-input-max-chunk-octets* 512)
(defconstant +fnn-max-read+ 65536)
(load-deployed-forms "host/native/io.lisp"
 '((defun fnn-make-octets) (deftype fnn-octets) (defun fnn-octets)
   (defun fnn-octet-list) (defun fnn-octets-string) (defun fnn-string-octets)
   (defmacro fnn-posix) (defvar *fnn-read-syscall*) (defvar *fnn-write-syscall*) (defvar *fnn-fd-waiter*)
   (defvar *fnn-connect-attempt*) (defvar *fnn-socket-pending-error*)
   (defun fnn-socket-class) (defvar *fnn-monotonic-ticks*) (defun fnn-now) (defun fnn-seconds-to-deadline)
   (defun fnn-eintr-p) (defun fnn-would-block-p) (defun fnn-set-nonblocking)
   (defun fnn-socket-fd) (defun fnn-socket-shut) (defun fnn-retry-eintr) (defun fnn-read-fd) (defun fnn-recv)))
;; Load the actual adapter, including its custody definitions. On the old
;; defect base the optional new logic book is absent; the old worker still
;; runs over these identical real kernel leaves and recorded protocol leaves.
(load "host/native/pull-service.lisp")
(dolist (path '("books/peer-round-driver.lisp"))
  (when (probe-file path)
    (with-open-file (stream path)
      (loop for form = (read stream nil :eof) until (eq form :eof)
            when (and (consp form) (member (car form) '(defun defstruct)))
              do (load-deployed-forms path (list (list (car form) (cadr form))))))))
(with-open-file (stream "host/native/io.lisp")
  (loop for form = (read stream nil :eof) until (eq form :eof)
        when (and (consp form) (eq (car form) 'defun)
                  (member (cadr form) '(fnn-connect-start fnn-connect-poll fnn-socket-read-now fnn-socket-write-now)))
          do (load-deployed-forms "host/native/io.lisp" (list (list 'defun (cadr form))))))
(defparameter *fn-feed-wire-input-max-chunk-octets* 512)
(load-deployed-forms "books/rev-onto.lisp" '((defun fn-ag-rev-onto)))
(load-deployed-forms "books/scheduler-peers.lisp"
 '((defun fn-sched-pull-entry) (defun fn-sched-pull-next) (defun fn-sched-pull-interval)
   (defun fn-sched-pull-busy) (defun fn-sched-pull-find) (defun fn-sched-pull-put-loop)
   (defun fn-sched-pull-put) (defun fn-sched-pull-configure) (defun fn-sched-pull-duep)
   (defun fn-sched-pull-due-aux) (defun fn-sched-pull-due)
   (defun fn-sched-pull-start) (defun fn-sched-pull-finish)))
(load-deployed-forms "books/peer-pull.lisp"
 '((defun fn-pull-at) (defun fn-pull-plan-peer) (defun fn-pull-plan-host)
   (defun fn-pull-plan-port) (defun fn-pull-plan-interval) (defun fn-pull-plan-for)
   (defun fn-pull-schedule-live-loop) (defun fn-pull-schedule-configure) (defun fn-pull-schedule)))
(defvar *started* (get-internal-real-time))
(defvar *sockets* nil)
(defvar *server-sockets* nil)
(defvar *completed* nil)
(defvar *partial* nil)
(defvar *slow-observed* nil)
(defvar *mode* (second sb-ext:*posix-argv*))
(defvar *plans* '(((65) "slow" 1 nil 5000) ((66) "healthy" 2 nil 5000)))
(defvar *cu-plans* '(((67) "catchup" 3 nil 5000)))
(defun driver-check (test message)
  (unless test (format t "~&ROUND_DRIVER_ASSERTION:~a~%" message) (finish-output)
    (error "driver assertion: ~a" message)))
(defun fnn-pull-monotonic ()
  (floor (* 1000 (get-internal-real-time)) internal-time-units-per-second))
(defun fnn-pull-stoppingp (runtime)
  (declare (ignore runtime))
  (> (- (get-internal-real-time) *started*) (/ internal-time-units-per-second 2)))
(defun fnn-owner-transit-serialized (service cid thunk)
  (declare (ignore service cid)) (funcall thunk))
(defun fnn-owner-core (subject)
  (case subject (fn-owner-pull-plans *plans*) (fn-owner-catchup-plans *cu-plans*)
    (otherwise (error "unexpected owner subject ~s" subject))))
(defun fnn-owner-wall-milliseconds () 1000)
(defun fnn-pull-profile (plan) (declare (ignore plan)) nil)
(defun fnn-pull-cursor-for (runtime plan)
  (let ((key (fnn-pull-peer-string (fn-pull-plan-peer plan))))
    (unless (assoc key (fnn-pull-runtime-cursors runtime) :test #'string=)
      (push (cons key :old) (fnn-pull-runtime-cursors runtime)))
    (values key :old)))
(defun fnn-catchup-cursor-for (runtime plan)
  (let ((key (fnn-pull-peer-string (fn-pull-plan-peer plan))))
    (unless (assoc key (fnn-pull-runtime-cu-cursors runtime) :test #'string=)
      (push (cons key :old) (fnn-pull-runtime-cu-cursors runtime)))
    (values key :old)))
(defun fnn-pull-journal-append (journal cursor &optional kind)
  (declare (ignore kind))
  (when (eq cursor :complete) (pushnew journal *completed* :test #'equal)))
(defun fnn-owner-feed-close (journal) (declare (ignore journal)))
(defun fnn-owner-response-unpin (service cid) (declare (ignore service cid)))
(defun fnn-tls-close-channel (channel) (declare (ignore channel)))
(defun fnn-tls-close-context (context) (declare (ignore context)))
(defun fnn-log-line (line) (declare (ignore line)))
(defun fnn-peer-dial-report (&rest args) (declare (ignore args)))
(defun fnn-peer-connect (host port &key timeout)
  (declare (ignore host timeout)) (cdr (assoc port *sockets*)))
(defun fnn-peer-connect-start (host port)
  (values (fnn-peer-connect host port) :connected))
(defun session-begin (plan)
  (list (list (fn-pull-plan-peer plan) 0 nil) '((:dial))))
(defun session-step (session event)
  (destructuring-bind (peer count done) session
    (declare (ignore done))
    (let* ((slow (equal peer '(65)))
           (new-count (+ count (if (eq (car event) :remote) (length (cdr event)) 0)))
           (done (or (eq (car event) :lost) (and (not slow) (plusp new-count)))))
      (when slow (setq *partial* new-count)
        (when (plusp new-count) (setq *slow-observed* t)))
      (list (list peer new-count done) nil nil))))
(defun fnn-core (subject &rest args)
  (case subject
    ((fn-pull-session-begin-pair fn-cu-session-begin-pair) (session-begin (first args)))
    ((fn-pull-session-step-triple fn-cu-session-step-pair)
     (let ((triple (apply #'session-step args)))
       (if (eq subject 'fn-cu-session-step-pair) (subseq triple 0 2) triple)))
    ((fn-pull-session-done-p fn-cu-session-done-p) (third (first args)))
    ((fn-pull-session-read-limit fn-cu-session-read-limit) 512)
    ((fn-pull-session-close-effects fn-cu-session-close-effects)
     (when (and (third (first args)) (not (equal (first (first args)) '(65))))
       (list (cons :journal :complete))))
    ((fn-pull-session-close fn-cu-session-close) :closed)
    ((fn-pull-session-log-line-why fn-cu-session-log-line) nil)
    (fn-owner-feed-connect-timeout 10)
    (fn-splan-step-plan (list :recorded-plan))
    (otherwise
     (unless (fboundp subject) (error "unexpected core subject ~s" subject))
     (apply (symbol-function subject) args))))
(defun connected-pair ()
  (let ((listener (make-instance 'sb-bsd-sockets:inet-socket :type :stream :protocol :tcp))
        (client nil) (server nil))
    (unwind-protect
         (progn
           (sb-bsd-sockets:socket-bind listener #(127 0 0 1) 0)
           (sb-bsd-sockets:socket-listen listener 1)
           (multiple-value-bind (address port) (sb-bsd-sockets:socket-name listener)
             (setq client (make-instance 'sb-bsd-sockets:inet-socket :type :stream :protocol :tcp))
             (sb-bsd-sockets:socket-connect client address port))
           (setq server (sb-bsd-sockets:socket-accept listener))
           (values client server))
      (sb-bsd-sockets:socket-close listener))))
(load-deployed-forms "host/native/owner.lisp" '((defun fnn-owner-join-octets)))
(defun local-fixture ()
  (let* ((runtime (%make-fnn-pull-runtime :service :recorded :lock (sb-thread:make-mutex)))
         (flight (%make-fnn-pull-flight :runtime runtime :cid 9 :input (fnn-octets '(1 2 3))
                                       :io :local))
         (steps 0) (polls 0) (renders 0) (callback nil) (unpins 0) (abandoned nil))
    (setf (symbol-function 'fnn-owner-peer-read-class) (lambda (service) (declare (ignore service)) :transit)
          (symbol-function 'fnn-owner-handle-chunk-step)
          (lambda (&rest args)
            (declare (ignore args))
            (case (incf steps) (1 (values :cold :page))
              (2 (values :await :step :redeem nil nil 2))
              (3 (values nil nil nil 1 nil))
              (t (error "unexpected local input replay"))))
          (symbol-function 'fnn-owner-cold-poll)
          (lambda (&rest args) (declare (ignore args))
            (if (= (incf polls) 1) (values '(:wait 10) 1 2 nil)
              (values :serve 1 3 nil)))
          (symbol-function 'fnn-owner-await-register)
          (lambda (service cid deliver socket) (declare (ignore service cid socket))
            (setq callback deliver) nil)
          (symbol-function 'fnn-owner-render-next-quantum)
          (lambda (&rest args) (declare (ignore args))
            (if (= (incf renders) 1) (values (fnn-octets '(82)) :rest nil nil)
              (values (fnn-octets '(83)) nil t nil)))
          (symbol-function 'fnn-owner-response-unpin)
          (lambda (&rest args) (declare (ignore args)) (incf unpins))
          (symbol-function 'fnn-owner-await-abandon)
          (lambda (&rest args) (declare (ignore args)) (setq abandoned t))
          (symbol-function 'fnn-owner-action) (lambda (&rest args) (declare (ignore args)) nil))
    (fnn-pull-flight-local-step flight) ; cold issue, input untouched
    (fnn-pull-flight-local-step flight) ; readiness wait, input untouched
    (driver-check (equal (fnn-octet-list (fnn-pull-flight-input flight)) '(1 2 3))
                  "cold readiness must retain exact input")
    (fnn-pull-flight-local-step flight) ; cold ready
    (fnn-pull-flight-local-step flight) ; submit, consumes prefix
    (driver-check (and (fnn-pull-flight-await flight)
                       (equal (fnn-octet-list (fnn-pull-flight-input flight)) '(3)))
                  "submitted prefix must not consume or replay the suffix")
    (driver-check (eq (fnn-pull-flight-local-step flight) :wait) "commit wait must yield")
    (funcall callback '(78))
    (fnn-pull-flight-local-step flight) ; completion -> actual ACL2 plan leaf
    (fnn-pull-flight-local-step flight) ; first render quantum
    (driver-check (and (= renders 1) (fnn-pull-flight-render flight)) "render must retain continuation")
    (fnn-pull-flight-local-step flight) ; last render
    (fnn-pull-flight-local-step flight) ; consume suffix once
    (fnn-pull-flight-local-step flight) ; publish ordered local reply
    (driver-check (and (= steps 3) (= renders 2) (= unpins 2)
                       (equal (fnn-pull-flight-events flight) '((:local 82 83)))
                       (null (fnn-pull-flight-io flight)))
                  "local continuation must preserve ordered bytes and release response pin")
    ;; Reopened flight rejects a callback captured for the retired await.
    (setf (fnn-pull-flight-await flight) (list :next :redeem))
    (fnn-pull-flight-close-local flight)
    (funcall callback '(99))
    (driver-check (and abandoned (null (fnn-pull-flight-completion flight)))
                  "abandoned callback must not publish into a later local connection")
    (format t "~&PEER_ROUND_DRIVER_PASS local~%")))
(defun io-fixture ()
  (let ((listener (make-instance 'sb-bsd-sockets:inet-socket :type :stream :protocol :tcp))
        (client nil) (server nil) (refused nil))
    (unwind-protect
         (progn
           (sb-bsd-sockets:socket-bind listener #(127 0 0 1) 0)
           (sb-bsd-sockets:socket-listen listener 1)
           (multiple-value-bind (address port) (sb-bsd-sockets:socket-name listener)
             (multiple-value-bind (socket word) (fnn-connect-start address port)
               (setq client socket)
               (unless (eq word :connected)
                 (loop repeat 100 until (eq (fnn-connect-poll client) :connected) do (sleep .001))))
             (setq server (sb-bsd-sockets:socket-accept listener))
             (let* ((fd (fnn-socket-fd client)) (sfd (fnn-socket-fd server))
                    (data (fnn-octets (loop for i below 2000 collect (mod i 256))))
                    (offset 0) (got nil))
               (driver-check (eq (fnn-socket-read-now fd 512) :wait) "idle read must yield without EOF")
               (loop while (< offset (length data)) do
                 (let* ((end (fn-prd-write-end offset (length data)))
                        (written (fnn-socket-write-now fd data offset end)))
                   (driver-check (integerp written) "loopback write made no progress")
                   (incf offset written)
                   (loop while (< (length got) offset) do
                     (unless (sb-sys:wait-until-fd-usable sfd :input 1)
                       (error "kernel loopback readiness was unavailable"))
                     (let ((part (fnn-socket-read-now sfd 512)))
                       (when (vectorp part)
                         (driver-check (plusp (length part)) "loopback closed before all bytes arrived")
                         (setq got (append got (fnn-octet-list part))))))))
               (driver-check (equal got (fnn-octet-list data)) "bounded writes must preserve all octets")
               (let ((*fnn-read-syscall* (lambda (&rest args) (declare (ignore args))
                                          (values nil sb-posix:eintr))))
                 (driver-check (eq (fnn-socket-read-now fd 512) :wait) "interrupted read must yield once")))
             (fnn-socket-shut listener)
             (multiple-value-bind (socket word) (fnn-connect-start address port)
               (declare (ignore word)) (setq refused socket)
               (driver-check (loop repeat 100 thereis
                              (handler-case (progn (fnn-connect-poll refused) (sleep .001) nil)
                                (fnn-os-error () t)))
                             "refused connect must retain a named OS failure")))
           (format t "~&PEER_ROUND_DRIVER_PASS io~%"))
      (dolist (socket (list client server refused listener)) (when socket (fnn-socket-shut socket))))))
(defun cleanup-fixture ()
  (let* ((runtime (%make-fnn-pull-runtime :service :recorded :lock (sb-thread:make-mutex)))
         (flight (%make-fnn-pull-flight :runtime runtime :cid 9 :cold (list :page nil 1)
                                       :await (list :step :redeem)))
         (awaited nil) (unpinned nil) (closed nil))
    (setf (symbol-function 'fnn-owner-cold-abandon)
          (lambda (read) (declare (ignore read)) (fnn-indeterminate "late cold escape"))
          (symbol-function 'fnn-owner-await-abandon)
          (lambda (&rest args) (declare (ignore args)) (setq awaited t))
          (symbol-function 'fnn-owner-response-unpin)
          (lambda (&rest args) (declare (ignore args)) (setq unpinned t) (fnn-fault "unpin escape"))
          (symbol-function 'fnn-owner-action)
          (lambda (&rest args) (declare (ignore args)) (setq closed t)))
    (driver-check (handler-case (progn (fnn-pull-flight-dispose flight) nil)
                    (fnn-store-indeterminate () t))
                  "first uncertain release must survive subsequent cleanup faults")
    (driver-check (and awaited unpinned closed (fnn-pull-flight-closed flight))
                  "failed cold abandonment must not skip await unpin or CID release")
    (format t "~&PEER_ROUND_DRIVER_PASS cleanup~%")))
(when (equal *mode* "cleanup") (cleanup-fixture) (sb-ext:exit :code 0))
(when (equal *mode* "io") (io-fixture) (sb-ext:exit :code 0))
(when (equal *mode* "local") (local-fixture) (sb-ext:exit :code 0))
(block worker-fixture
(let ((producer nil) (runtime (%make-fnn-pull-runtime :service :recorded
                              :lock (sb-thread:make-mutex :name "round fixture"))))
  (unwind-protect
       (progn
         (loop for port from 1 to 3 do
           (multiple-value-bind (client server) (connected-pair)
             (push (cons port client) *sockets*) (push (cons port server) *server-sockets*)
             (fnn-socket-fd client)))
         (dolist (port '(2 3))
           (sb-bsd-sockets:socket-send (cdr (assoc port *server-sockets*)) (fnn-octets '(72)) 1))
         (setq producer
               (sb-thread:make-thread
                (lambda ()
                  (handler-case
                      (dotimes (i 70)
                        (sb-bsd-sockets:socket-send (cdr (assoc 1 *server-sockets*)) (fnn-octets '(83)) 1)
                        (sleep .01))
                    (sb-bsd-sockets:socket-error () nil)))))
         (setq *started* (get-internal-real-time))
         (when (equal *mode* "fault")
           (setf (fnn-pull-runtime-journals runtime) '(("A" . :journal-a) ("B" . :journal-b))
                 (symbol-function 'fnn-owner-feed-close)
                 (lambda (journal) (declare (ignore journal)) (error 'fnn-os-error :errno sb-posix:eio)))
           (let ((*fnn-read-syscall*
                   (lambda (&rest args) (declare (ignore args)) (fnn-fault "injected round core fault"))))
             (driver-check
              (handler-case (progn (fnn-pull-worker runtime) nil)
                (fnn-store-fault () t))
              "round core fault must survive cleanup failure"))
           (format t "~&PEER_ROUND_DRIVER_PASS fault~%")
           (return-from worker-fixture nil))
         (fnn-pull-worker runtime)
         (driver-check (and (member "B" *completed* :test #'equal)
                            (member "C" *completed* :test #'equal) *slow-observed*)
                       "healthy pull and catch-up must progress while slow pull retains partial state")
         (driver-check (and (integerp *partial*) (plusp *partial*))
                       "slow round retains observed octets across readiness yields")
         (format t "~&PEER_ROUND_DRIVER_PASS~%"))
    (dolist (entry (append *sockets* *server-sockets*)) (fnn-socket-shut (cdr entry)))
    (when producer (sb-thread:join-thread producer)))))
