; SCN-1136: actual heap consumers with actual ACL2 DEFAULT arithmetic.
; Machine/config/base/output observations are explicit seams. This is neither
; complete allocation coverage nor execution of a saved image/Store recovery.
(load "tests/native_operator_diagnostics_source-mock.lisp")
(in-package "ACL2")
(defun natp (x) (and (integerp x) (<= 0 x)))
(defun posp (x) (and (integerp x) (< 0 x)))
(defun nfix (x) (if (natp x) x 0))
(defun zp (x) (not (posp x)))
(defun len (x) (length x))
(defun true-listp (x) (if (consp x) (true-listp (cdr x)) (null x)))
(defun member-eq (x xs) (member x xs :test #'eq))
(defun assoc-eq (x xs) (assoc x xs :test #'eq))
(load "books/profile-limits.lisp")
(load "books/cold-read-layout.lisp")
(load "books/decoded-worker-backing.lisp")
; Read only the selected actual definitions/constants, not theorem forms or
; dependency substitutes. ALL selected names must exist in the source.
(defun selected-source (path names)
  (with-open-file (in path)
    (loop for form = (read in nil :eof) until (eq form :eof)
          when (and (consp form) (member (car form) '(defun defconst))
                    (member (second form) names))
          do (eval form) (setf names (remove (second form) names))
          finally (assert (null names)))))
(selected-source "books/cold-guard-bootstrap.lisp"
 '(*fn-cgb-roster* fn-cgb-capacity fn-cgb-retained-conses
   fn-cgb-prewarm-conses fn-cgb-baseline-octets))
(selected-source "books/heap-figure.lisp"
 '(*fn-heap-mib* fn-heap-mb-of fn-heap-machine-octets))
(selected-source "books/native-config.lisp"
 '(fn-ncfg-nth *fn-ncfg-max-u64* fn-native-config-output-resources-wfp))
(selected-source "books/cold-read-reservation.lisp" '(fn-crv-nth))
(selected-source "books/output-reservation.lisp" '(fn-orv-policy-p fn-orv-extend-reservation))
(selected-source "books/heap-store-figure.lisp" '(fn-heap-core-file *fn-heap-nursery-least-octets* fn-heap-nursery-trigger fn-heap-with-nursery fn-heap-grow-runtime-dynamic))
(selected-source "books/heap-reservation.lisp"
 '(*fn-heap-thread-runtime-octets* fn-heap-reservation-octets))
(selected-source (or (fourth sb-ext:*posix-argv*) "books/page-read-startup.lisp")
 '(fn-prstartup-nth fn-prstartup-fd-bookkeeping fn-prstartup-baseline-heap
   fn-prstartup-required-heap fn-prstartup-extend-default-reservation
   fn-prstartup-extend-operation-reservation))
(source-forms (or (third sb-ext:*posix-argv*) "host/native/heap.lisp")
 '(fnn-heap-extend-reservation))
(source-forms (or (fifth sb-ext:*posix-argv*) (third sb-ext:*posix-argv*) "host/native/heap.lisp")
 '(fnn-heap-reservation fnn-heap-print-store-line))
(source-forms "host/native/extent.lisp" '(fnn-extent-cache-limit))
(defparameter +fnn-gc-nursery-octets+ 67108864)
(defparameter *base* '(:heap 256 :small 8192 1024 16))
(defparameter *cold* nil)
(defparameter *output* nil)
(defparameter *core-observation* '(83886080 . 67108864))
(defparameter *machine* '(8589934592))
(defparameter *calls* nil)
(defparameter *captured-core* 0)
(defparameter *captured-machine* 0)
(defparameter *original-core* (symbol-function 'fnn-core))
(defun fnn-absolute (path) (concatenate 'string "/absolute" path))
(defun fnn-developer-selector (name) (declare (ignore name)) nil)
(defun fnn-heap-image-observation () (incf *captured-core*) *core-observation*)
(defun fnn-heap-observations () (incf *captured-machine*) *machine*)
(defun fnn-heap-history-observation (&rest args) (declare (ignore args)) '(0 . 0))
(defun fnn-core (entry &rest args)
  (case entry
    ((fn-heap-reserve-operation-decide fn-heap-status-decide) *base*)
    (fn-native-operator-host-result-run-cold-resources *cold*)
    (fn-native-operator-host-result-run-output-resources *output*)
    (fn-pio-direct-workers 4)
    (fn-arx-read-cache-entries 8)
    (fn-crv-extend-reservation
     (push (cons :cold args) *calls*) (first args))
    ((fn-prstartup-extend-operation-reservation fn-prstartup-extend-default-reservation)
     (push (cons :default args) *calls*) (apply (symbol-function entry) args))
    (fn-pfr-extend-operation-reservation
     (push (cons :peer args) *calls*) (first args))
    (fn-orv-extend-reservation
     (push (cons :output args) *calls*) (apply (symbol-function entry) args))
    (fn-heap-reserve-report-line (format nil "~s" (first args)))
    (fn-heap-decision-exit-code (if (eq (caar args) :heap) 0 1))
    (otherwise (apply *original-core* entry args))))
(defun heap-command (&optional (action :run) cold)
  (let ((*native-action* action) (*cold* cold)
        (*fnn-stdout* (make-string-output-stream))
        (*calls* nil) (*captured-core* 0) (*captured-machine* 0))
    (let ((code (fnn-command-heap "--" '("operator" "CONFIG" "run"))))
      (values code (get-output-stream-string *fnn-stdout*)
              (reverse *calls*) *captured-core* *captured-machine*))))
(multiple-value-bind (code line calls cores machines) (heap-command)
  (assert (= code 0))
  (assert (equal line "(:HEAP 257 :SMALL 8192 1024 16)"))
  (assert (equal (mapcar #'car calls) '(:cold :default :peer :output)))
  (assert (equal (subseq (cdr (second calls)) 1 6)
                 '(:run nil "/absolute/fixture" 4 8)))
  (assert (equal (second (cdr (fourth calls))) nil))
  (assert (= cores machines 1)))
; No selected backing extension for init/offline/help, or explicit cold.
(dolist (action '(:init :status :compact nil))
  (multiple-value-bind (code line) (heap-command action)
    (assert (= code 0)) (assert (equal line "(:HEAP 256 :SMALL 8192 1024 16)"))))
(multiple-value-bind (code line) (heap-command :run '(complete))
  (assert (= code 0)) (assert (equal line "(:HEAP 256 :SMALL 8192 1024 16)")))
; Exact minimum-machine boundary and prior refusal remain ACL2 decisions.
(let* ((d (fn-prstartup-extend-default-reservation *base* nil "/absolute/fixture" 4 8
                                                  *core-observation* *machine*))
       (total (fn-heap-reservation-octets (second d) *core-observation* (fifth d) (sixth d))))
  (let ((*machine* (list total))) (assert (= (heap-command) 0)))
  (let ((*machine* (list (1- total)))) (assert (= (heap-command) 1))))
(let ((*base* '(:refused :original-refusal 256 128)))
  (multiple-value-bind (code line) (heap-command)
    (assert (= code 1)) (assert (equal line "(:REFUSED :ORIGINAL-REFUSAL 256 128)"))))
; Status's next-run figure shares the DEFAULT projection and observations.
(let ((*calls* nil) (*captured-core* 0) (*captured-machine* 0)
      (*fnn-stdout* (make-string-output-stream)))
  (fnn-heap-print-store-line "/fixture")
  (assert (equal (get-output-stream-string *fnn-stdout*) "(:HEAP 257 :SMALL 8192 1024 16)"))
  (assert (= *captured-core* *captured-machine* 1))
  (assert (equal (fourth (cdr (assoc :default *calls*))) "/absolute/fixture")))
(format t "SOURCE DEFAULT HEAP PASSED~%")
