; Evaluate the actual owner-run terminal conjunction, not a copied predicate.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "COMMON-LISP"))
(defpackage "ACL2_*1*_ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-arena-return-observation (log)
  (declare (ignorable log))
  (harness-stub-reached 'fnn-arena-return-observation "host/native/io.lisp"))
(defun fnn-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-core "host/native/io.lisp"))
(defun fnn-developer-selector (name)
  (declare (ignorable name))
  (harness-stub-reached 'fnn-developer-selector "host/native/io.lisp"))
(defun fnn-err (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-err "host/native/io.lisp"))
(defun fnn-extent-direct-start ()
  (harness-stub-reached 'fnn-extent-direct-start "host/native/extent.lisp"))
(defun fnn-extent-end-recovery-cache ()
  (harness-stub-reached 'fnn-extent-end-recovery-cache "host/native/extent.lisp"))
(defun fnn-extent-executor-stop ()
  (harness-stub-reached 'fnn-extent-executor-stop "host/native/extent.lisp"))
(defun fnn-fault (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-fault "host/native/io.lisp"))
(defun fnn-gc-nursery-octets ()
  (harness-stub-reached 'fnn-gc-nursery-octets "host/native/io.lisp"))
(defun fnn-listen (port &key family backlog address)
  (declare (ignorable port family backlog address))
  (harness-stub-reached 'fnn-listen "host/native/io.lisp"))
(defun fnn-log-line (line)
  (declare (ignorable line))
  (harness-stub-reached 'fnn-log-line "host/native/io.lisp"))
(defun fnn-log-writer-start ()
  (harness-stub-reached 'fnn-log-writer-start "host/native/io.lisp"))
(defun fnn-mux-budget-install (service tls-context)
  (declare (ignorable service tls-context))
  (harness-stub-reached 'fnn-mux-budget-install "host/native/mux.lisp"))
(defun fnn-mux-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-mux-start "host/native/mux.lisp"))
(defun fnn-out (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-out "host/native/io.lisp"))
(defun fnn-owner-accept (service listener once)
  (declare (ignorable service listener once))
  (harness-stub-reached 'fnn-owner-accept "host/native/owner.lisp"))
(defun fnn-owner-action (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-owner-action "host/native/owner.lisp"))
(defun fnn-owner-actor-join (service worker &key timeout)
  (declare (ignorable service worker timeout))
  (harness-stub-reached 'fnn-owner-actor-join "host/native/owner.lisp"))
(defun fnn-owner-claim-run-authority (&optional caller-reservation)
  (declare (ignorable caller-reservation))
  (harness-stub-reached 'fnn-owner-claim-run-authority "host/native/owner.lisp"))
(defun fnn-owner-cold-shutdown (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-cold-shutdown "host/native/owner.lisp"))
(defun fnn-owner-drain-service (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-drain-service "host/native/owner.lisp"))
(defun fnn-owner-feed-close-entries (entries)
  (declare (ignorable entries))
  (harness-stub-reached 'fnn-owner-feed-close-entries "host/native/owner.lisp"))
(defun fnn-owner-install (root max-connections &optional fault)
  (declare (ignorable root max-connections fault))
  (harness-stub-reached 'fnn-owner-install "host/native/owner.lisp"))
(defun fnn-owner-journal-close ()
  (harness-stub-reached 'fnn-owner-journal-close "host/native/owner.lisp"))
(defun fnn-owner-journal-open (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-journal-open "host/native/owner.lisp"))
(defun fnn-owner-log-settlement ()
  (harness-stub-reached 'fnn-owner-log-settlement "host/native/owner.lisp"))
(defun fnn-owner-measure-report ()
  (harness-stub-reached 'fnn-owner-measure-report "host/native/owner.lisp"))
(defun fnn-owner-page-read-startup (root max-connections cold-resources output-resources retain)
  (declare (ignorable root max-connections cold-resources output-resources retain))
  (harness-stub-reached 'fnn-owner-page-read-startup "host/native/owner.lisp"))
(defun fnn-owner-peer-flight-startup (service capture)
  (declare (ignorable service capture))
  (harness-stub-reached 'fnn-owner-peer-flight-startup "host/native/owner.lisp"))
(defun fnn-owner-refresh-read-octets (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-refresh-read-octets "host/native/owner.lisp"))
(defun fnn-owner-release-recovery-garbage ()
  (harness-stub-reached 'fnn-owner-release-recovery-garbage "host/native/owner.lisp"))
(defun fnn-owner-retain-run-authority (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-retain-run-authority "host/native/owner.lisp"))
(defun fnn-owner-retire-final-report (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-retire-final-report "host/native/owner.lisp"))
(defun fnn-owner-run-startup-hooks (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-run-startup-hooks "host/native/owner.lisp"))
(defun fnn-owner-service-nursery ()
  (harness-stub-reached 'fnn-owner-service-nursery "host/native/owner.lisp"))
(defun fnn-owner-space-prime (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-space-prime "host/native/owner.lisp"))
(defun fnn-owner-start-committer (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-start-committer "host/native/owner.lisp"))
(defun fnn-owner-start-tls-accept (service listener &optional implicit-tls)
  (declare (ignorable service listener implicit-tls))
  (harness-stub-reached 'fnn-owner-start-tls-accept "host/native/owner.lisp"))
(defun fnn-owner-stop-service (service exit-code)
  (declare (ignorable service exit-code))
  (harness-stub-reached 'fnn-owner-stop-service "host/native/owner.lisp"))
(defun fnn-owner-store-settlement (service settlement)
  (declare (ignorable service settlement))
  (harness-stub-reached 'fnn-owner-store-settlement "host/native/owner.lisp"))
(defun fnn-owner-wait-workers (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-wait-workers "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-joined (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-joined "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-start "host/native/owner.lisp"))
(defun fnn-socket-shut (socket)
  (declare (ignorable socket))
  (harness-stub-reached 'fnn-socket-shut "host/native/io.lisp"))
;;; ---- derived stubs: END ----
(defstruct fnn-owner-service snapshot-jobs peer-flight-bank workers cold-head committer)
(defmacro fnn-with-roster ((service) &body body) (declare (ignore service)) `(progn ,@body))
(defvar *fnn-cold-workers* nil)
(defun fnn-cold-worker-thread (slot) slot)
(defun fnn-mux-drained-p (service) (declare (ignore service)) t)
(defun fnn-owner-syncer-drained-p (service) (declare (ignore service)) t)
(defun fnn-owner-output-drained-p (service) (declare (ignore service)) t)
(defun fnn-extent-executor-drained-p () t)
(defun fnn-peer-flight-bank-drained (bank) (not bank))
(defun terminal-conjunction (form)
 (when (consp form)
  (if (and (eq (car form) 'when)
           (member '(fnn-owner-feed-close-all service) (cddr form) :test #'equal))
      (second form)
    (loop for item in form thereis (terminal-conjunction item)))))
(defparameter *terminal* nil)
(with-open-file (in "host/native/owner.lisp")
 (loop for form = (read in nil :eof) until (eq form :eof)
  when (and (consp form) (eq (car form) 'defun)) do
   (case (second form)
    (fnn-owner-snapshot-jobs-drained-p (eval form))
    (fnn-owner-run (setf *terminal* (terminal-conjunction form))))))
(assert *terminal*)
; The conjunction must consume the actual snapshot observer and peer bank.
(assert (member '(fnn-owner-snapshot-jobs-drained-p service) *terminal* :test #'equal))
(assert (member '(fnn-peer-flight-bank-drained (fnn-owner-service-peer-flight-bank service)) *terminal* :test #'equal))
(setf (symbol-function 'terminal-joined-p)
 (eval `(lambda (service modules-joined) ,*terminal*)))
(let ((service (make-fnn-owner-service)))
 (assert (terminal-joined-p service t))
 (setf (fnn-owner-service-snapshot-jobs service) '(:released-but-not-joined))
 (assert (not (terminal-joined-p service t)))
 (setf (fnn-owner-service-snapshot-jobs service) '(:joined-pin-return-uncertain))
 (assert (not (terminal-joined-p service t)))
 (setf (fnn-owner-service-snapshot-jobs service) nil
       (fnn-owner-service-peer-flight-bank service) :bank-debt)
 (assert (not (terminal-joined-p service t)))
 (setf (fnn-owner-service-peer-flight-bank service) nil)
 (assert (terminal-joined-p service t))
 (assert (not (terminal-joined-p service nil))))
(format t "SOURCE OWNER TERMINAL COHORTS PASSED~%")
