;;; Retained TCPCL physical-turn packet plus actual once drain consumer.
(load "tests/native_tcpcl_retained_turn_raw.lisp")
;;; Diagnostic once waits for retained local jobs after EOF. The ordinary
;;; listener loop also runs its service turn independently of any new input.
(defvar *pending* 0)
(defvar *turns* 0)
(defvar *control* 0)
(defvar *closed* 0)
(defvar *handled* 0)
(defun fnn-bpnc-pump (node) (declare (ignore node)) (incf *control*))
(defun fnn-bplc-live (listeners) (declare (ignore listeners)) '(99))
(defun fnn-socket-fd (socket) socket)
(defun fnn-poll-readable (fds timeout) (declare (ignore fds timeout)) 0)
(defun fnn-bplc-model (listeners) listeners)
;; The production socket is an object, never one of the wait/refuse keywords.
(defun fnn-accept-attempt (listener) (declare (ignore listener)) (list :socket))
(defun fnn-bplc-step (listeners event)
 (declare (ignore listeners)) (when (eq (car event) :session-closed) (incf *closed*)))
(defun fnn-out (&rest args) (declare (ignore args)))
(defun fnn-core (name &rest args)
 (declare (ignore args))
 (case name (fn-bplc-accept-plan '(1 99)) (fn-bplc-runtime-line "ready")
  (otherwise (error "unexpected core ~s" name))))
(with-open-file (stream "host/native/bp-control.lisp")
 (loop for form = (read stream nil :eof)
       when (eq form :eof) do (error "accept-loop missing")
       when (and (consp form) (eq (car form) 'defun) (eq (second form) 'fnn-bpnc-accept-loop))
       do (eval form) (return)))
(fnn-bpnc-accept-loop :control :listeners
 (lambda (socket) (declare (ignore socket)) (incf *handled*) (setq *pending* 3)) t
 :pending (lambda () (plusp *pending*))
 :progress (lambda () (incf *turns*) (when (plusp *pending*) (decf *pending*))))
(assert (= *handled* 1)) (assert (= *closed* 1))
(assert (zerop *pending*)) (assert (= *turns* 4)) (assert (= *control* 4))
(format t "PASS actual accept scheduling: once drains retained quanta with control turns.~%")
