(require :sb-posix)
(require :sb-bsd-sockets)
;;; Load complete production definitions, inject physical close failures.
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(defstruct fnn-owner-service store feeds)
(defvar *calls* nil)
(defvar *close-condition* (make-condition 'simple-error :format-control "close failed"))
(defvar *open-condition* (make-condition 'simple-error :format-control "open failed"))
(defun fnn-owner-feed-close (journal)
  (push journal *calls*)
  (when (member journal '(:a :b)) (error *close-condition*)))
(defun fnn-owner-feed-existing-peers (store) (declare (ignore store)) nil)
(defun fnn-owner-feed-open (store peer)
  (declare (ignore store))
  (cond ((equal peer "a") :a) ((equal peer "b") :b) (t (error *open-condition*))))
(with-open-file (input "host/native/owner.lisp")
  (loop for form = (read input nil :eof) until (eq form :eof) do
    (when (and (consp form) (eq (car form) 'defun)
               (member (second form) '(fnn-owner-feed-close-entries fnn-owner-feed-open-all
                                      fnn-owner-feed-close-all fnn-owner-feed-open-missing)))
      (eval form))))
(let ((service (make-fnn-owner-service :feeds '(("a" . :a) ("b" . :b) ("c" . :c))))
      (caught nil) (*calls* nil))
  (handler-case (fnn-owner-feed-close-all service) (error (e) (setq caught e)))
  (assert (eq caught *close-condition*))
  (assert (equal (reverse *calls*) '(:a :b :c)))
  (assert (null (fnn-owner-service-feeds service))))
(dolist (operation '(fnn-owner-feed-open-all fnn-owner-feed-open-missing))
  (let ((service (make-fnn-owner-service :feeds '(("old" . :old))))
        (caught nil) (*calls* nil))
    (handler-case (funcall operation service '("a" "b" "fail"))
      (error (e) (setq caught e)))
    (assert (eq caught *open-condition*))
    (assert (equal (reverse *calls*) '(:b :a)))
    (assert (equal (fnn-owner-service-feeds service) '(("old" . :old))))))
(format t "PASS actual source feed cleanup: all closes attempted; primary open failure preserved.~%")
