(load "tests/native_immutable_close_source.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-fault (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-fault "host/native/io.lisp"))
;;; ---- derived stubs: END ----
(defun fnn-node-secret-ensure-directory (&rest args) (declare (ignore args)) "/root")
(defun fnn-node-secret-path (&rest args) (declare (ignore args)) "/root/key")
(defun fnn-node-secret-read-entry (&rest args) (declare (ignore args)) :current)
(defun fnn-node-secret-epoch-path (&rest args) (declare (ignore args)) "/root/old-key")
(defun fnn-lstat (&rest args) (declare (ignore args)) t)
(defun fnn-node-secret-same-file-p (&rest args) (declare (ignore args)) t)
(defun fnn-node-secret-identity (&rest args) (declare (ignore args)) :identity)
(defun fnn-node-secret-fresh-root () :fixture-seed)
(defun fnn-node-secret-render (&rest args) (declare (ignore args)) #(1))
(defun fnn-staging (&rest args) (declare (ignore args)) "/root/stage")
(defun fnn-join (&rest args) (declare (ignore args)) "/root/stage/key")
(defun fnn-random-hex (&rest args) (declare (ignore args)) "suffix")
(defun fnn-node-secret-durable (&rest args) (declare (ignore args)))
(defun fnn-core (name &rest args)
  (case name (fn-ns-entry-epoch (if (eq (first args) :current) 1 2))
    (fn-ns-rotate-entry :next) (otherwise (error "core ~a" name))))
(defun fnn-replace (&rest args) (declare (ignore args)) (setq *published* t))
(with-open-file (in "host/native/io.lisp")
 (loop for f = (read in nil :eof) until (eq f :eof) do
  (when (and (consp f) (eq (car f) 'defun) (eq (second f) 'fnn-node-secret-rotate)) (eval f))))
(dolist (fault '(:close :write-close :body-close nil))
  (let ((*fnn-immutable-close-debts* nil) (*publication-failure* fault)
        (*publication-calls* nil) (*published* nil) (caught nil) (epoch nil))
    (handler-case (setq epoch (fnn-node-secret-rotate (%make-fnn-store)))
      (error (e) (setq caught e)))
    (assert (= 1 (count '(:close 55) *publication-calls* :test #'equal)))
    (if fault
        (progn
          (assert caught) (assert (not *published*))
          (assert (member :unlink *publication-calls*))
          (assert (eq (fnn-immutable-close-observation) :uncertain))
          (when (eq fault :body-close) (assert (eq caught *body-primary*))))
      (progn (assert (null caught)) (assert *published*) (assert (= epoch 2))))))
(format t "native node secret staged return source PASS~%")
