;;; Actual TCPCL session and BP accept-loop bodies: post-flush progress on
;;; keepalive/input, a zero poll for carried work, EOF to listener/once drain.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(define-condition fnn-store-indeterminate (error) ())
(defun fnn-register-verb (&rest args) (declare (ignore args)))
(defun fnn-core (&rest args) (declare (ignore args)) :session)
(defvar *fnn-tcl-source-start* nil)
(defvar *fnn-tcl-progress* nil)
(defvar *fnn-tcl-work-pending* nil)
(with-open-file (stream "host/native/tcpcl.lisp")
 (loop for form = (read stream nil :eof) until (eq form :eof) do
  (when (and (consp form)
             (or (and (eq (car form) 'defstruct) (eq (car (second form)) 'fnn-tcl-conn))
                 (and (eq (car form) 'defun) (eq (second form) 'fnn-tcl-session))))
   (eval form))))
(defvar *events* nil)
(defvar *reads* 0)
(defun fnn-tcl-now () 1000)
(defun fnn-tcl-apply (conn triple &optional source)
 (declare (ignore conn triple source)) (push :flush *events*))
(defun fnn-core (name &rest args)
 (declare (ignore args))
 (case name
  (fn-tcl-host-initial :session)
  (fn-tcl-host-phase :established)
  ((fn-tcl-host-open fn-tcl-host-tick fn-tcl-host-tcp-closed fn-tcl-host-drive) (list :session nil nil))
  (otherwise (error "unexpected core ~s" name))))
(defun fnn-tcl-offer (&rest args) (declare (ignore args)))
(defun fnn-tcl-record-trace (&rest args) (declare (ignore args)))
(defun fnn-octet-list (x) (coerce x 'list))
(defun fnn-recv (fd timeout)
 (declare (ignore fd)) (assert (zerop timeout))
 (incf *reads*) (if (<= *reads* 2) #(4) #()))
(let ((*fnn-tcl-work-pending* (lambda (conn) (declare (ignore conn)) t))
      (*fnn-tcl-progress* (lambda (conn) (declare (ignore conn))
                            (assert (eq (first *events*) :flush))
                            (push :progress *events*))))
 (fnn-tcl-session 99 :passive :params "test" "/spool")
 (assert (= *reads* 3))
 (assert (= (count :progress *events*) 2)))

;;; Diagnostic once waits for retained local jobs after EOF. The ordinary
;;; listener loop also runs its service turn independently of any new input.
(defvar *pending* 0)
(defvar *turns* 0)
(defvar *control* 0)
(defvar *closed* 0)
(defvar *handled* 0)
(defun fnn-bpnc-pump (node) (declare (ignore node)) (incf *control*))
(defun fnn-bplc-live (listeners) (declare (ignore listeners)) '(99))
(defun fnn-socket-fd (socket) socket)
(defun fnn-poll-readable (fds timeout) (declare (ignore fds timeout)) 0)
(defun fnn-bplc-model (listeners) listeners)
;; The production socket is an object, never one of the wait/refuse keywords.
(defun fnn-accept-attempt (listener) (declare (ignore listener)) (list :socket))
(defun fnn-bplc-step (listeners event)
 (declare (ignore listeners)) (when (eq (car event) :session-closed) (incf *closed*)))
(defun fnn-out (&rest args) (declare (ignore args)))
(defun fnn-core (name &rest args)
 (declare (ignore args))
 (case name (fn-bplc-accept-plan '(1 99)) (fn-bplc-runtime-line "ready")
  (otherwise (error "unexpected core ~s" name))))
(with-open-file (stream "host/native/bp-control.lisp")
 (loop for form = (read stream nil :eof)
       when (eq form :eof) do (error "accept-loop missing")
       when (and (consp form) (eq (car form) 'defun) (eq (second form) 'fnn-bpnc-accept-loop))
       do (eval form) (return)))
(fnn-bpnc-accept-loop :control :listeners
 (lambda (socket) (declare (ignore socket)) (incf *handled*) (setq *pending* 3)) t
 :pending (lambda () (plusp *pending*))
 :progress (lambda () (incf *turns*) (when (plusp *pending*) (decf *pending*))))
(assert (= *handled* 1)) (assert (= *closed* 1))
(assert (zerop *pending*)) (assert (= *turns* 4)) (assert (= *control* 4))
(format t "PASS actual TCPCL/accept scheduling: flush before progress on input, zero poll, EOF, once drains retained quanta with control turns.~%")
