; Actual internal raw source/controller/PRS/pin and receiver primitives.
; Mutable stobj recording shims; synthetic family demand; NO installer grant.
(require :sb-posix)
(unless (find-package "ACL2") (make-package "ACL2" :use '("COMMON-LISP")))
(in-package "ACL2")
; Load trusted definitions/constants/fixture literals, not previous scenarios.
(with-open-file (stream "tests/native_bpsec_source_observation.lisp")
 (loop for form = (read stream nil :end) until (eq form :end) do
  (when (and (consp form)
    (or (member (first form) '(defun defmacro defparameter defvar declaim))
        (eq (first form) 'handler-bind)
        (and (eq (first form) 'dolist) (eq (caadr form) 'selection))))
   (eval form))))
(load "build/bpsec-registered-source-observation/recording-loader.lisp")
(dolist (name '(fn-bprr-readcopy fn-bprr-controller-reserve fn-bprr-controller-install
               fn-bprr-registered-receive fn-tcl-make-contact fn-tcl-make-sess-init))
 (load-actual name))
(defun registered-source-prepare (wire)
 ; Real registered controller, exact retained TCPCL root and SAMEPRS next.
 ; Demand/factory/pool inputs are explicitly synthetic recording fixtures.
 (let* ((registry (create-fn-bprx-raw-registry))
        (ledger '((1048576 0 0 8 1000) (0 0 0 0 0) 41 nil))
        (demand '(32768 0 0 1 1))
        (params (fn-tcl-make-params 30 512 1024 '(100 116 110 58 97) nil nil))
        (controller nil) (ref nil) (root nil) (maintained-count nil))
  (multiple-value-bind (word token next-ledger next)
      (fn-bprr-controller-reserve :passive params 0 demand ledger registry)
   (source-check (eq word :tcpcl-reserved))
   (setf controller token ledger next-ledger registry next))
  (loop repeat 64 until (null (fn-bprr-intent registry)) do
   (multiple-value-bind (word left next) (fn-bprr-controller-install 64 registry)
    (declare (ignore left))
    (source-check (member word '(:source-directory-created :tcpcl-registered)))
    (setf registry next)))
  (source-check (null (fn-bprr-intent registry)))
  (let* ((bytes (coerce wire 'list)) (split (min 210 (length bytes)))
         (first (subseq bytes 0 split)) (last (nthcdr split bytes)))
   (dolist (message (list (fn-tcl-make-contact 4 0)
                         (fn-tcl-make-sess-init 30 512 1024 '(100 116 110 58 98) nil)
                         (fn-tcl-make-xfer-segment 2 9 nil first)
                         (fn-tcl-make-xfer-segment 0 9 nil nil)
                         (fn-tcl-make-xfer-segment 1 9 nil last)))
    (multiple-value-bind (word token events next-ledger left next)
        (fn-bprr-registered-receive controller message 0 demand ledger 64 registry)
     (declare (ignore left))
     (source-check (member word '(:no-source-completion :source-reserved)))
     (when token
      (source-check (equal token '(:bps-ref 42 42)))
      (source-check (equal events (list (list :send (fn-tcl-make-xfer-ack 1 9 (length bytes)))
                                      (list :source-registered token))))
      (setf ref token root (fn-bprr-at 4 (fn-bprr-intent next))
            maintained-count (fn-bprr-at 5 (fn-bprr-intent next)))
      (source-check (equal root (list last nil first))))
     (setf ledger next-ledger registry next))))
  (source-check ref)
  (loop repeat 100 until (null (fn-bprr-intent registry)) do
   (multiple-value-bind (word left next) (fn-bprr-install-step 64 registry)
    (declare (ignore left))
    (source-check (member word '(:source-directory-created :source-retained)))
    (setf registry next)))
  (source-check (null (fn-bprr-intent registry)))
  (let ((published nil))
   (loop repeat 4000 until published do
    (multiple-value-bind (word ignored left next) (fn-bprr-action ref :populate nil nil 0 0 64 registry)
     (declare (ignore ignored left)) (setf registry next)
     (cond ((eq word :source-needs-leaf)
            (multiple-value-bind (word ignored left next) (fn-bprr-action ref :construct nil nil 0 0 64 registry)
             (declare (ignore ignored left))
             (source-check (member word '(:source-directory-created :source-filling :source-leaf-present)))
             (setf registry next)))
           ((eq word :source-published) (setf published t))
           (t (source-check (member word '(:yield :source-byte-pending :source-byte)))))))
   (source-check published))
  (multiple-value-bind (word pin next-ledger left next)
      (fn-bprr-pin-issue ref '(4096 0 0 0 1) ledger 64 registry)
   (declare (ignore left))
   (source-check (eq word :source-pinned))
   (source-check (equal pin '(:bps-source-pin 43 42 42)))
   (values ref pin next-ledger next root maintained-count))))
(multiple-value-bind (ref pin ledger registry root) (registered-source-prepare *a2-wire*)
 (declare (ignore ledger root))
 (multiple-value-bind (word bytes left next) (fn-bprr-readcopy ref pin 0 64 4096 registry)
  (declare (ignore left next))
  (source-check (eq word :source-window))
  (source-check (equal bytes (coerce (subseq *a2-wire* 0 64) 'list))))
 (dolist (row (list (list '(:bps-ref 42 41) pin 0 1 4096 :stale-source)
                   (list ref '(:bps-source-pin 44 42 42) 0 1 4096 :stale-source-pin)
                   (list ref pin (length *a2-wire*) 1 4096 :source-range)
                   (list ref pin 0 1 0 :yield)))
  (let ((before *recording-creators*))
   (multiple-value-bind (word bytes left next)
       (fn-bprr-readcopy (first row) (second row) (third row) (fourth row) (fifth row) registry)
    (declare (ignore left next))
    (source-check (eq word (sixth row))) (source-check (null bytes)))
   (source-check (= before *recording-creators*)))))
(format t "PASS setup actual registered source/ref/pin/readcopy, checks=~d; recording only~%" *source-observation-checks*)

(defun registered-source-window (ref pin at count registry &optional (fuel 4096))
 (let ((before *recording-creators*))
  (multiple-value-bind (word bytes left next) (fn-bprr-readcopy ref pin at count fuel registry)
   (source-check (= before *recording-creators*))
   (source-check (eq registry next))
   (when (eq word :source-window) (source-check (= (length bytes) count)))
   (values word bytes left next))))
(defun registered-source-framing (ref root maintained-count q)
 ; Recording-only observation of ACTUAL stored intent root/count. Production
 ; registered framing begin and extent issuer remain BP-owned and unavailable.
 (let ((job (fn-bpsw-begin ref root maintained-count)) (events nil))
  (loop repeat (+ 100 (* 8 maintained-count)) do
   (multiple-value-bind (word next used event) (fn-bpsw-turn job q 0)
    (source-check (and (< 0 used) (<= used q)))
    (source-check (eq root (fn-tsc-at 8 (fn-bps-field 5 next))))
    (setf job next)
    (when (eq word :block-source) (push event events))
    (when (member word '(:source-complete :refused))
     (source-check (eq word :source-complete))
     (return-from registered-source-framing (reverse events)))))
  (error "registered source framing recording exhausted")))
(defun registered-asb (ref pin security descriptor q registry)
 (let* ((data (ninth security)) (start (third data)) (size (fourth data))
        (cursor (fn-bps-asb-start (fifth security) (second ref) start size
                   (fn-bps-limits-make 4096 128 16 16 2048 2048)))
        (role (if (eq (second descriptor) :verify-bib) :hmac :aad)))
  (loop repeat (+ 100 (* 10 size)) do
   (let* ((at (fn-bps-get :offset cursor))
          (fragment (fn-bps-input-fragment descriptor role data (- at start) q))
          (octets nil))
    (if (eq (first fragment) :input-complete)
     (source-check (= at (+ start size)))
     (progn
      (source-check (eq (first fragment) :bps-input-fragment))
      (let ((span (fourth fragment)))
       (source-check (equal (second span) ref))
       (multiple-value-bind (word bytes left next)
           (registered-source-window ref pin (third span) (fifth fragment) registry)
        (declare (ignore left next))
        (source-check (eq word :source-window)) (setf octets bytes)))))
    (let ((step (fn-bps-asb-step cursor (fn-bps-window-make (second ref) at octets) q)))
     (source-check (<= (fourth step) q)) (setf cursor (third step))
     (when (member (first step) '(:parsed :refused :unsupported))
      (source-check (eq (first step) :parsed))
      (source-check (= (fn-bps-get :offset cursor) (+ start size)))
      (return-from registered-asb (fn-bps-asb-span-result cursor))))))
  (error "registered ASB window recording exhausted")))
(defun registered-span-bytes (ref pin span registry)
 ; Test relation: parsed backing slot is the SAMEPRS source's slot. The
 ; production binding/lifetime refinement is NOT supplied by this assertion.
 (source-check (and (eq (first span) :bytes-span) (= (second span) (second ref))))
 (multiple-value-bind (word bytes left next)
     (registered-source-window ref pin (third span) (fourth span) registry)
  (declare (ignore left next))
  (source-check (eq word :source-window))
  (coerce bytes '(simple-array (unsigned-byte 8) (*)))))
(defun registered-primitive-command (function handle descriptor role command q ref pin registry)
 (let ((offset 0))
  (loop
   (let* ((fragment (fn-bps-input-fragment descriptor role command offset q))
          (selected (fourth fragment)) (bytes nil))
    (when (eq (first fragment) :input-complete) (return))
    (source-check (eq (first fragment) :bps-input-fragment))
    (case (first selected)
     (:bps-literal (setf bytes (coerce (second selected) '(simple-array (unsigned-byte 8) (*)))))
     (:bps-span
      (source-check (equal (second selected) ref))
      ; Genuine pre-I/O yield returns no bytes; no primitive call/advance.
      (multiple-value-bind (word unavailable left next)
          (registered-source-window ref pin (third selected) (fifth fragment) registry 0)
       (declare (ignore left next))
       (source-check (eq word :yield)) (source-check (null unavailable)))
      (multiple-value-bind (word octets left next)
          (registered-source-window ref pin (third selected) (fifth fragment) registry)
       (declare (ignore left next))
       (source-check (eq word :source-window))
       (setf bytes (coerce octets '(simple-array (unsigned-byte 8) (*))))))
     (otherwise (error "invalid selected primitive command")))
    (source-check (= (length bytes) (fifth fragment)))
    (source-check (null (funcall function handle bytes 0 (fifth fragment))))
    ; Proposed offset is committed only after the real primitive call returns.
    (setf offset (sixth fragment))))))
; Structural unknown-extension padding fixture moves the A1 result across
; actual frozen leaf255/256. Scope0 IPPT/MAC remains the published literal.
; This does not assert semantic admission of the padding extension/bundle.
(defparameter *a1-edge-wire*
 (concatenate '(simple-array (unsigned-byte 8) (*))
  (subseq *a1-wire* 0 29) #(133 24 200 3 0 0 88 180)
  (make-array 180 :element-type '(unsigned-byte 8) :initial-element 0)
  (subseq *a1-wire* 29)))
(defun registered-diagnostic-descriptor (template asb)
 ; UNISSUED operation/key/policy/input refs. Actual parsed IV/expected tag
 ; spans are retained verbatim; no policy/unwrap/key/current grant is created.
 (let* ((bib (eq (second template) :verify-bib))
        (params (copy-list (fn-bps-field 9 template)))
        (expected (second (first (first (eighth asb))))))
  (unless bib
   (setf (fourth params) (second (source-asb-pair 1 (seventh asb)))
         (fifth params) (second (source-asb-pair 3 (seventh asb)))))
  (fn-bps-op-make (fn-bps-field 1 template) (fn-bps-field 2 template)
   (fn-bps-field 3 template) (fn-bps-field 4 template) (fn-bps-field 5 template)
   (fn-bps-field 6 template) (fn-bps-field 7 template) (fn-bps-field 8 template)
   params (fn-bps-field 10 template) expected)))
; A1/A2 actual stored-source windows, not ghost slices or supplied window bytes.
(dolist (q '(1 7 64))
 (dolist (row (list (list :a1 *a1-wire* *a1-descriptor*)
                   (list :a2 *a2-wire* *a2-descriptor*)
                   (list :a1-edge *a1-edge-wire* *a1-descriptor*)))
  (multiple-value-bind (ref pin ledger registry root total) (registered-source-prepare (second row))
   (declare (ignore ledger))
   (destructuring-bind (primary &rest blocks) (registered-source-framing ref root total q)
    (let ((security (if (eq (first row) :a1-edge) (second blocks) (first blocks)))
          (target (car (last blocks))))
    (let* ((asb (registered-asb ref pin security (third row) q registry))
           (descriptor (registered-diagnostic-descriptor (third row) asb))
           (expected (registered-span-bytes ref pin (second (first (first (eighth asb)))) registry))
           (planned (fn-bps-input-plan descriptor primary target security)) (plan (second planned)))
     (source-check (eq (first planned) :planned))
     (format t "REGISTERED PLAN source=~s descriptor=~s commands=~s~%" ref descriptor plan)
     (when (eq (first row) :a1-edge)
      (let ((tagspan (second (first (first (eighth asb))))))
       (source-check (< (third tagspan) 256))
       (source-check (> (+ (third tagspan) (fourth tagspan)) 256))))
     (if (member (first row) '(:a1 :a1-edge))
      (progn
       (source-check (equal (fn-bps-primitive-select descriptor (length *a1-key*)) '(:refused :key-width)))
       (let ((handle (fnn-bpsec-hmac-start descriptor :sha512 *a1-key* 64)))
        (unwind-protect
         (progn
          (dolist (command (third plan))
           (registered-primitive-command #'fnn-bpsec-hmac-update handle descriptor :hmac command q ref pin registry))
          (let ((raw (fnn-bpsec-hmac-final handle)))
           (source-check (eq (first raw) descriptor))
           (source-check (equalp (subseq (third raw) 0 64) expected))
           (format t "REGISTERED A1 q=~d source=~s pin=~s parsed=~s mac=~a keyprofile=:refused~%"
             q ref pin asb (source-hex-string (subseq (third raw) 0 64)))
           (fnn-bpsec-cleanse (third raw))))
         (fnn-bpsec-cancel handle))))
      (let* ((iv (registered-span-bytes ref pin (second (source-asb-pair 1 (seventh asb))) registry))
             (primitive (fn-bps-primitive-select descriptor (length *a2-key*)))
             (handle (fnn-bpsec-gcm-start descriptor (third primitive) *a2-key* iv 64)))
       (unwind-protect
        (progn
         (dolist (command (third plan))
          (registered-primitive-command #'fnn-bpsec-gcm-aad handle descriptor :aad command q ref pin registry))
         (registered-primitive-command #'fnn-bpsec-gcm-update handle descriptor :ciphertext (fourth plan) q ref pin registry)
         (let* ((raw (fnn-bpsec-gcm-final handle expected))
                (answer (fn-bps-primitive-answer descriptor
                          (list :bps-primitive-observation (first raw) (second raw) (third raw)) nil)))
          (source-check (eq (second raw) :authenticated)) (source-check (null (third raw)))
          (source-check (eq (second answer) :authenticated))
          (source-check (not (fn-bps-completionp (fourth answer))))
          (format t "REGISTERED A2 q=~d source=~s pin=~s parsed=~s raw=~s core=~s~%"
             q ref pin asb raw answer)))
        (fnn-bpsec-cancel handle))))))))))
(format t "PASS actual registered array source -> bounded ASB/commands -> real receiver crypto, checks=~d; synthetic stobj/family fixtures, no native authority~%" *source-observation-checks*)
