;;; Actual streamed import ingress around a real regular-file/FIFO descriptor.
(require :sb-posix)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(defun source-definition (path kind name)
  (with-open-file (stream path)
    (let* ((text (make-string (file-length stream))) (prefix (format nil "(~a ~a " kind name)))
      (read-sequence text stream)
      (read-from-string text nil nil :start (or (search prefix text) (error "missing ~a" name))))))
(defparameter +fnn-o-nofollow+ 0)
(defparameter +fnn-config-record-bytes+ 1)
(defparameter +fnn-export-chunk+ 1)
(defvar *manifest* nil)
(defvar *closes* 0)
(defvar *reads* 0)
(defvar *close-failure* nil)
(defun fnn-err (&rest args) (declare (ignore args)))
(defun fnn-refuse (&rest args) (error (apply #'format nil args)))
(defun fnn-fault (&rest args) (error (apply #'format nil args)))
(defun fnn-join (&rest args) (declare (ignore args)) *manifest*)
(defun fnn-check-regular (path) (declare (ignore path)) t)
(defun fnn-archive-entry (&rest args) (declare (ignore args)) nil)
(defun fnn-archive-read-dir (&rest args) (declare (ignore args)) nil)
(defun fnn-octet-list (octets) octets)
(defun fnn-open (path flags)
  ;; Fail the baseline precondition rather than hanging the test runner on
  ;; its subsequent real FIFO case.  Patched source still exercises real I/O.
  (when (zerop (logand flags sb-posix:o-nonblock)) (error "manifest-open-can-block"))
  (sb-posix:open path flags))
(defun fnn-fstat (fd) (sb-posix:fstat fd))
(defun fnn-regular-p (info) (sb-posix:s-isreg (sb-posix:stat-mode info)))
(defun fnn-close (fd)
  (incf *closes*) (sb-posix:close fd)
  (when *close-failure* (error "close-fault")))
(defun fnn-read-up-to (&rest args) (declare (ignore args)) (incf *reads*) nil)
(defun fnn-core (name &rest args)
  (declare (ignore args))
  (case name (fn-sxd-archive-verdict :read)
    (fn-sxi-head (cons nil nil)) (fn-sxi-final '(:import :profile))
    (otherwise nil)))
(eval (source-definition (or (sb-ext:posix-getenv "FN_CLEANUP_HOST_SOURCE") "host/native/io.lisp")
                         "defmacro" "fnn-unwind-cleanups"))
(eval (source-definition (or (sb-ext:posix-getenv "FN_IMPORT_HOST_SOURCE") "host/native/io.lisp")
                         "defun" "fnn-import-pass"))
(let ((directory (sb-posix:mkdtemp "/tmp/fn-import-manifest-XXXXXX")))
  (unwind-protect
       (dolist (mode '(:regular :fifo :fifo-and-close-fault))
         (let* ((*manifest* (concatenate 'string directory "/MANIFEST"))
                (*closes* 0) (*reads* 0) (*close-failure* (eq mode :fifo-and-close-fault)))
           (if (eq mode :regular)
               (with-open-file (stream *manifest* :direction :output :if-exists :supersede) (declare (ignore stream)))
             (sb-posix:mkfifo *manifest* #o600))
           (let ((answer (handler-case (fnn-import-pass directory nil nil)
                           (error (e) (princ-to-string e)))))
             (assert (= *closes* 1))
             (if (eq mode :regular)
                 (progn (assert (equal answer '(:import :profile))) (assert (= *reads* 2)))
               (progn (assert (search "archive-incomplete entry=MANIFEST" answer))
                      (assert (= *reads* 0)))))
           (sb-posix:unlink *manifest*)))
    (let ((manifest (concatenate 'string directory "/MANIFEST")))
      (when (probe-file manifest) (sb-posix:unlink manifest)))
    (sb-posix:rmdir directory)))
(format t "Import MANIFEST actual regular/FIFO ingress passed (3 paths)~%")
