(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(defvar *fnn-store-failed-open-custody* nil)
(defstruct fnn-store completion-pending log lock-fd fenced close-debt)
(defstruct fnn-log fd spare spare-close-debt)
(defconstant +fnn-lock-un+ 8)
(defvar *calls* nil)
(defvar *failures* nil)
(defvar *condition* (make-condition 'simple-error :format-control "physical close failed"))
(defun record-call (name)
  (push name *calls*) (when (member name *failures*) (error *condition*)))
(defun fnn-close (fd) (record-call fd))
(defun fnn-flock (&rest ignored) (declare (ignore ignored)) (record-call :unlock))
(defun fnn-lstat (&rest ignored) (declare (ignore ignored)) t)
(defun fnn-unlink (&rest ignored) (declare (ignore ignored)) (record-call :unlink))
(defun fnn-err (&rest ignored) (declare (ignore ignored)))
(with-open-file (input "host/native/io.lisp")
  (loop for form = (read input nil :eof) until (eq form :eof) do
    (when (and (consp form) (member (car form) '(defun defmacro))
               (member (second form) '(fnn-unwind-cleanups fnn-store-close fnn-log-discard-spare fnn-store-failed-open-close)))
      (eval form))))
(dolist (failure '(:spare :unlink :log :unlock :lock))
  (let* ((*calls* nil) (*failures* (list failure))
         (log (make-fnn-log :fd :log :spare '(0 "/unused" :spare)))
         (store (make-fnn-store :log log :lock-fd :lock)) (caught nil))
    (handler-case (fnn-store-close store) (error (e) (setq caught e)))
    (assert (eq caught *condition*))
    (assert (equal (reverse *calls*) '(:spare :unlink :log :unlock :lock)))
    (assert (fnn-store-fenced store))
    (when (member failure '(:spare :unlink))
      (assert (equal (first (fnn-log-spare-close-debt log)) '(0 "/unused" :spare))))
    (assert (equal (fnn-store-close-debt store) (list log :lock *condition*)))
    (let ((*calls* nil))
      (handler-case (fnn-store-close store) (error (e) (assert (eq e *condition*))))
      (assert (null *calls*)))))
;; Normal values, handled body condition, and nonlocal exit remain distinct.
(assert (equal (multiple-value-list (fnn-unwind-cleanups ((values 1 2)) nil)) '(1 2)))
(let ((*calls* nil) (*failures* '(:a)))
  (assert (eq (catch 'escape (fnn-unwind-cleanups ((throw 'escape :body))
                              (record-call :a) (record-call :b))) :body))
  (assert (equal (reverse *calls*) '(:a :b))))
(let ((*failures* '(:a)) (caught nil))
  (handler-case
      (fnn-unwind-cleanups ((handler-case (error "handled") (error () :ok)))
        (record-call :a))
    (error (e) (setq caught e)))
  (assert (eq caught *condition*)))
(format t "PASS actual Store close: all physical cleanup attempted; uncertainty sticky; macro values/throw/handled error.~%")

(let* ((store (make-fnn-store :lock-fd :lock)) (*failures* '(:lock))
       (primary (make-condition 'simple-error :format-control "recovery failed"))
       (retained nil) (caught nil))
  (let ((*fnn-store-failed-open-custody* (lambda (actual) (setq retained actual))))
    (handler-case (fnn-store-failed-open-close store primary) (error (e) (setq caught e))))
  (assert (eq caught primary)) (assert (eq retained store))
  (assert (fnn-store-close-debt store)))
(format t "PASS failed-open close conveys actual Store debt before primary escape.~%")
