;;; Actual owner loan/close functions over recording physical and typed leaves.
;;; This checks native ordering; it is not typed/controller equivalence evidence.
(load "tests/native_output_response_lease_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-mux-after (loop conn after)
  (declare (ignorable loop conn after))
  (harness-stub-reached 'fnn-mux-after "host/native/mux.lisp"))
(defun fnn-mux-await (loop conn step redeem after)
  (declare (ignorable loop conn step redeem after))
  (harness-stub-reached 'fnn-mux-await "host/native/mux.lisp"))
(defun fnn-mux-plan-cold (loop conn plan after read)
  (declare (ignorable loop conn plan after read))
  (harness-stub-reached 'fnn-mux-plan-cold "host/native/mux.lisp"))
(defun fnn-mux-plan-yield (loop conn plan after &optional empty-progressp)
  (declare (ignorable loop conn plan after empty-progressp))
  (harness-stub-reached 'fnn-mux-plan-yield "host/native/mux.lisp"))
(defun fnn-mux-queue (loop conn octets op after &optional end)
  (declare (ignorable loop conn octets op after end))
  (harness-stub-reached 'fnn-mux-queue "host/native/mux.lisp"))
(defun fnn-now ()
  (harness-stub-reached 'fnn-now "host/native/io.lisp"))
(defun fnn-owner-chunk-results (service cid incoming socket class peerp results cold-since)
  (declare (ignorable service cid incoming socket class peerp results cold-since))
  (harness-stub-reached 'fnn-owner-chunk-results "host/native/owner.lisp"))
(defun fnn-owner-handle-chunk-read (service cid incoming socket class &optional peerp)
  (declare (ignorable service cid incoming socket class peerp))
  (harness-stub-reached 'fnn-owner-handle-chunk-read "host/native/owner.lisp"))
(defun fnn-owner-monotonic-ms ()
  (harness-stub-reached 'fnn-owner-monotonic-ms "host/native/owner.lisp"))
(defun fnn-owner-peer-read-class (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-peer-read-class "host/native/owner.lisp"))
(defun fnn-owner-resource-unavailable-line (service cid incoming word class)
  (declare (ignorable service cid incoming word class))
  (harness-stub-reached 'fnn-owner-resource-unavailable-line "host/native/owner.lisp"))
(defun fnn-owner-response-identity (service connection class)
  (declare (ignorable service connection class))
  (harness-stub-reached 'fnn-owner-response-identity "host/native/owner.lisp"))
(defun fnn-owner-syncer-physical (service grant receipt)
  (declare (ignorable service grant receipt))
  (harness-stub-reached 'fnn-owner-syncer-physical "host/native/owner.lisp"))
(defun fnn-owner-unavailable-line (service cid incoming since now limit class)
  (declare (ignorable service cid incoming since now limit class))
  (harness-stub-reached 'fnn-owner-unavailable-line "host/native/owner.lisp"))
(defun fnn-tls-consume-plaintext (fd expected seconds)
  (declare (ignorable fd expected seconds))
  (harness-stub-reached 'fnn-tls-consume-plaintext "host/native/tls.lisp"))
;;; ---- derived stubs: END ----
(load-deployed-forms "host/native/extent.lisp"
 '((defvar *fnn-extent-lock*) (defvar *fnn-extent-window-mode*)
   (defvar *fnn-extent-window-worker*) (defvar *fnn-extent-window-token*)))
(load-deployed-forms "host/native/owner.lisp"
 '((defun fnn-owner-window-activation) (defun fnn-owner-cold-remove-locked)
   (defun fnn-owner-cold-window-result-locked) (defun fnn-owner-response-window-close)))
(defvar *window-returned* nil)
(defvar *window-word* :ready)
(defvar *window-effects* nil)
(defvar *window-release-word* :released)
(defun fnn-extent-pool-funded-p () t)
(defun fnn-extent-executor-returned-p (worker) (declare (ignore worker)) *window-returned*)
(defun fnn-extent-window-outcome (worker token) (declare (ignore worker token)) *window-word*)
(defun fnn-extent-window-cancel (worker token)
  (push (list :cancel worker token) *window-effects*)
  (setq *window-word* :cancelled) :cancelled)
(defun fnn-extent-window-settle-cancelled (worker token)
  (push (list :release worker token) *window-effects*) *window-release-word*)
(defun fnn-extent-window-release (worker token)
  (push (list :release worker token) *window-effects*) *window-release-word*)
(defun fnn-owner-output-observe-returned (service read) (declare (ignore service read)))
(defun fnn-owner-output-dependency-consumed (service read)
  (declare (ignore service read)) (push :consumed *window-effects*))
(defun fnn-owner-release-pending-extents-locked (service) (declare (ignore service)))
(defun window-case (returned)
  (let* ((service (%make-fnn-owner-service :lock (sb-thread:make-mutex)))
         (read (%make-fnn-owner-cold-read :windowp t :worker :worker :token :token :queuedp t))
         (capture (%make-fnn-response-capture :window-read read))
         (*window-returned* returned) (*window-word* :ready) (*window-effects* nil))
    (setf (fnn-owner-service-cold-head service) read (fnn-owner-service-cold-tail service) read)
    (when returned
      (check (fnn-owner-cold-window-result-locked service read) "ready scalar loan")
      (check (and (fnn-owner-cold-read-borrowedp read) (not (fnn-owner-cold-read-settledp read))
                  (null *window-effects*)) "physical return alone retains scalar charge")
      (let ((*fnn-response-capture* capture))
        (fnn-owner-window-activation
         (lambda () (check (and *fnn-extent-window-mode*
                                (eq *fnn-extent-window-worker* :worker)
                                (eq *fnn-extent-window-token* :token)) "exact captured scalar borrow")))))
    (check (eq (fnn-owner-response-window-close service capture) :window-closed) "whole-response close")
    (unless returned
      (check (and (not (fnn-owner-cold-read-settledp read))
                  (eq (fnn-owner-service-cold-head service) read)
                  (= 1 (length *window-effects*))) "close before physical return preserves charge and roster")
      (setq *window-returned* t)
      (check (fnn-owner-cold-window-result-locked service read) "late actual return settles cancelled loan"))
    (check (and (fnn-owner-cold-read-settledp read) (null (fnn-owner-service-cold-head service))
                (= 1 (count :consumed *window-effects*))
                (= 1 (count :release *window-effects* :key (lambda (x) (if (consp x) (car x) x)))))
           "one release only after terminal last borrow")
    (let ((before (copy-list *window-effects*)))
      (fnn-owner-response-window-close service capture)
      (fnn-owner-cold-window-result-locked service read)
      (check (equal before *window-effects*) "duplicate close/reap never releases twice"))))
(window-case t)
(window-case nil)
(let* ((service (%make-fnn-owner-service :lock (sb-thread:make-mutex)))
       (read (%make-fnn-owner-cold-read :windowp t :worker :worker :token :token :abandonedp t))
       (*window-returned* t) (*window-word* :cancelled) (*window-release-word* :stale-job))
  (check (handler-case (progn (fnn-owner-cold-window-result-locked service read) nil) (serious-condition () t))
         "refused release faults")
  (check (and (not (fnn-owner-cold-read-settledp read)) (eq (fnn-owner-cold-read-worker read) :worker))
         "missing release receipt retains exact custody"))
(format t "native_response_window_raw: PASS ready borrow/close-held/late return/duplicate/refused release~%")
