;;; Deployed-function transport witness for the local owner command adapter.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")

(defvar *calls* nil)
(defvar *proposal* nil)
(defvar *position* '(:position (1 2)))
(defun fnn-owner-serialized (service cid thunk)
  (declare (ignore service cid)) (funcall thunk))
(defun fnn-owner-core (name &rest args)
  (push (cons name args) *calls*)
  (case name
    (fn-owner-consumer-local-position *position*)
    (fn-cp-cursor-encode '(1 2))
    (otherwise *proposal*)))
(defun fnn-core (name &rest args)
  (apply #'fnn-owner-core name args))
(defun fnn-owner-consumer-commit (service event)
  (declare (ignore service)) (push (list :commit event) *calls*) :durable)
(defun fnn-octet-list-p (x)
  (and (listp x) (every (lambda (o) (and (integerp o) (<= 0 o 255))) x)))
(defun fnn-fault (&rest args) (error "native fault: ~s" args))

(let ((found nil))
  (with-open-file (stream "host/native/owner.lisp")
    (loop for form = (read stream nil :eof)
          until (eq form :eof)
          when (and (consp form) (eq (car form) 'defun)
                    (eq (cadr form) 'fnn-owner-consumer-local-serialized))
            do (eval form) (setf found t)))
  (unless found (error "deployed local consumer function missing")))

(defun check (condition description)
  (unless condition (error "~a" description)))

(setf *proposal* '(:write (:consumer :exact-event)) *calls* nil)
(check (equal (fnn-owner-consumer-local-serialized :service :register '(7) '(8))
              '(:consumer-reply :accepted (1 2)))
       "register did not return committed position")
(check (equal (reverse *calls*)
              '((fn-owner-consumer-local-register (7) (8))
                (:commit (:consumer :exact-event))
                (fn-owner-consumer-local-position (7))))
       "register bypassed ACL2 proposal, exact event or position")

(setf *proposal* '(:write (:consumer :ack-event)) *calls* nil)
(check (equal (fnn-owner-consumer-local-serialized :service :ack '(9) nil)
              '(:consumer-reply :accepted (9)))
       "ack did not return accepted token")
(check (equal (reverse *calls*)
              '((fn-owner-consumer-local-ack (9))
                (:commit (:consumer :ack-event))))
       "ack did not publish exact ACL2 event")

(setf *proposal* '(:no-op :cursor) *calls* nil)
(check (equal (fnn-owner-consumer-local-serialized :service :ack '(9) nil)
              '(:consumer-reply :accepted (1 2)))
       "equal ack did not reuse ACL2 cursor encoding")
(check (not (member :commit *calls* :key #'car))
       "idempotent ack wrote a second event")

(setf *proposal* '(:refused :scope) *calls* nil)
(check (equal (fnn-owner-consumer-local-serialized :service :ack '(9) nil)
              '(:consumer-reply :refused nil))
       "scope refusal was not preserved")
(check (not (member :commit *calls* :key #'car))
       "scope refusal wrote an event")

(setf *calls* nil)
(check (equal (fnn-owner-consumer-local-serialized :service :position '(7) nil)
              '(:consumer-reply :accepted (1 2)))
       "position did not return ACL2 recorded token")
(check (not (member :commit *calls* :key #'car))
       "position performed a write")
(format t "native owner consumer local boundary passed~%")
