;;; PKT-897: actual owner adapter bodies at the publication/settlement boundary.
;;; Publisher/staging outcomes are injected; charge and handshake release
;;; are the deployed ACL2 bodies. No persistence or native allocator claim.
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(load "tests/native_io_prelude.lisp")
(defun natp (x) (and (integerp x) (<= 0 x)))
(defun posp (x) (and (integerp x) (< 0 x)))
(defun nfix (x) (if (natp x) x 0))
(defun len (x) (length x))
(defun true-listp (x) (if (consp x) (true-listp (cdr x)) (null x)))
(defun true-list-fix (x) (if (consp x) (cons (car x) (true-list-fix (cdr x))) nil))
(defmacro mv-let (vars call &body body) `(multiple-value-bind ,vars ,call ,@body))
(defmacro value (x) `(values nil ,x state))
(defun boundp-global (key state) (nth-value 1 (gethash key state)))
(defun f-get-global (key state) (gethash key state))
(defun f-put-global (key val state) (setf (gethash key state) val) state)
(book-defuns "books/config.lisp"
 '(fn-cfg-ag-car fn-cfg-ag-cdr fn-cfg-row-a fn-cfg-row-n fn-cfg-limit-value
   fn-cfg-row-lookup fn-cfg-limits fn-cfg-limit fn-cfg-generation fn-cfg-value))
(book-defuns "books/connection-budget.lisp"
 '(fn-cbud-handshake-slots fn-cbud-config-handshake-slots fn-cbud-run-held fn-cbud-held-at fn-cbud-live-held))
(book-defuns "books/tls-handshake-decision.lisp"
 '(fn-hsb-at fn-hsb-make fn-hsb-next fn-hsb-tick fn-hsb-started fn-hsb-flight
   fn-hsb-waiting fn-hsb-buckets fn-hsb-initial fn-hsb-remove fn-hsb-done))
(defvar *charge-refusal* nil)
(defvar *charge-verdict* nil)
(defvar *charge-next* nil)
(defvar *charge-stage-calls* 0)
(defun fn-owner-config (state) (gethash 'config state))
(defun fn-owner-ocfg (state) (gethash 'config state))
(defun fn-ocfg-config (oc) oc)
(defun fn-ocfg-owner (oc) (declare (ignore oc)) nil)
(defun fn-own-clock (own) (declare (ignore own)) nil)
(defun fn-cbud-deltas-refusal (&rest args) (declare (ignore args)) *charge-refusal*)
(defun fn-ores-config-refused (reason) (list :refused reason))
(defun fn-owner-reconfigure-deltas-admitted (id deltas fn-arena state)
  (declare (ignore id deltas fn-arena)) (incf *charge-stage-calls*)
  (value '(:refused :preflight)))
(defun fn-owner-authority-proposal-clear (state) state)
(defun fn-owner-served-post-bound (state) (declare (ignore state)) nil)
(defun fn-oclc-publish (&rest args) (declare (ignore args)) (values *charge-verdict* *charge-next*))
(defun fn-owner-install-ocfg (next state) (setf (gethash 'config state) next) state)
(book-defuns "host/owner-host.lisp"
 '(fn-owner-connection-held fn-owner-connection-held-refresh fn-owner-reconfigure-deltas
   fn-owner-reconfigure-complete fn-owner-handshake-state fn-owner-handshake-done))
(defun charge-config (slots)
  (list 1 (list nil nil nil nil nil nil (list (list "tls-handshakes-in-flight" nil nil slots)))))
(defun charge-check (ok text) (unless ok (error "~a" text)))
(let* ((state (make-hash-table))
       (held (fn-cbud-run-held 1 2 3 4 5 6 7 t 16)))
  (setf (gethash 'config state) (charge-config 16)
        (gethash 'fn-owner-connection-held state) held
        (gethash 'fn-owner-handshakes state)
        (fn-hsb-make 13 0 0 (loop for i from 1 to 12 collect (cons i "source")) 0 nil))
  (let ((*charge-refusal* :memory))
    (fn-owner-reconfigure-deltas 1 '(4096) nil state)
    (charge-check (equal (fn-owner-connection-held state) held) "memory refusal changed live charge"))
  (fn-owner-reconfigure-deltas 1 '(4096) nil state)
  (charge-check (= *charge-stage-calls* 1) "staging refusal was not reached")
  (charge-check (equal (fn-owner-connection-held state) held) "preflight refusal ratcheted charge")
  (dolist (*charge-verdict* '(:refused :recovery-required))
    (let ((*charge-next* (charge-config 16)))
      (fn-owner-reconfigure-complete 1 state)
      (charge-check (equal (fn-owner-connection-held state) held) "nondurable completion changed charge")))
  (let ((*charge-verdict* :durable) (*charge-next* (charge-config 4)))
    (fn-owner-reconfigure-complete 2 state))
  (charge-check (= (nth 8 (fn-owner-connection-held state)) 12) "lowering released still-active handshake slots")
  (loop for i from 1 to 9 do (fn-owner-handshake-done i state))
  (charge-check (= (nth 8 (fn-owner-connection-held state)) 4) "settled excess slots were not released")
  (fn-owner-handshake-done 9 state)
  (charge-check (= (nth 8 (fn-owner-connection-held state)) 4) "duplicate done changed minimum charge")
  (let ((*charge-verdict* :durable) (*charge-next* (charge-config 32)))
    (fn-owner-reconfigure-complete 3 state))
  (charge-check (= (nth 8 (fn-owner-connection-held state)) 32) "published increase not charged"))
(format t "native_connection_charge_publication_and_settlement: PASS~%")
