; SCN-1098: actual host diagnostic bodies and actual ACL2 condition classifier.
; Deliberate core/I/O seams distinguish faults from known refusals; this is
; source execution, not saved-image qualification or real profile I/O.
(require :sb-posix)
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(declaim (declaration xargs))
(defmacro defconst (name value) `(defparameter ,name ,value))
(defmacro include-book (&rest args) (declare (ignore args)) nil)
(defmacro defthm (&rest args) (declare (ignore args)) nil)
(defmacro in-theory (&rest args) (declare (ignore args)) nil)
(defun member-equal (x xs) (member x xs :test #'equal))
(defun assoc-equal (x xs) (assoc x xs :test #'equal))
(load "books/outcome-class.lisp")
(load "books/failure-scope.lisp")

(defparameter *fnn-section-step* nil)
(defparameter *fnn-constants* nil)
(defparameter +fnn-exit-refused+ (fn-outcome-code :refused))
(defparameter *fnn-stdout* nil)
(defparameter *fault-at* nil)
(defparameter *condition-kind* nil)
(defparameter *initial-result* '(1 2 3))
(defparameter *constants-result* '(10 32 42 100 100 100 100 100 100 100))
(defparameter *native-action* :run)
(defparameter *result-status* :accepted)

(defun source-forms (path names &optional optional)
  (with-open-file (in path)
    (loop for form = (read in nil :eof) until (eq form :eof)
          when (and (consp form) (member (car form) '(defun define-condition deftype))
                    (member (second form) (append names optional)))
          do (progn (eval form)
                    (unless (eq (car form) 'deftype)
                      (setf names (remove (second form) names)))
                    (when (null names) (return)))
          finally (assert (null names)))))
(source-forms (or (second sb-ext:*posix-argv*) "host/native/io.lisp")
              '(fnn-store-error fnn-store-fault fnn-store-indeterminate
                fnn-store-open-refusal fnn-usage-error fnn-refuse fnn-fault
                fnn-condition-class fnn-exit-code-for fnn-octets fnn-octet-list
                fnn-octet-list-p fnn-make-octets fnn-string-octets
                fnn-bridge-config-initial fnn-constants)
              '(fnn-octets))
(source-forms (or (third sb-ext:*posix-argv*) "host/native/heap.lisp")
              '(fnn-heap-store-profile fnn-heap-operator-profile
                fnn-heap-command-profile fnn-command-heap)
              '(fnn-heap-profile-refusal))

(define-condition unlisted-profile-condition (fnn-store-error) ())
(defstruct fixture-store (config '(:recorded-profile)))
(defun make-fnn-store (root) (declare (ignore root)) (make-fixture-store))
(defun fnn-store-config (store) (fixture-store-config store))
(defun fnn-config-path (store) (declare (ignore store)) "/fixture/config.json")
(defun fnn-lstat (path) (declare (ignore path)) t)
(defun maybe-condition (entry)
  (when (eq entry *fault-at*)
    (if (eq *condition-kind* 'simple-error)
        (error "fixture unexpected host error")
      (error *condition-kind* :message "fixture condition"))))
(defun fnn-load-config (store) (declare (ignore store)) (maybe-condition 'store-profile))
(defun fnn-absolute (path) path)
(defun fnn-operator-argv-octets (words) words)
(defun fnn-operator-read-config (&rest args)
  (declare (ignore args)) (maybe-condition 'config-read) '(1))
(defun fnn-operator-run-at (&rest args)
  (declare (ignore args)) (maybe-condition 'operator-plan) :result)
(defun fnn-heap-init-request (&rest args) (declare (ignore args)) :request)
(defun fnn-owner-wall-milliseconds () (values 0 t))
(defun fnn-monotonic-ms () 0)
(defun fnn-heap-reservation (&rest args) args)
(defun fnn-out (control &rest args) (apply #'format *fnn-stdout* control args))
(defun fnn-core (entry &rest args)
  (declare (ignore args)) (maybe-condition entry)
  (case entry
    (fn-native-operator-host-preflight :preflight)
    (fn-native-operator-host-preflight-needs-config-path-p nil)
    (fn-native-operator-host-preflight-needs-config-p t)
    (fn-native-config-host-max-octets 8192)
    (fn-native-operator-host-result-store-root "/fixture")
    (fn-native-operator-host-result-status *result-status*)
    (fn-native-operator-host-result-native-action *native-action*)
    (fn-native-operator-host-result-init-profile '(:requested-profile))
    (fn-bs-profile-resolve '(:requested-profile))
    ((fn-heap-reserve-init-connections fn-heap-reserve-run-connections) 4)
    (fn-native-operator-host-result-run-max-connections 4)
    (fn-heap-operation-observes-p nil)
    (fn-native-operator-host-result-run-cold-resources '(:cold))
    (fn-native-operator-host-result-run-output-resources '(:output))
    (fn-heap-reserve-report-line "heap=fixture")
    (fn-heap-decision-exit-code 0)
    (fn-cfg-host-initial-octets-at *initial-result*)
    (fn-store-frame-constants *constants-result*)
    (otherwise nil)))

(defun command-outcome (thunk expected &optional output)
  (let* ((*fnn-stdout* (make-string-output-stream))
         (code (handler-case (funcall thunk)
                 (error (condition) (fnn-exit-code-for condition)))))
    (assert (= code expected))
    (assert (equal (get-output-stream-string *fnn-stdout*) (or output "")))))

; The actual outer heap consumer must produce no accepting line on faults.
(dolist (entry '(config-read operator-plan store-profile
                 fn-native-operator-host-result-run-cold-resources
                 fn-native-operator-host-result-run-output-resources))
  (dolist (kind '(fnn-store-fault fnn-store-indeterminate simple-error
                 unlisted-profile-condition))
    (let ((*fault-at* entry) (*condition-kind* kind))
      (command-outcome (lambda () (fnn-command-heap "--" '("operator" "CONFIG" "run")))
                       (if (eq kind 'fnn-store-indeterminate) 3 4))))
  (format t "heap ~a faults remain distinct~%" entry))
; The initializer's profile-resolve branch also propagates a core guard fault.
(let ((*native-action* :init) (*fault-at* 'fn-bs-profile-resolve)
      (*condition-kind* 'fnn-store-fault))
  (command-outcome (lambda () (fnn-command-heap "--" '("operator" "CONFIG" "init"))) 4))
; A recognized semantic refusal still falls back to the no-store command
; figure, so the real command can print its named refusal when it executes.
(let ((*fault-at* 'operator-plan) (*condition-kind* 'fnn-store-error))
  (command-outcome (lambda () (fnn-command-heap "--" '("operator" "CONFIG" "run"))) 0 "heap=fixture"))
(assert (equal (multiple-value-list (fnn-heap-operator-profile "CONFIG" '("run")))
               '((:recorded-profile) 4 :run nil (:cold) (:output) "/fixture")))

; Initial configuration keeps only the actual ACL2 named refusal (:bad).
(let ((*initial-result* :bad))
  (command-outcome (lambda () (fnn-bridge-config-initial '("fn.test"))) 1))
(dolist (malformed '(:unexpected (1 999) "not octets"))
  (let ((*initial-result* malformed))
    (command-outcome (lambda () (fnn-bridge-config-initial '("fn.test"))) 4)))
(assert (equalp (fnn-bridge-config-initial '("fn.test")) #(1 2 3)))

; Frame shape or widths are image/core faults, never an input refusal.
(dolist (constants '((10 31 42 100 100 100 100 100 100 100)
                     (11 32 42 100 100 100 100 100 100 100)
                     (10 32) (10 32 :bad 100 100 100 100 100 100 100)))
  (let ((*constants-result* constants) (*fnn-constants* nil))
    (command-outcome (lambda () (fnn-constants)) 4)))
(assert (= (cdr (assoc :trailer (fnn-constants))) 32))
(format t "SOURCE OPERATOR DIAGNOSTICS PASSED~%")
