;;; Actual pre-factory helpers, actual ACL2 admission/unpriced bodies and
;;; limited span retry. Wire preview/typed bank are recording boundaries.
;;; Positive tariff is injected ONLY to discriminate prefix consumption;
;;; the actual current tariff producer always refuses incomplete coverage.
(load "tests/native_output_response_lease_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-mux-after (loop conn after)
  (declare (ignorable loop conn after))
  (harness-stub-reached 'fnn-mux-after "host/native/mux.lisp"))
(defun fnn-mux-await (loop conn step redeem after)
  (declare (ignorable loop conn step redeem after))
  (harness-stub-reached 'fnn-mux-await "host/native/mux.lisp"))
(defun fnn-mux-plan-cold (loop conn plan after read)
  (declare (ignorable loop conn plan after read))
  (harness-stub-reached 'fnn-mux-plan-cold "host/native/mux.lisp"))
(defun fnn-mux-plan-yield (loop conn plan after &optional empty-progressp)
  (declare (ignorable loop conn plan after empty-progressp))
  (harness-stub-reached 'fnn-mux-plan-yield "host/native/mux.lisp"))
(defun fnn-mux-queue (loop conn octets op after &optional end)
  (declare (ignorable loop conn octets op after end))
  (harness-stub-reached 'fnn-mux-queue "host/native/mux.lisp"))
(defun fnn-now ()
  (harness-stub-reached 'fnn-now "host/native/io.lisp"))
(defun fnn-owner-chunk-results (service cid incoming socket class peerp results cold-since)
  (declare (ignorable service cid incoming socket class peerp results cold-since))
  (harness-stub-reached 'fnn-owner-chunk-results "host/native/owner.lisp"))
(defun fnn-owner-handle-chunk-read (service cid incoming socket class &optional peerp)
  (declare (ignorable service cid incoming socket class peerp))
  (harness-stub-reached 'fnn-owner-handle-chunk-read "host/native/owner.lisp"))
(defun fnn-owner-monotonic-ms ()
  (harness-stub-reached 'fnn-owner-monotonic-ms "host/native/owner.lisp"))
(defun fnn-owner-peer-read-class (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-peer-read-class "host/native/owner.lisp"))
(defun fnn-owner-resource-unavailable-line (service cid incoming word class)
  (declare (ignorable service cid incoming word class))
  (harness-stub-reached 'fnn-owner-resource-unavailable-line "host/native/owner.lisp"))
(defun fnn-owner-response-identity (service connection class)
  (declare (ignorable service connection class))
  (harness-stub-reached 'fnn-owner-response-identity "host/native/owner.lisp"))
(defun fnn-owner-syncer-physical (service grant receipt)
  (declare (ignorable service grant receipt))
  (harness-stub-reached 'fnn-owner-syncer-physical "host/native/owner.lisp"))
(defun fnn-owner-unavailable-line (service cid incoming since now limit class)
  (declare (ignorable service cid incoming since now limit class))
  (harness-stub-reached 'fnn-owner-unavailable-line "host/native/owner.lisp"))
(defun fnn-tls-consume-plaintext (fd expected seconds)
  (declare (ignorable fd expected seconds))
  (harness-stub-reached 'fnn-tls-consume-plaintext "host/native/tls.lisp"))
;;; ---- derived stubs: END ----
(defmacro mv (&rest xs) `(values ,@xs))
(defmacro mv-let (vars form &body body) `(multiple-value-bind ,vars ,form ,@body))
(defmacro value (x) `(values nil ,x state))
(defun natp (x) (and (integerp x) (<= 0 x)))
(defun zp (x) (not (and (integerp x) (< 0 x))))
(defun len (x) (length x))
(load-deployed-forms "books/response-identity.lisp"
 '((defun fn-rid-wordp) (defun fn-rid-reserve) (defun fn-rid-response)))
(load-deployed-forms "books/output-command-admission.lisp"
 '((defun fn-ocap-at) (defun fn-ocap-previewp) (defun fn-ocap-tariffp)
   (defun fn-ocap-admit-preview) (defun fn-ocap-unpriced-tariff)))
(load-deployed-forms "host/owner-host.lisp" '((defun fn-owner-output-tariff-preview)))
(load-deployed-forms "host/native/extent.lisp"
 '((defvar *fnn-extent-lock*) (defvar *fnn-extent-window-mode*)
   (defvar *fnn-extent-window-worker*) (defvar *fnn-extent-window-token*)
   (defun fnn-core-page-read-pool) (defun fnn-extent-pool-funded-p)))
(load-deployed-forms "host/native/owner.lisp"
 '((defun fnn-owner-window-activation) (defun fnn-owner-response-identity-locked) (defun fnn-owner-output-begin-locked)
   (defun fnn-owner-output-prefix-locked) (defun fnn-owner-chunk-span-no-io)))
(defvar *preflight-lease-call* (symbol-function 'fnn-call))
(defvar *preflight-preview* '(:preview 3 :newnews (actual-recorded-tokens)))
(defvar *preflight-injected-tariff* nil)
(defvar *preflight-events* nil)
(defvar *preflight-cold* nil)
(defvar *preflight-line-end* 3)
(defun fnn-call (subject &rest args)
  (case subject
    (fn-owner-page-read-direct-mode
     (check (equal args '(:recorded-live-pool)) "actual pool adapter retains its typed pool")
     (list :offline)) ; recording typed mode; no decoded admission in this prefix fixture
    (fn-rid-response (multiple-value-list (apply #'fn-rid-response args)))
    (fn-oct-line-end (list *preflight-line-end*))
    (otherwise (apply *preflight-lease-call* subject args))))
(defun fnn-core (subject &rest args)
  (case subject
    ((fn-ocap-at fn-ocap-admit-preview) (apply (symbol-function subject) args))
    (fn-rlo-capacity 1048576) ; recording typed installed projection
    (fn-rlo-drainedp (null (test-output-ledger-token (car args))))
    (otherwise (error "unexpected pure preflight subject ~s" subject))))
(defun fnn-owner-core (subject &rest args)
  (check (eq subject 'fn-owner-output-tariff-preview) "actual tariff producer subject")
  (push :tariff *preflight-events*)
  (or *preflight-injected-tariff*
      (nth-value 1 (apply #'fn-owner-output-tariff-preview (append args (list nil))))))
(defun fnn-core-buffer-state (subject &rest args)
  (case subject
    (fn-owner-output-preview
     (check (and *fnn-response-capture* (fnn-response-capture-grant *fnn-response-capture*))
            "issue returned and is published before preview allocation")
     (push :preview *preflight-events*) *preflight-preview*)
    (fn-owner-chunk-span
     (push (list :factory (third args)) *preflight-events*)
     (when *preflight-cold* (setq *preflight-cold* nil) (throw 'fnn-extent-cold (list :actual-entry)))
     :actual-step)
    (otherwise (error "unexpected live buffer subject ~s" subject))))
(defun fnn-live-page-read-pool () :recorded-live-pool)
(defun fnn-live-octets () :recorded-existing-buffer)
(defun fnn-extent-no-io-usable-p () t)
(defun preflight-holder () (%make-fnn-response-capture :connection '(:connection 7 11)))
;; Actual unpriced producer refuses BEFORE any response factory. Known draw
;; is discoverable through the holder even though the reader has escaped.
(let* ((s (lease-service)) (*fnn-response-capture* (preflight-holder))
       (*preflight-events* nil) (*preflight-injected-tariff* nil)
       (conn (%make-fnn-mux-conn :cid 7 :response-capture *fnn-response-capture*)))
  (fnn-owner-output-begin-locked s 7)
  (check (equal (nth-value 1 (fn-owner-output-tariff-preview 7 *preflight-preview* nil))
                '(:unpriced :newnews)) "actual program producer is explicit unpriced")
  (let ((condition nil))
    (handler-case (fnn-owner-output-prefix-locked s 7 #(1 2 3 4 5 6 7 8))
      (simple-error (c) (setq condition c)))
    (check (and condition (search "accounted output command refused" (format nil "~a" condition)))
           "actual unpriced admission is the named refusal cause"))
  (check (equal (reverse *preflight-events*) '(:preview :tariff)) "no factory on unknown tariff")
  (fnn-mux-capture-output-grant conn)
  (check (eq (fnn-mux-conn-output-grant conn) (fnn-response-capture-grant *fnn-response-capture*))
         "returned issuance survives rejected reader")
  (fnn-owner-output-close s (fnn-mux-conn-output-grant conn) :discarded)
  (check (fnn-owner-output-drained-p s) "affirmative no-child operation closure settles known draw"))
;; Injected positive price only checks the consumer prefix/retry mechanics;
;; it is NOT a produced full footprint or supported runtime profile.
(let* ((s (lease-service)) (*fnn-response-capture* (preflight-holder))
       (*preflight-events* nil) (*preflight-injected-tariff* '(:tariff :newnews 1024)))
  (fnn-owner-output-begin-locked s 7)
  (let ((end (fnn-owner-output-prefix-locked s 7 #(1 2 3 4 5 6 7 8))))
    (check (= end 3) "actual ACL2 admission returns first command prefix")
    (check (eq (fnn-owner-chunk-span-no-io 7 #(1 2 3 4 5 6 7 8) :sched end) :actual-step)
           "limited actual span returns original result")
    (check (equal (first *preflight-events*) '(:factory 3)) "unpriced second command never enters factory")
    (let ((*preflight-cold* t) (*preflight-line-end* 3) (*preflight-events* nil))
      (fnn-owner-chunk-span-no-io 7 #(1 2 3 4 5 6 7 8) :sched end)
      (check (equal *preflight-events* '((:factory 3) (:factory 3))) "cold retry keeps same funded prefix"))
    (let ((*preflight-cold* t) (*preflight-line-end* 8) (*preflight-events* nil))
      (let ((condition nil))
        (handler-case (fnn-owner-chunk-span-no-io 7 #(1 2 3 4 5 6 7 8) :sched end)
          (fnn-store-fault (c) (setq condition c)))
        (check (and condition (search "malformed line end" (format nil "~a" condition)))
               "invalid fallback end faults before dispatch"))
      (check (equal *preflight-events* '((:factory 3))) "no fallback factory beyond accepted prefix")))
  (fnn-owner-output-close s (fnn-response-capture-grant *fnn-response-capture*) :drained))
(let ((s (%make-fnn-owner-service :output-ledger nil)))
  (check (= (fnn-owner-output-prefix-locked s 7 #(1 2 3 4 5 6 7 8)) 8)
         "absent output policy preserves explicitly partial legacy prefix"))
(format t "native_output_preflight_raw: PASS actual unpriced producer/refusal/retained draw/accepted prefix/cold retry~%")
