;;; Actual guarded served NEWNEWS stream consumer in the retained source world.
(in-package "ACL2")
(fnmg-function 'fn-cur-shared-make)
(defparameter *fnmg-original-cur* (symbol-function 'fn-cur-make))
(defparameter *fnmg-shared-cur* (symbol-function 'fn-cur-shared-make))
(defparameter *fnmg-stream-step* (fnmg-function 'fn-nnw-stream-step))
(defparameter *fnmg-stream-live* (fnmg-function 'fn-nnw-meta-livep))
(defparameter *fnmg-stream-remaining* (fnmg-function 'fn-nnw-stream-remaining t))
(defparameter *fnmg-stream-source* (fnmg-function 'fn-nnw-group-source))
(defparameter *fnmg-stream-start* (fnmg-function 'fn-nnw-stream-scan-cursor))
(defparameter *fnmg-cur* (fnmg-function 'fn-cur-make))
(defparameter *fnmg-article* (fnmg-function 'fn-make-article))
(defparameter *fnmg-diagnostic-max-transitions* 16384)

(defmacro fnmg-with-consumer-route ((route) &body body)
  (let ((cur (gensym "CUR")) (choice (gensym "ROUTE")))
    `(let ((,cur (symbol-function 'fn-cur-make)) (,choice ,route))
       (unwind-protect
            (fnmg-with-constructor-route ((if (eq ,choice :legacy) :legacy :shared))
              (setf (symbol-function 'fn-cur-make)
                    (if (eq ,choice :shared) *fnmg-shared-cur* *fnmg-original-cur*))
              ,@body)
         (setf (symbol-function 'fn-cur-make) ,cur)))))

(defun fnmg-stream-drain (initial)
  (let ((cur initial) (transitions 0))
    (loop while (funcall *fnmg-stream-live* cur) do
      ;; A diagnostic guard against a bad fixture/terminal interpretation,
      ;; never a production ceiling or a semantic input refusal.
      (assert (< transitions *fnmg-diagnostic-max-transitions*))
      (incf transitions)
      (multiple-value-bind (octets next spent phase)
          (funcall *fnmg-stream-step* cur 1 1 nil nil)
        (declare (ignore octets spent phase))
        (setf cur next)))))

(defun fnmg-newnews-case (id text)
  (let* ((parsed (funcall *fnmg-parse* (funcall *fnmg-octets* "*")))
         (patterns (funcall *fnmg-result-value* parsed))
         (article (funcall *fnmg-article* "<probe@x>" '(13 10 13 10 65)
                           (list text) (list (cons text 1)) 1 5))
         (source (funcall *fnmg-stream-source* patterns (list text)))
         (progress (funcall *fnmg-stream-start* source 0 (list article) 7 t))
         (context '(:snapshot :probe-root :configuration :probe-config))
         (old (fnmg-with-consumer-route (:legacy)
                (funcall *fnmg-cur* context progress nil nil)))
         (new (fnmg-with-consumer-route (:shared)
                (funcall *fnmg-cur* context progress nil nil)))
         (old-start old) (new-start new)
         (expected (funcall *fnmg-stream-remaining* old nil nil))
         (got nil) (steps 0) (visits 0))
    (loop while (funcall *fnmg-stream-live* old) do
      (assert (< steps *fnmg-diagnostic-max-transitions*))
      (assert (equal old new))
      (let ((a (fnmg-with-consumer-route (:legacy)
                 (multiple-value-list (funcall *fnmg-stream-step* old 1 1 nil nil))))
            (b (fnmg-with-consumer-route (:shared)
                 (multiple-value-list (funcall *fnmg-stream-step* new 1 1 nil nil)))))
        (assert (equal a b))
        (assert (<= (third a) 1))
        (dolist (byte (first a)) (push byte got))
        (incf visits (third a)) (incf steps)
        (setf old (second a) new (second b))))
    ;; The shell preserves context even at completion. Its actual live
    ;; predicate, rather than Lisp NIL, owns completion of this stream.
    (assert (not (funcall *fnmg-stream-live* new)))
    (assert (equal old new))
    (assert (equal (nreverse got) expected))
    (format t "~%FN_NEWNEWS_OPT {\"type\":\"case\",\"case_id\":~d,\"input_octets\":~d,\"steps\":~d,\"entry_visits\":~d,\"output_octets\":~d,\"equal_every_step_and_reply\":true,\"allocation_replays\":32}~%"
            id (length text) steps visits (length expected))
    (dolist (route '(:legacy :matcher-only :shared))
      (fnmg-with-consumer-route (route)
        (let ((initial (if (eq route :shared) new-start old-start)))
          (dotimes (i 4) (fnmg-stream-drain initial))
          (sb-ext:gc :full t)
          (fnn-trace-span (route :operation id)
            (dotimes (i 32) (fnmg-stream-drain initial))))))))

(fnn-trace-start :capacity 16 :allocation :isolated-process)
(unwind-protect
    (progn
      (fnmg-newnews-case 1 "fn.test")
      (fnmg-newnews-case 2 (make-string 460 :initial-element #\a))
      (fnn-trace-report *standard-output*)
      (format t "NATIVE_IMMUTABLE_NEWNEWS_PASS~%"))
  (setf *fnn-trace-state* nil)
  (assert (eq (symbol-function 'fn-cur-make) *fnmg-original-cur*))
  (assert (eq (symbol-function 'fn-wmc-node) *fnmg-original-node*))
  (assert (eq (symbol-function 'fn-wmc-state) *fnmg-original-state*)))
