;; Installed native builder control flow, with recorded ACL2 semantic seams.
;; The row/commit semantics themselves are proved/exercised by ACL2 teeth.
(require :sb-posix)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(defvar *fnn-checkpoint-image-custody* nil)
(defvar *fnn-checkpoint-stop-test* nil)
(defvar *fixture-sources* nil)
(defvar *fixture-rows* nil)
(defvar *fixture-fail-row* nil)
(defvar *fixture-yields* nil)
(defvar *fixture-binding-count* nil)
(defvar *fixture-release* nil)
(defvar *fixture-page-phase* 0)
(defvar *fixture-grows* 0)
(defun fnn-core (name &rest args)
  (case name
    (create-fn-hrecs$c
     (let ((instance (vector nil nil))) (push instance *fixture-sources*) instance))
    (fn-his-build-source-count (length (first args)))
    (fn-his-build-yieldp (push (first args) *fixture-yields*) (zerop (mod (first args) 256)))
    (fn-his-binding (setf *fixture-binding-count* (third args)) (list :binding (third args)))
    (fn-his-np 7)
    (otherwise (error "unexpected core dispatch ~s" name))))
(defun fnn-call (name &rest args)
  (case name
    (fn-his-build-begin (setf (aref (second args) 0) nil) (list (second args)))
    (fn-his-row-begin
      (if (equal (first args) *fixture-fail-row*)
          (list '(:refused :codec) nil (second args))
        (progn (setf (aref (second args) 1) (first args))
               (list :yield '(:append) (second args)))))
    (fn-his-row-step
      (let* ((snapshot (second args)) (ev (aref snapshot 1)))
        (cond ((and (eq ev :pages) (= *fixture-page-phase* 0))
               (setf *fixture-page-phase* 1)
               (list :yield '(:relocate :cursor) snapshot))
              ((and (eq ev :pages) (= *fixture-page-phase* 1))
               (list '(:grow-image 9) '(:relocate :cursor) snapshot))
              (t (push ev *fixture-rows*)
                 (push ev (aref snapshot 0))
                 (list :done nil snapshot)))))
    (fn-his-row-grow
      (incf *fixture-grows*) (setf *fixture-page-phase* 2)
      (list :yield '(:relocate :cursor) (second args)))
    (fn-his-build-finish
      (let* ((snapshot (second args)) (count (length (aref snapshot 0))))
        (unless (= count (first args)) (error "source count mismatch"))
        (list :ok :root '((1 0 0)) count snapshot)))
    (fn-his-release (push (first args) *fixture-release*) (list (first args)))
    (otherwise (error "unexpected call dispatch ~s" name))))
(defun fnn-refuse-io (format-string &rest args) (error (apply #'format nil format-string args)))
(defun fnn-fault (format-string &rest args) (error (apply #'format nil format-string args)))
(defun fixture-load (path names)
  (with-open-file (in path)
    (loop for form = (read in nil :eof) until (eq form :eof) do
      (when (and (consp form) (member (car form) '(defun defmacro))
                 (member (second form) names))
        (eval form)
        (setf names (remove (second form) names))
        (when (null names) (return))))))
(fixture-load "host/native/io.lisp"
 '(fnn-checkpoint-yield fnn-history-image-row-run fnn-history-image-build
   fnn-history-image-release fnn-with-history-image))
(let ((events (loop for i below 513 collect (list :all-event i))))
  (fnn-with-history-image
    (multiple-value-bind (position image)
        (fnn-history-image-build events :node 0 '(4 :trail))
      (assert (equal (first position) 4))
      (assert (equal (second position) :trail))
      (assert (equal (third position) '(:binding 513)))
      (assert (equal image '(7 ((1 0 0)))))
      (assert (= *fixture-binding-count* 513))
      (assert (equal (reverse *fixture-rows*) events))
      (assert (= (length *fixture-yields*) 513))))
  (assert (null *fnn-checkpoint-image-custody*))
  (assert (= (length *fixture-release*) 1))
  ;; A new publisher receives another private instance; its empty begin can
  ;; never erase the first snapshot during a yield.
  (let ((first (first *fixture-sources*)))
    (fnn-with-history-image (fnn-history-image-build '((:config 1)) :node 0 '(5 :trail2)))
    (assert (not (eq first (first *fixture-sources*))))
    (assert (= (length (aref first 0)) 513))))
;; Failure is terminal for this build and its owned scratch is returned.
(let ((*fixture-fail-row* :bad) (*fixture-rows* nil) (failed nil))
  (handler-case
      (fnn-with-history-image (fnn-history-image-build '(:first :bad :unreached) :node 0 '(6 :trail3)))
    (error () (setf failed t)))
  (assert failed)
  (assert (equal *fixture-rows* '(:first)))
  (assert (null *fnn-checkpoint-image-custody*)))
;; The owner's existing stop fence is observed before the first row and at
;; the next ACL2 scheduling cadence. Neither cut reaches finish/binding;
;; unwind returns its private scratch just as any pre-stage refusal does.
(dolist (cut '(0 256))
  (let* ((*fixture-rows* nil) (*fixture-binding-count* nil)
         (*fnn-checkpoint-stop-test* (lambda () (>= (length *fixture-rows*) cut)))
         (failed nil) (released-before (length *fixture-release*)))
    (handler-case
        (fnn-with-history-image
          (fnn-history-image-build (loop for i below 513 collect i) :node 0 '(7 :trail4)))
      (error () (setf failed t)))
    (assert failed)
    (assert (= (length *fixture-rows*) cut))
    (assert (null *fixture-binding-count*))
    (assert (= (length *fixture-release*) (1+ released-before)))
    (assert (null *fnn-checkpoint-image-custody*))))
(let ((*fixture-rows* nil) (*fixture-page-phase* 0) (*fixture-grows* 0))
  (fnn-with-history-image (fnn-history-image-build '(:pages) :node 0 '(8 :trail5)))
  (assert (equal *fixture-rows* '(:pages)))
  (assert (= *fixture-grows* 1)))
(let* ((*fixture-rows* nil) (*fixture-page-phase* 0) (*fixture-grows* 0)
       (*fixture-binding-count* nil)
       (*fnn-checkpoint-stop-test* (lambda () (= *fixture-page-phase* 1)))
       (failed nil))
  (handler-case
      (fnn-with-history-image (fnn-history-image-build '(:pages :unreached) :node 0 '(9 :trail6)))
    (error () (setf failed t)))
  (assert failed)
  (assert (null *fixture-rows*))
  (assert (null *fixture-binding-count*))
  (assert (= *fixture-grows* 0))
  (assert (null *fnn-checkpoint-image-custody*)))
(format t "native_history_builder_raw: private snapshots, complete frontier, failure and stop return PASS~%")
