;;; Execute the actual phased wrapper and live-limit caller with ACL2's real
;;; fn-orp-step and event mapper. I/O and owner/pool entries are fixtures;
;;; this checks adapter order and mutex placement, not storage or ACL2 proofs.
(require :sb-posix)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(defmacro mv (&rest xs) `(list ,@xs))
(defmacro mv-let (vars form &body body) `(destructuring-bind ,vars ,form ,@body))
(defun true-list-fix (x) (if (consp x) (cons (car x) (true-list-fix (cdr x))) nil))
(defun load-defuns (path predicate)
  (with-open-file (s path)
    (loop for f = (read s nil :eof) until (eq f :eof) do
      (when (and (consp f) (eq (car f) 'defun) (funcall predicate (cadr f)))
        (eval (append (subseq f 0 3)
                      (remove-if (lambda (x) (and (consp x) (eq (car x) 'declare)))
                                 (cdddr f))))))))
(load-defuns "books/owner-reconfig-phased.lisp" (constantly t))
(load-defuns "books/limits-live.lisp"
             (lambda (x) (member x '(fn-lim-funded-after fn-lim-decision-appliedp))))
(assert (fn-lim-decision-appliedp '(:applied 257)))
(dolist (d '(nil :applied (:at-restart 257) (:refused :applied)))
  (assert (not (fn-lim-decision-appliedp d))))
(defvar *owner-lock* (sb-thread:make-mutex :name "fixture owner"))
(defvar *fnn-extent-lock* (sb-thread:make-mutex :name "fixture extent"))
(defmacro fnn-with-observed-mutex ((lock label) &body body)
  (declare (ignore label)) `(sb-thread:with-mutex (,lock) ,@body))
(defun heldp (lock) (eq (sb-thread:mutex-owner lock) sb-thread:*current-thread*))
(defun ownerp () (assert (heldp *owner-lock*)))
(defun offp () (assert (not (heldp *owner-lock*))) (assert (not (heldp *fnn-extent-lock*))))
(defun poolp () (ownerp) (assert (heldp *fnn-extent-lock*)))
(define-condition fnn-store-error (error) ((message :initarg :message)))
(define-condition fnn-store-fault (fnn-store-error) ())
(define-condition fnn-store-indeterminate (fnn-store-error) ())
(defun fnn-fault (&rest args) (error 'fnn-store-fault :message args))
(defun fnn-refuse (&rest args) (error 'fnn-store-error :message args))
(defun fnn-indeterminate (&rest args) (error 'fnn-store-indeterminate :message args))
(defvar *fnn-section-step* nil)
(defvar *events* nil)
(defvar *convert* :protected-growth-admitted)
(defvar *authorized* t)
(defvar *present* nil)
(defvar *valid-name* t)
(defvar *publication* :durable)
(defvar *decision* '(:applied 257))
(defvar *owner-value* 'captured-owner)
(defvar *profile* 'funded)
(defvar *hold* nil)
(defvar *captures* 0)
(defvar *authorizations* 0)
(defvar *observations* 0)
(defun fnn-core (name &rest args)
  (case name
    (fn-orp-convert-event (apply #'fn-orp-convert-event args))
    (fn-oclc-live-authorizep
     (ownerp) (assert (eq (first args) 'captured-owner)) *authorized*)
    (fn-olau-next-name (offp) (assert (eq (first args) 'captured-owner))
                      (and *valid-name* "00000002.cfg"))
    (fn-olau-authorize-observed
     (offp) (incf *authorizations*)
     (assert (equal args (list 'captured-owner '(1 2) t
                              (if *valid-name* (if *present* :present :absent) :unknown)
                              'funded)))
     (cond ((not *valid-name*) '(:fault :observation))
           (*present* '(:refused :occupied)) (t '(:accepted nil))))
    (fn-native-admin-host-publication-status (first (first args)))
    (fn-native-admin-host-publication-reason (second (first args)))
    (fn-lim-apply-row 'candidate)
    (fn-lim-funded-after (apply #'fn-lim-funded-after args))
    (fn-lim-protected-growth (if (eq (first args) 'candidate) 20 0))
    (fn-lim-pool-decision (first args))
    (fn-lim-article-decision (first args))
    (fn-lim-decision-status :accepted)
    (fn-lim-decision-appliedp (apply #'fn-lim-decision-appliedp args))
    (otherwise (error "unexpected core call ~s ~s" name args))))
(defun fnn-call (name &rest args)
  (assert (eq name 'fn-orp-step))
  (when (eq (first args) :converting)
    (ownerp) (push (list :converting (third args)) *events*))
  (apply #'fn-orp-step args))
(defun fnn-owner-core (name &rest args)
  (ownerp)
  (case name
    (fn-owner-cfg-capture (incf *captures*) *owner-value*)
    (fn-owner-feed-journal-prefix-size 8)
    (fn-owner-limit-carried (cons 'requested 'funded))
    (fn-owner-limit-use '(100 20000000 1))
    (fn-owner-limit-decided
     (poolp) (push :carry *events*)
     (fn-lim-funded-after (third args) 'funded 'candidate))
    (fn-owner-apply-limit-profile (poolp) (push :profile *events*) :installed)
    (otherwise (error "unexpected owner call ~s" name))))
(defun fnn-core-page-read-pool (name &rest args)
  (poolp)
  (case name
    (fn-owner-page-read-protected-growth-preview (list :affordable))
    (fn-owner-page-read-growth-reserve (push (cons :reserve args) *events*) (list :admitted :token))
    (fn-owner-page-read-growth-convert (push (cons :convert args) *events*) (list *convert*))
    (fn-owner-page-read-growth-release (push (cons :release args) *events*) (list :evicted))
    (otherwise (error "unexpected pool call ~s" name))))
(defun fnn-owner-action (name &rest args)
  (declare (ignore args)) (ownerp)
  (assert (eq name 'fn-owner-reconfigure-complete)) :durable)
(defun fnn-owner-service-store (s) s)
(defun fnn-store-config (s) (declare (ignore s)) *profile*)
(defun (setf fnn-store-config) (v s) (declare (ignore s)) (setf *profile* v))
(defun fnn-admin-lock-observation (s) (declare (ignore s)) (ownerp) t)
(defun fnn-octet-list (x) x)
(defun fnn-nat (x) x)
(defun fnn-config-dir (s) (declare (ignore s)) "cfg")
(defun fnn-join (a b) (declare (ignore a)) b)
(defun fnn-lstat (path)
  (offp) (assert *hold*) (incf *observations*)
  (assert (equal path "00000002.cfg"))
  ;; A reader changed the live owner after capture. Authorization must still
  ;; receive the old value, and the profile captured with it.
  (setq *owner-value* 'reader-owner *profile* 'reader-profile)
  *present*)
(defun fnn-admin-publish-effect (&rest args)
  (declare (ignore args)) (offp) (assert *hold*) (push :publish *events*)
  (values *publication* 2 "00000002.cfg"))
(defun fnn-immutable-drain-cleanups () (offp))
(defun fnn-owner-refresh-config-cache (&rest args) (declare (ignore args)) (ownerp))
(defun fnn-owner-feed-configured-missing (&rest args) (declare (ignore args)) (ownerp) nil)
(defun fnn-owner-feed-install (&rest args) (declare (ignore args)) (ownerp) (push :install *events*))
(defun fnn-owner-feed-close-entries (entries) (assert (null entries)))
(defun fnn-owner-reconfigure-unstage () (ownerp) (push :unstage *events*))
(defun fnn-owner-reconfig-hold (service entry)
  (declare (ignore service)) (ownerp)
  (case entry (:begin (assert (not *hold*)) (setq *hold* t) :held)
              (:end (assert *hold*) (setq *hold* nil) :released)))
(defun fnn-quantum-control (service cid thunk &optional class)
  (declare (ignore service cid class)) (sb-thread:with-mutex (*owner-lock*) (funcall thunk)))
(defun fnn-store-fenced (s) (declare (ignore s)) nil)
(defun (setf fnn-store-fenced) (v s) (declare (ignore s)) v)
(defun fnn-heap-image-observation () 'core)
(defun fnn-heap-observations () 'machine)
(defun fnn-heap-history-observation (&rest args) (declare (ignore args)) (offp) 'history)
(defun fnn-store-root (s) s)
(defun fnn-owner-monotonic-ms () 0)
(defun fnn-admin-test-fault (&rest args) (declare (ignore args)))
(defun fnn-gc-nursery-octets () 64)
(defun fnn-lim-plan-field (p) (declare (ignore p)) "max-transactions")
(defun fnn-lim-plan-n (p) (declare (ignore p)) 200)
(defun fnn-lim-decision (&rest args) (declare (ignore args)) *decision*)
(defun fnn-lim-line (&rest args) (declare (ignore args)) "line")
(defun fnn-lim-reason (d) (car d))
(defun fnn-err (&rest args) (declare (ignore args)))
(defconstant +fnn-gc-nursery-octets+ 64)
;; Load the wrapper's real struct, helpers and macro, and the real limit caller.
(with-open-file (s "host/native/admin.lisp")
  (loop for f = (read s nil :eof) until (eq f :eof) do
    (when (and (consp f)
               (or (and (eq (car f) 'defstruct) (eq (caadr f) 'fnn-reconfig))
                   (and (eq (car f) 'defmacro) (eq (cadr f) 'fnn-owner-live-reconfigure))
                   (and (eq (car f) 'defun)
                        (or (search "FNN-RC-" (symbol-name (cadr f)))
                            (eq (cadr f) 'fnn-owner-limit-serialized)))))
      (eval f))))
;; Stage data is a fixture; every phase/dispatch/helper after it is real.
(defun fnn-rc-do-stage (run stage)
  (declare (ignore stage)) (ownerp) (setf (fnn-rc-record run) '(1 2)) :staged)
(defun exercise (&key (convert :protected-growth-admitted) (decision '(:applied 257))
                     (authorized t) present (valid-name t) (publication :durable)
                     expected (fault nil))
  (let ((*events* nil) (*hold* nil) (*convert* convert) (*decision* decision)
        (*authorized* authorized) (*present* present) (*valid-name* valid-name)
        (*publication* publication) (*owner-value* 'captured-owner) (*profile* 'funded)
        (*captures* 0) (*authorizations* 0) (*observations* 0))
    (let ((answer (handler-case (fnn-owner-limit-serialized 'store 'plan)
                    (fnn-store-fault () :fault))))
      (assert (if fault (eq answer :fault) (eq (second answer) (if (and authorized (not present)) :accepted :refused))))
      (assert (not *hold*))
      (assert (= *captures* 1))
      (assert (= *authorizations* (if authorized 1 0)))
      (assert (= *observations* (if (and authorized valid-name) 1 0)))
      (assert (equal (reverse *events*) expected)))))
(exercise :expected '((:reserve 20) :publish :install (:convert :token 20)
                      (:converting :converted) :carry :profile))
(exercise :decision '(:at-restart 257)
          :expected '((:reserve 0) :publish :install (:convert :token 0)
                      (:converting :converted) :carry))
(dolist (word '(:read-resources-unavailable :at-restart :unknown :converted nil))
  (exercise :convert word :fault t
            :expected '((:reserve 20) :publish :install (:convert :token 20)
                        (:converting :fault) (:release :token))))
(exercise :authorized nil :expected '(:unstage))
(exercise :present t :expected '((:reserve 20) (:release :token) :unstage))
(exercise :valid-name nil :fault t :expected '((:reserve 20)))
(format t "phased reconfiguration: 10 cases passed (capture, one observation, conversion, release, locks)~%")
