;;; `fn identity --frame CONTROL': the shipped adapter prints the reply frame
;;; its one exchange read, as hex, in place of ACL2's line, and exits by the
;;; same class; ACL2's plan ((:run CONTROL :frame), books/store-identity.lisp)
;;; says so.  Without the flag the line is printed and the frame is not.
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-control-transport-outcome (stage)
  (declare (ignorable stage))
  (harness-stub-reached 'fnn-control-transport-outcome "host/native/control-transport.lisp"))
;;; ---- derived stubs: END ----

(defvar *exchanges* 0)
(defvar *out* nil)
(defvar *plan* nil)
(defvar *frame* nil)
(defparameter +fnn-exit-usage+ 2)
(defun fnn-ascii-octet-list (s) (map 'list #'char-code s))
(defun fnn-octets (x) x)
(defun fnn-octet-list (x) (coerce x 'list))
(defun fnn-octets-string (x) (map 'string #'code-char x))
(defun fnn-hex (octets)
  (with-output-to-string (s)
    (map nil (lambda (o) (format s "~(~2,'0x~)" o)) octets)))
(defun fnn-core (name &rest args)
  (declare (ignorable args))
  (case name
    (fn-stid-host-cli-plan *plan*)
    (fn-stid-host-request '(1 2 3))
    (fn-stid-host-reply-read '(:accepted))
    (fn-stid-host-line (map 'list #'char-code "fn-store-identity-v1 line"))
    (fn-stid-host-exit-code 0)
    (fn-stid-host-usage "usage")
    (otherwise (error "unexpected ACL2 entry ~s" name))))
(defun fnn-control-exchange (path request &optional maximum seconds)
  (declare (ignore path request maximum seconds))
  (incf *exchanges*)
  (values *frame* :after-submission))
(defun fnn-out (fmt &rest args) (push (apply #'format nil fmt args) *out*))
(defun fnn-err (&rest args) (error "unexpected CLI refusal ~s" args))

(let ((found nil))
  (with-open-file (stream "host/native/store-identity.lisp")
    (loop for form = (read stream nil :eof)
          until (eq form :eof)
          when (and (consp form) (eq (car form) 'defun)
                    (eq (cadr form) 'fnn-command-store-identity))
            do (eval form) (setf found t)))
  (unless found (error "deployed identity adapter missing")))

(let ((*exchanges* 0) (*out* nil) (*plan* '(:run (47 99) :frame))
      (*frame* (make-array 6 :element-type '(unsigned-byte 8)
                             :initial-contents '(70 78 67 84 1 25))))
  (unless (eql (fnn-command-store-identity '("--frame" "/c")) 0) (error "exit"))
  (unless (equal (reverse *out*) (list "464e43540119"))
    (error "printed ~s, not the frame's hex" (reverse *out*)))
  (unless (= *exchanges* 1) (error "~d exchanges" *exchanges*)))
(format t "native store identity --frame boundary passed~%")

(let ((*exchanges* 0) (*out* nil) (*plan* '(:run (47 99)))
      (*frame* (make-array 6 :element-type '(unsigned-byte 8)
                             :initial-contents '(70 78 67 84 1 25))))
  (fnn-command-store-identity '("/c"))
  (unless (equal (reverse *out*) (list "fn-store-identity-v1 line"))
    (error "without --frame printed ~s" (reverse *out*))))
(format t "native store identity --frame absent boundary passed~%")
