(load "tests/native_immutable_close_source.lisp")
(in-package "ACL2")

(defun fnn-node-secret-ensure-directory (&rest args) (declare (ignore args)) "/root")
(defun fnn-node-secret-path (&rest args) (declare (ignore args)) "/root/key")
(defun fnn-node-secret-read-entry (&rest args) (declare (ignore args)) :current)
(defun fnn-node-secret-epoch-path (&rest args) (declare (ignore args)) "/root/old-key")
(defun fnn-lstat (&rest args) (declare (ignore args)) t)
(defun fnn-node-secret-same-file-p (&rest args) (declare (ignore args)) t)
(defun fnn-node-secret-identity (&rest args) (declare (ignore args)) :identity)
(defun fnn-node-secret-fresh-root () :fixture-seed)
(defun fnn-node-secret-render (&rest args) (declare (ignore args)) #(1))
(defun fnn-staging (&rest args) (declare (ignore args)) "/root/stage")
(defun fnn-join (&rest args) (declare (ignore args)) "/root/stage/key")
(defun fnn-random-hex (&rest args) (declare (ignore args)) "suffix")
(defun fnn-node-secret-durable (&rest args) (declare (ignore args)))
(defun fnn-core (name &rest args)
  (case name (fn-ns-entry-epoch (if (eq (first args) :current) 1 2))
    (fn-ns-rotate-entry :next) (otherwise (error "core ~a" name))))
(defun fnn-replace (&rest args) (declare (ignore args)) (setq *published* t))
(with-open-file (in "host/native/io.lisp")
 (loop for f = (read in nil :eof) until (eq f :eof) do
  (when (and (consp f) (eq (car f) 'defun) (eq (second f) 'fnn-node-secret-rotate)) (eval f))))
;; Fence dominates: an uncertain close under the body's fault escalates the escape;
;; the body's own condition is retained as its primary (body-primary-retained-p).
(dolist (fault '(:close :write-close :body-close nil))
  (let ((*fnn-immutable-close-debts* nil) (*publication-failure* fault)
        (*fnn-escape-cleanup-debts* (list nil))
        (*publication-calls* nil) (*published* nil) (caught nil) (epoch nil))
    (handler-case (setq epoch (fnn-node-secret-rotate (%make-fnn-store)))
      (error (e) (setq caught e)))
    (assert (= 1 (count '(:close 55) *publication-calls* :test #'equal)))
    (if fault
        (progn
          (assert caught) (assert (not *published*))
          (assert (member :unlink *publication-calls*))
          (assert (eq (fnn-immutable-close-observation) :uncertain))
          (assert (typep caught 'fnn-store-indeterminate))
          (when (eq fault :body-close) (assert (body-primary-retained-p))))
      (progn (assert (null caught)) (assert *published*) (assert (= epoch 2))))))
(format t "native node secret staged return source PASS~%")
