;;; SCN1137 actual guarded BP projection and actual heap profile consumer.
(require :sb-posix)
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-heap-command-profile-base (argv)
  (declare (ignorable argv))
  (harness-stub-reached 'fnn-heap-command-profile-base "host/native/heap.lisp"))
(defun fnn-peer-flight-profile (root)
  (declare (ignorable root))
  (harness-stub-reached 'fnn-peer-flight-profile "host/native/heap.lisp"))
;;; ---- derived stubs: END ----
(declaim (declaration xargs))
(defun posp (x) (and (integerp x) (< 0 x)))
(defun source-functions (path names)
 (with-open-file (in path)
  (loop for form = (read in nil :eof) until (eq form :eof)
   when (and (consp form) (eq (car form) 'defun) (member (second form) names))
   do (progn (eval form) (setf names (remove (second form) names)))
   finally (assert (null names)))))
(source-functions "books/bp-heap-command.lisp"
 '(fn-bph-decimal-characters fn-bph-connections fn-bph-command-plan fn-bph-refusal-line))
(defvar *events* nil)
(define-condition fixture-refused (error) ())
(defun fnn-core (name &rest args) (apply name args))
(defun fnn-absolute (root) (concatenate 'string "/captured/" root))
(defun fnn-heap-store-profile (root)
 (push (list :profile root) *events*) (list :profile root))
(defun fnn-refuse (&rest args) (declare (ignore args)) (error 'fixture-refused))
(source-functions "host/native/heap.lisp" '(fnn-heap-command-profile))
(dolist (entry
 '((("bp-node" "serve" "0" "journal" "store" "receipts" "workflow" "node" "peer" "dest" "policy" "issuer" "host" "4556") 1)
   (("bp-app" "receive" "0" "spool" "store" "receipts" "node" "peer" "dest" "policy" "issuer" "1" "02") 2)))
 (let ((*events* nil))
  (assert (equal (multiple-value-list (fnn-heap-command-profile (first entry)))
                 (list '(:profile "/captured/store") (second entry) :run nil nil nil "/captured/store")))
  (assert (equal *events* '((:profile "/captured/store"))))))
(dolist (argv
 '(("bp-node" "serve")
   ("bp-node" "serve" "0" "journal" "store")
   ("bp-app" "receive" "0" "spool" "store" "receipts" "node" "peer" "dest" "policy" "issuer" "1" "0")
   ("bp-app" "receive" "0" "spool" "store" "receipts" "node" "peer" "dest" "policy" "issuer" "1" "18446744073709551616")))
 (let ((*events* nil) (refused nil))
  (handler-case (fnn-heap-command-profile argv) (fixture-refused () (setq refused t)))
  (assert refused) (assert (null *events*))))
(let ((*events* nil))
 (assert (equal (multiple-value-list
                 (fnn-heap-command-profile '("bp-node" "dispatch" "journal" "store")))
                '(nil 0 nil nil)))
 (assert (null *events*)))
(format t "PASS actual BP heap source root and connection propagation~%")
