;;; Actual heap routing, profile capture and transport adapter. Physical
;;; liveness/transport are fixtures; the liveness decision is the real book.
(load "tests/native_operator_diagnostics_source-mock.lisp")
(in-package "ACL2")
(with-open-file (in "host/native/operator.lisp")
  (loop for form = (read in nil :eof) until (eq form :eof) do
    (when (and (consp form) (eq (car form) 'defstruct)
               (consp (second form)) (eq (caadr form) 'fnn-operator-live-owner))
      (eval form))))
(source-forms "books/native-control.lisp" '(fn-native-control-liveness))
(source-forms "host/native/store-identity.lisp"
              '(fnn-live-profile-read fnn-live-profile-owner-reply))
(defvar *disk-reads* 0)
(defvar *profile-asks* 0)
(defvar *socket-present* t)
(defvar *lock* :held)
(defvar *under-owner* nil)
(defvar *reply-ok* t)
(defvar *base-core* (symbol-function 'fnn-core))
(defun fnn-core (name &rest args)
  (case name
    (fn-omr-control-path-octets '(47 99))
    (fn-lpf-request '(26))
    (fn-lpf-reply-bound 676)
    (fn-lpf-reply (assert (not *under-owner*))
                  (assert (equal args '((:recorded-profile)))) '(27))
    (fn-lpf-reply-read (assert (equal args '((27))))
                       (and *reply-ok* '(:decided-profile)))
    (otherwise (apply *base-core* name args))))
(defun fnn-heap-store-profile (root)
  (assert (equal root "/fixture")) (incf *disk-reads*) '(:offline-profile))
(defun fnn-owner-serialized (service id thunk &optional class)
  (declare (ignore service id class))
  (let ((*under-owner* t)) (funcall thunk)))
(defun fnn-owner-service-store (service)
  (assert *under-owner*) service)
(defun fnn-octets-string (octets) (coerce (map 'list #'code-char octets) 'string))
(defun fnn-control-exchange (path request &optional bound seconds)
  (declare (ignore seconds))
  (assert (equal path "/c")) (assert (equal request '(26))) (assert (= bound 676))
  (incf *profile-asks*) (values #(27) :after-submission))
(assert (equal (fnn-live-profile-owner-reply (make-fixture-store)) '(27)))
(let ((*fnn-operator-live-owner*
        (make-fnn-operator-live-owner
         :admin-observe (lambda (root path queryp)
                          (assert (equal root "/fixture")) (assert (equal path '(47 99)))
                          (assert queryp)
                          (fn-native-control-liveness *socket-present* *lock*))
         :profile #'fnn-live-profile-read)))
  ;; Planted config occupants cannot be read on this path: no disk callback.
  (assert (equal (fnn-heap-operator-profile "CONFIG" '("group" "create" "fn.occupied"))
                 '(:decided-profile)))
  (assert (= *profile-asks* 1)) (assert (zerop *disk-reads*))
  ;; A live owner's bad reply is a fault, with no disk fallback.
  (let ((*reply-ok* nil))
    (assert (eq (handler-case (fnn-heap-operator-store-profile "/fixture" :result)
                  (fnn-store-fault () :fault)) :fault)))
  (assert (zerop *disk-reads*))
  ;; No reachable control socket with a held lock also forbids disk reads.
  (let ((*socket-present* nil))
    (assert (eq (handler-case (fnn-heap-operator-store-profile "/fixture" :result)
                  (fnn-store-error () :refused)) :refused)))
  (assert (zerop *disk-reads*))
  ;; The stopped/stale controls alone select disk observation.
  (dolist (socket '(nil t))
    (let ((*socket-present* socket) (*lock* :free))
      (assert (equal (fnn-heap-operator-store-profile "/fixture" :result) '(:offline-profile)))))
  (assert (= *disk-reads* 2)))
(format t "live profile: capture under owner, framing off owner, live/held never read disk; offline/stale controls passed~%")

;; Execute both owners' actual socket dispatch and the shared read handler.
;; The buffer codec seam uses the real kind table; a hard-coded BP admin
;; dispatch therefore fails this control before it can reach reconfiguration.
(require :sb-bsd-sockets)
(defmacro local (&rest forms) (declare (ignore forms)) nil)
(load "books/control-observation.lisp")
(defconst *fn-ctlk-store-kinds* (fn-nco-handler-kinds *fn-nco-kind-table* :store))
(defconst *fn-ctlk-read-kinds* (fn-nco-handler-kinds *fn-nco-kind-table* :read))
(source-forms "books/native-control-kinds.lisp" '(fn-ctlk-word))
(defstruct fnn-control-state service read-maximum)
(defstruct fnn-bpnc owner control listeners)
(defvar *fnn-hybrid-control-handler* nil)
(defvar *fnn-store-identity-next-handler* nil)
(defvar *fnn-control-frame-list* nil)
(defvar *frame-kind* 26)
(defvar *peer-owner* t)
(defvar *sent-profile* nil)
(defvar *bp-admin-turns* 0)
(defvar *profile-dispatch-core* (symbol-function 'fnn-core))
(defmacro fnn-with-control-buffer (() &body body) `(progn ,@body))
(defun fnn-core (name &rest args)
  (case name
    (fn-native-control-host-decode-frame
     (list nil nil nil nil nil nil nil nil (fn-ctlk-word *frame-kind*)))
    (fn-lpf-request-size-p (= (first args) 1))
    (fn-lpf-request-p (equal (first args) '(26)))
    (fn-stid-host-request-p nil)
    (fn-owner-bplc-turn-plan (incf *bp-admin-turns*) '(:refused :not-admin))
    (fn-native-control-host-reply-encode '(2))
    (otherwise (apply *profile-dispatch-core* name args))))
(defun fnn-owner-core (name &rest args) (apply #'fnn-core name args))
(defun fnn-control-peer-is-owner-p (socket) (declare (ignore socket)) *peer-owner*)
(defun fnn-control-read-frame (socket maximum)
  (declare (ignore socket maximum)) (fnn-octets (list *frame-kind*)))
(defun fnn-control-answering (&rest args) (declare (ignore args)))
(defun fnn-octets-ctl-fill (frame) frame)
(defun fnn-control-frame-octet-list (frame) (fnn-octet-list frame))
(defun fnn-socket-fd (socket) socket)
(defvar +fnn-control-io-seconds+ 1)
(defun fnn-send-all (fd octets seconds)
  (declare (ignore fd seconds)) (setq *sent-profile* (fnn-octet-list octets)))
(defun fnn-control-send-reply (socket status)
  (fnn-send-all socket (fnn-control-reply-octets status) 1))
(defun fnn-control-test-after-submit (status) (declare (ignore status)))
(defun fnn-owner-fault-service (&rest args) (error "unexpected fence ~s" args))
(defun fnn-owner-fence-service (&rest args) (error "unexpected fence ~s" args))
(defun fnn-bpnc-execute (node grant) (declare (ignore node grant)) :refused)
(source-forms "host/native/store-identity.lisp" '(fnn-store-identity-control-handle))
(source-forms "host/native/control.lisp" '(fnn-control-reply-octets fnn-control-handle-client))
(source-forms "host/native/bp-control.lisp" '(fnn-bpnc-handle))
(setq *fnn-hybrid-control-handler* #'fnn-store-identity-control-handle)
(dolist (kind '(:nntp :bp))
  (let* ((service (make-fixture-store))
         (control (make-fnn-control-state :service service :read-maximum 1024))
         (socket (make-instance 'sb-bsd-sockets:local-socket :type :stream))
         (*sent-profile* nil) (*bp-admin-turns* 0))
    (unwind-protect
        (progn
          (if (eq kind :bp)
              (fnn-bpnc-handle (make-fnn-bpnc :owner service :control control) socket)
            (fnn-control-handle-client control socket))
          (assert (equal *sent-profile* '(27)))
          (assert (zerop *bp-admin-turns*)))
      (ignore-errors (sb-bsd-sockets:socket-close socket)))))
;; Neither a non-read kind nor failed peer credentials can take BP's read
;; route, even with a profile-shaped frame at the codec seam.
(dolist (case '((4 t) (26 nil)))
  (let* ((*frame-kind* (first case)) (*peer-owner* (second case))
         (*sent-profile* nil) (*bp-admin-turns* 0)
         (socket (make-instance 'sb-bsd-sockets:local-socket :type :stream)))
    (fnn-bpnc-handle (make-fnn-bpnc :owner (make-fixture-store)
                                 :control (make-fnn-control-state :read-maximum 1024)) socket)
    (assert (equal *sent-profile* '(2)))
    (assert (= *bp-admin-turns* 1))))
(format t "live profile: NNTP/BP kind-table dispatch and peer refusal passed~%")
