;;; Actual ACL2 serial producer and native retained-result helpers/queue entry.
(load "tests/native_actor_envelope_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-arena-return-observation (log)
  (declare (ignorable log))
  (harness-stub-reached 'fnn-arena-return-observation "host/native/io.lisp"))
(defun fnn-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-core "host/native/io.lisp"))
(defun fnn-extent-direct-start ()
  (harness-stub-reached 'fnn-extent-direct-start "host/native/extent.lisp"))
(defun fnn-extent-end-recovery-cache ()
  (harness-stub-reached 'fnn-extent-end-recovery-cache "host/native/extent.lisp"))
(defun fnn-extent-executor-drained-p ()
  (harness-stub-reached 'fnn-extent-executor-drained-p "host/native/extent.lisp"))
(defun fnn-extent-executor-stop ()
  (harness-stub-reached 'fnn-extent-executor-stop "host/native/extent.lisp"))
(defun fnn-gc-nursery-octets ()
  (harness-stub-reached 'fnn-gc-nursery-octets "host/native/io.lisp"))
(defun fnn-listen (port &key family backlog address)
  (declare (ignorable port family backlog address))
  (harness-stub-reached 'fnn-listen "host/native/io.lisp"))
(defun fnn-log-line (line)
  (declare (ignorable line))
  (harness-stub-reached 'fnn-log-line "host/native/io.lisp"))
(defun fnn-log-sync-collected (log)
  (declare (ignorable log))
  (harness-stub-reached 'fnn-log-sync-collected "host/native/io.lisp"))
(defun fnn-log-writer-start ()
  (harness-stub-reached 'fnn-log-writer-start "host/native/io.lisp"))
(defun fnn-mux-budget-install (service tls-context)
  (declare (ignorable service tls-context))
  (harness-stub-reached 'fnn-mux-budget-install "host/native/mux.lisp"))
(defun fnn-mux-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-mux-drained-p "host/native/mux.lisp"))
(defun fnn-mux-plan-cold (loop conn plan after read)
  (declare (ignorable loop conn plan after read))
  (harness-stub-reached 'fnn-mux-plan-cold "host/native/mux.lisp"))
(defun fnn-mux-read-class (loop conn)
  (declare (ignorable loop conn))
  (harness-stub-reached 'fnn-mux-read-class "host/native/mux.lisp"))
(defun fnn-mux-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-mux-start "host/native/mux.lisp"))
(defun fnn-out (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-out "host/native/io.lisp"))
(defun fnn-owner-abandon-append-prefix (service grant)
  (declare (ignorable service grant))
  (harness-stub-reached 'fnn-owner-abandon-append-prefix "host/native/owner.lisp"))
(defun fnn-owner-accept (service listener once)
  (declare (ignorable service listener once))
  (harness-stub-reached 'fnn-owner-accept "host/native/owner.lisp"))
(defun fnn-owner-answer-early (ledger members)
  (declare (ignorable ledger members))
  (harness-stub-reached 'fnn-owner-answer-early "host/native/owner.lisp"))
(defun fnn-owner-claim-run-authority (&optional caller-reservation)
  (declare (ignorable caller-reservation))
  (harness-stub-reached 'fnn-owner-claim-run-authority "host/native/owner.lisp"))
(defun fnn-owner-cold-shutdown (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-cold-shutdown "host/native/owner.lisp"))
(defun fnn-owner-commit-complete-locked (service action members deferred)
  (declare (ignorable service action members deferred))
  (harness-stub-reached 'fnn-owner-commit-complete-locked "host/native/owner.lisp"))
(defun fnn-owner-commit-event (service event)
  (declare (ignorable service event))
  (harness-stub-reached 'fnn-owner-commit-event "host/native/owner.lisp"))
(defun fnn-owner-commit-start-locked (service &key seal held)
  (declare (ignorable service seal held))
  (harness-stub-reached 'fnn-owner-commit-start-locked "host/native/owner.lisp"))
(defun fnn-owner-commit-wake (service returned queued &optional append-idle append-returned held-caller)
  (declare (ignorable service returned queued append-idle append-returned held-caller))
  (harness-stub-reached 'fnn-owner-commit-wake "host/native/owner.lisp"))
(defun fnn-owner-complete-generation (ledger gen final members)
  (declare (ignorable ledger gen final members))
  (harness-stub-reached 'fnn-owner-complete-generation "host/native/owner.lisp"))
(defun fnn-owner-core (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-owner-core "host/native/owner.lisp"))
(defun fnn-owner-deliver (service cid completion)
  (declare (ignorable service cid completion))
  (harness-stub-reached 'fnn-owner-deliver "host/native/owner.lisp"))
(defun fnn-owner-disk-event (service kind &optional arg)
  (declare (ignorable service kind arg))
  (harness-stub-reached 'fnn-owner-disk-event "host/native/owner.lisp"))
(defun fnn-owner-disk-stalled-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-disk-stalled-p "host/native/owner.lisp"))
(defun fnn-owner-disk-wait-ms (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-disk-wait-ms "host/native/owner.lisp"))
(defun fnn-owner-drain-service (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-drain-service "host/native/owner.lisp"))
(defun fnn-owner-feed-close-all (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-feed-close-all "host/native/owner.lisp"))
(defun fnn-owner-frames-job (service job)
  (declare (ignorable service job))
  (harness-stub-reached 'fnn-owner-frames-job "host/native/owner.lisp"))
(defun fnn-owner-install (root max-connections &optional fault)
  (declare (ignorable root max-connections fault))
  (harness-stub-reached 'fnn-owner-install "host/native/owner.lisp"))
(defun fnn-owner-journal-close ()
  (harness-stub-reached 'fnn-owner-journal-close "host/native/owner.lisp"))
(defun fnn-owner-journal-note (service a b)
  (declare (ignorable service a b))
  (harness-stub-reached 'fnn-owner-journal-note "host/native/owner.lisp"))
(defun fnn-owner-journal-open (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-journal-open "host/native/owner.lisp"))
(defun fnn-owner-log-settlement ()
  (harness-stub-reached 'fnn-owner-log-settlement "host/native/owner.lisp"))
(defun fnn-owner-measure-report ()
  (harness-stub-reached 'fnn-owner-measure-report "host/native/owner.lisp"))
(defun fnn-owner-output-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-output-drained-p "host/native/owner.lisp"))
(defun fnn-owner-page-read-startup (root max-connections cold-resources output-resources retain)
  (declare (ignorable root max-connections cold-resources output-resources retain))
  (harness-stub-reached 'fnn-owner-page-read-startup "host/native/owner.lisp"))
(defun fnn-owner-peer-flight-startup (service capture)
  (declare (ignorable service capture))
  (harness-stub-reached 'fnn-owner-peer-flight-startup "host/native/owner.lisp"))
(defun fnn-owner-pipeline-close (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-pipeline-close "host/native/owner.lisp"))
(defun fnn-owner-reader-capture (event)
  (declare (ignorable event))
  (harness-stub-reached 'fnn-owner-reader-capture "host/native/owner.lisp"))
(defun fnn-owner-refresh-read-octets (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-refresh-read-octets "host/native/owner.lisp"))
(defun fnn-owner-release-recovery-garbage ()
  (harness-stub-reached 'fnn-owner-release-recovery-garbage "host/native/owner.lisp"))
(defun fnn-owner-retain-run-authority (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-retain-run-authority "host/native/owner.lisp"))
(defun fnn-owner-retire-final-report (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-retire-final-report "host/native/owner.lisp"))
(defun fnn-owner-run-startup-hooks (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-run-startup-hooks "host/native/owner.lisp"))
(defun fnn-owner-service-nursery ()
  (harness-stub-reached 'fnn-owner-service-nursery "host/native/owner.lisp"))
(defun fnn-owner-shed-queued-locked (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-shed-queued-locked "host/native/owner.lisp"))
(defun fnn-owner-snapshot-jobs-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-snapshot-jobs-drained-p "host/native/owner.lisp"))
(defun fnn-owner-space-event (service need)
  (declare (ignorable service need))
  (harness-stub-reached 'fnn-owner-space-event "host/native/owner.lisp"))
(defun fnn-owner-space-prime (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-space-prime "host/native/owner.lisp"))
(defun fnn-owner-stall-release (service members)
  (declare (ignorable service members))
  (harness-stub-reached 'fnn-owner-stall-release "host/native/owner.lisp"))
(defun fnn-owner-start-append-prefix (service gen job grant)
  (declare (ignorable service gen job grant))
  (harness-stub-reached 'fnn-owner-start-append-prefix "host/native/owner.lisp"))
(defun fnn-owner-start-committer (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-start-committer "host/native/owner.lisp"))
(defun fnn-owner-start-tls-accept (service listener &optional implicit-tls)
  (declare (ignorable service listener implicit-tls))
  (harness-stub-reached 'fnn-owner-start-tls-accept "host/native/owner.lisp"))
(defun fnn-owner-stop-service (service exit-code)
  (declare (ignorable service exit-code))
  (harness-stub-reached 'fnn-owner-stop-service "host/native/owner.lisp"))
(defun fnn-owner-store-settlement (service settlement)
  (declare (ignorable service settlement))
  (harness-stub-reached 'fnn-owner-store-settlement "host/native/owner.lisp"))
(defun fnn-owner-syncer-abandon (service grant ledger members)
  (declare (ignorable service grant ledger members))
  (harness-stub-reached 'fnn-owner-syncer-abandon "host/native/owner.lisp"))
(defun fnn-owner-syncer-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-syncer-drained-p "host/native/owner.lisp"))
(defun fnn-owner-syncer-outcome (service grant generation)
  (declare (ignorable service grant generation))
  (harness-stub-reached 'fnn-owner-syncer-outcome "host/native/owner.lisp"))
(defun fnn-owner-syncer-physical (service grant receipt)
  (declare (ignorable service grant receipt))
  (harness-stub-reached 'fnn-owner-syncer-physical "host/native/owner.lisp"))
(defun fnn-owner-wait-workers (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-wait-workers "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-joined (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-joined "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-start "host/native/owner.lisp"))
(defun fnn-peer-flight-bank-drained (bank)
  (declare (ignorable bank))
  (harness-stub-reached 'fnn-peer-flight-bank-drained "host/native/catchup-spool.lisp"))
;;; ---- derived stubs: END ----
(defmacro mv (&rest xs) `(values ,@xs))
(defmacro mv-let (vars form &body body) `(multiple-value-bind ,vars ,form ,@body))
(defun true-listp (x) (or (null x) (and (consp x) (true-listp (cdr x)))))
(defun len (x) (length x))
;; Actual pure definitions, only ACL2 declarations removed for SBCL execution.
(with-open-file (s "books/response-identity.lisp")
  (loop for f = (read s nil :eof) until (eq f :eof)
        when (and (consp f) (eq (car f) 'defun))
        do (eval (append (subseq f 0 3) (remove-if (lambda (x) (and (consp x) (eq (car x) 'declare))) (nthcdr 3 f))))))
(load-deployed-forms "host/native/owner.lisp"
 '((defun fnn-owner-connection-identity-locked) (defun fnn-owner-response-identity-locked) (defun fnn-owner-response-identity)))
(load-deployed-forms "host/native/mux.lisp"
 '((defstruct (fnn-mux-loop (:constructor %make-fnn-mux-loop)))
   (defstruct (fnn-mux-conn (:constructor %make-fnn-mux-conn)))
   (defun fnn-mux-queue-plan)))
(defvar *identity-calls* nil)
(defun fnn-call (subject &rest args)
  (push (cons subject args) *identity-calls*)
  (multiple-value-list (apply (symbol-function subject) args)))
(defun fnn-owner-serialized (service cid thunk &optional class)
  (declare (ignore cid class))
  (sb-thread:with-mutex ((fnn-owner-service-lock service)) (funcall thunk)))
(defun fnn-mux-service (loop) (fnn-mux-loop-service loop))
(defvar *seen-before-factory* nil)
(defun fnn-mux-render-next (loop conn plan)
  (declare (ignore loop))
  (push (list (fnn-mux-conn-response-identity conn) plan) *seen-before-factory*)
  (values #() plan nil t))
(defun fnn-mux-plan-yield (loop conn rest after cursorp)
  (declare (ignore loop after cursorp)) (setf (fnn-mux-conn-plan conn) rest))
(defun fnn-mux-queue (&rest xs) (declare (ignore xs)) (error "unexpected output"))
(defun fnn-mux-after (&rest xs) (declare (ignore xs)) (error "unexpected response terminal"))
(let* ((s (%make-fnn-owner-service :lock (sb-thread:make-mutex :name "actual recorded O")))
       (c1 (fnn-owner-connection-identity-locked s 17))
       (c2 (fnn-owner-connection-identity-locked s 17))
       (loop (%make-fnn-mux-loop :service s))
       (conn (%make-fnn-mux-conn :cid 17 :connection-identity c2))
       (plan (list :retained-cursor)))
  (check (equal c1 '(:connection 17 1)) "first admitted lifetime")
  (check (equal c2 '(:connection 17 2)) "same CID independent new lifetime")
  (fnn-mux-queue-plan loop conn plan :next)
  (let ((id (fnn-mux-conn-response-identity conn)) (calls (length *identity-calls*)))
    (check (equal id '(:response 17 2 1)) "ACL2 response keeps exact connection generation")
    (check (eq (fnn-mux-conn-plan conn) plan) "original cursor retained")
    (fnn-mux-queue-plan loop conn plan :next)
    (check (eq id (fnn-mux-conn-response-identity conn)) "resume retains exact identity object")
    (check (= calls (length *identity-calls*)) "resume does not reserve another operation"))
  (check (every (lambda (row) (and (first row) (eq (second row) plan))) *seen-before-factory*)
         "identity precedes every actual render factory entry")
  (setf (fnn-owner-service-response-generation s) 18446744073709551615
        (fnn-mux-conn-response-identity conn) nil)
  (let ((before (length *seen-before-factory*)))
    (check (handler-case (progn (fnn-mux-queue-plan loop conn plan :next) nil)
             (serious-condition () t)) "exhaustion signals before materialization")
    (check (= before (length *seen-before-factory*)) "no factory on exhausted serial")
    (check (= (fnn-owner-service-response-generation s) 18446744073709551615) "no wrap")))
(format t "native_response_identity_raw: PASS actual producer/native capture/pre-render/resume/exhaustion~%")
