;;; Exercise the deployed consumer publication wrapper with recording Store
;;; stubs.  ACL2 constructs the event; this test observes only the native
;;; reservation/preparation/publication boundary and its refusal cut.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")

(defvar *fnn-observe-callback* nil)
(defvar *fnn-finish-callback* nil)
(defvar *calls* nil)
(defvar *prepare-result* :prepared)
(defstruct mock-service store (records 0))
(define-condition consumer-refusal (error) ())
(defun fnn-refuse (&rest args) (declare (ignore args)) (error 'consumer-refusal))
(defun fnn-indeterminate (&rest args) (declare (ignore args))
  (error "indeterminate consumer publication"))
(defun fnn-owner-service-store (service) (mock-service-store service))
(defun fnn-owner-service-records (service) (mock-service-records service))
(defun fnn-config-max-transactions (store) (declare (ignore store)) 2)
(defun fnn-owner-preflight-publication (service kind)
  (declare (ignore service)) (push (list :preflight kind) *calls*) :admissible)
(defun fnn-owner-observe (&rest args) (declare (ignore args)) nil)
(defun fnn-owner-finish (&rest args) (declare (ignore args)) nil)
(defun fnn-owner-core (name &rest args)
  (declare (ignore args))
  (push (list :core name) *calls*)
  (unless (eq name 'fn-owner-next-txid) (error "wrong core call"))
  7)
(defun fnn-nat (x) (unless (and (integerp x) (<= 0 x)) (error "not nat")) x)
(defun fnn-advance-frontier (store txid)
  (declare (ignore store)) (push (list :advance txid) *calls*) :advanced)
(defun fnn-owner-action (name &rest args)
  (push (cons :action (cons name args)) *calls*)
  (ecase name
    (fn-owner-prepare-consumer *prepare-result*)
    (fn-owner-refuse-reservation :refused)))
(defun fnn-owner-publish-prepared (service label)
  (declare (ignore service)) (push (list :publish label) *calls*) :durable)

(let ((found nil))
  (with-open-file (stream "host/native/owner.lisp")
    (loop for form = (read stream nil :eof)
          until (eq form :eof)
          when (and (consp form) (eq (car form) 'defun)
                    (eq (cadr form) 'fnn-owner-consumer-commit))
            do (eval form) (setf found t)))
  (unless found (error "deployed fnn-owner-consumer-commit missing")))

(defun check (condition description)
  (unless condition (error "~a" description)))

(let* ((event '(:consumer :opaque-acl2-event))
       (service (make-mock-service :store :store)))
  (setf *calls* nil *prepare-result* :prepared)
  (check (eq (fnn-owner-consumer-commit service event) :durable)
         "prepared event did not become durable")
  (check (equal (reverse *calls*)
                (list '(:preflight :consumer)
                      '(:core fn-owner-next-txid)
                      '(:advance 7)
                      (list :action 'fn-owner-prepare-consumer event)
                      '(:publish "consumer")))
         "consumer publication call order or event identity changed")

  (setf *calls* nil *prepare-result* :refused)
  (handler-case (progn (fnn-owner-consumer-commit service event)
                       (error "refused event published"))
    (consumer-refusal () nil))
  (check (equal (reverse *calls*)
                (list '(:preflight :consumer)
                      '(:core fn-owner-next-txid)
                      '(:advance 7)
                      (list :action 'fn-owner-prepare-consumer event)
                      '(:action fn-owner-refuse-reservation)))
         "refused reservation was not consumed before refusal")

  (setf (mock-service-records service) 2 *calls* nil)
  (handler-case (progn (fnn-owner-consumer-commit service event)
                       (error "capacity refusal missed"))
    (consumer-refusal () nil))
  (check (null *calls*) "capacity refusal advanced the frontier"))
(format t "native owner consumer boundary passed~%")
