;;; S052: the BP application receiver's run tally keeps a deferral apart from
;;; a refusal.  The actual fnn-bpapp-deliver, fnn-bp-tally and fnn-bp-summary
;;; run; the owner seams (fnn-core, fnn-quantum-bp, fnn-bpapp-accept-locked,
;;; fnn-owner-action) are recorded stubs, so this is a source-level witness
;;; and no native claim.  The class word is the actual fn-olog-bp-app-class.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(declaim (declaration xargs))
(defun source-forms (path names)
 (with-open-file (in path)
  (loop for form = (read in nil :eof) until (eq form :eof)
   when (and (consp form) (member (car form) '(defun defstruct))
             (member (if (consp (second form)) (car (second form)) (second form)) names))
   do (progn (eval form)
             (setf names (remove (if (consp (second form)) (car (second form)) (second form)) names)))
   finally (assert (null names)))))

(defvar *lines* nil)
(defvar *result* nil)
(defvar *fnn-owner-transit-detail* nil)
(defstruct fnn-tclc pending)
(defun member-equal (x l) (member x l :test #'equal))
(defun fnn-bp-eid (x) x)
(defun fnn-bp-reserve-sequence (tally) (declare (ignore tally)) 0)
(defun fnn-bpapp-pause-after-decision () nil)
(defun fnn-octet-list (x) x)
(defun fnn-string-octets (x) x)
(defun fnn-fault (&rest args) (error "unreached: ~s" args))
(defun fnn-out (control &rest args) (push (apply #'format nil control args) *lines*))
(defun fnn-bp-observation (wall wall-error) (declare (ignore wall wall-error)) :obs)
(defun fnn-octets (x) x)
(defun fnn-octets-string (x) (declare (ignore x)) "id")
(defun fnn-bps-tcpcl-ingress (&rest args) (declare (ignore args)) :ingress)
(defun fnn-bp-evidence-publish (&rest args) (declare (ignore args)) "path")
(defun fnn-owner-log () nil)
(defun fnn-owner-action (name result xfer-id detail)
  (declare (ignore xfer-id detail))
  (assert (eq name 'fn-owner-app-refusal-log))
  (fn-olog-bp-app-class result))
(defun fnn-bpapp-accept-locked (&rest args) (declare (ignore args)) (values *result* nil))
(defun fnn-quantum-bp (service cid thunk &optional class)
  (declare (ignore service cid class))
  (funcall thunk))
(defun fnn-core (name &rest args)
  (declare (ignore args))
  (ecase name
    (fn-bpapp-receive :received)
    (fn-bpapp-receive-outcome :accepted)
    (fn-bpapp-receive-reason nil)
    (fn-bpapp-receive-adu nil)
    (fn-bpapp-receive-identity nil)
    (fn-bpapp-receive-source nil)
    (fn-bpapp-receive-destination nil)
    (fn-id-hex-octets nil)))

(load "tests/native_held_commit_prelude.lisp")
(source-forms "books/owner-log.lisp" '(fn-olog-bp-app-class))
(source-forms "host/native/bp.lisp" '(fnn-bp-tally fnn-bp-summary))
(source-forms "host/native/bp-app.lisp" '(fnn-bpapp-deliver))

(defun deliver (result)
  (let ((*result* result)
        (tally (make-fnn-bp-tally)))
    (values (fnn-bpapp-deliver nil nil tally nil nil 0 nil nil 0 nil) tally)))

(dolist (c '((:refused 1 0) (:busy 0 1) (:clock-unusable 0 1)))
  (multiple-value-bind (answer tally) (deliver (first c))
    ;; the wire answer stays a refusal carrying the transient word
    (assert (equal answer (list :refused (first c))))
    (assert (= (fnn-bp-tally-refused tally) (second c)))
    (assert (= (fnn-bp-tally-deferred tally) (third c)))
    (assert (= (fnn-bp-tally-uncertain tally) 0))
    (let ((*lines* nil))
      (fnn-bp-summary tally)
      (assert (equal *lines*
                     (list (if (= (third c) 1)
                               "BP summary accepted=0 refused=0 uncertain=0 deferred=1"
                               "BP summary accepted=0 refused=1 uncertain=0")))))))
(format t "PASS the BP application tally keeps a deferral apart from a refusal~%")
