(load "tests/native_bp_lock_return_source.lisp")
(in-package "ACL2")
(defconstant +fnn-exit-ok+ 0)
(defconstant +fnn-bp-lifetime+ 1)
(defconstant +fnn-bp-crc-type+ 2)
(defconstant +fnn-bp-hop-limit+ 3)
(defconstant +fnn-tcl-transfer-mru+ 4)
(defvar *profile-error* nil)
(defvar *installed* nil)
(defvar *output* nil)
(defun fnn-bp-config (&rest args) (declare (ignore args)) nil)
(defun fnn-bps-open (&rest args) (declare (ignore args)) (make-fnn-bps :root "/root"))
(defun fnn-bps-node-profile (&rest args) (declare (ignore args)) '(1 2 3 4 5))
(defun fnn-core (name &rest args)
  (declare (ignore args))
  (case name ((fn-bpnpf-node-profile-write-octets fn-bpsp-write) '(1))
    ((fn-bpnpf-file-name fn-bpsp-file-name) "profile")
    (otherwise (error "core ~a" name))))
(defun fnn-random-hex (&rest args) (declare (ignore args)) "suffix")
(defun fnn-octets (x) x)
(defun fnn-refuse (&rest args) (error "~a" args))
(defun fnn-write-staged (&rest args)
  (declare (ignore args)) (when (eq *profile-error* :stage) (error *primary*)))
(defun fnn-replace (&rest args)
  (declare (ignore args)) (setq *installed* t)
  (when (eq *profile-error* :replace) (error 'fnn-os-error)))
(defun fnn-fsync-dir (&rest args)
  (declare (ignore args)) (when (eq *profile-error* :barrier) (error 'fnn-os-error)))
(defun fnn-out (&rest args) (push args *output*))
;; Named root boundary adapter signals cleanup failure after actual command body.
(defun fnn-bps-release (&rest args)
  (declare (ignore args))
  (when (member *profile-error* '(:close :stage)) (error 'fnn-store-indeterminate)))
(fixture-read "host/native/bp-node.lisp"
 '(fnn-bpnode-replace-profile fnn-command-bp-node-profile fnn-command-bp-session-profile))
(dolist (command '(fnn-command-bp-node-profile fnn-command-bp-session-profile))
  (dolist (fault '(:replace :barrier :close :stage nil))
    (let ((*profile-error* fault) (*installed* nil) (*output* nil) (caught nil))
      (handler-case
          (assert (= (apply command (if (eq command 'fnn-command-bp-node-profile)
                                        '("/root" "id" 1 2) '("/root" "id" 1 2 3 4))) 0))
        (error (condition) (setq caught condition)))
      (if fault (assert caught) (assert (null caught)))
      (when (eq fault :stage) (assert (eq caught *primary*)))
      (when (member fault '(:replace :barrier :close))
        (assert (typep caught 'fnn-store-indeterminate)))
      (when (member fault '(:replace :barrier))
        (assert *installed*) (assert (null *output*))))))
(format t "native BP profile replacement return source PASS~%")
