; Raw consumer control-flow fixture. ACL2 producer seams are recorded doubles;
; this tests the actual native installer/walk, not page-codec refinement.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(defmacro fnn-owner-gated ((service class) &body body)
  (declare (ignore service class)) `(progn ,@body))
(define-condition fnn-store-io-refusal (error) ())
(defun fnn-refuse-io (&rest ignored) (declare (ignore ignored)) (error 'fnn-store-io-refusal))
(defun fnn-fault (&rest args) (error "fixture fault ~s" args))
(defun fnn-err (&rest ignored) (declare (ignore ignored)) nil)
(defstruct fnn-owner-service stopping)
(defvar *fnn-checkpoint-stop-test* nil)
(defun fnn-checkpoint-yield (&rest ignored)
  (declare (ignore ignored))
  (when (and *fnn-checkpoint-stop-test* (funcall *fnn-checkpoint-stop-test*))
    (error 'fnn-store-io-refusal)))
(defvar *the-live-state* (list (cons 'fn-hist nil)))
(defun user-stobj-alist (state) state)
(defvar *fnn-hist* nil)
(defvar *fnn-cat* nil)
(defun fnn-live-hist () *fnn-hist*)
(defvar *fx-events* nil)
(defvar *fx-generation* 0)
(defvar *fx-current* nil)
(defvar *fx-incarnation* nil)
(defvar *fx-retired* nil)
(defvar *fx-leases* nil)
(defvar *fx-token* 0)
(defvar *fx-trace* nil)
(defvar *fx-refuse* nil)
(defvar *fx-rewrite-at* nil)
(defvar *fx-tail-at-index* nil)
(defun fx-frontier () (list (length *fx-events*) :frontier :config *fx-incarnation*))
(defun fnn-owner-core (name &rest args)
  (push name *fx-trace*)
  (case name
    (fn-owner-hroot-detach
      (let ((old *fx-current*))
        (when old (push old *fx-retired*))
        (setq *fx-current* nil *fx-incarnation* :detached)
        (list :detached old)))
    (fn-owner-hroot-begin (if *fx-refuse* '(:refused :credit) (list :building (incf *fx-generation*))))
    (fn-owner-hroot-frontier-value (fx-frontier))
    (fn-owner-orcp-salt 0)
    (fn-owner-hroot-row
      (destructuring-bind (ordinal incarnation) args
        (cond ((not (eql incarnation *fx-incarnation*)) '(:refused :history-source-changed))
              ((= ordinal (length *fx-events*)) (list :done (fx-frontier)))
              (t (list :event (nth ordinal *fx-events*) (fx-frontier))))))
    (fn-owner-hroot-activate
      (destructuring-bind (generation count frontier) args
        (assert (= count (length *fx-events*)))
        (assert (equal frontier (fx-frontier)))
        (prog1 (list :installed generation *fx-current*)
          (when *fx-current* (push *fx-current* *fx-retired*))
          (setq *fx-current* generation))))
    (fn-owner-hroot-abandon :released)
    (fn-owner-hroot-retire
      (let ((generation (first args)))
        (if (and (member generation *fx-retired*)
                 (not (find generation *fx-leases* :key #'third))) :released :history-root-held)))
    (fn-owner-hroot-pin-funded
      (when (eql (first args) *fx-current*)
        (let ((source (list :history-root (incf *fx-token*) *fx-current*
                            (length *fx-events*) (fx-frontier))))
          (push source *fx-leases*) source)))
    (fn-owner-hroot-read-plan
      (destructuring-bind (source ordinal) args
        (assert (member source *fx-leases* :test #'equal))
        (assert (< ordinal (fourth source)))
        (list :read (third source) ordinal)))
    (fn-owner-hroot-read-owned 0)
    (fn-owner-hroot-read-fund :funded)
    (fn-owner-hroot-return
      (setq *fx-leases* (remove (first args) *fx-leases* :test #'equal)) :returned)
    (otherwise (error "unknown owner seam ~s" name))))
(defun fnn-call (name &rest args)
  (push name *fx-trace*)
  (case name
    (fn-owner-hroot-resize (list :funded nil))
    ((create-fn-hrecs$s create-fn-hist$p) (list (vector nil 0 nil nil)))
    (fn-his-build-begin (list (second args)))
    (fn-his-release (setf (aref (first args) 0) nil) (list (first args)))
    (fn-his-row-begin
      (setf (aref (second args) 3) (first args))
      (list :yield '(:append) (second args)))
    (fn-his-row-step
      (let ((stage (second args)))
        (setf (aref stage 0) (append (aref stage 0) (list (aref stage 3))))
        (when (eql (length (aref stage 0)) *fx-rewrite-at*) (setq *fx-incarnation* :rewritten))
        (list :done nil stage)))
    (fn-hist$p-adopt-stage
      (destructuring-bind (generation stage root) args
        (setf (aref root 0) (aref stage 0) (aref root 1) generation)
        (setf (aref stage 0) nil)
        (list stage root)))
    (fn-hist$p-root-index-next
      (destructuring-bind (ordinal root) args
        (if (= ordinal (length (aref root 0)))
            (progn
              (setf (aref root 2) t)
              (when *fx-tail-at-index*
                (setq *fx-events* (append *fx-events* (list *fx-tail-at-index*))
                      *fx-tail-at-index* nil))
              (list :done ordinal root))
          (list :yield (1+ ordinal) root))))
    ((fn-hroot-index-demand fn-hroot-read-demand) (list :ok 1000))
    ((fn-hroot-event-demand fn-hroot-retain-demand fn-hroot-root-retain-demand fn-hroot-tail-demand) (list 1000))
    (fn-hist$p-append
      (setf (aref (second args) 0) (append (aref (second args) 0) (list (first args))))
      (list (second args)))
    (fn-hist$p-root-generation (list (and (aref (first args) 2) (aref (first args) 1))))
    (fn-hist$p-read (list (list :ok (nth (first args) (aref (second args) 0)))))
    (fn-his-build-source-count (list (length (first args))))
    (fn-hist$p-candidate-word
      (list (if (and (aref (second args) 2) (= (first args) (length (aref (second args) 0))))
                :ready '(:refused :history-candidate-count))))
    (fn-owner-orc-init (list 0))
    (fn-owner-orc-chunk (list (list (first args) (+ (third args) (length (first args))))))
    (otherwise (error "unknown core seam ~s" name))))
(defun fnn-core (name &rest args) (first (apply #'fnn-call name args)))
(load "host/native/history-root.lisp")
(defparameter +fnn-reclaim-chunk-rows+ 3)
(with-open-file (s "host/native/owner.lisp")
  (loop for form = (read s nil :eof) until (eq form :eof)
        when (and (consp form) (eq (car form) 'defun)
                  (member (cadr form) '(fnn-owner-reclaim-walk fnn-fresh-stobj fnn-install-stobj))) do (eval form)))
(let* ((service (make-fnn-owner-service))
       (events '((:article a) (:config b) (:receipt c) (:ack d) (:key e) (:article f) (:lineage g)))
       (original (vector events 0 nil nil)))
  (setq *fx-events* events *fnn-hist* original)
  (setf (cdr (assoc 'fn-hist *the-live-state*)) original)
  (setq *fx-refuse* t)
  (assert (equal (fnn-owner-history-root-refresh service) '(:refused :credit)))
  (assert (eq *fnn-hist* original))
  (setq *fx-refuse* nil *fx-rewrite-at* 2)
  (assert (handler-case (progn (fnn-owner-history-root-refresh service) nil)
            (fnn-store-io-refusal () t)))
  (assert (eq *fnn-hist* original))
  (setq *fx-rewrite-at* nil *fx-tail-at-index* '(:outbox h))
  (assert (eq (first (fnn-owner-history-root-refresh service)) :installed))
  (assert (equal (aref *fnn-hist* 0) *fx-events*))
  (let* ((pin (fnn-owner-history-root-pin service)) (old-root (second pin))
         (old-generation (third (first pin))) (captured *fx-events*))
    (assert pin)
    (setq *fx-events* (append *fx-events* '((:new-tail i))))
    (fnn-core 'fn-hist$p-append '(:new-tail i) *fnn-hist*)
    (assert (eq (first (fnn-owner-history-root-refresh service)) :installed))
    (assert (not (eq old-root *fnn-hist*)))
    (assert (gethash old-generation *fnn-history-roots*))
    (multiple-value-bind (count rewritten)
        (fnn-owner-reclaim-walk '(:poisoned-list-source) nil t nil service pin)
      (assert (= count (length captured)))
      (assert (equal rewritten captured)))
    (let ((ordered (reverse *fx-trace*)))
      (assert (position 'fn-owner-hroot-read-fund ordered))
      (assert (< (position 'fn-owner-hroot-read-fund ordered)
                 (position 'fn-hist$p-read ordered))))
    (fnn-owner-history-root-unpin service pin)
    (assert (null (second pin)))
    (assert (null (gethash old-generation *fnn-history-roots*)))))
(format t "PASS actual native live adoption/catchup; stale rewrite/refusal; retained generation reclaim; decode prepayment; terminal retirement~%")
; The actual canonical replacement installer retires an unheld root even
; when replacement detached it before any later live root activation.
(let* ((service (make-fnn-owner-service))
       (old-generation *fx-current*)
       (new-empty (fnn-fresh-stobj 'fn-hist)))
  (declare (ignore service))
  (assert (gethash old-generation *fnn-history-roots*))
  (fnn-install-stobj 'fn-hist new-empty)
  (assert (eq *fnn-hist* new-empty))
  (assert (eq (cdr (assoc 'fn-hist *the-live-state*)) new-empty))
  (assert (null (gethash old-generation *fnn-history-roots*)))
  (assert (null *fx-current*)))
(format t "PASS actual canonical history replacement clears unheld retired root; registered private creator~%")

; Actual reclaim candidate path installs its already built page generation;
; no all-tail load or subsequent second history build is needed.
(let* ((service (make-fnn-owner-service))
       (served '((:article a) (:receipt b) (:config c)))
       (rewritten '((:tombstone a) (:receipt b) (:config c))))
  (setq *fx-events* served)
  (fnn-owner-history-root-refresh service)
  (let* ((pin (fnn-owner-history-root-pin service)) (old-generation (third (first pin)))
         (old-root (second pin))
         (prepared (fnn-owner-history-root-prepare-rows service rewritten 17)))
    (assert (not (eq (second prepared) *fnn-hist*)))
    (assert (equal (aref (second prepared) 0) rewritten))
    (assert (eq (second pin) old-root))
    ;; The preceding real owner swap supplies these new logical rows.
    (setq *fx-events* rewritten)
    (fnn-owner-history-root-install-held prepared)
    (assert (eq (second prepared) *fnn-hist*))
    (assert (equal (aref *fnn-hist* 0) rewritten))
    (assert (gethash old-generation *fnn-history-roots*))
    (assert (equal (fnn-owner-history-root-at service pin 0) (first served)))
    (fnn-owner-history-root-unpin service pin)
    (assert (null (gethash old-generation *fnn-history-roots*))))
  (let ((current *fnn-hist*))
    (setq *fx-refuse* t)
    (assert (handler-case
                (progn (fnn-owner-history-root-prepare-rows service rewritten 17) nil)
              (fnn-store-io-refusal () t)))
    (assert (eq current *fnn-hist*))
    (setq *fx-refuse* nil)))
(format t "PASS actual rewritten-root preparation/install; held old generation survives; refused preparation preserves authority~%")
