;;; Actual command unwind: body fault survives every independent cleanup fault.
(load "tests/native_bp_session_bank_raw.lisp")
(in-package "ACL2")
(defconstant +fnn-tcl-segment-mru+ 65536)
(defvar *fnn-bpnode-budgets* nil)
(defvar *fnn-bpnode-receipt-signer* nil)
(defvar *root-calls* nil)
(define-condition test-cleanup-error (error) ((marker :initarg :marker :reader marker)))
(defvar *body-condition* (make-condition 'test-cleanup-error :marker :body))
(defun fnn-bp-config (&rest xs) (declare (ignore xs)) :config)
(defun fnn-bps-open-node (&rest xs) (declare (ignore xs)) :bp)
(defun fnn-bpnode-read-budgets (&rest xs) (declare (ignore xs)) nil)
(defun fnn-owner-install (&rest xs) (declare (ignore xs)) :owner)
(defvar *held-root-test* nil)
(defvar *held-bank* nil)
(defun fnn-bp-session-install (&rest xs)
 (declare (ignore xs))
 (let ((bank (test-bank)))
  (when *held-root-test*
   (test-grant bank 2 :incoming nil (make-fnn-tcl-conn :finished t :source-pending t)))
  (setq *held-bank* bank) bank))
(defun fnn-bpnc-start (&rest xs) (declare (ignore xs)) :control)
(defun fnn-bpc-advance-clock (&rest xs) (declare (ignore xs)))
(defun fnn-bp-observation (&rest xs) xs)
(defun fnn-bpnode-delete-expired (&rest xs) (declare (ignore xs)))
(defun fnn-bpnode-observe-reports (&rest xs) (declare (ignore xs)))
(defun fnn-bpnode-dispatch-pending (&rest xs) (declare (ignore xs)))
(defun fnn-bps-tally (&rest xs) (declare (ignore xs)))
(defun fnn-bp-evidence-open (&rest xs) (declare (ignore xs)))
(defun fnn-bplc-start (&rest xs) (declare (ignore xs)) :listener)
(defun (setf fnn-bpnc-listeners) (new x) (declare (ignore x)) new)
(defun make-fnn-bp-receipt-cursor () :cursor)
(defun fnn-bp-session-loop (&rest xs) (declare (ignore xs)) (error *body-condition*))
(defun cleanup-error (name) (push name *root-calls*) (error 'test-cleanup-error :marker name))
(defun fnn-bpnc-retire (&rest xs) (declare (ignore xs)) (cleanup-error :control))
(defun fnn-bplc-close-all (&rest xs) (declare (ignore xs)) (cleanup-error :listener))
(defun fnn-owner-action (&rest xs) (declare (ignore xs)) (cleanup-error :unbind))
(defun fnn-owner-feed-close-all (&rest xs) (declare (ignore xs)) (cleanup-error :feed))
(defun fnn-owner-service-store (&rest xs) (declare (ignore xs)) :store)
(defun fnn-store-close (&rest xs) (declare (ignore xs)) (cleanup-error :store))
(defun fnn-bps-release (&rest xs) (declare (ignore xs)) (cleanup-error :bp))
(defun fnn-core (name &rest xs)
 (case name ((fn-bpsp-root-release-ready fn-bpsg-step fn-bpsg-release-ready) (apply name xs))
  (otherwise (error "unexpected core ~s" name))))
(with-open-file (stream "host/native/bp-node.lisp")
 (loop for form = (read stream nil :eof) until (eq form :eof) do
  (when (and (consp form) (eq (car form) 'defun) (eq (second form) 'fnn-command-bp-node))
   (eval form))))
(let ((caught nil))
 (handler-case
  (fnn-command-bp-node 9 nil "/bp" "/store" "/receipt" "/workflow"
     "node" "peer" "dest" "policy" "issuer" "host" 9 1 1 1 1000 nil 0 nil nil :control)
  (test-cleanup-error (condition) (setq caught condition)))
 (assert (eq caught *body-condition*))
 (assert (equal (reverse *root-calls*) '(:control :listener :unbind :feed :store :bp))))
(let ((*held-root-test* t) (*root-calls* nil) (*fnn-bp-session-stranded-roots* nil) (caught nil))
 (handler-case
  (fnn-command-bp-node 9 nil "/bp" "/store" "/receipt" "/workflow"
     "node" "peer" "dest" "policy" "issuer" "host" 9 1 1 1 1000 nil 0 nil nil :control)
  (test-cleanup-error (condition) (setq caught condition)))
 (assert (eq caught *body-condition*))
 (assert (equal (reverse *root-calls*) '(:control :listener)))
 (assert (= (hash-table-count (fnn-bpsb-held *held-bank*)) 1))
 (assert (equal *fnn-bp-session-stranded-roots* (list (list *held-bank* :owner :bp)))))
(format t "PASS actual BP root cleanup: all independent cleanup faults preserve original body fault.~%")
