; Actual private worker module. Real anonymous file I/O; supplied lease only
; tests the executor lifecycle, not launcher funding or ledger admission.
(require :sb-posix)
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(defconstant +fnn-o-nofollow+ sb-posix:o-nofollow)
(defmacro fnn-posix (context &body body) (declare (ignore context)) `(progn ,@body))
(defun fnn-fault (&rest args) (error "fixture fault ~s" args))
(defun fnn-open (path flags mode) (sb-posix:open path flags mode))
(defun fnn-close (fd) (sb-posix:close fd))
(defun fnn-unlink (path) (sb-posix:unlink path))
(defun fnn-fstat (fd) (sb-posix:fstat fd))
(defun fnn-regular-p (stat) (sb-posix:s-isreg (sb-posix:stat-mode stat)))
(defun fnn-make-octets (n) (make-array n :element-type '(unsigned-byte 8) :initial-element 0))
(defun create-fn-octets$c () (vector (fnn-make-octets 0) 0))
(defun fn-octets$c-reserve (n buf) (setf (svref buf 0) (fnn-make-octets n)) buf)
(defun fnn-write-range (fd data start end)
  (loop while (< start end) do
    (multiple-value-bind (count errno) (sb-unix:unix-write fd data start (- end start))
      (unless (and count (plusp count)) (error "write ~s" errno))
      (incf start count))))
(with-open-file (in "host/native/extent.lisp")
  (loop for form = (read in nil :eof) until (eq form :eof)
        when (and (consp form) (eq (car form) 'defun)
                  (eq (second form) 'fnn-extent-window-pread)) do (progn (eval form) (return))))
(load "host/native/catchup-spool.lisp")
(defun take-wait (worker)
  (loop repeat 1000 do
    (multiple-value-bind (ready status count condition) (fnn-csp-worker-take worker)
      (when ready (return-from take-wait (values status count condition))))
    (sleep 0.001))
  (error "worker timed out"))
(defun join-wait (worker)
  (loop repeat 1000 do
    (multiple-value-bind (joined condition) (fnn-csp-worker-join-now worker)
      (when joined (assert (null condition)) (return-from join-wait t)))
    (sleep 0.001))
  (error "join timed out"))
(let* ((path (format nil "/tmp/fn-csp-source-~d" (sb-posix:getpid)))
       (worker (fnn-csp-worker-start path '(7 11) (lambda (worker) (declare (ignore worker))))))
  (unwind-protect
       (progn
         (fnn-csp-worker-submit worker :open 0 0)
         (assert (eq :ok (take-wait worker)))
         (assert (not (probe-file path)))
         (dotimes (i 512) (setf (aref (fnn-csp-worker-input worker) i) (mod i 256)))
         (fnn-csp-worker-submit worker :write 0 512)
         (multiple-value-bind (status count condition) (take-wait worker)
           (assert (eq status :ok)) (assert (= count 512)) (assert (null condition)))
         (fnn-csp-worker-submit worker :digest 256 64)
         (multiple-value-bind (status count condition) (take-wait worker)
           (assert (eq status :ok)) (assert (= count 64)) (assert (null condition))
           (dotimes (i 64) (assert (= i (aref (fnn-csp-worker-digest worker) i)))))
         (fnn-csp-worker-submit worker :replay 0 512)
         (assert (eq :ok (take-wait worker)))
         (dotimes (i 512) (assert (= (mod i 256) (aref (fnn-csp-worker-replay worker) i)))))
    (fnn-csp-worker-stop worker)
    (join-wait worker))
  (assert (fnn-csp-worker-returned worker))
  (assert (fnn-csp-worker-joined worker))
  (assert (null (fnn-csp-worker-fd worker))))
 ; An exclusive-open failure cannot authorize unlink of somebody else's path.
(let* ((path (format nil "/tmp/fn-csp-existing-~d" (sb-posix:getpid)))
       (worker nil))
  (unwind-protect
       (progn
         (with-open-file (out path :direction :output :if-exists :error) (write-string "owned elsewhere" out))
         (setq worker (fnn-csp-worker-start path '(9 13) (lambda (holder) (setq worker holder))))
         (fnn-csp-worker-submit worker :open 0 0)
         (multiple-value-bind (status count condition) (take-wait worker)
           (declare (ignore count)) (assert (eq status :error)) (assert condition))
         (fnn-csp-worker-stop worker) (join-wait worker)
         (assert (probe-file path)))
    (when worker (fnn-csp-worker-stop worker) (join-wait worker))
    (when (probe-file path) (delete-file path))))
; Held actual activation: cancellation and take cannot turn it into a receipt.
(let* ((perform (symbol-function 'fnn-csp-worker-perform))
       (gate (sb-thread:make-mutex)) (changed (sb-thread:make-waitqueue))
       (entered nil) (release nil) (worker nil))
  (unwind-protect
       (progn
         (setf (symbol-function 'fnn-csp-worker-perform)
               (lambda (w operation offset count)
                 (declare (ignore w operation offset count))
                 (sb-thread:with-mutex (gate)
                   (setq entered t) (sb-thread:condition-broadcast changed)
                   (loop until release do (sb-thread:condition-wait changed gate)))
                 (values :ok 0)))
         (setq worker (fnn-csp-worker-start nil '(8 12) (lambda (holder) (setq worker holder))))
         (fnn-csp-worker-submit worker :open 0 0)
         (sb-thread:with-mutex (gate)
           (loop until entered do (sb-thread:condition-wait changed gate)))
         (assert (null (fnn-csp-worker-take worker)))
         (fnn-csp-worker-stop worker)
         (assert (null (fnn-csp-worker-join-now worker)))
         (assert (not (fnn-csp-worker-returned worker)))
         (sb-thread:with-mutex (gate) (setq release t) (sb-thread:condition-broadcast changed))
         (join-wait worker)
         (multiple-value-bind (status count condition) (take-wait worker)
           (assert (eq :ok status)) (assert (= count 0)) (assert (null condition))))
    (sb-thread:with-mutex (gate) (setq release t) (sb-thread:condition-broadcast changed))
    (when worker (fnn-csp-worker-stop worker) (join-wait worker))
    (setf (symbol-function 'fnn-csp-worker-perform) perform)))
(format t "CATCHUP SPOOL SOURCE PASSED~%")
; Constructor escape retains the object before any thread starts. There is
; no physical worker to wait for, and the observer must handle that exact cut.
(let ((retained nil) (escaped nil))
  (handler-case
      (fnn-csp-worker-start "/tmp/fn-csp-not-created" '(23 29)
                            (lambda (worker) (setq retained worker) (error "retained cut")))
    (error () (setq escaped t)))
  (assert escaped)
  (assert retained)
  (assert (null (fnn-csp-worker-thread retained)))
  (assert (null (fnn-csp-worker-fd retained)))
  (assert (fnn-csp-worker-join-now retained)))
