;;; Actual registered creator and semantic counterparts, then the real native
;;; lifetime interpreter. No full owner image/allocator tariff is claimed.
;;; Actual native counterpart/registered-creator discrimination. Not a proof
;;; or a whole-plan allocation tariff; source-loaded warnings stay in the log.
(in-package "ACL2")
(require :sb-posix)
(require :sb-bsd-sockets)

(defun fnout-load-host-forms (path wanted)
  (let ((missing (copy-list wanted)))
    (with-open-file (stream path)
      (loop for form = (read stream nil :eof) until (eq form :eof)
            when (and (consp form)
                      (member (list (car form) (cadr form)) wanted :test #'equal))
              do (eval form)
                 (setf missing (remove (list (car form) (cadr form)) missing :test #'equal))))
    (when missing (error "output custody host forms missing: ~s" missing))))

(fnout-load-host-forms "host/native/io.lisp"
 '((define-condition fnn-store-error) (define-condition fnn-store-fault)
   (define-condition fnn-entry-guard-fault) (defun fnn-fault)
   (defun fnn-counterpart) (defun fnn-install-raw-dispatch)
   (defun fnn-dispatch-function) (defun fnn-guard-conjuncts)
   (defun fnn-entry-guard-spec) (defun fnn-entry-guard-describe)
   (defun fnn-entry-guard) (defun fnn-call) (defun fnn-core)))
(defvar *fnn-dispatch-counterpart* nil)
(defvar *fnn-raw-dispatch* (make-hash-table :test 'eq))
(defvar *fnn-startup-creators* (make-hash-table :test 'eq))
(defvar *fnn-entry-guard-specs* (make-hash-table :test 'eq))
(defvar *fn-entry-guard-kinds* nil)
(fnn-install-raw-dispatch :report nil)
(in-package "ACL2")
(fnout-load-host-forms "host/native/owner.lisp"
 '((defstruct (fnn-owner-service (:constructor %make-fnn-owner-service)))
   (defstruct (fnn-owner-cold-read (:constructor %make-fnn-owner-cold-read)))
   (defstruct (fnn-output-dependency (:constructor %make-fnn-output-dependency)))
   (defstruct (fnn-output-grant (:constructor %make-fnn-output-grant)))
   (defun fnn-owner-output-issue) (defun fnn-owner-output-dependency)
   (defun fnn-owner-output-observe-returned) (defun fnn-owner-output-receipt-locked)
   (defun fnn-owner-output-maybe-physical-locked) (defun fnn-owner-output-close)
   (defun fnn-owner-output-dependency-consumed) (defun fnn-owner-output-drained-p)))
(fnout-load-host-forms "host/native/extent.lisp"
 '((defstruct (fnn-cold-worker (:constructor %make-fnn-cold-worker)))))
;; Physical leaf for this fixture's actual held thread. The deployed executor
;; observer is separately exercised by native PageIO; no condition is classified.
(defun fnn-extent-executor-observe-returned (worker)
  (not (sb-thread:thread-alive-p (fnn-cold-worker-thread worker))))
(defun fnn-refuse (&rest xs) (error "lease refused ~s" xs))
(let* ((ledger (fnn-core 'create-fn-resource-ledger))
       (policy '(16777216 1048576))
       (dynamic (sb-ext:dynamic-space-size))
       (store-need (fnn-core 'fn-heap-figure-octets *fn-heap-small-profile*
                            (sb-kernel:dynamic-usage) 0))
       (service (%make-fnn-owner-service :output-ledger ledger)))
  (unless (eq (first (fnn-call 'fn-rlo-install dynamic store-need nil policy 4 ledger)) :installed)
    (error "actual captured profile cannot install lease fixture"))
  (setq *fnn-dispatch-counterpart* t)
  (let* ((identity (second (fnn-call 'fn-rid-response '(:connection 7 11) 8)))
         (grant (fnn-owner-output-issue service identity))
         (release (sb-thread:make-semaphore :count 0))
         (entered (sb-thread:make-semaphore :count 0))
         (worker (sb-thread:make-thread
                  (lambda ()
                    (let ((window (make-array 8 :element-type '(unsigned-byte 8) :initial-element 17)))
                      (sb-thread:signal-semaphore entered)
                      (sb-thread:wait-on-semaphore release)
                      window))))
         (read (%make-fnn-owner-cold-read :token '(actual-exact-job)
                                         :worker (%make-fnn-cold-worker :thread worker))))
    (unwind-protect
         (progn
           (sb-thread:wait-on-semaphore entered)
           (fnn-owner-output-dependency service grant read)
           (fnn-owner-output-close service grant :drained)
           (unless (and (sb-thread:thread-alive-p worker)
                        (not (fnn-owner-output-drained-p service)))
             (error "actual typed interpreter refunded held physical dependency"))
           (sb-thread:signal-semaphore release)
           (let ((window (sb-thread:join-thread worker)))
             (unless (= (length window) 8) (error "actual held output window changed")))
           (fnn-owner-output-observe-returned service read)
           (unless (not (fnn-owner-output-drained-p service))
             (error "physical observation refunded before transfer activation ended"))
           (fnn-owner-output-dependency-consumed service read)
           (unless (and (fnn-owner-output-drained-p service)
                        (null (fnn-owner-service-output-grants service)))
             (error "actual terminal dual receipt failed to clear typed/native custody"))
           (fnn-owner-output-close service grant :drained))
      (when (sb-thread:thread-alive-p worker)
        (sb-thread:signal-semaphore release)
        (sb-thread:join-thread worker))))
  (let ((grant (fnn-owner-output-issue service
                (second (fnn-call 'fn-rid-response '(:connection 7 11) 9)))))
    (fnn-owner-output-close service grant :discarded)
    (unless (fnn-owner-output-drained-p service)
      (error "actual no-child closure did not settle after authority ended"))))
(format t "~%native_output_response_lease_counterpart: PASS actual creator, normal methods, native lifetime interpreter and real held child~%")
