; SCN-1130 actual owner-run startup/cleanup ordering. Physical constructors
; are observed seams here; this is not a saved-image or complete-price claim.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "COMMON-LISP"))
(defpackage "ACL2_*1*_ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-close (fd)
  (declare (ignorable fd))
  (harness-stub-reached 'fnn-close "host/native/io.lisp"))
(defun fnn-err (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-err "host/native/io.lisp"))
(defun fnn-extent-direct-start ()
  (harness-stub-reached 'fnn-extent-direct-start "host/native/extent.lisp"))
(defun fnn-extent-end-recovery-cache ()
  (harness-stub-reached 'fnn-extent-end-recovery-cache "host/native/extent.lisp"))
(defun fnn-flock (fd operation)
  (declare (ignorable fd operation))
  (harness-stub-reached 'fnn-flock "host/native/io.lisp"))
(defun fnn-listen (port &key family backlog address)
  (declare (ignorable port family backlog address))
  (harness-stub-reached 'fnn-listen "host/native/io.lisp"))
(defun fnn-log-close-active (log)
  (declare (ignorable log))
  (harness-stub-reached 'fnn-log-close-active "host/native/io.lisp"))
(defun fnn-log-discard-spare (log)
  (declare (ignorable log))
  (harness-stub-reached 'fnn-log-discard-spare "host/native/io.lisp"))
(defun fnn-log-line (line)
  (declare (ignorable line))
  (harness-stub-reached 'fnn-log-line "host/native/io.lisp"))
(defun fnn-mux-budget-install (service tls-context)
  (declare (ignorable service tls-context))
  (harness-stub-reached 'fnn-mux-budget-install "host/native/mux.lisp"))
(defun fnn-mux-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-mux-drained-p "host/native/mux.lisp"))
(defun fnn-mux-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-mux-start "host/native/mux.lisp"))
(defun fnn-out (control &rest args)
  (declare (ignorable control args))
  (harness-stub-reached 'fnn-out "host/native/io.lisp"))
(defun fnn-owner-accept (service listener once)
  (declare (ignorable service listener once))
  (harness-stub-reached 'fnn-owner-accept "host/native/owner.lisp"))
(defun fnn-owner-action (name &rest args)
  (declare (ignorable name args))
  (harness-stub-reached 'fnn-owner-action "host/native/owner.lisp"))
(defun fnn-owner-actor-join (service worker &key timeout)
  (declare (ignorable service worker timeout))
  (harness-stub-reached 'fnn-owner-actor-join "host/native/owner.lisp"))
(defun fnn-owner-cold-shutdown (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-cold-shutdown "host/native/owner.lisp"))
(defun fnn-owner-drain-service (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-drain-service "host/native/owner.lisp"))
(defun fnn-owner-feed-close-all (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-feed-close-all "host/native/owner.lisp"))
(defun fnn-owner-journal-open (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-journal-open "host/native/owner.lisp"))
(defun fnn-owner-measure-report ()
  (harness-stub-reached 'fnn-owner-measure-report "host/native/owner.lisp"))
(defun fnn-owner-output-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-output-drained-p "host/native/owner.lisp"))
(defun fnn-owner-peer-flight-startup (service capture)
  (declare (ignorable service capture))
  (harness-stub-reached 'fnn-owner-peer-flight-startup "host/native/owner.lisp"))
(defun fnn-owner-refresh-read-octets (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-refresh-read-octets "host/native/owner.lisp"))
(defun fnn-owner-release-recovery-garbage ()
  (harness-stub-reached 'fnn-owner-release-recovery-garbage "host/native/owner.lisp"))
(defun fnn-owner-retain-run-authority (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-retain-run-authority "host/native/owner.lisp"))
(defun fnn-owner-retire-final-report (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-retire-final-report "host/native/owner.lisp"))
(defun fnn-owner-run-startup-hooks (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-run-startup-hooks "host/native/owner.lisp"))
(defun fnn-owner-service-nursery ()
  (harness-stub-reached 'fnn-owner-service-nursery "host/native/owner.lisp"))
(defun fnn-owner-snapshot-jobs-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-snapshot-jobs-drained-p "host/native/owner.lisp"))
(defun fnn-owner-space-prime (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-space-prime "host/native/owner.lisp"))
(defun fnn-owner-start-committer (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-start-committer "host/native/owner.lisp"))
(defun fnn-owner-start-tls-accept (service listener &optional implicit-tls)
  (declare (ignorable service listener implicit-tls))
  (harness-stub-reached 'fnn-owner-start-tls-accept "host/native/owner.lisp"))
(defun fnn-owner-stop-service (service exit-code)
  (declare (ignorable service exit-code))
  (harness-stub-reached 'fnn-owner-stop-service "host/native/owner.lisp"))
(defun fnn-owner-syncer-drained-p (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-syncer-drained-p "host/native/owner.lisp"))
(defun fnn-owner-wait-workers (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-owner-wait-workers "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-joined (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-joined "host/native/owner.lisp"))
(defun fnn-payload-lifecycle-start (service)
  (declare (ignorable service))
  (harness-stub-reached 'fnn-payload-lifecycle-start "host/native/owner.lisp"))
(defun fnn-peer-flight-bank-drained (bank)
  (declare (ignorable bank))
  (harness-stub-reached 'fnn-peer-flight-bank-drained "host/native/catchup-spool.lisp"))
(defun fnn-socket-shut (socket)
  (declare (ignorable socket))
  (harness-stub-reached 'fnn-socket-shut "host/native/io.lisp"))
;;; ---- derived stubs: END ----
(declaim (declaration xargs))
(defmacro fnn-native-with-observation ((enabled capacity) &body body)
  (declare (ignore enabled capacity)) `(progn ,@body))
(defun source-forms (path names)
  (with-open-file (in path)
    (loop for form = (read in nil :eof) until (eq form :eof)
          when (and (consp form) (eq (car form) 'defun) (member (second form) names))
          do (progn (eval form) (setf names (remove (second form) names)))
          finally (assert (null names)))))
(source-forms "books/owner-retire-settlement.lisp"
 '(fn-ort-report-close-action fn-ort-store-close-action fn-ort-service-settlement-action
   fn-ort-service-start-action fn-ort-service-claim-action))
(defvar *fnn-owner-caller-reservation* nil)
(defvar *fnn-owner-retained-service* nil)
(defvar *fnn-owner-retained-settlement* :held)
(defvar *fnn-owner-reserving-thread* nil)
(defvar *fnn-log-writer* nil)
(defvar *fnn-log-queue-mutex* (sb-thread:make-mutex))
(defvar *fnn-owner-log-fd* nil)
(defvar *fnn-owner-time-service* nil)
(defvar *fnn-owner-measure* nil)
(defvar *fnn-sigterm-owner-active* nil)
(defvar *fnn-sigterm-requested* nil)
(defvar *fnn-sigterm-wakeup-fd* nil)
(defparameter +fnn-exit-ok+ 0)
(defparameter +fnn-exit-uncertain+ 3)
(defparameter +fnn-owner-listen-backlog+ 4)
(defvar *events* nil)
(defvar *mode* nil)
(defvar *installed* nil)
(defvar *workers* nil)
(defvar *fnn-arena-release-custody* nil)
(defvar *fnn-cold-workers* nil)
(defvar *fnn-extent-lock* (sb-thread:make-mutex))
(defmacro fnn-with-observed-mutex ((lock label) &body body)
  (declare (ignore label)) `(sb-thread:with-mutex (,lock) ,@body))
(source-forms (or (fourth sb-ext:*posix-argv*) "host/native/extent.lisp")
 '(fnn-extent-executor-drained-p))
(source-forms (or (fifth sb-ext:*posix-argv*) "host/native/io.lisp")
 '(fnn-arena-return-observation))
(defstruct (fnn-owner-service (:constructor %make-fnn-owner-service)) store)
(defstruct (fnn-store (:constructor %make-fnn-store)) fenced)
(define-condition fixture-stop (error) ())
(define-condition fixture-fault (error) ())
(define-condition fixture-uncertain (error) ())
(defun fnn-core (name &rest args) (apply name args))
(defun fnn-fault (&rest args) (declare (ignore args)) (error 'fixture-fault))
(defun fnn-indeterminate (&rest args) (declare (ignore args)) (error 'fixture-uncertain))
(defun fnn-gc-nursery-octets () 1048576)
(defvar *peer-policy* nil)
(defvar *peer-grant* nil)
(defun fnn-peer-flight-profile (root) (declare (ignore root)) *peer-policy*)
(defun fnn-developer-selector (&rest args) (declare (ignore args)) nil)
(defun fnn-trace-configure () nil)
(source-forms (or (sixth sb-ext:*posix-argv*) "host/native/owner.lisp")
 '(fnn-owner-page-read-startup))
(defparameter *actual-startup* (symbol-function 'fnn-owner-page-read-startup))
(defun fnn-log-writer-start () (push :log-start *events*))
(defun fnn-owner-log-settlement () (push :log-join *events*) :joined)
(defun fnn-owner-journal-close () (push :journal-close *events*) :closed)
(defun fnn-owner-page-read-startup (root connections cold output retain)
  (declare (ignore root connections cold output))
  (push :preflight *events*)
  (when (eq *mode* :refused) (error 'fixture-stop))
  (setf *installed* t)
  (funcall retain)
  (push :pool-installed *events*)
  (when (eq *mode* :table-error) (error 'fixture-stop))
  (setf *workers* t *fnn-cold-workers* '(:owned))
  (push :executor-start *events*)
  :started)
(defun fnn-owner-install (&rest args)
  (declare (ignore args))
  (assert (and *installed* *workers*))
  (push :store-open *events*)
  ;; Recovery fails before publishing a service, the old blind cleanup gap.
  (error 'fixture-stop))
(defun fnn-extent-executor-stop ()
  (push :executor-join *events*)
  (when (eq *mode* :join-error) (error 'fixture-stop))
  (unless (eq *mode* :joined-debt)
    (setf *workers* nil *fnn-cold-workers* nil)))
(source-forms (or (second sb-ext:*posix-argv*) "host/native/owner.lisp")
 '(fnn-owner-claim-run-authority fnn-owner-store-settlement fnn-owner-run))
(defun run-case (mode expected retainedp &optional (workers-held-p retainedp))
  (let ((*events* nil) (*mode* mode) (*installed* nil) (*workers* nil)
        (*fnn-cold-workers* nil)
        (*fnn-arena-release-custody* (and (eq mode :arena-debt) (vector :calling)))
        (*fnn-owner-retained-service* nil) (*fnn-owner-retained-settlement* :held)
        (*fnn-owner-reserving-thread* nil))
    (handler-case (fnn-owner-run "/scratch" 0 nil 2)
      (fixture-stop () nil))
    (assert (equal (reverse *events*) expected))
    (assert (eql (and *fnn-owner-retained-service* t) retainedp))
    (assert (eql *workers* workers-held-p))
    (format t "~a events=~s retained=~s~%" mode (reverse *events*) retainedp)))
(run-case :recovery-error
 '(:log-start :preflight :pool-installed :executor-start :store-open
   :executor-join :log-join :journal-close) nil)
(run-case :refused '(:log-start :preflight :log-join :journal-close) nil)
(run-case :table-error
 '(:log-start :preflight :pool-installed :executor-join :log-join :journal-close) nil)
(run-case :arena-debt
 '(:log-start :preflight :pool-installed :executor-start :store-open :executor-join) t nil)
(run-case :joined-debt
 '(:log-start :preflight :pool-installed :executor-start :store-open :executor-join) t)
(run-case :join-error
 '(:log-start :preflight :pool-installed :executor-start :store-open :executor-join) t)

;; A failing install can keep its Store in the existing authority carrier
;; before returning SERVICE. NIL at the caller is then not physical absence.
(when (third sb-ext:*posix-argv*)
  (source-forms (third sb-ext:*posix-argv*) '(fnn-owner-store-settlement)))
(let* ((store (%make-fnn-store))
       (carrier (%make-fnn-owner-service :store store))
       (*fnn-owner-retained-service* carrier)
       (closes 0))
  (setf (symbol-function 'fnn-store-close)
        (lambda (actual) (assert (eq actual store)) (incf closes)))
  (assert (eq (fnn-owner-store-settlement nil :joined) :joined))
  (assert (= closes 1))
  (assert (null *fnn-owner-retained-service*)))
(let* ((store (%make-fnn-store))
       (carrier (%make-fnn-owner-service :store store))
       (*fnn-owner-retained-service* carrier)
       (closes 0))
  (setf (symbol-function 'fnn-store-close)
        (lambda (actual) (assert (eq actual store)) (incf closes) (error 'fixture-stop)))
  (assert (eq (fnn-owner-store-settlement nil :joined) :held))
  (assert (= closes 1))
  (assert (fnn-store-fenced store))
  (assert (eq *fnn-owner-retained-service* carrier)))
(format t "PASS retained startup Store close observation~%")

;; The actual startup helper carries raw observations to the model, then
;; consumes only admitted capacities. Deliberate core results exercise the
;; native fault/refusal contract; numerical funding is the ACL2 book's test.
(defvar *plan* nil)
(defvar *install-word* :installed)
(defun fnn-heap-store-profile (root) (assert (equal root "/scratch")) :profile)
(defun fnn-heap-image-observation () '(54321 . 1234))
(defun fnn-heap-rlimit (resource) (assert (= resource #+linux 7 #-linux 8)) 1024)
(defun fnn-extent-cache-limit () 32)
(defun fnn-heap-observations () '(8589934592))
(defun fnn-core (name &rest args)
  (case name
    (fn-pio-direct-workers 4)
    (fn-prstartup-default-plan-with-peer
     (assert (equal (cdr args) (append '(1234 :profile (54321 . 1234) 1048576 nil nil 2 "/scratch" 4 32 1024) (list *peer-policy*))))
     (assert (plusp (first args)))
     (push :preflight *events*) *plan*)
    (fn-prstartup-peer-native-grant
     (assert (equal (cdr args) (list :profile '(54321 . 1234) 1048576 nil 2 *plan* *peer-policy* '(8589934592))))
     (push :peer-check *events*) *peer-grant*)
    (fn-prstartup-peer-native-refusal-line "peer native reservation not held")
    (fn-prstartup-status (first *plan*))
    (fn-prstartup-planp (equal *plan* '(:admitted :budget :baseline 11 12 99 4 21)))
    (fn-prstartup-refusal-line "cold startup refused")
    (fn-prstartup-install-status (if (eq (first args) :already-installed) :refused :fault))
    (fn-prstartup-install-refusal-line "cold pool already installed")
    (fn-prstartup-file-capacity 16)
    (fn-prstartup-decoded-workers 4)
    (fn-prstartup-cache-capacity 33)
    (otherwise (error "unexpected model call ~s" name))))
(defun fnn-core-page-read-pool (name &rest args)
  (assert (eq name 'fn-owner-page-read-install-default))
  (assert (equal args (list *plan*)))
  (push :install *events*) (list *install-word*))
(defun fnn-refuse (&rest args) (declare (ignore args)) (error 'fixture-stop))
(defun fnn-extent-pool-storage-start (files workers cache)
  (assert (equal (list files workers cache) '(16 4 33)))
  (push :tables *events*))
(defun fnn-cold-guard-cache-prepare (plan)
  (assert (eq plan *plan*)) (push :guards *events*))
(defun fnn-extent-executor-start (workers plan)
  (assert (= workers 4)) (assert (eq plan *plan*)) (push :workers *events*))
(defun helper-case (label plan word expected events)
  (let ((*plan* plan) (*install-word* word) (*events* nil))
    (assert
     (= (handler-case
            (progn (funcall *actual-startup* "/scratch" 2 nil nil
                            (lambda () (push :retain *events*))) 0)
          (fixture-stop () 1) (fixture-uncertain () 3) (fixture-fault () 4)) expected))
    (assert (equal (reverse *events*) events))
    (format t "~a events=~s code=~d~%" label (reverse *events*) expected)))
(helper-case :startup-order '(:admitted :budget :baseline 11 12 99 4 21) :installed
  0 '(:preflight :install :retain :tables :guards :workers))
(let ((*fnn-arena-release-custody* (vector :calling)))
  (helper-case :prior-arena-debt '(:admitted :budget :baseline 11 12 99 4 21) :installed 3 '(:retain)))
(helper-case :startup-refusal '(:refused :insufficient) :installed 1 '(:preflight))
(helper-case :malformed-admitted '(:admitted) :installed 4 '(:preflight))
(helper-case :unknown-status '(:unexpected) :installed 4 '(:preflight))
(helper-case :already-installed '(:admitted :budget :baseline 11 12 99 4 21)
  :already-installed 1 '(:preflight :install))
(helper-case :invalid-installer '(:admitted :budget :baseline 11 12 99 4 21)
  :unexpected 4 '(:preflight :install))
(format t "PASS actual owner pool pre-open ordering and orphan cleanup~%")

(let ((*peer-policy* :policy) (*peer-grant* '(:refused :peer-native-reservation-not-held)))
 (helper-case :peer-native-refusal '(:admitted :budget :baseline 11 12 99 4 21)
              :installed 1 '(:preflight :peer-check)))
(let* ((*peer-policy* :policy)
       (capture '(1000 100 :policy 8192 1024))
       (*peer-grant* (list :hold capture))
       (*plan* '(:admitted :budget :baseline 11 12 99 4 21))
       (*install-word* :installed) (*events* nil))
 (multiple-value-bind (plan returned)
     (funcall *actual-startup* "/scratch" 2 nil nil (lambda () (push :retain *events*)))
   (assert (eq plan *plan*)) (assert (eq returned capture)))
 (assert (equal (reverse *events*) '(:preflight :peer-check :install :retain :tables :guards :workers))))
