;;; Actual accepted-plan transport and startup caller ordering. ACL2 producer
;;; methods are recording boundaries here; Foundations owns actual typed probe.
(load "tests/native_actor_envelope_raw.lisp")
(in-package "ACL2")

;;; ---- derived stubs: BEGIN (python3 tools/harness_check.py --write-stubs; do not edit) ----
(define-condition harness-stub-reached (serious-condition)
  ((name :initarg :name :reader harness-stub-reached-name)
   (source :initarg :source :reader harness-stub-reached-source))
  (:report (lambda (c s)
             (format s "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it"
                     (harness-stub-reached-name c) (harness-stub-reached-source c)))))
(defun harness-stub-reached (name source)
  (format *error-output* "harness: host function ~(~a~) (~a) was reached; this harness neither stubs nor extracts it~%"
          name source)
  (finish-output *error-output*)
  (error 'harness-stub-reached :name name :source source))
(defun fnn-control-close (control service)
  (declare (ignorable control service))
  (harness-stub-reached 'fnn-control-close "host/native/control.lisp"))
(defun fnn-control-start (control service posting-enabledp)
  (declare (ignorable control service posting-enabledp))
  (harness-stub-reached 'fnn-control-start "host/native/control.lisp"))
(defun fnn-control-stop (control service)
  (declare (ignorable control service))
  (harness-stub-reached 'fnn-control-stop "host/native/control.lisp"))
(defun fnn-operator-run-final-settlement (cleanup-okp)
  (declare (ignorable cleanup-okp))
  (harness-stub-reached 'fnn-operator-run-final-settlement "host/native/operator-live.lisp"))
(defun fnn-owner-open-log (path)
  (declare (ignorable path))
  (harness-stub-reached 'fnn-owner-open-log "host/native/owner.lisp"))
(defun fnn-owner-syncer-physical (service grant receipt)
  (declare (ignorable service grant receipt))
  (harness-stub-reached 'fnn-owner-syncer-physical "host/native/owner.lisp"))
(defun fnn-string-octets (string)
  (declare (ignorable string))
  (harness-stub-reached 'fnn-string-octets "host/native/io.lisp"))
(defun fnn-tls-close-context (context)
  (declare (ignorable context))
  (harness-stub-reached 'fnn-tls-close-context "host/native/tls.lisp"))
(defun fnn-tls-start-context (certificate-path private-key-path)
  (declare (ignorable certificate-path private-key-path))
  (harness-stub-reached 'fnn-tls-start-context "host/native/tls-reload.lisp"))
(defun fnn-web-start (service plan tls-context)
  (declare (ignorable service plan tls-context))
  (harness-stub-reached 'fnn-web-start "host/native/web-host.lisp"))
;;; ---- derived stubs: END ----
(deftype fnn-octets () '(simple-array (unsigned-byte 8) (*)))
(defun fnn-octets (x) (if (typep x 'fnn-octets) x
                        (make-array (length x) :element-type '(unsigned-byte 8) :initial-contents x)))
(defun fnn-octet-list-p (x) (and (listp x) (every (lambda (n) (typep n '(unsigned-byte 8))) x)))
(defun fnn-octet-list (x) (coerce x 'list))
(defun fnn-octets-string (x) (map 'string #'code-char x))
(defvar *fnn-owner-startup-hooks* nil)
(defvar *fnn-owner-start-hooks* nil)
(defvar *fnn-owner-stop-hooks* nil)
(defvar *fnn-owner-close-hooks* nil)
(defvar *fnn-mux-control-clients* nil)
(defvar *fnn-owner-log-fd* nil)
(defvar *fnn-owner-log-path* nil)
(defvar *fnn-owner-log-mutex* (sb-thread:make-mutex))
(defvar *fnn-health-min-percent* nil)
(defvar *startup-cold* '(33554432 2 1048576))
(defvar *startup-output* '(16777216 1048576))
(defvar *startup-calls* nil)
(defvar *startup-run-args* nil)
(defvar *startup-refuse* nil)
(defvar *startup-allocations* 0)
(defvar *startup-ledger* nil)
(load-deployed-forms "books/output-reservation.lisp" '((defun fn-orv-startup-slots)))
(defun nfix (x) (if (and (integerp x) (<= 0 x)) x 0))
(defun fnn-core (name &rest args)
  (push (cons name args) *startup-calls*)
  (case name
    (fn-native-operator-host-result-run-auth-path-octets nil)
    ((fn-native-operator-host-result-run-auth-requiredp fn-native-operator-host-result-run-auth-protected-onlyp) nil)
    (fn-native-operator-host-result-health-min-percent 10)
    (fn-native-operator-host-result-run-store-octets '(115 116 111 114 101))
    (fn-native-operator-host-result-run-listener-host-octets '(49 50 55 46 48 46 48 46 49))
    (fn-native-operator-host-result-run-listener-port 1119)
    (fn-native-operator-host-result-run-oncep nil)
    (fn-native-operator-host-result-run-max-connections 3)
    (fn-native-operator-host-result-run-control-path-octets '(47 116 109 112 47 99 116 114 108))
    (fn-native-operator-host-result-run-posting-enabledp t)
    (fn-native-operator-host-result-run-cold-resources *startup-cold*)
    (fn-native-operator-host-result-run-output-resources *startup-output*)
    (fn-native-control-host-max-active-clients 4)
    (fn-native-control-host-lease-path '(47 116 109 112 47 108 101 97 115 101))
    (fn-native-config-host-listener-addresses '((:inet (127 0 0 1))))
    (fn-native-health-host-run-stopped-line nil)
    (fn-orv-startup-slots (apply #'fn-orv-startup-slots args))
    (fn-orv-startup-grant (if *startup-refuse* '(:refused :output-pool-not-held) '(:hold)))
    (create-fn-resource-ledger (incf *startup-allocations*) (setq *startup-ledger* (list :private-ledger)))
    (fn-heap-figure-octets 1000000)
    (fn-ort-log-close-exit (apply #'fn-ort-log-close-exit args))
    (otherwise (error "unrecorded startup subject ~s" name))))
(defun fnn-call (name &rest args)
  (push (cons name args) *startup-calls*)
  (check (eq name 'fn-rlo-install) "actual startup invokes frozen output installer")
  (list :installed (car (last args))))
(defun fnn-owner-run (&rest args) (setq *startup-run-args* args) 0)
(defun fnn-operator-optional-path (&rest args) (declare (ignore args)) nil)
(defun fnn-web-run-hooks (&rest args) (declare (ignore args)) nil)
(defun fnn-native-auth-startup-hook (&rest args) (declare (ignore args)) :auth-hook)
(defun fnn-operator-status-of-exit-code (code) (declare (ignore code)) :ok)
(defun fnn-operator-emit-status (&rest args) (declare (ignore args)) nil)
(defun fnn-operator-log-run-line (&rest args) (declare (ignore args)) nil)
(defun fnn-control-stop-cut-armed-p () nil)
(defun fnn-owner-control-test-fault () nil)
(defun fnn-post-entry-fault (x) (declare (ignore x)) nil)
(defun fnn-state-checkpoint-test-fault () nil)
(setq +fnn-exit-ok+ 0)
(defvar *fnn-owner-last-fault* nil)
(defun fnn-feed-service-start (&rest args) (declare (ignore args)) nil)
(defun fnn-feed-service-wake (&rest args) (declare (ignore args)) nil)
(defun fnn-feed-service-close (&rest args) (declare (ignore args)) nil)
(defun fnn-pull-service-start (&rest args) (declare (ignore args)) nil)
(defun fnn-pull-service-wake (&rest args) (declare (ignore args)) nil)
(defun fnn-pull-service-close (&rest args) (declare (ignore args)) nil)
(defun fnn-web-close-face (&rest args) (declare (ignore args)) nil)
;; The run's final log/Store settlement (fnn-operator-run-final-settlement)
;; is outside this boundary: the owner run above is a recording stub, so
;; nothing was opened to settle.  Recorded, never decided here.
(defvar *startup-settlements* nil)
(defun fnn-operator-run-final-settlement (cleanup-okp)
  (push cleanup-okp *startup-settlements*) :joined)
;; ACL2's exit over that settlement (books/owner-retire-settlement.lisp).
(load-deployed-forms "books/owner-retire-settlement.lisp" '((defun fn-ort-log-close-exit)))
(defun fnn-exit-code-for (condition) (error condition))
(load-deployed-forms "host/native/control-transport.lisp"
 '((defstruct (fnn-control-state (:constructor %make-fnn-control-state)))))
(load-deployed-forms "host/native/control.lisp" '((defun fnn-control-owner-run-normalized)))
(load-deployed-forms "host/native/owner.lisp"
 '((defun fnn-owner-run-normalized) (defun fnn-owner-output-install)))
;; The run's cleanup is the shipped unwind macro.
(load-deployed-forms "host/native/io.lisp" '((defmacro fnn-unwind-cleanups)))
(load-deployed-forms "host/native/operator-live.lisp" '((defun fnn-operator-execute-run)))
(check (= 0 (fnn-operator-execute-run :accepted-result)) "actual accepted-plan transport reaches owner")
(check (and (eq (nth 11 *startup-run-args*) *startup-cold*)
            (eq (nth 12 *startup-run-args*) *startup-output*))
       "same accepted cold/output descriptor objects survive operator/control/normalized owner chain")
(dolist (subject '(fn-native-operator-host-result-run-cold-resources fn-native-operator-host-result-run-output-resources))
  (check (equal (cdr (assoc subject *startup-calls*)) '(:accepted-result)) "both resources captured from the same actual result"))
(let ((service (%make-fnn-owner-service :cold-resources *startup-cold*
                                      :output-resources *startup-output* :output-slots 5)))
  (setq *startup-calls* nil *startup-allocations* 0)
  (fnn-owner-output-install service 64000000 1000000)
  (check (and (= *startup-allocations* 1)
              (eq (fnn-owner-service-output-ledger service) *startup-ledger*)
              (equal (subseq (cdr (assoc 'fn-rlo-install *startup-calls*)) 0 5)
                     (list 64000000 1000000 *startup-cold* *startup-output* 5)))
         "actual startup installer retains actual private ledger and exact captured funding inputs")
  (let ((ordered (reverse *startup-calls*)))
    (check (equal (mapcar #'car ordered) '(fn-orv-startup-grant create-fn-resource-ledger fn-rlo-install))
           "headroom grant precedes private constructor/resize")))
(let* ((*startup-refuse* t) (*startup-allocations* 0)
       (service (%make-fnn-owner-service :cold-resources *startup-cold*
                  :output-resources *startup-output* :output-slots 5)))
  (check (handler-case (progn (fnn-owner-output-install service 1 1000000) nil)
           (fnn-store-error () t)) "insufficient captured headroom refuses")
  (check (and (zerop *startup-allocations*) (null (fnn-owner-service-output-ledger service)))
         "headroom refusal allocates no private ledger"))
(let ((*startup-allocations* 0) (service (%make-fnn-owner-service)))
  (fnn-owner-output-install service 1 1000000)
  (check (zerop *startup-allocations*) "absent staged policy creates no output pool"))
(format t "native_output_startup_raw: PASS actual accepted-plan chain/headroom-before-allocation~%")

;; Actual mux hold is the caller of both worker and output installers.
(defvar *startup-budget-word* :hold)
(defvar *startup-syncer-installed* nil)
(defun fnn-mux-thread-count (service) (declare (ignore service)) 12)
(defun fnn-mux-thread-stack-octets () 1048576)
(defun fnn-store-config (store) (declare (ignore store)) :captured-store-profile)
(defun fnn-heap-machine-octets () 1000000000)
(defun fnn-heap-core-octets () 1000)
(defparameter +fnn-gc-nursery-octets+ 2000)
(defun fnn-owner-core (name &rest args)
  (push (cons name args) *startup-calls*)
  (check (eq name 'fn-owner-connection-budget) "actual mux qualification subject")
  *startup-budget-word*)
(defun fnn-owner-serialized (service cid thunk &optional class)
  (declare (ignore service cid class)) (funcall thunk))
(defun fnn-owner-syncer-install (service threads stack)
  (declare (ignore service)) (setq *startup-syncer-installed* (list threads stack)))
(defun fnn-global (name)
  (check (eq name 'fn-owner-connection-budget-line) "actual budget diagnostic subject") nil)
(defun fnn-log-line (line) (declare (ignore line)) nil)
(load-deployed-forms "host/native/mux.lisp" '((defun fnn-mux-budget-install)))
(let* ((*startup-calls* nil) (*startup-syncer-installed* nil) (*startup-allocations* 0)
       (service (%make-fnn-owner-service :store :store :cold-resources *startup-cold*
                  :output-resources *startup-output* :output-slots 5)))
  (check (eq (fnn-mux-budget-install service nil) :hold) "actual mux hold invokes installers")
  (check (and (equal *startup-syncer-installed* '(12 1048576))
              (= *startup-allocations* 1)
              (equal (cdr (assoc 'fn-heap-figure-octets *startup-calls*))
                     '(:captured-store-profile 1000 2000)))
         "actual mux installer captures pre-extension store figure and installs held output pool"))
(let* ((*startup-budget-word* :refused) (*startup-syncer-installed* nil) (*startup-allocations* 0)
       (service (%make-fnn-owner-service :store :store :cold-resources *startup-cold*
                  :output-resources *startup-output* :output-slots 5)))
  (check (handler-case (progn (fnn-mux-budget-install service nil) nil)
           (fnn-store-error () t)) "actual mux capacity refusal remains refusal")
  (check (and (null *startup-syncer-installed*) (zerop *startup-allocations*))
         "refused parent capacity grants neither child projection"))
(format t "native_output_startup_raw: PASS actual mux hold/refusal caller~%")
