;;; Actual native counterpart/registered-creator discrimination. Not a proof
;;; or a whole-plan allocation tariff; source-loaded warnings stay in the log.
(in-package "ACL2")
(require :sb-posix)
(require :sb-bsd-sockets)

(defun fnout-load-host-forms (path wanted)
  (let ((missing (copy-list wanted)))
    (with-open-file (stream path)
      (loop for form = (read stream nil :eof) until (eq form :eof)
            when (and (consp form)
                      (member (list (car form) (cadr form)) wanted :test #'equal))
              do (eval form)
                 (setf missing (remove (list (car form) (cadr form)) missing :test #'equal))))
    (when missing (error "output custody host forms missing: ~s" missing))))

(fnout-load-host-forms "host/native/io.lisp"
 '((define-condition fnn-store-error) (define-condition fnn-store-fault)
   (define-condition fnn-entry-guard-fault) (defun fnn-fault)
   (defun fnn-counterpart) (defun fnn-install-raw-dispatch)
   (defun fnn-dispatch-function) (defun fnn-guard-conjuncts)
   (defun fnn-entry-guard-spec) (defun fnn-entry-guard-describe)
   (defun fnn-entry-guard) (defun fnn-call) (defun fnn-core)))
(defvar *fnn-dispatch-counterpart* nil)
(defvar *fnn-raw-dispatch* (make-hash-table :test 'eq))
(defvar *fnn-startup-creators* (make-hash-table :test 'eq))
(defvar *fnn-entry-guard-specs* (make-hash-table :test 'eq))
(defvar *fn-entry-guard-kinds* nil)
(fnn-install-raw-dispatch :report nil)

(let* ((ledger (fnn-core 'create-fn-resource-ledger))
       (policy '(16777216 1048576))
       (dynamic (sb-ext:dynamic-space-size))
       (core-dynamic (sb-kernel:dynamic-usage))
       (store-need (fnn-core 'fn-heap-figure-octets *fn-heap-small-profile* core-dynamic 0))
       (text (make-string 1048576 :initial-element #\X)))
  ;; The private constructor used the actual validated creator route. All
  ;; semantics below use ordinary executable counterparts, no raw escape.
  (setq *fnn-dispatch-counterpart* t)
  (dolist (name '(fn-orv-startup-grant fn-rlo-install fn-rlo-issue
                 fn-rlo-output fn-rlo-physical fn-rlo-drainedp fn-sl-step))
    (unless (eq (fnn-dispatch-function name) (fnn-counterpart name))
      (error "output probe did not use normal semantic counterpart: ~s" name)))
  (unless (eq (first (fnn-call 'fn-rlo-install dynamic store-need nil policy 4 ledger)) :installed)
    (error "actual captured heap cannot fund output fixture"))
  (unless (fnn-core 'fn-rlo-drainedp ledger) (error "fresh output pool not drained"))
  (let* ((issued (fnn-call 'fn-rlo-issue 7 11 8 :none ledger))
         (token (second issued))
         (window (fnn-call 'fn-sl-step (fn-sl-start text) 128)))
    (unless (and (eq (first issued) :drawn) (= (length (first window)) 128)
                 (eq (first (second window)) text)
                 (not (fnn-core 'fn-rlo-drainedp ledger)))
      (error "actual renderer window was not charged/retained"))
    (unless (eq (first (fnn-call 'fn-rlo-output token 8 :timeout ledger)) :pending)
      (error "timeout authorized output release"))
    (unless (eq (first (fnn-call 'fn-rlo-output token 9 :discarded ledger)) :stale)
      (error "wrong window operation generation authorized release"))
    (setq window nil)
    (unless (and (eq (first (fnn-call 'fn-rlo-output token 8 :discarded ledger)) :settled)
                 (fnn-core 'fn-rlo-drainedp ledger)
                 (eq (first (fnn-call 'fn-rlo-output token 8 :discarded ledger)) :stale))
      (error "metadata window discard did not settle exactly once")))
  (let* ((issued (fnn-call 'fn-rlo-issue 7 12 9 :issued ledger))
         (token (second issued))
         (window (fnn-call 'fn-sl-step (fn-sl-start text) 128))
         (release (sb-thread:make-semaphore :count 0))
         (entered (sb-thread:make-semaphore :count 0))
         (worker (sb-thread:make-thread
                  (lambda ()
                    (let ((held window))
                      (sb-thread:signal-semaphore entered)
                      (sb-thread:wait-on-semaphore release)
                      (length (first held)))))))
    (unwind-protect
         (progn
           (sb-thread:wait-on-semaphore entered)
           (setq window nil)
           (unless (and (sb-thread:thread-alive-p worker)
                        (eq (first (fnn-call 'fn-rlo-output token 9 :drained ledger)) :pending)
                        (eq (first (fnn-call 'fn-rlo-physical token 9 :timeout ledger)) :pending)
                        (not (fnn-core 'fn-rlo-drainedp ledger)))
             (error "drain/timeout released physically held output custody"))
           (sb-thread:signal-semaphore release)
           (unless (= (sb-thread:join-thread worker) 128) (error "physical worker result changed"))
           (unless (and (not (sb-thread:thread-alive-p worker))
                        (eq (first (fnn-call 'fn-rlo-physical token 9 :terminal ledger)) :settled)
                        (fnn-core 'fn-rlo-drainedp ledger))
             (error "actual physical join did not release completed output custody")))
      (when (sb-thread:thread-alive-p worker)
        (sb-thread:signal-semaphore release)
        (sb-thread:join-thread worker)))))
(format t "~%native_output_custody_raw: PASS actual captured funding, registered private creator, normal semantic counterparts, renderer custody and real physical join~%")
