;;; The shipped ION caller: exact ACL2 seconds precede every publication;
;;; helper refusal, lost observation and durable bound observation differ.
(require :sb-posix)
(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(define-condition ion-answer (error) ((kind :initarg :kind :reader answer-kind)))
(defun fnn-refuse (&rest x) (declare (ignore x)) (error 'ion-answer :kind :refused))
(defun fnn-fault (&rest x) (declare (ignore x)) (error 'ion-answer :kind :fault))
(defun fnn-indeterminate (&rest x) (declare (ignore x)) (error 'ion-answer :kind :uncertain))
(defvar *seconds* 3600)
(defvar *helper-exit* 0)
(defvar *observation-valid* t)
(defvar *events* nil)
(defun fnn-core-state (name &rest x)
 (declare (ignore x))
 (case name
  (fn-workflow-ion-helper-seconds (push :lifetime *events*) *seconds*)
  (fn-workflow-ion-attempt-plan '(nil (:attempt 2 0 "work" "attempt" 0 "local" "peer" "policy" 3600000)))
  (fn-workflow-take-submit t)
  (fn-workflow-ion-route-record '(:ion-route "work" "attempt" 0 "dtn://fn-b/" "ipn:2.1" "ipn:1.1"))
  (fn-workflow-ion-request-adu '(1 2 3))
  (fn-workflow-ion-observation-record (and *observation-valid* '(:ion-observed "work" "attempt" 0 "dtn://fn-b/" "ipn:2.1" "ipn:1.1" 42 7)))
  (otherwise (error "unexpected core ~s" name))))
(defun fnn-workflow-ion-private-directory (x) (push :directory *events*) x)
(defun fnn-app-publish (journal record &key reserve-resolution)
 (declare (ignore journal reserve-resolution)) (push (first record) *events*))
(defun fnn-out (&rest x) (declare (ignore x)))
(defun fnn-octet-list-p (x) (equal x '(1 2 3)))
(defun fnn-octet-list (x) x)
(defun fnn-join (a b) (concatenate 'string a "/" b))
(defun fnn-random-hex (x) (declare (ignore x)) "random")
(defun fnn-workflow-ion-request-file (dir adu) (declare (ignore dir adu)) (push :request-file *events*) "/request")
(defun fnn-workflow-ion-run-helper (helper own destination peer request seconds observation)
 (declare (ignore helper observation))
 (assert (equal (list own destination peer request seconds)
                '("ipn:1.1" "ipn:2.1" "dtn://fn-b/" "/request" 3600)))
 (push :helper *events*) *helper-exit*)
(defun fnn-read-regular-bounded (&rest x) (declare (ignore x)) '(1 2 3))
(defun fnn-unlink (x) (declare (ignore x)))
(defun fnn-fsync-dir (x) (declare (ignore x)))
(with-open-file (stream "host/native/workflow.lisp")
 (loop for form = (read stream nil :eof)
       when (eq form :eof) do (error "shipped caller missing")
       when (and (consp form) (eq (car form) 'defun) (eq (second form) 'fnn-workflow-ion-submit))
       do (eval form) (return)))
(defun run-case (seconds exit valid)
 (let ((*seconds* seconds) (*helper-exit* exit) (*observation-valid* valid) (*events* nil))
  (let ((answer (handler-case
                 (fnn-workflow-ion-submit :journal 2 0 "work" "attempt" "ipn:2.1" "ipn:1.1" "/helper" "/private")
                 (ion-answer (e) (answer-kind e)))))
   (values answer (reverse *events*)))))
(multiple-value-bind (answer events) (run-case nil 0 t)
 (assert (eq answer :refused)) (assert (equal events '(:lifetime))))
(multiple-value-bind (answer events) (run-case 3600 0 t)
 (assert (eq answer :observed))
 (assert (equal events '(:lifetime :directory :attempt :outcome :ion-route :request-file :helper :ion-observed))))
(dolist (exit '(1 3 5 nil))
 (multiple-value-bind (answer events) (run-case 3600 exit t)
  (assert (eq answer (case exit (1 :refused) (5 :fault) (otherwise :uncertain))))
  (assert (not (member :ion-observed events))) (assert (member :helper events))))
(multiple-value-bind (answer events) (run-case 3600 0 nil)
 (assert (eq answer :uncertain)) (assert (not (member :ion-observed events))))
(format t "PASS shipped ION caller: exact seconds, no-publication lifetime refusal, helper outcome separation.~%")
