; Run after tools/owner_carrier/world.lisp in a small actual ACL2 world.
(in-package "ACL2")
(defun ocwt-direct (state)
  (declare (xargs :stobjs state :mode :program))
  (if (boundp-global 'fn-owner state) (f-get-global 'fn-owner state) nil))
(defun ocwt-write (oc state)
  (declare (xargs :stobjs state :mode :program))
  (f-put-global 'fn-owner oc state))
(defun ocwt-read-caller (state)
  (declare (xargs :stobjs state :mode :program))
  (ocwt-direct state))
(defun ocwt-write-caller (oc state)
  (declare (xargs :stobjs state :mode :program))
  (let ((state (ocwt-write oc state)))
    (f-put-global 'ocwt-aux :preserve state)))
(defun ocwt-unrelated (state)
  (declare (xargs :stobjs state :mode :program))
  (f-put-global 'ocwt-unrelated :unrelated state))
(make-event
 (let* ((snapshot (fn-ocw-snapshot state))
        (direct (cadr (assoc-keyword :direct snapshot)))
        (rows (cadr (assoc-keyword :functions snapshot))))
   (value
    (list 'assert-event
          (and (member-eq 'ocwt-direct direct)
               (member-eq 'ocwt-write direct)
               (not (member-eq 'ocwt-read-caller direct))
               (assoc-eq 'ocwt-read-caller rows)
               (assoc-eq 'ocwt-write-caller rows)
               (not (assoc-eq 'ocwt-unrelated rows))
               (equal (nth 5 (assoc-eq 'ocwt-write-caller rows)) t)
               (equal (nth 5 (assoc-eq 'ocwt-read-caller rows)) nil))))))
