; Scoped actual program-wrapper scenario, loaded with exact selected owner
; functions and output-command-admission. No semantic stubs or priced tariff.
; Shaped owner/connection fields suffice for this getter; no owner invariant
; or full native image qualification is claimed.
(in-package "ACL2")
(defun fn-output-preview-fixture (state)
  (declare (xargs :stobjs state :mode :program))
  (with-local-stobj fn-octets
    (mv-let (ok state fn-octets)
      (let* ((wire (fn-wire-make-state :command nil 0 nil nil 0 510 8192))
             (view (fn-own-view-make 7 17 nil))
             (config (fn-auth-open-config))
             (session (fn-auth-open-session nil nil nil nil config nil))
             (conn (fn-own-conn-make-indexed 4 6 16 wire session nil
                                            config nil nil nil))
             (owner (fn-own-make nil view (list conn) 5 10 nil nil nil nil
                                 nil nil nil nil nil nil))
             (oc (fn-ocfg-make owner nil nil nil))
             (before (if (boundp-global 'fn-owner state)
                         (f-get-global 'fn-owner state) nil))
             (state (f-put-global 'fn-owner oc state))
             (xs '(78 69 87 78 69 87 83 13 10 65 82 84 73 67 76 69 32 49 13 10))
             (fn-octets (fn-octets-from-list xs fn-octets)))
        (mv-let (erp preview state) (fn-owner-output-preview 4 0 20 fn-octets state)
          (mv-let (erp2 tariff state) (fn-owner-output-tariff-preview 4 preview state)
            (let ((ok (and (null erp) (null erp2)
                           (fn-wire-fast-statep wire)
                           (equal (fn-ocap-at 0 preview) :preview)
                           (equal (fn-ocap-at 1 preview) 9)
                           (equal (fn-ocap-at 2 preview) :newnews)
                           (equal (fn-ocap-at 3 preview) '((78 69 87 78 69 87 83)))
                           (equal (fn-oct-slice-list 9 20 fn-octets)
                                  '(65 82 84 73 67 76 69 32 49 13 10))
                           (equal tariff '(:unpriced :newnews))
                           (equal (fn-ocap-admit-preview preview tariff 1048576)
                                  '(:refused :unpriced-output-family :newnews))
                           (equal (f-get-global 'fn-owner state) oc))))
              (mv-let (erp3 unknown state) (fn-owner-output-preview 99 0 20 fn-octets state)
                (mv-let (erp4 bad-range state) (fn-owner-output-preview 4 0 21 fn-octets state)
                  (let* ((ok (and ok (null erp3) (equal unknown :unknown)
                                  (null erp4) (equal bad-range :bad-range)
                                  (equal (fn-octets-list fn-octets) xs)
                                  (equal (f-get-global 'fn-owner state) oc)))
                         (state (f-put-global 'fn-owner before state)))
                    (mv ok state fn-octets))))))))
      (mv ok state))))
(make-event
 (mv-let (ok state) (fn-output-preview-fixture state)
   (if ok (value '(value-triple :actual-output-preview-unpriced-pass))
     (er soft 'fn-output-preview-fixture "Actual program output preview failed."))))
