; Executes the actual cursor bodies with CL recording shims only.
; No ACL2 guard/proof, source issuer, TCPCL producer or native claim.
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(declaim (declaration xargs))
(defun natp (x) (and (integerp x) (<= 0 x)))
(defun zp (x) (or (not (integerp x)) (<= x 0)))
(defun fn-cbor-ag-car (x) (if (consp x) (car x) nil))
(defun fn-cbor-ag-cdr (x) (if (consp x) (cdr x) nil))
(defun fn-cbor-octetp (x) (and (integerp x) (<= 0 x 255)))
(defmacro mv (&rest args) `(values ,@args))
(defmacro mv-let (names expression &body body)
 `(multiple-value-bind ,names ,expression ,@body))
(with-open-file (stream "books/tcpcl-segment-source-cursor.lisp")
 (loop for form = (read stream nil :end) until (eq form :end)
       when (eq (car form) 'defun) do (eval form)))
(defun run-cursor (root count quantum)
 (let ((job (fn-tsc-begin root count)) (out nil))
  (loop repeat 100 do
   (multiple-value-bind (word next bytes used) (fn-tsc-turn job quantum)
    (assert (<= used quantum)) (assert (<= (length bytes) quantum))
    (assert (eq (fn-tsc-at 8 next) root))
    (setf job next out (append out bytes))
    (when (member word '(:source-complete :refused))
     (return-from run-cursor (values word out (fn-tsc-at 7 job))))))
  (error "Cursor failed to settle")))
(dolist (quantum '(1 7 64))
 (multiple-value-bind (word bytes reason) (run-cursor '((67 68) (65 66)) 4 quantum)
  (declare (ignore reason))
  (assert (eq word :source-complete)) (assert (equal bytes '(65 66 67 68)))))
(dolist (case '((((65 66)) 3 :source-count-short)
                (((65 66)) 1 :source-count-overrun)
                (((256)) 1 :source-octet)
                (((65) . broken) 1 :source-chain)))
 (multiple-value-bind (word bytes reason) (run-cursor (first case) (second case) 1)
  (declare (ignore bytes))
  (assert (eq word :refused)) (assert (eq reason (third case)))))
(format t "PASS actual cursor bodies: bounded turns, byte order, retained root and refusal cases.~%")
