; Actual caller recording only: no source issuer, constructor, TCPCL network
; or persistence verdict. Core disposition is recorded, never inferred.
(require :sb-posix)
(require :sb-bsd-sockets)
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(defun fnn-register-verb (&rest args) (declare (ignore args)))
(defun fnn-fault (&rest args) (error "fault ~s" args))
(defun fnn-core (&rest args) (error "unconfigured recording core ~s" args))
(define-condition fnn-store-indeterminate (error) ((message :initarg :message)))
(load "host/native/tcpcl.lisp")
(defvar *flushes* 0)
(defun fnn-tcl-log (&rest args) (declare (ignore args)))
(defun fnn-tcl-flush (conn) (declare (ignore conn)) (incf *flushes*))
(defun fnn-indeterminate (&rest args) (declare (ignore args)) (error "uncertain"))
(defun fnn-core (subject &rest args)
 (case subject
  (fn-tcl-source-result-action
   (if (eq (car (first args)) :source-yield) :retain :settle))
  (fn-tcl-source-result-token (second (first args)))
  (fn-tcl-delivery-plan (third args))
  (fn-tcl-delivery-plan-status (first (first args)))
  (fn-tcl-delivery-plan-messages nil)
  (fn-tcl-delivery-plan-progress-p nil)
  (fn-tcl-delivery-plan-detail nil)
  (otherwise (error "unexpected core subject ~s" subject))))
(dolist (terminal '(:accepted :refused :uncertain))
 (let* ((conn (make-fnn-tcl-conn)) (*flushes* 0)
        (root (list (list 67) (list 65 66))) (token (list :recording-token))
        (turns 0)
        (*fnn-tcl-source-start*
         (lambda (actual id segments count)
          (assert (eq actual conn)) (assert (= id 7)) (assert (= count 3))
          (assert (eq segments root))
          (assert (equal (fnn-tclc-held actual) '((:xfer-ack 3 7 3))))
          (list :source-yield token)))
        (*fnn-tcl-source-turn*
         (lambda (actual actual-token)
          (assert (eq actual conn)) (assert (eq actual-token token))
          (assert (eq (fnn-tclc-source-root actual) root))
          (assert (zerop *flushes*))
          (incf turns)
          (if (= turns 1) (list :source-yield token) (list terminal nil)))))
  (fnn-tcl-act conn (list '(:send (:xfer-ack 3 7 3))
                          (list :bundle-segments-received 7 root 3)))
  (assert (fnn-tclc-source-pending conn)) (assert (zerop *flushes*))
  (fnn-tcl-source-tick conn)
  (assert (= turns 1)) (assert (fnn-tclc-source-pending conn))
  (assert (eq (fnn-tclc-source-root conn) root))
  (let ((failed (handler-case (progn (fnn-tcl-source-tick conn) nil) (error () t))))
   (assert (eq failed (eq terminal :uncertain))))
  (if (eq terminal :uncertain)
   (progn (assert (fnn-tclc-fenced conn)) (assert (fnn-tclc-source-pending conn))
          (assert (eq (fnn-tclc-source-root conn) root))
          (assert (equal (fnn-tclc-source-held conn) '((:xfer-ack 3 7 3))))
          (assert (zerop *flushes*)))
   (progn (assert (null (fnn-tclc-source-pending conn)))
          (assert (null (fnn-tclc-source-root conn))) (assert (= *flushes* 1))))))
; An escaping start retains the exact borrowed chain and cannot be retried.
(let* ((conn (make-fnn-tcl-conn)) (*flushes* 0) (root (list (list 65)))
       (*fnn-tcl-source-start* (lambda (&rest args) (declare (ignore args)) (error "cut")))
       (*fnn-tcl-source-turn* (lambda (&rest args) (declare (ignore args)) (error "must not run"))))
 (assert (handler-case
   (progn (fnn-tcl-act conn (list '(:send (:xfer-ack 3 7 1))
                               (list :bundle-segments-received 7 root 1))) nil)
   (error () t)))
 (assert (fnn-tclc-fenced conn)) (assert (eq (fnn-tclc-source-root conn) root))
 (assert (fnn-tclc-source-pending conn)) (assert (zerop *flushes*)))
(format t "PASS actual source caller yields/END ACK retention/terminal settlement/escape fence.~%")
; Actual outer session loop selects the source driver and resumes the token
; before reading another socket chunk. Recorded I/O only; no real network.
(defvar *received-calls* 0)
(defvar *source-turns* 0)
(defvar *source-driver-calls* 0)
(defvar *recorded-root* '((67) (65 66)))
(defun fnn-tcl-now () 0)
(defun fnn-tcl-read-timeout (conn) (declare (ignore conn)) 0)
(defun fnn-recv (fd timeout)
 (declare (ignore fd timeout))
 (incf *received-calls*)
 (when (> *received-calls* 1) (assert (= *source-turns* 3)))
 (if (= *received-calls* 1) (vector 1 2 3) (vector)))
(defun fnn-octet-list (array) (coerce array 'list))
(defun fnn-tcl-log-events (&rest args) (declare (ignore args)))
(defun fnn-core (subject &rest args)
 (case subject
  (fn-tcl-host-initial :established)
  (fn-tcl-host-open (list :established nil nil))
  (fn-tcl-host-phase (first args))
  (fn-tcl-host-source-drive
   (incf *source-driver-calls*)
   (list :established
         (list '(:send (:xfer-ack 3 7 3))
               (list :bundle-segments-received 7 *recorded-root* 3)) nil :stepped))
  (fn-tcl-host-source-more-p nil)
  (fn-tcl-host-event-digests nil)
  (fn-tcl-host-tcp-closed (list :closed nil nil))
  (fn-tcl-source-result-action
   (if (eq (car (first args)) :source-yield) :retain :settle))
  (fn-tcl-source-result-token (second (first args)))
  (fn-tcl-delivery-plan (third args))
  (fn-tcl-delivery-plan-status (first (first args)))
  (fn-tcl-delivery-plan-messages nil)
  (fn-tcl-delivery-plan-progress-p nil)
  (fn-tcl-delivery-plan-detail nil)
  (otherwise (error "forbidden source-loop core subject ~s" subject))))
(let* ((*received-calls* 0) (*source-turns* 0) (*source-driver-calls* 0) (*flushes* 0)
       (token (list :recorded-source-token))
       (*fnn-tcl-source-start*
        (lambda (conn id root count)
         (declare (ignore id count))
         (assert (eq root *recorded-root*)) (assert (fnn-tclc-source-pending conn))
         (list :source-yield token)))
       (*fnn-tcl-source-turn*
        (lambda (conn actual-token)
         (assert (eq actual-token token))
         (assert (eq (fnn-tclc-source-root conn) *recorded-root*))
         (assert (= *received-calls* 1))
         (assert (equal (fnn-tclc-held conn) '((:xfer-ack 3 7 3))))
         (incf *source-turns*)
         (if (< *source-turns* 3) (list :source-yield token) '(:accepted nil))))
       (conn (fnn-tcl-session 99 :passive nil "recording" nil)))
 (assert (= *source-driver-calls* 1)) (assert (= *source-turns* 3))
 (assert (= *received-calls* 2)) (assert (= (fnn-tclc-accepted conn) 1))
 (assert (null (fnn-tclc-source-pending conn)))
 (assert (null (fnn-tclc-source-root conn))))
(format t "PASS actual outer session source-driver/token turns/no premature read or flatten.~%")
; The real outer function throws, but the typed uncertainty retains its
; otherwise lexical connection/root/END ACK after the complete unwind.
(let* ((*received-calls* 0) (*source-turns* 0) (*source-driver-calls* 0)
       (*fnn-tcl-source-start* (lambda (&rest args) (declare (ignore args)) (error "start cut")))
       (*fnn-tcl-source-turn* (lambda (&rest args) (declare (ignore args)) (error "must not resume")))
       (failure (handler-case (progn (fnn-tcl-session 99 :passive nil "recording" nil) nil)
                  (fnn-tcl-source-indeterminate (condition) condition))))
 (assert failure)
 (let ((conn (fnn-tcl-source-failure-connection failure)))
  (assert (fnn-tclc-fenced conn)) (assert (eq (fnn-tclc-outcome conn) :uncertain))
  (assert (eq (fnn-tclc-source-root conn) *recorded-root*))
  (assert (equal (fnn-tclc-source-held conn) '((:xfer-ack 3 7 3))))
  (assert (fnn-tclc-source-pending conn))))
(format t "PASS actual outer escape retains caller-visible source/END ACK record in uncertainty.~%")
