(defpackage "ACL2" (:use "CL"))
(in-package "ACL2")
(defmacro mv (&rest xs) `(values ,@xs))
(defun member-eq (x xs) (member x xs :test #'eq))
(defun natp (x) (and (integerp x) (<= 0 x)))
(deftype fnn-octets () '(simple-array (unsigned-byte 8) (*)))
(defun assoc-equal (x xs) (assoc x xs :test #'equal))
(defvar *allocations* nil)
(defvar *actions* nil)
(defun fnn-call (name &rest args) (multiple-value-list (apply (symbol-function name) args)))
(defun fnn-core (name &rest args)
 (let ((value (first (apply #'fnn-call name args))))
  (when (eq name 'fn-oru-reader-action) (push value *actions*)) value))

(defparameter *fn-outcome-codes*
  '((:accepted . 0) (:refused . 1) (:fenced . 3) (:fault . 4)
    (:usage . 5) (:interrupted . 6) (:not-connected . 7)))
(defun fn-outcome-code (class)

  (let ((pair (assoc-equal class *fn-outcome-codes*)))
    (if (consp pair) (cdr pair) 3)))
(defun fn-outcome-of-host-condition (kind)

  (case kind
    (:indeterminate :fenced)
    (:usage :usage)
    (:refusal :refused)
    (otherwise :fault)))
(defun fn-outcome-host-condition-exit-code (kind)

  (fn-outcome-code (fn-outcome-of-host-condition kind)))
(define-condition fnn-store-error (error)
  ((message :initarg :message :reader fnn-message))
  (:report (lambda (c s) (write-string (fnn-message c) s))))
(define-condition fnn-store-fault (fnn-store-error) ())
(define-condition fnn-store-indeterminate (fnn-store-error) ())
(define-condition fnn-usage-error (fnn-store-error) ())
(defconstant +fnn-exit-ok+ (fn-outcome-code :accepted))
(defun fnn-fault (control &rest args)
  (error 'fnn-store-fault :message (apply #'format nil control args)))
(defun fnn-exit-code-for (condition)
  "ACL2's code for the condition that ended a command: the host names the
condition's type (an observation) and books/outcome-class.lisp
fn-outcome-host-condition-exit-code classifies it (PRF-143,
fn-outcome-host-condition-fences-iff-indeterminate).  It runs in handlers,
so it calls the guard-t function directly rather than through fnn-core,
whose own failure would raise a new condition here."
  (fn-outcome-host-condition-exit-code
   (typecase condition
     (fnn-store-indeterminate :indeterminate)
     (fnn-store-fault :fault)
     (fnn-usage-error :usage)
     (fnn-store-error :refusal)
     (t :fault))))
(defun fn-cbor-octetp (x)
  (and (integerp x) (<= 0 x) (<= x 255)))
(defun fn-cbor-octet-listp (xs)
  (if (consp xs)
      (and (fn-cbor-octetp (car xs))
           (fn-cbor-octet-listp (cdr xs)))
    (null xs)))
(defun fn-cbor-at-mostp (xs bound)

  (if (consp xs)
      (if (zp bound)
          nil
        (fn-cbor-at-mostp (cdr xs) (1- bound)))
    t))
(defun fn-wildmat-octetp (x) (fn-cbor-octetp x))
(defun fn-wildmat-octet-listp (xs) (fn-cbor-octet-listp xs))
(defun fn-wildmat-at-mostp (xs bound)

  (fn-cbor-at-mostp xs bound))
(defun fn-wildmat-ok (value) (list :ok value))
(defun fn-wildmat-error (reason) (list :error reason))
(defun fn-wildmat-result-okp (result)
  (and (consp result) (equal (car result) :ok)))
(defun fn-wildmat-result-value (result)

  (car (cdr result)))
(defun fn-wildmat-utf8-ok (codepoint rest) (list :ok codepoint rest))
(defun fn-wildmat-utf8-rest (result)

  (car (cdr (cdr result))))
(defun fn-wildmat-utf8-tailp (byte)
  (and (integerp byte) (<= 128 byte) (<= byte 191)))
(defun fn-wildmat-utf8-2p (xs)

  (and (consp xs) (consp (cdr xs))
       (<= 194 (car xs)) (<= (car xs) 223)
       (fn-wildmat-utf8-tailp (car (cdr xs)))))
(defun fn-wildmat-utf8-3-tailsp (xs)
  (and (consp xs) (consp (cdr xs)) (consp (cdr (cdr xs)))
       (fn-wildmat-utf8-tailp (car (cdr xs)))
       (fn-wildmat-utf8-tailp (car (cdr (cdr xs))))))
(defun fn-wildmat-utf8-4-tailsp (xs)
  (and (consp xs) (consp (cdr xs)) (consp (cdr (cdr xs)))
       (consp (cdr (cdr (cdr xs))))
       (fn-wildmat-utf8-tailp (car (cdr xs)))
       (fn-wildmat-utf8-tailp (car (cdr (cdr xs))))
       (fn-wildmat-utf8-tailp (car (cdr (cdr (cdr xs)))))))
(defun fn-wildmat-utf8-2-value (xs)

  (+ (* 64 (- (car xs) 192))
     (- (car (cdr xs)) 128)))
(defun fn-wildmat-utf8-3-value (xs)

  (+ (* 4096 (- (car xs) 224))
     (* 64 (- (car (cdr xs)) 128))
     (- (car (cdr (cdr xs))) 128)))
(defun fn-wildmat-utf8-4-value (xs)

  (+ (* 262144 (- (car xs) 240))
     (* 4096 (- (car (cdr xs)) 128))
     (* 64 (- (car (cdr (cdr xs))) 128))
     (- (car (cdr (cdr (cdr xs)))) 128)))
(defun fn-wildmat-utf8-next (octets)
  ; The public decoder preflights its whole octet list.  Keep this internal
  ; step's successful-result contract sound on arbitrary ACL2 arguments too.
  (if (not (and (consp octets)
                (fn-wildmat-octetp (car octets))))
      (fn-wildmat-error :malformed-utf8)
    (let ((first (car octets)))
      (if (< first 128)
          (fn-wildmat-utf8-ok first (cdr octets))
        (if (fn-wildmat-utf8-2p octets)
            (fn-wildmat-utf8-ok (fn-wildmat-utf8-2-value octets)
                                (cdr (cdr octets)))
          (if (and (fn-wildmat-utf8-3-tailsp octets)
                   (or (and (equal first 224)
                            (<= 160 (car (cdr octets))))
                       (and (<= 225 first) (<= first 236))
                       (and (equal first 237)
                            (<= (car (cdr octets)) 159))
                       (and (<= 238 first) (<= first 239))))
              (fn-wildmat-utf8-ok (fn-wildmat-utf8-3-value octets)
                                  (cdr (cdr (cdr octets))))
            (if (and (fn-wildmat-utf8-4-tailsp octets)
                     (or (and (equal first 240)
                              (<= 144 (car (cdr octets))))
                         (and (<= 241 first) (<= first 243))
                         (and (equal first 244)
                              (<= (car (cdr octets)) 143))))
                (fn-wildmat-utf8-ok (fn-wildmat-utf8-4-value octets)
                                    (cdr (cdr (cdr (cdr octets)))))
              (fn-wildmat-error :malformed-utf8))))))))
(defun fn-oru-lead-width (byte)

  (cond ((< byte 128) 1)
        ((and (<= 194 byte) (<= byte 223)) 2)
        ((and (<= 224 byte) (<= byte 239)) 3)
        ((and (<= 240 byte) (<= byte 244)) 4)
        (t 0)))
(defun fn-oru-cursor (status pending remaining)

  (list status pending remaining))
(defun fn-oru-ready-p (cursor)

  (and (consp cursor) (consp (cdr cursor)) (consp (cddr cursor))
       (null (cdddr cursor))
       (member-eq (car cursor) '(:checking :valid :invalid))
       ; Short-circuit before the octet predicate: at most four cells ever
       ; reach that predicate, even for a deliberately corrupted argument.
       (fn-wildmat-at-mostp (cadr cursor) 4)
       (fn-wildmat-octet-listp (cadr cursor))
       (natp (caddr cursor)) (<= (caddr cursor) 3)))
(defun fn-oru-start ()

  (fn-oru-cursor :checking nil 0))
(defun fn-oru-step (cursor byte eofp)

  (let ((status (car cursor)) (pending (cadr cursor))
        (remaining (caddr cursor)))
    (cond ((not (equal status :checking)) cursor)
          (eofp (fn-oru-cursor (if (equal remaining 0) :valid :invalid)
                               pending remaining))
          ((equal remaining 0)
           (let ((width (fn-oru-lead-width byte)))
             (cond ((equal width 0) (fn-oru-cursor :invalid (list byte) 0))
                   ((equal width 1) (fn-oru-start))
                   (t (fn-oru-cursor :checking (list byte) (1- width))))))
          ((equal remaining 1)
           (let ((next (fn-wildmat-utf8-next (append pending (list byte)))))
             (if (fn-wildmat-result-okp next)
                 (fn-oru-start)
               (fn-oru-cursor :invalid (append pending (list byte)) 0))))
          (t (fn-oru-cursor :checking (append pending (list byte))
                            (1- remaining))))))
(defun fn-oru-reader-phasep (phase)

  (member-eq phase '(:validate :rewind :copy :done :invalid :error)))
(defun fn-oru-reader-action (cursor phase)

  (case phase
    (:validate :read-validate)
    (:rewind :rewind)
    (:copy (if (equal (car cursor) :valid) :read-copy :close-invalid))
    (:done :close-valid)
    (:invalid :close-invalid)
    (otherwise :close-error)))
(defun fn-oru-reader-step (cursor phase byte eofp io-okp)

  (cond ((member-eq phase '(:done :invalid :error)) (mv cursor phase nil))
        ((not io-okp) (mv cursor :error nil))
        ((equal phase :validate)
         (let ((next (fn-oru-step cursor byte eofp)))
           (mv next (case (car next) (:valid :rewind) (:invalid :invalid)
                                      (otherwise :validate)) nil)))
        ((not (equal (car cursor) :valid)) (mv cursor :invalid nil))
        ((equal phase :rewind) (mv cursor :copy nil))
        (eofp (mv cursor :done nil))
        (t (mv cursor :copy (list byte)))))
(defun fnn-make-octets (n)
  (make-array n :element-type '(unsigned-byte 8) :initial-element 0))
(defun fnn-octets (sequence)
  (if (typep sequence 'fnn-octets)
      sequence
      (let ((out (fnn-make-octets (length sequence))))
        (replace out sequence)
        out)))
(defun fnn-string-octets (string)
  (sb-ext:string-to-octets string :external-format :utf-8))
(defun fnn-octets-string (octets)
  (sb-ext:octets-to-string (fnn-octets octets) :external-format :utf-8))
(defun fnn-operator-read-retire-report-bounded (in out)
  (let ((cursor (fnn-core 'fn-oru-start)) (phase :validate))
    (loop
      (case (fnn-core 'fn-oru-reader-action cursor phase)
        ((:read-validate :read-copy)
         (let ((observed (read-byte in nil nil)))
           (destructuring-bind (next next-phase output)
               (fnn-call 'fn-oru-reader-step cursor phase (or observed 0)
                         (null observed) t)
             (setf cursor next phase next-phase)
             (when output (write-byte (car output) out)))))
        (:rewind
         (destructuring-bind (next next-phase output)
             (fnn-call 'fn-oru-reader-step cursor phase 0 nil
                       (file-position in 0))
           (declare (ignore output))
           (setf cursor next phase next-phase)))
        (:close-valid (finish-output out) (return +fnn-exit-ok+))
        (:close-invalid (fnn-fault "ACL2 refused malformed retire report UTF-8"))
        (:close-error (fnn-fault "retire report descriptor did not rewind"))
        (otherwise (fnn-fault "ACL2 returned an unknown report-reader action"))))))

(let ((actual (symbol-function 'fnn-make-octets)))
 (setf (symbol-function 'fnn-make-octets)
       (lambda (n) (push n *allocations*) (funcall actual n))))
(defun test-case (octets validp)
 (let ((input #p"reader-input.bin") (output #p"reader-output.bin")
       (status nil) (failed nil) (result nil))
  (unwind-protect
   (progn
    (with-open-file (s input :direction :output :if-exists :supersede
                       :element-type '(unsigned-byte 8))
     (write-sequence (fnn-octets octets) s))
    (setf *allocations* nil *actions* nil)
    (with-open-file (in input :element-type '(unsigned-byte 8))
     (with-open-file (out output :direction :output :if-exists :supersede
                          :element-type '(unsigned-byte 8))
      (handler-case (setf status (fnn-operator-read-retire-report-bounded in out))
       (error (c) (setf failed t status (fnn-exit-code-for c))))))
    (assert (null *allocations*))
    (with-open-file (s output :element-type '(unsigned-byte 8))
     ;; Whole arrays below belong only to this fixture's reference observer.
     (let ((v (make-array (file-length s) :element-type '(unsigned-byte 8))))
      (read-sequence v s) (setf result (coerce v 'list))))
    (if validp
     (progn (assert (and (not failed) (eql status (fn-outcome-code :accepted)) (equal result octets)))
      (assert (= (count :rewind *actions*) 1))
      (assert (= (count :read-validate *actions*) (1+ (length octets))))
      (assert (= (count :read-copy *actions*) (1+ (length octets))))
      (assert (equal (coerce (fnn-string-octets (fnn-octets-string octets)) 'list) octets)))
     (progn (assert failed) (assert (= status (fn-outcome-code :fault))) (assert (null result))
      (assert (not (member :rewind *actions*)))
      (assert (not (member :read-copy *actions*)))
      (assert (eql status (handler-case (progn (fnn-octets-string octets) nil)
                           (error (c) (fnn-exit-code-for c)))))))
    (format t "PASS input=~d valid=~s output=~d exit=~d reader-explicit-vector-allocations=~d~%"
            (length octets) validp (length result) status 0))
   (ignore-errors (delete-file input)) (ignore-errors (delete-file output)))))
(format t "Runtime ~a ~a~%" (lisp-implementation-type) (lisp-implementation-version))
(test-case nil t)
(test-case '(0 65 127 194 128 223 191 224 160 128 237 159 191
             239 191 191 240 144 128 128 244 143 191 191) t)
(test-case (make-list 600 :initial-element 65) t)
(test-case '(239 187 191 65 239 183 144 239 191 190 239 187 191) t)
(dolist (bad '((192 128) (224 128 128) (237 160 128) (244 144 128 128)
               (240 144 128) (255)))
 (test-case (append (make-list 600 :initial-element 65) bad) nil))
(format t "PASS actual bounded host consumer / real binary streams; extracted ACL2 bodies and recording dispatcher, no activation/funding claim~%")
