; Explicit recording doubles: current authority, core responses and existing
; pipeline action. Actual new native forms and their action/owner locks run.
(defstruct fake-service (lock (sb-thread:make-mutex :name "recorded owner")))
(defun fnn-owner-service-lock (s) (fake-service-lock s))
(define-condition fnn-snapshot-read-not-issued (error) ())
(defvar *mode* :ordinary)
(defvar *actions* 0)
(defvar *offers* 0)
(defvar *readouts* 0)
(defun fnn-refuse-io (text &rest args) (error (apply #'format nil text args)))
(defun fnn-core (name &rest args)
 (case name (fn-omk-at (nth (first args) (second args)))
  (otherwise (error "Unexpected scalar ~a" name))))
(defun fnn-core-state (name &rest args)
 (case name
  (fn-owner-recovery-census-current
   (if (or (eq *mode* :stale-before)
           (and (eq *mode* :lost-after) (> *actions* 0)))
       '(:unavailable :recovery-source) '(:current :frozen-token)))
  (fn-owner-recovery-census-offer
   (incf *offers*)
   (if (eq *mode* :lost-after) '(:unavailable :recovery-source)
    (list :retained (first args))))
  (fn-owner-recovery-census-readout
   (incf *readouts*)
   (list :measured '(:measured :frozen-token 0 0 :ctx :fields nil)
         (cons :measured (cdr (first args)))))
  (otherwise (error "Unexpected program ~a" name))))
(defun %fnn-snapshot-job-source-step (job)
 (declare (ignore job))
 (incf *actions*)
 (case *mode*
  (:terminal '(:census-complete (0 0)))
  (:not-issued (error 'fnn-snapshot-read-not-issued))
  (:thrown (error "unknown action failure"))
  (otherwise :yield)))
(defun reset-recording (mode)
 (setf *mode* mode *actions* 0 *offers* 0 *readouts* 0))
(defun recorded-job ()
 (let* ((collector (list :census :descriptor :remapper :census :ctx :fields nil :grant))
        (root (list :root)) (grant (list :grant)) (view (list :view)))
  (%fnn-snapshot-recovery-job-open (make-fake-service)
   (list :census :source collector) root grant view)))
(defun resources-held-p (j)
 (and (fnn-snapshot-job-root j) (fnn-snapshot-job-maintenance j)
      (fnn-snapshot-job-payload-view j) (fnn-snapshot-job-canonical j)
      (eq (fnn-snapshot-job-returned j) :returned)))
(defun run-census-recordings ()
 (reset-recording :ordinary)
 (let ((j (recorded-job)))
  (assert (eq (fnn-snapshot-recovery-census-step j) :yield))
  (assert (= *actions* 1)) (assert (= *offers* 1)) (assert (= *readouts* 0))
  (assert (resources-held-p j)) (assert (null (fnn-snapshot-job-capture j))))
 (reset-recording :stale-before)
 (let ((j (recorded-job)))
  (assert (equal (fnn-snapshot-recovery-census-step j) '(:unavailable :recovery-source)))
  (assert (= *actions* 0)) (assert (= *offers* 0)) (assert (resources-held-p j)))
 (reset-recording :terminal)
 (let ((j (recorded-job)))
  (assert (eq (first (fnn-snapshot-recovery-census-step j)) :measured))
  (assert (= *actions* 1)) (assert (= *readouts* 1))
  (assert (equal (fnn-snapshot-recovery-census-step j) '(:retained :measured)))
  (assert (= *actions* 1)) (assert (= *readouts* 1)) (assert (resources-held-p j)))
 (reset-recording :lost-after)
 (let* ((j (recorded-job)) (root (fnn-snapshot-job-root j))
        (grant (fnn-snapshot-job-maintenance j)))
  (assert (equal (fnn-snapshot-recovery-census-step j) '(:unavailable :recovery-source)))
  (assert (= *actions* 1)) (assert (eq (fnn-snapshot-job-phase j) :recovery-required))
  (assert (eq (fnn-snapshot-job-outcome j) :uncertain))
  (assert (eq root (fnn-snapshot-job-root j)))
  (assert (eq grant (fnn-snapshot-job-maintenance j))) (assert (resources-held-p j)))
 (dolist (mode '(:not-issued :thrown))
  (reset-recording mode)
  (let ((j (recorded-job)))
   (assert (handler-case (progn (fnn-snapshot-recovery-census-step j) nil) (error () t)))
   (assert (= *actions* 1)) (assert (= *offers* 0))
   (assert (eq (fnn-snapshot-job-outcome j) (if (eq mode :not-issued) :refused :uncertain)))
   (assert (resources-held-p j))))
 (format t "PASS six installed native recovery census protocol cases; explicit core/pipeline doubles.~%"))
