; Internal typed C acquisition. The record lives in the semantic lease,
; never OC.staged (whose invariant is the ordinary delta-record grammar).
(in-package "ACL2")
(include-book "owner-host")
(include-book "account-adoption-turn-host")
(include-book "../books/consumer-account-operation-state")
(include-book "../books/consumer-account-config-marker")
(include-book "../books/history-semantic-writer-state")

(defun fn-owner-account-config-source (state)
 (declare (xargs :stobjs state :guard t))
 (and (boundp-global 'fn-owner-history-semantic-source state)
      (f-get-global 'fn-owner-history-semantic-source state)))

(defun fn-owner-history-config-begin
 (slot nonce fn-allocation-turn-slots fn-page-read-pool state)
 (declare (xargs :stobjs (fn-allocation-turn-slots fn-page-read-pool state)
                 :mode :program :guard (boundp-global 'fn-owner state)))
 (let* ((holder (fn-owner-account-adoption-operation state))
        (selection (fn-prl-nth 3 holder)) (marker (fn-cp-nth 1 selection))
        (turn (fn-owner-account-turn-current state))
        (oc (fn-owner-ocfg state)) (owner (fn-ocfg-owner oc))
        (store (fn-own-store owner)) (files (fn-sn-files store))
        (config (fn-ocfg-config oc)) (generation (fn-cfg-generation config))
        (epoch (fn-owner-canonical-epoch state))
        (count (fn-sf-records-count files))
        (txid (fn-state-next-txid (fn-node-acceptance (fn-sn-node store))))
        (parent (and (boundp-global 'fn-owner-history-publication state)
                     (f-get-global 'fn-owner-history-publication state))))
  (cond
   ((fn-owner-account-config-source state) (mv :semantic-writer-busy nil fn-allocation-turn-slots fn-page-read-pool state))
   ((not (and (fn-apr-widthp 14 holder)
               (eq (fn-prl-nth 0 holder) :account-adoption-operation)
               (eq (fn-cp-nth 0 selection) :configure) (fn-cacm-markerp marker)
               (fn-cado-receipt-coordinatep (fn-prl-nth 13 holder))
               (fn-act-livep (fn-prl-nth 13 holder) turn)
               (fn-owner-account-turn-current-bodyp :operation-select
                 (fn-prl-nth 2 holder) slot nonce fn-allocation-turn-slots
                 fn-page-read-pool state)
               (null (fn-apr-owner-current state))
               (null (fn-ocfg-staged oc)) (null (fn-own-pending owner))
               (null (fn-state-pending (fn-node-acceptance (fn-sn-node store))))
               (eq (fn-sf-phase files) :ready)
               (fn-hsw-parentp parent) (equal (fn-prl-nth 5 parent) epoch)
               (equal epoch (fn-prl-nth 5 holder))
               (equal generation (fn-prl-nth 6 holder))
               (equal count (fn-prl-nth 7 holder))
               (equal generation (fn-cp-nth 2 marker))
               (equal count (fn-cp-nth 5 marker))
               (natp txid) (posp txid) (equal txid (fn-prl-nth 9 holder))))
    (mv :account-config-source-unavailable nil fn-allocation-turn-slots fn-page-read-pool state))
   (t
    ; Intent survives record/base/lease allocation escape; it is not a ready
    ; lease and excludes another semantic writer until definite cleanup.
    (let* ((state (f-put-global 'fn-owner-history-semantic-source
                    (list :history-config-acquiring (fn-prl-nth 1 holder)
                          (fn-prl-nth 13 holder)) state))
           (record (fn-cfg-record-make generation txid (1+ generation)
                     marker (fn-ocfg-config-stamp (fn-own-clock owner))))
           (state (f-put-global 'fn-owner-history-config-base
                    (list :history-config-base (fn-prl-nth 1 holder) store config
                          (fn-owner-canonical-state state) (fn-own-view owner)
                          (fn-own-config owner) (fn-owner-obligation-view state)) state))
           (state (f-put-global 'fn-owner-history-semantic-source
                    (list :history-config-source (fn-prl-nth 1 holder)
                          (fn-prl-nth 13 holder) parent epoch count generation
                          (list :configuration-record generation (1+ generation) txid)
                          record :acquired) state)))
     (mv :account-config-source-retained (fn-prl-nth 1 holder)
         fn-allocation-turn-slots fn-page-read-pool state))))))

(defun fn-owner-history-config-writer-gate (state)
 (declare (xargs :stobjs state :mode :program
                 :guard (boundp-global 'fn-owner state)))
 (let* ((lease (fn-owner-account-config-source state))
        (holder (fn-owner-account-adoption-operation state))
        (parent (and (boundp-global 'fn-owner-history-publication state)
                     (f-get-global 'fn-owner-history-publication state)))
        (fault (and (boundp-global 'fn-owner-history-completion-fault state)
                    (f-get-global 'fn-owner-history-completion-fault state)))
        (coordinate (fn-prl-nth 7 lease)) (record (fn-prl-nth 8 lease))
        (store (fn-owner-store state)) (files (fn-sn-files store)))
  (cond
   (fault :recovery-required)
   ((and (fn-apr-widthp 3 lease)
         (eq (fn-prl-nth 0 lease) :history-config-acquiring)) :recovery-required)
   ((not (and (fn-apr-widthp 10 lease)
               (eq (fn-prl-nth 0 lease) :history-config-source)
               (fn-apr-widthp 14 holder)
               (eq (fn-prl-nth 0 holder) :account-adoption-operation)
               (eq (fn-cp-nth 0 (fn-prl-nth 3 holder)) :configure)
               (fn-cado-receipt-coordinatep (fn-prl-nth 2 lease))
               (fn-cado-receipt-coordinatep (fn-prl-nth 13 holder))
               (equal (fn-prl-nth 2 lease) (fn-prl-nth 13 holder))
               (fn-act-livep (fn-prl-nth 2 lease)
                            (fn-owner-account-turn-current state))
               (fn-hsw-parentp parent) (fn-hsw-parentp (fn-prl-nth 3 lease))
               (equal (fn-prl-nth 4 lease) (fn-owner-canonical-epoch state))
               (equal (fn-prl-nth 5 parent) (fn-prl-nth 4 lease))
               (equal parent (fn-prl-nth 3 lease))
               (equal (fn-prl-nth 5 lease) (fn-sf-records-count files))
               (eq (fn-sf-phase files) :ready)
               (equal (fn-prl-nth 6 lease)
                      (fn-cfg-generation (fn-owner-config state)))
               (fn-apr-widthp 4 coordinate)
               (eq (fn-prl-nth 0 coordinate) :configuration-record)
               (fn-cacm-recordp record)
               (equal (fn-prl-nth 1 coordinate) (fn-cfg-record-sequence record))
               (equal (fn-prl-nth 2 coordinate) (fn-cfg-record-generation record))
               (equal (fn-prl-nth 3 coordinate) (fn-cfg-record-txid record))
               (equal (fn-prl-nth 3 coordinate) (fn-prl-nth 9 holder))
               (null (fn-apr-owner-current state)) (null (fn-ocfg-staged (fn-owner-ocfg state)))))
    :account-config-source-changed)
   (t :config-writer-current))))
