; Actual retained C claim across allocating turns. No release/promote/issue.
; Whole continuation source/peak and native alias invariants remain planned.
(in-package "ACL2")
(include-book "account-config-preparation-host")
(include-book "../books/history-config-journal-state")
(include-book "../books/account-adoption-turn-continuation")

(defun fn-owner-account-config-continuation-currentp (state)
 (declare (xargs :stobjs state :mode :program :guard t))
 (let* ((row (fn-owner-account-turn-current state))
        (token (fn-cp-nth 1 row))
        (holder (fn-owner-account-adoption-operation state))
        (lease (fn-owner-account-config-source state))
        (base (and (boundp-global 'fn-owner-history-config-base state)
                   (f-get-global 'fn-owner-history-config-base state)))
        (prep (fn-owner-account-config-preparation-state state)))
  (and (fn-act-livep token row)
       (member-eq (fn-cp-nth 2 row) '(:reserved :suspended))
       (eq (fn-cp-nth 4 row) :operation-select)
       (fn-cado-widthp 14 holder)
       (eq (fn-cp-nth 0 holder) :account-adoption-operation)
       (fn-cado-widthp 4 (fn-cp-nth 1 holder))
       (fn-cado-source-keyp (fn-cp-nth 2 holder))
       (eq (fn-cp-nth 0 (fn-cp-nth 3 holder)) :configure)
       (equal token (fn-cp-nth 13 holder))
       (equal (fn-cp-nth 5 row) (fn-cp-nth 2 holder))
       (fn-cado-widthp 10 lease)
       (eq (fn-cp-nth 0 lease) :history-config-source)
       (eq (fn-cp-nth 9 lease) :acquired)
       (equal (fn-cp-nth 1 lease) (fn-cp-nth 1 holder))
       (equal (fn-cp-nth 2 lease) token)
       (fn-cado-widthp 8 base)
       (eq (fn-cp-nth 0 base) :history-config-base)
       (equal (fn-cp-nth 1 base) (fn-cp-nth 1 holder))
       (fn-cado-widthp 14 prep)
       (eq (fn-cp-nth 0 prep) :account-config-preparation)
       (equal (fn-cp-nth 1 prep) (fn-cp-nth 1 holder))
       (equal (fn-cp-nth 2 prep) token)
       (member-eq (fn-cp-nth 7 prep) '(:groups :history :store-fields :semantic-joins))
       (not (fn-owner-history-config-journal state))
       (eq (fn-owner-history-config-writer-gate state) :config-writer-current))))

(defun fn-owner-account-config-suspended-currentp (state)
 (declare (xargs :stobjs state :mode :program :guard t))
 (let* ((row (fn-owner-account-turn-current state))
        (output (fn-cp-nth 8 row))
        (holder (fn-owner-account-adoption-operation state))
        (lease (fn-owner-account-config-source state))
        (prep (fn-owner-account-config-preparation-state state)))
  (and (fn-owner-account-config-continuation-currentp state)
       (eq (fn-cp-nth 2 row) :suspended)
       (fn-cado-widthp 6 output)
       (eq (fn-cp-nth 0 output) :account-config-suspension)
       (equal (fn-cp-nth 1 output) (fn-cp-nth 1 holder))
       (equal (fn-cp-nth 2 output) (fn-cp-nth 2 holder))
       (equal (fn-cp-nth 1 (fn-cp-nth 3 output)) (fn-cp-nth 1 holder))
       (equal (fn-cp-nth 1 (fn-cp-nth 4 output)) (fn-cp-nth 1 prep))
       (equal (fn-cp-nth 2 (fn-cp-nth 4 output)) (fn-cp-nth 2 prep))
       (equal (fn-cp-nth 1 (fn-cp-nth 5 output)) (fn-cp-nth 1 lease))
       (equal (fn-cp-nth 2 (fn-cp-nth 5 output)) (fn-cp-nth 2 lease)))))

(defun fn-owner-account-config-suspend-current
 (slot nonce fn-allocation-turn-slots fn-page-read-pool state)
 (declare (xargs :stobjs (fn-allocation-turn-slots fn-page-read-pool state)
                 :mode :program :guard t))
 (let* ((row (fn-owner-account-turn-current state))
        (intent (fn-cp-nth 9 row)))
  (cond
   ((and (fn-owner-account-config-suspended-currentp state)
         (fn-cado-widthp 6 intent)
         (eq (fn-cp-nth 0 intent) :account-turn-reservation)
         (natp nonce) (natp (fn-cp-nth 5 intent))
         (equal slot (fn-cp-nth 4 intent)) (< (fn-cp-nth 5 intent) nonce)
         (fn-ats-matchingp slot nonce fn-allocation-turn-slots fn-page-read-pool)
         (eq (fn-ats-kindsi slot fn-allocation-turn-slots) :owner-control)
         (member-eq (fn-ats-phasesi slot fn-allocation-turn-slots) '(2 3)))
    ; A refused fresh source/prepay has done no semantic work. It may finish
    ; that fresh Q receipt while the complete original claim remains parked.
    (mv :account-turn-retained fn-page-read-pool state))
   ((and (fn-owner-account-config-continuation-currentp state)
         (eq (fn-cp-nth 2 row) :reserved)
         (fn-owner-account-turn-current-bodyp :operation-select
            (fn-cp-nth 5 row) slot nonce fn-allocation-turn-slots fn-page-read-pool state))
    (let* ((base (f-get-global 'fn-owner-history-config-base state))
           (output (list :account-config-suspension
                     (fn-cp-nth 1 (fn-owner-account-adoption-operation state))
                     (fn-cp-nth 5 row) base
                     (fn-owner-account-config-preparation-state state)
                     (fn-owner-account-config-source state))))
     (mv-let (word next) (fn-act-suspend (fn-cp-nth 1 row) output row)
      (mv word fn-page-read-pool
          (if (eq word :account-turn-retained)
              (fn-owner-account-turn-keep next state) state)))))
   (t (mv :account-return-pending fn-page-read-pool state)))))

(defun fn-owner-account-config-resume
 (slot nonce fn-allocation-turn-slots fn-page-read-pool state)
 (declare (xargs :stobjs (fn-allocation-turn-slots fn-page-read-pool state)
                 :mode :program :guard t))
 (let* ((row (fn-owner-account-turn-current state))
        (intent (fn-cp-nth 9 row)))
  (if (not (and (fn-owner-account-config-suspended-currentp state)
                 (fn-cado-widthp 6 intent)
                 (eq (fn-cp-nth 0 intent) :account-turn-reservation)
                 (natp nonce) (natp (fn-cp-nth 5 intent))
                 (equal slot (fn-cp-nth 4 intent)) (< (fn-cp-nth 5 intent) nonce)
                 (fn-ats-matchingp slot nonce fn-allocation-turn-slots fn-page-read-pool)
                 (eq (fn-ats-kindsi slot fn-allocation-turn-slots) :owner-control)
                 (eql (fn-ats-phasesi slot fn-allocation-turn-slots) 2)))
      (mv :refused :account-continuation-changed fn-allocation-turn-slots fn-page-read-pool state)
   (if (eq (fn-cp-nth 7 (fn-owner-account-config-preparation-state state)) :semantic-joins)
       (mv :unavailable :configuration-semantic-pending
           fn-allocation-turn-slots fn-page-read-pool state)
   ; Actual CURRENT job/lease are the registered resume source. This complete
   ; compiled recipe must include rebind, ONE prep quantum, retained overlap
   ; and epilogue. Its result is not lowered from a family subtotal.
   (mv-let (available resources)
    (fn-owner-runtime-operation-resources :account-config-resume fn-page-read-pool state)
    (if (not (member-eq available '(:runtime-operation-available :runtime-operation-unavailable)))
        (mv-let (fenced state) (fn-owner-account-turn-fence state)
         (declare (ignore fenced))
         (mv :recovery-required available fn-allocation-turn-slots fn-page-read-pool state))
    (if (not (and (eq available :runtime-operation-available)
                  (fn-cado-widthp 8 resources)
                  (eq (fn-cp-nth 0 resources) :account-adoption-resources)
                  (eq (fn-cp-nth 1 resources) :account-config-resume)
                  (natp (fn-cp-nth 5 resources))
                  (fn-prs-vectorp (fn-cp-nth 2 resources))
                  (fn-prs-vectorp (fn-cp-nth 3 row))
                  (fn-prs-below (fn-cp-nth 2 resources) (fn-cp-nth 3 row))))
        (mv :unavailable :account-config-resume-resources-unavailable
            fn-allocation-turn-slots fn-page-read-pool state)
     (mv-let (paid fn-allocation-turn-slots fn-page-read-pool)
      (fn-ats-prepay-body-internal slot nonce (fn-cp-nth 5 resources)
         fn-allocation-turn-slots fn-page-read-pool)
      (if (not (and (eq paid :prepaid)
                    (fn-ats-role-bodyp slot nonce :owner-control
                      fn-allocation-turn-slots fn-page-read-pool)))
          (if (eq paid :yield)
              (mv :yield :account-config-resume-budget-yield
                  fn-allocation-turn-slots fn-page-read-pool state)
            (mv-let (fenced state) (fn-owner-account-turn-fence state)
             (declare (ignore fenced))
             (mv :recovery-required paid fn-allocation-turn-slots fn-page-read-pool state)))
       (mv-let (rebound next) (fn-act-rebind (fn-cp-nth 1 row) slot nonce row)
        (if (not (eq rebound :account-turn-rebound))
            (mv :recovery-required rebound fn-allocation-turn-slots fn-page-read-pool state)
          (let ((state (fn-owner-account-turn-keep next state)))
           ; Readout of the SAME selected opaque ID; no FnCATDNext or PRS issue.
           (mv :configure (fn-cp-nth 1 (fn-owner-account-adoption-operation state))
               fn-allocation-turn-slots fn-page-read-pool state)))))))))))

)

)
