; INTERNAL account epilogue effect, after actual SAMEpool CounterBegin has
; retained CURRENT and all four aliases in recovery mode, before CURRENT NIL
; and physical CounterFinish. This neither refunds nor releases canonical APR.
(in-package "ACL2")
(include-book "account-durable-completion-host")
(include-book "../books/page-read-counter-transaction")

; The counter receipt is the local result from actual CounterBegin. No native
; export takes a receipt. The enclosing producer retains the exact aliasRoots4
; from these globals before this call; correspondence is a producer invariant,
; never re-established by EQUAL over a shared semantic graph here.
(defun fn-owner-account-durable-alias-clear-internal
 (token receipt fn-page-read-pool state)
 (declare (xargs :stobjs (fn-page-read-pool state) :mode :program :guard t))
 (let* ((current (fn-owner-account-turn-current state))
        (settlement (fn-cp-nth 9 current))
        (aliases (fn-cp-nth 4 settlement))
        (promotion (fn-cp-nth 3 settlement))
        (mode (fn-prp-mode fn-page-read-pool))
        (outcome (fn-owner-account-durable-outcome state))
        (holder (fn-owner-account-adoption-operation state))
        (capture (and (boundp-global 'fn-owner-history-account-capture state)
                      (f-get-global 'fn-owner-history-account-capture state)))
        (ready (and (boundp-global 'fn-owner-history-account-state state)
                    (f-get-global 'fn-owner-history-account-state state)))
        (history-receipt (fn-prl-nth 2 outcome))
        (history-token (fn-prl-nth 1 history-receipt)))
  (if (not
       (and (fn-act-livep token current)
            (eq (fn-cp-nth 2 current) :uncertain)
            (eq (fn-cp-nth 4 current) :operation-select)
            (fn-apr-widthp 5 settlement)
            (eq (fn-cp-nth 0 settlement) :account-turn-settlement)
            (fn-apr-widthp 5 promotion)
            (eq (fn-cp-nth 0 promotion) :account-turn-promotion)
            (fn-apr-widthp 6 (fn-cp-nth 4 promotion))
            (eq (fn-cp-nth 0 (fn-cp-nth 4 promotion)) :account-turn-reservation)
            (fn-apr-widthp 4 aliases)
            (fn-apr-widthp 8 mode)
            (eq (fn-prl-nth 0 mode) :counter-publishing)
            (eq (fn-prp-alloc-mode fn-page-read-pool) :recovery)
            (fn-prb-counter-receipt-matchesp receipt (fn-prl-nth 6 mode))
            (eq (fn-prl-nth 5 receipt) :account-settle)
            (equal (fn-prl-nth 1 receipt) (fn-cp-nth 1 token))
            (fn-apr-widthp 7 outcome)
            (eq (fn-prl-nth 0 outcome) :account-durable-outcome)
            (fn-cado-receipt-coordinatep (fn-prl-nth 1 outcome))
            (equal token (fn-prl-nth 1 outcome))
            (fn-apr-widthp 14 holder)
            (eq (fn-prl-nth 0 holder) :account-adoption-operation)
            (fn-cado-receipt-coordinatep (fn-prl-nth 13 holder))
            (equal token (fn-prl-nth 13 holder))
            (fn-apr-widthp 3 history-receipt)
            (eq (fn-prl-nth 0 history-receipt) :history-completion)
            (fn-apr-tokenp history-token)
            (equal (fn-prl-nth 2 history-receipt) (fn-prl-nth 5 history-token))
            (equal (fn-prl-nth 8 holder) (fn-prl-nth 4 history-token))
            (equal (fn-prl-nth 9 holder) (fn-prl-nth 5 history-token))
            (fn-apr-widthp 5 capture)
            (eq (fn-prl-nth 0 capture) :history-account-capture)
            (fn-apr-tokenp (fn-prl-nth 1 capture))
            (equal history-token (fn-prl-nth 1 capture))
            (fn-apr-widthp 5 ready)
            (eq (fn-prl-nth 0 ready) :history-account-ready)
            (fn-apr-tokenp (fn-prl-nth 1 ready))
            (equal history-token (fn-prl-nth 1 ready))))
      (mv :account-alias-clear-unavailable state)
    (let* ((state (f-put-global 'fn-owner-history-account-capture nil state))
           (state (f-put-global 'fn-owner-history-account-state nil state))
           (state (fn-owner-account-adoption-operation-clear state))
           (state (f-put-global 'fn-owner-account-durable-outcome nil state)))
     ; The actual pool/STATE settlement continuation still owns every old
     ; graph. Only the subsequent physical finish may restore served modes.
     (mv :account-aliases-cleared state)))))
