; First complete semantic family assembly. Every input is fetched from the
; registered same-owner producers. No native tuple/Boolean/slot authority.
; Actual canonical operation qualification must precede this allocating call.
(in-package "ACL2")
(include-book "admission-history-tail-host")
(include-book "admission-semantic-census-host")
(include-book "account-admission-semantic-host")
(include-book "history-admission-producer-host")
(include-book "../books/admission-authority-install-plan")

(defun fn-owner-admission-authority-prepare-step (fuel fn-history-backing state)
 (declare (xargs :stobjs (fn-history-backing state) :mode :program
                 :guard (natp fuel)))
 (let* ((current (fn-apr-owner-current state)) (token (fn-prl-nth 0 current))
        (builder (fn-hep-builder fn-history-backing))
        (old (fn-hed-at 7 builder)) (tail (fn-hed-at 8 builder))
        (intent (and (boundp-global 'fn-owner-canonical-admission-executor state)
                     (f-get-global 'fn-owner-canonical-admission-executor state)))
        (reader (and (boundp-global 'fn-owner-history-semantic-reader-base state)
                     (f-get-global 'fn-owner-history-semantic-reader-base state)))
        (obligation (and (boundp-global 'fn-owner-history-semantic-obligation-base state)
                         (f-get-global 'fn-owner-history-semantic-obligation-base state)))
        (preparing (and (boundp-global 'fn-owner-history-preparation-intent state)
                        (f-get-global 'fn-owner-history-preparation-intent state))))
  (cond
   ((not (and (fn-apr-tokenp token) (fn-apr-livep token current)
              (eq (fn-owner-history-writer-gate token state) :writer-current)
              (fn-apr-tokenp (fn-hep-producer-token fn-history-backing))
              (equal token (fn-hep-producer-token fn-history-backing))
              (fn-hed-fixedp builder 10) (eq (fn-hed-at 0 builder) :history-builder)
              (fn-apr-tokenp (fn-hed-at 6 builder)) (equal token (fn-hed-at 6 builder))))
    (mv :writer-stale fuel fn-history-backing state))
   ((member-eq (fn-prl-nth 2 current) '(:produced :promoted))
    (mv :already-produced fuel fn-history-backing state))
   ((eq (fn-hep-producer-phase fn-history-backing) :prepared)
    (mv-let (word fn-history-backing state)
      (fn-owner-history-seal-produced fn-history-backing state)
     (mv word fuel fn-history-backing state)))
   (preparing (mv :recovery-required fuel fn-history-backing state))
   ((zp fuel) (mv :yield fuel fn-history-backing state))
   ((not (and (eq (fn-prl-nth 2 current) :reserved)
              (eq (fn-hep-producer-phase fn-history-backing) :offered)
              (fn-apr-widthp 8 intent)
              (eq (fn-prl-nth 0 intent) :admission-prepare-intent)
              (fn-apr-tokenp (fn-prl-nth 1 intent)) (equal token (fn-prl-nth 1 intent))
              (fn-apr-widthp 4 reader) (eq (fn-prl-nth 0 reader) :history-reader-base)
              (fn-apr-tokenp (fn-prl-nth 1 reader)) (equal token (fn-prl-nth 1 reader))
              (fn-apr-widthp 3 obligation)
              (eq (fn-prl-nth 0 obligation) :history-obligation-base)
              (fn-apr-tokenp (fn-prl-nth 1 obligation))
              (equal token (fn-prl-nth 1 obligation))
              (fn-hep-sourcep old) (fn-hep-epoch-livep old fn-history-backing)
              (fn-hep-source-stamps-equal old (fn-hep-current fn-history-backing))
              (equal (fn-hed-at 7 old) (fn-prl-nth 3 token))
              (or (fn-apr-widthp 4 tail) (fn-apr-widthp 7 tail))
              (eq (fn-hed-at 0 tail) :history-tail-ready)
              (fn-apr-tokenp (fn-hed-at 1 tail)) (equal token (fn-hed-at 1 tail))
              (fn-hed-leafp (fn-hed-at 2 tail))
              (natp (fn-hed-at 3 tail)) (< (fn-hed-at 3 tail) 256)))
    (mv :semantic-preparation-unavailable fuel fn-history-backing state))
   ; Same genuine issuance supplies both new fixed identity coordinates.
   ; It cannot accidentally reuse an initial/cold predecessor identity.
   ((or (equal (fn-prl-nth 1 token) (fn-hed-at 1 old))
         (equal (fn-prl-nth 1 token) (fn-hed-at 8 old)))
    (mv :publication-identity-unavailable fuel fn-history-backing state))
   (t
    (mv-let (account-word next-state full root)
      (fn-owner-admission-account-result state)
     (if (not (eq account-word :account-ready))
         (mv account-word fuel fn-history-backing state)
      (mv-let (census-word pool rows source4)
        (fn-owner-admission-census-result state)
       (if (not (eq census-word :census-prepared))
           (mv census-word fuel fn-history-backing state)
        (mv-let (candidate-word row produced context fields)
          (fn-hep-builder-readout fn-history-backing)
         (declare (ignore context fields))
         (if (not (and (eq candidate-word :candidate)
                       (fn-apr-widthp 6 produced) (eq (fn-prl-nth 2 produced) :carried)
                       (fn-evc-authorityp row)
                       (equal (fn-evc-sequence row) (fn-prl-nth 4 token))
                       (equal (fn-evc-txid row) (fn-prl-nth 5 token))
                       (fn-apr-widthp 17 next-state) (fn-apr-widthp 7 full)
                       (eq (fn-prl-nth 0 full) :ok)
                       (fn-apr-widthp 5 (fn-prl-nth 4 full))))
             (mv :recovery-required fuel fn-history-backing state)
          (let* ((state (f-put-global 'fn-owner-history-preparation-intent
                          (list :history-preparation-intent token) state))
                 (epoch (fn-prl-nth 2 token)) (count (fn-prl-nth 3 token))
                 (base (fn-prl-nth 5 intent))
                 (plan (fn-aip-authority-install-plan base produced (fn-prl-nth 1 next-state)
                         (fn-prl-nth 4 next-state) (fn-prl-nth 2 reader)
                         (1+ count) (fn-sf-frontier (fn-sn-files base))
                         (fn-prl-nth 3 reader)))
                 (canonical (list :ready epoch (1+ count)
                              (fn-prl-nth 0 produced) (fn-prl-nth 1 produced)
                              (fn-prl-nth 4 next-state)
                              (fn-prl-nth 1 (fn-prl-nth 4 full)) pool rows source4))
                 (publication (list :history-installed (fn-prl-nth 1 token)
                                (fn-hed-at 2 old) (fn-hed-at 3 old)
                                (fn-prl-nth 1 token) epoch))
                 (ready (list :history-owner-ready epoch count (fn-prl-nth 4 intent)
                              plan (fn-prl-nth 4 full) root canonical
                              (fn-prl-nth 2 obligation) publication))
                 (next-source (list :history-source (fn-prl-nth 1 token)
                                (fn-hed-at 2 old) (fn-hed-at 3 old)
                                (if (fn-apr-widthp 7 tail) (fn-hed-at 4 tail) (fn-hed-at 4 old))
                                (if (fn-apr-widthp 7 tail) (fn-hed-at 6 tail) (fn-hed-at 5 old))
                                (if (fn-apr-widthp 7 tail) (fn-hed-at 5 tail) (fn-hed-at 6 old))
                                (1+ count)
                                (fn-prl-nth 1 token)))
                 (state (f-put-global 'fn-owner-history-semantic-state
                          (list :history-semantic-done token row produced ready) state))
                 (fn-history-backing (update-fn-hep-producer-receipts
                   (list :history-preparation token (fn-prl-nth 5 token) next-source
                         (fn-hed-at 2 tail) (fn-hed-at 3 tail) ready) fn-history-backing))
                 (fn-history-backing (update-fn-hep-producer-phase :prepared fn-history-backing)))
           (mv-let (word fn-history-backing state)
             (fn-owner-history-seal-produced fn-history-backing state)
            (mv word (1- fuel) fn-history-backing state)))))))))))))
