; Registered same-source census preparation; no supplied row, count or lease.
; The remapped history census is distinct from CP encoding-size carries.
(in-package "ACL2")
(include-book "admission-semantic-node-host")
(include-book "../books/snapshot-source-cursor")
(include-book "../books/snapshot-row-source-remap")
(include-book "../books/history-census-controller")

(defun fn-owner-admission-census-begin (fn-history-backing state)
 (declare (xargs :stobjs (fn-history-backing state) :mode :program :guard t))
 (let* ((current (fn-apr-owner-current state))
        (token (fn-prl-nth 0 current))
        (intent (and (boundp-global 'fn-owner-canonical-admission-executor state)
                     (f-get-global 'fn-owner-canonical-admission-executor state)))
        (job (and (boundp-global 'fn-owner-history-semantic-census state)
                  (f-get-global 'fn-owner-history-semantic-census state))))
  (cond
   ((not (and (fn-apr-tokenp token) (fn-apr-livep token current)
              (eq (fn-owner-history-writer-gate token state) :writer-current)
              (fn-apr-widthp 8 intent)
              (eq (fn-prl-nth 0 intent) :admission-prepare-intent)
              (fn-apr-tokenp (fn-prl-nth 1 intent))
              (equal token (fn-prl-nth 1 intent))
              (fn-apr-tokenp (fn-hep-producer-token fn-history-backing))
              (equal token (fn-hep-producer-token fn-history-backing))))
    (mv :writer-stale fn-history-backing state))
   (job (mv (if (and (fn-apr-widthp 5 job)
                        (eq (fn-prl-nth 0 job) :history-census)
                        (fn-apr-tokenp (fn-prl-nth 1 job))
                        (equal token (fn-prl-nth 1 job)))
                    :census-retained :recovery-required)
             fn-history-backing state))
   (t
    (mv-let (word row produced context fields)
      (fn-hep-builder-readout fn-history-backing)
     (declare (ignore produced context fields))
     (if (not (and (eq word :candidate)
                   (equal (fn-evc-sequence row) (fn-prl-nth 4 token))
                   (equal (fn-evc-txid row) (fn-prl-nth 5 token))))
         (mv :writer-stale fn-history-backing state)
      (let* ((files (fn-sn-files (fn-prl-nth 5 intent)))
             (count (fn-sf-records-count files))
             (frontier (fn-sf-frontier files)))
       (if (not (and (natp count) (equal count (fn-prl-nth 3 token))
                     (natp frontier) (unsigned-byte-p 61 (1+ count))))
           (mv :census-domain-unavailable fn-history-backing state)
        (let* ((target (fn-sfr-snoc (fn-sf-records-field files) row))
               (pair (list (fn-prl-nth 1 token) (1+ count)))
               (source (list frontier pair 0 0))
               (state (f-put-global 'fn-owner-history-semantic-census
                        (list :history-census token
                              (fn-osrc-begin target (1+ count) frontier pair)
                              (fn-osm-begin source)
                              (fn-hct-begin (1+ count) pair token)) state)))
         (mv :census-started fn-history-backing state))))))))))
