; ACL2-only request projections for the filesystem receiver glue.
(in-package "ACL2")
(include-book "../books/bp-receipt")
(defun fn-bpreq-request (adu)
  (let ((answer (fn-bpa-decode-exact adu)))
    (if (and (fn-bpa-result-okp answer)
             (fn-bpa-requestp (fn-bpa-result-message answer)))
        (fn-bpa-result-message answer) nil)))
(defun fn-bpreq-article (adu state)
  (declare (xargs :stobjs state :mode :program))
  (let ((request (fn-bpreq-request adu)))
    (value (if request (fn-bpa-request-article request) nil))))
(defun fn-bpreq-work-id (adu state)
 (declare (xargs :stobjs state :mode :program))
 (let ((request (fn-bpreq-request adu)))
  (value (if request (fn-record-string-octets (fn-bpa-request-work-id request)) nil))))
(defun fn-bpreq-find-record (request records)
  (if (consp records)
      (let ((record (car records)))
        (if (and (fn-record-p record)
                 (equal (fn-record-payload record)
                        (fn-bpa-request-article request))
                 (equal (fn-record-content-subject record)
                        (fn-bpa-request-subject request)))
            record
          (fn-bpreq-find-record request (cdr records))))
    nil))
(defun fn-bpreq-existing-record (adu state)
 (declare (xargs :stobjs state :mode :program))
 (let* ((request (fn-bpreq-request adu))
        (store (f-get-global 'fn-store-sn state))
        (record (and request
                     (fn-bpreq-find-record
                      request (fn-sf-records (fn-sn-files store))))))
  (value (if (and record (fn-bpr-store-record-acceptedp store record))
             (fn-record-encode record) nil))))
(defun fn-bpreq-request-status (adu state)
 (declare (xargs :stobjs state :mode :program))
 (let* ((request (fn-bpreq-request adu))
        (st (f-get-global 'fn-bprj-state state)))
  (value
   (if (not request) :malformed
    (if (not (and (equal (fn-bpa-request-destination-eid request)
                        (fn-bpr-config-destination (fn-bpr-state-config st)))
                  (equal (fn-bpa-request-policy-id request)
                        (fn-bpr-config-policy-id (fn-bpr-state-config st)))))
        :refused
      (let* ((work-id (fn-bpa-request-work-id request))
             (context (fn-bpr-find-context work-id (fn-bpr-state-contexts st)))
             (pending (fn-bpr-state-pending st)))
       (cond ((and context (not (equal request (fn-bpr-context-request context))))
              :conflict)
             ((and context (fn-bpr-receipt-adu st request)) :committed)
             ((consp pending)
              (if (equal work-id
                         (fn-bpr-context-work-id
                          (fn-bpr-receipt-entry-context pending)))
                  :pending :blocked))
             (context :context)
             (t :new))))))))
(defun fn-bpreq-subject-matchp (adu subject-octets state)
  (declare (xargs :stobjs state :mode :program))
  (let ((request (fn-bpreq-request adu)))
    (value (if request
               (equal (fn-bpa-request-subject request)
                      (fn-record-octets-string subject-octets)) nil))))
