; Program bridge for native BP receive evidence allocation and recovery.
(in-package "ACL2")
(include-book "../books/bp-receive-evidence")

(defun fn-bpn-host-evidence-max-entries () (fn-bpn-evidence-max-entries))
(defun fn-bpn-host-evidence-directory-name () *fn-bpn-evidence-directory-name*)
(defun fn-bpn-host-evidence-recover (entries)
  (fn-bpn-evidence-recover entries))
(defun fn-bpn-host-evidence-readyp (st)
  (if (fn-bpn-evidence-statep st) t nil))
(defun fn-bpn-host-evidence-authorize (st outcome lock-ownedp
                                             wire-absentp result-absentp)
  ; An exact alias (definterface :delegates): the decision is the books'.
  (declare (xargs :guard t))
  (fn-bpn-evidence-authorize st outcome lock-ownedp
                             wire-absentp result-absentp))
(defun fn-bpn-host-evidence-next-wire-name (st)
  (if (fn-bpn-evidence-statep st)
      (fn-bpn-evidence-next-wire-name st)
    nil))
(defun fn-bpn-host-evidence-next-result-name (st outcome)
  (if (and (fn-bpn-evidence-statep st)
           (fn-bpn-evidence-outcomep outcome))
      (fn-bpn-evidence-next-result-name st outcome)
    nil))
(defun fn-bpn-host-evidence-operationp (operation)
  ; An exact alias (definterface :delegates); the recognizer is boolean.
  (fn-bpn-evidence-operationp operation))
(defun fn-bpn-host-evidence-operation-wire-name (operation)
  (fn-bpn-evidence-operation-wire-name operation))
(defun fn-bpn-host-evidence-operation-result-name (operation)
  (fn-bpn-evidence-operation-result-name operation))
(defun fn-bpn-host-evidence-operation-wire-publication (operation)
  (fn-bpn-evidence-operation-wire-publication operation))
(defun fn-bpn-host-evidence-operation-result-publication (operation)
  (fn-bpn-evidence-operation-result-publication operation))
(defun fn-bpn-host-evidence-operation-successor (operation)
  (fn-bpn-evidence-operation-successor operation))
