; Read-only actual installed owner/view/config association. No native export.
(in-package "ACL2")
(include-book "owner-host")
(include-book "../books/history-source-capture")
(defun fn-owner-history-current-view (fn-history-backing state)
 (declare (xargs :stobjs (fn-history-backing state) :mode :program))
 (if (not (boundp-global 'fn-owner state))
     (mv :history-view-unavailable nil nil nil nil state)
  (mv-let (word source) (fn-owner-history-source fn-history-backing state)
   (if (not (eq word :source)) (mv word nil nil nil nil state)
    (let* ((owner (fn-owner-core state))
           (files (fn-sn-files (fn-own-store owner)))
           (view (fn-own-view owner)))
     (if (not (and (eq (fn-sf-phase files) :ready)
                   (equal (fn-sf-records-count files) (fn-hhc-at 7 source))
                   (equal (fn-own-view-version view) (fn-sf-records-count files))
                   (equal (fn-own-view-frontier view) (fn-sf-frontier files))))
         (mv :history-view-unavailable nil nil nil nil state)
      (mv :history-view source view (fn-owner-config state)
          (fn-own-config owner) state)))))))
