(in-package "ACL2")
(include-book "index-publication-host")
(include-book "../books/index-generation-issuer")
(include-book "../books/index-writer-operation-demand")
(include-book "../books/allocation-turn-body-authority")
(include-book "../books/runtime-operation-source")
(program)

; Private executor continuation: slot/nonce are the actual ATS enter output.
; No demand, PreparedCommit, source family or arena coordinate is supplied.
; PROGRAM source proposal: admission and the installed executor join are open.
(defun fn-owner-index-writer-begin-issued
 (slot nonce fuel fn-allocation-turn-slots fn-mio$c fn-arena fn-page-read-pool state)
 (declare (xargs :stobjs (fn-allocation-turn-slots fn-mio$c fn-arena fn-page-read-pool state)))
 (if (not (fn-ats-role-bodyp slot nonce :index-writer
                            fn-allocation-turn-slots fn-page-read-pool))
     (mv :runtime-operation-unavailable nil fuel fn-mio$c fn-page-read-pool)
   (mv-let (source pc frontier version visibility) (fn-owner-index-source state)
    (declare (ignore frontier version visibility))
    (if (not (eq source :current))
        (mv :unavailable nil fuel fn-mio$c fn-page-read-pool)
      (mv-let (family-word family)
       (fn-owner-runtime-operation-source :index-writer fn-page-read-pool state)
       (mv-let (table-word table)
        (fn-owner-runtime-operation-role-table :index-writer fn-page-read-pool state)
        (if (not (and (eq family-word :runtime-operation-available)
                      (eq table-word :runtime-operation-available)))
            (mv :runtime-operation-unavailable nil fuel fn-mio$c fn-page-read-pool)
          (stobj-let ((fn-index-backing (fn-mio$c-provider fn-mio$c)))
           (word token left fn-index-backing fn-page-read-pool)
           (if (< (nfix fuel) (+ 1 (* 2 (+ 1 (fn-ibp-slot-depth fn-index-backing)))))
               (mv :yield nil (nfix fuel) fn-index-backing fn-page-read-pool)
             (mv-let (census-word census)
            (fn-iwd-census :generation-reserve pc
                          (fn-ibp-builder fn-index-backing)
                          (fn-ibp-page-pending fn-index-backing)
                          (fn-ibp-slot-depth fn-index-backing)
                          (fn-ibp-pool-capacity fn-index-backing))
            (if (not (eq census-word :census))
                (mv census-word nil fuel fn-index-backing fn-page-read-pool)
              (mv-let (demand-word demand) (fn-iwd-demand census family table)
               (if (not (eq demand-word :runtime-operation-available))
                   (mv demand-word nil fuel fn-index-backing fn-page-read-pool)
                 (mv-let (key-word key) (fn-owner-index-key state)
                  (if (not (eq key-word :key))
                      (mv key-word nil fuel fn-index-backing fn-page-read-pool)
                   (mv-let (reserved token fn-index-backing fn-page-read-pool)
                  (fn-igr-reserve pc demand fn-index-backing fn-page-read-pool)
                  (if (not (eq reserved :reserved))
                      (mv reserved token fuel fn-index-backing fn-page-read-pool)
                    (let ((fn-index-backing
                           (update-fn-ibp-builder
                            (update-nth 4 key (fn-ibp-builder fn-index-backing))
                            fn-index-backing)))
                     (mv-let (registered left fn-index-backing)
                      (fn-igr-register (nfix fuel) fn-index-backing)
                      (mv registered token left fn-index-backing fn-page-read-pool))))))))))))
           (if (not (eq word :registered))
               (mv word token left fn-mio$c fn-page-read-pool)
             (mv-let (captured remaining fn-mio$c)
              (fn-owner-index-writer-arena-capture left fn-mio$c fn-arena state)
              (mv captured token remaining fn-mio$c fn-page-read-pool)))))))))))

