; GENERATED by tools/interface_emit.py from raw route declarations.
; No availability filter: an absent target refuses the selected image.
(in-package "ACL2")
(include-book "../books/definterface")
(definterface fn-di-raw-with-problem :class :program :direct "Image-build declaration lint over the loaded world; no client data or served decision")
(definterface fn-di-raw-guarded-problem :class :program :direct "Image-build exact guard and stobj ABI validation over the exported ACL2 world")
(definterface fn-di-raw-guarded-target :class :program :direct "Image-build resolution of actual compiled callback or registered creator EXEC")
