; GENERATED by tools/interface_emit.py from raw route declarations.
; No availability filter: an absent target refuses the selected image.
(in-package "ACL2")
(include-book "../books/definterface")
(include-book "../books/decoded-worker-job")
(include-book "../books/history-paged")
(include-book "../books/history-paged-adopt")
(include-book "../books/history-records")
(include-book "../books/resource-vector-exec")
(definterface create-fn-resource-ledger :class :common-lisp-compliant :kinds () :raw-guarded (0 nil (fn-resource-ledger)))
; outside the DTN image: fn-owner-control-submit :raw-with (:carried fn-owner-served-carried), whose row is defined in host/owner-served-carried.lisp, which host/native/build-dtn.lisp does not load
; outside the DTN image: fn-owner-io :raw-with (:carried fn-owner-served-carried), whose row is defined in host/owner-served-carried.lisp, which host/native/build-dtn.lisp does not load
; outside the DTN image: fn-owner-take :raw-with (:carried fn-owner-served-carried), whose row is defined in host/owner-served-carried.lisp, which host/native/build-dtn.lisp does not load
; outside the DTN image: fn-owner-known-abort :raw-with (:carried fn-owner-served-carried), whose row is defined in host/owner-served-carried.lisp, which host/native/build-dtn.lisp does not load
; outside the DTN image: fn-owner-prepare-consumer :raw-with (:carried fn-owner-served-carried), whose row is defined in host/owner-served-carried.lisp, which host/native/build-dtn.lisp does not load
; outside the DTN image: fn-owner-prepare-identity :raw-with (:carried fn-owner-served-carried), whose row is defined in host/owner-served-carried.lisp, which host/native/build-dtn.lisp does not load
; outside the DTN image: fn-owner-prepare-retention :raw-with (:carried fn-owner-served-carried), whose row is defined in host/owner-served-carried.lisp, which host/native/build-dtn.lisp does not load
; outside the DTN image: fn-owner-prepare-topic :raw-with (:carried fn-owner-served-carried), whose row is defined in host/owner-served-carried.lisp, which host/native/build-dtn.lisp does not load
; outside the DTN image: fn-owner-refuse-reservation :raw-with (:carried fn-owner-served-carried), whose row is defined in host/owner-served-carried.lisp, which host/native/build-dtn.lisp does not load
(definterface create-fn-hrecs$c :class :common-lisp-compliant :kinds () :raw-guarded (0 nil (fn-hrecs$c)))
(definterface fn-di-raw-with-problem :class :program :direct "Image-build declaration lint over the loaded world; no client data or served decision")
(definterface fn-di-raw-guarded-problem :class :program :direct "Image-build exact guard and stobj ABI validation over the exported ACL2 world")
(definterface fn-di-raw-guarded-target :class :program :direct "Image-build resolution of actual compiled callback or registered creator EXEC")
(definterface create-fn-hrecs$s :class :common-lisp-compliant :kinds () :raw-guarded (0 nil (fn-hrecs$s)))
(definterface create-fn-hist$p :class :common-lisp-compliant :kinds () :raw-guarded (0 nil (fn-hist$p)))
(definterface fn-hroot-index-demand :class :common-lisp-compliant :kinds ((ordinal natp)) :raw-with (fn-hist$pcorr-implies-wfp fn-hist$p-root-is-physical))
(definterface fn-hroot-read-demand :class :common-lisp-compliant :kinds ((ordinal natp) (retained natp)) :raw-with (fn-hist$pcorr-implies-wfp fn-hist$p-root-is-physical))
(definterface fn-hist$p-root-index-next :class :common-lisp-compliant :kinds ((ordinal natp)) :raw-with (fn-hist$pcorr-implies-wfp fn-hist$p-index-next-keeps-wfp))
(definterface fn-hist$p-read :class :common-lisp-compliant :kinds ((ordinal natp)) :raw-with (fn-hist$pcorr-implies-wfp fn-hist$p-read-is-history-row))
(definterface fn-hist$p-append :class :common-lisp-compliant :kinds () :raw-with (fn-hist$pcorr-implies-wfp fn-hist$p-append-keeps-wfp))
(definterface fn-hist$p-candidate-word :class :common-lisp-compliant :kinds ((expected-count natp)) :raw-with (fn-hist$pcorr-implies-wfp fn-hist$p-count-natp))
(definterface create-fn-decoded-job :class :common-lisp-compliant :kinds () :raw-guarded (0 nil (fn-decoded-job)))
