(in-package "ACL2")
(include-book "../books/native-hybrid-control")
(defun fn-native-hybrid-control-host-max-frame ()
  (declare (xargs :mode :program))
  (+ *fn-frame-overhead-octets* *fn-nhctrl-max-payload*))
(defun fn-native-hybrid-control-host-uint32 (text)
  (declare (xargs :mode :program))
  (fn-native-hybrid-control-uint32 text))
(defun fn-native-hybrid-control-host-enroll-encode (g p e m)
  (declare (xargs :mode :program))
  (fn-native-hybrid-control-enroll-encode g p e m))
(defun fn-native-hybrid-control-host-enroll-decode (x)
  (declare (xargs :mode :program))
  (fn-native-hybrid-control-enroll-decode x))
(defun fn-native-hybrid-control-host-author-encode (g source ed ml path)
  (declare (xargs :mode :program))
  (fn-native-hybrid-control-author-encode g source ed ml path))
(defun fn-native-hybrid-control-host-author-decode (x)
  (declare (xargs :mode :program))
  (fn-native-hybrid-control-author-decode x))
(defun fn-native-hybrid-control-host-revoke-encode (g p)
  (declare (xargs :mode :program))
  (fn-native-hybrid-control-revoke-encode g p))
(defun fn-native-hybrid-control-host-revoke-decode (x)
  (declare (xargs :mode :program))
  (fn-native-hybrid-control-revoke-decode x))
