; Program bridge for the native administrative plan.
(in-package "ACL2")
(include-book "../books/native-admin")
(ld "store-node-host.lisp" :ld-error-action :error)
(ld "owner-host.lisp" :ld-error-action :error)

(defun fn-native-admin-host-plan (argv) (fn-native-admin-plan argv))
(defun fn-native-admin-host-status (result) (fn-native-admin-result-status result))
(defun fn-native-admin-host-reason (result) (fn-native-admin-result-reason result))
(defun fn-native-admin-host-kind (result) (fn-native-admin-result-kind result))
(defun fn-native-admin-host-name (result) (fn-native-admin-result-name result))
(defun fn-native-admin-host-capacity (result) (fn-native-admin-result-capacity result))
(defun fn-native-admin-host-peer (result) (fn-native-admin-result-peer result))
(defun fn-native-admin-host-value (result) (fn-native-admin-result-value result))
(defun fn-native-admin-host-queryp (result) (fn-native-admin-result-queryp result))
(defun fn-native-admin-host-peer-report (state)
  ; The `peer list' report over the configuration the store just replayed.
  ; The rows are the replayed value's own; this bridge selects no peer,
  ; orders nothing, and renders no field: books/native-admin.lisp does all
  ; three and raw Lisp only writes the octets out.
  (declare (xargs :stobjs state :mode :program))
  (value (fn-native-admin-peer-report
          (fn-cfg-peers (fn-cfg-value (f-get-global 'fn-store-cfg state))))))
(defun fn-native-admin-host-owner-reconfigure (id plan state)
  ; The live arm.  The delta list, labels as strings, is ACL2's
  ; (`fn-native-admin-plan-deltas', books/native-admin.lisp); this bridge
  ; only hands it to the owner's staging step.
  (declare (xargs :stobjs state :mode :program))
  (let ((deltas (fn-native-admin-plan-deltas plan)))
    (if deltas
        (fn-owner-reconfigure-deltas id deltas state)
      (value :refused))))
(defun fn-native-admin-host-apply (plan monotonic wall state)
  (declare (xargs :stobjs state :mode :program))
  (let ((kind (fn-native-admin-result-kind plan)))
    (cond ((member-equal kind '(:set-bp-boundary :set-bp-route :remove-bp-route))
           (fn-store-cfg-peer-delta-record
            (fn-native-admin-plan-deltas plan) monotonic wall state))
          ((equal kind :set-peer)
           (fn-store-cfg-peer-delta-record
            (list (fn-native-admin-set-peer-delta plan))
            monotonic wall state))
          ((equal kind :remove-peer)
           (fn-store-cfg-remove-peer (fn-native-admin-result-name plan)
                                     monotonic wall state))
          ((equal kind :set-policy)
           (fn-store-cfg-set-policy (fn-native-admin-result-name plan)
                                    (fn-native-admin-result-value plan)
                                    monotonic wall state))
          (t (fn-store-cfg-reconfigure
              kind (fn-native-admin-result-name plan)
              (fn-native-admin-result-capacity plan)
              monotonic wall state)))))
(defun fn-native-admin-host-config-name (generation)
  (fn-native-admin-config-name generation))
(defun fn-native-admin-host-clock-observation (monotonic wall)
  (fn-native-admin-clock-observation monotonic wall))
(defun fn-native-admin-host-clock-status (result)
  (fn-native-admin-clock-status result))
(defun fn-native-admin-host-clock-stamp (result)
  (fn-native-admin-clock-stamp result))
(defun fn-native-admin-host-clock-monotonic (stamp)
  (fn-clock-monotonic stamp))
(defun fn-native-admin-host-clock-wall (stamp)
  (fn-clock-wall stamp))
(defun fn-native-admin-host-publication-status (result)
  (fn-native-admin-publication-status result))
(defun fn-native-admin-host-publication-reason (result)
  (fn-native-admin-publication-reason result))
(defun fn-native-admin-host-publication-generation (result)
  (fn-native-admin-publication-generation result))
(defun fn-native-admin-host-publication-name (result)
  (fn-native-admin-publication-name result))
(defun fn-native-admin-host-publication-jpub (result)
  (fn-native-admin-publication-jpub result))
