; Program bridge for the native administrative plan.
(in-package "ACL2")
(include-book "../books/native-admin")
(ld "store-node-host.lisp" :ld-error-action :error)
(ld "owner-host.lisp" :ld-error-action :error)

(defun fn-native-admin-host-plan (argv) (fn-native-admin-plan argv))
(defun fn-native-admin-host-status (result) (fn-native-admin-result-status result))
(defun fn-native-admin-host-reason (result) (fn-native-admin-result-reason result))
(defun fn-native-admin-host-kind (result) (fn-native-admin-result-kind result))
(defun fn-native-admin-host-name (result) (fn-native-admin-result-name result))
(defun fn-native-admin-host-capacity (result) (fn-native-admin-result-capacity result))
(defun fn-native-admin-host-peer (result) (fn-native-admin-result-peer result))
(defun fn-native-admin-host-value (result) (fn-native-admin-result-value result))
(defun fn-native-admin-host-queryp (result) (fn-native-admin-result-queryp result))
(defun fn-native-admin-host-peer-report (state)
  ; The `peer list' report over the configuration the store just replayed.
  ; The rows are the replayed value's own; this bridge selects no peer,
  ; orders nothing, and renders no field: books/native-admin.lisp does all
  ; three and raw Lisp only writes the octets out.
  (declare (xargs :stobjs state :mode :program))
  (value (fn-native-admin-peer-report
          (fn-cfg-peers (fn-cfg-value (f-get-global 'fn-store-cfg state))))))
(defun fn-native-admin-host-owner-reconfigure (id plan state)
  (declare (xargs :stobjs state :mode :program))
  (let* ((kind (fn-native-admin-result-kind plan))
         (delta
          (cond ((equal kind :set-peer)
                 (fn-cfg-set-peer-delta (fn-native-admin-result-peer plan)))
                ((equal kind :remove-peer)
                 (fn-cfg-remove-peer-delta (fn-native-admin-result-name plan)))
                ((equal kind :create-group)
                 (fn-cfg-create-group (fn-native-admin-result-name plan)
                                      *fn-cfg-default-policy-id*))
                ((equal kind :remove-group)
                 (fn-cfg-remove-group (fn-native-admin-result-name plan)))
                ((equal kind :set-capacity)
                 (fn-cfg-set-capacity (fn-native-admin-result-capacity plan)))
                ; `fn-cfg-set-policy' takes the two labels as strings, as
                ; `fn-store-cfg-set-policy' (store-node-host.lisp) hands them.
                ((equal kind :set-policy)
                 (let ((slot (fn-store-octets->string
                              (fn-native-admin-result-name plan)))
                       (id (fn-store-octets->string
                            (fn-native-admin-result-value plan))))
                   (if (or (equal slot :bad) (equal id :bad))
                       nil
                     (fn-cfg-set-policy slot id))))
                (t nil))))
    (if delta
        (fn-owner-reconfigure-deltas id (list delta) state)
      (value :refused))))
(defun fn-native-admin-host-apply (plan monotonic wall state)
  (declare (xargs :stobjs state :mode :program))
  (let ((kind (fn-native-admin-result-kind plan)))
    (cond ((equal kind :set-peer)
           (fn-store-cfg-peer-delta-record
            (list (fn-cfg-set-peer-delta (fn-native-admin-result-peer plan)))
            monotonic wall state))
          ((equal kind :remove-peer)
           (fn-store-cfg-remove-peer (fn-native-admin-result-name plan)
                                     monotonic wall state))
          ((equal kind :set-policy)
           (fn-store-cfg-set-policy (fn-native-admin-result-name plan)
                                    (fn-native-admin-result-value plan)
                                    monotonic wall state))
          (t (fn-store-cfg-reconfigure
              kind (fn-native-admin-result-name plan)
              (fn-native-admin-result-capacity plan)
              monotonic wall state)))))
(defun fn-native-admin-host-config-name (generation)
  (fn-native-admin-config-name generation))
(defun fn-native-admin-host-clock-observation (monotonic wall)
  (fn-native-admin-clock-observation monotonic wall))
(defun fn-native-admin-host-clock-status (result)
  (fn-native-admin-clock-status result))
(defun fn-native-admin-host-clock-stamp (result)
  (fn-native-admin-clock-stamp result))
(defun fn-native-admin-host-clock-monotonic (stamp)
  (fn-clock-monotonic stamp))
(defun fn-native-admin-host-clock-wall (stamp)
  (fn-clock-wall stamp))
(defun fn-native-admin-host-publication-status (result)
  (fn-native-admin-publication-status result))
(defun fn-native-admin-host-publication-reason (result)
  (fn-native-admin-publication-reason result))
(defun fn-native-admin-host-publication-generation (result)
  (fn-native-admin-publication-generation result))
(defun fn-native-admin-host-publication-name (result)
  (fn-native-admin-publication-name result))
(defun fn-native-admin-host-publication-jpub (result)
  (fn-native-admin-publication-jpub result))
