(in-package "ACL2")
(include-book "../books/native-hybrid-control")
(defun fn-native-hybrid-control-host-max-frame ()
  (declare (xargs :mode :program))
  (+ *fn-frame-overhead-octets* *fn-nhctrl-max-payload*))
(defun fn-native-hybrid-control-host-enroll-encode (g p e m)
  (declare (xargs :mode :program))
  (fn-native-hybrid-control-enroll-encode g p e m))
(defun fn-native-hybrid-control-host-enroll-decode (x)
  (declare (xargs :mode :program))
  (fn-native-hybrid-control-enroll-decode x))
(defun fn-native-hybrid-control-host-author-encode
    (g id source ed ml path groups obligation subject release charge)
  (declare (xargs :mode :program))
  (fn-native-hybrid-control-author-encode
   g id source ed ml path groups obligation subject release charge))
(defun fn-native-hybrid-control-host-author-decode (x)
  (declare (xargs :mode :program))
  (fn-native-hybrid-control-author-decode x))
