; Actual owner/MIO/SAMEpool mount entry. Runtime phase units are missing;
; defaults refuse before socket/session/fid/provider constructors.
(in-package "ACL2")
(include-book "../books/ninep-mount")
(include-book "../books/runtime-operation-source")
(include-book "index-publication-host")

(defun fn-9p-mount-operation-demand (source)
 (declare (xargs :guard t))
 (declare (ignore source))
 ; A constructor fragment or source/family tuple is not the complete
 ; allocator/caller/parser/provider/return contract. No invented tariff.
 (mv :ninep-operation-unqualified nil))

(defun fn-ninep-mount-acquire (fuel fn-ninep-session fn-mio$c fn-page-read-pool state)
 (declare (xargs :stobjs (fn-ninep-session fn-mio$c fn-page-read-pool state)
                 :guard (natp fuel) :verify-guards nil))
 (mv-let (runtime-word source)
  (fn-owner-runtime-operation-source :ninep-readonly fn-page-read-pool state)
  (if (not source)
      (mv runtime-word nil fuel fn-ninep-session fn-mio$c fn-page-read-pool state)
    (mv-let (cost-word demand) (fn-9p-mount-operation-demand source)
     (if (not (eq cost-word :operation-demand))
         (mv cost-word nil fuel fn-ninep-session fn-mio$c fn-page-read-pool state)
       (mv-let (owner-word pc frontier version view) (fn-owner-index-source state)
        (declare (ignore pc view))
        (if (not (eq owner-word :current))
            (mv :mount-unavailable nil fuel fn-ninep-session fn-mio$c fn-page-read-pool state)
          (let ((generation (fn-9p-mount-current-generation fn-mio$c)))
           (mv-let (word row left) (fn-mio-generation-read generation fuel fn-mio$c)
            (let ((publication (fn-omk-at 2 row)))
             (if (not (and (eq word :present) (natp left)
                           (fn-ipub-shapep publication)
                           (equal frontier (fn-ipub-frontier publication))
                           (equal version (fn-ipub-view publication))))
                 (mv (if (eq word :yield) :yield :mount-unavailable) nil left
                     fn-ninep-session fn-mio$c fn-page-read-pool state)
               (mv-let (word token remaining fn-ninep-session fn-mio$c fn-page-read-pool)
                (fn-9p-mount-reserve-internal demand left fn-ninep-session fn-mio$c fn-page-read-pool)
                (mv word token remaining fn-ninep-session fn-mio$c fn-page-read-pool state))))))))))))

(defun fn-ninep-mount-pin-step (fuel fn-ninep-session fn-mio$c state)
 (declare (xargs :stobjs (fn-ninep-session fn-mio$c state)
                 :guard (natp fuel) :verify-guards nil))
 (mv-let (word token left fn-ninep-session fn-mio$c)
  (fn-9p-mount-pin-step fuel fn-ninep-session fn-mio$c)
  (mv word token left fn-ninep-session fn-mio$c state)))

(defun fn-ninep-mount-return (fuel fn-ninep-session fn-mio$c fn-page-read-pool state)
 (declare (xargs :stobjs (fn-ninep-session fn-mio$c fn-page-read-pool state)
                 :guard (natp fuel) :verify-guards nil))
 (mv-let (word left fn-ninep-session fn-mio$c fn-page-read-pool)
  (fn-9p-mount-return-current fuel fn-ninep-session fn-mio$c fn-page-read-pool)
  (mv word left fn-ninep-session fn-mio$c fn-page-read-pool state)))

(defun fn-ninep-runtime-start (port fn-page-read-pool state)
 (declare (xargs :stobjs (fn-page-read-pool state) :guard t))
 (if (not (and (natp port) (< port 65536)))
     (mv :invalid-port nil fn-page-read-pool state)
  (mv-let (word source)
   (fn-owner-runtime-operation-source :ninep-readonly fn-page-read-pool state)
   (if (not source) (mv word nil fn-page-read-pool state)
     (mv-let (cost-word demand) (fn-9p-mount-operation-demand source)
      (declare (ignore demand))
      (mv cost-word nil fn-page-read-pool state)))))
