; PRF-1133: actual owner globals for a fixed logical view bound to an arena.
; Native callers hold the owner mutex. Capture ticket is issued by fn-osl;
; a maintenance token is borrowed, not issued or funded by this adapter.
(in-package "ACL2")
(include-book "../books/payload-view-lease")
(include-book "../books/snapshot-capture-lease")
(include-book "../books/payload-view-arena")
(include-book "recovery-payload-view-state")
(defun fn-owner-payload-view-global (key state)
  (declare (xargs :stobjs state :mode :program))
  (if (f-boundp-global key state) (f-get-global key state) nil))
(defun fn-owner-payload-view-ledger (state)
  (declare (xargs :stobjs state :mode :program))
  (if (f-boundp-global 'fn-owner-payload-view state)
      (f-get-global 'fn-owner-payload-view state)
    (fn-pvl-seed)))
(defun fn-owner-payload-view-acquire (maintenance fn-arena state)
  (declare (xargs :stobjs (fn-arena state) :mode :program))
  (let ((capture (fn-owner-payload-view-global 'fn-owner-osn-lease state)))
    (if (not (and (fn-osl-leasep capture)
                  (equal (fn-omk-at 1 capture)
                         (fn-owner-payload-view-global 'fn-owner-sco-inflight state))))
        (value '(:refused :capture-not-owned))
      (let ((answer (fn-pvl-acquire (fn-owner-payload-view-ledger state)
                                   (fn-arena-count fn-arena)
                                   (fn-omk-at 0 capture) maintenance)))
        (if (not (eq (car answer) :acquired)) (value answer)
          (let ((state (f-put-global 'fn-owner-payload-view (fn-omk-at 2 answer) state)))
            (value answer)))))))
(defun fn-owner-payload-view-live-p (token state)
  (declare (xargs :stobjs state :mode :program))
  (value (fn-pvl-livep token (fn-owner-payload-view-ledger state))))
(defun fn-owner-payload-view-release (token settlement state)
  (declare (xargs :stobjs state :mode :program))
  (let ((answer (fn-pvl-release (fn-owner-payload-view-ledger state) token settlement)))
    (if (not (eq (car answer) :released)) (value answer)
      (let ((state (f-put-global 'fn-owner-payload-view (fn-omk-at 2 answer) state)))
        (value answer)))))
; Every current destructive native arena entry goes through this decision.
; Refusal returns the arena and ownership unchanged; no clear follows it.
(defun fn-owner-payload-view-reset (fn-arena state)
  (declare (xargs :stobjs (fn-arena state) :mode :program))
  ; Preflight the separate recovery namespace before destructive arena work.
  (let ((recovery (fn-rpv-reset (fn-owner-recovery-payload-view-ledger state))))
    (if (not (eq (car recovery) :reset))
        (mv nil recovery fn-arena state)
      (mv-let (answer fn-arena)
        (fn-pvl-clear (fn-owner-payload-view-ledger state) fn-arena)
        (if (not (eq (car answer) :reset)) (mv nil answer fn-arena state)
          (let* ((state (f-put-global 'fn-owner-payload-view (fn-omk-at 2 answer) state))
                 (state (f-put-global 'fn-owner-recovery-payload-view
                                      (fn-omk-at 2 recovery) state)))
            (mv nil answer fn-arena state)))))))

(defun fn-owner-payload-view-owned-p (state)
  (declare (xargs :stobjs state :mode :program))
  (let ((recovery (fn-owner-recovery-payload-view-ledger state)))
    (value (if (or (fn-omk-at 2 (fn-owner-payload-view-ledger state))
                   (not (fn-rpv-ledgerp recovery))
                   (fn-rpv-ownedp recovery)) t nil))))
