; INTERNAL actual accepted request completion, never native-supplied origin.
(in-package "ACL2")
(include-book "receiver-source-gate-host")
(include-book "../books/index-reader-request")
(include-book "../books/connection-receiver-repin")
(defun fn-owner-rx-connection-record-accepted-repin-backing (token fn-index-backing state)
 (declare (xargs :stobjs (fn-index-backing state) :mode :program))
  (let* ((receipt (fn-ibp-request-pending fn-index-backing))
         (request (fn-irr-receipt-request receipt))
         (phase (fn-omk-at 7 receipt))
         (id (fn-omk-at 1 request))
         (old (fn-irr-request-holder request))
         ; Replacement getter intentionally requires COMMITTED. Here the actual
         ; completed-but-uncommitted accepted phase authorizes field9.
         (new (fn-omk-at 9 receipt))
         (source (fn-irr-request-input-source request))
         (issued (fn-owner-rx-connection-issued state)))
   (cond
    ((not (member-eq phase '(:read-ready-repin-released :read-ready-repin-held)))
     (mv :unchanged state))
    ((not (and (eq (fn-omk-at 0 receipt) :index-request-receipt)
               (fn-ich-tokenp new) (fn-ibp-query-tokenp token)
               (equal token (fn-irq-candidate-token (fn-omk-at 2 receipt)
                  (fn-omk-at 3 receipt) (fn-irq-receipt-request-generation receipt)))
               (fn-omk-widthp source 4) (eq (fn-omk-at 0 source) :receiver-source)
               (equal (fn-omk-at 1 source) (fn-omk-at 2 issued))
               (fn-crx-origin-currentp (fn-omk-at 1 issued) id old
                  (fn-omk-at 2 source) (fn-omk-at 3 source))))
     (mv :recovery-required state))
    (t (let ((next (fn-crx-repin-issued issued id old new phase)))
        (if (equal next issued) (mv :recovery-required state)
         (let ((state (f-put-global 'fn-owner-rx-connection-issued next state)))
          (mv :associated state)))))))
)
(defun fn-owner-rx-connection-record-repin (token fn-mio$c state)
 (declare (xargs :stobjs (fn-mio$c state) :mode :program))
 (stobj-let ((fn-index-backing (fn-mio$c-provider fn-mio$c)))
  (word state)
  (fn-owner-rx-connection-record-accepted-repin-backing token fn-index-backing state)
  (mv word fn-mio$c state)))
