; PRF-1149: actual cold authority is issued from successful loader STATE.
; This source WIP is not activated until the loader generation/region and
; one-pass SSR carry companion are installed. No caller supplies final count.
(in-package "ACL2")
(include-book "../books/recovery-source-authority")
(include-book "../books/owner-canonical-state")
(include-book "store-checkpoint-context-host")

(defun fn-owner-recovery-global (key state)
  (declare (xargs :stobjs state :mode :program))
  (and (boundp-global key state) (f-get-global key state)))
; Called only inside the actual quiescent payload-reset lifecycle exclusion,
; before any physical load. Source callbacks retain their issued epoch.
(defun fn-owner-recovery-source-reset (state)
  (declare (xargs :stobjs state :mode :program))
  (let ((state (fn-owner-canonical-reset state)))
    (value (list :reset (fn-owner-canonical-epoch state)))))
(defun fn-owner-recovery-source-start (state)
  (declare (xargs :stobjs state :mode :program))
  (let* ((meta (fn-store-sco-recovery-source-value state))
         (generation (fn-store-sco-recovery-source-generation-value state))
         (epoch (fn-owner-canonical-epoch state))
         (prior (fn-owner-recovery-global 'fn-owner-recovery-source state))
         (oldticket (fn-owner-recovery-global 'fn-owner-recovery-next-ticket state))
         (ticket (if (not (boundp-global 'fn-owner-recovery-next-ticket state)) 0 oldticket)))
    (if (or (fn-owner-canonical-state state) (not (natp ticket))
            (and (fn-omk-widthp prior 9) (equal (fn-omk-at 2 prior) epoch)))
        (value '(:unavailable :recovery-source))
      (mv-let (word next) (fn-rsa-begin ticket epoch generation meta)
        (if (not (eq word :issued)) (value '(:unavailable :verified-source))
          (let* ((state (f-put-global 'fn-owner-recovery-next-ticket (+ 1 ticket) state))
                 (state (f-put-global 'fn-owner-recovery-source next state)))
            (value (list :issued (fn-rsa-token next)))))))))
(defun fn-owner-recovery-source-token (state)
  (declare (xargs :stobjs state :mode :program))
  (let* ((c (fn-owner-recovery-global 'fn-owner-recovery-source state))
         (token (fn-rsa-token c)))
    (value (if (and (fn-rsa-metap (fn-store-sco-recovery-source-value state))
                    (fn-rsa-currentp c token (fn-owner-canonical-epoch state)
                               (fn-store-sco-recovery-source-generation-value state)))
               token '(:unavailable :recovery-source)))))
(defun fn-owner-recovery-source-observe (token original-context actual-fold state)
  (declare (xargs :stobjs state :mode :program))
  (let ((c (fn-owner-recovery-global 'fn-owner-recovery-source state)))
    (if (not (fn-rsa-metap (fn-store-sco-recovery-source-value state)))
        (value '(:unavailable :verified-source))
    (mv-let (word next)
      (fn-rsa-observe c token (fn-owner-canonical-epoch state)
                      (fn-store-sco-recovery-source-generation-value state)
                      original-context actual-fold)
      (if (not (eq word :counted)) (value (list :unavailable word))
        (let ((state (f-put-global 'fn-owner-recovery-source next state)))
          (value (list :counted (fn-rsa-token next)))))))))
