; Single readonly recovery view state and reset implementation.
(in-package "ACL2")
(include-book "../books/recovery-payload-view")
(defun fn-owner-recovery-payload-view-ledger (state)
  (declare (xargs :stobjs state :mode :program))
  (if (f-boundp-global 'fn-owner-recovery-payload-view state)
      (f-get-global 'fn-owner-recovery-payload-view state) (fn-rpv-seed)))
(defun fn-owner-recovery-payload-view-owned-value (state)
  (declare (xargs :stobjs state :mode :program))
  (fn-rpv-ownedp (fn-owner-recovery-payload-view-ledger state)))
(defun fn-owner-recovery-payload-view-reset (state)
  (declare (xargs :stobjs state :mode :program))
  (let ((answer (fn-rpv-reset (fn-owner-recovery-payload-view-ledger state))))
    (if (not (eq (car answer) :reset)) (value answer)
      (let ((state (f-put-global 'fn-owner-recovery-payload-view (fn-omk-at 2 answer) state)))
        (value answer)))))
