; Production recovery-only view and INITIAL role transaction. Source WIP:
; exact includes/caller admission are pending, never substitute live PVL.
(in-package "ACL2")
(include-book "snapshot-initial-host")
(include-book "page-read-host")
(include-book "../books/recovery-payload-view")
(include-book "../books/snapshot-initial-custody")
(include-book "../books/payload-view-arena")
(include-book "recovery-payload-view-state")
(defun fn-owner-recovery-payload-view-acquire (source maintenance fn-arena fn-page-read-pool state)
  (declare (xargs :stobjs (fn-arena fn-page-read-pool state) :mode :program))
  (mv-let (erp descriptor state) (fn-owner-recovery-startup-source source state)
    (let ((ledger (fn-owner-page-read-ledger fn-page-read-pool)))
      (if (or erp (not (eq (fn-omk-at 0 descriptor) :recovery-census))
              (not (fn-owner-recovery-initial-livep source maintenance fn-page-read-pool state)))
          (mv erp '(:retained :initial-source) fn-arena fn-page-read-pool state)
        (let ((answer (fn-rpv-acquire (fn-owner-recovery-payload-view-ledger state)
                                      (fn-arena-count fn-arena) source maintenance)))
          (if (not (eq (car answer) :acquired))
              (mv nil answer fn-arena fn-page-read-pool state)
            (mv-let (word next) (fn-sni-role-claim ledger maintenance source :payload-view
                                                (fn-omk-at 1 answer))
              (if (not (eq word :claimed))
                  (mv nil (list :retained word) fn-arena fn-page-read-pool state)
                (let* ((fn-page-read-pool (fn-owner-page-read-keep-ledger next fn-page-read-pool))
                       (state (f-put-global 'fn-owner-recovery-payload-view
                                            (fn-omk-at 2 answer) state)))
                  (mv nil answer fn-arena fn-page-read-pool state))))))))))
(defun fn-owner-recovery-payload-view-release (token fn-page-read-pool state)
  (declare (xargs :stobjs (fn-page-read-pool state) :mode :program))
  (let* ((view (fn-owner-recovery-payload-view-ledger state))
         (active (fn-omk-at 3 view))
         (source (fn-omk-at 1 active)) (maintenance (fn-omk-at 2 active))
         (ledger (fn-owner-page-read-ledger fn-page-read-pool)))
    (if (not (and (fn-rpv-livep view token)
                  (fn-sni-role-releasablep ledger maintenance source :payload-view token)))
        (mv nil '(:retained :initial-view-custody) fn-page-read-pool state)
      (let ((answer (fn-rpv-release view token)))
        (if (not (eq (car answer) :released))
            (mv nil answer fn-page-read-pool state)
          (mv-let (word next) (fn-sni-role-return ledger maintenance source :payload-view token)
            (if (not (eq word :returned))
                (mv nil (list :retained word) fn-page-read-pool state)
              (let* ((fn-page-read-pool (fn-owner-page-read-keep-ledger next fn-page-read-pool))
                     (state (f-put-global 'fn-owner-recovery-payload-view
                                          (fn-omk-at 2 answer) state)))
                (mv nil answer fn-page-read-pool state)))))))))
