; Actual PRF acquire/release composed with INITIAL on the same physical pool.
; No host custody setter or caller joined flag. Source/caller admission pending.
(in-package "ACL2")
(include-book "page-file-lease-host")
(include-book "../books/snapshot-initial-custody")
(include-book "../books/history-records-disk")
(defun fn-owner-recovery-initial-root-filep (ledger source maintenance file)
  (declare (xargs :guard t))
  (let* ((initial (fn-prl-nth 3 (cdr (fn-prl-binding maintenance (fn-prl-nth 3 ledger)))))
         (context (fn-prl-nth 3 initial)))
    (and (fn-sni-livep ledger source maintenance)
         (equal file (fn-hrs-h-file (fn-prl-nth 5 context))))))
(defun fn-owner-recovery-initial-root-reservedp (ledger maintenance)
  (declare (xargs :guard t))
  (let* ((initial (fn-prl-nth 3 (cdr (fn-prl-binding maintenance (fn-prl-nth 3 ledger)))))
         (role (fn-sni-role-entry :source-root (fn-prl-nth 6 initial))))
    (equal (fn-prl-nth 1 role) :reserved)))
(defun fn-owner-recovery-initial-root-acquire (source maintenance file fn-page-read-pool)
  (declare (xargs :stobjs fn-page-read-pool))
  (if (not (and (fn-owner-recovery-initial-root-filep
                 (fn-owner-page-read-ledger fn-page-read-pool) source maintenance file)
                (fn-owner-recovery-initial-root-reservedp
                 (fn-owner-page-read-ledger fn-page-read-pool) maintenance)))
      (mv :initial-source-unavailable nil fn-page-read-pool)
    (mv-let (word token fn-page-read-pool)
      (fn-owner-page-file-pin file fn-page-read-pool)
      (if (not (eq word :admitted)) (mv word token fn-page-read-pool)
        (mv-let (claimed next)
          (fn-sni-role-claim (fn-owner-page-read-ledger fn-page-read-pool)
                            maintenance source :source-root token)
          (let ((fn-page-read-pool (fn-owner-page-read-keep-ledger next fn-page-read-pool)))
            ; The actual pin remains retained on a refused claim; report its
            ; token rather than silently rolling back an uncertain boundary.
            (mv (if (eq claimed :claimed) :admitted :initial-root-uncertain)
                token fn-page-read-pool)))))))
(defun fn-owner-recovery-initial-root-release (source maintenance token fn-page-read-pool)
  (declare (xargs :stobjs fn-page-read-pool))
  (if (not (fn-sni-role-releasablep (fn-owner-page-read-ledger fn-page-read-pool)
                                   maintenance source :source-root token))
      (mv :initial-root-retained fn-page-read-pool)
    (mv-let (word fn-page-read-pool) (fn-owner-page-file-unpin token fn-page-read-pool)
      (if (not (eq word :released)) (mv word fn-page-read-pool)
        (mv-let (returned next)
          (fn-sni-role-return (fn-owner-page-read-ledger fn-page-read-pool)
                             maintenance source :source-root token)
          (let ((fn-page-read-pool (fn-owner-page-read-keep-ledger next fn-page-read-pool)))
            (mv (if (eq returned :returned) :released :initial-root-uncertain)
                fn-page-read-pool)))))))
