; Scratch-only raw file profiling entry (served-path-cost lane): never committed.
(in-package "ACL2")
(require :sb-sprof)
(progn
        (defun fn-native-entry (st)
          (declare (ignore st))
          (fnn-crypto-startup)
          (fnn-tls-reset)
          (fnn-hsig-reset)
          (fnn-hsig-initialize)
          (let ((dir (sb-ext:posix-getenv "FN_SPROF_DIR")))
            (when dir
              (sb-thread:make-thread
               (lambda ()
                 (flet ((f (n) (concatenate 'string dir "/" n)))
                   (loop until (probe-file (f "start")) do (sleep 0.05))
                   (let ((names (sb-ext:posix-getenv "FN_DPROF")))
                     (if names
                         (let ((syms nil))
                           (dolist (n (let ((acc nil) (start 0))
                                        (loop for i = (position #\, names :start start)
                                              do (push (subseq names start i) acc)
                                                 (if i (setq start (1+ i)) (return)))
                                        acc))
                             (dolist (pkg '("ACL2" "ACL2_*1*_ACL2"))
                               (let ((sym (find-symbol (string-upcase n) pkg)))
                                 (when (and sym (fboundp sym)) (push sym syms)))))
                           (eval `(sb-profile:profile ,@syms))
                           (loop until (probe-file (f "stop")) do (sleep 0.05))
                           (with-open-file (s (f "dprof.txt") :direction :output :if-exists :supersede)
                             (let ((*standard-output* s)) (sb-profile:report)))
                           (sb-profile:unprofile))
                       (progn
                         (sb-sprof:start-profiling :max-samples 1000000 :mode :cpu
                                                   :sample-interval 0.001 :threads :all)
                         (loop until (probe-file (f "stop")) do (sleep 0.05))
                         (sb-sprof:stop-profiling))))
                   (unless (sb-ext:posix-getenv "FN_DPROF")
                   (with-open-file (s (f "flat.txt") :direction :output :if-exists :supersede)
                     (sb-sprof:report :type :flat :max 80 :stream s))
                   (with-open-file (s (f "graph.txt") :direction :output :if-exists :supersede)
                     (sb-sprof:report :type :graph :max 60 :stream s)))
                   (with-open-file (s (f "done") :direction :output :if-exists :supersede)
                     (print :done s))))
               :name "fn-sprof")))
          (fnn-main)
          (values nil :exited *the-live-state*)))
