; Recording transport tests only. No qualified runtime/PRS/ATS authority.
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(defvar *the-live-state* :state)
(defvar *recorded-dispatch* (make-hash-table))
(defun fnn-fault (control &rest args) (error (apply #'format nil control args)))
(defun fnn-fixed-callback-fail (name reason value) (error "~S ~S ~S" name reason value))
(defun fnn-fixed-raw-callback (name) (or (gethash name *recorded-dispatch*) (error "missing ~S" name)))
(load "build/writer-operation-source/core-mv-exact.lisp")
(load "host/native/index-writer-turn.lisp")
(setf (gethash 'fn-owner-index-writer-step-owned *recorded-dispatch*)
 (lambda (fuel slots mio pool state)
  (assert (equal (list fuel slots mio pool state) '(8 :slots1 :mio2 :pool2 :state)))
  (values :ready 3 :mio-stepped state)))

(let ((prepares 0) (resumes 0) (model-issues 0) (faults 0)
      (token '(:index-generation 1 1 0)) (binding nil))
 (setf (gethash 'fn-owner-cat-prepare-indexed *recorded-dispatch*)
  (lambda (slot fuel slots mio arena cat pool state)
   (assert (equal (list slot fuel slots mio arena cat pool state)
                  '(0 8 :slots0 :mio0 :arena :cat :pool0 :state)))
   (incf prepares) (incf model-issues)
   (values nil :yield token :slots1 :mio1 :pool1 state)))
 (setf (gethash 'fn-owner-index-writer-begin *recorded-dispatch*)
  (lambda (slots mio arena pool state)
   (assert (equal (list slots mio arena pool state) '(:slots1 :mio1 :arena :pool1 :state)))
   (incf resumes)
   (values :arena-held token :mio2 :pool2 state)))
 (setf (gethash 'fn-owner-index-writer-complete-owned *recorded-dispatch*)
  (lambda (fuel slots mio pool state)
   (assert (equal (list fuel slots mio pool state) '(8 :slots1 :mio-stepped :pool2 :state)))
   (values :published 4 :mio3 state)))
 (setf (gethash 'fn-owner-index-writer-finish *recorded-dispatch*)
  (lambda (slots pool state)
   (assert (equal (list slots pool) '(:slots1 :pool2)))
   (values :left :slots2 :pool3 state)))
 (setf (gethash 'fn-owner-index-writer-fault *recorded-dispatch*)
  (lambda (slots pool state) (declare (ignore slots pool))
   (incf faults) (values :recovery :slots-fenced :pool-fenced state)))
 (setf binding (fnn-index-writer-binding-make :pool0 :slots0 0 8 :mio0 :arena :cat))
 (multiple-value-bind (word actual) (fnn-index-writer-prepare-locked binding)
  (assert (and (eq word :yield) (eq actual token))))
 (multiple-value-bind (word actual) (fnn-index-writer-resume-locked binding)
  (assert (and (eq word :arena-held) (eq actual token))))
 (assert (and (= prepares 1) (= resumes 1) (= model-issues 1) (= faults 0)))
 (multiple-value-bind (word left) (fnn-index-writer-step-locked binding)
  (assert (and (eq word :ready) (= left 3)
               (eq (fnn-index-writer-binding-mio binding) :mio-stepped))))
 (assert (eq (fnn-index-writer-complete-locked binding) :published))
 (assert (eq (fnn-index-writer-finish-locked binding) :left))
 (assert (equal (list (fnn-index-writer-binding-slots binding)
                      (fnn-index-writer-binding-pool binding)
                      (fnn-index-writer-binding-mio binding)) '(:slots2 :pool3 :mio3)))
 (format t "PASS recorded yield/resume: prepare1 resume1 model-issue1; actual returned references retained~%"))

; An ERP after a returned mutation fences the RETURNED objects, not old refs.
(let ((binding nil) (faulted nil))
 (setf (gethash 'fn-owner-cat-prepare-indexed *recorded-dispatch*)
  (lambda (&rest args) (declare (ignore args))
   (values :error :recovery-required nil :new-slots :new-mio :new-pool :state)))
 (setf (gethash 'fn-owner-index-writer-fault *recorded-dispatch*)
  (lambda (slots pool state)
   (assert (and (eq slots :new-slots) (eq pool :new-pool)))
   (setf faulted t) (values :recovery :fenced-slots :fenced-pool state)))
 (setf binding (fnn-index-writer-binding-make :old-pool :old-slots 0 8 :old-mio :arena :cat))
 (handler-case (fnn-index-writer-prepare-locked binding) (error () nil))
 (assert (and faulted (eq (fnn-index-writer-binding-mio binding) :new-mio)
              (eq (fnn-index-writer-binding-slots binding) :fenced-slots)
              (eq (fnn-index-writer-binding-pool binding) :fenced-pool)))
 (format t "PASS recorded ERP fences returned slot/pool/MIO roots~%"))

; The repaired ordering places both definite waits BEFORE the sealed producer.
; Recording model counts producer/issuer calls; this is not an ACL2 witness.
(let ((binding nil) (calls 0) (seals 0) (model-issues 0)
      (candidate (list :candidate)) (pc nil))
 (setf (gethash 'fn-owner-cat-prepare-indexed *recorded-dispatch*)
  (lambda (slot fuel slots mio arena cat pool state)
   (declare (ignore slot fuel arena cat))
   (incf calls)
   (case calls
    (1 (assert candidate) (values nil :busy nil slots mio pool state))
    (2 (assert candidate) (values nil :yield nil slots mio pool state))
    (t (incf seals) (incf model-issues) (setf pc (list :prepared-pc) candidate nil)
       (values nil :constructor-required '(:index-generation 1 1 0) slots mio pool state)))))
 (setf (gethash 'fn-owner-index-writer-begin *recorded-dispatch*)
  (lambda (slots mio arena pool state) (declare (ignore arena))
   (assert pc) (values :arena-held '(:index-generation 1 1 0) mio pool state)))
 (setf binding (fnn-index-writer-binding-make :pool :slots 0 8 :mio :arena :cat))
 (assert (eq (fnn-index-writer-prepare-locked binding) :busy))
 (assert (and candidate (null pc) (= seals 0)))
 (assert (eq (fnn-index-writer-prepare-locked binding) :yield))
 (assert (and candidate (null pc) (= seals 0)))
 (assert (eq (fnn-index-writer-prepare-locked binding) :constructor-required))
 (let ((original-pc pc))
  (assert (eq (fnn-index-writer-resume-locked binding) :arena-held))
  (assert (eq pc original-pc)))
 (assert (and (= calls 3) (= seals 1) (= model-issues 1)))
 (format t "PASS recorded gate-busy/prepay-yield before seal; one seal/issue and SAME PC on resume~%"))
