; Recording fixture for the exact trusted repository ACL2 host wrapper.
; The core is deliberately stubbed: this checks selected callee and MV/STATE
; transport, NOT core installation, source authority, native funding or I/O.
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(declaim (declaration xargs))
(defmacro mv-let (names form &body body)
 `(multiple-value-bind ,names ,form ,@body))
(defmacro mv (&rest values) `(values ,@values))
(defvar *recorded-calls* nil)
(defvar *core-word* nil)
(defvar *core-left* nil)
(defvar *core-mio* nil)
(defvar *core-holder* nil)
(defun fn-irr-render-install (&rest ignored)
 (declare (ignore ignored))
 (error "Obsolete direct renderer was called"))
(defun fn-irc-registered-render-install (token fuel mio holder)
 (push (list token fuel mio holder) *recorded-calls*)
 (values *core-word* *core-left* *core-mio* *core-holder*))
(let ((source (second sb-ext:*posix-argv*)) (found nil))
 (assert source)
 ; Trusted project source, never network input or NNTP data.
 (with-open-file (in source)
  (loop for form = (read in nil :eof) until (eq form :eof) do
   (when (and (consp form) (eq (first form) 'defun)
              (eq (second form) 'fn-owner-index-reader-request-render-install))
    (assert (not found)) (eval form) (setf found t))))
 (assert found))
(dolist (word '(:installed :yield :recovery-required :busy :stale))
 (let* ((token (list :issued-token)) (mio (list :actual-mio))
        (holder (list :actual-holder)) (state (list :actual-state))
        (*recorded-calls* nil) (*core-word* word) (*core-left* 17)
        (*core-mio* (list :next-mio)) (*core-holder* (list :next-holder)))
  (multiple-value-bind (answer left next-mio next-holder next-state)
    (fn-owner-index-reader-request-render-install token 23 mio holder state)
   (assert (eq answer word)) (assert (= left 17))
   (assert (eq next-mio *core-mio*)) (assert (eq next-holder *core-holder*))
   (assert (eq next-state state))
   (assert (= (length *recorded-calls*) 1))
   (destructuring-bind (seen-token seen-fuel seen-mio seen-holder)
       (first *recorded-calls*)
    (assert (eq seen-token token)) (assert (= seen-fuel 23))
    (assert (eq seen-mio mio)) (assert (eq seen-holder holder))))))
(format t "PASS: exact caller selects registered custody constructor once; all five MVs/STATE preserved for five recorded dispositions.~%")
