;;; Test only actual driver control flow. Callback returns are fault injection,
;;; not runtime funding, admission, I/O, or proof evidence.
(defpackage "ACL2" (:use "COMMON-LISP"))
(in-package "ACL2")
(defparameter *owner-root* (namestring (truename "./")))
(defparameter *product-root* *owner-root*)
(defun load-selected-form (path name)
  (with-open-file (in path)
    (loop for form = (read in nil :eof) until (eq form :eof)
          when (and (consp form) (member (first form) '(defstruct defun))
                    (eq name (if (consp (second form)) (first (second form)) (second form))))
            do (eval form) (return))))
(load-selected-form (concatenate 'string *owner-root* "host/native/runtime-bootstrap.lisp")
                    'fnn-runtime-bootstrap)
(load-selected-form (concatenate 'string *product-root* "host/native/runtime-profile-envelope.lisp")
                    'fnn-runtime-profile-envelope-binding)
(defvar *fnn-runtime-bootstrap* nil)
(defvar *the-live-state* nil)
(defvar *fnn-extent-lock* (sb-thread:make-mutex :name "control-flow-regression"))
(defvar *mode*)
(defvar *binding*)
(defvar *fences* 0)
(defvar *primitive-calls* 0)
(defvar *controller-begins* 0)
(defvar *result-reads* 0)
(defvar *turn-begins* 0)
(defparameter *original-driver-p* nil)
(defmacro fnn-core-mv (subject call) (declare (ignore subject)) call)
(defun fnn-core (subject &rest args)
  (declare (ignore args))
  (case subject
    (fn-pfo-slot 0) (fn-pfo-turn 1)
    (fn-pfo-result (incf *result-reads*) :held-result)
    (otherwise (error "unexpected core subject ~s" subject))))
(defun fence-callback (pool) (incf *fences*) (values :fenced pool))
(load-selected-form (concatenate 'string *owner-root* "host/native/runtime-bootstrap.lisp")
                    'fnn-runtime-bootstrap-installation-failure)
(defun fnn-fixed-raw-callback (name)
  (ecase name
    (fn-owner-page-file-open-step
     (lambda (fuel controller buffer pool slots state)
       (declare (ignore fuel buffer state))
       (values (case *mode* (:finish :file-close) (:phase :recovery-operation-unavailable)
                         (otherwise :file-open))
               '(:file-open (:incarnation 1) "borrowed-path") 0 controller
               (if (eq *mode* :step) nil pool) slots)))
    (fn-owner-page-file-open-observe
     (lambda (token start end word count controller pool slots)
       (declare (ignore token start end word count pool slots))
       (values :file-closed-retained controller)))
    (fn-owner-page-file-open-begin
     (lambda (path slot nonce controller buffer pool slots state)
       (declare (ignore path slot nonce buffer pool state))
       (incf *controller-begins*)
       (values :recovery-file-ready controller slots)))))
(defun turn-begin-callback (path slots pool state)
  (declare (ignore path state))
  (incf *turn-begins*)
  (if (eq *mode* :phase) (values :recovery-operation-unavailable nil 0 slots pool)
    (values :prepaid 0 1 nil pool)))
(defun turn-finish-callback (slot nonce slots pool)
  (declare (ignore slot nonce slots)) (values :left nil pool))
(defun fnn-runtime-profile-envelope-live-binding (pool policy)
  (declare (ignore pool policy)) (values :profile-envelope-available *binding*))
(defun fnn-recovery-profile-perform (effect binding)
  (declare (ignore effect binding)) (incf *primitive-calls*) (values :closed 0 9))
(defun check-case (mode entry)
  (let* ((*mode* mode) (*fences* 0) (*primitive-calls* 0)
         (*controller-begins* 0) (*result-reads* 0)
         (controller (vector :retained-controller))
         (*binding* (%fnn-runtime-profile-envelope-binding
                     :pool nil :buffer :backing nil :policy controller))
         ;; Deliberately bypass phase selection to isolate the faulty bodies.
         ;; This fixture grants no real resource or installation authority.
         (*fnn-runtime-bootstrap*
           (%make-fnn-runtime-bootstrap :pool :pool :slots :slots
             :phase (if *original-driver-p* :accepted :production-entered)
             :profile-envelope *binding* :image-policy :policy :fault #'fence-callback
             :recovery-turn-begin #'turn-begin-callback
             :recovery-turn-finish #'turn-finish-callback))
         (answer (multiple-value-list
                   (if (eq entry :start) (fnn-recovery-profile-start "borrowed-path")
                     (fnn-recovery-profile-quantum *fnn-runtime-bootstrap* *binding* 1)))))
    (let ((ok (and (eq (first answer) :recovery-missing-effects)
                   (eq (second answer) :fenced) (= *fences* 1)
                   (= *controller-begins* 0) (= *result-reads* 0)
                   (= *primitive-calls* (if (eq mode :finish) 1 0))
                   (eq (fnn-runtime-bootstrap-pool *fnn-runtime-bootstrap*) :pool)
                   (eq (fnn-runtime-bootstrap-slots *fnn-runtime-bootstrap*) :slots))))
      (format t "~s: ~:[FAIL~;PASS~] answer=~s fences=~d primitive=~d begin=~d result=~d~%"
              mode ok answer *fences* *primitive-calls* *controller-begins* *result-reads*)
      ok)))
(defun check-phase (phase installed)
  (let* ((*mode* :phase) (*fences* 0) (*primitive-calls* 0)
         (*controller-begins* 0) (*result-reads* 0) (*turn-begins* 0)
         (*binding* (%fnn-runtime-profile-envelope-binding
                     :pool nil :buffer :backing nil :policy (vector :controller)))
         (*fnn-runtime-bootstrap*
           (%make-fnn-runtime-bootstrap :pool :pool :slots :slots :phase phase
             :profile-envelope *binding* :image-policy :policy :fault #'fence-callback
             :recovery-turn-begin #'turn-begin-callback))
         (start (multiple-value-list (fnn-recovery-profile-start "borrowed-path")))
         (next (multiple-value-list (fnn-recovery-profile-next)))
         (expected (if installed :recovery-operation-unavailable :recovery-bootstrap-unavailable))
         (ok (and (eq (first start) expected) (eq (first next) expected)
                  (= *turn-begins* (if installed 1 0))
                  (= *primitive-calls* 0) (= *controller-begins* 0)
                  (= *result-reads* 0) (= *fences* 0))))
    (format t "phase ~s: ~:[FAIL~;PASS~] start=~s next=~s turn-begins=~d~%"
            phase ok start next *turn-begins*)
    ok))
(load (second sb-ext:*posix-argv*))
(let ((ok (mapcar (lambda (x) (check-case (first x) (second x)))
                 '((:step :quantum) (:start :start) (:finish :quantum)))))
  (setf ok (append ok (mapcar (lambda (x) (check-phase (first x) (second x)))
                  '((:runtime-bootstrap-installed t) (:startup-accepted t)
                    (:production-entered t) (:saved nil) (:uncertain nil)
                    (:registry-mismatch nil) (:runtime-operation-installation-unavailable nil)
                    (:accepted nil)))))
  (sb-ext:exit :code (if (every #'identity ok) 0 1)))
