(in-package "CL-USER")
(defvar *participant-image-hook-runs* 0)
(defun participant-image-hook () (incf *participant-image-hook-runs*))
(let* ((pool (list :saved-pool))
       (gate (fnn-runtime-participants-install-for-image pool)))
  (fnn-with-runtime-participants-parked (gate pool)
    (assert (fnn-runtime-participants-parked gate)))
  (push #'participant-image-hook sb-ext:*after-gc-hooks*)
  (sb-ext:gc :full t)
  (fnn-with-runtime-participants-parked (gate pool)
    (assert (zerop *participant-image-hook-runs*)))
  (fnn-runtime-participants-register-image-hooks))
(sb-ext:save-lisp-and-die "/tmp/fn-participant-prototype.core")
