; bp-crc-exec: the perf-ledger harness (planning/evidence/perf-ledger-2026-09-26/bpenc.lisp)
; at 48 KiB, 256 KiB and 1 MiB, run against a developer image's raw Lisp, plus a
; digest of each wire (independent of the CRC under test) and the round trip.
(in-package "ACL2")
(defun pl-measure (label thunk)
  (sb-ext:gc :full t)
  (let* ((b0 (sb-ext:get-bytes-consed)) (t0 (get-internal-real-time))
         (v (funcall thunk))
         (t1 (get-internal-real-time)) (b1 (sb-ext:get-bytes-consed)))
    (format t "~a seconds ~,4f bytes-consed ~d~%" label
            (/ (- t1 t0) (float internal-time-units-per-second)) (- b1 b0))
    v))
(defun pl-digest (xs)
  (let ((h 0)) (dolist (x xs h) (setq h (mod (+ (* h 31) x 1) 2305843009213693951)))))
(let* ((sender (cons :dtn '(47 47 98 112 45 115 101 110 100 101 114 47)))
       (dest (cons :dtn '(47 47 98 112 45 100 101 115 116 47)))
       (config (fn-bpn-config sender 3600000 2 32 1048576))
       (obs (fn-clock-observation 1000 0 0 nil)))
  (format t "max-data ~d~%" *fn-bpb-max-data*)
  (dolist (n (list 49152 262144 1048576))
    (let* ((adu (make-list n :initial-element 65))
           (bundle (fn-bpn-send-bundle config dest adu 7 obs)))
      (format t "== payload ~d octets~%" n)
      (pl-measure "bundlep(guard)" (lambda () (fn-bpb-bundlep bundle)))
      (let ((wire (pl-measure "encode" (lambda () (fn-bpb-encode bundle)))))
        (format t "wire ~d octets digest ~d~%" (len wire) (pl-digest wire))
        (let ((d (pl-measure "decode" (lambda () (fn-bpb-decode wire (+ 16 (len wire)))))))
          (format t "round-trip ~a~%" (and (fn-cbor-result-okp d)
                                           (equal (fn-cbor-result-value d) bundle))))))))
