; scratch: call counts of the index builders between FN_ALLOC_DIR/start and /stop, plus an alloc profile
(in-package "ACL2")
(require :sb-sprof)
(defvar *fnc-counts* (make-hash-table :test (quote eq)))
(defvar *fnc-on* nil)
(dolist (f (quote (fn-gidx-build fn-index-build fn-gidx-refresh fn-midx-build fn-midx-refresh fn-own-refresh fn-ctl-refresh-visible fn-ctl-refresh-withdrawn fn-ctl-refresh-withdrawals)))
  (when (fboundp f)
    (let ((name f))
      (sb-int:encapsulate f (quote fnc)
        (lambda (g &rest args) (when *fnc-on* (incf (gethash name *fnc-counts* 0))) (apply g args))))))
(defvar *fna-dir* (sb-ext:posix-getenv "FN_ALLOC_DIR"))
(when *fna-dir*
  (sb-thread:make-thread
   (lambda ()
     (flet ((f (n) (concatenate (quote string) *fna-dir* "/" n)))
       (handler-case
           (progn
             (loop until (probe-file (f "start")) do (sleep 0.05))
             (setq *fnc-on* t)
             (sb-sprof:start-profiling :max-samples 2000000 :mode :alloc :threads :all)
             (loop until (probe-file (f "stop")) do (sleep 0.05))
             (sb-sprof:stop-profiling)
             (setq *fnc-on* nil)
             (with-open-file (s (f "counts.txt") :direction :output :if-exists :supersede)
               (maphash (lambda (k v) (format s "~(~a~) ~d~%" k v)) *fnc-counts*))
             (with-open-file (s (f "flat.txt") :direction :output :if-exists :supersede)
               (sb-sprof:report :type :flat :max 60 :stream s))
             (with-open-file (s (f "graph.txt") :direction :output :if-exists :supersede)
               (sb-sprof:report :type :graph :max 80 :stream s)))
         (serious-condition (c)
           (with-open-file (s (f "error.txt") :direction :output :if-exists :supersede)
             (format s "~a~%" c))))
       (with-open-file (s (f "done") :direction :output :if-exists :supersede)
         (print :done s))))
   :name "fn-alloc"))
