(in-package "ACL2")
(include-book "../../books/admission-semantic-census-begin-refinement")
; Internal actual PROGRAM transport MODEL, full high include not certified here.
(defun fn-owner-census-begin-model (fn-history-backing state)
 (declare (xargs :stobjs (fn-history-backing state) :mode :program))
 (let* ((token '(:admission-grant 3 0 0 0 0 :consumer))
        (current (list token nil :reserved nil nil))
        (parent '(:history-installed 0 0 0 0 0))
        (row '(:consumer 0 0 0 (:consumer-authority :begin)))
        (files '(:store-files :reserved 1 nil nil nil nil nil nil))
        (base-store (list nil nil files))
        (state (f-put-global 'fn-owner-canonical-admission-pending current state))
        (state (f-put-global 'fn-owner-canonical-epoch 0 state))
        (state (f-put-global 'fn-owner-history-completion-fault nil state))
        (state (f-put-global 'fn-owner-history-publication parent state))
        (state (f-put-global 'fn-owner-history-semantic-census nil state))
        (state (fn-owner-admission-retain-prepare-source
                token 0 0 1 base-store nil current parent nil nil nil nil state))
        (intent (f-get-global 'fn-owner-canonical-admission-executor state))
        (fn-history-backing (update-fn-hep-producer-token token fn-history-backing))
        (fn-history-backing (update-fn-hep-producer-phase :offered fn-history-backing))
        (fn-history-backing (update-fn-hep-builder
                (list :history-builder :offered row nil nil nil token nil nil nil)
                fn-history-backing))
        (antecedent (and (fn-apr-tokenp token) (fn-apr-livep token current)
          (eq (fn-owner-history-writer-gate token state) :writer-current)
          (fn-apr-widthp 8 intent) (equal (fn-prl-nth 3 intent) 0)
          (equal (fn-prl-nth 5 intent) base-store))))
  (mv-let (word fn-history-backing state)
   (fn-owner-admission-census-begin fn-history-backing state)
   (let* ((job (f-get-global 'fn-owner-history-semantic-census state))
          (source (fn-prl-nth 2 job))
          (ok (and antecedent (eq word :census-started)
                   (fn-osrc-guardp source)
                   (equal (fn-osrc-at 1 source) (fn-sfr-snoc nil row))
                   (equal (fn-osrc-at 3 source) 1)
                   (equal (f-get-global 'fn-owner-canonical-admission-executor state) intent))))
    (mv-let (again fn-history-backing state)
     (fn-owner-admission-census-begin fn-history-backing state)
     (mv (and ok (eq again :census-retained)
              (equal (f-get-global 'fn-owner-history-semantic-census state) job))
         fn-history-backing state))))))
(fn-owner-census-begin-model fn-history-backing state)
