(in-package "ACL2")
(include-book "../../books/admission-preallocation-resources")
; Constructor/current-slot readout fixtures only: not a granted owner pipeline.
(defconst *apkt-token* (fn-apr-token 3 '(4 5 5 6 :identity)))
(defconst *apkt-packet*
 (fn-apr-operation-packet '(literal-event) '(original-checked) '(fields)
  :unavailable :snapshot '(same-child) nil '(next-ready) '(prefix-node) '(next-node)))
(defconst *apkt-reserved* (list *apkt-token* '(100 10 10 10 1) :reserved '(base-roots) nil))
(assert-event
 (mv-let (word row) (fn-apr-produced *apkt-token* *apkt-packet* *apkt-reserved*)
  (and (eq word :produced) (fn-apr-operation-packetp *apkt-packet*)
       (equal (fn-apr-current-operation-packet row) *apkt-packet*)
       (equal (fn-prl-nth 0 (fn-apr-current-operation-packet row)) '(literal-event))
       (equal (fn-prl-nth 7 (fn-apr-current-operation-packet row)) '(next-ready))
       (equal (fn-prl-nth 3 row) '(base-roots))
       (mv-let (u uncertain) (fn-apr-uncertain *apkt-token* row)
        (and (eq u :uncertain)
             (equal (fn-apr-current-operation-packet uncertain) *apkt-packet*)
             (equal (fn-prl-nth 3 uncertain) '(base-roots)))))))
(assert-event (not (fn-apr-current-operation-packet *apkt-reserved*)))
(assert-event (not (fn-apr-operation-packetp (append *apkt-packet* '(extra)))))
(defun apkt-state-fixture (state)
 (declare (xargs :stobjs state :mode :program))
 (mv-let (word row) (fn-apr-produced *apkt-token* *apkt-packet* *apkt-reserved*)
  (declare (ignore word))
  (let* ((state (f-put-global 'fn-owner-canonical-admission-pending row state))
         (capture (fn-apr-owner-produced-capture state))
         (state (f-put-global 'fn-owner-canonical-admission-pending nil state)))
   (mv (and (equal capture *apkt-packet*)
            (not (fn-apr-owner-produced-capture state))) state))))
(make-event (mv-let (ok state) (apkt-state-fixture state)
             (value (list 'assert-event ok))))
