(in-package "ACL2")
(include-book "../../books/allocation-turn-body-authority")
; Synthetic source fixture: no installed image or physical allowance claim.
(defun atsbat-case (fn-allocation-turn-slots fn-page-read-pool)
 (declare (xargs :stobjs (fn-allocation-turn-slots fn-page-read-pool) :verify-guards nil))
 (let* ((association '(:allocation-epoch-association :runtime :profile :pool 10 1000))
        (installation (list :allocation-epoch-installation association 1000 800 2 20 20 20 50 10 20 7 0))
        (fn-page-read-pool (fn-owner-page-read-keep-ledger
          '((1000 1000 1000 1000 1000) (0 0 0 0 0) 0 nil (0 0 0 0 0)) fn-page-read-pool))
        (fn-page-read-pool (update-fn-prp-mode :served fn-page-read-pool))
        (fn-page-read-pool (update-fn-prp-alloc-installation installation fn-page-read-pool))
        (fn-page-read-pool (update-fn-prp-alloc-mode :active fn-page-read-pool))
        (fn-page-read-pool (update-fn-prp-alloc-occupied 100 fn-page-read-pool))
        (fn-page-read-pool (update-fn-prp-alloc-allocated 20 fn-page-read-pool)))
  (mv-let (made fn-allocation-turn-slots)
   (fn-ats-construct-internal '(:index-writer) fn-allocation-turn-slots fn-page-read-pool)
   (mv-let (entered nonce fn-allocation-turn-slots fn-page-read-pool)
    (fn-ats-enter-internal 0 :index-writer fn-allocation-turn-slots fn-page-read-pool)
    (let ((gate (and (eq made :constructed) (eq entered :gate-owned) (equal nonce 0)
      (fn-ats-matchingp 0 nonce fn-allocation-turn-slots fn-page-read-pool)
      (not (fn-ats-role-bodyp 0 nonce :index-writer fn-allocation-turn-slots fn-page-read-pool)))))
     (mv-let (paid fn-allocation-turn-slots fn-page-read-pool)
      (fn-ats-prepay-body-internal 0 nonce 40 fn-allocation-turn-slots fn-page-read-pool)
      (let ((body (and gate (eq paid :prepaid) (fn-aec-pool-statep fn-page-read-pool)
       (fn-ats-slotp 0 fn-allocation-turn-slots) (fn-ats-associatedp fn-allocation-turn-slots fn-page-read-pool)
       (natp nonce) (equal nonce (fn-ats-noncesi 0 fn-allocation-turn-slots))
       (equal (fn-ats-kindsi 0 fn-allocation-turn-slots) :index-writer)
       (equal (fn-ats-phasesi 0 fn-allocation-turn-slots) 3)
       (eq (fn-prp-alloc-mode fn-page-read-pool) :active)
       (equal (fn-prp-alloc-active-turns fn-page-read-pool) 1)
       (fn-ats-role-bodyp 0 nonce :index-writer fn-allocation-turn-slots fn-page-read-pool)
       (not (fn-ats-role-bodyp 0 1 :index-writer fn-allocation-turn-slots fn-page-read-pool))
       (not (fn-ats-role-bodyp 0 nonce :connection-start fn-allocation-turn-slots fn-page-read-pool))
       (not (fn-ats-role-bodyp 1 nonce :index-writer fn-allocation-turn-slots fn-page-read-pool)))))
       (mv-let (left fn-allocation-turn-slots fn-page-read-pool)
        (fn-ats-finish-owned 0 nonce fn-allocation-turn-slots fn-page-read-pool)
        (let ((idle (and body (eq left :left)
          (equal (fn-prp-alloc-active-turns fn-page-read-pool) 0)
          (equal (fn-ats-noncesi 0 fn-allocation-turn-slots) nonce)
          (not (fn-ats-role-bodyp 0 nonce :index-writer fn-allocation-turn-slots fn-page-read-pool)))))
         (mv-let (again next fn-allocation-turn-slots fn-page-read-pool)
          (fn-ats-enter-internal 0 :index-writer fn-allocation-turn-slots fn-page-read-pool)
          (mv-let (paid fn-allocation-turn-slots fn-page-read-pool)
           (fn-ats-prepay-body-internal 0 next 40 fn-allocation-turn-slots fn-page-read-pool)
           (let ((reused (and idle (eq again :gate-owned) (equal next 1) (eq paid :prepaid)
             (fn-ats-role-bodyp 0 next :index-writer fn-allocation-turn-slots fn-page-read-pool)
             (not (fn-ats-role-bodyp 0 nonce :index-writer fn-allocation-turn-slots fn-page-read-pool)))))
            (mv-let (fault fn-allocation-turn-slots fn-page-read-pool)
             (fn-ats-uncertain-internal fn-allocation-turn-slots fn-page-read-pool)
             (mv (and reused (eq fault :recovery-required)
                (equal (fn-ats-phasesi 0 fn-allocation-turn-slots) 3)
                (fn-ats-matchingp 0 next fn-allocation-turn-slots fn-page-read-pool)
                (eq (fn-prp-alloc-mode fn-page-read-pool) :recovery)
                (equal (fn-prp-alloc-active-turns fn-page-read-pool) 1)
                (not (fn-ats-role-bodyp 0 next :index-writer fn-allocation-turn-slots fn-page-read-pool)))
                 fn-allocation-turn-slots fn-page-read-pool))))))))))))))
(defun atsbat-local ()
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-page-read-pool
  (mv-let (ok fn-page-read-pool)
   (with-local-stobj fn-allocation-turn-slots
    (mv-let (ok fn-allocation-turn-slots fn-page-read-pool)
     (atsbat-case fn-allocation-turn-slots fn-page-read-pool) (mv ok fn-page-read-pool))) ok)))
(assert-event (atsbat-local))
