(in-package "ACL2")
; Fixture-only installation, never a production installer or authority.
(defun aect-pool-roundtrip ()
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-page-read-pool
  (mv-let (ok fn-page-read-pool)
   (let* ((fn-page-read-pool (update-fn-prp-data '(:ledger :other) fn-page-read-pool))
          (fn-page-read-pool (update-fn-prp-mode :served fn-page-read-pool))
          (fn-page-read-pool (update-fn-prp-incoming-slot :incoming fn-page-read-pool))
          (fn-page-read-pool (update-fn-prp-alloc-installation *aec-i* fn-page-read-pool))
          (fn-page-read-pool (update-fn-prp-alloc-mode :active fn-page-read-pool))
          (fn-page-read-pool (update-fn-prp-alloc-epoch 3 fn-page-read-pool))
          (fn-page-read-pool (update-fn-prp-alloc-occupied 100 fn-page-read-pool))
          (fn-page-read-pool (update-fn-prp-alloc-allocated 20 fn-page-read-pool)))
    (mv-let (entry fn-page-read-pool) (fn-aec-pool-enter-internal nil fn-page-read-pool)
     (mv-let (body fn-page-read-pool) (fn-aec-pool-body-internal 40 nil fn-page-read-pool)
      (let ((fn-page-read-pool (fn-aec-pool-drain-internal fn-page-read-pool)))
       (mv-let (left fn-page-read-pool) (fn-aec-pool-consumed-turn-internal fn-page-read-pool)
        (mv-let (prepare fn-page-read-pool) (fn-aec-pool-collect-prepay-internal fn-page-read-pool)
         (mv-let (issued fn-page-read-pool) (fn-aec-pool-collect-issued-internal 42 fn-page-read-pool)
          (mv-let (complete fn-page-read-pool)
           (fn-aec-pool-collect-complete-internal :fixture 3 42 :completed 80 fn-page-read-pool)
           (let* ((fn-page-read-pool (fn-owner-page-read-keep-ledger :released-logical-grant fn-page-read-pool))
                  (fn-page-read-pool (fn-aec-pool-uncertain-internal fn-page-read-pool)))
            (mv (and (equal (list entry body left prepare issued complete)
                            '(:prepaid :prepaid :left :issue-collection-nonce :collect :resume))
                     (fn-aec-pool-statep fn-page-read-pool)
                     (equal (fn-prp-alloc-mode fn-page-read-pool) :recovery)
                     (equal (fn-prp-alloc-epoch fn-page-read-pool) 4)
                     (equal (fn-prp-alloc-occupied fn-page-read-pool) 80)
                     (equal (fn-prp-alloc-allocated fn-page-read-pool) 7)
                     (equal (fn-prp-alloc-active-turns fn-page-read-pool) 0)
                     (equal (fn-prp-alloc-gc-nonce fn-page-read-pool) nil)
                     (equal (fn-prp-alloc-installation fn-page-read-pool) *aec-i*)
                     (equal (fn-owner-page-read-ledger fn-page-read-pool) :released-logical-grant)
                     (equal (fn-prp-mode fn-page-read-pool) :served)
                     (equal (fn-prp-incoming-slot fn-page-read-pool) :incoming))
                fn-page-read-pool))))))))))
   ok)))
(assert-event (aect-pool-roundtrip))
