(in-package "ACL2")
; Synthetic selected producer; no native observation or installation claim.
(assert-event
 (mv-let (word occupied) (fn-aec-observed-occupancy *aec-i* *aec-assoc* 8 10 1000)
  (and (eq word :observed)
       (equal *aec-assoc* (fn-aec-at 1 *aec-i*))
       (equal 10 (fn-aec-at 4 (fn-aec-at 1 *aec-i*)))
       (equal 1000 (fn-aec-at 5 (fn-aec-at 1 *aec-i*)))
       (natp occupied) (<= occupied 1000) (<= occupied (fn-aec-at 2 *aec-i*))
       (equal occupied (* 8 10)))))
; Removing the observed-status antecedent: all other theorem hypotheses are
; absent. Malformed geometry returns zero rather than computing its product.
(assert-event
 (mv-let (word occupied) (fn-aec-observed-occupancy *aec-i* *aec-assoc* 8 11 1000)
  (and (not (eq word :observed))
       (not (and (equal *aec-assoc* (fn-aec-at 1 *aec-i*))
                 (equal 11 (fn-aec-at 4 (fn-aec-at 1 *aec-i*)))
                 (equal 1000 (fn-aec-at 5 (fn-aec-at 1 *aec-i*)))
                 (natp occupied) (<= occupied 1000) (<= occupied (fn-aec-at 2 *aec-i*))
                 (equal occupied (* 8 11)))))))
(assert-event (equal (mv-list 2 (fn-aec-observed-occupancy *aec-i* *aec-assoc* 100 10 1000))
                     '(:observed 1000)))
(assert-event (equal (mv-list 2 (fn-aec-observed-occupancy *aec-i* *aec-assoc* 101 10 1000))
                     '(:invalid-observation 0)))
(assert-event (equal (mv-list 2 (fn-aec-observed-occupancy *aec-i* *aec-assoc* -1 10 1000))
                     '(:invalid-observation 0)))
(assert-event (equal (mv-list 2 (fn-aec-observed-occupancy *aec-i* :wrong-source 8 10 1000))
                     '(:invalid-observation 0)))
(assert-event (equal (mv-list 2 (fn-aec-observed-occupancy *aec-i* *aec-assoc* 8 0 1000))
                     '(:invalid-observation 0)))
(assert-event (equal (mv-list 2 (fn-aec-observed-occupancy *aec-i* *aec-assoc* 8 10 999))
                     '(:invalid-observation 0)))

(defun aect-observation-run (request oi oe og status pages size reservation)
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-page-read-pool
  (mv-let (result fn-page-read-pool)
   (let* ((fn-page-read-pool (update-fn-prp-alloc-installation *aec-i* fn-page-read-pool))
          (fn-page-read-pool (update-fn-prp-alloc-mode :collecting fn-page-read-pool))
          (fn-page-read-pool (update-fn-prp-alloc-epoch 3 fn-page-read-pool))
          (fn-page-read-pool (update-fn-prp-alloc-occupied 100 fn-page-read-pool))
          (fn-page-read-pool (update-fn-prp-alloc-allocated 90 fn-page-read-pool))
          (fn-page-read-pool (update-fn-prp-alloc-gc-nonce 42 fn-page-read-pool)))
    (mv-let (word fn-page-read-pool)
     (fn-aec-pool-collect-observed-internal request oi oe og status pages size reservation fn-page-read-pool)
     (mv (list word (fn-prp-alloc-mode fn-page-read-pool)
               (fn-prp-alloc-epoch fn-page-read-pool) (fn-prp-alloc-occupied fn-page-read-pool)
               (fn-prp-alloc-allocated fn-page-read-pool) (fn-prp-alloc-gc-nonce fn-page-read-pool)
               (fn-aec-pool-statep fn-page-read-pool))
         fn-page-read-pool)))
   result)))
(assert-event (equal (aect-observation-run 42 *aec-assoc* 3 42 :completed 8 10 1000)
                     '(:resume :active 4 80 7 nil t)))
(assert-event (equal (aect-observation-run 43 *aec-assoc* 3 42 :completed 8 10 1000)
                     '(:recovery-required :recovery 3 100 90 42 t)))
(assert-event (equal (aect-observation-run 42 *aec-assoc* 2 42 :completed 8 10 1000)
                     '(:recovery-required :recovery 3 100 90 42 t)))
(assert-event (equal (aect-observation-run 42 *aec-assoc* 3 41 :completed 8 10 1000)
                     '(:recovery-required :recovery 3 100 90 42 t)))
(assert-event (equal (aect-observation-run 42 *aec-assoc* 3 42 :uncertain 8 10 1000)
                     '(:recovery-required :recovery 3 100 90 42 t)))
(assert-event (equal (aect-observation-run 42 *aec-assoc* 3 42 :deferred 8 10 1000)
                     '(:recovery-required :recovery 3 100 90 42 t)))
(assert-event (equal (aect-observation-run 42 *aec-assoc* 3 42 :completed 101 10 1000)
                     '(:recovery-required :recovery 3 100 90 42 t)))
(assert-event (equal (aect-observation-run 42 *aec-assoc* 3 42 :completed 32 10 1000)
                     '(:resource-unavailable :draining 4 320 7 42 t)))
