(in-package "ACL2")
(include-book "../../books/bp-controller-checkpoint-current")
; Unfunded registered storage fixture. The issued operation is constructed
; explicitly; this is not a sanctioned controller factory or CK source grant.
(defun fn-bpcc-test-segment (fn-bpc-segment)
  (declare (xargs :stobjs fn-bpc-segment :guard t))
  (let* ((initial (fn-bpnf-initial-state
                   (fn-bpn-config (cons :dtn '(47 47 98 112 45 108 111 99 97 108 47))
                                  3600000 2 32 1048576) 8 1048576))
         (current (fn-bpnf-with-issued initial
                    (fn-bpnf-operation (fn-bpnf-epoch initial) 0 :checkpoint 5 :pending)))
         (controller '(:bp-controller 2 0))
         (pool (fn-prl-build '(1000000 100000 10 10 100) '(0 0 0 0 0)
                            7 nil '(1000 0 0 0 0))))
    (mv-let (registration fn-bpc-segment)
      (fn-bpc-segment-install 2 0 current :unfunded-storage-only fn-bpc-segment)
      (mv-let (word token ledger1 fn-bpc-segment)
        (fn-bpcc-segment-reserve controller 0 '(8192 4096 1 1 1) pool fn-bpc-segment)
        (let* ((row (fn-bpcs-rowsi 0 fn-bpc-segment))
               (job (fn-bpn-nth 4 row))
               (positive (and (eq registration :registered)
                              (fn-bpco-checkpoint-operation-p current)
                              (eq word :checkpoint-reserved)
                              (fn-bpcc-job-tokenp token)
                              (equal token (list :bp-job 7 controller (fn-bpnf-epoch current) 5))
                              (equal (fn-bpn-nth 2 row) current)
                              (equal (fn-bpn-nth 3 job) current)
                              (equal (fn-bpn-nth 1 job) '(8192 4096 1 1 1))
                              (equal (fn-prl-nth 2 ledger1) 8))))
          (mv-let (busy ignored ledger2 fn-bpc-segment)
            (fn-bpcc-segment-reserve controller 0 '(8192 4096 1 1 1) ledger1 fn-bpc-segment)
            (declare (ignore ignored))
            (mv-let (cancel fn-bpc-segment)
              (fn-bpcc-segment-cancel token 0 fn-bpc-segment)
              (let ((cancelled (fn-bpcs-rowsi 0 fn-bpc-segment)))
                (mv-let (repeat fn-bpc-segment)
                  (fn-bpcc-segment-cancel token 0 fn-bpc-segment)
                  (mv (and positive (eq busy :controller-busy)
                           (equal ledger1 ledger2)
                           (eq cancel :checkpoint-retained)
                           (eq repeat :checkpoint-retained)
                           (equal (fn-bpcs-rowsi 0 fn-bpc-segment) cancelled)
                           (equal (fn-bpn-nth 2 cancelled) current)
                           (equal (fn-bpn-nth 3 (fn-bpn-nth 4 cancelled)) current)
                           (equal (fn-bpn-nth 1 (fn-bpn-nth 4 cancelled)) '(8192 4096 1 1 1))
                           (eq (fn-bpn-nth 2 (fn-bpn-nth 4 cancelled)) :cancelled))
                      fn-bpc-segment))))))))))
(defun fn-bpcc-test-local ()
  (declare (xargs :guard t))
  (with-local-stobj fn-bpc-segment
    (mv-let (answer fn-bpc-segment)
      (fn-bpcc-test-segment fn-bpc-segment)
      answer)))
(assert-event (fn-bpcc-test-local))
