(in-package "ACL2")
(include-book "../../books/bp-controller-checkpoint-capture")
(include-book "bp-controller-checkpoint-payload-directory-tests")
; Actual registered storage seeded by the existing explicitly unfunded fixture.
; Marker payloads and the supplied reserve are not real constructor authority.
(defun fn-bpcc-pending-capture-test-observe (fn-bp-controller-registry fn-page-read-pool)
  (declare (xargs :stobjs (fn-bp-controller-registry fn-page-read-pool) :guard t))
  (mv-let (reserved token reserve-left fn-bp-controller-registry fn-page-read-pool)
    (fn-owner-bp-checkpoint-reserve '(:bp-controller 2 0) '(8192 4096 1 1 1)
                                   4 fn-bp-controller-registry fn-page-read-pool)
    (mv-let (word found current claim payload phase revision left)
      (fn-bpcc-pending-capture '(:bp-controller 2 0) 4 fn-bp-controller-registry)
      (mv-let (read read-current read-claim read-payload read-phase read-revision read-left fn-bp-controller-registry)
        (fn-bpcc-directory-payload '(:bp-controller 2 0) token :read nil nil nil nil
                                   4 fn-bp-controller-registry)
        (mv-let (stale stale-token stale-current stale-claim stale-payload stale-phase stale-revision stale-left)
          (fn-bpcc-pending-capture '(:bp-controller 3 0) 4 fn-bp-controller-registry)
          (mv-let (yielded yield-token yield-current yield-claim yield-payload yield-phase yield-revision yield-left)
            (fn-bpcc-pending-capture '(:bp-controller 2 0) 0 fn-bp-controller-registry)
            (let ((ledger (fn-owner-page-read-ledger fn-page-read-pool)))
              (mv-let (fenced fence-left fn-bp-controller-registry fn-page-read-pool)
                (fn-owner-bp-checkpoint-payload-fence-current '(:bp-controller 2 0) 4
                  fn-bp-controller-registry fn-page-read-pool)
                (mv-let (after after-token after-current after-claim after-payload after-phase after-revision after-left)
                  (fn-bpcc-pending-capture '(:bp-controller 2 0) 4 fn-bp-controller-registry)
                  (mv
                   (and (eq reserved :checkpoint-reserved) (equal reserve-left 2)
                        (fn-bpcc-job-tokenp token)
                        (equal token (list :bp-job 7 '(:bp-controller 2 0)
                                           (fn-bpnf-epoch current) 5))
                        (eq word :checkpoint-current) (equal found token)
                        (eq read :checkpoint-current)
                        (equal (list word current claim payload phase revision left)
                               (list read read-current read-claim read-payload
                                     read-phase read-revision read-left))
                        (eq phase :reserved) (equal revision 0) (equal left 3)
                        (equal claim '(8192 4096 1 1 1))
                        (eq stale :stale-checkpoint) (equal stale-left 3)
                        (not stale-token) (not stale-current) (not stale-claim)
                        (not stale-payload) (not stale-phase) (not stale-revision)
                        (eq yielded :yield) (equal yield-left 0)
                        (not yield-token) (not yield-current) (not yield-claim)
                        (not yield-payload) (not yield-phase) (not yield-revision)
                        (eq fenced :checkpoint-retained) (equal fence-left 3)
                        (eq after :checkpoint-current) (equal after-token token)
                        (equal after-current current) (equal after-claim claim)
                        (equal after-payload payload) (eq after-phase :cancelled)
                        (equal after-revision 0) (equal after-left 3)
                        (equal ledger (fn-owner-page-read-ledger fn-page-read-pool)))
                   fn-bp-controller-registry fn-page-read-pool))))))))))
(defun fn-bpcc-pending-capture-test-local ()
  (declare (xargs :verify-guards nil))
  (with-local-stobj fn-bp-controller-registry
    (mv-let (answer fn-bp-controller-registry)
      (with-local-stobj fn-page-read-pool
        (mv-let (answer fn-bp-controller-registry fn-page-read-pool)
          (mv-let (fn-bp-controller-registry fn-page-read-pool)
            (fn-bpcc-payload-directory-test-install fn-bp-controller-registry fn-page-read-pool)
            (fn-bpcc-pending-capture-test-observe fn-bp-controller-registry fn-page-read-pool))
          (mv answer fn-bp-controller-registry)))
      answer)))
(assert-event (fn-bpcc-pending-capture-test-local))
