(in-package "ACL2")
(include-book "../../books/bp-controller-checkpoint-payload")
; Unfunded storage-only continuation markers, not real job/digest authority.
(defun fn-bpcc-payload-test-segment (fn-bpc-segment)
  (declare (xargs :stobjs fn-bpc-segment :guard t))
  (let* ((initial (fn-bpnf-initial-state
                   (fn-bpn-config (cons :dtn '(47 47 98 112 45 108 111 99 97 108 47))
                                  3600000 2 32 1048576) 8 1048576))
         (current (fn-bpnf-with-issued initial
                    (fn-bpnf-operation (fn-bpnf-epoch initial) 0 :checkpoint 5 :pending)))
         (ledger (fn-prl-build '(1000000 100000 10 10 100) '(0 0 0 0 0)
                              7 nil '(1000 0 0 0 0)))
         (payload '(:test-job :test-control :test-digest-binding)))
    (mv-let (registration fn-bpc-segment)
      (fn-bpc-segment-install 2 0 current :unfunded-storage-only fn-bpc-segment)
      (mv-let (reserved token charged fn-bpc-segment)
        (fn-bpcc-segment-reserve '(:bp-controller 2 0) 0 '(8192 4096 1 1 1) ledger fn-bpc-segment)
        (mv-let (updated fn-bpc-segment)
          (fn-bpcc-segment-payload-replace token 0 0 :reserved :running payload fn-bpc-segment)
          (mv-let (word source claim retained phase revision)
            (fn-bpcc-segment-payload-read token 0 fn-bpc-segment)
            (let* ((row (fn-bpcs-rowsi 0 fn-bpc-segment))
                   (positive (and (eq registration :registered)
                                  (eq reserved :checkpoint-reserved)
                                  (eq updated :checkpoint-updated)
                                  (eq word :checkpoint-current)
                                  (equal source current)
                                  (equal claim '(8192 4096 1 1 1))
                                  (equal retained payload) (eq phase :running)
                                  (equal revision 1) (equal (fn-prl-nth 2 charged) 8))))
              (mv-let (stale fn-bpc-segment)
                (fn-bpcc-segment-payload-replace token 0 0 :running :running :delayed fn-bpc-segment)
                (let ((unchanged (equal row (fn-bpcs-rowsi 0 fn-bpc-segment))))
                  (mv-let (cancelled fn-bpc-segment)
                    (fn-bpcc-segment-payload-cancel-current '(:bp-controller 2 0) 0 fn-bpc-segment)
                    (mv-let (last-word last-source last-claim last-payload last-phase last-revision)
                      (fn-bpcc-segment-payload-read token 0 fn-bpc-segment)
                      (mv (and positive (eq stale :stale-checkpoint) unchanged
                               (eq cancelled :checkpoint-retained)
                               (eq last-word :checkpoint-current)
                               (equal last-source current) (equal last-claim claim)
                               (equal last-payload payload) (eq last-phase :cancelled)
                               (equal last-revision 1)) fn-bpc-segment))))))))))))
(defun fn-bpcc-payload-test-local ()
  (declare (xargs :guard t))
  (with-local-stobj fn-bpc-segment
    (mv-let (answer fn-bpc-segment)
      (fn-bpcc-payload-test-segment fn-bpc-segment)
      answer)))
(assert-event (fn-bpcc-payload-test-local))
