(in-package "ACL2")
(include-book "../../books/bp-controller-registry-carry")
; Actual initial CURRENT, unfunded storage fixture: no registration claim.
(defconst *bpcc-initial*
  (fn-bpnf-initial-state
    (fn-bpn-config (cons :dtn '(47 47 98 112 45 108 111 99 97 108 47))
                   3600000 2 32 1048576) 8 1048576))
(assert-event (and (true-listp *bpcc-initial*)
                  (fn-bpnp-step-guard-premisesp *bpcc-initial*)))
(defun bpcc-install (current fn-bp-controller-registry)
  (declare (xargs :stobjs fn-bp-controller-registry :guard t))
  (let ((fn-bp-controller-registry (update-fn-bpcr-highwater 1 fn-bp-controller-registry)))
    (stobj-let ((fn-bpc-node (fn-bpcr-root fn-bp-controller-registry)))
      (fn-bpc-node)
      (stobj-let ((fn-bpc-segment (fn-bpcn-children-get 'fn-bpc-segment fn-bpc-node (create-fn-bpc-segment))))
        (fn-bpc-segment)
        (update-fn-bpcs-rowsi 0 (list 7 :live current :unfunded-fixture nil) fn-bpc-segment)
        fn-bpc-node)
      fn-bp-controller-registry)))
(defun bpcc-observe (old next fn-bp-controller-registry)
  (declare (xargs :stobjs fn-bp-controller-registry :verify-guards nil))
  (let* ((fn-bp-controller-registry (bpcc-install old fn-bp-controller-registry))
         (carry (fn-bpc-registry-carryp fn-bp-controller-registry)))
    (mv-let (status current left) (fn-bpc-current '(:bp-controller 7 0) 4 fn-bp-controller-registry)
      (mv-let (updated rest fn-bp-controller-registry)
        (fn-bpc-current-replace '(:bp-controller 7 0) (fn-bpnf-epoch old)
                               (fn-bpnf-issued old) next 4 fn-bp-controller-registry)
        (mv (list carry status (true-listp current) (fn-bpnp-step-guard-premisesp current)
                  left updated rest (fn-bpc-registry-carryp fn-bp-controller-registry))
            fn-bp-controller-registry)))))
(defun bpcc-fixture (old next)
  (declare (xargs :verify-guards nil))
  (with-local-stobj fn-bp-controller-registry
    (mv-let (answer fn-bp-controller-registry)
      (bpcc-observe old next fn-bp-controller-registry) answer)))
; Complete read and replacement antecedents/conclusions in actual stobj effects.
(assert-event (equal (bpcc-fixture *bpcc-initial* *bpcc-initial*)
                     '(t :current t t 3 :updated 3 t)))
; Corrupted-state carry removal: actual :current, proper list, failed guard carry.
(assert-event (equal (bpcc-fixture '(:bpnf-state) *bpcc-initial*)
                     '(nil :current t nil 3 :updated 3 t)))
; Removal of replacement's next guard premise (proper next list retained).
(assert-event (and (true-listp '(:bpnf-state))
                  (not (fn-bpnp-step-guard-premisesp '(:bpnf-state)))
                  (equal (bpcc-fixture *bpcc-initial* '(:bpnf-state))
                         '(t :current t t 3 :updated 3 nil))))
; Removal of proper next CURRENT: guard-premises projection remains true.
(defconst *bpcc-improper* (append *bpcc-initial* :improper-tail))
(assert-event (and (not (true-listp *bpcc-improper*))
                  (fn-bpnp-step-guard-premisesp *bpcc-improper*)
                  (equal (bpcc-fixture *bpcc-initial* *bpcc-improper*)
                         '(t :current t t 3 :updated 3 nil))))
(defun bpcc-empty-observe (fn-bp-controller-registry)
  (declare (xargs :stobjs fn-bp-controller-registry :verify-guards nil))
  (mv-let (status current left) (fn-bpc-current '(:bp-controller 7 0) 4 fn-bp-controller-registry)
    (list (fn-bpc-registry-carryp fn-bp-controller-registry) status
          (true-listp current) (fn-bpnp-step-guard-premisesp current) left)))
(defun bpcc-empty-fixture ()
  (declare (xargs :verify-guards nil))
  (with-local-stobj fn-bp-controller-registry
    (mv-let (answer fn-bp-controller-registry)
      (mv (bpcc-empty-observe fn-bp-controller-registry) fn-bp-controller-registry)
      answer)))
; Maintained carry without an actual :current result does not imply guard carry.
(assert-event (equal (bpcc-empty-fixture) '(t :stale-controller t nil 4)))
(defun bpcc-corrupt-other-slot (fn-bp-controller-registry)
  (declare (xargs :stobjs fn-bp-controller-registry :guard t))
  (stobj-let ((fn-bpc-node (fn-bpcr-root fn-bp-controller-registry)))
    (fn-bpc-node)
    (stobj-let ((fn-bpc-segment (fn-bpcn-children-get 'fn-bpc-segment fn-bpc-node (create-fn-bpc-segment))))
      (fn-bpc-segment)
      (update-fn-bpcs-rowsi 1 '(9 :live (:bpnf-state) :corrupted-fixture nil) fn-bpc-segment)
      fn-bpc-node)
    fn-bp-controller-registry))
(defun bpcc-corrupt-other-fixture ()
  (declare (xargs :verify-guards nil))
  (with-local-stobj fn-bp-controller-registry
    (mv-let (answer fn-bp-controller-registry)
      (let ((fn-bp-controller-registry (bpcc-corrupt-other-slot fn-bp-controller-registry)))
        (bpcc-observe *bpcc-initial* *bpcc-initial* fn-bp-controller-registry))
      answer)))
; Replacement's registry-carry omission: other corrupted row survives actual
; update while both next CURRENT premises remain affirmed by the first test.
(assert-event (and (true-listp *bpcc-initial*)
                  (fn-bpnp-step-guard-premisesp *bpcc-initial*)
                  (equal (bpcc-corrupt-other-fixture)
                         '(nil :current t t 3 :updated 3 nil))))
