; Explicitly unfunded registered storage trajectory, no positive issuer.
(in-package "ACL2")
(include-book "../../books/bp-checkpoint-cancelled-observation")
(include-book "../../books/bp-checkpoint-close-registered")
(include-book "bp-checkpoint-prefix-registered-tests")
(set-verify-guards-eagerness 0)
(defun bpcancel-run (token current fn-bp-controller-registry)
 (declare (xargs :stobjs fn-bp-controller-registry :guard t))
 (mv-let (prepared action left fn-bp-controller-registry)
  (fn-bpck-registered-prefix-next '(:bp-controller 2 0) 1 4 fn-bp-controller-registry)
  (declare (ignore left))
  (mv-let (fenced ignored-current ignored-claim ignored-payload ignored-phase ignored-rev
            ignored-left fn-bp-controller-registry)
   (fn-bpcc-directory-payload '(:bp-controller 2 0) nil :fence-current
                              0 nil nil nil 4 fn-bp-controller-registry)
   (declare (ignore ignored-current ignored-claim ignored-payload ignored-phase ignored-rev ignored-left))
   (mv-let (ordinary ordinary-left fn-bp-controller-registry)
    (fn-bpck-registered-prefix-observe '(:bp-controller 2 0) token 2 :unknown 4 fn-bp-controller-registry)
    (declare (ignore ordinary-left))
    (mv-let (settled settled-left fn-bp-controller-registry)
     (fn-owner-bp-checkpoint-cancelled-observe '(:bp-controller 2 0) token 2 :unknown 4 fn-bp-controller-registry)
     (declare (ignore settled-left))
     (mv-let (close-prepared close-action close-left fn-bp-controller-registry)
      (fn-owner-bp-checkpoint-close-next '(:bp-controller 2 0) 4 fn-bp-controller-registry)
      (declare (ignore close-left))
      (mv-let (closed closed-left fn-bp-controller-registry)
       (fn-owner-bp-checkpoint-close-observe '(:bp-controller 2 0) token 4 :unknown 4 fn-bp-controller-registry)
       (declare (ignore closed-left))
       (mv-let (read actual-token frozen claim payload phase revision read-left)
        (fn-bpcc-pending-capture '(:bp-controller 2 0) 4 fn-bp-controller-registry)
        (declare (ignore read-left))
        (mv (and (eq prepared :action-prepared)
                 (equal action (list :bp-checkpoint-io-action token 2 :open 0 nil))
                 (eq fenced :checkpoint-retained)
                 (eq ordinary :stale-checkpoint-observation)
                 (eq settled :cancelled-uncertain)
                 (eq close-prepared :action-prepared)
                 (equal close-action (list :bp-checkpoint-io-action token 4 :close 0 nil))
                 (eq closed :close-uncertain) (eq read :checkpoint-current)
                 (equal actual-token token) (equal frozen current)
                 (equal claim '(8192 4096 1 1 1)) (eq phase :cancelled)
                 (equal revision 5)
                 (equal (fn-bpck-control-io payload) '(:fenced :uncertain))
                 (equal (fn-bpn-nth 11 (fn-bpck-control-job payload)) :uncertain)
                 (null (fn-bpck-control-action payload))) fn-bp-controller-registry)))))))))
(defun bpcancel-local ()
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-bp-controller-registry
  (mv-let (answer fn-bp-controller-registry)
   (mv-let (token job current fn-bp-controller-registry)
    (bppio-seed fn-bp-controller-registry)
    (declare (ignore job))
    (bpcancel-run token current fn-bp-controller-registry)) answer)))
(assert-event (bpcancel-local))
