; UNHOOKED cert-roots (2026-10-02): out of the Makefile certify roots -- its closure reaches books/bp-controller-checkpoint-payload-directory, a Codex-era book that never certified (fn-bpcc-directory-payload guard fails). The code stays; it certifies again with that book.
(in-package "ACL2")
(include-book "../../host/bp-controller-checkpoint-directory-host")
(include-book "../../host/bp-controller-checkpoint-payload-host")
; Seeded unfunded registered storage. Marker payloads are not a real writer.
(defun fn-bpcc-payload-directory-test-install (fn-bp-controller-registry fn-page-read-pool)
  (declare (xargs :stobjs (fn-bp-controller-registry fn-page-read-pool) :guard t))
  (let* ((initial (fn-bpnf-initial-state
                   (fn-bpn-config (cons :dtn '(47 47 98 112 45 108 111 99 97 108 47))
                                  3600000 2 32 1048576) 8 1048576))
         (current (fn-bpnf-with-issued initial
                    (fn-bpnf-operation (fn-bpnf-epoch initial) 0 :checkpoint 5 :pending)))
         (ledger (fn-prl-build '(1000000 100000 10 10 100) '(0 0 0 0 0)
                              7 nil '(1000 0 0 0 0)))
         (fn-page-read-pool (update-fn-prp-data (list ledger nil nil nil nil) fn-page-read-pool))
         (fn-page-read-pool (update-fn-prp-mode :served fn-page-read-pool))
         (fn-bp-controller-registry (update-fn-bpcr-highwater 1 fn-bp-controller-registry)))
    (stobj-let ((fn-bpc-node (fn-bpcr-root fn-bp-controller-registry)))
      (fn-bpc-node)
      (stobj-let ((fn-bpc-segment
                   (fn-bpcn-children-get 'fn-bpc-segment fn-bpc-node (create-fn-bpc-segment))))
        (fn-bpc-segment)
        (mv-let (word fn-bpc-segment)
          (fn-bpc-segment-install 2 0 current :unfunded-storage-only fn-bpc-segment)
          (declare (ignore word)) fn-bpc-segment)
        fn-bpc-node)
      (mv fn-bp-controller-registry fn-page-read-pool))))
(defun fn-bpcc-payload-directory-test-observe (fn-bp-controller-registry fn-page-read-pool)
  (declare (xargs :stobjs (fn-bp-controller-registry fn-page-read-pool) :guard t))
  (mv-let (reserved token left fn-bp-controller-registry fn-page-read-pool)
    (fn-owner-bp-checkpoint-reserve '(:bp-controller 2 0) '(8192 4096 1 1 1) 4 fn-bp-controller-registry fn-page-read-pool)
    (let ((ledger (fn-owner-page-read-ledger fn-page-read-pool)))
      (mv-let (updated current claim payload phase revision update-left fn-bp-controller-registry)
        (fn-bpcc-directory-payload '(:bp-controller 2 0) token :replace 0 :reserved :running
                                  '(:job-marker :control-marker :digest-binding-marker) 4 fn-bp-controller-registry)
        (mv-let (stale ignored-current ignored-claim ignored-payload ignored-phase ignored-revision stale-left fn-bp-controller-registry)
          (fn-bpcc-directory-payload '(:bp-controller 2 0) token :replace 0 :running :running :delayed 4 fn-bp-controller-registry)
          (declare (ignore ignored-current ignored-claim ignored-payload ignored-phase ignored-revision))
          (mv-let (fenced fence-left fn-bp-controller-registry fn-page-read-pool)
            (fn-owner-bp-checkpoint-payload-fence-current '(:bp-controller 2 0) 4 fn-bp-controller-registry fn-page-read-pool)
            (mv-let (word kept-current kept-claim kept-payload kept-phase kept-revision read-left fn-bp-controller-registry)
              (fn-bpcc-directory-payload '(:bp-controller 2 0) token :read nil nil nil nil 4 fn-bp-controller-registry)
              (mv (and (eq reserved :checkpoint-reserved) (equal left 2)
                       (eq updated :checkpoint-updated) (equal update-left 3)
                       (eq phase :running) (equal revision 1)
                       (eq stale :stale-checkpoint) (equal stale-left 3)
                       (eq fenced :checkpoint-retained) (equal fence-left 3)
                       (eq word :checkpoint-current) (equal read-left 3)
                       (equal current kept-current) (equal claim kept-claim)
                       (equal payload kept-payload) (equal kept-revision 1)
                       (eq kept-phase :cancelled)
                       (equal (fn-prl-nth 2 ledger) 8)
                       (equal (fn-prl-nth 1 ledger) '(8192 4096 1 1 1))
                       (equal ledger (fn-owner-page-read-ledger fn-page-read-pool)))
                  fn-bp-controller-registry fn-page-read-pool))))))))
(defun fn-bpcc-payload-directory-test-local ()
  (declare (xargs :verify-guards nil))
  (with-local-stobj fn-bp-controller-registry
    (mv-let (answer fn-bp-controller-registry)
      (with-local-stobj fn-page-read-pool
        (mv-let (answer fn-bp-controller-registry fn-page-read-pool)
          (mv-let (fn-bp-controller-registry fn-page-read-pool)
            (fn-bpcc-payload-directory-test-install fn-bp-controller-registry fn-page-read-pool)
            (fn-bpcc-payload-directory-test-observe fn-bp-controller-registry fn-page-read-pool))
          (mv answer fn-bp-controller-registry)))
      answer)))
(assert-event (fn-bpcc-payload-directory-test-local))
