; Unsanctioned local factories below are storage witnesses, not installed
; runtime/constructor/PRS authority. All service callbacks remain unavailable.
(in-package "ACL2")
(include-book "../../books/bp-digest-workspace-storage")
(set-verify-guards-eagerness 0)
(defun bpdst-seed-leaf (controller job fn-bpd-workspace-node)
 (declare (xargs :stobjs fn-bpd-workspace-node :guard t))
 (let ((fn-bpd-workspace-node
  (stobj-let ((fn-bpd-workspace-carry
   (fn-bpd-children-get 'fn-bpd-workspace-carry fn-bpd-workspace-node
                       (create-fn-bpd-workspace-carry))))
   (fn-bpd-workspace-carry)
   (let* ((fn-bpd-workspace-carry (update-fn-bpd-controller controller fn-bpd-workspace-carry))
          (fn-bpd-workspace-carry (update-fn-bpd-job job fn-bpd-workspace-carry))
          (fn-bpd-workspace-carry (update-fn-bpd-nonce 99 fn-bpd-workspace-carry))
          (fn-bpd-workspace-carry (update-fn-bpd-source :unfunded-source-incarnation fn-bpd-workspace-carry))
          (fn-bpd-workspace-carry (update-fn-bpd-phase :digesting fn-bpd-workspace-carry))
          (fn-bpd-workspace-carry (update-fn-bpd-revision 1 fn-bpd-workspace-carry)))
    fn-bpd-workspace-carry)
   fn-bpd-workspace-node)))
  (stobj-let ((pgs-digest-state
   (fn-bpd-children-get 'pgs-digest-state fn-bpd-workspace-node (create-pgs-digest-state))))
   (pgs-digest-state)
   (update-pgs-dc-mode :node pgs-digest-state)
   fn-bpd-workspace-node)))
(defun bpdst-scenario (fn-bpd-workspace-node)
 (declare (xargs :stobjs fn-bpd-workspace-node :guard t))
 (let* ((c0 '(:bp-controller 2 0)) (j0 '(:bp-job 7 (:bp-controller 2 0) 0 5))
        (c1 '(:bp-controller 3 1)) (j1 '(:bp-job 8 (:bp-controller 3 1) 0 5)))
  (mv-let (missing ignored left)
   (fn-bpd-node-read c0 j0 1 0 4 fn-bpd-workspace-node)
   (declare (ignore ignored))
   (let* ((untouched (and (not (fn-bpd-children-boundp 'pgs-digest-state fn-bpd-workspace-node))
                         (not (fn-bpd-children-boundp 'fn-bpd-workspace-carry fn-bpd-workspace-node))))
          (fn-bpd-workspace-node (bpdst-seed-leaf c0 j0 fn-bpd-workspace-node))
          (fn-bpd-workspace-node
           (stobj-let ((fn-bpd-workspace-right
             (fn-bpd-children-get 'fn-bpd-workspace-right fn-bpd-workspace-node
                                 (create-fn-bpd-workspace-right))))
            (fn-bpd-workspace-right)
            (bpdst-seed-leaf c1 j1 fn-bpd-workspace-right)
            fn-bpd-workspace-node)))
    (mv-let (zero rev0 left0)
     (fn-bpd-node-read c0 j0 1 0 4 fn-bpd-workspace-node)
     (mv-let (one rev1 left1)
      (fn-bpd-node-read c1 j1 1 1 4 fn-bpd-workspace-node)
      (mv-let (alias ignored ignored-left)
       (fn-bpd-node-read c0 j0 1 1 4 fn-bpd-workspace-node)
       (declare (ignore ignored ignored-left))
       (mv-let (stale ignored ignored-left)
        (fn-bpd-node-read c0 j0 0 0 4 fn-bpd-workspace-node)
        (declare (ignore ignored ignored-left))
        (mv-let (absent ignored absent-left)
         (fn-bpd-node-read c0 j0 1 2 4 fn-bpd-workspace-node)
         (declare (ignore ignored))
         (mv (and (eq missing :workspace-unavailable) (equal left 3) untouched
                  (eq zero :workspace-current) (equal rev0 1) (equal left0 3)
                  (eq one :workspace-current) (equal rev1 1) (equal left1 2)
                  (eq alias :stale-workspace) (eq stale :stale-workspace-revision)
                  (eq absent :workspace-unavailable) (equal absent-left 3)
                  (not (fn-bpd-children-boundp 'fn-bpd-workspace-left fn-bpd-workspace-node)))
             fn-bpd-workspace-node))))))))))
(defun bpdst-run ()
 (declare (xargs :guard t))
 (with-local-stobj fn-bpd-workspace-node
  (mv-let (passed fn-bpd-workspace-node) (bpdst-scenario fn-bpd-workspace-node) passed)))
(assert-event (bpdst-run))
