; UNHOOKED cert-roots (2026-10-02): out of the Makefile certify roots -- its closure reaches books/bp-controller-checkpoint-payload-directory, a Codex-era book that never certified (fn-bpcc-directory-payload guard fails). The code stays; it certifies again with that book.
; Deliberately unfunded carry storage; no SAME-pool promotion or grant.
(in-package "ACL2")
(include-book "../../books/bp-digest-workspace-publication")
(include-book "bp-digest-workspace-factory-tests")
(set-verify-guards-eagerness 0)
(defun bpdpub-carry-local ()
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-bpd-workspace-carry
  (mv-let (answer fn-bpd-workspace-carry)
   (let* ((fn-bpd-workspace-carry
            (fn-bpd-factory-initialize-carry *bpdf-plan* fn-bpd-workspace-carry))
          (source (fn-bpn-nth 4 *bpdf-plan*))
          (wrong (list :bp-digest-install
                  (list :bp-digest 9 *bpdf-controller* *bpdf-job*)
                  *bpdf-controller* *bpdf-job* source :constructing 7)))
    (mv-let (stale fn-bpd-workspace-carry)
     (fn-bpd-carry-publish wrong 10 fn-bpd-workspace-carry)
     (let ((unchanged (and (eq (fn-bpd-phase fn-bpd-workspace-carry) :constructing)
                          (equal (fn-bpd-revision fn-bpd-workspace-carry) 7))))
      (mv-let (published fn-bpd-workspace-carry)
       (fn-bpd-carry-publish *bpdf-plan* 10 fn-bpd-workspace-carry)
       (mv-let (duplicate fn-bpd-workspace-carry)
        (fn-bpd-carry-publish *bpdf-plan* 10 fn-bpd-workspace-carry)
        (mv-let (wrong-revision fn-bpd-workspace-carry)
         (fn-bpd-carry-publish *bpdf-plan* 11 fn-bpd-workspace-carry)
         (mv (and (eq stale :stale-workspace) unchanged
                  (eq published :carry-published) (eq duplicate :carry-already-installed)
                  (eq wrong-revision :stale-workspace)
                  (eq (fn-bpd-phase fn-bpd-workspace-carry) :installed)
                  (equal (fn-bpd-revision fn-bpd-workspace-carry) 10)
                  (equal (fn-bpd-source fn-bpd-workspace-carry) source)
                  (equal (fn-bpd-nonce fn-bpd-workspace-carry) 8))
             fn-bpd-workspace-carry))))))) answer)))
(assert-event (bpdpub-carry-local))

(include-book "bp-digest-workspace-registered-factory-tests")
; Seed promotion metadata deliberately without performing accounting. This
; checks only registered storage/revision fencing and leaves SAMEpool intact.
(defun bpdpub-registered (fn-bp-controller-registry fn-page-read-pool)
 (declare (xargs :stobjs (fn-bp-controller-registry fn-page-read-pool) :guard t))
 (mv-let (setup fn-bp-controller-registry fn-page-read-pool)
  (bpdfr-observe fn-bp-controller-registry fn-page-read-pool)
  (mv-let (captured job current claim payload phase revision left)
   (fn-bpcc-pending-capture '(:bp-controller 2 0) 4 fn-bp-controller-registry)
   (declare (ignore current claim left))
   (let* ((intent (fn-bpdi-payload-intent payload))
          (workspace (fn-bpdi-token intent))
          (ledger (fn-owner-page-read-ledger fn-page-read-pool)))
    (mv-let (stored plan plan-left fn-bp-controller-registry)
     (fn-owner-bp-digest-install-plan '(:bp-controller 2 0) workspace 4 fn-bp-controller-registry)
     (declare (ignore plan-left))
     (let* ((action (list :bp-digest-publication plan :promoting '(512 0 0 0 0) 5))
            (promoting (fn-bpdi-make workspace :promoting (fn-bpdi-source intent)
                         (fn-bpdi-claim intent) (fn-bpdi-allowance intent)))
            (first (fn-bpck-control-make (fn-bpck-control-job payload)
                     (fn-bpck-control-io payload) promoting action))
            (promoted (fn-bpdi-make workspace :promoted (fn-bpdi-source intent)
                        '(0 0 0 0 1) (fn-bpdi-allowance intent)))
            (second (fn-bpdi-with-intent first promoted)))
      (mv-let (prepared c1 q1 p1 ph1 r1 l1 fn-bp-controller-registry)
       (fn-bpcc-directory-payload '(:bp-controller 2 0) job :replace revision phase :running
                                  first 4 fn-bp-controller-registry)
       (declare (ignore c1 q1 p1 ph1 l1))
       (mv-let (seeded c2 q2 p2 ph2 r2 l2 fn-bp-controller-registry)
        (fn-bpcc-directory-payload '(:bp-controller 2 0) job :replace 3 :running :running
                                   second 4 fn-bp-controller-registry)
        (declare (ignore c2 q2 p2 ph2 l2))
        (mv-let (published pub-left fn-bp-controller-registry)
         (fn-bpd-registered-publish-carry '(:bp-controller 2 0) workspace 4 fn-bp-controller-registry)
         (declare (ignore pub-left))
         (mv-let (unexposed unexposed-left fn-bp-controller-registry)
          (fn-bpd-registered-installed-readout '(:bp-controller 2 0) workspace 4 fn-bp-controller-registry)
          (declare (ignore unexposed-left))
          (mv-let (duplicate dup-left fn-bp-controller-registry)
           (fn-bpd-registered-publish-carry '(:bp-controller 2 0) workspace 4 fn-bp-controller-registry)
           (declare (ignore dup-left))
           (let* ((installed (fn-bpdi-make workspace :installed (fn-bpdi-source intent)
                               '(0 0 0 0 1) (fn-bpdi-allowance intent)))
                  (final (fn-bpck-control-make (fn-bpck-control-job payload)
                           (fn-bpck-control-io payload) installed nil)))
            (mv-let (finished c3 q3 p3 ph3 r3 l3 fn-bp-controller-registry)
             (fn-bpcc-directory-payload '(:bp-controller 2 0) job :replace 4 :running :running
                                        final 4 fn-bp-controller-registry)
             (declare (ignore c3 q3 p3 ph3 l3))
             (mv-let (ready ready-left fn-bp-controller-registry)
              (fn-bpd-registered-installed-readout '(:bp-controller 2 0) workspace 4 fn-bp-controller-registry)
              (declare (ignore ready-left))
              (mv-let (stale stale-left fn-bp-controller-registry)
               (fn-bpd-registered-installed-readout '(:bp-controller 2 0)
                (list :bp-digest 9 '(:bp-controller 2 0) job) 4 fn-bp-controller-registry)
               (declare (ignore stale-left))
               (mv (and setup (eq captured :checkpoint-current) (equal revision 2)
                        (eq stored :stored-plan) (eq prepared :checkpoint-updated) (equal r1 3)
                        (eq seeded :checkpoint-updated) (equal r2 4)
                        (eq published :carry-published) (eq unexposed :workspace-unpublished)
                        (eq duplicate :carry-already-installed)
                        (eq finished :checkpoint-updated) (equal r3 5)
                        (eq ready :installed-storage-ready) (eq stale :stale-workspace)
                        (equal ledger (fn-owner-page-read-ledger fn-page-read-pool)))
                   fn-bp-controller-registry fn-page-read-pool))))))))))))))
))
(defun bpdpub-registered-local ()
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-bp-controller-registry
  (mv-let (answer fn-bp-controller-registry)
   (with-local-stobj fn-page-read-pool
    (mv-let (answer fn-bp-controller-registry fn-page-read-pool)
     (mv-let (fn-bp-controller-registry fn-page-read-pool)
      (fn-bpcc-payload-directory-test-install fn-bp-controller-registry fn-page-read-pool)
      (bpdpub-registered fn-bp-controller-registry fn-page-read-pool))
     (mv answer fn-bp-controller-registry))) answer)))
(assert-event (bpdpub-registered-local))
