; Actual registered source/storage trajectory with deliberately seeded intent.
; No installed allowance or native constructor permission follows.
(in-package "ACL2")
(include-book "../../books/bp-digest-workspace-registered-factory")
(include-book "bp-controller-checkpoint-payload-directory-tests")
(set-verify-guards-eagerness 0)
(defun bpdfr-fixture-prefix (job fuel)
 (declare (xargs :guard (natp fuel) :measure (nfix fuel)))
 (if (or (zp fuel) (not (eq (fn-bpn-nth 6 job) :emit))) job
  (bpdfr-fixture-prefix (fn-bpn-nth 0 (fn-bpck-emit-step job)) (1- fuel))))
(defun bpdfr-observe (fn-bp-controller-registry fn-page-read-pool)
 (declare (xargs :stobjs (fn-bp-controller-registry fn-page-read-pool) :guard t))
 (mv-let (reserved job-token reserve-left fn-bp-controller-registry fn-page-read-pool)
  (fn-owner-bp-checkpoint-reserve '(:bp-controller 2 0) '(8192 4096 1 1 1)
                                 4 fn-bp-controller-registry fn-page-read-pool)
  (declare (ignore reserve-left))
  (let* ((controller '(:bp-controller 2 0))
         (workspace (list :bp-digest 8 controller job-token))
         (initial (fn-bpck-begin job-token 0 5 (fn-bpnr-depth-budget 8) nil nil 8 0 1048576))
         (counted (fn-bpck-census-step initial 10000))
         (emitting (fn-bpck-stage-observation
                    (fn-bpck-stage-granted counted (list :grown job-token)) :created))
         (job (bpdfr-fixture-prefix emitting 10000))
         (payload0 (fn-bpck-control-make job '(:digest-start :pending) nil nil))
         (source (fn-bpck-control-source-incarnation payload0))
         (intent (fn-bpdi-make workspace :reserved source '(512 0 0 0 1) nil))
         (payload (fn-bpdi-with-intent payload0 intent))
         (ledger (fn-owner-page-read-ledger fn-page-read-pool)))
   (mv-let (updated ignored-current ignored-claim ignored-payload ignored-phase ignored-revision ignored-left fn-bp-controller-registry)
    (fn-bpcc-directory-payload controller job-token :replace 0 :reserved :running payload 4 fn-bp-controller-registry)
    (declare (ignore ignored-current ignored-claim ignored-payload ignored-phase ignored-revision ignored-left))
    (mv-let (constructed construct-left fn-bp-controller-registry fn-page-read-pool)
     (fn-owner-bp-digest-install-constructing controller workspace 8 fn-bp-controller-registry fn-page-read-pool)
     (declare (ignore construct-left))
     (mv-let (unavailable public-left fn-bp-controller-registry fn-page-read-pool)
      (fn-owner-bp-digest-install-step controller workspace 8 fn-bp-controller-registry fn-page-read-pool)
      (mv-let (root root-left fn-bp-controller-registry)
       (fn-bpd-registered-factory-turn controller workspace 8 fn-bp-controller-registry)
       (mv-let (digest digest-left fn-bp-controller-registry)
        (fn-bpd-registered-factory-turn controller workspace 8 fn-bp-controller-registry)
        (mv-let (carry carry-left fn-bp-controller-registry)
         (fn-bpd-registered-factory-turn controller workspace 8 fn-bp-controller-registry)
         (mv-let (present present-left fn-bp-controller-registry)
          (fn-bpd-registered-factory-turn controller workspace 8 fn-bp-controller-registry)
          (mv (and (eq reserved :checkpoint-reserved) (eq updated :checkpoint-updated)
                   (eq (fn-bpn-nth 6 job) :digest-finish)
                   (equal source (list :bp-checkpoint-stage job-token 5))
                   (eq constructed :constructing)
                   (eq unavailable :bp-runtime-unavailable) (equal public-left 8)
                   (eq root :root-created) (equal root-left 5)
                   (eq digest :digest-created) (equal digest-left 5)
                   (eq carry :carry-created) (equal carry-left 5)
                   (eq present :storage-present) (equal present-left 5)
                   (equal ledger (fn-owner-page-read-ledger fn-page-read-pool)))
              fn-bp-controller-registry fn-page-read-pool)))))))))))
(defun bpdfr-local ()
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-bp-controller-registry
  (mv-let (answer fn-bp-controller-registry)
   (with-local-stobj fn-page-read-pool
    (mv-let (answer fn-bp-controller-registry fn-page-read-pool)
     (mv-let (fn-bp-controller-registry fn-page-read-pool)
      (fn-bpcc-payload-directory-test-install fn-bp-controller-registry fn-page-read-pool)
      (bpdfr-observe fn-bp-controller-registry fn-page-read-pool))
     (mv answer fn-bp-controller-registry))) answer)))
(assert-event (bpdfr-local))
