; UNHOOKED cert-roots (2026-10-02): out of the Makefile certify roots -- its closure reaches books/bp-controller-checkpoint-payload-directory, a Codex-era book that never certified (fn-bpcc-directory-payload guard fails). The code stays; it certifies again with that book.
; Explicitly unfunded local storage factory. Plan shape is not permission.
(in-package "ACL2")
(include-book "../../books/bp-digest-workspace-factory")
(set-verify-guards-eagerness 0)
(defconst *bpdf-controller* '(:bp-controller 2 1))
(defconst *bpdf-job* '(:bp-job 7 (:bp-controller 2 1) 0 5))
(defconst *bpdf-token* (list :bp-digest 8 *bpdf-controller* *bpdf-job*))
(defconst *bpdf-plan* (list :bp-digest-install *bpdf-token* *bpdf-controller* *bpdf-job*
                          (list :bp-checkpoint-stage *bpdf-job* 5) :constructing 7))
(defun bpdf-local ()
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-bpd-workspace-node
  (mv-let (answer fn-bpd-workspace-node)
   (mv-let (yield left0 fn-bpd-workspace-node)
    (fn-bpd-node-install-turn *bpdf-plan* 1 0 fn-bpd-workspace-node)
    (let ((no-create (not (fn-bpd-children-boundp 'fn-bpd-workspace-right fn-bpd-workspace-node))))
     (mv-let (node left1 fn-bpd-workspace-node)
      (fn-bpd-node-install-turn *bpdf-plan* 1 2 fn-bpd-workspace-node)
      (mv-let (missing ignored missing-left)
       (fn-bpd-node-read *bpdf-controller* *bpdf-job* 7 1 2 fn-bpd-workspace-node)
       (declare (ignore ignored missing-left))
       (mv-let (digest left2 fn-bpd-workspace-node)
        (fn-bpd-node-install-turn *bpdf-plan* 1 2 fn-bpd-workspace-node)
        (mv-let (still-missing ignored still-left)
         (fn-bpd-node-read *bpdf-controller* *bpdf-job* 7 1 2 fn-bpd-workspace-node)
         (declare (ignore ignored still-left))
         (mv-let (carry left3 fn-bpd-workspace-node)
          (fn-bpd-node-install-turn *bpdf-plan* 1 2 fn-bpd-workspace-node)
          (mv-let (read revision read-left)
           (fn-bpd-node-read *bpdf-controller* *bpdf-job* 7 1 2 fn-bpd-workspace-node)
           (declare (ignore read-left))
           (mv-let (present left4 fn-bpd-workspace-node)
            (fn-bpd-node-install-turn *bpdf-plan* 1 2 fn-bpd-workspace-node)
            (mv (and (equal yield :yield) (equal left0 0) no-create
                     (equal node :node-created) (equal left1 1)
                     (equal missing :workspace-unavailable)
                     (equal digest :digest-created) (equal left2 0)
                     (equal still-missing :workspace-unavailable)
                     (equal carry :carry-created) (equal left3 0)
                     (equal read :workspace-current) (equal revision 7)
                     (equal present :storage-present) (equal left4 0)
                     (not (fn-bpd-children-boundp 'pgs-digest-state fn-bpd-workspace-node))
                     (not (fn-bpd-children-boundp 'fn-bpd-workspace-carry fn-bpd-workspace-node)))
                fn-bpd-workspace-node)))))))))) answer)))
(assert-event (bpdf-local))
; Literal returned-fuel support teeth. Actual local node, not installed grant.
(defun bpdf-fuel-domain-local (fuel)
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-bpd-workspace-node
  (mv-let (answer fn-bpd-workspace-node)
   (mv-let (word left fn-bpd-workspace-node)
    (fn-bpd-node-install-turn *bpdf-plan* 1 fuel fn-bpd-workspace-node)
    (declare (ignore word))
    (mv (and (natp left) (<= left fuel)) fn-bpd-workspace-node)) answer)))
(assert-event (and (natp 2) (bpdf-fuel-domain-local 2)))
; Guard-domain removal witness: invalid negative fuel; no runtime invocation.
(assert-event (with-guard-checking :none
 (and (not (natp -1)) (not (bpdf-fuel-domain-local -1)))))
