; Successful served-path restart from a rotation that owes a queued job.
(in-package "ACL2")
(include-book "bp-node-rotation-due-tests")
(include-book "../../books/bp-node-rotation-recovery")

(defteeth fn-bpnj-rotation-restart-succeeds-with-owed-work
  :claim (let* ((plan (fn-bpnr-published-plan st generation ck))
         (fresh (fn-bpnr-open-fresh st))
         (seeded (fn-bpnr-seed-state fresh plan))
         (event (fn-bpnr-recover-auto-event seeded nil :ready nil plan))
         (served (append (fn-bprpf-admit-recovery event profile) (list domain)))
         (answer (fn-bpnj-step seeded served)))
    (((proposes (equal (car (car (fn-bpnf-answer-effects
                          (fn-bpnp-rotate-step st generation ck)))) :persist-checkpoint))
      (invariant (fn-bpn-machine-invariantp (fn-bpnf-base st)))
      (projection (fn-bpnr-recovery-replayp
         0 (+ 1 (fn-bpnf-epoch st))
         (list :ready (fn-bpnf-held-list st) (fn-bpnf-handoffs st)
               (cons (fn-bpnf-epoch st) 0) (fn-bpnf-next-arrival st))
         (fn-bpn-machine-state-max-jobs (fn-bpnf-base st))
         (fn-bpn-machine-state-max-octets (fn-bpnf-base st))))
      (profile (or (not (equal (fn-bpn-nth 0 (fn-bpn-nth 4 event)) :ready))
            (and (fn-bpnpf-profilep profile)
             (fn-bprpf-held-adus-fitp (fn-bpn-nth 1 (fn-bpn-nth 4 event))
                                    (fn-bpnpf-adu-octets profile)))))
      (domain (fn-bpnp-clock-domain-admitsp served)))
     (and (equal (car (car (fn-bpnf-answer-effects answer))) :restart-ready)
        (equal (fn-bpn-machine-state-jobs (fn-bpnf-base (fn-bpnf-answer-state answer)))
               (fn-bpn-machine-state-jobs (fn-bpnf-base st)))
        (equal (fn-bpn-machine-state-next-token (fn-bpnf-base (fn-bpnf-answer-state answer)))
               (fn-bpn-machine-state-next-token (fn-bpnf-base st)))
        (equal (fn-bpn-host-lifecycle-recovery-agrees-p
                (fn-bpn-lifecycle-recovery-from nil nil (fn-bpnr-plan-start-token plan))
                (fn-bpnf-base (fn-bpnf-answer-state answer))) t))))
  :subject fn-bpnj-step
  :witness ((st (bprd-owed-q)) (generation 1) (ck (bprd-owed-ck))
            (profile '(8 1048576 65538 1048576)) (domain '(:same (7 7 7 7))))
  :breaks ((proposes ((ck (update-nth 7 nil (bprd-owed-ck)))))
           (invariant ((st (bprd-token-q 5000))
                       (ck (update-nth 8 5000 (bprd-owed-ck)))))
           (projection ((st (update-nth 10 0 (bprd-owed-q)))
                        (ck (update-nth 5 0 (bprd-owed-ck)))))
           (profile ((profile nil)))
           (domain ((domain '(:fence :different-boot)))))
  :mutations ((reopens-unseeded
               (:conclusion (let* ((unseeded-event (fn-bpnr-recover-auto-event fresh nil :ready nil plan))
        (answer (fn-bpnj-step fresh (append (fn-bprpf-admit-recovery unseeded-event profile) (list domain)))))
(and (equal (car (car (fn-bpnf-answer-effects answer))) :restart-ready)
        (equal (fn-bpn-machine-state-jobs (fn-bpnf-base (fn-bpnf-answer-state answer)))
               (fn-bpn-machine-state-jobs (fn-bpnf-base st)))
        (equal (fn-bpn-machine-state-next-token (fn-bpnf-base (fn-bpnf-answer-state answer)))
               (fn-bpn-machine-state-next-token (fn-bpnf-base st)))
        (equal (fn-bpn-host-lifecycle-recovery-agrees-p
                (fn-bpn-lifecycle-recovery-from nil nil (fn-bpnr-plan-start-token plan))
                (fn-bpnf-base (fn-bpnf-answer-state answer))) t))))
               ((st (bprd-owed-q)) (generation 1) (ck (bprd-owed-ck))
                (profile '(8 1048576 65538 1048576)) (domain '(:same (7 7 7 7))))
               :fault "omitting fn-bpnr-seed-state loses the owed job in fn-bpnj-step's answer")))
