; Isolated guard and malformed-input regression evidence.
(in-package "ACL2")
(include-book "../../books/bp-workflow-records")
(assert-event (equal (symbol-class 'fn-bp-journal-textp (w state)) :common-lisp-compliant))
(assert-event (equal (guard 'fn-bp-journal-textp nil (w state)) ''t))
(assert-event (equal (symbol-class 'fn-bp-u64p (w state)) :common-lisp-compliant))
(assert-event (equal (guard 'fn-bp-u64p nil (w state)) ''t))
(assert-event (equal (symbol-class 'fn-bp-journal-nth (w state)) :common-lisp-compliant))
(assert-event (equal (guard 'fn-bp-journal-nth nil (w state)) ''t))
(assert-event (equal (symbol-class 'fn-bp-config-recordp (w state)) :common-lisp-compliant))
(assert-event (equal (guard 'fn-bp-config-recordp nil (w state)) ''t))
(assert-event (equal (symbol-class 'fn-bp-config-from-record (w state)) :common-lisp-compliant))
(assert-event (equal (guard 'fn-bp-config-from-record nil (w state)) ''t))
(assert-event (equal (symbol-class 'fn-bp-journal-recordp (w state)) :common-lisp-compliant))
(assert-event (equal (guard 'fn-bp-journal-recordp nil (w state)) ''t))
(assert-event (equal (symbol-class 'fn-bp-record-event (w state)) :common-lisp-compliant))
(assert-event (equal (guard 'fn-bp-record-event nil (w state)) ''t))
(assert-event (equal (symbol-class 'fn-bp-record-contextp (w state)) :common-lisp-compliant))
(assert-event (equal (guard 'fn-bp-record-contextp nil (w state)) ''t))
(assert-event (equal (symbol-class 'fn-bp-apply-journal-record (w state)) :common-lisp-compliant))
(assert-event (equal (guard 'fn-bp-apply-journal-record nil (w state)) ''t))
(assert-event (equal (symbol-class 'fn-bp-replay-records (w state)) :common-lisp-compliant))
(assert-event (equal (guard 'fn-bp-replay-records nil (w state)) ''t))
(assert-event (equal (symbol-class 'fn-bp-replay-journal (w state)) :common-lisp-compliant))
(assert-event (equal (guard 'fn-bp-replay-journal nil (w state)) ''t))

; Malformed/garbage inputs are handled totally: no error.
(assert-event (equal (fn-bp-journal-textp 7) nil))
(assert-event (equal (fn-bp-journal-nth 3 7) nil))
(assert-event (equal (fn-bp-journal-nth 0 '(a b . c)) 'a))
(assert-event (equal (fn-bp-journal-recordp 7) nil))
(assert-event (equal (fn-bp-record-event 7) nil))
(assert-event (equal (fn-bp-apply-journal-record 7 7) (list nil 7 nil)))
(assert-event (equal (fn-bp-apply-journal-record 7 '(a . b)) (list nil 7 nil)))
(assert-event (equal (fn-bp-replay-records 7 '(a . b) nil) (list nil 7 nil)))
(assert-event (equal (fn-bp-replay-journal 7 7) (list nil nil nil)))
(assert-event (equal (fn-bp-replay-journal 7 '(a . b)) (list nil nil nil)))
