(in-package "ACL2")
(include-book "../../books/cold-read-layout")
(include-book "std/testing/assert-bang" :dir :system)
; Independent numeric pins from the recorded native introspection, summing
; each actual object's primitive-object-size, including synchronized lock.
(assert! (equal (fn-crl-table-octets 8 nil) 496))
(assert! (equal (fn-crl-table-octets 8 t) 560))
(assert! (equal (fn-crl-table-octets 16 nil) 688))
(assert! (equal (fn-crl-table-octets 16 t) 784))
(assert! (equal (fn-crl-table-octets 100 nil) 2816))
(assert! (equal (fn-crl-table-octets 100 t) 3248))
(assert! (equal (fn-crl-table-octets 65536 nil) 1573168))
(assert! (equal (fn-crl-table-octets 65536 t) 1835344))
(assert! (and (fn-crl-table-supportedp (expt 2 24))
              (not (fn-crl-table-supportedp (+ 1 (expt 2 24))))))
(assert! (equal (fn-crl-natural-octets (- (expt 2 62) 1)) 0))
(assert! (equal (fn-crl-natural-octets (- (expt 2 63) 1)) 16))
(assert! (equal (fn-crl-natural-octets (- (expt 2 64) 1)) 32))
(assert! (equal (fn-crl-natural-octets (- (expt 2 256) 1)) 48))
(assert! (equal (fn-crl-natural-octets (- (expt 2 4096) 1)) 528))
