(in-package "ACL2")
(include-book "../../books/cold-read-bootstrap")
(include-book "std/testing/assert-bang" :dir :system)
(defconst *crb-runtime* '("SBCL" "2.6.8" "X86-64" "Linux" 3 0 0))
(defconst *crb-policy* '(67108864 2 64 100000 100000))
; Literal map object pins: four EQL64=4*1840, EQUAL8=560, EQ9=544.
(assert! (equal (fn-crb-map-octets *crb-policy*) (+ (* 4 1840) 560 544)))
(assert! (equal (fn-crb-executor-octets *crb-policy* *crb-runtime*) 134880))
(assert! (equal (fn-crb-binding-capacity *crb-policy*) 75))
(assert! (equal (fn-crb-remove-scratch-octets *crb-policy*) 2400))
(assert! (equal (nthcdr 3 (fn-crb-start-plan *crb-policy* nil *crb-runtime*)) '(64 8 9 2 21)))
(assert! (and (equal (fn-crv-nth 0 (fn-crb-start-plan *crb-policy* nil *crb-runtime*)) :admitted)
              (fn-prs-fundedp (fn-crv-pool-budget *crb-policy* nil)
                              (fn-crb-permanent-baseline *crb-policy* nil *crb-runtime*)
                              '(0 0 0 0 0) '(0 0 0 0 0))))
; Failed bootstrap cannot leak constructor capacities.
(assert! (equal (fn-crb-start-plan '(1 2 64 100000 100000) nil *crb-runtime*)
                '(:refused :cold-bootstrap-exceeds-budget)))
(assert! (equal (fn-crb-start-plan nil nil *crb-runtime*) '(:refused :invalid-cold-resource-profile)))
(assert! (equal (fn-crb-start-plan (list (expt 2 63) 1 (+ 1 (expt 2 24)) 100000 100000) nil *crb-runtime*)
                '(:refused :unrepresentable-cold-table-capacity)))

(assert! (equal (fn-crb-start-plan *crb-policy* nil nil)
                '(:refused :unsupported-cold-runtime)))
(assert! (equal (fn-crb-start-plan *crb-policy* nil '("SBCL" "2.6.8" "X86-64" "Linux" 3 1 0))
                '(:refused :unsupported-cold-runtime)))
(assert! (equal (fn-crb-start-plan *crb-policy* nil '("SBCL" "2.6.8" "X86-64" "Linux" 3 0 1))
                '(:refused :unsupported-cold-runtime)))
(assert! (equal (fn-crb-start-plan *crb-policy* nil '("SBCL" "2.6.9" "X86-64" "Linux" 3 0 0))
                '(:refused :unsupported-cold-runtime)))

(assert! (fn-cgb-planp (fn-crb-start-plan *crb-policy* nil *crb-runtime*)))
