(in-package "ACL2")
(include-book "../../host/cold-read-bootstrap-host")
(include-book "std/testing/assert-bang" :dir :system)
(defun prh-bootstrap-run (fn-page-read-pool)
  (declare (xargs :mode :program :stobjs fn-page-read-pool))
  (mv-let (refused ignored fn-page-read-pool)
    (fn-owner-page-read-bootstrap '(1 2 64 100000 100000) nil '("SBCL" "2.6.8" "X86-64" "Linux" 3 0 0) 0 0 fn-page-read-pool)
    (let ((uninstalled (and (not ignored) (not (fn-prp-data fn-page-read-pool))
                            (equal (fn-prp-mode fn-page-read-pool) :uninitialized))))
      (mv-let (word plan fn-page-read-pool)
        (fn-owner-page-read-bootstrap '(67108864 2 64 100000 100000) nil '("SBCL" "2.6.8" "X86-64" "Linux" 3 0 0) 0 0 fn-page-read-pool)
        (mv (list refused uninstalled word (nthcdr 3 plan)
                  (equal (fn-prl-baseline (fn-owner-page-read-ledger fn-page-read-pool))
                         (fn-crb-permanent-baseline '(67108864 2 64 100000 100000) nil '("SBCL" "2.6.8" "X86-64" "Linux" 3 0 0))))
            fn-page-read-pool)))))
(defun prh-bootstrap-exec ()
  (declare (xargs :mode :program))
  (with-local-stobj fn-page-read-pool
    (mv-let (result fn-page-read-pool) (prh-bootstrap-run fn-page-read-pool) result)))
(assert! (equal (prh-bootstrap-exec)
                '(:cold-bootstrap-exceeds-budget t :installed (64 8 9 2) t)))
(assert-event (eq (symbol-class 'fn-owner-page-read-bootstrap (w state)) :common-lisp-compliant))
