; Actual STATE/ATS callback fixtures with synthetic installation. No native
; runtime selection or source allowance is asserted by this setup.
(in-package "ACL2")
(include-book "../../host/connection-operation-ticket-host")

(defun fn-cott-setup (fn-allocation-turn-slots fn-page-read-pool)
 (declare (xargs :stobjs (fn-allocation-turn-slots fn-page-read-pool) :verify-guards nil))
 (let* ((association '(:allocation-epoch-association :runtime :profile :pool 10 1000))
        (installation (list :allocation-epoch-installation association 1000 800 2 20 20 20 50 10 20 7))
        (fn-page-read-pool (fn-owner-page-read-keep-ledger
          '((1000 1000 1000 1000 1000) (0 0 0 0 0) 0 nil (0 0 0 0 0)) fn-page-read-pool))
        (fn-page-read-pool (update-fn-prp-alloc-installation installation fn-page-read-pool))
        (fn-page-read-pool (update-fn-prp-alloc-mode :active fn-page-read-pool))
        (fn-page-read-pool (update-fn-prp-alloc-occupied 100 fn-page-read-pool))
        (fn-page-read-pool (update-fn-prp-alloc-allocated 20 fn-page-read-pool)))
  (mv-let (word fn-allocation-turn-slots)
   (fn-ats-construct-internal '(:connection-start) fn-allocation-turn-slots fn-page-read-pool)
   (mv word fn-allocation-turn-slots fn-page-read-pool))))

(defun fn-cott-case (kind fn-allocation-turn-slots fn-page-read-pool state)
 (declare (xargs :stobjs (fn-allocation-turn-slots fn-page-read-pool state) :verify-guards nil))
 (mv-let (constructed fn-allocation-turn-slots fn-page-read-pool)
  (fn-cott-setup fn-allocation-turn-slots fn-page-read-pool)
  (mv-let (entered nonce fn-allocation-turn-slots fn-page-read-pool)
   (fn-ats-enter-internal 0 :connection-start fn-allocation-turn-slots fn-page-read-pool)
   (let* ((ticket (and (not (member-eq kind '(:refuse :no-ticket)))
                   (list :connection-operation-ticket
                         (if (eq kind :intent) :start-intent :started)
                         :reader nil nil nil 42 0 nonce 0 9 :descriptor '(40 0 0 0 1) 8 20 :token)))
          (state (f-put-global 'fn-owner-connection-operation-ticket ticket state))
          (state (f-put-global 'fn-owner-connection-operation-installation :retained-installation state))
          (initial (and (eq constructed :constructed) (eq entered :gate-owned)
                        (equal nonce 0) (equal (fn-prp-alloc-active-turns fn-page-read-pool) 1)
                        (equal (fn-prp-alloc-allocated fn-page-read-pool) 30))))
    (cond
     ((eq kind :refuse)
      (mv-let (erp word retained fn-allocation-turn-slots fn-page-read-pool state)
       (fn-owner-index-connection-refuse-internal 0 nonce :refused fn-allocation-turn-slots fn-page-read-pool state)
       (mv (and initial (not erp) (eq word :refused) (not retained)
                (equal (fn-prp-alloc-active-turns fn-page-read-pool) 0)
                (equal (fn-prp-alloc-allocated fn-page-read-pool) 30)
                (not (fn-owner-connection-operation-ticket state)))
           fn-allocation-turn-slots fn-page-read-pool state)))
     ((eq kind :fault)
      (mv-let (erp word fn-allocation-turn-slots fn-page-read-pool state)
       (fn-owner-index-connection-fault fn-allocation-turn-slots fn-page-read-pool state)
       (let ((once (list (fn-ats-noncesi 0 fn-allocation-turn-slots)
                         (fn-ats-phasesi 0 fn-allocation-turn-slots)
                         (fn-prp-alloc-mode fn-page-read-pool)
                         (fn-prp-alloc-active-turns fn-page-read-pool)
                         (fn-prp-alloc-allocated fn-page-read-pool)
                         (fn-owner-connection-operation-ticket state))))
        (mv-let (erp2 word2 fn-allocation-turn-slots fn-page-read-pool state)
         (fn-owner-index-connection-fault fn-allocation-turn-slots fn-page-read-pool state)
         (mv (and initial (not erp) (not erp2) (eq word :recovery-required) (eq word2 word)
                  (equal once (list (fn-ats-noncesi 0 fn-allocation-turn-slots)
                                    (fn-ats-phasesi 0 fn-allocation-turn-slots)
                                    (fn-prp-alloc-mode fn-page-read-pool)
                                    (fn-prp-alloc-active-turns fn-page-read-pool)
                                    (fn-prp-alloc-allocated fn-page-read-pool)
                                    (fn-owner-connection-operation-ticket state)))
                  (equal ticket (fn-owner-connection-operation-ticket state))
                  (eq (fn-prp-alloc-mode fn-page-read-pool) :recovery)
                  (equal (fn-prp-alloc-active-turns fn-page-read-pool) 1)
                  (equal (fn-prp-alloc-allocated fn-page-read-pool) 30))
             fn-allocation-turn-slots fn-page-read-pool state)))))
     (t
      (mv-let (erp word fn-allocation-turn-slots fn-page-read-pool state)
       (fn-owner-index-connection-finish 0 nonce fn-allocation-turn-slots fn-page-read-pool state)
       (let ((ok (and initial (not erp)
                   (if (member-eq kind '(:intent :no-ticket))
                       (and (eq word :recovery-required)
                            (equal ticket (fn-owner-connection-operation-ticket state))
                            (equal (fn-prp-alloc-active-turns fn-page-read-pool) 1))
                     (and (eq word :left)
                          (equal (fn-owner-connection-operation-ticket state)
                                 (update-nth 1 :finished ticket))
                          (equal (fn-prp-alloc-active-turns fn-page-read-pool) 0)))
                   (equal (fn-prp-alloc-allocated fn-page-read-pool) 30)
                   (eq (fn-owner-connection-operation-installation state) :retained-installation))))
        (mv-let (erp2 word2 fn-allocation-turn-slots fn-page-read-pool state)
         (fn-owner-index-connection-finish 0 nonce fn-allocation-turn-slots fn-page-read-pool state)
         (mv (and ok (not erp2) (eq word2 :recovery-required)
                  (equal (fn-prp-alloc-active-turns fn-page-read-pool)
                         (if (member-eq kind '(:intent :no-ticket)) 1 0)))
             fn-allocation-turn-slots fn-page-read-pool state))))))))))

(defun fn-cott-local (kind state)
 (declare (xargs :stobjs state :verify-guards nil))
 (with-local-stobj fn-page-read-pool
  (mv-let (ok fn-page-read-pool state)
   (with-local-stobj fn-allocation-turn-slots
    (mv-let (ok fn-allocation-turn-slots fn-page-read-pool state)
     (fn-cott-case kind fn-allocation-turn-slots fn-page-read-pool state)
     (mv ok fn-page-read-pool state)))
   (mv ok state))))

(make-event (mv-let (ok state) (fn-cott-local :finish state)
 (if ok (value '(value-triple :passed-finish)) (er soft 'ticket "finish failed"))))
(make-event (mv-let (ok state) (fn-cott-local :refuse state)
 (if ok (value '(value-triple :passed-refuse)) (er soft 'ticket "refuse failed"))))
(make-event (mv-let (ok state) (fn-cott-local :intent state)
 (if ok (value '(value-triple :passed-intent)) (er soft 'ticket "intent failed"))))
(make-event (mv-let (ok state) (fn-cott-local :fault state)
 (if ok (value '(value-triple :passed-fault)) (er soft 'ticket "fault failed"))))
(make-event (mv-let (ok state) (fn-cott-local :no-ticket state)
 (if ok (value '(value-triple :passed-no-ticket)) (er soft 'ticket "no-ticket failed"))))

(assert-event
 (and (eq (getpropc 'fn-owner-index-connection-finish 'symbol-class nil (w state)) :common-lisp-compliant)
      (eq (getpropc 'fn-owner-index-connection-fault 'symbol-class nil (w state)) :common-lisp-compliant)
      (equal (getpropc 'fn-owner-index-connection-finish 'stobjs-out nil (w state))
             '(nil nil fn-allocation-turn-slots fn-page-read-pool state))
      (equal (getpropc 'fn-owner-index-connection-fault 'stobjs-out nil (w state))
             '(nil nil fn-allocation-turn-slots fn-page-read-pool state))))
(assert-event
 (and (not (fn-di-raw-with-problem 'fn-owner-index-connection-finish
            (cdr (assoc-eq 'fn-owner-index-connection-finish (table-alist 'fn-interfaces (w state)))) (w state)))
      (not (fn-di-raw-with-problem 'fn-owner-index-connection-fault
            (cdr (assoc-eq 'fn-owner-index-connection-fault (table-alist 'fn-interfaces (w state)))) (w state)))))
(assert-event
 (fn-di-raw-with-problem 'fn-owner-index-connection-finish
  '(:class :common-lisp-compliant :raw-with (fn-owner-index-connection-finish-retains-installed-roots)) (w state)))
(assert-event
 (fn-di-raw-with-problem 'fn-owner-index-connection-fault
  '(:class :common-lisp-compliant :raw-with (fn-owner-index-connection-finish-raw-with)) (w state)))
