; Actual prepare/start/abort/finish composition in one pool and MIO provider.
; Installation fields are explicit synthetic fixtures, not runtime authority.
(in-package "ACL2")
(include-book "connection-operation-ticket-tests")
(include-book "index-connection-issuer-tests")
(include-book "../../host/index-connection-start-host")

(defun fn-cost-setup (children fn-allocation-turn-slots fn-mio$c fn-page-read-pool)
 (declare (xargs :stobjs (fn-allocation-turn-slots fn-mio$c fn-page-read-pool) :verify-guards nil))
 (mv-let (fn-mio$c fn-page-read-pool)
  (stobj-let ((fn-index-backing (fn-mio$c-provider fn-mio$c)))
   (fn-index-backing fn-page-read-pool)
   (fn-icr-test-setup children fn-index-backing fn-page-read-pool)
   (mv fn-mio$c fn-page-read-pool))
  (mv-let (word fn-allocation-turn-slots fn-page-read-pool)
   (fn-cott-setup fn-allocation-turn-slots fn-page-read-pool)
   (mv word fn-allocation-turn-slots fn-mio$c fn-page-read-pool))))

(defun fn-cost-case (case fn-allocation-turn-slots fn-mio$c fn-page-read-pool state)
 (declare (xargs :stobjs (fn-allocation-turn-slots fn-mio$c fn-page-read-pool state) :verify-guards nil))
 (mv-let (setup fn-allocation-turn-slots fn-mio$c fn-page-read-pool)
  (fn-cost-setup (not (eq case :absent)) fn-allocation-turn-slots fn-mio$c fn-page-read-pool)
  (let* ((state (f-put-global 'fn-owner '((nil nil nil 42)) state))
         (state (f-put-global 'fn-owner-connection-operation-ticket nil state))
         (state (f-put-global 'fn-owner-connection-operation-installation
                  (and (not (eq case :unavailable))
                   (list :connection-operation-installation 9
                    '(:allocation-epoch-association :runtime :profile :pool 10 1000)
                    :synthetic-source 1000 '(40 0 0 0 1)
                    (if (eq case :body-yield) 700 40) 0 0 20)) state)))
   (mv-let (erp word nonce fn-allocation-turn-slots fn-mio$c fn-page-read-pool state)
    (fn-owner-index-connection-prepare (if (eq case :bad-input) :invalid :reader)
     nil nil nil 0 fn-allocation-turn-slots fn-mio$c fn-page-read-pool state)
    (if (member-eq case '(:unavailable :body-yield :bad-input))
        (mv (and (eq setup :constructed) (not erp) (not nonce)
                 (eq word (case case (:unavailable :unsupported-runtime) (:body-yield :yield) (otherwise :refused)))
                 (not (fn-owner-connection-operation-ticket state))
                 (equal (fn-prp-alloc-active-turns fn-page-read-pool) 0)
                 (equal (fn-prp-alloc-allocated fn-page-read-pool) 30)
                 (equal (fn-prl-nth 2 (fn-owner-page-read-ledger fn-page-read-pool)) 1)
                 (equal (fn-ats-phasesi 0 fn-allocation-turn-slots) 0))
            fn-allocation-turn-slots fn-mio$c fn-page-read-pool state)
     (let* ((prepared (and (eq setup :constructed) (not erp) (eq word :prepared) (equal nonce 0)
                       (equal (fn-ats-phasesi 0 fn-allocation-turn-slots) 3)
                       (equal (fn-prp-alloc-active-turns fn-page-read-pool) 1)
                       (equal (fn-prp-alloc-allocated fn-page-read-pool) 70)))
            (before (fn-owner-page-read-ledger fn-page-read-pool))
            (ticket (fn-owner-connection-operation-ticket state)))
      (mv-let (fault-erp fault-word fn-allocation-turn-slots fn-page-read-pool state)
       (if (eq case :fault)
           (fn-owner-index-connection-fault fn-allocation-turn-slots fn-page-read-pool state)
         (mv nil nil fn-allocation-turn-slots fn-page-read-pool state))
       (declare (ignore fault-erp fault-word))
       (mv-let (erp word token fuel fn-mio$c fn-page-read-pool state)
        (fn-owner-index-connection-start :reader nil nil nil fn-mio$c fn-page-read-pool state)
        (if (eq case :fault)
            (mv (and prepared (not erp) (eq word :recovery-required) (not token)
                     (equal before (fn-owner-page-read-ledger fn-page-read-pool))
                     (equal ticket (fn-owner-connection-operation-ticket state))
                     (equal (fn-prp-alloc-active-turns fn-page-read-pool) 1)
                     (equal (fn-prp-alloc-allocated fn-page-read-pool) 70))
                fn-allocation-turn-slots fn-mio$c fn-page-read-pool state)
         (let ((started (and prepared (not erp)
                         (if (eq case :absent) (and (eq word :refused) (not token))
                           (and (eq word :reserved) (equal token '(:connection-holder 2 1 0)))))))
          (mv-let (aborted left fn-mio$c fn-page-read-pool)
           (if token
               (stobj-let ((fn-index-backing (fn-mio$c-provider fn-mio$c)))
                (aborted left fn-index-backing fn-page-read-pool)
                (fn-icr-abort token fuel fn-index-backing fn-page-read-pool)
                (mv aborted left fn-mio$c fn-page-read-pool))
             (mv :released fuel fn-mio$c fn-page-read-pool))
           (declare (ignore left))
           (mv-let (erp word fn-allocation-turn-slots fn-page-read-pool state)
            (fn-owner-index-connection-finish 0 nonce fn-allocation-turn-slots fn-page-read-pool state)
            (mv (and started (eq aborted :released) (not erp) (eq word :left)
                     (equal (fn-prp-alloc-active-turns fn-page-read-pool) 0)
                     (equal (fn-prp-alloc-allocated fn-page-read-pool) 70)
                     (equal (fn-prl-nth 1 (fn-owner-page-read-ledger fn-page-read-pool)) '(0 0 0 0 2))
                     (equal (fn-prl-nth 2 (fn-owner-page-read-ledger fn-page-read-pool)) 2)
                     (eq (fn-omk-at 1 (fn-owner-connection-operation-ticket state)) :finished))
                fn-allocation-turn-slots fn-mio$c fn-page-read-pool state)))))))))))))

(defun fn-cost-local (case state)
 (declare (xargs :stobjs state :verify-guards nil))
 (with-local-stobj fn-page-read-pool
  (mv-let (ok fn-page-read-pool state)
   (with-local-stobj fn-allocation-turn-slots
    (mv-let (ok fn-allocation-turn-slots fn-page-read-pool state)
     (with-local-stobj fn-mio$c
      (mv-let (ok fn-allocation-turn-slots fn-mio$c fn-page-read-pool state)
       (fn-cost-case case fn-allocation-turn-slots fn-mio$c fn-page-read-pool state)
       (mv ok fn-allocation-turn-slots fn-page-read-pool state)))
     (mv ok fn-page-read-pool state)))
   (mv ok state))))

(make-event (mv-let (ok state) (fn-cost-local :success state)
 (if ok (value '(value-triple :passed-start)) (er soft 'start "success failed"))))
(make-event (mv-let (ok state) (fn-cost-local :absent state)
 (if ok (value '(value-triple :passed-absent)) (er soft 'start "absent failed"))))
(make-event (mv-let (ok state) (fn-cost-local :unavailable state)
 (if ok (value '(value-triple :passed-unavailable)) (er soft 'start "unavailable failed"))))
(make-event (mv-let (ok state) (fn-cost-local :body-yield state)
 (if ok (value '(value-triple :passed-body-yield)) (er soft 'start "body-yield failed"))))
(make-event (mv-let (ok state) (fn-cost-local :bad-input state)
 (if ok (value '(value-triple :passed-bad-input)) (er soft 'start "bad-input failed"))))
(make-event (mv-let (ok state) (fn-cost-local :fault state)
 (if ok (value '(value-triple :passed-faulted-start)) (er soft 'start "faulted-start failed"))))

; Literal public-keystone teeth: confirm the actual return antecedent and all
; receipt fields, then remove the sole antecedent in a no-ticket invocation.
(defun fn-cost-public-witness (preparep fn-allocation-turn-slots fn-mio$c fn-page-read-pool state)
 (declare (xargs :stobjs (fn-allocation-turn-slots fn-mio$c fn-page-read-pool state) :verify-guards nil))
 (mv-let (setup fn-allocation-turn-slots fn-mio$c fn-page-read-pool)
  (fn-cost-setup t fn-allocation-turn-slots fn-mio$c fn-page-read-pool)
  (let* ((state (f-put-global 'fn-owner '((nil nil nil 42)) state))
         (state (f-put-global 'fn-owner-connection-operation-ticket nil state))
         (state (f-put-global 'fn-owner-connection-operation-installation
                  '(:connection-operation-installation 9
                    (:allocation-epoch-association :runtime :profile :pool 10 1000)
                    :synthetic-source 1000 (40 0 0 0 1) 40 0 0 20) state)))
   (mv-let (erp prepared nonce fn-allocation-turn-slots fn-mio$c fn-page-read-pool state)
    (if preparep
        (fn-owner-index-connection-prepare :reader nil nil nil 0 fn-allocation-turn-slots fn-mio$c fn-page-read-pool state)
      (mv nil nil nil fn-allocation-turn-slots fn-mio$c fn-page-read-pool state))
    (declare (ignore erp prepared nonce))
    (mv-let (erp word token fuel fn-mio$c fn-page-read-pool state)
     (fn-owner-index-connection-start :reader nil nil nil fn-mio$c fn-page-read-pool state)
     (declare (ignore fuel))
     (let* ((receipt (stobj-let ((fn-index-backing (fn-mio$c-provider fn-mio$c)))
                     (receipt) (fn-ibp-connection-pending fn-index-backing) receipt))
            (antecedent (eq word :reserved))
            (conclusion (and (equal (fn-omk-at 1 receipt) token)
                             (eq (fn-omk-at 0 receipt) :connection-reservation)
                             (eq (fn-omk-at 6 receipt) :registered))))
      (mv (and (eq setup :constructed) (not erp)
               (if preparep (and antecedent conclusion)
                 (and (not antecedent) (not conclusion) (eq word :unsupported-runtime))))
          fn-allocation-turn-slots fn-mio$c fn-page-read-pool state)))))))

(defun fn-cost-local-witness (preparep state)
 (declare (xargs :stobjs state :verify-guards nil))
 (with-local-stobj fn-page-read-pool
  (mv-let (ok fn-page-read-pool state)
   (with-local-stobj fn-allocation-turn-slots
    (mv-let (ok fn-allocation-turn-slots fn-page-read-pool state)
     (with-local-stobj fn-mio$c
      (mv-let (ok fn-allocation-turn-slots fn-mio$c fn-page-read-pool state)
       (fn-cost-public-witness preparep fn-allocation-turn-slots fn-mio$c fn-page-read-pool state)
       (mv ok fn-allocation-turn-slots fn-page-read-pool state)))
     (mv ok fn-page-read-pool state)))
   (mv ok state))))

(make-event (mv-let (ok state) (fn-cost-local-witness t state)
 (if ok (value '(value-triple :passed-public-positive)) (er soft 'start "public positive failed"))))
(make-event (mv-let (ok state) (fn-cost-local-witness nil state)
 (if ok (value '(value-triple :passed-public-hypothesis-removal)) (er soft 'start "public removal failed"))))

(assert-event (and (eq (getpropc (quote fn-owner-index-connection-prepare) (quote symbol-class) nil (w state)) :common-lisp-compliant) (eq (getpropc (quote fn-owner-index-connection-start) (quote symbol-class) nil (w state)) :common-lisp-compliant)))

(assert-event
 (and (not (fn-di-raw-with-problem 'fn-owner-index-connection-prepare
       (cdr (assoc-eq 'fn-owner-index-connection-prepare (table-alist 'fn-interfaces (w state)))) (w state)))
      (not (fn-di-get :raw-with
       (cdr (assoc-eq 'fn-owner-index-connection-start (table-alist 'fn-interfaces (w state))))))))

(assert-event
 (fn-di-raw-with-problem 'fn-owner-index-connection-prepare
  '(:class :common-lisp-compliant :raw-with (fn-owner-index-connection-prepare-retains-installed-roots)) (w state)))
