(in-package "ACL2")
(include-book "../../books/connection-registry-source-cost")
; Complete literal segment states; actual source constructors are the inputs.
(defthm icrct-literal-reserve-complete
 (let* ((before (update-fn-ich-segment-id 1 (create-fn-ibp-connection-segment)))
        (token '(:connection-holder 2 1 0)) (grant '(40 0 0 0 1))
        (row (list :connection-holder token 42 nil :reserved grant 0))
        (after (list (cons row (make-list 63 :initial-element nil)) 1 1)))
  (and (fn-ibp-connection-segmentp before) (fn-ich-tokenp token)
       (natp 42) grant (equal (fn-omk-at 2 token) (fn-ich-segment-id before))
       (< (fn-ich-active before) 64)
       (equal (fn-ich-reserve token 42 grant before) (list :reserved after))
       (equal (fn-ichc-reserve token 42 grant before)
        (list :reserved after (list nil 7 '((:add (1 0))) '((:constructor :connection-holder-row 7)))))))
 :rule-classes nil)
(defthm icrct-literal-stale-complete
 (let* ((token '(:connection-holder 2 1 0)) (grant '(40 0 0 0 1))
        (row (list :connection-holder token 42 nil :reserved grant 0))
        (before (list (cons row (make-list 63 :initial-element nil)) 1 1)))
  (and (fn-ibp-connection-segmentp before) (fn-ich-tokenp token)
       (equal (fn-ich-reserve token 42 grant before) (list :stale before))
       (equal (fn-ichc-reserve token 42 grant before) (list :stale before (list nil 0 nil nil)))))
 :rule-classes nil)
(defthm icrct-literal-refused-complete
 (let ((before (update-fn-ich-segment-id 1 (create-fn-ibp-connection-segment))))
  (and (fn-ibp-connection-segmentp before) (not (fn-ich-tokenp '(:connection-holder 2 1 64)))
       (equal (fn-ich-reserve '(:connection-holder 2 1 64) 42 '(40 0 0 0 1) before) (list :refused before))
       (equal (fn-ichc-reserve '(:connection-holder 2 1 64) 42 '(40 0 0 0 1) before)
              (list :refused before (list nil 0 nil nil))))) :rule-classes nil)
