(in-package "ACL2")
(include-book "../../books/connection-runtime-arithmetic-objects")
; These descriptors are synthetic source witnesses, never installed authority.
(defun srco-t-install (base domain quantum)
 (list :connection-operation-installation 7 '(runtime pool 1 2 3 4)
       '(source-only-test) domain '(4 4 4 4 1) base 2 3 quantum))
(defun srco-t-actual (i kind family address peer depth)
 (mv-let (word demand fuel body quantum) (fn-cop-evaluate i kind family address peer depth)
  (list word demand fuel body quantum)))
(encapsulate ()
 (local (defun srco-t-model-event (event coordinate)
  (if (fn-srif-domain-p (fn-atsc-at 0 event)
   (fn-atsc-at 0 (fn-atsc-at 1 event))
   (fn-atsc-at 1 (fn-atsc-at 1 event)) coordinate) 0 1)))
 (local (defun srco-t-model-trace (ops coordinate)
  (if (consp ops) (+ (srco-t-model-event (car ops) coordinate)
                     (srco-t-model-trace (cdr ops) coordinate)) 0)))
 ; Literal event and trace positives assert the full source/unit domain.
 (local (assert-event
  (and (fn-copod-operationp '(:floor (4096 8)) 4096)
       (<= 4096 4611686018427387903)
       (equal *fn-srif-coordinate* *fn-srif-coordinate*)
       (fn-srif-domain-p :floor 4096 8 *fn-srif-coordinate*)
       (equal (srco-t-model-event '(:floor (4096 8)) *fn-srif-coordinate*) 0))))
 (local (assert-event
  (let* ((i (srco-t-install 10 1000 8))
         (seen (fn-copc-evaluate i :peer nil nil '(1 2 3) 1)))
   (and (<= (fn-omk-at 4 i) 4611686018427387903)
        (equal *fn-srif-coordinate* *fn-srif-coordinate*)
        (fn-copod-operationsp (fn-atsc-ops seen) (fn-omk-at 4 i))
        (equal (fn-atsc-value seen) '(:derived (4 4 4 4 1) 16 22 8))
        (equal (fn-atsc-value seen) (srco-t-actual i :peer nil nil '(1 2 3) 1))
        (equal (srco-t-model-trace (fn-atsc-ops seen) *fn-srif-coordinate*) 0)))))
 (local (assert-event
  (let* ((i (srco-t-install 10 1000 2))
         (seen (fn-copc-evaluate i :peer nil nil '(1 2 3) 0)))
   (and (<= (fn-omk-at 4 i) 4611686018427387903)
        (equal *fn-srif-coordinate* *fn-srif-coordinate*)
        (fn-copod-operationsp (fn-atsc-ops seen) (fn-omk-at 4 i))
        (equal (fn-atsc-value seen) '(:refused nil 0 0 2))
        (equal (fn-atsc-value seen) (srco-t-actual i :peer nil nil '(1 2 3) 0))
        (equal (srco-t-model-trace (fn-atsc-ops seen) *fn-srif-coordinate*) 0)))))
 ; Scope consistency/removal models, not physical runtime counterexamples.
 (local (assert-event (and
   (not (fn-copod-operationp '(:unknown (0 0)) 1000))
   (<= 1000 4611686018427387903)
   (equal *fn-srif-coordinate* *fn-srif-coordinate*)
   (not (fn-srif-domain-p :unknown 0 0 *fn-srif-coordinate*))
   (not (equal (srco-t-model-event '(:unknown (0 0)) *fn-srif-coordinate*) 0)))))
 (local (assert-event (and
   (fn-copod-operationp '(:add (4611686018427387904 0)) 4611686018427387904)
   (not (<= 4611686018427387904 4611686018427387903))
   (equal *fn-srif-coordinate* *fn-srif-coordinate*)
   (not (fn-srif-domain-p :add 4611686018427387904 0 *fn-srif-coordinate*))
   (not (equal (srco-t-model-event '(:add (4611686018427387904 0)) *fn-srif-coordinate*) 0)))))
 (local (assert-event (and
   (fn-copod-operationp '(:add (0 0)) 1000)
   (<= 1000 4611686018427387903)
   (not (equal :unqualified *fn-srif-coordinate*))
   (not (fn-srif-domain-p :add 0 0 :unqualified))
   (not (equal (srco-t-model-event '(:add (0 0)) :unqualified) 0)))))
)
