(in-package "ACL2")
(include-book "../../books/index-connection-rx-repin")
(defun fn-crxr-setup (children fn-index-backing fn-page-read-pool)
 (declare (xargs :stobjs (fn-index-backing fn-page-read-pool) :guard t))
 (let* ((fn-page-read-pool
          (fn-owner-page-read-keep-ledger
           (fn-prl-build '(1000 1000 5 5 99) '(0 0 0 0 0) 0 '(:legacy) '(100 0 0 0 0))
           fn-page-read-pool))
        (fn-index-backing (update-fn-ibp-pool-capacity 1 fn-index-backing)))
  (if (not children) (mv fn-index-backing fn-page-read-pool)
   (stobj-let ((fn-ibp-node (fn-ibp-registry fn-index-backing)))
    (fn-ibp-node)
    (stobj-let ((fn-ibp-generation-segment
                (fn-ibp-node-children-get 'fn-ibp-generation-segment fn-ibp-node
                                         (create-fn-ibp-generation-segment))))
     (fn-ibp-generation-segment)
     (let ((fn-ibp-generation-segment (update-fn-ibp-gs-id 1 fn-ibp-generation-segment)))
      (mv-let (a fn-ibp-generation-segment)
       (fn-ibp-generation-begin '(:index-generation 9 1 0) :gen-grant fn-ibp-generation-segment)
       (declare (ignore a))
       (mv-let (b fn-ibp-generation-segment)
        (fn-ibp-generation-capture-arena '(:index-generation 9 1 0) 7 22 fn-ibp-generation-segment)
        (declare (ignore b))
        (mv-let (c fn-ibp-generation-segment)
         (fn-ibp-generation-install-publication '(:index-generation 9 1 0)
          (fn-ipub-make 9 :key nil 0 3 2 nil 0 1 nil 0 2 nil 3 :complete :selected-view 7 22)
          fn-ibp-generation-segment)
         (declare (ignore c)) fn-ibp-generation-segment))))
     (stobj-let ((fn-ibp-connection-segment
                 (fn-ibp-node-children-get 'fn-ibp-connection-segment fn-ibp-node
                                          (create-fn-ibp-connection-segment))))
      (fn-ibp-connection-segment)
      (update-fn-ich-segment-id 1 fn-ibp-connection-segment)
      fn-ibp-node))
    (let ((fn-index-backing
           (update-fn-ibp-current
            (list :installed-publication '(:index-generation 9 1 0)
             (fn-ipub-make 9 :key nil 0 3 2 nil 0 1 nil 0 2 nil 3 :complete :selected-view 7 22))
            fn-index-backing)))
     (mv fn-index-backing fn-page-read-pool))))))

; Actual issuer/registry transitions; synthetic capacity/publication fixture.
; The turn91 is a model association seed, not an installed receive issuer.
(defun fn-crxr-chain-v4 (fn-index-backing fn-page-read-pool)
 (declare (xargs :stobjs (fn-index-backing fn-page-read-pool) :guard t :verify-guards nil))
(mv-let (fn-index-backing fn-page-read-pool)
 (fn-crxr-setup t fn-index-backing fn-page-read-pool)
 (declare (ignorable fn-index-backing fn-page-read-pool))
 (mv-let (a old fn-index-backing fn-page-read-pool)
 (fn-icr-reserve 1000000 '(40 0 0 0 1) fn-index-backing fn-page-read-pool)
 (declare (ignorable a old fn-index-backing fn-page-read-pool))
 (mv-let (b l0 fn-index-backing)
 (fn-icr-register old 1 fn-index-backing)
 (declare (ignorable b l0 fn-index-backing))
 (mv-let (c pin l1 fn-index-backing)
 (fn-icr-capture old :current 2 fn-index-backing)
 (declare (ignorable c pin l1 fn-index-backing))
 (mv-let (d l2 fn-index-backing)
 (fn-icr-finish-open 1000000 old 1 fn-index-backing)
 (declare (ignorable d l2 fn-index-backing))
 (mv-let (bound z0 l3 fn-index-backing)
 (fn-ibp-connection-event old :rx-bind 1000000 (fn-crx-open-origin (list :opened 1000000 old) '(:rx-capacity 0 0 4096) 0) 1 fn-index-backing)
 (declare (ignorable bound z0 l3 fn-index-backing))
 (mv-let (borrow z1 l4 fn-index-backing)
 (fn-ibp-connection-event old :acquire 1000000 nil 1 fn-index-backing)
 (declare (ignorable borrow z1 l4 fn-index-backing))
 (mv-let (e new fn-index-backing fn-page-read-pool)
 (fn-icr-reserve 1000000 '(40 0 0 0 1) fn-index-backing fn-page-read-pool)
 (declare (ignorable e new fn-index-backing fn-page-read-pool))
 (mv-let (f l5 fn-index-backing)
 (fn-icr-register new 1 fn-index-backing)
 (declare (ignorable f l5 fn-index-backing))
 (mv-let (g pin2 l6 fn-index-backing)
 (fn-icr-capture new :current 2 fn-index-backing)
 (declare (ignorable g pin2 l6 fn-index-backing))
 (mv-let (joined l7 fn-index-backing fn-page-read-pool)
 (fn-icr-repin-rx-accept 1000000 old new 9 fn-index-backing fn-page-read-pool)
 (declare (ignorable joined l7 fn-index-backing fn-page-read-pool))
 (mv-let (read origin l8 fn-index-backing)
 (fn-ibp-connection-event new :rx-origin 1000000 nil 1 fn-index-backing)
 (declare (ignorable read origin l8 fn-index-backing))
 (mv-let (h refused fn-index-backing fn-page-read-pool)
 (fn-icr-reserve 1000000 '(40 0 0 0 1) fn-index-backing fn-page-read-pool)
 (declare (ignorable h refused fn-index-backing fn-page-read-pool))
 (mv-let (i l9 fn-index-backing)
 (fn-icr-register refused 1 fn-index-backing)
 (declare (ignorable i l9 fn-index-backing))
 (mv-let (j ignored-pin l10 fn-index-backing)
 (fn-icr-capture refused :current 2 fn-index-backing)
 (declare (ignorable j ignored-pin l10 fn-index-backing))
 (mv-let (snapshot-ledger snapshot-pending)
 (mv (fn-owner-page-read-ledger fn-page-read-pool) (fn-ibp-connection-pending fn-index-backing))
 (declare (ignorable snapshot-ledger snapshot-pending))
 (mv-let (stale l11 fn-index-backing fn-page-read-pool)
 (fn-icr-repin-rx-accept 999 new refused 9 fn-index-backing fn-page-read-pool)
 (declare (ignorable stale l11 fn-index-backing fn-page-read-pool))
 (let ((unchanged (and (equal snapshot-ledger (fn-owner-page-read-ledger fn-page-read-pool)) (equal snapshot-pending (fn-ibp-connection-pending fn-index-backing)))))
 (mv-let (aborted l12 fn-index-backing fn-page-read-pool)
 (fn-icr-abort refused 5 fn-index-backing fn-page-read-pool)
 (declare (ignorable aborted l12 fn-index-backing fn-page-read-pool))
 (mv-let (still still-origin l13 fn-index-backing)
 (fn-ibp-connection-event new :rx-origin 1000000 nil 1 fn-index-backing)
 (declare (ignorable still still-origin l13 fn-index-backing))
 (let* ((original (fn-crx-open-origin (list :opened 1000000 old) '(:rx-capacity 0 0 4096) 0))
 (issued (fn-crx-issued original :admitted '(:receiver-turn 91)))
 (next (fn-crx-repin-issued issued 1000000 old new :read-ready-repin-held)))
 (mv (list (and (eq a :reserved) (eq b :registered) (eq c :captured) (eq d :opened)
               (eq bound :associated) (eq borrow :acquired) (eq e :reserved)
               (eq f :registered) (eq g :captured) (eq joined :repinned-held))
           (and (eq read :current) (equal origin (fn-omk-at 1 next)))
           (fn-crx-turn-currentp next 1000000 new '(:receiver-turn 91) '(:rx-capacity 0 0 4096) 0)
           (not (fn-crx-turn-currentp issued 1000000 new '(:receiver-turn 91) '(:rx-capacity 0 0 4096) 0))
           (equal (fn-crx-repin-issued issued 1000000 old new :read-ready-repin-aborted) issued)
           (equal (fn-crx-repin-issued issued 999 old new :read-ready-repin-held) issued)
           (equal (fn-crx-repin-issued issued 1000000 new old :read-ready-repin-held) issued)
           (equal (fn-omk-at 2 next) (fn-omk-at 2 issued))
           (equal original (fn-omk-at 1 issued))
           (and (eq h :reserved) (eq i :registered) (eq j :captured) (eq stale :stale) (eq aborted :released))
           (and (eq still :current) (equal still-origin origin))
           unchanged)
     fn-index-backing fn-page-read-pool)))))))))))))))))))))))
(defun fn-crxr-exec-v4 ()
 (declare (xargs :guard t :verify-guards nil))
 (with-local-stobj fn-index-backing
  (mv-let (result fn-index-backing)
   (with-local-stobj fn-page-read-pool
    (mv-let (result fn-index-backing fn-page-read-pool)
     (fn-crxr-chain-v4 fn-index-backing fn-page-read-pool)
     (mv result fn-index-backing))) result)))
(assert-event (equal (fn-crxr-exec-v4) '(t t t t t t t t t t t t)))
