; Concrete local fixtures, not runtime custody/profile issuers.
(in-package "ACL2")

(include-book "../../books/consumer-remote-visible-buffer")

(include-book "../../books/consumer-reason")
(include-book "../../books/records-attach")

(defun fn-crvp-test-run (s key extent fuel fn-arena fn-octets)
 (declare (xargs :stobjs (fn-arena fn-octets) :guard (natp fuel) :measure (nfix fuel)))
 (if (zp fuel) (mv '(:test-fuel) s fn-octets)
  (mv-let (answer fn-octets) (fn-crvp-step s key extent fn-arena fn-octets)
   (if (eq (fn-cp-nth 0 answer) :yield)
       (fn-crvp-test-run (fn-cp-nth 1 answer) key extent (- fuel 1) fn-arena fn-octets)
    (mv answer s fn-octets)))))

(defun fn-crvp-fixture-1 ()
 (declare (xargs :guard t))
 (with-local-stobj fn-arena
  (mv-let (ok fn-arena)
   (with-local-stobj fn-octets
    (mv-let (ok fn-arena fn-octets)
     (let* ((h (fn-arena-count fn-arena)) (fn-arena (fn-arena-seal-list '(65 66 67) fn-arena)))
      (let* ((wire (fn-record-make 1 2 3 "<m@x>" '(65 66 67) '("a" "closed") "o" "s" "e" 3 0))
             (row (fn-held-plain wire h))
             (article (fn-make-article "<m@x>" h '("a" "closed") '(("a" . 1) ("closed" . 2)) t 0))
             (projection (list :report-input (list :current-article article) '("a") '(("a" . 1))))
             (start (fn-crvp-begin '(key) :visible projection row 4096 0 fn-arena)))
       (mv-let (answer final fn-octets)
        (fn-crvp-test-run (fn-cp-nth 1 start) '(key) 4096 400 fn-arena fn-octets)
        (let* ((bytes (fn-octets-list fn-octets))
               (expected (fn-record-encode-impl (fn-crvp-record row '("a") '(65 66 67))))
               (cursor (fn-cp-cursor-encode (fn-cp-cursor '(1) '(2) '(3) '(4) '(5) 1 1 1 2)))
               (typed (fn-ncr-consumer-reply-decode :poll (fn-ncl-poll-reply-encode :accepted cursor bytes))))
         (mv (and (fn-record-p wire) (eq (car start) :yield) (equal answer '(:encoded))
                  (equal (fn-cp-nth 11 final) (fn-cp-nth 14 final))
                  (equal bytes expected)
                  (equal typed (list :consumer-poll-reply :accepted cursor bytes))
                  (equal (fn-record-groups (fn-record-result-record (fn-record-decode-exact bytes))) '("a"))
                  (equal (fn-record-msgid (fn-record-result-record (fn-record-decode-exact bytes))) "<m@x>")
                  (equal (fn-record-payload (fn-record-result-record (fn-record-decode-exact bytes))) '(65 66 67)))
             fn-arena fn-octets)))))
     (mv ok fn-arena)))
   ok)))

(assert-event (fn-crvp-fixture-1))

(defun fn-crvp-fixture-2 ()
 (declare (xargs :guard t))
 (with-local-stobj fn-arena
  (mv-let (ok fn-arena)
   (with-local-stobj fn-octets
    (mv-let (ok fn-arena fn-octets)
     (let* ((h (fn-arena-count fn-arena)) (fn-arena (fn-arena-seal-list '(65) fn-arena)))
      (let* ((row (fn-record-make 1 2 3 "<m>" h '("a") "o" "s" "e" 1 0))
             (s (fn-crvp-state '(key) :payload row '("a") nil 1 2 1 4096 1 1 0 nil 10 nil))
             (fn-octets (fn-octets-from-list '(9) fn-octets)))
       (mv-let (reference expected) (fn-crvp-reference s '(key) 10 fn-arena '(9))
        (mv-let (answer fn-octets) (fn-crvp-step s '(key) 10 fn-arena fn-octets)
         (mv (and (equal answer reference) (equal (fn-octets-list fn-octets) expected)
                  (equal expected '(9 65))) fn-arena fn-octets)))))
     (mv ok fn-arena)))
   ok)))

(assert-event (fn-crvp-fixture-2))

(defun fn-crvp-fixture-3 ()
 (declare (xargs :guard t))
 (with-local-stobj fn-arena
  (mv-let (ok fn-arena)
   (with-local-stobj fn-octets
    (mv-let (ok fn-arena fn-octets)
     (let* ((h (fn-arena-count fn-arena)) (fn-arena (fn-arena-seal-list '(65) fn-arena)))
      (let* ((row (fn-record-make 1 2 3 "<m>" h '("a") "o" "s" "e" 1 0))
             (s (fn-crvp-state '(key) :payload row '("a") nil 1 2 1 4096 1 1 0 nil 10 nil))
             (fn-octets (fn-octets-from-list '(9) fn-octets)))
       (mv-let (changed fn-octets) (fn-crvp-step s '(changed) 10 fn-arena fn-octets)
        (mv-let (short fn-octets) (fn-crvp-step s '(key) 9 fn-arena fn-octets)
         (mv (and (equal changed '(:refused :consumer-source-changed))
                  (equal short '(:refused :remote-report-extent))
                  (equal (fn-octets-list fn-octets) '(9))) fn-arena fn-octets)))))
     (mv ok fn-arena)))
   ok)))

(assert-event (fn-crvp-fixture-3))

(defun fn-crvp-fixture-4 ()
 (declare (xargs :guard t))
 (with-local-stobj fn-arena
  (mv-let (ok fn-arena)
   (let* ((h (fn-arena-count fn-arena)) (fn-arena (fn-arena-seal-list '(65) fn-arena)))
    (let* ((row (fn-record-make 1 2 3 "<m>" h '("a") "o" "s" "e" 1 0))
           (a (fn-make-article "<other>" h '("a") '(("a" . 1)) t 0))
           (p (list :report-input (list :current-article a) '("a") '(("a" . 1)))))
     (mv (and (equal (fn-crvp-begin '(key) :visible p row 4096 0 fn-arena)
                      '(:refused :remote-visible-source-binding))
              (equal (fn-crvp-begin '(key) :withdrawn p row 4096 0 fn-arena)
                      '(:refused :remote-visible-kind))) fn-arena)))
   ok)))

(assert-event (fn-crvp-fixture-4))

(defun fn-crvp-fixture-5 ()
 (declare (xargs :guard t))
 (with-local-stobj fn-arena
  (mv-let (ok fn-arena)
   (with-local-stobj fn-octets
    (mv-let (ok fn-arena fn-octets)
     (let* ((h (fn-arena-count fn-arena)) (fn-arena (fn-arena-seal-list '(65) fn-arena)))
      (let* ((row (fn-record-make 1 2 3 "<m>" h '("a") "o" "s" "e" 1 0))
             (a (fn-make-article "<m>" h '("a") '(("a" . 1)) t 0))
             (p (list :report-input (list :current-article a) '("a") '(("a" . 1))))
             (start (fn-crvp-begin '(key) :visible p row 1 0 fn-arena))
             (bad (fn-crvp-state '(key) :prepare row '("bad name") '("bad name") 0 0 1 4096 0 0 0 nil nil nil)))
       (mv-let (answer final fn-octets)
        (fn-crvp-test-run (fn-cp-nth 1 start) '(key) 4096 10 fn-arena fn-octets)
        (declare (ignore final))
        (mv (and (equal answer '(:refused :oversize)) (equal (fn-octets-list fn-octets) nil)
                 (equal (fn-crvp-plan bad '(key) 0 4096 fn-arena) '(:refused :remote-visible-group-codec)))
            fn-arena fn-octets))))
     (mv ok fn-arena)))
   ok)))

(assert-event (fn-crvp-fixture-5))
