; Exercise actual private stobj backing across authenticated decode, retirement,
; a smaller successor, and corrupted source. No native scheduling claim.
(in-package "ACL2")
(include-book "../../books/decoded-worker-job")

(defun dwret-input (bytes fn-decoded-job)
  (declare (xargs :stobjs fn-decoded-job :verify-guards nil))
  (stobj-let ((fn-octets (fn-dwj-input fn-decoded-job)))
    (fn-octets)
    (fn-octets-from-list bytes fn-octets)
    fn-decoded-job))

(defun dwret-drive (fuel archive token fn-decoded-job)
  (declare (xargs :stobjs fn-decoded-job :verify-guards nil :measure (nfix fuel)))
  (if (zp fuel) (mv :exhausted fn-decoded-job)
    (mv-let (word effect fn-decoded-job) (fn-dwj-one token fn-decoded-job)
      (cond
       ((member-eq word '(:ready :refused :stale-decoded-worker))
        (mv word fn-decoded-job))
       ((eq word :read)
        (let* ((read (nth 3 effect))
               (bytes (take (nth 5 read) (nthcdr (- (nth 4 read) 100) archive)))
               (fn-decoded-job (dwret-input bytes fn-decoded-job)))
          (mv-let (answer fn-decoded-job)
            (fn-dwj-read-observation token (nth 2 effect) :ok fn-decoded-job)
            (declare (ignore answer))
            (dwret-drive (1- fuel) archive token fn-decoded-job))))
       (t (dwret-drive (1- fuel) archive token fn-decoded-job))))))

(defun dwret-cycle (ledger worker compressed decoded incarnation corruptp cancelp fn-decoded-job)
  (declare (xargs :stobjs fn-decoded-job :verify-guards nil))
  (let* ((message (append '(9 8) compressed '(7)))
         (digest (fn-blake3 message))
         (trailer (fn-bch-pack digest))
         (archive (append message digest))
         (archive (if corruptp (update-nth 0 10 archive) archive))
         (admit (mv-list 3 (fn-pwz-admit ledger
                     (list 7 100 (len message) 102 (len compressed) 0 trailer decoded 0)
                     '(86928 0 0 1 1))))
         (token (nth 1 admit))
         (acquire (mv-list 3 (fn-pwx-acquire (nth 2 admit) worker token))))
    (mv-let (assigned fn-decoded-job)
      (fn-dwj-assign (nth 2 acquire) (nth 1 acquire) token token incarnation fn-decoded-job)
      (mv-let (begun fn-decoded-job) (fn-dwj-begin token fn-decoded-job)
        (mv-let (terminal fn-decoded-job) (dwret-drive 10000 archive token fn-decoded-job)
          (let* ((cancelled (if cancelp
                               (mv-list 3 (fn-pwx-cancel (nth 2 acquire) (nth 1 acquire) token))
                             acquire))
                 (returned (mv-list 3 (fn-pwx-return (nth 2 cancelled) (nth 1 cancelled) token)))
                 (ledger (nth 2 returned)) (worker (nth 1 returned))
                 (outcome (fn-dwj-outcome ledger worker token fn-decoded-job))
                 (first-byte (mv-list 2 (fn-dwj-byte-at ledger worker token 7 100
                              (len message) 102 (len compressed) trailer decoded 0 0 fn-decoded-job)))
                 (last-byte (mv-list 2 (fn-dwj-byte-at ledger worker token 7 100
                              (len message) 102 (len compressed) trailer decoded 0 (1- decoded) fn-decoded-job)))
                 (beyond (mv-list 2 (fn-dwj-byte-at ledger worker token 7 100
                              (len message) 102 (len compressed) trailer decoded 0 decoded fn-decoded-job))))
            (mv-let (retired fn-decoded-job) (fn-dwj-retire ledger worker token fn-decoded-job)
              (let* ((stale (mv-list 2 (fn-dwj-byte-at ledger worker token 7 100
                              (len message) 102 (len compressed) trailer decoded 0 0 fn-decoded-job)))
                     (released (if cancelp
                                   (mv-list 3 (fn-pwx-settle-cancelled ledger worker token))
                                 (mv-list 3 (fn-pwx-release ledger worker token)))))
                (mv (list (car admit) (car acquire) assigned begun terminal outcome
                          first-byte last-byte beyond retired stale (car released))
                    (nth 2 released) (nth 1 released) fn-decoded-job)))))))))

(defun dwret-reuse ()
  (declare (xargs :verify-guards nil))
  (with-local-stobj fn-decoded-job
    (mv-let (answer fn-decoded-job)
      (let* ((fn-decoded-job (fn-dwj-reserve fn-decoded-job))
             (ledger (nth 1 (mv-list 2 (fn-prl-register (fn-prl-make '(200000 0 2 1 20))
                                               7 '(64 0 1 0 0))))))
        (mv-let (a ledger worker fn-decoded-job)
          (dwret-cycle ledger (fn-pxe-new 0) '(115 116 28 177 0 0) 251 47 nil nil fn-decoded-job)
          (mv-let (b ledger worker fn-decoded-job)
            (dwret-cycle ledger worker '(1 1 0 254 255 90) 1 48 nil nil fn-decoded-job)
            (mv-let (c ledger worker fn-decoded-job)
              (dwret-cycle ledger worker '(1 1 0 254 255 89) 1 49 t nil fn-decoded-job)
              (mv-let (d ledger worker fn-decoded-job)
                (dwret-cycle ledger worker '(1 1 0 254 255 88) 1 50 nil t fn-decoded-job)
                (mv-let (e ledger worker fn-decoded-job)
                  (dwret-cycle ledger worker '(1 2 0 253 255 66 67) 2 51 nil nil fn-decoded-job)
                  (declare (ignore ledger worker))
                  (mv (list a b c d e) fn-decoded-job)))))))
      answer)))

(assert-event
 (let* ((r (dwret-reuse)) (a (car r)) (b (cadr r)) (c (caddr r))
        (d (nth 3 r)) (e (nth 4 r)))
   (and (equal (take 6 a) '(:admitted :assigned :decoded-assigned :decoded-started :ready :ready))
        (equal (take 6 b) '(:admitted :assigned :decoded-assigned :decoded-started :ready :ready))
        (equal (nth 6 a) '(:byte 65)) (equal (nth 7 a) '(:byte 65))
        (equal (nth 6 b) '(:byte 90)) (equal (nth 7 b) '(:byte 90))
        (not (equal (car (nth 8 a)) :byte)) (not (equal (car (nth 8 b)) :byte))
        (equal (nth 4 c) :refused)
        (not (equal (car (nth 6 c)) :byte))
        (equal (nth 9 a) :reusable) (equal (nth 9 b) :reusable) (equal (nth 9 c) :reusable)
        (not (equal (car (nth 10 a)) :byte))
        (not (equal (car (nth 10 b)) :byte))
        (not (equal (car (nth 10 c)) :byte))
        (equal (nth 11 a) :released) (equal (nth 11 b) :released) (equal (nth 11 c) :released)
        (equal (nth 4 d) :ready) (equal (nth 5 d) :cancelled)
        (equal (nth 6 d) '(:cancelled nil))
        (equal (nth 9 d) :reusable) (equal (nth 11 d) :released)
        (equal (take 6 e) '(:admitted :assigned :decoded-assigned :decoded-started :ready :ready))
        (equal (nth 6 e) '(:byte 66)) (equal (nth 7 e) '(:byte 67))
        (equal (nth 9 e) :reusable) (equal (nth 11 e) :released))))
