; Seeded unfunded storage-only activation fixture; no native return premise.
(in-package "ACL2")
(include-book "../../books/decoded-worker-return-provider")
(defun fn-dwr-storage-fixture (fn-pww-node)
 (declare (xargs :stobjs fn-pww-node :guard t :verify-guards nil))
 (let* ((token '(:decoded-window 1 7 100 320 120 40 200 99 250 0))
        (source '(:unfunded-source :retained))
        (fn-pww-node
         (stobj-let
          ((fn-pww-carry (fn-pww-children-get 'fn-pww-carry fn-pww-node (create-fn-pww-carry))))
          (fn-pww-carry)
          (let* ((fn-pww-carry (update-fn-pww-token token fn-pww-carry))
                 (fn-pww-carry (update-fn-pww-phase :running fn-pww-carry))
                 (fn-pww-carry (update-fn-pww-borrow-phase :owned fn-pww-carry))
                 (fn-pww-carry (update-fn-pww-root source fn-pww-carry)))
           fn-pww-carry)
          fn-pww-node)))
  (mv-let (cancel left fn-pww-node)
   (fn-dwr-node-transition token 0 0 :cancel 1 fn-pww-node)
   (declare (ignore left))
   (mv-let (returned left fn-pww-node)
    (fn-dwr-node-transition token 0 0 :activation-return 1 fn-pww-node)
    (declare (ignore left))
    (mv-let (stale left fn-pww-node)
     (fn-dwr-node-transition '(:decoded-window 2 7 100 320 120 40 200 99 250 0)
                              0 0 :activation-return 1 fn-pww-node)
     (declare (ignore left))
     (stobj-let
      ((fn-pww-carry (fn-pww-children-get 'fn-pww-carry fn-pww-node (create-fn-pww-carry))))
      (ok)
      (and (eq cancel :cancelled) (eq returned :activation-returned)
           (eq stale :stale-worker)
           (eq (fn-pww-phase fn-pww-carry) :cancelled-returned)
           (eq (fn-pww-borrow-phase fn-pww-carry) :owned)
           (equal (fn-pww-token fn-pww-carry) token)
           (equal (fn-pww-root fn-pww-carry) source))
      (mv ok fn-pww-node)))))))
(defun fn-dwr-local-fixture ()
 (declare (xargs :guard t :verify-guards nil))
 (with-local-stobj fn-pww-node
  (mv-let (ok fn-pww-node) (fn-dwr-storage-fixture fn-pww-node) ok)))
(assert-event (fn-dwr-local-fixture))
