; Generated by tools/docs_check.py --write from docs/*.md and docs/nodes/*.md;
; do not edit (NNT-032).  Every operator invocation the docs quote, reduced
; to the argv after `operator CONFIG' with each placeholder given a sample
; value, is accepted by ACL2's own grammar: `fn-native-operator-run', which
; host/native-operator-host.lisp fn-native-operator-host-run calls for every
; `fn operator CONFIG ...', and `fn-native-operator-mission-run' for
; `mission'.  make check (tools/docs_check.py --check) fails when this file
; is not what the docs say now, so the verdict certified here is the verdict
; for the docs at these bytes.
(in-package "ACL2")
(include-book "../../books/native-operator")
(include-book "../../books/codec-attach")

(defun fn-docs-argv (words)
  (if (consp words)
      (cons (fn-record-string-octets (car words)) (fn-docs-argv (cdr words)))
    nil))

(defun fn-docs-lines (lines)
  (if (consp lines)
      (append (fn-record-string-octets (car lines)) (list 10)
              (fn-docs-lines (cdr lines)))
    nil))

; The smallest configuration an operator following the pages writes.
(defconst *fn-docs-config*
  (fn-docs-lines '("[store]" "path = \"/srv/fn/store\"")))

(defun fn-docs-operator-status (words)
  (fn-native-operator-result-status
   (if (equal (car words) "mission")
       (fn-native-operator-mission-run (fn-record-string-octets "/srv/fn/fn.toml")
                                       (fn-docs-argv words))
     (fn-native-operator-run *fn-docs-config* (fn-docs-argv words)))))

; Rows are (DOC LINE WORD...); the rows whose argv the grammar does not accept.
(defun fn-docs-operator-rejected (rows)
  (if (consp rows)
      (if (equal (fn-docs-operator-status (cddr (car rows))) :accepted)
          (fn-docs-operator-rejected (cdr rows))
        (cons (list (car (car rows)) (cadr (car rows))
                    (fn-docs-operator-status (cddr (car rows))))
              (fn-docs-operator-rejected (cdr rows))))
    nil))

(defconst *fn-docs-operator-argv*
  '(
    ("docs/operator.md" 35 "help")
    ("docs/operator.md" 36 "init" "fn.letters" "fn.test")
    ("docs/operator.md" 38 "status")
    ("docs/operator.md" 39 "recover")
    ("docs/operator.md" 40 "group" "create" "fn.announce")
    ("docs/operator.md" 41 "group" "retire" "fn.announce")
    ("docs/operator.md" 42 "capacity" "1048576")
    ("docs/operator.md" 43 "peer" "add" "peer1" "news.example.invalid" "127.0.0.1" "1119" "fn.*" "fn.*" "127.0.0.1" "true")
    ("docs/operator.md" 44 "peer" "remove" "peer1")
    ("docs/operator.md" 45 "peer" "list")
    ("docs/operator.md" 46 "policy" "set" "path-identity" "news.example.invalid")
    ("docs/operator.md" 47 "run")
    ("docs/operator.md" 155 "init" "--max-transactions" "100000" "--max-article-octets" "20000" "fn.letters")
    ("docs/operator.md" 156 "init" "--profile" "development" "fn.letters")
    ("docs/operator.md" 157 "init" "--profile" "scale" "fn.letters")
    ("docs/operator.md" 187 "store" "upgrade-profile" "--max-transactions" "1000000")
    ("docs/operator.md" 188 "store" "upgrade-profile" "scale")
    ("docs/operator.md" 189 "store" "upgrade-profile")
    ("docs/operator.md" 221 "store" "inspect" "<fn-client.20260922T034404Z.3fd1ce9e@yue.invalid>")
    ("docs/operator.md" 223 "store" "inspect" "<never-posted@fn.example.invalid>")
    ("docs/operator.md" 241 "store" "compact")
    ("docs/operator.md" 321 "obligations")
    ("docs/operator.md" 324 "pins")
    ("docs/operator.md" 417 "health")
    ("docs/operator.md" 592 "bp-boundary" "add" "relay-r1" "r1.example" "dtn://neighbour/" "1119" "carries" "dtn://far-node/")
    ("docs/operator.md" 593 "bp-boundary" "add" "far-node" "far.example" "dtn://far-node/" "1120" "fn.*" "32768" "16")
    ("docs/operator.md" 755 "peer" "add" "peer1" "news.example.invalid" "127.0.0.1" "1119" "fn.*" "fn.*" "source-address" "127.0.0.1" "true")
    ("docs/operator.md" 1099 "principal" "bind" "alice" "9261767a9261767a9261767a9261767a9261767a9261767a9261767a9261767a")
    ("docs/operator.md" 1100 "policy" "set" "posting-policy" "bound-logins")
    ("docs/operator.md" 1164 "store" "needs-upgrade")
    ("docs/operator.md" 1168 "store" "upgrade-profile" "--max-transactions" "1000")
    ("docs/operator.md" 1169 "store" "rollback-check" "/srv/kept/config.json.format-7")
    ("docs/operator.md" 1170 "store" "rollback-check" "--snapshot" "/srv/snapshot/store")))

(assert-event (null (fn-docs-operator-rejected *fn-docs-operator-argv*))
              :msg (msg "The grammar refuses these documented invocations: ~x0"
                        (fn-docs-operator-rejected *fn-docs-operator-argv*)))

; Teeth: the same verdict refuses a documented row with a word dropped, a
; placeholder left unfilled and an unknown verb, so the assertion above is
; not satisfied by a verdict that accepts everything.
(assert-event (equal (fn-docs-operator-status '("peer" "remove")) :usage))
(assert-event (equal (fn-docs-operator-status '("capacity" "N")) :usage))
(assert-event (equal (fn-docs-operator-status '("store" "inspekt")) :usage))
