; Native stobj traces complement the complete ground antecedent/conclusion
; teeth. Calls use the profile-sized arrays and exact-capacity entry buffers.
(in-package "ACL2")
(include-book "extent-cache-storage-fixtures")

(defun xcs5-fill-stage (fn-xce-stage)
  (declare (xargs :stobjs fn-xce-stage :verify-guards nil))
  (let* ((fn-xce-stage (fn-xce-stage-clear fn-xce-stage))
         (fn-xce-stage (fn-xce-stage-resize 35 fn-xce-stage))
         (fn-xce-stage (fn-xce-stage-put 0 1 fn-xce-stage))
         (fn-xce-stage (fn-xce-stage-put 1 2 fn-xce-stage)))
    (fn-xce-stage-put 2 3 fn-xce-stage)))
(defun xcs5-row-length (slot fn-xce)
  (declare (xargs :stobjs fn-xce :guard (and (natp slot) (< slot 8))))
  (stobj-let ((fn-xce-entry (fn-xce-entriesi slot fn-xce))) (n)
    (fn-xce-entry-len fn-xce-entry) n))

(defun xcs5-live-entry-retirement (fn-xcs fn-xcc fn-xce fn-xce-stage fn-ew-span)
  (declare (xargs :stobjs (fn-xcs fn-xcc fn-xce fn-xce-stage fn-ew-span) :verify-guards nil))
  (let* ((fn-xcs (fn-xcs-clear fn-xcs)) (fn-xcc (fn-xcc-clear fn-xcc))
         (fn-xce (fn-xce-drop 0 fn-xce)) (fn-xce-stage (xcs5-fill-stage fn-xce-stage)))
    (mv-let (init fn-xcs fn-xcc) (fn-xc-init-all 1 0 fn-xcs fn-xcc)
      (mv-let (a slot victim fn-xcs fn-xcc fn-xce fn-xce-stage)
        (fn-xc-install-entry-funded *xcs5-entry-ledger* 11 100 3 77 *xcs5-et* fn-xcs fn-xcc fn-xce fn-xce-stage)
        (let ((charged (and (= (xcs5-row-length 0 fn-xce) 35)
                            (<= (xcs5-row-length 0 fn-xce) (fn-xce-cached-charge *xcs5-entry-ledger* (fn-xc-slot-token 0 fn-xcs))))))
          (mv-let (word count found fn-ew-span fn-xcs fn-xcc)
            (fn-xc-entry-span-at 0 11 100 3 100 3 77 1 3 fn-xcs fn-xcc fn-xce fn-ew-span)
            (let ((fn-xce-stage (xcs5-fill-stage fn-xce-stage)))
              (mv-let (b slot2 old fn-xcs fn-xcc fn-xce fn-xce-stage)
                (fn-xc-install-entry-funded *xcs5-entry-ledger* 12 100 3 77 *xcs5-et2* fn-xcs fn-xcc fn-xce fn-xce-stage)
                (let ((released (and (= (fn-xce-stage-len fn-xce-stage) 0) (= (xcs5-row-length 0 fn-xce) 35))))
                  (mv-let (freed retired fn-xcs fn-xce) (fn-xc-free-bytes 0 fn-xcs fn-xce)
                    (let* ((empty (= (xcs5-row-length 0 fn-xce) 0)) (fn-xce-stage (xcs5-fill-stage fn-xce-stage)))
                      (mv-let (c slot3 old3 fn-xcs fn-xcc fn-xce fn-xce-stage)
                        (fn-xc-install-entry-funded *xcs5-entry-ledger* 11 100 3 77 *xcs5-et* fn-xcs fn-xcc fn-xce fn-xce-stage)
                        (mv-let (yielded slot4 retired4 fn-xcs fn-xce) (fn-xc-yield-bytes fn-xcs fn-xcc fn-xce)
                          (mv (and (equal init :initialized) (equal a :installed) (= slot 0) (not victim) charged
                                   (equal word :span) (= count 2) (= found 0)
                                   (= (fn-ew-span-bytesi 0 fn-ew-span) 2) (= (fn-ew-span-bytesi 1 fn-ew-span) 3)
                                   (equal b :replaced) (= slot2 0) (equal old *xcs5-et*) released
                                   (equal freed :freed) (equal retired *xcs5-et2*) empty
                                   (equal c :installed) (= slot3 0) (not old3)
                                   (equal yielded :yielded) (= slot4 0) (equal retired4 *xcs5-et*)
                                   (= (xcs5-row-length 0 fn-xce) 0) (= (fn-xce-stage-len fn-xce-stage) 0))
                              fn-xcs fn-xcc fn-xce fn-xce-stage fn-ew-span))))))))))))))

(assert-event (xcs5-live-entry-retirement fn-xcs fn-xcc fn-xce fn-xce-stage fn-ew-span)
              :stobjs-out '(nil fn-xcs fn-xcc fn-xce fn-xce-stage fn-ew-span))

(defun xcs5-live-decoded-walk (fn-xcs fn-xcc fn-xcw fn-ew-buffer fn-ew-span)
  (declare (xargs :stobjs (fn-xcs fn-xcc fn-xcw fn-ew-buffer fn-ew-span) :verify-guards nil))
  (let* ((fn-xcs (fn-xcs-clear fn-xcs)) (fn-xcc (fn-xcc-clear fn-xcc))
         (fn-ew-buffer (update-fn-ew-bytesi 0 1 fn-ew-buffer))
         (fn-ew-buffer (update-fn-ew-bytesi 1 2 fn-ew-buffer))
         (fn-ew-buffer (update-fn-ew-bytesi 2 3 fn-ew-buffer)))
    (mv-let (init fn-xcs fn-xcc) (fn-xc-init-all 0 2 fn-xcs fn-xcc)
      (mv-let (a first old1 fn-xcs fn-xcc fn-xcw)
        (fn-xc-install-decoded-bytes *xcs5-zt1* *xcs5-z1* fn-xcs fn-xcc fn-xcw fn-ew-buffer)
        (mv-let (b second old2 fn-xcs fn-xcc fn-xcw)
          (fn-xc-install-decoded-bytes *xcs5-zt* *xcs5-z* fn-xcs fn-xcc fn-xcw fn-ew-buffer)
          (mv-let (word count slot fn-ew-span fn-xcs fn-xcc)
            (fn-xc-decoded-span-at 0 *xcs5-z-ledger* 11 100 3 100 3 77 3 0 1 3 fn-xcs fn-xcc fn-xcw fn-ew-span)
            (let* ((hit (and (equal word :span) (= count 2) (= slot 1)
                            (= (fn-ew-span-bytesi 0 fn-ew-span) 2) (= (fn-ew-span-bytesi 1 fn-ew-span) 3)
                            (equal (fn-xcw-plansi 1 fn-xcw) *xcs5-z*)))
                  (tick (fn-xc-tick fn-xcc)) (fn-xcw (update-fn-xcw-plansi 1 nil fn-xcw)))
              (mv-let (miss n s fn-ew-span fn-xcs fn-xcc)
                (fn-xc-decoded-span-at 0 *xcs5-z-ledger* 11 100 3 100 3 77 3 0 1 3 fn-xcs fn-xcc fn-xcw fn-ew-span)
                (mv (and (equal init :initialized) (equal a :installed) (= first 0) (not old1)
                         (equal b :installed) (= second 1) (not old2) hit
                         (equal miss :miss) (= n 0) (not s) (= tick (fn-xc-tick fn-xcc))
                         (= (fn-ew-span-bytesi 0 fn-ew-span) 2) (= (fn-ew-span-bytesi 1 fn-ew-span) 3))
                    fn-xcs fn-xcc fn-xcw fn-ew-buffer fn-ew-span)))))))))

(assert-event (xcs5-live-decoded-walk fn-xcs fn-xcc fn-xcw fn-ew-buffer fn-ew-span)
              :stobjs-out '(nil fn-xcs fn-xcc fn-xcw fn-ew-buffer fn-ew-span))
