; Generated closed teeth; source claims are checked against admitted theorems.
(in-package "ACL2")
(include-book "extent-cache-storage-fixtures")

(xcs5-ground fn-xc-entry-span-at-answers-from-a-matching-slot-positive-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) (and (let* ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst)) (s (mv-nth 2 r)) (n (mv-nth 1 r))) (declare (ignorable r s n)) (equal (mv-nth 0 r) :span)) (let* ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst)) (s (mv-nth 2 r)) (n (mv-nth 1 r))) (declare (ignorable r s n)) (and (natp s) (<= from s) (< s (fn-xc-ne cells)) (fn-xc-slot-matchp s nil 1 file eoff elen 0 0 0 0 trailer 0 slots) (equal (nth s (nth 0 entries)) (fn-xc-entry-key file eoff elen trailer (fn-xc-slot-token s slots))) (equal (len (nth s (nth 1 entries))) (+ elen *fn-frame-trailer-octets*)) (<= eoff poff) (<= (+ poff plen) (+ eoff elen)) (posp n) (<= (+ p n) end) (<= (+ p n) plen) (<= n *fn-ew-span-capacity*)))))

(xcs5-ground fn-xc-entry-span-at-answers-from-a-matching-slot-without-h1-witness ((file 12) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) (and (not (let* ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst)) (s (mv-nth 2 r)) (n (mv-nth 1 r))) (declare (ignorable r s n)) (equal (mv-nth 0 r) :span))) (not (let* ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst)) (s (mv-nth 2 r)) (n (mv-nth 1 r))) (declare (ignorable r s n)) (and (natp s) (<= from s) (< s (fn-xc-ne cells)) (fn-xc-slot-matchp s nil 1 file eoff elen 0 0 0 0 trailer 0 slots) (equal (nth s (nth 0 entries)) (fn-xc-entry-key file eoff elen trailer (fn-xc-slot-token s slots))) (equal (len (nth s (nth 1 entries))) (+ elen *fn-frame-trailer-octets*)) (<= eoff poff) (<= (+ poff plen) (+ eoff elen)) (posp n) (<= (+ p n) end) (<= (+ p n) plen) (<= n *fn-ew-span-capacity*))))))

(xcs5-ground fn-xc-entry-span-at-answers-from-a-matching-slot-mutant-stale-row-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (update-nth 0 (make-list 8 :initial-element nil) (mv-nth 5 (xcs5-entry-build)))) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) (and (let* ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst)) (s (mv-nth 2 r)) (n (mv-nth 1 r))) (declare (ignorable r s n)) (equal (mv-nth 0 (xcs5-entry-stale-row-mutant from file eoff elen poff plen trailer p end slots cells entries dst)) :span)) (not (let* ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst)) (s (mv-nth 2 r)) (n (mv-nth 1 r))) (declare (ignorable r s n)) (equal (mv-nth 0 r) :span))) (not (let* ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst)) (s (mv-nth 2 r)) (n (mv-nth 1 r))) (declare (ignorable r s n)) (and (natp s) (<= from s) (< s (fn-xc-ne cells)) (fn-xc-slot-matchp s nil 1 file eoff elen 0 0 0 0 trailer 0 slots) (equal (nth s (nth 0 entries)) (fn-xc-entry-key file eoff elen trailer (fn-xc-slot-token s slots))) (equal (len (nth s (nth 1 entries))) (+ elen *fn-frame-trailer-octets*)) (<= eoff poff) (<= (+ poff plen) (+ eoff elen)) (posp n) (<= (+ p n) end) (<= (+ p n) plen) (<= n *fn-ew-span-capacity*))))))

(defteeth fn-xc-entry-span-at-answers-from-a-matching-slot :claim (let* ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst)) (s (mv-nth 2 r)) (n (mv-nth 1 r))) (((h1 (equal (mv-nth 0 r) :span))) (and (natp s) (<= from s) (< s (fn-xc-ne cells)) (fn-xc-slot-matchp s nil 1 file eoff elen 0 0 0 0 trailer 0 slots) (equal (nth s (nth 0 entries)) (fn-xc-entry-key file eoff elen trailer (fn-xc-slot-token s slots))) (equal (len (nth s (nth 1 entries))) (+ elen *fn-frame-trailer-octets*)) (<= eoff poff) (<= (+ poff plen) (+ eoff elen)) (posp n) (<= (+ p n) end) (<= (+ p n) plen) (<= n *fn-ew-span-capacity*)))) :subject fn-xc-entry-span-at :witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) :witness-lemma fn-xc-entry-span-at-answers-from-a-matching-slot-positive-witness :breaks ((h1 ((file 12)) :lemma fn-xc-entry-span-at-answers-from-a-matching-slot-without-h1-witness)) :mutations ((stale-row (:hypothesis h1 (equal (mv-nth 0 (xcs5-entry-stale-row-mutant from file eoff elen poff plen trailer p end slots cells entries dst)) :span)) ((entries (update-nth 0 (make-list 8 :initial-element nil) (mv-nth 5 (xcs5-entry-build))))) :fault "mutant omits the stored plan/key check and serves stale backing" :lemma fn-xc-entry-span-at-answers-from-a-matching-slot-mutant-stale-row-witness)))

(xcs5-ground fn-xc-entry-span-at-miss-changes-nothing-positive-witness ((file 12) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) (and (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (not (equal (mv-nth 0 r) :span))) (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (equal r (list :miss 0 nil dst slots cells)))))

(xcs5-ground fn-xc-entry-span-at-miss-changes-nothing-without-h1-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) (and (not (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (not (equal (mv-nth 0 r) :span)))) (not (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (equal r (list :miss 0 nil dst slots cells))))))

(xcs5-ground fn-xc-entry-span-at-miss-changes-nothing-mutant-touch-on-miss-witness ((file 12) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) (and (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (not (equal (mv-nth 0 r) :span))) (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (equal r (list :miss 0 nil dst slots cells))) (not (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (equal (mv-nth 4 r) (mv-nth 1 (fn-xc-touch 0 slots cells)))))))

(defteeth fn-xc-entry-span-at-miss-changes-nothing :claim (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (((h1 (not (equal (mv-nth 0 r) :span)))) (equal r (list :miss 0 nil dst slots cells)))) :subject fn-xc-entry-span-at :witness ((file 12) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) :witness-lemma fn-xc-entry-span-at-miss-changes-nothing-positive-witness :breaks ((h1 ((file 11)) :lemma fn-xc-entry-span-at-miss-changes-nothing-without-h1-witness)) :mutations ((touch-on-miss (:conclusion (equal (mv-nth 4 r) (mv-nth 1 (fn-xc-touch 0 slots cells)))) () :fault "mutant touches slot zero even when every candidate misses" :lemma fn-xc-entry-span-at-miss-changes-nothing-mutant-touch-on-miss-witness)))

(xcs5-ground fn-xc-entry-span-at-is-the-entry-bytes-positive-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) (and (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (natp k)) (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (< k (mv-nth 1 r))) (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (equal (nth k (nth 0 (mv-nth 3 r))) (nth (+ (- poff eoff) p k) (nth (mv-nth 2 r) (nth 1 entries)))))))

(xcs5-ground fn-xc-entry-span-at-is-the-entry-bytes-without-h1-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k -1) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) (and (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (< k (mv-nth 1 r))) (not (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (natp k))) (not (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (equal (nth k (nth 0 (mv-nth 3 r))) (nth (+ (- poff eoff) p k) (nth (mv-nth 2 r) (nth 1 entries))))))))

(xcs5-ground fn-xc-entry-span-at-is-the-entry-bytes-without-h2-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 1) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) (and (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (natp k)) (not (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (< k (mv-nth 1 r)))) (not (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (equal (nth k (nth 0 (mv-nth 3 r))) (nth (+ (- poff eoff) p k) (nth (mv-nth 2 r) (nth 1 entries))))))))

(xcs5-ground fn-xc-entry-span-at-is-the-entry-bytes-mutant-source-off-by-one-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) (and (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (natp k)) (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (< k (mv-nth 1 r))) (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (equal (nth k (nth 0 (mv-nth 3 r))) (nth (+ (- poff eoff) p k) (nth (mv-nth 2 r) (nth 1 entries))))) (not (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (declare (ignorable r)) (equal (nth k (nth 0 (mv-nth 3 r))) (nth (+ 1 p k) (nth (mv-nth 2 r) (nth 1 entries))))))))

(defteeth fn-xc-entry-span-at-is-the-entry-bytes :claim (let ((r (fn-xc-entry-span-at from file eoff elen poff plen trailer p end slots cells entries dst))) (((h1 (natp k)) (h2 (< k (mv-nth 1 r)))) (equal (nth k (nth 0 (mv-nth 3 r))) (nth (+ (- poff eoff) p k) (nth (mv-nth 2 r) (nth 1 entries)))))) :subject fn-xc-entry-span-at :witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) :witness-lemma fn-xc-entry-span-at-is-the-entry-bytes-positive-witness :breaks ((h1 ((k -1)) :lemma fn-xc-entry-span-at-is-the-entry-bytes-without-h1-witness) (h2 ((k 1)) :lemma fn-xc-entry-span-at-is-the-entry-bytes-without-h2-witness)) :mutations ((source-off-by-one (:conclusion (equal (nth k (nth 0 (mv-nth 3 r))) (nth (+ 1 p k) (nth (mv-nth 2 r) (nth 1 entries))))) () :fault "mutant starts the copy one octet too far into the stored row" :lemma fn-xc-entry-span-at-is-the-entry-bytes-mutant-source-off-by-one-witness)))

(defteeth-check)
