; Install pair, table-decision, and profile-init teeth.
(in-package "ACL2")
(include-book "extent-cache-storage-fixtures")

(xcs5-ground fn-xc-install-entry-bytes-installs-the-table-decision-positive-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 1 (fn-xc-init-all 1 0 nil nil))) (cells (mv-nth 2 (fn-xc-init-all 1 0 nil nil))) (entries *xcs5-empty-entries*) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) (and (fn-xc-readyp slots cells) (<= (fn-xc-ne cells) (fn-xce-keys-length entries)) (natp elen) (equal (len stage) (+ elen *fn-frame-trailer-octets*)) (equal (take 5 (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (fn-xc-install-entry file eoff elen trailer token slots cells))))

(xcs5-ground fn-xc-install-entry-bytes-installs-the-table-decision-without-h1-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 1 (fn-xc-init-all 1 0 nil nil))) (cells (quote (0 0 0))) (entries *xcs5-empty-entries*) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) (and (<= (fn-xc-ne cells) (fn-xce-keys-length entries)) (natp elen) (equal (len stage) (+ elen *fn-frame-trailer-octets*)) (not (fn-xc-readyp slots cells)) (not (equal (take 5 (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (fn-xc-install-entry file eoff elen trailer token slots cells)))))

(xcs5-ground fn-xc-install-entry-bytes-installs-the-table-decision-without-h2-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (make-list 9 :initial-element (quote (0 nil 0 0 0 0 0 0 0 0 0 0 0 0)))) (cells (quote (0 9 0))) (entries *xcs5-empty-entries*) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) (and (fn-xc-readyp slots cells) (natp elen) (equal (len stage) (+ elen *fn-frame-trailer-octets*)) (not (<= (fn-xc-ne cells) (fn-xce-keys-length entries))) (not (equal (take 5 (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (fn-xc-install-entry file eoff elen trailer token slots cells)))))

(xcs5-ground fn-xc-install-entry-bytes-installs-the-table-decision-without-h3-witness ((file 11) (eoff 100) (elen -1) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 1 (fn-xc-init-all 1 0 nil nil))) (cells (mv-nth 2 (fn-xc-init-all 1 0 nil nil))) (entries *xcs5-empty-entries*) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage (make-list 31 :initial-element 0))) (and (fn-xc-readyp slots cells) (<= (fn-xc-ne cells) (fn-xce-keys-length entries)) (equal (len stage) (+ elen *fn-frame-trailer-octets*)) (not (natp elen)) (not (equal (take 5 (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (fn-xc-install-entry file eoff elen trailer token slots cells)))))

(xcs5-ground fn-xc-install-entry-bytes-installs-the-table-decision-without-h4-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 1 (fn-xc-init-all 1 0 nil nil))) (cells (mv-nth 2 (fn-xc-init-all 1 0 nil nil))) (entries *xcs5-empty-entries*) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage nil)) (and (fn-xc-readyp slots cells) (<= (fn-xc-ne cells) (fn-xce-keys-length entries)) (natp elen) (not (equal (len stage) (+ elen *fn-frame-trailer-octets*))) (not (equal (take 5 (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (fn-xc-install-entry file eoff elen trailer token slots cells)))))

(xcs5-ground fn-xc-install-entry-bytes-installs-the-table-decision-mutant-omit-table-write-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 1 (fn-xc-init-all 1 0 nil nil))) (cells (mv-nth 2 (fn-xc-init-all 1 0 nil nil))) (entries *xcs5-empty-entries*) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) (and (fn-xc-readyp slots cells) (<= (fn-xc-ne cells) (fn-xce-keys-length entries)) (natp elen) (equal (len stage) (+ elen *fn-frame-trailer-octets*)) (equal (take 5 (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (fn-xc-install-entry file eoff elen trailer token slots cells)) (not (equal (take 5 (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (list :installed 0 nil slots cells)))))

(defteeth fn-xc-install-entry-bytes-installs-the-table-decision :claim (((h1 (fn-xc-readyp slots cells)) (h2 (<= (fn-xc-ne cells) (fn-xce-keys-length entries))) (h3 (natp elen)) (h4 (equal (len stage) (+ elen *fn-frame-trailer-octets*)))) (equal (take 5 (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (fn-xc-install-entry file eoff elen trailer token slots cells))) :subject fn-xc-install-entry-bytes :witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 1 (fn-xc-init-all 1 0 nil nil))) (cells (mv-nth 2 (fn-xc-init-all 1 0 nil nil))) (entries *xcs5-empty-entries*) (ledger *xcs5-entry-ledger*) (token *xcs5-et*) (stage *xcs5-bytes*)) :witness-lemma fn-xc-install-entry-bytes-installs-the-table-decision-positive-witness :breaks ((h1 ((cells (quote (0 0 0)))) :lemma fn-xc-install-entry-bytes-installs-the-table-decision-without-h1-witness) (h2 ((slots (make-list 9 :initial-element (quote (0 nil 0 0 0 0 0 0 0 0 0 0 0 0)))) (cells (quote (0 9 0)))) :lemma fn-xc-install-entry-bytes-installs-the-table-decision-without-h2-witness) (h3 ((elen -1) (stage (make-list 31 :initial-element 0))) :lemma fn-xc-install-entry-bytes-installs-the-table-decision-without-h3-witness) (h4 ((stage nil)) :lemma fn-xc-install-entry-bytes-installs-the-table-decision-without-h4-witness)) :mutations ((omit-table-write (:conclusion (equal (take 5 (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (list :installed 0 nil slots cells))) () :fault "mutant reports installation while retaining the original slot table" :lemma fn-xc-install-entry-bytes-installs-the-table-decision-mutant-omit-table-write-witness)))

(xcs5-ground fn-xc-install-entry-bytes-stores-the-pair-positive-witness ((file 12) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et2*) (stage (update-nth 0 9 *xcs5-bytes*))) (and (let* ((r (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (s (mv-nth 1 r)) (new (mv-nth 5 r))) (declare (ignorable r s new)) (and (fn-xcsp slots) (fn-xccp cells) (member-equal (mv-nth 0 r) (quote (:installed :replaced))))) (let* ((r (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (s (mv-nth 1 r)) (new (mv-nth 5 r))) (declare (ignorable r s new)) (and (equal (nth s (nth 0 new)) (fn-xc-entry-key file eoff elen trailer token)) (equal (nth s (nth 1 new)) stage) (equal (mv-nth 6 r) (nth s (nth 1 entries)))))))

(xcs5-ground fn-xc-install-entry-bytes-stores-the-pair-without-h1-witness ((file 12) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et2*) (stage nil)) (and (not (let* ((r (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (s (mv-nth 1 r)) (new (mv-nth 5 r))) (declare (ignorable r s new)) (and (fn-xcsp slots) (fn-xccp cells) (member-equal (mv-nth 0 r) (quote (:installed :replaced)))))) (not (let* ((r (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (s (mv-nth 1 r)) (new (mv-nth 5 r))) (declare (ignorable r s new)) (and (equal (nth s (nth 0 new)) (fn-xc-entry-key file eoff elen trailer token)) (equal (nth s (nth 1 new)) stage) (equal (mv-nth 6 r) (nth s (nth 1 entries))))))))

(xcs5-ground fn-xc-install-entry-bytes-stores-the-pair-mutant-omit-backing-write-witness ((file 12) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et2*) (stage (update-nth 0 9 *xcs5-bytes*))) (and (let* ((r (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (s (mv-nth 1 r)) (new (mv-nth 5 r))) (declare (ignorable r s new)) (and (fn-xcsp slots) (fn-xccp cells) (member-equal (mv-nth 0 r) (quote (:installed :replaced))))) (let* ((r (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (s (mv-nth 1 r)) (new (mv-nth 5 r))) (declare (ignorable r s new)) (and (equal (nth s (nth 0 new)) (fn-xc-entry-key file eoff elen trailer token)) (equal (nth s (nth 1 new)) stage) (equal (mv-nth 6 r) (nth s (nth 1 entries))))) (not (let* ((r (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (s (mv-nth 1 r)) (new (mv-nth 5 r))) (declare (ignorable r s new)) (equal (mv-nth 5 r) entries)))))

(defteeth fn-xc-install-entry-bytes-stores-the-pair :claim (let* ((r (fn-xc-install-entry-bytes file eoff elen trailer token slots cells entries stage)) (s (mv-nth 1 r)) (new (mv-nth 5 r))) (((h1 (and (fn-xcsp slots) (fn-xccp cells) (member-equal (mv-nth 0 r) (quote (:installed :replaced)))))) (and (equal (nth s (nth 0 new)) (fn-xc-entry-key file eoff elen trailer token)) (equal (nth s (nth 1 new)) stage) (equal (mv-nth 6 r) (nth s (nth 1 entries)))))) :subject fn-xc-install-entry-bytes :witness ((file 12) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries (mv-nth 5 (xcs5-entry-build))) (ledger *xcs5-entry-ledger*) (token *xcs5-et2*) (stage (update-nth 0 9 *xcs5-bytes*))) :witness-lemma fn-xc-install-entry-bytes-stores-the-pair-positive-witness :breaks ((h1 ((stage nil)) :lemma fn-xc-install-entry-bytes-stores-the-pair-without-h1-witness)) :mutations ((omit-backing-write (:conclusion (equal (mv-nth 5 r) entries)) () :fault "mutant updates the table but retains the displaced row backing" :lemma fn-xc-install-entry-bytes-stores-the-pair-mutant-omit-backing-write-witness)))

(xcs5-ground fn-xc-install-decoded-bytes-installs-the-table-decision-positive-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 1 (fn-xc-init-all 0 1 nil nil))) (cells (mv-nth 2 (fn-xc-init-all 0 1 nil nil))) (wins *xcs5-empty-wins*) (ledger *xcs5-z-ledger*) (returned-ledger *xcs5-z-returned*) (worker *xcs5-z-worker*) (token *xcs5-zt*) (z *xcs5-z*) (buf *xcs5-buf*)) (and (fn-xc-readyp slots cells) (<= (fn-xc-nw cells) (fn-xcw-plans-length wins)) (fn-xc-decoded-planp z token) (equal (take 5 (fn-xc-install-decoded-bytes token z slots cells wins buf)) (fn-xc-install-window token slots cells))))

(xcs5-ground fn-xc-install-decoded-bytes-installs-the-table-decision-without-h1-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 1 (fn-xc-init-all 0 1 nil nil))) (cells (quote (0 0 0))) (wins *xcs5-empty-wins*) (ledger *xcs5-z-ledger*) (returned-ledger *xcs5-z-returned*) (worker *xcs5-z-worker*) (token *xcs5-zt*) (z *xcs5-z*) (buf *xcs5-buf*)) (and (<= (fn-xc-nw cells) (fn-xcw-plans-length wins)) (fn-xc-decoded-planp z token) (not (fn-xc-readyp slots cells)) (not (equal (take 5 (fn-xc-install-decoded-bytes token z slots cells wins buf)) (fn-xc-install-window token slots cells)))))

(xcs5-ground fn-xc-install-decoded-bytes-installs-the-table-decision-without-h2-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (make-list 9 :initial-element (quote (0 nil 0 0 0 0 0 0 0 0 0 0 0 0)))) (cells (quote (0 0 9))) (wins *xcs5-empty-wins*) (ledger *xcs5-z-ledger*) (returned-ledger *xcs5-z-returned*) (worker *xcs5-z-worker*) (token *xcs5-zt*) (z *xcs5-z*) (buf *xcs5-buf*)) (and (fn-xc-readyp slots cells) (fn-xc-decoded-planp z token) (not (<= (fn-xc-nw cells) (fn-xcw-plans-length wins))) (not (equal (take 5 (fn-xc-install-decoded-bytes token z slots cells wins buf)) (fn-xc-install-window token slots cells)))))

(xcs5-ground fn-xc-install-decoded-bytes-installs-the-table-decision-without-h3-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 1 (fn-xc-init-all 0 1 nil nil))) (cells (mv-nth 2 (fn-xc-init-all 0 1 nil nil))) (wins *xcs5-empty-wins*) (ledger *xcs5-z-ledger*) (returned-ledger *xcs5-z-returned*) (worker *xcs5-z-worker*) (token *xcs5-zt*) (z nil) (buf *xcs5-buf*)) (and (fn-xc-readyp slots cells) (<= (fn-xc-nw cells) (fn-xcw-plans-length wins)) (not (fn-xc-decoded-planp z token)) (not (equal (take 5 (fn-xc-install-decoded-bytes token z slots cells wins buf)) (fn-xc-install-window token slots cells)))))

(xcs5-ground fn-xc-install-decoded-bytes-installs-the-table-decision-mutant-omit-table-write-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 1 (fn-xc-init-all 0 1 nil nil))) (cells (mv-nth 2 (fn-xc-init-all 0 1 nil nil))) (wins *xcs5-empty-wins*) (ledger *xcs5-z-ledger*) (returned-ledger *xcs5-z-returned*) (worker *xcs5-z-worker*) (token *xcs5-zt*) (z *xcs5-z*) (buf *xcs5-buf*)) (and (fn-xc-readyp slots cells) (<= (fn-xc-nw cells) (fn-xcw-plans-length wins)) (fn-xc-decoded-planp z token) (equal (take 5 (fn-xc-install-decoded-bytes token z slots cells wins buf)) (fn-xc-install-window token slots cells)) (not (equal (take 5 (fn-xc-install-decoded-bytes token z slots cells wins buf)) (list :installed 0 nil slots cells)))))

(defteeth fn-xc-install-decoded-bytes-installs-the-table-decision :claim (((h1 (fn-xc-readyp slots cells)) (h2 (<= (fn-xc-nw cells) (fn-xcw-plans-length wins))) (h3 (fn-xc-decoded-planp z token))) (equal (take 5 (fn-xc-install-decoded-bytes token z slots cells wins buf)) (fn-xc-install-window token slots cells))) :subject fn-xc-install-decoded-bytes :witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 1 (fn-xc-init-all 0 1 nil nil))) (cells (mv-nth 2 (fn-xc-init-all 0 1 nil nil))) (wins *xcs5-empty-wins*) (ledger *xcs5-z-ledger*) (returned-ledger *xcs5-z-returned*) (worker *xcs5-z-worker*) (token *xcs5-zt*) (z *xcs5-z*) (buf *xcs5-buf*)) :witness-lemma fn-xc-install-decoded-bytes-installs-the-table-decision-positive-witness :breaks ((h1 ((cells (quote (0 0 0)))) :lemma fn-xc-install-decoded-bytes-installs-the-table-decision-without-h1-witness) (h2 ((slots (make-list 9 :initial-element (quote (0 nil 0 0 0 0 0 0 0 0 0 0 0 0)))) (cells (quote (0 0 9)))) :lemma fn-xc-install-decoded-bytes-installs-the-table-decision-without-h2-witness) (h3 ((z nil)) :lemma fn-xc-install-decoded-bytes-installs-the-table-decision-without-h3-witness)) :mutations ((omit-table-write (:conclusion (equal (take 5 (fn-xc-install-decoded-bytes token z slots cells wins buf)) (list :installed 0 nil slots cells))) () :fault "mutant reports installation while retaining the original slot table" :lemma fn-xc-install-decoded-bytes-installs-the-table-decision-mutant-omit-table-write-witness)))

(xcs5-ground fn-xc-install-decoded-bytes-stores-the-pair-positive-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-decoded-build))) (cells (mv-nth 4 (xcs5-decoded-build))) (wins (mv-nth 5 (xcs5-decoded-build))) (ledger *xcs5-z-ledger*) (returned-ledger *xcs5-z-returned*) (worker *xcs5-z-worker*) (token *xcs5-zt1*) (z *xcs5-z1*) (buf *xcs5-buf*) (j 0)) (and (let* ((r (fn-xc-install-decoded-bytes token z slots cells wins buf)) (row (fn-xc-row (mv-nth 1 r) (mv-nth 4 r))) (new (mv-nth 5 r))) (declare (ignorable r row new)) (and (fn-xcsp slots) (fn-xccp cells) (member-equal (mv-nth 0 r) (quote (:installed :replaced))))) (let* ((r (fn-xc-install-decoded-bytes token z slots cells wins buf)) (row (fn-xc-row (mv-nth 1 r) (mv-nth 4 r))) (new (mv-nth 5 r))) (declare (ignorable r row new)) (and (equal (fn-xcw-plan row new) z) (implies (and (natp j) (< j (fn-pwz-token-window-length token))) (equal (nth j (nth 0 (fn-xcw-window row new))) (nth j (nth 0 buf))))))))

(xcs5-ground fn-xc-install-decoded-bytes-stores-the-pair-without-h1-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-decoded-build))) (cells (mv-nth 4 (xcs5-decoded-build))) (wins (mv-nth 5 (xcs5-decoded-build))) (ledger *xcs5-z-ledger*) (returned-ledger *xcs5-z-returned*) (worker *xcs5-z-worker*) (token *xcs5-zt1*) (z nil) (buf *xcs5-buf*) (j 0)) (and (not (let* ((r (fn-xc-install-decoded-bytes token z slots cells wins buf)) (row (fn-xc-row (mv-nth 1 r) (mv-nth 4 r))) (new (mv-nth 5 r))) (declare (ignorable r row new)) (and (fn-xcsp slots) (fn-xccp cells) (member-equal (mv-nth 0 r) (quote (:installed :replaced)))))) (not (let* ((r (fn-xc-install-decoded-bytes token z slots cells wins buf)) (row (fn-xc-row (mv-nth 1 r) (mv-nth 4 r))) (new (mv-nth 5 r))) (declare (ignorable r row new)) (and (equal (fn-xcw-plan row new) z) (implies (and (natp j) (< j (fn-pwz-token-window-length token))) (equal (nth j (nth 0 (fn-xcw-window row new))) (nth j (nth 0 buf)))))))))

(xcs5-ground fn-xc-install-decoded-bytes-stores-the-pair-mutant-omit-backing-write-witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-decoded-build))) (cells (mv-nth 4 (xcs5-decoded-build))) (wins (mv-nth 5 (xcs5-decoded-build))) (ledger *xcs5-z-ledger*) (returned-ledger *xcs5-z-returned*) (worker *xcs5-z-worker*) (token *xcs5-zt1*) (z *xcs5-z1*) (buf *xcs5-buf*) (j 0)) (and (let* ((r (fn-xc-install-decoded-bytes token z slots cells wins buf)) (row (fn-xc-row (mv-nth 1 r) (mv-nth 4 r))) (new (mv-nth 5 r))) (declare (ignorable r row new)) (and (fn-xcsp slots) (fn-xccp cells) (member-equal (mv-nth 0 r) (quote (:installed :replaced))))) (let* ((r (fn-xc-install-decoded-bytes token z slots cells wins buf)) (row (fn-xc-row (mv-nth 1 r) (mv-nth 4 r))) (new (mv-nth 5 r))) (declare (ignorable r row new)) (and (equal (fn-xcw-plan row new) z) (implies (and (natp j) (< j (fn-pwz-token-window-length token))) (equal (nth j (nth 0 (fn-xcw-window row new))) (nth j (nth 0 buf)))))) (not (let* ((r (fn-xc-install-decoded-bytes token z slots cells wins buf)) (row (fn-xc-row (mv-nth 1 r) (mv-nth 4 r))) (new (mv-nth 5 r))) (declare (ignorable r row new)) (equal new wins)))))

(defteeth fn-xc-install-decoded-bytes-stores-the-pair :claim (let* ((r (fn-xc-install-decoded-bytes token z slots cells wins buf)) (row (fn-xc-row (mv-nth 1 r) (mv-nth 4 r))) (new (mv-nth 5 r))) (((h1 (and (fn-xcsp slots) (fn-xccp cells) (member-equal (mv-nth 0 r) (quote (:installed :replaced)))))) (and (equal (fn-xcw-plan row new) z) (implies (and (natp j) (< j (fn-pwz-token-window-length token))) (equal (nth j (nth 0 (fn-xcw-window row new))) (nth j (nth 0 buf))))))) :subject fn-xc-install-decoded-bytes :witness ((file 11) (eoff 100) (elen 3) (poff 100) (plen 3) (compressed 3) (trailer 77) (decoded 3) (dict-id 0) (p 1) (end 2) (k 0) (i 0) (dst *xcs5-dst*) (from 0) (slots (mv-nth 3 (xcs5-decoded-build))) (cells (mv-nth 4 (xcs5-decoded-build))) (wins (mv-nth 5 (xcs5-decoded-build))) (ledger *xcs5-z-ledger*) (returned-ledger *xcs5-z-returned*) (worker *xcs5-z-worker*) (token *xcs5-zt1*) (z *xcs5-z1*) (buf *xcs5-buf*) (j 0)) :witness-lemma fn-xc-install-decoded-bytes-stores-the-pair-positive-witness :breaks ((h1 ((z nil)) :lemma fn-xc-install-decoded-bytes-stores-the-pair-without-h1-witness)) :mutations ((omit-backing-write (:conclusion (equal new wins)) () :fault "mutant updates the table but retains the displaced row backing" :lemma fn-xc-install-decoded-bytes-stores-the-pair-mutant-omit-backing-write-witness)))

(xcs5-ground fn-xc-init-all-readies-all-rows-positive-witness ((ne 1) (nw 1) (slots nil) (cells nil) (entries *xcs5-empty-entries*) (wins *xcs5-empty-wins*)) (and (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (and (fn-xcsp slots) (fn-xccp cells) (equal (fn-xcs-count slots) 0) (equal (fn-xcc-count cells) 0))) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (natp ne)) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (natp nw)) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (<= ne (fn-profile-limit :extent-cache-entries))) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (<= nw (fn-profile-limit :extent-cache-windows))) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (and (equal (mv-nth 0 r) :initialized) (fn-xcsp (mv-nth 1 r)) (fn-xccp (mv-nth 2 r)) (fn-xc-readyp (mv-nth 1 r) (mv-nth 2 r)) (equal (fn-xc-ne (mv-nth 2 r)) ne) (equal (fn-xc-nw (mv-nth 2 r)) nw) (<= ne (fn-xce-keys-length entries)) (<= nw (fn-xcw-plans-length wins))))))

(xcs5-ground fn-xc-init-all-readies-all-rows-without-h1-witness ((ne 1) (nw 1) (slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build))) (entries *xcs5-empty-entries*) (wins *xcs5-empty-wins*)) (and (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (natp ne)) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (natp nw)) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (<= ne (fn-profile-limit :extent-cache-entries))) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (<= nw (fn-profile-limit :extent-cache-windows))) (not (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (and (fn-xcsp slots) (fn-xccp cells) (equal (fn-xcs-count slots) 0) (equal (fn-xcc-count cells) 0)))) (not (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (and (equal (mv-nth 0 r) :initialized) (fn-xcsp (mv-nth 1 r)) (fn-xccp (mv-nth 2 r)) (fn-xc-readyp (mv-nth 1 r) (mv-nth 2 r)) (equal (fn-xc-ne (mv-nth 2 r)) ne) (equal (fn-xc-nw (mv-nth 2 r)) nw) (<= ne (fn-xce-keys-length entries)) (<= nw (fn-xcw-plans-length wins)))))))

(xcs5-ground fn-xc-init-all-readies-all-rows-without-h2-witness ((ne -1) (nw 1) (slots nil) (cells nil) (entries *xcs5-empty-entries*) (wins *xcs5-empty-wins*)) (and (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (and (fn-xcsp slots) (fn-xccp cells) (equal (fn-xcs-count slots) 0) (equal (fn-xcc-count cells) 0))) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (natp nw)) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (<= ne (fn-profile-limit :extent-cache-entries))) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (<= nw (fn-profile-limit :extent-cache-windows))) (not (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (natp ne))) (not (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (and (equal (mv-nth 0 r) :initialized) (fn-xcsp (mv-nth 1 r)) (fn-xccp (mv-nth 2 r)) (fn-xc-readyp (mv-nth 1 r) (mv-nth 2 r)) (equal (fn-xc-ne (mv-nth 2 r)) ne) (equal (fn-xc-nw (mv-nth 2 r)) nw) (<= ne (fn-xce-keys-length entries)) (<= nw (fn-xcw-plans-length wins)))))))

(xcs5-ground fn-xc-init-all-readies-all-rows-without-h3-witness ((ne 1) (nw -1) (slots nil) (cells nil) (entries *xcs5-empty-entries*) (wins *xcs5-empty-wins*)) (and (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (and (fn-xcsp slots) (fn-xccp cells) (equal (fn-xcs-count slots) 0) (equal (fn-xcc-count cells) 0))) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (natp ne)) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (<= ne (fn-profile-limit :extent-cache-entries))) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (<= nw (fn-profile-limit :extent-cache-windows))) (not (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (natp nw))) (not (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (and (equal (mv-nth 0 r) :initialized) (fn-xcsp (mv-nth 1 r)) (fn-xccp (mv-nth 2 r)) (fn-xc-readyp (mv-nth 1 r) (mv-nth 2 r)) (equal (fn-xc-ne (mv-nth 2 r)) ne) (equal (fn-xc-nw (mv-nth 2 r)) nw) (<= ne (fn-xce-keys-length entries)) (<= nw (fn-xcw-plans-length wins)))))))

(xcs5-ground fn-xc-init-all-readies-all-rows-without-h4-witness ((ne 9) (nw 1) (slots nil) (cells nil) (entries *xcs5-empty-entries*) (wins *xcs5-empty-wins*)) (and (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (and (fn-xcsp slots) (fn-xccp cells) (equal (fn-xcs-count slots) 0) (equal (fn-xcc-count cells) 0))) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (natp ne)) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (natp nw)) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (<= nw (fn-profile-limit :extent-cache-windows))) (not (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (<= ne (fn-profile-limit :extent-cache-entries)))) (not (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (and (equal (mv-nth 0 r) :initialized) (fn-xcsp (mv-nth 1 r)) (fn-xccp (mv-nth 2 r)) (fn-xc-readyp (mv-nth 1 r) (mv-nth 2 r)) (equal (fn-xc-ne (mv-nth 2 r)) ne) (equal (fn-xc-nw (mv-nth 2 r)) nw) (<= ne (fn-xce-keys-length entries)) (<= nw (fn-xcw-plans-length wins)))))))

(xcs5-ground fn-xc-init-all-readies-all-rows-without-h5-witness ((ne 1) (nw 9) (slots nil) (cells nil) (entries *xcs5-empty-entries*) (wins *xcs5-empty-wins*)) (and (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (and (fn-xcsp slots) (fn-xccp cells) (equal (fn-xcs-count slots) 0) (equal (fn-xcc-count cells) 0))) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (natp ne)) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (natp nw)) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (<= ne (fn-profile-limit :extent-cache-entries))) (not (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (<= nw (fn-profile-limit :extent-cache-windows)))) (not (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (and (equal (mv-nth 0 r) :initialized) (fn-xcsp (mv-nth 1 r)) (fn-xccp (mv-nth 2 r)) (fn-xc-readyp (mv-nth 1 r) (mv-nth 2 r)) (equal (fn-xc-ne (mv-nth 2 r)) ne) (equal (fn-xc-nw (mv-nth 2 r)) nw) (<= ne (fn-xce-keys-length entries)) (<= nw (fn-xcw-plans-length wins)))))))

(xcs5-ground fn-xc-init-all-readies-all-rows-mutant-omit-init-witness ((ne 1) (nw 1) (slots nil) (cells nil) (entries *xcs5-empty-entries*) (wins *xcs5-empty-wins*)) (and (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (and (fn-xcsp slots) (fn-xccp cells) (equal (fn-xcs-count slots) 0) (equal (fn-xcc-count cells) 0))) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (natp ne)) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (natp nw)) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (<= ne (fn-profile-limit :extent-cache-entries))) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (<= nw (fn-profile-limit :extent-cache-windows))) (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (and (equal (mv-nth 0 r) :initialized) (fn-xcsp (mv-nth 1 r)) (fn-xccp (mv-nth 2 r)) (fn-xc-readyp (mv-nth 1 r) (mv-nth 2 r)) (equal (fn-xc-ne (mv-nth 2 r)) ne) (equal (fn-xc-nw (mv-nth 2 r)) nw) (<= ne (fn-xce-keys-length entries)) (<= nw (fn-xcw-plans-length wins)))) (not (let ((r (fn-xc-init-all ne nw slots cells))) (declare (ignorable r)) (equal (mv-nth 1 r) slots)))))

(defteeth fn-xc-init-all-readies-all-rows :claim (let ((r (fn-xc-init-all ne nw slots cells))) (((h1 (and (fn-xcsp slots) (fn-xccp cells) (equal (fn-xcs-count slots) 0) (equal (fn-xcc-count cells) 0))) (h2 (natp ne)) (h3 (natp nw)) (h4 (<= ne (fn-profile-limit :extent-cache-entries))) (h5 (<= nw (fn-profile-limit :extent-cache-windows)))) (and (equal (mv-nth 0 r) :initialized) (fn-xcsp (mv-nth 1 r)) (fn-xccp (mv-nth 2 r)) (fn-xc-readyp (mv-nth 1 r) (mv-nth 2 r)) (equal (fn-xc-ne (mv-nth 2 r)) ne) (equal (fn-xc-nw (mv-nth 2 r)) nw) (<= ne (fn-xce-keys-length entries)) (<= nw (fn-xcw-plans-length wins))))) :subject fn-xc-init-all :witness ((ne 1) (nw 1) (slots nil) (cells nil) (entries *xcs5-empty-entries*) (wins *xcs5-empty-wins*)) :witness-lemma fn-xc-init-all-readies-all-rows-positive-witness :breaks ((h1 ((slots (mv-nth 3 (xcs5-entry-build))) (cells (mv-nth 4 (xcs5-entry-build)))) :lemma fn-xc-init-all-readies-all-rows-without-h1-witness) (h2 ((ne -1)) :lemma fn-xc-init-all-readies-all-rows-without-h2-witness) (h3 ((nw -1)) :lemma fn-xc-init-all-readies-all-rows-without-h3-witness) (h4 ((ne 9)) :lemma fn-xc-init-all-readies-all-rows-without-h4-witness) (h5 ((nw 9)) :lemma fn-xc-init-all-readies-all-rows-without-h5-witness)) :mutations ((omit-init (:conclusion (equal (mv-nth 1 r) slots)) () :fault "mutant reports initialization without allocating the slot rows" :lemma fn-xc-init-all-readies-all-rows-mutant-omit-init-witness)))

(xcs5-ground fn-xc-init-all-refuses-more-entries-than-rows-positive-witness ((ne 9) (nw 0) (slots nil) (cells nil)) (and (natp ne) (< (fn-profile-limit :extent-cache-entries) ne) (equal (fn-xc-init-all ne nw slots cells) (list :refused-entry-rows slots cells))))

(xcs5-ground fn-xc-init-all-refuses-more-entries-than-rows-without-h1-witness ((ne (/ 19 2)) (nw 0) (slots nil) (cells nil)) (and (< (fn-profile-limit :extent-cache-entries) ne) (not (natp ne)) (not (equal (fn-xc-init-all ne nw slots cells) (list :refused-entry-rows slots cells)))))

(xcs5-ground fn-xc-init-all-refuses-more-entries-than-rows-without-h2-witness ((ne 8) (nw 0) (slots nil) (cells nil)) (and (natp ne) (not (< (fn-profile-limit :extent-cache-entries) ne)) (not (equal (fn-xc-init-all ne nw slots cells) (list :refused-entry-rows slots cells)))))

(xcs5-ground fn-xc-init-all-refuses-more-entries-than-rows-mutant-truncate-profile-rows-witness ((ne 9) (nw 0) (slots nil) (cells nil)) (and (natp ne) (< (fn-profile-limit :extent-cache-entries) ne) (equal (fn-xc-init-all ne nw slots cells) (list :refused-entry-rows slots cells)) (not (equal (mv-nth 0 (fn-xc-init-all ne nw slots cells)) :initialized))))

(defteeth fn-xc-init-all-refuses-more-entries-than-rows :claim (((h1 (natp ne)) (h2 (< (fn-profile-limit :extent-cache-entries) ne))) (equal (fn-xc-init-all ne nw slots cells) (list :refused-entry-rows slots cells))) :subject fn-xc-init-all :witness ((ne 9) (nw 0) (slots nil) (cells nil)) :witness-lemma fn-xc-init-all-refuses-more-entries-than-rows-positive-witness :breaks ((h1 ((ne (/ 19 2))) :lemma fn-xc-init-all-refuses-more-entries-than-rows-without-h1-witness) (h2 ((ne 8)) :lemma fn-xc-init-all-refuses-more-entries-than-rows-without-h2-witness)) :mutations ((truncate-profile-rows (:conclusion (equal (mv-nth 0 (fn-xc-init-all ne nw slots cells)) :initialized)) () :fault "mutant silently truncates the requested row count and reports initialization" :lemma fn-xc-init-all-refuses-more-entries-than-rows-mutant-truncate-profile-rows-witness)))

(xcs5-ground fn-xc-init-all-refuses-more-windows-than-rows-positive-witness ((ne 0) (nw 9) (slots nil) (cells nil)) (and (not (and (natp ne) (< (fn-profile-limit :extent-cache-entries) ne))) (natp nw) (< (fn-profile-limit :extent-cache-windows) nw) (equal (fn-xc-init-all ne nw slots cells) (list :refused-window-rows slots cells))))

(xcs5-ground fn-xc-init-all-refuses-more-windows-than-rows-without-h1-witness ((ne 9) (nw 9) (slots nil) (cells nil)) (and (natp nw) (< (fn-profile-limit :extent-cache-windows) nw) (not (not (and (natp ne) (< (fn-profile-limit :extent-cache-entries) ne)))) (not (equal (fn-xc-init-all ne nw slots cells) (list :refused-window-rows slots cells)))))

(xcs5-ground fn-xc-init-all-refuses-more-windows-than-rows-without-h2-witness ((ne 0) (nw (/ 19 2)) (slots nil) (cells nil)) (and (not (and (natp ne) (< (fn-profile-limit :extent-cache-entries) ne))) (< (fn-profile-limit :extent-cache-windows) nw) (not (natp nw)) (not (equal (fn-xc-init-all ne nw slots cells) (list :refused-window-rows slots cells)))))

(xcs5-ground fn-xc-init-all-refuses-more-windows-than-rows-without-h3-witness ((ne 0) (nw 8) (slots nil) (cells nil)) (and (not (and (natp ne) (< (fn-profile-limit :extent-cache-entries) ne))) (natp nw) (not (< (fn-profile-limit :extent-cache-windows) nw)) (not (equal (fn-xc-init-all ne nw slots cells) (list :refused-window-rows slots cells)))))

(xcs5-ground fn-xc-init-all-refuses-more-windows-than-rows-mutant-truncate-profile-rows-witness ((ne 0) (nw 9) (slots nil) (cells nil)) (and (not (and (natp ne) (< (fn-profile-limit :extent-cache-entries) ne))) (natp nw) (< (fn-profile-limit :extent-cache-windows) nw) (equal (fn-xc-init-all ne nw slots cells) (list :refused-window-rows slots cells)) (not (equal (mv-nth 0 (fn-xc-init-all ne nw slots cells)) :initialized))))

(defteeth fn-xc-init-all-refuses-more-windows-than-rows :claim (((h1 (not (and (natp ne) (< (fn-profile-limit :extent-cache-entries) ne)))) (h2 (natp nw)) (h3 (< (fn-profile-limit :extent-cache-windows) nw))) (equal (fn-xc-init-all ne nw slots cells) (list :refused-window-rows slots cells))) :subject fn-xc-init-all :witness ((ne 0) (nw 9) (slots nil) (cells nil)) :witness-lemma fn-xc-init-all-refuses-more-windows-than-rows-positive-witness :breaks ((h1 ((ne 9)) :lemma fn-xc-init-all-refuses-more-windows-than-rows-without-h1-witness) (h2 ((nw (/ 19 2))) :lemma fn-xc-init-all-refuses-more-windows-than-rows-without-h2-witness) (h3 ((nw 8)) :lemma fn-xc-init-all-refuses-more-windows-than-rows-without-h3-witness)) :mutations ((truncate-profile-rows (:conclusion (equal (mv-nth 0 (fn-xc-init-all ne nw slots cells)) :initialized)) () :fault "mutant silently truncates the requested row count and reports initialization" :lemma fn-xc-init-all-refuses-more-windows-than-rows-mutant-truncate-profile-rows-witness)))

(defteeth-check)
