(in-package "ACL2")
(include-book "../../books/extent-window-stream-refinement")

(defthm ewsrt-block-positive
  (let ((source-block '(1 2 3)) (input '(1 2 3)) (count 3))
    (and (fn-b3-octet-listp source-block) (equal input source-block)
         (equal count (len source-block))
         (equal (fn-b3x-words 16 0 count nil 0 0 input) (fn-b3-words 16 source-block))))
  :rule-classes nil)
(defthm ewsrt-block-source-removal
  (let ((source-block '(1 2 3)) (input '(1 2 4)) (count 3))
    (and (fn-b3-octet-listp source-block) (not (equal input source-block))
         (equal count (len source-block))
         (not (equal (fn-b3x-words 16 0 count nil 0 0 input) (fn-b3-words 16 source-block)))))
  :rule-classes nil)

(defun-nx ewsrt-scan ()
  (let ((begin (fn-ews-begin 7 100 3 100 3 0 23 47 59 0 (create-pgs-digest-state))))
    (fn-ews-tick (car begin) (cadr begin))))

; Full antecedent/conclusion, including prior-window implication.
(defthm ewsrt-actual-source-window-positive
  (let* ((ready (ewsrt-scan)) (s (nth 1 ready)) (cursor (nth 2 ready))
         (buffer (create-fn-ew-buffer)) (j 1) (msg '(1 2 3)) (input '(1 2 3))
         (effect (fn-ews-effect s cursor)))
    (and (natp j) (natp (nth 4 s)) (natp (nth 5 s)) (natp (nth 7 s))
         (equal (nth 0 s) :scan) (< j (nth 5 s))
         (< (+ (nth 4 s) j) (+ (nth 7 s) (fn-ewp-demand s)))
         (fn-ews-effect s cursor) (equal effect (fn-ews-effect s cursor))
         (equal :ok :ok) (equal (fn-octets-len input) (fn-ewp-demand s))
         (equal input (fn-shr-win (nth 7 s) (fn-ewp-demand s) msg))
         (implies (< (+ (nth 4 s) j) (nth 7 s))
                  (equal (nth j (nth 0 buffer)) (nth (+ (nth 4 s) j) msg)))
         (equal (nth j (nth 0 (nth 3 (fn-ews-read effect :ok s input cursor buffer))))
                (nth (+ (nth 4 s) j) msg))))
  :rule-classes nil)
(defthm ewsrt-actual-source-window-source-removal
  (let* ((ready (ewsrt-scan)) (s (nth 1 ready)) (cursor (nth 2 ready))
         (buffer (create-fn-ew-buffer)) (j 1) (msg '(1 7 3)) (input '(1 2 3))
         (effect (fn-ews-effect s cursor)))
    (and (natp j) (natp (nth 4 s)) (natp (nth 5 s)) (natp (nth 7 s))
         (equal (nth 0 s) :scan) (< j (nth 5 s))
         (< (+ (nth 4 s) j) (+ (nth 7 s) (fn-ewp-demand s)))
         (fn-ews-effect s cursor) (equal effect (fn-ews-effect s cursor))
         (equal :ok :ok) (equal (fn-octets-len input) (fn-ewp-demand s))
         (not (equal input (fn-shr-win (nth 7 s) (fn-ewp-demand s) msg)))
         (implies (< (+ (nth 4 s) j) (nth 7 s))
                  (equal (nth j (nth 0 buffer)) (nth (+ (nth 4 s) j) msg)))
         (not (equal (nth j (nth 0 (nth 3 (fn-ews-read effect :ok s input cursor buffer))))
                     (nth (+ (nth 4 s) j) msg)))))
  :rule-classes nil)
