(in-package "ACL2")
(include-book "../../books/resource-syncer-pipeline")
(include-book "must-fail-checked")
(assert-event
 (and (equal (fn-ros-pipeline-partition 2) '((:barrier :append) 0))
      (equal (fn-ros-pipeline-partition 7) '((:barrier :append) 5))
      (not (fn-ros-pipeline-partition 1))
      (equal (fn-ocp-extra-io-workers) 1)))
(make-event
 (mv-let (word fn-resource-ledger)
   (fn-ros-install-pipeline-role :append 2 1048576 fn-resource-ledger)
   (if (and (equal word :installed) (fn-ros-drainedp fn-resource-ledger))
       (mv nil '(value-triple :append-role-installed) state fn-resource-ledger)
     (mv t nil state fn-resource-ledger))))
(make-event
 (mv-let (word token fn-resource-ledger)
   (fn-ros-pipeline-issue :append 7 fn-resource-ledger)
   (if (and (equal word :drawn) (equal token '(:append (:resource :owner 2 1)))
            (not (fn-ros-drainedp fn-resource-ledger)))
       (mv nil '(value-triple :append-role-drawn) state fn-resource-ledger)
     (mv t nil state fn-resource-ledger))))
(make-event
 (let ((before (fn-rl-bank fn-resource-ledger)))
   (mv-let (word fn-resource-ledger)
     (fn-ros-pipeline-physical :append '(:barrier (:resource :owner 2 1)) :terminal fn-resource-ledger)
     (if (and (equal word :stale) (equal before (fn-rl-bank fn-resource-ledger)))
         (mv nil '(value-triple :cross-role-receipt-keeps-custody) state fn-resource-ledger)
       (mv t nil state fn-resource-ledger)))))
(make-event
 (mv-let (word fn-resource-ledger)
   (fn-ros-pipeline-outcome :append '(:append (:resource :owner 2 1)) 7 fn-resource-ledger)
   (if (and (equal word :pending) (not (fn-ros-drainedp fn-resource-ledger)))
       (mv nil '(value-triple :operation-alone-keeps-custody) state fn-resource-ledger)
     (mv t nil state fn-resource-ledger))))
(make-event
 (mv-let (word fn-resource-ledger)
   (fn-ros-pipeline-physical :append '(:append (:resource :owner 2 1)) :terminal fn-resource-ledger)
   (if (and (equal word :settled) (fn-ros-drainedp fn-resource-ledger))
       (mv nil '(value-triple :both-append-receipts-settle) state fn-resource-ledger)
     (mv t nil state fn-resource-ledger))))
(must-fail-checked (assert-event (fn-ros-pipeline-partition 1)))
(value-triple :role-custody-witnesses-passed)
