(in-package "ACL2")
(include-book "../../books/group-number-source-reader-refinement")
(include-book "group-number-source-lookup-tests")
(defun fn-tgnr-run (fuel c)
 (declare (xargs :guard (natp fuel) :measure (nfix fuel)))
 (if (or (zp fuel) (not (fn-gns-number-cursorp c))
         (member-eq (fn-gns-at 0 c) '(:done :refused))) c
   (fn-tgnr-run (1- fuel) (fn-gns-number-step c))))
(defconst *tgnr-cat* (list (fn-cat-assign *tgnq-h* nil)))
(defconst *tgnr-root* (fn-gns-group-value-root
 (fn-gns-group-get "a" 0 0 (fn-gns-at 1 (fn-gns-stage-result *tgnq-c*)))))
(defconst *tgnr-c* (fn-tgnr-run 8 (fn-gns-number-begin 1 *tgnr-root* 1)))
; Actual stage->bounded reader reachable positive, including ordinal0.
(assert-event (and (fn-gns-number-cursorp *tgnr-c*)
 (eq (fn-gns-at 0 *tgnr-c*) :done) (equal (fn-gns-at 3 *tgnr-c*) (len *tgnr-cat*))
 (equal (fn-gnix-get (fn-gns-at 1 *tgnr-c*) (fn-gns-at 2 *tgnr-c*))
        (fn-gns-ordinal-option (fn-cat-number-seq "a" 1 *tgnr-cat* 0)))
 (equal (fn-gns-number-result *tgnr-c*)
        (list :ordinal (fn-cat-number-seq "a" 1 *tgnr-cat* 0)))
 (equal (fn-gns-number-result *tgnr-c*) '(:ordinal 0))))
; Reachable hole carries exact catalog absence, not malformed option0.
(assert-event (let ((c (fn-tgnr-run 8 (fn-gns-number-begin 2 *tgnr-root* 1))))
 (and (fn-gns-number-cursorp c) (eq (fn-gns-at 0 c) :done)
      (equal (fn-gns-at 3 c) (len *tgnr-cat*))
      (equal (fn-gnix-get (fn-gns-at 1 c) (fn-gns-at 2 c))
             (fn-gns-ordinal-option (fn-cat-number-seq "a" 2 *tgnr-cat* 0)))
      (not (fn-cat-number-seq "a" 2 *tgnr-cat* 0))
      (equal (fn-gns-number-result c) '(:missing)))))
; Corrupted cursor removal: terminal residual2, every other premise true.
(assert-event (let ((c (list :done 2 (fn-gnix-set 2 '(:ordinal 0) nil) 1 0)))
 (and (not (fn-gns-number-cursorp c)) (eq (fn-gns-at 0 c) :done)
      (equal (fn-gns-at 3 c) (len *tgnr-cat*))
      (equal (fn-gnix-get (fn-gns-at 1 c) (fn-gns-at 2 c))
             (fn-gns-ordinal-option (fn-cat-number-seq "a" 1 *tgnr-cat* 0)))
      (not (equal (fn-gns-number-result c) '(:ordinal 0))))))
; Completion removal: real begin cursor still pending, relation remains true.
(assert-event (let ((c (fn-gns-number-begin 1 *tgnr-root* 1)))
 (and (fn-gns-number-cursorp c) (not (eq (fn-gns-at 0 c) :done))
      (equal (fn-gns-at 3 c) (len *tgnr-cat*))
      (equal (fn-gnix-get (fn-gns-at 1 c) (fn-gns-at 2 c))
             (fn-gns-ordinal-option (fn-cat-number-seq "a" 1 *tgnr-cat* 0)))
      (not (equal (fn-gns-number-result c) '(:ordinal 0))))))
; Capturedcount mismatch removal: valid completed cursor refusesordinal0.
(assert-event (let ((c (fn-tgnr-run 8 (fn-gns-number-begin 1 *tgnr-root* 0))))
 (and (fn-gns-number-cursorp c) (eq (fn-gns-at 0 c) :done)
      (not (equal (fn-gns-at 3 c) (len *tgnr-cat*)))
      (equal (fn-gnix-get (fn-gns-at 1 c) (fn-gns-at 2 c))
             (fn-gns-ordinal-option (fn-cat-number-seq "a" 1 *tgnr-cat* 0)))
      (not (equal (fn-gns-number-result c) '(:ordinal 0))))))
; Corrupted association removal: valid completed reader on wrong root.
(assert-event (let ((c (fn-tgnr-run 8 (fn-gns-number-begin 1 nil 1))))
 (and (fn-gns-number-cursorp c) (eq (fn-gns-at 0 c) :done)
      (equal (fn-gns-at 3 c) (len *tgnr-cat*))
      (not (equal (fn-gnix-get (fn-gns-at 1 c) (fn-gns-at 2 c))
                  (fn-gns-ordinal-option (fn-cat-number-seq "a" 1 *tgnr-cat* 0))))
      (not (equal (fn-gns-number-result c) '(:ordinal 0))))))
