; Teeth for books/handle-holds (TEETH CONTRACT v1): the two released-handles
; keystones.  Both are stated over (mv-nth K (fn-arpn-step ..)), which defteeth's
; executable witnesses cannot evaluate, so their witnesses are ground theorems
; (:witness-lemma, :lemma on each mutation): lemma debt (TEETH-OWED-MV-CLAIM).
; The claims keep every antecedent inside the implication, so each mutation
; is the statement with one antecedent dropped (false at a witness where that
; antecedent fails) or one conclusion conjunct broken.

(in-package "ACL2")
(include-book "../../books/handle-holds")
(include-book "../../books/defkeystone")

(defconst *hht-w*
  (fn-record-make 0 1 0 "<a@x>" '(83 58 32 97 13 10 13 10) '("fn.test") "o" "s" "e" 1 5))
(defconst *hht-old*
  (list (fn-held-plain *hht-w* 0) (fn-held-plain *hht-w* 1) (fn-held-plain *hht-w* 2)))
(defconst *hht-new*
  (list (fn-held-plain *hht-w* 0) (fn-held-plain *hht-w* 3) (fn-held-plain *hht-w* 2)))
(defconst *hht-named* '(0 3 2))
(defconst *hht-named-bad* '(0 1 2))
; a reader pinned at generation 1; the retirement of handle 1 is pending at
; stamp 0, which the pin does not hold (0 < 1): the release answers it.
(defconst *hht-st* '(2 ((1 . 1)) ((0 (:forget 1)))))
(defconst *hht-st-forget5* '(2 ((1 . 1)) ((0 (:forget 5)))))
(defconst *hht-e* '(0 (:forget 1)))
(defconst *hht-e-absent* '(7 (:forget 1)))

(defthm hht-fixture-positive
  (and (fn-arpn-okp *hht-st*)
       (equal (mv-nth 1 (fn-arpn-step *hht-st* '(:release))) (list *hht-e*))
       (equal (cdr *hht-e*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new*)))
       (fn-arf-disjointp (fn-arf-changed-handles *hht-old* *hht-new*) *hht-named*)
       (not (fn-arf-disjointp (fn-arf-changed-handles *hht-old* *hht-new*) *hht-named-bad*))
       (equal (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))) 1)
       (no-duplicatesp-equal (fn-arf-rows-handles *hht-old*))
       (fn-arf-rewrite-of-p *hht-old* *hht-new* (fn-arf-rows-handles *hht-old*))
       (equal (fn-arf-rows-handles *hht-new*) *hht-named*))
  :rule-classes nil)

(defconst *hht-old-dup* (list (fn-held-plain *hht-w* 1) (fn-held-plain *hht-w* 1)))
(defconst *hht-new-dup* (list (fn-held-plain *hht-w* 3) (fn-held-plain *hht-w* 1)))
(defconst *hht-new-swap*
  (list (fn-held-plain *hht-w* 1) (fn-held-plain *hht-w* 0) (fn-held-plain *hht-w* 2)))
(defconst *hht-st-swap* '(2 ((1 . 1)) ((0 (:forget 0) (:forget 1)))))
(defconst *hht-e-swap* '(0 (:forget 0) (:forget 1)))

(defthm hht-unnamed-witness
  (implies (and (fn-arpn-okp *hht-st*)
                      (member-equal *hht-e* (mv-nth 1 (fn-arpn-step *hht-st* '(:release))))
                      (equal (cdr *hht-e*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new*)))
                      (fn-arf-disjointp (fn-arf-changed-handles *hht-old* *hht-new*) *hht-named*))
                 (and (member-equal *hht-e* (third *hht-st*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))))
                               (< (car *hht-e*) 1))
                      (equal (fn-arf-items-handles (cdr *hht-e*)) (fn-arf-changed-handles *hht-old* *hht-new*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e*)))
                               (not (member-equal 1 *hht-named*)))))
  :rule-classes nil)

(defthm hht-unnamed-mut1
  (and (implies (and (fn-arpn-okp *hht-st*)
                      (member-equal *hht-e* (mv-nth 1 (fn-arpn-step *hht-st* '(:release))))
                      (equal (cdr *hht-e*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new*)))
                      (fn-arf-disjointp (fn-arf-changed-handles *hht-old* *hht-new*) *hht-named-bad*))
                 (and (member-equal *hht-e* (third *hht-st*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))))
                               (< (car *hht-e*) 1))
                      (equal (fn-arf-items-handles (cdr *hht-e*)) (fn-arf-changed-handles *hht-old* *hht-new*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e*)))
                               (not (member-equal 1 *hht-named-bad*)))))
       (not (implies (and (fn-arpn-okp *hht-st*)
                      (member-equal *hht-e* (mv-nth 1 (fn-arpn-step *hht-st* '(:release))))
                      (equal (cdr *hht-e*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new*))))
                 (and (member-equal *hht-e* (third *hht-st*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))))
                               (< (car *hht-e*) 1))
                      (equal (fn-arf-items-handles (cdr *hht-e*)) (fn-arf-changed-handles *hht-old* *hht-new*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e*)))
                               (not (member-equal 1 *hht-named-bad*)))))))
  :rule-classes nil)

(defthm hht-unnamed-mut2
  (and (implies (and (fn-arpn-okp *hht-st-forget5*)
                      (member-equal '(0 (:forget 5)) (mv-nth 1 (fn-arpn-step *hht-st-forget5* '(:release))))
                      (equal (cdr '(0 (:forget 5))) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new*)))
                      (fn-arf-disjointp (fn-arf-changed-handles *hht-old* *hht-new*) *hht-named*))
                 (and (member-equal '(0 (:forget 5)) (third *hht-st-forget5*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st-forget5* '(:release))))))
                               (< (car '(0 (:forget 5))) 1))
                      (equal (fn-arf-items-handles (cdr '(0 (:forget 5)))) (fn-arf-changed-handles *hht-old* *hht-new*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr '(0 (:forget 5)))))
                               (not (member-equal 1 *hht-named*)))))
       (not (implies (and (fn-arpn-okp *hht-st-forget5*)
                      (member-equal '(0 (:forget 5)) (mv-nth 1 (fn-arpn-step *hht-st-forget5* '(:release))))
                      (fn-arf-disjointp (fn-arf-changed-handles *hht-old* *hht-new*) *hht-named*))
                 (and (member-equal '(0 (:forget 5)) (third *hht-st-forget5*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st-forget5* '(:release))))))
                               (< (car '(0 (:forget 5))) 1))
                      (equal (fn-arf-items-handles (cdr '(0 (:forget 5)))) (fn-arf-changed-handles *hht-old* *hht-new*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr '(0 (:forget 5)))))
                               (not (member-equal 1 *hht-named*)))))))
  :rule-classes nil)

(defthm hht-unnamed-mut3
  (and (implies (and (fn-arpn-okp *hht-st*)
                      (member-equal *hht-e-absent* (mv-nth 1 (fn-arpn-step *hht-st* '(:release))))
                      (equal (cdr *hht-e-absent*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new*)))
                      (fn-arf-disjointp (fn-arf-changed-handles *hht-old* *hht-new*) *hht-named*))
                 (and (member-equal *hht-e-absent* (third *hht-st*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))))
                               (< (car *hht-e-absent*) 1))
                      (equal (fn-arf-items-handles (cdr *hht-e-absent*)) (fn-arf-changed-handles *hht-old* *hht-new*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e-absent*)))
                               (not (member-equal 1 *hht-named*)))))
       (not (implies (and (fn-arpn-okp *hht-st*)
                      (equal (cdr *hht-e-absent*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new*)))
                      (fn-arf-disjointp (fn-arf-changed-handles *hht-old* *hht-new*) *hht-named*))
                 (and (member-equal *hht-e-absent* (third *hht-st*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))))
                               (< (car *hht-e-absent*) 1))
                      (equal (fn-arf-items-handles (cdr *hht-e-absent*)) (fn-arf-changed-handles *hht-old* *hht-new*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e-absent*)))
                               (not (member-equal 1 *hht-named*)))))))
  :rule-classes nil)

(defthm hht-unnamed-mut4
  (and (implies (and (fn-arpn-okp *hht-st*)
                      (member-equal *hht-e* (mv-nth 1 (fn-arpn-step *hht-st* '(:release))))
                      (equal (cdr *hht-e*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new*)))
                      (fn-arf-disjointp (fn-arf-changed-handles *hht-old* *hht-new*) *hht-named*))
                 (and (member-equal *hht-e* (third *hht-st*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))))
                               (< (car *hht-e*) 1))
                      (equal (fn-arf-items-handles (cdr *hht-e*)) (fn-arf-changed-handles *hht-old* *hht-new*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e*)))
                               (not (member-equal 1 *hht-named*)))))
       (not (implies (and (fn-arpn-okp *hht-st*)
                      (member-equal *hht-e* (mv-nth 1 (fn-arpn-step *hht-st* '(:release))))
                      (equal (cdr *hht-e*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new*)))
                      (fn-arf-disjointp (fn-arf-changed-handles *hht-old* *hht-new*) *hht-named*))
                 (and (member-equal *hht-e* (third *hht-st*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))))
                               (< 1 (car *hht-e*)))
                      (equal (fn-arf-items-handles (cdr *hht-e*)) (fn-arf-changed-handles *hht-old* *hht-new*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e*)))
                               (not (member-equal 1 *hht-named*)))))))
  :rule-classes nil)

(defteeth fn-handle-holds-released-handles-are-unnamed-and-postdate-every-pin
  :claim (() (implies (and (fn-arpn-okp st)
                      (member-equal e (mv-nth 1 (fn-arpn-step st '(:release))))
                      (equal (cdr e) (fn-arf-tag (fn-arf-changed-handles old new)))
                      (fn-arf-disjointp (fn-arf-changed-handles old new) named))
                 (and (member-equal e (third st))
                      (implies (< 0 (fn-arpn-pins-of g (second (mv-nth 0 (fn-arpn-step st '(:release))))))
                               (< (car e) g))
                      (equal (fn-arf-items-handles (cdr e)) (fn-arf-changed-handles old new))
                      (implies (member-equal h (fn-arf-items-handles (cdr e)))
                               (not (member-equal h named))))))
  :subject fn-arpn-step
  :witness-lemma hht-unnamed-witness
  :witness ((st *hht-st*) (e *hht-e*) (old *hht-old*) (new *hht-new*) (named *hht-named*) (g 1) (h 1))
  :mutations ((no-disjointness
               (:conclusion (implies (and (fn-arpn-okp st)
                      (member-equal e (mv-nth 1 (fn-arpn-step st '(:release))))
                      (equal (cdr e) (fn-arf-tag (fn-arf-changed-handles old new))))
                 (and (member-equal e (third st))
                      (implies (< 0 (fn-arpn-pins-of g (second (mv-nth 0 (fn-arpn-step st '(:release))))))
                               (< (car e) g))
                      (equal (fn-arf-items-handles (cdr e)) (fn-arf-changed-handles old new))
                      (implies (member-equal h (fn-arf-items-handles (cdr e)))
                               (not (member-equal h named))))))
               ((st *hht-st*) (e *hht-e*) (old *hht-old*) (new *hht-new*) (named *hht-named-bad*) (g 1) (h 1))
               :fault "a statement that does not require the changed handles to be unnamed"
               :lemma hht-unnamed-mut1)
              (no-tag-hypothesis
               (:conclusion (implies (and (fn-arpn-okp st)
                      (member-equal e (mv-nth 1 (fn-arpn-step st '(:release))))
                      (fn-arf-disjointp (fn-arf-changed-handles old new) named))
                 (and (member-equal e (third st))
                      (implies (< 0 (fn-arpn-pins-of g (second (mv-nth 0 (fn-arpn-step st '(:release))))))
                               (< (car e) g))
                      (equal (fn-arf-items-handles (cdr e)) (fn-arf-changed-handles old new))
                      (implies (member-equal h (fn-arf-items-handles (cdr e)))
                               (not (member-equal h named))))))
               ((st *hht-st-forget5*) (e '(0 (:forget 5))) (old *hht-old*) (new *hht-new*) (named *hht-named*) (g 1) (h 1))
               :fault "a statement that does not tie the released items to the changed handles"
               :lemma hht-unnamed-mut2)
              (no-membership-hypothesis
               (:conclusion (implies (and (fn-arpn-okp st)
                      (equal (cdr e) (fn-arf-tag (fn-arf-changed-handles old new)))
                      (fn-arf-disjointp (fn-arf-changed-handles old new) named))
                 (and (member-equal e (third st))
                      (implies (< 0 (fn-arpn-pins-of g (second (mv-nth 0 (fn-arpn-step st '(:release))))))
                               (< (car e) g))
                      (equal (fn-arf-items-handles (cdr e)) (fn-arf-changed-handles old new))
                      (implies (member-equal h (fn-arf-items-handles (cdr e)))
                               (not (member-equal h named))))))
               ((st *hht-st*) (e *hht-e-absent*) (old *hht-old*) (new *hht-new*) (named *hht-named*) (g 1) (h 1))
               :fault "a statement about an item the release never answered"
               :lemma hht-unnamed-mut3)
              (pin-ordering-reversed
               (:conclusion (implies (and (fn-arpn-okp st)
                      (member-equal e (mv-nth 1 (fn-arpn-step st '(:release))))
                      (equal (cdr e) (fn-arf-tag (fn-arf-changed-handles old new)))
                      (fn-arf-disjointp (fn-arf-changed-handles old new) named))
                 (and (member-equal e (third st))
                      (implies (< 0 (fn-arpn-pins-of g (second (mv-nth 0 (fn-arpn-step st '(:release))))))
                               (< g (car e)))
                      (equal (fn-arf-items-handles (cdr e)) (fn-arf-changed-handles old new))
                      (implies (member-equal h (fn-arf-items-handles (cdr e)))
                               (not (member-equal h named))))))
               ((st *hht-st*) (e *hht-e*) (old *hht-old*) (new *hht-new*) (named *hht-named*) (g 1) (h 1))
               :fault "a release that claims it follows the pin it must precede"
               :lemma hht-unnamed-mut4)))

(defthm hht-pairwise-witness
  (implies (and (fn-arpn-okp *hht-st*)
                      (member-equal *hht-e* (mv-nth 1 (fn-arpn-step *hht-st* '(:release))))
                      (equal (cdr *hht-e*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new*)))
                      (no-duplicatesp-equal (fn-arf-rows-handles *hht-old*))
                      (fn-arf-rewrite-of-p *hht-old* *hht-new* (fn-arf-rows-handles *hht-old*)))
                 (and (member-equal *hht-e* (third *hht-st*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))))
                               (< (car *hht-e*) 1))
                      (equal (fn-arf-items-handles (cdr *hht-e*)) (fn-arf-changed-handles *hht-old* *hht-new*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e*)))
                               (not (member-equal 1 (fn-arf-rows-handles *hht-new*))))))
  :rule-classes nil)

(defthm hht-pairwise-mut1
  (and (implies (and (fn-arpn-okp *hht-st*)
                      (member-equal *hht-e* (mv-nth 1 (fn-arpn-step *hht-st* '(:release))))
                      (equal (cdr *hht-e*) (fn-arf-tag (fn-arf-changed-handles *hht-old-dup* *hht-new-dup*)))
                      (no-duplicatesp-equal (fn-arf-rows-handles *hht-old-dup*))
                      (fn-arf-rewrite-of-p *hht-old-dup* *hht-new-dup* (fn-arf-rows-handles *hht-old-dup*)))
                 (and (member-equal *hht-e* (third *hht-st*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))))
                               (< (car *hht-e*) 1))
                      (equal (fn-arf-items-handles (cdr *hht-e*)) (fn-arf-changed-handles *hht-old-dup* *hht-new-dup*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e*)))
                               (not (member-equal 1 (fn-arf-rows-handles *hht-new-dup*))))))
       (not (implies (and (fn-arpn-okp *hht-st*)
                      (member-equal *hht-e* (mv-nth 1 (fn-arpn-step *hht-st* '(:release))))
                      (equal (cdr *hht-e*) (fn-arf-tag (fn-arf-changed-handles *hht-old-dup* *hht-new-dup*)))
                      (fn-arf-rewrite-of-p *hht-old-dup* *hht-new-dup* (fn-arf-rows-handles *hht-old-dup*)))
                 (and (member-equal *hht-e* (third *hht-st*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))))
                               (< (car *hht-e*) 1))
                      (equal (fn-arf-items-handles (cdr *hht-e*)) (fn-arf-changed-handles *hht-old-dup* *hht-new-dup*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e*)))
                               (not (member-equal 1 (fn-arf-rows-handles *hht-new-dup*))))))))
  :rule-classes nil)

(defthm hht-pairwise-mut2
  (and (implies (and (fn-arpn-okp *hht-st-swap*)
                      (member-equal *hht-e-swap* (mv-nth 1 (fn-arpn-step *hht-st-swap* '(:release))))
                      (equal (cdr *hht-e-swap*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new-swap*)))
                      (no-duplicatesp-equal (fn-arf-rows-handles *hht-old*))
                      (fn-arf-rewrite-of-p *hht-old* *hht-new-swap* (fn-arf-rows-handles *hht-old*)))
                 (and (member-equal *hht-e-swap* (third *hht-st-swap*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st-swap* '(:release))))))
                               (< (car *hht-e-swap*) 1))
                      (equal (fn-arf-items-handles (cdr *hht-e-swap*)) (fn-arf-changed-handles *hht-old* *hht-new-swap*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e-swap*)))
                               (not (member-equal 1 (fn-arf-rows-handles *hht-new-swap*))))))
       (not (implies (and (fn-arpn-okp *hht-st-swap*)
                      (member-equal *hht-e-swap* (mv-nth 1 (fn-arpn-step *hht-st-swap* '(:release))))
                      (equal (cdr *hht-e-swap*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new-swap*)))
                      (no-duplicatesp-equal (fn-arf-rows-handles *hht-old*)))
                 (and (member-equal *hht-e-swap* (third *hht-st-swap*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st-swap* '(:release))))))
                               (< (car *hht-e-swap*) 1))
                      (equal (fn-arf-items-handles (cdr *hht-e-swap*)) (fn-arf-changed-handles *hht-old* *hht-new-swap*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e-swap*)))
                               (not (member-equal 1 (fn-arf-rows-handles *hht-new-swap*))))))))
  :rule-classes nil)

(defthm hht-pairwise-mut3
  (and (implies (and (fn-arpn-okp *hht-st*)
                      (member-equal *hht-e-absent* (mv-nth 1 (fn-arpn-step *hht-st* '(:release))))
                      (equal (cdr *hht-e-absent*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new*)))
                      (no-duplicatesp-equal (fn-arf-rows-handles *hht-old*))
                      (fn-arf-rewrite-of-p *hht-old* *hht-new* (fn-arf-rows-handles *hht-old*)))
                 (and (member-equal *hht-e-absent* (third *hht-st*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))))
                               (< (car *hht-e-absent*) 1))
                      (equal (fn-arf-items-handles (cdr *hht-e-absent*)) (fn-arf-changed-handles *hht-old* *hht-new*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e-absent*)))
                               (not (member-equal 1 (fn-arf-rows-handles *hht-new*))))))
       (not (implies (and (fn-arpn-okp *hht-st*)
                      (equal (cdr *hht-e-absent*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new*)))
                      (no-duplicatesp-equal (fn-arf-rows-handles *hht-old*))
                      (fn-arf-rewrite-of-p *hht-old* *hht-new* (fn-arf-rows-handles *hht-old*)))
                 (and (member-equal *hht-e-absent* (third *hht-st*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))))
                               (< (car *hht-e-absent*) 1))
                      (equal (fn-arf-items-handles (cdr *hht-e-absent*)) (fn-arf-changed-handles *hht-old* *hht-new*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e-absent*)))
                               (not (member-equal 1 (fn-arf-rows-handles *hht-new*))))))))
  :rule-classes nil)

(defthm hht-pairwise-mut4
  (and (implies (and (fn-arpn-okp *hht-st*)
                      (member-equal *hht-e* (mv-nth 1 (fn-arpn-step *hht-st* '(:release))))
                      (equal (cdr *hht-e*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new*)))
                      (no-duplicatesp-equal (fn-arf-rows-handles *hht-old*))
                      (fn-arf-rewrite-of-p *hht-old* *hht-new* (fn-arf-rows-handles *hht-old*)))
                 (and (member-equal *hht-e* (third *hht-st*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))))
                               (< (car *hht-e*) 1))
                      (equal (fn-arf-items-handles (cdr *hht-e*)) (fn-arf-changed-handles *hht-old* *hht-new*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e*)))
                               (not (member-equal 1 (fn-arf-rows-handles *hht-new*))))))
       (not (implies (and (fn-arpn-okp *hht-st*)
                      (member-equal *hht-e* (mv-nth 1 (fn-arpn-step *hht-st* '(:release))))
                      (equal (cdr *hht-e*) (fn-arf-tag (fn-arf-changed-handles *hht-old* *hht-new*)))
                      (no-duplicatesp-equal (fn-arf-rows-handles *hht-old*))
                      (fn-arf-rewrite-of-p *hht-old* *hht-new* (fn-arf-rows-handles *hht-old*)))
                 (and (member-equal *hht-e* (third *hht-st*))
                      (implies (< 0 (fn-arpn-pins-of 1 (second (mv-nth 0 (fn-arpn-step *hht-st* '(:release))))))
                               (< 1 (car *hht-e*)))
                      (equal (fn-arf-items-handles (cdr *hht-e*)) (fn-arf-changed-handles *hht-old* *hht-new*))
                      (implies (member-equal 1 (fn-arf-items-handles (cdr *hht-e*)))
                               (not (member-equal 1 (fn-arf-rows-handles *hht-new*))))))))
  :rule-classes nil)

(defteeth fn-handle-holds-released-handles-are-unnamed-under-the-pairwise-root-fact
  :claim (() (implies (and (fn-arpn-okp st)
                      (member-equal e (mv-nth 1 (fn-arpn-step st '(:release))))
                      (equal (cdr e) (fn-arf-tag (fn-arf-changed-handles old new)))
                      (no-duplicatesp-equal (fn-arf-rows-handles old))
                      (fn-arf-rewrite-of-p old new (fn-arf-rows-handles old)))
                 (and (member-equal e (third st))
                      (implies (< 0 (fn-arpn-pins-of g (second (mv-nth 0 (fn-arpn-step st '(:release))))))
                               (< (car e) g))
                      (equal (fn-arf-items-handles (cdr e)) (fn-arf-changed-handles old new))
                      (implies (member-equal h (fn-arf-items-handles (cdr e)))
                               (not (member-equal h (fn-arf-rows-handles new)))))))
  :subject fn-arpn-step
  :witness-lemma hht-pairwise-witness
  :witness ((st *hht-st*) (e *hht-e*) (old *hht-old*) (new *hht-new*) (g 1) (h 1))
  :mutations ((no-distinct-old-handles
               (:conclusion (implies (and (fn-arpn-okp st)
                      (member-equal e (mv-nth 1 (fn-arpn-step st '(:release))))
                      (equal (cdr e) (fn-arf-tag (fn-arf-changed-handles old new)))
                      (fn-arf-rewrite-of-p old new (fn-arf-rows-handles old)))
                 (and (member-equal e (third st))
                      (implies (< 0 (fn-arpn-pins-of g (second (mv-nth 0 (fn-arpn-step st '(:release))))))
                               (< (car e) g))
                      (equal (fn-arf-items-handles (cdr e)) (fn-arf-changed-handles old new))
                      (implies (member-equal h (fn-arf-items-handles (cdr e)))
                               (not (member-equal h (fn-arf-rows-handles new)))))))
               ((st *hht-st*) (e *hht-e*) (old *hht-old-dup*) (new *hht-new-dup*) (g 1) (h 1))
               :fault "a statement that does not require the old rows' handles to be distinct"
               :lemma hht-pairwise-mut1)
              (no-rewrite-relation
               (:conclusion (implies (and (fn-arpn-okp st)
                      (member-equal e (mv-nth 1 (fn-arpn-step st '(:release))))
                      (equal (cdr e) (fn-arf-tag (fn-arf-changed-handles old new)))
                      (no-duplicatesp-equal (fn-arf-rows-handles old)))
                 (and (member-equal e (third st))
                      (implies (< 0 (fn-arpn-pins-of g (second (mv-nth 0 (fn-arpn-step st '(:release))))))
                               (< (car e) g))
                      (equal (fn-arf-items-handles (cdr e)) (fn-arf-changed-handles old new))
                      (implies (member-equal h (fn-arf-items-handles (cdr e)))
                               (not (member-equal h (fn-arf-rows-handles new)))))))
               ((st *hht-st-swap*) (e *hht-e-swap*) (old *hht-old*) (new *hht-new-swap*) (g 1) (h 1))
               :fault "a statement that does not require the new rows to be a rewrite of the old"
               :lemma hht-pairwise-mut2)
              (no-membership-hypothesis
               (:conclusion (implies (and (fn-arpn-okp st)
                      (equal (cdr e) (fn-arf-tag (fn-arf-changed-handles old new)))
                      (no-duplicatesp-equal (fn-arf-rows-handles old))
                      (fn-arf-rewrite-of-p old new (fn-arf-rows-handles old)))
                 (and (member-equal e (third st))
                      (implies (< 0 (fn-arpn-pins-of g (second (mv-nth 0 (fn-arpn-step st '(:release))))))
                               (< (car e) g))
                      (equal (fn-arf-items-handles (cdr e)) (fn-arf-changed-handles old new))
                      (implies (member-equal h (fn-arf-items-handles (cdr e)))
                               (not (member-equal h (fn-arf-rows-handles new)))))))
               ((st *hht-st*) (e *hht-e-absent*) (old *hht-old*) (new *hht-new*) (g 1) (h 1))
               :fault "a statement about an item the release never answered"
               :lemma hht-pairwise-mut3)
              (pin-ordering-reversed
               (:conclusion (implies (and (fn-arpn-okp st)
                      (member-equal e (mv-nth 1 (fn-arpn-step st '(:release))))
                      (equal (cdr e) (fn-arf-tag (fn-arf-changed-handles old new)))
                      (no-duplicatesp-equal (fn-arf-rows-handles old))
                      (fn-arf-rewrite-of-p old new (fn-arf-rows-handles old)))
                 (and (member-equal e (third st))
                      (implies (< 0 (fn-arpn-pins-of g (second (mv-nth 0 (fn-arpn-step st '(:release))))))
                               (< g (car e)))
                      (equal (fn-arf-items-handles (cdr e)) (fn-arf-changed-handles old new))
                      (implies (member-equal h (fn-arf-items-handles (cdr e)))
                               (not (member-equal h (fn-arf-rows-handles new)))))))
               ((st *hht-st*) (e *hht-e*) (old *hht-old*) (new *hht-new*) (g 1) (h 1))
               :fault "a release that claims it follows the pin it must precede"
               :lemma hht-pairwise-mut4)))
