(in-package "ACL2")
(include-book "../../books/history-census-controller")

; Test-only bounded driver retains the predecessor of a completed row, so
; the literal boundary's complete antecedent is checked at the real tick.
(defun fn-hct-test-before-row (fuel c)
  (if (zp fuel) c
    (mv-let (v summary next) (fn-hct-tick c)
      (declare (ignore summary))
      (if (eq v :continue) (fn-hct-test-before-row (1- fuel) next) c))))

(assert-event
 (let* ((ev '(1 2 3)) (h nil)
        (start (fn-hct-begin 2 'epoch 'funded))
        (offered (nth 1 (mv-list 2 (fn-hct-offer start 0 (list :resident ev)))))
        (c (fn-hct-test-before-row 100 offered))
        (r (mv-list 3 (fn-hct-tick c))))
   (and (fn-hct-shapep c) (equal (fn-hrcur-field 0 c) :codec)
        (equal (fn-hrcur-field 2 c) (len h))
        (equal (fn-hrcur-field 3 c) (fn-hp-pes-len h))
        (fn-hrcur-census-invariantp (fn-hrcur-field 4 c))
        (equal (fn-hrcur-census-total (fn-hrcur-field 4 c))
               (len (fn-scc-encode ev)))
        (equal (car r) :row-done)
        (equal (fn-hrcur-field 2 (nth 2 r)) (len (append h (list ev))))
        (equal (fn-hrcur-field 3 (nth 2 r)) (fn-hp-pes-len (append h (list ev))))
        (fn-hct-shapep (nth 2 r))
        (equal (fn-hrcur-field 5 (nth 2 r)) 'epoch)
        (equal (fn-hrcur-field 6 (nth 2 r)) 'funded))))
(assert-event
 (let* ((c (fn-hct-begin 0 'epoch 'funded))
        (r (mv-list 3 (fn-hct-tick c))))
   (and (fn-hct-shapep c) (equal r (list :prepared '(0 0) c)))))
(assert-event
 (let ((c (fn-hct-begin 2 'epoch 'funded)))
   (equal (mv-list 2 (fn-hct-offer c 1 '(:resident t))) (list :stale c))))
(assert-event
 (let* ((c (nth 1 (mv-list 2 (fn-hct-offer (fn-hct-begin 2 'epoch 'funded)
                                  0 '(:resident t))))))
   (equal (mv-list 2 (fn-hct-offer c 0 '(:resident t))) (list :stale c))))
(assert-event
 (let* ((c0 (nth 1 (mv-list 2 (fn-hct-offer (fn-hct-begin 2 'epoch 'funded)
                                   0 '(:resident (1 2 3))))))
        (c1 (nth 2 (mv-list 3 (fn-hct-tick (fn-hct-test-before-row 100 c0)))))
        (c2 (nth 1 (mv-list 2 (fn-hct-offer c1 1 '(:resident "hello")))))
        (c3 (nth 2 (mv-list 3 (fn-hct-tick (fn-hct-test-before-row 200 c2))))))
   (and (equal (fn-hrcur-field 0 c3) :prepared)
        (equal (fn-hrcur-field 2 c3) 2)
        (equal (fn-hrcur-field 3 c3) (fn-hp-pes-len '((1 2 3) "hello")))
        (equal (nth 0 (mv-list 3 (fn-hct-tick c3))) :prepared))))
; Reachable continuation: establish the child invariant from a resident row,
; then retain exact total and both accumulated history scalars through yield.
(assert-event
 (let* ((row '(1 2 3)) (base (fn-hct-begin 1 'epoch 'funded))
        (c (nth 1 (mv-list 2 (fn-hct-offer base 0 (list :resident row)))))
        (r (mv-list 3 (fn-hct-tick c))) (next (nth 2 r)))
   (and (fn-hct-shapep base) (equal (fn-hrcur-field 0 base) :need-row)
        (equal 0 (fn-hrcur-field 2 base))
        (fn-hrcur-tree-domainp row)
        (< (len (fn-scc-encode row)) *fn-hrcur-u64-bound*)
        (fn-hrcur-census-invariantp (fn-hrcur-field 4 c))
        (equal (fn-hrcur-census-total (fn-hrcur-field 4 c)) (len (fn-scc-encode row)))
        (fn-hct-shapep c) (equal (fn-hrcur-field 0 c) :codec)
        (equal (car r) :continue)
        (fn-hrcur-census-invariantp (fn-hrcur-field 4 next))
        (equal (fn-hrcur-census-total (fn-hrcur-field 4 next))
               (fn-hrcur-census-total (fn-hrcur-field 4 c)))
        (equal (fn-hrcur-field 2 next) (fn-hrcur-field 2 c))
        (equal (fn-hrcur-field 3 next) (fn-hrcur-field 3 c)))))

; Hypothesis removal: Corrupted completed count.
(assert-event
 (let* ((h nil) (ev t)
        (offered (nth 1 (mv-list 2 (fn-hct-offer (fn-hct-begin 3 'epoch 'funded)
                                               0 '(:resident t)))))
        (before (fn-hct-test-before-row 100 offered))
        (c (update-nth 2 1 before)) (r (mv-list 3 (fn-hct-tick c))))
   (declare (ignorable before))
   (and (not (equal (fn-hrcur-field 2 c) (len h)))
        (equal (fn-hrcur-field 3 c) (fn-hp-pes-len h))
        (fn-hrcur-census-invariantp (fn-hrcur-field 4 c))
        (equal (fn-hrcur-census-total (fn-hrcur-field 4 c)) (len (fn-scc-encode ev)))
        (equal (car r) :row-done)
        (not (and (equal (fn-hrcur-field 2 (nth 2 r)) (len (append h (list ev))))
                  (equal (fn-hrcur-field 3 (nth 2 r))
                         (fn-hp-pes-len (append h (list ev)))))))))

; Hypothesis removal: Corrupted accumulated pool.
(assert-event
 (let* ((h nil) (ev t)
        (offered (nth 1 (mv-list 2 (fn-hct-offer (fn-hct-begin 3 'epoch 'funded)
                                               0 '(:resident t)))))
        (before (fn-hct-test-before-row 100 offered))
        (c (update-nth 3 8 before)) (r (mv-list 3 (fn-hct-tick c))))
   (declare (ignorable before))
   (and (equal (fn-hrcur-field 2 c) (len h))
        (not (equal (fn-hrcur-field 3 c) (fn-hp-pes-len h)))
        (fn-hrcur-census-invariantp (fn-hrcur-field 4 c))
        (equal (fn-hrcur-census-total (fn-hrcur-field 4 c)) (len (fn-scc-encode ev)))
        (equal (car r) :row-done)
        (not (and (equal (fn-hrcur-field 2 (nth 2 r)) (len (append h (list ev))))
                  (equal (fn-hrcur-field 3 (nth 2 r))
                         (fn-hp-pes-len (append h (list ev)))))))))

; Hypothesis removal: Corrupted child done flag with unconsumed bytes.
(assert-event
 (let* ((h nil) (ev "123456789")
        (offered (nth 1 (mv-list 2 (fn-hct-offer (fn-hct-begin 3 'epoch 'funded)
                                               0 '(:resident t)))))
        (before (fn-hct-test-before-row 100 offered))
        (c (list :codec 3 0 0 (list :done (fn-hrcur-byte-begin (list :resident ev) 'epoch 'funded) 0) 'epoch 'funded)) (r (mv-list 3 (fn-hct-tick c))))
   (declare (ignorable before))
   (and (equal (fn-hrcur-field 2 c) (len h))
        (equal (fn-hrcur-field 3 c) (fn-hp-pes-len h))
        (not (fn-hrcur-census-invariantp (fn-hrcur-field 4 c)))
        (equal (fn-hrcur-census-total (fn-hrcur-field 4 c)) (len (fn-scc-encode ev)))
        (equal (car r) :row-done)
        (not (and (equal (fn-hrcur-field 2 (nth 2 r)) (len (append h (list ev))))
                  (equal (fn-hrcur-field 3 (nth 2 r))
                         (fn-hp-pes-len (append h (list ev)))))))))

; Hypothesis removal: Wrong row attribution.
(assert-event
 (let* ((h nil) (ev "123456789")
        (offered (nth 1 (mv-list 2 (fn-hct-offer (fn-hct-begin 3 'epoch 'funded)
                                               0 '(:resident t)))))
        (before (fn-hct-test-before-row 100 offered))
        (c before) (r (mv-list 3 (fn-hct-tick c))))
   (declare (ignorable before))
   (and (equal (fn-hrcur-field 2 c) (len h))
        (equal (fn-hrcur-field 3 c) (fn-hp-pes-len h))
        (fn-hrcur-census-invariantp (fn-hrcur-field 4 c))
        (not (equal (fn-hrcur-census-total (fn-hrcur-field 4 c)) (len (fn-scc-encode ev))))
        (equal (car r) :row-done)
        (not (and (equal (fn-hrcur-field 2 (nth 2 r)) (len (append h (list ev))))
                  (equal (fn-hrcur-field 3 (nth 2 r))
                         (fn-hp-pes-len (append h (list ev)))))))))

; Hypothesis removal: Completion required.
(assert-event
 (let* ((h nil) (ev t)
        (offered (nth 1 (mv-list 2 (fn-hct-offer (fn-hct-begin 3 'epoch 'funded)
                                               0 '(:resident t)))))
        (before (fn-hct-test-before-row 100 offered))
        (c offered) (r (mv-list 3 (fn-hct-tick c))))
   (declare (ignorable before))
   (and (equal (fn-hrcur-field 2 c) (len h))
        (equal (fn-hrcur-field 3 c) (fn-hp-pes-len h))
        (fn-hrcur-census-invariantp (fn-hrcur-field 4 c))
        (equal (fn-hrcur-census-total (fn-hrcur-field 4 c)) (len (fn-scc-encode ev)))
        (not (equal (car r) :row-done))
        (not (and (equal (fn-hrcur-field 2 (nth 2 r)) (len (append h (list ev))))
                  (equal (fn-hrcur-field 3 (nth 2 r))
                         (fn-hp-pes-len (append h (list ev)))))))))
