; Constructed supported column phases; actual complete page issuance.
; Labelled full-premise mutations; no full-image/native/provenance claim.
(in-package "ACL2")
(include-book "../../books/history-image-column-handoff")
(include-book "../../books/history-image-effect-boundary")

(local (defun hpich-test-buffer-copy (fn-hpb)
 (declare (xargs :stobjs fn-hpb :verify-guards nil))
 (list (fn-hpb-prefix-aux 0 2048 fn-hpb) (fn-hpb-used fn-hpb)
       (fn-hpb-epoch fn-hpb) (fn-hpb-lease fn-hpb))))
(local (defun hpich-test-digest-frames (n pgs-digest-state)
 (declare (xargs :stobjs pgs-digest-state :verify-guards nil :measure (nfix n)))
 (if (zp n) nil (cons (pgs-dc-framesi (1- n) pgs-digest-state)
                     (hpich-test-digest-frames (1- n) pgs-digest-state)))))
(local (defun hpich-test-digest-copy (pgs-digest-state)
 (declare (xargs :stobjs pgs-digest-state :verify-guards nil))
 (list (pgs-dc-mode pgs-digest-state) (pgs-dc-sel pgs-digest-state)
       (pgs-dc-base pgs-digest-state) (pgs-dc-total pgs-digest-state)
       (pgs-dc-start pgs-digest-state) (pgs-dc-end pgs-digest-state)
       (pgs-dc-pos pgs-digest-state) (pgs-dc-counter pgs-digest-state)
       (pgs-dc-power pgs-digest-state) (pgs-dc-depth pgs-digest-state)
       (pgs-dc-cv pgs-digest-state) (pgs-dc-output pgs-digest-state)
       (pgs-dc-capture pgs-digest-state) (pgs-dc-lease pgs-digest-state)
       (pgs-dc-answer pgs-digest-state) (hpich-test-digest-frames 64 pgs-digest-state))))


(local (defun hpich-test-history (n)
 (declare (xargs :measure (nfix n)))
 (if (zp n) nil (cons "ABC" (hpich-test-history (1- n))))))
(local (defun hpich-test-fill (words fn-hpb)
 (declare (xargs :stobjs fn-hpb :verify-guards nil :measure (len words)))
 (if (atom words) fn-hpb
  (mv-let (status fn-hpb) (fn-hpb-put (car words) fn-hpb)
   (declare (ignore status)) (hpich-test-fill (cdr words) fn-hpb)))))
(local (defun hpich-test-region-fill (region h body pages source maintenance fn-hpb)
 (declare (xargs :stobjs fn-hpb :verify-guards nil))
 (let ((fn-hpb (fn-hpb-begin source maintenance fn-hpb)))
  (hpich-test-fill
   (nthcdr (* 2048 (nfix (nth region pages)))
    (fn-hpicol-history-model region (fn-hpicol-carried-history region h "ABC" body) 17)) fn-hpb))))
(local (defun hpich-test-case (region mode fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
 (declare (xargs :stobjs (fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) :verify-guards nil))
 (mv-let (admitted maintenance ledger)
  (fn-pmn-admit (fn-prl-make '(10000000 10000000 4 1 10)) 7 1 '(1000000 16384 3 1 1))
  (let ((initial (fn-hpi-begin 2049 16392 2 2 '(7 (9 2049) 0 0) maintenance (fn-omk-at 1 maintenance) 10000000 "node" 17 "trail")))
   (mv-let (funded request c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
    (fn-hpi-tick initial nil ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
    (declare (ignore request))
    (let* ((n 2048) (h (hpich-test-history n))
           (body (fn-hpcx-with :columns n (* 8 n) nil (list 7 '(9 2049) 1 n) (fn-hp-mkey "ABC" 17) (len (fn-scc-encode "ABC")) region (fn-omk-at 14 c)))
           (pages (list (if (and (= n 2048) (< 0 region)) 1 0)
                        (if (and (= n 2048) (< 1 region)) 1 0)
                        (if (and (= n 2048) (< 2 region)) 1 0)
                        0 1))
           (source (fn-omk-at 1 c))
           (c (fn-hpi-set 0 :body (fn-hpi-set 15 pages (fn-hpi-set 14 body c))))
           (fn-hpq0 (hpich-test-region-fill 0 h body pages source maintenance fn-hpq0))
           (fn-hpq1 (hpich-test-region-fill 1 h body pages source maintenance fn-hpq1))
           (fn-hpq2 (hpich-test-region-fill 2 h body pages source maintenance fn-hpq2))
           (fn-hpq3 (hpich-test-region-fill 3 h body pages source maintenance fn-hpq3))
           (baseline (and (eq admitted :admitted) (eq funded :funded)
                         (fn-hpicol-writer-ready-p h "ABC" 17 c fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3)
                         (fn-hpi-grant-matchesp c ledger)))
           ; Mutate only after establishing supported baseline.
           (c (if (eq mode :status) (fn-hpi-set 22 nil c) c))
           (fn-hpq0 (if (and (eq mode :ready) (= region 0)) (update-fn-hpb-wi 0 (logxor 1 (fn-hpb-wi 0 fn-hpq0)) fn-hpq0) fn-hpq0))
           (fn-hpq1 (if (and (eq mode :ready) (= region 1)) (update-fn-hpb-wi 0 (logxor 1 (fn-hpb-wi 0 fn-hpq1)) fn-hpq1) fn-hpq1))
           (fn-hpq2 (if (and (eq mode :ready) (= region 2)) (update-fn-hpb-wi 0 (logxor 1 (fn-hpb-wi 0 fn-hpq2)) fn-hpq2) fn-hpq2))
           (fn-hpq3 (if (and (eq mode :ready) (= region 3)) (update-fn-hpb-wi 0 (logxor 1 (fn-hpb-wi 0 fn-hpq3)) fn-hpq3) fn-hpq3))
           (ready (fn-hpicol-writer-ready-p h "ABC" 17 c fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3))
           (selected (case region (0 (fn-hpb-prefix fn-hpq0)) (1 (fn-hpb-prefix fn-hpq1))
                     (2 (fn-hpb-prefix fn-hpq2)) (otherwise (fn-hpb-prefix fn-hpq3))))
           (used (fn-hpi-region-used region fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb))
           (before0 (hpich-test-buffer-copy fn-hpq0)) (before1 (hpich-test-buffer-copy fn-hpq1))
           (before2 (hpich-test-buffer-copy fn-hpq2)) (before3 (hpich-test-buffer-copy fn-hpq3))
           (before4 (hpich-test-buffer-copy fn-hpb)) (before-digest (hpich-test-digest-copy pgs-digest-state)))
     (mv-let (await-status await-effect await-next)
      (fn-hpi-await-region region :body (fn-hpi-set 14 body c))
      (declare (ignore await-status))
     (mv-let (status effect next next-ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
      (fn-hpi-tick c nil ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
      (let ((conclusion (and (natp region) (< region 4) (= used 2048) (= (len selected) 2048)
              (equal selected (nthcdr (* 2048 (nfix (nth region pages)))
                 (fn-hpicol-history-model region (fn-hpicol-carried-history region h "ABC" body) 17)))
              (fn-hpicp-ack-contextp next)
              (eq status :write) (equal effect await-effect) (equal next await-next)
              (equal next-ledger ledger)
              (equal before0 (hpich-test-buffer-copy fn-hpq0)) (equal before1 (hpich-test-buffer-copy fn-hpq1))
              (equal before2 (hpich-test-buffer-copy fn-hpq2)) (equal before3 (hpich-test-buffer-copy fn-hpq3))
              (equal before4 (hpich-test-buffer-copy fn-hpb)) (equal before-digest (hpich-test-digest-copy pgs-digest-state)))))
       (mv (list baseline ready (eq status :write) conclusion)
           fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)))))))))
)
(local (defun hpich-test-local (column mode)
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-hpq0 (mv-let (result fn-hpq0) (with-local-stobj fn-hpq1 (mv-let (result fn-hpq0 fn-hpq1) (with-local-stobj fn-hpq2 (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2) (with-local-stobj fn-hpq3 (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3) (with-local-stobj fn-hpb (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb) (with-local-stobj pgs-digest-state (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) (hpich-test-case column mode fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) (mv result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb))) (mv result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3))) (mv result fn-hpq0 fn-hpq1 fn-hpq2))) (mv result fn-hpq0 fn-hpq1))) (mv result fn-hpq0))) result))))
; Supported phase positive; complete literal premise/conclusion.
(assert-event (equal (hpich-test-local 0 :positive) '(t t t t)))
; Labelled removal/mutation: ready; complete literal premise/conclusion.
(assert-event (equal (hpich-test-local 0 :ready) '(t nil t nil)))
; Labelled removal/mutation: status; complete literal premise/conclusion.
(assert-event (equal (hpich-test-local 0 :status) '(t t nil nil)))
; Supported phase positive; complete literal premise/conclusion.
(assert-event (equal (hpich-test-local 1 :positive) '(t t t t)))
; Labelled removal/mutation: ready; complete literal premise/conclusion.
(assert-event (equal (hpich-test-local 1 :ready) '(t nil t nil)))
; Labelled removal/mutation: status; complete literal premise/conclusion.
(assert-event (equal (hpich-test-local 1 :status) '(t t nil nil)))
; Supported phase positive; complete literal premise/conclusion.
(assert-event (equal (hpich-test-local 2 :positive) '(t t t t)))
; Labelled removal/mutation: ready; complete literal premise/conclusion.
(assert-event (equal (hpich-test-local 2 :ready) '(t nil t nil)))
; Labelled removal/mutation: status; complete literal premise/conclusion.
(assert-event (equal (hpich-test-local 2 :status) '(t t nil nil)))
; Supported phase positive; complete literal premise/conclusion.
(assert-event (equal (hpich-test-local 3 :positive) '(t t t t)))
; Labelled removal/mutation: ready; complete literal premise/conclusion.
(assert-event (equal (hpich-test-local 3 :ready) '(t nil t nil)))
; Labelled removal/mutation: status; complete literal premise/conclusion.
(assert-event (equal (hpich-test-local 3 :status) '(t t nil nil)))
