(in-package "ACL2")
(include-book "../../books/history-decode-completion")
(defun fn-csz-test-feed (bytes s infos prefix usable)
  (declare (xargs :verify-guards nil))
  (if (consp bytes)
      (mv-let (next ni np nu) (fn-hds-feed (car bytes) s infos prefix usable)
        (fn-csz-test-feed (cdr bytes) next ni np nu))
    (list :parser-completion '(7 (9 10) 11 12) s infos prefix usable)))
(assert-event
 (mv-let (s infos prefix usable) (fn-hds-begin 0 1 7 '(9 10))
   (let ((bundle (fn-csz-test-feed '(0) s infos prefix usable)))
    (equal (car (mv-list 6 (fn-hds-completion 0 bundle '(7 (9 10) 11 12)))) :ok))))
(assert-event
 (mv-let (s infos prefix usable) (fn-hds-begin 0 1 7 '(9 10))
   (let ((bundle (fn-csz-test-feed '(0) s infos prefix usable)))
    (equal (car (mv-list 6 (fn-hds-completion 0 bundle '(7 (9 11) 11 12)))) :refused))))
(assert-event
 (let* ((value '(:ok 0 nil nil 0 nil)) (bytes (fn-scc-program value)))
  (mv-let (s infos prefix usable) (fn-hds-begin 0 (len bytes) 7 '(9 10))
   (let* ((bundle (fn-csz-test-feed bytes s infos prefix usable))
          (result (mv-list 6 (fn-hds-completion 6 bundle '(7 (9 10) 11 12)))))
    (and (equal (car result) :ok) (equal (nth 2 result) (fn-scs-summary value))
         (equal (nth 3 result) (list (fn-scs-summary :ok) (fn-scs-summary 0)
                                     (fn-scs-summary nil) (fn-scs-summary nil)
                                     (fn-scs-summary 0) (fn-scs-summary nil)))
         (equal (nth 4 result) 7) (equal (nth 5 result) '(9 10)))))))
(assert-event
 (let* ((value '(:checkpoint 1 nil 0 nil nil nil)) (bytes (fn-scc-program value)))
  (mv-let (s infos prefix usable) (fn-hds-begin 0 (len bytes) 7 '(9 10))
   (let* ((bundle (fn-csz-test-feed bytes s infos prefix usable))
          (result (mv-list 6 (fn-hds-completion 7 bundle '(7 (9 10) 11 12)))))
    (and (equal (car result) :ok) (equal (nth 2 result) (fn-scs-summary value))
         (equal (len (nth 3 result)) 7))))))
