(in-package "ACL2")
(include-book "../../books/history-event-backing")
; Explicit test-only construction/registration. This fixture is NOT a served
; issuer, installation, allocator grant or atomic raw publication argument.
(defconst *hept-token* '(:history-operation 7))
(defconst *hept-leaf* '(:history-leaf 0 17 0 1 0))
(defconst *hept-old* '(:history-source 20 1 21 nil 0 0 0 22))
(defconst *hept-next*
 (list :history-source 23 1 25 (list (list :history-block 1 0 *hept-leaf*)) 0 1 1 24))
(defconst *hept-receipt* '(:history-completion (:history-operation 7) 91))
(defconst *hept-produced* '(:context :fields :accepted :none nil :sizes))
(defun hept-init (fn-history-backing)
 (declare (xargs :stobjs fn-history-backing :verify-guards nil))
 (mv-let (word fn-history-backing)
  (stobj-let ((fn-hep-node (fn-hep-provider fn-history-backing)))
   (word fn-hep-node)
   (stobj-let ((fn-history-event-page
     (fn-hep-node-children-get 'fn-history-event-page fn-hep-node (create-fn-history-event-page))))
    (word fn-history-event-page)
    (fn-hec-initialize 1 17 0 0 fn-history-event-page)
    (mv word fn-hep-node))
   (mv word fn-history-backing))
  (let* ((fn-history-backing (update-fn-hep-installed-source *hept-old* fn-history-backing))
         (fn-history-backing (update-fn-hep-epoch
           '(:history-epoch 1 8 (:history-operation 7) :live t 0 1 (:page17) nil :debt nil)
           fn-history-backing))
         (fn-history-backing (update-fn-hep-producer-token *hept-token* fn-history-backing))
         (fn-history-backing (update-fn-hep-producer-phase :reserved fn-history-backing)))
   (mv word fn-history-backing))))
(defun hept-view (fn-history-backing)
 (declare (xargs :stobjs fn-history-backing :verify-guards nil))
 (list (fn-hep-current fn-history-backing) (fn-hep-epoch fn-history-backing)
       (fn-hep-builder fn-history-backing) (fn-hep-producer-token fn-history-backing)
       (fn-hep-producer-phase fn-history-backing) (fn-hep-producer-receipts fn-history-backing)
       (fn-hep-completion fn-history-backing) (fn-hep-capture fn-history-backing)))
(defun hept-lifecycle (fn-history-backing)
 (declare (xargs :stobjs fn-history-backing :verify-guards nil))
 (mv-let (init fn-history-backing) (hept-init fn-history-backing)
  (let ((preflight (and (eq init :initialized) (fn-hep-offer-currentp *hept-token* fn-history-backing))))
   (mv-let (offer fn-history-backing)
    (fn-hep-offer-produced nil *hept-produced* :context :fields *hept-token* fn-history-backing)
    (mv-let (readout row produced context fields) (fn-hep-builder-readout fn-history-backing)
     (let* ((retained (and preflight (eq offer :offered) (eq readout :candidate)
                           (null row) (equal produced *hept-produced*)
                           (eq context :context) (eq fields :fields)))
            (fn-history-backing (update-fn-hep-producer-receipts
              (list :history-preparation *hept-token* 91 *hept-next* *hept-leaf* 0 :actual-owner-result)
              fn-history-backing))
            (fn-history-backing (update-fn-hep-producer-phase :prepared fn-history-backing))
            (before (hept-view fn-history-backing)))
      (mv-let (wrong fn-history-backing)
       (fn-hep-register-completion-internal '(:history-completion (:history-operation 7) 92)
                                            *hept-token* fn-history-backing)
       (let ((wrong-ok (and retained (eq wrong :unavailable) (equal before (hept-view fn-history-backing)))))
        (mv-let (completed fn-history-backing)
         (fn-hep-register-completion-internal *hept-receipt* *hept-token* fn-history-backing)
         (let ((antecedent (and wrong-ok (eq completed :completed)
                                (fn-hep-completion-matchesp *hept-receipt* *hept-token* fn-history-backing)
                                (eq (fn-hep-producer-phase fn-history-backing) :completed)
                                (equal (fn-hep-completion fn-history-backing) *hept-receipt*)))
               (completed-view (hept-view fn-history-backing)))
          (mv-let (repeat fn-history-backing)
           (fn-hep-register-completion-internal *hept-receipt* *hept-token* fn-history-backing)
           (let ((repeat-ok (and antecedent (eq repeat :already-completed)
                                 (equal completed-view (hept-view fn-history-backing)))))
            (mv-let (published fn-history-backing) (fn-hep-publish-current *hept-receipt* fn-history-backing)
             (let ((publication (and repeat-ok (eq published :published)
                                    (equal (fn-hep-current fn-history-backing) *hept-next*)
                                    (eq (fn-hep-producer-phase fn-history-backing) :published)))
                   (published-view (hept-view fn-history-backing)))
              (mv-let (word row left) (fn-hep-page-read *hept-next* *hept-leaf* 0 1 1 fn-history-backing)
               (let ((row-ok (and publication (eq word :row) (null row) (equal left 0))))
                (mv-let (duplicate fn-history-backing) (fn-hep-publish-current *hept-receipt* fn-history-backing)
                 (mv (and row-ok (eq duplicate :consumed)
                          (equal published-view (hept-view fn-history-backing))) fn-history-backing)))))))))))))))))
)
(defun hept-run ()
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-history-backing
  (mv-let (ok fn-history-backing) (hept-lifecycle fn-history-backing) ok)))
(assert-event (hept-run))
(defun hept-default-step (fn-history-backing)
 (declare (xargs :stobjs fn-history-backing :verify-guards nil))
 (mv-let (word fn-history-backing) (fn-hep-publish-current nil fn-history-backing)
  (mv (and (eq word :unavailable) (null (fn-hep-current fn-history-backing))
           (not (fn-hep-offer-currentp *hept-token* fn-history-backing))) fn-history-backing)))
(defun hept-default ()
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-history-backing
  (mv-let (ok fn-history-backing) (hept-default-step fn-history-backing) ok)))
(assert-event (hept-default))
(defun hept-fence-step (fn-history-backing)
 (declare (xargs :stobjs fn-history-backing :verify-guards nil))
 (mv-let (init fn-history-backing) (hept-init fn-history-backing)
  (mv-let (offer fn-history-backing)
   (fn-hep-offer-produced :event *hept-produced* :context :fields *hept-token* fn-history-backing)
   (let ((before (hept-view fn-history-backing)))
    (mv-let (word fn-history-backing) (fn-hep-fence-current *hept-token* fn-history-backing)
     (let ((after (hept-view fn-history-backing)))
      (mv-let (publish fn-history-backing) (fn-hep-publish-current *hept-receipt* fn-history-backing)
       (mv (and (eq init :initialized) (eq offer :offered) (eq word :recovery-required)
                (equal after (update-nth 4 :fenced before))
                (eq publish :unavailable) (equal after (hept-view fn-history-backing))
                (not (fn-hep-offer-currentp *hept-token* fn-history-backing))) fn-history-backing))))))))
(defun hept-fence ()
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-history-backing
  (mv-let (ok fn-history-backing) (hept-fence-step fn-history-backing) ok)))
(assert-event (hept-fence))
; Conditional retirement storage fixture: registered physical-return producer
; remains absent. The fixed fixture payload below is NOT an allocator grant.
(defun hept-retire-step (fn-history-backing)
 (declare (xargs :stobjs fn-history-backing :verify-guards nil))
 (let* ((epoch '(:history-epoch 1 8 (:history-operation 7) :retiring nil 0 0
                 (17 18) nil :retained-debt nil))
        (fn-history-backing (update-fn-hep-epoch epoch fn-history-backing))
        (fn-history-backing (update-fn-hep-retirement-cursor
          '(:history-handle-return 1 (:history-operation 7) :page 17 (:physical-release-fixture))
          fn-history-backing)))
  (mv-let (word fn-history-backing) (fn-hep-retire-return-internal fn-history-backing)
   (let ((once (and (eq word :retired-handle)
                    (equal (fn-hep-epoch fn-history-backing) (update-nth 8 '(18) epoch))
                    (null (fn-hep-retirement-cursor fn-history-backing))))
         (after (hept-view fn-history-backing)))
    (mv-let (repeat fn-history-backing) (fn-hep-retire-return-internal fn-history-backing)
     (mv (and once (eq repeat :unavailable) (equal after (hept-view fn-history-backing)))
         fn-history-backing))))))
(defun hept-retire ()
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-history-backing
  (mv-let (ok fn-history-backing) (hept-retire-step fn-history-backing) ok)))
(assert-event (hept-retire))
