(in-package "ACL2")
(include-book "../../books/history-pool-columns")
(defun hpcs-test-run (fuel c pool fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb)
  (declare (xargs :stobjs (fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb) :verify-guards nil :measure (nfix fuel)))
  (if (zp fuel) (mv :fuel nil c fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb)
    (mv-let (v n next fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb) (fn-hpcx-tick c fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb)
      (cond ((member-eq v '(:continue :columns :column-stored))
             (hpcs-test-run (1- fuel) next pool fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb))
            ((fn-hsrcb-demandp v)
             (mv-let (sv supplied fn-hpb)
               (fn-hpcx-supply c (fn-hrcur-field 1 v)
                                (nth (fn-hrcur-field 1 v) pool) fn-hpb)
               (if (eq sv :continue) (hpcs-test-run (1- fuel) supplied pool fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb)
                 (mv sv nil supplied fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb))))
            (t (mv v n next fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb))))))

(defun hpcs-test-one ()
  (declare (xargs :verify-guards nil))
(with-local-stobj fn-hpq0
 (mv-let (ok fn-hpq0)
 (with-local-stobj fn-hpq1
 (mv-let (ok fn-hpq0 fn-hpq1)
 (with-local-stobj fn-hpq2
 (mv-let (ok fn-hpq0 fn-hpq1 fn-hpq2)
 (with-local-stobj fn-hpq3
 (mv-let (ok fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3)
 (with-local-stobj fn-hpb
 (mv-let (ok fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb)
 (mv-let (fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb) (fn-hpq-begin :capture :lease fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb)
 (let* ((row "ABC") (encoded (len (fn-scc-encode row)))
        (padded (+ encoded (fn-hp-pad8-count encoded)))
        (key (fn-hp-mkey row 17)) (token '(7 (9 1) 1 0))
        (initial (fn-hpcx-begin 1 padded token :capture :lease)))
  (mv-let (offered c)
    (fn-hpcx-offer initial 0 '(:decoded (:span 3 0 1 3)) token key)
    (mv-let (v n final fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb) (hpcs-test-run 200 c '(0 65 66 67) fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb)
      (mv (and (eq offered :started) (eq v :row-done) (equal n encoded)
               (fn-hpcx-shapep final) (eq (fn-hrcur-field 0 final) :prepared)
               (equal (fn-hrcur-field 2 final) 1)
               (equal (fn-hrcur-field 3 final) padded)
               (equal (fn-hpb-prefix fn-hpq0) (list key))
               (equal (fn-hpb-prefix fn-hpq1) (list encoded))
               (equal (fn-hpb-prefix fn-hpq2) '(0))
               (equal (fn-hpb-prefix fn-hpq3) (list padded))
               (equal (fn-hpb-prefix fn-hpb) (fn-hp-pack8 (ceiling padded 8) (fn-scc-encode row))))
          fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb)))))
 (mv ok fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3)))
 (mv ok fn-hpq0 fn-hpq1 fn-hpq2)))
 (mv ok fn-hpq0 fn-hpq1)))
 (mv ok fn-hpq0)))
 ok)))
(assert-event (hpcs-test-one))
