(in-package "ACL2")
(include-book "../../books/history-auth-reader-frontier")

; Test-only bounded seeker over actual operations, no invented intermediate
; cursor. The general scheduling theorems use no fuel or source size ceiling.
(defun fn-hsr-digest-test-seek (fuel mode side pgs-digest-state)
  (declare (xargs :stobjs pgs-digest-state :measure (nfix fuel) :verify-guards nil))
  (if (or (zp fuel)
          (and (equal (pgs-dc-mode pgs-digest-state) mode)
               (or (not side)
                   (and (posp (pgs-dc-depth pgs-digest-state))
                        (equal (fn-b3-nthx 0 (pgs-dc-framesi (1- (pgs-dc-depth pgs-digest-state)) pgs-digest-state)) side)))))
      pgs-digest-state
    (mv-let (status pgs-digest-state) (pgs-dc-step nil pgs-digest-state)
      (declare (ignore status))
      (fn-hsr-digest-test-seek (1- fuel) mode side pgs-digest-state))))

(defun-nx fn-hsr-digest-test-state (mode side)
  (fn-hsr-digest-test-seek 500 mode side
    (pgs-dc-begin 0 0 256 :captured :lease (create-pgs-digest-state))))

(defthm fn-hsr-digest-order-begin-positive
  (let ((nb 256))
    (and (natp nb)
         (fn-hsr-digest-orderp (pgs-dc-begin 0 0 nb :captured :lease (create-pgs-digest-state)))))
  :hints (("Goal" :in-theory (enable fn-hsr-digest-orderp fn-hsr-digest-end-stackp)))
  :rule-classes nil)

; One reachable witness per actual scheduling phase, including both kinds of
; frame return. Each asserts the complete literal antecedent and conclusion.
(defthm fn-hsr-digest-order-node-positive
  (let* ((cursor (fn-hsr-digest-test-state :node nil))
         (next (mv-nth 1 (pgs-dc-step nil cursor))))
    (and (equal (pgs-dc-mode cursor) :node)
         (pgs-dcd-domainp 4 cursor) (fn-hsr-digest-orderp cursor)
         (fn-hsr-digest-orderp next)
         (equal (fn-hsr-digest-frontier next)
                (+ (fn-hsr-digest-frontier cursor) (pgs-dc-read-demand cursor)))))
  :hints (("Goal" :expand ((:free (end total cursor) (fn-hsr-digest-end-stackp 4 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 3 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 2 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 1 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 0 end total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 4 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 3 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 2 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 1 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 0 limit total cursor)))
                  :in-theory (enable fn-hsr-digest-orderp fn-hsr-digest-end-stackp fn-hsr-digest-frontier
                                     pgs-dc-framesi fn-b3-nthx
                                   pgs-dcd-domainp pgs-dcd-framesp pgs-dcd-powerp)))
  :rule-classes nil)
(defthm fn-hsr-digest-order-split-positive
  (let* ((cursor (fn-hsr-digest-test-state :split nil))
         (next (mv-nth 1 (pgs-dc-step nil cursor))))
    (and (equal (pgs-dc-mode cursor) :split)
         (pgs-dcd-domainp 4 cursor) (fn-hsr-digest-orderp cursor)
         (fn-hsr-digest-orderp next)
         (equal (fn-hsr-digest-frontier next)
                (+ (fn-hsr-digest-frontier cursor) (pgs-dc-read-demand cursor)))))
  :hints (("Goal" :expand ((:free (end total cursor) (fn-hsr-digest-end-stackp 4 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 3 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 2 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 1 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 0 end total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 4 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 3 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 2 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 1 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 0 limit total cursor)))
                  :in-theory (enable fn-hsr-digest-orderp fn-hsr-digest-end-stackp fn-hsr-digest-frontier
                                     pgs-dc-framesi fn-b3-nthx
                                   pgs-dcd-domainp pgs-dcd-framesp pgs-dcd-powerp)))
  :rule-classes nil)
(defthm fn-hsr-digest-order-chunk-positive
  (let* ((cursor (fn-hsr-digest-test-state :chunk nil))
         (next (mv-nth 1 (pgs-dc-step nil cursor))))
    (and (equal (pgs-dc-mode cursor) :chunk)
         (pgs-dcd-domainp 4 cursor) (fn-hsr-digest-orderp cursor)
         (fn-hsr-digest-orderp next)
         (equal (fn-hsr-digest-frontier next)
                (+ (fn-hsr-digest-frontier cursor) (pgs-dc-read-demand cursor)))))
  :hints (("Goal" :expand ((:free (end total cursor) (fn-hsr-digest-end-stackp 4 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 3 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 2 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 1 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 0 end total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 4 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 3 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 2 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 1 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 0 limit total cursor)))
                  :in-theory (enable fn-hsr-digest-orderp fn-hsr-digest-end-stackp fn-hsr-digest-frontier
                                     pgs-dc-framesi fn-b3-nthx
                                   pgs-dcd-domainp pgs-dcd-framesp pgs-dcd-powerp)))
  :rule-classes nil)
(defthm fn-hsr-digest-order-left-return-positive
  (let* ((cursor (fn-hsr-digest-test-state :return :left))
         (next (mv-nth 1 (pgs-dc-step nil cursor))))
    (and (equal (pgs-dc-mode cursor) :return)
         (pgs-dcd-domainp 4 cursor) (fn-hsr-digest-orderp cursor)
         (fn-hsr-digest-orderp next)
         (equal (fn-hsr-digest-frontier next)
                (+ (fn-hsr-digest-frontier cursor) (pgs-dc-read-demand cursor)))))
  :hints (("Goal" :expand ((:free (end total cursor) (fn-hsr-digest-end-stackp 4 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 3 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 2 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 1 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 0 end total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 4 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 3 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 2 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 1 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 0 limit total cursor)))
                  :in-theory (enable fn-hsr-digest-orderp fn-hsr-digest-end-stackp fn-hsr-digest-frontier
                                     pgs-dc-framesi fn-b3-nthx
                                   pgs-dcd-domainp pgs-dcd-framesp pgs-dcd-powerp)))
  :rule-classes nil)
(defthm fn-hsr-digest-order-right-return-positive
  (let* ((cursor (fn-hsr-digest-test-state :return :right))
         (next (mv-nth 1 (pgs-dc-step nil cursor))))
    (and (equal (pgs-dc-mode cursor) :return)
         (pgs-dcd-domainp 4 cursor) (fn-hsr-digest-orderp cursor)
         (fn-hsr-digest-orderp next)
         (equal (fn-hsr-digest-frontier next)
                (+ (fn-hsr-digest-frontier cursor) (pgs-dc-read-demand cursor)))))
  :hints (("Goal" :expand ((:free (end total cursor) (fn-hsr-digest-end-stackp 4 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 3 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 2 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 1 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 0 end total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 4 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 3 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 2 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 1 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 0 limit total cursor)))
                  :in-theory (enable fn-hsr-digest-orderp fn-hsr-digest-end-stackp fn-hsr-digest-frontier
                                     pgs-dc-framesi fn-b3-nthx
                                   pgs-dcd-domainp pgs-dcd-framesp pgs-dcd-powerp)))
  :rule-classes nil)
(defthm fn-hsr-digest-order-root-positive
  (let* ((cursor (fn-hsr-digest-test-state :root nil))
         (next (mv-nth 1 (pgs-dc-step nil cursor))))
    (and (equal (pgs-dc-mode cursor) :root)
         (pgs-dcd-domainp 4 cursor) (fn-hsr-digest-orderp cursor)
         (fn-hsr-digest-orderp next)
         (equal (fn-hsr-digest-frontier next)
                (+ (fn-hsr-digest-frontier cursor) (pgs-dc-read-demand cursor)))))
  :hints (("Goal" :expand ((:free (end total cursor) (fn-hsr-digest-end-stackp 4 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 3 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 2 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 1 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 0 end total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 4 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 3 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 2 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 1 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 0 limit total cursor)))
                  :in-theory (enable fn-hsr-digest-orderp fn-hsr-digest-end-stackp fn-hsr-digest-frontier
                                     pgs-dc-framesi fn-b3-nthx
                                   pgs-dcd-domainp pgs-dcd-framesp pgs-dcd-powerp)))
  :rule-classes nil)
(defthm fn-hsr-digest-order-done-positive
  (let* ((cursor (fn-hsr-digest-test-state :done nil))
         (next (mv-nth 1 (pgs-dc-step nil cursor))))
    (and (equal (pgs-dc-mode cursor) :done)
         (pgs-dcd-domainp 4 cursor) (fn-hsr-digest-orderp cursor)
         (fn-hsr-digest-orderp next)
         (equal (fn-hsr-digest-frontier next)
                (+ (fn-hsr-digest-frontier cursor) (pgs-dc-read-demand cursor)))))
  :hints (("Goal" :expand ((:free (end total cursor) (fn-hsr-digest-end-stackp 4 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 3 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 2 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 1 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 0 end total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 4 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 3 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 2 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 1 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 0 limit total cursor)))
                  :in-theory (enable fn-hsr-digest-orderp fn-hsr-digest-end-stackp fn-hsr-digest-frontier
                                     pgs-dc-framesi fn-b3-nthx
                                   pgs-dcd-domainp pgs-dcd-framesp pgs-dcd-powerp)))
  :rule-classes nil)

; Deliberately corrupted-state hypothesis removals. Every retained literal
; premise is affirmed, the omitted one fails, and the full conclusion fails.
(defthm fn-hsr-digest-begin-natural-removal
  (let ((nb -1))
    (and (not (natp nb))
         (not (fn-hsr-digest-orderp (pgs-dc-begin 0 0 nb :captured :lease (create-pgs-digest-state))))))
  :hints (("Goal" :expand ((:free (end total cursor) (fn-hsr-digest-end-stackp 4 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 3 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 2 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 1 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 0 end total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 4 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 3 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 2 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 1 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 0 limit total cursor)))
                  :in-theory (e/d (pgs-dc-begin update-pgs-dc-mode update-pgs-dc-power fn-hsr-digest-orderp fn-hsr-digest-end-stackp fn-hsr-digest-frontier
                                     pgs-dc-framesi fn-b3-nthx
                                   pgs-dcd-domainp pgs-dcd-framesp pgs-dcd-powerp)
                                   ((:executable-counterpart pgs-dc-begin) (:executable-counterpart update-pgs-dc-power)))))
  :rule-classes nil)
(defthm fn-hsr-digest-step-domain-removal
  (let* ((cursor (update-pgs-dc-mode :split
                   (update-pgs-dc-pos 192 (pgs-dc-begin 0 0 32 :captured :lease (create-pgs-digest-state)))))
         (next (mv-nth 1 (pgs-dc-step nil cursor))))
    (and (fn-hsr-digest-orderp cursor) (not (pgs-dcd-domainp 4 cursor))
         (not (fn-hsr-digest-orderp next))))
  :hints (("Goal" :expand ((:free (end total cursor) (fn-hsr-digest-end-stackp 4 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 3 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 2 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 1 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 0 end total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 4 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 3 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 2 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 1 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 0 limit total cursor)))
                  :in-theory (e/d (pgs-dc-step pgs-dc-begin update-pgs-dc-mode update-pgs-dc-power fn-hsr-digest-orderp fn-hsr-digest-end-stackp fn-hsr-digest-frontier
                                     pgs-dc-framesi fn-b3-nthx
                                   pgs-dcd-domainp pgs-dcd-framesp pgs-dcd-powerp)
                                   ((:executable-counterpart pgs-dc-step) (:executable-counterpart update-pgs-dc-end) (:executable-counterpart update-pgs-dc-framesi) (:executable-counterpart update-pgs-dc-depth) (:executable-counterpart pgs-dc-begin) (:executable-counterpart update-pgs-dc-power)))))
  :rule-classes nil)
(defthm fn-hsr-digest-step-order-removal
  (let* ((cursor (update-pgs-dc-framesi 0 '(:left 1025 2048 8 nil)
                   (fn-hsr-digest-test-state :chunk nil)))
         (next (mv-nth 1 (pgs-dc-step nil cursor))))
    (and (pgs-dcd-domainp 4 cursor) (not (fn-hsr-digest-orderp cursor))
         (not (fn-hsr-digest-orderp next))))
  :hints (("Goal" :expand ((:free (end total cursor) (fn-hsr-digest-end-stackp 4 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 3 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 2 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 1 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 0 end total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 4 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 3 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 2 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 1 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 0 limit total cursor)))
                  :in-theory (e/d (pgs-dc-begin update-pgs-dc-mode update-pgs-dc-power fn-hsr-digest-orderp fn-hsr-digest-end-stackp fn-hsr-digest-frontier
                                     pgs-dc-framesi fn-b3-nthx
                                   pgs-dcd-domainp pgs-dcd-framesp pgs-dcd-powerp)
                                   ((:executable-counterpart pgs-dc-begin) (:executable-counterpart update-pgs-dc-power)))))
  :rule-classes nil)
(defthm fn-hsr-digest-frontier-order-removal
  (let* ((cursor (update-pgs-dc-framesi 3 '(:left 129 256 1 nil)
                   (fn-hsr-digest-test-state :return :left)))
         (next (mv-nth 1 (pgs-dc-step nil cursor))))
    (and (not (fn-hsr-digest-orderp cursor))
         (not (equal (fn-hsr-digest-frontier next)
                     (+ (fn-hsr-digest-frontier cursor) (pgs-dc-read-demand cursor))))))
  :hints (("Goal" :expand ((:free (end total cursor) (fn-hsr-digest-end-stackp 4 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 3 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 2 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 1 end total cursor))
                           (:free (end total cursor) (fn-hsr-digest-end-stackp 0 end total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 4 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 3 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 2 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 1 limit total cursor))
                           (:free (limit total cursor) (pgs-dcd-framesp 0 limit total cursor)))
                  :in-theory (e/d (pgs-dc-begin update-pgs-dc-mode update-pgs-dc-power fn-hsr-digest-orderp fn-hsr-digest-end-stackp fn-hsr-digest-frontier
                                     pgs-dc-framesi fn-b3-nthx
                                   pgs-dcd-domainp pgs-dcd-framesp pgs-dcd-powerp)
                                   ((:executable-counterpart pgs-dc-begin) (:executable-counterpart update-pgs-dc-power)))))
  :rule-classes nil)
