(in-package "ACL2")
(include-book "../../books/history-pool-emitter")

(defun hpes-test-drive (fuel c pool fn-hpb)
  (declare (xargs :stobjs fn-hpb :verify-guards nil :measure (nfix fuel)))
  (if (zp fuel) (mv :fuel nil c fn-hpb)
    (mv-let (v n next fn-hpb) (fn-hpe-tick c fn-hpb)
      (cond ((eq v :continue) (hpes-test-drive (1- fuel) next pool fn-hpb))
            ((fn-hsrcb-demandp v)
             (mv-let (sv supplied fn-hpb)
               (fn-hpe-supply c (fn-hrcur-field 1 v)
                              (nth (fn-hrcur-field 1 v) pool) fn-hpb)
               (if (eq sv :continue) (hpes-test-drive (1- fuel) supplied pool fn-hpb)
                 (mv sv nil supplied fn-hpb))))
            (t (mv v n next fn-hpb))))))

(defun hpes-test-cold (source pool model)
  (declare (xargs :verify-guards nil))
  (with-local-stobj fn-hpb
    (mv-let (ok fn-hpb)
      (let ((fn-hpb (fn-hpb-begin :epoch :lease fn-hpb)))
        (mv-let (v n final fn-hpb)
          (hpes-test-drive 300 (fn-hpe-begin source :epoch :lease) pool fn-hpb)
          (mv (and (eq v :prepared) (equal n (len (fn-scc-encode model)))
                   (fn-hpe-shapep final) (fn-hpbp fn-hpb)
                   (equal (fn-hpb-prefix fn-hpb)
                          (fn-hp-pack8 (ceiling (len (fn-scc-encode model)) 8)
                            (fn-scc-encode model))))
              fn-hpb))) ok)))

(assert-event (hpes-test-cold '(:decoded (:span 3 0 1 3)) '(0 65 66 67) "ABC"))
(assert-event (hpes-test-cold '(:decoded (:span 6 0 1 8)) '(0 1 2 3 4 5 6 7 8)
                            '(1 2 3 4 5 6 7 8)))
