; Actual directory metadata phase, not a native qualification witness.
(in-package "ACL2")
(include-book "../../books/history-image-canonical-refinement")
(include-book "../../books/history-image-table-refinement")
(include-book "history-image-writer-refinement-tests")

(local (defun hpic-test-until-directory (fuel stop c observation ledger pages spools rows source pool key
                    fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
  (declare (xargs :stobjs (fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
                  :verify-guards nil :measure (nfix fuel)
                  :hints (("Goal" :in-theory (disable fn-hpi-tick fn-hpi-offer
                     fn-omk-at hpi-test-buffer pgs-words-le-octets)))))
  (if (zp fuel)
      (mv (list :fuel c pages spools rows) fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
    (mv-let (v effect next ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
      (fn-hpi-tick c observation ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
      (let ((tag (fn-omk-at 0 effect)))
        (cond
         ((and (or (eq tag stop)
                   (and (eq stop :directory-begin) (eq v :continue)
                        (eq (fn-omk-at 0 next) :metadata)
                        (eq (fn-hpic-meta-field 0 next) :directory))
                   (and (eq stop :table-begin) (eq v :continue)
                        (eq (fn-omk-at 0 next) :metadata)
                        (eq (fn-hpic-meta-field 0 next) :table)
                        (equal (fn-hpic-meta-field 6 next) 0))
                   (and (eq stop :directory-write) (eq tag :write-page)
                        (eq (fn-omk-at 4 effect) :directory)))
               (or (not (eq tag :read-spool)) (eq (fn-omk-at 4 effect) :table)))
          (mv (list :stopped v effect next ledger pages spools rows c)
              fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))
         ((eq v :prepared)
          (mv (list :prepared next pages spools rows) fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))
         ((eq v :need-row)
          (mv-let (offered next)
            (fn-hpi-offer next rows source (fn-omk-at 1 effect) key)
            (if (not (eq offered :started))
                (mv (list :offer-refused offered next) fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
              (hpic-test-until-directory (1- fuel) stop next nil ledger pages spools rows source pool key
                            fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))))
         ((member-eq v '(:funded :continue :written :row-done :need-byte :write :io))
          (let* ((rows (if (eq v :row-done) (+ 1 rows) rows))
                 (pages (if (eq tag :write-page)
                            (acons (fn-omk-at 6 effect)
                                   (hpi-test-buffer (fn-omk-at 0 (fn-omk-at 17 next))
                                                    fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb)
                                   pages) pages))
                 (spools (if (eq tag :write-spool)
                             (acons (cons (fn-omk-at 4 effect) (fn-omk-at 5 effect))
                                    (fn-omk-at 9 effect) spools) spools))
                 (obs
                   (cond
                    ((eq v :need-byte)
                     (list :supply (fn-omk-at 1 effect) (nth (fn-omk-at 1 effect) pool)))
                    ((eq tag :write-page)
                     (list :written (fn-omk-at 1 effect) (fn-omk-at 2 effect)
                           (fn-omk-at 3 effect) (fn-omk-at 9 effect) :ok))
                    ((eq tag :write-spool)
                     (list :spool-written (fn-omk-at 1 effect) (fn-omk-at 2 effect)
                           (fn-omk-at 3 effect) (fn-omk-at 4 effect) (fn-omk-at 5 effect)
                           (fn-omk-at 8 effect) :ok))
                    ((member-eq tag '(:read-stage :read-spool))
                     (let* ((offset (fn-omk-at 6 effect))
                            (bytes (if (eq tag :read-stage)
                                       (pgs-words-le-octets
                                         (cdr (assoc-equal (floor (- offset 16384) 16384) pages)))
                                     (cdr (assoc-equal (cons (fn-omk-at 4 effect)
                                                            (fn-omk-at 5 effect)) spools))))
                            (offset (if (eq tag :read-stage) (mod offset 16384) 0)))
                       (list (if (eq tag :read-stage) :image-read :spool-read)
                             (fn-omk-at 1 effect) (fn-omk-at 2 effect)
                             (fn-omk-at 3 effect) (fn-omk-at 4 effect) (fn-omk-at 5 effect)
                             (fn-omk-at 8 effect) :ok
                             (take (fn-omk-at 7 effect) (nthcdr offset bytes)))))
                    (t nil))))
            (hpic-test-until-directory (1- fuel) stop next obs ledger pages spools rows source pool key
                          fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)))
         (t (mv (list :unexpected v next effect) fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))))))))

(local (defun hpic-test-more-directory (fuel c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
 (declare (xargs :stobjs (fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
                 :verify-guards nil :measure (nfix fuel)
                 :hints (("Goal" :in-theory (disable fn-hpi-tick)))))
 (if (zp fuel)
  (mv :continue c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
  (mv-let (v e c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
   (fn-hpi-tick c nil ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
   (declare (ignore e))
   (if (eq v :continue)
    (hpic-test-more-directory (1- fuel) c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
    (mv v c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))))))

(local (defun hpic-test-directory-point (mode fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
 (declare (xargs :stobjs (fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) :verify-guards nil))
 (mv-let (admitted maintenance ledger)
  (fn-pmn-admit (fn-prl-make '(10000000 10000000 4 1 10)) 7 1 '(1000000 16384 3 1 1))
  (let ((initial (fn-hpi-begin 1 8 1 1 '(7 (9 1) 0 0) maintenance (fn-omk-at 1 maintenance)
                  10000000 "node" 17 "trail")))
   (mv-let (r fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
    (hpic-test-until-directory 50000 :read-spool initial nil ledger nil nil 0
      '(:decoded (:span 3 0 1 3)) '(0 65 66 67) (fn-hp-mkey "ABC" 17)
      fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
    (let* ((effect (nth 2 r)) (c (nth 3 r)) (ledger (nth 4 r))
           (bytes (cdr (assoc-equal (cons :table 0) (nth 6 r))))
           (digests (list (pgs-octets-be-nat bytes)))
           (observation (fn-hie-observation c effect (fn-omk-at 3 c) ledger 32 :ok bytes)))
     (mv-let (read-status read-effect c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
      (fn-hpi-tick c observation ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
      (declare (ignore read-effect))
      (mv-let (a ae c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
       (fn-hpi-tick c nil ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
       (declare (ignore ae))
       (mv-let (b be c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
        (fn-hpi-tick c nil ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
        (declare (ignore be))
        (mv-let (more c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
         (hpic-test-more-directory (if (eq mode :padding) 4 0) c ledger
            fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
        (let* ((original c)
               (c (case mode (:invariant (fn-hpi-set 21 (list :digest 0 0) c))
                             (:status (fn-hpi-set 21 nil c))
                             (:padding (fn-hpi-set 21 (list :digest 1 17) c)) (otherwise c)))
               (inv (fn-hpic-directory-invariantp c digests fn-hpb))
               (old-prefix (fn-hpb-prefix fn-hpb)) (old-used (fn-hpb-used fn-hpb))
               (target (fn-hpic-directory-model c digests))
               (word (nth (+ (* 6 (fn-hpic-meta-field 1 c)) (fn-hpic-meta-field 2 c)) target))
               (old-model (hpiw-test-full-model fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))
               (old-ledger ledger))
         (mv-let (v e next ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
          (fn-hpi-tick c nil ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
          (declare (ignore e))
          (let* ((next-model (hpiw-test-full-model fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))
                 (law (and (equal (fn-hpb-prefix fn-hpb) (append old-prefix (list word)))
                           (equal ledger old-ledger)
                           (equal (take 4 next-model) (take 4 old-model))
                           (equal (nth 5 next-model) (nth 5 old-model))))
                 (next-inv (fn-hpic-directory-invariantp next digests fn-hpb))
                 (prefix-law (equal (fn-hpb-prefix fn-hpb)
                   (take (+ 1 old-used) (nthcdr (* 2048 (fn-hpic-meta-field 6 c)) target)))))
           (mv (and (eq admitted :admitted) (eq (car r) :stopped)
                    (eq (fn-omk-at 0 effect) :read-spool) (eq (fn-omk-at 4 effect) :table)
                    (eq read-status :continue) (eq a :continue) (eq b :continue) (eq more :continue)
                    (equal (fn-omk-at 0 original) :metadata)
                    (equal (fn-hpic-meta-field 0 original) :directory)
                    (equal (fn-hpic-meta-field 1 original) (if (eq mode :padding) 1 0))
                    (equal (fn-hpic-meta-field 2 original) (if (eq mode :padding) 0 2))
                    (equal old-used (if (eq mode :padding) 6 2))
                    (if (eq mode :padding)
                     (and (equal word 0)
                          (equal (fn-omk-at 1 (fn-omk-at 21 c)) (fn-hpic-meta-field 1 c))
                          (not (equal (fn-omk-at 2 (fn-omk-at 21 c)) (nth (fn-hpic-meta-field 1 c) digests))))
                     (not (equal word 0)))
                    (equal (list (if inv t nil) (equal v :continue))
                      (case mode (:invariant '(nil t)) (:status '(t nil)) (otherwise '(t t))))
                    (equal law (if (member-eq mode '(:positive :padding)) t nil))
                    (equal prefix-law (if (member-eq mode '(:positive :padding)) t nil))
                    (equal (if next-inv t nil) (if (member-eq mode '(:positive :padding)) t nil)))
               fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))))))))))))))

(local (defun hpic-test-local-directory-point (mode)
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-hpq0 (mv-let (result fn-hpq0) (with-local-stobj fn-hpq1 (mv-let (result fn-hpq0 fn-hpq1) (with-local-stobj fn-hpq2 (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2) (with-local-stobj fn-hpq3 (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3) (with-local-stobj fn-hpb (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb) (with-local-stobj pgs-digest-state (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) (hpic-test-directory-point mode fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) (mv result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb))) (mv result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3))) (mv result fn-hpq0 fn-hpq1 fn-hpq2))) (mv result fn-hpq0 fn-hpq1))) (mv result fn-hpq0))) result))))

; Actual reachable complete directory-word/prefix positive.
(local (assert-event (hpic-test-local-directory-point :positive)))

; Corrupt only current cached digest; continuation remains true.
(local (assert-event (hpic-test-local-directory-point :invariant)))

; Remove cached availability: actual query yields IO, canonical invariant remains true.
(local (assert-event (hpic-test-local-directory-point :status)))

; Labelled padding-cache mutation: a matching irrelevant cached ordinal
; disagrees with nth beyond the active digest list. The weakened carried
; invariant and complete actual continuation conclusion both remain true.
(local (assert-event (hpic-test-local-directory-point :padding)))


(local (defun hpic-test-page-point (mode fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
 (declare (xargs :stobjs (fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) :verify-guards nil))
 (mv-let (admitted maintenance ledger)
  (fn-pmn-admit (fn-prl-make '(10000000 10000000 4 1 10)) 7 1 '(1000000 16384 3 1 1))
  (let ((initial (fn-hpi-begin 1 8 1 1 '(7 (9 1) 0 0) maintenance (fn-omk-at 1 maintenance)
                  10000000 "node" 17 "trail")))
   (mv-let (r fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
    (hpic-test-until-directory 50000 :directory-write initial nil ledger nil nil 0
      '(:decoded (:span 3 0 1 3)) '(0 65 66 67) (fn-hp-mkey "ABC" 17)
      fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
    (let* ((actual-pre (nth 8 r)) (ledger (nth 4 r))
           (digests (list (pgs-octets-be-nat (cdr (assoc-equal (cons :table 0) (nth 6 r))))))
           (c (if (eq mode :handoff-status) (fn-hpi-set 22 nil actual-pre) actual-pre))
           (fn-hpb (if (eq mode :handoff-invariant)
                       (update-fn-hpb-wi 0 (+ 1 (fn-hpb-wi 0 fn-hpb)) fn-hpb) fn-hpb))
           (inv (fn-hpic-directory-invariantp c digests fn-hpb))
           (old-model (hpiw-test-full-model fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))
           (old-ledger ledger))
     (mv-let (v e next ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
      (fn-hpi-tick c nil ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
      (let* ((handoff-law
        (and (equal (fn-hpb-used fn-hpb) 2048)
             (equal e (fn-hpi-write-effect (fn-omk-at 1 c) (fn-omk-at 3 c)
                       (nfix (fn-omk-at 4 c)) :directory (fn-hpic-meta-field 6 c)
                       (+ 1 (fn-hpic-meta-field 6 c)) (nfix (fn-omk-at 4 (fn-omk-at 16 c)))))
             (equal (fn-hpb-prefix fn-hpb)
                    (take 2048 (nthcdr (* 2048 (fn-hpic-meta-field 6 c)) (fn-hpic-directory-model c digests))))
             (equal (fn-omk-at 0 next) :wait-write)
             (equal (fn-hpic-meta-field 6 next) (+ 1 (fn-hpic-meta-field 6 c)))
             (equal (fn-hpic-meta-field 1 next) (fn-hpic-meta-field 1 c))
             (equal (fn-hpic-meta-field 2 next) (fn-hpic-meta-field 2 c))
             (equal (fn-hpic-meta-field 3 next) (fn-hpic-meta-field 3 c))
             (equal ledger old-ledger)
             (equal (hpiw-test-full-model fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) old-model)))
             (handoff-check
              (and (equal (list (if inv t nil) (equal v :write))
                     (case mode (:handoff-invariant '(nil t)) (:handoff-status '(t nil)) (otherwise '(t t))))
                   (equal (if handoff-law t nil) (if (member-eq mode '(:handoff-invariant :handoff-status)) nil t)))))
       (if (member-eq mode '(:handoff-positive :handoff-invariant :handoff-status))
        (mv (and (eq admitted :admitted) (eq (car r) :stopped) handoff-check)
             fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
        (let* ((c (if (eq mode :reset-context)
                      (fn-hpi-set 17 (list 0 (fn-omk-at 1 (fn-omk-at 17 next))) next) next))
               (observation (list :written (fn-omk-at 1 e) (fn-omk-at 2 e)
                                  (+ (fn-omk-at 3 e) (if (eq mode :reset-status) 1 0))
                                  (fn-omk-at 9 e) :ok))
               (context (fn-hpic-scratch-ack-contextp c))
               (old-model (hpiw-test-full-model fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))
               (old-ledger ledger))
         (mv-let (v e next ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
          (fn-hpi-tick c observation ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
          (declare (ignore e))
          (let* ((next-model (hpiw-test-full-model fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))
                 (law
                  (and (equal (fn-hpi-written-status (fn-omk-at 5 c) observation) :written)
                       (equal (fn-omk-at 0 next) (fn-omk-at 1 (fn-omk-at 17 c)))
                       (equal (fn-omk-at 19 next) (fn-omk-at 19 c))
                       (equal (fn-omk-at 6 next) (fn-omk-at 6 c))
                       (equal (fn-omk-at 21 next) (fn-omk-at 21 c))
                       (equal (fn-omk-at 4 (fn-omk-at 16 next)) (+ 1 (nfix (fn-omk-at 4 (fn-omk-at 16 c)))))
                       (equal (fn-omk-at 5 next) nil) (equal (fn-omk-at 17 next) nil)
                       (equal (fn-hpb-prefix fn-hpb) nil)
                       (equal (nth 4 next-model) (list (car (nth 4 old-model)) 0 (fn-omk-at 1 c) (fn-omk-at 2 c)))
                       (equal ledger old-ledger) (equal (take 4 next-model) (take 4 old-model))
                       (equal (nth 5 next-model) (nth 5 old-model)))))
           (mv (and (eq admitted :admitted) (eq (car r) :stopped) handoff-check
                    (equal (list (if context t nil) (equal v :written))
                     (case mode (:reset-context '(nil t)) (:reset-status '(t nil)) (otherwise '(t t))))
                    (equal (if law t nil) (eq mode :reset-positive)))
               fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)))))))))))))

(local (defun hpic-test-local-page-point (mode)
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-hpq0 (mv-let (result fn-hpq0) (with-local-stobj fn-hpq1 (mv-let (result fn-hpq0 fn-hpq1) (with-local-stobj fn-hpq2 (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2) (with-local-stobj fn-hpq3 (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3) (with-local-stobj fn-hpb (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb) (with-local-stobj pgs-digest-state (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) (hpic-test-page-point mode fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) (mv result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb))) (mv result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3))) (mv result fn-hpq0 fn-hpq1 fn-hpq2))) (mv result fn-hpq0 fn-hpq1))) (mv result fn-hpq0))) result))))

; Whole actual directory page handoff and exact selected-scratch reset.
(local (assert-event (hpic-test-local-page-point :handoff-positive)))
; Corrupted scratch prefix, retained actual write status.
(local (assert-event (hpic-test-local-page-point :handoff-invariant)))
; Missing live receipt, retained canonical directory invariant.
(local (assert-event (hpic-test-local-page-point :handoff-status)))
(local (assert-event (hpic-test-local-page-point :reset-positive)))
; Corrupted retained buffer selector: exact ACK still succeeds for another buffer.
(local (assert-event (hpic-test-local-page-point :reset-context)))
; Stale ACK serial: scratch ACK context remains true, no reset or generation advance.
(local (assert-event (hpic-test-local-page-point :reset-status)))

; Constructed two-page DIRECTORY PHASE witnesses, not a completed image
; trajectory: a valid large layout and actual growth receipt are combined
; with its canonical current page. No huge backing file or image is built.
(local (defun hpic-test-fill-page (words fn-hpb)
 (declare (xargs :stobjs fn-hpb :verify-guards nil
                 :hints (("Goal" :in-theory (disable fn-hpb-put)))))
 (if (endp words) fn-hpb
  (mv-let (v fn-hpb) (fn-hpb-put (car words) fn-hpb)
   (declare (ignore v)) (hpic-test-fill-page (cdr words) fn-hpb)))))

(local (defun hpic-test-cross-page (mode fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
 (declare (xargs :stobjs (fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
                 :verify-guards nil))
 (mv-let (admitted maintenance ledger)
  (fn-pmn-admit (fn-prl-make '(10000000 5000000000 4 1 10)) 7 1 '(1000000 16384 3 1 1))
  (let ((initial (fn-hpi-begin 1 2147483648 1 131072 '(7 (9 1) 0 0)
                   maintenance (fn-omk-at 1 maintenance) 5000000000 "node" 17 "trail")))
   (mv-let (funded e c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
    (fn-hpi-tick initial nil ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
    (declare (ignore e))
    (let* ((layout (fn-omk-at 1 (fn-omk-at 6 c)))
           (digests (pgs-zeros (nfix (fn-omk-at 2 layout))))
           (finalp (eq mode :handoff-remaining)) (page (if finalp 1 0))
           (position (* 2048 (+ 1 page)))
           (ordinal (floor position 6)) (component (mod position 6))
           (remaining (- 4096 position))
           (c (fn-hpi-set 19 (list :directory ordinal component remaining (len digests)
                              (fn-omk-at 5 layout) page)
                (fn-hpi-set 21 (list :digest ordinal 0) (fn-hpi-set 0 :metadata c))))
           (words (take 2048 (nthcdr (* 2048 page) (fn-hpic-directory-model c digests))))
           (fn-hpb (fn-hpb-begin (fn-omk-at 1 c) (fn-omk-at 2 c) fn-hpb))
           (fn-hpb (hpic-test-fill-page words fn-hpb))
           (c (cond ((eq mode :handoff-invariant)
                     (fn-hpi-set 19 (fn-hpi-set 3 2047 (fn-omk-at 19 c)) c))
                    ((eq mode :handoff-status) (fn-hpi-set 22 nil c)) (t c)))
           (inv (fn-hpic-directory-invariantp c digests fn-hpb))
           (positive-remaining (posp (fn-hpic-meta-field 3 c))))
     (mv-let (v effect next ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
      (fn-hpi-tick c nil ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
      (let ((resume (fn-hpic-directory-resume-invariantp next digests)))
       (if (member-eq mode '(:handoff-positive :handoff-invariant :handoff-remaining :handoff-status))
        (mv (and (eq admitted :admitted) (eq funded :funded)
                 (equal (fn-omk-at 3 layout) 2)
                 (equal (list (if inv t nil) (if positive-remaining t nil) (eq v :write))
                   (case mode (:handoff-invariant '(nil t t))
                              (:handoff-remaining '(t nil t))
                              (:handoff-status '(t t nil)) (otherwise '(t t t))))
                 (equal (if resume t nil) (eq mode :handoff-positive)))
            fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
        (let* ((c (if (eq mode :resume-invariant)
                      (fn-hpi-set 19 (fn-hpi-set 3 2047 (fn-omk-at 19 next)) next) next))
               (before (fn-hpic-directory-resume-invariantp c digests))
               (obs (list :written (fn-omk-at 1 effect) (fn-omk-at 2 effect)
                          (+ (fn-omk-at 3 effect) (if (eq mode :resume-status) 1 0))
                          (fn-omk-at 9 effect) :ok)))
         (mv-let (v e next ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
          (fn-hpi-tick c obs ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
          (declare (ignore e ledger))
          (mv (and (eq admitted :admitted) (eq funded :funded) inv positive-remaining resume
                   (equal (list (if before t nil) (eq v :written))
                     (case mode (:resume-invariant '(nil t)) (:resume-status '(t nil)) (otherwise '(t t))))
                   (equal (if (fn-hpic-directory-invariantp next digests fn-hpb) t nil)
                          (eq mode :resume-positive)))
              fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))))))))))))

(local (defun hpic-test-local-cross-page (mode)
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-hpq0 (mv-let (result fn-hpq0) (with-local-stobj fn-hpq1 (mv-let (result fn-hpq0 fn-hpq1) (with-local-stobj fn-hpq2 (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2) (with-local-stobj fn-hpq3 (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3) (with-local-stobj fn-hpb (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb) (with-local-stobj pgs-digest-state (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) (hpic-test-cross-page mode fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) (mv result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb))) (mv result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3))) (mv result fn-hpq0 fn-hpq1 fn-hpq2))) (mv result fn-hpq0 fn-hpq1))) (mv result fn-hpq0))) result))))

(local (assert-event (hpic-test-local-cross-page :handoff-positive)))
(local (assert-event (hpic-test-local-cross-page :handoff-invariant)))
(local (assert-event (hpic-test-local-cross-page :handoff-remaining)))
(local (assert-event (hpic-test-local-cross-page :handoff-status)))
(local (assert-event (hpic-test-local-cross-page :resume-positive)))
(local (assert-event (hpic-test-local-cross-page :resume-invariant)))
(local (assert-event (hpic-test-local-cross-page :resume-status)))

; Constructed TABLE PHASE fixtures with a supported two-table layout.
; The scratch prefix is canonical and the stage grant is actual; this is
; not a complete large image/source-census/native execution witness.
(local (defun hpic-test-table-point (mode fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
 (declare (xargs :stobjs (fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) :verify-guards nil))
 (mv-let (admitted maintenance ledger)
  (fn-pmn-admit (fn-prl-make '(10000000 100000000 4 1 10)) 7 1 '(1000000 16384 3 1 1))
  (let ((initial (fn-hpi-begin 1 8388608 1 512 '(7 (9 1) 0 0) maintenance
                   (fn-omk-at 1 maintenance) 100000000 "node" 17 "trail")))
   (mv-let (funded e c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
    (fn-hpi-tick initial nil ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
    (declare (ignore e))
    (let* ((layout (fn-omk-at 1 (fn-omk-at 6 c)))
           (digests (update-nth 340 17 (pgs-zeros (nfix (fn-omk-at 1 layout)))))
           (c (fn-hpi-meta-begin :table 0 c))
           (c (fn-hpi-set 19 (fn-hpi-set 1 340 (fn-hpi-set 2 5 (fn-hpi-set 3 3 (fn-omk-at 19 c))))
                 (fn-hpi-set 21 (list :digest 340 17) c)))
           (fn-hpb (fn-hpb-begin (fn-omk-at 1 c) (fn-omk-at 2 c) fn-hpb))
           (fn-hpb (hpic-test-fill-page (take 2045 (fn-hpic-table-model c digests)) fn-hpb))
           (tailp (member-eq mode '(:tail-positive :tail-invariant :tail-used :tail-status)))
           (pagep (member-eq mode '(:table-page-positive :table-page-invariant :table-page-status)))
           (steps (cond (pagep 3) ((and tailp (not (eq mode :tail-used))) 1) (t 0))))
     (mv-let (continued c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
      (hpic-test-more-directory steps c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
      (let* ((c (cond ((eq mode :table-word-invariant) (fn-hpi-set 21 (list :digest 340 18) c))
                      ((member-eq mode '(:table-word-status :tail-status :table-page-status)) (fn-hpi-set 22 nil c))
                      (t c)))
             (fn-hpb (if (member-eq mode '(:tail-invariant :table-page-invariant))
                         (update-fn-hpb-wi 0 (+ 1 (fn-hpb-wi 0 fn-hpb)) fn-hpb) fn-hpb))
             (inv (fn-hpic-table-invariantp c digests fn-hpb))
             (used (fn-hpb-used fn-hpb)) (prefix (fn-hpb-prefix fn-hpb))
             (old (hpiw-test-full-model fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))
             (old-ledger ledger))
       (mv-let (v effect next ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
        (fn-hpi-tick c nil ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
        (let* ((now (hpiw-test-full-model fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))
               (frame (and (equal ledger old-ledger) (equal (take 4 now) (take 4 old)) (equal (nth 5 now) (nth 5 old))))
               (law (cond
                (pagep
                 (and (equal (fn-hpb-prefix fn-hpb) (fn-hpic-table-model c digests))
                      (equal effect (fn-hpi-write-effect (fn-omk-at 1 c) (fn-omk-at 3 c)
                         (nfix (fn-omk-at 4 c)) :table (fn-hpic-meta-field 6 c)
                         (+ (nfix (fn-omk-at 5 layout)) (fn-hpic-meta-field 6 c))
                         (nfix (fn-omk-at 4 (fn-omk-at 16 c)))))
                      (equal (fn-omk-at 0 next) :wait-write)
                      (equal (fn-omk-at 19 next) (fn-omk-at 19 c))
                      (equal (fn-omk-at 6 next) (fn-omk-at 6 c))
                      (equal (fn-omk-at 17 next) '(4 :table-digest-start))
                      frame (equal now old)))
                (tailp (and (equal (fn-hpb-prefix fn-hpb) (append prefix (list 0)))
                            (fn-hpic-table-invariantp next digests fn-hpb) frame))
                (t (and (equal (fn-hpb-prefix fn-hpb)
                               (append prefix (list (nth used (fn-hpic-table-model c digests)))))
                        (fn-hpic-table-invariantp next digests fn-hpb) frame))))
               (expected-inv (not (member-eq mode '(:table-word-invariant :tail-invariant :table-page-invariant))))
               (expected-status (not (member-eq mode '(:table-word-status :tail-status :table-page-status))))
               (positive (member-eq mode '(:table-word-positive :tail-positive :table-page-positive))))
         (mv (and (eq admitted :admitted) (eq funded :funded) (eq continued :continue)
                  (equal (fn-omk-at 2 layout) 2) (equal (fn-hpic-meta-field 4 c) 341)
                  (equal (if inv t nil) (if expected-inv t nil))
                  (equal (equal v (if pagep :write :continue)) (if expected-status t nil))
                  (or (not tailp) (equal (<= 2046 used) (not (eq mode :tail-used))))
                  (equal (if law t nil) (if positive t nil))
                  (or (not pagep) (equal (nthcdr 2046 (fn-hpic-table-model c digests)) '(0 0))))
             fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)))))))))))

(local (defun hpic-test-local-table-point (mode)
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-hpq0 (mv-let (result fn-hpq0) (with-local-stobj fn-hpq1 (mv-let (result fn-hpq0 fn-hpq1) (with-local-stobj fn-hpq2 (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2) (with-local-stobj fn-hpq3 (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3) (with-local-stobj fn-hpb (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb) (with-local-stobj pgs-digest-state (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) (hpic-test-table-point mode fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) (mv result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb))) (mv result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3))) (mv result fn-hpq0 fn-hpq1 fn-hpq2))) (mv result fn-hpq0 fn-hpq1))) (mv result fn-hpq0))) result))))

(local (assert-event (hpic-test-local-table-point :table-word-positive)))
(local (assert-event (hpic-test-local-table-point :table-word-invariant)))
(local (assert-event (hpic-test-local-table-point :table-word-status)))
(local (assert-event (hpic-test-local-table-point :tail-positive)))
(local (assert-event (hpic-test-local-table-point :tail-invariant)))
(local (assert-event (hpic-test-local-table-point :tail-used)))
(local (assert-event (hpic-test-local-table-point :tail-status)))
(local (assert-event (hpic-test-local-table-point :table-page-positive)))
(local (assert-event (hpic-test-local-table-point :table-page-invariant)))
(local (assert-event (hpic-test-local-table-point :table-page-status)))


; First table uses the actual complete small decoded-row image trajectory
; through its final data digest spool ACK. Next table is separately labelled
; a supported two-table phase construction with actual issued I/O and grant.
(local (defun hpic-test-check-table-transition (mode c observation digests ledger
                    fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
 (declare (xargs :stobjs (fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) :verify-guards nil))
 (let* ((fn-hpb (if (eq mode :spool-context) (update-fn-hpb-used 1 fn-hpb) fn-hpb))
        (observation (if (eq mode :spool-status) (update-nth 3 (+ 1 (nfix (fn-omk-at 3 observation))) observation) observation))
        (context (fn-hpic-table-spool-contextp c digests fn-hpb))
        (old (hpiw-test-full-model fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))
        (old-ledger ledger))
  (mv-let (v e next ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
   (fn-hpi-tick c observation ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
   (declare (ignore e))
   (let ((law (and (and (equal (fn-omk-at 0 next) :metadata) (fn-hpic-table-invariantp next digests fn-hpb))
                  (equal ledger old-ledger)
                  (equal (hpiw-test-full-model fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) old))))
    (mv (cond ((eq mode :spool-context) (and (not context) (eq v :continue) (not law)))
              ((eq mode :spool-status) (and context (not (eq v :continue)) (not law)))
              (t (and context (eq v :continue) law)))
        fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))))))

(local (defun hpic-test-table-transition (mode constructed fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
 (declare (xargs :stobjs (fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) :verify-guards nil))
 (mv-let (admitted maintenance ledger)
  (fn-pmn-admit (fn-prl-make '(10000000 100000000 4 1 10)) 7 1 '(1000000 16384 3 1 1))
  (declare (ignore admitted))
  (let ((initial (fn-hpi-begin 1 (if constructed 8388608 8) 1 (if constructed 512 1)
                   '(7 (9 1) 0 0) maintenance (fn-omk-at 1 maintenance) 100000000 "node" 17 "trail")))
   (if constructed
    (mv-let (funded e c ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
     (fn-hpi-tick initial nil ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
     (declare (ignore funded e))
     (let* ((c (fn-hpi-set 20 '(:table 0 16384 16384) c))
            (digests (pgs-zeros (nfix (fn-omk-at 1 (fn-omk-at 1 (fn-omk-at 6 c)))))))
      (mv-let (issued effect c) (fn-hpi-issue-io :write-spool :table 0 0 32 (pgs-zeros 32) :wait-spool-write c)
       (declare (ignore issued))
       (hpic-test-check-table-transition mode c (fn-hie-observation c effect (fn-omk-at 3 c) ledger 32 :ok nil)
            digests ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))))
    (mv-let (r fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
     (hpic-test-until-directory 50000 :table-begin initial nil ledger nil nil 0
       '(:decoded (:span 3 0 1 3)) '(0 65 66 67) (fn-hp-mkey "ABC" 17)
       fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
     (let* ((c (nth 8 r)) (ledger (nth 4 r)) (effect (fn-omk-at 5 c))
            (digests (pgs-zeros (nfix (fn-omk-at 1 (fn-omk-at 1 (fn-omk-at 6 c)))))))
      (hpic-test-check-table-transition mode c (fn-hie-observation c effect (fn-omk-at 3 c) ledger 32 :ok nil)
           digests ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))))))))

(local (defun hpic-test-local-table-transition (mode constructed)
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-hpq0 (mv-let (result fn-hpq0) (with-local-stobj fn-hpq1 (mv-let (result fn-hpq0 fn-hpq1) (with-local-stobj fn-hpq2 (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2) (with-local-stobj fn-hpq3 (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3) (with-local-stobj fn-hpb (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb) (with-local-stobj pgs-digest-state (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) (hpic-test-table-transition mode constructed fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) (mv result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb))) (mv result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3))) (mv result fn-hpq0 fn-hpq1 fn-hpq2))) (mv result fn-hpq0 fn-hpq1))) (mv result fn-hpq0))) result))))


(local (assert-event (hpic-test-local-table-transition :spool-positive nil)))
(local (assert-event (hpic-test-local-table-transition :spool-context nil)))
(local (assert-event (hpic-test-local-table-transition :spool-status nil)))
(local (assert-event (hpic-test-local-table-transition :spool-positive t)))
(local (assert-event (hpic-test-local-table-transition :spool-context t)))
(local (assert-event (hpic-test-local-table-transition :spool-status t)))

(local (defun hpic-test-check-directory-transition (mode c observation digests ledger
                    fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
 (declare (xargs :stobjs (fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) :verify-guards nil))
 (let* ((fn-hpb (if (eq mode :spool-context) (update-fn-hpb-used 1 fn-hpb) fn-hpb))
        (observation (if (eq mode :spool-status) (update-nth 3 (+ 1 (nfix (fn-omk-at 3 observation))) observation) observation))
        (context (fn-hpic-directory-spool-contextp c digests fn-hpb))
        (old (hpiw-test-full-model fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))
        (old-ledger ledger))
  (mv-let (v e next ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
   (fn-hpi-tick c observation ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
   (declare (ignore e))
   (let ((law (and (fn-hpic-directory-invariantp next digests fn-hpb)
                  (equal ledger old-ledger)
                  (equal (hpiw-test-full-model fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) old))))
    (mv (cond ((eq mode :spool-context) (and (not context) (eq v :continue) (not law)))
              ((eq mode :spool-status) (and context (not (eq v :continue)) (not law)))
              (t (and context (eq v :continue) law)))
        fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state))))))


(local (defun hpic-test-directory-transition (mode fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
 (declare (xargs :stobjs (fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) :verify-guards nil))
 (mv-let (admitted maintenance ledger)
  (fn-pmn-admit (fn-prl-make '(10000000 100000000 4 1 10)) 7 1 '(1000000 16384 3 1 1))
  (declare (ignore admitted))
  (let ((initial (fn-hpi-begin 1 8 1 1 '(7 (9 1) 0 0) maintenance (fn-omk-at 1 maintenance)
                  100000000 "node" 17 "trail")))
   (mv-let (r fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
    (hpic-test-until-directory 50000 :directory-begin initial nil ledger nil nil 0
      '(:decoded (:span 3 0 1 3)) '(0 65 66 67) (fn-hp-mkey "ABC" 17)
      fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)
    (let* ((c (nth 8 r)) (ledger (nth 4 r)) (effect (fn-omk-at 5 c))
           (digests (pgs-zeros (nfix (fn-omk-at 2 (fn-omk-at 1 (fn-omk-at 6 c)))))))
     (hpic-test-check-directory-transition mode c (fn-hie-observation c effect (fn-omk-at 3 c) ledger 32 :ok nil)
        digests ledger fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state)))))))

(local (defun hpic-test-local-directory-transition (mode)
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-hpq0 (mv-let (result fn-hpq0) (with-local-stobj fn-hpq1 (mv-let (result fn-hpq0 fn-hpq1) (with-local-stobj fn-hpq2 (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2) (with-local-stobj fn-hpq3 (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3) (with-local-stobj fn-hpb (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb) (with-local-stobj pgs-digest-state (mv-let (result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) (hpic-test-directory-transition mode fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb pgs-digest-state) (mv result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3 fn-hpb))) (mv result fn-hpq0 fn-hpq1 fn-hpq2 fn-hpq3))) (mv result fn-hpq0 fn-hpq1 fn-hpq2))) (mv result fn-hpq0 fn-hpq1))) (mv result fn-hpq0))) result))))


(local (assert-event (hpic-test-local-directory-transition :spool-positive)))
(local (assert-event (hpic-test-local-directory-transition :spool-context)))
(local (assert-event (hpic-test-local-directory-transition :spool-status)))
