; Real concrete page-store schedules, not simulated relocation effects.
(in-package "ACL2")
(include-book "../../books/history-pages-relocate-step")
(defconst *hpr-lens* '(8 8 8 8 32768))
(defconst *hpr-starts* '(1 2 3 4 5))

(defun hpr-test-array (sel i n pgs-mem)
 (declare (xargs :mode :program :stobjs pgs-mem))
 (if (>= i n) nil
  (cons (case sel (0 (pgs-wi i pgs-mem)) (1 (pgs-mi i pgs-mem))
         (2 (pgs-ti i pgs-mem)) (3 (pgs-di i pgs-mem))
         (4 (pgs-vi i pgs-mem)) (otherwise (pgs-tvi i pgs-mem)))
        (hpr-test-array sel (+ i 1) n pgs-mem))))
(defun hpr-test-snapshot (pgs-mem)
 (declare (xargs :mode :program :stobjs pgs-mem))
 (list (hpr-test-array 0 0 (pgs-w-length pgs-mem) pgs-mem)
       (hpr-test-array 1 0 (pgs-m-length pgs-mem) pgs-mem)
       (hpr-test-array 2 0 (pgs-t-length pgs-mem) pgs-mem)
       (hpr-test-array 3 0 (pgs-d-length pgs-mem) pgs-mem)
       (hpr-test-array 4 0 (pgs-v-length pgs-mem) pgs-mem)
       (hpr-test-array 5 0 (pgs-tv-length pgs-mem) pgs-mem)))
(defun hpr-test-base (pgs-mem)
 (declare (xargs :mode :program :stobjs pgs-mem))
 (let* ((pgs-mem (pgs-x-grow-image 7 pgs-mem))
        (pgs-mem (update-pgs-wi 10240 41 pgs-mem))
        (pgs-mem (update-pgs-wi 12287 99 pgs-mem))
        (pgs-mem (update-pgs-wi 12288 73 pgs-mem)))
   (update-pgs-wi 14335 103 pgs-mem)))
(defun hpr-test-differences (a b)
 (declare (xargs :mode :program))
 (if (atom a) 0
  (+ (if (equal (car a) (car b)) 0 1) (hpr-test-differences (cdr a) (cdr b)))))
(defun hpr-test-drive (fuel cursor pgs-mem)
 (declare (xargs :mode :program :stobjs pgs-mem))
 (if (zp fuel) (mv (list :exhausted cursor) pgs-mem)
  (let* ((grow (eq (nth 0 cursor) :grow-image))
         (before (hpr-test-array 0 0 (pgs-w-length pgs-mem) pgs-mem)))
   (mv-let (v next pgs-mem)
    (if grow (fn-hpr-grow-image cursor pgs-mem) (fn-hpr-step cursor pgs-mem))
    (let* ((after (hpr-test-array 0 0 (pgs-w-length pgs-mem) pgs-mem))
           (bound (or grow (<= (hpr-test-differences before after) 2048))))
     (cond ((not bound) (mv (list :unbounded-tick cursor) pgs-mem))
           ((eq v :yield)
            (if (and (fn-hpr-cursorp next)
                     (< (fn-hpr-rank next) (fn-hpr-rank cursor))
                     (not (fn-hpr-placement next)))
                (hpr-test-drive (1- fuel) next pgs-mem)
              (mv (list :bad-progress cursor) pgs-mem)))
           (t (mv (list v (fn-hpr-placement next)) pgs-mem))))))))
(defun hpr-test-run (old)
 (declare (xargs :mode :program))
 (with-local-stobj pgs-mem
  (mv-let (res pgs-mem)
   (let ((pgs-mem (hpr-test-base pgs-mem)))
    (if old
     (mv-let (v starts np pgs-mem)
      (fn-hp-x-relocate 4 4 1 *hpr-lens* *hpr-starts* 7 pgs-mem)
      (mv (list v (list starts np) (hpr-test-snapshot pgs-mem)) pgs-mem))
     (mv-let (v cursor pgs-mem)
      (fn-hpr-begin 4 4 1 *hpr-lens* *hpr-starts* 7 pgs-mem)
      (if (not (eq v :yield)) (mv (list :bad-begin v) pgs-mem)
       (mv-let (res pgs-mem)
        (hpr-test-drive (+ 1 (fn-hpr-rank cursor)) cursor pgs-mem)
        (mv (list (car res) (cadr res) (hpr-test-snapshot pgs-mem)) pgs-mem))))))
   res)))
(assert-event
 (let* ((old (hpr-test-run t)) (new (hpr-test-run nil)) (words (car (caddr new))))
  (and (equal (car old) :ok) (equal (car new) :done)
       (equal (cadr new) '((1 2 3 4 7) 11))
       (equal (cdr old) (cdr new))
       (equal (nth 14336 words) 41) (equal (nth 16383 words) 99)
       (equal (nth 16384 words) 73) (equal (nth 18431 words) 103)
       (equal (nth 10240 words) 0) (equal (nth 14335 words) 0))))

(defun hpr-test-wait (table)
 (declare (xargs :mode :program))
 (with-local-stobj pgs-mem
  (mv-let (res pgs-mem)
   (let* ((pgs-mem (hpr-test-base pgs-mem))
          (pgs-mem (if table (update-pgs-tvi 0 0 pgs-mem) (update-pgs-vi 6 0 pgs-mem)))
          (before (hpr-test-snapshot pgs-mem))
          (cursor (fn-hpr-cursor (if table :header-ready :ready) 4 4 1 *hpr-lens* *hpr-starts* 7 (if table 0 1))))
    (mv-let (v next pgs-mem) (fn-hpr-step cursor pgs-mem)
     (let* ((same (and (equal before (hpr-test-snapshot pgs-mem)) (equal next cursor)
                       (not (fn-hpr-placement next))
                       (equal (car v) (if table :need-table :need-page))))
            ; Only fixture cache completion: no physical I/O claim.
            (pgs-mem (if table (update-pgs-tvi 0 2 pgs-mem) (update-pgs-vi 6 2 pgs-mem))))
      (mv-let (v2 next2 pgs-mem) (fn-hpr-step next pgs-mem)
       (mv (and same (eq v2 :yield) (not (equal next2 cursor))) pgs-mem)))))
   res)))
(assert-event (and (hpr-test-wait t) (hpr-test-wait nil)))

(defun hpr-test-refuse (c np)
 (declare (xargs :mode :program))
 (with-local-stobj pgs-mem
  (mv-let (res pgs-mem)
   (let* ((pgs-mem (hpr-test-base pgs-mem)) (before (hpr-test-snapshot pgs-mem)))
    (mv-let (v cursor pgs-mem) (fn-hpr-begin 4 c 1 *hpr-lens* *hpr-starts* np pgs-mem)
     (mv (list v (equal before (hpr-test-snapshot pgs-mem)) cursor) pgs-mem)))
   res)))
(assert-event (equal (hpr-test-refuse 1 7) '((:refused :capacity) t nil)))
(assert-event (equal (hpr-test-refuse 4 6) '((:refused :image) t nil)))
