(in-package "ACL2")
(include-book "incoming-pool-holder-tests")
(defun icst-sequence-in (fn-input-copy fn-page-read-pool)
 (declare (xargs :stobjs (fn-input-copy fn-page-read-pool) :verify-guards nil))
 (mv-let (installed fn-page-read-pool)
  (fn-owner-page-read-install '(8192 0 0 0 8) 0 0 0 8 fn-page-read-pool)
  (mv-let (backing fn-page-read-pool) (iohp-install-backing fn-page-read-pool)
   (mv-let (reserved token fn-page-read-pool)
    (fn-owner-incoming-reserve '(256 0 0 0 1) fn-page-read-pool)
    (mv-let (begun fn-input-copy fn-page-read-pool)
     (fn-owner-incoming-copy-start token 20 nil fn-input-copy fn-page-read-pool)
     (mv-let (word start count end fn-input-copy fn-page-read-pool)
      (fn-owner-incoming-copy-next token fn-input-copy fn-page-read-pool)
      (let ((before (fn-input-copy-view fn-input-copy)) (pool-before (iohp-test-view fn-page-read-pool))
            (generic-mutation-denied (not (fn-owner-incoming-mutation-allowedp token fn-page-read-pool))))
       (mv-let (repeat start2 count2 end2 fn-input-copy fn-page-read-pool)
        (fn-owner-incoming-copy-next token fn-input-copy fn-page-read-pool)
        (let ((repeat-kept (and (equal before (fn-input-copy-view fn-input-copy))
                               (equal pool-before (iohp-test-view fn-page-read-pool)))))
         (mv-let (stale fn-input-copy fn-page-read-pool)
          (fn-owner-incoming-copy-ack token 1 count end :copied fn-input-copy fn-page-read-pool)
          (let ((stale-kept (and (equal before (fn-input-copy-view fn-input-copy))
                                (equal pool-before (iohp-test-view fn-page-read-pool)))))
           (mv-let (copied fn-input-copy fn-page-read-pool)
            (fn-owner-incoming-copy-ack token start count end :copied fn-input-copy fn-page-read-pool)
            (mv-let (complete z1 z2 z3 fn-input-copy fn-page-read-pool)
             (fn-owner-incoming-copy-next token fn-input-copy fn-page-read-pool)
             (let ((sealed (fn-prl-nth 1 (fn-owner-incoming-row fn-page-read-pool)))
                   (done (fn-input-copy-view fn-input-copy)) (done-pool (iohp-test-view fn-page-read-pool)))
              (mv-let (held fn-input-copy fn-page-read-pool)
               (fn-owner-incoming-copy-stop token nil t fn-input-copy fn-page-read-pool)
               (let ((held-kept (and (equal done (fn-input-copy-view fn-input-copy))
                                    (equal done-pool (iohp-test-view fn-page-read-pool)))))
                (mv-let (released fn-input-copy fn-page-read-pool)
                 (fn-owner-incoming-copy-stop token t t fn-input-copy fn-page-read-pool)
                 (mv (list installed backing reserved begun word start count end
                           repeat start2 count2 end2 repeat-kept generic-mutation-denied stale stale-kept copied
                           complete z1 z2 z3 sealed held held-kept released (fn-input-copy-view fn-input-copy)
                           (fn-owner-incoming-row fn-page-read-pool)
                           (fn-owner-incoming-backing fn-page-read-pool)
                           (fn-prl-baseline (fn-owner-page-read-ledger fn-page-read-pool)))
                     fn-input-copy fn-page-read-pool))))))))))))))))))
(defun icst-sequence ()
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-input-copy
  (mv-let (result fn-input-copy)
   (with-local-stobj fn-page-read-pool
    (mv-let (result fn-input-copy fn-page-read-pool)
     (icst-sequence-in fn-input-copy fn-page-read-pool)
     (mv result fn-input-copy))) result)))
(assert-event
 (equal (icst-sequence)
  '(:installed :released :admitted :setup-started :copy 0 20 20
    :copy 0 20 20 t t :stale-copy t :copy-recorded :complete 0 0 0
    :readonly :incoming-held t :released nil nil (:input-backing 0 64) (512 0 0 0 0))))
