; Actual registry/shared-pool repin fixtures. Installed children/publications
; are synthetic: these tests do not establish constructor or owner authority.
(in-package "ACL2")
(include-book "../../books/index-connection-repin")
(include-book "index-connection-issuer-tests")
(defun fn-icr-test-second-publication (fn-index-backing)
 (declare (xargs :stobjs fn-index-backing :guard t))
 (stobj-let ((fn-ibp-node (fn-ibp-registry fn-index-backing)))
  (fn-ibp-node)
  (stobj-let ((fn-ibp-generation-segment
              (fn-ibp-node-children-get 'fn-ibp-generation-segment fn-ibp-node
                                       (create-fn-ibp-generation-segment))))
   (fn-ibp-generation-segment)
   (mv-let (a fn-ibp-generation-segment)
    (fn-ibp-generation-begin '(:index-generation 10 1 1) :gen-grant fn-ibp-generation-segment)
    (declare (ignore a))
    (mv-let (b fn-ibp-generation-segment)
     (fn-ibp-generation-capture-arena '(:index-generation 10 1 1) 7 24 fn-ibp-generation-segment)
     (declare (ignore b))
     (mv-let (c fn-ibp-generation-segment)
      (fn-ibp-generation-install-publication '(:index-generation 10 1 1)
       (fn-ipub-make 10 :new-key nil 0 4 3 nil 0 1 nil 0 2 nil 3 :complete :new-view 7 24)
       fn-ibp-generation-segment)
      (declare (ignore c)) fn-ibp-generation-segment)))
   fn-ibp-node)
  (update-fn-ibp-current
   (list :installed-publication '(:index-generation 10 1 1)
    (fn-ipub-make 10 :new-key nil 0 4 3 nil 0 1 nil 0 2 nil 3 :complete :new-view 7 24))
   fn-index-backing)))
(defun fn-icr-test-captured-holder (finish fn-index-backing fn-page-read-pool)
 (declare (xargs :stobjs (fn-index-backing fn-page-read-pool) :guard t))
 (mv-let (a token fn-index-backing fn-page-read-pool)
  (fn-icr-reserve 7 '(40 0 0 0 1) fn-index-backing fn-page-read-pool)
  (mv-let (b l0 fn-index-backing) (fn-icr-register token 1 fn-index-backing)
   (mv-let (c pin l1 fn-index-backing) (fn-icr-capture token :current 2 fn-index-backing)
    (mv-let (d l2 fn-index-backing)
     (if finish (fn-icr-finish-open 7 token 1 fn-index-backing)
       (mv :not-needed 1 fn-index-backing))
     (declare (ignore l2))
     (mv (and (natp l0) (natp l1) (eq a :reserved) (eq b :registered) (eq c :captured) pin
              (eq d (if finish :opened :not-needed)))
         token fn-index-backing fn-page-read-pool))))))
(defun fn-icr-test-gen-refs (token fn-index-backing)
 (declare (xargs :stobjs fn-index-backing :guard t))
 (stobj-let ((fn-ibp-node (fn-ibp-registry fn-index-backing)))
  (word row left)
  (fn-ibp-node-generation-read token 1 0 0 fn-ibp-node)
  (prog2$ (list word left) (list (fn-omk-at 4 row) (fn-omk-at 5 row)))))
(defun fn-icr-test-repin (held refuse fn-index-backing fn-page-read-pool)
 (declare (xargs :stobjs (fn-index-backing fn-page-read-pool) :guard t))
 (mv-let (fn-index-backing fn-page-read-pool)
 (fn-icr-test-setup t fn-index-backing fn-page-read-pool)
 (mv-let (ok0 old fn-index-backing fn-page-read-pool)
 (fn-icr-test-captured-holder t fn-index-backing fn-page-read-pool)
 (mv-let (a ignored l0 fn-index-backing)
 (if held (fn-ibp-connection-event old :acquire 7 nil 1 fn-index-backing) (mv :not-needed nil 1 fn-index-backing))
 (let*
 ((ok1 (and (eq a (if held :acquired :not-needed)) (not ignored) (natp l0))) (fn-index-backing (fn-icr-test-second-publication fn-index-backing)))
 (mv-let (ok2 new fn-index-backing fn-page-read-pool)
 (fn-icr-test-captured-holder nil fn-index-backing fn-page-read-pool)
 (mv-let (before-old old-row l1)
 (fn-ibp-connection-read old 1 fn-index-backing)
 (mv-let (before-new new-row l2)
 (fn-ibp-connection-read new 1 fn-index-backing)
 (let*
 ((before-pending (fn-ibp-connection-pending fn-index-backing)) (before-ledger (fn-owner-page-read-ledger fn-page-read-pool)) (ok3 (and (eq before-old :present) (eq before-new :present) (equal l1 0) (equal l2 0) (equal (fn-icr-test-gen-refs '(:index-generation 9 1 0) fn-index-backing) '(1 0)) (equal (fn-icr-test-gen-refs '(:index-generation 10 1 1) fn-index-backing) '(1 0)))))
 (mv-let (same left0 fn-index-backing fn-page-read-pool)
 (fn-icr-repin-accept 7 new new 7 fn-index-backing fn-page-read-pool)
 (mv-let (short left1 fn-index-backing fn-page-read-pool)
 (fn-icr-repin-accept 7 old new 6 fn-index-backing fn-page-read-pool)
 (mv-let (wrong left2 fn-index-backing fn-page-read-pool)
 (fn-icr-repin-accept 8 old new 7 fn-index-backing fn-page-read-pool)
 (mv-let (after-old old2 l3)
 (fn-ibp-connection-read old 1 fn-index-backing)
 (mv-let (after-new new2 l4)
 (fn-ibp-connection-read new 1 fn-index-backing)
 (let
 ((ok4 (and (eq same :stale) (equal left0 7) (eq short :yield) (equal left1 6) (eq wrong :stale) (equal left2 7) (eq after-old :present) (eq after-new :present) (equal l3 0) (equal l4 0) (equal old-row old2) (equal new-row new2) (equal before-pending (fn-ibp-connection-pending fn-index-backing)) (equal before-ledger (fn-owner-page-read-ledger fn-page-read-pool)))))
 (mv-let (word left fn-index-backing fn-page-read-pool)
 (if refuse (fn-icr-abort new 5 fn-index-backing fn-page-read-pool) (fn-icr-repin-accept 7 old new 7 fn-index-backing fn-page-read-pool))
 (mv-let (a old3 l5)
 (fn-ibp-connection-read old 1 fn-index-backing)
 (mv-let (b new3 l6)
 (fn-ibp-connection-read new 1 fn-index-backing)
 (let*
 ((ok5 (and (eq word (if refuse :released (if held :repinned-held :repinned))) (natp left) (natp l5) (natp l6) (eq a :present) (eq b :present) (eq (fn-omk-at 4 old3) (if refuse :live (if held :closing :released))) (eq (fn-omk-at 4 new3) (if refuse :released :live)) (equal (fn-icr-test-gen-refs '(:index-generation 9 1 0) fn-index-backing) (if (or refuse held) '(1 0) '(0 0))) (equal (fn-icr-test-gen-refs '(:index-generation 10 1 1) fn-index-backing) (if refuse '(0 0) '(1 0))) (equal (fn-prl-nth 1 (fn-owner-page-read-ledger fn-page-read-pool)) (if (and held (not refuse)) '(80 0 0 0 2) '(40 0 0 0 2))) (not (fn-ibp-connection-pending fn-index-backing)) (if refuse (equal old-row old3) (and (eq (fn-omk-at 4 new3) :live) (equal (fn-omk-at 1 (fn-omk-at 3 new3)) '(:index-generation 10 1 1)) (or (not held) (and (eq (fn-omk-at 4 old3) :closing) (equal (fn-omk-at 6 old3) 1))))))))
 (mv-let (ret ignored l7 fn-index-backing)
 (if (and held (not refuse)) (fn-ibp-connection-event old :return 7 nil 1 fn-index-backing) (mv :not-needed nil 1 fn-index-backing))
 (mv-let (settled l8 fn-index-backing fn-page-read-pool)
 (if (and held (not refuse)) (fn-icr-settle old 4 fn-index-backing fn-page-read-pool) (mv :not-needed 4 fn-index-backing fn-page-read-pool))
 (mv (list ok0 ok1 ok2 ok3 ok4 ok5
 (and (not ignored) (natp l7) (natp l8)
      (eq ret (if (and held (not refuse)) :returned :not-needed))
      (eq settled (if (and held (not refuse)) :released :not-needed))
      (equal (fn-prl-nth 1 (fn-owner-page-read-ledger fn-page-read-pool)) '(40 0 0 0 2))
      (equal (fn-prl-nth 2 (fn-owner-page-read-ledger fn-page-read-pool)) 2)
      (equal (fn-icr-test-gen-refs '(:index-generation 9 1 0) fn-index-backing) (if refuse '(1 0) '(0 0)))
      (equal (fn-icr-test-gen-refs '(:index-generation 10 1 1) fn-index-backing) (if refuse '(0 0) '(1 0)))))
 fn-index-backing fn-page-read-pool))))))))))))))))))))))
(defun fn-icr-test-repin-exec (held refuse)
 (declare (xargs :guard t))
 (with-local-stobj fn-index-backing
  (mv-let (result fn-index-backing)
   (with-local-stobj fn-page-read-pool
    (mv-let (result fn-index-backing fn-page-read-pool)
     (fn-icr-test-repin held refuse fn-index-backing fn-page-read-pool)
     (mv result fn-index-backing)))
   result)))
(assert-event (equal (fn-icr-test-repin-exec nil nil) '(t t t t t t t)))
(assert-event (equal (fn-icr-test-repin-exec t nil) '(t t t t t t t)))
(assert-event (equal (fn-icr-test-repin-exec nil t) '(t t t t t t t)))
(assert-event (equal (fn-icr-test-repin-exec t t) '(t t t t t t t)))
