(in-package "ACL2")
(include-book "../../books/index-backing-resource-driver")

(defun-nx ibpres-segment (mio)
  (fn-ibp-node-children-get 'fn-ibp-query-segment
    (fn-ibp-registry (fn-mio$c-provider mio)) (create-fn-ibp-query-segment)))

; Synthetic installed-state regression. It exercises the actual token-only
; provider/pool subject; no old row snapshot is an input to that subject.
(defun-nx ibpres-two-query-stale-release ()
  (let* ((a (fn-ibp-query-token 1 1 0 1)) (b (fn-ibp-query-token 2 1 1 1))
         (cap (fn-ibp-capture-make 1 '(1 2) 2 1 9 nil 0 1 nil 0 2))
         (qa (fn-miq-make 1 1 '(1 2) 1 9 2 "<a@x>" 7 '(0 2 0) nil nil :done))
         (qb (fn-miq-make 2 1 '(1 2) 1 9 2 "<b@x>" 8 '(0 2 0) nil nil :done))
         (seg (update-fn-ibp-qs-id 1 (create-fn-ibp-query-segment)))
         (ra (mv-list 2 (fn-ibp-query-slot-register a qa cap seg)))
         (rb (mv-list 2 (fn-ibp-query-slot-register b qb cap (nth 1 ra))))
         (seg (update-fn-ibp-qs-inputsi 0 '(:query-context nil nil nil nil (:query-payload 1 0 1 4 8 1)) (nth 1 rb)))
         (seg (update-fn-ibp-qs-inputsi 1 '(:query-context nil nil nil nil (:query-payload 2 1 1 4 8 1)) seg))
         (node (fn-ibp-node-children-put 'fn-ibp-query-segment seg (create-fn-ibp-node)))
         (backing (update-fn-ibp-pool-capacity 1 (update-fn-ibp-registry node (create-fn-index-backing))))
         (mio (update-fn-mio$c-provider backing (create-fn-mio$c)))
         (pool (update-fn-prp-data '(((16384 0 0 0 0) (0 0 0 0 0) 71 ((legacy . binding)) (0 0 0 0 0)) 3 4 5 6)
                                 (create-fn-page-read-pool)))
         (aa (mv-list 5 (fn-miq-resource-transition a :admit '(4096 0 0 0 0) nil 1 mio pool)))
         (ab (mv-list 5 (fn-miq-resource-transition b :admit '(4096 0 0 0 0) nil 1 (nth 3 aa) (nth 4 aa))))
         (ar (mv-list 5 (fn-miq-resource-transition a :release nil :joined 1 (nth 3 ab) (nth 4 ab))))
         (again (mv-list 5 (fn-miq-resource-transition a :release nil :joined 1 (nth 3 ar) (nth 4 ar))))
         (promote (mv-list 5 (fn-miq-resource-transition a :promote '(4096 0 0 0 0) nil 1 (nth 3 again) (nth 4 again))))
         (ledger (fn-owner-page-read-ledger (nth 4 promote)))
         (backing (fn-mio$c-provider (nth 3 promote)))
         (node (fn-ibp-registry backing))
         (seg (fn-ibp-node-children-get 'fn-ibp-query-segment node (create-fn-ibp-query-segment)))
         (old-row (fn-ibp-qs-admissionsi 0 seg))
         ; Model completed query-slot retirement, then use real registration.
         (seg (update-fn-ibp-qs-ticketsi 0 0 (update-fn-ibp-qs-active 1 seg)))
         (new (fn-ibp-query-token 3 1 0 1))
         (qnew (fn-miq-make 3 1 '(1 2) 1 9 2 "<c@x>" 9 '(0 2 0) nil nil :done))
         (rn (mv-list 2 (fn-ibp-query-slot-register new qnew cap seg)))
         (seg (update-fn-ibp-qs-inputsi 0 '(:query-context nil nil nil nil (:query-payload 3 0 1 4 8 1)) (nth 1 rn)))
         (node (fn-ibp-node-children-put 'fn-ibp-query-segment seg node))
         (mio (update-fn-mio$c-provider (update-fn-ibp-registry node backing) (nth 3 promote)))
         (an (mv-list 5 (fn-miq-resource-transition new :admit '(4096 0 0 0 0) nil 1 mio (nth 4 promote))))
         (stale (mv-list 5 (fn-miq-resource-transition a :release nil :joined 1 (nth 3 an) (nth 4 an))))
         (stale-promote (mv-list 5 (fn-miq-resource-transition a :promote '(4096 0 0 0 0) nil 1 (nth 3 stale) (nth 4 stale)))))
    (and (equal (nth 0 aa) :admitted) (equal (nth 0 ab) :admitted)
         (equal (nth 0 ar) :released)
         (equal (nth 0 again) :stale) (equal (nth 0 promote) :stale)
         (equal (nth 4 again) (nth 4 ar)) (equal (ibpres-segment (nth 3 again)) (ibpres-segment (nth 3 ar)))
         (equal (fn-prl-nth 1 ledger) '(4096 0 0 0 0))
         (equal (fn-prl-nth 2 ledger) 71) (equal (fn-prl-nth 3 ledger) '((legacy . binding)))
         (equal (fn-prl-nth 2 old-row) :released)
         (equal (nth 0 rn) :captured) (equal (nth 0 an) :admitted)
         (equal (nth 0 stale) :stale) (equal (nth 0 stale-promote) :stale)
         (equal (ibpres-segment (nth 3 stale-promote)) (ibpres-segment (nth 3 an))) (equal (nth 4 stale-promote) (nth 4 an))
         (equal (fn-prl-nth 1 (fn-owner-page-read-ledger (nth 4 stale-promote))) '(8192 0 0 0 0)))))
(defthm ibpres-two-query-stale-release-witness (ibpres-two-query-stale-release) :rule-classes nil)
