(in-package "ACL2")
(include-book "../../books/index-backing-chunks")

(defun-nx ibptest-table ()
  (let* ((src (fn-ibp-table-set 2 4294967295 (create-fn-ibp-table-page)))
         (dst (fn-ibp-table-set 7 777 (create-fn-ibp-table-page2)))
         (copied (fn-ibp-table-copy-span 1 3 src dst)))
    (and (natp 1) (natp 3) (natp 2)
         (fn-ibp-table-pagep src) (fn-ibp-table-page2p dst)
         (equal (fn-ibp-table2-sealed dst) 0) (<= 3 64) (<= (+ 1 3) 2048)
         (equal (nth 2 (nth 0 copied))
                (if (and (<= 1 2) (< 2 (+ 1 3)))
                    (nth 2 (nth 0 src)) (nth 2 (nth 0 dst))))
         (equal (fn-ibp-table-word 2 copied) 4294967295)
         (equal (fn-ibp-table-word 7 copied) 777))))
; KEYSTONE fn-ibp-table-copy-span-exact-output. REACHABLE POSITIVE.
(defthm ibptest-table-witness (ibptest-table) :rule-classes nil)

(defun-nx ibptest-row ()
  (let* ((src (fn-ibp-row-set 1 '(held-row 3 old-context) (create-fn-ibp-row-page)))
         (dst (fn-ibp-row-set 5 '(other-row 8) (create-fn-ibp-row-page2)))
         (copied (fn-ibp-row-copy-span 0 2 src dst)))
    (and (natp 0) (natp 2) (natp 1)
         (fn-ibp-row-pagep src) (fn-ibp-row-page2p dst)
         (equal (fn-ibp-row2-sealed dst) 0) (<= 2 32) (<= (+ 0 2) 256)
         (equal (nth 1 (nth 0 copied))
                (if (and (<= 0 1) (< 1 (+ 0 2)))
                    (nth 1 (nth 0 src)) (nth 1 (nth 0 dst))))
         (equal (fn-ibp-row 1 copied) '(held-row 3 old-context))
         (equal (fn-ibp-row 5 copied) '(other-row 8)))))
; KEYSTONE fn-ibp-row-copy-span-exact-output. REACHABLE POSITIVE.
(defthm ibptest-row-witness (ibptest-row) :rule-classes nil)

; HYPOTHESIS-REMOVAL: all retained START/COUNT hypotheses affirmatively hold;
; negative logical J selects NTH0 while the literal span condition is false.
(defun-nx ibptest-table-j-removal ()
  (let* ((src (fn-ibp-table-set 0 41 (create-fn-ibp-table-page)))
         (dst (fn-ibp-table-set 0 7 (create-fn-ibp-table-page2)))
         (copied (fn-ibp-table-copy-span 0 1 src dst)))
    (and (natp 0) (natp 1) (not (natp -1))
         (not (equal (nth -1 (nth 0 copied))
                      (if (and (<= 0 -1) (< -1 (+ 0 1)))
                          (nth -1 (nth 0 src)) (nth -1 (nth 0 dst))))))))
(defthm ibptest-table-j-removal-witness (ibptest-table-j-removal) :rule-classes nil)
(defun-nx ibptest-row-j-removal ()
  (let* ((src (fn-ibp-row-set 0 '(old-row) (create-fn-ibp-row-page)))
         (dst (fn-ibp-row-set 0 '(other-row) (create-fn-ibp-row-page2)))
         (copied (fn-ibp-row-copy-span 0 1 src dst)))
    (and (natp 0) (natp 1) (not (natp -1))
         (not (equal (nth -1 (nth 0 copied))
                      (if (and (<= 0 -1) (< -1 (+ 0 1)))
                          (nth -1 (nth 0 src)) (nth -1 (nth 0 dst))))))))
(defthm ibptest-row-j-removal-witness (ibptest-row-j-removal) :rule-classes nil)

; Reachable identity/read-only gate plus wrong-identity mutation.
(defun-nx ibptest-seal ()
  (let* ((initialized (mv-list 2 (fn-ibp-table-initialize 7 3 (create-fn-ibp-table-page))))
         (page (nth 1 initialized))
         (wrong (mv-list 2 (fn-ibp-table-seal 8 3 page)))
         (sealed (mv-list 2 (fn-ibp-table-seal 7 3 page)))
         (again (mv-list 2 (fn-ibp-table-initialize 8 4 (nth 1 sealed)))))
    (and (equal (nth 0 initialized) :initialized)
         (equal (nth 0 wrong) :stale-chunk) (equal (nth 1 wrong) page)
         (equal (nth 0 sealed) :sealed)
         (equal (fn-ibp-table-sealed (nth 1 sealed)) 1)
         (not (equal (fn-ibp-table-sealed (nth 1 sealed)) 0))
         (equal (nth 0 again) :already-initialized)
         (equal (nth 1 again) (nth 1 sealed)))))
(defthm ibptest-seal-witness (ibptest-seal) :rule-classes nil)
