(in-package "ACL2")
(include-book "../../books/index-backing-provider")

; Directory/control representation fixtures, not whole O/funding witnesses.
(defun-nx ibptest-absent-read ()
  (let* ((node (create-fn-ibp-node))
         (read (fn-ibp-node-left-id-read node)))
    (and (equal read '(:unavailable nil))
         (equal (fn-ibp-node-children-count node) 0))))
(defthm ibptest-absent-read-witness (ibptest-absent-read) :rule-classes nil)

(defun ibptest-directory-yield ()
  (let* ((root '(:branch (:chunk 3 17 2) (:chunk 4 18 2)))
         (first (mv-list 4 (fn-ibp-directory-step (fn-ibp-directory-start root 1 1) 1)))
         (second (mv-list 4 (fn-ibp-directory-step (nth 1 first) 1))))
    (and (equal (nth 0 first) :yield) (equal (nth 2 first) nil)
         (equal (nth 1 first) '((:chunk 4 18 2) 0 0))
         (equal second '(:borrow-ready ((:chunk 4 18 2) 0 0) (:chunk 4 18 2) 0)))))
(assert-event (ibptest-directory-yield))

(defun-nx ibptest-registered-borrow ()
  (let* ((segment (update-fn-ibp-qs-id 1 (create-fn-ibp-query-segment)))
         (token (fn-ibp-query-token 1 1 0 1))
         (query (fn-miq-make 1 1 '(1 2) 1 9 2 "<a@x>" 7 '(1 2 0) nil nil :probing))
         (capture (fn-ibp-capture-make 1 '(1 2) 2 1 9
                    '(:branch (:chunk 3 17 2) (:chunk 4 18 2)) 1 1 nil 0 2))
         (registered (mv-list 2 (fn-ibp-query-slot-register token query capture segment)))
         (started (mv-list 2 (fn-ibp-query-slot-borrow-start token :table (nth 1 registered))))
         (first (mv-list 4 (fn-ibp-query-slot-borrow-step token 1 (nth 1 started))))
         (second (mv-list 4 (fn-ibp-query-slot-borrow-step token 1 (nth 3 first)))))
    (and (equal (nth 0 registered) :captured)
         (fn-ibp-query-slot-livep token (nth 1 registered))
         (not (fn-ibp-query-slot-livep (fn-ibp-query-token 2 1 0 1) (nth 1 registered)))
         (equal (nth 0 started) :borrowing)
         (equal (nth 0 first) :yield) (equal (nth 1 first) nil)
         (equal (nth 0 second) :borrow-ready) (equal (nth 1 second) '(:chunk 4 18 2))
         (equal (fn-ibp-qs-controlsi 0 (nth 3 second)) query)
         (equal (fn-miq-answer query) nil))))
(defthm ibptest-registered-borrow-witness (ibptest-registered-borrow) :rule-classes nil)

; Terminal zero remains a selected ordinal; unfinished work is not absence.
(defun ibptest-selected-zero ()
  (let* ((token (fn-ibp-query-token 1 1 0 1))
         (query (fn-miq-make 1 1 '(1 2) 1 9 2 "<a@x>" 7 '(1 2 0) nil 0 :done))
         (capture (fn-ibp-capture-make 1 '(1 2) 2 1 9 nil 0 1 nil 0 2))
         (selected (fn-miq-selected-token token 0 2))
         (held '(retained-row-reference))
         (borrow (list :selected selected held '(:chunk 4 18 2))))
    (and (fn-miq-selected-tokenp selected)
         (fn-ibp-query-capture-matchesp query capture)
         (equal (mv-list 2 (fn-ibp-selected-observation selected query capture borrow))
                (list :selected held))
         (equal (mv-list 2 (fn-ibp-selected-observation
                          (fn-miq-selected-token (fn-ibp-query-token 2 1 0 1) 0 2)
                          query capture borrow))
                '(:recovery-required nil)))))
(assert-event (ibptest-selected-zero))

; Synthetic retained-state fixture: exercises the composed projection and
; active indexed grants, not publication/funding/faithful source authorization.
(defun-nx ibptest-active-selected-read ()
  (let* ((token (fn-ibp-query-token 1 1 0 1))
         (query (fn-miq-make 1 1 '(1 2) 1 9 2 "<a@x>" 7 '(1 2 0) nil 0 :done))
         (capture (fn-ibp-capture-make 1 '(1 2) 2 1 9 nil 0 1 nil 0 2))
         (grant '(:query-grant 1 1 0 1 1 2 1 9 1 4 8))
         (qpg (update-fn-qpg-segment-id 1 (create-fn-query-payload-grants)))
         (acquired (mv-list 3 (fn-qpg-acquire 1 0 1 4 8 grant qpg)))
         (qpg-token (nth 1 acquired))
         (segment (update-fn-ibp-qs-id 1 (create-fn-ibp-query-segment)))
         (registered (mv-list 2 (fn-ibp-query-slot-register token query capture segment)))
         (segment (update-fn-ibp-qs-inputsi 0 (list :query-context nil nil nil nil qpg-token)
                                            (nth 1 registered)))
         (segment (update-fn-ibp-qs-admissionsi 0 (list grant '(1 0 0 0 0) :active 1) segment))
         (selected (fn-miq-selected-token token 0 2))
         (held '(retained-row-reference))
         (updated (mv-list 2 (fn-ibp-query-slot-update token query
                              (list :selected selected held '(:chunk 4 18 2)) segment)))
         (node (fn-ibp-node-children-put 'fn-ibp-query-segment (nth 1 updated) (create-fn-ibp-node)))
         (node (fn-ibp-node-children-put 'fn-query-payload-grants (nth 2 acquired) node))
         (backing (update-fn-ibp-registry node (create-fn-index-backing)))
         (backing (update-fn-ibp-pool-capacity 1 backing))
         (mio (update-fn-mio$c-provider backing (create-fn-mio$c)))
         (answer (mv-list 4 (fn-miq-selected-read selected 3 mio)))
         (released (mv-list 3 (fn-qpg-release qpg-token :joined (nth 2 acquired))))
         (node (fn-ibp-node-children-put 'fn-query-payload-grants (nth 2 released) node))
         (backing (update-fn-ibp-registry node backing))
         (after (mv-list 4 (fn-miq-selected-read selected 3
                                             (update-fn-mio$c-provider backing mio)))))
    (and (equal (nth 0 acquired) :acquired)
         (equal (nth 0 registered) :captured)
         (equal (nth 0 updated) :updated)
         (equal answer (list :selected held qpg-token 0))
         (equal (nth 0 released) :released)
         (equal after '(:recovery-required nil nil 0)))))
(defthm ibptest-active-selected-read-witness (ibptest-active-selected-read) :rule-classes nil)
