(in-package "ACL2")
(include-book "../../books/index-query-resources")
(defconst *iqr-ledger* (nth 1 (mv-list 2 (fn-prl-make-baseline '(1000000 0 2 2 100) '(1000 0 0 0 0)))))
(defconst *iqr-token* '(:query-grant 21 11 0 3 40 41 100 90 3 7 100))
(defconst *iqr-admitted* (mv-list 4 (fn-iqr-admit *iqr-ledger* *iqr-token* nil '(4096 0 0 0 0))))
(defconst *iqr-row* (nth 2 *iqr-admitted*))
(defconst *iqr-held* (nth 3 *iqr-admitted*))
(assert-event (and (fn-iqr-tokenp *iqr-token*) (equal (nth 0 *iqr-admitted*) :admitted)
                  (fn-iqr-livep *iqr-token* *iqr-row*)
                  (equal (fn-prl-nth 1 *iqr-held*) '(4096 0 0 0 0))
                  (equal (fn-prl-nth 2 *iqr-held*) (fn-prl-nth 2 *iqr-ledger*))
                  (equal (fn-prl-nth 3 *iqr-held*) (fn-prl-nth 3 *iqr-ledger*))))
; Literal cancellation pool retention plus unjoined exact row/pool retention.
(assert-event (and
  (equal (nth 2 (mv-list 3 (fn-iqr-cancel *iqr-token* *iqr-row* *iqr-held*))) *iqr-held*)
  (not (eq :cancelled :joined))
  (equal (nth 1 (mv-list 3 (fn-iqr-release *iqr-token* *iqr-row* :cancelled *iqr-held*))) *iqr-row*)
  (equal (nth 2 (mv-list 3 (fn-iqr-release *iqr-token* *iqr-row* :cancelled *iqr-held*))) *iqr-held*)))
; Literal other-query antecedent and entire stale outcome.
(assert-event (and (not (equal '(:query-grant 22 11 0 3 40 41 100 90 3 7 100) (fn-prl-nth 0 *iqr-row*)))
  (equal (mv-list 3 (fn-iqr-release '(:query-grant 22 11 0 3 40 41 100 90 3 7 100) *iqr-row* :joined *iqr-held*))
         (list :stale *iqr-row* *iqr-held*))))
(defconst *iqr-promoted* (mv-list 3 (fn-iqr-promote-installed-capacity *iqr-token* *iqr-row* '(1024 0 0 0 0) *iqr-held*)))
(assert-event (and (fn-iqr-resident-promotion-domainp *iqr-held* '(1024 0 0 0 0))
  (equal (fn-iqr-resident-total (nth 2 *iqr-promoted*)) (fn-iqr-resident-total *iqr-held*))
  (equal (nth 0 *iqr-promoted*) :promoted)
  (equal (fn-prl-baseline (nth 2 *iqr-promoted*)) '(2024 0 0 0 0))
  (equal (fn-prl-nth 1 (nth 2 *iqr-promoted*)) '(3072 0 0 0 0))
  (equal (fn-prl-nth 1 (nth 1 *iqr-promoted*)) '(3072 0 0 0 0))
  (equal (fn-prs-plus (fn-prl-baseline (nth 2 *iqr-promoted*)) (fn-prl-nth 1 (nth 2 *iqr-promoted*)))
         (fn-prs-plus (fn-prl-baseline *iqr-held*) (fn-prl-nth 1 *iqr-held*)))))
(defconst *iqr-released* (mv-list 3 (fn-iqr-release *iqr-token* (nth 1 *iqr-promoted*) :joined (nth 2 *iqr-promoted*))))
(assert-event (and (equal (nth 0 *iqr-released*) :released)
  (equal (fn-prl-baseline (nth 2 *iqr-released*)) '(2024 0 0 0 0))
  (equal (fn-prl-nth 1 (nth 2 *iqr-released*)) '(0 0 0 0 0))
  (equal (nth 0 (mv-list 4 (fn-iqr-admit (nth 2 *iqr-released*) *iqr-token* (nth 1 *iqr-released*) '(4096 0 0 0 0)))) :refused)))
; Refusal before allocations does not mutate the shared capacity.
(assert-event (equal (mv-list 4 (fn-iqr-admit *iqr-ledger* *iqr-token* nil '(1000001 0 0 0 0)))
                     (list :refused nil nil *iqr-ledger*)))
