; Historical held15 MODEL fixtures. Grant/registry setup is synthetic;
; no genuine published captured-source or native reachability claim.
(in-package "ACL2")
(include-book "../../books/index-range-render-output")
(defun-nx ibrjout2-setup ()
 (let* ((arena '((65 66 67)))
        (token '(:index-query 17 1 0 7))
        (publication (fn-ipub-make 7 nil nil 1 19 7 nil 0 11 nil 0 12 nil 13 nil nil 4 1))
        (range '("g" 1 3 7 nil t))
        (plan (fn-spp-begin nil '(:source 17) '(:resource 18)))
        (number (fn-gns-number-step (fn-gns-number-begin 1 (cons '(:ordinal 0) nil) 1)))
        (control (fn-ibr-make 17 7 :row plan
          (list :publication-pin '(:generation 7) publication)
          (fn-gns-group-begin "g" nil) number (fn-ibr-work range publication nil nil)))
        (held (fn-held-make 0 1 0 "<e@x>" 0 '("g") "o" "s" "e" 1 5
          (fn-hf-make 3 nil 0 (list nil nil nil (fn-hnov-make nil t "s" "f" "d" "<e@x>" "")))
          (fn-hc-make (fn-stx-make-verdict :absent nil 0) nil 0) '(("g" . 1)) nil))
        (control (mv-nth 1 (fn-ibr-selected-held-row-install control held arena)))
        (capture (fn-ibp-capture-make 7 nil nil 1 19 nil 0 11 nil 0 12))
        (claim '(:query-grant 17 1 0 7 11 12 1 19 7 4 1))
        (qpg (update-fn-qpg-segment-id 1 (create-fn-query-payload-grants)))
        (acquired (mv-list 3 (fn-qpg-acquire 17 0 7 4 1 claim qpg)))
        (qpg-token (nth 1 acquired))
        (segment (update-fn-ibp-qs-id 1 (create-fn-ibp-query-segment)))
        (registered (mv-list 2 (fn-ibp-slot-register token :range control capture
          (list :query-context :saved :step :source :receiver qpg-token) segment)))
        (segment (update-fn-ibp-qs-admissionsi 0 (list claim '(1 0 0 0 0) :active 1)
                      (nth 1 registered))))
  (let* ((qpg (nth 2 acquired))
         (segment (mv-nth 2 (fn-ibr-joint-segment-held-one token segment qpg arena)))
         (segment (mv-nth 2 (fn-ibr-joint-segment-held-one token segment qpg arena)))
         (segment (mv-nth 2 (fn-ibr-joint-segment-held-one token segment qpg arena)))
         (segment (mv-nth 2 (fn-ibr-joint-segment-held-one token segment qpg arena)))
         (segment (mv-nth 2 (fn-ibr-joint-segment-held-one token segment qpg arena))))
    (list token segment qpg arena))))

(defthm ibrjout2-actual-cached-row-first-byte-model-positive
 (let* ((setup (ibrjout2-setup)) (token (nth 0 setup))
        (segment (nth 1 setup)) (qpg (nth 2 setup)) (arena (nth 3 setup))
        (control (fn-ibp-qs-controlsi 0 segment))
        (step (fn-ibr-joint-segment-held-one token segment qpg arena))
        (answer (fn-ibr-joint-segment-held-output-one 1 token segment qpg arena nil)))
  (and (fn-ibp-query-slot-livep token segment)
       (fn-ibr-held-current-ready-p control arena)
       (equal (fn-hmid-at 4 (fn-spp-at 4 (fn-spp-at 8 control))) :row)
       (equal (fn-hmid-at 2 (fn-hmid-at 5 (fn-spp-at 4 (fn-spp-at 8 control)))) :emit)
       (equal (mv-nth 0 (fn-ibr-joint-segment-demand token segment qpg arena)) :none)
       (equal (mv-nth 0 step) '(50))
       (equal (mv-nth 0 answer) (mv-nth 1 step))
       (equal (mv-nth 1 answer) (mv-nth 2 step))
       (equal (mv-nth 2 answer) (append nil (mv-nth 0 step)))
       (equal (fn-octets-len (mv-nth 2 answer)) 1)
       (fn-ibr-held-current-ready-p (fn-ibp-qs-controlsi 0 (mv-nth 1 answer)) arena)))
 :rule-classes nil)
(defthm ibrjout2-full-window-does-not-consume-next-byte-model
 (let* ((setup (ibrjout2-setup)) (token (nth 0 setup))
        (segment (nth 1 setup)) (qpg (nth 2 setup)) (arena (nth 3 setup))
        (first (fn-ibr-joint-segment-held-output-one 1 token segment qpg arena nil))
        (nextsegment (mv-nth 1 first)) (buffer (mv-nth 2 first))
        (second (fn-ibr-joint-segment-held-output-one 1 token nextsegment qpg arena buffer)))
  (and (equal buffer '(50))
       (equal (fn-octets-len buffer) 1)
       (equal (mv-nth 0 second) :output-full)
       (equal (mv-nth 1 second) nextsegment)
       (equal (mv-nth 2 second) buffer)))
 :rule-classes nil)


; MUTATION: unsupported fractional capacity, not a reachable guarded call.
(defthm ibrjout2-capacity-nat-premise-removal-mutation
 (let* ((s (ibrjout2-setup)) (token (nth 0 s)) (segment (nth 1 s))
        (qpg (nth 2 s)) (arena (nth 3 s)) (capacity 1/2)
        (answer (fn-ibr-joint-segment-held-output-one capacity token segment qpg arena nil)))
  (and (fn-ibp-query-slot-livep token segment)
       (fn-ibr-held-current-ready-p (fn-ibp-qs-controlsi 0 segment) arena)
       (not (natp capacity)) (<= (fn-octets-len nil) capacity)
       (not (<= (fn-octets-len (mv-nth 2 answer)) capacity))))
 :rule-classes nil)
; MUTATION: preexisting buffer exceeds its allowance; no issued factory claim.
(defthm ibrjout2-capacity-prefix-premise-removal-mutation
 (let* ((s (ibrjout2-setup)) (token (nth 0 s)) (segment (nth 1 s))
        (qpg (nth 2 s)) (arena (nth 3 s)) (capacity 0) (buffer '(50))
        (answer (fn-ibr-joint-segment-held-output-one capacity token segment qpg arena buffer)))
  (and (fn-ibp-query-slot-livep token segment)
       (fn-ibr-held-current-ready-p (fn-ibp-qs-controlsi 0 segment) arena)
       (natp capacity) (not (<= (fn-octets-len buffer) capacity))
       (not (<= (fn-octets-len (mv-nth 2 answer)) capacity))
       (equal (mv-nth 0 answer) :output-full)
       (equal (mv-nth 1 answer) segment) (equal (mv-nth 2 answer) buffer)))
 :rule-classes nil)
