; Actual ledger/registry transition fixtures with synthetic installed capacity.
; These do not qualify runtime constructors or an actual accepted owner open.
(in-package "ACL2")
(include-book "../../books/index-connection-issuer")
(defun fn-icr-test-setup (children fn-index-backing fn-page-read-pool)
 (declare (xargs :stobjs (fn-index-backing fn-page-read-pool) :guard t))
 (let* ((fn-page-read-pool
          (fn-owner-page-read-keep-ledger
           (fn-prl-build '(1000 1000 5 5 99) '(0 0 0 0 0) 0 '(:legacy) '(100 0 0 0 0))
           fn-page-read-pool))
        (fn-index-backing (update-fn-ibp-pool-capacity 1 fn-index-backing)))
  (if (not children) (mv fn-index-backing fn-page-read-pool)
   (stobj-let ((fn-ibp-node (fn-ibp-registry fn-index-backing)))
    (fn-ibp-node)
    (stobj-let ((fn-ibp-generation-segment
                (fn-ibp-node-children-get 'fn-ibp-generation-segment fn-ibp-node
                                         (create-fn-ibp-generation-segment))))
     (fn-ibp-generation-segment)
     (let ((fn-ibp-generation-segment (update-fn-ibp-gs-id 1 fn-ibp-generation-segment)))
      (mv-let (a fn-ibp-generation-segment)
       (fn-ibp-generation-begin '(:index-generation 9 1 0) :gen-grant fn-ibp-generation-segment)
       (declare (ignore a))
       (mv-let (b fn-ibp-generation-segment)
        (fn-ibp-generation-capture-arena '(:index-generation 9 1 0) 7 22 fn-ibp-generation-segment)
        (declare (ignore b))
        (mv-let (c fn-ibp-generation-segment)
         (fn-ibp-generation-install-publication '(:index-generation 9 1 0)
          (fn-ipub-make 9 :key nil 0 3 2 nil 0 1 nil 0 2 nil 3 :complete :selected-view 7 22)
          fn-ibp-generation-segment)
         (declare (ignore c)) fn-ibp-generation-segment))))
     (stobj-let ((fn-ibp-connection-segment
                 (fn-ibp-node-children-get 'fn-ibp-connection-segment fn-ibp-node
                                          (create-fn-ibp-connection-segment))))
      (fn-ibp-connection-segment)
      (update-fn-ich-segment-id 1 fn-ibp-connection-segment)
      fn-ibp-node))
    (let ((fn-index-backing
           (update-fn-ibp-current
            (list :installed-publication '(:index-generation 9 1 0)
             (fn-ipub-make 9 :key nil 0 3 2 nil 0 1 nil 0 2 nil 3 :complete :selected-view 7 22))
            fn-index-backing)))
     (mv fn-index-backing fn-page-read-pool))))))
(defun fn-icr-test-pins (fn-index-backing)
 (declare (xargs :stobjs fn-index-backing :guard t))
 (stobj-let ((fn-ibp-node (fn-ibp-registry fn-index-backing)))
  (word row left)
  (fn-ibp-node-generation-read '(:index-generation 9 1 0) 1 0 0 fn-ibp-node)
  (prog2$ (list word left) (fn-omk-at 4 row))))

(defun fn-icr-test-lifecycle (fn-index-backing fn-page-read-pool)
 (declare (xargs :stobjs (fn-index-backing fn-page-read-pool) :guard t))
 (mv-let (fn-index-backing fn-page-read-pool)
  (fn-icr-test-setup t fn-index-backing fn-page-read-pool)
  (mv-let (word token fn-index-backing fn-page-read-pool)
 (fn-icr-reserve 1000000 '(40 0 0 0 1) fn-index-backing fn-page-read-pool)
 (let ((ok0 (and (eq word :reserved) (equal token '(:connection-holder 1 1 0)) (equal (fn-prl-nth 1 (fn-owner-page-read-ledger fn-page-read-pool)) '(40 0 0 0 1)) (equal (fn-prl-nth 2 (fn-owner-page-read-ledger fn-page-read-pool)) 1) (equal (fn-prl-baseline (fn-owner-page-read-ledger fn-page-read-pool)) '(100 0 0 0 0)) (equal (fn-prl-nth 3 (fn-owner-page-read-ledger fn-page-read-pool)) '(:legacy)))))
 (mv-let (word ignored fn-index-backing fn-page-read-pool)
 (fn-icr-reserve 9 '(40 0 0 0 1) fn-index-backing fn-page-read-pool)
 (let ((ok1 (and (eq word :busy) (not ignored) (equal (fn-prl-nth 2 (fn-owner-page-read-ledger fn-page-read-pool)) 1) (equal (fn-prl-nth 1 (fn-owner-page-read-ledger fn-page-read-pool)) '(40 0 0 0 1)))))
 (mv-let (word left fn-index-backing)
 (fn-icr-register token 1 fn-index-backing)
 (let ((ok2 (and (eq word :registered) (equal left 0))))
 (mv-let (word left fn-index-backing)
 (fn-icr-register token 1 fn-index-backing)
 (let ((ok3 (and (eq word :registered) (equal left 1) (equal (fn-icr-test-pins fn-index-backing) 0))))
 (mv-let (word ignored left fn-index-backing)
 (fn-icr-capture token :d 2 fn-index-backing)
 (let ((ok4 (and (eq word :unavailable) (not ignored) (equal left 2) (equal (fn-icr-test-pins fn-index-backing) 0) (eq (fn-omk-at 6 (fn-ibp-connection-pending fn-index-backing)) :registered))))
 (mv-let (word ignored left fn-index-backing)
 (fn-icr-capture token :current 1 fn-index-backing)
 (let ((ok5 (and (eq word :yield) (not ignored) (equal left 1) (equal (fn-icr-test-pins fn-index-backing) 0))))
 (mv-let (word pin left fn-index-backing)
 (fn-icr-capture token :current 2 fn-index-backing)
 (let ((ok6 (and (eq word :captured) pin (equal left 0) (equal (fn-icr-test-pins fn-index-backing) 1) (eq (fn-omk-at 6 (fn-ibp-connection-pending fn-index-backing)) :source-owned))))
 (mv-let (word same left fn-index-backing)
 (fn-icr-capture token :current 2 fn-index-backing)
 (let ((ok7 (and (eq word :captured) (equal same pin) (equal left 2) (equal (fn-icr-test-pins fn-index-backing) 1))))
 (mv-let (word row left)
 (fn-ibp-connection-read token 1 fn-index-backing)
 (let ((ok8 (mv-let (bad bad-pin) (fn-ich-row-source 999 row)
 (mv-let (good good-pin) (fn-ich-row-source 1000000 row)
 (and (eq word :present) (equal left 0) (eq bad :stale) (not bad-pin) (eq good :current) (equal good-pin pin))))))
 (mv-let (word left fn-index-backing)
 (fn-icr-finish-open 1000000 token 1 fn-index-backing)
 (let ((ok9 (and (eq word :opened) (equal left 0) (not (fn-ibp-connection-pending fn-index-backing)))))
 (mv-let (word ignored left fn-index-backing)
 (fn-ibp-connection-event token :acquire 1000000 nil 1 fn-index-backing)
 (let ((ok10 (and (eq word :acquired) (not ignored) (equal left 0))))
 (mv-let (word ignored left fn-index-backing)
 (fn-ibp-connection-event token :close 1000000 nil 1 fn-index-backing)
 (let ((ok11 (and (eq word :closing) (not ignored) (equal left 0))))
 (mv-let (word left fn-index-backing fn-page-read-pool)
 (fn-icr-settle token 4 fn-index-backing fn-page-read-pool)
 (let ((ok12 (and (eq word :held) (equal left 3) (equal (fn-icr-test-pins fn-index-backing) 1) (equal (fn-prl-nth 1 (fn-owner-page-read-ledger fn-page-read-pool)) '(40 0 0 0 1)))))
 (mv-let (word ignored left fn-index-backing)
 (fn-ibp-connection-event token :return 1000000 nil 1 fn-index-backing)
 (let ((ok13 (and (eq word :returned) (not ignored) (equal left 0))))
 (mv-let (word left fn-index-backing fn-page-read-pool)
 (fn-icr-settle token 4 fn-index-backing fn-page-read-pool)
 (let ((ok14 (and (eq word :released) (equal left 0) (equal (fn-icr-test-pins fn-index-backing) 0) (equal (fn-prl-nth 1 (fn-owner-page-read-ledger fn-page-read-pool)) '(0 0 0 0 1)) (equal (fn-prl-nth 2 (fn-owner-page-read-ledger fn-page-read-pool)) 1) (equal (fn-ibp-connection-free fn-index-backing) '(0)))))
 (mv-let (word left fn-index-backing fn-page-read-pool)
 (fn-icr-settle token 4 fn-index-backing fn-page-read-pool)
 (let ((ok15 (and (eq word :stale) (equal left 3) (equal (fn-icr-test-pins fn-index-backing) 0) (equal (fn-prl-nth 1 (fn-owner-page-read-ledger fn-page-read-pool)) '(0 0 0 0 1)) (equal (fn-ibp-connection-free fn-index-backing) '(0)))))
 (mv-let (word newtoken fn-index-backing fn-page-read-pool)
 (fn-icr-reserve 1000001 '(40 0 0 0 1) fn-index-backing fn-page-read-pool)
 (let ((ok16 (and (eq word :reserved) (equal newtoken '(:connection-holder 2 1 0)) (equal (fn-prl-nth 1 (fn-owner-page-read-ledger fn-page-read-pool)) '(40 0 0 0 2)) (equal (fn-prl-nth 2 (fn-owner-page-read-ledger fn-page-read-pool)) 2) (equal (fn-ibp-connection-highwater fn-index-backing) 1))))
 (mv-let (word left fn-index-backing)
 (fn-icr-register newtoken 1 fn-index-backing)
 (let ((ok17 (and (eq word :registered) (equal left 0))))
 (mv-let (word row left)
 (fn-ibp-connection-read token 1 fn-index-backing)
 (let ((ok18 (and (eq word :stale) (not row) (equal left 0))))
 (mv (list ok0 ok1 ok2 ok3 ok4 ok5 ok6 ok7 ok8 ok9 ok10 ok11 ok12 ok13 ok14 ok15 ok16 ok17 ok18) fn-index-backing fn-page-read-pool)))))))))))))))))))))))))))))))))))))))))
(defun fn-icr-test-lifecycle-exec ()
 (declare (xargs :guard t))
 (with-local-stobj fn-index-backing
  (mv-let (result fn-index-backing)
   (with-local-stobj fn-page-read-pool
    (mv-let (result fn-index-backing fn-page-read-pool)
     (fn-icr-test-lifecycle fn-index-backing fn-page-read-pool)
     (mv result fn-index-backing)))
   result)))
(assert-event (equal (fn-icr-test-lifecycle-exec) '(t t t t t t t t t t t t t t t t t t t)))

(defun fn-icr-test-refusals (fn-index-backing fn-page-read-pool)
 (declare (xargs :stobjs (fn-index-backing fn-page-read-pool) :guard t))
 (mv-let (fn-index-backing fn-page-read-pool)
  (fn-icr-test-setup nil fn-index-backing fn-page-read-pool)
  (mv-let (word ignored fn-index-backing fn-page-read-pool)
 (fn-icr-reserve 7 '(40 0 0 0 0) fn-index-backing fn-page-read-pool)
 (let ((ok0 (and (eq word :unsupported-runtime) (not ignored) (equal (fn-prl-nth 2 (fn-owner-page-read-ledger fn-page-read-pool)) 0))))
 (mv-let (word ignored fn-index-backing fn-page-read-pool)
 (fn-icr-reserve 7 '(901 0 0 0 1) fn-index-backing fn-page-read-pool)
 (let ((ok1 (and (eq word :read-resources-unavailable) (not ignored) (equal (fn-prl-nth 2 (fn-owner-page-read-ledger fn-page-read-pool)) 0) (equal (fn-ibp-connection-highwater fn-index-backing) 0))))
 (mv-let (word token fn-index-backing fn-page-read-pool)
 (fn-icr-reserve 7 '(40 0 0 0 1) fn-index-backing fn-page-read-pool)
 (let ((ok2 (and (eq word :reserved) (equal token '(:connection-holder 1 1 0)))))
 (mv-let (word left fn-index-backing)
 (fn-icr-register token 1 fn-index-backing)
 (let ((ok3 (and (eq word :unavailable) (equal left 1) (equal (fn-prl-nth 1 (fn-owner-page-read-ledger fn-page-read-pool)) '(40 0 0 0 1)) (eq (fn-omk-at 6 (fn-ibp-connection-pending fn-index-backing)) :charged))))
 (mv-let (word left fn-index-backing)
 (let ((fn-index-backing (update-fn-ibp-connection-pending
 (fn-icr-keep-phase (fn-ibp-connection-pending fn-index-backing) :register-intent nil) fn-index-backing)))
 (fn-icr-register token 1 fn-index-backing))
 (let ((ok4 (and (eq word :recovery-required) (equal left 1) (eq (fn-omk-at 6 (fn-ibp-connection-pending fn-index-backing)) :register-intent) (equal (fn-prl-nth 2 (fn-owner-page-read-ledger fn-page-read-pool)) 1))))
 (mv-let (word ignored left fn-index-backing)
 (let ((fn-index-backing (update-fn-ibp-connection-pending
 (fn-icr-keep-phase (fn-ibp-connection-pending fn-index-backing) :pin-intent '(:index-generation 9 1 0)) fn-index-backing)))
 (fn-icr-capture token :current 2 fn-index-backing))
 (let ((ok5 (and (eq word :recovery-required) (not ignored) (equal left 2) (eq (fn-omk-at 6 (fn-ibp-connection-pending fn-index-backing)) :pin-intent) (equal (fn-prl-nth 1 (fn-owner-page-read-ledger fn-page-read-pool)) '(40 0 0 0 1)))))
 (mv-let (word left fn-index-backing fn-page-read-pool)
 (fn-icr-settle token 4 fn-index-backing fn-page-read-pool)
 (let ((ok6 (and (eq word :recovery-required) (equal left 4) (equal (fn-prl-nth 2 (fn-owner-page-read-ledger fn-page-read-pool)) 1))))
 (mv (list ok0 ok1 ok2 ok3 ok4 ok5 ok6) fn-index-backing fn-page-read-pool)))))))))))))))))
(defun fn-icr-test-refusals-exec ()
 (declare (xargs :guard t))
 (with-local-stobj fn-index-backing
  (mv-let (result fn-index-backing)
   (with-local-stobj fn-page-read-pool
    (mv-let (result fn-index-backing fn-page-read-pool)
     (fn-icr-test-refusals fn-index-backing fn-page-read-pool)
     (mv result fn-index-backing)))
   result)))
(assert-event (equal (fn-icr-test-refusals-exec) '(t t t t t t t)))

; A successful retain followed by interrupted attachment owns one reference.
; Resume may attach that SAME pin, never retain a second one. The subsequent
; injected settlement intent models an uncertain cut, not a reachable success.
(defun fn-icr-test-retained-cut (fn-index-backing fn-page-read-pool)
 (declare (xargs :stobjs (fn-index-backing fn-page-read-pool) :guard t))
 (mv-let (fn-index-backing fn-page-read-pool)
  (fn-icr-test-setup t fn-index-backing fn-page-read-pool)
  (mv-let (a token fn-index-backing fn-page-read-pool)
   (fn-icr-reserve 7 '(40 0 0 0 1) fn-index-backing fn-page-read-pool)
   (mv-let (b l0 fn-index-backing) (fn-icr-register token 1 fn-index-backing)
    (mv-let (c pub l1 fn-index-backing)
     (fn-ibp-generation-reference '(:index-generation 9 1 0) :retain :pin nil 1 fn-index-backing)
     (let* ((pin (list :publication-pin '(:index-generation 9 1 0) pub))
            (fn-index-backing
             (update-fn-ibp-connection-pending
              (fn-icr-keep-phase (fn-ibp-connection-pending fn-index-backing) :pin-owned pin)
              fn-index-backing)))
      (mv-let (d actual l2 fn-index-backing) (fn-icr-capture token :current 2 fn-index-backing)
       (let* ((count (fn-icr-test-pins fn-index-backing))
              (fn-index-backing
               (update-fn-ibp-connection-pending
                (fn-icr-keep-phase (fn-ibp-connection-pending fn-index-backing) :settle-intent pin)
                fn-index-backing)))
        (mv-let (e l3 fn-index-backing fn-page-read-pool)
         (fn-icr-settle token 4 fn-index-backing fn-page-read-pool)
         (mv-let (f ignored fn-index-backing fn-page-read-pool)
          (fn-icr-reserve 8 '(40 0 0 0 1) fn-index-backing fn-page-read-pool)
          (mv (list a b l0 c l1 d (equal actual pin) l2 count e l3 f ignored
                    (fn-icr-test-pins fn-index-backing)
                    (fn-owner-page-read-ledger fn-page-read-pool)
                    (fn-omk-at 6 (fn-ibp-connection-pending fn-index-backing)))
              fn-index-backing fn-page-read-pool)))))))))))
(defun fn-icr-test-retained-cut-exec ()
 (declare (xargs :guard t))
 (with-local-stobj fn-index-backing
  (mv-let (result fn-index-backing)
   (with-local-stobj fn-page-read-pool
    (mv-let (result fn-index-backing fn-page-read-pool)
     (fn-icr-test-retained-cut fn-index-backing fn-page-read-pool)
     (mv result fn-index-backing)))
   result)))
(assert-event
 (equal (fn-icr-test-retained-cut-exec)
  '(:reserved :registered 0 :retained 0 :captured t 1 1
    :recovery-required 4 :recovery-required nil 1
    ((1000 1000 5 5 99) (40 0 0 0 1) 1 (:legacy) (100 0 0 0 0)) :settle-intent)))

(defun fn-icr-test-abort (phase fn-index-backing fn-page-read-pool)
 (declare (xargs :stobjs (fn-index-backing fn-page-read-pool) :guard t))
 (mv-let (fn-index-backing fn-page-read-pool)
  (fn-icr-test-setup t fn-index-backing fn-page-read-pool)
  (mv-let (a token fn-index-backing fn-page-read-pool)
   (fn-icr-reserve 7 '(40 0 0 0 1) fn-index-backing fn-page-read-pool)
   (declare (ignore a))
   (mv-let (b l0 fn-index-backing)
    (if (eq phase :charged) (mv :not-needed 1 fn-index-backing)
      (fn-icr-register token 1 fn-index-backing))
    (declare (ignore b l0))
    (mv-let (c pin l1 fn-index-backing)
     (if (eq phase :source-owned) (fn-icr-capture token :current 2 fn-index-backing)
       (mv :not-needed nil 2 fn-index-backing))
     (declare (ignore c pin l1))
     (mv-let (released left fn-index-backing fn-page-read-pool)
      (fn-icr-abort token 5 fn-index-backing fn-page-read-pool)
      (declare (ignore left))
      (mv-let (again left fn-index-backing fn-page-read-pool)
       (fn-icr-abort token 5 fn-index-backing fn-page-read-pool)
       (declare (ignore left))
       (mv (list released again (fn-icr-test-pins fn-index-backing)
                 (fn-owner-page-read-ledger fn-page-read-pool)
                 (fn-ibp-connection-free fn-index-backing)
                 (fn-ibp-connection-pending fn-index-backing))
           fn-index-backing fn-page-read-pool))))))))
(defun fn-icr-test-abort-exec (phase)
 (declare (xargs :guard t))
 (with-local-stobj fn-index-backing
  (mv-let (result fn-index-backing)
   (with-local-stobj fn-page-read-pool
    (mv-let (result fn-index-backing fn-page-read-pool)
     (fn-icr-test-abort phase fn-index-backing fn-page-read-pool)
     (mv result fn-index-backing)))
   result)))
(assert-event
 (equal (fn-icr-test-abort-exec :charged)
  '(:released :stale 0 ((1000 1000 5 5 99) (0 0 0 0 1) 1 (:legacy) (100 0 0 0 0)) (0) nil)))
(assert-event
 (equal (fn-icr-test-abort-exec :registered)
  '(:released :stale 0 ((1000 1000 5 5 99) (0 0 0 0 1) 1 (:legacy) (100 0 0 0 0)) (0) nil)))
(assert-event
 (equal (fn-icr-test-abort-exec :source-owned)
  '(:released :stale 0 ((1000 1000 5 5 99) (0 0 0 0 1) 1 (:legacy) (100 0 0 0 0)) (0) nil)))
