; Real registry/reference operations with synthetic admitted children and grants.
; Two distinct publications distinguish D from working, including replay change.
(in-package "ACL2")
(include-book "../../books/index-connection-repin-prepare")
(include-book "index-connection-repin-tests")
(defun fn-icr-test-offer-prepare (use-d fn-index-backing fn-page-read-pool)
 (declare (xargs :stobjs (fn-index-backing fn-page-read-pool) :guard t))
(mv-let (fn-index-backing fn-page-read-pool)
 (fn-icr-test-setup t fn-index-backing fn-page-read-pool)
(mv-let (old-ok old fn-index-backing fn-page-read-pool)
 (fn-icr-test-captured-holder t fn-index-backing fn-page-read-pool)
(let* ((old-association (fn-ibp-current fn-index-backing))
         (d-pin (list :publication-pin (fn-omk-at 1 old-association) (fn-omk-at 2 old-association)))
         (fn-index-backing (fn-icr-test-second-publication fn-index-backing)))
(mv-let (reserved new fn-index-backing fn-page-read-pool)
 (fn-icr-reserve 7 '(40 0 0 0 1) fn-index-backing fn-page-read-pool)
(mv-let (registered register-left fn-index-backing)
 (fn-icr-register new 1 fn-index-backing)
(let ((before (fn-ibp-connection-pending fn-index-backing))
       (ledger (fn-owner-page-read-ledger fn-page-read-pool)))
(mv-let (short short-pin short-left fn-index-backing)
 (fn-icr-repin-prepare 7 old new :current 2 fn-index-backing)
(mv-let (same same-pin same-left fn-index-backing)
 (fn-icr-repin-prepare 7 new new :current 3 fn-index-backing)
(mv-let (wrong wrong-pin wrong-left fn-index-backing)
 (fn-icr-repin-prepare 8 old new :current 3 fn-index-backing)
(mv-let (missing missing-pin missing-left fn-index-backing)
 (fn-icr-repin-prepare 7 old new :d 3 fn-index-backing)
(let* ((refusals-ok
 (and (eq short :yield) (not short-pin) (equal short-left 2)
      (eq same :stale) (not same-pin) (equal same-left 3)
      (eq wrong :stale) (not wrong-pin) (equal wrong-left 3)
      (eq missing :unavailable) (not missing-pin) (equal missing-left 2)
      (equal before (fn-ibp-connection-pending fn-index-backing))
      (equal ledger (fn-owner-page-read-ledger fn-page-read-pool))
      (equal (fn-icr-test-gen-refs '(:index-generation 9 1 0) fn-index-backing) '(1 0))
      (equal (fn-icr-test-gen-refs '(:index-generation 10 1 1) fn-index-backing) '(0 0))))
       (fn-index-backing (update-fn-ibp-reader-d-pin d-pin fn-index-backing))
       (kind (if use-d :d :current))
       (expected (if use-d '(:index-generation 9 1 0) '(:index-generation 10 1 1))))
(mv-let (prepared pin left fn-index-backing)
 (fn-icr-repin-prepare 7 old new kind 3 fn-index-backing)
(let ((captured (fn-ibp-connection-pending fn-index-backing))
       (refs (list (fn-icr-test-gen-refs '(:index-generation 9 1 0) fn-index-backing)
                   (fn-icr-test-gen-refs '(:index-generation 10 1 1) fn-index-backing))))
(mv-let (again same-pin again-left fn-index-backing)
 (fn-icr-repin-prepare 7 old new kind 3 fn-index-backing)
(mv-let (changed changed-pin changed-left fn-index-backing)
 (fn-icr-repin-prepare 7 old new (if use-d :current :d) 3 fn-index-backing)
(let ((replay-ok
 (and (eq again :captured) (equal same-pin pin) (equal again-left 2)
      (eq changed :stale-source) (not changed-pin) (equal changed-left 2)
      (equal captured (fn-ibp-connection-pending fn-index-backing))
      (equal ledger (fn-owner-page-read-ledger fn-page-read-pool))
      (equal refs (if use-d '((2 0) (0 0)) '((1 0) (1 0))))
      (equal refs (list (fn-icr-test-gen-refs '(:index-generation 9 1 0) fn-index-backing)
                        (fn-icr-test-gen-refs '(:index-generation 10 1 1) fn-index-backing))))))
(mv-let (released after fn-index-backing fn-page-read-pool)
 (fn-icr-abort new 5 fn-index-backing fn-page-read-pool)
(mv (and old-ok (eq reserved :reserved) (eq registered :registered)
          (equal register-left 0) refusals-ok
          (eq prepared :captured) (equal (fn-omk-at 1 pin) expected) (equal left 0)
          replay-ok (eq released :released) (natp after)
          (equal (fn-icr-test-gen-refs '(:index-generation 9 1 0) fn-index-backing) '(1 0))
          (equal (fn-icr-test-gen-refs '(:index-generation 10 1 1) fn-index-backing) '(0 0))
          (equal (fn-prl-nth 1 (fn-owner-page-read-ledger fn-page-read-pool)) '(40 0 0 0 2))
          (not (fn-ibp-connection-pending fn-index-backing)))
     fn-index-backing fn-page-read-pool)))))))))))))))))))

(defun fn-icr-test-offer-prepare-exec (use-d)
 (declare (xargs :guard t))
 (with-local-stobj fn-index-backing
  (mv-let (result fn-index-backing)
   (with-local-stobj fn-page-read-pool
    (mv-let (result fn-index-backing fn-page-read-pool)
     (fn-icr-test-offer-prepare use-d fn-index-backing fn-page-read-pool)
     (mv result fn-index-backing)))
   result)))
(assert-event (fn-icr-test-offer-prepare-exec nil))
(assert-event (fn-icr-test-offer-prepare-exec t))
