; Representation-only fixture: actual registry/generation/connection operations,
; deliberately synthetic profile grants, publication and child construction.
(in-package "ACL2")
(include-book "../../books/index-backing-connection-pins")
(defun fn-ich-test-registry-setup (fn-index-backing)
 (declare (xargs :stobjs fn-index-backing :guard t))
 (stobj-let ((fn-ibp-node (fn-ibp-registry fn-index-backing)))
  (fn-ibp-node)
  (stobj-let ((fn-ibp-generation-segment
               (fn-ibp-node-children-get 'fn-ibp-generation-segment fn-ibp-node
                                        (create-fn-ibp-generation-segment))))
   (pin fn-ibp-generation-segment)
   (let* ((fn-ibp-generation-segment
            (update-fn-ibp-gs-id 1 fn-ibp-generation-segment))
          (pub (fn-ipub-make 9 :key nil 0 3 2 nil 0 1 nil 0 2 nil 3
                             :complete :selected-view 7 22)))
    (mv-let (a fn-ibp-generation-segment)
     (fn-ibp-generation-begin '(:index-generation 9 1 0) :gen-grant fn-ibp-generation-segment)
     (declare (ignore a))
     (mv-let (b fn-ibp-generation-segment)
      (fn-ibp-generation-capture-arena '(:index-generation 9 1 0) 7 22 fn-ibp-generation-segment)
      (declare (ignore b))
      (mv-let (c fn-ibp-generation-segment)
       (fn-ibp-generation-install-publication '(:index-generation 9 1 0) pub fn-ibp-generation-segment)
       (declare (ignore c))
       (mv-let (d actual-publication fn-ibp-generation-segment)
        (fn-ibp-generation-retain '(:index-generation 9 1 0) :pin fn-ibp-generation-segment)
        (declare (ignore d))
        (mv (list :publication-pin '(:index-generation 9 1 0) actual-publication)
            fn-ibp-generation-segment))))))
   (stobj-let ((fn-ibp-connection-segment
                (fn-ibp-node-children-get 'fn-ibp-connection-segment fn-ibp-node
                                         (create-fn-ibp-connection-segment))))
    (a b fn-ibp-connection-segment)
    (let ((fn-ibp-connection-segment (update-fn-ich-segment-id 1 fn-ibp-connection-segment)))
     (mv-let (a fn-ibp-connection-segment)
      (fn-ich-reserve '(:connection-holder 17 1 0) 42 :conn-grant fn-ibp-connection-segment)
      (mv-let (b fn-ibp-connection-segment)
       (fn-ich-attach '(:connection-holder 17 1 0) pin fn-ibp-connection-segment)
       (mv a b fn-ibp-connection-segment))))
    (prog2$ (list a b) fn-ibp-node)))
  fn-index-backing))
(defun fn-ich-test-pin-count (fn-index-backing)
 (declare (xargs :stobjs fn-index-backing :guard t))
 (stobj-let ((fn-ibp-node (fn-ibp-registry fn-index-backing)))
  (status row left)
  (fn-ibp-node-generation-read '(:index-generation 9 1 0) 1 0 0 fn-ibp-node)
  (prog2$ (list status left) (fn-omk-at 4 row))))
(defun fn-ich-test-registry (fn-index-backing)
 (declare (xargs :stobjs fn-index-backing :guard t))
 (let ((fn-index-backing (fn-ich-test-registry-setup fn-index-backing)))
  (mv-let (a payload left fn-index-backing)
   (fn-ibp-connection-event '(:connection-holder 17 1 0) :acquire 42 nil 1 fn-index-backing)
   (declare (ignore payload left))
   (mv-let (b payload left fn-index-backing)
    (fn-ibp-connection-event '(:connection-holder 17 1 0) :close 42 nil 1 fn-index-backing)
    (declare (ignore payload left))
    (mv-let (held held-grant held-left fn-index-backing)
     (fn-ibp-connection-release '(:connection-holder 17 1 0) 3 fn-index-backing)
     (let ((held-count (fn-ich-test-pin-count fn-index-backing)))
      (mv-let (c payload left fn-index-backing)
       (fn-ibp-connection-event '(:connection-holder 17 1 0) :return 42 nil 1 fn-index-backing)
       (declare (ignore payload left))
       (mv-let (released grant remaining fn-index-backing)
        (fn-ibp-connection-release '(:connection-holder 17 1 0) 3 fn-index-backing)
        (let ((after-count (fn-ich-test-pin-count fn-index-backing)))
         (mv-let (duplicate duplicate-grant duplicate-left fn-index-backing)
          (fn-ibp-connection-release '(:connection-holder 17 1 0) 3 fn-index-backing)
          (mv (list a b held held-grant held-left held-count c released grant remaining
                    after-count duplicate duplicate-grant duplicate-left
                    (fn-ich-test-pin-count fn-index-backing)) fn-index-backing)))))))))))
(defun fn-ich-test-registry-result ()
 (declare (xargs :guard t))
 (with-local-stobj fn-index-backing
  (mv-let (result fn-index-backing) (fn-ich-test-registry fn-index-backing) result)))
(assert-event
 (equal (fn-ich-test-registry-result)
        '(:acquired :closing :held nil 2 1 :returned :released :conn-grant 0
          0 :stale nil 2 0)))
