(in-package "ACL2")
(include-book "../../books/msgid-query-chunk")

; Concrete chunk boundary witness; provider publication/capture is separate.
(defun-nx miqtest-read ()
  (let* ((p (fn-ibp-table-set 0 7 (create-fn-ibp-table-page)))
         (p (fn-ibp-table-set 1024 1 p))
         (actual (fn-miq-chunk-next 7 '(0 1 0) 2 1 0 p))
         (model (fn-mpl-page-next 7 '(0 1 0) 2 1 0 (nth 0 p))))
    (and (fn-ibp-table-pagep p) (fn-mpr-cursorp '(0 1 0) 1)
         (equal actual model)
         (equal actual '(:candidate (0 1 1) 0 1)))))
(defthm miqtest-read-boundary-witness (miqtest-read) :rule-classes nil)

(defun-nx miqtest-place ()
  (let* ((p (create-fn-ibp-table-page))
         (actual (mv-list 4 (fn-miw-chunk-place 7 0 '(0 1 0) 2 1 0 p)))
         (model (fn-mpl-page-place 7 0 '(0 1 0) 2 1 0 (nth 0 p))))
    (and (fn-ibp-table-pagep p) (fn-mpr-cursorp '(0 1 0) 1)
         (posp 7) (unsigned-byte-p 64 7) (natp 0)
         (unsigned-byte-p 64 (+ 1 0))
         (equal (fn-ibp-table-sealed p) 0)
         (equal (nth 0 actual) (nth 0 model))
         (equal (nth 1 actual) (nth 1 model))
         (equal (nth 2 actual) (nth 2 model))
         (equal (nth 0 (nth 3 actual)) (nth 3 model))
         (equal (nth 0 actual) :placed)
         (equal (fn-ibp-table-word 0 (nth 3 actual)) 7)
         (equal (fn-ibp-table-word 1024 (nth 3 actual)) 1))))
(defthm miqtest-place-boundary-witness (miqtest-place) :rule-classes nil)

(defun miqtest-held (seq msgid)
  (fn-held-make seq (+ 1 seq) 0 msgid seq '("fn.test") "o" "s" "e" 1 5
                (fn-hf-make 100 14 2 nil)
                (fn-hc-make (fn-stx-make-verdict :unverified nil 0) nil 0) nil nil))

; Ordinal zero is a genuine match. This checks the internal same-row read,
; not the pending provider root/ordinal-to-chunk association.
(defun-nx miqtest-confirm-zero ()
  (let* ((held (miqtest-held 0 "<a@x>"))
         (p (fn-ibp-row-set 0 held (create-fn-ibp-row-page)))
         (init (mv-list 2 (fn-ibp-row-initialize 1 0 p)))
         (seal (mv-list 2 (fn-ibp-row-seal 1 0 (nth 1 init))))
         (p (nth 1 seal))
         (q (fn-miq-make 1 1 '(1 2) 4 9 1 "<a@x>" 7 '(0 1 1) 0 3 :candidate))
         (answer (fn-miq-row-confirm q 0 p)))
    (and (fn-held-p held) (fn-ibp-row-pagep p)
         (equal (nth 0 init) :initialized) (equal (nth 0 seal) :sealed)
         (equal (fn-ibp-row-sealed p) 1) (posp (fn-ibp-row-id p))
         (natp 0) (< 0 (fn-miq-count q))
         (< (fn-record-sequence held) (fn-miq-frontier q))
         (equal (fn-record-msgid held) (fn-miq-msgid q))
         (equal (nth 0 answer) :continue)
         (equal (fn-miq-best (nth 1 answer)) 0)
         (equal (fn-miq-phase (nth 1 answer)) :probing)
         (equal (fn-miq-answer (nth 1 answer)) nil))))
(defthm miqtest-confirm-zero-witness (miqtest-confirm-zero) :rule-classes nil)
