(in-package "ACL2")
(include-book "../../books/native-redeem-input")

; Complete antecedents and conclusions for the two unconditional keystones.
(assert-event (and (equal (fn-rip-password-step 495 nil 126) :octet)
                   (natp 495) (booleanp nil) (not nil)
                   (integerp 126) (<= 33 126) (<= 126 126)
                   (<= (+ 495 1 13) *fn-nntp-max-command-octets*)))
(assert-event (and (equal (fn-rip-reply-status 512 511) :line)
                   (natp 512) (natp 511) (< 511 512)
                   (<= (+ 511 1) *fn-nntp-max-response-octets*)))
(assert-event (equal (fn-rip-password-step 496 nil 33) :refused))
(assert-event (equal (fn-rip-password-step 496 nil 10) :end))
(assert-event (equal (fn-rip-password-step 1 nil 13) :return))
(assert-event (equal (fn-rip-password-step 1 t 13) :refused))
(assert-event (equal (fn-rip-password-step 1 t 10) :end))
(assert-event (equal (fn-rip-password-step 1 nil 32) :refused))
(assert-event (equal (fn-rip-password-step 1 nil 256) :refused))
(assert-event (equal (fn-rip-password-step 0 nil :eof) :refused))
(assert-event (equal (fn-rip-reply-status 513 512) :refused))
(assert-event (equal (fn-rip-reply-status 511 nil) :need))
(assert-event (equal (fn-rip-reply-status 512 nil) :refused))
