(in-package "ACL2")
(include-book "../../books/ninep-fields")

(defun-nx ninep-fields-read-literal ()
 (let* ((buf (fn-octets-from-list '(23 0 0 0 116 1 0 9 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0) (create-fn-octets)))
        (c0 (fn-9p-fields-start (fn-9p-header-at 0 23 128 buf)))
        (c1 (mv-nth 1 (fn-9p-fields-step c0 buf)))
        (c2 (mv-nth 1 (fn-9p-fields-step c1 buf)))
        (c3 (mv-nth 1 (fn-9p-fields-step c2 buf)))
        (c4 (mv-nth 1 (fn-9p-fields-step c3 buf))))
  (and (fn-octets-p buf)
       (fn-9p-fields-ready-p c0)
       (fn-9p-fields-ready-p c1)
       (fn-9p-fields-ready-p c2)
       (fn-9p-fields-ready-p c3)
       (fn-9p-fields-ready-p c4)
       (equal (nth 9 c4) :parsed)
       (equal (nth 6 c4) '(9 0 3)))))
(defthm ninep-fields-read-literal-holds (ninep-fields-read-literal) :rule-classes nil)

(defun-nx ninep-fields-version-literal ()
 (let* ((buf (fn-octets-from-list '(19 0 0 0 100 1 0 64 0 0 0 6 0 57 80 50 48 48 48) (create-fn-octets)))
        (c0 (fn-9p-fields-start (fn-9p-header-at 0 19 128 buf)))
        (c1 (mv-nth 1 (fn-9p-fields-step c0 buf)))
        (c2 (mv-nth 1 (fn-9p-fields-step c1 buf)))
        (c3 (mv-nth 1 (fn-9p-fields-step c2 buf)))
        (c4 (mv-nth 1 (fn-9p-fields-step c3 buf)))
        (c5 (mv-nth 1 (fn-9p-fields-step c4 buf)))
        (c6 (mv-nth 1 (fn-9p-fields-step c5 buf)))
        (c7 (mv-nth 1 (fn-9p-fields-step c6 buf)))
        (c8 (mv-nth 1 (fn-9p-fields-step c7 buf)))
        (c9 (mv-nth 1 (fn-9p-fields-step c8 buf)))
        (c10 (mv-nth 1 (fn-9p-fields-step c9 buf))))
  (and (fn-octets-p buf)
       (fn-9p-fields-ready-p c0)
       (fn-9p-fields-ready-p c1)
       (fn-9p-fields-ready-p c2)
       (fn-9p-fields-ready-p c3)
       (fn-9p-fields-ready-p c4)
       (fn-9p-fields-ready-p c5)
       (fn-9p-fields-ready-p c6)
       (fn-9p-fields-ready-p c7)
       (fn-9p-fields-ready-p c8)
       (fn-9p-fields-ready-p c9)
       (fn-9p-fields-ready-p c10)
       (equal (nth 9 c10) :parsed)
       (equal (nth 6 c10) '(64 (:string 13 6))))))
(defthm ninep-fields-version-literal-holds (ninep-fields-version-literal) :rule-classes nil)

(defun-nx ninep-fields-nul-refused ()
 (let* ((buf (fn-octets-from-list '(14 0 0 0 100 1 0 64 0 0 0 1 0 0) (create-fn-octets)))
        (c0 (fn-9p-fields-start (fn-9p-header-at 0 14 128 buf)))
        (c1 (mv-nth 1 (fn-9p-fields-step c0 buf)))
        (c2 (mv-nth 1 (fn-9p-fields-step c1 buf)))
        (c3 (mv-nth 1 (fn-9p-fields-step c2 buf))))
  (and (fn-octets-p buf)
       (fn-9p-fields-ready-p c0)
       (fn-9p-fields-ready-p c1)
       (fn-9p-fields-ready-p c2)
       (fn-9p-fields-ready-p c3)
       (equal (nth 9 c3) :malformed-string))))
(defthm ninep-fields-nul-refused-holds (ninep-fields-nul-refused) :rule-classes nil)

(defun-nx ninep-fields-overlong-utf8-refused ()
 (let* ((buf (fn-octets-from-list '(15 0 0 0 100 1 0 64 0 0 0 2 0 192 128) (create-fn-octets)))
        (c0 (fn-9p-fields-start (fn-9p-header-at 0 15 128 buf)))
        (c1 (mv-nth 1 (fn-9p-fields-step c0 buf)))
        (c2 (mv-nth 1 (fn-9p-fields-step c1 buf)))
        (c3 (mv-nth 1 (fn-9p-fields-step c2 buf))))
  (and (fn-octets-p buf)
       (fn-9p-fields-ready-p c0)
       (fn-9p-fields-ready-p c1)
       (fn-9p-fields-ready-p c2)
       (fn-9p-fields-ready-p c3)
       (equal (nth 9 c3) :malformed-string))))
(defthm ninep-fields-overlong-utf8-refused-holds (ninep-fields-overlong-utf8-refused) :rule-classes nil)

(defun-nx ninep-fields-trailing-refused ()
 (let* ((buf (fn-octets-from-list '(12 0 0 0 120 1 0 1 0 0 0 99) (create-fn-octets)))
        (c0 (fn-9p-fields-start (fn-9p-header-at 0 12 128 buf)))
        (c1 (mv-nth 1 (fn-9p-fields-step c0 buf)))
        (c2 (mv-nth 1 (fn-9p-fields-step c1 buf))))
  (and (fn-octets-p buf)
       (fn-9p-fields-ready-p c0)
       (fn-9p-fields-ready-p c1)
       (fn-9p-fields-ready-p c2)
       (equal (nth 9 c2) :trailing-octets))))
(defthm ninep-fields-trailing-refused-holds (ninep-fields-trailing-refused) :rule-classes nil)

(defun-nx ninep-fields-walk-count-refused ()
 (let* ((buf (fn-octets-from-list '(17 0 0 0 110 1 0 1 0 0 0 2 0 0 0 17 0) (create-fn-octets)))
        (c0 (fn-9p-fields-start (fn-9p-header-at 0 17 128 buf)))
        (c1 (mv-nth 1 (fn-9p-fields-step c0 buf)))
        (c2 (mv-nth 1 (fn-9p-fields-step c1 buf)))
        (c3 (mv-nth 1 (fn-9p-fields-step c2 buf))))
  (and (fn-octets-p buf)
       (fn-9p-fields-ready-p c0)
       (fn-9p-fields-ready-p c1)
       (fn-9p-fields-ready-p c2)
       (fn-9p-fields-ready-p c3)
       (equal (nth 9 c3) :too-many-walk-elements))))
(defthm ninep-fields-walk-count-refused-holds (ninep-fields-walk-count-refused) :rule-classes nil)

