(in-package "ACL2")
(include-book "../../books/obligation-view-cursor-refinement")
(defconst *ovct-view* (cons 2 (fn-vdc-bump "ab" 11 (fn-vdc-bump "z" 4 nil))))
(assert-event
 (let ((start (fn-ovc-begin :arrival "ab" 7 *ovct-view*)))
  (mv-let (end used) (fn-ovc-drive start 100)
   (and (eq (fn-vcu-at 0 end) :done) (<= used (nfix 100))
        (equal (fn-ovc-result end)
               (list :done (fn-ovc-reference :arrival "ab" 7 *ovct-view*)))
        (equal (car (cadr (fn-ovc-result end))) 3)
        (equal (fn-vdc-get "ab" (cdr (cadr (fn-ovc-result end)))) '(2 . 18))
        (equal (fn-ovc-meaning (fn-ovc-step start)) (fn-ovc-meaning start))
        (equal (fn-ovc-meaning end) (fn-ovc-meaning start))))))
(assert-event
 (let ((start (fn-ovc-begin :release "ab" 11 *ovct-view*)))
  (mv-let (end used) (fn-ovc-drive start 100)
   (declare (ignore used))
   (and (eq (fn-vcu-at 0 end) :done)
        (equal (fn-ovc-result end)
               (list :done (fn-ovc-reference :release "ab" 11 *ovct-view*)))
        (equal (car (cadr (fn-ovc-result end))) 1)
        (equal (fn-vdc-get "z" (cdr (cadr (fn-ovc-result end)))) '(1 . 4))))))
; Hypothesis removal: unfinished full view has no completed result.
(assert-event
 (let ((start (fn-ovc-begin :arrival "ab" 7 *ovct-view*)))
  (mv-let (end used) (fn-ovc-drive start 1)
   (and (equal used 1) (not (eq (fn-vcu-at 0 end) :done))
        (not (equal (fn-ovc-result end)
                    (list :done (fn-ovc-reference :arrival "ab" 7 *ovct-view*))))))))
(assert-event
 (and (equal (fn-ovc-result (fn-ovc-begin :same nil 0 *ovct-view*))
             (list :done *ovct-view*))
      (equal (fn-ovc-result (fn-ovc-begin :unknown nil 0 *ovct-view*))
             '(:error :delta))))
