(in-package "ACL2")
(include-book "../../books/over-byte-full-parser-range")

(defconst *obfpt-source*
 (append (fn-record-string-octets "Subject: a") '(13 10 32 98 13 10)
         (fn-record-string-octets "From: c") '(13 10)
         (fn-record-string-octets "Date: d") '(13 10)
         (fn-record-string-octets "Message-ID: <e@x>") '(13 10)
         (fn-record-string-octets "References: <r@x>") '(13 10 13 10 122 13 10)))
(defun obfpt-token ()
 (mv-let (owners pins status) (fn-rpin-step nil '(31 nil nil) '(:acquire 7))
  (declare (ignore pins status)) (fn-rpin-token 7 owners)))
(defun obfpt-advance (s steps fn-arena fn-cat)
 (declare (xargs :stobjs (fn-arena fn-cat) :measure (nfix steps) :verify-guards nil))
 (if (zp steps) s
  (mv-let (out next) (fn-obc-one s fn-arena fn-cat)
   (declare (ignore out)) (obfpt-advance next (1- steps) fn-arena fn-cat))))
(defun-nx obfpt-conclusionp (s fn-arena fn-cat)
 (declare (xargs :stobjs (fn-arena fn-cat) :verify-guards nil))
 (let ((r (fn-obc-one s fn-arena fn-cat)))
  (equal (append (mv-nth 0 r)
                 (fn-obc-actual-old-residual (mv-nth 1 r) fn-arena fn-cat))
         (fn-obc-actual-old-residual s fn-arena fn-cat))))

; Actual ONE reachability witness.
(defthm obfpt-positive-terminal
 (let* ((source *obfpt-source*) (fn-arena (list source)) (number 1)
        (top number) (v 1)
        (wire (fn-record-make 0 1 0 "<e@x>" source '("fn.test") "o" "s" "e" 1 5))
        (fn-cat (list (fn-held-with-numbers (fn-held-plain wire 0)
                       (list (cons "fn.test" number)))))
        (range (fn-ovw-cursor "fn.test" number top v nil t))
        (s (obfpt-advance (fn-obc-begin range (obfpt-token)) (len source) fn-arena fn-cat))
        (seq (fn-cnx-view-seq "fn.test" number v fn-cat))
        (row (fn-cat-at seq fn-cat)) (h (fn-record-payload row))
        (bytes (nth (fn-obc-selected-handle s fn-cat) fn-arena)))
  (and (equal (nth 2 s) :parse)
       (fn-obc-parser-prefix-p s fn-arena fn-cat)
       (fn-cbor-octet-listp bytes)
       (posp number)
       (<= number *fn-nntp-max-article-number*)
       (<= number (nfix top))
       seq
       (fn-scat-msgid-idp (fn-record-msgid row))
       (natp h)
       (obfpt-conclusionp s fn-arena fn-cat)))
 :rule-classes nil)

; Actual ONE reachability witness.
(defthm obfpt-positive-yield
 (let* ((source *obfpt-source*) (fn-arena (list source)) (number 1)
        (top number) (v 1)
        (wire (fn-record-make 0 1 0 "<e@x>" source '("fn.test") "o" "s" "e" 1 5))
        (fn-cat (list (fn-held-with-numbers (fn-held-plain wire 0)
                       (list (cons "fn.test" number)))))
        (range (fn-ovw-cursor "fn.test" number top v nil t))
        (s (obfpt-advance (fn-obc-begin range (obfpt-token)) 1 fn-arena fn-cat))
        (seq (fn-cnx-view-seq "fn.test" number v fn-cat))
        (row (fn-cat-at seq fn-cat)) (h (fn-record-payload row))
        (bytes (nth (fn-obc-selected-handle s fn-cat) fn-arena)))
  (and (equal (nth 2 s) :parse)
       (fn-obc-parser-prefix-p s fn-arena fn-cat)
       (fn-cbor-octet-listp bytes)
       (posp number)
       (<= number *fn-nntp-max-article-number*)
       (<= number (nfix top))
       seq
       (fn-scat-msgid-idp (fn-record-msgid row))
       (natp h)
       (obfpt-conclusionp s fn-arena fn-cat)))
 :rule-classes nil)

; Corrupted-state literal removal; every retained hypothesis is asserted.
(defthm obfpt-without-phase
 (let* ((source *obfpt-source*) (fn-arena (list source)) (number 1)
        (top number) (v 1)
        (wire (fn-record-make 0 1 0 "<e@x>" source '("fn.test") "o" "s" "e" 1 5))
        (fn-cat (list (fn-held-with-numbers (fn-held-plain wire 0)
                       (list (cons "fn.test" number)))))
        (range (fn-ovw-cursor "fn.test" number top v nil t))
        (s (fn-obc-make range (obfpt-token) :bad (fn-lpc-feed (butlast source 1) (fn-lpc-begin 0 (len source) (obfpt-token))) nil 0))
        (seq (fn-cnx-view-seq "fn.test" number v fn-cat))
        (row (fn-cat-at seq fn-cat)) (h (fn-record-payload row))
        (bytes (nth (fn-obc-selected-handle s fn-cat) fn-arena)))
  (and (not (equal (nth 2 s) :parse))
       (fn-obc-parser-prefix-p s fn-arena fn-cat)
       (fn-cbor-octet-listp bytes)
       (posp number)
       (<= number *fn-nntp-max-article-number*)
       (<= number (nfix top))
       seq
       (fn-scat-msgid-idp (fn-record-msgid row))
       (natp h)
       (not (obfpt-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)

; Corrupted-state literal removal; every retained hypothesis is asserted.
(defthm obfpt-without-prefix
 (let* ((source *obfpt-source*) (fn-arena (list source)) (number 1)
        (top number) (v 1)
        (wire (fn-record-make 0 1 0 "<e@x>" source '("fn.test") "o" "s" "e" 1 5))
        (fn-cat (list (fn-held-with-numbers (fn-held-plain wire 0)
                       (list (cons "fn.test" number)))))
        (range (fn-ovw-cursor "fn.test" number top v nil t))
        (s (fn-obc-make range (obfpt-token) :parse (fn-lpc-feed (append source '(122 13 10)) (fn-lpc-begin 0 (+ 3 (len source)) (obfpt-token))) nil 0))
        (seq (fn-cnx-view-seq "fn.test" number v fn-cat))
        (row (fn-cat-at seq fn-cat)) (h (fn-record-payload row))
        (bytes (nth (fn-obc-selected-handle s fn-cat) fn-arena)))
  (and (equal (nth 2 s) :parse)
       (not (fn-obc-parser-prefix-p s fn-arena fn-cat))
       (fn-cbor-octet-listp bytes)
       (posp number)
       (<= number *fn-nntp-max-article-number*)
       (<= number (nfix top))
       seq
       (fn-scat-msgid-idp (fn-record-msgid row))
       (natp h)
       (not (obfpt-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)

; Corrupted-state literal removal; every retained hypothesis is asserted.
(defthm obfpt-without-octets
 (let* ((source (append (butlast *obfpt-source* 3) '(256 13 10))) (fn-arena (list source)) (number 1)
        (top number) (v 1)
        (wire (fn-record-make 0 1 0 "<e@x>" source '("fn.test") "o" "s" "e" 1 5))
        (fn-cat (list (fn-held-with-numbers (fn-held-plain wire 0)
                       (list (cons "fn.test" number)))))
        (range (fn-ovw-cursor "fn.test" number top v nil t))
        (s (fn-obc-make range (obfpt-token) :parse (fn-lpc-feed (butlast source 1) (fn-lpc-begin 0 (len source) (obfpt-token))) nil 0))
        (seq (fn-cnx-view-seq "fn.test" number v fn-cat))
        (row (fn-cat-at seq fn-cat)) (h (fn-record-payload row))
        (bytes (nth (fn-obc-selected-handle s fn-cat) fn-arena)))
  (and (equal (nth 2 s) :parse)
       (fn-obc-parser-prefix-p s fn-arena fn-cat)
       (not (fn-cbor-octet-listp bytes))
       (posp number)
       (<= number *fn-nntp-max-article-number*)
       (<= number (nfix top))
       seq
       (fn-scat-msgid-idp (fn-record-msgid row))
       (natp h)
       (not (obfpt-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)

; Corrupted-state literal removal; every retained hypothesis is asserted.
(defthm obfpt-without-positive-number
 (let* ((source *obfpt-source*) (fn-arena (list source)) (number 0)
        (top number) (v 1)
        (wire (fn-record-make 0 1 0 "<e@x>" source '("fn.test") "o" "s" "e" 1 5))
        (fn-cat (list (fn-held-with-numbers (fn-held-plain wire 0)
                       (list (cons "fn.test" number)))))
        (range (fn-ovw-cursor "fn.test" number top v nil t))
        (s (fn-obc-make range (obfpt-token) :parse (fn-lpc-feed (butlast source 1) (fn-lpc-begin 0 (len source) (obfpt-token))) nil 0))
        (seq (fn-cnx-view-seq "fn.test" number v fn-cat))
        (row (fn-cat-at seq fn-cat)) (h (fn-record-payload row))
        (bytes (nth (fn-obc-selected-handle s fn-cat) fn-arena)))
  (and (equal (nth 2 s) :parse)
       (fn-obc-parser-prefix-p s fn-arena fn-cat)
       (fn-cbor-octet-listp bytes)
       (not (posp number))
       (<= number *fn-nntp-max-article-number*)
       (<= number (nfix top))
       seq
       (fn-scat-msgid-idp (fn-record-msgid row))
       (natp h)
       (not (obfpt-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)

; Corrupted-state literal removal; every retained hypothesis is asserted.
(defthm obfpt-without-number-bound
 (let* ((source *obfpt-source*) (fn-arena (list source)) (number (+ 1 *fn-nntp-max-article-number*))
        (top number) (v 1)
        (wire (fn-record-make 0 1 0 "<e@x>" source '("fn.test") "o" "s" "e" 1 5))
        (fn-cat (list (fn-held-with-numbers (fn-held-plain wire 0)
                       (list (cons "fn.test" number)))))
        (range (fn-ovw-cursor "fn.test" number top v nil t))
        (s (fn-obc-make range (obfpt-token) :parse (fn-lpc-feed (butlast source 1) (fn-lpc-begin 0 (len source) (obfpt-token))) nil 0))
        (seq (fn-cnx-view-seq "fn.test" number v fn-cat))
        (row (fn-cat-at seq fn-cat)) (h (fn-record-payload row))
        (bytes (nth (fn-obc-selected-handle s fn-cat) fn-arena)))
  (and (equal (nth 2 s) :parse)
       (fn-obc-parser-prefix-p s fn-arena fn-cat)
       (fn-cbor-octet-listp bytes)
       (posp number)
       (not (<= number *fn-nntp-max-article-number*))
       (<= number (nfix top))
       seq
       (fn-scat-msgid-idp (fn-record-msgid row))
       (natp h)
       (not (obfpt-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)

; Corrupted-state literal removal; every retained hypothesis is asserted.
(defthm obfpt-without-range-bound
 (let* ((source *obfpt-source*) (fn-arena (list source)) (number 1)
        (top 0) (v 1)
        (wire (fn-record-make 0 1 0 "<e@x>" source '("fn.test") "o" "s" "e" 1 5))
        (fn-cat (list (fn-held-with-numbers (fn-held-plain wire 0)
                       (list (cons "fn.test" number)))))
        (range (fn-ovw-cursor "fn.test" number top v nil t))
        (s (fn-obc-make range (obfpt-token) :parse (fn-lpc-feed (butlast source 1) (fn-lpc-begin 0 (len source) (obfpt-token))) nil 0))
        (seq (fn-cnx-view-seq "fn.test" number v fn-cat))
        (row (fn-cat-at seq fn-cat)) (h (fn-record-payload row))
        (bytes (nth (fn-obc-selected-handle s fn-cat) fn-arena)))
  (and (equal (nth 2 s) :parse)
       (fn-obc-parser-prefix-p s fn-arena fn-cat)
       (fn-cbor-octet-listp bytes)
       (posp number)
       (<= number *fn-nntp-max-article-number*)
       (not (<= number (nfix top)))
       seq
       (fn-scat-msgid-idp (fn-record-msgid row))
       (natp h)
       (not (obfpt-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)

; Corrupted-state literal removal; every retained hypothesis is asserted.
(defthm obfpt-without-sequence
 (let* ((source *obfpt-source*) (fn-arena (list source)) (number 1)
        (top number) (v 0)
        (wire (fn-record-make 0 1 0 "<e@x>" source '("fn.test") "o" "s" "e" 1 5))
        (fn-cat (list (fn-held-with-numbers (fn-held-plain wire 0)
                       (list (cons "fn.test" number)))))
        (range (fn-ovw-cursor "fn.test" number top v nil t))
        (s (fn-obc-make range (obfpt-token) :parse (fn-lpc-feed (butlast source 1) (fn-lpc-begin 0 (len source) (obfpt-token))) nil 0))
        (seq (fn-cnx-view-seq "fn.test" number v fn-cat))
        (row (fn-cat-at seq fn-cat)) (h (fn-record-payload row))
        (bytes (nth (fn-obc-selected-handle s fn-cat) fn-arena)))
  (and (equal (nth 2 s) :parse)
       (fn-obc-parser-prefix-p s fn-arena fn-cat)
       (fn-cbor-octet-listp bytes)
       (posp number)
       (<= number *fn-nntp-max-article-number*)
       (<= number (nfix top))
       (not seq)
       (fn-scat-msgid-idp (fn-record-msgid row))
       (natp h)
       (not (obfpt-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)

; Corrupted-state literal removal; every retained hypothesis is asserted.
(defthm obfpt-without-msgid
 (let* ((source *obfpt-source*) (fn-arena (list source)) (number 1)
        (top number) (v 1)
        (wire (fn-record-make 0 1 0 "" source '("fn.test") "o" "s" "e" 1 5))
        (fn-cat (list (fn-held-with-numbers (fn-held-plain wire 0)
                       (list (cons "fn.test" number)))))
        (range (fn-ovw-cursor "fn.test" number top v nil t))
        (s (fn-obc-make range (obfpt-token) :parse (fn-lpc-feed (butlast source 1) (fn-lpc-begin 0 (len source) (obfpt-token))) nil 0))
        (seq (fn-cnx-view-seq "fn.test" number v fn-cat))
        (row (fn-cat-at seq fn-cat)) (h (fn-record-payload row))
        (bytes (nth (fn-obc-selected-handle s fn-cat) fn-arena)))
  (and (equal (nth 2 s) :parse)
       (fn-obc-parser-prefix-p s fn-arena fn-cat)
       (fn-cbor-octet-listp bytes)
       (posp number)
       (<= number *fn-nntp-max-article-number*)
       (<= number (nfix top))
       seq
       (not (fn-scat-msgid-idp (fn-record-msgid row)))
       (natp h)
       (not (obfpt-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)

; Corrupted-state literal removal; every retained hypothesis is asserted.
(defthm obfpt-without-payload-type
 (let* ((source *obfpt-source*) (fn-arena (list source)) (number 1)
        (top number) (v 1)
        (wire (fn-record-make 0 1 0 "<e@x>" source '("fn.test") "o" "s" "e" 1 5))
        (fn-cat (list (fn-held-with-numbers (fn-held-plain wire -1)
                       (list (cons "fn.test" number)))))
        (range (fn-ovw-cursor "fn.test" number top v nil t))
        (s (fn-obc-make range (obfpt-token) :parse (fn-lpc-feed (butlast source 1) (fn-lpc-begin 0 (len source) (obfpt-token))) nil 0))
        (seq (fn-cnx-view-seq "fn.test" number v fn-cat))
        (row (fn-cat-at seq fn-cat)) (h (fn-record-payload row))
        (bytes (nth (fn-obc-selected-handle s fn-cat) fn-arena)))
  (and (equal (nth 2 s) :parse)
       (fn-obc-parser-prefix-p s fn-arena fn-cat)
       (fn-cbor-octet-listp bytes)
       (posp number)
       (<= number *fn-nntp-max-article-number*)
       (<= number (nfix top))
       seq
       (fn-scat-msgid-idp (fn-record-msgid row))
       (not (natp h))
       (not (obfpt-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)

; Complete multirow execution fixture on a fixed captured catalog.  C=3
; and V=7 are deliberately distinct.  These are source-model witnesses,
; not publication/grant admission or native lifetime claims.
(defun obfpt-run (s fuel fn-arena fn-cat)
 (declare (xargs :stobjs (fn-arena fn-cat) :measure (nfix fuel) :verify-guards nil))
 (if (or (zp fuel) (not s)) (mv nil s)
  (mv-let (out next) (fn-obc-one s fn-arena fn-cat)
   (mv-let (rest final) (obfpt-run next (1- fuel) fn-arena fn-cat)
    (mv (append out rest) final)))))
(defun obfpt-held (id h number source)
 (declare (xargs :verify-guards nil))
 (fn-held-with-numbers
  (fn-held-plain (fn-record-make 0 1 0 id source '("fn.test") "o" "s" "e" 1 5) h)
  (list (cons "fn.test" number))))
(defthm obfpt-complete-multirow-with-invalid-middle
 (let* ((a *obfpt-source*) (bad '(120 13 10))
        (fn-arena (list a bad a))
        (fn-cat (list (obfpt-held "<e@x>" 0 1 a)
                      (obfpt-held "<bad@x>" 1 2 bad)
                      (obfpt-held "<e@x>" 2 4 a)))
        (range (fn-ovw-cursor "fn.test" 1 4 7 nil t))
        (answer (obfpt-run (fn-obc-begin range (obfpt-token)) 1000 fn-arena fn-cat)))
  (and (equal (fn-cat-count fn-cat) 3)
       (not (fn-cnx-view-seq "fn.test" 3 7 fn-cat))
       (equal (len (fn-ovw-lines "fn.test" 1 4 7 fn-arena fn-cat)) 2)
       (not (mv-nth 1 answer))
       (equal (mv-nth 0 answer) (fn-obc-old-range-reply range fn-arena fn-cat))))
 :rule-classes nil)
(defthm obfpt-complete-advanced-owed-state
 (let* ((a *obfpt-source*) (fn-arena (list a a))
        (fn-cat (list (obfpt-held "<e@x>" 0 1 a)
                      (obfpt-held "<e@x>" 1 4 a)))
        (range (fn-ovw-cursor "fn.test" 2 4 7 nil nil))
        (answer (obfpt-run (fn-obc-begin range (obfpt-token)) 1000 fn-arena fn-cat)))
  (and (equal (len (fn-ovw-lines "fn.test" 2 4 7 fn-arena fn-cat)) 1)
       (not (mv-nth 1 answer))
       (equal (mv-nth 0 answer) (fn-obc-old-range-reply range fn-arena fn-cat))))
 :rule-classes nil)
(defthm obfpt-complete-multirow-with-tombstone
 (let* ((a *obfpt-source*)
        (tomb (append *fn-rcl-magic* (make-list 137 :initial-element 0)))
        (fn-arena (list a tomb a))
        (fn-cat (list (obfpt-held "<e@x>" 0 1 a)
                      (obfpt-held "<gone@x>" 1 2 tomb)
                      (obfpt-held "<e@x>" 2 3 a)))
        (range (fn-ovw-cursor "fn.test" 1 3 7 nil t))
        (answer (obfpt-run (fn-obc-begin range (obfpt-token)) 1200 fn-arena fn-cat)))
  (and (fn-rcl-tombstonep tomb)
       (equal (len (fn-ovw-lines "fn.test" 1 3 7 fn-arena fn-cat)) 2)
       (not (mv-nth 1 answer))
       (equal (mv-nth 0 answer) (fn-obc-old-range-reply range fn-arena fn-cat))))
 :rule-classes nil)
