(in-package "ACL2")
(include-book "../../books/over-byte-seek-parser-range")
(defun obst-token ()
 (mv-let (owners pins status) (fn-rpin-step nil '(31 nil nil) '(:acquire 7))
  (declare (ignore pins status)) (fn-rpin-token 7 owners)))
(defun-nx obst-conclusionp (s fn-arena fn-cat)
 (declare (xargs :stobjs (fn-arena fn-cat) :verify-guards nil))
 (let ((r (fn-obc-one s fn-arena fn-cat)))
  (and (equal (nth 2 (mv-nth 1 r)) :parse)
       (fn-obc-parser-prefix-p (mv-nth 1 r) fn-arena fn-cat)
       (equal (append (mv-nth 0 r)
                      (fn-obc-actual-old-residual (mv-nth 1 r) fn-arena fn-cat))
              (fn-obc-actual-old-residual s fn-arena fn-cat)))))

; Reachable actual begin, complete antecedent and conclusion.
(defthm obst-positive
 (let* ((source '(120 13 10)) (fn-arena (list source)) (k 1)
        (top k) (v 1)
        (held (fn-held-make 0 1 0 "<e@x>" 0 '("fn.test") "o" "s" "e" 1 5
                 (fn-hf-make (len source) nil 0 nil) nil (list (cons "fn.test" k)) nil))
        (fn-cat (list held))
        (range (fn-ovw-cursor "fn.test" k top v nil t))
        (s (fn-obc-make range (obst-token) :seek nil nil 0))
        (seq (fn-cnx-view-seq "fn.test" k v fn-cat))
        (row (and seq (fn-cat-at seq fn-cat))))
  (and (equal (nth 2 s) :seek)
       (<= k (nfix top))
       (posp k)
       (<= k *fn-nntp-max-article-number*)
       (fn-scat-msgid-idp (fn-record-msgid row))
       (not (fn-nrf-facts seq fn-cat))
       (obst-conclusionp s fn-arena fn-cat)))
 :rule-classes nil)

; Corrupted-state literal removal, all retained hypotheses asserted.
(defthm obst-without-phase
 (let* ((source '(120 13 10)) (fn-arena (list source)) (k 1)
        (top k) (v 1)
        (held (fn-held-make 0 1 0 "<e@x>" 0 '("fn.test") "o" "s" "e" 1 5
                 (fn-hf-make (len source) nil 0 nil) nil (list (cons "fn.test" k)) nil))
        (fn-cat (list held))
        (range (fn-ovw-cursor "fn.test" k top v nil t))
        (s (fn-obc-make range (obst-token) :bad nil nil 0))
        (seq (fn-cnx-view-seq "fn.test" k v fn-cat))
        (row (and seq (fn-cat-at seq fn-cat))))
  (and (not (equal (nth 2 s) :seek))
       (<= k (nfix top))
       (posp k)
       (<= k *fn-nntp-max-article-number*)
       (fn-scat-msgid-idp (fn-record-msgid row))
       (not (fn-nrf-facts seq fn-cat))
       (not (obst-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)

; Corrupted-state literal removal, all retained hypotheses asserted.
(defthm obst-without-top
 (let* ((source '(120 13 10)) (fn-arena (list source)) (k 1)
        (top 0) (v 1)
        (held (fn-held-make 0 1 0 "<e@x>" 0 '("fn.test") "o" "s" "e" 1 5
                 (fn-hf-make (len source) nil 0 nil) nil (list (cons "fn.test" k)) nil))
        (fn-cat (list held))
        (range (fn-ovw-cursor "fn.test" k top v nil t))
        (s (fn-obc-make range (obst-token) :seek nil nil 0))
        (seq (fn-cnx-view-seq "fn.test" k v fn-cat))
        (row (and seq (fn-cat-at seq fn-cat))))
  (and (equal (nth 2 s) :seek)
       (not (<= k (nfix top)))
       (posp k)
       (<= k *fn-nntp-max-article-number*)
       (fn-scat-msgid-idp (fn-record-msgid row))
       (not (fn-nrf-facts seq fn-cat))
       (not (obst-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)

; Corrupted-state literal removal, all retained hypotheses asserted.
(defthm obst-without-positive
 (let* ((source '(120 13 10)) (fn-arena (list source)) (k 0)
        (top k) (v 1)
        (held (fn-held-make 0 1 0 "<e@x>" 0 '("fn.test") "o" "s" "e" 1 5
                 (fn-hf-make (len source) nil 0 nil) nil (list (cons "fn.test" k)) nil))
        (fn-cat (list held))
        (range (fn-ovw-cursor "fn.test" k top v nil t))
        (s (fn-obc-make range (obst-token) :seek nil nil 0))
        (seq (fn-cnx-view-seq "fn.test" k v fn-cat))
        (row (and seq (fn-cat-at seq fn-cat))))
  (and (equal (nth 2 s) :seek)
       (<= k (nfix top))
       (not (posp k))
       (<= k *fn-nntp-max-article-number*)
       (fn-scat-msgid-idp (fn-record-msgid row))
       (not (fn-nrf-facts seq fn-cat))
       (not (obst-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)

; Corrupted-state literal removal, all retained hypotheses asserted.
(defthm obst-without-supported-number
 (let* ((source '(120 13 10)) (fn-arena (list source)) (k (+ 1 *fn-nntp-max-article-number*))
        (top k) (v 1)
        (held (fn-held-make 0 1 0 "<e@x>" 0 '("fn.test") "o" "s" "e" 1 5
                 (fn-hf-make (len source) nil 0 nil) nil (list (cons "fn.test" k)) nil))
        (fn-cat (list held))
        (range (fn-ovw-cursor "fn.test" k top v nil t))
        (s (fn-obc-make range (obst-token) :seek nil nil 0))
        (seq (fn-cnx-view-seq "fn.test" k v fn-cat))
        (row (and seq (fn-cat-at seq fn-cat))))
  (and (equal (nth 2 s) :seek)
       (<= k (nfix top))
       (posp k)
       (not (<= k *fn-nntp-max-article-number*))
       (fn-scat-msgid-idp (fn-record-msgid row))
       (not (fn-nrf-facts seq fn-cat))
       (not (obst-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)

; Corrupted-state literal removal, all retained hypotheses asserted.
(defthm obst-without-msgid
 (let* ((source '(120 13 10)) (fn-arena (list source)) (k 1)
        (top k) (v 1)
        (held (fn-held-make 0 1 0 "" 0 '("fn.test") "o" "s" "e" 1 5
                 (fn-hf-make (len source) nil 0 nil) nil (list (cons "fn.test" k)) nil))
        (fn-cat (list held))
        (range (fn-ovw-cursor "fn.test" k top v nil t))
        (s (fn-obc-make range (obst-token) :seek nil nil 0))
        (seq (fn-cnx-view-seq "fn.test" k v fn-cat))
        (row (and seq (fn-cat-at seq fn-cat))))
  (and (equal (nth 2 s) :seek)
       (<= k (nfix top))
       (posp k)
       (<= k *fn-nntp-max-article-number*)
       (not (fn-scat-msgid-idp (fn-record-msgid row)))
       (not (fn-nrf-facts seq fn-cat))
       (not (obst-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)

; Corrupted-state literal removal, all retained hypotheses asserted.
(defthm obst-without-uncached
 (let* ((source '(120 13 10)) (fn-arena (list source)) (k 1)
        (top k) (v 1)
        (held (fn-held-make 0 1 0 "<e@x>" 0 '("fn.test") "o" "s" "e" 1 5
                 (fn-held-facts-of source) nil (list (cons "fn.test" k)) nil))
        (fn-cat (list held))
        (range (fn-ovw-cursor "fn.test" k top v nil t))
        (s (fn-obc-make range (obst-token) :seek nil nil 0))
        (seq (fn-cnx-view-seq "fn.test" k v fn-cat))
        (row (and seq (fn-cat-at seq fn-cat))))
  (and (equal (nth 2 s) :seek)
       (<= k (nfix top))
       (posp k)
       (<= k *fn-nntp-max-article-number*)
       (fn-scat-msgid-idp (fn-record-msgid row))
       (not (not (fn-nrf-facts seq fn-cat)))
       (not (obst-conclusionp s fn-arena fn-cat))))
 :rule-classes nil)
