; Reachable owner epoch and one-use boundaries. CP7 content correspondence
; belongs to its producer; this fixture tests the installer's retained metadata.
(in-package "ACL2")
(include-book "../../books/owner-replay-install")
(defun orbit-fields (xs)
 (if (consp xs) (cons (fn-scs-summary (car xs)) (orbit-fields (cdr xs))) nil))
(defun orbit-lifecycle (state)
 (declare (xargs :stobjs state :guard t :verify-guards nil))
 (let* ((state (f-put-global 'fn-owner-canonical-epoch 0 state))
        (state (f-put-global 'fn-owner-canonical-pending nil state))
        (source '(1 (2 0) 0 0))
        (cp '(:metadata-only nil nil nil nil nil nil)))
  (mv-let (start state) (fn-owner-orcb-start source 0 state)
   (let ((captured (fn-owner-orcb-pending state)))
    (mv-let (first state) (fn-owner-orcb-complete cp (orbit-fields cp) 0 0 state)
     (mv-let (again state) (fn-owner-orcb-complete cp (orbit-fields cp) 0 0 state)
      (let* ((ready (fn-owner-canonical-state state))
             (state (fn-owner-canonical-reset state))
             ; A late callback restores its old packet, not its old epoch.
             (state (f-put-global 'fn-owner-canonical-pending captured state)))
       (mv-let (stale state) (fn-owner-orcb-complete cp (orbit-fields cp) 0 0 state)
        (mv (and (eq start :ready) (fn-omk-widthp captured 3)
                 (eq first :installed) (eq again :refused)
                 (eq (fn-omk-at 0 ready) :ready)
                 (equal (fn-omk-at 2 ready) 0)
                 (equal (fn-omk-at 3 ready) (fn-stxk-initial-context 0))
                 (equal (fn-owner-canonical-epoch state) 1)
                 (equal (fn-omk-at 0 captured) 0)
                 (eq stale :refused) (not (fn-owner-canonical-state state)))
            state)))))))))
(make-event
 (mv-let (ok state) (orbit-lifecycle state)
  (if ok (mv nil '(value-triple :passed) state)
   (mv "Owner bootstrap epoch/one-use witness failed" nil state))))

; ORIGINAL context remains usable before the independent CP7/pool join.
(defun orbit-original-lifecycle (state)
 (declare (xargs :stobjs state :guard t :verify-guards nil))
 (let* ((state (f-put-global 'fn-owner-canonical-epoch 7 state))
        (state (f-put-global 'fn-owner-canonical-pending nil state))
        (state (f-put-global 'fn-owner-canonical-state nil state))
        (source '(1 (2 0) 0 0))
        (next-source '(2 (3 1) 0 0))
        (row (fn-stxk-make 0 1 1 0 '(1) '(7 8)))
        (child (fn-scs-summary row)))
  (mv-let (start state) (fn-owner-orcb-start source 0 state)
   (let ((before (fn-owner-orcb-context 0 state)))
    (mv-let (phase state) (fn-owner-orcb-append-current next-source 0 row child state)
     (let* ((after (fn-owner-orcb-context 1 state))
            (packet (fn-owner-orcb-pending state))
            (wrong-count (fn-owner-orcb-context 0 state)))
      (mv-let (refused state) (fn-owner-orcb-append-current next-source 0 row child state)
       (let* ((unchanged (equal packet (fn-owner-orcb-pending state)))
              (state (fn-owner-canonical-reset state))
              (state (f-put-global 'fn-owner-canonical-pending packet state)))
        (mv (and (eq start :ready) (eq (car before) :context)
                 (eq phase :ready) (eq (car after) :context)
                 (equal (fn-omk-at 3 after)
                        (fn-replay-identity-step (fn-stxk-initial-context 0) row))
                 (fn-scs-correspondsp (fn-omk-at 4 after) (fn-omk-at 3 after))
                 (equal (fn-omk-at 5 after) next-source)
                 (eq (car wrong-count) :unavailable)
                 (eq refused :refused) unchanged
                 (not (fn-owner-canonical-state state))
                 (eq (car (fn-owner-orcb-context 1 state)) :unavailable))
            state)))))))))
(make-event
 (mv-let (ok state) (orbit-original-lifecycle state)
  (if ok (mv nil '(value-triple :passed) state)
   (mv "Original context independent readiness/count/reset witness failed" nil state))))
