(in-package "ACL2")
(include-book "../../books/owner-canonical-state")

; Exercise actual STATE effects; these witnesses assert metadata behavior,
; not authenticated producer correspondence or a funded owner activation.
(defun fn-ocs-live-witness (state)
  (declare (xargs :stobjs state :mode :program))
  (let* ((state (fn-owner-canonical-reset state))
         (epoch (fn-owner-canonical-epoch state))
         (ctx '(:ok 9 nil nil nil :none))
         (fields (make-list 6 :initial-element '(0 0 nil)))
         (cpfields (make-list 7 :initial-element '(0 0 nil)))
         (source '(1 (2 3) 4 5))
         (state (f-put-global 'fn-owner-canonical-pending :pending state)))
    (mv-let (status state)
      (fn-owner-canonical-install epoch 2 ctx fields '(a b c d e f g)
                                  cpfields 8 1 source state)
      (let* ((installed (and (eq status :installed)
                             (fn-owner-canonical-availablep 2 state)
                             (not (fn-owner-canonical-availablep 3 state))
                             (equal (fn-owner-canonical-ready-capture state)
                                    (list :ready epoch 2 ctx fields '(a b c d e f g)
                                          cpfields 8 1 source))
                             (null (f-get-global 'fn-owner-canonical-pending state))))
             (state (fn-owner-canonical-reset state)))
        (mv-let (status state)
          (fn-owner-canonical-install epoch 2 ctx fields '(a b c d e f g)
                                      cpfields 8 1 source state)
          (mv (and installed (eq status :refused)
                   (equal (fn-owner-canonical-epoch state) (1+ epoch))
                   (equal (fn-owner-canonical-ready-capture state)
                          '(:unavailable :canonical-size))) state))))))
(make-event
 (mv-let (ok state) (fn-ocs-live-witness state)
   (value (list 'assert-event ok))))
