; Reachable owner epoch and one-use boundaries. CP7 content correspondence
; belongs to its producer; this fixture tests the installer's retained metadata.
(in-package "ACL2")
(include-book "../../books/owner-replay-install")
(defun orbit-fields (xs)
 (if (consp xs) (cons (fn-scs-summary (car xs)) (orbit-fields (cdr xs))) nil))
(defun orbit-lifecycle (state)
 (declare (xargs :stobjs state :guard t :verify-guards nil))
 (let* ((state (f-put-global 'fn-owner-canonical-epoch 0 state))
        (state (f-put-global 'fn-owner-canonical-pending nil state))
        (source '(1 (2 0) 0 0))
        (cp '(:metadata-only nil nil nil nil nil nil)))
  (mv-let (start state) (fn-owner-orcb-start source 0 state)
   (let ((captured (fn-owner-orcb-pending state)))
    (mv-let (first state) (fn-owner-orcb-complete cp (orbit-fields cp) 0 0 state)
     (mv-let (again state) (fn-owner-orcb-complete cp (orbit-fields cp) 0 0 state)
      (let* ((ready (fn-owner-canonical-state state))
             (state (fn-owner-canonical-reset state))
             ; A late callback restores its old packet, not its old epoch.
             (state (f-put-global 'fn-owner-canonical-pending captured state)))
       (mv-let (stale state) (fn-owner-orcb-complete cp (orbit-fields cp) 0 0 state)
        (mv (and (eq start :ready) (fn-omk-widthp captured 3)
                 (eq first :installed) (eq again :refused)
                 (eq (fn-omk-at 0 ready) :ready)
                 (equal (fn-omk-at 2 ready) 0)
                 (equal (fn-omk-at 3 ready) (fn-stxk-initial-context 0))
                 (equal (fn-owner-canonical-epoch state) 1)
                 (equal (fn-omk-at 0 captured) 0)
                 (eq stale :refused) (not (fn-owner-canonical-state state)))
            state)))))))))
(make-event
 (mv-let (ok state) (orbit-lifecycle state)
  (if ok (mv nil '(value-triple :passed) state)
   (mv "Owner bootstrap epoch/one-use witness failed" nil state))))
