(in-package "ACL2")
(include-book "../../books/paged-checkpoint-context-plan")
(include-book "must-fail-checked")
(include-book "std/testing/assert-bang" :dir :system)
(defun pckcp-f (configs recs) (declare (xargs :guard t) (ignore configs recs)) nil)
(defattach fn-pck-f pckcp-f)
(defun pckcp-record (i)
  (fn-record-make i (+ 1 (nfix i)) 0 "<a@x>" '(7)
                  '("fn.test") "o" "s" "e" 1 5))
(defun pckcp-witness (wrong)
  (let* ((prefix (list (pckcp-record 0))) (delta (list (pckcp-record 1)))
         (c (fn-sco-capture nil prefix))
         (full (fn-pck-st-of (fn-pck-seed) prefix))
         (thin (fn-pck-context-state (fn-pck-context full)))
         (st (if wrong (fn-ssr-state nil (fn-ssr-at 1 thin) 1 (fn-ssr-at 3 thin)) thin))
         (pw (adt-tp-seq-words *fn-pck-row-schema* (fn-pck-rows prefix)))
         (cnt (len pw)) (tail (nthcdr (* 2048 (floor cnt 2048)) pw))
         (base (fn-pck-plen prefix 0))
         (tree (fn-pck-root-tree-of-capture (fn-sco-extend c nil delta)
                                           (fn-pck-f nil (append prefix delta))
                                           (fn-pck-plen (append prefix delta) 0))))
    (list (and (equal cnt (len pw))
               (equal tail (nthcdr (* 2048 (floor (len pw) 2048)) pw))
               (true-listp delta) (equal base (fn-pck-plen prefix 0))
               (fn-pck-context-agreep st full)
               (equal c (fn-sco-capture nil prefix))
               (equal tree (fn-pck-root-tree-of-capture (fn-sco-extend c nil delta)
                                                      (fn-pck-f nil (append prefix delta))
                                                      (fn-pck-plen (append prefix delta) 0))))
          (equal (fn-pck-publish-plan-at cnt tail tree delta base st)
                 (fn-pck-publish-plan nil prefix delta))
          (equal (car (fn-pck-publish-plan-at cnt tail tree delta base st)) :commit))))
(assert-event (equal (pckcp-witness nil) '(t t t)))
(assert-event (equal (pckcp-witness t) '(nil nil t)))
(must-fail-checked (assert-event (cadr (pckcp-witness t))))
