; Both adopted slots and the wrong (adopted-slot) mutation.
(in-package "ACL2")
(include-book "../../books/pagestore-commit-slot")
(include-book "must-fail-checked")
(include-book "std/testing/assert-bang" :dir :system)
(defun pgs-slot-test-digest (x)
  (declare (xargs :guard t))
  (acl2-count x))
(defattach pgs-digest pgs-slot-test-digest)
(defun pgs-slot-test-disk (k)
  (let ((rec (pgs-make-rec 1 1 0 (pgs-digest nil))))
    (list (list (cons 1 nil))
          (cons :main (if (equal k 0) (cons rec nil) (cons nil rec))))))
(defun pgs-slot-test-witness (k)
  (let* ((disk (pgs-slot-test-disk k))
         (o (pgs-open disk :main :eager))
         (p (pgs-plan-commit disk :main :eager nil '(nil 2))))
    (and (equal (car o) :ok)
         (equal (second o) k)
         (equal (car p) :plan)
         (equal (pgs-x-commit-slot (second o)) (* 512 (third p)))
         (not (equal (pgs-x-commit-slot (second o)) (* 512 k))))))
(assert-event (pgs-slot-test-witness 0))
(assert-event (pgs-slot-test-witness 1))
(must-fail-checked
 (assert-event
  (let* ((disk (pgs-slot-test-disk 0))
         (p (pgs-plan-commit disk :main :eager nil '(nil 2))))
    (and (equal (car p) :plan)
         (equal (* 512 (second (pgs-open disk :main :eager)))
                (* 512 (third p)))))))
