; Unfunded local-storage tests only. No installer or allocation authority.
(in-package "ACL2")
(include-book "../../books/page-read-binding-revision")
(defun fn-prb-counter-publication-storage-test (fn-page-read-pool)
  (declare (xargs :stobjs fn-page-read-pool))
  (mv-let (word fn-page-read-pool)
    (fn-owner-page-read-counter-publish nil fn-page-read-pool)
    (let* ((uninstalled (and (eq word :unavailable)
                             (not (fn-prp-data fn-page-read-pool))))
           (rows '((( :incarnation 1) (64 0 1 0 0) :incarnation nil)))
           (current (fn-prl-build '(1000 1000 10 10 1000) '(64 0 1 0 0)
                                  2 rows '(0 0 0 0 0)))
           (fn-page-read-pool
            (update-fn-prp-data (list current 1 2 3 4) fn-page-read-pool))
           (next (fn-prl-build '(1000 1000 10 10 1000) '(65 0 1 0 1)
                               3 '(:foreign-binding-root) '(0 0 0 0 0))))
      (mv-let (word fn-page-read-pool)
        (fn-owner-page-read-counter-publish next fn-page-read-pool)
        (let* ((data (fn-prp-data fn-page-read-pool))
               (published (and (eq word :published)
                               (equal (fn-prl-nth 3 (fn-prl-nth 0 data)) rows)
                               (equal (fn-prl-nth 1 (fn-prl-nth 0 data)) '(65 0 1 0 1))
                               (equal (fn-prl-nth 2 (fn-prl-nth 0 data)) 3)
                               (equal (cdr data) '(1 2 3 4 0))))
               (fn-page-read-pool
                (update-fn-prp-data (list current 1 2 3 4 7) fn-page-read-pool)))
          (mv-let (word fn-page-read-pool)
            (fn-owner-page-read-counter-publish next fn-page-read-pool)
            (mv (and uninstalled published (eq word :published)
                     (equal (fn-owner-page-read-binding-revision fn-page-read-pool) 7)
                     (equal (fn-prl-nth 3 (fn-owner-page-read-ledger fn-page-read-pool)) rows))
                fn-page-read-pool)))))))

(defun fn-prb-counter-publication-storage-observer ()
  (declare (xargs :guard t))
  (with-local-stobj fn-page-read-pool
    (mv-let (ok fn-page-read-pool)
      (fn-prb-counter-publication-storage-test fn-page-read-pool)
      ok)))
(assert-event (fn-prb-counter-publication-storage-observer))
