; Metadata publication fixture only: seeded storage is not installation.
(in-package "ACL2")
(include-book "../../books/page-read-binding-revision")
(defun fn-prb-counter-fixture (fn-page-read-pool)
 (declare (xargs :stobjs fn-page-read-pool))
 (let* ((old (fn-prl-build '(100 100 100 100 100) '(1 1 1 1 1) 7 '((:actual-root)) '(2 2 2 2 0)))
        (next (fn-prl-build '(100 100 100 100 100) '(3 3 3 3 1) 8 '((:foreign-root)) '(2 2 2 2 0)))
        (fn-page-read-pool (update-fn-prp-data (list old :book :octets :fds 4096 9) fn-page-read-pool))
        (fn-page-read-pool (update-fn-prp-mode :served fn-page-read-pool))
        (fn-page-read-pool (update-fn-prp-alloc-mode :active fn-page-read-pool)))
  (mv-let (word fn-page-read-pool) (fn-owner-page-read-counter-publish next fn-page-read-pool)
   (let ((ok (and (eq word :published)
                  (equal (fn-owner-page-read-ledger fn-page-read-pool) (fn-prb-keep-current-bindings next old))
                  (equal (fn-owner-page-read-binding-revision fn-page-read-pool) 9)
                  (equal (fn-prp-data fn-page-read-pool) (list (fn-prb-keep-current-bindings next old) :book :octets :fds 4096 9))
                  (eq (fn-prp-mode fn-page-read-pool) :served)
                  (eq (fn-prp-alloc-mode fn-page-read-pool) :active))))
    (let ((fn-page-read-pool (update-fn-prp-mode :publication-fenced fn-page-read-pool)))
     (let ((before (fn-prp-data fn-page-read-pool)))
      (mv-let (refusal fn-page-read-pool) (fn-owner-page-read-counter-publish old fn-page-read-pool)
       (mv (and ok (eq refusal :counter-publication-unavailable)
                (equal before (fn-prp-data fn-page-read-pool))
                (eq (fn-prp-mode fn-page-read-pool) :publication-fenced)) fn-page-read-pool))))))))
(defun fn-prb-counter-fixture-run ()
 (with-local-stobj fn-page-read-pool
  (mv-let (ok fn-page-read-pool) (fn-prb-counter-fixture fn-page-read-pool) ok)))
(assert-event (fn-prb-counter-fixture-run))
