(in-package "ACL2")
(include-book "../../books/payload-table-runtime-domain")

(defthm pawtr-corrupted-max-octet-table-domain-positive
 (let ((e 1746) (fn-zin-tab (make-list 3494 :initial-element 255)))
  (and (natp e) (< e *fn-zin-tab-entries*)
       (fn-zin-tab-okp fn-zin-tab) (fn-cbor-octet-listp fn-zin-tab)
       (fn-cbor-octetp (fn-zin-tab-get (* 2 e) fn-zin-tab))
       (fn-cbor-octetp (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab))
       (natp (* 2 e)) (< (* 2 e) *fn-zin-tab-octets*)
       (natp (+ 1 (* 2 e))) (< (+ 1 (* 2 e)) *fn-zin-tab-octets*)
       (natp (* 256 (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab)))
       (<= (* 256 (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab)) 65280)
       (natp (fn-zin-tget e fn-zin-tab)) (< (fn-zin-tget e fn-zin-tab) 65536)
       (equal (fn-zin-tget e fn-zin-tab) 65535)))
 :rule-classes nil)

(defthm pawtr-remove-index-natural-corrupted-offset
 (let ((e -1) (fn-zin-tab '(0 0)))
  (and (not (natp e)) (< e *fn-zin-tab-entries*)
       (fn-cbor-octetp (fn-zin-tab-get (* 2 e) fn-zin-tab))
       (fn-cbor-octetp (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab))
       (not (and (natp (* 2 e)) (< (* 2 e) *fn-zin-tab-octets*)
        (natp (+ 1 (* 2 e))) (< (+ 1 (* 2 e)) *fn-zin-tab-octets*)
        (natp (* 256 (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab)))
        (<= (* 256 (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab)) 65280)
        (natp (fn-zin-tget e fn-zin-tab)) (< (fn-zin-tget e fn-zin-tab) 65536)))))
 :rule-classes nil)

(defthm pawtr-remove-index-bound-corrupted-table
 (let ((e 1747) (fn-zin-tab (make-list 3496 :initial-element 0)))
  (and (natp e) (not (< e *fn-zin-tab-entries*))
       (fn-cbor-octetp (fn-zin-tab-get (* 2 e) fn-zin-tab))
       (fn-cbor-octetp (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab))
       (not (and (natp (* 2 e)) (< (* 2 e) *fn-zin-tab-octets*)
        (natp (+ 1 (* 2 e))) (< (+ 1 (* 2 e)) *fn-zin-tab-octets*)
        (natp (* 256 (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab)))
        (<= (* 256 (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab)) 65280)
        (natp (fn-zin-tget e fn-zin-tab)) (< (fn-zin-tget e fn-zin-tab) 65536)))))
 :rule-classes nil)

(defthm pawtr-remove-low-octet-corrupted-buffer
 (let ((e 0) (fn-zin-tab '(65536 0)))
  (and (natp e) (< e *fn-zin-tab-entries*)
       (not (fn-cbor-octetp (fn-zin-tab-get (* 2 e) fn-zin-tab)))
       (fn-cbor-octetp (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab))
       (not (and (natp (* 2 e)) (< (* 2 e) *fn-zin-tab-octets*)
        (natp (+ 1 (* 2 e))) (< (+ 1 (* 2 e)) *fn-zin-tab-octets*)
        (natp (* 256 (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab)))
        (<= (* 256 (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab)) 65280)
        (natp (fn-zin-tget e fn-zin-tab)) (< (fn-zin-tget e fn-zin-tab) 65536)))))
 :rule-classes nil)

(defthm pawtr-remove-high-octet-corrupted-buffer
 (let ((e 0) (fn-zin-tab '(0 256)))
  (and (natp e) (< e *fn-zin-tab-entries*)
       (fn-cbor-octetp (fn-zin-tab-get (* 2 e) fn-zin-tab))
       (not (fn-cbor-octetp (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab)))
       (not (and (natp (* 2 e)) (< (* 2 e) *fn-zin-tab-octets*)
        (natp (+ 1 (* 2 e))) (< (+ 1 (* 2 e)) *fn-zin-tab-octets*)
        (natp (* 256 (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab)))
        (<= (* 256 (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab)) 65280)
        (natp (fn-zin-tget e fn-zin-tab)) (< (fn-zin-tget e fn-zin-tab) 65536)))))
 :rule-classes nil)


; The complete positive starts at actual reset, pulls a fixed-code header
; octet through the real input operation, then executes the actual header
; action. Its table is produced by the decoder, not an arbitrary octet list.
(defthm pawtr-actual-fixed-header-read-complete-positive
 (let* ((initial (fn-zin-reset (create-fn-zin-st)))
        (st (fn-zin-pull 0 initial '(3)))
        (win (make-list 65536 :initial-element 0))
        (tab (make-list 3494 :initial-element 0))
        (r (fn-zin-act st win tab nil))
        (fn-zin-tab (mv-nth 3 r)) (e 1746))
  (and (fn-zin-window-ready-p win) (fn-zin-tab-okp tab)
       (equal (mv-nth 0 r) nil) (equal (fn-zin-mode (mv-nth 1 r)) 8)
       (natp e) (< e *fn-zin-tab-entries*)
       (fn-zin-tab-okp fn-zin-tab) (fn-cbor-octet-listp fn-zin-tab)
       (fn-cbor-octetp (fn-zin-tab-get (* 2 e) fn-zin-tab))
       (fn-cbor-octetp (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab))
       (natp (* 2 e)) (< (* 2 e) *fn-zin-tab-octets*)
       (natp (+ 1 (* 2 e))) (< (+ 1 (* 2 e)) *fn-zin-tab-octets*)
       (natp (* 256 (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab)))
       (<= (* 256 (fn-zin-tab-get (+ 1 (* 2 e)) fn-zin-tab)) 65280)
       (natp (fn-zin-tget e fn-zin-tab)) (< (fn-zin-tget e fn-zin-tab) 65536)
       (equal (fn-zin-tget e fn-zin-tab) 2591)))
 :rule-classes nil)
