(in-package "ACL2")
(include-book "../../books/payload-view-lease")
(defconst *pvl-seed* (fn-pvl-seed))
(defconst *pvl-acquired* (fn-pvl-acquire *pvl-seed* 8 0 '(:maintenance 2 3 4)))
(defconst *pvl-token* (fn-omk-at 1 *pvl-acquired*))
(defconst *pvl-live* (fn-omk-at 2 *pvl-acquired*))
(assert-event (and (equal (car *pvl-acquired*) :acquired)
                   (fn-pvl-ledgerp *pvl-live*) (fn-pvl-livep *pvl-token* *pvl-live*)
                   (equal *pvl-token* '(:payload-view 0 8 0))))
(assert-event (and (fn-omk-at 2 *pvl-live*)
                   (equal (car (fn-pvl-reset *pvl-live*)) :refused)
                   (equal (fn-omk-at 2 (fn-pvl-reset *pvl-live*)) *pvl-live*)))
(assert-event (and (fn-pvl-livep *pvl-token* *pvl-live*)
                   (not (eq :cancel :joined))
                   (equal (car (fn-pvl-release *pvl-live* *pvl-token* :cancel)) :retained)
                   (equal (fn-omk-at 2 (fn-pvl-release *pvl-live* *pvl-token* :cancel)) *pvl-live*)))
; Literal joined-observation removal: live token retained, no release.
(assert-event (and (fn-pvl-livep *pvl-token* *pvl-live*)
                   (not (eq :uncertain :joined))
                   (not (equal (car (fn-pvl-release *pvl-live* *pvl-token* :uncertain)) :released))))
; Literal live-token removal: definite cleanup retained, stale token refused.
(assert-event (and (not (fn-pvl-livep '(:payload-view 0 8 1) *pvl-live*))
                   (eq :joined :joined)
                   (not (equal (car (fn-pvl-release *pvl-live* '(:payload-view 0 8 1) :joined)) :released))))
(defconst *pvl-released* (fn-pvl-release *pvl-live* *pvl-token* :joined))
(defconst *pvl-quiet* (fn-omk-at 2 *pvl-released*))
(assert-event (and (fn-pvl-livep *pvl-token* *pvl-live*) (eq :joined :joined)
                   (equal (car *pvl-released*) :released)
                   (not (fn-pvl-livep *pvl-token* *pvl-quiet*))))
(assert-event (equal (car (fn-pvl-release *pvl-quiet* *pvl-token* :joined)) :refused))
(assert-event (and (equal (car (fn-pvl-acquire *pvl-quiet* 8 0 '(:maintenance 2 3 4))) :refused)
                   (equal (fn-omk-at 2 (fn-pvl-acquire *pvl-quiet* 8 0 '(:maintenance 2 3 4))) *pvl-quiet*)))
(defconst *pvl-reset* (fn-pvl-reset *pvl-quiet*))
(assert-event (and (equal (car *pvl-reset*) :reset)
                   (fn-pvl-ledgerp (fn-omk-at 2 *pvl-reset*))
                   (equal (fn-omk-at 0 (fn-omk-at 2 *pvl-reset*)) 1)
                   (equal (fn-omk-at 1 (fn-omk-at 2 *pvl-reset*)) 0)
                   (not (fn-omk-at 2 (fn-omk-at 2 *pvl-reset*)))))
(assert-event (let* ((a (fn-pvl-acquire (fn-omk-at 2 *pvl-reset*) 2 1 '(:maintenance 3 4 0)))
                     (next (fn-omk-at 2 a)))
                (and (equal (car a) :acquired)
                     (fn-pvl-livep (fn-omk-at 1 a) next)
                     (not (fn-pvl-livep *pvl-token* next)))))
(assert-event (and (equal (car (fn-pvl-acquire *pvl-seed* 8 0 nil)) :refused)
                   (equal (fn-omk-at 2 (fn-pvl-acquire *pvl-seed* 8 0 nil)) *pvl-seed*)))

; State-free phase exclusion and literal start-hypothesis removal.
(assert-event
 (and (equal (fn-pvl-runtime-step :quiescent :reset nil nil) '(:allowed :quiescent))
      (equal (fn-pvl-runtime-step :serving :reset nil nil) '(:refused :serving))
      (equal (fn-pvl-runtime-step :draining :reset nil nil) '(:refused :draining))))
(assert-event
 (let* ((phase :quiescent) (owned nil) (joined nil)
        (start (fn-pvl-runtime-step phase :start owned joined)))
   (and (equal (car start) :allowed)
        (equal (fn-pvl-runtime-step (cadr start) :reset nil nil) '(:refused :serving)))))
(assert-event
 (let* ((phase :quiescent) (owned t) (joined nil)
        (start (fn-pvl-runtime-step phase :start owned joined)))
   (and (not (equal (car start) :allowed))
        (not (equal (fn-pvl-runtime-step (cadr start) :reset nil nil) '(:refused :serving))))))
(assert-event
 (and (equal (fn-pvl-runtime-step :draining :joined t t) '(:refused :draining))
      (equal (fn-pvl-runtime-step :draining :joined nil nil) '(:refused :draining))
      (equal (fn-pvl-runtime-step :draining :joined nil t) '(:allowed :quiescent))))
