; Witnesses and teeth for books/payload-lz (the LZ payload decoder and the
; seal check; lane codec-c1).
;
; The real witness is a held-out 1993 Usenet article from the registered
; corpus (/tank/fn/scratch/fixtures/usenet-20news-19997) and the blocks
; liblz4-HC 9 wrote for it, without and with a dictionary; the constants
; are generated by planning/evidence/codec-c1-2026-09-27/witness.py.
(in-package "ACL2")
(include-book "../../books/payload-lz")
(include-book "std/testing/must-fail" :dir :system)

; generated by planning/evidence/codec-c1-2026-09-27/witness.py; group alt.atheism, held-out index 11
; article sha256 47eb37f113361d16ebae11ca5e29c8cc3bbfd6b2ff86a35f527af1a9f2be2cba
; the article: 750 octets (CRLF wire form)
(defconst *plz-article*
  '(80 97 116 104 58 32 99 97 110 116 97 108 111 117 112 101 46 115 114 118 46
    99 115 46 99 109 117 46 101 100 117 33 100 97 115 45 110 101 119 115 46 104
    97 114 118 97 114 100 46 101 100 117 33 104 117 115 99 45 110 101 119 115 46
    104 97 114 118 97 114 100 46 101 100 117 33 107 117 104 117 98 46 99 99 46
    117 107 97 110 115 46 101 100 117 33 119 117 112 111 115 116 33 101 109 111
    114 121 33 115 111 108 46 99 116 114 46 99 111 108 117 109 98 105 97 46 101
    100 117 33 117 114 115 97 33 112 111 111 104 33 104 97 108 97 116 13 10 78
    101 119 115 103 114 111 117 112 115 58 32 97 108 116 46 97 116 104 101 105
    115 109 13 10 83 117 98 106 101 99 116 58 32 82 101 58 32 65 109 101 114 105
    99 97 110 115 32 97 110 100 32 69 118 111 108 117 116 105 111 110 13 10 77
    101 115 115 97 103 101 45 73 68 58 32 60 51 48 48 54 57 64 117 114 115 97 46
    98 101 97 114 46 99 111 109 62 13 10 70 114 111 109 58 32 104 97 108 97 116
    64 112 111 111 104 46 98 101 97 114 115 32 40 74 105 109 32 72 97 108 97 116
    41 13 10 68 97 116 101 58 32 49 32 65 112 114 32 57 51 32 50 50 58 53 48 58
    49 49 32 71 77 84 13 10 82 101 112 108 121 45 84 111 58 32 104 97 108 97 116
    64 112 111 111 104 46 98 101 97 114 115 32 40 74 105 109 32 72 97 108 97 116
    41 13 10 83 101 110 100 101 114 58 32 110 101 119 115 64 98 101 97 114 46 99
    111 109 13 10 82 101 102 101 114 101 110 99 101 115 58 32 60 57 51 48 56 57
    46 49 52 51 48 52 56 73 79 51 48 52 51 54 64 77 65 73 78 69 46 77 65 73 78
    69 46 69 68 85 62 32 60 106 48 61 53 108 51 61 64 114 112 105 46 101 100 117
    62 13 10 76 105 110 101 115 58 32 49 48 13 10 13 10 73 110 32 97 114 116 105
    99 108 101 32 60 106 48 61 53 108 51 61 64 114 112 105 46 101 100 117 62 44
    32 106 111 104 110 115 100 50 64 106 101 99 51 50 50 46 105 116 115 46 114
    112 105 46 101 100 117 32 40 68 97 110 32 74 111 104 110 115 111 110 41 32
    119 114 105 116 101 115 58 13 10 62 73 110 32 97 114 116 105 99 108 101 32
    49 52 51 48 52 56 73 79 51 48 52 51 54 64 77 65 73 78 69 46 77 65 73 78 69
    46 69 68 85 44 32 60 73 79 51 48 52 51 54 64 77 65 73 78 69 46 77 65 73 78
    69 46 69 68 85 62 32 40 41 32 119 114 105 116 101 115 58 13 10 13 10 68 97
    110 32 74 111 104 110 115 111 110 45 13 10 13 10 89 111 117 32 100 111 110
    39 116 32 107 110 111 119 32 109 101 44 32 98 117 116 32 116 97 107 101 32
    116 104 105 115 32 104 97 110 100 32 97 110 121 119 97 121 46 32 32 66 114
    97 118 111 32 102 111 114 32 71 79 40 68 83 41 32 61 32 48 46 32 13 10 66
    101 97 117 116 105 102 117 108 33 32 32 83 105 109 112 108 121 32 98 101 97
    117 116 105 102 117 108 33 13 10 13 10 45 106 105 109 32 104 97 108 97 116
    13 10 13 10))

; its liblz4-HC 9 block, no dictionary: 593 octets
(defconst *plz-block*
  '(241 33 80 97 116 104 58 32 99 97 110 116 97 108 111 117 112 101 46 115 114
    118 46 99 115 46 99 109 117 46 101 100 117 33 100 97 115 45 110 101 119 115
    46 104 97 114 118 97 114 100 21 0 78 104 117 115 99 22 0 225 107 117 104 117
    98 46 99 99 46 117 107 97 110 115 19 0 241 14 119 117 112 111 115 116 33 101
    109 111 114 121 33 115 111 108 46 99 116 114 46 99 111 108 117 109 98 105 97
    34 0 240 84 117 114 115 97 33 112 111 111 104 33 104 97 108 97 116 13 10 78
    101 119 115 103 114 111 117 112 115 58 32 97 108 116 46 97 116 104 101 105
    115 109 13 10 83 117 98 106 101 99 116 58 32 82 101 58 32 65 109 101 114 105
    99 97 110 115 32 97 110 100 32 69 118 111 108 117 116 105 111 110 13 10 77
    101 115 115 97 103 101 45 73 68 58 32 60 51 48 48 54 57 64 99 0 64 46 98 101
    97 122 0 161 109 62 13 10 70 114 111 109 58 32 111 0 16 64 122 0 1 28 0 128
    115 32 40 74 105 109 32 72 22 0 255 25 41 13 10 68 97 116 101 58 32 49 32 65
    112 114 32 57 51 32 50 50 58 53 48 58 49 49 32 71 77 84 13 10 82 101 112 108
    121 45 84 111 69 0 13 128 83 101 110 100 101 114 58 32 42 1 20 64 129 0 0 63
    0 242 22 102 101 114 101 110 99 101 115 58 32 60 57 51 48 56 57 46 49 52 51
    48 52 56 73 79 51 48 52 51 54 64 77 65 73 78 69 46 6 0 240 2 69 68 85 62 32
    60 106 48 61 53 108 51 61 64 114 112 105 54 1 96 62 13 10 76 105 110 64 0
    254 1 49 48 13 10 13 10 73 110 32 97 114 116 105 99 108 101 43 0 243 6 44 32
    106 111 104 110 115 100 50 64 106 101 99 51 50 50 46 105 116 115 46 29 0 112
    32 40 68 97 110 32 74 32 0 231 111 110 41 32 119 114 105 116 101 115 58 13
    10 62 81 0 15 155 0 10 63 44 32 60 181 0 6 23 40 81 0 39 13 10 105 0 16 45
    16 0 240 19 89 111 117 32 100 111 110 39 116 32 107 110 111 119 32 109 101
    44 32 98 117 116 32 116 97 107 101 32 116 104 105 115 32 104 217 1 245 38 97
    110 121 119 97 121 46 32 32 66 114 97 118 111 32 102 111 114 32 71 79 40 68
    83 41 32 61 32 48 46 32 13 10 66 101 97 117 116 105 102 117 108 33 32 32 83
    105 109 112 108 121 32 98 19 0 0 104 0 224 45 106 105 109 32 104 97 108 97
    116 13 10 13 10))

; the dictionary: the previous held-out article of the group, 2749 octets
(defconst *plz-dict*
  '(80 97 116 104 58 32 99 97 110 116 97 108 111 117 112 101 46 115 114 118 46
    99 115 46 99 109 117 46 101 100 117 33 100 97 115 45 110 101 119 115 46 104
    97 114 118 97 114 100 46 101 100 117 33 104 117 115 99 45 110 101 119 115 46
    104 97 114 118 97 114 100 46 101 100 117 33 104 115 100 110 100 101 118 33
    119 117 112 111 115 116 33 122 97 112 104 111 100 46 109 112 115 46 111 104
    105 111 45 115 116 97 116 101 46 101 100 117 33 112 105 116 116 46 101 100
    117 33 112 111 103 111 46 105 115 112 46 112 105 116 116 46 101 100 117 33
    106 111 115 108 105 110 13 10 78 101 119 115 103 114 111 117 112 115 58 32
    116 97 108 107 46 114 101 108 105 103 105 111 110 46 109 105 115 99 44 97
    108 116 46 97 116 104 101 105 115 109 13 10 83 117 98 106 101 99 116 58 32
    82 101 58 32 42 42 42 32 84 104 101 32 108 105 115 116 32 111 102 32 66 105
    98 108 105 99 97 108 32 99 111 110 116 114 97 100 105 99 116 105 111 110 115
    13 10 77 101 115 115 97 103 101 45 73 68 58 32 60 55 57 49 50 64 98 108 117
    101 46 99 105 115 46 112 105 116 116 46 101 100 117 62 13 10 70 114 111 109
    58 32 106 111 115 108 105 110 64 112 111 103 111 46 105 115 112 46 112 105
    116 116 46 101 100 117 32 40 68 97 118 105 100 32 74 111 115 108 105 110 41
    13 10 68 97 116 101 58 32 53 32 65 112 114 32 57 51 32 50 48 58 52 49 58 48
    56 32 71 77 84 13 10 83 101 110 100 101 114 58 32 110 101 119 115 43 64 112
    105 116 116 46 101 100 117 13 10 70 111 108 108 111 119 117 112 45 84 111 58
    32 116 97 108 107 46 114 101 108 105 103 105 111 110 46 109 105 115 99 13 10
    82 101 102 101 114 101 110 99 101 115 58 32 60 98 115 107 101 110 100 105
    103 67 53 48 116 110 117 46 73 110 111 64 110 101 116 99 111 109 46 99 111
    109 62 13 10 79 114 103 97 110 105 122 97 116 105 111 110 58 32 73 110 116
    101 108 108 105 103 101 110 116 32 83 121 115 116 101 109 115 32 80 114 111
    103 114 97 109 13 10 76 105 110 101 115 58 32 52 52 13 10 13 10 83 111 109
    101 111 110 101 32 119 114 105 116 101 115 58 13 10 62 73 32 102 111 117 110
    100 32 97 32 108 105 115 116 32 111 102 32 66 105 98 108 105 99 97 108 32 99
    111 110 116 114 97 100 105 99 116 105 111 110 115 32 97 110 100 32 99 108
    101 97 110 101 100 32 105 116 32 117 112 32 97 32 98 105 116 44 32 98 117
    116 13 10 62 110 111 119 32 73 39 100 32 108 105 107 101 32 115 111 109 101
    32 104 101 108 112 32 119 105 116 104 32 105 116 46 32 32 13 10 13 10 73 39
    109 32 99 117 114 105 111 117 115 32 116 111 32 107 110 111 119 32 119 104
    97 116 32 112 117 114 112 111 115 101 32 112 101 111 112 108 101 32 116 104
    105 110 107 32 116 104 101 115 101 32 108 105 115 116 115 32 115 101 114 118
    101 46 13 10 76 105 115 116 115 32 108 105 107 101 32 116 104 105 115 32 115
    101 101 109 32 116 111 32 118 97 108 117 101 32 113 117 97 110 116 105 116
    121 32 111 118 101 114 32 113 117 97 108 105 116 121 44 32 97 110 32 34 97
    114 103 117 109 101 110 116 13 10 102 114 111 109 32 97 114 116 105 99 108
    101 32 108 101 110 103 116 104 46 34 32 32 65 110 100 32 116 104 101 32 108
    105 115 116 32 121 111 117 32 104 97 118 101 32 104 101 114 101 32 105 115
    32 111 102 32 112 111 111 114 101 114 13 10 113 117 97 108 105 116 121 32
    116 104 97 110 32 109 111 115 116 46 32 32 83 105 110 99 101 32 116 104 101
    32 113 117 111 116 101 115 32 115 101 101 109 32 116 111 32 98 101 32 116 97
    107 101 110 32 102 114 111 109 32 97 110 13 10 111 110 45 108 105 110 101 32
    98 105 98 108 101 44 32 73 32 100 111 117 98 116 32 116 104 97 116 32 116
    104 101 114 101 32 119 105 108 108 32 98 101 32 109 117 99 104 32 112 114
    111 98 108 101 109 32 119 105 116 104 13 10 118 101 114 115 101 115 32 113
    117 111 116 101 100 32 105 110 97 99 99 117 114 97 116 101 108 121 46 32 32
    66 117 116 32 116 104 97 116 32 105 115 110 39 116 32 116 104 101 32 112 114
    111 98 108 101 109 32 104 101 114 101 46 13 10 13 10 73 39 118 101 32 107
    110 111 119 110 32 97 32 108 111 116 32 111 102 32 102 117 110 100 97 109
    101 110 116 97 108 105 115 116 115 32 105 110 32 109 121 32 108 105 102 101
    44 32 98 117 116 32 110 111 110 101 32 119 104 111 13 10 100 101 110 105 101
    100 32 116 104 97 116 32 116 104 101 114 101 32 119 101 114 101 32 101 114
    114 111 114 115 32 105 110 32 116 114 97 110 115 109 105 115 115 105 111 110
    44 32 101 116 99 46 32 32 65 110 100 32 109 97 110 121 32 111 102 13 10 116
    104 101 32 99 111 110 116 114 97 100 105 99 116 105 111 110 115 32 104 101
    114 101 32 45 45 32 83 111 108 111 109 111 110 32 104 97 118 105 110 103 32
    52 48 44 48 48 48 32 104 111 114 115 101 32 115 116 97 108 108 115 32 105
    110 13 10 111 110 101 32 118 101 114 115 101 44 32 97 110 100 32 52 44 48 48
    48 32 105 110 32 97 110 111 116 104 101 114 32 45 45 32 97 114 101 32 106
    117 115 116 32 116 104 101 32 115 111 114 116 32 111 102 13 10 99 111 110
    116 114 97 100 105 99 116 105 111 110 32 116 104 97 116 32 102 117 110 100
    105 101 115 32 100 111 110 39 116 32 104 97 118 101 32 97 32 112 114 111 98
    108 101 109 32 119 105 116 104 44 32 105 110 32 109 121 13 10 101 120 112
    101 114 105 101 110 99 101 46 32 32 83 111 32 104 111 119 32 100 111 32 116
    104 101 115 101 32 115 111 114 116 115 32 111 102 32 99 111 110 116 114 97
    100 105 99 116 105 111 110 115 32 97 109 111 117 110 116 32 116 111 13 10 97
    110 121 116 104 105 110 103 32 109 111 114 101 32 116 104 97 110 32 97 116
    116 97 99 107 105 110 103 32 97 32 115 116 114 97 119 32 109 97 110 63 13 10
    13 10 83 111 109 101 32 111 102 32 116 104 101 32 111 116 104 101 114 115 32
    97 114 101 32 106 117 115 116 32 115 105 108 108 121 44 32 111 114 32 114
    101 108 121 32 111 110 32 116 97 107 105 110 103 32 113 117 111 116 101 115
    32 111 117 116 13 10 111 102 32 99 111 110 116 101 120 116 44 32 111 114 32
    104 97 118 101 32 114 101 97 115 111 110 97 98 108 101 32 101 120 112 108 97
    110 97 116 105 111 110 115 46 32 32 66 117 116 32 101 118 101 110 32 116 104
    101 32 111 110 101 115 13 10 116 104 97 116 32 97 114 101 32 103 101 110 117
    105 110 101 32 99 111 110 116 114 97 100 105 99 116 105 111 110 115 32 110
    101 101 100 32 116 111 32 104 97 118 101 32 109 111 114 101 32 115 97 105
    100 32 97 98 111 117 116 13 10 116 104 101 109 32 116 104 97 110 32 119 104
    97 116 32 105 115 32 103 105 118 101 110 32 104 101 114 101 46 32 32 40 65
    116 32 116 104 101 32 118 101 114 121 32 108 101 97 115 116 44 32 115 111
    109 101 32 101 102 102 111 114 116 13 10 115 104 111 117 108 100 32 98 101
    32 109 97 100 101 32 116 111 32 117 110 100 101 114 115 116 97 110 100 32 97
    110 100 32 114 101 115 112 111 110 100 32 116 111 32 116 104 101 32 99 111
    109 109 111 110 32 114 101 112 108 105 101 115 13 10 103 105 118 101 110 32
    98 121 32 102 117 110 100 105 101 115 46 41 32 32 76 111 111 107 32 102 111
    114 32 101 120 97 109 112 108 101 32 97 116 32 116 104 101 32 114 101 115
    101 97 114 99 104 32 116 104 97 116 32 68 97 118 101 13 10 66 117 116 108
    101 114 32 112 117 116 32 105 110 116 111 32 97 110 32 97 114 116 105 99 108
    101 32 101 120 97 109 105 110 105 110 103 32 97 32 102 97 108 115 101 32 112
    114 111 112 104 101 99 121 32 97 98 111 117 116 32 84 121 114 101 46 13 10
    84 104 97 116 32 119 111 117 108 100 32 98 101 32 97 110 32 101 120 99 101
    108 108 101 110 116 32 115 116 97 114 116 32 102 111 114 32 97 110 32 97 110
    116 105 45 105 110 101 114 114 97 110 99 121 32 108 105 115 116 32 116 104
    97 116 13 10 119 111 117 108 100 32 104 97 118 101 32 115 111 109 101 32 116
    101 101 116 104 46 32 32 40 79 110 101 32 119 101 108 108 45 114 101 115 101
    97 114 99 104 101 100 32 97 110 100 32 100 111 99 117 109 101 110 116 101
    100 13 10 99 111 110 116 114 97 100 105 99 116 105 111 110 32 105 115 32 119
    111 114 116 104 32 109 111 114 101 32 116 104 97 110 32 111 110 101 32 104
    117 110 100 114 101 100 32 113 117 111 116 101 115 32 116 97 107 101 110 32
    111 117 116 13 10 111 102 32 99 111 110 116 101 120 116 32 97 110 100 32 116
    104 114 111 119 110 32 116 111 103 101 116 104 101 114 32 105 110 32 97 32
    108 105 115 116 46 41 13 10 13 10 76 105 115 116 115 32 108 105 107 101 32
    116 104 105 115 32 116 104 97 116 32 106 117 115 116 32 116 111 115 115 32
    97 32 98 117 110 99 104 32 111 102 32 113 117 111 116 101 115 32 116 111 103
    101 116 104 101 114 32 116 111 13 10 109 97 107 101 32 97 32 98 105 98 108
    101 32 118 101 114 115 101 32 115 97 108 97 100 32 106 117 115 116 32 100
    111 110 39 116 32 99 117 116 32 105 116 46 32 32 84 104 111 115 101 32 111
    102 32 117 115 32 119 104 111 13 10 119 97 110 116 32 116 111 32 97 114 103
    117 101 32 97 103 97 105 110 115 116 32 105 110 101 114 114 97 110 99 121 32
    115 104 111 117 108 100 32 102 105 110 100 32 116 104 105 115 32 115 111 114
    116 32 111 102 32 116 104 105 110 103 13 10 97 115 32 101 109 98 97 114 97
    115 115 105 110 103 32 97 115 32 116 104 101 32 102 117 110 100 105 101 115
    32 115 104 111 117 108 100 32 102 105 110 100 32 74 111 115 104 32 77 99 68
    111 119 101 108 108 46 13 10 13 10 100 106 13 10 13 10 80 46 83 46 32 89 111
    117 32 99 97 110 32 102 105 110 100 32 115 111 109 101 32 103 111 111 100 32
    109 97 116 101 114 105 97 108 32 97 116 32 102 116 112 46 114 117 116 103
    101 114 115 46 101 100 117 32 105 110 13 10 47 112 117 98 47 115 111 99 46
    114 101 108 105 103 105 111 110 46 99 104 114 105 115 116 105 97 110 47 111
    116 104 101 114 115 47 99 111 110 116 114 97 100 105 99 116 105 111 110 115
    46 32 32 84 104 101 32 113 117 97 108 105 116 121 13 10 105 115 32 118 101
    114 121 32 117 110 101 118 101 110 32 111 110 32 98 111 116 104 32 115 105
    100 101 115 32 111 102 32 116 104 101 32 97 114 103 117 109 101 110 116 32
    40 105 116 32 105 115 32 106 117 115 116 32 97 13 10 99 111 109 112 105 108
    97 116 105 111 110 32 111 102 32 116 104 105 110 103 115 32 109 97 110 121
    32 112 101 111 112 108 101 32 104 97 118 101 32 119 114 105 116 116 101 110
    41 44 32 98 117 116 32 115 111 109 101 32 111 102 13 10 105 116 32 119 111
    117 108 100 32 98 101 32 117 115 101 102 117 108 32 105 110 32 97 110 32 97
    110 116 105 45 105 110 101 114 114 97 110 99 121 32 70 65 81 46 32 32 65 102
    116 101 114 32 101 120 97 109 115 44 32 73 13 10 109 105 103 104 116 32 98
    101 32 119 105 108 108 105 110 103 32 116 111 32 104 101 108 112 32 112 117
    116 32 105 116 32 116 111 103 101 116 104 101 114 46 13 10))

; the article's liblz4-HC 9 block against that dictionary: 395 octets
(defconst *plz-dict-block*
  '(15 189 10 56 209 107 117 104 117 98 46 99 99 46 117 107 97 110 134 1 4 200
    10 241 7 101 109 111 114 121 33 115 111 108 46 99 116 114 46 99 111 108 117
    109 98 105 97 34 0 250 0 117 114 115 97 33 112 111 111 104 33 104 97 108 97
    116 183 10 15 164 10 7 115 65 109 101 114 105 99 97 57 9 80 69 118 111 108
    117 106 1 11 148 10 96 51 48 48 54 57 64 99 0 83 46 98 101 97 114 223 9 2
    145 10 1 111 0 16 64 122 0 1 28 0 128 115 32 40 74 105 109 32 72 22 0 5 134
    10 21 49 134 10 114 50 58 53 48 58 49 49 134 10 81 82 101 112 108 121 107 10
    15 69 0 11 8 174 10 20 64 129 0 11 140 10 242 11 57 51 48 56 57 46 49 52 51
    48 52 56 73 79 51 48 52 51 54 64 77 65 73 78 69 46 6 0 243 2 69 68 85 62 32
    60 106 48 61 53 108 51 61 64 114 112 105 86 11 3 121 10 33 49 48 119 8 6 66
    5 13 43 0 243 6 44 32 106 111 104 110 115 100 50 64 106 101 99 51 50 50 46
    105 116 115 46 29 0 0 125 11 48 110 32 74 32 0 56 111 110 41 184 10 6 81 0
    15 155 0 10 63 44 32 60 181 0 6 23 40 81 0 39 13 10 105 0 16 45 16 0 0 211 3
    2 126 4 1 167 10 19 109 13 9 36 116 97 231 4 18 104 142 6 49 121 119 97 125
    9 65 114 97 118 111 214 5 240 9 71 79 40 68 83 41 32 61 32 48 46 32 13 10 66
    101 97 117 116 105 102 117 108 33 38 10 101 109 112 108 121 32 98 19 0 0 104
    0 224 45 106 105 109 32 104 97 108 97 116 13 10 13 10))


; -----------------------------------------------------------------------------
; KEYSTONE fn-lz-seal-form-denotes (no hypothesis): the reachable :lz
; witness.  The liblz4-HC block of the real article seals as :lz, and the
; form denotes exactly the article; so does the block written against the
; dictionary, whose offsets reach back into the dictionary (it is 198
; octets shorter than the block without one).

(assert-event
 (let ((form (fn-lz-seal-form nil *plz-article* *plz-block*)))
   (and (fn-cbor-octet-listp *plz-article*) (fn-cbor-octet-listp *plz-block*)
        (equal (len *plz-article*) 750)
        (equal form (list :lz 750 *plz-block*))
        (equal (fn-lz-denote nil form) *plz-article*))))

(assert-event
 (let ((form (fn-lz-seal-form *plz-dict* *plz-article* *plz-dict-block*)))
   (and (equal form (list :lz 750 *plz-dict-block*))
        (equal (fn-lz-denote *plz-dict* form) *plz-article*)
        (< (len *plz-dict-block*) (len *plz-block*))
        ; the dictionary is needed: without it the same block is refused
        (equal (car (fn-lz-decode nil *plz-dict-block* 750)) :error))))

; The :raw arm: a corrupted candidate (one offset octet changed) seals as
; :raw, and the form still denotes exactly the article.
(defun plz-corrupt (xs i v)
  (declare (xargs :guard (and (true-listp xs) (natp i))))
  (update-nth i v xs))

(assert-event
 (let* ((bad (plz-corrupt *plz-block* 100 (logxor 1 (nth 100 *plz-block*))))
        (form (fn-lz-seal-form nil *plz-article* bad)))
   (and (not (equal bad *plz-block*))
        (equal form (list :raw *plz-article*))
        (equal (fn-lz-denote nil form) *plz-article*))))

; A candidate that decodes, to other octets, also seals as :raw.
(assert-event
 (let ((form (fn-lz-seal-form nil *plz-article* (fn-lz-literal-block '(1 2 3)))))
   (and (equal (fn-lz-decode nil (fn-lz-literal-block '(1 2 3)) 750) '(:error :short))
        (equal form (list :raw *plz-article*))
        (equal (fn-lz-denote nil form) *plz-article*))))

; -----------------------------------------------------------------------------
; fn-lz-decode-of-literal-block and fn-lz-seal-form-of-literal-block
; (hypothesis: (fn-cbor-octet-listp x)).  Witnesses: five octets (a token
; alone) and 300 (a token, the extension octets 255 and 30, the literals).

(assert-event
 (let ((x '(72 101 108 108 111)))
   (and (fn-cbor-octet-listp x)
        (equal (fn-lz-literal-block x) (cons 80 x))
        (equal (fn-lz-decode nil (fn-lz-literal-block x) (len x)) (list :ok x))
        (equal (fn-lz-seal-form *plz-dict* x (fn-lz-literal-block x))
               (list :lz 5 (fn-lz-literal-block x))))))

(assert-event
 (let ((x (make-list 300 :initial-element 13)))
   (and (fn-cbor-octet-listp x)
        (equal (take 3 (fn-lz-literal-block x)) '(240 255 30))
        (equal (fn-lz-decode nil (fn-lz-literal-block x) (len x)) (list :ok x))
        (equal (fn-lz-seal-form nil x (fn-lz-literal-block x))
               (list :lz 300 (fn-lz-literal-block x))))))

; Hypothesis removal: X = (1 2 . 3) is not an octet list, and neither
; conclusion holds of it (the decode answers the true list (1 2)).  A
; theorem, not an assert-event: X is outside the guards, so the terms are
; evaluated in the logic.
(defthm plz-literal-block-improper-list
 (let ((x '(1 2 . 3)))
   (and (not (fn-cbor-octet-listp x))
        (equal (fn-lz-decode nil (fn-lz-literal-block x) (len x)) '(:ok (1 2)))
        (not (equal (fn-lz-decode nil (fn-lz-literal-block x) (len x)) (list :ok x)))
        (equal (fn-lz-seal-form nil x (fn-lz-literal-block x)) (list :raw x))))
 :rule-classes nil)

(must-fail
 (defthm plz-literal-block-without-octets
   (equal (fn-lz-decode dict (fn-lz-literal-block x) (len x)) (list :ok x))
   :hints (("Goal" :do-not-induct t))))

(must-fail
 (defthm plz-seal-literal-block-without-octets
   (equal (fn-lz-seal-form dict x (fn-lz-literal-block x))
          (list :lz (len x) (fn-lz-literal-block x)))
   :hints (("Goal" :do-not-induct t))))

; -----------------------------------------------------------------------------
; The refusals are distinct and the output never passes N
; (fn-lz-decode-buf-out-len-bound, fn-lz-run-out-len-bound).

(assert-event
 (and
  ; the block ends inside a sequence (the final literal-only sequence cut)
  (equal (fn-lz-decode nil (butlast *plz-block* 1) 750) '(:error :truncated))
  ; an offset of 0
  (equal (fn-lz-decode nil '(16 65 0 0 0) 5) '(:error :offset))
  ; an offset past dict ++ out: one octet out, offset 2, no dictionary
  (equal (fn-lz-decode nil '(16 65 2 0 0) 5) '(:error :offset))
  ; the same block with a two-octet dictionary reaches into its last octet
  (equal (fn-lz-decode '(66 67) '(16 65 2 0 0) 5) '(:ok (65 67 65 67 65)))
  ; the article decodes to 750 octets: asked for 749, the output stops at
  ; 749 and the block is refused
  (equal (fn-lz-decode nil *plz-block* 749) '(:error :overflow))
  ; asked for 751, the block ends one short
  (equal (fn-lz-decode nil *plz-block* 751) '(:error :short))))

; -----------------------------------------------------------------------------
; D27: the decoder runs in quanta.  The article's block decoded seven
; steps at a time, resuming from the state each quantum answers (:more),
; reaches the same octets as one budget.

(defun plz-quanta (q fuel ip mode k m off lim fn-octets fn-lz-dict fn-lz-out)
  (declare (xargs :stobjs (fn-octets fn-lz-dict fn-lz-out)
                  :guard (and (posp q) (natp fuel))
                  :measure (nfix fuel)
                  :verify-guards nil))
  (if (zp fuel)
      (mv :fuel 0 fn-lz-out)
    (mv-let (st ip mode k m off fn-lz-out)
      (fn-lz-run q ip (fn-octets-len fn-octets) mode k m off lim
                 fn-octets fn-lz-dict fn-lz-out)
      (if (eq st :more)
          (mv-let (st2 n fn-lz-out)
            (plz-quanta q (1- fuel) ip mode k m off lim fn-octets fn-lz-dict fn-lz-out)
            (mv st2 (1+ n) fn-lz-out))
        (mv st 1 fn-lz-out)))))

(defun plz-decode-in-quanta (dict c n q)
  ; (list status quanta octets)
  (declare (xargs :guard (and (fn-cbor-octet-listp dict) (fn-cbor-octet-listp c)
                              (natp n) (posp q))
                  :verify-guards nil))
  (with-local-stobj fn-octets
    (mv-let (r fn-octets)
      (with-local-stobj fn-lz-dict
        (mv-let (r fn-lz-dict fn-octets)
          (with-local-stobj fn-lz-out
            (mv-let (r fn-lz-out fn-lz-dict fn-octets)
              (let* ((fn-octets (fn-octets-from-list c fn-octets))
                     (fn-lz-dict (fn-lz-dict-from-list dict fn-lz-dict))
                     (fn-lz-out (fn-lz-out-clear fn-lz-out)))
                (mv-let (st quanta fn-lz-out)
                  (plz-quanta q (+ 1 (fn-lz-budget (len c) n)) 0 0 0 0 0 n
                              fn-octets fn-lz-dict fn-lz-out)
                  (mv (list st quanta (fn-lz-out-list fn-lz-out))
                      fn-lz-out fn-lz-dict fn-octets)))
              (mv r fn-lz-dict fn-octets)))
          (mv r fn-octets)))
      r)))

(assert-event
 (let ((r (plz-decode-in-quanta *plz-dict* *plz-dict-block* 750 7)))
   (and (equal (first r) :done)
        (< 10 (second r))
        (equal (third r) *plz-article*))))

; -----------------------------------------------------------------------------
; fn-lz-run-extends-out (hypothesis: (true-listp out)).  Witness: a run
; from a non-empty output keeps it as a prefix.  Removal: from the
; improper output (7 . 8) the prefix of the answer is (7), not (7 . 8).

(defun plz-run-from (out c)
  (declare (xargs :guard (and (fn-cbor-octet-listp out) (fn-cbor-octet-listp c))))
  (with-local-stobj fn-octets
    (mv-let (r fn-octets)
      (with-local-stobj fn-lz-dict
        (mv-let (r fn-lz-dict fn-octets)
          (with-local-stobj fn-lz-out
            (mv-let (r fn-lz-out fn-lz-dict fn-octets)
              (let* ((fn-octets (fn-octets-from-list c fn-octets))
                     (fn-lz-out (fn-lz-out-from-list out fn-lz-out)))
                (mv-let (st ip mode k m off fn-lz-out)
                  (fn-lz-run 100 0 (fn-octets-len fn-octets) 0 0 0 0 100
                             fn-octets fn-lz-dict fn-lz-out)
                  (declare (ignore ip mode k m off))
                  (mv (list st (fn-lz-out-list fn-lz-out)) fn-lz-out fn-lz-dict fn-octets)))
              (mv r fn-lz-dict fn-octets)))
          (mv r fn-octets)))
      r)))

(assert-event
 (let ((r (plz-run-from '(7 8) '(16 65 1 0 0))))
   (and (true-listp '(7 8))
        (equal r '(:done (7 8 65 65 65 65 65)))
        (equal (take 2 (second r)) '(7 8)))))

(defthm plz-extends-out-improper-list
  (let ((r (fn-lz-run 100 0 5 0 0 0 0 100 '(16 65 1 0 0) nil '(7 . 8))))
    (and (not (true-listp '(7 . 8)))
         (equal (mv-nth 6 r) '(7 65 65 65 65 65))
         (not (equal (take (len '(7 . 8)) (mv-nth 6 r)) '(7 . 8)))))
  :rule-classes nil)

(must-fail
 (defthm plz-extends-out-without-true-listp
   (equal (take (len fn-lz-out)
                (mv-nth 6 (fn-lz-run b ip end mode k m off lim fn-octets fn-lz-dict
                                     fn-lz-out)))
          fn-lz-out)
   :hints (("Goal" :do-not-induct t))))

; -----------------------------------------------------------------------------
; Lane keystone-audit (2026-09-27): the two :exec equalities.  Ground
; witnesses proved by evaluation (the out-of-guard teeth by expanding the
; stobj wrappers, whose guards hide a ground call).
;
; fn-lz-lits-words-is-append: nine literals from 1 (a word of 7, then 2)
; after one output octet; every hypothesis holds.  Without the bound
; (+ IP N) <= (len octets): the words past the end read 0 where take pads
; nil.  Without an octet list: a cell of 256 carries into the next octet.
; (true-listp out), (natp ip) and (natp n) are kept from the guard: at the
; instances tried, an improper output and a negative index still agree.
(defthm plz-lits-words-witness
  (and (fn-cbor-octet-listp '(1 2 3 4 5 6 7 8 9 10 11)) (true-listp '(0))
       (natp 1) (natp 9) (<= (+ 1 9) (len '(1 2 3 4 5 6 7 8 9 10 11)))
       (equal (fn-lz-lits-words 1 9 '(1 2 3 4 5 6 7 8 9 10 11) '(0))
              (append '(0) (take 9 (nthcdr 1 '(1 2 3 4 5 6 7 8 9 10 11)))))
       (equal (fn-lz-lits-words 1 9 '(1 2 3 4 5 6 7 8 9 10 11) '(0))
              '(0 2 3 4 5 6 7 8 9 10)))
  :rule-classes nil)
(defthm plz-lits-words-without-the-bound
  (and (not (<= (+ 5 9) (len '(1 2 3 4 5 6 7 8 9 10 11))))
       (not (equal (fn-lz-lits-words 5 9 '(1 2 3 4 5 6 7 8 9 10 11) '(0))
                   (append '(0) (take 9 (nthcdr 5 '(1 2 3 4 5 6 7 8 9 10 11)))))))
  :hints (("Goal" :expand ((:free (ip n o out) (fn-lz-lits-words ip n o out)))))
  :rule-classes nil)
(defthm plz-lits-words-without-octets
  (and (not (fn-cbor-octet-listp '(1 256 3)))
       (not (equal (fn-lz-lits-words 0 3 '(1 256 3) '(0))
                   (append '(0) (take 3 (nthcdr 0 '(1 256 3)))))))
  :rule-classes nil)

; fn-lz-match-bulk-is-copy-match: a match of 4 at offset 5 over a 3-octet
; output and a 3-octet dictionary (two octets from the dictionary, then two
; overlapping from the output); every hypothesis holds.  Without the bound
; OFF <= (len out) + (len dict): offset 7 reaches before the dictionary; the
; per-octet copy stops and the bulk copy does not.  The other hypotheses are
; kept from the guard (no counterexample claimed).
(defthm plz-match-bulk-witness
  (and (fn-cbor-octet-listp '(7 8 9)) (true-listp '(1 2 3))
       (natp 5) (<= 1 5) (natp 4) (<= 5 (+ (len '(1 2 3)) (len '(7 8 9))))
       (equal (fn-lz-match-bulk 5 4 '(7 8 9) '(1 2 3))
              (fn-lz-copy-match 5 4 '(7 8 9) '(1 2 3)))
       (equal (fn-lz-match-bulk 5 4 '(7 8 9) '(1 2 3)) '(1 2 3 8 9 1 2)))
  :hints (("Goal" :expand ((:free (off n d out) (fn-lz-match-bulk off n d out))
                           (:free (off n d out) (fn-lz-copy-match off n d out))
                           (:free (s n d out) (fn-lz-dict-words s n d out)))))
  :rule-classes nil)
(defthm plz-match-bulk-without-the-bound
  (and (not (<= 7 (+ (len '(1 2 3)) (len '(7 8 9)))))
       (not (equal (fn-lz-match-bulk 7 2 '(7 8 9) '(1 2 3))
                   (fn-lz-copy-match 7 2 '(7 8 9) '(1 2 3)))))
  :hints (("Goal" :expand ((:free (off n d out) (fn-lz-match-bulk off n d out))
                           (:free (off n d out) (fn-lz-copy-match off n d out))
                           (:free (s n d out) (fn-lz-dict-words s n d out)))))
  :rule-classes nil)
