; Live foundation/abstract-arena correspondence, from fresh creators and seals.
(in-package "ACL2")
(include-book "../../books/payload-arena")
(include-book "../../books/defkeystone")
(defun art-snapshot (n fn-arena)
 (declare (xargs :stobjs fn-arena :verify-guards nil :measure (nfix n)))
 (if (zp n) nil
  (append (art-snapshot (1- n) fn-arena)
          (list (fn-arena-payload (1- n) fn-arena)))))
(defthm art-snapshot-is-take
 (equal (art-snapshot n fn-arena) (take (nfix n) fn-arena))
 :hints (("Goal" :induct (art-snapshot n fn-arena)
          :in-theory (enable art-snapshot fn-arena-payload))))

(defun art-corr (fn-arena$l fn-arena)
 (declare (xargs :stobjs (fn-arena$l fn-arena) :verify-guards nil))
 (mv (and (fn-arena-p fn-arena)
          (equal (fn-arena$l-items fn-arena$l)
                 (art-snapshot (fn-arena-count fn-arena) fn-arena)))
     fn-arena$l fn-arena))
(local (defthm art-take-len (implies (true-listp xs) (equal (take (len xs) xs) xs))))
(defthm art-corr-is-lcorr
 (equal (mv-nth 0 (art-corr fn-arena$l fn-arena))
        (fn-arena$lcorr fn-arena$l fn-arena))
 :hints (("Goal" :in-theory (enable art-corr fn-arena$lcorr fn-arena-p fn-arena$ap))))
(defun art-list (xs fn-arena$l fn-arena)
 (declare (xargs :stobjs (fn-arena$l fn-arena) :verify-guards nil))
 (let* ((fn-arena$l (fn-arena$l-seal-list xs fn-arena$l))
(fn-arena (fn-arena-seal-list xs fn-arena)))
 (art-corr fn-arena$l fn-arena)))
(defun art-list-skip (xs fn-arena$l fn-arena)
 (declare (xargs :stobjs (fn-arena$l fn-arena) :verify-guards nil))
 (let* ((fn-arena (fn-arena-seal-list xs fn-arena)))
 (art-corr fn-arena$l fn-arena)))
(defun art-buffer (fn-octets fn-arena$l fn-arena)
 (declare (xargs :stobjs (fn-arena$l fn-arena fn-octets) :verify-guards nil))
 (let* ((fn-arena$l (fn-arena$l-seal-buffer fn-octets fn-arena$l))
(fn-arena (fn-arena-seal-buffer fn-octets fn-arena)))
 (art-corr fn-arena$l fn-arena)))
(defun art-buffer-skip (fn-octets fn-arena$l fn-arena)
 (declare (xargs :stobjs (fn-arena$l fn-arena fn-octets) :verify-guards nil))
 (let* ((fn-arena (fn-arena-seal-buffer fn-octets fn-arena)))
 (art-corr fn-arena$l fn-arena)))
(defun art-range (a b fn-octets fn-arena$l fn-arena)
 (declare (xargs :stobjs (fn-arena$l fn-arena fn-octets) :verify-guards nil))
 (let* ((fn-arena$l (fn-arena$l-seal-range a b fn-octets fn-arena$l))
(fn-arena (fn-arena-seal-range a b fn-octets fn-arena)))
 (art-corr fn-arena$l fn-arena)))
(defun art-range-skip (a b fn-octets fn-arena$l fn-arena)
 (declare (xargs :stobjs (fn-arena$l fn-arena fn-octets) :verify-guards nil))
 (let* ((fn-arena (fn-arena-seal-range a b fn-octets fn-arena)))
 (art-corr fn-arena$l fn-arena)))
(defteeth fn-arena-seal-list{correspondence}
 :subject fn-arena-seal-list
 :claim (((correspondence (fn-arena$lcorr fn-arena$l fn-arena)) (octets (fn-cbor-octet-listp xs))) (fn-arena$lcorr (fn-arena$l-seal-list xs fn-arena$l) (fn-arena$a-seal-list xs fn-arena)))
 :witness ((lseed '(17)) (xs '(65 66)) (buffer '(65 66 67)) (a 0) (b 2))
 :stobjs ((fn-arena$l (fn-arena$l-seal-list lseed fn-arena$l))
 (fn-arena (fn-arena-seal-list '(17) fn-arena))
 (fn-octets (fn-octets-from-list buffer fn-octets)))
 :stobj-checks
 (((fn-arena$lcorr fn-arena$l fn-arena) (art-corr fn-arena$l fn-arena))
 ((fn-arena$lcorr (fn-arena$l-seal-list xs fn-arena$l) (fn-arena$a-seal-list xs fn-arena))
 (art-list xs fn-arena$l fn-arena)
 :hints (("Goal" :in-theory (e/d (art-list fn-arena-seal-list) (fn-arena$lcorr art-corr)))))
 ((fn-arena$lcorr fn-arena$l (fn-arena$a-seal-list xs fn-arena))
 (art-list-skip xs fn-arena$l fn-arena)
 :hints (("Goal" :in-theory (e/d (art-list-skip fn-arena-seal-list) (fn-arena$lcorr art-corr))))))
 :breaks ((correspondence ((lseed '(18))))
 (octets ((xs '(300))) :logical "non-octet input makes the appended arena invalid"))
 :mutations ((seal-skipped (:conclusion (fn-arena$lcorr fn-arena$l (fn-arena$a-seal-list xs fn-arena))) () :fault "implementation skips the foundation seal but publishes the logical append")))
(defteeth fn-arena-seal-buffer{correspondence}
 :subject fn-arena-seal-buffer
 :claim (((correspondence (fn-arena$lcorr fn-arena$l fn-arena)) (buffer (fn-octets-p fn-octets))) (fn-arena$lcorr (fn-arena$l-seal-buffer fn-octets fn-arena$l) (fn-arena$a-seal-buffer fn-octets fn-arena)))
 :witness ((lseed '(17)) (xs '(65 66)) (buffer '(65 66 67)) (a 0) (b 2))
 :stobjs ((fn-arena$l (fn-arena$l-seal-list lseed fn-arena$l))
 (fn-arena (fn-arena-seal-list '(17) fn-arena))
 (fn-octets (fn-octets-from-list buffer fn-octets)))
 :stobj-checks
 (((fn-arena$lcorr fn-arena$l fn-arena) (art-corr fn-arena$l fn-arena))
 ((fn-arena$lcorr (fn-arena$l-seal-buffer fn-octets fn-arena$l) (fn-arena$a-seal-buffer fn-octets fn-arena))
 (art-buffer fn-octets fn-arena$l fn-arena)
 :hints (("Goal" :in-theory (e/d (art-buffer fn-arena-seal-buffer) (fn-arena$lcorr art-corr)))))
 ((fn-arena$lcorr fn-arena$l (fn-arena$a-seal-buffer fn-octets fn-arena))
 (art-buffer-skip fn-octets fn-arena$l fn-arena)
 :hints (("Goal" :in-theory (e/d (art-buffer-skip fn-arena-seal-buffer) (fn-arena$lcorr art-corr))))))
 :breaks ((correspondence ((lseed '(18))))
 (buffer ((buffer '(300 66 67))) :logical "corrupted logical buffer has a non-octet cell"))
 :mutations ((seal-skipped (:conclusion (fn-arena$lcorr fn-arena$l (fn-arena$a-seal-buffer fn-octets fn-arena))) () :fault "implementation skips the foundation seal but publishes the logical append")))
(local
 (defthm art-range-past-end
  (not (fn-cbor-octet-listp (fn-oct-slice-list 0 4 '(65 66 67))))
  :hints (("Goal" :expand ((fn-oct-slice-list 0 4 '(65 66 67))
                           (fn-oct-slice-list 1 4 '(65 66 67))
                           (fn-oct-slice-list 2 4 '(65 66 67))
                           (fn-oct-slice-list 3 4 '(65 66 67))
                           (fn-oct-slice-list 4 4 '(65 66 67)))
           :in-theory (e/d (fn-octets-get) ((:e fn-oct-slice-list)))))))
(defteeth fn-arena-seal-range{correspondence}
 :subject fn-arena-seal-range
 :claim (((correspondence (fn-arena$lcorr fn-arena$l fn-arena)) (buffer (fn-octets-p fn-octets)) (end-bound (<= b (fn-octets-len fn-octets)))) (fn-arena$lcorr (fn-arena$l-seal-range a b fn-octets fn-arena$l) (fn-arena$a-seal-range a b fn-octets fn-arena)))
 :hints (("Goal" :in-theory (e/d (fn-oct-slice-list fn-octets-get)
                                  ((:e fn-oct-slice-list) (:e fn-octets-get)))))
 :witness ((lseed '(17)) (xs '(65 66)) (buffer '(65 66 67)) (a 0) (b 2))
 :stobjs ((fn-arena$l (fn-arena$l-seal-list lseed fn-arena$l))
 (fn-arena (fn-arena-seal-list '(17) fn-arena))
 (fn-octets (fn-octets-from-list buffer fn-octets)))
 :stobj-checks
 (((fn-arena$lcorr fn-arena$l fn-arena) (art-corr fn-arena$l fn-arena))
 ((fn-arena$lcorr (fn-arena$l-seal-range a b fn-octets fn-arena$l) (fn-arena$a-seal-range a b fn-octets fn-arena))
 (art-range a b fn-octets fn-arena$l fn-arena)
 :hints (("Goal" :in-theory (e/d (art-range fn-arena-seal-range fn-arena-seal-list) (fn-arena$lcorr art-corr)))))
 ((fn-arena$lcorr fn-arena$l (fn-arena$a-seal-range a b fn-octets fn-arena))
 (art-range-skip a b fn-octets fn-arena$l fn-arena)
 :hints (("Goal" :in-theory (e/d (art-range-skip fn-arena-seal-range fn-arena-seal-list) (fn-arena$lcorr art-corr))))))
 :breaks ((correspondence ((lseed '(18))))
 (buffer ((buffer '(300 66 67))) :logical "corrupted logical buffer has a non-octet cell")
 (end-bound ((b 4)) :logical "range crosses the buffer end"))
 :mutations ((seal-skipped (:conclusion (fn-arena$lcorr fn-arena$l (fn-arena$a-seal-range a b fn-octets fn-arena))) () :fault "implementation skips the foundation seal but publishes the logical append")))
(defteeth-check (fn-arena-seal-list{correspondence} fn-arena-seal-buffer{correspondence} fn-arena-seal-range{correspondence}))
