; Actual session traces retain transport loss, not a guessed failure cause.
(in-package "ACL2")
(include-book "../../books/peer-catchup-diagnostics")

(defconst *pcdt-peer* (fn-record-string-octets "A"))
(defconst *pcdt-plan*
 (list *pcdt-peer* (fn-record-string-octets "10.1.2.3") 11119
       (fn-record-string-octets "fn.*") 2000
       (list :tls :starttls "localhost" "/a/anchor.pem")
       (list :authinfo "/b/A.fnauth" nil) *fn-pull-default-unavailable-rounds*))
(defconst *pcdt-begin*
 (fn-cu-session-begin-pair *pcdt-plan* (fn-cu-fresh-cursor *pcdt-peer*)
                         (list (fn-record-string-octets "nodeB")
                               (fn-record-string-octets "s3cret"))))
(defconst *pcdt-start* (car *pcdt-begin*))
(assert-event (equal (fn-pull-plan-verdict *pcdt-plan*) :tls))
(assert-event (not (fn-cu-session-done-p *pcdt-start*)))
(assert-event (not (fn-cu-session-readyp *pcdt-start*)))

(defun pcdt-line (text) (append (fn-record-string-octets text) '(13 10)))
(defun pcdt-drive (s events)
 (declare (xargs :verify-guards nil))
 (if (consp events)
     (pcdt-drive (car (fn-cu-session-step-triple s (car events))) (cdr events))
   s))
(defconst *pcdt-ready*
 (pcdt-drive *pcdt-start*
  (list (cons :remote (pcdt-line "200 A ready"))
        (cons :remote (pcdt-line "382 begin TLS"))
        (list :tls-up)
        (cons :remote (pcdt-line "381 password"))
        (cons :remote (pcdt-line "281 ok")))))
(assert-event (fn-cu-session-readyp *pcdt-ready*))
(assert-event (not (fn-cu-session-done-p *pcdt-ready*)))
(assert-event (equal (fn-cu-r-phase (fn-cu-s-round *pcdt-ready*)) :reply))

(defthm pcdt-preamble-dial-retains-the-actual-loss
 (let* ((event '(:lost :dial))
        (triple (fn-cu-session-step-triple *pcdt-start* event))
        (s2 (car triple))
        (detail (caddr triple)))
  (and (not (fn-cu-session-done-p *pcdt-start*))
       (equal (fn-cu-r-phase (fn-cu-s-round s2)) :failed)
       (equal (take 2 triple) (fn-cu-session-step-pair *pcdt-start* event))
       (equal detail '("lost-dial" "preamble"))
       (equal (fn-cu-session-log-line-detail s2 detail)
              (append (fn-cu-session-log-line s2)
                      (fn-record-string-octets " loss=lost-dial loss-phase=preamble")))))
 :rule-classes nil)

(defthm pcdt-preamble-tls-retains-the-actual-loss
 (let* ((event '(:lost :tls))
        (triple (fn-cu-session-step-triple *pcdt-start* event))
        (s2 (car triple))
        (detail (caddr triple)))
  (and (not (fn-cu-session-done-p *pcdt-start*))
       (equal (fn-cu-r-phase (fn-cu-s-round s2)) :failed)
       (equal (take 2 triple) (fn-cu-session-step-pair *pcdt-start* event))
       (equal detail '("lost-tls" "preamble"))
       (equal (fn-cu-session-log-line-detail s2 detail)
              (append (fn-cu-session-log-line s2)
                      (fn-record-string-octets " loss=lost-tls loss-phase=preamble")))))
 :rule-classes nil)

(defthm pcdt-preamble-send-retains-the-actual-loss
 (let* ((event '(:lost :send))
        (triple (fn-cu-session-step-triple *pcdt-start* event))
        (s2 (car triple))
        (detail (caddr triple)))
  (and (not (fn-cu-session-done-p *pcdt-start*))
       (equal (fn-cu-r-phase (fn-cu-s-round s2)) :failed)
       (equal (take 2 triple) (fn-cu-session-step-pair *pcdt-start* event))
       (equal detail '("lost-send" "preamble"))
       (equal (fn-cu-session-log-line-detail s2 detail)
              (append (fn-cu-session-log-line s2)
                      (fn-record-string-octets " loss=lost-send loss-phase=preamble")))))
 :rule-classes nil)

(defthm pcdt-preamble-timeout-retains-the-actual-loss
 (let* ((event '(:lost :timeout))
        (triple (fn-cu-session-step-triple *pcdt-start* event))
        (s2 (car triple))
        (detail (caddr triple)))
  (and (not (fn-cu-session-done-p *pcdt-start*))
       (equal (fn-cu-r-phase (fn-cu-s-round s2)) :failed)
       (equal (take 2 triple) (fn-cu-session-step-pair *pcdt-start* event))
       (equal detail '("lost-timeout" "preamble"))
       (equal (fn-cu-session-log-line-detail s2 detail)
              (append (fn-cu-session-log-line s2)
                      (fn-record-string-octets " loss=lost-timeout loss-phase=preamble")))))
 :rule-classes nil)

(defthm pcdt-preamble-read-retains-the-actual-loss
 (let* ((event '(:lost :read))
        (triple (fn-cu-session-step-triple *pcdt-start* event))
        (s2 (car triple))
        (detail (caddr triple)))
  (and (not (fn-cu-session-done-p *pcdt-start*))
       (equal (fn-cu-r-phase (fn-cu-s-round s2)) :failed)
       (equal (take 2 triple) (fn-cu-session-step-pair *pcdt-start* event))
       (equal detail '("lost-read" "preamble"))
       (equal (fn-cu-session-log-line-detail s2 detail)
              (append (fn-cu-session-log-line s2)
                      (fn-record-string-octets " loss=lost-read loss-phase=preamble")))))
 :rule-classes nil)

(defthm pcdt-preamble-eof-retains-the-actual-loss
 (let* ((event '(:lost :eof))
        (triple (fn-cu-session-step-triple *pcdt-start* event))
        (s2 (car triple))
        (detail (caddr triple)))
  (and (not (fn-cu-session-done-p *pcdt-start*))
       (equal (fn-cu-r-phase (fn-cu-s-round s2)) :failed)
       (equal (take 2 triple) (fn-cu-session-step-pair *pcdt-start* event))
       (equal detail '("lost-eof" "preamble"))
       (equal (fn-cu-session-log-line-detail s2 detail)
              (append (fn-cu-session-log-line s2)
                      (fn-record-string-octets " loss=lost-eof loss-phase=preamble")))))
 :rule-classes nil)

(defthm pcdt-preamble-local-retains-the-actual-loss
 (let* ((event '(:lost :local))
        (triple (fn-cu-session-step-triple *pcdt-start* event))
        (s2 (car triple))
        (detail (caddr triple)))
  (and (not (fn-cu-session-done-p *pcdt-start*))
       (equal (fn-cu-r-phase (fn-cu-s-round s2)) :failed)
       (equal (take 2 triple) (fn-cu-session-step-pair *pcdt-start* event))
       (equal detail '("lost-local" "preamble"))
       (equal (fn-cu-session-log-line-detail s2 detail)
              (append (fn-cu-session-log-line s2)
                      (fn-record-string-octets " loss=lost-local loss-phase=preamble")))))
 :rule-classes nil)

(defthm pcdt-reply-dial-retains-the-actual-loss
 (let* ((event '(:lost :dial))
        (triple (fn-cu-session-step-triple *pcdt-ready* event))
        (s2 (car triple))
        (detail (caddr triple)))
  (and (not (fn-cu-session-done-p *pcdt-ready*))
       (equal (fn-cu-r-phase (fn-cu-s-round s2)) :failed)
       (equal (take 2 triple) (fn-cu-session-step-pair *pcdt-ready* event))
       (equal detail '("lost-dial" "reply"))
       (equal (fn-cu-session-log-line-detail s2 detail)
              (append (fn-cu-session-log-line s2)
                      (fn-record-string-octets " loss=lost-dial loss-phase=reply")))))
 :rule-classes nil)

(defthm pcdt-reply-tls-retains-the-actual-loss
 (let* ((event '(:lost :tls))
        (triple (fn-cu-session-step-triple *pcdt-ready* event))
        (s2 (car triple))
        (detail (caddr triple)))
  (and (not (fn-cu-session-done-p *pcdt-ready*))
       (equal (fn-cu-r-phase (fn-cu-s-round s2)) :failed)
       (equal (take 2 triple) (fn-cu-session-step-pair *pcdt-ready* event))
       (equal detail '("lost-tls" "reply"))
       (equal (fn-cu-session-log-line-detail s2 detail)
              (append (fn-cu-session-log-line s2)
                      (fn-record-string-octets " loss=lost-tls loss-phase=reply")))))
 :rule-classes nil)

(defthm pcdt-reply-send-retains-the-actual-loss
 (let* ((event '(:lost :send))
        (triple (fn-cu-session-step-triple *pcdt-ready* event))
        (s2 (car triple))
        (detail (caddr triple)))
  (and (not (fn-cu-session-done-p *pcdt-ready*))
       (equal (fn-cu-r-phase (fn-cu-s-round s2)) :failed)
       (equal (take 2 triple) (fn-cu-session-step-pair *pcdt-ready* event))
       (equal detail '("lost-send" "reply"))
       (equal (fn-cu-session-log-line-detail s2 detail)
              (append (fn-cu-session-log-line s2)
                      (fn-record-string-octets " loss=lost-send loss-phase=reply")))))
 :rule-classes nil)

(defthm pcdt-reply-timeout-retains-the-actual-loss
 (let* ((event '(:lost :timeout))
        (triple (fn-cu-session-step-triple *pcdt-ready* event))
        (s2 (car triple))
        (detail (caddr triple)))
  (and (not (fn-cu-session-done-p *pcdt-ready*))
       (equal (fn-cu-r-phase (fn-cu-s-round s2)) :failed)
       (equal (take 2 triple) (fn-cu-session-step-pair *pcdt-ready* event))
       (equal detail '("lost-timeout" "reply"))
       (equal (fn-cu-session-log-line-detail s2 detail)
              (append (fn-cu-session-log-line s2)
                      (fn-record-string-octets " loss=lost-timeout loss-phase=reply")))))
 :rule-classes nil)

(defthm pcdt-reply-read-retains-the-actual-loss
 (let* ((event '(:lost :read))
        (triple (fn-cu-session-step-triple *pcdt-ready* event))
        (s2 (car triple))
        (detail (caddr triple)))
  (and (not (fn-cu-session-done-p *pcdt-ready*))
       (equal (fn-cu-r-phase (fn-cu-s-round s2)) :failed)
       (equal (take 2 triple) (fn-cu-session-step-pair *pcdt-ready* event))
       (equal detail '("lost-read" "reply"))
       (equal (fn-cu-session-log-line-detail s2 detail)
              (append (fn-cu-session-log-line s2)
                      (fn-record-string-octets " loss=lost-read loss-phase=reply")))))
 :rule-classes nil)

(defthm pcdt-reply-eof-retains-the-actual-loss
 (let* ((event '(:lost :eof))
        (triple (fn-cu-session-step-triple *pcdt-ready* event))
        (s2 (car triple))
        (detail (caddr triple)))
  (and (not (fn-cu-session-done-p *pcdt-ready*))
       (equal (fn-cu-r-phase (fn-cu-s-round s2)) :failed)
       (equal (take 2 triple) (fn-cu-session-step-pair *pcdt-ready* event))
       (equal detail '("lost-eof" "reply"))
       (equal (fn-cu-session-log-line-detail s2 detail)
              (append (fn-cu-session-log-line s2)
                      (fn-record-string-octets " loss=lost-eof loss-phase=reply")))))
 :rule-classes nil)

(defthm pcdt-reply-local-retains-the-actual-loss
 (let* ((event '(:lost :local))
        (triple (fn-cu-session-step-triple *pcdt-ready* event))
        (s2 (car triple))
        (detail (caddr triple)))
  (and (not (fn-cu-session-done-p *pcdt-ready*))
       (equal (fn-cu-r-phase (fn-cu-s-round s2)) :failed)
       (equal (take 2 triple) (fn-cu-session-step-pair *pcdt-ready* event))
       (equal detail '("lost-local" "reply"))
       (equal (fn-cu-session-log-line-detail s2 detail)
              (append (fn-cu-session-log-line s2)
                      (fn-record-string-octets " loss=lost-local loss-phase=reply")))))
 :rule-classes nil)

(defconst *pcdt-first-loss* (fn-cu-session-step-triple *pcdt-ready* '(:lost :timeout)))
(assert-event (equal (caddr *pcdt-first-loss*) '("lost-timeout" "reply")))
; A terminal session does not blame a later observation for its failure.
(assert-event (null (caddr (fn-cu-session-step-triple (car *pcdt-first-loss*) '(:lost :eof)))))
; A protocol refusal retains its protocol reason, without inventing a socket loss.
(defconst *pcdt-protocol-refusal*
 (fn-cu-session-step-triple *pcdt-start* (cons :remote (pcdt-line "500 no greeting"))))
(assert-event (equal (fn-cu-r-phase (fn-cu-s-round (car *pcdt-protocol-refusal*))) :failed))
(assert-event (null (caddr *pcdt-protocol-refusal*)))
(assert-event (equal (fn-cu-session-log-line-detail (car *pcdt-protocol-refusal*) nil)
                     (fn-cu-session-log-line (car *pcdt-protocol-refusal*))))
