(in-package "ACL2")
(include-book "../../books/peer-catchup-spool-hash")

(defun csp-hash-test-run (total bytes lease fuel fn-octets pgs-digest-state)
  (declare (xargs :stobjs (fn-octets pgs-digest-state) :mode :program))
  (if (zp fuel) (mv :exhausted nil fn-octets pgs-digest-state)
    (let ((action (fn-csp-hash-action total 0 lease pgs-digest-state)))
      (case (car action)
        (:done (mv :done (cadr action) fn-octets pgs-digest-state))
        (:read
         (let* ((part (take (caddr action) (nthcdr (cadr action) bytes)))
                (fn-octets (fn-octets-from-list part fn-octets)))
           (mv-let (word pgs-digest-state)
             (fn-csp-hash-read total lease :ok (caddr action) fn-octets pgs-digest-state)
             (if (eq word :invalid) (mv :invalid nil fn-octets pgs-digest-state)
               (csp-hash-test-run total bytes lease (1- fuel) fn-octets pgs-digest-state)))))
        (:tick
         (mv-let (word pgs-digest-state) (fn-csp-hash-tick total lease pgs-digest-state)
           (if (eq word :invalid) (mv :invalid nil fn-octets pgs-digest-state)
             (csp-hash-test-run total bytes lease (1- fuel) fn-octets pgs-digest-state))))
        (otherwise (mv :refused nil fn-octets pgs-digest-state))))))

(defun csp-hash-test (bytes fn-octets pgs-digest-state)
  (declare (xargs :stobjs (fn-octets pgs-digest-state) :mode :program))
  (let ((pgs-digest-state (fn-csp-hash-begin (len bytes) '(7 11) pgs-digest-state)))
    (mv-let (word digest fn-octets pgs-digest-state)
      (csp-hash-test-run (len bytes) bytes '(7 11) 1000 fn-octets pgs-digest-state)
      (mv (list word digest) fn-octets pgs-digest-state))))

(defun csp-hash-fixture (n)
  (declare (xargs :mode :program))
  (with-local-stobj fn-octets
    (mv-let (result fn-octets)
      (with-local-stobj pgs-digest-state
        (mv-let (result fn-octets pgs-digest-state)
          (csp-hash-test (make-list n :initial-element 120) fn-octets pgs-digest-state)
          (mv result fn-octets)))
      result)))

(assert-event (equal (csp-hash-fixture 0)
                    (list :done (fn-blake3-stobj nil))))
(assert-event (equal (csp-hash-fixture 1)
                    (list :done (fn-blake3-stobj '(120)))))
(assert-event (equal (csp-hash-fixture 63)
                    (list :done (fn-blake3-stobj (make-list 63 :initial-element 120)))))
(assert-event (equal (csp-hash-fixture 64)
                    (list :done (fn-blake3-stobj (make-list 64 :initial-element 120)))))
(assert-event (equal (csp-hash-fixture 65)
                    (list :done (fn-blake3-stobj (make-list 65 :initial-element 120)))))
(assert-event (equal (csp-hash-fixture 1023)
                    (list :done (fn-blake3-stobj (make-list 1023 :initial-element 120)))))
(assert-event (equal (csp-hash-fixture 1024)
                    (list :done (fn-blake3-stobj (make-list 1024 :initial-element 120)))))
(assert-event (equal (csp-hash-fixture 1025)
                    (list :done (fn-blake3-stobj (make-list 1025 :initial-element 120)))))
(assert-event (equal (csp-hash-fixture 16385)
                    (list :done (fn-blake3-stobj (make-list 16385 :initial-element 120)))))
