(in-package "ACL2")

(include-book "../../books/post-identity-source-cursor-source-complete")

(defthm fn-psc-source-complete-generated-held-literal
 (let* ((xs (append (fn-inj-path-line '(97)) (fn-inj-injection-info-line '(97)) '(13 10 120))) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (start 0) (end 1) (n (len xs)) (incoming-n (len incoming))
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs))
        (skip (fn-psc-model-skip-complete c incoming held)) (entry (fn-psc-step skip nil)) (pos (fn-psc-get pos skip)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (<= start end) (<= end (len incoming)) (equal n (len xs)) (equal incoming-n (len incoming))
       (equal desc '(41 41 41)) (equal (fn-psc-get phase d) :done)
       (equal (fn-psc-result d) (if desc (cons :source desc) :no-source))
       (or (equal (fn-psc-result d) :no-source) (and (equal (car (fn-psc-result d)) :source) (fn-pbb-descp (cdr (fn-psc-result d)) n)))
       (fn-psc-source-contextp c incoming held) (equal (fn-psc-get phase c) :control) (equal (fn-psc-get resume c) :start)
       (equal d (fn-psc-model-source-complete c incoming held))
       (fn-psc-source-contextp entry incoming held) (natp pos) (<= pos n) (equal (fn-psc-get skip entry) pos) (equal pos (fn-pbb-skip-at xs))
       (equal d (fn-psc-model-source-body-complete pos entry incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-body-cost pos entry incoming held) entry incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-complete-generated-incoming-literal
 (let* ((xs (append (fn-inj-path-line '(97)) (fn-inj-injection-info-line '(97)) '(13 10 120))) (incoming xs) (held xs) (mode :source-incoming) (msgid "<a@b>")
        (start 6) (end 7) (n (len xs)) (incoming-n (len incoming))
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs))
        (skip (fn-psc-model-skip-complete c incoming held)) (entry (fn-psc-step skip nil)) (pos (fn-psc-get pos skip)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (<= start end) (<= end (len incoming)) (equal n (len xs)) (equal incoming-n (len incoming))
       (equal desc '(41 41 41)) (equal (fn-psc-get phase d) :done)
       (equal (fn-psc-result d) (if desc (cons :source desc) :no-source))
       (or (equal (fn-psc-result d) :no-source) (and (equal (car (fn-psc-result d)) :source) (fn-pbb-descp (cdr (fn-psc-result d)) n)))
       (fn-psc-source-contextp c incoming held) (equal (fn-psc-get phase c) :control) (equal (fn-psc-get resume c) :start)
       (equal d (fn-psc-model-source-complete c incoming held))
       (fn-psc-source-contextp entry incoming held) (natp pos) (<= pos n) (equal (fn-psc-get skip entry) pos) (equal pos (fn-pbb-skip-at xs))
       (equal d (fn-psc-model-source-body-complete pos entry incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-body-cost pos entry incoming held) entry incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-complete-v3-held-literal
 (let* ((xs (append (fn-inj-injection-info-line '(97)) '(80 97 116 104 58 32 97 33 112 101 101 114 13 10 13 10 120))) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (start 0) (end 1) (n (len xs)) (incoming-n (len incoming))
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs))
        (skip (fn-psc-model-skip-complete c incoming held)) (entry (fn-psc-step skip nil)) (pos (fn-psc-get pos skip)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (<= start end) (<= end (len incoming)) (equal n (len xs)) (equal incoming-n (len incoming))
       (equal desc '(19 25 27)) (equal (fn-psc-get phase d) :done)
       (equal (fn-psc-result d) (if desc (cons :source desc) :no-source))
       (or (equal (fn-psc-result d) :no-source) (and (equal (car (fn-psc-result d)) :source) (fn-pbb-descp (cdr (fn-psc-result d)) n)))
       (fn-psc-source-contextp c incoming held) (equal (fn-psc-get phase c) :control) (equal (fn-psc-get resume c) :start)
       (equal d (fn-psc-model-source-complete c incoming held))
       (fn-psc-source-contextp entry incoming held) (natp pos) (<= pos n) (equal (fn-psc-get skip entry) pos) (equal pos (fn-pbb-skip-at xs))
       (equal d (fn-psc-model-source-body-complete pos entry incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-body-cost pos entry incoming held) entry incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-complete-v3-casefold-literal
 (let* ((xs (append (fn-inj-injection-info-line '(97)) '(112 65 116 72 58 32 97 33 112 101 101 114 13 10))) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (start 0) (end 1) (n (len xs)) (incoming-n (len incoming))
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs))
        (skip (fn-psc-model-skip-complete c incoming held)) (entry (fn-psc-step skip nil)) (pos (fn-psc-get pos skip)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (<= start end) (<= end (len incoming)) (equal n (len xs)) (equal incoming-n (len incoming))
       (equal desc '(19 25 27)) (equal (fn-psc-get phase d) :done)
       (equal (fn-psc-result d) (if desc (cons :source desc) :no-source))
       (or (equal (fn-psc-result d) :no-source) (and (equal (car (fn-psc-result d)) :source) (fn-pbb-descp (cdr (fn-psc-result d)) n)))
       (fn-psc-source-contextp c incoming held) (equal (fn-psc-get phase c) :control) (equal (fn-psc-get resume c) :start)
       (equal d (fn-psc-model-source-complete c incoming held))
       (fn-psc-source-contextp entry incoming held) (natp pos) (<= pos n) (equal (fn-psc-get skip entry) pos) (equal pos (fn-pbb-skip-at xs))
       (equal d (fn-psc-model-source-body-complete pos entry incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-body-cost pos entry incoming held) entry incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-complete-v1-literal
 (let* ((xs (append (fn-inj-path-line '(97)) (fn-inj-injection-date-line '(97 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48)) (fn-inj-injection-info-line '(97)))) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (start 0) (end 1) (n (len xs)) (incoming-n (len incoming))
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs))
        (skip (fn-psc-model-skip-complete c incoming held)) (entry (fn-psc-step skip nil)) (pos (fn-psc-get pos skip)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (<= start end) (<= end (len incoming)) (equal n (len xs)) (equal incoming-n (len incoming))
       (equal desc '(90 90 90)) (equal (fn-psc-get phase d) :done)
       (equal (fn-psc-result d) (if desc (cons :source desc) :no-source))
       (or (equal (fn-psc-result d) :no-source) (and (equal (car (fn-psc-result d)) :source) (fn-pbb-descp (cdr (fn-psc-result d)) n)))
       (fn-psc-source-contextp c incoming held) (equal (fn-psc-get phase c) :control) (equal (fn-psc-get resume c) :start)
       (equal d (fn-psc-model-source-complete c incoming held))
       (fn-psc-source-contextp entry incoming held) (natp pos) (<= pos n) (equal (fn-psc-get skip entry) pos) (equal pos (fn-pbb-skip-at xs))
       (equal d (fn-psc-model-source-body-complete pos entry incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-body-cost pos entry incoming held) entry incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-complete-v2-literal
 (let* ((xs (append (fn-inj-path-line '(97)) (fn-inj-injection-date-line '(97 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48)) (fn-inj-message-id-line '(60 97 64 98 62)) (fn-inj-date-line '(97 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48 48)) (fn-inj-injection-info-line '(97)))) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (start 0) (end 1) (n (len xs)) (incoming-n (len incoming))
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs))
        (skip (fn-psc-model-skip-complete c incoming held)) (entry (fn-psc-step skip nil)) (pos (fn-psc-get pos skip)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (<= start end) (<= end (len incoming)) (equal n (len xs)) (equal incoming-n (len incoming))
       (equal desc (list (len xs) (len xs) (len xs))) (equal (fn-psc-get phase d) :done)
       (equal (fn-psc-result d) (if desc (cons :source desc) :no-source))
       (or (equal (fn-psc-result d) :no-source) (and (equal (car (fn-psc-result d)) :source) (fn-pbb-descp (cdr (fn-psc-result d)) n)))
       (fn-psc-source-contextp c incoming held) (equal (fn-psc-get phase c) :control) (equal (fn-psc-get resume c) :start)
       (equal d (fn-psc-model-source-complete c incoming held))
       (fn-psc-source-contextp entry incoming held) (natp pos) (<= pos n) (equal (fn-psc-get skip entry) pos) (equal pos (fn-pbb-skip-at xs))
       (equal d (fn-psc-model-source-body-complete pos entry incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-body-cost pos entry incoming held) entry incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-complete-cancel-lock-key-literal
 (let* ((xs (append '(67 97 110 99 101 108 45 76 111 99 107 58 32 120 13 10 67 97 110 99 101 108 45 75 101 121 58 32 121 13 10) (append (fn-inj-path-line '(97)) (fn-inj-injection-info-line '(97)) '(13 10 120)))) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (start 0) (end 1) (n (len xs)) (incoming-n (len incoming))
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs))
        (skip (fn-psc-model-skip-complete c incoming held)) (entry (fn-psc-step skip nil)) (pos (fn-psc-get pos skip)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (<= start end) (<= end (len incoming)) (equal n (len xs)) (equal incoming-n (len incoming))
       (equal desc '(72 72 72)) (equal (fn-psc-get phase d) :done)
       (equal (fn-psc-result d) (if desc (cons :source desc) :no-source))
       (or (equal (fn-psc-result d) :no-source) (and (equal (car (fn-psc-result d)) :source) (fn-pbb-descp (cdr (fn-psc-result d)) n)))
       (fn-psc-source-contextp c incoming held) (equal (fn-psc-get phase c) :control) (equal (fn-psc-get resume c) :start)
       (equal d (fn-psc-model-source-complete c incoming held))
       (fn-psc-source-contextp entry incoming held) (natp pos) (<= pos n) (equal (fn-psc-get skip entry) pos) (equal pos (fn-pbb-skip-at xs))
       (equal d (fn-psc-model-source-body-complete pos entry incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-body-cost pos entry incoming held) entry incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-complete-no-path-literal
 (let* ((xs (append (fn-inj-injection-info-line '(97)) '(13 10 120))) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (start 0) (end 1) (n (len xs)) (incoming-n (len incoming))
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs))
        (skip (fn-psc-model-skip-complete c incoming held)) (entry (fn-psc-step skip nil)) (pos (fn-psc-get pos skip)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (<= start end) (<= end (len incoming)) (equal n (len xs)) (equal incoming-n (len incoming))
       (equal desc nil) (equal (fn-psc-get phase d) :done)
       (equal (fn-psc-result d) (if desc (cons :source desc) :no-source))
       (or (equal (fn-psc-result d) :no-source) (and (equal (car (fn-psc-result d)) :source) (fn-pbb-descp (cdr (fn-psc-result d)) n)))
       (fn-psc-source-contextp c incoming held) (equal (fn-psc-get phase c) :control) (equal (fn-psc-get resume c) :start)
       (equal d (fn-psc-model-source-complete c incoming held))
       (fn-psc-source-contextp entry incoming held) (natp pos) (<= pos n) (equal (fn-psc-get skip entry) pos) (equal pos (fn-pbb-skip-at xs))
       (equal d (fn-psc-model-source-body-complete pos entry incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-body-cost pos entry incoming held) entry incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-complete-agent-mismatch-literal
 (let* ((xs (append (fn-inj-path-line '(98)) (fn-inj-injection-info-line '(98)))) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (start 0) (end 1) (n (len xs)) (incoming-n (len incoming))
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs))
        (skip (fn-psc-model-skip-complete c incoming held)) (entry (fn-psc-step skip nil)) (pos (fn-psc-get pos skip)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (<= start end) (<= end (len incoming)) (equal n (len xs)) (equal incoming-n (len incoming))
       (equal desc nil) (equal (fn-psc-get phase d) :done)
       (equal (fn-psc-result d) (if desc (cons :source desc) :no-source))
       (or (equal (fn-psc-result d) :no-source) (and (equal (car (fn-psc-result d)) :source) (fn-pbb-descp (cdr (fn-psc-result d)) n)))
       (fn-psc-source-contextp c incoming held) (equal (fn-psc-get phase c) :control) (equal (fn-psc-get resume c) :start)
       (equal d (fn-psc-model-source-complete c incoming held))
       (fn-psc-source-contextp entry incoming held) (natp pos) (<= pos n) (equal (fn-psc-get skip entry) pos) (equal pos (fn-pbb-skip-at xs))
       (equal d (fn-psc-model-source-body-complete pos entry incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-body-cost pos entry incoming held) entry incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-complete-truncated-stamp-literal
 (let* ((xs (append (fn-inj-path-line '(97)) '(73 110 106 101 99 116 105 111 110 45 68 97 116 101 58 32 97))) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (start 0) (end 1) (n (len xs)) (incoming-n (len incoming))
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs))
        (skip (fn-psc-model-skip-complete c incoming held)) (entry (fn-psc-step skip nil)) (pos (fn-psc-get pos skip)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (<= start end) (<= end (len incoming)) (equal n (len xs)) (equal incoming-n (len incoming))
       (equal desc nil) (equal (fn-psc-get phase d) :done)
       (equal (fn-psc-result d) (if desc (cons :source desc) :no-source))
       (or (equal (fn-psc-result d) :no-source) (and (equal (car (fn-psc-result d)) :source) (fn-pbb-descp (cdr (fn-psc-result d)) n)))
       (fn-psc-source-contextp c incoming held) (equal (fn-psc-get phase c) :control) (equal (fn-psc-get resume c) :start)
       (equal d (fn-psc-model-source-complete c incoming held))
       (fn-psc-source-contextp entry incoming held) (natp pos) (<= pos n) (equal (fn-psc-get skip entry) pos) (equal pos (fn-pbb-skip-at xs))
       (equal d (fn-psc-model-source-body-complete pos entry incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-body-cost pos entry incoming held) entry incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-complete-v3-empty-agent-literal
 (let* ((xs (append (fn-inj-injection-info-line nil) '(80 97 116 104 58 32 33 112 101 101 114 13 10))) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (start 0) (end 0) (n (len xs)) (incoming-n (len incoming))
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs))
        (skip (fn-psc-model-skip-complete c incoming held)) (entry (fn-psc-step skip nil)) (pos (fn-psc-get pos skip)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (<= start end) (<= end (len incoming)) (equal n (len xs)) (equal incoming-n (len incoming))
       (equal desc '(18 24 25)) (equal (fn-psc-get phase d) :done)
       (equal (fn-psc-result d) (if desc (cons :source desc) :no-source))
       (or (equal (fn-psc-result d) :no-source) (and (equal (car (fn-psc-result d)) :source) (fn-pbb-descp (cdr (fn-psc-result d)) n)))
       (fn-psc-source-contextp c incoming held) (equal (fn-psc-get phase c) :control) (equal (fn-psc-get resume c) :start)
       (equal d (fn-psc-model-source-complete c incoming held))
       (fn-psc-source-contextp entry incoming held) (natp pos) (<= pos n) (equal (fn-psc-get skip entry) pos) (equal pos (fn-pbb-skip-at xs))
       (equal d (fn-psc-model-source-body-complete pos entry incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-body-cost pos entry incoming held) entry incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-complete-empty-source-literal
 (let* ((xs nil) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (start 0) (end 1) (n (len xs)) (incoming-n (len incoming))
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs))
        (skip (fn-psc-model-skip-complete c incoming held)) (entry (fn-psc-step skip nil)) (pos (fn-psc-get pos skip)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (<= start end) (<= end (len incoming)) (equal n (len xs)) (equal incoming-n (len incoming))
       (equal desc nil) (equal (fn-psc-get phase d) :done)
       (equal (fn-psc-result d) (if desc (cons :source desc) :no-source))
       (or (equal (fn-psc-result d) :no-source) (and (equal (car (fn-psc-result d)) :source) (fn-pbb-descp (cdr (fn-psc-result d)) n)))
       (fn-psc-source-contextp c incoming held) (equal (fn-psc-get phase c) :control) (equal (fn-psc-get resume c) :start)
       (equal d (fn-psc-model-source-complete c incoming held))
       (fn-psc-source-contextp entry incoming held) (natp pos) (<= pos n) (equal (fn-psc-get skip entry) pos) (equal pos (fn-pbb-skip-at xs))
       (equal d (fn-psc-model-source-body-complete pos entry incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-body-cost pos entry incoming held) entry incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-complete-source-length-removal-literal
 (let* ((xs (append (fn-inj-path-line '(97)) (fn-inj-injection-info-line '(97)))) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (n 0) (incoming-n 1) (start 0) (end 1)
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (not (equal n (len xs))) (equal incoming-n (len incoming)) (<= end (len incoming)) (<= start end)
       (equal desc (list (len xs) (len xs) (len xs)))
       (equal (fn-psc-get phase d) :done) (equal (fn-psc-result d) :no-source)
       (not (equal (fn-psc-result d) (if desc (cons :source desc) :no-source)))))
 :rule-classes nil)

(defthm fn-psc-source-complete-incoming-length-removal-literal
 (let* ((xs (append (fn-inj-path-line '(97)) (fn-inj-injection-info-line '(97)))) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (n 41) (incoming-n 0) (start 0) (end 1)
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (equal n (len xs)) (not (equal incoming-n (len incoming))) (<= end (len incoming)) (<= start end)
       (equal desc (list (len xs) (len xs) (len xs)))
       (equal (fn-psc-get phase d) :done) (equal (fn-psc-result d) :no-source)
       (not (equal (fn-psc-result d) (if desc (cons :source desc) :no-source)))))
 :rule-classes nil)

(defthm fn-psc-source-complete-agent-end-removal-literal
 (let* ((xs (append (fn-inj-path-line '(97)) (fn-inj-injection-info-line '(97)))) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (n 41) (incoming-n 1) (start 0) (end 2)
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (equal n (len xs)) (equal incoming-n (len incoming)) (not (<= end (len incoming))) (<= start end)
       (equal desc (list (len xs) (len xs) (len xs)))
       (equal (fn-psc-get phase d) :done) (equal (fn-psc-result d) :no-source)
       (not (equal (fn-psc-result d) (if desc (cons :source desc) :no-source)))))
 :rule-classes nil)

(defthm fn-psc-source-complete-agent-order-removal-literal
 (let* ((xs (append (fn-inj-path-line nil) (fn-inj-injection-info-line nil))) (incoming '(97)) (held xs) (mode :source-held) (msgid "<a@b>")
        (n 39) (incoming-n 1) (start 1) (end 0)
        (c (fn-psc-begin mode n msgid (list :agent start end) incoming-n))
        (d (fn-psc-model-byte-run (fn-psc-model-source-cost c incoming held) c incoming held))
        (desc (fn-pbb-source-index (fn-inj-take (- end start) (nthcdr start incoming)) (fn-record-string-octets msgid) xs)))
  (and (member-eq mode '(:source-incoming :source-held)) (true-listp incoming) (true-listp xs) (stringp msgid)
       (natp start) (natp end) (equal n (len xs)) (equal incoming-n (len incoming)) (<= end (len incoming)) (not (<= start end))
       (equal desc (list (len xs) (len xs) (len xs)))
       (equal (fn-psc-get phase d) :done) (equal (fn-psc-result d) :no-source)
       (not (equal (fn-psc-result d) (if desc (cons :source desc) :no-source)))))
 :rule-classes nil)
