; Complete literal antecedent/conclusion witnesses for actual source extents.
(in-package "ACL2")
(include-book "../../books/post-identity-captured-source-pair-context")
(include-book "post-identity-captured-agent-join-tests")
(defconst *pic-spt-held* (make-list 145 :initial-element 0))
(defthm pic-spt-producer-positive
 (let* ((incoming *pic-test-stamped*) (held *pic-spt-held*) (c (pic-ajt-initial incoming))
        (obs (pic-ajt-length c)) (d (mv-nth 1 (fn-pic-feed-funded c obs 1))))
  (and (true-listp incoming) (true-listp held) (not (zp 1))
       (fn-pic-observation-okp c (fn-pic-demand c) obs)
       (equal (fn-pic-at 4 obs) (len held))
       (fn-pic-source-pair-contextp d incoming held))) :rule-classes nil)
(defthm pic-spt-producer-incoming-removal-improper
 (let* ((incoming '(97 . 2)) (held *pic-spt-held*) (c (pic-ajt-initial incoming))
        (obs (pic-ajt-length c)) (d (mv-nth 1 (fn-pic-feed-funded c obs 1))))
  (and (not (true-listp incoming)) (true-listp held) (not (zp 1))
       (fn-pic-observation-okp c (fn-pic-demand c) obs)
       (equal (fn-pic-at 4 obs) (len held))
       (not (fn-pic-source-pair-contextp d incoming held)))) :rule-classes nil)
(defthm pic-spt-producer-held-removal-improper
 (let* ((incoming *pic-test-stamped*) (held '(0 . 1)) (c (pic-ajt-initial incoming))
        (obs (list :payload-length (fn-pic-get selected c) (fn-pic-get grant c)
                   (fn-record-payload (fn-pic-get held c)) (len held)))
        (d (mv-nth 1 (fn-pic-feed-funded c obs 1))))
  (and (true-listp incoming) (not (true-listp held)) (not (zp 1))
       (fn-pic-observation-okp c (fn-pic-demand c) obs)
       (equal (fn-pic-at 4 obs) (len held))
       (not (fn-pic-source-pair-contextp d incoming held)))) :rule-classes nil)
(defthm pic-spt-producer-fuel-removal
 (let* ((incoming *pic-test-stamped*) (held *pic-spt-held*) (c (pic-ajt-initial incoming))
        (obs (pic-ajt-length c)) (d (mv-nth 1 (fn-pic-feed-funded c obs 0))))
  (and (true-listp incoming) (true-listp held) (zp 0)
       (fn-pic-observation-okp c (fn-pic-demand c) obs)
       (equal (fn-pic-at 4 obs) (len held))
       (not (fn-pic-source-pair-contextp d incoming held)))) :rule-classes nil)
; Invalid typed authority and wrong extent are distinct observation mutations.
(defthm pic-spt-producer-effect-removal-mutated-tag
 (let* ((incoming *pic-test-stamped*) (held *pic-spt-held*) (c (pic-ajt-initial incoming))
        (obs (update-nth 0 :wrong (pic-ajt-length c))) (d (mv-nth 1 (fn-pic-feed-funded c obs 1))))
  (and (true-listp incoming) (true-listp held) (not (zp 1))
       (not (fn-pic-observation-okp c (fn-pic-demand c) obs))
       (equal (fn-pic-at 4 obs) (len held))
       (not (fn-pic-source-pair-contextp d incoming held)))) :rule-classes nil)
(defthm pic-spt-producer-extent-removal-mutated-length
 (let* ((incoming *pic-test-stamped*) (held *pic-spt-held*) (c (pic-ajt-initial incoming))
        (obs (update-nth 4 146 (pic-ajt-length c))) (d (mv-nth 1 (fn-pic-feed-funded c obs 1))))
  (and (true-listp incoming) (true-listp held) (not (zp 1))
       (fn-pic-observation-okp c (fn-pic-demand c) obs)
       (not (equal (fn-pic-at 4 obs) (len held)))
       (not (fn-pic-source-pair-contextp d incoming held)))) :rule-classes nil)
(defthm pic-spt-source-pair-resumptions-positive
 (let* ((c *pic-ajt-entry*) (obs (pic-ajt-observation c *pic-test-stamped*)))
  (and (fn-pic-source-pair-contextp c *pic-test-stamped* *pic-spt-held*)
       (fn-pic-source-pair-contextp (mv-nth 1 (fn-pic-feed-funded c obs 1)) *pic-test-stamped* *pic-spt-held*)
       (fn-pic-source-pair-contextp (mv-nth 1 (fn-pic-next c 1 *pic-test-stamped*)) *pic-test-stamped* *pic-spt-held*))) :rule-classes nil)
(defthm pic-spt-pair-context-removal-corrupted-held-extent
 (let* ((c (fn-pic-set held-n 146 *pic-ajt-entry*)) (obs (pic-ajt-observation c *pic-test-stamped*)))
  (and (not (fn-pic-source-pair-contextp c *pic-test-stamped* *pic-spt-held*))
       (not (fn-pic-source-pair-contextp (mv-nth 1 (fn-pic-feed-funded c obs 1)) *pic-test-stamped* *pic-spt-held*))
       (not (fn-pic-source-pair-contextp (mv-nth 1 (fn-pic-next c 1 *pic-test-stamped*)) *pic-test-stamped* *pic-spt-held*)))) :rule-classes nil)
(defthm pic-spt-pair-context-removal-corrupted-held-descriptor
 (let ((c (fn-pic-set held-desc '(0 0 146) *pic-ajt-entry*)))
  (and (not (fn-pic-source-pair-contextp c *pic-test-stamped* *pic-spt-held*))
       (not (fn-pic-source-pair-contextp (mv-nth 1 (fn-pic-next c 0 *pic-test-stamped*)) *pic-test-stamped* *pic-spt-held*)))) :rule-classes nil)
(defthm pic-spt-actual-agent-entry-positive
 (let ((d (mv-nth 1 (fn-pic-next *pic-ajt-before* 1 *pic-test-stamped*))))
  (and (fn-pic-source-pair-contextp *pic-ajt-before* *pic-test-stamped* *pic-spt-held*)
       (fn-pic-agent-tracep *pic-ajt-before* *pic-ajt-ticks* *pic-test-stamped*)
       (equal (fn-pic-get phase d) :source-incoming)
       (fn-pic-source-pair-agent-contextp d *pic-test-stamped* *pic-spt-held*))) :rule-classes nil)
(defthm pic-spt-agent-entry-pair-removal-corrupted-extent
 (let* ((c (fn-pic-set held-n 146 *pic-ajt-before*))
        (d (mv-nth 1 (fn-pic-next c 1 *pic-test-stamped*))))
  (and (not (fn-pic-source-pair-contextp c *pic-test-stamped* *pic-spt-held*))
       (fn-pic-agent-tracep c *pic-ajt-ticks* *pic-test-stamped*)
       (equal (fn-pic-get phase d) :source-incoming)
       (not (fn-pic-source-pair-agent-contextp d *pic-test-stamped* *pic-spt-held*)))) :rule-classes nil)
(defthm pic-spt-agent-entry-trace-removal-corrupted-span
 (let* ((p (fn-pic-parser *pic-ajt-before*))
        (c (fn-pic-set parser (fn-psc-set agent-start (+ 1 (fn-psc-get agent-start p)) p) *pic-ajt-before*))
        (d (mv-nth 1 (fn-pic-next c 1 *pic-test-stamped*))))
  (and (fn-pic-source-pair-contextp c *pic-test-stamped* *pic-spt-held*)
       (not (fn-pic-agent-tracep c *pic-ajt-ticks* *pic-test-stamped*))
       (equal (fn-pic-get phase d) :source-incoming)
       (not (fn-pic-source-pair-agent-contextp d *pic-test-stamped* *pic-spt-held*)))) :rule-classes nil)
(defthm pic-spt-agent-entry-phase-removal-pending
 (let ((d (mv-nth 1 (fn-pic-next *pic-ajt-start* 1 *pic-test-stamped*))))
  (and (fn-pic-source-pair-contextp *pic-ajt-start* *pic-test-stamped* *pic-spt-held*)
       (fn-pic-agent-tracep *pic-ajt-start* 0 *pic-test-stamped*)
       (not (equal (fn-pic-get phase d) :source-incoming))
       (not (fn-pic-source-pair-agent-contextp d *pic-test-stamped* *pic-spt-held*)))) :rule-classes nil)
(defthm pic-spt-agent-context-resumptions-positive
 (let* ((c *pic-ajt-entry*) (obs (pic-ajt-observation c *pic-test-stamped*)))
  (and (fn-pic-source-pair-agent-contextp c *pic-test-stamped* *pic-spt-held*)
       (fn-pic-source-pair-agent-contextp (mv-nth 1 (fn-pic-feed-funded c obs 1)) *pic-test-stamped* *pic-spt-held*)
       (fn-pic-source-pair-agent-contextp (mv-nth 1 (fn-pic-next c 1 *pic-test-stamped*)) *pic-test-stamped* *pic-spt-held*))) :rule-classes nil)
(defthm pic-spt-agent-context-removal-corrupted-retained-span
 (let* ((a (fn-pic-get agent *pic-ajt-entry*))
        (c (fn-pic-set agent (list :agent (+ 1 (fn-pic-at 1 a)) (fn-pic-at 2 a)) *pic-ajt-entry*))
        (obs (pic-ajt-observation c *pic-test-stamped*)))
  (and (not (fn-pic-source-pair-agent-contextp c *pic-test-stamped* *pic-spt-held*))
       (not (fn-pic-source-pair-agent-contextp (mv-nth 1 (fn-pic-feed-funded c obs 1)) *pic-test-stamped* *pic-spt-held*))
       (not (fn-pic-source-pair-agent-contextp (mv-nth 1 (fn-pic-next c 1 *pic-test-stamped*)) *pic-test-stamped* *pic-spt-held*)))) :rule-classes nil)
(defun pic-spt-digest-resumptions-positive ()
 (declare (xargs :verify-guards nil))
 (with-local-stobj pgs-digest-state
  (mv-let (ok pgs-digest-state)
   (let ((c (fn-pic-hash-start nil *pic-ajt-entry*)))
    (mv-let (status d left pgs-digest-state) (fn-pic-digest-next c 2 pgs-digest-state)
     (declare (ignore status left))
     (mv (and (fn-pic-source-pair-contextp c *pic-test-stamped* *pic-spt-held*)
              (fn-pic-source-pair-agent-contextp c *pic-test-stamped* *pic-spt-held*)
              (equal (fn-pic-get phase d) :digest-next)
              (fn-pic-source-pair-contextp d *pic-test-stamped* *pic-spt-held*)
              (fn-pic-source-pair-agent-contextp d *pic-test-stamped* *pic-spt-held*)) pgs-digest-state)))
   ok)))
(assert-event (pic-spt-digest-resumptions-positive))
(defthm pic-spt-digest-pair-context-removal-corrupted-extent
 (let ((c (fn-pic-set held-n 146 (fn-pic-hash-start nil *pic-ajt-entry*))))
  (and (not (fn-pic-source-pair-contextp c *pic-test-stamped* *pic-spt-held*))
       (not (fn-pic-source-pair-contextp (mv-nth 1 (fn-pic-digest-next c 1 pgs-digest-state))
                                        *pic-test-stamped* *pic-spt-held*)))) :rule-classes nil)
(defthm pic-spt-digest-agent-context-removal-corrupted-span
 (let* ((a (fn-pic-get agent *pic-ajt-entry*))
        (c (fn-pic-set agent (list :agent (+ 1 (fn-pic-at 1 a)) (fn-pic-at 2 a))
             (fn-pic-hash-start nil *pic-ajt-entry*))))
  (and (not (fn-pic-source-pair-agent-contextp c *pic-test-stamped* *pic-spt-held*))
       (not (fn-pic-source-pair-agent-contextp (mv-nth 1 (fn-pic-digest-next c 1 pgs-digest-state))
                                              *pic-test-stamped* *pic-spt-held*)))) :rule-classes nil)
(defthm pic-spt-derived-choice-context-positive
 (and (fn-pic-source-pair-contextp *pic-ajt-entry* *pic-test-stamped* *pic-spt-held*)
      (<= *fn-rcl-tombstone-fixed* (len *pic-spt-held*))
      (fn-pic-choice-contextp *pic-ajt-entry* *pic-test-stamped* *pic-spt-held*)) :rule-classes nil)
(defthm pic-spt-choice-pair-context-removal-corrupted-extent
 (let ((c (fn-pic-set held-n 146 *pic-ajt-entry*)))
  (and (not (fn-pic-source-pair-contextp c *pic-test-stamped* *pic-spt-held*))
       (<= *fn-rcl-tombstone-fixed* (len *pic-spt-held*))
       (not (fn-pic-choice-contextp c *pic-test-stamped* *pic-spt-held*)))) :rule-classes nil)
(defthm pic-spt-choice-header-removal-short-held
 (let* ((held '(0)) (c (fn-pic-set held-n (len held) *pic-ajt-entry*)))
  (and (fn-pic-source-pair-contextp c *pic-test-stamped* held)
       (not (<= *fn-rcl-tombstone-fixed* (len held)))
       (not (fn-pic-choice-contextp c *pic-test-stamped* held)))) :rule-classes nil)
(defthm pic-spt-current-agent-choice-positive
 (let* ((c (fn-pic-set incoming-desc '(0 0 0) *pic-ajt-entry*))
        (held (pic-test-tomb 1 (make-list 32 :initial-element 0)
                              (make-list 32 :initial-element 0) '(97 98 99))))
  (and (fn-pic-agent-contextp c *pic-test-stamped*)
       (fn-pic-retained-source-choicep c *pic-test-stamped* held)
       (equal (fn-pic-retained-source-choicep c *pic-test-stamped* held)
        (and (fn-rcl-tomb-sourcep held) (fn-pic-get incoming-desc c)
             (equal (fn-pb-path-agent *pic-test-stamped* (fn-record-string-octets (fn-pic-get msgid c)))
                    (fn-rcl-tomb-agent held)))))) :rule-classes nil)
(defthm pic-spt-current-agent-choice-removal-corrupted-span
 (let* ((a (fn-pic-get agent *pic-ajt-entry*))
        (c (fn-pic-set incoming-desc '(0 0 0)
             (fn-pic-set agent (list :agent (+ 1 (fn-pic-at 1 a)) (fn-pic-at 2 a)) *pic-ajt-entry*)))
        (held (pic-test-tomb 1 (make-list 32 :initial-element 0)
                              (make-list 32 :initial-element 0) '(98 99))))
  (and (not (fn-pic-agent-contextp c *pic-test-stamped*))
       (fn-pic-retained-source-choicep c *pic-test-stamped* held)
       (not (equal (fn-pic-retained-source-choicep c *pic-test-stamped* held)
        (and (fn-rcl-tomb-sourcep held) (fn-pic-get incoming-desc c)
             (equal (fn-pb-path-agent *pic-test-stamped* (fn-record-string-octets (fn-pic-get msgid c)))
                    (fn-rcl-tomb-agent held))))))) :rule-classes nil)
