(in-package "ACL2")
(include-book "../../books/post-identity-captured-hash-choice")
(include-book "post-identity-captured-tests")
(defun pic-cht-before-flag (c incoming held fuel)
 (declare (xargs :measure (nfix fuel) :verify-guards nil))
 (if (or (zp fuel) (equal (fn-pic-get phase c) :tomb-flag)
         (equal (fn-pic-get phase c) :done)) c
  (pic-cht-before-flag (pic-test-drive c incoming held 1) incoming held (1- fuel))))
(defun pic-cht-flag (incoming held)
 (declare (xargs :verify-guards nil))
 (pic-cht-before-flag
  (fn-pic-begin *pic-test-selected* *pic-test-grant*
   (pic-test-held "<m>" nil *pic-test-binding*) *pic-test-incoming*
   (len incoming) "<m>" *pic-test-binding* nil) incoming held 3000))
(defun pic-cht-observation (c byte)
 (list :payload-byte (fn-pic-get selected c) (fn-pic-get grant c) 0
  (fn-pic-at 1 (fn-pic-demand c)) byte))
(defconst *pic-cht-held* (pic-test-tomb 1 *pic-test-abc-hash* *pic-test-abc-hash* '(97 98 99)))
(defun pic-cht-start (incoming held)
 (declare (xargs :verify-guards nil))
 (pic-test-drive (pic-cht-flag incoming held) incoming held 1))
(defthm pic-cht-entry-positive-source-agent-candidate
 (let* ((c (pic-cht-flag *pic-test-stamped* *pic-cht-held*))
        (obs (pic-cht-observation c 1)) (next (mv-nth 1 (fn-pic-feed-funded c obs 1))))
  (and (fn-pic-choice-contextp c *pic-test-stamped* *pic-cht-held*)
       (equal (fn-pic-get phase c) :tomb-flag)
       (fn-pic-choice-observationp c obs *pic-test-stamped* *pic-cht-held*)
       (member-eq (fn-pic-get phase next) '(:tomb-agent-held :digest-begin))
       (fn-pic-choice-outcomep next *pic-test-stamped* *pic-cht-held*)
       (fn-pic-choice-productp next *pic-test-stamped* *pic-cht-held*)
       (equal (fn-pic-get pos next) 0))) :rule-classes nil)
(defthm pic-cht-entry-positive-whole-flag
 (let* ((held (update-nth 8 0 *pic-cht-held*)) (c (pic-cht-flag *pic-test-stamped* held))
        (obs (pic-cht-observation c 0)) (next (mv-nth 1 (fn-pic-feed-funded c obs 1))))
  (and (fn-pic-choice-contextp c *pic-test-stamped* held)
       (equal (fn-pic-get phase c) :tomb-flag) (fn-pic-choice-observationp c obs *pic-test-stamped* held)
       (member-eq (fn-pic-get phase next) '(:tomb-agent-held :digest-begin))
       (fn-pic-choice-outcomep next *pic-test-stamped* held)
       (equal (fn-pic-get digest-base next) 9) (equal (fn-pic-get digest-desc next) '(0 0 0)))) :rule-classes nil)
(defthm pic-cht-entry-positive-missing-inverse
 (let* ((c (pic-cht-flag '(97 98 99) *pic-cht-held*))
        (obs (pic-cht-observation c 1)) (next (mv-nth 1 (fn-pic-feed-funded c obs 1))))
  (and (fn-pic-choice-contextp c '(97 98 99) *pic-cht-held*)
       (equal (fn-pic-get phase c) :tomb-flag) (fn-pic-choice-observationp c obs '(97 98 99) *pic-cht-held*)
       (not (fn-pic-get incoming-desc c))
       (member-eq (fn-pic-get phase next) '(:tomb-agent-held :digest-begin))
       (fn-pic-choice-outcomep next '(97 98 99) *pic-cht-held*)
       (equal (fn-pic-get digest-base next) 9))) :rule-classes nil)
(defthm pic-cht-entry-positive-agent-length-mismatch
 (let* ((held (append *pic-cht-held* '(100))) (c (pic-cht-flag *pic-test-stamped* held))
        (obs (pic-cht-observation c 1)) (next (mv-nth 1 (fn-pic-feed-funded c obs 1))))
  (and (fn-pic-choice-contextp c *pic-test-stamped* held)
       (equal (fn-pic-get phase c) :tomb-flag) (fn-pic-choice-observationp c obs *pic-test-stamped* held)
       (member-eq (fn-pic-get phase next) '(:tomb-agent-held :digest-begin))
       (fn-pic-choice-outcomep next *pic-test-stamped* held)
       (equal (fn-pic-get digest-base next) 9))) :rule-classes nil)
(defthm pic-cht-feedback-positive-held-cache
 (let* ((c (pic-cht-start *pic-test-stamped* *pic-cht-held*)) (obs (pic-cht-observation c 97))
        (next (mv-nth 1 (fn-pic-feed-funded c obs 1))))
  (and (fn-pic-choice-productp c *pic-test-stamped* *pic-cht-held*)
       (fn-pic-choice-observationp c obs *pic-test-stamped* *pic-cht-held*)
       (fn-pic-choice-outcomep next *pic-test-stamped* *pic-cht-held*)
       (equal (fn-pic-get phase next) :tomb-agent-incoming) (equal (fn-pic-get cached next) 97))) :rule-classes nil)
(defthm pic-cht-read-positive-incoming-prefix
 (let* ((c (pic-test-drive (pic-cht-start *pic-test-stamped* *pic-cht-held*) *pic-test-stamped* *pic-cht-held* 1))
        (next (mv-nth 1 (fn-pic-next c 2 *pic-test-stamped*))))
  (and (fn-pic-choice-productp c *pic-test-stamped* *pic-cht-held*)
       (fn-cbor-octet-listp *pic-test-stamped*)
       (fn-pic-choice-outcomep next *pic-test-stamped* *pic-cht-held*)
       (equal (fn-pic-get phase next) :tomb-agent-held) (equal (fn-pic-get pos next) 1))) :rule-classes nil)
(defthm pic-cht-read-positive-full-agent-source-choice
 (let* ((c (pic-test-drive (pic-cht-start *pic-test-stamped* *pic-cht-held*) *pic-test-stamped* *pic-cht-held* 6))
        (next (mv-nth 1 (fn-pic-next c 1 *pic-test-stamped*))))
  (and (fn-pic-choice-productp c *pic-test-stamped* *pic-cht-held*)
       (fn-cbor-octet-listp *pic-test-stamped*) (fn-pic-choice-observationp c :control *pic-test-stamped* *pic-cht-held*)
       (fn-pic-choice-outcomep next *pic-test-stamped* *pic-cht-held*)
       (equal (fn-pic-get phase next) :digest-begin) (equal (fn-pic-get digest-base next) 41)
       (equal (fn-pic-get digest-desc next) (fn-pic-get incoming-desc c)))) :rule-classes nil)
(defthm pic-cht-read-positive-agent-byte-mismatch
 (let* ((held (update-nth 147 100 *pic-cht-held*))
        (c (pic-test-drive (pic-cht-start *pic-test-stamped* held) *pic-test-stamped* held 5))
        (next (mv-nth 1 (fn-pic-next c 2 *pic-test-stamped*))))
  (and (fn-pic-choice-productp c *pic-test-stamped* held) (fn-cbor-octet-listp *pic-test-stamped*)
       (fn-pic-choice-outcomep next *pic-test-stamped* held)
       (equal (fn-pic-get phase next) :digest-begin) (equal (fn-pic-get digest-base next) 9))) :rule-classes nil)
; Corrupted continuation skips a mismatching suffix; exact control and input domain remain.
(defthm pic-cht-product-removal-corrupted-skipped-prefix
 (let* ((held (update-nth 147 100 *pic-cht-held*))
        (c (fn-pic-set pos 3 (pic-cht-start *pic-test-stamped* held)))
        (a (mv-nth 1 (fn-pic-feed-funded c :control 1))) (b (mv-nth 1 (fn-pic-next c 1 *pic-test-stamped*))))
  (and (not (fn-pic-choice-productp c *pic-test-stamped* held))
       (fn-pic-choice-observationp c :control *pic-test-stamped* held) (fn-cbor-octet-listp *pic-test-stamped*)
       (not (fn-pic-choice-outcomep a *pic-test-stamped* held))
       (not (fn-pic-choice-outcomep b *pic-test-stamped* held)))) :rule-classes nil)
; Mutated byte retains the typed token effect but corrupts the cached semantic observation.
(defthm pic-cht-observation-removal-mutated-held-byte
 (let* ((c (pic-cht-start *pic-test-stamped* *pic-cht-held*)) (obs (pic-cht-observation c 100))
        (next (mv-nth 1 (fn-pic-feed-funded c obs 1))))
  (and (fn-pic-choice-productp c *pic-test-stamped* *pic-cht-held*)
       (fn-pic-observation-okp c (fn-pic-demand c) obs)
       (not (fn-pic-choice-observationp c obs *pic-test-stamped* *pic-cht-held*))
       (not (fn-pic-choice-outcomep next *pic-test-stamped* *pic-cht-held*)))) :rule-classes nil)
; Unsupported logical octet domain; no authorized mutation of a sealed native buffer is asserted.
(defthm pic-cht-octet-domain-removal-mutated-logical-input
 (let* ((c (pic-test-drive (pic-cht-start *pic-test-stamped* *pic-cht-held*) *pic-test-stamped* *pic-cht-held* 1))
        (incoming (update-nth (fn-pic-at 1 (fn-pic-get agent c)) 256 *pic-test-stamped*))
        (next (mv-nth 1 (fn-pic-next c 2 incoming))))
  (and (fn-pic-choice-productp c incoming *pic-cht-held*) (not (fn-cbor-octet-listp incoming))
       (not (fn-pic-choice-outcomep next incoming *pic-cht-held*)))) :rule-classes nil)
; Corrupted captured extent routes equal actual agents to a whole-hash comparison.
(defthm pic-cht-entry-context-removal-corrupted-held-extent
 (let* ((c (fn-pic-set held-n 147 (pic-cht-flag *pic-test-stamped* *pic-cht-held*)))
        (obs (pic-cht-observation c 1)) (next (mv-nth 1 (fn-pic-feed-funded c obs 1))))
  (and (not (fn-pic-choice-contextp c *pic-test-stamped* *pic-cht-held*))
       (equal (fn-pic-get phase c) :tomb-flag) (fn-pic-choice-observationp c obs *pic-test-stamped* *pic-cht-held*)
       (member-eq (fn-pic-get phase next) '(:tomb-agent-held :digest-begin))
       (not (fn-pic-choice-outcomep next *pic-test-stamped* *pic-cht-held*)))) :rule-classes nil)
; Mutated flag effect passes typed authority but contradicts the actual tombstone flag.
(defthm pic-cht-entry-observation-removal-mutated-flag
 (let* ((c (pic-cht-flag *pic-test-stamped* *pic-cht-held*)) (obs (pic-cht-observation c 0))
        (next (mv-nth 1 (fn-pic-feed-funded c obs 1))))
  (and (fn-pic-choice-contextp c *pic-test-stamped* *pic-cht-held*)
       (equal (fn-pic-get phase c) :tomb-flag) (fn-pic-observation-okp c (fn-pic-demand c) obs)
       (not (fn-pic-choice-observationp c obs *pic-test-stamped* *pic-cht-held*))
       (member-eq (fn-pic-get phase next) '(:tomb-agent-held :digest-begin))
       (not (fn-pic-choice-outcomep next *pic-test-stamped* *pic-cht-held*)))) :rule-classes nil)
; Wrong entry phase leaves an already corrupt agent continuation unchanged at zero fuel.
(defthm pic-cht-entry-phase-removal-corrupted-existing-prefix
 (let* ((held (update-nth 147 100 *pic-cht-held*))
        (c (fn-pic-set pos 3 (pic-cht-start *pic-test-stamped* held)))
        (next (mv-nth 1 (fn-pic-feed-funded c :control 0))))
  (and (fn-pic-choice-contextp c *pic-test-stamped* held)
       (not (equal (fn-pic-get phase c) :tomb-flag)) (fn-pic-choice-observationp c :control *pic-test-stamped* held)
       (member-eq (fn-pic-get phase next) '(:tomb-agent-held :digest-begin))
       (not (fn-pic-choice-outcomep next *pic-test-stamped* held)))) :rule-classes nil)
