(in-package "ACL2")
(include-book "../../books/post-identity-source-cursor-info")

(defthm fn-psc-info-plain-literal
 (let* ((incoming (fn-inj-injection-info-line '(97 98 99)))
        (begin (fn-psc-begin :agent (len incoming) "" nil (len incoming)))
        (c (fn-psc-model-byte-run 42 begin incoming nil))
        (a (fn-psc-get pos c)) (line (fn-pb-line (nthcdr a incoming)))
        (prefix (fn-pb-upto-semicolon line))
        (end (+ a (if (equal prefix :no) (- (len line) 2) (len prefix))))
        (agent (fn-pb-info-line-agent (nthcdr (fn-psc-get base c) incoming)))
        (d (fn-psc-model-info-agent-complete c incoming)))
  (and (fn-psc-info-agent-statep c incoming)
       (equal agent '(97 98 99))
       (equal (fn-psc-result d) (if agent (list :agent a end) :no-source))
       (implies agent (equal (fn-inj-take (- end a) (nthcdr a incoming)) agent))
       (equal d (fn-psc-model-byte-run (fn-psc-model-info-agent-cost c incoming) c incoming nil))))
 :rule-classes nil)

(defthm fn-psc-info-parameters-literal
 (let* ((incoming (append *fn-inj-injection-info-field* '(97 98 99 59 120 61 121 13 10)))
        (begin (fn-psc-begin :agent (len incoming) "" nil (len incoming)))
        (c (fn-psc-model-byte-run 42 begin incoming nil))
        (a (fn-psc-get pos c)) (line (fn-pb-line (nthcdr a incoming)))
        (prefix (fn-pb-upto-semicolon line))
        (end (+ a (if (equal prefix :no) (- (len line) 2) (len prefix))))
        (agent (fn-pb-info-line-agent (nthcdr (fn-psc-get base c) incoming)))
        (d (fn-psc-model-info-agent-complete c incoming)))
  (and (fn-psc-info-agent-statep c incoming)
       (equal agent '(97 98 99))
       (equal (fn-psc-result d) (if agent (list :agent a end) :no-source))
       (implies agent (equal (fn-inj-take (- end a) (nthcdr a incoming)) agent))
       (equal d (fn-psc-model-byte-run (fn-psc-model-info-agent-cost c incoming) c incoming nil))))
 :rule-classes nil)

(defthm fn-psc-info-malformed-literal
 (let* ((incoming (append *fn-inj-injection-info-field* '(97 98 99 13 88 10)))
        (begin (fn-psc-begin :agent (len incoming) "" nil (len incoming)))
        (c (fn-psc-model-byte-run 42 begin incoming nil))
        (a (fn-psc-get pos c)) (line (fn-pb-line (nthcdr a incoming)))
        (prefix (fn-pb-upto-semicolon line))
        (end (+ a (if (equal prefix :no) (- (len line) 2) (len prefix))))
        (agent (fn-pb-info-line-agent (nthcdr (fn-psc-get base c) incoming)))
        (d (fn-psc-model-info-agent-complete c incoming)))
  (and (fn-psc-info-agent-statep c incoming)
       (equal agent nil)
       (equal (fn-psc-result d) (if agent (list :agent a end) :no-source))
       (implies agent (equal (fn-inj-take (- end a) (nthcdr a incoming)) agent))
       (equal d (fn-psc-model-byte-run (fn-psc-model-info-agent-cost c incoming) c incoming nil))))
 :rule-classes nil)

(defthm fn-psc-info-empty-prefix-literal
 (let* ((incoming (append *fn-inj-injection-info-field* '(59 120 61 121 13 10)))
        (begin (fn-psc-begin :agent (len incoming) "" nil (len incoming)))
        (c (fn-psc-model-byte-run 42 begin incoming nil))
        (a (fn-psc-get pos c)) (line (fn-pb-line (nthcdr a incoming)))
        (prefix (fn-pb-upto-semicolon line))
        (end (+ a (if (equal prefix :no) (- (len line) 2) (len prefix))))
        (agent (fn-pb-info-line-agent (nthcdr (fn-psc-get base c) incoming)))
        (d (fn-psc-model-info-agent-complete c incoming)))
  (and (fn-psc-info-agent-statep c incoming)
       (equal agent nil)
       (equal (fn-psc-result d) (if agent (list :agent a end) :no-source))
       (implies agent (equal (fn-inj-take (- end a) (nthcdr a incoming)) agent))
       (equal d (fn-psc-model-byte-run (fn-psc-model-info-agent-cost c incoming) c incoming nil))))
 :rule-classes nil)

; Corrupted-state hypothesis removal: exact extent alone fails.
(defthm fn-psc-info-source-extent-removal
 (let* ((incoming (fn-inj-injection-info-line '(97 98 99)))
        (begin (fn-psc-begin :agent (len incoming) "" nil (len incoming)))
        (good (fn-psc-model-byte-run 42 begin incoming nil))
        (c (fn-psc-set n 16 good))
        (a (fn-psc-get pos c)) (line (fn-pb-line (nthcdr a incoming)))
        (prefix (fn-pb-upto-semicolon line))
        (end (+ a (if (equal prefix :no) (- (len line) 2) (len prefix))))
        (agent (fn-pb-info-line-agent (nthcdr (fn-psc-get base c) incoming)))
        (d (fn-psc-model-info-agent-complete c incoming)))
  (and (equal (fn-psc-get mode c) :agent) (equal (fn-psc-get phase c) :control)
       (equal (fn-psc-get resume c) :agent-info-field) (fn-psc-get ok c)
       (true-listp incoming) (not (equal (fn-psc-get n c) (len incoming)))
       (natp a) (<= a (len incoming)) (natp (fn-psc-get base c))
       (equal a (+ 16 (fn-psc-get base c)))
       (not (equal (fn-inj-strip *fn-inj-injection-info-field* (nthcdr (fn-psc-get base c) incoming)) :no))
       (not (and (equal (fn-psc-result d) (if agent (list :agent a end) :no-source))
                 (implies agent (equal (fn-inj-take (- end a) (nthcdr a incoming)) agent))))))
 :rule-classes nil)
