(in-package "ACL2")

(include-book "../../books/post-identity-source-cursor-source-after-path")

(defthm fn-psc-source-after-path-simple-incoming-literal
 (let* ((xs (fn-inj-injection-info-line '(97))) (incoming xs) (held nil)
        (c (fn-psc-begin :source-incoming (len xs) "<a@b>" '(:agent 16 17) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal p 19) (equal (fn-psc-get phase d) (if p :control :done))
       (implies p (and (equal (fn-psc-get resume d) :source-found) (equal (fn-psc-get pos d) p) (fn-psc-get ok d)))
       (implies (not p) (equal (fn-psc-result d) :no-source)) (fn-psc-source-contextp d incoming held)
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-after-path-cost 0 c incoming held)
                  (fn-psc-literal 0 *fn-inj-injection-date-field* :source-stamp c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-after-path-simple-held-literal
 (let* ((xs (fn-inj-injection-info-line '(97))) (incoming '(97)) (held xs)
        (c (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal p 19) (equal (fn-psc-get phase d) (if p :control :done))
       (implies p (and (equal (fn-psc-get resume d) :source-found) (equal (fn-psc-get pos d) p) (fn-psc-get ok d)))
       (implies (not p) (equal (fn-psc-result d) :no-source)) (fn-psc-source-contextp d incoming held)
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-after-path-cost 0 c incoming held)
                  (fn-psc-literal 0 *fn-inj-injection-date-field* :source-stamp c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-after-path-stamp-incoming-literal
 (let* ((xs (append (fn-inj-injection-date-line (make-list 31 :initial-element 48)) (fn-inj-injection-info-line '(97)))) (incoming xs) (held nil)
        (c (fn-psc-begin :source-incoming (len xs) "<a@b>" '(:agent 65 66) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal p 68) (equal (fn-psc-get phase d) (if p :control :done))
       (implies p (and (equal (fn-psc-get resume d) :source-found) (equal (fn-psc-get pos d) p) (fn-psc-get ok d)))
       (implies (not p) (equal (fn-psc-result d) :no-source)) (fn-psc-source-contextp d incoming held)
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-after-path-cost 0 c incoming held)
                  (fn-psc-literal 0 *fn-inj-injection-date-field* :source-stamp c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-after-path-stamp-held-literal
 (let* ((xs (append (fn-inj-injection-date-line (make-list 31 :initial-element 48)) (fn-inj-injection-info-line '(97)))) (incoming '(97)) (held xs)
        (c (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal p 68) (equal (fn-psc-get phase d) (if p :control :done))
       (implies p (and (equal (fn-psc-get resume d) :source-found) (equal (fn-psc-get pos d) p) (fn-psc-get ok d)))
       (implies (not p) (equal (fn-psc-result d) :no-source)) (fn-psc-source-contextp d incoming held)
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-after-path-cost 0 c incoming held)
                  (fn-psc-literal 0 *fn-inj-injection-date-field* :source-stamp c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-after-path-v2-held-literal
 (let* ((xs (append (fn-inj-injection-date-line (make-list 31 :initial-element 48)) (fn-inj-message-id-line (fn-record-string-octets "<a@b>")) (fn-inj-date-line (make-list 31 :initial-element 48)) (fn-inj-injection-info-line '(97)))) (incoming '(97)) (held xs)
        (c (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal p 126) (equal (fn-psc-get phase d) (if p :control :done))
       (implies p (and (equal (fn-psc-get resume d) :source-found) (equal (fn-psc-get pos d) p) (fn-psc-get ok d)))
       (implies (not p) (equal (fn-psc-result d) :no-source)) (fn-psc-source-contextp d incoming held)
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-after-path-cost 0 c incoming held)
                  (fn-psc-literal 0 *fn-inj-injection-date-field* :source-stamp c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-after-path-v1-ambiguity-literal
 (let* ((xs (append (fn-inj-injection-date-line (make-list 31 :initial-element 48)) (fn-inj-injection-info-line '(97)) (fn-inj-message-id-line (fn-record-string-octets "<a@b>")))) (incoming '(97)) (held xs)
        (c (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal p nil) (equal (fn-psc-get phase d) (if p :control :done))
       (implies p (and (equal (fn-psc-get resume d) :source-found) (equal (fn-psc-get pos d) p) (fn-psc-get ok d)))
       (implies (not p) (equal (fn-psc-result d) :no-source)) (fn-psc-source-contextp d incoming held)
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-after-path-cost 0 c incoming held)
                  (fn-psc-literal 0 *fn-inj-injection-date-field* :source-stamp c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-after-path-short-date-literal
 (let* ((xs (append *fn-inj-injection-date-field* '(48 13 10))) (incoming '(97)) (held xs)
        (c (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal p nil) (equal (fn-psc-get phase d) (if p :control :done))
       (implies p (and (equal (fn-psc-get resume d) :source-found) (equal (fn-psc-get pos d) p) (fn-psc-get ok d)))
       (implies (not p) (equal (fn-psc-result d) :no-source)) (fn-psc-source-contextp d incoming held)
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-after-path-cost 0 c incoming held)
                  (fn-psc-literal 0 *fn-inj-injection-date-field* :source-stamp c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-after-path-bad-crlf-literal
 (let* ((xs (append *fn-inj-injection-date-field* (make-list 31 :initial-element 48) '(13 11) (fn-inj-injection-info-line '(97)))) (incoming '(97)) (held xs)
        (c (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal p nil) (equal (fn-psc-get phase d) (if p :control :done))
       (implies p (and (equal (fn-psc-get resume d) :source-found) (equal (fn-psc-get pos d) p) (fn-psc-get ok d)))
       (implies (not p) (equal (fn-psc-result d) :no-source)) (fn-psc-source-contextp d incoming held)
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-after-path-cost 0 c incoming held)
                  (fn-psc-literal 0 *fn-inj-injection-date-field* :source-stamp c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-after-path-stamp-eof-literal
 (let* ((xs (append *fn-inj-injection-date-field* (make-list 31 :initial-element 48))) (incoming '(97)) (held xs)
        (c (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal p nil) (equal (fn-psc-get phase d) (if p :control :done))
       (implies p (and (equal (fn-psc-get resume d) :source-found) (equal (fn-psc-get pos d) p) (fn-psc-get ok d)))
       (implies (not p) (equal (fn-psc-result d) :no-source)) (fn-psc-source-contextp d incoming held)
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-after-path-cost 0 c incoming held)
                  (fn-psc-literal 0 *fn-inj-injection-date-field* :source-stamp c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-after-path-info-eof-literal
 (let* ((xs (append *fn-inj-injection-info-field* '(97))) (incoming '(97)) (held xs)
        (c (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal p nil) (equal (fn-psc-get phase d) (if p :control :done))
       (implies p (and (equal (fn-psc-get resume d) :source-found) (equal (fn-psc-get pos d) p) (fn-psc-get ok d)))
       (implies (not p) (equal (fn-psc-result d) :no-source)) (fn-psc-source-contextp d incoming held)
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-after-path-cost 0 c incoming held)
                  (fn-psc-literal 0 *fn-inj-injection-date-field* :source-stamp c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-after-path-params-held-literal
 (let* ((xs (append (fn-inj-injection-date-line (make-list 31 :initial-element 48)) *fn-inj-injection-info-field* '(97 59 120 13 10))) (incoming '(97)) (held xs)
        (c (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal p 70) (equal (fn-psc-get phase d) (if p :control :done))
       (implies p (and (equal (fn-psc-get resume d) :source-found) (equal (fn-psc-get pos d) p) (fn-psc-get ok d)))
       (implies (not p) (equal (fn-psc-result d) :no-source)) (fn-psc-source-contextp d incoming held)
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-after-path-cost 0 c incoming held)
                  (fn-psc-literal 0 *fn-inj-injection-date-field* :source-stamp c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-after-path-params-eof-literal
 (let* ((xs (append (fn-inj-injection-date-line (make-list 31 :initial-element 48)) *fn-inj-injection-info-field* '(97 59 120))) (incoming '(97)) (held xs)
        (c (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal p nil) (equal (fn-psc-get phase d) (if p :control :done))
       (implies p (and (equal (fn-psc-get resume d) :source-found) (equal (fn-psc-get pos d) p) (fn-psc-get ok d)))
       (implies (not p) (equal (fn-psc-result d) :no-source)) (fn-psc-source-contextp d incoming held)
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-after-path-cost 0 c incoming held)
                  (fn-psc-literal 0 *fn-inj-injection-date-field* :source-stamp c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-after-path-empty-agent-literal
 (let* ((xs (append (fn-inj-injection-date-line (make-list 31 :initial-element 48)) (fn-inj-injection-info-line nil))) (incoming nil) (held xs)
        (c (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 0) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal p 67) (equal (fn-psc-get phase d) (if p :control :done))
       (implies p (and (equal (fn-psc-get resume d) :source-found) (equal (fn-psc-get pos d) p) (fn-psc-get ok d)))
       (implies (not p) (equal (fn-psc-result d) :no-source)) (fn-psc-source-contextp d incoming held)
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-after-path-cost 0 c incoming held)
                  (fn-psc-literal 0 *fn-inj-injection-date-field* :source-stamp c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-after-path-garbage-literal
 (let* ((xs '(97 98 99)) (incoming '(97)) (held xs)
        (c (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal p nil) (equal (fn-psc-get phase d) (if p :control :done))
       (implies p (and (equal (fn-psc-get resume d) :source-found) (equal (fn-psc-get pos d) p) (fn-psc-get ok d)))
       (implies (not p) (equal (fn-psc-result d) :no-source)) (fn-psc-source-contextp d incoming held)
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-after-path-cost 0 c incoming held)
                  (fn-psc-literal 0 *fn-inj-injection-date-field* :source-stamp c) incoming held))))
 :rule-classes nil)
(defthm fn-psc-source-after-path-extent-hypothesis-removal
 (let* ((incoming '(97)) (held (fn-inj-injection-info-line '(97)))
        (c (fn-psc-begin :source-held 0 "<a@b>" '(:agent 0 1) (len incoming)))
        (p (fn-pbb-source-after-path 0 (fn-psc-model-retained-agent c incoming)
             (fn-record-string-octets (fn-psc-get msgid c)) (fn-psc-model-source c incoming held)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (not (fn-psc-source-contextp c incoming held)) (equal p 19)
       (not (equal (fn-psc-get phase d) (if p :control :done)))
       (equal (fn-psc-result d) :no-source)))
 :rule-classes nil)
