; Actual source parser boundary teeth; mutations are logical corruptions.
(in-package "ACL2")
(include-book "../../books/post-identity-captured-source-parser-context")
(include-book "post-identity-captured-source-pair-context-tests")
(defthm pic-sxt-begin-shape-positive
 (and (fn-pic-agent-shapep (pic-ajt-initial *pic-test-stamped*))
      (fn-pic-agent-shapep
       (fn-pic-begin *pic-test-selected* *pic-test-grant* nil *pic-test-incoming*
                    (len *pic-test-stamped*) "<m>" nil nil))) :rule-classes nil)
(defconst *pic-sxt-improper-agent*
 (let ((a (fn-pic-get agent *pic-ajt-entry*)))
  (list* :agent (fn-pic-at 1 a) (fn-pic-at 2 a) 1)))
(defconst *pic-sxt-corrupt* (fn-pic-set agent *pic-sxt-improper-agent* *pic-ajt-entry*))
(defthm pic-sxt-shape-carry-positive
 (let* ((c *pic-ajt-entry*) (obs (pic-ajt-observation c *pic-test-stamped*)))
  (and (fn-pic-agent-shapep c)
       (fn-pic-agent-shapep (mv-nth 1 (fn-pic-feed-funded c obs 1)))
       (fn-pic-agent-shapep (mv-nth 1 (fn-pic-next c 1 *pic-test-stamped*))))) :rule-classes nil)
(defthm pic-sxt-shape-removal-corrupted-improper-agent
 (let ((c *pic-sxt-corrupt*))
  (and (not (fn-pic-agent-shapep c))
       (not (fn-pic-agent-shapep (mv-nth 1 (fn-pic-feed-funded c :control 0))))
       (not (fn-pic-agent-shapep (mv-nth 1 (fn-pic-next c 0 *pic-test-stamped*)))))) :rule-classes nil)
(defthm pic-sxt-source-incoming-start-positive
 (let* ((c *pic-ajt-entry*) (d (fn-pic-start-parser :source-incoming :source-incoming c)) (p (fn-pic-parser d)))
  (and (fn-pic-source-pair-agent-contextp c *pic-test-stamped* *pic-spt-held*)
       (fn-pic-agent-shapep c) (member-eq :source-incoming '(:source-incoming :source-held))
       (fn-psc-source-contextp p *pic-test-stamped* *pic-spt-held*)
       (equal (fn-psc-model-retained-agent p *pic-test-stamped*)
              (fn-pb-path-agent *pic-test-stamped* (fn-record-string-octets (fn-pic-get msgid c)))))) :rule-classes nil)
(defthm pic-sxt-source-held-start-positive
 (let* ((c *pic-ajt-entry*) (d (fn-pic-start-parser :source-held :source-held c)) (p (fn-pic-parser d)))
  (and (fn-pic-source-pair-agent-contextp c *pic-test-stamped* *pic-spt-held*)
       (fn-pic-agent-shapep c) (member-eq :source-held '(:source-incoming :source-held))
       (fn-psc-source-contextp p *pic-test-stamped* *pic-spt-held*)
       (equal (fn-psc-model-retained-agent p *pic-test-stamped*)
              (fn-pb-path-agent *pic-test-stamped* (fn-record-string-octets (fn-pic-get msgid c)))))) :rule-classes nil)
(defthm pic-sxt-source-start-shape-removal-improper-agent
 (let* ((c *pic-sxt-corrupt*) (d (fn-pic-start-parser :source-held :source-held c)) (p (fn-pic-parser d)))
  (and (fn-pic-source-pair-agent-contextp c *pic-test-stamped* *pic-spt-held*)
       (not (fn-pic-agent-shapep c)) (member-eq :source-held '(:source-incoming :source-held))
       (not (and (fn-psc-source-contextp p *pic-test-stamped* *pic-spt-held*)
        (equal (fn-psc-model-retained-agent p *pic-test-stamped*)
               (fn-pb-path-agent *pic-test-stamped* (fn-record-string-octets (fn-pic-get msgid c)))))))) :rule-classes nil)
(defthm pic-sxt-source-start-context-removal-corrupted-held-extent
 (let* ((c (fn-pic-set held-n 146 *pic-ajt-entry*))
        (d (fn-pic-start-parser :source-held :source-held c)) (p (fn-pic-parser d)))
  (and (not (fn-pic-source-pair-agent-contextp c *pic-test-stamped* *pic-spt-held*))
       (fn-pic-agent-shapep c) (member-eq :source-held '(:source-incoming :source-held))
       (not (and (fn-psc-source-contextp p *pic-test-stamped* *pic-spt-held*)
        (equal (fn-psc-model-retained-agent p *pic-test-stamped*)
               (fn-pb-path-agent *pic-test-stamped* (fn-record-string-octets (fn-pic-get msgid c)))))))) :rule-classes nil)
; Direct helper domain mutation; :agent is not a source callback mode.
(defthm pic-sxt-source-start-mode-removal-corrupted-call
 (let* ((c *pic-ajt-entry*) (d (fn-pic-start-parser :agent :agent c)) (p (fn-pic-parser d)))
  (and (fn-pic-source-pair-agent-contextp c *pic-test-stamped* *pic-spt-held*)
       (fn-pic-agent-shapep c) (not (member-eq :agent '(:source-incoming :source-held)))
       (not (and (fn-psc-source-contextp p *pic-test-stamped* *pic-spt-held*)
        (equal (fn-psc-model-retained-agent p *pic-test-stamped*)
               (fn-pb-path-agent *pic-test-stamped* (fn-record-string-octets (fn-pic-get msgid c)))))))) :rule-classes nil)
(defthm pic-sxt-actual-readonly-parser-entry-positive
 (let* ((d (mv-nth 1 (fn-pic-next *pic-ajt-before* 1 *pic-test-stamped*))) (p (fn-pic-parser d)))
  (and (fn-pic-agent-tracep *pic-ajt-before* *pic-ajt-ticks* *pic-test-stamped*)
       (equal (fn-pic-get phase d) :source-incoming)
       (fn-psc-source-contextp p *pic-test-stamped* *pic-spt-held*)
       (equal (fn-psc-model-retained-agent p *pic-test-stamped*)
        (fn-pb-path-agent *pic-test-stamped* (fn-record-string-octets (fn-pic-get msgid d)))))) :rule-classes nil)
(defthm pic-sxt-actual-entry-trace-removal-corrupted-span
 (let* ((p (fn-pic-parser *pic-ajt-before*))
        (c (fn-pic-set parser (fn-psc-set agent-start (+ 1 (fn-psc-get agent-start p)) p) *pic-ajt-before*))
        (d (mv-nth 1 (fn-pic-next c 1 *pic-test-stamped*))) (q (fn-pic-parser d)))
  (and (not (fn-pic-agent-tracep c *pic-ajt-ticks* *pic-test-stamped*))
       (equal (fn-pic-get phase d) :source-incoming)
       (not (and (fn-psc-source-contextp q *pic-test-stamped* *pic-spt-held*)
        (equal (fn-psc-model-retained-agent q *pic-test-stamped*)
         (fn-pb-path-agent *pic-test-stamped* (fn-record-string-octets (fn-pic-get msgid d)))))))) :rule-classes nil)
(defthm pic-sxt-actual-entry-phase-removal-pending
 (let* ((d (mv-nth 1 (fn-pic-next *pic-ajt-start* 1 *pic-test-stamped*))) (p (fn-pic-parser d)))
  (and (fn-pic-agent-tracep *pic-ajt-start* 0 *pic-test-stamped*)
       (not (equal (fn-pic-get phase d) :source-incoming))
       (not (and (fn-psc-source-contextp p *pic-test-stamped* *pic-spt-held*)
        (equal (fn-psc-model-retained-agent p *pic-test-stamped*)
         (fn-pb-path-agent *pic-test-stamped* (fn-record-string-octets (fn-pic-get msgid d)))))))) :rule-classes nil)
(defun pic-sxt-digest-shape-positive ()
 (declare (xargs :verify-guards nil))
 (with-local-stobj pgs-digest-state
  (mv-let (ok pgs-digest-state)
   (let ((c (fn-pic-hash-start nil *pic-ajt-entry*)))
    (mv-let (status d left pgs-digest-state) (fn-pic-digest-next c 2 pgs-digest-state)
     (declare (ignore status left))
     (mv (and (fn-pic-agent-shapep c) (equal (fn-pic-get phase d) :digest-next)
              (fn-pic-agent-shapep d)) pgs-digest-state)))
   ok)))
(assert-event (pic-sxt-digest-shape-positive))
(defthm pic-sxt-digest-shape-removal-corrupted-improper-agent
 (let ((c (fn-pic-hash-start nil *pic-sxt-corrupt*)))
  (and (not (fn-pic-agent-shapep c))
       (not (fn-pic-agent-shapep (mv-nth 1 (fn-pic-digest-next c 1 pgs-digest-state)))))) :rule-classes nil)
(defconst *pic-sxt-pool*
 (list nil :uninitialized
  (fn-ibc-carrier (list :input-backing 4 (len *pic-test-stamped*))
                  (list *pic-test-incoming* :readonly '(0 0 0 0 1)))))
(defthm pic-sxt-pooled-source-entry-positive
 (let* ((c *pic-ajt-before*) (d (mv-nth 1 (fn-pic-held-next c 1 *pic-test-stamped* *pic-sxt-pool*)))
        (p (fn-pic-parser d)))
  (and (fn-pic-agent-tracep c *pic-ajt-ticks* *pic-test-stamped*)
       (equal (fn-pic-get phase d) :source-incoming)
       (equal (fn-ioh-access (fn-ibc-carrier-row (fn-prp-incoming-slot *pic-sxt-pool*))
                             (fn-pic-get incoming-token c) :read) :holder-readonly)
       (fn-psc-source-contextp p *pic-test-stamped* *pic-spt-held*)
       (equal (fn-psc-model-retained-agent p *pic-test-stamped*)
              (fn-pb-path-agent *pic-test-stamped* (fn-record-string-octets (fn-pic-get msgid d)))))) :rule-classes nil)
(defthm pic-sxt-pooled-entry-trace-removal-corrupted-span
 (let* ((p (fn-pic-parser *pic-ajt-before*))
        (c (fn-pic-set parser (fn-psc-set agent-start (+ 1 (fn-psc-get agent-start p)) p) *pic-ajt-before*))
        (d (mv-nth 1 (fn-pic-held-next c 1 *pic-test-stamped* *pic-sxt-pool*))) (q (fn-pic-parser d)))
  (and (not (fn-pic-agent-tracep c *pic-ajt-ticks* *pic-test-stamped*))
       (equal (fn-pic-get phase d) :source-incoming)
       (equal (fn-ioh-access (fn-ibc-carrier-row (fn-prp-incoming-slot *pic-sxt-pool*))
                             (fn-pic-get incoming-token c) :read) :holder-readonly)
       (not (and (fn-psc-source-contextp q *pic-test-stamped* *pic-spt-held*)
        (equal (fn-psc-model-retained-agent q *pic-test-stamped*)
         (fn-pb-path-agent *pic-test-stamped* (fn-record-string-octets (fn-pic-get msgid d)))))))) :rule-classes nil)
(defthm pic-sxt-pooled-entry-phase-removal-pending
 (let* ((c *pic-ajt-start*) (d (mv-nth 1 (fn-pic-held-next c 1 *pic-test-stamped* *pic-sxt-pool*)))
        (p (fn-pic-parser d)))
  (and (fn-pic-agent-tracep c 0 *pic-test-stamped*)
       (not (equal (fn-pic-get phase d) :source-incoming))
       (not (and (fn-psc-source-contextp p *pic-test-stamped* *pic-spt-held*)
        (equal (fn-psc-model-retained-agent p *pic-test-stamped*)
         (fn-pb-path-agent *pic-test-stamped* (fn-record-string-octets (fn-pic-get msgid d)))))))) :rule-classes nil)
(defun pic-sxt-pooled-entry-observation (phase token)
 (declare (xargs :verify-guards nil))
 (with-local-stobj fn-page-read-pool
  (mv-let (ok fn-page-read-pool)
   (let* ((carrier (fn-ibc-carrier (list :input-backing 4 (len *pic-test-stamped*))
                                  (list token phase '(0 0 0 0 1))))
          (fn-page-read-pool (update-fn-prp-incoming-slot carrier fn-page-read-pool)))
    (mv (with-local-stobj fn-octets
     (mv-let (ok fn-octets)
      (let* ((fn-octets (fn-octets-from-list *pic-test-stamped* fn-octets)) (c *pic-ajt-before*))
       (mv-let (word d left) (fn-pic-held-next c 1 fn-octets fn-page-read-pool)
        (declare (ignore word))
        (let ((access (fn-ioh-access (fn-ibc-carrier-row (fn-prp-incoming-slot fn-page-read-pool))
                                    (fn-pic-get incoming-token c) :read)))
         (mv (and (fn-pic-agent-tracep c *pic-ajt-ticks* *pic-test-stamped*)
                  (equal (fn-octets-list fn-octets) *pic-test-stamped*)
                  (equal (fn-prp-incoming-slot fn-page-read-pool) carrier)
                  (if (equal access :holder-readonly)
                   (and (equal (fn-pic-get phase d) :source-incoming)
                        (fn-psc-source-contextp (fn-pic-parser d) *pic-test-stamped* *pic-spt-held*)
                        (equal (fn-psc-model-retained-agent (fn-pic-parser d) *pic-test-stamped*)
                         (fn-pb-path-agent *pic-test-stamped* (fn-record-string-octets (fn-pic-get msgid d)))))
                   (and (not (equal (fn-pic-get phase d) :source-incoming))
                        (equal d c) (equal left 1)))) fn-octets))))
      ok)) fn-page-read-pool))
   ok)))
(assert-event (pic-sxt-pooled-entry-observation :readonly *pic-test-incoming*))
(assert-event (pic-sxt-pooled-entry-observation :setup *pic-test-incoming*))
(assert-event (pic-sxt-pooled-entry-observation :cancelled *pic-test-incoming*))
(assert-event (pic-sxt-pooled-entry-observation :readonly '(:incoming 5)))
(defthm pic-sxt-pooled-shape-carry-positive
 (let ((c *pic-ajt-entry*))
  (and (fn-pic-agent-shapep c)
       (fn-pic-agent-shapep (mv-nth 1 (fn-pic-held-next c 1 *pic-test-stamped* *pic-sxt-pool*))))) :rule-classes nil)
(defthm pic-sxt-pooled-shape-removal-corrupted-improper-agent
 (let ((c *pic-sxt-corrupt*))
  (and (not (fn-pic-agent-shapep c))
       (not (fn-pic-agent-shapep (mv-nth 1 (fn-pic-held-next c 0 *pic-test-stamped* *pic-sxt-pool*)))))) :rule-classes nil)
