(in-package "ACL2")

(include-book "../../books/post-identity-source-cursor-source-path")

(defthm fn-psc-source-path-held-match-literal
 (let* ((xs (fn-inj-path-line '(97))) (incoming '(97)) (held xs)
        (c (fn-psc-set skip 0 (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming))))
        (d (fn-psc-model-source-path-prefix-complete 0 c incoming held))
        (p (fn-pbb-strip-at (fn-inj-path-line (fn-psc-model-retained-agent c incoming)) 0 (fn-psc-model-source c incoming held))))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (equal (fn-psc-get skip c) 0)
       (equal p 22) (equal (fn-psc-get phase d) :compare) (equal (fn-psc-get resume d) :source-stamp)
       (equal (fn-psc-get base d) (if (equal p :no) 0 p))
       (iff (fn-psc-get has-path d) (not (equal p :no))) (fn-psc-source-contextp d incoming held)
       (equal (fn-psc-model-source d incoming held) (fn-psc-model-source c incoming held))
       (equal (fn-psc-model-retained-agent d incoming) (fn-psc-model-retained-agent c incoming))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-path-prefix-cost 0 c incoming held)
         (fn-psc-literal 0 *fn-inj-path-field* :source-path-field c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-path-incoming-match-literal
 (let* ((xs (fn-inj-path-line '(97))) (incoming xs) (held nil)
        (c (fn-psc-set skip 0 (fn-psc-begin :source-incoming (len xs) "<a@b>" '(:agent 6 7) (len incoming))))
        (d (fn-psc-model-source-path-prefix-complete 0 c incoming held))
        (p (fn-pbb-strip-at (fn-inj-path-line (fn-psc-model-retained-agent c incoming)) 0 (fn-psc-model-source c incoming held))))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (equal (fn-psc-get skip c) 0)
       (equal p 22) (equal (fn-psc-get phase d) :compare) (equal (fn-psc-get resume d) :source-stamp)
       (equal (fn-psc-get base d) (if (equal p :no) 0 p))
       (iff (fn-psc-get has-path d) (not (equal p :no))) (fn-psc-source-contextp d incoming held)
       (equal (fn-psc-model-source d incoming held) (fn-psc-model-source c incoming held))
       (equal (fn-psc-model-retained-agent d incoming) (fn-psc-model-retained-agent c incoming))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-path-prefix-cost 0 c incoming held)
         (fn-psc-literal 0 *fn-inj-path-field* :source-path-field c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-path-held-field-mismatch-literal
 (let* ((xs '(0)) (incoming '(97)) (held xs)
        (c (fn-psc-set skip 0 (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming))))
        (d (fn-psc-model-source-path-prefix-complete 0 c incoming held))
        (p (fn-pbb-strip-at (fn-inj-path-line (fn-psc-model-retained-agent c incoming)) 0 (fn-psc-model-source c incoming held))))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (equal (fn-psc-get skip c) 0)
       (equal p :no) (equal (fn-psc-get phase d) :compare) (equal (fn-psc-get resume d) :source-stamp)
       (equal (fn-psc-get base d) (if (equal p :no) 0 p))
       (iff (fn-psc-get has-path d) (not (equal p :no))) (fn-psc-source-contextp d incoming held)
       (equal (fn-psc-model-source d incoming held) (fn-psc-model-source c incoming held))
       (equal (fn-psc-model-retained-agent d incoming) (fn-psc-model-retained-agent c incoming))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-path-prefix-cost 0 c incoming held)
         (fn-psc-literal 0 *fn-inj-path-field* :source-path-field c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-path-held-agent-mismatch-literal
 (let* ((xs (fn-inj-path-line '(98))) (incoming '(97)) (held xs)
        (c (fn-psc-set skip 0 (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming))))
        (d (fn-psc-model-source-path-prefix-complete 0 c incoming held))
        (p (fn-pbb-strip-at (fn-inj-path-line (fn-psc-model-retained-agent c incoming)) 0 (fn-psc-model-source c incoming held))))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (equal (fn-psc-get skip c) 0)
       (equal p :no) (equal (fn-psc-get phase d) :compare) (equal (fn-psc-get resume d) :source-stamp)
       (equal (fn-psc-get base d) (if (equal p :no) 0 p))
       (iff (fn-psc-get has-path d) (not (equal p :no))) (fn-psc-source-contextp d incoming held)
       (equal (fn-psc-model-source d incoming held) (fn-psc-model-source c incoming held))
       (equal (fn-psc-model-retained-agent d incoming) (fn-psc-model-retained-agent c incoming))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-path-prefix-cost 0 c incoming held)
         (fn-psc-literal 0 *fn-inj-path-field* :source-path-field c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-path-held-tail-eof-literal
 (let* ((xs (append *fn-inj-path-field* '(97 33))) (incoming '(97)) (held xs)
        (c (fn-psc-set skip 0 (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming))))
        (d (fn-psc-model-source-path-prefix-complete 0 c incoming held))
        (p (fn-pbb-strip-at (fn-inj-path-line (fn-psc-model-retained-agent c incoming)) 0 (fn-psc-model-source c incoming held))))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (equal (fn-psc-get skip c) 0)
       (equal p :no) (equal (fn-psc-get phase d) :compare) (equal (fn-psc-get resume d) :source-stamp)
       (equal (fn-psc-get base d) (if (equal p :no) 0 p))
       (iff (fn-psc-get has-path d) (not (equal p :no))) (fn-psc-source-contextp d incoming held)
       (equal (fn-psc-model-source d incoming held) (fn-psc-model-source c incoming held))
       (equal (fn-psc-model-retained-agent d incoming) (fn-psc-model-retained-agent c incoming))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-path-prefix-cost 0 c incoming held)
         (fn-psc-literal 0 *fn-inj-path-field* :source-path-field c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-path-held-eof-literal
 (let* ((xs nil) (incoming '(97)) (held xs)
        (c (fn-psc-set skip 0 (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming))))
        (d (fn-psc-model-source-path-prefix-complete 0 c incoming held))
        (p (fn-pbb-strip-at (fn-inj-path-line (fn-psc-model-retained-agent c incoming)) 0 (fn-psc-model-source c incoming held))))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (equal (fn-psc-get skip c) 0)
       (equal p :no) (equal (fn-psc-get phase d) :compare) (equal (fn-psc-get resume d) :source-stamp)
       (equal (fn-psc-get base d) (if (equal p :no) 0 p))
       (iff (fn-psc-get has-path d) (not (equal p :no))) (fn-psc-source-contextp d incoming held)
       (equal (fn-psc-model-source d incoming held) (fn-psc-model-source c incoming held))
       (equal (fn-psc-model-retained-agent d incoming) (fn-psc-model-retained-agent c incoming))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-path-prefix-cost 0 c incoming held)
         (fn-psc-literal 0 *fn-inj-path-field* :source-path-field c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-path-held-offset-literal
 (let* ((xs (cons 0 (fn-inj-path-line '(97)))) (incoming '(97)) (held xs)
        (c (fn-psc-set skip 1 (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 1) (len incoming))))
        (d (fn-psc-model-source-path-prefix-complete 1 c incoming held))
        (p (fn-pbb-strip-at (fn-inj-path-line (fn-psc-model-retained-agent c incoming)) 1 (fn-psc-model-source c incoming held))))
  (and (fn-psc-source-contextp c incoming held) (natp 1) (equal (fn-psc-get skip c) 1)
       (equal p 23) (equal (fn-psc-get phase d) :compare) (equal (fn-psc-get resume d) :source-stamp)
       (equal (fn-psc-get base d) (if (equal p :no) 1 p))
       (iff (fn-psc-get has-path d) (not (equal p :no))) (fn-psc-source-contextp d incoming held)
       (equal (fn-psc-model-source d incoming held) (fn-psc-model-source c incoming held))
       (equal (fn-psc-model-retained-agent d incoming) (fn-psc-model-retained-agent c incoming))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-path-prefix-cost 1 c incoming held)
         (fn-psc-literal 1 *fn-inj-path-field* :source-path-field c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-path-skip-removal-literal
 (let* ((incoming '(97)) (held '(0))
        (c (fn-psc-set skip 1 (fn-psc-begin :source-held 1 "<a@b>" '(:agent 0 1) 1)))
        (d (fn-psc-model-source-path-prefix-complete 0 c incoming held))
        (p (fn-pbb-strip-at (fn-inj-path-line (fn-psc-model-retained-agent c incoming)) 0 held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (not (equal (fn-psc-get skip c) 0))
       (equal p :no) (not (equal (fn-psc-get base d) (if (equal p :no) 0 p)))))
 :rule-classes nil)

(defthm fn-psc-source-path-natural-position-removal-literal
 (let* ((incoming '(97)) (held '(0))
        (c (fn-psc-set skip -1 (fn-psc-begin :source-held 1 "<a@b>" '(:agent 0 1) 1)))
        (d (fn-psc-model-source-path-prefix-complete -1 c incoming held))
        (p (fn-pbb-strip-at (fn-inj-path-line (fn-psc-model-retained-agent c incoming)) -1 held)))
  (and (fn-psc-source-contextp c incoming held) (equal (fn-psc-get skip c) -1) (not (natp -1))
       (equal p :no) (not (equal (fn-psc-get base d) (if (equal p :no) -1 p)))))
 :hints (("Goal" :in-theory (enable fn-pbb-strip-at)))
 :rule-classes nil)

(defthm fn-psc-source-path-recipe-retains-present-path-literal
 (let* ((incoming '(97)) (held (fn-inj-injection-info-line '(97)))
        (c (fn-psc-set has-path t (fn-psc-begin :source-held (len held) "<a@b>" '(:agent 0 1) 1)))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal (fn-psc-get has-path d) (fn-psc-get has-path c)) (equal (fn-psc-get has-path d) t)))
 :rule-classes nil)

(defthm fn-psc-source-path-recipe-retains-absent-path-literal
 (let* ((incoming '(97)) (held (fn-inj-injection-info-line '(97)))
        (c (fn-psc-begin :source-held (len held) "<a@b>" '(:agent 0 1) 1))
        (d (fn-psc-model-source-after-path-complete 0 c incoming held)))
  (and (fn-psc-source-contextp c incoming held) (natp 0) (<= 0 (len (fn-psc-model-source c incoming held)))
       (equal (fn-psc-get has-path d) (fn-psc-get has-path c)) (equal (fn-psc-get has-path d) nil)))
 :rule-classes nil)
