(in-package "ACL2")
(include-book "../../books/post-identity-source-cursor-source-date")

(defthm fn-psc-source-date-incoming-literal
 (let* ((incoming (append (make-list 31 :initial-element 65) (fn-inj-date-line (make-list 31 :initial-element 65)) '(88))) (held nil)
        (xs (if (equal :source-incoming :source-held) held incoming))
        (c (fn-psc-set date 0 (fn-psc-begin :source-incoming (len xs) "<a@b>" '(:agent 0 0) (len incoming))))
        (d (fn-psc-model-source-date-complete 31 :source-optional-date c incoming held))
        (p (fn-pbb-strip-at (fn-inj-date-line (fn-psc-model-captured-date c incoming held)) 31 xs)))
  (and (fn-psc-source-date-contextp c incoming held) (natp 31) (<= 31 (len xs))
       (equal p 70) (equal (fn-psc-get phase d) :control)
       (equal (fn-psc-get resume d) :source-optional-date)
       (iff (fn-psc-get ok d) (not (equal p :no)))
       (implies (not (equal p :no)) (equal (fn-psc-get pos d) p))
       (fn-psc-source-date-contextp d incoming held)
       (equal (fn-psc-model-captured-date d incoming held) (fn-psc-model-captured-date c incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-date-cost 31 :source-optional-date c incoming held)
                    (fn-psc-date-compare 31 :source-optional-date c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-date-held-literal
 (let* ((incoming nil) (held (append (make-list 31 :initial-element 65) (fn-inj-date-line (make-list 31 :initial-element 65)) '(88)))
        (xs (if (equal :source-held :source-held) held incoming))
        (c (fn-psc-set date 0 (fn-psc-begin :source-held (len xs) "<a@b>" '(:agent 0 0) (len incoming))))
        (d (fn-psc-model-source-date-complete 31 :source-optional-date c incoming held))
        (p (fn-pbb-strip-at (fn-inj-date-line (fn-psc-model-captured-date c incoming held)) 31 xs)))
  (and (fn-psc-source-date-contextp c incoming held) (natp 31) (<= 31 (len xs))
       (equal p 70) (equal (fn-psc-get phase d) :control)
       (equal (fn-psc-get resume d) :source-optional-date)
       (iff (fn-psc-get ok d) (not (equal p :no)))
       (implies (not (equal p :no)) (equal (fn-psc-get pos d) p))
       (fn-psc-source-date-contextp d incoming held)
       (equal (fn-psc-model-captured-date d incoming held) (fn-psc-model-captured-date c incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-date-cost 31 :source-optional-date c incoming held)
                    (fn-psc-date-compare 31 :source-optional-date c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-date-bad-lf-literal
 (let* ((incoming (append (make-list 31 :initial-element 65) *fn-inj-date-field* (make-list 31 :initial-element 65) '(13 88))) (held nil)
        (xs (if (equal :source-incoming :source-held) held incoming))
        (c (fn-psc-set date 0 (fn-psc-begin :source-incoming (len xs) "<a@b>" '(:agent 0 0) (len incoming))))
        (d (fn-psc-model-source-date-complete 31 :source-optional-date c incoming held))
        (p (fn-pbb-strip-at (fn-inj-date-line (fn-psc-model-captured-date c incoming held)) 31 xs)))
  (and (fn-psc-source-date-contextp c incoming held) (natp 31) (<= 31 (len xs))
       (equal p :no) (equal (fn-psc-get phase d) :control)
       (equal (fn-psc-get resume d) :source-optional-date)
       (iff (fn-psc-get ok d) (not (equal p :no)))
       (implies (not (equal p :no)) (equal (fn-psc-get pos d) p))
       (fn-psc-source-date-contextp d incoming held)
       (equal (fn-psc-model-captured-date d incoming held) (fn-psc-model-captured-date c incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-date-cost 31 :source-optional-date c incoming held)
                    (fn-psc-date-compare 31 :source-optional-date c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-date-mismatch-literal
 (let* ((incoming (append (make-list 31 :initial-element 65) (fn-inj-date-line (make-list 31 :initial-element 66)))) (held nil)
        (xs (if (equal :source-incoming :source-held) held incoming))
        (c (fn-psc-set date 0 (fn-psc-begin :source-incoming (len xs) "<a@b>" '(:agent 0 0) (len incoming))))
        (d (fn-psc-model-source-date-complete 31 :source-optional-date c incoming held))
        (p (fn-pbb-strip-at (fn-inj-date-line (fn-psc-model-captured-date c incoming held)) 31 xs)))
  (and (fn-psc-source-date-contextp c incoming held) (natp 31) (<= 31 (len xs))
       (equal p :no) (equal (fn-psc-get phase d) :control)
       (equal (fn-psc-get resume d) :source-optional-date)
       (iff (fn-psc-get ok d) (not (equal p :no)))
       (implies (not (equal p :no)) (equal (fn-psc-get pos d) p))
       (fn-psc-source-date-contextp d incoming held)
       (equal (fn-psc-model-captured-date d incoming held) (fn-psc-model-captured-date c incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-date-cost 31 :source-optional-date c incoming held)
                    (fn-psc-date-compare 31 :source-optional-date c) incoming held))))
 :rule-classes nil)

(defthm fn-psc-source-date-eof-literal
 (let* ((incoming (append (make-list 31 :initial-element 65) *fn-inj-date-field* '(65))) (held nil)
        (xs (if (equal :source-incoming :source-held) held incoming))
        (c (fn-psc-set date 0 (fn-psc-begin :source-incoming (len xs) "<a@b>" '(:agent 0 0) (len incoming))))
        (d (fn-psc-model-source-date-complete 31 :source-optional-date c incoming held))
        (p (fn-pbb-strip-at (fn-inj-date-line (fn-psc-model-captured-date c incoming held)) 31 xs)))
  (and (fn-psc-source-date-contextp c incoming held) (natp 31) (<= 31 (len xs))
       (equal p :no) (equal (fn-psc-get phase d) :control)
       (equal (fn-psc-get resume d) :source-optional-date)
       (iff (fn-psc-get ok d) (not (equal p :no)))
       (implies (not (equal p :no)) (equal (fn-psc-get pos d) p))
       (fn-psc-source-date-contextp d incoming held)
       (equal (fn-psc-model-captured-date d incoming held) (fn-psc-model-captured-date c incoming held))
       (equal d (fn-psc-model-byte-run (fn-psc-model-source-date-cost 31 :source-optional-date c incoming held)
                    (fn-psc-date-compare 31 :source-optional-date c) incoming held))))
 :rule-classes nil)
(defthm fn-psc-source-date-capture-bound-removal-literal
 (let* ((incoming (fn-inj-date-line nil)) (held nil)
        (c (fn-psc-set date 8 (fn-psc-begin :source-incoming 8 "<a@b>" '(:agent 0 0) 8)))
        (d (fn-psc-model-source-date-complete 0 :source-optional-date c incoming held))
        (p (fn-pbb-strip-at (fn-inj-date-line (fn-psc-model-captured-date c incoming held)) 0 incoming)))
  (and (fn-psc-source-contextp c incoming held) (natp (fn-psc-get date c))
       (natp 0) (<= 0 (len incoming))
       (not (<= (+ 31 (fn-psc-get date c)) (len incoming)))
       (not (fn-psc-source-date-contextp c incoming held))
       (equal p 8) (not (fn-psc-get ok d))
       (not (iff (fn-psc-get ok d) (not (equal p :no))))))
 :rule-classes nil)
