; The table lookup a book writes for a reply text is the literal the book
; admitted before (lanes defprotocol, defprotocol-2): every (fn-proto-text ROW
; KEY) call site in books/ expands to the text below.  tools/protocol_emit.py
; --expand makes the same substitution for the byte-identical-expansion
; differential of a converted book; this book pins that its mirror is the
; macro ACL2 expands (a table text edited without the sites would show here
; and in the books that prove facts about the literal).
; Mutation: a wrong literal for one call fails (the must-fail at the end).
(in-package "ACL2")
(include-book "../../books/protocol-table")
(include-book "must-fail-checked")

(assert-event (equal (fn-proto-text "(connection)" :auth-failures) "400 too many authentication failures; closing connection"))
(assert-event (equal (fn-proto-text "(connection)" :auth-failures-address) "400 too many authentication failures from this address; try again later"))
(assert-event (equal (fn-proto-text "(connection)" :busy) "400 too many connections; try again later"))
(assert-event (equal (fn-proto-text "(connection)" :busy-address) "400 too many connections from this address; try again later"))
(assert-event (equal (fn-proto-text "(connection)" :fault) "403 internal fault; this connection is closed and the server continues"))
(assert-event (equal (fn-proto-text "(syntax)" :syntax) "501 syntax error"))
(assert-event (equal (fn-proto-text "(unrecognized)" :unknown) "500 command not recognized"))
(assert-event (equal (fn-proto-text "AUTHINFO" :accepted) "281 authentication accepted"))
(assert-event (equal (fn-proto-text "AUTHINFO" :failed) "481 authentication failed"))
(assert-event (equal (fn-proto-text "AUTHINFO" :no-sasl) "502 no SASL mechanism is offered"))
(assert-event (equal (fn-proto-text "AUTHINFO" :password) "381 password required"))
(assert-event (equal (fn-proto-text "AUTHINFO" :sequence) "482 authentication commands issued out of sequence"))
(assert-event (equal (fn-proto-text "CAPABILITIES" :list) "101 capability list follows"))
(assert-event (equal (fn-proto-text "CAPABILITIES" :syntax) "501 syntax error"))
(assert-event (equal (fn-proto-text "DATE" :no-observation) "503 no clock observation supplied"))
(assert-event (equal (fn-proto-text "DATE" :no-wall) "503 server holds no wall clock reading"))
(assert-event (equal (fn-proto-text "DATE" :out-of-range) "503 clock reading outside the representable range"))
(assert-event (equal (fn-proto-text "DATE" :syntax) "501 syntax error"))
(assert-event (equal (fn-proto-text "GROUP" :syntax) "501 syntax error"))
(assert-event (equal (fn-proto-text "HDR" :headers) "225 headers follow"))
(assert-event (equal (fn-proto-text "HDR" :no-control-status) "503 control status unavailable"))
(assert-event (equal (fn-proto-text "HDR" :no-msgid) "430 no article with that message-id"))
(assert-event (equal (fn-proto-text "HDR" :syntax) "501 syntax error"))
(assert-event (equal (fn-proto-text "HELP" :syntax) "501 syntax error"))
(assert-event (equal (fn-proto-text "HELP" :text) "100 help text follows"))
(assert-event (equal (fn-proto-text "IHAVE" :closing) "436 the article was not received; closing"))
(assert-event (equal (fn-proto-text "IHAVE" :duplicate) "435 duplicate"))
(assert-event (equal (fn-proto-text "IHAVE" :not-received) "436 transfer failed; the article was not received"))
(assert-event (equal (fn-proto-text "IHAVE" :rejected-by-acceptance) "437 transfer rejected; refused by acceptance"))
(assert-event (equal (fn-proto-text "IHAVE" :retry-no-clock) "436 retry later; no usable clock reading"))
(assert-event (equal (fn-proto-text "IHAVE" :send) "335 send it; end with <CR-LF>.<CR-LF>"))
(assert-event (equal (fn-proto-text "IHAVE" :transferred) "235 article transferred OK"))
(assert-event (equal (fn-proto-text "IHAVE" :uncertain) "436 transfer failed; the outcome is uncertain"))
(assert-event (equal (fn-proto-text "LAST" :no-previous) "422 no previous article"))
(assert-event (equal (fn-proto-text "LAST" :syntax) "501 syntax error"))
(assert-event (equal (fn-proto-text "LIST" :active) "215 list of active newsgroups follows"))
(assert-event (equal (fn-proto-text "LIST" :headers) "215 field list follows"))
(assert-event (equal (fn-proto-text "LIST" :motd) "215 message of the day follows"))
(assert-event (equal (fn-proto-text "LIST" :newsgroups) "215 list of newsgroups follows"))
(assert-event (equal (fn-proto-text "LIST" :not-stored) "503 data item not stored"))
(assert-event (equal (fn-proto-text "LIST" :overview-fmt) "215 order of fields in overview database"))
(assert-event (equal (fn-proto-text "LIST" :subscriptions) "215 list of recommended newsgroups follows"))
(assert-event (equal (fn-proto-text "LIST" :syntax) "501 syntax error"))
(assert-event (equal (fn-proto-text "LIST" :times) "215 information follows"))
(assert-event (equal (fn-proto-text "LIST" :variant) "501 unsupported LIST variant"))
(assert-event (equal (fn-proto-text "MODE" :no-posting) "201 posting prohibited"))
(assert-event (equal (fn-proto-text "MODE" :no-reader) "502 reading service permanently unavailable"))
(assert-event (equal (fn-proto-text "MODE" :posting) "200 posting allowed"))
(assert-event (equal (fn-proto-text "MODE" :streaming) "203 streaming permitted"))
(assert-event (equal (fn-proto-text "NEWGROUPS" :listed) "231 list of new newsgroups follows"))
(assert-event (equal (fn-proto-text "NEWNEWS" :listed) "230 list of new articles by message-id follows"))
(assert-event (equal (fn-proto-text "NEXT" :no-next) "421 no next article"))
(assert-event (equal (fn-proto-text "NEXT" :syntax) "501 syntax error"))
(assert-event (equal (fn-proto-text "POST" :key-change-refused) "240 article received OK; the key change it carries was refused (key-change-refused)"))
(assert-event (equal (fn-proto-text "POST" :malformed-session) "403 internal fault; the posting session is malformed"))
(assert-event (equal (fn-proto-text "POST" :not-permitted) "440 posting not permitted"))
(assert-event (equal (fn-proto-text "POST" :not-received) "441 posting failed; the article was not received"))
(assert-event (equal (fn-proto-text "POST" :principal) "440 posting not permitted for this principal"))
(assert-event (equal (fn-proto-text "POST" :received) "240 article received OK"))
(assert-event (equal (fn-proto-text "POST" :refused-approval-not-moderator) "441 posting failed; Approved is accepted only from a moderator of each moderated group named (LIST ACTIVE status m)"))
(assert-event (equal (fn-proto-text "POST" :refused-clock-out-of-range) "441 posting failed; this server clock is outside the modelled range"))
(assert-event (equal (fn-proto-text "POST" :refused-clock-unusable) "441 posting failed; this server has no usable clock reading"))
(assert-event (equal (fn-proto-text "POST" :refused-date-duplicate) "441 posting failed; Date appears more than once"))
(assert-event (equal (fn-proto-text "POST" :refused-from-duplicate) "441 posting failed; From appears more than once"))
(assert-event (equal (fn-proto-text "POST" :refused-from-invalid) "441 posting failed; From is not a valid mailbox list"))
(assert-event (equal (fn-proto-text "POST" :refused-from-missing) "441 posting failed; From is required"))
(assert-event (equal (fn-proto-text "POST" :refused-group-read-only) "441 posting failed; a group this article names is read-only here (LIST ACTIVE status n)"))
(assert-event (equal (fn-proto-text "POST" :refused-header-fields-limit) "441 posting failed; the header has more fields than the profile's max-header-fields"))
(assert-event (equal (fn-proto-text "POST" :refused-header-lines-limit) "441 posting failed; the header has more lines than the profile's max-header-lines"))
(assert-event (equal (fn-proto-text "POST" :refused-header-octets-limit) "441 posting failed; the header has more octets than the profile's max-header-octets"))
(assert-event (equal (fn-proto-text "POST" :refused-injection-date-present) "441 posting failed; Injection-Date must not be supplied"))
(assert-event (equal (fn-proto-text "POST" :refused-injection-info) "441 posting failed; Injection-Info must not be supplied"))
(assert-event (equal (fn-proto-text "POST" :refused-message-id-duplicate) "441 posting failed; Message-ID appears more than once"))
(assert-event (equal (fn-proto-text "POST" :refused-message-id-invalid) "441 posting failed; Message-ID is not a valid identifier"))
(assert-event (equal (fn-proto-text "POST" :refused-moderation-unavailable) "441 posting failed; a moderated group is named and the article could not be forwarded to its moderation queue"))
(assert-event (equal (fn-proto-text "POST" :refused-newsgroups-duplicate) "441 posting failed; Newsgroups appears more than once"))
(assert-event (equal (fn-proto-text "POST" :refused-newsgroups-invalid) "441 posting failed; Newsgroups is not a valid newsgroup list"))
(assert-event (equal (fn-proto-text "POST" :refused-newsgroups-missing) "441 posting failed; Newsgroups is required"))
(assert-event (equal (fn-proto-text "POST" :refused-no-groups) "441 posting failed; no newsgroup was named"))
(assert-event (equal (fn-proto-text "POST" :refused-oversize) "441 posting failed; the article exceeds the configured size"))
(assert-event (equal (fn-proto-text "POST" :refused-path-duplicate) "441 posting failed; Path appears more than once"))
(assert-event (equal (fn-proto-text "POST" :refused-path-malformed) "441 posting failed; Path is not a valid path"))
(assert-event (equal (fn-proto-text "POST" :refused-path-posted) "441 posting failed; Path must not carry a POSTED diagnostic"))
(assert-event (equal (fn-proto-text "POST" :refused-path-present) "441 posting failed; Path must not be supplied"))
(assert-event (equal (fn-proto-text "POST" :refused-posting-disallowed) "441 posting failed; posting is not permitted"))
(assert-event (equal (fn-proto-text "POST" :refused-subject-duplicate) "441 posting failed; Subject appears more than once"))
(assert-event (equal (fn-proto-text "POST" :refused-subject-missing) "441 posting failed; Subject is required"))
(assert-event (equal (fn-proto-text "POST" :refused-unknown-group) "441 posting failed; a named newsgroup is not carried here"))
(assert-event (equal (fn-proto-text "POST" :refused-unnamed) "441 posting failed"))
(assert-event (equal (fn-proto-text "POST" :refused-unparsable) "441 posting failed; the article is not valid syntax"))
(assert-event (equal (fn-proto-text "POST" :refused-line-length) "441 posting failed; a header line is longer than 998 octets (RFC 5322 section 2.1.1); fold it"))
(assert-event (equal (fn-proto-text "POST" :refused-xref) "441 posting failed; Xref must not be supplied"))
(assert-event (equal (fn-proto-text "POST" :send) "340 send article to be posted"))
(assert-event (equal (fn-proto-text "POST" :syntax) "501 syntax error"))
(assert-event (equal (fn-proto-text "POST" :uncertain) "441 posting failed; the outcome is uncertain, do not repost"))
(assert-event (equal (fn-proto-text "QUIT" :closing) "205 closing connection"))
(assert-event (equal (fn-proto-text "QUIT" :syntax) "501 syntax error"))
(assert-event (equal (fn-proto-text "STARTTLS" :active) "502 a TLS layer is already active"))
(assert-event (equal (fn-proto-text "STARTTLS" :cannot) "580 can not initiate TLS negotiation"))
(assert-event (equal (fn-proto-text "STARTTLS" :continue) "382 continue with TLS negotiation"))
(assert-event (equal (fn-proto-text "XFNCATCHUP" :out-of-range) "503 catch-up log position out of range"))
(assert-event (equal (fn-proto-text "XFNCATCHUP" :past-end) "423 catch-up position past the end of the log"))
(assert-event (equal (fn-proto-text "XREDEEM" :bound) "281 account bound; authenticate with AUTHINFO on a new connection"))
(assert-event (equal (fn-proto-text "XREDEEM" :password) "381 send the password with XREDEEM PASS"))
(assert-event (equal (fn-proto-text "XREDEEM" :refused) "482 invitation code refused"))
(assert-event (equal (fn-proto-text "XREDEEM" :sequence) "482 redemption commands issued out of sequence"))
(assert-event (equal (fn-proto-text * :already) "502 already authenticated"))
(assert-event (equal (fn-proto-text * :auth-required) "480 authentication required"))
(assert-event (equal (fn-proto-text * :empty-range) "423 no articles in that range"))
(assert-event (equal (fn-proto-text * :header) "221 header follows"))
(assert-event (equal (fn-proto-text * :no-century) "503 two-digit year needs a wall clock reading"))
(assert-event (equal (fn-proto-text * :no-current) "420 no current article"))
(assert-event (equal (fn-proto-text * :no-framing) "503 stored article framing unavailable"))
(assert-event (equal (fn-proto-text * :no-group) "411 no such newsgroup"))
(assert-event (equal (fn-proto-text * :no-group-selected) "412 no newsgroup selected"))
(assert-event (equal (fn-proto-text * :no-identifier) "503 stored article identifier unavailable"))
(assert-event (equal (fn-proto-text * :no-msgid) "430 no article with that message-id"))
(assert-event (equal (fn-proto-text * :no-number) "423 no article with that number"))
(assert-event (equal (fn-proto-text * :no-projection) "503 archive projection unavailable"))
(assert-event (equal (fn-proto-text * :none-selected) "420 no article(s) selected"))
(assert-event (equal (fn-proto-text * :overview) "224 overview information follows"))
(assert-event (equal (fn-proto-text * :protect) "483 a protected channel is required; use STARTTLS"))
(assert-event (equal (fn-proto-text * :reclaimed) "423 article reclaimed"))
(assert-event (equal (fn-proto-text * :reclaimed-msgid) "430 article reclaimed"))
(assert-event (equal (fn-proto-text * :syntax) "501 syntax error"))
(assert-event (equal (fn-proto-text * :transit) "502 transit is not permitted on this connection"))
(assert-event (equal (fn-proto-text * :withdrawn-msgid) "430 withdrawn"))
(assert-event (equal (fn-proto-text * :withdrawn-number) "423 withdrawn"))

(must-fail-checked
  (assert-event (equal (fn-proto-text * :syntax) "500 syntax error")))
