(in-package "ACL2")
(include-book "../../books/query-payload-scalar")
(defun qpstest-run (fn-arena)
  (declare (xargs :stobjs fn-arena))
  (let* ((fn-arena (fn-arena-seal-list '(10 20) fn-arena))
         (held '(0 0 0 nil 0))
         (grant '(:query-payload 21 0 3 7 1 11))
         (selected '(:index-selected (:index-query 21 11 0 3) 0 41))
         (ledger '(7 nil nil))
         (length (mv-list 3 (fn-qps-selected-length selected held grant ledger 2 fn-arena)))
         (byte (mv-list 3 (fn-qps-selected-byte selected held grant ledger 1 1 fn-arena)))
         (yield (mv-list 3 (fn-qps-selected-byte selected held grant ledger 1 0 fn-arena)))
         (bounds (mv-list 3 (fn-qps-selected-byte selected held grant ledger 2 1 fn-arena)))
         (stale (mv-list 3 (fn-qps-selected-length selected held grant '(8 nil nil) 1 fn-arena))))
    (mv (and (fn-qps-eligiblep held grant ledger fn-arena)
             (equal length (list :ready (list :payload-length selected grant 0 2) 1))
             (equal byte (list :ready (list :payload-byte selected grant 0 1 20) 0))
             (equal yield '(:yield nil 0))
             (equal bounds '(:refused nil 0))
             (not (fn-qps-eligiblep held grant '(8 nil nil) fn-arena))
             (equal stale '(:refused nil 0))) fn-arena)))
(defun qpstest ()
  (with-local-stobj fn-arena
    (mv-let (answer fn-arena) (qpstest-run fn-arena) answer)))
; Internal scalar observation only; supplied test grant is not provider authority.
(assert-event (qpstest))
