(in-package "ACL2")
(include-book "../../books/reader-output-job")
; MODEL storage token: real runtime/factory/source registration remain open.
(defun-nx rogmt-current ()
 (let* ((ledger (fn-prl-make '(1000 1000 10 10 100)))
        (reserved (mv-list 3 (fn-rog-reserve-current
          '(:receiver-response (:receiver-turn 7) 1) 0 '(:buffer-storage 9)
          '(200 100 1 0 1) nil ledger)))
        (job (nth 1 reserved)) (token (fn-prl-nth 4 job))
        (prepared (mv-list 2 (fn-rog-prepare-current token job)))
        (installed (mv-list 2 (fn-rog-install-current token 5 '(:actual-window-plan)
                            (nth 1 prepared)))))
  (list reserved prepared installed)))
(defthm rogmt-actual-issue-and-partial-write-model-positive
 (let* ((setup (rogmt-current)) (reserved (nth 0 setup))
        (job (nth 1 (nth 2 setup))) (token (fn-prl-nth 4 job))
        (part (fn-rog-observe-current token :written 2 job))
        (wait (fn-rog-observe-current token :output 0 (mv-nth 2 part)))
        (done (fn-rog-observe-current token :written 3 (mv-nth 2 wait))))
  (and (equal (nth 0 reserved) :reserved)
       (equal (fn-prl-nth 3 token) 0)
       (equal (fn-prl-nth 2 (nth 2 reserved)) 1)
       (equal (nth 0 (nth 1 setup)) :constructing)
       (equal (nth 0 (nth 2 setup)) :installed)
       (fn-rog-jobp job)
       (equal (mv-nth 0 part) :writing) (equal (mv-nth 1 part) 2)
       (equal (mv-nth 0 wait) :wait) (equal (mv-nth 1 wait) 2)
       (equal (mv-nth 0 done) :drained) (equal (mv-nth 1 done) 5)
       (fn-rog-jobp (mv-nth 2 done))
       (equal (fn-prl-nth 5 (mv-nth 2 done)) (fn-prl-nth 5 job))
       (null (fn-prl-nth 11 (mv-nth 2 done)))))
 :rule-classes nil)
(defthm rogmt-stale-window-cannot-advance-model
 (let* ((job (nth 1 (nth 2 (rogmt-current))))
        (wrong '(:reader-output-window (:receiver-response (:receiver-turn 7) 1)
                 1 0 (:buffer-storage 9)))
        (answer (fn-rog-observe-current wrong :written 2 job)))
  (and (fn-rog-jobp job) (not (equal wrong (fn-prl-nth 4 job)))
       (equal (mv-nth 0 answer) :stale) (null (mv-nth 1 answer))
       (equal (mv-nth 2 answer) job)))
 :rule-classes nil)
(defthm rogmt-overrun-cancel-and-no-return-model
 (let* ((job (nth 1 (nth 2 (rogmt-current)))) (token (fn-prl-nth 4 job))
        (bad (fn-rog-observe-current token :written 6 job))
        (cancel (fn-rog-observe-current token :cancelled 0 job))
        (again (fn-rog-observe-current token :written 5 (mv-nth 2 cancel))))
  (and (fn-rog-jobp job)
       (equal (mv-nth 0 bad) :invalid-io-observation) (equal (mv-nth 2 bad) job)
       (equal (mv-nth 0 cancel) :cancelled)
       (equal (fn-prl-nth 5 (mv-nth 2 cancel)) (fn-prl-nth 5 job))
       (equal (mv-nth 0 again) :retained)
       (equal (mv-nth 2 again) (mv-nth 2 cancel))
       (equal (fn-rog-outgoing-source-status) :outgoing-source-unavailable)))
 :rule-classes nil)

(defthm rogmt-returned-active-corruption-refuses-successor
 (let* ((live (nth 1 (nth 2 (rogmt-current))))
        (corrupt (list (fn-prl-nth 0 live) (fn-prl-nth 1 live)
                       (fn-prl-nth 2 live) :returned (fn-prl-nth 4 live)
                       (fn-prl-nth 5 live) (fn-prl-nth 6 live)
                       (fn-prl-nth 7 live) (fn-prl-nth 8 live)
                       (fn-prl-nth 9 live) nil nil))
        (ledger (fn-prl-make '(1000 1000 10 10 100)))
        (answer (mv-list 3 (fn-rog-reserve-issued-current
           (fn-prl-nth 1 corrupt) 1 '(:buffer-storage 10)
           '(200 100 1 0 1) corrupt ledger))))
   (and (fn-rog-jobp corrupt) (eq (fn-prl-nth 3 corrupt) :returned)
        (eq (fn-prl-nth 2 (fn-prl-nth 5 corrupt)) :active)
        (not (fn-rog-successor-ready-p corrupt))
        (equal answer (list :busy corrupt ledger))))
 :rule-classes nil)
