(in-package "ACL2")
(include-book "../../books/receiver-provider")
; Literal logical shape teeth. The actual issuer/install fixture lives with
; physical installer708292d3c; these are not constructor authority fixtures.
(defthm fn-rxp-range-positive-literal
 (let* ((token '(:rx-capacity 0 0 4096))
        (provider (list nil (list token 0 4096)))
        (answer (fn-rxp-fill-range token 16 nil 16 provider)))
  (and (fn-rx-providerp provider)
       (equal (mv-nth 0 answer) :receive-copy)
       (natp 16) (<= 16 4096) (<= 16 (fn-cbud-step-read-octets nil))
       (equal (fn-rxp-token provider) token)
       (equal (fn-rxp-instance provider) 0)
       (equal (fn-rxp-capacity provider) 4096)
       (equal (mv-nth 1 answer) 0) (equal (mv-nth 2 answer) 16)
       (equal (mv-nth 3 answer) 0) (equal (mv-nth 4 answer) provider)))
 :rule-classes nil)
(defthm fn-rxp-range-foreign-token-literal
 (let* ((token '(:rx-capacity 0 0 4096))
        (foreign '(:rx-capacity 1 0 4096))
        (provider (list nil (list token 0 4096)))
        (answer (fn-rxp-fill-range foreign 16 nil 16 provider)))
  (and (fn-rx-providerp provider) (not (equal token foreign))
       (equal (mv-nth 0 answer) :receiver-unavailable)
       (equal (mv-nth 1 answer) 0) (equal (mv-nth 2 answer) 0)
       (equal (mv-nth 3 answer) 16) (equal (mv-nth 4 answer) provider)))
 :rule-classes nil)
(defthm fn-rxp-range-exhausted-fuel-literal
 (let* ((token '(:rx-capacity 0 0 4096))
        (provider (list nil (list token 0 4096)))
        (answer (fn-rxp-fill-range token 16 nil 15 provider)))
  (and (fn-rx-providerp provider) (natp 16) (natp 15)
       (<= 16 (fn-cbud-step-read-octets nil)) (> 16 15)
       (equal (mv-nth 0 answer) :receive-yield)
       (equal (mv-nth 1 answer) 0) (equal (mv-nth 2 answer) 0)
       (equal (mv-nth 3 answer) 15) (equal (mv-nth 4 answer) provider)))
 :rule-classes nil)
; Mutation witness: interrupted publication has token/instance but no capacity.
(defthm fn-rxp-range-partial-carry-refuses-literal
 (let* ((token '(:rx-capacity 0 0 4096))
        (provider (list '(9 8) (list token 0 nil)))
        (answer (fn-rxp-fill-range token 16 nil 16 provider)))
  (and (fn-rx-providerp provider) (equal (fn-rxp-token provider) token)
       (equal (fn-rxp-instance provider) 0) (null (fn-rxp-capacity provider))
       (equal (mv-nth 0 answer) :receiver-unavailable)
       (equal (mv-nth 1 answer) 0) (equal (mv-nth 2 answer) 0)
       (equal (mv-nth 3 answer) 16) (equal (mv-nth 4 answer) provider)))
 :rule-classes nil)
(defthm fn-rxp-range-quantum-exhaustion-refuses-literal
 (let* ((token '(:rx-capacity 0 0 4096))
        (provider (list '(9 8) (list token 0 4096)))
        (answer (fn-rxp-fill-range token 4097 nil 4097 provider)))
  (and (fn-rx-providerp provider) (> 4097 (fn-cbud-step-read-octets nil))
       (equal (mv-nth 0 answer) :receive-quantum-full)
       (equal (mv-nth 1 answer) 0) (equal (mv-nth 2 answer) 0)
       (equal (mv-nth 3 answer) 4097) (equal (mv-nth 4 answer) provider)))
 :rule-classes nil)
