(in-package "ACL2")
(include-book "../../books/receiver-provider")
; Logical shape teeth. Actual native exception/fence ordering is a separate
; composed caller obligation, not supplied by these constant models.
(defthm fn-rxp-fence-positive-literal
 (let* ((token '(:rx-capacity 0 0 4096))
        (provider (list '(9 8) (list token 0 4096)))
        (answer (fn-rxp-fence token provider))
        (next (mv-nth 1 answer))
        (again (fn-rxp-fence token next))
        (range (fn-rxp-fill-range token 16 nil 16 next)))
  (and (fn-rx-providerp provider) (fn-rxp-currentp token provider)
       (equal (mv-nth 0 answer) :receiver-fenced)
       (equal next (list '(9 8) (list token 0 nil)))
       (equal (fn-rxp-token next) token) (equal (fn-rxp-instance next) 0)
       (not (fn-rxp-currentp token next))
       (not (fn-rxc-uninitializedp (nth 1 next)))
       (equal (mv-nth 0 again) :receiver-unavailable)
       (equal (mv-nth 1 again) next)
       (equal (mv-nth 0 range) :receiver-unavailable)
       (equal (mv-nth 1 range) 0) (equal (mv-nth 2 range) 0)
       (equal (mv-nth 3 range) 16) (equal (mv-nth 4 range) next)))
 :rule-classes nil)
; Foreign-token mutation exclusion: the current provider remains ready.
(defthm fn-rxp-fence-foreign-token-literal
 (let* ((token '(:rx-capacity 0 0 4096))
        (foreign '(:rx-capacity 1 0 4096))
        (provider (list '(9 8) (list token 0 4096)))
        (answer (fn-rxp-fence foreign provider)))
  (and (fn-rx-providerp provider) (fn-rxp-currentp token provider)
       (not (fn-rxp-currentp foreign provider))
       (equal (mv-nth 0 answer) :receiver-unavailable)
       (equal (mv-nth 1 answer) provider)
       (fn-rxp-currentp token (mv-nth 1 answer))))
 :rule-classes nil)
