; Scalar/token fixtures, not a real accepted-history replay proof.
(in-package "ACL2")
(include-book "../../books/recovery-source-authority")
(defconst *rsa-ctx2* '(:ok 2 nil nil 0 :ordinary))
(defconst *rsa-root* (list :fn-store-checkpoint '(:row-a :row-b) nil *rsa-ctx2* nil nil nil))
(defconst *rsa-meta* (list :verified-checkpoint '(:checked-frame-plan) *rsa-root*
                         '(:summary-region 100 140 :R 1) '(2 (0 1 2)) 7 2))
(defun rsa-test-begin (ticket epoch generation meta)
 (mv-let (word next) (fn-rsa-begin ticket epoch generation meta) (list word next)))
(defun rsa-test-observe (c token epoch generation ctx fold)
 (mv-let (word next) (fn-rsa-observe c token epoch generation ctx fold) (list word next)))
(defun rsa-test-seal (c token epoch generation count frontier)
 (mv-let (word source next) (fn-rsa-seal c token epoch generation count frontier)
  (list word source next)))
(defconst *rsa-start* (nth 1 (rsa-test-begin 8 3 9 *rsa-meta*)))
(defconst *rsa-token0* (fn-rsa-token *rsa-start*))
(defconst *rsa-ctx4* '(:ok 4 nil nil 0 :ordinary))
(defconst *rsa-step* (nth 1 (rsa-test-observe *rsa-start* *rsa-token0* 3 9 *rsa-ctx4* 9)))
(assert-event
 (and (equal (nth 0 (rsa-test-begin 8 3 9 *rsa-meta*)) :issued)
      (equal *rsa-token0* '(:recovery-source 8 3 0))
      (equal (nth 0 (rsa-test-observe *rsa-start* *rsa-token0* 3 9 *rsa-ctx4* 9)) :counted)
      (equal (fn-omk-at 4 *rsa-step*) 4)
      (equal (fn-rsa-token *rsa-step*) '(:recovery-source 8 3 1))
      (equal (fn-omk-at 3 *rsa-step*) *rsa-meta*)))
(assert-event
 (and (equal (nth 0 (rsa-test-observe *rsa-step* *rsa-token0* 3 9 *rsa-ctx4* 9)) :refused)
      (equal (nth 1 (rsa-test-observe *rsa-step* *rsa-token0* 3 9 *rsa-ctx4* 9)) *rsa-step*)
      (equal (nth 0 (rsa-test-observe *rsa-start* *rsa-token0* 4 9 *rsa-ctx4* 9)) :refused)
      (equal (nth 0 (rsa-test-observe *rsa-start* *rsa-token0* 3 10 *rsa-ctx4* 9)) :refused)
      (equal (nth 0 (rsa-test-seal *rsa-step* (fn-rsa-token *rsa-step*) 3 9 5 9)) :refused)))
(assert-event
 (let ((sealed (rsa-test-seal *rsa-step* (fn-rsa-token *rsa-step*) 3 9 4 9)))
  (and (equal (nth 0 sealed) :sealed)
       (equal (nth 1 sealed) '(9 (8 4) 0 0))
       (equal (nth 0 (rsa-test-seal (nth 2 sealed) (fn-rsa-token *rsa-step*) 3 9 4 9))
              :refused))))
(assert-event
 (and (not (fn-rsa-regionp '(:summary-region 100 140 :R 2)))
      (not (fn-rsa-regionp '(:summary-region 140 100 :R 1)))
      (equal (nth 0 (rsa-test-begin 8 3 9 nil)) :refused)))
