; Unfunded local-stobj storage fixture. The cursor is seeded deliberately;
; this does not supply an actual epilogue, installed BODY or release authority.
(in-package "ACL2")
(include-book "../../books/render-window-terminal-slot")

(defun fn-prwt-slot-storage-fixture (fn-ibp-query-segment fn-page-read-pool)
 (declare (xargs :stobjs (fn-ibp-query-segment fn-page-read-pool) :guard t))
 (let* ((token '(:index-query 29 1 0 1))
        (window '(:window 17 3 0 200 0 100 5 55))
        (rows (list (list '(:window 18 3 0 200 0 100 5 55) nil :window :running)
                    (list window nil :window :returned)))
        (root (list :render-window window :source :recipient token :origin 4))
        (cursor (fn-prwt-start root 7 rows))
        (custody (list :receiver-custody :source :recipient nil 0 0 :held
                       token :rh nil nil cursor))
        (context (list :reader-context nil nil nil nil nil nil nil nil custody))
        (data (list nil nil nil nil nil 7))
        (fn-page-read-pool (update-fn-prp-data data fn-page-read-pool))
        (fn-ibp-query-segment (update-fn-ibp-qs-id 1 fn-ibp-query-segment))
        (fn-ibp-query-segment (update-fn-ibp-qs-ticketsi 0 29 fn-ibp-query-segment))
        (fn-ibp-query-segment (update-fn-ibp-qs-capturesi 0 '(:capture 1) fn-ibp-query-segment))
        (fn-ibp-query-segment (update-fn-ibp-qs-controlsi 0 '(:fn-ibr 29 1) fn-ibp-query-segment))
        (fn-ibp-query-segment (update-fn-ibp-qs-inputsi 0 context fn-ibp-query-segment)))
  (mv-let (word receipt left fn-ibp-query-segment fn-page-read-pool)
   (fn-prwt-slot-step token 2 fn-ibp-query-segment fn-page-read-pool)
   (let* ((current (fn-ibp-qs-inputsi 0 fn-ibp-query-segment))
          (held (fn-prl-nth 11 (fn-prl-nth 9 current)))
          (first (and (eq word :yield) (not receipt) (equal left 0)
                      (equal (fn-prl-nth 3 held) rows)
                      (equal (fn-prl-nth 9 held) root)
                      (equal (fn-prp-data fn-page-read-pool) data))))
    (mv-let (word receipt left fn-ibp-query-segment fn-page-read-pool)
     (fn-prwt-slot-step token 8 fn-ibp-query-segment fn-page-read-pool)
     (let ((ready (fn-ibp-qs-inputsi 0 fn-ibp-query-segment)))
      (mv-let (again receipt2 left2 fn-ibp-query-segment fn-page-read-pool)
       (fn-prwt-slot-step token 8 fn-ibp-query-segment fn-page-read-pool)
       (mv (and first (eq word :commit-unavailable) (not receipt)
                (equal left 3) (eq again :commit-unavailable) (not receipt2)
                (equal left2 8)
                (equal (fn-ibp-qs-inputsi 0 fn-ibp-query-segment) ready)
                (equal (fn-prp-data fn-page-read-pool) data))
           fn-ibp-query-segment fn-page-read-pool))))))))

(defun fn-prwt-slot-storage-local ()
 (declare (xargs :guard t))
 (with-local-stobj fn-ibp-query-segment
  (mv-let (ok fn-ibp-query-segment)
   (with-local-stobj fn-page-read-pool
    (mv-let (ok fn-ibp-query-segment fn-page-read-pool)
     (fn-prwt-slot-storage-fixture fn-ibp-query-segment fn-page-read-pool)
     (mv ok fn-ibp-query-segment)))
   ok)))

(assert-event (fn-prwt-slot-storage-local))
