(in-package "ACL2")
(include-book "../../books/replay-produced-size")
(include-book "../../books/statement-attach")
(defun ript-fields (xs)
 (if (consp xs) (cons (fn-scs-summary (car xs)) (ript-fields (cdr xs))) nil))
(defconst *ript-ctx* (fn-stxk-initial-context 0))
(defconst *ript-snapshot* (fn-stxk-make 0 1 1 0 '(1) '(7 8)))
(defun ript-positive ()
 (mv-let (checked fields status)
  (fn-ris-produced-step *ript-ctx* (ript-fields *ript-ctx*)
                        *ript-snapshot* (fn-scs-summary *ript-snapshot*))
  (and (equal checked (fn-replay-identity-step *ript-ctx* *ript-snapshot*))
       (eq status :carried) (fn-scs-correspondsp fields checked))))
(assert-event (ript-positive))
(defun ript-missing ()
 (mv-let (checked fields status)
  (fn-ris-produced-step *ript-ctx* nil *ript-snapshot* nil)
  (and (equal checked (fn-replay-identity-step *ript-ctx* *ript-snapshot*))
       (eq status :unavailable) (null fields))))
(assert-event (ript-missing))
(defun ript-corrupt-context ()
 (mv-let (checked fields status)
  (fn-ris-produced-step '(bad ctx) nil *ript-snapshot* nil)
  (and (equal checked (fn-replay-identity-step '(bad ctx) *ript-snapshot*))
       (eq status :unavailable) (null fields))))
(assert-event (ript-corrupt-context))
(defconst *ript-verdict* (fn-stxe-make 1 2 2 "<a@x>" :unverified '(9) 0 '(1)))
(defun ript-child-parser-carry ()
 (mv-let (r sizes) (fn-stxs-decode (fn-stxe-encode *ript-verdict*))
  (and (fn-stmt-okp r)
       (equal (fn-rips-verdict-carry (fn-stmt-value r) sizes)
              (fn-scs-summary *ript-verdict*)))))
(assert-event (ript-child-parser-carry))
