(in-package "ACL2")
(include-book "../../books/resource-operation")

(defconst *fn-rot-budget* '(100 100 10 10 10 10 10 10 100))
(defconst *fn-rot-baseline* '(5 0 0 0 0 0 0 0 0))
(defconst *fn-rot-reserve* '(10 0 0 0 0 0 0 0 10))
(defconst *fn-rot-user* '(50 0 2 0 0 0 0 0 20))
(defconst *fn-rot-gate* '(2 0 0 0 0 0 0 0 1))
(defconst *fn-rot-demand* '(10 0 1 0 0 0 0 0 2))
(defconst *fn-rot-output* '(4 0 0 0 0 0 0 0 0))
(defconst *fn-rot-installed*
  (fn-rop-install *fn-rot-budget* *fn-rot-baseline* *fn-rot-reserve* 4 2))
(assert-event (and (eq (car *fn-rot-installed*) :installed)
                   (fn-rt-okp (cadr *fn-rot-installed*))
                   (equal (fn-rv-demand 0 (fn-rt-root (cadr *fn-rot-installed*)))
                          *fn-rot-baseline*)
                   (equal (fn-rv-demand 1 (fn-rt-root (cadr *fn-rot-installed*)))
                          *fn-rot-reserve*)))
(defconst *fn-rot-opened*
  (fn-rop-open (cadr *fn-rot-installed*) 2 *fn-rot-user* 3))
(assert-event (and (eq (car *fn-rot-opened*) :opened)
                   (equal (caddr *fn-rot-opened*) '(2 . 1))
                   (fn-rt-okp (cadr *fn-rot-opened*))))
(assert-event (equal (fn-rop-open (cadr *fn-rot-installed*) 1 *fn-rot-user* 3)
                     (list :reserved-owner-slot (cadr *fn-rot-installed*))))
(defconst *fn-rot-admitted*
  (fn-rop-admit (cadr *fn-rot-opened*) (caddr *fn-rot-opened*)
                0 *fn-rot-gate* 1 *fn-rot-demand*))
(assert-event (and (eq (car *fn-rot-admitted*) :drawn)
                   (fn-rt-okp (cadr *fn-rot-admitted*))
                   (fn-rop-token-livep (cadr *fn-rot-admitted*) (nth 2 *fn-rot-admitted*))
                   (fn-rop-token-livep (cadr *fn-rot-admitted*) (nth 3 *fn-rot-admitted*))
                   (equal (fn-rt-root (cadr *fn-rot-admitted*))
                          (fn-rt-root (cadr *fn-rot-opened*)))
                   (equal (fn-rv-drawn (fn-rt-sub 2 (cadr *fn-rot-admitted*)))
                          (fn-rv-plus *fn-rot-gate* *fn-rot-demand*))))
(assert-event
 (and (equal (fn-rop-timeout (cadr *fn-rot-admitted*) (nth 3 *fn-rot-admitted*))
             (list :pending (cadr *fn-rot-admitted*)))
      (equal (fn-rop-complete (cadr *fn-rot-admitted*) (nth 3 *fn-rot-admitted*)
                             nil *fn-rv-zero*)
             (list :pending (cadr *fn-rot-admitted*)))
      (equal (fn-rop-close (cadr *fn-rot-admitted*) (caddr *fn-rot-opened*))
             (list :pending (cadr *fn-rot-admitted*)))))
(defconst *fn-rot-retained*
  (fn-rop-complete (cadr *fn-rot-admitted*) (nth 3 *fn-rot-admitted*) t *fn-rot-output*))
(assert-event (and (eq (car *fn-rot-retained*) :retained)
                   (fn-rt-okp (cadr *fn-rot-retained*))
                   (fn-rop-token-livep (cadr *fn-rot-retained*) (nth 3 *fn-rot-admitted*))
                   (equal (fn-rv-drawn (fn-rt-sub 2 (cadr *fn-rot-retained*)))
                          '(6 0 0 0 0 0 0 0 3))
                   (eq (car (fn-rop-close (cadr *fn-rot-retained*) (caddr *fn-rot-opened*)))
                       :pending)))
(assert-event (equal (fn-rop-release (cadr *fn-rot-retained*) (nth 3 *fn-rot-admitted*) t nil)
                     (list :pending (cadr *fn-rot-retained*))))
(defconst *fn-rot-released*
  (fn-rop-release (cadr *fn-rot-retained*) (nth 3 *fn-rot-admitted*) t t))
(assert-event (and (eq (car *fn-rot-released*) :settled)
                   (equal (fn-rv-drawn (fn-rt-sub 2 (cadr *fn-rot-released*)))
                          '(2 0 0 0 0 0 0 0 3))
                   (equal (fn-rop-release (cadr *fn-rot-released*)
                                           (nth 3 *fn-rot-admitted*) t t)
                          (list :stale (cadr *fn-rot-released*)))))
(defconst *fn-rot-gate-released*
  (fn-rop-release (cadr *fn-rot-released*) (nth 2 *fn-rot-admitted*) t t))
(defconst *fn-rot-closed*
  (fn-rop-close (cadr *fn-rot-gate-released*) (caddr *fn-rot-opened*)))
(assert-event (and (eq (car *fn-rot-closed*) :destroyed)
                   (fn-rt-okp (cadr *fn-rot-closed*))
                   (equal (fn-rv-drawn (fn-rt-root (cadr *fn-rot-closed*)))
                          '(15 0 0 0 0 0 0 0 13))
                   (equal (fn-rop-release (cadr *fn-rot-closed*)
                                           (nth 2 *fn-rot-admitted*) t t)
                          (list :stale (cadr *fn-rot-closed*)))))

; Refused work still consumes the already funded gate's :work; nothing
; returns from the owner rescue and no operation draw token is issued.
(defconst *fn-rot-denied*
  (fn-rop-admit (cadr *fn-rot-opened*) (caddr *fn-rot-opened*)
                0 *fn-rot-gate* 1 '(100 0 0 0 0 0 0 0 2)))
(assert-event (and (eq (car *fn-rot-denied*) :resources-unavailable)
                   (null (nth 3 *fn-rot-denied*))
                   (fn-rop-token-livep (cadr *fn-rot-denied*) (nth 2 *fn-rot-denied*))
                   (equal (fn-rv-drawn (fn-rt-sub 2 (cadr *fn-rot-denied*)))
                          *fn-rot-gate*)
                   (equal (fn-rt-root (cadr *fn-rot-denied*))
                          (fn-rt-root (cadr *fn-rot-opened*)))))
(assert-event
 (let ((r (fn-rop-release (cadr *fn-rot-denied*) (nth 2 *fn-rot-denied*) t t)))
   (and (eq (car r) :settled)
        (equal (fn-rv-drawn (fn-rt-sub 2 (cadr r))) '(0 0 0 0 0 0 0 0 1)))))
(assert-event
 (equal (fn-rop-admit (cadr *fn-rot-opened*) (caddr *fn-rot-opened*)
                      0 '(100 0 0 0 0 0 0 0 1) 1 *fn-rot-demand*)
        (list :resources-unavailable (cadr *fn-rot-opened*) nil nil)))
