; Default compiler fallback teeth. No positive compiler table is fabricated.
(in-package "ACL2")
(include-book "../../books/runtime-bootstrap-admission")
(include-book "../../books/recovery-prs-install")
(include-book "../../books/runtime-bootstrap-turn-installation")
(defthm fn-bge-default-compiler-case-1
 (and (not *fn-runtime-operation-compiled-binding*)
      (mv-let (word capsule installation suffix) (fn-rbcp-request)
       (and (eq word :runtime-bootstrap-source-unavailable)
            (not capsule) (not installation) (not suffix)))) :rule-classes nil)
(defthm fn-bge-default-compiler-case-2
 (let ((pool (create-fn-page-read-pool)))
  (and (fn-rbc-virgin-poolp pool)
       (mv-let (word outcome next)
         (fn-owner-runtime-bootstrap-admit :qualification-request 0 0 0 pool)
         (and (eq word :runtime-qualification-unavailable) (eq outcome :refused) (equal next pool)))
       (mv-let (word outcome next)
         (fn-owner-runtime-bootstrap-admit :completed 513 4096 2101248 pool)
         (and (eq word :runtime-qualification-unavailable) (eq outcome :refused) (equal next pool))))) :rule-classes nil)
(defthm fn-bge-default-compiler-case-3
 (let* ((pool (create-fn-page-read-pool))
        (fenced (update-fn-prp-alloc-mode (fn-aec-uncertain) pool)))
  (and (not (fn-rbc-virgin-poolp fenced))
       (mv-let (word outcome next)
         (fn-owner-runtime-bootstrap-admit :completed 513 4096 2101248 fenced)
         (and (eq word :runtime-bootstrap-already-attempted) (eq outcome :fenced) (equal next fenced))))) :rule-classes nil)
(defthm fn-bge-default-compiler-case-4
 (let ((pool (create-fn-page-read-pool))
       (slots (create-fn-allocation-turn-slots)))
  (and (equal (fn-ats-kinds-length slots) 1)
       (equal (fn-ats-nonces-length slots) 1)
       (equal (fn-ats-phases-length slots) 1)
       (mv-let (word next) (fn-owner-runtime-ats-construct-internal slots pool)
         (and (eq word :runtime-turn-source-unavailable) (equal next slots))))) :rule-classes nil)
