(in-package "ACL2")
(include-book "../../books/assumptions-selected-runtime-initializer-register")
(assert-event (mv-let (word bytes requests)
 (fn-srir-primary-object-request 19 32768 *fn-srir-coordinate*)
 (and (fn-srir-domain-p 19 32768 *fn-srir-coordinate*)
      (eq word :primary-object) (equal bytes 0) (equal requests 0))))
(assert-event (mv-let (word bytes requests)
 (fn-srir-primary-object-request 0 0 *fn-srir-coordinate*)
 (and (fn-srir-domain-p 0 0 *fn-srir-coordinate*)
      (eq word :primary-object) (equal bytes 0) (equal requests 0))))
; Scalar domain refusal tests; not platform assumption counterexamples.
(assert-event (and (natp 20) (natp 0) (<= 0 32768)
 (not (< 20 20)) (not (fn-srir-domain-p 20 0 *fn-srir-coordinate*))))
(assert-event (and (< -1 20) (natp 0) (<= 0 32768)
 (not (natp -1)) (not (fn-srir-domain-p -1 0 *fn-srir-coordinate*))))
(assert-event (and (natp 0) (< 0 20) (<= -1 32768)
 (not (natp -1)) (not (fn-srir-domain-p 0 -1 *fn-srir-coordinate*))))
(assert-event (and (natp 0) (< 0 20) (natp 32769)
 (not (<= 32769 32768)) (not (fn-srir-domain-p 0 32769 *fn-srir-coordinate*))))
(assert-event (and (natp 0) (< 0 20) (natp 0) (<= 0 32768)
 (not (equal :corrupt *fn-srir-coordinate*))
 (not (fn-srir-domain-p 0 0 :corrupt))))

; Guard-only standalone unit models; actual initializer trajectory joins separately.
(encapsulate ()
 (local (defun srir-t-model (i v c) (if (fn-srir-domain-p i v c) 0 1)))
 (local (assert-event (and (fn-srir-domain-p 18 32768 *fn-srir-coordinate*)
                          (equal (srir-t-model 18 32768 *fn-srir-coordinate*) 0))))
 (local (assert-event (and (not (equal :corrupt *fn-srir-coordinate*))
  (natp 0)
  (< 0 20)
  (natp 0)
  (<= 0 32768)
  (not (equal (srir-t-model 0 0 :corrupt) 0)))))
 (local (assert-event (and (equal *fn-srir-coordinate* *fn-srir-coordinate*)
  (not (natp -1))
  (< -1 20)
  (natp 0)
  (<= 0 32768)
  (not (equal (srir-t-model -1 0 *fn-srir-coordinate*) 0)))))
 (local (assert-event (and (equal *fn-srir-coordinate* *fn-srir-coordinate*)
  (natp 20)
  (not (< 20 20))
  (natp 0)
  (<= 0 32768)
  (not (equal (srir-t-model 20 0 *fn-srir-coordinate*) 0)))))
 (local (assert-event (and (equal *fn-srir-coordinate* *fn-srir-coordinate*)
  (natp 0)
  (< 0 20)
  (not (natp -1))
  (<= -1 32768)
  (not (equal (srir-t-model 0 -1 *fn-srir-coordinate*) 0)))))
 (local (assert-event (and (equal *fn-srir-coordinate* *fn-srir-coordinate*)
  (natp 0)
  (< 0 20)
  (natp 32769)
  (not (<= 32769 32768))
  (not (equal (srir-t-model 0 32769 *fn-srir-coordinate*) 0)))))
)
