(in-package "ACL2")
(include-book "../../books/assumptions-selected-runtime-bp-creators")
(assert-event (and (fn-srbc-domain-p :record12 *fn-srbc-coordinate*)
 (equal (mv-list 4 (fn-srbc-constructor-object-request :record12 *fn-srbc-coordinate*))
        '(:creator-objects 144 2 144))))
(assert-event (and (fn-srbc-domain-p :digest16 *fn-srbc-coordinate*)
 (equal (mv-list 4 (fn-srbc-constructor-object-request :digest16 *fn-srbc-coordinate*))
        '(:creator-objects 672 2 672))))
(assert-event (and (fn-srbc-domain-p :carry6 *fn-srbc-coordinate*)
 (equal (mv-list 4 (fn-srbc-constructor-object-request :carry6 *fn-srbc-coordinate*))
        '(:creator-objects 64 1 64))))
(assert-event (and (fn-srbc-domain-p :node16 *fn-srbc-coordinate*)
 (equal (mv-list 4 (fn-srbc-constructor-object-request :node16 *fn-srbc-coordinate*))
        '(:creator-objects 704 10 608))))
(assert-event (and (not (fn-srbc-domain-p :node16 :wrong-coordinate))
 (equal (mv-list 4 (fn-srbc-constructor-object-request :node16 :wrong-coordinate))
        '(:unavailable nil nil nil))))
(assert-event (and (not (fn-srbc-domain-p :record11 *fn-srbc-coordinate*))
 (equal (mv-list 4 (fn-srbc-constructor-object-request :record11 *fn-srbc-coordinate*))
        '(:unavailable nil nil nil))))
; Explicit local-model counterexamples, not physical constructor executions.
(defun srbc-t-removal-model (kind coordinate)
 (if (fn-srbc-domain-p kind coordinate) (fn-srbc-allocated-octets kind)
  (+ 1 (fn-srbc-allocated-octets kind))))
(assert-event (and (not (fn-srbc-domain-p :node16 :wrong-coordinate))
 (> (srbc-t-removal-model :node16 :wrong-coordinate) (fn-srbc-allocated-octets :node16))))
(assert-event (and (equal *fn-srbc-coordinate* *fn-srbc-coordinate*)
 (not (fn-srbc-unitp :record11))
 (> (srbc-t-removal-model :record11 *fn-srbc-coordinate*) (fn-srbc-allocated-octets :record11))))
