(in-package "ACL2")
(include-book "../../books/assumptions-selected-runtime-octets-resize")
; Local executable model only; opaque assumption is not a runtime observation.
(assert-event (and (fn-sror-resize-domain-p 64 0 *fn-sror-coordinate*)
                  (equal (fn-sror-primary-request 64) 80)))
(assert-event (and (fn-sror-resize-domain-p 3494 10 *fn-sror-coordinate*)
                  (equal (fn-sror-primary-request 3494) 3520)))
(assert-event (and (fn-sror-resize-domain-p 65536 65535 *fn-sror-coordinate*)
                  (equal (fn-sror-primary-request 65536) 65552)))
(assert-event (mv-let (word bytes count)
 (fn-sror-success-object-request 65536 0 *fn-sror-coordinate*)
 (and (eq word :primary-object) (equal bytes 65552) (equal count 1))))
(assert-event (mv-let (word bytes count)
 (fn-sror-success-object-request 64 64 *fn-sror-coordinate*)
 (and (eq word :unavailable) (null bytes) (null count))))

; Model-only retained-clause removals: every other scalar clause is affirmative.
(assert-event (and (equal *fn-sror-coordinate* *fn-sror-coordinate*)
 (natp 0) (< 0 128) (not (member-equal 128 '(64 3494 65536)))
 (not (fn-sror-resize-domain-p 128 0 *fn-sror-coordinate*))))
(assert-event (and (member-equal 64 '(64 3494 65536)) (< -1 64)
 (not (natp -1)) (not (fn-sror-resize-domain-p 64 -1 *fn-sror-coordinate*))))
(assert-event (and (member-equal 64 '(64 3494 65536)) (natp 64)
 (not (< 64 64)) (not (fn-sror-resize-domain-p 64 64 *fn-sror-coordinate*))))
(assert-event (and (member-equal 64 '(64 3494 65536)) (natp 0) (< 0 64)
 (not (equal :corrupt *fn-sror-coordinate*))
 (not (fn-sror-resize-domain-p 64 0 :corrupt))))
