(in-package "ACL2")
(include-book "../../books/served-plan-position-window")

(defconst *sppwt-plan*
 '(nil (:log accepted) (:retain source) (:reply (49 50 51))
       (:over-cursor ("fn.test" 1 100000 7 nil t)) (:close)))

(defthm sppwt-positioned-original-window-positive
 (let* ((p (mv-nth 1 (fn-spp-tick (fn-spp-begin *sppwt-plan* :origin :funded) 2)))
        (fn-octets nil) (actual (fn-spp-window p 2 fn-octets))
        (original (fn-splan-window (fn-spp-active-plan p) 2 fn-octets))
        (next (mv-nth 1 actual)))
  (and (equal (fn-spp-status p) :reply) (posp 2)
       (<= 2 (fn-spp-window-size p))
       (equal (mv-nth 0 actual) (mv-nth 0 original))
       (equal (mv-nth 2 actual) (mv-nth 2 original))
       (equal (fn-spp-active-plan next) (mv-nth 1 original))
       (equal (mv-nth 0 actual) :ok) (equal (mv-nth 2 actual) '(49 50))
       (equal (fn-spp-cur next) '(51))
       (equal (fn-spp-prefix next) (fn-spp-prefix p))
       (equal (fn-spp-origin next) (fn-spp-origin p))
       (equal (fn-spp-resource next) (fn-spp-resource p))
       (equal (fn-spp-rest next) (cdr (fn-spp-rest p)))
       (equal (fn-spp-plan next)
        '((51) (:log accepted) (:retain source)
               (:over-cursor ("fn.test" 1 100000 7 nil t)) (:close)))))
 :rule-classes nil)

 ; Reply-status premise removed after proving the stronger tail theorem.
(defthm sppwt-unrecognized-holder-stronger-tail-positive
 (let ((p '(:other (49) nil ((:reply (50)) (:close)) :origin :funded))
       (fn-octets nil))
  (and (not (equal (fn-spp-status p) :reply)) (posp 1)
       (<= 1 (fn-spp-window-size p))
       (equal (fn-spp-rest (mv-nth 1 (fn-spp-window p 1 fn-octets)))
              (if (consp (fn-spp-cur p)) (fn-spp-rest p)
               (fn-ag-cdr (fn-spp-rest p))))))
 :rule-classes nil)

(defthm sppwt-window-without-positive-size-corrupted-state
 (let* ((p (mv-nth 1 (fn-spp-tick (fn-spp-begin *sppwt-plan* :origin :funded) 2)))
        (fn-octets nil))
  (and (equal (fn-spp-status p) :reply) (not (posp 0))
       (<= 0 (fn-spp-window-size p))
       (not (equal (fn-spp-rest (mv-nth 1 (fn-spp-window p 0 fn-octets)))
                   (if (consp (fn-spp-cur p)) (fn-spp-rest p)
                    (fn-ag-cdr (fn-spp-rest p)))))))
 :rule-classes nil)

(defthm sppwt-window-without-head-bound-corrupted-state
 (let* ((p (fn-spp-begin '(nil (:reply (49)) (:log retained) (:reply (50))) :origin :funded))
        (fn-octets nil))
  (and (equal (fn-spp-status p) :reply) (posp 2)
       (not (<= 2 (fn-spp-window-size p)))
       (not (equal (fn-spp-rest (mv-nth 1 (fn-spp-window p 2 fn-octets)))
                   (if (consp (fn-spp-cur p)) (fn-spp-rest p)
                    (fn-ag-cdr (fn-spp-rest p)))))))
 :rule-classes nil)

(defun sppwt-actual-buffer-windows (fn-octets)
 (declare (xargs :stobjs fn-octets :verify-guards nil))
 (mv-let (position-status p work)
   (fn-spp-tick (fn-spp-begin *sppwt-plan* :origin :funded) 2)
  (declare (ignore position-status work))
  (mv-let (status p1 fn-octets) (fn-spp-window p 2 fn-octets)
   (let ((first-good (and (eq status :ok) (equal (fn-octets-len fn-octets) 2)
                          (equal (fn-octets-get 0 fn-octets) 49)
                          (equal (fn-octets-get 1 fn-octets) 50))))
    (mv-let (status p2 fn-octets) (fn-spp-window p1 1 fn-octets)
     (mv (and first-good (eq status :ok) (equal (fn-octets-len fn-octets) 1)
               (equal (fn-octets-get 0 fn-octets) 51)
               (eq (fn-spp-status p2) :cursor)
               (equal (fn-spp-prefix p2) '((:retain source) (:log accepted)))
               (equal (fn-spp-origin p2) :origin) (equal (fn-spp-resource p2) :funded))
          fn-octets))))))

(assert-event (mv-let (good fn-octets) (sppwt-actual-buffer-windows fn-octets)
                (mv good fn-octets)) :stobjs-out '(nil fn-octets))
