(in-package "ACL2")
(include-book "../../books/snapshot-source-cursor")
(defconst *osrc-suffix* '(:snoc 2 second first))
(defconst *osrc-source* '(:hrs-based (:hrs-handle file root 0 1 (8 8 8 8 8) (1 2 3 4 5) 6) :snoc 2 second first))
(defconst *osrc-0* (fn-osrc-begin *osrc-source* 3 'epoch '(8 3)))
(defconst *osrc-1* (cadr (fn-osrc-tick *osrc-0* nil)))
(defconst *osrc-2* (cadr (fn-osrc-tick *osrc-1* nil)))
(defconst *osrc-3* (cadr (fn-osrc-tick *osrc-2* nil)))
(defconst *osrc-need* (fn-osrc-tick *osrc-3* nil))
(defconst *osrc-wait* (fn-osrc-at 4 *osrc-need*))
(defconst *osrc-token* (fn-osrc-token *osrc-wait*))
(assert-event
 (and (equal (fn-osrc-at 0 *osrc-0*) :reverse)
      (posp (fn-osrc-at 6 *osrc-0*)) (consp (fn-osrc-at 7 *osrc-0*))
      (equal (car (fn-osrc-tick *osrc-0* nil)) :yield)
      (equal (fn-osrc-at 6 *osrc-1*) (1- (fn-osrc-at 6 *osrc-0*)))
      (equal (fn-osrc-at 7 *osrc-1*) (cdr (fn-osrc-at 7 *osrc-0*)))
      (equal (fn-osrc-at 8 *osrc-1*)
             (cons (car (fn-osrc-at 7 *osrc-0*)) (fn-osrc-at 8 *osrc-0*)))))
(assert-event (equal (fn-osrc-at 8 *osrc-2*) '(first second)))
(assert-event (equal *osrc-need* (list :need-row 0 '(:hrs-handle file root 0 1 (8 8 8 8 8) (1 2 3 4 5) 6)
                                    '(epoch (8 3) 0 0) *osrc-wait*)))
(assert-event
 (let* ((obs (list :decoded *osrc-token* '(:atom original)))
        (result (fn-osrc-tick *osrc-wait* obs))
        (next (fn-osrc-at 4 result)))
   (and (equal (fn-osrc-at 0 *osrc-wait*) :waiting)
        (consp obs) (equal (car obs) :decoded)
        (equal (fn-osrc-at 1 obs) (fn-osrc-token *osrc-wait*))
        (equal (car result) :row)
        (equal (fn-osrc-at 2 next) (1+ (fn-osrc-at 2 *osrc-wait*)))
        (equal (fn-osrc-at 1 next) (fn-osrc-at 1 *osrc-wait*))
        (equal (fn-osrc-at 3 next) (fn-osrc-at 3 *osrc-wait*))
        (equal (fn-osrc-at 5 next) (fn-osrc-at 5 *osrc-wait*))
        (equal (fn-osrc-at 9 next) (fn-osrc-at 9 *osrc-wait*))
        (equal (fn-osrc-at 10 next) (fn-osrc-at 10 *osrc-wait*)))))
; Stale lease completion: retained phase/opcode/ordinal/epoch, token differs.
(assert-event
 (let ((obs '(:decoded (epoch (7 3) 0 0) (:atom original))))
   (and (equal (fn-osrc-at 0 *osrc-wait*) :waiting)
        (consp obs) (equal (car obs) :decoded)
        (not (equal (fn-osrc-at 1 obs) (fn-osrc-token *osrc-wait*)))
        (not (equal (car (fn-osrc-tick *osrc-wait* obs)) :row))
        (equal (fn-osrc-at 2 (fn-osrc-tick *osrc-wait* obs)) *osrc-wait*))))
(defconst *osrc-prefix-row* (fn-osrc-tick *osrc-wait* (list :decoded *osrc-token* '(:atom original))))
(defconst *osrc-suffix-start* (cadr (fn-osrc-tick (fn-osrc-at 4 *osrc-prefix-row*) nil)))
(defconst *osrc-first* (fn-osrc-tick *osrc-suffix-start* nil))
(defconst *osrc-second* (fn-osrc-tick (fn-osrc-at 4 *osrc-first*) nil))
(assert-event (equal (fn-osrc-at 2 *osrc-first*) '(:resident first)))
(assert-event (equal (fn-osrc-at 2 *osrc-second*) '(:resident second)))
(assert-event (equal (fn-osrc-tick (fn-osrc-at 4 *osrc-second*) nil)
                     '(:done (epoch (8 3) 0 3))))
; Duplicate ordinal cannot advance the next prefix request's token.
(assert-event (equal (fn-osrc-tick (fn-osrc-at 4 *osrc-prefix-row*)
                                 (list :decoded *osrc-token* '(:atom original)))
                     (list :yield *osrc-suffix-start*)))
; Malformed captures are separate from valid-provider correspondence.
(assert-event (equal (fn-osrc-tick (fn-osrc-begin '(:snoc 2 first) 2 'epoch 'lease) nil)
                     '(:yield (:reverse (:snoc 2 first) 0 2 0 nil 1 nil (first) epoch lease nil 0))))

(assert-event (and (natp 3) (fn-osrc-guardp *osrc-0*)))
(assert-event
 (and (fn-osrc-guardp *osrc-0*)
      (equal (car (fn-osrc-tick *osrc-0* nil)) :yield)
      (fn-osrc-guardp (fn-osrc-at 1 (fn-osrc-tick *osrc-0* nil)))))
(assert-event
 (let ((result (fn-osrc-tick *osrc-wait* (list :decoded *osrc-token* '(:atom original)))))
   (and (fn-osrc-guardp *osrc-wait*)
        (member-equal (car result) '(:need-row :row))
        (fn-osrc-guardp (fn-osrc-at 4 result)))))

(assert-event
 (let* ((drained (fn-osrc-at 4 *osrc-second*))
        (restarted (fn-osrc-restart drained)) (cursor (cadr restarted)))
   (and (equal (car restarted) :restarted)
        (equal (fn-osrc-at 2 cursor) 0)
        (equal (fn-osrc-at 8 cursor) '(first second))
        (equal (fn-osrc-at 11 cursor) '(first second))
        (equal (fn-osrc-at 1 cursor) *osrc-source*)
        (equal (fn-osrc-token cursor) '(epoch (8 3) 1 0))
        (equal (car (fn-osrc-tick cursor nil)) :need-row))))
(assert-event (equal (fn-osrc-restart *osrc-0*)
                     (list :refused :source-not-drained *osrc-0*)))

; Prior-pass sameordinal completion is now stale after restart, even though
; the source/epoch/lease are intentionally shared across all column passes.
(assert-event
 (let* ((old (fn-osrc-at 4 *osrc-second*))
        (restarted (cadr (fn-osrc-restart old)))
        (need (fn-osrc-tick restarted nil))
        (waiting (fn-osrc-at 4 need))
        (stale (fn-osrc-tick waiting (list :decoded *osrc-token* '(:atom original)))))
   (and (fn-osrc-guardp old)
        (equal (car (fn-osrc-restart old)) :restarted)
        (fn-osrc-guardp restarted)
        (equal (fn-osrc-at 12 restarted) (1+ (fn-osrc-at 12 old)))
        (equal (fn-osrc-at 2 restarted) 0)
        (equal (fn-osrc-at 1 restarted) (fn-osrc-at 1 old))
        (equal (fn-osrc-at 9 restarted) (fn-osrc-at 9 old))
        (equal (fn-osrc-at 10 restarted) (fn-osrc-at 10 old))
        (equal (fn-osrc-at 8 restarted) (fn-osrc-at 11 old))
        (equal (car need) :need-row)
        (not (equal *osrc-token* (fn-osrc-token waiting)))
        (equal stale (list :refused :row-completion waiting)))))
(assert-event (equal (fn-osrc-restart *osrc-wait*)
                     (list :refused :source-not-drained *osrc-wait*)))
