(in-package "ACL2")
(include-book "../../books/snapshot-message-key")
(defun omkt-list (nodes)
  (if (consp nodes) (fn-hdc-pair (car nodes) (omkt-list (cdr nodes)))
    (fn-hdc-atom nil)))
(defconst *omkt-token* '(7 (8 3) 0 0))
(defconst *omkt-lease* '(:maintenance 9 7 2))
; The generic current tree decoder permits these nodes; Store semantic
; grammar and root-authenticated span correspondence remain separate joins.
(defconst *omkt-node* (omkt-list
 (list (fn-hdc-atom 1) (fn-hdc-atom 0) (fn-hdc-atom 0)
       (fn-hdc-span 3 0 10 5) (fn-hdc-atom 7)
       (fn-hdc-atom nil) (fn-hdc-atom 0) (fn-hdc-atom 0)
       (fn-hdc-atom nil) (fn-hdc-atom 0) (fn-hdc-atom 0)
       (fn-hdc-atom nil) (fn-hdc-atom nil) (fn-hdc-atom nil) (fn-hdc-atom nil))))
(defconst *omkt-source* (list :decoded *omkt-node*))
(defconst *omkt-begin* (fn-omk-begin *omkt-source* 0 *omkt-token* *omkt-lease*))
(defconst *omkt-c* (cadr *omkt-begin*))
(defconst *omkt-o* (list :byte *omkt-token* 10 60))
(assert-event
 (and (unsigned-byte-p 32 0) (equal (car *omkt-begin*) :begun)
      (fn-omk-guardp *omkt-c*)
      (equal (fn-omk-message-source *omkt-source*) '(:span 10 5))
      (equal (fn-omk-tick *omkt-c* nil) (list :need-byte 10 *omkt-token* *omkt-c*))))
(assert-event
 (and (fn-omk-guardp *omkt-c*) (equal (fn-omk-at 0 *omkt-c*) :span)
      (< (fn-omk-at 3 *omkt-c*) (fn-omk-at 4 *omkt-c*))
      (fn-omk-widthp *omkt-o* 4) (equal (car *omkt-o*) :byte)
      (fn-omk-token-matchp (fn-omk-at 1 *omkt-o*) (fn-omk-at 6 *omkt-c*))
      (equal (fn-omk-at 2 *omkt-o*) (+ (fn-omk-at 2 *omkt-c*) (fn-omk-at 3 *omkt-c*)))
      (unsigned-byte-p 8 (fn-omk-at 3 *omkt-o*))
      (equal (car (fn-omk-tick *omkt-c* *omkt-o*)) :continue)))
(assert-event
 (let ((next (cadr (fn-omk-tick *omkt-c* *omkt-o*))))
   (and (equal (car (fn-omk-tick *omkt-c* *omkt-o*)) :continue)
        (equal (fn-omk-at 3 next) (+ 1 (fn-omk-at 3 *omkt-c*)))
        (equal (fn-omk-at 0 next) (fn-omk-at 0 *omkt-c*))
        (equal (fn-omk-at 1 next) (fn-omk-at 1 *omkt-c*))
        (equal (fn-omk-at 2 next) (fn-omk-at 2 *omkt-c*))
        (equal (fn-omk-at 4 next) (fn-omk-at 4 *omkt-c*))
        (equal (fn-omk-at 6 next) *omkt-token*) (equal (fn-omk-at 7 next) *omkt-lease*)
        (fn-omk-guardp *omkt-c*) (fn-omk-guardp next))))
; Full specified-message residual antecedent, including verified-byte meaning.
(assert-event
 (let ((next (cadr (fn-omk-tick *omkt-c* *omkt-o*))))
   (and (fn-omk-guardp *omkt-c*) (equal (fn-omk-at 0 *omkt-c*) :span)
        (stringp "<a@x>") (equal (length "<a@x>") (fn-omk-at 4 *omkt-c*))
        (< (fn-omk-at 3 *omkt-c*) (fn-omk-at 4 *omkt-c*))
        (fn-omk-widthp *omkt-o* 4) (equal (car *omkt-o*) :byte)
        (fn-omk-token-matchp (fn-omk-at 1 *omkt-o*) (fn-omk-at 6 *omkt-c*))
        (equal (fn-omk-at 2 *omkt-o*) (+ (fn-omk-at 2 *omkt-c*) (fn-omk-at 3 *omkt-c*)))
        (equal (fn-omk-at 3 *omkt-o*) (char-code (char "<a@x>" (fn-omk-at 3 *omkt-c*))))
        (equal (car (fn-omk-tick *omkt-c* *omkt-o*)) :continue)
        (equal (fn-hist-fnv "<a@x>" (fn-omk-at 3 next) (fn-omk-at 5 next))
               (fn-hist-fnv "<a@x>" (fn-omk-at 3 *omkt-c*) (fn-omk-at 5 *omkt-c*))))))
(defconst *omkt-resident* (list :resident '(1 0 0 "<a@x>" 7 nil 0 0 nil 0 0)))
(defconst *omkt-rc* (cadr (fn-omk-begin *omkt-resident* 0 *omkt-token* *omkt-lease*)))
(assert-event
 (let ((next (cadr (fn-omk-tick *omkt-rc* nil))))
   (and (fn-omk-guardp *omkt-rc*) (equal (fn-omk-at 0 *omkt-rc*) :string)
        (equal (car (fn-omk-tick *omkt-rc* nil)) :continue)
        (equal (fn-hist-fnv (fn-omk-at 1 *omkt-rc*) (fn-omk-at 3 next) (fn-omk-at 5 next))
               (fn-hist-fnv (fn-omk-at 1 *omkt-rc*) (fn-omk-at 3 *omkt-rc*) (fn-omk-at 5 *omkt-rc*))))))
(defun omkt-run-resident (fuel cursor)
  (if (zp fuel) (fn-omk-tick cursor nil)
    (let ((r (fn-omk-tick cursor nil)))
      (if (equal (car r) :continue) (omkt-run-resident (1- fuel) (cadr r)) r))))
(defun omkt-run-span (bytes cursor)
  (if (atom bytes) (fn-omk-tick cursor nil)
    (let ((r (fn-omk-tick cursor
                         (list :byte (fn-omk-at 6 cursor)
                               (+ (fn-omk-at 2 cursor) (fn-omk-at 3 cursor)) (car bytes)))))
      (if (equal (car r) :continue) (omkt-run-span (cdr bytes) (cadr r)) r))))
(assert-event
 (and (equal (car (omkt-run-resident 6 *omkt-rc*)) :done)
      (equal (cadr (omkt-run-resident 6 *omkt-rc*)) (fn-hp-mkey (cadr *omkt-resident*) 0))
      (equal (car (omkt-run-span '(60 97 64 120 62) *omkt-c*)) :done)
      (equal (cadr (omkt-run-span '(60 97 64 120 62) *omkt-c*)) (fn-hp-mkey (cadr *omkt-resident*) 0))))
; Literal stale pass retains guard/kind/range/opcode/offset/octet premises.
(assert-event
 (let ((o '(:byte (7 (8 3) 1 0) 10 60)))
   (and (fn-omk-guardp *omkt-c*) (equal (fn-omk-at 0 *omkt-c*) :span)
        (< (fn-omk-at 3 *omkt-c*) (fn-omk-at 4 *omkt-c*))
        (fn-omk-widthp o 4) (equal (car o) :byte)
        (not (fn-omk-token-matchp (fn-omk-at 1 o) *omkt-token*))
        (equal (fn-omk-at 2 o) (+ (fn-omk-at 2 *omkt-c*) (fn-omk-at 3 *omkt-c*)))
        (unsigned-byte-p 8 (fn-omk-at 3 o))
        (not (equal (car (fn-omk-tick *omkt-c* o)) :continue))
        (equal (fn-omk-tick *omkt-c* o) (list :refused :message-byte *omkt-c*)))))
; Correct token with stale byte position cannot advance or replace the borrow.
(assert-event
 (let ((o (list :byte *omkt-token* 11 60)))
   (and (fn-omk-guardp *omkt-c*) (equal (fn-omk-at 0 *omkt-c*) :span)
        (< (fn-omk-at 3 *omkt-c*) (fn-omk-at 4 *omkt-c*))
        (fn-omk-widthp o 4) (equal (car o) :byte)
        (fn-omk-token-matchp (fn-omk-at 1 o) *omkt-token*)
        (not (equal (fn-omk-at 2 o) (+ (fn-omk-at 2 *omkt-c*) (fn-omk-at 3 *omkt-c*))))
        (unsigned-byte-p 8 (fn-omk-at 3 o))
        (not (equal (car (fn-omk-tick *omkt-c* o)) :continue))
        (equal (fn-omk-tick *omkt-c* o) (list :refused :message-byte *omkt-c*)))))
; Mutation: authenticated source-byte correspondence is indispensable.
(assert-event
 (let* ((o (list :byte *omkt-token* 10 61)) (next (cadr (fn-omk-tick *omkt-c* o))))
   (and (fn-omk-guardp *omkt-c*) (equal (fn-omk-at 0 *omkt-c*) :span)
        (stringp "<a@x>") (equal (length "<a@x>") (fn-omk-at 4 *omkt-c*))
        (< (fn-omk-at 3 *omkt-c*) (fn-omk-at 4 *omkt-c*))
        (fn-omk-widthp o 4) (equal (car o) :byte)
        (fn-omk-token-matchp (fn-omk-at 1 o) *omkt-token*)
        (equal (fn-omk-at 2 o) (+ (fn-omk-at 2 *omkt-c*) (fn-omk-at 3 *omkt-c*)))
        (not (equal (fn-omk-at 3 o) (char-code (char "<a@x>" (fn-omk-at 3 *omkt-c*)))))
        (not (equal (fn-hist-fnv "<a@x>" (fn-omk-at 3 next) (fn-omk-at 5 next))
                    (fn-hist-fnv "<a@x>" (fn-omk-at 3 *omkt-c*) (fn-omk-at 5 *omkt-c*)))))))
