; Structural cursor order/restart witness, not actual typed Store capture.
(in-package "ACL2")
(include-book "../../books/snapshot-source-order-lineage")
(defconst *rccot-field* (fn-sl-of '(:first :second)))
(defconst *rccot-begin* (fn-osrc-begin *rccot-field* (fn-sfr-count *rccot-field*) 7 11))
(defconst *rccot-c1* (fn-osrc-at 1 (fn-osrc-tick *rccot-begin* nil)))
(defconst *rccot-c2* (fn-osrc-at 1 (fn-osrc-tick *rccot-c1* nil)))
(defconst *rccot-c3* (fn-osrc-at 1 (fn-osrc-tick *rccot-c2* nil)))
(defconst *rccot-c4* (fn-osrc-at 1 (fn-osrc-tick *rccot-c3* nil)))
(defconst *rccot-row1* (fn-osrc-tick *rccot-c4* nil))
(defconst *rccot-row2* (fn-osrc-tick (fn-osrc-at 4 *rccot-row1*) nil))
(defconst *rccot-drained* (fn-osrc-at 4 *rccot-row2*))
(defconst *rccot-restarted* (fn-osrc-at 1 (fn-osrc-restart *rccot-drained*)))
(defconst *rccot-again*
 (fn-osrc-tick (fn-osrc-at 1 (fn-osrc-tick *rccot-restarted* nil)) nil))
(thm
 (and (fn-sfr-canonp *rccot-field*)
      (fn-rccos-cursor-invariantp *rccot-c4*)
      (equal (car *rccot-row1*) :row)
      (equal (fn-osrc-at 0 (fn-osrc-at 2 *rccot-row1*)) :resident)
      (equal (fn-osrc-at 1 *rccot-row1*) (fn-osrc-at 2 *rccot-c4*))
      (equal (fn-osrc-at 1 (fn-osrc-at 2 *rccot-row1*))
             (nth (fn-osrc-at 2 *rccot-c4*) (fn-sfr-list *rccot-field*)))
      (fn-rcco-prepared-invariantp *rccot-begin*)
      (fn-rcco-prepared-invariantp *rccot-c4*)
      (fn-rcco-prepared-invariantp *rccot-drained*)
      (equal (car (fn-osrc-restart *rccot-drained*)) :restarted)
      (fn-rcco-prepared-invariantp *rccot-restarted*)
      (equal (fn-osrc-at 1 *rccot-restarted*) *rccot-field*)
      (equal (fn-osrc-at 2 *rccot-restarted*) 0)
      (equal (fn-osrc-at 9 *rccot-restarted*) 7)
      (equal (fn-osrc-at 10 *rccot-restarted*) 11)
      (equal (fn-osrc-at 12 *rccot-restarted*) 1)
      (equal (fn-osrc-at 2 *rccot-again*) '(:resident :first))
      (equal (fn-osrc-at 3 *rccot-again*) '(7 11 1 0)))
 :hints (("Goal" :in-theory (enable fn-rcco-prepared-invariantp fn-rccos-cursor-invariantp
                                  fn-rccos-base fn-rccos-suffix))))
; Corrupted prepared alias: scalar count/old cursor relation alone is insufficient.
(thm
 (let* ((bad (update-nth 11 '(:wrong) *rccot-drained*))
        (next (fn-osrc-at 1 (fn-osrc-restart bad))))
  (and (fn-rcco-prepared-invariantp *rccot-drained*)
       (fn-rccos-cursor-invariantp bad)
       (not (fn-rcco-prepared-invariantp bad))
       (equal (car (fn-osrc-restart bad)) :restarted)
       (not (fn-rccos-cursor-invariantp next))))
 :hints (("Goal" :in-theory (enable fn-rcco-prepared-invariantp fn-rccos-cursor-invariantp
                                  fn-rccos-base fn-rccos-suffix))))
