; Actual PROGRAM INITIAL refusal paths. The completed-open STATE fixture is
; a logical source witness, not an installed runtime or native allocation.
(in-package "ACL2")
(include-book "../../host/snapshot-initial-host")

(defun fn-sniht-probe (fn-page-read-pool state)
 (declare (xargs :stobjs (fn-page-read-pool state) :mode :program))
 (let* ((oldsource (fn-owner-recovery-global 'fn-owner-recovery-source state))
        (oldorigin (fn-owner-recovery-global 'fn-store-recovery-open-origin state))
        (oldepoch (fn-owner-recovery-global 'fn-owner-canonical-epoch state))
        (oldstore (fn-owner-recovery-global 'fn-store-sn state))
        (before (fn-owner-page-read-ledger fn-page-read-pool))
        (st (fn-sn-initial nil 1))
        (origin (list :completed-store-open 7 11 :empty-initialized st))
        (source '(:recovery-source 19 11 0)))
  (mv-let (word c) (fn-rsoa-begin 19 11 origin '(:ok 0 nil nil nil nil) 0 0)
   (let* ((state (f-put-global 'fn-owner-recovery-source c state))
          (state (f-put-global 'fn-store-recovery-open-origin origin state))
          (state (f-put-global 'fn-owner-canonical-epoch 11 state))
          (state (f-put-global 'fn-store-sn st state)))
    (mv-let (erp descriptor state) (fn-owner-recovery-startup-source source state)
     (let ((valid (and (not erp) (eq word :issued)
                       (fn-sni-sourcep source descriptor))))
      (mv-let (erp answer fn-page-read-pool state)
       (fn-owner-recovery-initial-admit source fn-page-read-pool state)
       (let ((runtime-refused
              (and valid (not erp)
                   (equal answer '(:unavailable :initial-runtime-family))
                   (equal before (fn-owner-page-read-ledger fn-page-read-pool)))))
        (mv-let (erp answer fn-page-read-pool state)
         (fn-owner-recovery-initial-admit '(:recovery-source 20 11 0)
                                          fn-page-read-pool state)
         (let* ((stale-refused
                  (and (not erp) (equal answer '(:unavailable :recovery-source))
                       (equal before (fn-owner-page-read-ledger fn-page-read-pool))))
                (state (f-put-global 'fn-owner-recovery-source oldsource state))
                (state (f-put-global 'fn-store-recovery-open-origin oldorigin state))
                (state (f-put-global 'fn-owner-canonical-epoch oldepoch state))
                (state (f-put-global 'fn-store-sn oldstore state)))
           (mv nil (list 'assert-event (and runtime-refused stale-refused))
               fn-page-read-pool state)))))))))))

(defun fn-sniht-run (state)
 (declare (xargs :stobjs state :mode :program))
 (with-local-stobj fn-page-read-pool
  (mv-let (erp form fn-page-read-pool state)
   (fn-sniht-probe fn-page-read-pool state)
   (mv erp form state))))
(make-event (fn-sniht-run state))
