; Actual emitted F/P/E/R frame fixture, not native recovery qualification.
(in-package "ACL2")
(include-book "../../books/store-checkpoint-size-reader-provenance-lift")
(defun sctl-frames (octets acc fuel fn-octets)
 (declare (xargs :stobjs fn-octets :mode :program))
 (if (or (zp fuel) (atom octets))
  (mv (if (consp octets) :torn (revappend acc nil)) fn-octets)
  (let* ((hn *fn-scc-segment-header-octets*) (tn *fn-frame-trailer-octets*)
         (header (take hn octets)) (h (fn-scc-parse-header header)))
   (if (or (not h) (< (len octets) (+ hn (nth 2 h) tn)))
    (mv :torn fn-octets)
    (let* ((chunk (take (nth 2 h) (nthcdr hn octets)))
           (trailer (take tn (nthcdr (+ hn (nth 2 h)) octets)))
           (rest (nthcdr (+ hn (nth 2 h) tn) octets))
           (a (fn-octets-len fn-octets))
           (fn-octets (fn-octets-append-list chunk fn-octets)))
     (sctl-frames rest (cons (list header a (+ a (len chunk)) trailer) acc)
                  (1- fuel) fn-octets))))))
(defun sctl-fixture (fn-octets)
 (declare (xargs :stobjs fn-octets :mode :program))
 (let* ((ctx '(:ok 0 nil nil nil nil))
        (consumer '(:ok ("history" "incarnation" 0 0 0 nil (:authority0 1 nil nil nil))
                       (:account-root :policy nil nil) 0))
        (tables (list (fn-sct-f-row 0 0 "outer" nil 0) nil nil
                      (list :distinct-configured-fold ctx consumer nil)))
        (progs (fn-sct-table-programs tables nil))
        (file (fn-scc-concat (fn-sct-file-segments progs 64 0)))
        (fn-octets (fn-octets-clear fn-octets)))
  (mv-let (plan fn-octets) (sctl-frames file nil (len file) fn-octets)
   (mv-let (result info region consumer-info) (fn-sctsr-load-all plan fn-octets)
    (mv-let (old old-info old-region) (fn-sctsr-load plan fn-octets)
     (mv (and (fn-octets-p fn-octets)
              (equal result (list :ok tables))
              (equal result old) (equal info old-info) (equal region old-region)
              (<= (fn-sco-at 1 (fn-sct-tables-f (cadr result))) (1+ *fn-cbor-max-uint*))
              (fn-scsr-info-provenancep info ctx)
              (fn-scsr-info-provenancep consumer-info consumer)
              (fn-scsr-info-provenancep (fn-scsr-info-field 1 consumer-info) (nth 1 consumer))
              (fn-scsr-info-provenancep (fn-scsr-info-field 2 consumer-info) (nth 2 consumer)))
         fn-octets))))))
(defun sctl-local ()
 (declare (xargs :mode :program))
 (with-local-stobj fn-octets
  (mv-let (ok fn-octets) (sctl-fixture fn-octets) ok)))
(assert-event (sctl-local))
