(in-package "ACL2")
(include-book "../../books/store-files-admission-carry")
(defconst *sfat-event* (fn-stxk-make 0 0 0 0 '(1) '(2)))
(defconst *sfat-s* (fn-sf-make :reserved 1 nil nil nil nil nil *fn-sf-recovery-barrier-count*))
(defconst *sfat-prefix* (fn-replay nil 10 nil))
(defconst *sfat-node* (fn-replay-result-node *sfat-prefix*))
(defconst *sfat-next* (fn-replay-apply-record *sfat-node* *sfat-event*))
(assert-event
 (and (fn-sf-statep *sfat-s*) (fn-store-event-p *sfat-event*)
      (equal *sfat-prefix* (fn-replay nil 10 (fn-sf-records *sfat-s*)))
      (fn-replay-okp *sfat-prefix*)
      (equal 0 (fn-sf-next-lower (fn-sf-records *sfat-s*) 0))
      (equal *sfat-node* (fn-replay-result-node *sfat-prefix*))
      (equal *sfat-next* (fn-replay-apply-record *sfat-node* *sfat-event*))
      (equal (fn-sf-phase (fn-sfa-prepare-from-produced *sfat-s* *sfat-event* 0 *sfat-node* *sfat-next*)) :record-staged)
      (equal (fn-sfa-prepare-from-produced *sfat-s* *sfat-event* 0 *sfat-node* *sfat-next*)
             (fn-sf-prepare-record *sfat-s* *sfat-event* nil 10))))
; Each removal checks all retained hypotheses and failure of complete output.
(defun sfat-removal (which)
 (let* ((groups (if (eq which :prefix-source) :bad nil))
        (prefix *sfat-prefix*)
        (lower (if (eq which :lower) 1 0))
        (node (if (eq which :prefix-node) (fn-replay-advance-txid *sfat-node* 9) *sfat-node*))
        (next (if (eq which :next-node) nil (fn-replay-apply-record node *sfat-event*)))
        (h1 (equal prefix (fn-replay groups 10 (fn-sf-records *sfat-s*))))
        (h2 (fn-replay-okp prefix))
        (h3 (equal lower (fn-sf-next-lower (fn-sf-records *sfat-s*) 0)))
        (h4 (equal node (fn-replay-result-node prefix)))
        (h5 (equal next (fn-replay-apply-record node *sfat-event*))))
  (and (if (eq which :prefix-source) (not h1) h1) h2
       (if (eq which :lower) (not h3) h3)
       (if (eq which :prefix-node) (not h4) h4)
       (if (eq which :next-node) (not h5) h5)
       (not (equal (fn-sfa-prepare-from-produced *sfat-s* *sfat-event* lower node next)
                   (fn-sf-prepare-record *sfat-s* *sfat-event* groups 10))))))
(assert-event (sfat-removal :prefix-source)) ; corrupted configured source
(assert-event (sfat-removal :lower))
(assert-event (sfat-removal :prefix-node))
(assert-event (sfat-removal :next-node))
; Corrupted semantic history: well-shaped held record names an absent group.
; It is not an arena/provenance or accepted native publication witness.
(defconst *sfat-bad-row*
 (fn-held-plain (fn-record-make 0 0 0 "<bad@example.invalid>" '(1) '("missing")
                  "o" "s" "e" 1 841000000) 0))
(assert-event
 (let* ((s (fn-sf-make :reserved 2 nil (list *sfat-bad-row*) nil nil nil *fn-sf-recovery-barrier-count*))
        (prefix (fn-replay nil 10 (fn-sf-records s)))
        (node (fn-replay-result-node prefix))
        (event (fn-stxk-make 1 1 1 0 '(1) '(2)))
        (next (fn-replay-apply-record node event)))
  (and (fn-held-p *sfat-bad-row*) (fn-sf-statep s)
       (equal prefix (fn-replay nil 10 (fn-sf-records s)))
       (not (fn-replay-okp prefix))
       (equal 1 (fn-sf-next-lower (fn-sf-records s) 0))
       (equal node (fn-replay-result-node prefix))
       (equal next (fn-replay-apply-record node event))
       (not (equal (fn-sfa-prepare-from-produced s event 1 node next)
                   (fn-sf-prepare-record s event nil 10))))))
