(in-package "ACL2")
(include-book "../../books/store-node-produced-identity")
(include-book "replay-produced-size-tests")
; Full constructor result, over the actual interned carried-record fixture.
(defun snpit-live (fn-arena)
 (declare (xargs :mode :program :stobjs fn-arena))
 (mv-let (row fn-arena) (fn-intern-event *ript-carried-event* nil 0 fn-arena)
  (let ((s (fn-sn-initial nil 10)))
   (mv-let (out checked fields status effect child sizes)
    (fn-snpi-finish-produced s (fn-sn-files s) row (fn-sn-node s)
                            *ript-ctx* (ript-fields *ript-ctx*) nil)
    (declare (ignore sizes))
    (mv (and (equal (fn-sn-identity-context s) (fn-ripc-without-prior-verdicts *ript-ctx*))
             (fn-hstxa-p row) (eq effect :verdict) (eq status :carried)
             (equal child *ript-carried-child*)
             (equal out (fn-sn-finish-identity s (fn-sn-files s) row (fn-sn-node s)))
             (equal checked (fn-replay-identity-step *ript-ctx* row))
             (fn-scs-correspondsp fields checked)
             (consp (fn-sn-verdicts out))) fn-arena)))))
(defun snpit-local ()
 (declare (xargs :mode :program))
 (with-local-stobj fn-arena (mv-let (ok fn-arena) (snpit-live fn-arena) ok)))
(make-event (value (list 'assert-event (snpit-local))))
; Removing the ORIGINALctx/core relation genuinely changes the full output.
(assert-event
 (let* ((s (fn-sn-initial nil 10))
        (original (fn-stxk-initial-context 7))
        (event (fn-stxk-make 7 8 1 0 '(1) '(7 8))))
  (mv-let (out checked fields status effect child sizes)
   (fn-snpi-finish-produced s (fn-sn-files s) event (fn-sn-node s)
                           original (ript-fields original) (fn-scs-summary event))
   (declare (ignore fields sizes))
   (and (not (equal (fn-sn-identity-context s) (fn-ripc-without-prior-verdicts original)))
        (fn-stxk-p event) (eq (fn-stxk-context-kind checked) :ok)
        (eq status :carried) (eq effect :snapshot) (equal child event)
        (not (equal out (fn-sn-finish-identity s (fn-sn-files s) event (fn-sn-node s))))))))
