; Actual ACL2 program/window subjects against the complete existing page plan.
; Execution witnesses, not guard/refinement or native resource proofs.
(in-package "ACL2")
(include-book "../../host/web-host")

(defun wwst-scan (xs scan width fn-web-in)
  (declare (xargs :mode :program :stobjs fn-web-in))
  (if (atom xs) (mv scan fn-web-in)
    (let* ((n (min (len xs) (max 1 (nfix width))))
           (fn-web-in (fn-octets-from-list (take n xs) fn-web-in))
           (next (fn-web-host-stream-scan scan fn-web-in)))
      (wwst-scan (nthcdr n xs) next width fn-web-in))))

(defun wwst-drain (fuel xs cursor base count emitp rev fn-web-in)
  (declare (xargs :mode :program :stobjs fn-web-in))
  (if (zp fuel) (mv (reverse rev) count nil fn-web-in)
    (mv-let (bytes next total done need)
      (fn-web-host-window-page-step cursor base count emitp fn-web-in)
      (let ((rev (revappend bytes rev)))
        (if done (mv (reverse rev) total t fn-web-in)
          (if need
              (let ((fn-web-in (fn-octets-from-list
                               (take (- (cdr need) (car need)) (nthcdr (car need) xs)) fn-web-in)))
                (wwst-drain (- fuel 1) xs next (car need) total emitp rev fn-web-in))
            (wwst-drain (- fuel 1) xs next base total emitp rev fn-web-in)))))))

(defun wwst-compare (config flow xs width)
  (declare (xargs :mode :program))
  (with-local-stobj fn-web-in
    (mv-let (r fn-web-in)
      (with-local-stobj fn-web-out
        (mv-let (r fn-web-in fn-web-out)
          (let* ((config (append (take 6 config) (list :page-plan)))
                 (fn-web-in (fn-octets-from-list xs fn-web-in)))
            (mv-let (reference table fn-web-out)
              (fn-web-step config nil flow '(:reply) fn-web-in fn-web-out)
              (declare (ignore table))
              (let* ((html (fn-wr-seq (nth 5 reference) xs))
                     (fn-web-in (fn-octets-clear fn-web-in)))
                (mv-let (scan fn-web-in)
                  (wwst-scan xs (fn-web-host-stream-start flow) width fn-web-in)
                  (let* ((action (fn-web-host-stream-page config flow scan))
                         (cursor (fn-wpc-cursor (nth 5 action)))
                         (fn-web-in (fn-octets-clear fn-web-in)))
                    (mv-let (ignored count counted fn-web-in)
                      (wwst-drain 100000 xs cursor 0 0 nil nil fn-web-in)
                      (declare (ignore ignored))
                      (let ((fn-web-in (fn-octets-clear fn-web-in)))
                        (mv-let (actual emitted drained fn-web-in)
                          (wwst-drain 100000 xs cursor 0 0 t nil fn-web-in)
                          (mv (list (equal (nth 1 reference) 200) (equal (nth 1 action) 200)
                                    counted drained (equal count (len html))
                                    (equal emitted count) (equal actual html))
                              fn-web-in fn-web-out)))))))))
          (mv r fn-web-in)))
      r)))

(defun wwst-octs (s) (declare (xargs :mode :program)) (fn-wrq-chars-octets (coerce s 'list)))
(defun wwst-lines (ss)
  (declare (xargs :mode :program))
  (if (consp ss) (append (wwst-octs (car ss)) '(13 10) (wwst-lines (cdr ss))) nil))
(defconst *wwst-config* (list :web-config (wwst-octs "fn") nil nil 600 16))
(defconst *wwst-session* (list nil nil (wwst-octs "wren") (wwst-octs "csrf")))
(defconst *wwst-ctx* (append (list (list :request :get)) (make-list 8) (list *wwst-session* :auto)))
(defconst *wwst-article* (list :article :article *wwst-ctx* (list (wwst-octs "fn.test"))))
(defconst *wwst-article-input*
  (append (wwst-lines '("211 1 1 1 fn.test" "220 1 <m@fn> article follows"
                       "Subject: =?UTF-8?Q?caf=C3=A9_&?=" "From: Wren <wren@fn>"
                       "Date: now" "Newsgroups: fn.test" "Message-ID: <m@fn>" "" "..one<&"))
          (make-list 5003 :initial-element 38) '(13 10 46 13 10)))
(assert-event (equal (wwst-compare *wwst-config* *wwst-article* *wwst-article-input* 7)
                     '(t t t t t t t)))
(assert-event (equal (wwst-compare *wwst-config* *wwst-article* *wwst-article-input* 4096)
                     '(t t t t t t t)))
(defconst *wwst-groups* (list :groups :list *wwst-ctx* nil))
(assert-event (equal (wwst-compare *wwst-config* *wwst-groups*
                     (wwst-lines '("215 list" "fn.a 17 1 y" "fn.b 0 0 n" ".")) 1)
                     '(t t t t t t t)))
(assert-event (equal (wwst-compare *wwst-config* *wwst-groups* (wwst-lines '("215 list" ".")) 2)
                     '(t t t t t t t)))
(defconst *wwst-over* (list :group :over *wwst-ctx* (list (wwst-octs "fn.test") 2 1)))
(assert-event (equal (wwst-compare *wwst-config* *wwst-over*
                     (wwst-lines '("224 overview" "2	First &	wren	date	<m@fn>		12	1" ".")) 7)
                     '(t t t t t t t)))
