(in-package "ACL2")
(include-book "web-private-begin-tests")
(include-book "../../books/web-post-stream")
(defun wpst-drain (fuel width cursor acc fn-web-in)
  (declare (xargs :mode :program :stobjs fn-web-in))
  (if (zp fuel) (mv nil nil)
    (mv-let (bytes next done) (fn-wps-window width cursor nil fn-web-in)
      (if (or (> (len bytes) width) (> (len (nth 5 next)) 5)) (mv nil nil)
        (let ((acc (revappend bytes acc)))
          (if done (mv (reverse acc) t)
            (wpst-drain (1- fuel) width next acc fn-web-in)))))))
(defun wpst-check (request width)
  (declare (xargs :mode :program))
  (with-local-stobj fn-web-in
    (mv-let (r fn-web-in)
      (with-local-stobj fn-web-out
        (mv-let (r fn-web-in fn-web-out)
          (let* ((fn-web-in (fn-octets-from-list request fn-web-in))
                 (event (wsst-begin request 300)))
            (mv-let (old table fn-web-out)
              (fn-web-step *cfg* *ss* nil event fn-web-in fn-web-out)
              (declare (ignore table))
              (let* ((bytes (fn-octets-list fn-web-out))
                     (fn-web-out (fn-octets-clear fn-web-out)))
                (mv-let (staged table fn-web-out)
                  (fn-web-step (append (take 6 *cfg*) (list :page-plan :private-begin))
                               *ss* nil event fn-web-in fn-web-out)
                  (declare (ignore table))
                  (mv-let (new fn-web-out)
                    (fn-wps-private-begin *cfg* staged fn-web-in fn-web-out)
                    (if (equal (car new) :post-command)
                        (mv-let (tail done) (wpst-drain 100000 width (nth 2 new) nil fn-web-in)
                          (let* ((flow (nth 3 new))
                                 (fn-web-in (fn-octets-from-list (wsst-octs "340 Send article~r~n") fn-web-in)))
                            (mv-let (after fn-web-out)
                              (fn-wps-private-reply *cfg* flow '(:reply) (nth 2 new) fn-web-in fn-web-out)
                              (mv (and done (equal (car old) :send)
                                       (equal (append (fn-octets-list fn-web-out) tail) bytes)
                                       (equal (nth 1 new) (nth 1 old))
                                       (equal flow (nth 4 old))
                                       (equal (car after) :post-stream)
                                       (equal (fn-wss-f-stage (nth 2 after)) :article))
                                  fn-web-in fn-web-out))))
                      (mv (equal new old) fn-web-in fn-web-out)))))))
          (mv r fn-web-in)))
      r)))
(assert-event (wpst-check *wpbt-post* 1))
(assert-event (wpst-check *wpbt-post* 2))
(assert-event (wpst-check *wpbt-post* 7))
(assert-event (wpst-check *wpbt-post* 4096))
(assert-event (wpst-check *wpbt-bad-csrf* 7))
(assert-event (wpst-check *wpbt-remove* 7))
