(in-package "ACL2")
(include-book "../../books/wildmat-live")

; Test-only traces; actual served code invokes one retained step.
(defun wmlt-find (s tag fuel)
 (declare (xargs :measure (nfix fuel) :verify-guards nil))
 (if (or (zp fuel) (eq (fn-wmc-at 0 (fn-wmc-at 0 s)) tag)) s
   (wmlt-find (fn-wmc-step s 1 (fn-wmc-demand s)) tag (1- fuel))))
(defun wmlt-peak (s fuel)
 (declare (xargs :measure (nfix fuel) :verify-guards nil))
 (if (zp fuel) (fn-wml-live-cells s)
   (max (fn-wml-live-cells s)
        (wmlt-peak (fn-wmc-step s 1 (fn-wmc-demand s)) (1- fuel)))))
(defun wmlt-frames (s fuel)
 (declare (xargs :measure (nfix fuel) :verify-guards nil))
 (if (zp fuel) (len (fn-wmc-at 1 s))
   (max (len (fn-wmc-at 1 s))
        (wmlt-frames (fn-wmc-step s 1 (fn-wmc-demand s)) (1- fuel)))))
(defconst *wmlt-patterns* '((:positive (42 97 98 42)) (:positive (42 99 99 99)) (:negative (42 100 100 100))))
(defconst *wmlt-start* (fn-wmc-start *wmlt-patterns* "abb"))
(defconst *wmlt-row* (wmlt-find *wmlt-start* :star-aux 1000))
(defthm wmlt-start-positive
 (and (fn-wildmat-pattern-listp *wmlt-patterns*)
      (equal (len *wmlt-patterns*) 3) (equal (fn-wm-total-items *wmlt-patterns*) 12)
      (equal (length "abb") 3) (equal (fn-wml-capacity 3 12 3) 158)
      (fn-wml-livep *wmlt-start*) (fn-wml-coveredp *wmlt-start* 3 12 3)
      (<= (fn-wml-room *wmlt-start*) 158)
      (<= (fn-wml-live-cells *wmlt-start*) (fn-wml-room *wmlt-start*))) :rule-classes nil)
(defthm wmlt-reachable-step-positive
 (let ((next (fn-wmc-step *wmlt-row* 1 (fn-wmc-demand *wmlt-row*))))
  (and (eq (fn-wmc-at 0 (fn-wmc-at 0 *wmlt-row*)) :star-aux)
       (fn-wmc-shapedp *wmlt-row*) (fn-wmc-core-shapedp *wmlt-row*)
       (not (eq (fn-wmc-at 0 (fn-wmc-at 0 *wmlt-row*)) :decode))
       (fn-wml-livep *wmlt-row*) (fn-wml-coveredp *wmlt-row* 3 12 3)
       (fn-wmc-acceptedp *wmlt-row* 1 (fn-wmc-demand *wmlt-row*))
       (<= (fn-wml-core-room (fn-wmc-core-one *wmlt-row*)) (fn-wml-core-room *wmlt-row*))
       (<= (fn-wml-room next) (fn-wml-room *wmlt-row*))
       (fn-wml-livep next) (fn-wml-coveredp next 3 12 3)
       (<= (fn-wml-live-cells next) 158)
       (equal (fn-wmc-result next) (fn-wmc-result *wmlt-row*)))) :rule-classes nil)
(defthm wmlt-overlap-positive
 (and (>= (wmlt-frames *wmlt-start* 1000) 9)
      (>= (wmlt-peak *wmlt-start* 1000) 61)
      (<= (wmlt-peak *wmlt-start* 1000) (fn-wml-capacity 3 12 3))) :rule-classes nil)
(defthm wmlt-utf8-positive
 (let* ((p '((:positive (233)))) (name (coerce (list (code-char 195) (code-char 169)) 'string))
        (s (fn-wmc-start p name)) (next (fn-wmc-step s 1 15)))
  (and (fn-wildmat-pattern-listp p) (fn-wmc-shapedp s)
       (eq (fn-wmc-at 0 (fn-wmc-at 0 s)) :utf8) (fn-wml-livep s)
       (fn-wml-coveredp s 1 1 2) (fn-wml-coveredp next 1 1 2)
       (<= (fn-wml-room next) (fn-wml-room s))
       (equal (fn-wml-utf8-budget (fn-wmc-at 0 next)) 1))) :rule-classes nil)
; Grammar-corrupted state: all shape/phase requirements retained, parsed omitted.
(defthm wmlt-parsed-profile-removal
 (let* ((p (list (make-list 40 :initial-element 0)))
        (s (fn-wmc-start p "")) (next (fn-wmc-one s))
        (non (fn-wmc-start p 17)))
  (and (not (fn-wildmat-pattern-listp p)) (fn-wmc-shapedp s)
       (not (eq (fn-wmc-at 0 (fn-wmc-at 0 s)) :decode))
       (eq (fn-wmc-at 0 (fn-wmc-at 0 s)) :utf8)
       (not (fn-wml-livep s))
       (not (<= (fn-wml-room next) (fn-wml-room s)))
       (not (<= (fn-wml-room non) (fn-wml-capacity (len p) (fn-wm-total-items p) 0))))) :rule-classes nil)
