;;; Build the export in a BARE SBCL (no ACL2): compile every file, load it.
(setq *compile-verbose* nil *compile-print* nil)
;; ACL2's own policy (acl2.lisp *acl2-optimize-form*)
(proclaim '(optimize (compilation-speed 0) (speed 3) (space 1) (safety 0)))
(defvar *dir* (sb-ext:posix-getenv "RF_OUT"))
(defvar *out* (sb-ext:posix-getenv "RF_FASL"))
(ensure-directories-exist *out*)
(defun f (name) (concatenate 'string *dir* name))
(defvar *undefined* nil)
(defun build (src)
  (let ((fasl (concatenate 'string *out* (pathname-name src) ".fasl")))
    (compile-file src :output-file fasl :external-format :latin-1)
    (load fasl)))
(load (f "00-packages.lisp"))
(with-compilation-unit ()
(build (f "shim.lisp"))
(build (f "01-globals.lisp"))
(build (f "01-stobjs-in.lisp"))
  (build (f "01-ftypes.lisp"))
  (build (f "01-inline.lisp"))
(dolist (p (sort (mapcar #'namestring (directory (f "02-defs-*.lisp"))) #'string<)) (build p))
(build (f "03-stobjs.lisp"))
(build (f "shim-post.lisp")))
(sb-ext:gc :full t)
(format t "~&RFB loaded; dynamic usage ~,1f MiB~%" (/ (sb-kernel:dynamic-usage) 1048576.0))
