;;; Save a bare-SBCL core holding the export (the "plain CL on SBCL" path).
(defvar *fasl* (sb-ext:posix-getenv "RF_FASL"))
(defvar *here* (sb-ext:posix-getenv "RF_HERE"))
(load (concatenate 'string *here* "out/00-packages.lisp"))
(dolist (f '("shim" "01-globals" "01-stobjs-in" "01-ftypes" "01-inline")) (load (concatenate 'string *fasl* f ".fasl")))
(dolist (p (sort (mapcar #'namestring (directory (concatenate 'string *fasl* "02-defs-*.fasl"))) #'string<)) (load p))
(dolist (f '("03-stobjs" "shim-post")) (load (concatenate 'string *fasl* f ".fasl")))
(load (compile-file (concatenate 'string *here* "serial.lisp") :output-file (concatenate 'string *fasl* "serial.fasl")))
(load (compile-file (concatenate 'string *here* "replay.lisp") :output-file (concatenate 'string *fasl* "replay.fasl")))
(load (compile-file (concatenate 'string *here* "host-port.lisp") :output-file (concatenate 'string *fasl* "host-port.fasl")))
(defvar *rf-stobjs-fasl* (concatenate 'string *fasl* "03-stobjs.fasl"))
(defvar *rf-globals-fasl* (concatenate 'string *fasl* "01-globals.fasl"))
(defun rf-main ()
  ;; The live stobjs are made at start: a saved core puts constant-folded
  ;; literals (the empty arrays of a fresh stobj) in read-only space.
  (load *rf-stobjs-fasl*)
  (let ((mode (sb-ext:posix-getenv "RF_MODE")) (tr (sb-ext:posix-getenv "RF_TRACE")))
    (format t "~&RS start rss-kib ~a dynamic ~,1f MiB~%" (acl2::rp-rss-kib) (/ (sb-kernel:dynamic-usage) 1048576.0))
    (finish-output)
    (when (equal mode "idle") (sleep 3)
      (format t "~&RS idle rss-kib ~a~%" (acl2::rp-rss-kib)))
    (when tr
      (acl2::rp-replay tr :report 3)
      (sb-ext:gc :full t)
      (format t "~&RS after-replay rss-kib ~a dynamic ~,1f MiB~%" (acl2::rp-rss-kib) (/ (sb-kernel:dynamic-usage) 1048576.0))
      (when (sb-ext:posix-getenv "RF_HOLD") (sleep (parse-integer (sb-ext:posix-getenv "RF_HOLD")))))
    (finish-output)
    (sb-ext:exit :code 0)))
(sb-ext:gc :full t)
(sb-ext:save-lisp-and-die (concatenate 'string *here* "plain-sbcl.core") :toplevel #'rf-main :executable nil)
