[store]
path = "/home/hbox/fn-deploy/native-47bdb9a4-4ba40cf/b/init/store"
[listener]
host = "127.0.0.1"
port = 11296
[control]
path = "/home/hbox/fn-deploy/native-47bdb9a4-4ba40cf/b/init/control.sock"
