;;; Spike for lane extract-forms (X1/X2): the raw def and the *1* def ACL2
;;; itself installs (interface-raw.lisp install-defs-for-add-trip), re-derived
;;; from the world's cltl-commands, fully macroexpanded by this image's SBCL.
;;; Run in the extraction world image (raw Lisp, after :q):
;;;   (load "forms-spike.lisp")  with SPIKE_OUT naming the output directory.
;;; Writes spike-defs.lisp, spike-packages.lisp, spike-report.txt.
(in-package "ACL2")
(require :sb-cltl2)
(defvar *sp-out* (sb-ext:posix-getenv "SPIKE_OUT"))
(defvar *sp-w* (w *the-live-state*))

;;; --- the world's definitions: fn -> (mode ignorep def), newest wins -------
(defvar *sp-defs* (make-hash-table :test 'eq))
(defvar *sp-stobj-cmds* nil)
(defvar *sp-consts* (make-hash-table :test 'eq))
(defvar *sp-attach* (make-hash-table :test 'eq))
(dolist (trip *sp-w*)
  (when (and (eq (car trip) 'cltl-command) (eq (cadr trip) 'global-value) (consp (cddr trip)))
    (let ((cmd (cddr trip)))
      (case (car cmd)
        (defuns
         (dolist (def (cdddr cmd))
           (unless (gethash (car def) *sp-defs*)
             (setf (gethash (car def) *sp-defs*) (list (cadr cmd) (caddr cmd) def)))))
        ((defstobj defabsstobj) (push cmd *sp-stobj-cmds*))
        (defconst (unless (gethash (cadr cmd) *sp-consts*) (setf (gethash (cadr cmd) *sp-consts*) cmd)))
        (attachment (dolist (x (cdr cmd))
                      (let ((n (if (symbolp x) x (car x))))
                        (unless (or (gethash n *sp-attach*) (eq n *special-cltl-cmd-attachment-mark-name*))
                          (setf (gethash n *sp-attach*) x)))))))))

;;; stobj-introduced defs (defstobj/defabsstobj): raw-defs are defun/defabbrev/
;;; defmacro, ax-defs are oneified with the stobj name as stobj-flag
(defvar *sp-stobj-fns* (make-hash-table :test 'eq))   ; fn -> (kind stobj def): raw-defs
(defvar *sp-stobj-ax* (make-hash-table :test 'eq))    ; fn -> (:ax stobj def): axiomatic-defs
(dolist (cmd *sp-stobj-cmds*)
  (let ((absp (eq (car cmd) 'defabsstobj)) (name (nth 1 cmd)))
    (dolist (d (nth 4 cmd))
      (setf (gethash (car d) *sp-stobj-fns*)
            (list (if absp :abs-raw-macro (if (member-equal *stobj-inline-declare* d) :raw-abbrev :raw-defun)) name d)))
    (dolist (d (nth 6 cmd))
      (setf (gethash (car d) *sp-stobj-ax*) (list :ax name d)))))

;;; --- canonical printing: uninterned symbols renamed by first occurrence ---
(defun sp-canon (x)
  (let ((map (make-hash-table :test 'eq)) (n 0))
    (labels ((go-x (x)
               (cond ((and (symbolp x) x (null (symbol-package x)))
                      (or (gethash x map) (setf (gethash x map) (make-symbol (format nil "G~d" (incf n))))))
                     ((consp x) (cons (go-x (car x)) (go-x (cdr x))))
                     (t x))))
      (go-x x))))

(defun sp-expand-def (def)
  "(NAME FORMALS . BODY) -> (NAME FORMALS . EXPANDED-BODY) via macroexpand-all of the lambda."
  (let ((e (sb-cltl2:macroexpand-all `(lambda ,(cadr def) ,@(cddr def)))))
    ;; e is (function (lambda ...)) or (lambda ...)
    (let ((lam (if (eq (car e) 'function) (cadr e) e)))
      (list* (car def) (cadr lam) (cddr lam)))))

;;; --- the free function names of an expanded form -------------------------
(defvar *sp-special-ok* '(quote function if progn let let* flet labels lambda block return-from setq the
                          tagbody go catch throw unwind-protect multiple-value-prog1 multiple-value-call
                          load-time-value locally eval-when progv declare))
(defun sp-calls (form acc locals)
  "ACC: hash of called symbols; LOCALS: flet/labels names in scope (ignored)."
  (labels ((walk (x locals)
             (cond ((atom x) nil)
                   (t (let ((op (car x)))
                        (case op
                          (quote nil)
                          (function (if (symbolp (cadr x)) (note (cadr x) locals) (walk (cadr x) locals)))
                          (lambda (walk-body (cddr x) locals))
                          ((let let*) (dolist (b (cadr x)) (when (consp b) (walk (cadr b) locals)))
                           (walk-body (cddr x) locals))
                          ((flet labels)
                           (let ((l2 (append (mapcar #'car (cadr x)) locals)))
                             (dolist (f (cadr x)) (walk-body (cddr f) (if (eq op 'flet) locals l2)))
                             (walk-body (cddr x) l2)))
                          ((block) (walk-body (cddr x) locals))
                          (return-from (walk (caddr x) locals))
                          (the (walk (caddr x) locals))
                          (tagbody (dolist (y (cdr x)) (when (consp y) (walk y locals))))
                          (go nil)
                          (declare nil)
                          (load-time-value (walk (cadr x) locals))
                          (eval-when (walk-body (cddr x) locals))
                          (progv (walk (cadr x) locals) (walk (caddr x) locals) (walk-body (cdddr x) locals))
                          (t (if (member op '(if progn setq catch throw unwind-protect multiple-value-prog1
                                              multiple-value-call locally))
                                 (dolist (y (cdr x)) (walk y locals))
                                 (progn (if (symbolp op) (note op locals) (walk op locals))
                                        (dolist (y (cdr x)) (walk y locals)))))))))) 
           (walk-body (b locals) (dolist (y b) (walk y locals)))
           (note (s locals) (unless (member s locals) (setf (gethash s acc) t))))
    (walk form locals)))

(defun sp-star1-name-p (s)
  (and (symbolp s) (symbol-package s)
       (let ((p (package-name (symbol-package s)))) (and (> (length p) 9) (equal (subseq p 0 9) "ACL2_*1*_")))))
(defun sp-unstar1 (s)
  (intern (symbol-name s) (subseq (package-name (symbol-package s)) 9)))

(defun sp-forms-for (f)
  "The expanded (raw . *1*) forms ACL2 installs for F; NIL when F has none in the world."
  (let ((e (gethash f *sp-defs*)) (s (gethash f *sp-stobj-fns*)) (ax (gethash f *sp-stobj-ax*)))
    (cond (e (destructuring-bind (mode ignorep def) e
               (list :defuns f
                     (cond ((not ignorep) (sp-expand-def def))
                           ((and s (member (car s) '(:raw-defun :raw-abbrev)))
                            (sp-expand-def (if (eq (car s) :raw-abbrev) (remove-stobj-inline-declare (caddr s)) (caddr s)))))
                     (sp-expand-def (oneify-cltl-code mode def (if (consp ignorep) (cdr ignorep) nil) *sp-w*)))))
          ((or s ax) (destructuring-bind (kind st def) (or s ax)
               (ecase kind
                 (:raw-defun (list :stobj-raw f (sp-expand-def def) nil))
                 (:raw-abbrev (list :stobj-abbrev f (sp-expand-def (remove-stobj-inline-declare def)) nil))
                 (:abs-raw-macro (list :abs-macro f nil nil))
                 (:ax (list :stobj-ax f nil (sp-expand-def (oneify-cltl-code :logic def st *sp-w*)))))))
          (t nil))))

;;; --- selection of the roots ----------------------------------------------
(defun sp-fn-p (f) (and (equal (symbol-package-name f) "ACL2") (> (length (symbol-name f)) 3)
                        (equal (subseq (symbol-name f) 0 3) "FN-")))
(defun sp-tree-has (sym x) (cond ((eq x sym) t) ((consp x) (or (sp-tree-has sym (car x)) (sp-tree-has sym (cdr x)))) (t nil)))
(defvar *sp-roots* nil)
(defvar *sp-report* nil)
(defun sp-pick (label n pred)
  (let ((got nil))
    (maphash (lambda (f e) (when (and (< (length got) n) (sp-fn-p f) (funcall pred f e)) (push f got))) *sp-defs*)
    (push (cons label got) *sp-report*)
    (setq *sp-roots* (append *sp-roots* (reverse got)))))
(sp-pick :mbe-guard-verified 3 (lambda (f e) (and (eq (symbol-class f *sp-w*) :common-lisp-compliant) (sp-tree-has 'mbe (caddr e)))))
(sp-pick :ideal 3 (lambda (f e) (declare (ignore e)) (eq (symbol-class f *sp-w*) :ideal)))
(sp-pick :program-invariant-risk 3 (lambda (f e) (and (eq (symbol-class f *sp-w*) :program) (getpropc f 'invariant-risk nil *sp-w*) e)))
(sp-pick :clc-invariant-risk 2 (lambda (f e) (declare (ignore e)) (and (eq (symbol-class f *sp-w*) :common-lisp-compliant) (getpropc f 'invariant-risk nil *sp-w*))))
(sp-pick :program-plain 2 (lambda (f e) (declare (ignore e)) (and (eq (symbol-class f *sp-w*) :program) (not (getpropc f 'invariant-risk nil *sp-w*)))))
(sp-pick :stobj-taking 2 (lambda (f e) (declare (ignore e)) (and (getpropc f 'stobj-function nil *sp-w*) (eq (symbol-class f *sp-w*) :common-lisp-compliant))))
;; stobj accessors/updaters and abs-stobj exports, fn's own
(let ((st nil) (abs nil))
  (dolist (cmd *sp-stobj-cmds*)
    (when (and (sp-fn-p (nth 1 cmd)) (not (equal (symbol-name (nth 1 cmd)) "STATE")))
      (if (eq (car cmd) 'defabsstobj) (push cmd abs) (push cmd st))))
  (push (list :stobj-names (mapcar (lambda (c) (nth 1 c)) st) :abs-names (mapcar (lambda (c) (nth 1 c)) abs)) *sp-report*)
  (let ((c (car (last st)))) (when c (setq *sp-roots* (append *sp-roots* (mapcar #'car (subseq (nth 4 c) 0 (min 3 (length (nth 4 c)))))
                                                                   (mapcar #'car (subseq (nth 6 c) 0 (min 2 (length (nth 6 c)))))))))
  (let ((c (car (last abs)))) (when c (setq *sp-roots* (append *sp-roots* (mapcar #'car (subseq (nth 4 c) 0 (min 3 (length (nth 4 c)))))
                                                                   (mapcar #'car (subseq (nth 6 c) 0 (min 3 (length (nth 6 c))))))))))
;; constrained with defattach: names from attachment cltl-commands that also have a defs entry
(let ((att nil))
  (dolist (trip *sp-w*)
    (when (and (eq (car trip) 'cltl-command) (eq (cadr trip) 'global-value) (consp (cddr trip)) (eq (caddr trip) 'attachment))
      (dolist (x (cdddr trip)) (let ((n (if (symbolp x) x (car x)))) (when (and (symbolp n) (gethash n *sp-defs*)) (pushnew n att))))))
  (let ((fnatt (remove-if-not #'sp-fn-p att)))
    (push (list :defattach-targets (length att) :fn-ones (subseq fnatt 0 (min 5 (length fnatt)))) *sp-report*)
    (setq *sp-roots* (append *sp-roots* (subseq fnatt 0 (min 3 (length fnatt)))
                             (if fnatt nil (subseq att 0 (min 2 (length att))))))))
(setq *sp-roots* (remove-duplicates *sp-roots*))

;;; --- the closure: expand roots, follow callees that have world defs --------
(defvar *sp-emitted* (make-hash-table :test 'eq))
(defvar *sp-runtime* (make-hash-table :test 'eq))   ; needed name -> :star1 / :raw
(defvar *sp-out-forms* nil)
(defvar *sp-limit* (parse-integer (or (sb-ext:posix-getenv "SPIKE_LIMIT") "3000")))
(defvar *sp-nroot* (length *sp-roots*))
(let ((work (copy-list *sp-roots*)) (nroot *sp-nroot*))
  (loop while (and work (< (hash-table-count *sp-emitted*) *sp-limit*))
        do (let ((f (pop work)))
             (unless (gethash f *sp-emitted*)
               (let ((r (sp-forms-for f)))
                 (cond ((null r) (setf (gethash f *sp-runtime*) :no-world-def))
                       (t (setf (gethash f *sp-emitted*) r)
                          (let ((x (gethash f *sp-attach*)))
                            (when (consp x) (let ((syms nil)) (labels ((c (y) (cond ((and y (symbolp y)) (push y syms)) ((consp y) (c (car y)) (c (cdr y)))))) (c (cdr x)))
                                              (dolist (y syms) (when (or (gethash y *sp-defs*) (gethash y *sp-stobj-fns*) (gethash y *sp-stobj-ax*)) (push y work))))))
                          (let ((acc (make-hash-table :test 'eq)))
                            (when (third r) (sp-calls (cons 'progn (cddr (third r))) acc nil))
                            (when (fourth r) (sp-calls (cons 'progn (cddr (fourth r))) acc nil))
                            (maphash (lambda (s v) (declare (ignore v))
                                       (let ((o (if (sp-star1-name-p s) (sp-unstar1 s) s)))
                                         (cond ((equal (symbol-package-name o) "COMMON-LISP")
                                                (when (sp-star1-name-p s) (setf (gethash s *sp-runtime*) :star1-of-cl)))
                                               ((and (symbol-package o) (let ((pn (package-name (symbol-package o)))) (and (> (length pn) 3) (equal (subseq pn 0 3) "SB-")))) nil)
                                               ((gethash o *sp-emitted*) nil)
                                               (t (push o work)))))
                                     acc))))))))
  (format t "~&SPIKE roots=~a emitted=~a pending-work=~a~%" nroot (hash-table-count *sp-emitted*) (length work)))

;;; --- print the forms and the packages --------------------------------------
(defvar *sp-dummy-pkg* (or (find-package "SPIKE-DUMMY") (make-package "SPIKE-DUMMY" :use nil)))
(defvar *sp-pkgs* (make-hash-table :test 'equal))
(defun sp-note-pkgs (x) (cond ((and (symbolp x) x (symbol-package x)) (setf (gethash (package-name (symbol-package x)) *sp-pkgs*) t))
                              ((consp x) (sp-note-pkgs (car x)) (sp-note-pkgs (cdr x)))))
(defun sp-print (x stream)
  (sp-note-pkgs x)
  (let ((*package* *sp-dummy-pkg*) (*print-circle* t) (*print-readably* t) (*print-pretty* nil)
        (*print-case* :upcase) (*print-length* nil) (*print-level* nil) (*read-default-float-format* 'single-float))
    (prin1 (sp-canon x) stream) (terpri stream)))
(defvar pkgs nil)
(let ((fns (sort (loop for k being the hash-keys of *sp-emitted* collect k)
                 (lambda (a b) (string< (format nil "~a::~a" (symbol-package-name a) (symbol-name a))
                                        (format nil "~a::~a" (symbol-package-name b) (symbol-name b))))))
      (nfail 0))
  (with-open-file (o (concatenate 'string *sp-out* "spike-defs.lisp") :direction :output :if-exists :supersede :external-format :latin-1)
    (sp-print '(declaim (declaration acl2::xargs acl2::irrelevant)) o)
    ;; the defconsts any emitted form names (ifat-defparameter's form)
    (let ((seen (make-hash-table :test 'eq)) (cs nil))
      (labels ((c (y) (cond ((and y (symbolp y)) (when (and (gethash y *sp-consts*) (not (equal (symbol-package-name y) "COMMON-LISP")) (not (gethash y seen))) (setf (gethash y seen) t) (push y cs)))
                            ((consp y) (c (car y)) (c (cdr y))))))
        (dolist (f fns) (let ((r (gethash f *sp-emitted*))) (c (third r)) (c (fourth r)))))
      (setq cs (sort cs #'string< :key #'symbol-name))
      (dolist (n cs) (let ((cmd (gethash n *sp-consts*))) (let ((form (ifat-defparameter (cadr cmd) (cadddr cmd) (caddr cmd)))) (sp-print (list (car form) (cadr form) (sb-cltl2:macroexpand-all (caddr form))) o))))
      (format t "~&SPIKE defconsts ~a~%" (length cs)))
    ;; attachments of emitted functions (set-attachment-symbol-form)
    (let ((na 0))
      (dolist (f fns)
        (let ((x (gethash f *sp-attach*)))
          (when x (incf na) (sp-print (if (symbolp x) (set-attachment-symbol-form x nil) (set-attachment-symbol-form (car x) (cdr x))) o))))
      (format t "~&SPIKE attachments ~a~%" na))
    (dolist (f fns)
      (let ((r (gethash f *sp-emitted*)))
        (when (and (third r) (inline-namep (symbol-name f))) (sp-print `(declaim (inline ,f)) o))
        (when (and (third r) (notinline-namep (symbol-name f))) (sp-print `(declaim (notinline ,f)) o))
        (dolist (form (list (third r) (fourth r)))
          (when form
            (handler-case
                (sp-print (list* 'defun form) o)
              (error (e) (incf nfail) (format t "~&PRINT FAIL ~s: ~a~%" f (substitute #\Space #\Newline (princ-to-string e)))))))))
    (let ((sts nil))
      (dolist (f fns) (let ((sr (gethash f *sp-stobj-fns*))) (when sr (pushnew (cadr sr) sts))))
      (dolist (cmd *sp-stobj-cmds*)
        (when (member (nth 1 cmd) sts)
          (sp-print `(defparameter ,(nth 2 cmd) ,(nth 3 cmd)) o)))
      (format t "~&SPIKE stobj inits ~a~%" (length sts))))
  (format t "~&SPIKE printed ~a fns, print failures ~a~%" (length fns) nfail)
  ;; packages: every package any printed symbol lives in
  (setq pkgs *sp-pkgs*)
  (let ((known (known-package-alist *the-live-state*)))
    (with-open-file (o (concatenate 'string *sp-out* "spike-packages.lisp") :direction :output :if-exists :supersede :external-format :latin-1)
      (let ((names (sort (loop for k being the hash-keys of pkgs unless (member k '("COMMON-LISP" "KEYWORD") :test #'equal) collect k) #'string<)))
        (dolist (p names) (format o "(unless (find-package ~s) (make-package ~s :use nil))~%" p p))
        (dolist (p names)
          (let ((e (find p known :key (lambda (e) (package-entry-name e)) :test #'equal)))
            (when e (dolist (s (package-entry-imports e))
                      (format o "(import (list (intern ~s ~s)) ~s)~%" (symbol-name s) (symbol-package-name s) p))))))))
  )
;;; --- report ---------------------------------------------------------------
(with-open-file (o (concatenate 'string *sp-out* "spike-report.txt") :direction :output :if-exists :supersede)
  (format o "ROOTS ~s~%" *sp-roots*)
  (dolist (r (reverse *sp-report*)) (format o "PICK ~s~%" r))
  (format o "EMITTED ~a~%" (hash-table-count *sp-emitted*))
  (let ((kinds (make-hash-table)))
    (maphash (lambda (k r) (declare (ignore k)) (incf (gethash (car r) kinds 0))) *sp-emitted*)
    (maphash (lambda (k v) (format o "KIND ~s ~a~%" k v)) kinds))
  (maphash (lambda (s why) (format o "RUNTIME ~a::~a ~s~%" (symbol-package-name s) (symbol-name s) why)) *sp-runtime*))
(format t "~&SPIKE done; runtime names ~a~%" (hash-table-count *sp-runtime*))
