; Recording decoder/SSR/STATE doubles: exercises only native forwarding.
(defvar *decode-calls* 0)
(defvar *worker-calls* 0)
(defvar *observed* nil)
(defvar *last-wires* nil)
(defvar *last-carries* nil)
(defvar *serial* 0)
(defvar *raise-decode* nil)
(defun fnn-fault (format &rest args) (error (apply #'format nil format args)))
(defun fnn-octet-list (x) (coerce x 'list))
(defun fnn-live-arena () :recording-arena)
(defun fnn-core (name &rest args)
 (case name
  (fn-srs-chunk-fullp (>= (first args) 2))
  (fn-store-sn-recover-records :ok)
  (fn-ofw-wire-next (+ (length (first args)) (second args)))
  (fn-ssr-at (nth (first args) (second args)))
  (fn-ssr-rows (second (first args)))
  (otherwise (error "unexpected core call ~s" name))))
(defun fnn-core-state (name &rest args)
 (case name
  (fn-store-statement-replay-seed-sized (list (list :ssr nil nil :ctx) :seed-fields :carried))
  ((fn-owner-recovery-source-observe-seed-sized fn-owner-recovery-source-observe-sized)
   (assert (equal (first args) (list :token *serial*)))
   (push (cons name args) *observed*)
   (list :counted (list :token (incf *serial*))))
  (otherwise (error "unexpected state call ~s" name))))
(defun fnn-call (name &rest args)
 (case name
  (fn-srss-decode
   (incf *decode-calls*)
   (when *raise-decode* (error "recording decoder failure"))
   (let ((records (first args)))
    (if (member '(255) records :test #'equal) (list :bad nil)
     (progn
      (setf *last-wires* (mapcar (lambda (r) (list :wire (car r))) records)
            *last-carries* (mapcar (lambda (r) (and (= (car r) 10) (list :snapshot-carry (car r)))) records))
      (list *last-wires* *last-carries*)))))
  (fn-ssrs-intern-step
   (incf *worker-calls*)
   (assert (eq (third args) *last-wires*))
   (assert (eq (eighth args) *last-carries*))
   (let ((rows (append (second (first args)) (third args))))
    (list (list :ssr rows nil :ctx) :next-fields :carried :recording-arena)))
  (otherwise (error "unexpected multi-value core call ~s" name))))
(defun reset-recording ()
 (setf *decode-calls* 0 *worker-calls* 0 *serial* 0 *observed* nil *raise-decode* nil))
(defun check-native-forwarding ()
 (reset-recording)
 (multiple-value-bind (rows fold ctx token fields status)
  (fnn-recover-suffix-intern (list #(10) #(20) #(30)) nil 0 '(:token 0))
  (assert (equal rows '((:wire 10) (:wire 20) (:wire 30))))
  (assert (= fold 3)) (assert (eq ctx :ctx))
  (assert (equal token '(:token 3))) (assert (eq fields :next-fields))
  (assert (eq status :carried))
  (assert (= *decode-calls* 2)) (assert (= *worker-calls* 2)))
 (reset-recording)
 (multiple-value-bind (rows fold ctx token fields status)
  (fnn-recover-suffix-intern nil nil 0 '(:token 0))
  (assert (null rows)) (assert (= fold 0)) (assert (eq ctx :ctx))
  (assert (equal token '(:token 1))) (assert (eq fields :seed-fields))
  (assert (eq status :carried))
  (assert (= *decode-calls* 0)) (assert (= *worker-calls* 0)))
 (reset-recording)
 (multiple-value-bind (rows fold ctx token fields status)
  (fnn-recover-suffix-intern (list #(10) #(20) #(255) #(40) #(50)) nil 0 '(:token 0))
  (assert (eq rows :bad)) (assert (= fold 0)) (assert (null ctx))
  (assert (equal token '(:token 2))) (assert (null fields))
  (assert (eq status :unavailable))
  (assert (= *decode-calls* 2)) (assert (= *worker-calls* 1)))
 (reset-recording)
 (multiple-value-bind (rows fold ctx token fields status)
  (fnn-recover-suffix-intern (list #(20)) nil 0 nil)
  (assert (equal rows '((:wire 20)))) (assert (= fold 1))
  (assert (eq ctx :ctx)) (assert (null token)) (assert (eq fields :next-fields))
  (assert (eq status :carried)) (assert (equal *last-carries* (list nil))))
 (reset-recording)
 (setf *raise-decode* t)
 (assert (handler-case (progn (fnn-recover-suffix-intern (list #(10)) nil 0 '(:token 0)) nil)
           (error () t)))
 (assert (= *decode-calls* 1)) (assert (= *worker-calls* 0))
 (assert (= *serial* 1))
 (format t "Five native same-pass forwarding cases PASS; decoder/SSR/STATE are recording doubles.~%"))
