;;; Supporting native differential fixture, not allocation authority.
(in-package "ACL2")
(let* ((controller (funcall (fnn-fixed-raw-callback 'create-fn-input-copy)))
       (pool (funcall (fnn-fixed-raw-callback 'create-fn-page-read-pool)))
       (*fnn-octets* (fn-octets$c-reserve 64 (create-fn-octets$c)))
       (destination (svref *fnn-octets* 0))
       (old-fill (svref *fnn-octets* 1))
       (source (make-array 20 :element-type '(unsigned-byte 8) :initial-element 7)))
 (fn-owner-page-read-install '(8192 0 0 0 8) 0 0 0 8 pool)
 (iohp-install-backing pool)
 (multiple-value-bind (word token pool1)
  (fn-owner-incoming-reserve '(256 0 0 0 1) pool)
  (assert (and (eq word :admitted) (eq pool pool1)))
  (multiple-value-bind (word controller1 pool2)
   (fnn-core-mv 'fn-owner-incoming-copy-start
    (funcall (fnn-fixed-raw-callback 'fn-owner-incoming-copy-start)
             token 20 nil controller pool))
   (assert (and (eq word :setup-started) (eq controller controller1) (eq pool pool2))))
  (let* ((ledger (fn-owner-page-read-ledger pool))
         (job (%make-fnn-owner-admission-job :input-token token :source-vector source)))
   (multiple-value-bind (word controller1 pool2)
    (fnn-owner-incoming-copy-step job
     (fnn-fixed-raw-callback 'fn-owner-incoming-copy-next)
     (fnn-fixed-raw-callback 'fn-owner-incoming-copy-ack) controller pool)
    (assert (and (eq word :copy-recorded) (eq controller controller1) (eq pool pool2)
                 (eq ledger (fn-owner-page-read-ledger pool))
                 (equal token (fn-input-copy-token controller))
                 (= (fn-icc-offset controller) 20)
                 (eq destination (svref *fnn-octets* 0))
                 (= (svref *fnn-octets* 1) old-fill)
                 (= (length destination) 64)
                 (loop for i below 20 always (= (aref destination i) (aref source i)))
                 (loop for i from 20 below 64 always (zerop (aref destination i)))
                 (loop for byte across source always (= byte 7)))))
   (multiple-value-bind (word controller1 pool2)
    (fnn-owner-incoming-copy-step job
     (fnn-fixed-raw-callback 'fn-owner-incoming-copy-next)
     (fnn-fixed-raw-callback 'fn-owner-incoming-copy-ack) controller pool)
    (assert (and (eq word :complete) (eq controller controller1) (eq pool pool2)
                 (eq ledger (fn-owner-page-read-ledger pool)))))
   (format t "~&PASS ACTUAL FIXED COPY: compiled selected creators/start/next/ack; core token/ledger; exact bytes/unchanged-fill/outside/source/identities; terminal complete~%"))))

; Fault injection after the actual selected NEXT has mutated its controller.
; This tests the native wrapper, not the composed service recovery fence.
(defvar *fnn-srt-trap-reports* 0)
(define-condition fnn-srt-report-trap (error) ()
 (:report (lambda (condition stream)
            (declare (ignore condition stream))
            (incf *fnn-srt-trap-reports*)
            (error "unexpected condition rendering"))))
(let* ((controller (funcall (fnn-fixed-raw-callback 'create-fn-input-copy)))
       (pool (funcall (fnn-fixed-raw-callback 'create-fn-page-read-pool)))
       (*fnn-octets* (fn-octets$c-reserve 64 (create-fn-octets$c)))
       (cause (make-condition 'fnn-srt-report-trap))
       (*fnn-srt-trap-reports* 0))
 (fn-owner-page-read-install '(8192 0 0 0 8) 0 0 0 8 pool)
 (iohp-install-backing pool)
 (multiple-value-bind (word token pool1)
  (fn-owner-incoming-reserve '(256 0 0 0 1) pool)
  (assert (and (eq word :admitted) (eq pool pool1)))
  (funcall (fnn-fixed-raw-callback 'fn-owner-incoming-copy-start) token 20 nil controller pool)
  (let* ((ledger (fn-owner-page-read-ledger pool))
         (next (fnn-fixed-raw-callback 'fn-owner-incoming-copy-next))
         (job (%make-fnn-owner-admission-job :input-token token
               :source-vector (make-array 20 :element-type '(unsigned-byte 8) :initial-element 7)))
         (fault
          (handler-case
           (fnn-owner-incoming-copy-step job
            (lambda (tok ctrl state)
             (multiple-value-prog1 (funcall next tok ctrl state) (error cause)))
            (fnn-fixed-raw-callback 'fn-owner-incoming-copy-ack) controller pool)
           (fnn-fixed-callback-fault (condition) condition))))
   (assert (and (typep fault 'fnn-fixed-callback-fault)
                (eq (fnn-fixed-fault-cause fault) cause)
                (eq (fnn-fixed-fault-tag fault) :raw-callback-failed)
                (eq (fnn-fixed-fault-subject fault) 'fn-owner-incoming-copy-next)
                (zerop *fnn-srt-trap-reports*)
                (fn-icc-pending controller) (zerop (fn-icc-offset controller))
                (eq ledger (fn-owner-page-read-ledger pool))
                (equal token (fn-input-copy-token controller))))
   (format t "~&PASS INJECTED POST-NEXT FAULT: actual mutation held, same cause retained, reports0; composed quarantine remains open~%"))))
