;;; Actual literal worker creators, measurement-only, 1024 calls each.
(in-package "ACL2")
(defvar *fnn-worker-observed*)
(defun fnn-worker-observe (name thunk)
 (dotimes (i 64) (setf *fnn-worker-observed* (funcall thunk)))
 (sb-ext:gc :full t)
 (let ((before (sb-ext:get-bytes-consed)))
  (dotimes (i 1024) (setf *fnn-worker-observed* (funcall thunk)))
  (format t "~&WORKER-CONSTRUCTOR ~s calls=1024 allocated=~d~%"
   name (- (sb-ext:get-bytes-consed) before))))
(dolist (name '(create-pgs-digest-state create-fn-ew-buffer create-fn-octets$c fn-octets$c-reserve))
 (unless (compiled-function-p (symbol-function name))
  (error "Worker constructor is not compiled")))
(let ((pgs (create-pgs-digest-state)) (ew (create-fn-ew-buffer))
      (oct (fn-octets$c-reserve 64 (create-fn-octets$c))))
 (assert (and (typep pgs 'simple-vector) (= (length pgs) 16)
              (typep (svref pgs 15) 'simple-vector) (= (length (svref pgs 15)) 64)))
 (assert (and (typep ew '(simple-array (unsigned-byte 8) (*)))
              (= (length ew) 16384)))
 (assert (and (typep oct 'simple-vector) (= (length oct) 2)
              (= (length (svref oct 0)) 64) (= (svref oct 1) 0)))
 (format t "~&WORKER-LAYOUT digest=16+64T extent=direct16384UB8 octets=2+64UB8~%"))
(fnn-worker-observe :digest (lambda () (create-pgs-digest-state)))
(fnn-worker-observe :extent (lambda () (create-fn-ew-buffer)))
(fnn-worker-observe :octets-reserve64
 (lambda () (fn-octets$c-reserve 64 (create-fn-octets$c))))
(with-open-file (stream "/home/ember/fn-gates/runtime-selected-attached-077b/build/runtime-constructor/worker-disassembly.txt"
 :direction :output :if-exists :supersede)
 (let ((*standard-output* stream))
  (dolist (name '(create-pgs-digest-state create-fn-ew-buffer create-fn-octets$c fn-octets$c-reserve resize-fn-octets$c-buf))
   (format t "~&WORKER-FUNCTION ~s~%" name)
   (disassemble (symbol-function name)))
  (format t "~&WORKER-FUNCTION OCTETS-RESERVE64-CALLER~%")
  (disassemble (compile nil '(lambda () (fn-octets$c-reserve 64 (create-fn-octets$c)))))))
