"""Hybrid-signed carriers for the native measurements (throughput gate,
service envelope).

One author: the fixed principal and Ed25519 pair of measure_signed.py
(planning/evidence/signed-history-index-2026-09-26/) and an ML-DSA-65 pair
generated by the OpenSSL 3.5 prefix.  Carriers are signed by the image's own
`hybrid-sign-carrier` (a separate process per carrier, before or beside the
owner) and the author is enrolled through the running owner's control socket
(`hybrid-enroll`), as measure_signed.py does.  Nothing here signs or checks
anything itself: Python only starts the image and carries octets.
"""
from pathlib import Path
import subprocess
import time

ED_PUBLIC = "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a"
ED_SECRET = "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60" + ED_PUBLIC
LINE = b"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdef"[:78] + b"\r\n"


def source(msgid, octets, subject="signed"):
    """An authored source of about OCTETS octets: the fixed header, then
    78-character body lines (none starts with a dot)."""
    head = ("From: agent@example.invalid\r\nDate: Wed, 23 Sep 2026 12:00:00 +0000\r\n"
            "Newsgroups: fn.test\r\nSubject: %s\r\nMessage-ID: %s\r\n\r\n" % (subject, msgid)).encode("ascii")
    need = max(0, octets - len(head))
    body = LINE * max(1, need // len(LINE))
    return head + body


def dot_stuff(octets):
    return b"".join((b"." + line if line.startswith(b".") else line)
                    for line in octets.splitlines(keepends=True))


class HybridAuthor:
    def __init__(self, image, env, work, openssl_bin):
        self.image, self.env, self.work = str(image), env, Path(work)
        self.work.mkdir(parents=True, exist_ok=True)
        self.principal = self.work / "principal.bin"
        self.principal.write_bytes(bytes([0x55]) * 32)
        self.edp, self.eds = self.work / "ed-public.bin", self.work / "ed-secret.bin"
        self.edp.write_bytes(bytes.fromhex(ED_PUBLIC))
        self.eds.write_bytes(bytes.fromhex(ED_SECRET))
        self.mlpriv, self.mlpub = self.work / "ml-private.pem", self.work / "ml-public.pem"
        self.sign_seconds = []
        if openssl_bin is None:
            if not (self.mlpriv.is_file() and self.mlpub.is_file()):
                raise SystemExit("no ML-DSA pair under %s" % self.work)
            return
        subprocess.run([openssl_bin, "genpkey", "-algorithm", "ML-DSA-65", "-out", str(self.mlpriv)],
                       check=True, env=env, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
        subprocess.run([openssl_bin, "pkey", "-in", str(self.mlpriv), "-pubout", "-out", str(self.mlpub)],
                       check=True, env=env, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)

    @classmethod
    def existing(cls, image, env, work):
        """The author whose keys WORK already holds (a resumed load)."""
        return cls(image, env, work, None)

    def fn(self, *args, timeout=600):
        r = subprocess.run([self.image, "--fn"] + [str(x) for x in args], env=self.env,
                           stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout)
        if r.returncode != 0:
            raise SystemExit("%s -> %d: %r" % (args[:1], r.returncode, r.stderr[-800:]))
        return r

    def sign(self, stem, octets):
        """The carried octets of a source of about OCTETS octets, Message-ID
        <STEM@example.invalid>."""
        src, out = self.work / (stem + ".eml"), self.work / (stem + "-carried.eml")
        src.write_bytes(source("<%s@example.invalid>" % stem, octets))
        t0 = time.perf_counter()
        self.fn("hybrid-sign-carrier", self.principal, self.edp, self.eds, self.mlpub, self.mlpriv, src, out)
        self.sign_seconds.append(time.perf_counter() - t0)
        carried = out.read_bytes()
        src.unlink()
        out.unlink()
        return carried

    def enroll(self, control):
        return self.fn("hybrid-enroll", control, "1", self.principal, self.edp, self.mlpub)


def post_octets(conn, octets):
    """POST ready octets on an open msgid_measure.Conn: the seconds from the
    command to the reply line, and the seconds from the terminating line to
    the reply line (the owner's whole commit, prepare to durable reply)."""
    t0 = time.perf_counter()
    r = conn.line("POST")
    if not r.startswith(b"340"):
        raise SystemExit("POST: %r" % r)
    conn.stream.write(dot_stuff(octets))
    t1 = time.perf_counter()
    conn.stream.write(b".\r\n")
    r = conn.readline()
    t2 = time.perf_counter()
    if not r.startswith(b"240"):
        raise SystemExit("POST body: %r" % r)
    return t2 - t0, t2 - t1
