[store]
path = "/home/hbox/fn-deploy/native-47bdb9a4-4ba40cf/a/profile/store"
[listener]
host = "127.0.0.1"
port = 11297
[log]
path = "/home/hbox/fn-deploy/native-47bdb9a4-4ba40cf/a/profile/service.log"
[control]
path = "/home/hbox/fn-deploy/native-47bdb9a4-4ba40cf/a/profile/control.sock"
