[store]
path = "/home/hbox/fn-deploy/native-6c0626c5-c60bb37/b/init/store"
[listener]
host = "127.0.0.1"
port = 11296
[control]
path = "/home/hbox/fn-deploy/native-6c0626c5-c60bb37/b/init/control.sock"
