#!/bin/sh
cd /tank/fn/scratch/qual-bbf52159
sh run.sh test_native_auth test_native_profile test_native_admin test_native_starttls test_native_auth_admin_fidelity test_native_owner test_native_raw_scripts test_native_live_reconfiguration test_native_control test_native_operator_cli test_native_operator_verbs test_native_profile_upgrade test_native_program_check test_native_initializer_fidelity test_native_recovery test_native_storage_codec test_native_served_differential test_native_reader_index test_native_newnews_migration test_native_stamp_migration test_native_history_marker
touch /tank/fn/scratch/qual-bbf52159/done.B
