;; Each attempted close/unlock failure retains recovery aliases. The remaining
;; descriptor fields describe what is known; they do not prove an unlocked
;; lock remains held or authorize automatic reuse/retry after uncertainty.
(dolist (failure '(503 501 502 :unlock))
 (let* ((identity (list :original-context))
        (source (list :issued-recovery-token))
        (spare (list 1 "/recording-stage" 503))
        (log (make-fnn-log :fd 501 :spare spare))
        (store (make-fnn-store :log log :lock-fd 502
                  :completion-pending :owed :recovery-identity identity
                  :recovery-source source))
        (*failure* failure) (*calls* nil))
  (assert (handler-case (progn (fnn-store-close store) nil) (error () t)))
  (assert (eq (fnn-store-recovery-identity store) identity))
  (assert (eq (fnn-store-recovery-source store) source))
  (assert (= (fnn-store-lock-fd store) 502))
  (if (member failure '(503 501))
      (assert (eq (fnn-store-log store) log))
    (assert (null (fnn-store-log store))))
  (if (eql failure 503)
      (progn (assert (eq (fnn-log-spare log) spare))
             (assert (equal *calls* '((:close 503)))))
    (progn (assert (null (fnn-log-spare log)))
           (assert (= (count '(:close 503) *calls* :test #'equal) 1))
           (assert (= (count '(:close 501) *calls* :test #'equal) 1))))
  (when (member failure '(502 :unlock))
   (assert (= (count '(:close 502) *calls* :test #'equal) 1))
   (assert (= (count '(:flock 502 8) *calls* :test #'equal) 1)))
  (format t "PASS close failure ~s retains recovery authority~%" failure)))
(let* ((log (make-fnn-log :fd 501 :spare (list 1 "/recording-stage" 503)))
       (store (make-fnn-store :log log :lock-fd 502
                 :recovery-identity :identity :recovery-source :source))
       (*failure* nil) (*calls* nil))
 (fnn-store-close store)
 (assert (null (fnn-store-log store)))
 (assert (null (fnn-store-lock-fd store)))
 (assert (null (fnn-store-recovery-identity store)))
 (assert (null (fnn-store-recovery-source store)))
 (assert (equal (reverse *calls*) '((:close 503) (:unlink "/recording-stage")
                                   (:close 501) (:flock 502 8) (:close 502))))
 (format t "PASS definite closes clear aliases after observed return~%"))
